### ISSUE TITLE
Stuck on FeatureExtraction // Popsift - CUDA - GPU EXTRACTION

### ISSUE THREAD

**Issue by fisietto23** [alicevision/meshroom#1000]
Hey there I just downloaded Meshroom and trying to do my first work. Since when I tried CPU features extraction my laptop was too slow I changed to GPU extraction but I always get this error message: 

C:/GitHub/popsift/src/popsift/s_image.cu:292
    Could not create texture object: invalid argument

![fail](https://user-images.githubusercontent.com/68775513/88455544-64c02c00-ce76-11ea-9677-c574bf1a3a64.PNG)

\\\[12:50:15.276508][warning] Some image(s) have no serial number to identify the camera/lens device.
This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximation they will share the same internal camera parameters.
41 image(s) are concerned.
[12:50:15.293905][warning] Sensor width doesn't exist in the database for image(s):
        - camera brand: Xiaomi
        - camera model: Redmi Note 8 Pro
           - image: IMG_20200717_221431.jpg
Please add camera model(s) and sensor width(s) in the database.
[12:50:15.335738][info] CameraInit report:
        - # views listed: 41
           - # views with an initialized intrinsic listed: 41
           - # views without metadata (with a default intrinsic): 0
        - # intrinsics listed: 1
Nodes to execute:  ['FeatureExtraction_1']
WARNING: downgrade status on node "FeatureExtraction_1(0)" from Status.ERROR to Status.SUBMITTED

[1/1](1/2) FeatureExtraction
 - commandLine: aliceVision_featureExtraction  --input "D:/Federico/Education/Photogrammetry/Meshroom image folder/MeshroomCache/CameraInit/4e31c6223f4ec9b75f4279283020cf2afe353996/cameraInit.sfm" --describerTypes sift --describerPreset normal --forceCpuExtraction False --verboseLevel info --output "D:/Federico/Education/Photogrammetry/Meshroom image folder/MeshroomCache/FeatureExtraction/d97cf38aeffeaa7d27b4dc4f1819b132cb95ee28" --rangeStart 0 --rangeSize 40
 - logFile: D:/Federico/Education/Photogrammetry/Meshroom image folder/MeshroomCache/FeatureExtraction/d97cf38aeffeaa7d27b4dc4f1819b132cb95ee28/0.log
 - elapsed time: 0:00:03.808098
ERROR:root:Error on node computation: Error on node "FeatureExtraction_1(0)":
Log:
Program called with the following parameters:
 * describerPreset = "normal"
 * describerTypes = "sift"
 * forceCpuExtraction = 0
 * input = "D:/Federico/Education/Photogrammetry/Meshroom image folder/MeshroomCache/CameraInit/4e31c6223f4ec9b75f4279283020cf2afe353996/cameraInit.sfm"
 * maxThreads = 0 (default)
 * output = "D:/Federico/Education/Photogrammetry/Meshroom image folder/MeshroomCache/FeatureExtraction/d97cf38aeffeaa7d27b4dc4f1819b132cb95ee28"
 * rangeSize = 40
 * rangeStart = 0
 * verboseLevel = "info"

[12:56:54.987289][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce GTX 1050 Ti
        - compute capability:      6.1
        - total device memory:     4096 MB
        - device memory available: 3367 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   2048
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {131072,65536}
        - max 3D array texture:    {16384,16384,16384}
        - max 2D linear texture:   {131072,65000,2097120}
        - max 2D layered texture:  {32768,32768,2048}
        - number of SM(x)s:        6
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte

[12:56:56.137309][info] Supported CUDA-Enabled GPU detected.
[12:56:57.877771][info] Extracting sift features from view 'C:/Users/fcann/Desktop/acquisizione ogre 1/IMG_20200717_221228.jpg' [gpu]
Choosing device 0: GeForce GTX 1050 Ti
C:/GitHub/popsift/src/popsift/s_image.cu:292
    Could not create texture object: invalid argument

WARNING: downgrade status on node "FeatureExtraction_1(1)" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "FeatureExtraction_1(0)":
Log:
Program called with the following parameters:
 * describerPreset = "normal"
 * describerTypes = "sift"
 * forceCpuExtraction = 0
 * input = "D:/Federico/Education/Photogrammetry/Meshroom image folder/MeshroomCache/CameraInit/4e31c6223f4ec9b75f4279283020cf2afe353996/cameraInit.sfm"
 * maxThreads = 0 (default)
 * output = "D:/Federico/Education/Photogrammetry/Meshroom image folder/MeshroomCache/FeatureExtraction/d97cf38aeffeaa7d27b4dc4f1819b132cb95ee28"
 * rangeSize = 40
 * rangeStart = 0
 * verboseLevel = "info"

[12:56:54.987289][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce GTX 1050 Ti
        - compute capability:      6.1
        - total device memory:     4096 MB
        - device memory available: 3367 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   2048
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {131072,65536}
        - max 3D array texture:    {16384,16384,16384}
        - max 2D linear texture:   {131072,65000,2097120}
        - max 2D layered texture:  {32768,32768,2048}
        - number of SM(x)s:        6
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte

[12:56:56.137309][info] Supported CUDA-Enabled GPU detected.
[12:56:57.877771][info] Extracting sift features from view 'C:/Users/fcann/Desktop/acquisizione ogre 1/IMG_20200717_221228.jpg' [gpu]
Choosing device 0: GeForce GTX 1050 Ti
C:/GitHub/popsift/src/popsift/s_image.cu:292
    Could not create texture object: invalid argument

 - OS: [e.g. win 10, osx, ]
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: 2019.2.0
   - Binary version -
   - Commit reference (if applicable) [e.g. 08ddbe2]

Can someone please tell me how should I proceed? I am not really good at it. I don't have any knowledge in programming and I can't understand what's wrong....

**Comment by JustCommitRandomness** [comment]
I'm seeing this too, in Meshroom-2021.1.0, also with a GFX 1050TI, only when "Force CPU" is unticked.

the error is triggered in AliceVision popsift at the following:
    err = cudaCreateTextureObject( &_input_image_tex, &_input_image_resDesc, &_input_image_texDesc, 0 );

[info] CUDA-Enabled GPU.
Device information:
	- id:                      0
	- name:                    NVIDIA GeForce GTX 1050 Ti
	- compute capability:      6.1
	- total device memory:     4096 MB 
	- device memory available: 3372 MB 
	- per-block shared memory: 49152
	- warp size:               32
	- max threads per block:   1024
	- max threads per SM(X):   2048
	- max block sizes:         {1024,1024,64}
	- max grid sizes:          {2147483647,65535,65535}
	- max 2D array texture:    {131072,65536}
	- max 3D array texture:    {16384,16384,16384}
	- max 2D linear texture:   {131072,65000,2097120}
	- max 2D layered texture:  {32768,32768,2048}
	- number of SM(x)s:        6
	- registers per SM(x):     65536
	- registers per block:     65536
	- concurrent kernels:      yes
	- mapping host memory:     yes
	- unified addressing:      yes
	- texture alignment:       512 byte
	- pitch alignment:         32 byte
0
