### ISSUE TITLE
ExportAnimatedCamera fails, but no errors that I can see

### ISSUE THREAD

**Issue by ahemberger** [alicevision/meshroom#1003]
**Describe the problem**
After running the default operation chain from CameraInit up to StructureFromMotion (which seems to ahve run successfully), I add an ExportAnimatedCamera node to the output of StructureFromMotion, and click "Compute". The node seems to do *something* for a few seconds, then turns red. I'm unable to find any obvious error messages or warnings, so am not sure how to troubleshoot.

**Log**
\\\
Program called with the following parameters:
 * exportUndistortedImages = 1
 * input = "H:/MeshroomCache/StructureFromMotion/076bc65c0e074261f00ea8c5aacc7b97f498e134/sfm.abc"
 * output = "H:/MeshroomCache/ExportAnimatedCamera/61512f945ec717c115d134e0f57c4f88b3ebe106"
 * undistortedImageType = "jpg"
 * verboseLevel = "debug"
 * viewFilter = ""

[19:50:59.363551][debug] 0 samples found in this animated xform.
[19:50:59.370548][debug] 0 samples found in this animated xform.
[19:50:59.817547][debug] 0 samples found in this animated xform.
[19:50:59.817547][debug] 0 samples found in this animated xform.
[19:50:59.817547][debug] 0 samples found in this animated xform.
[19:51:00.044547][info] Build animated camera(s)...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*
\\\

**Desktop (please complete the following and other pertinent information):**
 - OS: Windown 10
 - Python version 3.6.6
 - Meshroom version: 2019.2.0

**Additional context**
My dataset is 2168 images, originally filmed via a Canon 5dmkiii using Magic Lantern. After converting the original cinemaDNG images from Magic Lantern into jpgs, I copied exif data over, all of which meshroom seems to recognize fine. There is a frame 0, not sure if that affects anything; I see in the Images pane after the StructureFromMotion node has run that I have 2168 images, but 2167 cameras. 

I'm sure I'm overlooking something simple, but I do not yet have a deep knowledge of this software and am unsure how to troubleshoot. Can anyone offer me some advice? 

Thank you!

**Comment by natowi** [comment]
ExportAnimatedCamera requires a sequential image series, so if you have unordered images, no camera path can be generated.
If you don`t mind using blender, take a look  this Addon:
https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer

**Comment by ahemberger** [comment]
Hi, yes, as I mentioned, I am using sequential images. Are there requirements for frame padding?

**Comment by ahemberger** [comment]
Responding in the hopes of getting more meaningful help: I tried re-exporting my image sequence using 4-digit frame padding (previously it had no zero-padding), and the ExportAnimatedCamera still fails. 

If anyone has any advice about how to troubleshoot further it would be greatly appreciated!

**Comment by natowi** [comment]
Can you share a small dataset for testing?

**Comment by ahemberger** [comment]
Yes; here are 100 frames of my original 2168-frame sequence. When I load these into a fresh, new Meshroom session, I can run the default graph successfully up to the point of the StructureFromMotion node, but appending an ExportAnimatedCamera and trying to run it fails, with no meaningful error reporting that I can find. 

https://www.dropbox.com/sh/mj5fiotxpay1kr9/AACUXAUCwPSZw2Y0rayKkObia?dl=0

**Comment by ahemberger** [comment]
Hm, on a bit of further experimentation, I notice that if I strip the EXIF data from the above sample images, the ExportAnimatedCamera node indeed seems to produce a result (and undistorted images). Perhaps there is a clash between the EXIF data and the solution meshroom actually derives for the camera? I do notice that - while the EXIF data for the images denotes a 19mm focal length lens, the actual lens I used was a 17-40mm zoom lens that was set to its widest setting (so, 17mm). Would this cause the problems I'm experiencing? 

Obviously I can try to make progress by just removing EXIF data from my entire dataset, but understanding why this is failing would be good to know!

**Comment by natowi** [comment]
`while the EXIF data for the images denotes a 19mm focal length lens, the actual lens I used was a 17-40mm zoom lens that was set to its widest setting (so, 17mm)`

Yes, inaccurate metadata can confuse Meshroom. If you are not sure about the metadata, better leave it. Meshroom will estimate the values.
I´ll try your dataset tomorrow.

**Comment by natowi** [comment]
It also stops in PrepareDenseScene.
