### ISSUE TITLE
50 images are taking too long (5 hours, not even halfway)

### ISSUE THREAD

**Issue by WimBee** [alicevision/meshroom#1004]
Hi guys! I'm trying to scan my face. I've a intel i7 -, 16 gigs ram, GTX 1650. The program is working 5 hours at it and is not even halfway. How can I speed this up?

**Comment by WimBee** [comment]
![image](https://user-images.githubusercontent.com/68851415/88537221-74be4400-d00d-11ea-9e4f-2d312fc2dead.png)
![image](https://user-images.githubusercontent.com/68851415/88537256-84d62380-d00d-11ea-99c7-7292e84102f0.png)

Those are some stats... I already solved a problem. Meshroom was fully running on cpu. Now I assigned gpu. I see no difference...

**Comment by gryan315** [comment]
Is this a laptop?

**Comment by WimBee** [comment]
yea it' a laptop...

**Comment by gryan315** [comment]
That would be the reason it is taking so long, a CPU designed for under 50w (in most cases under 35w) just isn't powerful enough for this type of computational processing.

**Comment by WimBee** [comment]
Just found the problem, I had to update the graphic driver... Thx for taking time funding the answer!

**Comment by fabiencastan** [comment]
@WimBee Thanks for the feedback. What is the rough computation time for the overall dataset after the drivers update?

**Comment by WimBee** [comment]
That's a difficult question. I would say 2-3 hours. (50 images taken with iPhone 7,laptop was charging) Meshroom wasn't able to find the location and angle of 9 pictures, result is pretty bad... I Found some tips online and I'll try again!
