### ISSUE TITLE
How to improve the reconstructed result

### ISSUE THREAD

**Issue by GYX97** [alicevision/meshroom#1005]
Hi guys:

I tried to use the meshroom to reconstruct a cup and a human. For the cup, the shape can not reconstruct properly even I took over 100 images, but the shape of the cup can not be reconstructed well.
![WeChat Screenshot_20200728102902](https://user-images.githubusercontent.com/46411954/88686946-3e400200-d0bd-11ea-920f-2340a6664ec7.png)

When I test on the human, the body part could reconstruct well, but the face can not be reconstructed well, with some drape on it like a zombie. And the hair part can not be reconstructed with over 200 images.
![WeChat Screenshot_20200728104326](https://user-images.githubusercontent.com/46411954/88688651-341f0300-d0bf-11ea-9171-b6ece3357388.png)

I use the default nodes to reconstruct the result. Is there anyone could tell me how to improve the result?
Thanks

**Comment by xzhub** [comment]
@GYX97 [denoise node](https://meshroom-manual.readthedocs.io/en/latest/node-reference/nodes/MeshDenoising.html) might be helpful to make the skin smoother, but it's still not ideal.

**Comment by hargrovecompany** [comment]
I might be able to help.   Can you tell me about the camera settings used for the cup?  Did you move the cup?  Was there a flash used?   

As for the person, curious as to how you were able to get 200 images without the person moving?   Also, hair that light can pass through just won't work well.  Straight hair that lays down give best results, Thinning hair that's wispy will basically disappear.  Tips always disappear.  Curls with locks that stay together will work.  The outter part of frizzy hair will disappear.

**Comment by tkircher** [comment]
I recommend computing the sparse map with ultra settings and several feature detectors, then use that to generate the mesh. The sparse map is almost always perfectly accurate while the dense map almost never is.
