### ISSUE TITLE
Unable to import any photos on a Mac

### ISSUE THREAD

**Issue by urbanstarship** [alicevision/meshroom#1006]
I've been trying to get this to run on a Mac.  I've got the app to run, but cannot import any photos.  I've tried a variety of types of files so I don't suspect the photos themselves.

If I drag and drop or use the file menu I get this in Terminal:
`/bin/sh: aliceVision_cameraInit: command not found`

and if I try to load using the file menu I get this in the Console:
`Python: Connection to sharingd became invalid`

My Specs:
MacBook Pro (Retina, 15-inch, Late 2013)
macOS 10.13.6
NVIDIA GeForce GT 750M
'clang' version Apple LLVM version 10.0.0
CUDA Driver Version 10.1
running Meshroom 2019.2.0

**Comment by simogasp** [comment]
Be sure when I launch meshroom to set up all required env variables and paths:
https://meshroom-manual.readthedocs.io/en/latest/install/linux/linux.html#set-up-environment

(It's for Linux but it also applied to osx)

**Comment by urbanstarship** [comment]
I followed Ryan Baumann's official instructions for MacOS:

[https://ryanfb.github.io/etc/2018/08/17/alicevision_and_meshroom_on_mac_os_x.html](https://ryanfb.github.io/etc/2018/08/17/alicevision_and_meshroom_on_mac_os_x.html)
[https://meshroom-manual.readthedocs.io/en/latest/install/osx/osx.html](https://meshroom-manual.readthedocs.io/en/latest/install/osx/osx.html)

I'm fairly new at this Unix and Python stuff, but I think his Homebrew script wrote the files to `/usr/local/bin/` and `/usr/local/lib/`(already listed in $PATH) but there seems to be files missing.  When I looked at the Linux binary ZIP file from the AliceVision site there is a file inside called "aliceVision_cameraInit" in the `bin` folder, for example, but that's not in my `/usr/local/bin/`

Not sure how to fix that...

**Comment by urbanstarship** [comment]
I think it's something to do with the update from

**Comment by urbanstarship** [comment]
OK, I believe it's working now.  @ryanfb updated his brew formula...

https://github.com/ryanfb/homebrew-alicevision/issues/9

I still couldn't get meshroom-2019.2.0 to run, but meshroom-2019.1.0 seems to be.

It was a bit of a paradox to have the macOS 10.13 High Sierra, CUDA 10.2 and Xcode 10.2 combo because Apple does not want you to run Xcode 10.2 on anything earlier than macOS 10.14 Mojave.  I did find a guide to make it work:

https://codewithchris.com/xcode-update/#:~:text=Xcode%2010.2%20on%20High%20Sierra%20%E2%80%93%20Step%20by%20Step&text=Recently%20Apple%20has%20updated%20Xcode,Swift%205%20using%20Xcode%2010.2.

**Comment by ryanfb** [comment]
FWIW, I've updated [my guide](https://ryanfb.github.io/etc/2018/08/17/alicevision_and_meshroom_on_mac_os_x.html) to recommend just using CUDA 10.1 for that reason. I also updated it to reflect the correct version numbers for meshroom-2019.2.0 etc.—I tried 2019.2.0 the other day after fixing my formula and it worked fine for processing photos & generating models, though Meshroom's built-in model renderer seemed to be broken and I don't have the time to investigate.
