### ISSUE TITLE
interaction problems on 15" 4k display of HP spectre x360 (2019 edition)

### ISSUE THREAD

**Issue by heikog** [alicevision/meshroom#1008]
Hi Guys,
when I use MR on my spectre I cannot activate many of the small buttons.
Mayn UI parts are inaccessible - it seems the "hit target" or so is "a bit off"

**Comment by fabiencastan** [comment]
If someone is interested to look at this problem, here is a Qt article:
https://doc.qt.io/qt-5/highdpi.html
