### ISSUE TITLE
How to take pictures of two positions of an object for meshroom?[question]

### ISSUE THREAD

**Issue by Bonegurl** [alicevision/meshroom#1009]
I am trying to get a full 3D mesh of bones. Hence, i have managed to successfully produce a very detailed mesh of a bone, but when i try with all the other ones it doesn't work by taking two sets of pictures in two positions. As in, meshroom recognizes that it has been 'flipped over' and doesn't take into account the pictures with the second position, even though i got it to work with an original bone. I tried to recreate the same environment the successful bone was in,  but meshroom still isn't having it. And yes the background is featureless and just white. I mean it worked with the first bone, why would it not work now?

If anyone has any suggestions to trick meshroom into taking both positions into account in during the reconstruction, it would be much appreciated. I've literally tried everything I could think of.

**Comment by gryan315** [comment]
It can be difficult because of not having enough overlap with just a flipped over object. One solution is to put the object into a third position that will have significant overlap of the other two positions. 

Is the background in your photos truly featureless (including no shadow)? I normally use a black velvet background which does a terrific job of absorbing light, but once in a while a piece of dust will sneak in and throw everything off, then I'll go through every photo and remove the dust (and sometimes play with the curves and levels to see if there are any other hidden features).

**Comment by Bonegurl** [comment]
> It can be difficult because of not having enough overlap with just a flipped over object. One solution is to put the object into a third position that will have significant overlap of the other two positions.
> 
> Is the background in your photos truly featureless (including no shadow)? I normally use a black velvet background which does a terrific job of absorbing light, but once in a while a piece of dust will sneak in and throw everything off, then I'll go through every photo and remove the dust (and sometimes play with the curves and levels to see if there are any other hidden features).

Thank you for ur comment, I will try the third position!

There is shadow under the bones, ive tried to light it with lights to minimize the contrast, but no luck.  But there is not a shadow in the background, but i will try to clean the background to see if that changes anything. The black velvet background is a genius idea. Do you go to any fabric store and just ask for 'black velvet' or is there a specific name for this material?

**Comment by gryan315** [comment]
I just got what was available at the fabric store, I use a lint roller on it before I shoot (and sometimes in the middle of a shoot, velvet is a dust magnet). I've used it inside a home made lightbox and with a ring flash.

**Comment by xzhub** [comment]
I was testing a web service recently, which implemented AI image masking pipeline besides meshroom to make it capable to build full angel 3d models. You may want to check it out and see if it helps: https://www.3dscan.io/faq
The construction process may last a couple of hours but the final result is pretty good.
