### ISSUE TITLE
[question]The following "submitters" plugins could not be loaded ==   * simpleFarmSubmitter: No module named 'simpleFarm'

### ISSUE THREAD

**Issue by zhuangpeixi** [alicevision/meshroom#1010]
**Describe the problem**
A clear and concise description of what the problem is.
The following "submitters" plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'
**Screenshots**

**Dataset**
If applicable, add a link or *few* images to help better understand where the problem may come from.

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ]
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1]
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**

**Comment by natowi** [comment]
This can be ignored. It refers to a renderfarm submitter plugin that is not included.
