### ISSUE TITLE
How to get aliceVision_cameraInit.exe?

### ISSUE THREAD

**Issue by zhuangpeixi** [alicevision/meshroom#1011]
RuntimeError: CameraInit failed with error code 127.
Command was: "aliceVision_cameraInit  --groupCameraFallback folder --viewIdRegex ".*?(\d+)" --defaultFieldOfView 45.0 --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --verboseLevel info --viewIdMethod metadata --sensorDatabase "" --output "/tmp/tmpckTnvt/CameraInit/8ba5ac2ccbfbc9dee484d6196f5a537c4e8087aa/cameraInit.sfm" --allowSingleView 1 --input "/tmp/tmpckTnvt/CameraInit/8ba5ac2ccbfbc9dee484d6196f5a537c4e8087aa//viewpoints.sfm"".

**Comment by natowi** [comment]
How to get aliceVision_cameraInit.exe

It is included in the release https://www.fosshub.com/Meshroom.html?dwl=Meshroom-2019.2.0-win64.zip

I am not sure about your other problem

**Comment by zhuangpeixi** [comment]
I see,thanks.
