### ISSUE TITLE
Error on node computation: Error on node "PrepareDenseScene_1(0)"

### ISSUE THREAD

**Issue by zhuangpeixi** [alicevision/meshroom#1012]
[2020-08-01 08:41:10,392][ERROR] Error on node computation: Error on node "PrepareDenseScene_1(0)":
Log:
Program called with the following parameters:
 * evCorrection = 0
 * input = "C:/Users/庄培溪/AppData/Local/Temp/MeshroomCache/StructureFromMotion/a6684631da09ba4fbc91a6535848fd2656de77fe/sfm.abc"
 * output = "C:/Users/庄培溪/AppData/Local/Temp/MeshroomCache/PrepareDenseScene/919091b8b496a744420239db85b7d54e2685aeee"
 * outputFileType = "exr"
 * rangeSize = 40
 * rangeStart = 0
 * saveMatricesTxtFiles = 0
 * saveMetadata = 1
 * verboseLevel = "info"

Exporting Scene Undistorted Images
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
[08:41:06.054886][info] median Ev : 9.92481

WARNING: downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Publish_1" from Status.SUBMITTED to Status.NONE
Traceback (most recent call last):
  File "meshroom_photogrammetry", line 203, in <module>
    meshroom.core.graph.executeGraph(graph, toNodes=toNodes, forceCompute=args.forceCompute, forceStatus=args.forceStatus)
  File "E:\GitHub\meshroom\meshroom\core\graph.py", line 1150, in executeGraph
    chunk.process(forceCompute)
  File "E:\GitHub\meshroom\meshroom\core\node.py", line 365, in process
    self.node.nodeDesc.processChunk(self)
  File "E:\GitHub\meshroom\meshroom\core\desc.py", line 490, in processChunk
    raise RuntimeError('Error on node "{}":\nLog:\n{}'.format(chunk.name, logContent))
RuntimeError: Error on node "PrepareDenseScene_1(0)":
Log:
Program called with the following parameters:
 * evCorrection = 0
 * input = "C:/Users/庄培溪/AppData/Local/Temp/MeshroomCache/StructureFromMotion/a6684631da09ba4fbc91a6535848fd2656de77fe/sfm.abc"
 * output = "C:/Users/庄培溪/AppData/Local/Temp/MeshroomCache/PrepareDenseScene/919091b8b496a744420239db85b7d54e2685aeee"
 * outputFileType = "exr"
 * rangeSize = 40
 * rangeStart = 0
 * saveMatricesTxtFiles = 0
 * saveMetadata = 1
 * verboseLevel = "info"

Exporting Scene Undistorted Images
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
[08:41:06.054886][info] median Ev : 9.92481

**Comment by natowi** [comment]
Some nodes may not work with non-latin characters in the paths (like 庄培溪)
