### ISSUE TITLE
Prepare Dense Scene Error

### ISSUE THREAD

**Issue by miquelrosell99** [alicevision/meshroom#1015]
Hello,
I'm getting an error when trying to compute the Prepare Dense Scene node. It's strange, because it usually works without any problems:
![image](https://user-images.githubusercontent.com/38435442/89116553-b0d22880-d495-11ea-9c5b-50299e1868ef.png)

These are the logs i get:
{
    "status": "ERROR",
    "execMode": "LOCAL",
    "nodeName": "PrepareDenseScene_1",
    "nodeType": "PrepareDenseScene",
    "packageName": "aliceVision",
    "packageVersion": null,
    "graph": "",
    "commandLine": "aliceVision_prepareDenseScene  --input \"F:/Documentos/Universitat/GEM/Quart/TFG/Projectes Meshroom/Excursi\u00f3 Pirineus/MeshroomCache/StructureFromMotion/0096df343e4b80c2fa3e9eadcbb056167847f231/sfm.abc\" --outputFileType exr --saveMetadata True --saveMatricesTxtFiles False --evCorrection False --verboseLevel info --output \"F:/Documentos/Universitat/GEM/Quart/TFG/Projectes Meshroom/Excursi\u00f3 Pirineus/MeshroomCache/PrepareDenseScene/52532b163b1736f5eab5d7ee5826748d6fd6bc1f\" --rangeStart 0 --rangeSize 40",
    "env": null,
    "startDateTime": "2020-08-02 07:52:57.937947",
    "endDateTime": "",
    "elapsedTime": 0,
    "hostname": "Baymax",
    "sessionUid": "32b5829c-d483-11ea-b305-d0c0bfb5a3ae",
    "returnCode": 3221226505,
    "elapsedTimeStr": "0:00:00"
}

Any help will be appreciated. Thanks!

**Comment by natowi** [comment]
Looks like you have a special character in your path: Ó // u00f3 Pirineus. 
Avoid special characters/non-ASCII characters in Meshroom and images file paths

**Comment by miquelrosell99** [comment]
Thanks!

**Comment by fabiencastan** [comment]
The error comes from https://github.com/OpenImageIO/oiio/issues/2779

**Comment by alhas2016** [comment]
![Error on computation_PrepareDenseScene node](https://user-images.githubusercontent.com/19624228/221356096-8bf5b8cf-99c9-4d2c-9752-61df5a99345a.PNG)

I'm encountering a computation error on the PrepareDenseScene node in Meshroom 2021.1.0, and can't see what's causing it.

As far as I can see, 
I have no special characters or non-ASCII characters in the file paths. *
The file pathway isn't too long *

* I've certainly never had these problems before now.

What else might be causing this, please ?
