### ISSUE TITLE
Meshroom stops at Meshing stage, with below details. 

### ISSUE THREAD

**Issue by allajlaaj** [alicevision/meshroom#1023]
**Configuration**
Version 2019.2.0
Windows 10 
Python 3.6.6
PC details: gtx980ti
i7-6700k
updated camera details
thanks 
Program called with the following parameters:
 * addLandmarksToTheDensePointCloud = 0
 * angleFactor = 15
 * colorizeOutput = 0
 * contributeMarginFactor = 2
 * depthMapsFilterFolder = "C:/Users/Admin/AppData/Local/Temp/MeshroomCache/DepthMapFilter/b29de16ceb6da4b3c58ef117c4fe8fa117be0af7"
 * depthMapsFolder = "C:/Users/Admin/AppData/Local/Temp/MeshroomCache/DepthMap/dcce580f8cb5254ed4471d9ae33c3302abdb7a9c"
 * estimateSpaceFromSfM = 1
 * estimateSpaceMinObservationAngle = 56
 * estimateSpaceMinObservations = 3
 * input = "C:/Users/Admin/AppData/Local/Temp/MeshroomCache/StructureFromMotion/3c59a8e0a5327a7fd4fefa8edc82ea42a7862013/sfm.abc"
 * maxInputPoints = 500000
 * maxPoints = 100000
 * maxPointsPerVoxel = 1000000
 * minAngleThreshold = 1
 * minStep = 2
 * output = "C:/Users/Admin/AppData/Local/Temp/MeshroomCache/Meshing/971adc1bd3d691e7f9cdce639d0ce2dde57c7ba2/densePointCloud.abc"
 * outputMesh = "C:/Users/Admin/AppData/Local/Temp/MeshroomCache/Meshing/971adc1bd3d691e7f9cdce639d0ce2dde57c7ba2/mesh.obj"
 * partitioning =  Unknown Type "enum EPartitioningMode"
 * pixSizeMarginFinalCoef = 4
 * pixSizeMarginInitCoef = 2
 * refineFuse = 1
 * repartition =  Unknown Type "enum ERepartitionMode"
 * saveRawDensePointCloud = 0
 * simFactor = 15
 * simGaussianSize = 10
 * simGaussianSizeInit = 10
 * universePercentile = 0.999 (default)
 * verboseLevel = "info"
 * voteMarginFactor = 4

[01:38:09.187390][info] Found 1 image dimension(s): 
[01:38:09.188388][info] 	- [3648x2736]
[01:38:09.192377][info] Overall maximum dimension: [3648x2736]
[01:38:09.192377][warning] repartitionMode: 1
[01:38:09.192377][warning] partitioningMode: 1
[01:38:09.192377][info] Meshing mode: multi-resolution, partitioning: single block.
[01:38:09.193374][info] Estimate space from SfM.

**Comment by natowi** [comment]
Sorry for the late reply. Do you still have this problem?
