### ISSUE TITLE
[bug] moto z 2 force incorrectly named in camerasensors.db

### ISSUE THREAD

**Issue by jscancella** [alicevision/meshroom#1024]
**Describe the bug**
The Motorola Z2 force is listed as `Motorola Moto Z2 Force Edition` however, when viewing the images in meshroom the name shows up as `Moto Z (2)`.

**To Reproduce**
1. drop image taken with Motorola Z 2 force phone
2. See error in top left of image

**Expected behavior**
Camera sensor width is correct found in camerasensors.db

**Screenshots**
![moto z 2 force](https://user-images.githubusercontent.com/7903917/89717600-1d619180-d986-11ea-9d9b-d91fe6dff088.PNG)

**Log**
```
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:/Users/John/Documents/Meshroom-2019.2.0-win64/saved projects/MeshroomCache/CameraInit/feb4080b95056b6243a715a0e9c5bac32298323d//viewpoints.sfm"
 * output = "C:/Users/John/Documents/Meshroom-2019.2.0-win64/saved projects/MeshroomCache/CameraInit/feb4080b95056b6243a715a0e9c5bac32298323d/cameraInit.sfm"
 * sensorDatabase = "C:\Users\John\Documents\Meshroom-2019.2.0-win64\aliceVision\share\aliceVision\cameraSensors.db"
 * verboseLevel = "info"

[13:38:47.665944][info] CameraInit report:
	- # views listed: 160
	   - # views with an initialized intrinsic listed: 160
	   - # views without metadata (with a default intrinsic): 0
	- # intrinsics listed: 1
```

**Desktop (please complete the following and other pertinent information):**
 - OS: Windows 10
 - Python version: 3.3.6
 - Qt/PySide version: whatever comes with meshroom
 - Meshroom version: 2019.2.0

**Photo from phone**
![IMG_20200808_112034864](https://user-images.githubusercontent.com/7903917/89717640-81845580-d986-11ea-9c1b-16b2f3c715fb.jpg)

**Comment by natowi** [comment]
Simply add `Motorola;Moto Z (2);4.96;devicespecifications` to your sensor database.

https://github.com/alicevision/AliceVision/pull/840

**Comment by jscancella** [comment]
wouldn't it be better to fix line https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/sensorDB/cameraSensors.db#L3268 so that it works correctly?

**Comment by natowi** [comment]
I have added your model name. I did not remove the old entry, as it may be possible that some devices have a different model name in the metadata (this can change with device build versions,)

**Comment by jscancella** [comment]
ok that makes sense. Thanks!
