### ISSUE TITLE
[question] obj without texture or stl

### ISSUE THREAD

**Issue by jscancella** [alicevision/meshroom#1025]
**Describe the problem**
The default pipeline produces an obj with texture at the end. I am more interested in 3d printing, which doesn't care about this texture. Is there a way to generate a "plain" obj or stl (without the colored texture)?

**Comment by ChemicalXandco** [comment]
You can delete the 'Texturing' node before pressing start.

**Comment by jscancella** [comment]
@ChemicalXandco so which node produces the obj file then?

**Comment by ChemicalXandco** [comment]
The 'MeshFiltering' node will have the mesh.

**Comment by jscancella** [comment]
awesome, thanks!
