### ISSUE TITLE
Depth map information

### ISSUE THREAD

**Issue by bgpantojar** [alicevision/meshroom#1028]
Dear all,

I just was wondering if is possible to get as output the information about the images depthmap  that meshroom computes?. If so, how can I generate them or where can I find that information?.

Thanks!

**Comment by natowi** [comment]
"information about the images" ? Can you please clarify what exactly you are looking for?

**Comment by bgpantojar** [comment]
The depthmap. The depth of each pixel in the images used to generate the 3D model

**Comment by natowi** [comment]
Are you asking which pixel correspond to which depth? I don´t know the answer, but there is a recent addition to MR dev that allows to add DepthMaps to the 3D viewer. I think you could take a look at the code to find out how it works. https://github.com/alicevision/meshroom/pull/650 merged https://github.com/alicevision/meshroom/pull/769

If you could explain why and what for you want to use the DepthMaps it may help to find a solution.

**Comment by bgpantojar** [comment]
Exactly, I would like to have the depth for each pixel in the images used to generate the 3D model. I want to be able to discriminate 2 planes whose normal is towards the camera but they are at different distances. So, I thought maybe the depthmaps meshroom calculates to find the dense model could contain some related information.

For instance, in the next image, you can see 5 planes with the same normal direction (towards the camera), and they are localized at 3 different distances from the camera. I thought the depth can give me some information usable in that case.

![100_7104](https://user-images.githubusercontent.com/35929939/89989466-48e3c500-dc81-11ea-84a9-182856053ff9.JPG)

**Comment by natowi** [comment]
Does the new Depth Image viewer solve your issue?

**Comment by bgpantojar** [comment]
Yes!.. thanks a lot!
