### ISSUE TITLE
Images do not load. "You probably have a corrupted image within the images that you are trying to import."

### ISSUE THREAD

**Issue by bgpantojar** [alicevision/meshroom#1034]
I am using the meshroom repository (up to the date) and inside I have the binaries of alicevision and qtPlugins (from the last release). At the moment of loading the images the message of the picture is displayed.

![Screenshot from 2020-08-15 09-55-03](https://user-images.githubusercontent.com/35929939/90308186-b55b0000-dedd-11ea-93d6-9b74ddcc3fc6.png)

In an old version repository I have, it works fine. Also in the last year's release version of meshroom.

**Desktop (please complete the following and other pertinent information):**
 - OS: 
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
 - Python version  2.7.17

Any sugestion please?

**Comment by natowi** [comment]
"meshroom repository (up to the date) ... alicevision (from the last release)"

You can not mix different Alicevision and Meshroom  versions. If you use the latest Meshroom dev, you also have to use the latest Alicevision dev.

**Comment by bgpantojar** [comment]
It has been difficult for me to build up the Alicevision-dev. Is there another possibility of using meshroom last version without building alicevision?

**Comment by natowi** [comment]
We only have appveyor snapshot-dev-builds for windows. If you are not in a hurry: the 2020.1 version will be released in a few weeks.

**Comment by bgpantojar** [comment]
Understand... that is great. Looking forward for new release.. thanks
