### ISSUE TITLE
HELP！！ERROR:root:Error on node computation: Error on node "StructureFromMotion_1"

### ISSUE THREAD

**Issue by dragunov47** [alicevision/meshroom#1036]
I'm using monstree mini3 as my object ,but it could not work .
OS :Windows 10
Version 2019.2.0
RAM :16GB 

Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportColoredPointCloud, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, LDRToHDR, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
WARNING:root:Unable to open default EUDC font: "EUDC.TTE"
WARNING:root:Unable to open default EUDC font: "EUDC.TTE"
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:\Users\wsdxlwj\AppData\Local\Temp\tmp4ltfjf2y/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm"
 * output = "C:/Users/wsdxlwj/AppData/Local/Temp/tmp4ltfjf2y/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm"
 * sensorDatabase = "C:\Users\wsdxlwj\Anaconda3\Lib\site-packages\PyQt5\Qt\plugins\Meshroom-2019.2.0\aliceVision\share\aliceVision\cameraSensors.db"
 * verboseLevel = "info"

[19:50:25.854712][warning] Some image(s) have no serial number to identify the camera/lens device.
This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximation they will share the same internal camera parameters.
3 image(s) are concerned.
[19:50:25.870669][info] CameraInit report:
        - # views listed: 3
           - # views with an initialized intrinsic listed: 3
           - # views without metadata (with a default intrinsic): 0
        - # intrinsics listed: 1
Nodes to execute:  ['StructureFromMotion_1', 'PrepareDenseScene_1', 'DepthMap_1', 'DepthMapFilter_1', 'Meshing_1', 'MeshFiltering_1', 'Texturing_1']
WARNING: downgrade status on node "StructureFromMotion_1" from Status.ERROR to Status.SUBMITTED

[1/7] StructureFromMotion
 - commandLine: aliceVision_incrementalSfM  --input "C:/Users/wsdxlwj/Documents/MeshroomCache/CameraInit/a9077232903a59114463d31dd401c15cdb3925a5/cameraInit.sfm" --featuresFolders "C:/Users/wsdxlwj/Documents/MeshroomCache/FeatureExtraction/45944f83946d862bfc9cfade200ed28b9247568c" --matchesFolders "C:/Users/wsdxlwj/Documents/MeshroomCache/FeatureMatching/cda5749a21bdd5539821c352b10f9223762c791d" --describerTypes sift --localizerEstimator acransac --localizerEstimatorMaxIterations 4096 --localizerEstimatorError 0.0 --lockScenePreviouslyReconstructed False --useLocalBA True --localBAGraphDistance 1 --maxNumberOfMatches 0 --minInputTrackLength 2 --minNumberOfObservationsForTriangulation 2 --minAngleForTriangulation 3.0 --minAngleForLandmark 2.0 --maxReprojectionError 4.0 --minAngleInitialPair 5.0 --maxAngleInitialPair 40.0 --useOnlyMatchesFromInputFolder False --useRigConstraint True --lockAllIntrinsics False --initialPairA "" --initialPairB "" --interFileExtension .abc --verboseLevel info --output "C:/Users/wsdxlwj/Documents/MeshroomCache/StructureFromMotion/11bc96cad5eaad3ed136a62b933a1fa46e658e6e/sfm.abc" --outputViewsAndPoses "C:/Users/wsdxlwj/Documents/MeshroomCache/StructureFromMotion/11bc96cad5eaad3ed136a62b933a1fa46e658e6e/cameras.sfm" --extraInfoFolder "C:/Users/wsdxlwj/Documents/MeshroomCache/StructureFromMotion/11bc96cad5eaad3ed136a62b933a1fa46e658e6e"
 - logFile: C:/Users/wsdxlwj/Documents/MeshroomCache/StructureFromMotion/11bc96cad5eaad3ed136a62b933a1fa46e658e6e/log
 - elapsed time: 0:00:05.715377
ERROR:root:Error on node computation: Error on node "StructureFromMotion_1":
Log:
Program called with the following parameters:
 * describerTypes = "sift"
 * extraInfoFolder = "C:/Users/wsdxlwj/Documents/MeshroomCache/StructureFromMotion/11bc96cad5eaad3ed136a62b933a1fa46e658e6e"
 * featuresFolders =  = [C:/Users/wsdxlwj/Documents/MeshroomCache/FeatureExtraction/45944f83946d862bfc9cfade200ed28b9247568c]
 * initialPairA = ""
 * initialPairB = ""
 * input = "C:/Users/wsdxlwj/Documents/MeshroomCache/CameraInit/a9077232903a59114463d31dd401c15cdb3925a5/cameraInit.sfm"
 * interFileExtension = ".abc"
 * localBAGraphDistance = 1
 * localizerEstimator =  Unknown Type "enum aliceVision::robustEstimation::ERobustEstimator"
 * localizerEstimatorError = 0
 * localizerEstimatorMaxIterations = 4096
 * lockAllIntrinsics = 0
 * lockScenePreviouslyReconstructed = 0
 * matchesFolders =  = [C:/Users/wsdxlwj/Documents/MeshroomCache/FeatureMatching/cda5749a21bdd5539821c352b10f9223762c791d]
 * maxAngleInitialPair = 40
 * maxNumberOfMatches = 0
 * maxReprojectionError = 4
 * minAngleForLandmark = 2
 * minAngleForTriangulation = 3
 * minAngleInitialPair = 5
 * minInputTrackLength = 2
 * minNumberOfObservationsForTriangulation = 2
 * output = "C:/Users/wsdxlwj/Documents/MeshroomCache/StructureFromMotion/11bc96cad5eaad3ed136a62b933a1fa46e658e6e/sfm.abc"
 * outputViewsAndPoses = "C:/Users/wsdxlwj/Documents/MeshroomCache/StructureFromMotion/11bc96cad5eaad3ed136a62b933a1fa46e658e6e/cameras.sfm"
 * useLocalBA = 1
 * useOnlyMatchesFromInputFolder = 0
 * useRigConstraint = 1
 * useTrackFiltering = 1 (default)
 * verboseLevel = "info"

Loading features
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
[19:50:42.326685][info] Supported CUDA-Enabled GPU detected.

WARNING: downgrade status on node "PrepareDenseScene_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "StructureFromMotion_1":
Log:
Program called with the following parameters:
 * describerTypes = "sift"
 * extraInfoFolder = "C:/Users/wsdxlwj/Documents/MeshroomCache/StructureFromMotion/11bc96cad5eaad3ed136a62b933a1fa46e658e6e"
 * featuresFolders =  = [C:/Users/wsdxlwj/Documents/MeshroomCache/FeatureExtraction/45944f83946d862bfc9cfade200ed28b9247568c]
 * initialPairA = ""
 * initialPairB = ""
 * input = "C:/Users/wsdxlwj/Documents/MeshroomCache/CameraInit/a9077232903a59114463d31dd401c15cdb3925a5/cameraInit.sfm"
 * interFileExtension = ".abc"
 * localBAGraphDistance = 1
 * localizerEstimator =  Unknown Type "enum aliceVision::robustEstimation::ERobustEstimator"
 * localizerEstimatorError = 0
 * localizerEstimatorMaxIterations = 4096
 * lockAllIntrinsics = 0
 * lockScenePreviouslyReconstructed = 0
 * matchesFolders =  = [C:/Users/wsdxlwj/Documents/MeshroomCache/FeatureMatching/cda5749a21bdd5539821c352b10f9223762c791d]
 * maxAngleInitialPair = 40
 * maxNumberOfMatches = 0
 * maxReprojectionError = 4
 * minAngleForLandmark = 2
 * minAngleForTriangulation = 3
 * minAngleInitialPair = 5
 * minInputTrackLength = 2
 * minNumberOfObservationsForTriangulation = 2
 * output = "C:/Users/wsdxlwj/Documents/MeshroomCache/StructureFromMotion/11bc96cad5eaad3ed136a62b933a1fa46e658e6e/sfm.abc"
 * outputViewsAndPoses = "C:/Users/wsdxlwj/Documents/MeshroomCache/StructureFromMotion/11bc96cad5eaad3ed136a62b933a1fa46e658e6e/cameras.sfm"
 * useLocalBA = 1
 * useOnlyMatchesFromInputFolder = 0
 * useRigConstraint = 1
 * useTrackFiltering = 1 (default)
 * verboseLevel = "info"

Loading features
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
[19:50:42.326685][info] Supported CUDA-Enabled GPU detected.

PLEASE HELP！！

**Comment by natowi** [comment]
"Anaconda3\Lib\site-packages\PyQt5\Qt\plugins\Meshroom-2019.2.0"

There is probably an issue with your Meshroom installation. Do you use the pre-build binaries? https://github.com/alicevision/meshroom/releases/tag/v2019.2.0

**Comment by dragunov47** [comment]
> "Anaconda3\Lib\site-packages\PyQt5\Qt\plugins\Meshroom-2019.2.0" (that´s a strange path for the sensordb)
> 
> There is probably an issue with your Meshroom installation . Do you use the pre-build binaries? https://github.com/alicevision/meshroom/releases/tag/v2019.2.0

Yes，I used the the pre-build binaries（https://github.com/alicevision/meshroom/releases/tag/v2019.2.0）
download the Meshroom-2019.2.0-win64.zip and unzip, click Meshroom.exe to start.
Any extra installation step did I miss?  ⊙(・◇・)？
![image](https://user-images.githubusercontent.com/57161542/90327075-879bb700-dfc2-11ea-886a-340de22655de.png)
I put Meshroom-2019.2.0 at  "Anaconda3\Lib\site-packages\PyQt5\Qt\plugins\'' because there is  a  problem when I start Meshroom.exe "This application failed to start because no Qt platform plugin could be initialized"
I have reinstalled Pyqt5 and put it at''sensorDatabase = "C:\Users\wsdxlwj\Desktop\Meshroom-2019.2.0\aliceVision\share\aliceVision\cameraSensors.db"
But it still doesn't work. It's the same mistake.
I'm terribly grateful to you for all your help(ง •_•)ง

**Comment by natowi** [comment]
You can try https://github.com/alicevision/meshroom/issues/304

**Comment by dragunov47** [comment]
I have found a solution to the problem.
Some errors in SFM seem to be caused by a problem with the address I saved.
When I choose continue without saving and continue refactoring, the program will not have any problems
Thank you for your help. Thank you
