### ISSUE TITLE
render array

### ISSUE THREAD

**Issue by mpdugas** [alicevision/meshroom#1037]
**Describe the problem**
I would like to use a render array taken from a 3D object in 3D space, using a virtual camera in the 3D program.   In this way, I can control alignment, lighting, background and all other image factors for a usable render.

I can provide as much information as the render program gives me regarding the virtual camera, such as focal length, f-stop shutter open and close, etc.

**Desktop (please complete the following and other pertinent information):
 - OS: win 10
 - Meshroom version: 2019.2.0
   
I have attached a couple of sample renders, and the Meshroom reaction to them.

render array:
![Render 1](https://user-images.githubusercontent.com/69727434/90344409-26361100-dfdf-11ea-982a-7242ce9c0f42.png)
![Render 2](https://user-images.githubusercontent.com/69727434/90344411-26cea780-dfdf-11ea-8a4d-a9dc2b3935b8.png)
![Render 3](https://user-images.githubusercontent.com/69727434/90344412-26cea780-dfdf-11ea-9d90-a8e20aedc0ed.png)

Meshroom reaction to renders:
![Render 4](https://user-images.githubusercontent.com/69727434/90344413-26cea780-dfdf-11ea-9754-9e98b2dfff1e.png)

Do not be concerned about the model's position in the renders.  Tracking objects, centering, all of those concerns can be addressed as the render is set-up.

Mainly I wanted to show how Meshroom reacts to the renders, and I am asking what can I put in the camera database to emulate this virtual camera?

Many thanks for any help in this regard; being able to use Meshroom would offer a host of creative possibilities that just exporting the 3D object, which this rendering program does not do very well, would give me.

**Comment by fabiencastan** [comment]
Sorry, we missed to answer this issue!
As indicated on your screenshot, it would help to set the metadata:
- `Make`
- `Model`
- `Exif:FocalLength`
And ensure that Make/Model exist in the sensor database.

And eventually (only important if you simulate several types of cameras that you want to combine in the reconstruction):
- `Exif:BodySerialNumber`
- `Exif:LensSerialNumber`

You can use ExifTool to set metadata on your rendered images.

BTW, the challenge on you sample dataset is that the lack of textures on your object.

**Comment by mpdugas** [comment]
This is a virtual camera within the 3D rendering software; it has no "make" nor "model" nor "sensor" size to include in the camera database.

I was hoping that there might be a way to create an imaginary camera that Meshroom would recognize as part of its camera database.    How can I create an entry in the camera database that Meshroom will accept?  The only data that I can give is the imaginary camera's focal length.  The rest of the requirements that Meshroom needs for camera information are not something I know.  I can, however, experiment with different values until Meshroom begins to process the array correctly.

While I can directly export the object itself for 3D printing, there are some copyright issues with certain models that make that solution unrealistic, thus Meshroom is my "work-around".

The figure's plain surface textures are not a real concern; this is only a sample render, in its simplest form, of how the model could be rendered, thus creating the photo array for Meshroom to process.  The final model can have surface textures that re as complex as any in the world itself.

Thanks for giving this your consideration!!  Hopefully, I can find a way to begin 'playing' with this to make it work,

**Comment by natowi** [comment]
> This is a virtual camera within the 3D rendering software; it has no "make" nor "model" nor "sensor" size to include in the camera database.

In Blender you can define all parameters of your camera: https://blender.stackexchange.com/questions/30555/how-to-simulate-a-real-camera-with-blender https://visp-doc.inria.fr/doxygen/visp-3.2.0/tutorial-tracking-mb-generic-rgbd-Blender.html

You can then add the metadata to your exported images using ExifTool or by setting the values in the cameraInit node (intrinsics).

I think there was a blender plugin somewhere to replicate real camera sensors/lenses,... for cinematic productions with exif support. (or was it a Unreal plugin?)
