### ISSUE TITLE
efficient rendering on a renderfarm

### ISSUE THREAD

**Issue by FaRin27** [alicevision/meshroom#1039]
Sry for my English, it's not the best, but I hope you can understand what I want.

**Describe the problem**
I want to use Meshroom more efficiently on the render farm (CGRU / AFANASY).
I know how to send a Job to the Farm so that it start and produce the correct result.
(I use the command line wit Meshroom_photogrammetry ...)
At the moment exact one Render-Node compute one node of the Meshroom-Graph.
Is there a way that two or more render-node compute one node from the Meshroom-Graph?
For example:
- RenderNode1 compute the half from the DepthMap-Node and at the same time
- RenderNode2 compute the other half from the DepthMap-Node
Didn't found anything and have no more Idea where else I could look

**Screenshots**
---

**Dataset**
---

**Log**
---

**Desktop (please complete the following and other pertinent information):**
 - OS: CENTOS 7 and CENTOS 8
 - Python version 2.7.16 and 3.8.5
 - Qt/PySide version 5.12.4
 - Meshroom version: 
   - Binary version 2019.2

**Additional context**
---

**Comment by natowi** [comment]
There was a side note somewhere her about processing nodes in parallel. I don´t know if this https://github.com/alicevision/meshroom/pull/778 helps (computing chunks in parallel)

Would you be so kind to share the details on your (CGRU / AFANASY) setup? It would be a great addition to the documentation.

**Comment by FaRin27** [comment]
=), this could help,
will try it and hope it work how I want.

And yes I can share the setup details for the CGRU/Afanasy render farm, when I finished.
Is there a page for this where I can do that.

**Comment by natowi** [comment]
You could create a new wiki page here https://github.com/alicevision/meshroom/wiki

**Comment by natowi** [comment]
I started a draft here https://github.com/alicevision/meshroom/wiki/Renderfarm-submitters

**Comment by natowi** [comment]
@FaRin27 how do you do?

**Comment by natowi** [comment]
@FaRin27 It would be great to read your experience on the CGRU / AFANASY setup
