### ISSUE TITLE
Cannot load images

### ISSUE THREAD

**Issue by KurtKoss** [alicevision/meshroom#1043]
I cannot load images - error says Vcomp140.DLL was not found. I can launch Meshroom but can't load images. Can anyone help?

**Comment by ChemicalXandco** [comment]
Try installing [Visual C++ redistributable](https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads) (x64).

**Comment by KurtKoss** [comment]
Thanks for the post - installing Visual C++ fixed this issue. Now I have the problem needing a graphics card that is NVidia CUDA - enabled GPU. I will never be an expert at this but want to use Meshroom effectively. Thanks for your help.
