### ISSUE TITLE
VGA analysis problem with depthmapX-0.7.0_win64

### ISSUE THREAD

**Issue by archbsr** [alicevision/meshroom#1056]
Hello, 

I can't get Visual Mean Depth (VMD) at Depthmap 0.0.7 for win64x, While my friend does the same steps at apple-book he can get the analyses. After I started the run VGA analyses, my system waits minutes it gives me only "Visual Integration". I guess it's about the operating system.

On the other hand, I do the same steps on UCL DepthMap 10, gives me VMD analyses. Perhaps because it has set up a file rather than running on .exe file. But the problem is UCL DepthMap10 hasn't got export map as .csv format. That requires me for QGIS.

How can I get VMD analyses on DepthmapX 0.0.7 version?

**Comment by natowi** [comment]
@archbsr You are in the wrong repository. Go to https://github.com/varoudis/depthmapX
