### ISSUE TITLE
[question]Meshroom GoPro 3D scanning

### ISSUE THREAD

**Issue by mb3m3r** [alicevision/meshroom#1059]
**Describe the problem**
I'm using Meshroom on windows 10 with NVIDIA 1060 gtx 3 GB and a GoPro HERO set to timelapse 0.5 secs. to gather a dataset of a doghouse sitting in my garden.  I've made multiple datasets at different times of the day to see if I get different results (which I didn't). The mesh comes all messed up, kinda ignores the object and maps the surroundings. 

When I import all the 150+ pictures of the dataset (some are up to 300 images) they all get the green icons (camera intrinsic and alignment). 

I've tried with a tree and the doghouse, it computes everything well but the outcome is just a bunch of dots not even outlining the object. When I try opening the .OBJ in blender it shows exactly what's on display on Meshroom. 

I'm thinking what can I do to improve this reconstruction? I've tried with my phone which is kinda old (oneplus 2) but get a bunch of alignment and intrinsic issues). I made a few tests with an old Canon Rebel XS with the same alignment issues.  

Should I change the way/angles/background the images were taken? or quantity? 

**Screenshots**

![MESHROOM3](https://user-images.githubusercontent.com/20687352/93005848-d33a7580-f51a-11ea-9fb5-b0c516ec3393.png)
![Meshroom1](https://user-images.githubusercontent.com/20687352/93005851-d9c8ed00-f51a-11ea-8840-36fa4d9acf8f.png)
![Meshroom2](https://user-images.githubusercontent.com/20687352/93005852-dd5c7400-f51a-11ea-8807-4dfb159edc3d.png)

**Dataset**
I uploaded the images from the tree and doghouse to this folder https://drive.google.com/drive/folders/1SpAuKNTUApBmrvXJS4kvmS7JIHKzS3Sw?usp=sharing

**Desktop (please complete the following and other pertinent information):**
-Windows 10
-Nvidia GTX 1060 3GB
-Meshroom 2019.2.0
-GoPro HERO
-Canon Rebel XS
-Oneplus 2

**Comment by natowi** [comment]
Similar to https://github.com/alicevision/meshroom/issues/755, #505, #565, #646
(object does not fill most of the image frame + single coloured flat surface)
