### ISSUE TITLE
Missing plugins

### ISSUE THREAD

**Issue by DagerD** [alicevision/meshroom#1062]
**Describe the problem**
I built meshroom with his dependencies. As i start meshroom with command line i see following warnings:
```
D:\VS_projects\meshroom_with_dependencies\meshroom>python meshroom/ui
[2020-09-15 03:25:09,560][WARNING] == The following "submitters" plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

[2020-09-15 03:25:10,997][WARNING] file:///D:/VS_projects/meshroom_with_dependencies/meshroom/meshroom/ui/qml/Viewer/TestOIIOPlugin.qml:1:1: plugin cannot be loaded for module "DepthMapEntity": ?????????? ????????? ?????????? D:\VS_projects\meshroom_with_dependencies\meshroom\qtPlugins\qml\DepthMapEntity\depthMapEntityQmlPlugin.dll: ?? ?????? ????????? ??????.
[2020-09-15 03:25:11,002][WARNING] file:///D:/VS_projects/meshroom_with_dependencies/meshroom/meshroom/ui/qml/Viewer/TestAliceVisionPlugin.qml:1:1: plugin cannot be loaded for module "AliceVision": ?????????? ????????? ?????????? D:\VS_projects\meshroom_with_dependencies\meshroom\qtPlugins\qml\AliceVision\qtAliceVisionPlugin.dll: ?? ?????? ????????? ??????.
[2020-09-15 03:25:11,090][WARNING] Missing plugin qtAliceVision.
[2020-09-15 03:25:11,090][WARNING] Missing plugin qtOIIO.
```
Plugin structure:
D:\VS_projects\meshroom_with_dependencies\meshroom\qtPlugins\imageformats\QtOIIOPlugin.dll
D:\VS_projects\meshroom_with_dependencies\meshroom\qtPlugins\imageformats\QtOIIOPlugin.lib

D:\VS_projects\meshroom_with_dependencies\meshroom\qtPlugins\qml\AlembicEntity\alembicEntityQmlPlugin.dll
D:\VS_projects\meshroom_with_dependencies\meshroom\qtPlugins\qml\AlembicEntity\alembicEntityQmlPlugin.lib
D:\VS_projects\meshroom_with_dependencies\meshroom\qtPlugins\qml\AlembicEntity\qmldir

D:\VS_projects\meshroom_with_dependencies\meshroom\qtPlugins\qml\AliceVision\qtAliceVisionPlugin.dll
D:\VS_projects\meshroom_with_dependencies\meshroom\qtPlugins\qml\AliceVision\qtAliceVisionPlugin.lib
D:\VS_projects\meshroom_with_dependencies\meshroom\qtPlugins\qml\AliceVision\qmldir

D:\VS_projects\meshroom_with_dependencies\meshroom\qtPlugins\qml\DepthMapEntity\depthMapEntityQmlPlugin.dll
D:\VS_projects\meshroom_with_dependencies\meshroom\qtPlugins\qml\DepthMapEntity\depthMapEntityQmlPlugin.lib
D:\VS_projects\meshroom_with_dependencies\meshroom\qtPlugins\qml\DepthMapEntity\qmldir

Here is my commands to launch meshroom:
```
set QT_PLUGIN_PATH=D:\VS_projects\meshroom_with_dependencies\meshroom\qtPlugins
set QML2_IMPORT_PATH=%QT_PLUGIN_PATH%\qml
set QML_IMPORT_PATH=%QT_PLUGIN_PATH%\qml

cd D:\VS_projects\meshroom_with_dependencies\meshroom && D:

set PYTHONPATH=%CD%

python meshroom/ui
```

Also i have corresponding environment variables:
![image](https://user-images.githubusercontent.com/42409851/93151452-a8137a00-f704-11ea-8392-07cc506f868e.png)
![image](https://user-images.githubusercontent.com/42409851/93151473-b5c8ff80-f704-11ea-88a4-6f9ef33be2e2.png)
![image](https://user-images.githubusercontent.com/42409851/93151507-ce391a00-f704-11ea-9e89-1191e7a4ee78.png)

But i noticed that ALICEVISION_BIN_DIR isn't working, so i duplicated it in "Path" variable

But i created project with QT creator and there is no problem. We can see it on screeshot - no red underlines and IDE says plugin loaded ok.

![Снимок экрана 2020-09-15 030632](https://user-images.githubusercontent.com/42409851/93149962-8d3f0680-f700-11ea-9c4b-3ef20dacd7ec.png)

Here is my log with set QT_DEBUG_PLUGINS=1 and set QML_IMPORT_TRACE=1
[log.txt](https://github.com/alicevision/meshroom/files/5221744/log.txt)

**Desktop (please complete the following and other pertinent information):**
 - OS: win 10
 - Python version 3.8.2
 - Qt/PySide version 5.14.1
 - Meshroom version: 2019.2.0-develop
 - Qt Creator 4.13.0
    Based on Qt 5.15.0 (MSVC 2019, 64 bit)

**Comment by DagerD** [comment]
After upgrading to PySide2 5.15.1i get following 
[log.txt](https://github.com/alicevision/meshroom/files/5222976/log.txt)

**Comment by DagerD** [comment]
Ok i think i got it. Looks like my qtplugins were broken. So i changed the, with qtplugins from latest meshroom release and downgrade DepthMapEntity to 2.0. Now i don't see any errors on startup. But when i make an attempt to load photos, i get:
[log.txt](https://github.com/alicevision/meshroom/files/5223033/log.txt)

**Comment by natowi** [comment]
"changed them with qtplugins from latest meshroom release"
You can not mix files from the 2019.2 release with the latest version build from source.
But you can replicate the file structure from the 2019.2 release, so you don´t need to set env. variables.
