### ISSUE TITLE
[bug] Cannot xyz rotate with SfMTransform

### ISSUE THREAD

**Issue by remmel** [alicevision/meshroom#1064]
**Describe the bug**
The [documentation](https://meshroom-manual.readthedocs.io/en/v2019.2/node-reference/nodes/SfMTransform.html?highlight=Rotation) indicates that it is possible to apply a rotation.
![image](https://user-images.githubusercontent.com/937836/93223437-5a345b80-f770-11ea-8fbf-6bf7611d596c.png)

However, the 2019.2 GUI doesn't contain any Rotation option 
![image](https://user-images.githubusercontent.com/937836/93211201-30276d00-f761-11ea-9aff-f5c039a1f116.png)
and it is not possible to call `aliceVision_utils_sfmTransform` with the `rotation` argument
`aliceVision_utils_sfmTransform  --input "SfM.abc" --rotation "216.0646,-63.92401282503656,-1.1522813235599187" --scale 10.0 --verboseLevel info --output "transformedSfM.abc"`
output following error:
`ERROR: unrecognised option '--rotation'`

Does the documentation wrong or GUI/CLI wrong? How to make a xyz rotation ? The transformation method `transformation` can only rotate around Y.

I also tried without success following command : 
`aliceVision_utils_sfmTransform  --input "SfM.abc" --method rotation --transformation "216.0646,-63.92401282503656,-1.1522813235599187" --scale 1.0 --verboseLevel info --output "transformedSfM.abc"`

(also, the documentation doesn't seems to match the GUI/CLI for `Markers` and `Translation` options)

Related with [main_sfmTransform.cpp](https://github.com/alicevision/AliceVision/blob/v2.2.0/src/software/utils/main_sfmTransform.cpp)

**Comment by natowi** [comment]
Thank you, there was a slip up (my fault ;) ), those options are not available in MR2019.2, but will be in MR2020.1. This will include an interactive rotation and scaling tool.

In MR 2019.2 you have to use the "Transformation" setting and provide the transformation in the format **X,Y,Z;R;S** (note the difference: comma and semicolon) Example: 0,0,0;45;0.1 (rotate by 45°, 0.1 is the default scale)

**Comment by natowi** [comment]
For details on the new Transform tool read: https://github.com/alicevision/meshroom/issues/256#issuecomment-709983331
