### ISSUE TITLE
MR hangs on StructureFromMotions

### ISSUE THREAD

**Issue by SirAxolot** [alicevision/meshroom#1067]
**Describe the problem**
Meshroom consistently throws an error on StructureFromMotions

**Dataset**
[LINK](https://imgur.com/a/puN9Cxw)

**Log**
Where is the log?

**Desktop (please complete the following and other pertinent information):**
 - OS: Win 10
 - Python version: 3.8
 - Qt/PySide version: How do I check this?
 - Meshroom version: Website version
   - Binary version: 2019.2.0
   - Commit reference: I have no idea, I downloaded it from the website.

**Plugins loaded:**  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportColoredPointCloud, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, LDRToHDR, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing

**Comment by natowi** [comment]
Your object has basically no features (smooth black surface). Also some images are out of focus, the object of interest does not fill most of the image and there are light reflections. Check out the other issues with the [dataset-issues label](https://github.com/alicevision/meshroom/issues?q=label%3Adataset-issues+) for similar problems and for solutions.
For your particular case check out http://lellep.xyz/blog/how-to-use-3d-scanning-for-cad-modeling.html

List of tutorials: https://github.com/alicevision/meshroom/wiki/Tutorials
