### ISSUE TITLE
How to set up Camera Rig correctly?

### ISSUE THREAD

**Issue by Dave-van-der-Meer** [alicevision/meshroom#1068]
I have a Stereo Camera which makes image pairs and I want to use them for a reconstruction with known poses. Before using the known poses, I want to make sure the image pairs are correctly initiated as camera rig.

From what I understand from #527 , it is important to have the following folder/file structure:

```
image_folder
├──0
   ├──1.png
   ├──2.png
   └──3.png
└──1
   ├──1.png
   ├──2.png
   └──3.png

```

Initially, I had it slightly different as I named the image files after their relative position:

```
main_folder
├──0
   ├──image_1_left.png
   ├──image_2_left.png
   └──image_3_left.png
└──1
   ├──image_1_right.png
   ├──image_2_right.png
   └──image_3_right.png

```

From what I understand, the first format above is correct and the second presented here is wrong. **Do I understand this correctly?**

The second format gave me 2 different entries for the intrinsics in the cameraInit.sfm folder and the default workflow worked just fine. The first entry (the correct one I guess) crashed at the StructureFromMotion node and it gives me the following entries in the cameraInit.sfm file:

```json
"intrinsics": [
        {
            "intrinsicId": "158036735",
            "width": "800",
            "height": "800",
            "serialNumber": "D:\/student_job\/simulation_7_dataset\/dataset_7_sorted_renamed\/rig\/0_rig_1107225601_0",
            "type": "radial3",
            "initializationMode": "unknown",
            "pxInitialFocalLength": "-1",
            "pxFocalLength": "965.68542494923793",
            "principalPoint": [
                "400",
                "400"
            ],
            "distortionParams": [
                "0",
                "0",
                "0"
            ],
            "locked": "0"
        }
    ],
    "rigs": [
        {
            "rigId": "1107225601",
            "subPoses": [
                {
                    "status": "uninitialized",
                    "pose": {
                        "rotation": [
                            "1",
                            "0",
                            "0",
                            "0",
                            "1",
                            "0",
                            "0",
                            "0",
                            "1"
                        ],
                        "center": [
                            "0",
                            "0",
                            "0"
                        ]
                    }
                }
            ]
        }
    ]
```
**What do "rotation" and the "center" refer to? Do they refer to the center of the rig in respect to the ground?**

I know the exact distance between both cameras. **How can I provide the distance between the cameras to Meshroom?**

**Why is the StructureFromMotion node crashing?** I attach the log file of the SFM node below:

[log.log](https://github.com/alicevision/meshroom/files/5251406/log.log)

**Comment by Dave-van-der-Meer** [comment]
As additional information, the images are retrieved from a video with OpenCV and have no EXIF data. How important are EXIF data in this process?

**Comment by fabiencastan** [comment]
> it is important to have the following folder/file structure
> From what I understand, the first format above is correct and the second presented here is wrong. Do I understand this correctly?

Yes, for now it simply assumes that the filename is just a number. It would be a nice first contribution to use a regex to extract the number instead of the direct string to int conversion as it is done for now:
https://github.com/alicevision/AliceVision/blob/develop/src/software/pipeline/main_cameraInit.cpp#L439

> What do "rotation" and the "center" refer to? Do they refer to the center of the rig in respect to the ground?

Subposes refers to relative poses of the cameras in the rig to an arbitrary position (by default one of the input cameras).

> I know the exact distance between both cameras. How can I provide the distance between the cameras to Meshroom?

Do you also know the relative rotations?
If not, you could just use the known translation between the 2 cameras to rescale the scene at the end.

In your log it seems that only one of the 2 cameras are reconstructed. Is there some overlap between the 2 cameras?

**Comment by Dave-van-der-Meer** [comment]
Knowing that I am using the correct folder structure is already enough. My programming skills are rather mediocre to make a useful contribution in this regard. Maybe one day in the future :D

The cameras are in the exact same plane so there is no rotation, only a translation of 12 cm sidewards between each other.

Well, as all the images are retrieved from a video, all the images have plenty of overlap (both the image pairs as well as the consecutive images per camera). When I use the same dataset with the wrong folder/filename structure, the reconstruction works just fine.

**Comment by fabiencastan** [comment]
> The cameras are in the exact same plane so there is no rotation, only a translation of 12 cm sidewards between each other.

You shoud make a reconstruction with the rig and auto-calibration first. The precision required for the calibration should be very precise, so I would rely on the auto-calibration first.

Difficult to see what is the problem in your reconstruction with rig. Could you share one dataset privately or publicly?

**Comment by Dave-van-der-Meer** [comment]
I already wondered if I need to calibrate the rig somehow. I could not find how to do this in the documentation.
Which nodes do I need for this and how do I need to connect them?
Do I calibrate the rig in a different meshroom.mg file as the reconstruction or is this all done in one single flow?

I could share the dataset privately if this helps.

**Comment by Dave-van-der-Meer** [comment]
@fabiencastan do you have a possibility to send you the data set of images that I used privately, otherwise I might be able to make a link available for a limited amount of time here on the feed.

**Comment by fabiencastan** [comment]
You can send me a link to fabien.castan@mikrosimage.com
