### ISSUE TITLE
RuntimeError: CameraInit failed with error code 1.[question]

### ISSUE THREAD

**Issue by Phoenix-64** [alicevision/meshroom#1070]
I manually installed the newest version of meshroom. Now i get this error: 
RuntimeError: CameraInit failed with error code 1.
Command was: "aliceVision_cameraInit  --sensorDatabase "D:\Programme\meshroom_2020_09\AliceVision\src\aliceVision\sensorDB\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --viewIdMethod metadata --verboseLevel info --output "C:/Users/piosb/AppData/Local/Temp/tmppo1d2u9f/CameraInit/ac38bdd16b58bc6daeecdeacbfc7df059355110f/cameraInit.sfm" --allowSingleView 1 --input "C:\Users\piosb\AppData\Local\Temp\tmppo1d2u9f/CameraInit/ac38bdd16b58bc6daeecdeacbfc7df059355110f//viewpoints.sfm"".

Theese are my envoirmetn variables:
![grafik](https://user-images.githubusercontent.com/52720948/93834789-65f6b500-fc7d-11ea-9086-5d317eac943e.png)

And this is my file structure
[output.docx](https://github.com/alicevision/meshroom/files/5258756/output.docx)

I just followed the documentation:
https://github.com/alicevision/meshroom/blob/develop/INSTALL.md

**Comment by Phoenix-64** [comment]
![DSC00091](https://user-images.githubusercontent.com/52720948/93868651-0d4e0900-fccb-11ea-8a0f-ae467788c082.JPG)
![DSC00092](https://user-images.githubusercontent.com/52720948/93868654-0e7f3600-fccb-11ea-9e09-c870c80adf48.JPG)
![DSC00090](https://user-images.githubusercontent.com/52720948/93868658-1048f980-fccb-11ea-8f18-fa50e31bf3f7.JPG)
these are some of the images I tryed to import

**Comment by natowi** [comment]
Do you have the latest corresponding AliceVision release (dev build) installed?

**Comment by Phoenix-64** [comment]
I installed both on the same day so I suppose but if it is the dev build I am not sure about that I just followed the instructions. How can I check it?

**Comment by natowi** [comment]
What AliceVision binaries do you use? Do you use your own build? (just to make sure this issue is not related to missing AV or wrong version,...)

**Comment by Phoenix-64** [comment]
I just did what is in this guide:
https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md
Building the project using vcpkg
With the Cuda >= 10 version, I checked that Cuda is > 10.
And I seem to have gotten the Release 2.2.0

**Comment by natowi** [comment]
Ok, do you get the same error message with other images?

**Comment by Phoenix-64** [comment]
Should I first run the setup.py? I directly ran the sh file

**Comment by Phoenix-64** [comment]
When I start the start.sh I instantly get these error messages:
[2020-09-23 13:06:14,370][WARNING] == The following "submitters" plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

[2020-09-23 13:06:16,264][WARNING] Missing plugin qtAliceVision.
[2020-09-23 13:06:16,264][WARNING] Missing plugin qtOIIO.
[2020-09-23 13:06:18,237][WARNING] Retrying to obtain clipboard.

**Comment by natowi** [comment]
qtAliceVision and qtOIIO are missing or not found. You need the latest builds for those, too.

**Comment by Phoenix-64** [comment]
ah okay, how can I build them?

**Comment by Phoenix-64** [comment]
I give up... When des the next Build comes out?

**Comment by natowi** [comment]
Meshroom 2020 is 98% complete and should be released in a few weeks. https://github.com/alicevision/AliceVision/milestone/31 https://github.com/alicevision/meshroom/milestone/10

**Comment by Phoenix-64** [comment]
Perfect
