### ISSUE TITLE
[question] What's the best way to get the current 2020.x build ?

### ISSUE THREAD

**Issue by ChrisDean** [alicevision/meshroom#1071]
Release of 2020.1.0 seems to be very close looking at the milestone task list  and it has features I'd like to work with, but it's been this way for a number of months.

So, what is the best way of obtaining the current version of 2020 even if not 100% release ready?

On another thread some weeks ago I think someone mentioned there were nightly builds being generated somewhere but I can't find this now... is that the case?

Do I just need to clone the repo (and alicevision), check out develop and build everything from scratch?

If there are nightly (or otherwise regular) dev builds somewhere it would be great to give them a try.

Thanks

Chris

**Comment by natowi** [comment]
Yes, there are Snapshot builds for AliceVision and Meshroom https://github.com/alicevision/AliceVision/wiki/Windows-Snapshot-Builds but most of the features you are most likely waiting for require the updated qtAlicevision Plugin. You have to build it on your own (auto build process is not yet supported for the plugins). When using the Plugins  from a previous version some features will not work.

_Just a side note_: One reason why devbuilds or snapshots are not promoted is that most users can not solve issues related to them on their own. In the future the build / auto-build process will be improved, but at the moment you should know what you are doing.
Users working with devbuilds tend to open new issues that take time to address here that would be better spent in finalizing the release. For example answering questions regarding partially implemented features that are in the repository but are not yet finalized. Meshroom is being tested internally prior the release, so only official releases can be considered stable.

The next release should be available within a few weeks.

**Comment by ChrisDean** [comment]
Thanks @natowi I appreciate the side note and the comment on waiting :) but I have a requirement that is driving me to look at dev builds to achieve what I need to do. There's no intended implication that the release should be rushed, just an observation that the status has remained somewhat static with no obvious end in sight.

I'm actually on Linux and have experience building stuff and debugging to reasonably indepth level, but what I (REALLY) don't have on my side right now is time; so my reasoning is: If I can find (or worst case roll my own) a dev build with the features I need and avoid aspects that might break, that could be good enough to progress.

**Comment by natowi** [comment]
I can relate to your need to have a more recent release.

Building Meshroom is the easiest part. It is also possible to run Meshroom without compiling.
The hassle is building Alicevision with its libraries. For this reason I´d recommend you to start building Alicevision https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md#linux-compilation
Building on linux looks straight forward to me compared to the windows building process.
Don´t forget to build qtAlicevision and other required libraries.

**Comment by ChrisDean** [comment]
Thanks @natowi - have made a start on building for Alicevision for Linux. Initially running into a lot of library dependency issues on a default latest Ubuntu desktop install but am working through those as I write this. Closing question as I think this has to be the way forward for now. Thanks for the feedback :)
