### ISSUE TITLE
Is it possible to import a mesh and images, and generate textures for the mesh?

### ISSUE THREAD

**Issue by itisyeetimetoday** [alicevision/meshroom#1076]
Is it possible to import a mesh with no textures, and some images, and create texture files for that mesh? If so, could someone send  instruction or a screenshot on which nodes to use, and how to link them up to create the texture file?

**Comment by fabiencastan** [comment]
The only way would be to make a reconstruction with your input images (if you have enough of them), create a new mesh.
Then manually align the external mesh with the one generated from the images (btw, there is a [PR](https://github.com/alicevision/meshroom/pull/988) to help for that, but that's not ready). And then compute the Texturing node, using your external mesh as "Other Input Mesh" input.

**Comment by natowi** [comment]
@itisyeetimetoday This is something you can do in Meshlab https://www.youtube.com/watch?v=iLs5IIYE4F8

**Comment by itisyeetimetoday** [comment]
Thank you for your help. I will be closing the issue.
