### ISSUE TITLE
[question] convert .ply to .abc sfm format

### ISSUE THREAD

**Issue by mserouar** [alicevision/meshroom#1078]
HI !

Is there a way to come back to .abc ? 
In fact I converted the .abc file into .ply (with the node SFMConvert)  to clean some points in Python, but I would like to come back in Meshroom to end the task with some Meshing to have a full model (instead of just dense points cloud) in a .obj format.

Is there a way or should I use something like Meshlab or CloudCompare ?

**Comment by fabiencastan** [comment]
PLY is not able to store all the information of the sfmData, so there is no way to convert it back to sfmData.
You could export to ".SFM" if you want a json text file that you can easily parse.
