### ISSUE TITLE
Can I import .ply pointclouds and mesh/texture them in Meshroom?

### ISSUE THREAD

**Issue by jessekirbs** [alicevision/meshroom#1085]
Hello - I've captured a pointcloud using depth sensors and would like to know if it's possible to import these into Meshroom to utilize the meshing and texturing features.

 - OS: [Windows 10 64-bit ]
 - Python version [Python 3.7.6]
 - Qt/PySide version [?]
 - Meshroom version: [Release 2019.2.0]

Thanks!

**Comment by natowi** [comment]
No. Take a look at Meshlab https://www.youtube.com/watch?v=iLs5IIYE4F8

**Comment by jessekirbs** [comment]
Thanks, @natowi.

**Comment by TheNemo05** [comment]
but meshlab cannot create a 3d structure on its own. it will require stitching ? meshroom can create a 3d structure.
