### ISSUE TITLE
Has anyone configured Meshroom to work with Google Street View Data?

### ISSUE THREAD

**Issue by anon-14** [alicevision/meshroom#1086]
**Describe the problem**
I'm working around with trying to use google street view data to reconstruct simple 3d structures (I explicitly checked GMaps ToS and this is acceptable use with Maps, Google Earth is the one they dont want you to use for 3d renders) and I was wondering if someone has gotten this working and if so how they configured Meshroom. I tried taking the panoramas from several spots on google map and ran it through: 

`https://github.com/alicevision/AliceVision/blob/develop/src/software/utils/main_split360Images.cpp`

with 20 splits so that there would be a fair amount of overlap between images. I found that the 7 positions and 20 sub images was only leading to a thin line of points along the driven route being rendered. Each image is a 1200 x 1200 cut.

Since this type of problem only has a few perspective switches but covers a wide area is outside the capabilities of what meshroom can render? 

Note: I could go for cases where you wrap around more of the entire place however for any building not on a corner this luxury isnt available, GMaps will sometimes be completely different years, or other issues can arise so I was trying to do this along 1 drive path.

**Screenshots**

![image](https://user-images.githubusercontent.com/72489085/95297623-662bae80-0840-11eb-9485-a4fd45a0d1ea.png)

**Dataset**
Here are 3 (I could post more but was trying to follow the guideline of a "few" images) of the spherical images which you can process to get images with the command:
`.\aliceVision\bin\aliceVision_utils_split360Images.exe -i <imagename> -o <outputfolder> --equirectangularNbSplits 20
`                           
![Carlot 1](https://user-images.githubusercontent.com/72489085/95298869-6036cd00-0842-11eb-998f-1f9c76c06bee.jpg)
![Carlot2 1](https://user-images.githubusercontent.com/72489085/95298880-6331bd80-0842-11eb-9baa-2a8ec616efea.jpg)
![Carlot3 1](https://user-images.githubusercontent.com/72489085/95298875-62009080-0842-11eb-9ee5-c835ef700cec.jpg)

**Desktop (please complete the following and other pertinent information):**
 - OS:  win 10
 - Python 3.8
 - Meshroom 2019.2.0

**Comment by Darkar25** [comment]
it is technically possible to reconstruct a 3d scene from google street view panoramas(at least should be possible)...but i just can't get meshroom to work with these...maybe i dont have enough experience with meshroom or the GSW does not have enough images for meshroom...maybe some other software will do the trick...
