### ISSUE TITLE
Is it possible to use meshroom with 360 photos to scan a room? 

### ISSUE THREAD

**Issue by nafergo** [alicevision/meshroom#1089]
Is it possible to use meshroom with 360 photos (ricoh theta) to scan a room? like matterport does.
Any guidance for the workflow would be appreciated.

**Comment by fabiencastan** [comment]
Hi @nafergo 
You could take photos in dual-fisheye mode, using https://pluginstore.theta360.com/plugins/com.hirota41.dualfisheye_plugin
Split the dual fisheye in 2 fisheye images with the right metadata using the command line "aliceVision_split360Images" (there is no corresponding Meshroom node for now).
It has not been much tested, but it should work.
If it works fine, we could include it as a Meshroom node, so let us know how it goes!
