### ISSUE TITLE
[2020.1.0] VCRUNTIME140_1.dll not found

### ISSUE THREAD

**Issue by spono** [alicevision/meshroom#1090]
Hi,
I'm working on Windows 10 with the new 2020.1.0 version.

Drag&dropping pics, it returns an error with CameraInit saying that it "cannot find VCRUNTIME140_1.dll, try to reinstall".

![dll_not_found](https://user-images.githubusercontent.com/14940295/95676167-79ca7280-0bbc-11eb-98a4-a0e4669c47b7.png)
Closing the first warning, it throws a second one: "Probably you have corrupted image".

The same set of images works in 2019.2.0 with no issues at all. I checked in the folders and I found many "VCRUNTIME140.dll" but not the "_1". Is it a typo? or maybe the dll hasn't been shipped with the original package..?

**Comment by natowi** [comment]
If you don’t have it installed already, you need to install the Microsoft Visual C++ Redistributable Package 2015, 2017 and 2019 available on Microsoft’s Support portal: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads.

**Comment by simogasp** [comment]
@fabiencastan Maybe we can have a look at this
https://devblogs.microsoft.com/cppblog/how-to-redistribute-the-visual-c-libraries-with-your-application/
to see if we can embed it in the application

**Comment by fabiencastan** [comment]
A more recent article:
https://docs.microsoft.com/en-us/cpp/windows/determining-which-dlls-to-redistribute

**Comment by fabiencastan** [comment]
Does https://github.com/alicevision/meshroom/releases/tag/v2020.1.1 solves your issue?

**Comment by spono** [comment]
now it works, but in the meantime, as suggested by Natowi, I installed Microsoft Visual C++ Redistributable Package 2015, 2017 and 2019....so I don't really know if it's thanks to the installation or the new addition.
BTW thank you very much for the quick fix!
