### ISSUE TITLE
can't see load model button in meshroom 3d viewer

### ISSUE THREAD

**Issue by inspeckls** [alicevision/meshroom#1094]
This is my first try. I did every steps and the texture model was created (I can view obj model). But, I can't see "load model" button in the 3D viewer of Meshroom, so I couldn't load the model into 3D viewer. Did anyone have the same issue? Thanks.
![No Load Model button](https://user-images.githubusercontent.com/72777956/95811289-edfe3680-0ce0-11eb-80df-f8d7eb8ca97a.jpg)

**Comment by natowi** [comment]
Double click on the Texturing node to load the model

**Comment by inspeckls** [comment]
Thank you very much, Simon. I did it and the model is loaded. By the way, I still don't see the buttons for SfM, Mesh, Grid, Locator and Load Model in 3D viewer window. Is it a setting issue? Maybe, I just didn't look hard enough. Li

**Comment by eltonhcchan** [comment]
@natowi , thx for your hint. I've encountered the same problem that the so called "Load Model" button did not show up after all the process complete.

**Comment by natowi** [comment]
Yes, the button is known to be unreliable. But double clicking on the nodes or dragging the file from a folder into the viewer works reliable.

**Comment by natowi** [comment]
@inspeckls can you share a full screenshot of Meshroom with the missing 3Dviewer elements?
Do you use the latest binaries? Are there any error messages in the cli?

For the missing Load Model button I´ve created a bug report.

**Comment by inspeckls** [comment]
@natowi , as requested, here is a full screenshot.
![Meshroom screen capture](https://user-images.githubusercontent.com/72777956/97457606-499b0780-1910-11eb-9fb2-4b7761906545.jpg)
This is the version I used. I didn't see any error message unless I didn't look at the right place.
![Meshroom screen capture2](https://user-images.githubusercontent.com/72777956/97458032-adbdcb80-1910-11eb-9a82-e9ca3e7a1a1a.jpg)

**Comment by inspeckls** [comment]
@natowi ,in fact, I also tried to use Blender, when I clicked on mouse or key on keyboard, it supposed to show what I clicked at left bottom of 3D viewer screen. I couldn't see these displays either. Is it a setting problem of my laptop?

**Comment by natowi** [comment]
> I still don't see the buttons for SfM, Mesh, Grid, Locator and Load Model in 3D viewer window

Everything looks normal. The Buttons are right under the "Display" Text in the 3D viewer in the upper right corner of the window.

**Comment by inspeckls** [comment]
@natowi , Thanks. But I mean these buttons (circled in following image) appeared in some demo videos.

![Untitled](https://user-images.githubusercontent.com/72777956/97470349-d00a1600-191d-11eb-84e8-dcecad9b6018.jpg)

**Comment by natowi** [comment]
Yes, but the video shows the older 2019 version. The 2020 version has some GUI design changes.

**Comment by DSLituiev** [comment]
I'm running version 2020.1.0 and still missing the "Load model", "fsm" and other buttons

![Screenshot from 2020-12-23 23-33-50](https://user-images.githubusercontent.com/8426290/103070931-76b61000-4577-11eb-91c0-c8d752ee0997.png)

**Comment by VR-Architect** [comment]
Me too on 2020.1.1 Windows 10

**Comment by natowi** [comment]
The load mesh button is no longer needed. Just double click on the meshing or texturing node to load the model

**Comment by markuskruse** [comment]
> The load mesh button is no longer needed. Just double click on the meshing or texturing node to load the model

Wrong, it is needed so people know how to load the mesh. There is no hint, in the gui, that double-clicking a node does something.

**Comment by dschiller** [comment]
Then someone should update the documentation at https://meshroom-manual.readthedocs.io/en/latest/tutorials/sketchfab/sketchfab.html#step-3-basic-workflow
