### ISSUE TITLE
Is the Image Masking Node Included in 2020.1?

### ISSUE THREAD

**Issue by ChrisDean** [alicevision/meshroom#1097]
In PR #641 @fabiencastan comments that PR #708 (Image masking Node) has been integrated and will be part of the next release.

I don't see this node in the downloadable linux build or mentioned in the docs.

Should this be there? Not sure if the feature's been bumped out of the release on purpose or missed or if there's something I need to do to activate it?

**Comment by fabiencastan** [comment]
No, it is not yet integrated in 2020.1.
It has been integrated with another PR but is not yet ready.

**Comment by ChrisDean** [comment]
Ah no problem - thanks for the feedback 👍

**Comment by andytany** [comment]
Can this node be used in version 2020.1?

**Comment by natowi** [comment]
@andytany you can use the python version of the masking plugin as described here https://github.com/alicevision/meshroom/pull/641

Building AliceVision with the PR that includes this feature is possible, but I would advice against it, unless you feel confident in building software from source and dealing with issues related to that.

 The next release will probably be in February[*](https://github.com/alicevision/meshroom/issues/1216#issuecomment-760587684).

**Comment by andytany** [comment]
Hello， Simon!
      I want to write some functions for the gui of meshroom, can I submit
it?

Simon <notifications@github.com> 于2021年2月12日周五 上午10:39写道：

**Comment by fabiencastan** [comment]
It will not be part of the next release as those developments are linked to major code refactoring in the depth map step which is not ready to be included in 2021.1.0.

**Comment by andytany** [comment]
I used another method, which is to apply a mask to the image before sift
sampling, rendering a transparent png sequence (in other software), I found
this method is very effective. Can reduce the interference of the scene.
You can try to add a mask drawing tool in front of the sampling node. This
method is simpler than exporting the mask and applying it to the depth map.

Fabien Castan <notifications@github.com> 于2021年2月26日周五 上午9:48写道：

**Comment by minch-dev** [comment]
> Building AliceVision with the PR that includes this feature is possible, but I would advice against it, unless you feel confident in building software from source and dealing with issues related to that.
I'm okay with building from source, but where is it?  `WIP Masking interface #750` merge was rejected and deleted from author's repo (i suppose), most branches related to masking seem to be gone. Any directions?

**Comment by minch-dev** [comment]
> I used another method, which is to apply a mask to the image before sift sampling
Isn't it supposed to work exactly like that to begin with? I mean applying a mask to original images first and only then processing them. Why would you waste computational power extracting features from background noise if it can be avoided? And then waste it again applying the masks to depth maps; it kinda doesn't make too much sense.

**Comment by natowi** [comment]
https://github.com/alicevision/Meshroom/wiki/New-Features-in-Meshroom-2023.1#1-image-masking
