### ISSUE TITLE
[question] What's the reason for the bumpy result

### ISSUE THREAD

**Issue by xzhub** [alicevision/meshroom#1098]
Here is one of the pictures of the wall
![IMG_7958](https://user-images.githubusercontent.com/3990687/95945657-8a2d5800-0e1d-11eb-949a-151e1ea22a86.PNG)
It is bumpy, and the result is bumpy too, which is good, it's accurate:
![image](https://user-images.githubusercontent.com/3990687/95945709-a630f980-0e1d-11eb-91a6-629e19dc2937.png)

Here is one of the pictures of skin
![IMG_7959](https://user-images.githubusercontent.com/3990687/95945749-bcd75080-0e1d-11eb-8bac-cc64c129c2f2.PNG)
It's smooth. However, the result is bumpy, which is not good. 
![image](https://user-images.githubusercontent.com/3990687/95945797-d7112e80-0e1d-11eb-95d5-3db9526d94ad.png)

Could anyone point out the possible reason? Is it because the skin texture is too small for my phone camera to capture it? I've already tried to take close up images as I can.

usually, what's the major reason for the bumpy result? (From the algorithm point of view.)
1. object movement
2. picture resolution is too low
3. picture is blur (out of focus)
4. overlap between pictures is not high enough(less than 60%)
5. other?

**Comment by natowi** [comment]
The reason could be the (white) light reflections on the skin. You could smooth the reconstruction.

**Comment by fabiencastan** [comment]
> object movement

Yes, that's an issue in your skin example

> picture resolution is too low

Yes

> picture is blur (out of focus)

Yes, that's an issue in your skin example

> overlap between pictures is not high enough(less than 60%)

The question is not really in term of overlap as in panorama. Here it's more about angles between the surface and the 2 best cameras observing it, and of course, overall density of the acquisition.

> other?

Non-lambertian surface is problematic (as @natowi said)
Weakly textured surfaces is problematic

**Comment by xzhub** [comment]
@natowi @fabiencastan Thank you for the input. As @natowi suggested, I tried the denosizing node. Most of the time it worked well, I have to increase the lamda a bit to get a better result for skin. 
in rare cases, the node failed with log like this. If any of you have any clue what is the cause and what parameters should I modify, please kindly let me know.

```
Program called with the following parameters:
 * denoisingIterations = 5
 * eta = 1.5
 * input = "/tmp/workdir/pipeline_dir/MeshroomCache/MeshFiltering/7226b4f0b4ba0d1adea47dc38e0e8906cea011fb/mesh.obj"
 * lambda = 0.6
 * meshUpdateClosenessWeight = 0.001
 * meshUpdateMethod = 0
 * mu = 1.5
 * nu = 0.3
 * output = "/tmp/workdir/pipeline_dir/MeshroomCache/MeshDenoising/1d063baa86136d713c48938c06cc39aa631968af/mesh.obj"
 * verboseLevel = "info"


====== Filter parameters =========
Lambda: 0.6
Eta:1.5
Mu:1.5
Nu:0.3
Mesh denoising outer iterations: 5
==================================

[21:35:39.488424][info] Mesh file: "/tmp/workdir/pipeline_dir/MeshroomCache/MeshFiltering/7226b4f0b4ba0d1adea47dc38e0e8906cea011fb/mesh.obj" loaded.
[21:35:39.488556][info] Input mesh: 134358 vertices and 268062 facets.
[21:35:39.488572][info] Mesh normalization.
[21:35:39.501465][info] Start mesh denoising.
Denoising started
Outer iteration 1...
Preprocessing......
Filtering......
Solver converged after 9 iterations
Starting iterative mesh update......
Outer iteration 2...
Preprocessing......
Unable to get neighborhood information, no filtering done...
Error: unable to initialize filter
Error in performing SD filter
Unable to perform normal filter. Denoising aborted.
[21:36:01.103159][info] Mesh denoising done.
[21:36:01.135088][info] Output mesh: 134358 vertices and 268062 facets.
[21:36:01.135142][info] Save mesh.
[OBJWriter] : write file
[21:36:01.433123][info] Mesh file: "/tmp/workdir/pipeline_dir/MeshroomCache/MeshDenoising/1d063baa86136d713c48938c06cc39aa631968af/mesh.obj" saved.
[21:36:01.433157][info] Task done in (s): 23.139000
```
