### ISSUE TITLE
[bug] 3D Viewer Trackball frozen

### ISSUE THREAD

**Issue by natowi** [alicevision/meshroom#1101]
**Describe the bug**
Double clicking to set the centre point for the trackball in the 3D Viewer does not work.
The trackball gets brighter with a click, but does not re-centre.
It is possible to rotate the model, but the Trackball stays at the origin.

**Desktop (please complete the following and other pertinent information):**
 - OS: Win. 10
 - Meshroom version: 2020.1.1

**Additional context**
Meshroom crashed a session before. The new start took unusually long and the cli window was empty during the startup.
Maybe there was an issue while loading the 3D viewer components.

**Comment by ChemicalXandco** [comment]
I noticed this too, shift+drag still works though.

**Comment by natowi** [comment]
I have a hunch that the unexpected crashes mentioned in other issues are linked to a qt problem and the 3D viewer...

**Comment by natowi** [comment]
Still an issue in the 2021.1.0 release
