### ISSUE TITLE
Use SLAM output for Dense reconstruction

### ISSUE THREAD

**Issue by Sachet12345** [alicevision/meshroom#1103]
Hi, I am new to this field and I was wondering if its possible to use sparse SLAM outputs such as orbslam3 and get a dense pointcloud using meshroom?

I would be thankful if anyone could provide me any resources or reading material.

**Comment by natowi** [comment]
I think you can convert your camera poses to the Meshroom format. This is experimental and not officially supported: https://github.com/alicevision/meshroom/wiki/Using-known-camera-positions

Best use the original images if available to do the complete photogrammetry pipeline in Meshroom. The only benefit of SLAM I can see at the moment is speed. Using Meshroom to compute the depthmap (required for the dense point cloud) takes time, so you can use the full Meshroom pipeline to begin with.

**Comment by nikste** [comment]
only getting into this deeper now as well, it seems though, if i want to produce a dense point cloud from some car mounted camera video footage, then slam can provide some stuff like loop closure, which meshroom does not, right?

**Comment by LukasPoque** [comment]
@nikste I agree with you. Loopclusure and additional information like IMU data could be really beneficial for places where normal photogrammetry struggles. 
Any updates on this? So maybe someone has an idea of how to fuse the information inside Mesroom?
