### ISSUE TITLE
problem on Azure VM

### ISSUE THREAD

**Issue by bistek** [alicevision/meshroom#1108]
Hello, and thanks for this very interesting and useful project!

I am trying to run Meshroom on an Azure VM with Windows 10 64 bit, Nvidia Tesla GPU, 12 core processor, and 56 GB RAM.

I have copied the unzipped Meshroom folder in C:\ and I am able to run Meshroom.

This message comes out in the terminal immediately at startup:

```
WARNING:root:Missing plugin qtAliceVision.
WARNING:root:Missing plugin qtOIIO.
WARNING:root:glPointSize() and GL_PROGRAM_POINT_SIZE are not supported by ES 2.0
```

However when I try to import a set of photos with drag and drop I got three error messages:

1) "The code execution cannot proceed because MFPlat.DLL was not found. Reinstalling the program may fix this problem."

2) "The code execution cannot proceed because MF.DLL was not found. Reinstalling the program may fix this problem."

3) "The code execution cannot proceed because MFPReadWrite.DLL was not found. Reinstalling the program may fix this problem."

After I press OK on all three, another message comes out saying:

4) "You probably have a corrupted image within the images that you are trying t import".

This is strange since they are all standard jpg images.

After all this, in the terminal I got:

```
ERROR:root:Error while building intrinsics: CameraInit failed with error code 3221225781.
Command was: "aliceVision_cameraInit  --sensorDatabase "C:\Meshroom-2020.1.1-win64\Meshroom-2020.1.1\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --viewIdMethod metadata --verboseLevel info --output "C:/Users/user/AppData/Local/Temp/tmph_aezwzx/CameraInit/ac38bdd16b58bc6daeecdeacbfc7df059355110f/cameraInit.sfm" --allowSingleView 1 --input "C:\Users\user\AppData\Local\Temp\tmph_aezwzx/CameraInit/ac38bdd16b58bc6daeecdeacbfc7df059355110f//viewpoints.sfm"".

WARNING:root:QQmlComponent: Created graphical object was not placed in the graphics scene.
```

I have tried to reinstall as suggested but with no success. Could you please suggest a solution?

Thanks very much!

**Comment by bistek** [comment]
Could this be related to missing Microsoft Visual C++ Redistributable Package 2015, 2017 and 2019?

**Comment by natowi** [comment]
The Microsoft Visual C++ Redistributable Packages should be installed as well as the latest Nvidia drivers for Cuda support.
Your Meshroom folder should look like this: https://meshroom-manual.readthedocs.io/en/latest/_images/win.jpg (minus the garatest folder)

**Comment by bistek** [comment]
Hello, and thanks for the prompt answer.

Visual C++ and CUDA seem to be OK:

![image](https://user-images.githubusercontent.com/12087912/96857374-33e49880-145f-11eb-8685-d007755158d7.png)

The Meshroom directory is like this:

![image](https://user-images.githubusercontent.com/12087912/96857564-67272780-145f-11eb-8b7a-4d827de0ef02.png)

It is just the archive I downloaded, unzipped directly in the C: disk root.

Maybe I should place it somewhere else?

Or is it something with the configuration of Azure virtual machines?

Thanks very much!

**Comment by natowi** [comment]
If possible try another path or better directory.

**Comment by bistek** [comment]
Do you suggest to put it in a "User" directory or in "Program Files"? The VM is shared between different people so if we use user directories we will be forced to install one version for each user.

In any case, if you have a working solution I will replicate it.

Thanks very much!

**Comment by natowi** [comment]
Program Files should suffice.

**Comment by bistek** [comment]
Hello, I have tried both in Program Files and on a directory on the Desktop (so within Users) and I always get the same error.

Thanks!

**Comment by bistek** [comment]
Hello, I have tried some different options, but nothing... no way to run Meshroom on this Azure VM, that is supposed to be very good with 12 cores and a Tesla GPU. I tried also placing the meshroom directory directly on the desktop, but it is still the same.

I have also noticed that when I run Meshroom, I immediately get a message in the terminal saying:

```
WARNING:root:Missing plugin qtAliceVision.
WARNING:root:Missing plugin qtOIIO.
WARNING:root:glPointSize() and GL_PROGRAM_POINT_SIZE are not supported by ES 2.0
```

Then when I try to import photos it goes as said above, with this error in the terminal:

```
ERROR:root:Error while building intrinsics: CameraInit failed with error code 3221225781.
Command was: "aliceVision_cameraInit  --sensorDatabase "C:\Users\buser\Desktop\Meshroom-2020.1.1\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --viewIdMethod metadata --verboseLevel info --output "C:/Users/buser/AppData/Local/Temp/tmpw179uuy5/CameraInit/ac38bdd16b58bc6daeecdeacbfc7df059355110f/cameraInit.sfm" --allowSingleView 1 --input "C:\Users\buser\AppData\Local\Temp\tmpw179uuy5/CameraInit/ac38bdd16b58bc6daeecdeacbfc7df059355110f//viewpoints.sfm"".
```

Please help, thanks very much!

**Comment by natowi** [comment]
Can you test this with the 2019.2 version / the [monstree ](https://github.com/alicevision/dataset_monstree)dataset? 

I found a similar error message here https://github.com/alicevision/meshroom/issues/447 You could try to force to run Meshroom on the GPU.

> GL_PROGRAM_POINT_SIZE are not supported by ES 2.0

"OpenGL for Embedded Systems -> OpenGL ES"

So from what I understand you don´t have access to OpenGL / OpenGL not installed and/or Meshroom does not run on the GPU.

+ https://stackoverflow.com/questions/48433641/does-azure-allow-app-need-opengl-any-way-to-go-around

Maybe some frameworks are not supported on some VMs? https://docs.microsoft.com/en-us/answers/questions/131575/where-are-the-gpu-vm39s.html

**Comment by bistek** [comment]
Hello, this sounds a bit strange. I have a Tesla with up-to-date drivers, Cuda, etc., and I am able to run other OpenGL and CUDA applications. I will try the 2019 release.

In any case, it does not find the AliceVision and qtOIIO plugins. Maybe this is a PATH problem?

Thanks!

**Comment by natowi** [comment]
Just guessing here.
You could try to run Meshroom from the cli to see if it works. https://github.com/alicevision/AliceVision/wiki/CLI-Parameters. If it does work, we could try to set the PATH to the GUI plugins (but with the binary release normally this should not be necessary).

**Comment by bistek** [comment]
Hello, I just tried running from the command line. On my laptop it works, but on the Azure VM it still results in the same error, but with some more message in the terminal. Maybe it tells something:

```
C:\Users\buser\Desktop\Meshroom-2020.1.1>Meshroom.exe -I C:\Users\buser\Desktop\foto_equalizzate
ERROR:root:Error while building intrinsics: CameraInit failed with error code 3221225781.
Command was: "aliceVision_cameraInit  --sensorDatabase "C:\Users\buser\Desktop\Meshroom-2020.1.1\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --viewIdMethod metadata --verboseLevel info --output "C:/Users/buser/AppData/Local/Temp/tmpyyodazpq/CameraInit/ac38bdd16b58bc6daeecdeacbfc7df059355110f/cameraInit.sfm" --allowSingleView 1 --input "C:\Users\buser\AppData\Local\Temp\tmpyyodazpq/CameraInit/ac38bdd16b58bc6daeecdeacbfc7df059355110f//viewpoints.sfm"".

Traceback (most recent call last):
  File "d:\release\BUILD\meshroom\venv\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "d:\release\BUILD\meshroom\venv\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "meshroom/ui/__main__.py", line 11, in <module>
  File "d:\release\BUILD\meshroom\meshroom\ui\app.py", line 156, in __init__
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 804, in importImagesFromFolder
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 873, in buildIntrinsics
  File "d:\release\BUILD\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 269, in buildIntrinsics
RuntimeError: CameraInit failed with error code 3221225781.
Command was: "aliceVision_cameraInit  --sensorDatabase "C:\Users\buser\Desktop\Meshroom-2020.1.1\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --viewIdMethod metadata --verboseLevel info --output "C:/Users/buser/AppData/Local/Temp/tmpyyodazpq/CameraInit/ac38bdd16b58bc6daeecdeacbfc7df059355110f/cameraInit.sfm" --allowSingleView 1 --input "C:\Users\buser\AppData\Local\Temp\tmpyyodazpq/CameraInit/ac38bdd16b58bc6daeecdeacbfc7df059355110f//viewpoints.sfm"".

```

**Comment by natowi** [comment]
That is strange,but I have seen this before. "d:\release\BUILD\" is the directory where the binaries were compiled to. (previously "C:\Users\DEV\AppData\" https://github.com/alicevision/meshroom/issues/852 ) This error occurred when running Meshroom from within the zip file without extracting. Since Windows handles zip files like folders one can accidentally forget to unzip them https://github.com/alicevision/meshroom/issues/600. 
Try reinstalling [Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) as it solved this issue here https://github.com/alicevision/meshroom/issues/840.

If nothing works, try the following:

- Download the Meshroom [Source](https://github.com/alicevision/meshroom/archive/v2020.1.1.zip)
- Unzip the archive and copy the _aliceVision_ and _qtPlugins_ folders from the binary release folder into the new Meshroom folder.

- python 3.6 is recommended
- install requirements: (cli-> navigate in meshroom-develop folder) ´´pip install -r requirements.txt´´

Create a new .bat file within the Meshroom folder with:
```
set MESHROOM_INSTALL_DIR=%CD%
set PYTHONPATH=%CD% && python meshroom/ui
```
Now you should be able to run Meshroom by executing the batch file.

**Comment by bistek** [comment]
Thanks! Maybe I better make a new Azure VM instance, completely dedicated to Meshroom? In this case, would you recommend Windows or Linux?

**Comment by natowi** [comment]
Sorry, I don´t have experience with Azure. You need to test and find out what works best for you.
Did the last recommendation work?

**Comment by bistek** [comment]
Hello, I'm starting to think that the problem is not Azure in general, but the VM that I am using, where also other stuff is already installed. So one option could be to create a new VM, optimised for Meshroom (not a problem since we turn them on and off on demand).

In this case, would you suggest Windows or Linux (e.g. Ubuntu), or it is the same?

And what else should I install in the two cases?

On Ubuntu I will have Python 3.x pre-installed and I guess I just need to add CUDA.

On Windows I shall install Anaconda, CUDA and Visual Studio 2015, 2017 and 2019.

Something else?

Thanks very much!

**Comment by natowi** [comment]
Windows is the easiest to set up. Only Cuda and VS 2015/17/19 are required. Meshroom works well on linux too, but cuda can be difficult to install depending on the distribution.

**Comment by natowi** [comment]
You could try to install the windows media feature pack as suggested here https://github.com/alicevision/meshroom/issues/1122#issuecomment-717713395 Windows N version does not contain Windows Media Feature Pack by default, which causes the dll errors.

**Comment by bistek** [comment]
Thanks very much! We will try and let you know. The error reported on #1122 seems exactly the same.

**Comment by natowi** [comment]
@bistek Did it work now?

**Comment by bistek** [comment]
Hello, just to let you know. I installed a clean instance with Windows 10 Enterprise (not the N version but the standard one), added Microsoft Visual C++ Redistributable Package 2015, 2017 and 2019, and now Meshroom-2020.1.1 works very well.

Thanks!
