### ISSUE TITLE
 MeshRoom failure at DepthMap

### ISSUE THREAD

**Issue by sescomtl** [alicevision/meshroom#1110]
Hi, I'm trying to 3D scan a rather complex part to save myself the hassle of CADing, but keep encountering a failure when I get to DepthMap. I have attached everything from the step at which it fails to what I assume to be the error.

Any help I can get with this would be hugely appreciated. Thank you in advance!

[7/11](1/95) DepthMap
 - commandLine: aliceVision_depthMapEstimation  --input "C:/Users/jarred/Desktop/Mask/Visor and Silicon/MeshroomCache/StructureFromMotion/5477af6a2a98eb78fee56a9fb1a3a5e358247f4f/sfm.abc" --imagesFolder "C:/Users/jarred/Desktop/Mask/Visor and Silicon/MeshroomCache/PrepareDenseScene/fabf89b9567b232f932bf2a1feee253a019d9676" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output "C:/Users/jarred/Desktop/Mask/Visor and Silicon/MeshroomCache/DepthMap/075401ca104999c8af13daf757fdb6c64c7fb172" --rangeStart 0 --rangeSize 3
 - logFile: C:/Users/jarred/Desktop/Mask/Visor and Silicon/MeshroomCache/DepthMap/075401ca104999c8af13daf757fdb6c64c7fb172/0.log
 - elapsed time: 0:02:10.111207
ERROR:root:Error on node computation: Error on node "DepthMap_1(0)":
Log:
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "C:/Users/jarred/Desktop/Mask/Visor and Silicon/MeshroomCache/PrepareDenseScene/fabf89b9567b232f932bf2a1feee253a019d9676"
 * input = "C:/Users/jarred/Desktop/Mask/Visor and Silicon/MeshroomCache/StructureFromMotion/5477af6a2a98eb78fee56a9fb1a3a5e358247f4f/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/Users/jarred/Desktop/Mask/Visor and Silicon/MeshroomCache/DepthMap/075401ca104999c8af13daf757fdb6c64c7fb172"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[19:04:10.006621][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce GTX 960M
        - compute capability:      5.0
        - total device memory:     2048 MB
        - device memory available: 1678 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   2048
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {65536,65536}
        - max 3D array texture:    {4096,4096,4096}
        - max 2D linear texture:   {65536,65536,1048544}
        - max 2D layered texture:  {16384,16384,2048}
        - number of SM(x)s:        5
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte
[19:04:10.391926][info] Supported CUDA-Enabled GPU detected.
[19:04:14.246557][info] Found 1 image dimension(s):
[19:04:14.247558][info]         - [4032x1908]
[19:04:15.042274][info] Overall maximum dimension: [4032x1908]
[19:04:15.042274][info] Create depth maps.
number of CUDA devices: 1
   0: GeForce GTX 960M
[19:04:15.043272][info] # GPU devices: 1, # CPU threads: 8
[19:04:15.043272][info] Plane sweeping parameters:
        - scale: 2
        - step: 3
[19:04:15.043272][info] PlaneSweepingCuda:
        - _nImgsInGPUAtTime: 2
        - scales: 2
        - subPixel: Yes
        - varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 369.634369, free: 1678.365601, total: 2048.000000
Device 0 memory - used: 444.509369, free: 1603.490601, total: 2048.000000
[19:04:15.058230][info] Found only 1/10 nearest cameras for view id: 996279
[19:04:15.063283][info] Found only 1/6 nearest cameras for view id: 996279
[19:04:16.087270][info] Estimate depth map, view id: 996279
Device 0 memory - used: 466.571869, free: 1581.428101, total: 2048.000000
total size of volume map in GPU memory: 22.048828
nDepths 284, nDepthsToSearch 284
ps_computeSimilarityVolume elapsed time: 5.000000 ms
ps_SGMoptimizeSimVolume
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
SGM volume gpu elapsed time: 204.000000 ms
ps_SGMoptimizeSimVolume done
[19:04:18.400922][info] Refine depth map, view id: 996279
gpu elapsed time: 355.000000 ms
gpu elapsed time: 344.000000 ms
gpu elapsed time: 340.000000 ms
gpu elapsed time: 344.000000 ms
gpu elapsed time: 111.000000 ms
gpu elapsed time: 106.000000 ms
gpu elapsed time: 111.000000 ms
gpu elapsed time: 114.000000 ms
rc: 0, gpu elapsed time: 207.000000 ms
rc: 0, gpu elapsed time: 210.000000 ms
rc: 0, gpu elapsed time: 215.000000 ms
rc: 0, gpu elapsed time: 212.000000 ms
[19:04:32.367952][info] Estimate depth map, view id: 7879080
Device 0 memory - used: 485.946869, free: 1562.053101, total: 2048.000000
total size of volume map in GPU memory: 41.380371
nDepths 533, nDepthsToSearch 533
ps_computeSimilarityVolume elapsed time: 7.000000 ms
Device 0 memory - used: 489.009369, free: 1558.990601, total: 2048.000000
total size of volume map in GPU memory: 44.485840
nDepths 573, nDepthsToSearch 573
ps_computeSimilarityVolume elapsed time: 8.000000 ms
Device 0 memory - used: 489.009369, free: 1558.990601, total: 2048.000000
total size of volume map in GPU memory: 44.485840
nDepths 573, nDepthsToSearch 573
ps_computeSimilarityVolume elapsed time: 7.000000 ms
Device 0 memory - used: 489.009369, free: 1558.990601, total: 2048.000000
total size of volume map in GPU memory: 44.485840
nDepths 573, nDepthsToSearch 573
ps_computeSimilarityVolume elapsed time: 9.000000 ms
Device 0 memory - used: 481.321869, free: 1566.678101, total: 2048.000000
total size of volume map in GPU memory: 36.799805
nDepths 474, nDepthsToSearch 474
ps_computeSimilarityVolume elapsed time: 8.000000 ms
Device 0 memory - used: 489.009369, free: 1558.990601, total: 2048.000000
total size of volume map in GPU memory: 44.485840
nDepths 573, nDepthsToSearch 573
ps_computeSimilarityVolume elapsed time: 9.000000 ms
Device 0 memory - used: 475.134369, free: 1572.865601, total: 2048.000000
total size of volume map in GPU memory: 30.588867
nDepths 394, nDepthsToSearch 394
ps_computeSimilarityVolume elapsed time: 7.000000 ms
Device 0 memory - used: 478.321869, free: 1569.678101, total: 2048.000000
total size of volume map in GPU memory: 33.771973
nDepths 435, nDepthsToSearch 435
ps_computeSimilarityVolume elapsed time: 8.000000 ms
Device 0 memory - used: 466.259369, free: 1581.740601, total: 2048.000000
total size of volume map in GPU memory: 21.738281
nDepths 280, nDepthsToSearch 280
ps_computeSimilarityVolume elapsed time: 6.000000 ms
Device 0 memory - used: 481.321869, free: 1566.678101, total: 2048.000000
total size of volume map in GPU memory: 36.799805
nDepths 474, nDepthsToSearch 474
ps_computeSimilarityVolume elapsed time: 9.000000 ms
ps_SGMoptimizeSimVolume
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
SGM volume gpu elapsed time: 970.000000 ms
ps_SGMoptimizeSimVolume done
[19:05:03.680619][info] Refine depth map, view id: 7879080
gpu elapsed time: 1686.000000 ms
gpu elapsed time: 1654.000000 ms
gpu elapsed time: 1688.000000 ms
gpu elapsed time: 1756.000000 ms
gpu elapsed time: 1632.000000 ms
gpu elapsed time: 1674.000000 ms
gpu elapsed time: 1692.000000 ms
gpu elapsed time: 1783.000000 ms
gpu elapsed time: 1380.000000 ms
gpu elapsed time: 1595.000000 ms
gpu elapsed time: 1691.000000 ms
gpu elapsed time: 1767.000000 ms
gpu elapsed time: 1162.000000 ms
gpu elapsed time: 1473.000000 ms
gpu elapsed time: 1462.000000 ms
gpu elapsed time: 1305.000000 ms
gpu elapsed time: 1721.000000 ms
gpu elapsed time: 1695.000000 ms
gpu elapsed time: 1710.000000 ms
gpu elapsed time: 1776.000000 ms
gpu elapsed time: 1329.000000 ms
gpu elapsed time: 1479.000000 ms
gpu elapsed time: 1674.000000 ms
gpu elapsed time: 1762.000000 ms
gpu elapsed time: 1182.000000 ms
gpu elapsed time: 1184.000000 ms
gpu elapsed time: 1188.000000 ms
gpu elapsed time: 1206.000000 ms
rc: 1, gpu elapsed time: 519.000000 ms
rc: 1, gpu elapsed time: 525.000000 ms
rc: 1, gpu elapsed time: 526.000000 ms
rc: 1, gpu elapsed time: 514.000000 ms
[19:06:02.624156][info] Estimate depth map, view id: 13202978

WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(11)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(12)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(13)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(14)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(15)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(16)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(17)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(18)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(19)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(20)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(21)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(22)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(23)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(24)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(25)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(26)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(27)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(28)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(29)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(30)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(31)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(32)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(33)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(34)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(35)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(36)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(37)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(38)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(39)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(40)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(41)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(42)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(43)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(44)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(45)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(46)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(47)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(48)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(49)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(50)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(51)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(52)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(53)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(54)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(55)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(56)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(57)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(58)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(59)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(60)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(61)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(62)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(63)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(64)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(65)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(66)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(67)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(68)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(69)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(70)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(71)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(72)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(73)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(74)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(75)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(76)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(77)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(78)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(79)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(80)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(81)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(82)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(83)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(84)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(85)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(86)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(87)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(88)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(89)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(90)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(91)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(92)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(93)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(94)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(11)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(12)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(13)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(14)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(15)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(16)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(17)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(18)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(19)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(20)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(21)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(22)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(23)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(24)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(25)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(26)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(27)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(28)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "DepthMap_1(0)":
Log:
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "C:/Users/jarred/Desktop/Mask/Visor and Silicon/MeshroomCache/PrepareDenseScene/fabf89b9567b232f932bf2a1feee253a019d9676"
 * input = "C:/Users/jarred/Desktop/Mask/Visor and Silicon/MeshroomCache/StructureFromMotion/5477af6a2a98eb78fee56a9fb1a3a5e358247f4f/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/Users/jarred/Desktop/Mask/Visor and Silicon/MeshroomCache/DepthMap/075401ca104999c8af13daf757fdb6c64c7fb172"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[19:04:10.006621][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce GTX 960M
        - compute capability:      5.0
        - total device memory:     2048 MB
        - device memory available: 1678 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   2048
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {65536,65536}
        - max 3D array texture:    {4096,4096,4096}
        - max 2D linear texture:   {65536,65536,1048544}
        - max 2D layered texture:  {16384,16384,2048}
        - number of SM(x)s:        5
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte
[19:04:10.391926][info] Supported CUDA-Enabled GPU detected.
[19:04:14.246557][info] Found 1 image dimension(s):
[19:04:14.247558][info]         - [4032x1908]
[19:04:15.042274][info] Overall maximum dimension: [4032x1908]
[19:04:15.042274][info] Create depth maps.
number of CUDA devices: 1
   0: GeForce GTX 960M
[19:04:15.043272][info] # GPU devices: 1, # CPU threads: 8
[19:04:15.043272][info] Plane sweeping parameters:
        - scale: 2
        - step: 3
[19:04:15.043272][info] PlaneSweepingCuda:
        - _nImgsInGPUAtTime: 2
        - scales: 2
        - subPixel: Yes
        - varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 369.634369, free: 1678.365601, total: 2048.000000
Device 0 memory - used: 444.509369, free: 1603.490601, total: 2048.000000
[19:04:15.058230][info] Found only 1/10 nearest cameras for view id: 996279
[19:04:15.063283][info] Found only 1/6 nearest cameras for view id: 996279
[19:04:16.087270][info] Estimate depth map, view id: 996279
Device 0 memory - used: 466.571869, free: 1581.428101, total: 2048.000000
total size of volume map in GPU memory: 22.048828
nDepths 284, nDepthsToSearch 284
ps_computeSimilarityVolume elapsed time: 5.000000 ms
ps_SGMoptimizeSimVolume
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
SGM volume gpu elapsed time: 204.000000 ms
ps_SGMoptimizeSimVolume done
[19:04:18.400922][info] Refine depth map, view id: 996279
gpu elapsed time: 355.000000 ms
gpu elapsed time: 344.000000 ms
gpu elapsed time: 340.000000 ms
gpu elapsed time: 344.000000 ms
gpu elapsed time: 111.000000 ms
gpu elapsed time: 106.000000 ms
gpu elapsed time: 111.000000 ms
gpu elapsed time: 114.000000 ms
rc: 0, gpu elapsed time: 207.000000 ms
rc: 0, gpu elapsed time: 210.000000 ms
rc: 0, gpu elapsed time: 215.000000 ms
rc: 0, gpu elapsed time: 212.000000 ms
[19:04:32.367952][info] Estimate depth map, view id: 7879080
Device 0 memory - used: 485.946869, free: 1562.053101, total: 2048.000000
total size of volume map in GPU memory: 41.380371
nDepths 533, nDepthsToSearch 533
ps_computeSimilarityVolume elapsed time: 7.000000 ms
Device 0 memory - used: 489.009369, free: 1558.990601, total: 2048.000000
total size of volume map in GPU memory: 44.485840
nDepths 573, nDepthsToSearch 573
ps_computeSimilarityVolume elapsed time: 8.000000 ms
Device 0 memory - used: 489.009369, free: 1558.990601, total: 2048.000000
total size of volume map in GPU memory: 44.485840
nDepths 573, nDepthsToSearch 573
ps_computeSimilarityVolume elapsed time: 7.000000 ms
Device 0 memory - used: 489.009369, free: 1558.990601, total: 2048.000000
total size of volume map in GPU memory: 44.485840
nDepths 573, nDepthsToSearch 573
ps_computeSimilarityVolume elapsed time: 9.000000 ms
Device 0 memory - used: 481.321869, free: 1566.678101, total: 2048.000000
total size of volume map in GPU memory: 36.799805
nDepths 474, nDepthsToSearch 474
ps_computeSimilarityVolume elapsed time: 8.000000 ms
Device 0 memory - used: 489.009369, free: 1558.990601, total: 2048.000000
total size of volume map in GPU memory: 44.485840
nDepths 573, nDepthsToSearch 573
ps_computeSimilarityVolume elapsed time: 9.000000 ms
Device 0 memory - used: 475.134369, free: 1572.865601, total: 2048.000000
total size of volume map in GPU memory: 30.588867
nDepths 394, nDepthsToSearch 394
ps_computeSimilarityVolume elapsed time: 7.000000 ms
Device 0 memory - used: 478.321869, free: 1569.678101, total: 2048.000000
total size of volume map in GPU memory: 33.771973
nDepths 435, nDepthsToSearch 435
ps_computeSimilarityVolume elapsed time: 8.000000 ms
Device 0 memory - used: 466.259369, free: 1581.740601, total: 2048.000000
total size of volume map in GPU memory: 21.738281
nDepths 280, nDepthsToSearch 280
ps_computeSimilarityVolume elapsed time: 6.000000 ms
Device 0 memory - used: 481.321869, free: 1566.678101, total: 2048.000000
total size of volume map in GPU memory: 36.799805
nDepths 474, nDepthsToSearch 474
ps_computeSimilarityVolume elapsed time: 9.000000 ms
ps_SGMoptimizeSimVolume
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
SGM volume gpu elapsed time: 970.000000 ms
ps_SGMoptimizeSimVolume done
[19:05:03.680619][info] Refine depth map, view id: 7879080
gpu elapsed time: 1686.000000 ms
gpu elapsed time: 1654.000000 ms
gpu elapsed time: 1688.000000 ms
gpu elapsed time: 1756.000000 ms
gpu elapsed time: 1632.000000 ms
gpu elapsed time: 1674.000000 ms
gpu elapsed time: 1692.000000 ms
gpu elapsed time: 1783.000000 ms
gpu elapsed time: 1380.000000 ms
gpu elapsed time: 1595.000000 ms
gpu elapsed time: 1691.000000 ms
gpu elapsed time: 1767.000000 ms
gpu elapsed time: 1162.000000 ms
gpu elapsed time: 1473.000000 ms
gpu elapsed time: 1462.000000 ms
gpu elapsed time: 1305.000000 ms
gpu elapsed time: 1721.000000 ms
gpu elapsed time: 1695.000000 ms
gpu elapsed time: 1710.000000 ms
gpu elapsed time: 1776.000000 ms
gpu elapsed time: 1329.000000 ms
gpu elapsed time: 1479.000000 ms
gpu elapsed time: 1674.000000 ms
gpu elapsed time: 1762.000000 ms
gpu elapsed time: 1182.000000 ms
gpu elapsed time: 1184.000000 ms
gpu elapsed time: 1188.000000 ms
gpu elapsed time: 1206.000000 ms
rc: 1, gpu elapsed time: 519.000000 ms
rc: 1, gpu elapsed time: 525.000000 ms
rc: 1, gpu elapsed time: 526.000000 ms
rc: 1, gpu elapsed time: 514.000000 ms
[19:06:02.624156][info] Estimate depth map, view id: 13202978

**Comment by natowi** [comment]
Sorry for the late reply, see https://github.com/alicevision/meshroom/wiki/DepthMap-slow-or-red-bar-or-crash, keep an eye on your RAM (try downscaling to 3/4/...) and try the latest release. If the error persists with the 2021 release, open a new issue.
