### ISSUE TITLE
2020.1.0 doesn't find GPU on google Colab (stop at Depthmap)

### ISSUE THREAD

**Issue by fredkomo** [alicevision/meshroom#1111]
I've tried three times but the process stop at Depthmap on google Colab ... "can't find CUDA card..."
2019.2.0 works.

(GPU execution selected)

**Comment by Makiese** [comment]
I have the same problem, probably I have an incompatible graphics card.


### LOG- Output

`[16:19:52.499091][warning] Could not determine number of CUDA cards in this system
[16:19:52.498093][warning] No CUDA-Enabled GPU.
[16:19:52.499091][error] cudaGetDeviceCount failed: CUDA driver version is insufficient for CUDA runtime version
[16:19:52.499091][info] Can't find CUDA-Enabled GPU.
[16:19:52.499091][error] This program needs a CUDA-Enabled GPU (with at least compute capability 2.0).`


What am I doing wrong?

**Used Version:**
Meshroom v.2020.1.1

**My Specs:**
CPU: Intel Core i5 7600K (4.6 GHz)
RAM: Corsair Dominator Platinum DDR4 16GB (2 x 8GB) Kit 3200 MHz
GPU: AMD Radeon HD 7970 GHz Edition
OS: Windows 10 x64

**Comment by natowi** [comment]
@fredkomo You can continue using the 2019.2 release. Since you are using colab, you won´t have a gui with most of the new features anyway (except if you want to compute a 2020 graph file from your local computer)
I´d have to what the problem could be.

@Makiese see https://github.com/alicevision/meshroom/wiki/Draft-Meshing

**Comment by Makiese** [comment]
@natowi Thank you! The Link was very helpful!

**Comment by fredkomo** [comment]
@natowi I plan to use CCtag for scaling and orient but I don't know if it's possible without gui (i'd like to introduce somewhere the coordinates of three points). Thanks for your work.

**Comment by GeneralProtectionFault** [comment]
I'm getting the same issue.  I have a GeForce GTX 480, which I believe is listed as having 2.0 CUDA.  Here's the output on Windows 10 x64:
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 5
 * sgmWSH = 4
 * verboseLevel = "info"

[22:09:01.055418][warning] Could not determine number of CUDA cards in this system
[22:09:01.041409][warning] No CUDA-Enabled GPU.
[22:09:01.055418][error] cudaGetDeviceCount failed: CUDA driver version is insufficient for CUDA runtime version
[22:09:01.055418][info] Can't find CUDA-Enabled GPU.
[22:09:01.055418][error] This program needs a CUDA-Enabled GPU (with at least compute capability 2.0).

I have the latest GeForce driver - 391.35.
I also fail at DepthMap on Linux Mint, with proprietary driver installed.

**Comment by thelatestshit** [comment]
When I take a look at the statistics tab, it says: No GPU.
But in the log tab it says: [22:44:37.904431][info] Supported CUDA-Enabled GPU detected.
BUT when I take a look at the taskmanager the CUDA of my RTX 2080Ti isnt used at all. I have this issue for years now.

Latest drivers are installed (460.89)

still, love your work!
