### ISSUE TITLE
Trees look great in the point cloud but are inverted in the final mesh 

### ISSUE THREAD

**Issue by jtvalgora** [alicevision/meshroom#1112]
Hi, I am new to Meshroom but I'm loving learning and using it so far. 
I'm using drone photography to get detailed scans of smallish areas of 35000 sqft from about 115-75ft flying height. 

I'm using an unmodified default pipeline, and have been trying to sort through some tutorials but this problem seems relevant to some settings I haven't discovered yet. 

Basically all the trees in my scans appear to be very well represented in the point clouds generated during the StructureFromMotion, but when I view the final mesh all the trees are three-dimensionally inverted like a balloon turned inside out. 

Here are some images representing this:

These two show how the trees have proper three dimensional mass 
![image](https://user-images.githubusercontent.com/73245943/96751617-69c04900-139b-11eb-9bcc-b44acfde414a.png)
![image](https://user-images.githubusercontent.com/73245943/96751665-7775ce80-139b-11eb-91d6-feddbd6b3d2d.png)

However after completing the remainder of the default pipeline this happens: 
![image](https://user-images.githubusercontent.com/73245943/96751846-b2780200-139b-11eb-9354-aae1bdd8810b.png)
![image](https://user-images.githubusercontent.com/73245943/96752048-f23ee980-139b-11eb-9889-e30353040ddd.png)

and looking "underneath" the mesh I see the trees taking up sort of a negative mass:
![image](https://user-images.githubusercontent.com/73245943/96751924-cc194980-139b-11eb-8939-d913b15aa1b9.png)
 
If it's hard to understand whats happening I can explain more or take more screenshots. 

Thanks so much for any help!

**Comment by natowi** [comment]
Try disabling "Keep only the largest Mesh" in the MeshFiltering node.

**Comment by jtvalgora** [comment]
> Try disabling "Keep only the largest Mesh" in the MeshFiltering node.

just checked an I don't think that setting is enabled in the default pipeline. It's already disabled I believe.

**Comment by natowi** [comment]
Yes, you are right. I´m out of ideas here, too.
