### ISSUE TITLE
[bug] Texturing after external retopology

### ISSUE THREAD

**Issue by AxelRueweler** [alicevision/meshroom#1113]
**Describe the bug**
I have a mesh that I reworked a little bit with meshlab. I would like to input it into the textturing node but the computation ends with a fatal error that the file can not be loaded.

**To Reproduce**
1. Rework a mesh generated by "MeshFiltering" with meshlab and export it as a obj file
2. Remove the input from MeshFiltering and added the file to "Other Input Mesh".
3. Start the computation.

**Expected behavior**
The mesh get's texttured

**Log**
```
[09:45:48.950235][debug] Reading view 2135073574 projection matrix from image metadata.
[09:45:48.950235][info] Overall maximum dimension: [4032x3024]
[09:45:48.950235][info] Load input mesh.
[09:45:48.950235][info] Loading mesh from obj file: C:/Users/axelr/Documents/MeshroomCache/Meshing/6377b686ccd8ba7e9856823d7c3e4256790036da/meshSimplyfied.obj
[09:45:50.937917][info] 	- # vertices: 1299932
	- # normals: 1299932
	- # uv coordinates: 0
	- # triangles: 0
[09:45:57.868791][info] Mesh loaded: 
	- #points: 1299932
	- # triangles: 0
[09:45:58.348681][fatal] Unable to load: C:/Users/axelr/Documents/MeshroomCache/Meshing/6377b686ccd8ba7e9856823d7c3e4256790036da/meshSimplyfied.obj
```

**Desktop (please complete the following and other pertinent information):**
 - OS: Windows 10
 - Binary version (if applicable): 2020.1

**Comment by natowi** [comment]
I can confirm this problem.
@AxelRueweler Can you check if it works in the 2019.2 release?
(https://github.com/alicevision/meshroom/wiki/Texturing-after-external-re-topology)

**Comment by gbsison** [comment]
Same Issue
I edit the MeshFiltering node's output without changing orientation but almost immediately get an error in the Texturing Node when trying to use the imported obj file.


![Capture](https://user-images.githubusercontent.com/54126803/98819640-11dfa400-2468-11eb-8987-c33903400a68.JPG)




ERROR:root:Error during Graph execution Error on node "Texturing_2":
Log:
Program called with the following parameters:
 * angleHardThreshold = 90
 * bestScoreThreshold = 0.1
 * correctEV = 0
 * downscale =  Unknown Type "unsigned int"
 * fillHoles = 1
 * flipNormals = 0
 * forceVisibleByAllVertices = 0
 * imagesFolder = "D:/Photogrammetry/Projects/MeshroomCache/PrepareDenseScene/12c0f3c069c5af779fdc56960fac7bf41d39fcfc"
 * input = "D:/Photogrammetry/Projects/MeshroomCache/Meshing/1ed6d553163a4572e0d31057d2a047255e81b8c9/densePointCloud.abc"
 * inputMesh = "D:/Photogrammetry/tile3.obj"
 * multiBandDownscale =  Unknown Type "unsigned int"
 * multiBandNbContrib =  Unknown Type "class std::vector<int,class std::allocator<int> >"
 * output = "D:/Photogrammetry/Projects/MeshroomCache/Texturing/c1eb6c9a4f911a98a5303edb6f6f73629b0ad889"
 * outputTextureFileType = "png"
 * padding =  Unknown Type "unsigned int"
 * processColorspace = "sRGB"
 * textureSide =  Unknown Type "unsigned int"
 * unwrapMethod = "Basic"
 * useScore = 1
 * useUDIM = 1
 * verboseLevel = "info"
 * visibilityRemappingMethod = "PullPush"

[21:46:24.684097][info] Found 1 image dimension(s):
[21:46:24.685094][info]         - [6000x4000]
[21:46:24.712597][info] Overall maximum dimension: [6000x4000]
[21:46:24.712597][info] Loading mesh from obj file: D:/Photogrammetry/tile3.obj
[21:46:25.972182][info]         - # vertices: 603710
        - # normals: 603710
        - # uv coordinates: 0
        - # triangles: 0
[21:46:30.086330][info] Mesh loaded:
        - #points: 603710
        - # triangles: 0

**Comment by natowi** [comment]
Could be related to https://github.com/alicevision/AliceVision/pull/923

**Comment by natowi** [comment]
Is this now fixed by the 2021 release?

**Comment by ksune4ka-00x** [comment]
Are there any updates on this issue ? Or the instructions to create the input mesh in the correct format ?
