### ISSUE TITLE
VCOMP140.DLL not found

### ISSUE THREAD

**Issue by rclarsfull** [alicevision/meshroom#1119]
I cant add data, im gettin this error:
![Unbenannt](https://user-images.githubusercontent.com/19623214/97118578-00c63180-170b-11eb-9c76-cdfad2cd5c51.PNG)
version: 2020.1.1

**Comment by natowi** [comment]
f you don’t have it installed already, you need to install the Microsoft Visual C++ Redistributable Package 2015, 2017 and 2019 available on [Microsoft’s Support portal.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads.)
