### ISSUE TITLE
Empty egg from bdist

### ISSUE THREAD

**Issue by GottfriedHofmann** [alicevision/meshroom#112]
I'm on Ubuntu 17.10 x64 and (possibly) compiled PySide2 successfully. Running bdist on meshroom creates a tar file that includes an almost empty egg. Here is the console log:

> python setup.py bdist
running bdist
running bdist_dumb
running build
installing to build/bdist.linux-x86_64/dumb
running install
running install_egg_info
running egg_info
creating Meshroom.egg-info
writing Meshroom.egg-info/PKG-INFO
writing top-level names to Meshroom.egg-info/top_level.txt
writing dependency_links to Meshroom.egg-info/dependency_links.txt
writing manifest file 'Meshroom.egg-info/SOURCES.txt'
reading manifest file 'Meshroom.egg-info/SOURCES.txt'
writing manifest file 'Meshroom.egg-info/SOURCES.txt'
Copying Meshroom.egg-info to build/bdist.linux-x86_64/dumb/usr/local/lib/python2.7/dist-packages/Meshroom-0.0.0.egg-info
running install_scripts
creating /home/g/git-repositories/meshroom/dist
Creating tar archive
removing 'build/bdist.linux-x86_64/dumb' (and everything under it)

And here is the .tar:
[Meshroom-0.0.0.linux-x86_64.tar.gz](https://github.com/alicevision/meshroom/files/1957558/Meshroom-0.0.0.linux-x86_64.tar.gz)

**Comment by gnatty7** [comment]
Yeah, `setup.py` appears to be broken. I just copied the entire 'meshroom' directory in to my site-packages to run it.  Obviously not ideal, but a workaround until this is addressed.

**Comment by yann-lty** [comment]
Thanks for your feedback. We are aware that we need to improve this. In production context, we don't package Meshroom using bdist but rely on a global package manager ([rez](https://github.com/nerdvegas/rez)) that includes it in the PYTHONPATH instead. The setup.py is mainly used to setup the development environment for now but making Meshroom easily packageable is clearly on the roadmap. By the way, any help on the subject would be welcome !
I started to test [cx_Freeze](http://cx-freeze.readthedocs.io/en/latest/) for packaging and I'm eager to see what Qt will make available for Python application packaging.

**Comment by GottfriedHofmann** [comment]
How can I run it after I copied the 'meshroom' directory into site packages?

**Comment by aaronvark** [comment]
I've tried copying it to site packages as well, and manually running __main__.py, but I get errors on QtQuick.Controls 2.3 not being installed, and simpleFarm being an unknown module.

**Comment by yann-lty** [comment]
It will open up, but you won't be able to do much since we mainly call AliceVision binaries from Meshroom. This will also be clarified in the README update.

**Comment by gnatty7** [comment]
Ahh, that's what I figured.  I'll get the AliceVision library and tinker with that.  Thanks!

**Comment by GottfriedHofmann** [comment]
Thanks @gnatty7 for the info on how to run the program. The UI now starts up but it is completely black and the console prints the following error:

> shader compilation failed: 
""
QOpenGLShaderProgram::uniformLocation(matrix): shader program is not linked
QOpenGLShaderProgram::uniformLocation(opacity): shader program is not linked
QOpenGLShaderProgram::uniformLocation(pixelSize): shader program is not linked

When I quit it, I get the following, further error:

> Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/meshroom/ui/reconstruction.py", line 427, in _setSfm
    self.updateViewsAndPoses()
  File "/usr/lib/python2.7/dist-packages/meshroom/ui/reconstruction.py", line 412, in updateViewsAndPoses
    self._views, self._poses = self._sfm.nodeDesc.getViewsAndPoses(self._sfm)
AttributeError: 'PySide2.QtCore.QObject' object has no attribute 'nodeDesc'

**Comment by gnatty7** [comment]
Hi @GottfriedHofmann 
I already filed an issue about the problem quitting:
https://github.com/alicevision/meshroom/issues/115

I didn't get those shader compilation errors as you did.  What sort of GPU do you have and what driver version are you using?

**Comment by GottfriedHofmann** [comment]
GPU is Geforce GTX 1070ti and driver version is 384.111 x86_64
OS is Ubuntu 17.10
I installed QT 5.10 from http://download.qt.io/official_releases/online_installers/ and pointed the PySide2 setup routine to the qmake...

**Comment by gnatty7** [comment]
I also have a GTX 1070 with driver version 388.13 x86_64 on Windows 10
I'm wondering if it has something to do with the Qt installer not having GL supported?  That feels weird though.

**Comment by GottfriedHofmann** [comment]
I found a fix - I added
`from OpenGL import GL`

to __main__.py and now the UI starts up.

**Comment by yann-lty** [comment]
You should not need to do that, seems like something related to OpenGL is missing in your library path.

**Comment by fabiencastan** [comment]
@GottfriedHofmann See my comments in https://github.com/alicevision/meshroom/pull/120 for the QOpenGLShaderProgram error. It comes from a library name problem specific to ubuntu which uses the mesa drivers version of libGL.so instead of the one from the nvidia drivers. So you need to add `/usr/lib/nvidia-340` to the LD_LIBRARY_PATH.

**Comment by fabiencastan** [comment]
I'm closing this issue as the problem with the `setup.py` is now solved and the readme has been updated with the info for opengl drivers.
