### ISSUE TITLE
["No Camera Instrinsic Parameters (missing metadata?)" but camera is in Data base]

### ISSUE THREAD

**Issue by Bloedon** [alicevision/meshroom#1124]
just got a quick problem Camera Instrinsic Parameters wont  read but my Camera is in the Sensor Database

My Camera: 
Make: SONY
Modell: ILCE-6400

Thanks for help in advance ^^

**Comment by natowi** [comment]
Can you please share the log file of the CameraInit node?

**Comment by Bloedon** [comment]
Never mind i just switched to alice vision 2020 an it works fine thanks ^^ anyway
