### ISSUE TITLE
[question]{[WARNING]QQmlApplicationEngine failed to load component} what plugins I missed?

### ISSUE THREAD

**Issue by ScuptFang** [alicevision/meshroom#1127]
[question]{[WARNING]QQmlApplicationEngine failed to load component} what plugins I missed?
**Describe the problem**
Maybe some plugins missed but It is following guide in INSTALL markdown.

command: python meshroom/ui

**Screenshots**

**Dataset**
opening ui of meshroom.

**Log**
[2020-10-30 10:36:31,368][WARNING] == The following "submitters" plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'
[2020-10-30 10:36:31,470][WARNING] QQmlApplicationEngine failed to load component

**Desktop (please complete the following and other pertinent information):**
 - OS: win 10
 - Python version 3.8
 - Qt/PySide version 5.15.0/5.14.1
 - Meshroom version: develop
   - Binary version (if applicable) 2020 10 16

**Comment by avani17101** [comment]
I am facing the same issue on ubuntu 20.04

**Comment by natowi** [comment]
> The following "submitters" plugins could not be loaded

This refers to the renderfarm plugin and can be ignored.

**Comment by ScuptFang** [comment]
thanks a lot! sorry for delayed closing.
