### ISSUE TITLE
[question]warning:root:Ignored

### ISSUE THREAD

**Issue by unmeshbane** [alicevision/meshroom#1130]
I get this warning when I clock on any node in meshroom

WARNING:root:Ignored NaN, Inf, or -Inf value.

**Comment by Nailik** [comment]
Same here, some explanation would be useful.

**Comment by natowi** [comment]
It´s a GUI warning, could be related to this https://github.com/alicevision/meshroom/issues/1101 or https://github.com/alicevision/meshroom/issues/1088
As long as Meshroom works without crashing, this warning can be ignored for now. It will be fixed with other bugs.

**Comment by diedthreetimes** [comment]
I think that printing this warning could be stalling the FeatureExtraction process. 

Synchronous IO can stall the process if not careful.

My CPU is at 34% utilization and I see this warning printed a couple of times a second:

`WARNING:root:Ignored NaN, Inf, or -Inf value.`

**Comment by natowi** [comment]
@diedthreetimes You are welcome to contribute a fix :)
