### ISSUE TITLE
Dense point cloud analyses

### ISSUE THREAD

**Issue by pomat** [alicevision/meshroom#1132]
I'd like to make measures directly on the dense point cloud of a scene through a dedicated software (Cloud Compare). 
I've found the point cloud in **.abc** format in the cache folder "meshing", but Cloud Compare isn't able to read this extension. 

Is there any way to extract a dense point cloud in another format (ASCII for example)?

**Comment by natowi** [comment]
In the SFM node you can change the InterFile Extension to ply or you can use the ConvertSFMFormat node. The ConvertSFMFormat node works with the SFM node output and the Meshing node output (for the dense point cloud)

**Comment by pomat** [comment]
Thank you for the prompt answer.

I don't find the InterFile Extension in the attributes of the SFM node.

I tried the other option and added directly the .abc file from the mesh folder (which I had previously saved) in the input box of the ConvertSFMFormat node but it didn't work. 
Should I rerun the entire process so that it can work with the cache files?

What about "Image White List"? Should I add something?

**Comment by natowi** [comment]
Solution 1

![filety1](https://user-images.githubusercontent.com/8138537/98008086-6e055100-1df4-11eb-88a7-5123b4c3b5d2.JPG)


Solution 2 A/B

![conv](https://user-images.githubusercontent.com/8138537/98008305-ae64cf00-1df4-11eb-9890-750017b00d8c.JPG)

![formt](https://user-images.githubusercontent.com/8138537/98008083-6cd42400-1df4-11eb-8cc8-d1aef9d2da1c.JPG)

**Comment by pomat** [comment]
Thank you I succesfully esxtracted a .ply version of the dense point cloud from the "meshing" mode.
