### ISSUE TITLE
Georeferencing the scene

### ISSUE THREAD

**Issue by pomat** [alicevision/meshroom#1133]
Is there a way to assign known coordinates to some key points in the scene in order to georeference all the model?

**Comment by natowi** [comment]
You can use [CCTAGs](https://github.com/alicevision/meshroom/wiki/CCTAG-scaling) or [Meshlab](https://www.youtube.com/watch?v=6psAppbOOXM) to scale a scene.

**Comment by pomat** [comment]
Thank you.

Sorry, I need to perform **orientation** measures on some features of the cloud, so I don't need to rescale it but to orient it in a defined coordinate system. 

Using the SfMTransform node with "from_markers" transformation method can I pick the markers directly from the SfM cloud in Meshroom?

**Comment by natowi** [comment]
You can orient and scale a scene with a SfMTransform node. You can not manually pick markers, they will be detected automatically if placed in the scene. Applying a real Coordinate system (like UTM) is not supported within Meshroom. You need to convert the point cloud/mesh to a supported format to reference it in another software like CloudCompare (https://danielgm.net/cc/forum/viewtopic.php?t=2739 https://www.youtube.com/watch?v=PjiJBqckv90 https://www.youtube.com/watch?v=_eG-oj22YrY)

**Comment by pomat** [comment]
Is it possible to geocode the scene knowing the position of the cameras? 
It would be a good option in cases where it is not possible to rely on markers in the scene.

**Comment by natowi** [comment]
No, at the moment there is no such feature implemented.

**Comment by natowi** [comment]
@pomat Here is a tutorial that uses Meshroom, Blender+BlenderGIS and QGIS for 3D georeferencing: https://www.youtube.com/watch?v=XAUc831V (it´s in Italian ;) ) 
But I´d prefer a native solution within Meshroom to this workaround, too.

**Comment by pomat** [comment]
Thank you but I can't open the video on youtube.
It says "not available"

**Comment by natowi** [comment]
@pomat sorry, it´s https://www.youtube.com/watch?v=XAUc831V-Nk
