### ISSUE TITLE
Features not getting detected

### ISSUE THREAD

**Issue by Sachet12345** [alicevision/meshroom#1137]
**Describe the problem**
Both the objects are of simmilar materials but feature is getting detected on one and not the other. What could be the reason? Is there any way I can detect enough features on the duck for dense reconstruction?

**Screenshots**
![duck](https://user-images.githubusercontent.com/39695026/98432839-3e9e5f00-20e8-11eb-8d5a-b879e49f91a9.JPG)
![teddy1](https://user-images.githubusercontent.com/39695026/98432842-4231e600-20e8-11eb-8570-bca99172431d.JPG)

**Comment by natowi** [comment]
Bright colours are more reflective than darker colours. And reflective areas are bad for feature detection.

**Comment by ChemicalXandco** [comment]
If the camera are calibrated properly dense reconstruction will work just fine, but if you want more features on the object for some reason you can set describer preset on the feature extraction node to high or ultra and then you will get more features on your object.

**Comment by Sachet12345** [comment]
Hi @natowi, thanks for the swift reply. Is there anyway I can get a dense reconstruction from the first datset? I have alrrady tried high present and sift with akaze but only 2/35 cameras are getting reconstructed in that case.

**Comment by Sachet12345** [comment]
Hi @ChemicalXandco, the camera has been calibrated. I was of the impression that the model reconstructed was bad because not enough features are getting recognised on the object that can be matched. 
Please correct me if I am wrong.
