### ISSUE TITLE
is there a way to insert images with known camera pose estimation for each image? 

### ISSUE THREAD

**Issue by lidorshimoni** [alicevision/meshroom#1140]
**Describe the problem**
I want to make a scene reconstruction for an environment that is being scanned and photographed by a robot. 
the robot has its own pose estimation, i.e, I have a good estimate for the position & orientation of the camera in each photo that is taken.
can this "free" extra info about every image with meshroom? can it help the accuracy of the reconstruction? or even lower the computation time?

**Desktop (please complete the following and other pertinent information):**
 - OS: ubuntu 18
 - Python version irrelevent but 3.6
 - Qt/PySide version 5.12.4
 - Meshroom version: release version
   - Binary version 2020.1.0

**Additional context**
using ros2 and cartographer for the slam. (this is how I get the pose estimation)

**Comment by natowi** [comment]
Take a look at https://github.com/alicevision/meshroom/wiki/Using-known-camera-positions and the linked issues there
