### ISSUE TITLE
[question] UI won't load on headless system (no display attached), Teamviewer/VNC

### ISSUE THREAD

**Issue by dadaphl** [alicevision/meshroom#1143]
**Describe the problem**
I'm trying to run Meshlab on a Windows machine, that doesn't have a display attached to it and the UI doesn't load up. I connect through Teamviewer. When I attach a display I can load the UI and start the process. When I disconnect the display, the UI freezes in it's last state but the computation continues and I can see in the logs that the process finishes. I assume, that Windows doesn't initiate the opengl system when no display is attached. Does anybody know a workaround? I know there is dummy/ghost hdmi plugs, but I would like to avoid them.

**Screenshots**
<img width="670" alt="Screen Shot 2020-11-10 at 12 27 57" src="https://user-images.githubusercontent.com/415536/98668961-ecac4200-2350-11eb-96f2-91394b5890dc.png">

**Dataset**
N/A

**Log**
N/A

**Desktop (please complete the following and other pertinent information):**
 - OS: win 10 pro
 - Meshroom version: Binary version 2020.1.1
 - MSI GTX 970

**Comment by ChemicalXandco** [comment]
You can use either `meshroom_photogrammetry` or `meshroom_compute` on a headless system, as they do not load the GUI.

**Comment by sidk99** [comment]
How can Meshroom be installed in a headless fashion? running the released binaries seems to require qt plugins which gets the following error: qt.qpa.xcb: could not connect to display
