### ISSUE TITLE
[bug] live reconstruction

### ISSUE THREAD

**Issue by r33p** [alicevision/meshroom#1144]
**Describe the bug**
live reconstruction doesn't do anything

**To Reproduce**
1. Save the project : File -> Save As -> 'name of your project'
2. Click on : View -> Live reconstruction
3. in the Live 'Reconstruction window', click on the 'Image Folder Icon' and choose the folder to watch
4. press the 'start button' in the 'live reconstruction window'
but nothing happen, no operations are done, the cpu keep quiet

**Expected behavior**
start to watch the image folder, and do the SFM's computation

**Log**
Traceback (most recent call last):
  File "/opt/Meshroom/meshroom/ui/reconstruction.py", line 106, in timerEvent
  File "/opt/Meshroom/meshroom/ui/reconstruction.py", line 115, in update
TypeError: 'FilesByType' object is not iterable
Traceback (most recent call last):
  File "/opt/Meshroom/meshroom/ui/reconstruction.py", line 106, in timerEvent
  File "/opt/Meshroom/meshroom/ui/reconstruction.py", line 115, in update
TypeError: 'FilesByType' object is not iterable
Traceback (most recent call last):

**Desktop (please complete the following and other pertinent information):**
 - OS: ubuntu 20.04
 - Python version 2.7
 - Meshroom version: binary release 2020.1.0

**Comment by Oshaik** [comment]
You have to initialize the software with a few images then click start.

**Comment by Aquilux** [comment]
I am getting this error (same reproduction method) even after having dragged and dropped initial images into the appropriate window, hitting start on the top status bar and then hitting start on the live reconstruction tab.

**Comment by Oshaik** [comment]
Try it without clicking start at the top.

**Comment by Aquilux** [comment]
Repeating the process without clicking the start button at the top does not change this behavior.

**Comment by IchbinkeinReh** [comment]
Seems https://github.com/alicevision/meshroom/pull/1145 has solved the issue. When i tried it with that code it works. But unfortunately that change is not yet present in the current release

**Comment by marcusdiy** [comment]
Was the build updated too? Im trying to download it from https://alicevision.org/#meshroom but the error persists...
Using Meshroom 2020.1.1 64-bit and even with the Meshroom 2020.1.0 64-bit

**Comment by ChemicalXandco** [comment]
@marcusdiy this bug is present in versions `2020.1.0` and `2020.1.1`.

**Comment by natowi** [comment]
I build the latest version with the fix for you (on windows), replacing _reconstruction.pyc_ in _Meshroom-2020.1.1\lib\meshroom\ui_ should work

[reconstruction.zip](https://github.com/alicevision/meshroom/files/6037826/reconstruction.zip)
