### ISSUE TITLE
PrepareDenseScene Error

### ISSUE THREAD

**Issue by zRavenDE** [alicevision/meshroom#1146]
The PrepareDenseScene node doesn´t work for soem reason, I couldn´t figure out why, also tried recomputing several times...
Here´s my log: 

`Nodes to execute:  ['PrepareDenseScene_1']
WARNING: downgrade status on node "PrepareDenseScene_1(5)" from Status.ERROR to Status.SUBMITTED

[1/1](1/8) PrepareDenseScene
Node chunk already computed: PrepareDenseScene_1(0)

[1/1](2/8) PrepareDenseScene
Node chunk already computed: PrepareDenseScene_1(1)

[1/1](3/8) PrepareDenseScene
Node chunk already computed: PrepareDenseScene_1(2)

[1/1](4/8) PrepareDenseScene
Node chunk already computed: PrepareDenseScene_1(3)

[1/1](5/8) PrepareDenseScene
Node chunk already computed: PrepareDenseScene_1(4)

[1/1](6/8) PrepareDenseScene
 - commandLine: aliceVision_prepareDenseScene  --input "C:/Users/MB/Desktop/Mesh (falls es funktioniert)/MeshroomCache/StructureFromMotion/c22d2ad39f6aa0ade9983da86e0db11318b6f2cb/sfm.abc" --outputFileType exr --saveMetadata True --saveMatricesTxtFiles False --evCorrection False --verboseLevel info --output "C:/Users/MB/Desktop/Mesh (falls es funktioniert)/MeshroomCache/PrepareDenseScene/702011feaba028c6d76b4467a08adbc4710554dc" --rangeStart 200 --rangeSize 40
 - logFile: C:/Users/MB/Desktop/Mesh (falls es funktioniert)/MeshroomCache/PrepareDenseScene/702011feaba028c6d76b4467a08adbc4710554dc/5.log
 - elapsed time: 0:00:05.412513
ERROR:root:Error on node computation: Error on node "PrepareDenseScene_1(5)":
Log:
Program called with the following parameters:
 * evCorrection = 0
 * input = "C:/Users/MB/Desktop/Mesh (falls es funktioniert)/MeshroomCache/StructureFromMotion/c22d2ad39f6aa0ade9983da86e0db11318b6f2cb/sfm.abc"
 * output = "C:/Users/MB/Desktop/Mesh (falls es funktioniert)/MeshroomCache/PrepareDenseScene/702011feaba028c6d76b4467a08adbc4710554dc"
 * outputFileType = "exr"
 * rangeSize = 40
 * rangeStart = 200
 * saveMatricesTxtFiles = 0
 * saveMetadata = 1
 * verboseLevel = "info"

Exporting Scene Undistorted Images
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
[18:52:37.023548][info] median Ev : 7.33985
*
WARNING: downgrade status on node "PrepareDenseScene_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "PrepareDenseScene_1(7)" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "PrepareDenseScene_1(5)":
Log:
Program called with the following parameters:
 * evCorrection = 0
 * input = "C:/Users/MB/Desktop/Mesh (falls es funktioniert)/MeshroomCache/StructureFromMotion/c22d2ad39f6aa0ade9983da86e0db11318b6f2cb/sfm.abc"
 * output = "C:/Users/MB/Desktop/Mesh (falls es funktioniert)/MeshroomCache/PrepareDenseScene/702011feaba028c6d76b4467a08adbc4710554dc"
 * outputFileType = "exr"
 * rangeSize = 40
 * rangeStart = 200
 * saveMatricesTxtFiles = 0
 * saveMetadata = 1
 * verboseLevel = "info"

Exporting Scene Undistorted Images
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
[18:52:37.023548][info] median Ev : 7.33985`

I´m using Win10,
GTX 1060 6GB
Intel Core i5-8400
16GB Ram
Meshroom Version: 2019.2.0
I made a project with 286 photos (only 285 got this Camera Icon, couldn´t find the one that didn´t), all photos got the metadata icon (those Apeture blades), shot them with a Canon EOS M50...

**Comment by fabiencastan** [comment]
Avoid special characters like "(" in your path.

**Comment by cramnaoj** [comment]
I had the same problem. I was using the "ñ" character in one of the paths, and it crashed in PrepareDenseScene or if I clicked in Display Features to see what was beeing selected. Also it might also happen if you are saving it really deep.
