### ISSUE TITLE
SIFT bad Feature Extraction and possible endless loop when using AKAZE

### ISSUE THREAD

**Issue by NotErikUden** [alicevision/meshroom#1147]
I've taken 108 pictures with a smartphone with the same focal length, focus, etc. one example of which is seen here:
![IMG_20201111_131137](https://user-images.githubusercontent.com/52011431/99145203-1aed9280-266d-11eb-88c5-072c58729d6c.jpg)
(I hope metadata transfers)

The issue is that whenever I run all standard options over these images, the StructureFromMotion node has no more points than this:
![image](https://user-images.githubusercontent.com/52011431/99145239-58eab680-266d-11eb-81cc-3e6c629e551c.png)

I won't have to show you how the resulting 3D model only has an insanely detailed background, but not even an existing foreground / 3D model of the person I was trying to take pictures of. 

I looked around and found out about the describer preset in the FeatureExtraction node and put it to **high** _(since I only had 108 images and not more)_. From there on I put the Describer Types in the FeatureExtraction, FeatureMatching and StructureFromMotion nodes to have **akaze** selected as well as **SIFT**. 

I have an RTX 2080 Ti and a 12-Core 24 Threads Ryzen Threadripper 1920x and it has been running for _20 hours_. The only message I am getting is:

`WARNING:root:Ignored NaN, Inf, or -Inf value.`

And the program is still on the FeatureMatching node. Is akaze just too much? Also why is only my CPU utilized, does akaze not make use of CUDA / CUDA 11.1?

**Screenshots**
![image](https://user-images.githubusercontent.com/52011431/99145138-681d3480-266c-11eb-8e3c-753318c4d7f7.png)

**Desktop:**
 - OS: Windows 10 64 x86
 - Python version: 3.8.5
 - Qt/PySide version: I don't have them
 - Meshroom version: 2020.1.1

**Additional context**
I'm simply interested in knowing what the issue is or why it takes so long! Hopefully someone even has an idea on why SIFT doesn't get any features extracted from my images.
![image](https://user-images.githubusercontent.com/52011431/99145450-4a050380-266f-11eb-8105-011ba7a5861f.png)

Here SIFT finds lots of features in the background, but not so many on the foreground person. I get that the background is partially important to extract features about the camera's position etc. so, having cutouts of these images would be counterproductive, but why can't it find any features on the actual person?  How would you be capable to improve this by either taking better pictures or using a different algorithm for feature extraction? Because Akaze is taking days whilst utilizing 100% of my CPU which has 24 threads all running at >3.68GHz.
Is Akaze supposed to be like this, or is there some error I am causing?

Any help would be appreciated!

**Comment by natowi** [comment]
"WARNING:root:Ignored NaN, Inf, or -Inf value." is not related to your problem and can be ignored for now.

You can disable Force CPU Extraction in the FeatureExtraction node to use your GPU. (https://github.com/alicevision/meshroom/issues/502#issuecomment-727196258)

You need to capture close-up images. The person should fill most of the image frame in your case.
As you can see the clothing is not really suited for a good reconstruction (black surface). The person you want to capture should wear something with a pattern and with minimum areas with a single colour. 
Also a studio-setup (feature less backdrop that contrasts your person) with indirect lighting is recommended. This can be combined with https://github.com/alicevision/meshroom/wiki/Projected-Light-Patterns

**Comment by NotErikUden** [comment]
Thank you very much for your recommendations!

![image](https://user-images.githubusercontent.com/52011431/99147379-d5d35b80-2680-11eb-95cc-1a1861d52d77.png)

I've just wanted to note that this is true for Akaze as well. As you can very well see, the entirety of the black surface has little to no features extracted from it. You're right. No patterns and non-close-up images make this awfully hard.

**Comment by natowi** [comment]
> I've just wanted to note that this is true for Akaze as well.

That is expected. Sift and Akaze are FeatureDecectors and combining both can give better results but this still requires that there are features that can be detected. If you need the person with the exact clothing, I`d recommend you to try out the light pattern projection.

**Comment by NotErikUden** [comment]
Is removing the background that good of an idea? I obviously thought of it, but doesn't the background often give particularly valuable information about the camera's position, or is the person itself enough for the algorithm to figure it out?

I do have Photoshop and will try the other tools you specified. Thank you very much! Sorry for initially tagging this as a "bug." 
This thread can be closed as all my questions, beyond this one, are resolved.

**Comment by natowi** [comment]
It really depends on what you are trying to reconstruct. Masking out the background can improve the computation time, but is not beneficial when you want to capture something with sparse features.
