### ISSUE TITLE
[GUI text not displaying]

### ISSUE THREAD

**Issue by Iridhunter** [alicevision/meshroom#1148]
**Describe the problem**
Text for the GUI isn't being displayed on start up.
tired, installing ( extracting file not as admin) and reinstalled program of two different releases.
I'm an visual artist without coding experience but very wiling to put in the time to solve issue, 

![14 11 2020_18 50 42_REC](https://user-images.githubusercontent.com/74495808/99185808-25c72680-2744-11eb-9084-66f990a687a8.png)

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, ]
 - Python version [e.g. 3.9]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version:  release version 3,9
   
**Additional context**
Thanks for your time.

**Comment by natowi** [comment]
Try to install  [Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

This issue has been reported previously [Issue ???]
