### ISSUE TITLE
Stops at DepthMap on RTX 3080

### ISSUE THREAD

**Issue by Prelqit** [alicevision/meshroom#1149]
[7/11](2/18) DepthMap
 - commandLine: aliceVision_depthMapEstimation  --input "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/StructureFromMotion/822b644141db5269cee0448981f9b668f2fbcba4/sfm.abc" --imagesFolder "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/PrepareDenseScene/2c3ee38a39d78001873959700beefeaeb1df7567" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/DepthMap/2709753aea435631495cfa1b48cab443e905b89a" --rangeStart 3 --rangeSize 3
 - logFile: C:/Users/tobir/AppData/Local/Temp/MeshroomCache/DepthMap/2709753aea435631495cfa1b48cab443e905b89a/1.log
 - elapsed time: 0:00:02.827053
ERROR:root:Error on node computation: Error on node "DepthMap_1(1)":
Log:
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/PrepareDenseScene/2c3ee38a39d78001873959700beefeaeb1df7567"
 * input = "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/StructureFromMotion/822b644141db5269cee0448981f9b668f2fbcba4/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/DepthMap/2709753aea435631495cfa1b48cab443e905b89a"
 * rangeSize = 3
 * rangeStart = 3
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[15:20:07.078264][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce RTX 3080
        - compute capability:      8.6
        - total device memory:     10240 MB
        - device memory available: 9078 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   1536
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {131072,65536}
        - max 3D array texture:    {16384,16384,16384}
        - max 2D linear texture:   {131072,65000,2097120}
        - max 2D layered texture:  {32768,32768,2048}
        - number of SM(x)s:        68
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte
[15:20:07.253800][info] Supported CUDA-Enabled GPU detected.
[15:20:07.304664][info] Found 1 image dimension(s):
[15:20:07.304664][info]         - [1280x720]
[15:20:07.338574][info] Overall maximum dimension: [1280x720]
[15:20:07.338574][info] Create depth maps.
number of CUDA devices: 1
   0: GeForce RTX 3080
[15:20:07.338574][info] # GPU devices: 1, # CPU threads: 16
[15:20:07.338574][info] Plane sweeping parameters:
        - scale: 2
        - step: 1
[15:20:07.338574][info] PlaneSweepingCuda:
        - _nImgsInGPUAtTime: 22
        - scales: 2
        - subPixel: Yes
        - varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 1161.250000, free: 9078.750000, total: 10240.000000
Device 0 memory - used: 1265.750000, free: 8974.250000, total: 10240.000000
[15:20:07.696615][info] Estimate depth map, view id: 209825996

WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(11)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(12)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(13)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(14)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(15)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(16)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(17)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "DepthMap_1(1)":
Log:
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/PrepareDenseScene/2c3ee38a39d78001873959700beefeaeb1df7567"
 * input = "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/StructureFromMotion/822b644141db5269cee0448981f9b668f2fbcba4/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/DepthMap/2709753aea435631495cfa1b48cab443e905b89a"
 * rangeSize = 3
 * rangeStart = 3
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[15:20:07.078264][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce RTX 3080
        - compute capability:      8.6
        - total device memory:     10240 MB
        - device memory available: 9078 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   1536
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {131072,65536}
        - max 3D array texture:    {16384,16384,16384}
        - max 2D linear texture:   {131072,65000,2097120}
        - max 2D layered texture:  {32768,32768,2048}
        - number of SM(x)s:        68
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte
[15:20:07.253800][info] Supported CUDA-Enabled GPU detected.
[15:20:07.304664][info] Found 1 image dimension(s):
[15:20:07.304664][info]         - [1280x720]
[15:20:07.338574][info] Overall maximum dimension: [1280x720]
[15:20:07.338574][info] Create depth maps.
number of CUDA devices: 1
   0: GeForce RTX 3080
[15:20:07.338574][info] # GPU devices: 1, # CPU threads: 16
[15:20:07.338574][info] Plane sweeping parameters:
        - scale: 2
        - step: 1
[15:20:07.338574][info] PlaneSweepingCuda:
        - _nImgsInGPUAtTime: 22
        - scales: 2
        - subPixel: Yes
        - varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 1161.250000, free: 9078.750000, total: 10240.000000
Device 0 memory - used: 1265.750000, free: 8974.250000, total: 10240.000000
[15:20:07.696615][info] Estimate depth map, view id: 209825996

It stops at DepthMap if i hit start again it just stops. Maby my RTX 3080 is not Supported?
Or am i doing anything wrong. Thx

**Comment by Prelqit** [comment]
If i manually try to compute DepthMap it looks like it crashes at 4/18 Step.
[1/1](2/18) DepthMap
 - commandLine: aliceVision_depthMapEstimation  --input "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/StructureFromMotion/822b644141db5269cee0448981f9b668f2fbcba4/sfm.abc" --imagesFolder "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/PrepareDenseScene/2c3ee38a39d78001873959700beefeaeb1df7567" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/DepthMap/2709753aea435631495cfa1b48cab443e905b89a" --rangeStart 3 --rangeSize 3
 - logFile: C:/Users/tobir/AppData/Local/Temp/MeshroomCache/DepthMap/2709753aea435631495cfa1b48cab443e905b89a/1.log
 - elapsed time: 0:00:04.003194

[1/1](3/18) DepthMap
 - commandLine: aliceVision_depthMapEstimation  --input "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/StructureFromMotion/822b644141db5269cee0448981f9b668f2fbcba4/sfm.abc" --imagesFolder "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/PrepareDenseScene/2c3ee38a39d78001873959700beefeaeb1df7567" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/DepthMap/2709753aea435631495cfa1b48cab443e905b89a" --rangeStart 6 --rangeSize 3
 - logFile: C:/Users/tobir/AppData/Local/Temp/MeshroomCache/DepthMap/2709753aea435631495cfa1b48cab443e905b89a/2.log
 - elapsed time: 0:00:03.467332

[1/1](4/18) DepthMap
 - commandLine: aliceVision_depthMapEstimation  --input "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/StructureFromMotion/822b644141db5269cee0448981f9b668f2fbcba4/sfm.abc" --imagesFolder "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/PrepareDenseScene/2c3ee38a39d78001873959700beefeaeb1df7567" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/DepthMap/2709753aea435631495cfa1b48cab443e905b89a" --rangeStart 9 --rangeSize 3
 - logFile: C:/Users/tobir/AppData/Local/Temp/MeshroomCache/DepthMap/2709753aea435631495cfa1b48cab443e905b89a/3.log
 - elapsed time: 0:00:03.123285
ERROR:root:Error on node computation: Error on node "DepthMap_1(3)":
Log:
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/PrepareDenseScene/2c3ee38a39d78001873959700beefeaeb1df7567"
 * input = "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/StructureFromMotion/822b644141db5269cee0448981f9b668f2fbcba4/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/DepthMap/2709753aea435631495cfa1b48cab443e905b89a"
 * rangeSize = 3
 * rangeStart = 9
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[16:47:47.261307][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce RTX 3080
        - compute capability:      8.6
        - total device memory:     10240 MB
        - device memory available: 9078 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   1536
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {131072,65536}
        - max 3D array texture:    {16384,16384,16384}
        - max 2D linear texture:   {131072,65000,2097120}
        - max 2D layered texture:  {32768,32768,2048}
        - number of SM(x)s:        68
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte
[16:47:47.479399][info] Supported CUDA-Enabled GPU detected.
[16:47:47.530265][info] Found 1 image dimension(s):
[16:47:47.530265][info]         - [1280x720]
[16:47:47.571155][info] Overall maximum dimension: [1280x720]
[16:47:47.571155][info] Create depth maps.
number of CUDA devices: 1
   0: GeForce RTX 3080
[16:47:47.571155][info] # GPU devices: 1, # CPU threads: 16
[16:47:47.571155][info] Plane sweeping parameters:
        - scale: 2
        - step: 1
[16:47:47.571155][info] PlaneSweepingCuda:
        - _nImgsInGPUAtTime: 22
        - scales: 2
        - subPixel: Yes
        - varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 1161.250000, free: 9078.750000, total: 10240.000000
Device 0 memory - used: 1265.750000, free: 8974.250000, total: 10240.000000
[16:47:47.580132][info] Found only 4/10 nearest cameras for view id: 581601496
[16:47:47.581129][info] Found only 4/6 nearest cameras for view id: 581601496
[16:47:47.721262][info] Estimate depth map, view id: 581601496
Device 0 memory - used: 1281.437500, free: 8958.562500, total: 10240.000000
total size of volume map in GPU memory: 15.644531
nDepths 178, nDepthsToSearch 178
ps_computeSimilarityVolume elapsed time: 2.000000 ms
Device 0 memory - used: 1281.437500, free: 8958.562500, total: 10240.000000
total size of volume map in GPU memory: 15.644531
nDepths 178, nDepthsToSearch 178
ps_computeSimilarityVolume elapsed time: 2.000000 ms
Device 0 memory - used: 1273.875000, free: 8966.125000, total: 10240.000000
total size of volume map in GPU memory: 8.085938
nDepths 92, nDepthsToSearch 92
ps_computeSimilarityVolume elapsed time: 1.000000 ms
Device 0 memory - used: 1281.062500, free: 8958.937500, total: 10240.000000
total size of volume map in GPU memory: 15.292969
nDepths 174, nDepthsToSearch 174
ps_computeSimilarityVolume elapsed time: 2.000000 ms
ps_SGMoptimizeSimVolume
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
SGM volume gpu elapsed time: 44.000000 ms
ps_SGMoptimizeSimVolume done
[16:47:48.081918][info] Refine depth map, view id: 581601496
gpu elapsed time: 9.000000 ms
gpu elapsed time: 5.000000 ms
gpu elapsed time: 8.000000 ms
gpu elapsed time: 6.000000 ms
gpu elapsed time: 5.000000 ms
gpu elapsed time: 8.000000 ms
gpu elapsed time: 5.000000 ms
gpu elapsed time: 9.000000 ms
gpu elapsed time: 7.000000 ms
gpu elapsed time: 7.000000 ms
gpu elapsed time: 9.000000 ms
gpu elapsed time: 3.000000 ms
gpu elapsed time: 8.000000 ms
gpu elapsed time: 5.000000 ms
gpu elapsed time: 9.000000 ms
gpu elapsed time: 5.000000 ms
gpu elapsed time: 10.000000 ms
gpu elapsed time: 9.000000 ms
gpu elapsed time: 10.000000 ms
gpu elapsed time: 8.000000 ms
rc: 9, gpu elapsed time: 7.000000 ms
rc: 9, gpu elapsed time: 5.000000 ms
rc: 9, gpu elapsed time: 4.000000 ms
rc: 9, gpu elapsed time: 5.000000 ms
[16:47:48.713492][info] Estimate depth map, view id: 632410147

WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(11)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(12)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(13)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(14)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(15)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(16)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(17)" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "DepthMap_1(3)":
Log:
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/PrepareDenseScene/2c3ee38a39d78001873959700beefeaeb1df7567"
 * input = "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/StructureFromMotion/822b644141db5269cee0448981f9b668f2fbcba4/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/Users/tobir/AppData/Local/Temp/MeshroomCache/DepthMap/2709753aea435631495cfa1b48cab443e905b89a"
 * rangeSize = 3
 * rangeStart = 9
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[16:47:47.261307][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce RTX 3080
        - compute capability:      8.6
        - total device memory:     10240 MB
        - device memory available: 9078 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   1536
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {131072,65536}
        - max 3D array texture:    {16384,16384,16384}
        - max 2D linear texture:   {131072,65000,2097120}
        - max 2D layered texture:  {32768,32768,2048}
        - number of SM(x)s:        68
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte
[16:47:47.479399][info] Supported CUDA-Enabled GPU detected.
[16:47:47.530265][info] Found 1 image dimension(s):
[16:47:47.530265][info]         - [1280x720]
[16:47:47.571155][info] Overall maximum dimension: [1280x720]
[16:47:47.571155][info] Create depth maps.
number of CUDA devices: 1
   0: GeForce RTX 3080
[16:47:47.571155][info] # GPU devices: 1, # CPU threads: 16
[16:47:47.571155][info] Plane sweeping parameters:
        - scale: 2
        - step: 1
[16:47:47.571155][info] PlaneSweepingCuda:
        - _nImgsInGPUAtTime: 22
        - scales: 2
        - subPixel: Yes
        - varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 1161.250000, free: 9078.750000, total: 10240.000000
Device 0 memory - used: 1265.750000, free: 8974.250000, total: 10240.000000
[16:47:47.580132][info] Found only 4/10 nearest cameras for view id: 581601496
[16:47:47.581129][info] Found only 4/6 nearest cameras for view id: 581601496
[16:47:47.721262][info] Estimate depth map, view id: 581601496
Device 0 memory - used: 1281.437500, free: 8958.562500, total: 10240.000000
total size of volume map in GPU memory: 15.644531
nDepths 178, nDepthsToSearch 178
ps_computeSimilarityVolume elapsed time: 2.000000 ms
Device 0 memory - used: 1281.437500, free: 8958.562500, total: 10240.000000
total size of volume map in GPU memory: 15.644531
nDepths 178, nDepthsToSearch 178
ps_computeSimilarityVolume elapsed time: 2.000000 ms
Device 0 memory - used: 1273.875000, free: 8966.125000, total: 10240.000000
total size of volume map in GPU memory: 8.085938
nDepths 92, nDepthsToSearch 92
ps_computeSimilarityVolume elapsed time: 1.000000 ms
Device 0 memory - used: 1281.062500, free: 8958.937500, total: 10240.000000
total size of volume map in GPU memory: 15.292969
nDepths 174, nDepthsToSearch 174
ps_computeSimilarityVolume elapsed time: 2.000000 ms
ps_SGMoptimizeSimVolume
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
SGM volume gpu elapsed time: 44.000000 ms
ps_SGMoptimizeSimVolume done
[16:47:48.081918][info] Refine depth map, view id: 581601496
gpu elapsed time: 9.000000 ms
gpu elapsed time: 5.000000 ms
gpu elapsed time: 8.000000 ms
gpu elapsed time: 6.000000 ms
gpu elapsed time: 5.000000 ms
gpu elapsed time: 8.000000 ms
gpu elapsed time: 5.000000 ms
gpu elapsed time: 9.000000 ms
gpu elapsed time: 7.000000 ms
gpu elapsed time: 7.000000 ms
gpu elapsed time: 9.000000 ms
gpu elapsed time: 3.000000 ms
gpu elapsed time: 8.000000 ms
gpu elapsed time: 5.000000 ms
gpu elapsed time: 9.000000 ms
gpu elapsed time: 5.000000 ms
gpu elapsed time: 10.000000 ms
gpu elapsed time: 9.000000 ms
gpu elapsed time: 10.000000 ms
gpu elapsed time: 8.000000 ms
rc: 9, gpu elapsed time: 7.000000 ms
rc: 9, gpu elapsed time: 5.000000 ms
rc: 9, gpu elapsed time: 4.000000 ms
rc: 9, gpu elapsed time: 5.000000 ms
[16:47:48.713492][info] Estimate depth map, view id: 632410147

**Comment by Prelqit** [comment]
I think my gpu just crashed caused by an overclock. Every other Programm / Game was working but with default settings it works ^^

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/issues/741#issuecomment-583902412 may be worth a try
