### ISSUE TITLE
Can I export the camera coordinates of my file?

### ISSUE THREAD

**Issue by Snobbil** [alicevision/meshroom#1150]
Hello,

I am currently working on a project in which I am required to know the camera coordinates Meshroom has estimated. 

I then use these coordinates to calculate a scaling factor for my point cloud. 

I am working on Windows and I use Meshroom 2020.1.1

Regards,

Alan

**Comment by natowi** [comment]
The camera coordinates are stored in the abc file or in the SFM file. You can convert the file format with the convertSFMformat node. Maybe this is a better option for you: https://github.com/alicevision/meshroom/wiki/CCTAG-scaling

**Comment by Snobbil** [comment]
Thank you for the quick response natowi! 

I managed to export the points.

I would need to be able to find out which point corresponds to which picture, however - is that possible?

**Comment by natowi** [comment]
At the moment only CCTAG based scaling is supported within Meshroom.

You could measure the camera distance in Meshlab and calculate the scaling factor. Then use https://github.com/alicevision/meshroom/issues/256#issuecomment-709983331 or directly scale it in Meshlab.
