### ISSUE TITLE
Import dense cloud

### ISSUE THREAD

**Issue by Roby87** [alicevision/meshroom#1152]
hello,
I am writing for a technical clarification. my goal is to carry out a complete photogrammetic process, but I saw that meshroom has no cleaning tools (I searched and found nothing of the kind) and to insert the GCPs for georeferencing, so I saw that it is possible to export the dense cloud, and once clean and georeferenced it in CC, I would to reintroduce it in meshroom to make a mesh and put textures, is there a way to introduce the modified dense cloud into its own workflow?

**Comment by natowi** [comment]
At the moment cleaning and georeferencing is not possible within Meshroom. You can use CCTAG markers to scale your model. To georeference a model you have to use another software for now.

https://github.com/alicevision/meshroom/wiki/Texturing-after-external-re-topology
https://github.com/alicevision/meshroom/wiki/CCTAG-scaling
