### ISSUE TITLE
Sorry but your product is crap[bug]

### ISSUE THREAD

**Issue by Tristan3D** [alicevision/meshroom#1154]
**Describe the bug**
Seriously, I've never encountered such incompetence. The images, clear cut iumages with lots of features, can not be recognized regardless of what detection method is used. Are you amateurs? That never happened with the commercial versions, which I highcly recommend using instead of the, I must call it that, crap you are producing. Now give it up or do better, much, much better.... can't be so hard now can it? Amatuers!
**To Reproduce**

**Expected behavior**

**Screenshots**

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ]
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1]
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**

**Comment by AlexKiryanov** [comment]
I think you should apologize for your post to the developer.
I'm shocked

**Comment by natowi** [comment]
There is no reason to use this kind of language. Other users also had problems with their images and they just asked for help.

**Comment by fabiencastan** [comment]
Sorry but your issue is crap :D
