### ISSUE TITLE
CR2 format issue

### ISSUE THREAD

**Issue by Hollywoodwp** [alicevision/meshroom#1158]
I recently purchased a  laptop with an Nvidia RTX2080 MaxQ processor intel i7 9750. I previously had a desktop with GTX970 and used the .CR2 files with no issues. I'm unsure if it's a glitch in Meshroom or if it's a compatibility issue with the card. I tried putting in a jpg file it worked but none of my .CR2 files do. Please help! 
![cr2 prob 1](https://user-images.githubusercontent.com/43288492/99718300-abb2dc80-2a78-11eb-90f5-9c4664644024.PNG)
![cr2 prob 2](https://user-images.githubusercontent.com/43288492/99718301-abb2dc80-2a78-11eb-9f17-68deb6eda720.PNG)

d.

**Comment by natowi** [comment]
Could you share a file for testing?

**Comment by Hollywoodwp** [comment]
Hi there! Thanks for the help. I wasn't able to upload .CR2 files to the Github so uploaded to my google drive folder for you

https://drive.google.com/drive/folders/1C7aTv_xt1ONokseXGPCB6JZLun5mlW4U?usp=sharing

**Comment by Hollywoodwp** [comment]
> Could you share a file for testing?
Hi there! Thanks for the help. I wasn't able to upload .CR2 files to the Github so uploaded to my google drive folder for you

https://drive.google.com/drive/folders/1C7aTv_xt1ONokseXGPCB6JZLun5mlW4U?usp=sharing

**Comment by natowi** [comment]
The link is not public. Just rename the .cr2 file to .txt to upload it to Github.

**Comment by Hollywoodwp** [comment]
> The link is not public. Just rename the .cr2 file to .txt to upload it to Github.

I tried uploading it to GitHub but it's too big. It won't take anything bigger than 10mb. But I made the same link public now. sorry about that

**Comment by natowi** [comment]
Thanks, I´ll give it a try.
