### ISSUE TITLE
Missing the object shown in SFM in version 2020.1.1 

### ISSUE THREAD

**Issue by Lev-Bat** [alicevision/meshroom#1161]
**Describe the problem**
missing the main object. 

**Screenshots**
![Screenshot 2020-11-20 162900](https://user-images.githubusercontent.com/74896706/99937650-82d76380-2d66-11eb-9aaf-5ec863b61047.jpg)

**Dataset**
![IMG20201120082238](https://user-images.githubusercontent.com/74896706/99937721-a7cbd680-2d66-11eb-88c9-0ef593b4969f.jpg)
![IMG20201120082324](https://user-images.githubusercontent.com/74896706/99937753-bb773d00-2d66-11eb-809f-153db5b12ca2.jpg)
![IMG20201120082349](https://user-images.githubusercontent.com/74896706/99937758-be722d80-2d66-11eb-86ee-2a0404ccb287.jpg)

**Log**
most common LOG: WARNING:root:Ignored NaN, Inf, or -Inf value.
if needed i will restart the whole process to get a good LOG - file.

**Desktop (please complete the following and other pertinent information):**
 - OS:win 10
 - AMD Ryzen 9 3900x 12-Core, 32GB RAM, GeForce RTX 2080
 - Unfortunately I use a cam from mobile phone - realme x2 pro - but added in "share/cameraSensors - Realme;Realme X2 Pro;4.37;devicespecifications" no problems detected
MAYBE the cam settings in "auto" mode keep getting me diffrent settings of each picture???
81 pictures were taken

**Additional context**
Read the #333, #359, #755 and more but none of them lead me to a successful result

KEEP ONLY THE LARGEST MESH -> unchecked

Thx for help!
Lev-Bat
(Germany)

**Comment by natowi** [comment]
The metallic surface is reflective, and featureless. Meshroom is unable to detect features on the surface of your model (and some parts are really thin):
![feaatannt](https://user-images.githubusercontent.com/8138537/99940646-e1074500-2d6c-11eb-8822-0824c3282f81.JPG)

You need to cover the surface with something to get some texture.

**Comment by Lev-Bat** [comment]
thank you for the (really fast) answer so far...
i should
a) paint the model somehow to be not reflective? -but in SFM is a fine dot range so i can easy imagine the model
why there is no *.obj output???
b) test meshroom with another object...? that would be sad!

my goal is to get a 3D Print out of the meshroom (+blender) results...

**Comment by natowi** [comment]
There are some tutorials out there (coating in removable spray, powder, paint sparkles from a brush,...)
The algorithm can is unable to imagine how the model is supposed to look like. If there is no data, the algorithm won´t produce a result.

The obj is only available with the meshing and the final texturing node
