### ISSUE TITLE
Resuming a stopped meshroom_photogrammetry

### ISSUE THREAD

**Issue by tmhab** [alicevision/meshroom#1165]
**Describe the problem**
I am unsure how to resume a previous call to meshroom_photogrammetry (with input images) that ended during Texturing.
I think that Texturing might be the last node but generally I am unsure how to resume a graph from the last running node.

**Screenshots**
N/A

**Dataset**
N/A

**Log**
N/A

**Desktop (please complete the following and other pertinent information):**
 - OS: Ubuntu
 - Binary version Meshroom-2020.1.0 for Linux

**Additional context**
I do have a few textures, a .mtl and an .obj file but the "status" file in the Texturing directory reads "status": "RUNNING" so I asume the node did not get to finish which makes sense since the working computer was likely stopped during the run.

I have read the --help but can not immediately understand how to managing (start, resume from running node) and configuring a graph.

**Comment by fabiencastan** [comment]
You should be able to launch the same command line again with '--forceStatus'.

**Comment by tmhab** [comment]
Do I need to tell meshroom_photogrammetry which files to continue on? Does it know from a '--cache' argument?

**Comment by fabiencastan** [comment]
If you launch the same command line, it will compute the same graph in the same place and found the already computed files in your cache.

**Comment by tmhab** [comment]
Looks like --forceStatus worked like I wanted - thanks! By the way - what does the Submitted status mean?

**Comment by fabiencastan** [comment]
It means that an instance is planning to compute this node.
For instance, if you open multiple Meshroom on the same files (usually from multiple machines sharing a storage). It is important when you submit a job on a renderfarm that will manage the scheduling on multiple machines.

**Comment by tmhab** [comment]
Thanks for explaining that! If you don't mind, I have another question: if I want to explore command-line configuration of meshroom_photogrammetry, is the best reference for settings, to use Meshroom to generate .mg files and reference the node reference on the doc site? https://meshroom-manual.readthedocs.io/en/latest/node-reference/node-reference.html

**Comment by fabiencastan** [comment]
I'm sorry I do not understand what is the question.
