### ISSUE TITLE
[question] Orthomosaic support

### ISSUE THREAD

**Issue by smarvar** [alicevision/meshroom#1171]
Hi AliceVision group.

Thanks for excellent work with the project Meshroom. I'm actually working with point cloud processing. I'm interested in can generate orthomosaic with UAV images.  How can I generated this Ortho?  Is there something implemented? examples?. 

Thanks for helping to community!

Steven.

**Comment by natowi** [comment]
No, at the moment Meshroom lacks many Geo-related features, including Orthomosaic generation. At the moment the best alternative for that is OpenDroneMap.

**Comment by smarvar** [comment]
Ok. Thanks for your response
