### ISSUE TITLE
LSCM Unwrap fail, Help! [Bugg]

### ISSUE THREAD

**Issue by simp91** [alicevision/meshroom#1172]
Hi i get this issue after i uv unrwrap with LSCM, done everything right even meshdecimate.
(Iam below 600k faces)

Error code: "OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix"
Abnormal program termination: received signal 11 (Segmentation fault: 11)

(Latest version Meshroom-2020.1.1-win64 wont work with LSCM
Older version Meshroom-2018.1.0-win64 it acually works with LSCM unwrap)

I have read and find a potential fix for this, but think i need some codeing skills for it, that i dont have.
If some one can help i be happy :)

I belive this thread has a fix but dont understand how to change files.
Texturing segfault fix #923

So far what i have read i think its a "geogram issue"

**Comment by natowi** [comment]
The fix https://github.com/alicevision/AliceVision/pull/923 will be included in a future build.

**Comment by ChrisDean** [comment]
As a simple quick fix/workaround for this (particularly if you're not a developer or similar) you can grab my OldTexturing node for 2020.1.x from here: https://github.com/ChrisDean/meshroom_nodes

Instructions on how to use are in the readme there

Hope it helps someone
