### ISSUE TITLE
[question] How to best achieve consistent scaling 

### ISSUE THREAD

**Issue by ChrisDean** [alicevision/meshroom#1175]
I have a rig of cameras setup in fixed positions around a subject.

For each subject I process through meshroom the scale is wildly different (everything is proprtionally correct but the scale varies massively).

What's the best way to get a consistent scale between meshroom runs of different subjects?

Will adding cctags help with this? 

If I get a full reconstruction of all cameras would setting their positions somehow remedy this?

If I can get a consistent scale I can then automate some further processes with a set scale factor on each sucessive run of meshroom using the SFM transform node but I'm just not sure how to best achieve a consistent scale in the first place.

Any help would be appreciated here

Thanks in advance.

**Comment by natowi** [comment]
CCTAGs can help with scaling and orientation https://github.com/alicevision/meshroom/wiki/CCTAG-scaling

If you use a fixed rig, you could compute the cameras with a dataset where all cameras are reconstructed and use it a) as reference for alignment or B) as SFM known camera input.

**Comment by ChrisDean** [comment]
Thanks for the link @natowi I will look at the cctag option but could use an SFM option now to fix a couple of immediate challenges I have (as I do have a construction where all cameras have been identified).

What would I hook up where in the workflow to do this?

I think I did see a ticket before on that somewhere with a reply from @fabiencastan suggesting similar but I didn't really understand how to apply what he was suggesting.

**Comment by natowi** [comment]
There are multiple solutions to this problem. Here is one:

1) compute the cameras with a dataset where all cameras are reconstructed, use cctags
2) orient and scale the model
3) save the sfm file as reference
4) reconstruct a new scene with your fixed rig
5) place a SfMAlignment node after the StructureFromMotion node
6) use the reference.sfm as reference to align your new scene to

**Comment by ChrisDean** [comment]
Thanks @natowi that worked great first time and seems so simple now you've laid out the steps 👍 

Something just wasn't computing for there process wise, but having followed this its actually really easy to sort out!
