### ISSUE TITLE
[bug] GUI crashes while preforming StructureFromMotion, but still computing in the background

### ISSUE THREAD

**Issue by Yuvix25** [alicevision/meshroom#1178]
**What Happens?**
While computing the StructureFromMotion on a large dataset (2401 photos), the gui crashes, but it is still computing in the background, so when it finishes and I reopen the GUI, it says "graph is being computed externally".

**Solution:**
Manually change the StructureFromMotion status from "RUNNING" to: "SUCCESS", and then in the Graph Editor click the 3 dots and then "Clear Pending Status".

**To Reproduce:**
Run Meshroom on a large dataset.

**Desktop (please complete the following and other pertinent information):**
 - OS: win 10
 - Python version: 3.7
 - Meshroom version: 2020.1.1
 - GPU: Nvidia GeForce GTX 1050 TI
 - CPU: Intel Core i7-4790

**Comment by natowi** [comment]
Could be related to this issue https://github.com/alicevision/meshroom/issues/1088

**Comment by Yuvix25** [comment]
It does not seem to be related
