### ISSUE TITLE
[request] Integrate AprilTag library for detection of markers (tag16h5 family) 

### ISSUE THREAD

**Issue by elektrokokke** [alicevision/meshroom#1179]
Corresponding Meshroom issue for AliceVision feature [issue 949](https://github.com/alicevision/AliceVision/issues/949).

In the modules where it makes sense, add "tag16h5" to the available describer types, enabling the usage of AprilTag markers from the tag16h5 family.

**Comment by natowi** [comment]
You don´t need to open an issue if you already opened a pull request
