### ISSUE TITLE
[question] alicevision_incrementalSfM seems to work but generates no output

### ISSUE THREAD

**Issue by videoDD** [alicevision/meshroom#1181]
**Describe the problem**
I'm trying to write a little python script to automate some steps, but after executing the incrementalSfM stops after detecting the GPU

I'm currently using the monstree dataset in full resolution, perhaps it's a typo or another little mistake.

**Log**
PS C:\Users\videoDD> aliceVision_incrementalSfM.exe -i A:\00_UNI_00\bachelor\testRun\cameraInit.sfm -o A:\00_UNI_00\bachelor\testRun\incrementalSFM\ -f A:\00_UNI_00\bachelor\testRun\featureMatching\ -m A:\00_UNI_00\bachelor\testRun\imageMatching\
Program called with the following parameters:
 * describerTypes = "sift" (default)
 * extraInfoFolder = "" (default)
 * featuresFolders =  = [A:\00_UNI_00\bachelor\testRun\featureMatching\]
 * initialPairA = "" (default)
 * initialPairB = "" (default)
 * input = "A:\00_UNI_00\bachelor\testRun\cameraInit.sfm"
 * interFileExtension = ".ply" (default)
 * localBAGraphDistance = 1 (default)
 * localizerEstimator =  Unknown Type "enum aliceVision::robustEstimation::ERobustEstimator" (default)
 * localizerEstimatorError = 0 (default)
 * localizerEstimatorMaxIterations = 4096 (default)
 * lockAllIntrinsics = 0 (default)
 * lockScenePreviouslyReconstructed = 1 (default)
 * matchesFolders =  = [A:\00_UNI_00\bachelor\testRun\imageMatching\]
 * maxAngleInitialPair = 40 (default)
 * maxNumberOfMatches = 0 (default)
 * maxReprojectionError = 4 (default)
 * minAngleForLandmark = 2 (default)
 * minAngleForTriangulation = 3 (default)
 * minAngleInitialPair = 5 (default)
 * minInputTrackLength = 2 (default)
 * minNumberOfObservationsForTriangulation = 2 (default)
 * output = "A:\00_UNI_00\bachelor\testRun\incrementalSFM\"
 * outputViewsAndPoses = "" (default)
 * useLocalBA = 0 (default)
 * useOnlyMatchesFromInputFolder = 0 (default)
 * useRigConstraint = 1 (default)
 * useTrackFiltering = 1 (default)
 * verboseLevel = "info" (default)

Loading features
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
[14:08:00.624821][info] Supported CUDA-Enabled GPU detected.

- OS: Win10.0.18363.1256
- Python 3.8.6
- Meshroom version: Meshroom-2019.2.0-win64

**Comment by ChemicalXandco** [comment]
Why not use [meshroom_compute](https://github.com/alicevision/meshroom/blob/develop/bin/meshroom_compute) or [meshroom_photogrammetry](https://github.com/alicevision/meshroom/blob/develop/bin/meshroom_photogrammetry)? This is the preferred way to run the pipeline from a command.

**Comment by natowi** [comment]
+ https://github.com/alicevision/AliceVision/wiki/CLI-Parameters

**Comment by videoDD** [comment]
Thank you I'll give it a try.
I wanted to get a better understanding of the individual steps and the pipeline.
