### ISSUE TITLE
Does meshroom support stereo-camera-image-based reconstructions that are metrically accurate?

### ISSUE THREAD

**Issue by jeremyma-tri** [alicevision/meshroom#1185]
I am interested in using Meshroom for scene reconstruction. I understand Meshroom can resolve scale iff an April Tag or CCTag is placed in the scene. However, what if a traditional stereo pair were to be used for the image aquisition? In particular: 

1) If i have a stereo pair (with known calibration, intrinsics and extrinsics) does Meshroom allow for loading in a list of left images and right images (while knowing which is left and which is right)? 

2) Can I specify to Meshroom the known intrinsics of each camera (left/right) and enforce Meshroom not to optimize those values when solving for the reconstruction?

3) Can I specify to Meshroom the known extrinsics between my two cameras (baseline) and enforce Meshroom not to optimize those values when solving for the reconstruction?

4) Will the resolved mesh and camera poses be metrically accurate since I have provided a pre-calibrated stereo pair?

Thanks

**Comment by natowi** [comment]
1. you can define a rig constraint https://github.com/alicevision/meshroom/wiki/Multi-Camera-Rig
2. you can define the intrinsics in the cameraInit node
3.  see1&2, some nodes allow overriding the auto-optimization when calibrated values are known
4. You can use CCTAGs, AprilTags are not yet fully implemented https://github.com/alicevision/meshroom/wiki/CCTAG-scaling

**Comment by jeremyma-tri** [comment]
Thanks for the response. With regards to (4), why would I need CCTAGS? by virtue of passing a left and right camera (calibrated rigid pair) one can solve for depth (using standard stereo matching along the epipolar lines) or back out the scale using a know distance between two views (left and right camera). 

My question is if Meshroom can resolve scale from left/right pairs and if the resultant mesh is metrically accurate without the need of any tag -- does that make sense?

**Comment by fabiencastan** [comment]
@jeremyma-tri
The easiest way would be to rescale the scene at the end using the SfMTransform. The option is only available "from_markers" for now, but you can easily add the same option "from_cameras". So you choose 2 cameras of your known rig and rescale the scene from that.

You should also be able to create the rig and setup the sub-poses as "ERigSubPoseStatus::CONSTANT". The only problem is that for now the resection is single view only. There is a multi-cameras resection functions but it is not yet used within the SfM. If you are interested in looking into that, it would be a very interesting contribution and we will be happy to help you.

**Comment by natowi** [comment]
> why would I need CCTAGS?

@jeremyma-tri  At the moment this is the only way to automatically set a reference distance to scale the scene.

> option "from_cameras". So you choose 2 cameras of your known rig and rescale the scene from that.

@fabiencastan SfMTransform has the option "auto_from_cameras" - could you please explain the usage?

**Comment by fabiencastan** [comment]
auto_from_cameras: fit a bounding box around the cameras
auto_from_landmarks: fit a bounding box around the 3d points

**Comment by natowi** [comment]
> but you can easily add the same option "from_cameras". So you choose 2 cameras of your known rig and rescale the scene from that.

With "you can easily add" you mean "you can easily implement a new from_cameras option to solve this problem" ?
I was irritated the first time, as I was not aware of such a feature already being implemented. It would be a great addition indeed (adding cameras with filename or view_ID similar to the from_markers menu).

**Comment by elektrokokke** [comment]
Don't know whether extrinsics within a rig can be given and fixed currently.

If not, the easiest you can do is look into the .sfm output of the StructureFromMotion node, look for the two cameras, and adjust the scale manually with the SfmTransform node according to the relation between reconstructed and actual distance between the cameras.

**Comment by jeremyma-tri** [comment]
thanks you everyone for the responses. I will try the suggested methods.

**Comment by ajay098patro** [comment]
Hy, I have no experience in Photogrammetry software as well as coding and my works require a DSM that is not available for my study or and other the only method that i see is a stereo image pair for my study are to create, is it possible to create a mesh using two stereo images in meshroom, like erdas, envi, metashape does to create a DSM.

**Comment by natowi** [comment]
@ajay098patro For DSM best take a look at [opendronemap](https://opendronemap.org)
