### ISSUE TITLE
Panorama pipeline error

### ISSUE THREAD

**Issue by EmilienCerem** [alicevision/meshroom#1186]
Hello everybody, 

I am a student in an internship and i am searching for help on an issue . I would like to create a panorama using meshroom. I am using the basic pipeline that we can generate with "File -> new pipeline -> Panorama HDR". I put my dataset (the front of a house) and launch the process but the "Panorama Compositing" node make an error "bad allocation". I'm new to this software and photogrammetry. Can you help me ? 

My second question is, can we only use a stitching pipeline to have a picture that is not curved (not a panorama but more like an orthophoto) with meshroom ?

**Comment by natowi** [comment]
At the moment the Meshroom panorama pipeline only supports _360° panoramas_. Hugin is an open source software specialized in panorama stitching http://hugin.sourceforge.net/tutorials/multi-row/en.shtml. 
Adding similar support to Meshroom - especially orthophoto stitching- is something to consider in the long term.

**Comment by EmilienCerem** [comment]
> At the moment the Meshroom panorama pipeline only supports _360° panoramas_. Hugin is an open source software specialized in panorama stitching http://hugin.sourceforge.net/tutorials/multi-row/en.shtml.
> Adding similar support to Meshroom - especially orthophoto stitching- is something for a future contribution.

Is it a near future ?

**Comment by natowi** [comment]
It is one of many things on the already long wish-list.
