### ISSUE TITLE
Stuck at meshing - Meshroom 2018.1.0, windows 10

### ISSUE THREAD

**Issue by robinaerts** [alicevision/meshroom#1187]
I'm quite new to meshroom and tried it out today, but I keep getting stuck at the meshing step. I'm using the 2018 version because I had some issues with the other versions and I have already come far with the model in this version.

Here's my log:

Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, ExportUndistortedImages, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[QtOIIO] Plugin Initialized
[DepthMapEntity] DepthMapEntity
Failed to download scene at QUrl("")
Nodes to execute:  ['Meshing_1', 'MeshFiltering_1', 'Texturing_1']
WARNING: downgrade status on node "Meshing_1" from Status.ERROR to Status.SUBMITTED

[1/3] Meshing
 - commandLine: aliceVision_meshing  --ini "D:/3D SCANNING/MeshroomCache/PrepareDenseScene/d4f2fe0288faccd809f268779b6ead0ac29a80d2/mvs.ini" --depthMapFolder "D:/3D SCANNING/MeshroomCache/DepthMap/1413f160584767dda1896868077889fc94e879d6" --depthMapFilterFolder "D:/3D SCANNING/MeshroomCache/DepthMapFilter/62cc69d85a9aeae9030fe17d84ed968667aeddce" --maxInputPoints 50000000 --maxPoints 5000000 --maxPointsPerVoxel 1000000 --minStep 2 --partitioning singleBlock --repartition multiResolution --angleFactor 15.0 --simFactor 15.0 --pixSizeMarginInitCoef 2.0 --pixSizeMarginFinalCoef 4.0 --voteMarginFactor 4.0 --contributeMarginFactor 2.0 --simGaussianSizeInit 10.0 --simGaussianSize 10.0 --minAngleThreshold 1.0 --refineFuse True --verboseLevel info --output "D:/3D SCANNING/MeshroomCache/Meshing/ba0e6b2e43d08dfe7c6b1acb20efdbe733078a38/mesh.obj"
 - logFile: D:/3D SCANNING/MeshroomCache/Meshing/ba0e6b2e43d08dfe7c6b1acb20efdbe733078a38/log
 - elapsed time: 0:00:08.109098
ERROR:root:Error on node computation: Error on node "Meshing_1":
Log:
Program called with the following parameters:
 * angleFactor = 15
 * contributeMarginFactor = 2
 * depthMapFilterFolder = "D:/3D SCANNING/MeshroomCache/DepthMapFilter/62cc69d85a9aeae9030fe17d84ed968667aeddce"
 * depthMapFolder = "D:/3D SCANNING/MeshroomCache/DepthMap/1413f160584767dda1896868077889fc94e879d6"
 * ini = "D:/3D SCANNING/MeshroomCache/PrepareDenseScene/d4f2fe0288faccd809f268779b6ead0ac29a80d2/mvs.ini"
 * maxInputPoints = 50000000
 * maxPoints = 5000000
 * maxPointsPerVoxel = 1000000
 * minAngleThreshold = 1
 * minStep = 2
 * output = "D:/3D SCANNING/MeshroomCache/Meshing/ba0e6b2e43d08dfe7c6b1acb20efdbe733078a38/mesh.obj"
 * partitioning =  Unknown Type "enum EPartitioningMode"
 * pixSizeMarginFinalCoef = 4
 * pixSizeMarginInitCoef = 2
 * refineFuse = 1
 * repartition =  Unknown Type "enum ERepartitionMode"
 * simFactor = 15
 * simGaussianSize = 10
 * simGaussianSizeInit = 10
 * verboseLevel = "info"
 * voteMarginFactor = 4

[16:38:03.495747][info] Found 1 image dimension(s):
[16:38:03.497747][info]  - [4624x2604]
[16:38:03.610747][info] Overall maximum dimension: [2312x1302]
[16:38:03.610747][warning] repartitionMode: 1
[16:38:03.610747][warning] partitioningMode: 1
[16:38:03.610747][info] Meshing mode: multi-resolution, partitioning: single block.
[16:38:03.611748][info] Estimate space.

WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "Meshing_1":
Log:
Program called with the following parameters:
 * angleFactor = 15
 * contributeMarginFactor = 2
 * depthMapFilterFolder = "D:/3D SCANNING/MeshroomCache/DepthMapFilter/62cc69d85a9aeae9030fe17d84ed968667aeddce"
 * depthMapFolder = "D:/3D SCANNING/MeshroomCache/DepthMap/1413f160584767dda1896868077889fc94e879d6"
 * ini = "D:/3D SCANNING/MeshroomCache/PrepareDenseScene/d4f2fe0288faccd809f268779b6ead0ac29a80d2/mvs.ini"
 * maxInputPoints = 50000000
 * maxPoints = 5000000
 * maxPointsPerVoxel = 1000000
 * minAngleThreshold = 1
 * minStep = 2
 * output = "D:/3D SCANNING/MeshroomCache/Meshing/ba0e6b2e43d08dfe7c6b1acb20efdbe733078a38/mesh.obj"
 * partitioning =  Unknown Type "enum EPartitioningMode"
 * pixSizeMarginFinalCoef = 4
 * pixSizeMarginInitCoef = 2
 * refineFuse = 1
 * repartition =  Unknown Type "enum ERepartitionMode"
 * simFactor = 15
 * simGaussianSize = 10
 * simGaussianSizeInit = 10
 * verboseLevel = "info"
 * voteMarginFactor = 4

[16:38:03.495747][info] Found 1 image dimension(s):
[16:38:03.497747][info]  - [4624x2604]
[16:38:03.610747][info] Overall maximum dimension: [2312x1302]
[16:38:03.610747][warning] repartitionMode: 1
[16:38:03.610747][warning] partitioningMode: 1
[16:38:03.610747][info] Meshing mode: multi-resolution, partitioning: single block.
[16:38:03.611748][info] Estimate space.

I have already tried to change the 'max-points' value, but because that didn't solve it, I've set it back to the default values.

**Comment by natowi** [comment]
Most of the issues are related to dataset problems. Can you provide a screenshot of Meshroom with the computed nodes? How many images were reconstructed in the sfm? How many points does the sfm have? 

The Meshing can fail when there is not enough to mesh.

**Comment by robinaerts** [comment]
Here is a screenshot:
![image](https://user-images.githubusercontent.com/67053248/102694326-96b89d00-4220-11eb-8fa1-4a0f8aab8613.png)


It's made up of 87 images.

**Comment by natowi** [comment]
All images were reconstructed, that´s a good sign. Now I would check the reconstructed features, the feature viewer and the depthMap, but the gui features are not available in the 2018 release. It is possible that the point cloud of your figure is not dense enough to mesh. Hard to say this far zoomed out.

What were the issues with the newer releases?

**Comment by robinaerts** [comment]
I had an issue with the DepthMap, but I tried it again today and it worked. So my problem is solved, thank you!
