### ISSUE TITLE
Feature Matching Issue loadPairs: Impossible 

### ISSUE THREAD

**Issue by VIRUSPOINTPLUS** [alicevision/meshroom#1188]
Hi,

New user of Meshroom, i don't understand this error :

[20:18:52.083949][warning] loadPairs: Impossible to read the specified file: "D:/LOLA/3D/MeshroomCache/ImageMatching/984c6adc896c84dd910483e88a5620c198ce97a4/imageMatches.txt".

What does it means?

I try to mesh a tailor dummy (72 pictures taken in studio photo)

I tried several settings with same results.

Thank you for you help !

Another try with same results:
Program called with the following parameters:
 * describerTypes = "sift"
 * distanceRatio = 0.8
 * exportDebugFiles = 0
 * featuresFolders =  = [D:/LOLA/3D/MeshroomCache/FeatureExtraction/b04f7d00b5515b2b094b129c605ec674fcad1798]
 * geometricError = 0
 * geometricEstimator =  Unknown Type "enum aliceVision::robustEstimation::ERobustEstimator"
 * geometricFilterType = "fundamental_matrix"
 * guidedMatching = 0
 * imagePairsList =  = [D:/LOLA/3D/MeshroomCache/ImageMatching/f516f8a2b09301c664d7878ea027136cd38fec79/imageMatches.txt]
 * input = "D:/LOLA/3D/MeshroomCache/CameraInit/ac9b5b70ab10012b2c8aa3e500a2c2cb016cf35a/cameraInit.sfm"
 * knownPosesGeometricErrorMax = 5
 * matchFilePerImage = 0 (default)
 * matchFromKnownCameraPoses = 0
 * maxIteration = 2048
 * maxMatches = 0
 * output = "D:/LOLA/3D/MeshroomCache/FeatureMatching/f6dfee16ec6543e19df84fbc16be52c1c7cc428b"
 * photometricMatchingMethod = "ANN_L2"
 * rangeSize = 20
 * rangeStart = 0
 * savePutativeMatches = 0
 * useGridSort = 1 (default)
 * verboseLevel = "info"

[20:27:05.840731][info] Load pair list from file: D:/LOLA/3D/MeshroomCache/ImageMatching/f516f8a2b09301c664d7878ea027136cd38fec79/imageMatches.txt
[20:27:05.840731][warning] loadPairs: Impossible to read the specified file: "D:/LOLA/3D/MeshroomCache/ImageMatching/f516f8a2b09301c664d7878ea027136cd38fec79/imageMatches.txt".

**Comment by gnbl** [comment]
Maybe related to https://github.com/alicevision/meshroom/issues/1311
