### ISSUE TITLE
Nothing in the 3D viewer

### ISSUE THREAD

**Issue by Olivertwisst** [alicevision/meshroom#1192]
**Describe the problem**
A clear and concise description of what the problem is.

**Screenshots**

**Dataset**
If applicable, add a link or *few* images to help better understand where the problem may come from.

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ]
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1]
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**

**Comment by Olivertwisst** [comment]
Hi,
after a successful computation of the SFM node, I've got nothing displayed in the 3D viewer. 

My system:
Windows 10
Intel core i7 9750H CPU 2.6GHz
16Gb RAM
Python 3.9.1
Meshroom V2020.1.1
QT/pyside: absolutely no idea of how to get and install this thing (even after careful review of your GH docs...), but I believe this should be all included with the version of Meshroom I'm using... Surely hope so because if not I'm screwed ;-)

Meshroom is working just fine because the .abc file is created and I can import it in Blender with no problem. But it's impossible to load it in the 3D viewer with drag and drop or double click on the node.

I made all the recommended updates: Nvidia, visualbasic, ... 
I assigned the graphic GPU to Meshroom in the Nvidia control panel.

Here is a printscreen of my project.

![image](https://user-images.githubusercontent.com/76439679/102792384-ba0e5400-43a8-11eb-8eab-a43f827ea097.png)

My picture are crappy and the model is not prepared accordingly to what I read here and there (shiny surfaces) so the features detected are not the best. But for now I just want to make Meshroom work.

In the 2nd panel I've got this message at the end of computation though: 

WARNING:root:Ignored NaN, Inf, or -Inf value.

Looking forward to read you.
Thanks in advance.

**Comment by Olivertwisst** [comment]
And sorry for the printscreen, I have dual screens...

**Comment by Olivertwisst** [comment]
This should be better

![image](https://user-images.githubusercontent.com/76439679/102793866-c8f60600-43aa-11eb-8b87-790357e7d582.png)

**Comment by natowi** [comment]
Yes there are a few gui issues with the 2020 release. Sometimes restarting Meshroom or computing the full graph helps fixing this problem. If you need something reliable, you can use the 2019.2 release.

**Comment by Olivertwisst** [comment]
Thanks for your quick answer.

I just tried as suggested with the same result but the log is slightly different with some errors, but the .abc is still OK and importable in Blender.

Here is the log:

Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportColoredPointCloud, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, LDRToHDR, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:\Users\mwall\AppData\Local\Temp\tmpi4cimd7t/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm"
 * output = "C:/Users/mwall/AppData/Local/Temp/tmpi4cimd7t/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm"
 * sensorDatabase = "C:\Users\mwall\Desktop\Meshroom-2019.2.0\aliceVision\share\aliceVision\cameraSensors.db"
 * verboseLevel = "info"

[18:04:02.487566][warning] Some image(s) have no serial number to identify the camera/lens device.
This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximation they will share the same internal camera parameters.
36 image(s) are concerned.
[18:04:02.490054][warning] The camera found in the database is slightly different for image(s):
[18:04:02.490054][warning] image: 'DSCN2371.JPG'
        - image camera brand: NIKON
        - image camera model: COOLPIX L840
        - database camera brand: Nikon
        - database camera model: Nikon Coolpix L840
        - database camera sensor size: 6.17 mm
[18:04:02.490983][warning] Please check and correct camera model(s) name in the database.

[18:04:02.536924][info] CameraInit report:
        - # views listed: 36
           - # views with an initialized intrinsic listed: 36
           - # views without metadata (with a default intrinsic): 0
        - # intrinsics listed: 3
Nodes to execute:  ['CameraInit_1', 'FeatureExtraction_1', 'ImageMatching_1', 'FeatureMatching_1', 'StructureFromMotion_1']

[1/5] CameraInit
 - commandLine: aliceVision_cameraInit  --sensorDatabase "C:\Users\mwall\Desktop\Meshroom-2019.2.0\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/CameraInit/82103a1d87bc17c44e3cd342158f4ab0a6d7f44b/cameraInit.sfm" --allowSingleView 1  --input "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/CameraInit/82103a1d87bc17c44e3cd342158f4ab0a6d7f44b//viewpoints.sfm"
 - logFile: C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/CameraInit/82103a1d87bc17c44e3cd342158f4ab0a6d7f44b/log
 - elapsed time: 0:00:00.297443

[2/5] FeatureExtraction
 - commandLine: aliceVision_featureExtraction  --input "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/CameraInit/82103a1d87bc17c44e3cd342158f4ab0a6d7f44b/cameraInit.sfm" --describerTypes sift --describerPreset high --forceCpuExtraction True --verboseLevel info --output "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/FeatureExtraction/3b4ed163717de50ad2832dfdac1c51b64a6b7145" --rangeStart 0 --rangeSize 40
 - logFile: C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/FeatureExtraction/3b4ed163717de50ad2832dfdac1c51b64a6b7145/0.log
 - elapsed time: 0:01:07.096397

[3/5] ImageMatching
 - commandLine: aliceVision_imageMatching  --input "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/CameraInit/82103a1d87bc17c44e3cd342158f4ab0a6d7f44b/cameraInit.sfm" --featuresFolders "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/FeatureExtraction/3b4ed163717de50ad2832dfdac1c51b64a6b7145" --tree "C:\Users\mwall\Desktop\Meshroom-2019.2.0\aliceVision\share\aliceVision\vlfeat_K80L3.SIFT.tree" --weights "" --minNbImages 200 --maxDescriptors 500 --nbMatches 50 --verboseLevel info --output "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/ImageMatching/455aaf1e6c9e9ce4c960856a04ac6ff937ce455a/imageMatches.txt"
 - logFile: C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/ImageMatching/455aaf1e6c9e9ce4c960856a04ac6ff937ce455a/log
 - elapsed time: 0:00:00.287901

[4/5](1/2) FeatureMatching
 - commandLine: aliceVision_featureMatching  --input "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/CameraInit/82103a1d87bc17c44e3cd342158f4ab0a6d7f44b/cameraInit.sfm" --featuresFolders "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/FeatureExtraction/3b4ed163717de50ad2832dfdac1c51b64a6b7145" --imagePairsList "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/ImageMatching/455aaf1e6c9e9ce4c960856a04ac6ff937ce455a/imageMatches.txt" --describerTypes sift --photometricMatchingMethod ANN_L2 --geometricEstimator acransac --geometricFilterType fundamental_matrix --distanceRatio 0.8 --maxIteration 2048 --geometricError 0.0 --maxMatches 0 --savePutativeMatches False --guidedMatching True --exportDebugFiles False --verboseLevel info --output "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/FeatureMatching/6eb904b077875e17f7e3799d1ce98ba5a49786e9" --rangeStart 0 --rangeSize 20
 - logFile: C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/FeatureMatching/6eb904b077875e17f7e3799d1ce98ba5a49786e9/0.log
 - elapsed time: 0:15:02.818619

[4/5](2/2) FeatureMatching
 - commandLine: aliceVision_featureMatching  --input "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/CameraInit/82103a1d87bc17c44e3cd342158f4ab0a6d7f44b/cameraInit.sfm" --featuresFolders "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/FeatureExtraction/3b4ed163717de50ad2832dfdac1c51b64a6b7145" --imagePairsList "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/ImageMatching/455aaf1e6c9e9ce4c960856a04ac6ff937ce455a/imageMatches.txt" --describerTypes sift --photometricMatchingMethod ANN_L2 --geometricEstimator acransac --geometricFilterType fundamental_matrix --distanceRatio 0.8 --maxIteration 2048 --geometricError 0.0 --maxMatches 0 --savePutativeMatches False --guidedMatching True --exportDebugFiles False --verboseLevel info --output "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/FeatureMatching/6eb904b077875e17f7e3799d1ce98ba5a49786e9" --rangeStart 20 --rangeSize 20
 - logFile: C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/FeatureMatching/6eb904b077875e17f7e3799d1ce98ba5a49786e9/1.log
 - elapsed time: 0:03:25.276059

[5/5] StructureFromMotion
 - commandLine: aliceVision_incrementalSfM  --input "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/CameraInit/82103a1d87bc17c44e3cd342158f4ab0a6d7f44b/cameraInit.sfm" --featuresFolders "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/FeatureExtraction/3b4ed163717de50ad2832dfdac1c51b64a6b7145" --matchesFolders "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/FeatureMatching/6eb904b077875e17f7e3799d1ce98ba5a49786e9" --describerTypes sift --localizerEstimator acransac --localizerEstimatorMaxIterations 4096 --localizerEstimatorError 0.0 --lockScenePreviouslyReconstructed False --useLocalBA True --localBAGraphDistance 1 --maxNumberOfMatches 0 --minInputTrackLength 2 --minNumberOfObservationsForTriangulation 2 --minAngleForTriangulation 3.0 --minAngleForLandmark 2.0 --maxReprojectionError 4.0 --minAngleInitialPair 5.0 --maxAngleInitialPair 40.0 --useOnlyMatchesFromInputFolder False --useRigConstraint True --lockAllIntrinsics False --initialPairA "" --initialPairB "" --interFileExtension .abc --verboseLevel info --output "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/StructureFromMotion/68c69ad622d2a74db97ac6c15b12fb318d8b3f07/sfm.abc" --outputViewsAndPoses "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/StructureFromMotion/68c69ad622d2a74db97ac6c15b12fb318d8b3f07/cameras.sfm" --extraInfoFolder "C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/StructureFromMotion/68c69ad622d2a74db97ac6c15b12fb318d8b3f07"
 - logFile: C:/Users/mwall/Desktop/Mes modèles/Carrosseries/Clio maxi/Meshroom/MeshroomCache/StructureFromMotion/68c69ad622d2a74db97ac6c15b12fb318d8b3f07/log
 - elapsed time: 0:00:27.332736
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: C:\GitHub\vcpkg\buildtrees\hdf5\src\hdf5-c7a3a597c4\hdf5-1.10.5\src\H5F.c line 370 in H5Fis_hdf5(): unable open file
    major: File accessibilty
    minor: Not an HDF5 file
  #001: C:\GitHub\vcpkg\buildtrees\hdf5\src\hdf5-c7a3a597c4\hdf5-1.10.5\src\H5Fint.c line 826 in H5F__is_hdf5(): unable to open file
    major: Low-level I/O
    minor: Unable to initialize object
  #002: C:\GitHub\vcpkg\buildtrees\hdf5\src\hdf5-c7a3a597c4\hdf5-1.10.5\src\H5FD.c line 734 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: C:\GitHub\vcpkg\buildtrees\hdf5\src\hdf5-c7a3a597c4\hdf5-1.10.5\src\H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = 'C:/Users/mwall/Desktop/Mes mod├¿les/Carrosseries/Clio maxi/Meshroom/MeshroomCache/StructureFromMotion/68c69ad622d2a74db97ac6c15b12fb318d8b3f07/sfm.abc', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: C:\GitHub\vcpkg\buildtrees\hdf5\src\hdf5-c7a3a597c4\hdf5-1.10.5\src\H5F.c line 370 in H5Fis_hdf5(): unable open file
    major: File accessibilty
    minor: Not an HDF5 file
  #001: C:\GitHub\vcpkg\buildtrees\hdf5\src\hdf5-c7a3a597c4\hdf5-1.10.5\src\H5Fint.c line 826 in H5F__is_hdf5(): unable to open file
    major: Low-level I/O
    minor: Unable to initialize object
  #002: C:\GitHub\vcpkg\buildtrees\hdf5\src\hdf5-c7a3a597c4\hdf5-1.10.5\src\H5FD.c line 734 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: C:\GitHub\vcpkg\buildtrees\hdf5\src\hdf5-c7a3a597c4\hdf5-1.10.5\src\H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = 'C:/Users/mwall/Desktop/Mes mod├¿les/Carrosseries/Clio maxi/Meshroom/MeshroomCache/StructureFromMotion/68c69ad622d2a74db97ac6c15b12fb318d8b3f07/sfm.abc', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file



And here the printscreen:

![image](https://user-images.githubusercontent.com/76439679/102805646-d36ccb80-43bb-11eb-915d-17bb62e44ab7.png)

**Comment by natowi** [comment]
Here is the problem: 

>Mes mod├¿les

avoid special characters/non-ASCII characters in Meshroom and images file paths

**Comment by Olivertwisst** [comment]
simple as that...

The path is now clean and everything works flawlessly:

![image](https://user-images.githubusercontent.com/76439679/102808759-1d0be500-43c1-11eb-9ab9-66e8bf94d12e.png)

Now I can spend long hours learning how to take pictures like a pro ;-)

Thank you very much for your help and for your work!
You and your team are awesome to have made such a software available to all for free and to be responsive like this!

**Comment by natowi** [comment]
This should also work with the 2020 version. 

Here are a few tutorials I can recommend: https://github.com/alicevision/meshroom/wiki/Tutorials

Feel free to ask if you have any more questions.
