### ISSUE TITLE
[bug] Cannot import images.

### ISSUE THREAD

**Issue by dreisicht** [alicevision/meshroom#1194]
**Describe the bug**
Images cannot be imported.

**To Reproduce**
Drag and drop image files into meshroom or use the import menu.

Following error message comes up using drag and drop:
```
Failed to Import Images - Meshroom 2020.1.1
You probably have a corrupted image within the images that you are trying to import.
```

**Expected behavior**
Images get imported.

**Screenshots**

**Log**
Following error message is shown in the console using the import menu.
```
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )
WARNING:root:importFilesDialog fileUrls: file:///C:/Users/peter/Desktop/AL_DJI_0034.jpg
ERROR:root:Error while building intrinsics: [WinError 2] No such file or directory
Traceback (most recent call last):
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 817, in importImagesUrls
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 804, in importImagesFromFolder
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 873, in buildIntrinsics
  File "d:\release\BUILD\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 264, in buildIntrinsics
  File "d:\release\BUILD\meshroom\venv\lib\site-packages\psutil\__init__.py", line 1332, in __init__
  File "C:\Program Files\Python37\lib\subprocess.py", line 775, in __init__
  File "C:\Program Files\Python37\lib\subprocess.py", line 1178, in _execute_child
FileNotFoundError: [WinError 2] No such file or directory
WARNING:root:Model size of -145 is less than 0
WARNING:root:Model size of -9 is less than 0
```

**Desktop (please complete the following and other pertinent information):**
 - OS: Win 10
 - Python version 3.9
 - Qt/PySide version not installed
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2020.1.1]

**Additional context**

**Failed attempts of solving the issue** 
- Reinstalling Python
- Using older versions of Meshroom (up to 2018.1)
- reinstalling graphics drivers
- reinstalling Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019

**Comment by natowi** [comment]
> WARNING:root:Model size of -145 is less than 0

> file:///C:/Users/peter/Desktop/AL_DJI_0034.jpg

could be an access restriction, try using another path like D:/...

If this does not help, check your image metadata.

The import module from AliceVision has problems parsing corrupted image files.
Some cameras produce images which are not valid. Most image viewers and editing software can handle minor inconsistencies. 

Use tools like [Bad Peggy](https://www.coderslagoon.com/) to [search for errors](http://openpreservation.org/blog/2016/11/29/jpegvalidation/) in your image files (JPEG, PNG, BMP, GIF).

e.g. "_...extraneous bytes before marker 0xdb_".

or "Truncated File - Missing EOI marker"

If you find the images are corrupted, you need to bulk convert your dataset  to fix this problem.
You can use IrfranView `File->Batch Conversion` or Imagemagick. Make sure you set the quality to 100%. Now you can add the images to Meshroom (assuming the camera is in the sensor db).

**Comment by r33p** [comment]
can it be related to this one ? :
https://github.com/alicevision/meshroom/issues/1168
