### ISSUE TITLE
MEshroom ui does not start on centos 7 with xfce

### ISSUE THREAD

**Issue by Amjadhpc** [alicevision/meshroom#1195]
**Describe the problem**
I downloaded the Linux binaries in centos 7 box  with xfce desktop manager.

**Screenshots**
When i try to start Meshroom ui, it gives the following error.
 /gpfs/software/ada/build/Meshroom/Meshroom-2020.1.0/Meshroom
qt.qpa.xcb: X server does not support XInput 2
WARNING:root:qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
WARNING:root:qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
WARNING:root:qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
**CRITICAL:root:Could not initialize GLX**
Aborted

**Dataset**
If applicable, add a link or *few* images to help better understand where the problem may come from.

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: centos 7
 - Python version [e.g. 2.6] 3.8 
 - Qt/PySide version [e.g. 5.12.4]: Qt version Py Qt5.9
 - Meshroom version: please specif
   - Binary version (if applicable) [e.g. 2019.1] 2020.1.0
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**
The installation is on shared location running /gpfs file system  on a HPC cluster

**Comment by natowi** [comment]
I can not help with the specific error message, but if you intend to run Meshroom on a cluster, you don´t need to use the Meshroom GUI. You can run Meshroom projects prepared on a desktop computer from the cli https://github.com/alicevision/AliceVision/wiki/CLI-Parameters and you could even write a renderfarm submitter https://github.com/alicevision/meshroom/wiki/Renderfarm-submitters
