### ISSUE TITLE
Combining terrestrial and aerial footage

### ISSUE THREAD

**Issue by Tomma49** [alicevision/meshroom#1197]
I'm trying to build a 3D model that combines images captured on a Phantom 4 Pro V2 and an Apple iPhone 6.  The images from the iPhone will work when loaded on their own but when the Phantom files are added the iPhone images are not reconstructed.  How can I use images captured on the two different cameras?

**Comment by natowi** [comment]
Your drone and camera footage need to have a sufficient overlap.

**Comment by Tomma49** [comment]
Thanks for the prompt response Simon.  That makes sense.  Is there a way in the software to view the overlap between photographs?

**Comment by natowi** [comment]
At the moment you can only use the image viewer to check your images.
The best way to make sure you have a good image overlap is to use a flight mission planner to capture images in sphere.

Capturing method A will give good results each, but not combined. Method B provides a seamless transition.
![overl](https://user-images.githubusercontent.com/8138537/103169238-4c47a980-483a-11eb-8bba-5dc2449b947a.jpg)
The overlap between images should be 60%+.

(Similar issue https://github.com/alicevision/meshroom/issues/1063)

**Comment by Tomma49** [comment]
Thanks Simon, I had a bit of a hybrid scenario between A & B but must not have given myself enough overlap between the aerial and terrestrial images. I'll try again in the new year and ensure I have a lot more overlap between the images like in scenario B above.
