### ISSUE TITLE
Using google Colab to run meshroom - how to change a default setting? [question]

### ISSUE THREAD

**Issue by RayzedByRobots** [alicevision/meshroom#1200]
Hi  - I'm using google colab to run meshroom in the cloud. Here are the link and video that describes the process: https://www.youtube.com/watch?v=xcN_UaZUKew

This meshroom copy runs with all of the default settings. I now want to change one setting in Meshroom prior to running - I want to use guided matching, but I can't figure out how to change this setting in this cloud version of meshroom? The setting I want to change lives in the FeatureMatching node. 

When I'm in the colab notebook, I can mount my drive, load meshroom and then navigate to the featureMatching folder - where I would expect to find the code I need to change, but when I double click it looks like machine code. 

Path to the featureMatching Node: 
/content/meshroom/Meshroom-2019.1.0/aliceVision/bin/aliceVision_featureMatching-1.0

Thanks

**Comment by 5685C4A059D5** [comment]
You can setup the pipeline on your computer with the GUI, save the graph file, fix paths then run meshroom_compute with the graph file on colab.
There's a guide at the end of the colab wiki page.

**Comment by RayzedByRobots** [comment]
@5685C4A059D5 very helpful thank you for your answer. Here is the link to the wiki: 

https://github.com/alicevision/meshroom/wiki/Meshroom-in-Google-Colab-(cloud). Thanks I'll try this.
