### ISSUE TITLE
When I try to drag in my images, it says: "The images are corrupted". I have Visual C++, so I really don't know what causes the problem.

### ISSUE THREAD

**Issue by MrDwinkley** [alicevision/meshroom#1201]
**Describe the problem**
A clear and concise description of what the problem is.

**Screenshots**

**Dataset**
If applicable, add a link or *few* images to help better understand where the problem may come from.

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ]
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1]
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**

**Comment by MrDwinkley** [comment]
I use the version 2020.1.1

**Comment by natowi** [comment]
What camera do you use? Do the images show up in the image viewer in Meshroom? Does the reconstruction work?
