### ISSUE TITLE
Feature shown in SFM not reconstructed in mesh[question]

### ISSUE THREAD

**Issue by 295361179** [alicevision/meshroom#1202]
Hi,
I'm trying to reconstruct an insect model. The SFM result looks good, all the legs/antennas were included in the point cloud, but they were not reconstructed in the final mesh. I want to ask if there is a way to improve such result or these features are just too thin for meshroom to reconstruct? The following are some sample input images and screen shots of the result

[sample.zip](https://github.com/alicevision/meshroom/files/5756426/sample.zip)
![meshroom](https://user-images.githubusercontent.com/76801381/103393971-b1223d00-4b75-11eb-9cca-eb20c4675ff6.JPG)
![mesh](https://user-images.githubusercontent.com/76801381/103393968-acf61f80-4b75-11eb-92ed-f0d79ab6daea.JPG)

**Comment by natowi** [comment]
As you can see in the pointcloud, the pointcloud is sparse in the leg areas. It´s not dense enough for proper meshing. You could try playing  with https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters.

Can you get any closer? The insect should fill most of the image.
