### ISSUE TITLE
dense point cloud is less dense than sparse point cloud?

### ISSUE THREAD

**Issue by WenTheProgrammer** [alicevision/meshroom#1203]
I have a set of aerial images taken over an apple orchard. I tried to reconstruct a dense orchard point cloud using the standard photogrammetry pipeline. I wanted to output the dense point cloud from the Meshing node, but I noticed that the dense point cloud is not only not "dense" (as a reference other 3D reconstruction software can achieve around 350,000 points) , but even more sparse than the sparse point cloud from the StructureFromMotion node:
![Untitled](https://user-images.githubusercontent.com/67032259/103432260-5eaf4380-4baa-11eb-8514-89949db25700.png)
I don't understand what is wrong so any help is greatly appreaciated!

**Comment by natowi** [comment]
For meshing, this is not the point cloud density, its the poly-count.
To get the dense point cloud, open the Meshing node folder (densePointCloud.abc). You can drag and drop it in the 3d viewer and use the convertsfmformat node with describer type "unknown" enabled to convert the abc file to an other format.

**Comment by WenTheProgrammer** [comment]
I just reconstructed a model and I got the same result:
![Untitled](https://user-images.githubusercontent.com/67032259/103489898-f51b7900-4de5-11eb-89c6-d66c8e27714b.png)

**Comment by natowi** [comment]
Hard to say without seeing the images, feature count and sfm point cloud, but there are probably many outliers that are being filtered out. (In DepthMapFilter)

You could increase the reconstruction quality https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters
