### ISSUE TITLE
3D Scanning a hall (Photogrammetry) [question]

### ISSUE THREAD

**Issue by MartinVanVan** [alicevision/meshroom#1206]
Hello,
I am totally new to photogrammetry and 3D Scanning. My Bachelor Project is to scan a hall and reconstruct a 3D Model, which can be used in a virtual environment.

I’ve shot 495 Photos in total. Both on an **iPhone XS** (automatic stock camera) and with a **Nikon D5100** (ISO 125; Exposure Time 1/3; Aperture f.9). All photos have been shot in portrait mode/orientation.
The photos on the iPhone and the Nikon are from the same position. (each time I shot a photo with the Nikon, I also took a photo with the iPhone)

**I put all the photos into a video, so you can see all the photos and perspectives I took:**
https://drive.google.com/file/d/19RcorQ5kERXesQ921S808puQYo0WN1LR/view?usp=sharing

At first I tried to put all the iPhone photos into **Meshroom**. Just to see the outcoming results.
With the default settings I was able to reconstruct 379 camera positions (out of 494).
The 3D Model isreally bad:

![aulaNoSet](https://user-images.githubusercontent.com/63474954/103481237-e8912380-4dd9-11eb-8b1e-7b324ce6875d.PNG)

So I tried to turn up the Feature Extraction -> Describer Preset to “Ultra” and set the Describer Types of the FeatureExtraction, FeatureMatching, StructureFromMotion to “akaze”.
The processing took almost 2 days but now way more cameras could be reconstructed:

![aulaUltra](https://user-images.githubusercontent.com/63474954/103481258-17a79500-4dda-11eb-9b0f-6822c36e3720.PNG)

This time I was able to reconstruct 473 camera positions (out of 494).
But the result is still not really good.

I also tried to use **RealityCapture** but the software could only align **20 ish photos out of 495.**
Do you know how RealityCapture can align more photos?

![RealityCaptureiPhone](https://user-images.githubusercontent.com/63474954/103481307-69e8b600-4dda-11eb-9437-53dbc1435dec.PNG)

My guess is that my pictures are not good enough to be used for photogrammetry. Do you have any recommendations and tips how I can improve my images?

**Comment by natowi** [comment]
see https://github.com/alicevision/meshroom/issues/1207
