### ISSUE TITLE
3D Scanning a hall (Photogrammetry) [question]

### ISSUE THREAD

**Issue by MartinVanVan** [alicevision/meshroom#1207]
Hello,
I am totally new to photogrammetry and 3D Scanning. My Bachelor Project is to scan a hall and reconstruct a 3D Model, which can be used in a virtual environment.

I’ve shot 495 Photos in total. Both on an **iPhone XS** (automatic stock camera) and with a **Nikon D5100** (ISO 125; Exposure Time 1/3; Aperture f.9). All photos have been shot in portrait mode/orientation.
The photos on the iPhone and the Nikon are from the same position. (each time I shot a photo with the Nikon, I also took a photo with the iPhone)

**I put all the photos into a video, so you can see all the photos and perspectives I took:**
https://drive.google.com/file/d/19RcorQ5kERXesQ921S808puQYo0WN1LR/view?usp=sharing

Some examples:

![IMG_7176](https://user-images.githubusercontent.com/63474954/103481501-af59b300-4ddb-11eb-9f81-a53f779454b5.JPG)

![IMG_7363](https://user-images.githubusercontent.com/63474954/103481513-c26c8300-4ddb-11eb-996a-40052559d1b8.JPG)

At first I tried to put all the iPhone photos into **Meshroom**. Just to see the outcoming results.
With the default settings I was able to reconstruct 379 camera positions (out of 494).
The 3D Model isreally bad:

![aulaNoSet](https://user-images.githubusercontent.com/63474954/103481237-e8912380-4dd9-11eb-8b1e-7b324ce6875d.PNG)

So I tried to turn up the Feature Extraction -> Describer Preset to “Ultra” and set the Describer Types of the FeatureExtraction, FeatureMatching, StructureFromMotion to “akaze”.
The processing took almost 2 days but now way more cameras could be reconstructed:

![aulaUltra](https://user-images.githubusercontent.com/63474954/103481258-17a79500-4dda-11eb-9b0f-6822c36e3720.PNG)

This time I was able to reconstruct 473 camera positions (out of 494).
But the result is even worse.

I also tried to use **RealityCapture** but the software could only align **20 ish photos out of 495.**
Do you know how RealityCapture can align more photos?

![RealityCaptureiPhone](https://user-images.githubusercontent.com/63474954/103481307-69e8b600-4dda-11eb-9437-53dbc1435dec.PNG)

**My guess is that my pictures are not good enough to be used for photogrammetry. Do you have any recommendations and tips how I can improve my images?**

**Comment by natowi** [comment]
> The 3D Model is really bad

actually it not so bad. It can be improved with better image capturing strategy.
You need more images for the badly reconstructed areas. When cameras are not reconstructed, it is a hint that the overlap is not high enough or some other capturing issue. 

The repeating patterns increase the reconstruction difficulty. Similar issue with the desks, they have a white, featureless surface and reflective, thin stands. 

Capturing tips: https://www.agisoft.com/forum/index.php?topic=9089.msg42594#msg42594

> Describer Preset to “Ultra 

this is not recommended for large datasets

**Comment by MartinVanVan** [comment]
> 
> 
> > The 3D Model is really bad
> 
> actually it not so bad. It can be improved with better image capturing strategy.
> You need more images for the badly reconstructed areas. When cameras are not reconstructed, it is a hint that the overlap is not high enough or some other capturing issue.
>
Ok thank you. So its really like I guessed, that my images are still not good enough... its really hard to scan a big hall like this. I've seen techniques like putting random color pattern on the surfaces, but that is not allowed or possible in this hall. 

> The repeating patterns increase the reconstruction difficulty. Similar issue with the desks, they have a white, featureless surface and reflective, thin stands.
> 
actually I dont want the desks to be reconstructed (or need to remove them afterwards). I cant move the desks because its all measured/positioned for exams with Covid regulations. 

> > Describer Preset to “Ultra
> 
> this is not recommended for large datasets
ok that is good to know. with these settings the project took about 40GB space...
