### ISSUE TITLE
[bug] Open and Save dialog are unable (QT 5.15.2)

### ISSUE THREAD

**Issue by skinkie** [alicevision/meshroom#1208]
**Describe the bug**
When I try to use to use the open or save button, the dialog is completely unusable. The window itself is responsible, it can be moved around. But I cannot navigate, load or save the project at all. I am aware I am using a quite more recent version of QT. But never experienced this kind of stuff.

https://www.youtube.com/watch?v=04_orqSh9FI

Using a test program with QFileDialog I have validated that this function behaves normally.

I have also tested a very small QML example, that starts FileDialog, which is also browseble. 

Upstream bug: https://bugreports.qt.io/browse/PYSIDE-1471

**Desktop (please complete the following and other pertinent information):**
 - OS: Linux
 - Python version 3.7
 - Qt/PySide version 5.15.2 / 5.15.1
 - Meshroom version: please specify if you are using a release version or your own build
   - Commit reference (if applicable) latest develop, with two fixes.

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/issues/1211

**Comment by zicklag** [comment]
This made the [latest version (v2023.3.0)](https://github.com/alicevision/Meshroom/releases/tag/v2023.3.0) of Meshroom unusable for me

**Comment by Kwonunn** [comment]
I am also experiencing this issue. I'm running GNOME 42.9.
