### ISSUE TITLE
Segmentation fault when loading images

### ISSUE THREAD

**Issue by MarjorieCoulin** [alicevision/meshroom#122]
(Ubuntu 18.04, Qt 5.11)

Hi,
I get to load the Meshroom UI, but as soon as I try to drag & drop images I get the following error :

> Plugins loaded:  AppendText, Ls, AppendFiles
> Plugins loaded:  MeshDenoising, CameraCalibration, ImageMatching, ConvertSfMFormat, Texturing, CameraInit, ExportMayaMVG, ImageMatchingMultiSfM, KeyframeSelection, SfMAlignment, MeshResampling, FeatureMatching, SfMTransform, CameraConnection, MeshDecimate, MeshFiltering, DepthMapFilter, Meshing, DepthMap, CameraRigCalibration, CameraLocalization, FeatureExtraction, PrepareDenseScene, Publish, CameraRigLocalization, StructureFromMotion, ConvertAnimatedCamera
> == Error while loading the following plugins: ==
>   * Errors while loading "simpleFarmSubmitter".
>     File: simpleFarmSubmitter.py
>     No module named simpleFarm
> ================================================
> Failed to download scene at QUrl("")
> Program called with the following parameters:
>  * allowIncompleteOutput = 1
>  * allowSingleView = 1
>  * defaultCameraModel = "" (default)
>  * defaultFieldOfView = 45
>  * defaultFocalLengthPix = -1 (default)
>  * defaultIntrinsic = "" (default)
>  * groupCameraModel = 2 (default)
>  * imageFolder = "" (default)
>  * input = "/tmp/tmprj929S/CameraInit/fdba592891e8db45e3af8f93b1a59e1470b45d69/viewpoints.sfm"
>  * output = "/tmp/tmprj929S/CameraInit/fdba592891e8db45e3af8f93b1a59e1470b45d69/cameraInit.sfm"
>  * sensorDatabase = "/home/marjorie/AliceVision/src/aliceVision/sensorDB/sensor_width_camera_database.txt"
>  * verboseLevel = "info"
> 
> Segmentation fault (core dumped)
> [2018-05-23 15:12:52,430][WARNING] CameraInit: Error on buildIntrinsics of node "None".
> [2018-05-23 15:12:52,432][WARNING] CameraInit: Error on buildIntrinsics of node "None".
> [2018-05-23 15:12:52,434][ERROR] Error while building intrinsics : Traceback (most recent call last):
>   File "/home/marjorie/meshroom/meshroom/ui/reconstruction.py", line 347, in buildIntrinsics
>     views, intrinsics = cameraInitCopy.nodeDesc.buildIntrinsics(cameraInitCopy, additionalViews)
>   File "/home/marjorie/meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 136, in buildIntrinsics
>     jsonData = open(cameraInitSfM, 'r').read()
> IOError: [Errno 2] No such file or directory: '/tmp/tmprj929S/CameraInit/fdba592891e8db45e3af8f93b1a59e1470b45d69/cameraInit.sfm'

Any idea what's wrong ?
Thank you !

**Comment by paperkettle** [comment]
Seeing something related I think

(Ubuntu 18.04, Qt 5.11 w/pyside2 via latest wheel as suggested in the readme)

Got stuck with simpleFarmSubmitter until I commented out the lines like in [commit 3c6ebf3df44435ee9290ff0e824f2b8fef0dcbf3](https://github.com/alicevision/meshroom/commit/3c6ebf3df44435ee9290ff0e824f2b8fef0dcbf3)

But now hitting a qt ssl issue alongside this reconstruction issue 

deep3d@deep3d:~/photogrammetry/meshroom$ PYTHONPATH=$PWD python2 meshroom/ui
Plugins loaded:  FeatureExtraction, CameraLocalization, ImageMatching, CameraConnection, PrepareDenseScene, CameraRigLocalization, CameraCalibration, MeshFiltering, ConvertAnimatedCamera, DepthMap, StructureFromMotion, Meshing, KeyframeSelection, MeshDenoising, MeshResampling, ExportMayaMVG, MeshDecimate, Publish, Texturing, CameraInit, SfMTransform, FeatureMatching, ImageMatchingMultiSfM, SfMAlignment, DepthMapFilter, CameraRigCalibration, ConvertSfMFormat
Plugins loaded:  Ls, AppendText, AppendFiles
== Error while loading the following plugins: ==
  * Errors while loading "simpleFarmSubmitter".
    File: simpleFarmSubmitter.py
    No module named simpleFarm
================================================
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: Incompatible version of OpenSSL
Failed to download scene at QUrl("")
/bin/sh: 1: aliceVision_cameraInit: Permission denied
[2018-05-28 01:00:24,928][WARNING] CameraInit: Error on buildIntrinsics of node "None".
[2018-05-28 01:00:24,928][WARNING] CameraInit: Error on buildIntrinsics of node "None".
[2018-05-28 01:00:24,929][ERROR] Error while building intrinsics : Traceback (most recent call last):
  File "/home/deep3d/photogrammetry/meshroom/meshroom/ui/reconstruction.py", line 347, in buildIntrinsics
    views, intrinsics = cameraInitCopy.nodeDesc.buildIntrinsics(cameraInitCopy, additionalViews)
  File "/home/deep3d/photogrammetry/meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 136, in buildIntrinsics
    jsonData = open(cameraInitSfM, 'r').read()
IOError: [Errno 2] No such file or directory: '/tmp/tmp3u7ReU/CameraInit/fdba592891e8db45e3af8f93b1a59e1470b45d69/cameraInit.sfm'

**Comment by paperkettle** [comment]
SSL errors cleared up with the install suggestions [here](https://bugreports.qt.io/browse/QTBUG-68156?focusedCommentId=403523&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-403523)

Still facing those same issues from

Failed to download scene at QUrl("")
/bin/sh: 1: aliceVision_cameraInit: Permission denied

and on

**Comment by paperkettle** [comment]
@fabiencastan I think so yeah. Got what I believe is a successful build on AliceVision after a long dependency quest, so maybe something was awry, but seemed to build and install successfully. Have some exports in my .bashrc and echoing $PATH shows the install's bin folder and $LD_LIBRARY_PATH shows install's the lib folder

**Comment by MarjorieCoulin** [comment]
Same as @paperkettle 

("long dependency quest", indeed)

**Comment by dreness** [comment]
I had the missing cameraInit.sfm problem because I moved my AliceVision installation but forgot to update the ```ALICEVISION_SENSOR_DB``` and ```ALICEVISION_VOCTREE``` environment vars. Now that I've fixed those, I can import photos into the UI without any explosions.

```
(meshroom) C:\Users\andre\work\meshroom>python meshroom/ui
Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportMayaMVG, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, Meshing, MeshResampling, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
Plugins loaded:  AppendFiles, AppendText, Ls
== Error while loading the following plugins: ==
  * Errors while loading "simpleFarmSubmitter".
    File: simpleFarmSubmitter.py
    No module named simpleFarm
================================================
Failed to download scene at QUrl("")
```
(drag some photos in)
```
Program called with the following parameters:
 * allowIncompleteOutput = 1
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraModel = 2 (default)
 * imageFolder = "" (default)
 * input = "c:\users\andre\appdata\local\temp\tmpyrmnex/CameraInit/fdba592891e8db45e3af8f93b1a59e1470b45d69/viewpoints.sfm"
 * output = "c:/users/andre/appdata/local/temp/tmpyrmnex/CameraInit/fdba592891e8db45e3af8f93b1a59e1470b45d69/cameraInit.sfm"
 * sensorDatabase = "C:\Users\andre\work\AliceVision\src\aliceVision\sensorDB\sensor_width_camera_database.txt"
 * verboseLevel = "info"

[00:34:05.558824][info] CameraInit report:
        - # views listed in SfMData: 42
        - # views with an initialized intrinsic listed in SfMData: 42
        - # intrinsics listed in SfMData: 2
```

**Comment by MarjorieCoulin** [comment]
I believe AliceVision was correctly installed, at least I have a bunch of bin,lib,include,etc. in C:\Program Files (x86)\aliceVision

I set a few environment variables as requested in meshroom install.md, naming
[Powershell, Windows 10]
$env:Path = $env:Path + ";C:\Program Files (x86)\aliceVision\;C:\Program Files (x86)\aliceVision\bin;C:\Program Files (x86)\aliceVision\lib"
$env:PYTHONPATH="E:\meshroom\"
$env:ALICEVISION_SENSOR_DB="E:\AliceVision\src\aliceVision\sensorDB\sensor_width_camera_database.txt"
$env:ALICEVISION_VOCTREE="E:\AliceVision\vlfeat_K80L3.SIFT.tree"
[/Poweshell]

sensorDB and the voctree were left in the original directory. I still get the cameraInit.sfm error when trying to load images though :

Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportMayaMVG, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
Plugins loaded:  AppendFiles, AppendText, Ls
[2018-06-21 17:17:37,018][WARNING] == Error while loading the following plugins ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

Failed to download scene at QUrl("")
[2018-06-21 17:17:54,950][WARNING] CameraInit: Error on buildIntrinsics of node "None".
[2018-06-21 17:17:54,950][WARNING] CameraInit: Error on buildIntrinsics of node "None".
[2018-06-21 17:17:54,953][ERROR] Error while building intrinsics : Traceback (most recent call last):
  File "C:\Users\ICO-Workstation-03\Documents\Marjorie\meshroom\meshroom\ui\reconstruction.py", line 365, in buildIntrinsics
    views, intrinsics = cameraInitCopy.nodeDesc.buildIntrinsics(cameraInitCopy, additionalViews)
  File "C:\Users\ICO-Workstation-03\Documents\Marjorie\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 136, in buildIntrinsics
    jsonData = open(cameraInitSfM, 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/ICO-WO~1/AppData/Local/Temp/tmpjtk841h5/CameraInit/fdba592891e8db45e3af8f93b1a59e1470b45d69/cameraInit.sfm'

I must say I am out of ideas right now. Any idea what I am doing wrong ?

**Comment by MarjorieCoulin** [comment]
Weird thing probably not linked to the issue, but still :
When I try to launch the UI with Powershell in administrator mode, I can't even drag and drop images in the panel, I get a "forbidden" mouse cursor. I don't have the issue in normal mode.

**Comment by TravisWu** [comment]
@MarjorieCoulin have you installed QT5 ?

**Comment by MarjorieCoulin** [comment]
@fabiencastan No sorry, I got caught by other tasks.

**Comment by yann-lty** [comment]
@MarjorieCoulin is it still an open issue or did you manage to use Meshroom?

**Comment by simogasp** [comment]
@MarjorieCoulin can we close the issue?

**Comment by forest-hermit** [comment]
I have the same error on Kubuntu 19.10

`./Meshroom 
Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportColoredPointCloud, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, LDRToHDR, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "20EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "/tmp/tmpb53ev08w/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm"
 * output = "/tmp/tmpb53ev08w/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm"
 * sensorDatabase = "/home/otomo/Programas/Meshroom-2019.2.0/aliceVision/share/aliceVision/cameraSensors.db"
 * verboseLevel = "info"

Segmentation fault (core dumped)
ERROR:root:Error while building intrinsics : Traceback (most recent call last):
  File "/opt/Meshroom/meshroom/ui/reconstruction.py", line 399, in buildIntrinsics
  File "/opt/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 192, in buildIntrinsics
RuntimeError: CameraInit failed with error code 139. Command was: "aliceVision_cameraInit  --sensorDatabase "/home/otomo/Programas/Meshroom-2019.2.0/aliceVision/share/aliceVision/cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "/tmp/tmpb53ev08w/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm" --allowSingleView 1  --input "/tmp/tmpb53ev08w/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm""
`

**Comment by forest-hermit** [comment]
False alarm in my case, it was caused by a weird .jpg format of a drone, after convert that images to normal 8 bit jpgs it worked again perfectly.
