### ISSUE TITLE
Video, Image & Color Calibration Processing Nodes

### ISSUE THREAD

**Issue by jeffreyianwilson** [alicevision/meshroom#1221]
Please consider:

1. Color Calibration Node to apply color calibration from Macbeth charts
2. Video processing node to extract frames and apply metadata to video to images frame as well as inject user defined metadata and apply color calibration
3. Image processing node to convert raw photography and apply color calibration

Thanks,
Jeff

**Comment by natowi** [comment]
1. It´s being worked on, but I don´t know the status https://github.com/alicevision/meshroom/issues/480#issuecomment-495974588
2. -> KeyframeSelection node (extract frames and apply metadata to video to images frame as well as inject user defined metadata )
3.  -> ImageProcessing node (should be able to convert raw images)

**Comment by jeffreyianwilson** [comment]
Oh wow, I totally missed 2&3, thanks!
Jeff

**Comment by natowi** [comment]
The next release will have color checker nodes with Macbeth support: 

**ColorCheckerDetection**: 
(BETA) \\
Performs Macbeth color checker chart detection.
Outputs:
- the detected color charts position and colors
- the associated tranform matrix from "theoric" to "measured" 
assuming that the "theoric" Macbeth chart corners coordinates are: 
(0, 0), (1675, 0), (1675, 1125), (0, 1125)
Dev notes:
- Fisheye/pinhole is not handled
- ColorCheckerViewer is unstable with multiple color chart within a same image

**ColorCheckerCorrection**: (BETA) \\
Performs color calibration from Macbeth color checker chart.
The node assumes all the images to process are sharing the same colorimetric properties.
All the input images will get the same correction.
If multiple color charts are submitted, only the first one will be taken in account.

**Comment by natowi** [comment]
--> https://github.com/alicevision/Meshroom/wiki/New-Features-in-Meshroom-2023.1
