### ISSUE TITLE
Having the equivalent of the features matches in the points cloud

### ISSUE THREAD

**Issue by EmilienCerem** [alicevision/meshroom#1222]
Hi all, 

I use the node exportmatches to export the .svg of each pair of images analyzed in the featurematching node. With the .svg i can see the coordinates (in pixel) of the matches point for each pair of images, but I also want to have the equivalent of the coordinates of this point in the final cloud points, is it possible ? 

Thanks, 
Emilien,

**Comment by natowi** [comment]
I think this is similar to this request https://github.com/alicevision/meshroom/issues/512

**Comment by EmilienCerem** [comment]
I don't think it is the same request, i only want to have in a file, not visually in the gui, the coordinates of the matches points in the point clouds. I think that the pipeline to create the point clouds use this information but i don't find it in the files...

**Comment by EmilienCerem** [comment]
> I think this is similar to this request #512

I don't think it is the same request, i only want to have in a file, not visually in the gui, the coordinates of the matches points in the point clouds. I think that the pipeline to create the point clouds use this information but i don't find it in the files... I just want an equivalent of the matches point in pixel in the photos and in (x,y,z) system in the cloud points
