### ISSUE TITLE
DepthMap produces incorrect point cloud after SfMTransform

### ISSUE THREAD

**Issue by Crunchie52** [alicevision/meshroom#1223]
I am evaluating the use of photogrammetry & Meshroom to reverse engineer components of vintage machinery and thus far have some encouraging results albeit with a few challenges. Scaling with markers (CCTags) is a mandatory requirement, and  orientation/positioning  of the object is highly desirable before transferring to CAD system. I have been unable to produce a correct dense cloud/mesh after using SfMTransform to scale & position the StructureFromMotion output.

Numerous subjects/image sets have been tried, all with the same result - the Dense Cloud is incorrect, it tends to be something like a small "wrapper" of part of the sparse cloud. It seems that the information passed to DepthMap by SfMTransform is incomplete or incorrect for DepthMap to do its job correctly.

Perhaps the problem is mine, or perhpaps it is a bug? I don't know, so have initially posted as a question with example shown below.

Test Example: 
Using relatively small set of 141 images to reverse engineer a cylinder head, these reconstruct perfectly using the default Meshroom workflow. The CCtags form a square having sides of 120mm:
![A -example image](https://user-images.githubusercontent.com/77319761/104448599-ad42e180-559d-11eb-85ac-b2cc40829edc.PNG)
A SfMTransform Node is inserted as shown:
![B -nodes](https://user-images.githubusercontent.com/77319761/104451252-90a8a880-55a1-11eb-9272-1c6b44538b48.PNG)
![C -SfMTransform](https://user-images.githubusercontent.com/77319761/104451260-930b0280-55a1-11eb-8133-7ef7cbf36fe3.PNG)
The output of StructureFromMotion (before Transform) is:
![D -Sparse Cloud](https://user-images.githubusercontent.com/77319761/104451361-b7ff7580-55a1-11eb-8dcb-cbd1eb0edc97.PNG)
The output of the SfMTransform, superimposed on the untransformed SfM output. It seems that the transform has correctly scaled and positioned everything!
![E -Sparse Transform](https://user-images.githubusercontent.com/77319761/104451493-e8471400-55a1-11eb-9e51-755a26452620.PNG)
However, Depth Map produces a "nonsensical" dense cloud:
![F -Dense Cloud](https://user-images.githubusercontent.com/77319761/104451654-23e1de00-55a2-11eb-8ca6-d58bd7c7cbda.PNG)
Dense Cloud zoomed:
![G -Dense Cloud Zoom](https://user-images.githubusercontent.com/77319761/104451716-3825db00-55a2-11eb-964b-b6802452b584.PNG)

**Comment by natowi** [comment]
Could you share a portion of your dataset for testing?

**Comment by Crunchie52** [comment]
Download Link for dataset

https://johnhfry.wetransfer.com/downloads/a4ef59ef3471b65646fba703a50678d220210113172438/c5d041bd1817c40868c31bf99472539820210113172439/e47b0b

**Comment by fabiencastan** [comment]
You should put the sfmTransform in input of the PrepareDenseScene.

**Comment by Crunchie52** [comment]
> You should put the sfmTransform in input of the PrepareDenseScene.

Hi Fabien,
Both scenarios (i.e the one I have shown, and the one you suggest) are shown in the CCtag Wiki article, and I have tried both with the same result. I've since stuck with the one I've shown because it is very clear in the Wiki article; it is possible that I misinterpreted the other, so will try it again.
Thanks

**Comment by fabiencastan** [comment]
SfmTransform before PrepareDenseScene should work. I use it regularly. Let me know if there is an issue in this case.

**Comment by natowi** [comment]
I used seven images from the dataset for testing: IMG_6984.CR2, IMG_7003.CR2, IMG_7014.CR2, IMG_7086.CR2, IMG_7097.CR2, IMG_7108.CR2, IMG_7119.CR2

This is the default result:

![def1](https://user-images.githubusercontent.com/8138537/104500323-91abfb00-55de-11eb-88ef-a2f37cda7ec9.JPG)

This with sfm transform (with Id0 and id1) + draft meshing

![draft](https://user-images.githubusercontent.com/8138537/104500374-a7212500-55de-11eb-9df7-ac50775887a5.JPG)

Looks fine

And this with sfmtransform (with Id0 and id1) + depthmap (with point cloud overlay for context)

![full2](https://user-images.githubusercontent.com/8138537/104501314-d84e2500-55df-11eb-9357-ae318e7986eb.JPG)

![gr](https://user-images.githubusercontent.com/8138537/104501108-91f8c600-55df-11eb-995e-d4feb3e0a413.JPG)

Distance as expected (checked in Meshlab):

![dist](https://user-images.githubusercontent.com/8138537/104501881-84900b80-55e0-11eb-8d62-1994e03db2e2.JPG)


---

Reproduce my last graph and if it works, use it for your full dataset.
I´d recommend to write the marker ID on the paper so you don´t confuse the order.

**Comment by Crunchie52** [comment]
@natowi and @fabiencastan thank you both for your input.
I've used the graph as shown by Simon above and Depth Map now produces a correctly oriented and placed object - fully working with the 4 markers. Using a full set of images the mesh is essentially good enough to reverse engineer to a solid in CAD and I can now do some further tests to see how accurate I can get the metrics.
First I have to sort out the scale. The documentation talks about Meshroom using units of 100mm, so I used +/-0.6 with the intent of getting 120mm. However, when I load the model to CAD it is 1.2mm (Simon's MeshLab snapshot also shows 1.2 as the measure). Is this the intent, and that I should scale up 100x in CAD, or am I still misunderstanding something?

**Comment by natowi** [comment]
You can adjust the _additional scaling_ factor to 100 in the node.

**Comment by Crunchie52** [comment]
> You can adjust the _additional scaling_ factor to 100 in the node. Software packages may use different scales when importing models.

@natowi . Thanks. Scaling seems to work correctly as long as the product of "Additional Scaling Factor" and the value entered in the coordinate results in the distance required. So either 100 * 0.6 or 1 * 60  gives the required result. 
Despite my poor cctag setup and the less than perfect images, the dimensions are accurate to +/- 0.5%  when imported to CAD. 
So now I will find a way to produce better scales with perfectly spaced and planar cctags, and try again with a decent set of images.
Very encouraged so far. Thanks. again.
