### ISSUE TITLE
Im using both the iphone 12 pros front and rear camera. any pictures taken with the front camera are not used.

### ISSUE THREAD

**Issue by piwkoperson** [alicevision/meshroom#1225]
All of my pictures have the error Warning:SerialNumber Metadata is missing.
I have a green camera focus looking thing in the top left of all of my photos. I don't know how to fix this problem and I believe it may be the reason that all of my photos from the front camera are not used. Anything would be helpful I'm extremely new to this.

**Comment by natowi** [comment]
The SerialNumber is being used to distinguish cameras/lens combinations. You can manually add a serial number to the exif using exif tools

**Comment by piwkoperson** [comment]
Thank you for replying and so quicky! I said that Im very new to this so I have 2 questions. Where do I find a serial number for each camera? And where would I get exif tools? Also would this be a reason for meshroom not to use those cameras?

**Comment by piwkoperson** [comment]
@natowi

**Comment by natowi** [comment]
Do you use two different cameras in the same dataset? Check the CamerInit node, Viewpoints and Intrinsics should have 2 elements each.

**Comment by fabiencastan** [comment]
@piwkoperson Could you share a dataset to make tests?
