### ISSUE TITLE
v2019.1.0 works but 2020.1.1 fails - no CUDA enabled GPU detected.

### ISSUE THREAD

**Issue by DIYiT32** [alicevision/meshroom#1231]
I have a Windows 10 PC with a GTX 560 Ti graphics card. Meshroom 2020.1.1 does not progress through the DepthMap stage because no CUDA GPU is detected.

```
[12:29:05.869267][warning] Could not determine number of CUDA cards in this system
[12:29:05.864271][warning] No CUDA-Enabled GPU.
[12:29:05.869267][error] cudaGetDeviceCount failed: CUDA driver version is insufficient for CUDA runtime version
[12:29:05.869267][info] Can't find CUDA-Enabled GPU.
[12:29:05.869267][error] This program needs a CUDA-Enabled GPU (with at least compute capability 2.0).
```

If I run v2019.1.0 it runs perfectly fine:

```
[12:30:46.349056][info] CUDA-Enabled GPU.
Device information:
	- id:                      0
	- name:                    GeForce GTX 560 Ti
	- compute capability:      2.1
	- total device memory:     1024 MB 
	- device memory available: 804 MB 
	- per-block shared memory: 49152
	- warp size:               32
	- max threads per block:   1024
	- max threads per SM(X):   1536
	- max block sizes:         {1024,1024,64}
	- max grid sizes:          {65535,65535,65535}
	- max 2D array texture:    {65536,65535}
	- max 3D array texture:    {2048,2048,2048}
	- max 2D linear texture:   {65000,65000,1048544}
	- max 2D layered texture:  {16384,16384,2048}
	- number of SM(x)s:        8
	- registers per SM(x):     32768
	- registers per block:     32768
	- concurrent kernels:      yes
	- mapping host memory:     yes
	- unified addressing:      yes
	- texture alignment:       512 byte
	- pitch alignment:         32 byte
Device information:
	- id:                      1
	- name:                    GeForce GTX 560 Ti
	- compute capability:      2.1
	- total device memory:     1024 MB 
	- device memory available: 803 MB 
	- per-block shared memory: 49152
	- warp size:               32
	- max threads per block:   1024
	- max threads per SM(X):   1536
	- max block sizes:         {1024,1024,64}
	- max grid sizes:          {65535,65535,65535}
	- max 2D array texture:    {65536,65535}
	- max 3D array texture:    {2048,2048,2048}
	- max 2D linear texture:   {65000,65000,1048544}
	- max 2D layered texture:  {16384,16384,2048}
	- number of SM(x)s:        8
	- registers per SM(x):     32768
	- registers per block:     32768
	- concurrent kernels:      yes
	- mapping host memory:     yes
	- unified addressing:      yes
	- texture alignment:       512 byte
	- pitch alignment:         32 byte

[12:30:46.497941][info] Supported CUDA-Enabled GPU detected.
[12:30:46.509930][info] Found 1 image dimension(s): 
[12:30:46.509930][info] 	- [4032x3024]
[12:30:46.516926][info] Overall maximum dimension: [4032x3024]
[12:30:46.516926][info] Create depth maps.
number of CUDA devices:	2
   0: GeForce GTX 560 Ti
   1: GeForce GTX 560 Ti
[12:30:46.520922][info] # GPU devices: 2, # CPU threads: 12
[12:30:46.520922][info] CPU thread 0 / 2 uses CUDA device: 0
```

I know the 560 Ti at this point is an unsupported product by NVIDIA, but with the current GPU market, I don't see myself getting a new one soon. Is this an expected change due to the obsolete nature of the 500 series GPUs, or is this a bug that can be fixed so I can run the latest version of Meshroom?

**Comment by natowi** [comment]
From this table https://de.wikipedia.org/wiki/CUDA it looks like your GPU only support compute capability 2.1.
Meshroom 2019.2 supports CC 2.0 and higher, Meshroom 2020 requires compute capability 3.0 to 7.5.

**Comment by DIYiT32** [comment]
OK. Thanks for the quick reply.

First, it looks like the error message needs to be updated to denote the change to CUDA capability 3.0 minimum being required. I was stuck on the fact that my GPU should have been supported since it's compute capability is 2.1 as you stated.

I suppose I can look around for documentation on what the major changes are from the 2019 to 2020 versions are, but as a beginner, I'm not sure how important it is that I run the latest & greatest version yet.

I tried moving the two files that you suggested, but I get the following error in the command window:

```
WARNING:root:== The following "aliceVision" plugins could not be loaded ==
  * DepthMap: bad magic number in 'aliceVision.DepthMap': b'3\r\r\n'

Traceback (most recent call last):
  File "d:\release\BUILD\meshroom\venv\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "d:\release\BUILD\meshroom\venv\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "meshroom/ui/__main__.py", line 11, in <module>
  File "d:\release\BUILD\meshroom\meshroom\ui\app.py", line 149, in __init__
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 486, in new
  File "d:\release\BUILD\meshroom\meshroom\multiview.py", line 286, in photogrammetry
  File "d:\release\BUILD\meshroom\meshroom\multiview.py", line 312, in photogrammetryPipeline
  File "d:\release\BUILD\meshroom\meshroom\multiview.py", line 371, in mvsPipeline
  File "d:\release\BUILD\meshroom\meshroom\core\graph.py", line 465, in addNewNode
  File "d:\release\BUILD\meshroom\meshroom\core\node.py", line 820, in __init__
meshroom.core.exception.UnknownNodeTypeError: Unknown Node Type: DepthMap
```

**Comment by natowi** [comment]
I´ll have to try the workaround myself (I did not have the time today). As the error message suggests "bad magic" at work here :D

**Comment by remmel** [comment]
As Alicevision for Meshroom 2020 is built with SDK 10 and last version compatible with compute capability 2.0 is max SDK 8 (see [GPU supported](https://en.wikipedia.org/wiki/CUDA#GPUs_supported) section in wiki), could it be possible to build it with SDK 8 (like previous versions) or does the depthmap really use new features of compute capability 3.0 ?

Also it would be great if the error message give more information. I spent so many time knowing that my graphics card needs to be compatible with *both* SDK used and compute compability.
Maybe you can put a link in that error message and the version of the sdk used.

SDK summary in my tests :
Win / Meshroom 2018 : cudart64_91.dll
Win / Meshroom 2019 : cudart64_80.dll
Win / Meshroom 2020 : cudart64_101.dll
Lin / Meshroom 2018 : libcudart.so.7.0
Lin / Meshroom 2019 : libcudart.so.7.0
Lin / Meshroom 2020 : libcudart.so.10.2

**Comment by fabiencastan** [comment]
The problem is that some recent cards require a recent version of CUDA while old card are not compatible with it. The code itself requires only compute capability 2 but depending on the build options used it has different compatibilities.
One solution could be to provide multiple builds...

**Comment by natowi** [comment]
> One solution could be to provide multiple builds

Could be added to the wish list for the Github auto-build process.
