### ISSUE TITLE
How to get more details for flat objects such as the ground and wall

### ISSUE THREAD

**Issue by andytany** [alicevision/meshroom#1233]
Meshroom is better for calculating three-dimensional objects, and the calculation quality for flat objects is poor. It is recommended that the depth node can retain more details of flat objects such as the ground and wall.

**Comment by natowi** [comment]
Meshroom can reconstruct flat objects, but they have to be well textured. The quality of the reconstruction really depends on your scene and setup. As you can see in [this paper](https://iopscience.iop.org/article/10.1088/1757-899X/1007/1/012026/pdf) it is possible to use Meshroom to reconstruct rooms.
