### ISSUE TITLE
When I reload a project, it doesn't reload the textured version of the model.. just the point cloud, Clicking on the texture button does not rerun the texturing. Can the textured model be loaded when reloading project?

### ISSUE THREAD

**Issue by softwarelifecycle** [alicevision/meshroom#1234]
**Describe the problem**
A clear and concise description of what the problem is.

**Screenshots**

**Dataset**
If applicable, add a link or *few* images to help better understand where the problem may come from.

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ]
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1]
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**

**Comment by natowi** [comment]
Try double clicking on the Texturing node.
