### ISSUE TITLE
x,y,z widget

### ISSUE THREAD

**Issue by softwarelifecycle** [alicevision/meshroom#1235]
On youtube videos on meshroom from about a year ago, the 3d panel shows an xyz widget for rotating the image.  On the  latest version I downloaded, this widget is not here...  Has that been removed or is there a settings to turn that on?  I can't find it...

Thanks
Harold
![meshroom](https://user-images.githubusercontent.com/44659478/105256830-84e65480-5b54-11eb-9f63-46186d852319.png)

**Comment by natowi** [comment]
It has been removed. You can zoom and rotate in the 3d window with your mouse.
