### ISSUE TITLE
[bug] Meshroom 2020.1.0 package will not start on Ubuntu 18.04

### ISSUE THREAD

**Issue by dscience7** [alicevision/meshroom#1236]
**Describe the bug**
I have downloaded Meshroom-2020.1.0-linux-cuda10.tar.gz and extracted to a directory. Running `./Meshroom` leads to the following error:

`./Meshroom: error while loading shared libraries: libpython3.6m.so.rh-python36-1.0: cannot open shared object file: No such file or directory
`

I have python 3.6 installed. The result of the command `ls -la /usr/bin/python' is:

`lrwxrwxrwx 1 root root 18 Jan 21 18:45 /usr/bin/python -> /usr/bin/python3.6`

**To Reproduce**
See above

**Expected behavior**
Launch Meshroom

**Screenshots**

**Log**
N/A

**Desktop (please complete the following and other pertinent information):**
 - OS: Ubuntu 18.04.5 LTS
 - Python 3.6
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version  2020.1

**Additional context**
I have Anaconda running on this machine. But it is inactive.

**Comment by ChemicalXandco** [comment]
This binary uses it's own python lib, so does `./lib/libpython3.6m.so.rh-python36-1.0` exist?

**Comment by dscience7** [comment]
Thanks that fixed the issue. The Ubuntu UI extractor extracted all the files into a flat folder structure. Prevented this and now the application is working.
