### ISSUE TITLE
ERROR:root:Error while building intrinsics: CameraInit failed with error code 1.

### ISSUE THREAD

**Issue by ahananq** [alicevision/meshroom#1238]
**Describe the problem**
I have used Meshroom before as well, and it was smooth. However this time I have again tried it after 3 months. I am getting this error when I transferred images. I am using this time 'Meshroom-2020.1.0', however, for confirmation I also checked 'Meshroom-2019.2.0' but same issue. 
I transferred same folder of 'Meshroom-2020.1.0' to my laptop and it works fine there, so means files are okay. I have seen all the Issues reported here but unable to fix this issue.

**Screenshots**

![Untitled](https://user-images.githubusercontent.com/69455941/105498365-11327c00-5cfb-11eb-85ca-c76f3632973a.png)

**Dataset**
use tested dataset (monstree).

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: Win10
 - Python version: 3.8.5

**Additional context**
I have tried everything as advised in previous issues, I even uninstalled and reinstalled Microsoft Visual C++ Redistributable Package 2015, 2017 and 2019. Basically I am not a programmer, but I am using photogrammetry for some project.

**Comment by BanKeTang** [comment]
Have you solved this issue? I met the same problem.

**Comment by ahananq** [comment]
@BanKeTang hey bro, well I remembered that I tried every possible solution available on internet, when nothing worked then i realized its something linked to Windows so I re-installed my Windows and the issue was resolved.
But before all of that I tried every possible available de-bugging.

**Comment by ahananq** [comment]
@BanKeTang , bro I was using Windows 10, and at that time various software I was testing for photogrammetry, so may be Windows got bugged.
