### ISSUE TITLE
Building and running Meshroom

### ISSUE THREAD

**Issue by ahemberger** [alicevision/meshroom#1239]
This thread is a continuation of questions I originally asked [here](https://github.com/alicevision/meshroom/issues/1216#issuecomment-764333032). The proposed solution to my original issue (a faulty camera solve) was to build Meshroom from scratch to pick up a development fix. 

Building and "installing" AliceVIsion (on Windows) according to the current [docs ](https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md) yield an installation that exists in **C:\Program Files\aliceVision**. After a few days of trolling around these issue threads, Google groups, etc., it seems like having a space in the PATH for AliceVision causes troubles. 

I've been able to resolve - _in part_ - the issues I mention in the above thread by wholly moving the AliceVision install into a path that doesn't involve spaces. At least, I think that might be what's helped...troubleshooting this issue is a bit foggy for me. Currently I can get Meshroom launched, but see the following warnings (which I suspect are significant)

> [2021-01-22 08:43:30,198][WARNING] == The following "submitters" plugins could not be loaded ==
>   * simpleFarmSubmitter: No module named 'simpleFarm'
> 
> [2021-01-22 08:43:35,135][WARNING] Missing plugin qtAliceVision.
> [2021-01-22 08:43:35,135][WARNING] Missing plugin qtOIIO.

I can find no definitive information about resolving the above warnings; they exist no matter how much massaging of PATH vars I do. 

Nevertheless, I try to load an EXR image that has no camera metadata. The Release version of Meshroom handles this operation fine. But my development build throws the following errors, and the image fails to load. Might anyone be able to provide advice as to how I might resolve this? :

--------------------

[2021-01-22 08:43:52,961][WARNING] importFilesDialog fileUrls: file:///H:/tmp/plate/plate_cc/plate_cc.0.exr
ERROR: unrecognised option '--useInternalWhiteBalance'
Usage:

AliceVision cameraInit:

Required parameters:
  -i [ --input ] arg                    A SfMData file (*.sfm) [if specified,
                                        --imageFolder cannot be used].
  --imageFolder arg                     Input images folder [if specified,
                                        --input cannot be used].
  -s [ --sensorDatabase ] arg           Camera sensor width database path.
  -o [ --output ] arg (=cameraInit.sfm) Output file path for the new SfMData
                                        file

Optional parameters:
  --defaultFocalLengthPix arg (=-1)     Focal length in pixels. (or '-1' to
                                        unset)
  --defaultFieldOfView arg (=-1)        Empirical value for the field of view
                                        in degree. (or '-1' to unset)
  --defaultIntrinsic arg                Intrinsics Kmatrix "f;0;ppx;0;f;ppy;0;0
                                        ;1".
  --defaultCameraModel arg              Default camera model type (pinhole,
                                        radial1, radial3, brown, fisheye4,
                                        fisheye1).
  --allowedCameraModels arg (=pinhole,radial1,radial3,brown,fisheye4,fisheye1)
                                        Permitted model type (pinhole, radial1,
                                        radial3, brown, fisheye4, fisheye1).
  --groupCameraFallback arg (=folder)   When there is no serial number in the
                                        image metadata, we cannot know if the
                                        images come from the same camera. This
                                        is problematic for grouping images
                                        sharing the same internal camera
                                        settings and we have to decide on a
                                        fallback strategy:
                                         * global: all images may come from a
                                        single device (make/model/focal will
                                        still be a differentiator).
                                         * folder: different folders will be
                                        considered as different devices
                                         * image: consider that each image has
                                        different internal camera parameters
  --viewIdMethod arg (=metadata)        Allows to choose the way the viewID is
                                        generated:
                                         * metadata: Generate viewId from image
                                        metadata.
                                         * filename: Generate viewId from file
                                        names using regex.
  --viewIdRegex arg (=.*?(\d+))         Regex used to catch number used as
                                        viewId in filename.
  --allowSingleView arg (=0)            Allow the program to process a single
                                        view.
                                        Warning: if a single view is process,
                                        the output file can't be use in many
                                        other programs.

Log parameters:
  -v [ --verboseLevel ] arg (=info)     verbosity level (fatal, error, warning,
                                        info, debug, trace).

[2021-01-22 08:44:04,651][ERROR] Error while building intrinsics: CameraInit failed with error code 1.
Command was: "aliceVision_cameraInit  --sensorDatabase "H:\github\meshroom\meshroom\AliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --useInternalWhiteBalance True --viewIdMethod metadata --verboseLevel info --output "C:/Users/me/AppData/Local/Temp/tmpo7i3rhut/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm" --allowSingleView 1 --input "C:\Users\me\AppData\Local\Temp\tmpo7i3rhut/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"".

Traceback (most recent call last):
  File "H:\github\meshroom\meshroom\ui\reconstruction.py", line 817, in importImagesUrls
    self.importImagesFromFolder(paths)
  File "H:\github\meshroom\meshroom\ui\reconstruction.py", line 804, in importImagesFromFolder
    self.buildIntrinsics(self.cameraInit, filesByType.images)
  File "H:\github\meshroom\meshroom\ui\reconstruction.py", line 873, in buildIntrinsics
    views, intrinsics = cameraInitCopy.nodeDesc.buildIntrinsics(cameraInitCopy, additionalViews)
  File "H:\github\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 276, in buildIntrinsics
    proc.returncode, cmd)
RuntimeError: CameraInit failed with error code 1.
Command was: "aliceVision_cameraInit  --sensorDatabase "H:\github\meshroom\meshroom\AliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --useInternalWhiteBalance True --viewIdMethod metadata --verboseLevel info --output "C:/Users/me/AppData/Local/Temp/tmpo7i3rhut/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm" --allowSingleView 1 --input "C:\Users\me\AppData\Local\Temp\tmpo7i3rhut/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"".

[2021-01-22 08:44:04,688][WARNING] Model size of -5245 is less than 0
[2021-01-22 08:44:04,708][WARNING] Model size of -825 is less than 0

**Comment by ChemicalXandco** [comment]
> ERROR: unrecognised option '--useInternalWhiteBalance'

The alicevision version and meshroom version do not match. Try installing [the latest alicevision from the develop branch](https://github.com/alicevision/AliceVision)

**Comment by ahemberger** [comment]
After some time rebuilding the entire AliceVision/Meshroom suite completely from scratch, I have some success and also some feedback in case anyone else is running into similar troubles. 

It seems like I can trace the vast majority of the difficulty I've experienced building this on Windows to filepaths with spaces (by default, several of the packages that need to be installed for this pipeline go into C:\Program Files, which seems to be highly problematic), and with Meshroom's expectation about slash direction. There also seems to be some issue as of this writing with ilmbase compatibility. 

NOTE that I'm still experiencing some problems:

When I launch Meshroom, I see this:

> 	[2021-01-23 15:55:22,989][WARNING] Missing plugin qtAliceVision.
> 	[2021-01-23 15:55:22,989][WARNING] Missing plugin qtOIIO.

I can successfully load an EXR image sequence, though the thumbnails in the UI all appear black. 

I can see the SensorDB field is empty in the CameraInit node. I traced this to a slash direction issue in the env variable (meshroom seems to expect that oath to have Linux-style slashes, rather than Windows-style). 

What follows is an exhaustive outline of the steps I took:

My development environment:
Windows 10 Pro
Visual Studio 16 2019

1) installed vcpkg from scratch

2) installed all AliceVision dependencies as follows:

	vcpkg install boost-algorithm boost-accumulators boost-atomic boost-container boost-date-time boost-exception boost-filesystem boost-graph boost-log boost-program-options boost-property-tree boost-ptr-container boost-regex boost-serialization boost-system boost-test boost-thread boost-timer lz4 openexr alembic geogram eigen3 opencv[eigen,ffmpeg,webp,contrib,nonFree,cuda] openimageio[libraw,ffmpeg,freetype,opencv,gif,openjpeg,webp,tools] ceres[suitesparse,cxsparse] cuda tbb --triplet x64-windows

3) Clone AliceVision repository, and ran cmake as follows:

	cmake .. -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 16 2019" -A x64 -T host=x64


4) Opened resulting AliceVision.sln file in VS19, and build the following:

	_CMakePredefinedTargets/ALL_BUILD

5) Tried running _CMakePredefinedTargets/INSTALL, but this 1) fails unless I run as an administrator, but more importantly 2) tries to installed to C:\Program Files\aliceVision, which I think is an erroneous installation destination because this whole system seems to dislike filepaths that include spaces. So, I decide to ignore this build target, and work with files located here:

	H:\github\AliceVision\build\Windows-AMD64\Release

6) Clone Meshroom repo to here:

	H:\github\meshroom

	Meshroom does not actually seem to include any build instructions (though I notice there are CMake files?).  I verify all Python requirements are installed, then build qt plugins as follows:

7) qmlAlembic - I clone the repo, then run cmake as follows: 

	cmake .. -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DCMAKE_PREFIX_PATH=%QT_DIR% -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=H:\github\meshroom\meshroom\qtPlugins -DCMAKE_BUILD_TYPE=Release

	*NOTE* This generates errors to do with ILMBASE, which I've been advised I can fix by
	1) set AliceVision_DIR=H:\github\AliceVision\build\src\generated, which contains AliceVisionConfig.cmake
	2) Adding this to the AliceVisionConfig.cmake.in file: find_dependency(OpenEXR)
	3) removing cmake/FindIlmBase.cmake
	4) adding the following to the CMakeLists.txt file:

> 		# AliceVision dependency
> 		find_package(IlmBase REQUIRED)
> 		find_package(AliceVision REQUIRED)

8) Modifying the CMAKE line as follows:
		
		cmake .. -DAliceVision_DIR=%AliceVision_DIR% -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DCMAKE_PREFIX_PATH=%QT_DIR% -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=H:\github\meshroom\meshroom\qtPlugins -DCMAKE_BUILD_TYPE=Release

	This ultimately results in the following files:
	H:\github\meshroom\meshroom\qtPlugins\qml\AlembicEntity\alembicEntityQmlPlugin.dll
	H:\github\meshroom\meshroom\qtPlugins\qml\AlembicEntity\alembicEntityQmlPlugin.lib
	H:\github\meshroom\meshroom\qtPlugins\qml\AlembicEntity\qmldir

9) QtAliceVision- - I clone the repo, then make the same modificationas as above (because the documented build process results in the same ILMBASE errors): 
	

	This ultimately results in the following files:
	H:\github\meshroom\meshroom\qtPlugins\qml\AliceVision\qtAliceVisionPlugin.dll
	H:\github\meshroom\meshroom\qtPlugins\qml\AliceVision\qtAliceVisionPlugin.dll
	H:\github\meshroom\meshroom\qtPlugins\qml\AliceVision\qmldir

10) QtOIIO- I clone the repo, then run cmake as follows:

	cmake .. -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DCMAKE_PREFIX_PATH=%QT_DIR% -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=H:\github\meshroom\meshroom\qtPlugins -DCMAKE_BUILD_TYPE=Release

	I can build and install the resulting VS19 .sln file fine, which results in the following files:
	H:\github\meshroom\meshroom\qtPlugins\qml\DepthMapEntity\depthMapEntityQmlPlugin.dll
	H:\github\meshroom\meshroom\qtPlugins\qml\DepthMapEntity\depthMapEntityQmlPlugin.lib
	H:\github\meshroom\meshroom\qtPlugins\qml\DepthMapEntity\qmldir

	H:\github\meshroom\meshroom\qtPlugins\imageformats\QtOIIOPlugin.dll
	H:\github\meshroom\meshroom\qtPlugins\imageformats\QtOIIOPlugin.lib

11) Now I think I'm ready to actually try to launch Meshroom. At H:\Github, I create a Meshroom.bat file containing the following:


	:: Path to AliceVision
	set PATH=%PATH%;H:\github\AliceVision\build\Windows-AMD64\Release

	:: Trying to get these paths set up right. NOTE THE SLASH DIRECTION
	set ALICEVISION_SENSOR_DB=H:/github/AliceVision/src/aliceVision/sensorDB/cameraSensors.db
	set ALICEVISION_VOCTREE=H:/github/meshroom/meshroom/AliceVision/share/aliceVision/vlfeat_K80L3.SIFT.tree
	set PYTHONPATH=H:/github/meshroom
	set QML2_IMPORT_PATH=H:/github/meshroom/meshroom/qtPlugins\qml
	set QT_PLUGIN_PATH=H:/github/meshroom/meshroom/qtPlugins

	:: Run Meshroom
	H:\pythonVenv\python.exe meshroom\ui\__main__.py

This successfully launches Meshroom, at which point I see the following problems:

> 	[2021-01-23 15:55:22,989][WARNING] Missing plugin qtAliceVision.
> 	[2021-01-23 15:55:22,989][WARNING] Missing plugin qtOIIO.

I can now successfully load an EXR image sequence, though the thumbnails in the UI all appear black. 

I can see the SensorDB field is empty in the CameraInit node. I traced this to a slash direction issue in the env variable (meshroom seems to expect that oath to have Linux-style slashes, rather than Windows-style). 

I'm still waiting here to see if I can actually test the thing @fabian actually suggested I test, but hoo boy are there a lotta gotchas with the building and installation of meshroom. Hopefully some of the above is helpful for anyone else struggling to get this working.

**Comment by ahemberger** [comment]
Still trying to build Meshroom (over a week into it here). I'm trying to resolve the above QT plugin warnings.  I notice that the requirements.txt and dev_requirements.txt include versions, which at this point seem like they might be outdated (?). So I tried removing the versions to install the latest of all python module requirements. Now when I launch Meshroom, I see the following crash/error:

> H:\github>H:\github\pyEnv\menv\Scripts\python.exe H:\github\meshroom\meshroom\ui\__main__.py
> [2021-01-25 22:19:56,908][WARNING] == The following "submitters" plugins could not be loaded ==
>   * simpleFarmSubmitter: No module named 'simpleFarm'
> 
> Traceback (most recent call last):
>   File "H:\github\meshroom\meshroom\ui\__main__.py", line 10, in <module>
>     from meshroom.ui.app import MeshroomApp
>   File "H:\github\meshroom\meshroom\ui\app.py", line 19, in <module>
>     from meshroom.ui.reconstruction import Reconstruction
>   File "H:\github\pyEnv\menv\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
>     return original_import(name, *args, **kwargs)
>   File "H:\github\meshroom\meshroom\ui\reconstruction.py", line 169, in <module>
>     class ViewpointWrapper(QObject):
>   File "H:\github\meshroom\meshroom\ui\reconstruction.py", line 252, in ViewpointWrapper
>     @Property(type=QObject, constant=True)
> TypeError: A constant property cannot have a WRITE method or a NOTIFY signal.

Can anyone from the Meshroom team please help?

**Comment by SoninnM** [comment]
> > * simpleFarmSubmitter: No module named 'simpleFarm'
I met the same probelm,have you solved it?

**Comment by fabiencastan** [comment]
simpleFarmSubmitter is just a warning. It's a submitter to a specific renderfarm system, you don't want it.

**Comment by fabiencastan** [comment]
@ahemberger I'm sorry I missed to answer this issue.
What version is it using? It looks like a Qt 6 error.
Meshroom is not compatible with Qt 6 for now and works fine with Qt 5.14.1.

Help on Qt 6 migration is of course more than welcome ;)

**Comment by Syderitic** [comment]
> Still trying to build Meshroom (over a week into it here). I'm trying to resolve the above QT plugin warnings. I notice that the requirements.txt and dev_requirements.txt include versions, which at this point seem like they might be outdated (?). So I tried removing the versions to install the latest of all python module requirements. Now when I launch Meshroom, I see the following crash/error:
> 
> > H:\github>H:\github\pyEnv\menv\Scripts\python.exe H:\github\meshroom\meshroom\ui__main__.py
> > [2021-01-25 22:19:56,908][WARNING] == The following "submitters" plugins could not be loaded ==
> > 
> > * simpleFarmSubmitter: No module named 'simpleFarm'
> > 
> > Traceback (most recent call last):
> > File "H:\github\meshroom\meshroom\ui__main__.py", line 10, in 
> > from meshroom.ui.app import MeshroomApp
> > File "H:\github\meshroom\meshroom\ui\app.py", line 19, in 
> > from meshroom.ui.reconstruction import Reconstruction
> > File "H:\github\pyEnv\menv\lib\site-packages\shiboken2\files.dir\shibokensupport__feature__.py", line 142, in _import
> > return original_import(name, *args, **kwargs)
> > File "H:\github\meshroom\meshroom\ui\reconstruction.py", line 169, in 
> > class ViewpointWrapper(QObject):
> > File "H:\github\meshroom\meshroom\ui\reconstruction.py", line 252, in ViewpointWrapper
> > @Property(type=QObject, constant=True)
> > TypeError: A constant property cannot have a WRITE method or a NOTIFY signal.
> 
> Can anyone from the Meshroom team please help?


I have this exact same problem when compiling AliceVision-2.4.0/Meshroom-v2021.1.0, but on the Linux side.

cx_Freeze 6.6
shiboken 5.15.2

WARNING:root:== The following "submitters" plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
    module.run()
  File "/var/tmp/portage/media-libs/meshroom-2021.1.0/work/meshroom-2021.1.0/setupInitScriptUnix.py", line 39, in run
  File "meshroom/ui/__main__.py", line 10, in <module>
  File "/var/tmp/portage/media-libs/meshroom-2021.1.0/work/meshroom-2021.1.0/meshroom/ui/app.py", line 19, in <module>
  File "shibokensupport/__feature__.py", line 142, in _import
  File "/var/tmp/portage/media-libs/meshroom-2021.1.0/work/meshroom-2021.1.0/meshroom/ui/reconstruction.py", line 169, in <module>
  File "/var/tmp/portage/media-libs/meshroom-2021.1.0/work/meshroom-2021.1.0/meshroom/ui/reconstruction.py", line 253, in ViewpointWrapper
TypeError: A constant property cannot have a WRITE method or a NOTIFY signal.

**Comment by BabaMasha** [comment]
I am also receiving this warning and the pipeline does not run 

[2021-11-25 13:16:40,429][WARNING] == The following "submitters" plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

**Comment by tkircher** [comment]
> TypeError: A constant property cannot have a WRITE method or a NOTIFY signal

I fixed this by deleting the offending @Property(..., constant=True) entries. For me there were only three:

  above ViewpointWrapper in meshroom/ui/reconstruction.py
  above systemInfo in meshroom/ui/app.py
  above licensesModel in meshroom/ui/app.py

After this it launches successfully.
