### ISSUE TITLE
Make a VirtualBox image with pre-built binaries

### ISSUE THREAD

**Issue by vmchaz** [alicevision/meshroom#124]
I see that some people have troubles with getting through the "dependencies quest", but they still want to try this software. I think it the best solution - to upload a virtual machine image where AliceVision and MeshRoom are already built (with sources, of course) - so anyone could download it and run.

**Comment by paperkettle** [comment]
I originally started working to setup AliceVision core libs in a new Docker container but figured I'd bump into major issues trying to get the Meshroom GUI working. Tho if the lib offers good results and I have time to wrap my head around the project more deeply I'd consider working on a web frontend which might make it viable. 

Maybe something like Flatpack is also an option? Tho only addresses the Linux side of things / I don't have experience with them yet

**Comment by vmchaz** [comment]
Any of these options are OK. I said about Virtualbox image because I saw NeST (neuron simulation tool) could be downloaded as a vbox image also, and this (despite its definitely large size) really helps starting using the software right after downloading.
So you could try this as the first (and easiest) option. (Though, those who want to use CUDA couldnt use it inside vbox without extra configuring)

**Comment by fabiencastan** [comment]
Yes, with cuda Docker and VM are not so easy to setup.
IMO, Flatpak and/or snapcraft packages would be the most convenient solution for Linux.

**Comment by fabiencastan** [comment]
@simogasp has started to add the support for Docker, if you want to give it a try:
https://github.com/alicevision/meshroom/blob/devDocker/Dockerfile

**Comment by yann-lty** [comment]
I'm closing this since official releases are now available on Windows and Linux.
