### ISSUE TITLE
[bug] FeatureExtraction extract only part of features following “Using-known-camera-positions” tuto

### ISSUE THREAD

**Issue by remmel** [alicevision/meshroom#1240]
Hi,

During _ImageMatching_ if I follow your tuto [Using-known-camera-positions](https://github.com/alicevision/meshroom/wiki/Using-known-camera-positions) (connecting _FeatureExtraction.input_ = _camerasWithPoses.sfm_) I get  “_Can't find descriptor of view_” error this is because **_FeatureExtraction_ have not generated all the .desc and .feat.**

My dataset contains 70 images. In the normal pipeline _FeatureExtraction_ generates 70 x .desc and 70 x .feat. 2 chunks are done. Which is correct.
But in the _"Using-known-camera-positions"_ pipeline (_FeatureExtraction.input = camerasKnown.sfm_), _FeatureExtraction_ step generates 40 x .desc and 40 x .feat. Only 1 chunk is done. (and as the node changes it recalculates the feature).

That's not a big deal, as there are easy workaround :
- copy-pasting .feat and .desc between _FeatureExtraction_ folder works
- Or better, connecting instead _ImageMatching.input = camerasWithPoses.sfm_

But do you know why it does not work?

I’m using Meshroom 2020.1.0 on Ubuntu 20.04 LTS

[EDIT] Note that same bug in Meshroom dev built with `Can't find view 1186364016 region files` error in FeatureMatching

**Comment by Tom-Notch** [comment]
One more thing to notice:
Set **Know Poses Geometric Error Max** to 0 if your poses are not accurate.
I used poses estimated from some deep-learning models and FeatureMatching errors without any output.
