### ISSUE TITLE
[question] Get more texture details and realism

### ISSUE THREAD

**Issue by andytany** [alicevision/meshroom#1243]
When obtaining details, meshroom and agisoft are quite different, and the realness calculated by meshroom on the right is relatively poor.

The same material will be darkened using meshroom calculations. I used the default settings, and agisoft also used the default settings. The result of meshroom is darker than agisoft and the realism is lost. I don't know where it is affected.

![image](https://user-images.githubusercontent.com/76229960/105643809-5ccb5e00-5e92-11eb-9aa8-768ba4156fe2.png)

**Comment by fabiencastan** [comment]
Difficult to answer without looking to the scene in details.
Are all cameras localized?
Are you working on RAW images? If yes, from what camera? Could you try to convert them to TIFF or EXR in another software to ensure they are not incorrectly interpreted (in term of colorspace)?

**Comment by andytany** [comment]
It's not just the color, but also the details. The wall of the meshroom on the right will be affected by objects, but Agisoft handles it better. Are there any settings in meshroom that can improve this problem?

![image](https://user-images.githubusercontent.com/76229960/105833746-ec275d00-5fc9-11eb-91b2-d1a2e59643cf.png)

**Comment by fabiencastan** [comment]
If you have high quality pictures of an object (and not a full environment), you may want to remove the downscale on the DepthMap and Texturing nodes.
