### ISSUE TITLE
CameraCalibration failure

### ISSUE THREAD

**Issue by EnigmaRaptor** [alicevision/meshroom#1244]
When attempting to point camera calibration to a folder which is populated with .JPEG files, the CameraCalibration computation results in no output and the following message in log:

Program called with the following parameters:
 * calibGridSize = 10
 * debugRejectedImgFolder = ""
 * debugSelectedImgFolder = ""
 * input =  Unknown Type "class boost::filesystem::path"
 * maxCalibFrames = 199
 * maxFrames = 0
 * maxTotalAvgErr = 0.1
 * minInputFrames = 10
 * nbDistortionCoef = 3
 * output = "H:/MeshRoom Projects/MeshroomCache/CameraCalibration/4f624674296cf264ba555e605c3afd4a2adc4396/cameraCalibration.cal"
 * pattern =  Unknown Type "enum aliceVision::calibration::Pattern"
 * size =  Unknown Type "class std::vector<unsigned __int64,class std::allocator<unsigned __int64> >"
 * squareSize = 27

[2021-01-25 15:50:26.286178] [0x00003924] [debug]   filePattern: Checkerboard
[2021-01-25 15:50:26.286178] [0x00003924] [debug]   directory feedImage
Input video length is 0.
find points duration: 
Grid detected in 0 images on 0 input images.

**Comment by natowi** [comment]
Try using a .mp4 video as calibration source input
