### ISSUE TITLE
[request] 

### ISSUE THREAD

**Issue by andytany** [alicevision/meshroom#1246]
When there are multiple nodes, it is difficult to find the required files.
It is recommended to use the node name for the model storage directory. Add and modify the output name.

![image](https://user-images.githubusercontent.com/76229960/105862772-75ea2100-5ff0-11eb-9a21-f7653567782c.png)

**Comment by ChemicalXandco** [comment]
If you right-click the node, a context menu will open and you can click 'Open folder' to access the node folder.
