### ISSUE TITLE
Feature matching failed using known camera poses

### ISSUE THREAD

**Issue by 295361179** [alicevision/meshroom#1248]
Hi, I'm trying to do the reconstruction using known camera positions following the steps outlined in the [Wiki](https://github.com/alicevision/meshroom/wiki/Using-known-camera-positions). However, the process failed at Feature Matching when computing pairwise fundamental guided matching. There is no error message, so I'm not sure what the problem is.

Below is the sfm file that I created and the log of Feature Matching node:
[sfm.zip](https://github.com/alicevision/meshroom/files/5878276/sfm.zip)

**Comment by remmel** [comment]
This is same error I guess. I wrote the workaround : https://github.com/alicevision/meshroom/issues/1240

**Comment by 295361179** [comment]
> This is same error I guess. I wrote the workaround : #1240

I did encounter this error as well, but I made a similar workaround as yours. However, the error now is at feature matching, it can't compute the relative pose kernel.

**Comment by antoinebio** [comment]
Hello;
I am working with last release, MR Version 2025.1.0
I would like to re-open that issue As I am facing it as well.
Is there any fixed solution with that last release ?
issue is occuring on node FeatureMatching. Previous nodes are successful.
the issue on FeatureMatching node is related to that wierd message saying " Can't find view 40 region files in folders" pointing to MeshroomCache/FeatureExtraction folder...
