### ISSUE TITLE
Could not determine number of CUDA cards in this system？

### ISSUE THREAD

**Issue by kdthrive** [alicevision/meshroom#1253]
It has been running normally before, but this error was reported today
![image](https://user-images.githubusercontent.com/19604626/106731006-f4c30780-6649-11eb-8a17-e17e1485f772.png)

**Comment by natowi** [comment]
Can you provide your hardware / OS / driver details please?

**Comment by olexster** [comment]
I have same problem  
Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz   2.60 GHz
ram 8,00 GB

os:	Windows 10 Pro, 64-bit
DirectX:	12.0 
GPU:		NVS 5200M
driver v:	387.95
Version API Direct3D:	11.2
Direct3D Feature Level: 11_0
CUDA Cores: 96
Core clock: 672 MHz
Shader clock: 1344 MHz
Memory data frequency: 3138MHz
Memory interface: 64 bit
Memory bandwidth: 25.10 GB / s
Total graphics memory available: 5071 MB
1024 MB discrete GDDR5 graphics memory
Video memory in the system: 0 MB
Shared memory in the system: 4,047 MB
Video BIOS version: 70.08.A8.00.8E
IRQ: Not used
Bus: PCI Express x16 Gen2

**Comment by natowi** [comment]
On notebooks you sometimes need to prioritize the nvidia gpu in the control panel for Meshroom. This can be messed up by updates from time to time or with windows updates that change the energy options to prefer the intel gpu for example. Make sure you have the latest drivers for your gpu installed.

**Comment by Wakeelfahmed** [comment]
Hi, I am also getting the same error
![image](https://github.com/alicevision/Meshroom/assets/67804908/4af72ce5-543b-4798-b057-7f569814a2f0)

System specs:

Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz   3.40 GHz
RAM	8.00 GB
8 GB ram
Integrated GPU only
![image](https://github.com/alicevision/Meshroom/assets/67804908/dbdbf5fa-0326-40d8-b91d-502c21006096)
256 SSD

Does Meshroom require a Nvidia GPU?

**Comment by natowi** [comment]
@Wakeelfahmed "Does Meshroom require a Nvidia GPU?" Yes https://github.com/alicevision/Meshroom/wiki/Draft-Meshing
