### ISSUE TITLE
[question] AKAZE workflow

### ISSUE THREAD

**Issue by isolin** [alicevision/meshroom#1254]
I would like to ask for help determining the right setting of the nodes for SfM with AKAZE only:

- I realized that I need to add either SIFT in `FeatureMatching` or I have to take exhaustive matching in `ImagesMatching` node
- As AKAZE is a binary descriptor, I choose bruteforce hamming for `FeatureMatching`. It goes really fast, wow! It is however suspicious that after comparing the image pairs in each chunk I always get _No putative feature matches._ on the last line.
- StructureFromMotion crashes straight away stating _Unable to load matches._

What am I doing wrong?

Ad Putative matches in `FeatureMatching`: With AKAZE I get the notification about no putative matches even if I don't enable them (disabled by default). If I enable it with SIFT I always get an error:

```
[21:05:27.539129][fatal] boost::filesystem::rename: No such file or directory: "/home/user/Meshroom-2020.1.0/MeshroomCache/FeatureMatching/f6b0d85f6bc97d8715b71fd5f5d9924547aa3423/putativeMatches/0.matches.0e47-84d3-8806-6f00.txt", "/home/user/Meshroom-2020.1.0/MeshroomCache/FeatureMatching/f6b0d85f6bc97d8715b71fd5f5d9924547aa3423/putativeMatches/0.matches.txt"
```

**Comment by fabiencastan** [comment]
Using AKAZE on FeatureExtraction and ImageMatching:Method=Exhaustive, the pipeline works fine.
I'm not sure why you have this error.
Have you tried on a simple dataset first, like https://github.com/alicevision/dataset_monstree/tree/master/mini6?
