### ISSUE TITLE
Holes in reconstructed mesh

### ISSUE THREAD

**Issue by ahemberger** [alicevision/meshroom#1258]
Hi;

I have a well-textured rock that I've shot an animated image sequence of (this is the same sequence referred to in [this thread](https://github.com/alicevision/meshroom/issues/1216#issuecomment-756166831)). The reconstructed mesh of the rock has lots of holes in it. Is there a way I can fix this? What causes it?

![Screenshot 2021-02-06 164458](https://user-images.githubusercontent.com/21340636/107131385-604fe380-689b-11eb-95a2-db25a37e0573.png)

**Comment by isolin** [comment]
Could you please have a look and post a preview of some of the depth maps generated? In particular look for black "holes" in the respective areas.

**Comment by ahemberger** [comment]
Bit hard for me to understand what I'm looking at, but in spot-checking a dozen or so of the depth maps, they all look more or less like this, with no obvious "holes" anywhere except near the edges of the maps (which I assume represents the areas nearest the camera frustum, which are understandably less stable). 

![Screenshot 2021-02-09 205838](https://user-images.githubusercontent.com/21340636/107458379-9e5a3b00-6b19-11eb-829e-121181f3ef2c.png)
