### ISSUE TITLE
How does one Crop with Meshroom[question]

### ISSUE THREAD

**Issue by migpics** [alicevision/meshroom#1260]
As with most 2D editing program, there is a way to mask or crop the image.  Is there a way to crop or limit the area to be processed visually for example, a box_
I assume Mesh Filtering is one way to filter out areas that might not have much information but I am unsure how to have more control over what areas are processed and which ones are not.

If Cropping is the not the correct word, please educate me on the nomenclature.
Thanks.

**Comment by ChemicalXandco** [comment]
In the meshing node there is a setting called bounding box and then if you enable it you can use the bounding box widget in the 3D viewer.

**Comment by migpics** [comment]
Thank you!  I noticed other people looking for a crop type feature but it did not come up in the help.  Thoughts on adding the word crop to that feature at least in the help docs_

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/wiki/Bounding-Box
I´ll dedicate some time to update the docs this months...
