### ISSUE TITLE
[bug] Manual SfMTransform active during processing

### ISSUE THREAD

**Issue by isolin** [alicevision/meshroom#1263]
**Describe the bug**
I often use SfMTransform to turn the point cloud properly. It mostly happens to be oriented up-side down. If I then open the the point cloud in the 3D view a rotation gizmo appears. That's nice, but it stays there even when I don't need it anymore.

**To Reproduce**

1. Create a sparse point cloud
2. Insert a `SfMTransform` node in manual mode, right before `PrepareDenseScene`
3. Start the whole pipeline
4. Hit the gizmo and change the rotation

**Expected behavior**

- Everything else is locked during processing, so this should be no exception either.
- In fact it is easy to hit the gizmo by accident anytime, so I think it should be only displayed in the 3D view while the `SfMTransform` node is selected or there should be a button in the `DISPLAY` menu to hide it.

**Desktop (please complete the following and other pertinent information):**
 - Ubuntu 18.04
 - Meshroom version: 2020.1.0

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/issues/1106
