### ISSUE TITLE
[question] feature matching is taking prohibitively long

### ISSUE THREAD

**Issue by Fennecai** [alicevision/meshroom#1267]
**Describe the problem**
i am trying to track a very long video clip's camera movement with the software, but "feature matching" is taking unreasonably long. How do i get my intended result faster? i need the sfm data as accurate as possible in order to export it to blender and use it to stabilize the camera.

its on step 2 out of 510 after running for 12 hours straight.

i already extracted the features and did the image matching steps (on "ultra" and "exhaustive") and now this is taking extremely long.

**Dataset**
the dataset is 9999 images long (I'm not joking) so i don't know which parts of it to share that would be helpful

**Log**
the log is too much for my clipboard to handle without freezing chrome when i paste it.

**Desktop (please complete the following and other pertinent information):**
 - OS: win 10
 - Python version: 3.8.3
 - Qt/PySide version: don't know what this is or how to find out it's version
 - Meshroom version: 2020.1.1

**Additional context**
i am trying to use meshroom to track the camera motion of a 360 degree video- however, i already rendered out a flat version of the video (only looking in one direction relative to the camera, with a perfect 90 degree FOV, there is no distortion at all). the flat video frames have already gone through the image matching and feature detection steps and didn't take very long to do so despite the amount reaching meshroom's maximum capacity.

my goal is to use the SFM data with blender to completely cancel out the camera's rotation; and using adobe after effects to track the camera doesn't work for presumably a similar reason (though i don't know what the reason actually is.) 

Is there another way to set the nodes up or change the settings so that i can still get a perfect camera track without it taking until Christmas?

**Comment by natowi** [comment]
You could use the [keyframe selection](https://github.com/alicevision/meshroom/wiki/Reconstruction-from-videos) node to only select suitable images from your video (mp4) - this way you can filter out blurred images that will not be used anyway in the SFM step. In addition to that you can try to disable the advanced setting "force cpu" in the featureExtraction node to force Meshroom to use your GPU.

**Comment by Fennecai** [comment]
I already did the thing of unchecking "force CPU", it doesn't help. :/ would using the keyframe filtering step to omit certain frames affect the motion tracking accuracy of the output's timing though? i need my virtual camera to move _exactly_ like my physical camera in order for my use case to work correctly when i export the sfm to blender. i want to use it to cancel out the camera's rotation, essentially.

**Comment by natowi** [comment]
How long is your video? ~6min? If you extract all frames, you will get many images that are not needed for the camera path reconstruction (only when you have a really fast camera movement) so this will increase the computation time.
The keyframe filtering node has the "Use Sparse Distance Selection" and the "Use Sharpness Selection" to select relevant images.
You´d need to adjust the parameters and give it a try to see if it works well enough with your dataset.

You can use the ExportAnaimated camera after SFM and/or the [Blender plugin](https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer) to work with the track.

**Comment by Fennecai** [comment]
the video is indeed 6 minutes long. i am already 100% aware of the ways to use the sfm and plugin. this was literally my intention from the beginning.

**Comment by fabiencastan** [comment]
@Fennecai You should use the sequential mode in the ImageMatching node.

**Comment by fabiencastan** [comment]
You should definitely not use "ultra" and "exhaustive" which could makes sense only for the opposite: very sparse acquisitions.

**Comment by Fennecai** [comment]
ah- ok. i'll try again with sequential

**Comment by Fennecai** [comment]
update: reducing it from "ultra" down to "normal" resulted in the SFM failing, presumably due to not having enough matched features. could that have to do with the blank concrete walls and sidewalk that feature in almost all the frames, as well as the clear blue sky? there seem to be no features detected on those. Would it be helpful for me to send the dataset to help diagnose the issues I'm having?

**Comment by natowi** [comment]
Sounds like a common [dataset issue](https://github.com/alicevision/meshroom/issues?q=is%3Aissue+label%3Adataset-issues)
You can share one image here (if the image does not contain private/third party owned information) and I can give you some pointers on what to change if re-shooting is an option

**Comment by Fennecai** [comment]
![image](https://user-images.githubusercontent.com/10889213/108266599-85f4ac80-7127-11eb-8536-694dd034df74.png)

**Comment by Fennecai** [comment]
also note that the video is walking down this path

**Comment by rasamaya** [comment]
If it were me, I would test on a 30sec to 1min segment vs the whole data set. When you're happy with the first 30sec, use those settings on everything.

**Comment by natowi** [comment]
Your dataset is quite challenging. As you can see, Meshroom can only detect features in 1/4 of the image. But since you only want to get the camera path this might be enough. The repeating patterns of the railway track and the featureless wall and walkway are the real challenge for any photogrammetry software. In general lens flare, reflections and the sun should be avoided. 

With AKAZE you can get some more features on the railway track that may help later on with the matching in _normal_ mode. As rasamaya suggested, best try a small reconstruction with a few images & follow the advice by fabien

![pts2](https://user-images.githubusercontent.com/8138537/108635786-9a1b0f80-7481-11eb-9ebb-5e85a40ff960.jpg)
![pts3](https://user-images.githubusercontent.com/8138537/108635788-9b4c3c80-7481-11eb-9a5c-4c324a382817.jpg)

**Comment by Fennecai** [comment]
mind pointing me at an "affordable" gimbal then?

**Comment by natowi** [comment]
@Fennecai From the quality of your image I assume you used a mobile phone) Phone gimbals start at 120$ like the Osmo mobile 3 from DJI. You can get used mobile phone gimbals or older versions / other brands below 100$, I bought one for my gopro for 60$ - so in my opinion it´s quite affordable.

**Comment by Fennecai** [comment]
it wasn't actually a mobile phone- its actually a discontinued Chinese model of 360 camera called the YI360, but I withheld that information previously because I thought it would lead to incorrect assumptions regarding my dataset's lens distortion or whatever- the dataset is flat and completely devoid of lense distortion because I re-rendered it from blender using a 90-degree FOV camera pointing only one direction within the sphere. its sad to hear that this overpriced un-supported camera really does have crap quality and it wasn't just me. i guess I'll have to invest in a more decent 360 camera at some point- but anyways, yes, all meshroom related questions have been answered, so time to close up shop.

**Comment by natowi** [comment]
@Fennecai did you try to use the original fisheye images in Meshroom? Did you add your camera model to the sensor database? It´s a Sony CMOS IMX377 1/2.3″ -> sensor width 6.16 -> check the image metadata (make/model) and add the following information to your sensordatabase: _make;model;6.16;usercontribution_
In the cameraInit node you can set the input to fisheye. When using the keyframeselection node, insert the make and model in the metadata section to append the information to the extracted frames.
This may help your reconstruction - maybe some information was lost before from your re-rendering in blender.

**Comment by Fennecai** [comment]
...i dont think that will help- the raw footage always has _both_ images in it and i would have to crop half of it anyways and lose probably all the exact same data. would manually entering the sensor data still help even on a manually cropped image sequence?

![image](https://user-images.githubusercontent.com/10889213/108716201-0bd27800-74d9-11eb-89f1-d1241dbd7d16.png)


the camera has a built-in stabilizer sensor, but its malfunctioning and causes the footage to randomly twitch around if i actually use it.

**Comment by natowi** [comment]
You can spilt the extracted images from the video with Meshroom-2020.1.1\aliceVision\bin\aliceVision_utils_split360Images.exe (cli tool), but you can use your own tool, too. Adding Metadata and Sensor information can help with the reconstruction
