### ISSUE TITLE
[bug] Inconsistent UIDs

### ISSUE THREAD

**Issue by isolin** [alicevision/meshroom#1269]
**Describe the bug**
In the past days I created an own pipeline. I create a `.mg` file using the GUI and then I use my own script to start the computation of nodes one after each other using the `meshroom_compute` utility. This is because at some points I do custom processing and based on intermediate results I generate and run new Meshing and Texturing nodes.

I thought that for each node in a `.mg` file `["uids"]["0"]` determines the directory name in the respective cache folder when `"internalFolder": "{cache}/{nodeType}/{uid0}/"`. At least on my home machine it works like that. Now I wanted to run the reconstruction on a remote computer and suddenly I saw that it saves the results under different UIDs! How is that possible? `meshroom_compute` follows the UIDs on the machine that created the `.mg` file but it ignores them and creates new (without altering the `.mg` file) on a different machine. 

**To Reproduce**
1. Create a `.mg` file.
2. Run with `meshroom_compute --node CameraInit_1` on the same machine and check the `output` directory. :heavy_check_mark: 
3. Copy the project and the images to a different machine (same OS version)
4. Edit the `.mg` file and for `CameraInit_1` node adapt the absolute paths of images and the `sensorDatabase` path accordingly
5. Run on the second machine with `meshroom_compute --node CameraInit_1` :x: 

**Expected behavior**
The cache folders should always adhere to the UIDs given in the `.md` file.

**Desktop (please complete the following and other pertinent information):**
 - OS: Ubuntu 18.04 on both computers
 - Python version 2.7 and 3.6 on both computers
 - Meshroom version: 2020.1.0 on both computers

**Workaround**
I will try to utilize `--cache` to mitigate that. And BTW what is `--extern` good for?

**Comment by fabiencastan** [comment]
There is a different in the hash function between python2 and python3.
Are you using the same python version on both computers?

**Comment by isolin** [comment]
Primary machine has: `python --version` 2.7.17 and `python3 -- version` is 3.6.9.
Secondary machine has: `python --version` `command not found` and `python3 -- version` is 3.6.9.

So yes that could be the issue. But why is the uid recomputed? If I understand it correctly, it happens in `meshroom_compute` line 36 with the `update()` call?

**Comment by isolin** [comment]
Another update: 

- Neither `--extern` nor `--cache` were helpful.
- I tried to run the python source of `meshroom_compute` with the line 36 commented out, but since Python is not my language of choice I failed at `import meshroom`. Any suggestions on how to use the Python API? I did't find anything in the docs.
- 'meshroom_photogrammetry' seems to be able to override node settings, but it can't be used to run single nodes only the whole pipeline which is not what I want.

So far no solution for me.
@fabiencastan thank you for your quick response, any further help appreciated.

**Comment by fabiencastan** [comment]
Use python3 on both machines, python2 support will be dropped at some point. We keep it only for one reason for now.

**Comment by fabiencastan** [comment]
> meshroom_photogrammetry seems to be able to override node settings, but it can't be used to run single nodes, only the whole pipeline which is not what I want.

There is an executable called meshroom_compute for that. Generate a .mg file first, and then use meshroom_compute.

**Comment by fabiencastan** [comment]
As said before, you should use python 3 on all platforms.
