### ISSUE TITLE
Windows: Live Reconstruction path selected via browser is invalid

### ISSUE THREAD

**Issue by dreness** [alicevision/meshroom#127]
On Windows, when selecting a "Live Reconstruction" path by clicking the folder icon and browsing to the desired folder, the resulting path is invalid because it starts with a "/".

![mehsroom-live-reconstruction-path-invalid](https://user-images.githubusercontent.com/5242016/40957838-aced7da4-684b-11e8-9c11-822b4e88c3ae.png)

```
Traceback (most recent call last):
  File "C:\Users\andre\work\meshroom\meshroom\ui\reconstruction.py", line 72, in start
    raise RuntimeError("Invalid folder provided: {}".format(folder))
RuntimeError: Invalid folder provided: /F:/ai-ml-models/images/live
```

Removing the leading "/" makes the path valid. This problem seems to occur for any path selected via the browser.

Perhaps a solution is to test for platform type after getting the path from the browser and remove any leading "/" if platform == windows? I think that should be safe as long as browser-selected paths are always in the form [drive letter][colon][the rest of the path components delimited by "/"]

(p.s. I'm not sure how to use the Live Reconstruction feature; even after fixing the path and clicking 'Start', it doesn't seem to be doing anything after I add ${Min. Images per Step} images into that folder, even if I've already primed the pipeline all the way through to a textured model. But I can wait for details on this, at least until a time when fewer people are struggling to get meshroom to build :)

(I can probably send a PR with this fix, but wanted to document it first in case it helps anybody else)

**Comment by yann-lty** [comment]
Good catch and sorry for the delay. We're using a Python helper class (`Filepath`) to manipulate filepaths in a cross-platform way from JS code and missed to fix this one.
I've also fixed a bug preventing the process to finish correctly, which might explain why nothing was happening on your side.

Live reconstruction is meant to be used along with a camera that can transfer images to a computer while shooting. Meshroom can watch a folder for new images and successively augment previous SfM (point clouds + cameras) after each ${Min. Images per Step}. This allows to get an iterative preview during shooting, e.g to see which areas of the dataset requires more coverage. A way to mimic this is indeed to drop successive batches of N images in the folder. You should then see in the graph one branch (from CameraInit to StructureFromMotion) for each batch of images.
