### ISSUE TITLE
Check failed: pt != result Inplace rotation is not supported. [bug]

### ISSUE THREAD

**Issue by TR7** [alicevision/meshroom#1275]
**Describe the bug**
i use meshroom_compute to compute a pipeline but under linux no pointcloud file (ply) is generated and instead i got this error in the logs:
[16:45:54.837020][info] Start bundle adjustment iteration: 0
block_sparse_matrix.cc:80 Allocating values array with 27029280 bytes.
detect_structure.cc:113 Schur complement static structure <2,3,6>.
rotation.h:593 Check failed: pt != result Inplace rotation is not supported.
rotation.h:593 Check failed: pt != result Inplace rotation is not supported.
Aborted (core dumped)

**To Reproduce**

1. create meshroom project.mg by meshroom_photogrammetry binary and --compute no
2. run meshroom_compute with project.mg and --toNode StructureFromMotion
3. See StructureFromMotion log

(project.mg is attached in this post)

**Expected behavior**
under windows 10, it works perfectly and generates a point cloud ply file
but under linux (docker) no ply file is generated but the error listed above

**Desktop (please complete the following and other pertinent information):**
- Release 2020.1.0 (2020.10.09)
- Python 3.7.9
- Linux (Docker in Google Cloud)
- Dataset: i had the bug in two from two independent Datasets, both with a GoPro Fusion 360

**Additional context**
[log.log](https://github.com/alicevision/meshroom/files/5973325/log.log)
[project.zip](https://github.com/alicevision/meshroom/files/5973338/project.zip)

**Comment by TR7** [comment]
did someone have a hint what the problem could be? **is there maybe a parameter or something in SFM that i can change to avoid the bug?**
fyi: i saw that in the "intermediate_steps"-folder from SFM several uncolored pointcloud files are generated, so i guess if its  possible to deactivate the bundle adjustment, meshroom will finish the job without the bug

**Comment by fabiencastan** [comment]
The new release is coming, so you will have to check if the problem is still there.

**Comment by TR7** [comment]
i checked the problem with the 2021.1 version and its still there :-(
i don't understand how meshroom can work under linux at all, because i have tried it with several datasets now and the problem always occurred.
i attached the current pipeline.mg file (2021 kompatible):
[pipeline2021.zip](https://github.com/alicevision/meshroom/files/6071796/pipeline2021.zip)

also under windows 10 its working fine, only the linux version aborts and prints:





--------------------------------------------------------------
[18:34:16.438993][info] Remove outliers: 
	- # outliers residual error: 43
	- # outliers angular error: 0
[18:34:16.457250][info] Bundle adjustment iteration: 0 took 242 msec.
[18:34:16.457332][info] Bundle adjustment with 1 iterations took 274 msec.
[18:34:16.652426][info] Rig(s) calibration start
[18:34:17.965354][info] Initialize rig calibration: 
	- rig id: 1069065184
	- # detected sub-poses: 2
	- # detected frames: 86
[18:34:17.972549][info] Bundle adjustment start.
[18:34:18.186360][info] Start bundle adjustment iteration: 0
block_sparse_matrix.cc:80 Allocating values array with 42423120 bytes.
detect_structure.cc:113 Schur complement static structure <2,3,6>.
rotation.h:593 Check failed: pt != result Inplace rotation is not supported.
rotation.h:593 Check failed: pt != result Inplace rotation is not supported.
Aborted (core dumped)

**Comment by fabiencastan** [comment]
Could you send me your dataset at fabien.castan@mikrosimage.com?
