### ISSUE TITLE
[question]Food object matching problem

### ISSUE THREAD

**Issue by andytany** [alicevision/meshroom#1277]
Foods with whiter colors always fail to match.
Do objects with a lot of white require special settings to recognize?

Darker colors generally match well, lighter colors are difficult to match

Set as shown below
![image](https://user-images.githubusercontent.com/76229960/107846595-35a6e300-6de5-11eb-91e5-a6c00d8bc194.png)

**Comment by fabiencastan** [comment]
What version are you using? Development version or latest release?

**Comment by andytany** [comment]
new version.  2020.1.1
I tried this with high, but it only matched one lap. I took a total of three laps. Cannot match another image.
  I used 105 images.
I have done a good mask cutout

![image](https://user-images.githubusercontent.com/76229960/107858046-50ec0f80-6e32-11eb-89a1-44caaf51504a.png)

other try
![image](https://user-images.githubusercontent.com/76229960/107858094-a9231180-6e32-11eb-9ec6-8089c9297cfd.png)

**Comment by rasamaya** [comment]
I would test on normal. start with the images of one circular pass. I would also try with only sift on all nodes. 
you could add a textured table below your object so Meshroom has vision data to help. Then remove later(I know there are pros and cons but you're stuck)  I dont even use the VOID method, I let Meshroom see my room and have settings on my camera to keep object and background within the same focus-ish. There are not enough features imo.

One thing you can do is use what you just did for the texture pass, and add another node of photos to be used for SFM/model and mark your white fruit with features, or use little stickers. It's a two step, but I saw someone else do it.

**Comment by fabiencastan** [comment]
@andytany You should try on release 2021.1 with dspsift.
