### ISSUE TITLE
[bug] version 2020.1.1 Interface does not load properly

### ISSUE THREAD

**Issue by WesselSytsma** [alicevision/meshroom#1286]
**Describe the bug**
After a installing version 2020.1.1 the start-up log does not show any text (see img. 1), and when the window loads the UI seems to be incorrectly loaded (see img. 2).

**To Reproduce**
1. Clean install
2. Start software

**Expected behavior**
Expected a text in start-up log and a interface similar to version 2019.2.0

**Screenshots**
![Start-up log](https://user-images.githubusercontent.com/14802789/108411587-1cf55d80-7229-11eb-8730-699f563b631f.png)
![Interface](https://user-images.githubusercontent.com/14802789/108411609-21217b00-7229-11eb-8b27-cada60330e11.png)

**Desktop (please complete the following and other pertinent information):**
 - OS: Windows 10 Home V10.0.19042
 - Python version: 3.9
 - Qt/PySide version: Unknown
 - Meshroom version: 2020.1.1

**Comment by elmarquez** [comment]
I've have a similar if not equal problem. The application starts but the user interface is not rendered correctly and the UI is flickering. There is no output on the console.

<img width="1413" alt="2021-02-20_22-19-47-meshroom-windows-broken" src="https://user-images.githubusercontent.com/388002/108593828-38e43500-73ca-11eb-8b91-af9d7d7a090f.png">

- Surface Book 3 with Windows 10 Enterprise 10.0.18363
- Meshroom 2020.1.1

**Comment by rasamaya** [comment]
@WesselSytsma Nvidia graphics with cuda? Which card?

**Comment by WesselSytsma** [comment]
@rasamaya I believe so. It is the GeForce GTX 1050 2GB which has CUDA 6.1 support according to: https://en.wikipedia.org/wiki/GeForce_10_series

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/issues/1093 https://github.com/alicevision/meshroom/issues/1088
> Some users (in issue 1093) report that running Meshroom in Windows 8 compatibility mode solves the crashing gui issue.

You could try if this solves your issues, too

**Comment by elmarquez** [comment]
Running Meshroom in Windows 8 compatibility mode appears to resolve my UI issue.

**Comment by WesselSytsma** [comment]
@natowi, awesome that does it! I will mention though that on start-up the log remains empty until I click on start. Perhaps what is shown in the log simply changed, however in case it is relevant.

Anyway thanks again, for this quick solution.
