### ISSUE TITLE
[question] Meshroom does not start properly

### ISSUE THREAD

**Issue by vincenthird** [alicevision/meshroom#1288]
Hi all,
I was hoping to use Meshroom but I am running on macOS (MacBook Pro 2018), so I have installed a virtual machine (Parallels Desktop) to run Windows 10 and Windows-compatible programs.
So far all the programs I have run on this VM worked properly and I only found an issue while trying to open Meshroom.

I have downloaded the latest ZIP from Alicevision website (Meshroom-2020.1.1), unzipped it without issue, and naively launched the application from its icon.
That is where the issue starts (and ends actually). Once the app icon is clicked, a command window opens and that's it. No text in the command window, no error message, nothing apart from a black empty window.

I tried to open as admin, nothing.
I tried to give some time to the app, nothing even after 30 min.

I am now clueless and beg for your advice.

 - macOS BigSur 11.2.1
 - VM on Windows 10 (through Parallels 16)

Thank you in advance for your help.

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/wiki/MacOS
> Apple ditched Nvidia support, so new Macs don`t have a Nvidia GPU and even NVIDIA eGPUs are not supported since MacOS 10.14 (Mojave). 

You can run Meshroom in a Windows 10 VM, but you need a NVIDIA GPU for the DepthMap step.

**Comment by vincenthird** [comment]
Thank you @natowi for your answer. Well I’m screwed then 😕. I will try to find a PC because Mushroom looks very interesting.

**Comment by natowi** [comment]
@vincenthird You can take a look if this is an option for you: https://github.com/alicevision/meshroom/wiki/Meshroom-in-Google-Colab-(cloud)
