### ISSUE TITLE
[bug] Overlap in input images and estimated cameras labels

### ISSUE THREAD

**Issue by evo-za** [alicevision/meshroom#1290]
**Describe the bug**
There is an overlap in the input images and estimated cameras labels when a large number of images are used.

**To Reproduce**
Use a large number of images (+999)

**Expected behavior**
No overlap

**Screenshots**
![Screenshot 2021-02-20 112939](https://user-images.githubusercontent.com/72976909/108591106-91d2af80-736f-11eb-84a1-794971adc5db.png)

**Log**
N/A

**Desktop (please complete the following and other pertinent information):**
 - OS: win 10
 - Meshroom version: 2020.1.1

**Additional context**
N/A

**Comment by ChemicalXandco** [comment]
https://github.com/alicevision/meshroom/commit/9476019996625baa3230993e6f1ecae50b00dd47 should fix this so it will be fixed in the next release.

**Comment by ChemicalXandco** [comment]
Does release [2021.1.0](https://github.com/alicevision/meshroom/releases/tag/v2021.1.0) fix this for you @evo-za?

**Comment by evo-za** [comment]
It does, yes. Thanks, will close.
