### ISSUE TITLE
Sensor size for binned phone cameras (S21 Ultra)

### ISSUE THREAD

**Issue by sweets9** [alicevision/meshroom#1292]
I have been taking many photos of a small object with my Samsung S21 Ultra using the burst mode on a turnable. I added 
a camera definition 12.03mm per calculations but calculated models are not being produce with good quality.

Due to the pixel binning on the S21 Ultra (108MP > 12MP), is there different settings that should be used for these types of cameras? Thanks

**Comment by rasamaya** [comment]
This is what I added to the camera sensor dB for mine:
Samsung;Samsung SM-G998W;8.17;usercontribution
I would not try to calculate for mobile. I would find the number and with the s21U make sure you're using the correct camera.

**Comment by sweets9** [comment]
Thanks for the quick reply. I will try your setting and see if it makes any difference. Is camera calibration any use for this sensor?

**Comment by natowi** [comment]
Yes, camera calibration can be used with any camera/sensor if necessary. The documentation is a little bit sparse here, but it is not too difficult. Print a checkerboard calibration sheet, make a mp4 video of it moving around and use it for calibration. The resulting information can be used in the CameraInit node https://meshroom-manual.readthedocs.io/en/latest/node-reference/nodes/CameraCalibration.html

**Comment by rasamaya** [comment]
here is the open cv   Camera calibration file used for testing(openCV)
https://docs.opencv.org/3.0-beta/_downloads/pattern.png 
I don't know if the asymmetrical circle patterns work, but I may try if natowi doesn't reply

**Comment by natowi** [comment]
@rasamaya you can select ASYMMETRIC CIRCLES in the cameracalibration node if you so desire
