### ISSUE TITLE
[solved] [bug] Other Input Mesh. Fatal. Unable to load ...

### ISSUE THREAD

**Issue by TimoFriedri** [alicevision/meshroom#1293]
**Note**
I actually solved it while typing this. For anyone after me, here is the "bug" and the solution.

**Describe the bug** / **To Reproduce**
I cleaned a mesh from a MeshFIltering Node in Blender.  (removed, added, moved vertices. Rotation etc. untouched)
Triangulated mesh.  
Exported back to obj.
Back to Meshroom.
Duplicated Texturing Node. 
Disconnected InputMesh and typed the cleaned mesh path in Other Input Mesh.
Compute ...
I see in the log that vertices are there, but no triangles!

**Expected behavior**
Should load the mesh and retexture the clean mesh.

**Log**
```
Program called with the following parameters:
 * angleHardThreshold = 90
 * bestScoreThreshold = 0.1
 * correctEV = 0
 * downscale =  Unknown Type "unsigned int"
 * fillHoles = 0
 * flipNormals = 0
 * forceVisibleByAllVertices = 0
 * imagesFolder = "C:/Users/re901371/Desktop/PCL_Garage/MeshroomCache/PrepareDenseScene/8ac89aaf3acd7fdb7d806492d56cbc3e8966ecde"
 * input = "C:/Users/re901371/Desktop/PCL_Garage/MeshroomCache/Meshing/e5b2be048c9eb60615df9bdb10526e2b51e1632c/densePointCloud.abc"
 * inputMesh = "C:/Users/re901371/Desktop/PCL_Garage/clean_mesh.obj"
 * multiBandDownscale =  Unknown Type "unsigned int"
 * multiBandNbContrib =  Unknown Type "class std::vector<int,class std::allocator<int> >"
 * output = "C:/Users/re901371/Desktop/PCL_Garage/MeshroomCache/Texturing/29859c586278fb4755ea8e5c8477bc4793ec8bf2"
 * outputTextureFileType = "png"
 * padding =  Unknown Type "unsigned int"
 * processColorspace = "sRGB"
 * subdivisionTargetRatio = 0.8
 * textureSide =  Unknown Type "unsigned int"
 * unwrapMethod = "Basic"
 * useScore = 1
 * useUDIM = 1
 * verboseLevel = "info"
 * visibilityRemappingMethod = "PullPush"

[21:48:22.516124][info] Load dense point cloud.
[21:48:23.398073][warning] Alembic LOAD: NO OBSERVATIONS_WITH_FEATURES: , mvg_visibilityFeatId: 0, mvg_visibilityFeatPos: 0, OBSERVATIONS_WITH_FEATURES flag: false
[21:48:27.797733][info] Found 1 image dimension(s): 
[21:48:27.797733][info] 	- [5472x3648]
[21:48:28.489450][info] Overall maximum dimension: [5472x3648]
[21:48:28.489450][info] Load input mesh.
[21:48:28.489450][info] Loading mesh from obj file: C:/.../clean_mesh.obj
[21:48:28.530725][info] 	- # vertices: 27777
	- # normals: 55392
	- # uv coordinates: 0
	- # triangles: 0
[21:48:28.743564][info] Mesh loaded: 
	- #points: 27777
	- # triangles: 0
[21:48:29.678145][fatal] Unable to load: C:/.../clean_mesh.obj

```

**Desktop (please complete the following and other pertinent information):**
Version 2020.1.1
Windows 10 
Python 3.7.4

**Solution**
I forgot to activate the checkbox "Triangulate Faces" in the export dialog of obj in Blender. Doing so solves the issue.

**Suggestion**
The obj was correct even without "Triangulated Faces" active. Other Tools visualized the mesh just fine.
Meshroom should give a meaningful suggestion here. Like obj file incompatible, Faces stored in wrong format. Please use Triangulates Faces explicitly (Blender: ...)
Something like that. 

Would have saved me a lot of time.
Nevertheless, Meshroom is an awesome tool. Nice work,

**Comment by CyrilPaulus** [comment]
Checking "Triangulated Faces" is not enough.
I think you need to have only one object (no groups) and preserve vertex order.
Here my export options that work from blender.

![image](https://user-images.githubusercontent.com/928124/111540680-be5fc880-876f-11eb-83b0-e5de698b42dd.png)

**Comment by TimoFriedri** [comment]
I am not sure about the vertex order. I changed my mesh, (added, removeds vertices, ...) and then used it successfully back in Meshroom.
The vertex order can't be the same in my case.

BUT I think I also had groups deactivated.
