### ISSUE TITLE
[question] Image import/metadata

### ISSUE THREAD

**Issue by natowi** [alicevision/meshroom#1294]
Question moved from PR to Issues: https://github.com/alicevision/AliceVision/pull/988#issuecomment-784322332 @Donmiclette

> I took a video of my whole house and then converted the video to images and it ended up being over 26,000 images. So
I added them to the Meshroom to use to make a perfect as much as possible design i can use for projection mapping this year.. when i load the pictures i always have a red emblem in left corner. I am new to this so if anyone can assist if I'm doing something wrong   please let me know.

---
Reply
---

Sensor Database entry: Samsung;Samsung Galaxy A51;6.4;devicespecification

- How did you convert the video? Did you use the KeyframeSelection node or another tool? When Metadata is missing from the images, you can add the information in the camerainit node 
- what exactly does the exif information say (in the video/and or image metadata)? The same make and model need to be added to the sensordatabase so it will match with the image metadata on import (-> green icon)
- 26,000 images are way too much if you only walked hough all rooms and did not cover all surfaces.

**Comment by Donmiclette** [comment]
Thank you again for your response,

     The program i used to convert the video was Prism Video File Converter
and I converted to jpg sequence which loaded all the pics. I wasn't aware
that there was a way to convert the video in Meshroom. I guess I was a
little bland on saying I videoed my whole house. I was meaning I took a 15
minute video with my phone of the outside so I can use it in photogrammetry
house mapping for the holidays. I am about to delete and start over so I
can get this right.

**Comment by natowi** [comment]
> I am about to delete and start over so I can get this right.

Good preparation is everything. I´d recommend you to read/watch some tutorials on the topics to watch for things to avoid.
https://www.vertexlibrary.com/guide-to-3d-scanning-outdoor-photogrammetry-tips is a good starting point.
