### ISSUE TITLE
[SOLVED] [bug] Texture is completely black after mesh retopology and custom UV unwrap workflow

### ISSUE THREAD

**Issue by TheoCoeugnietWhiteDev** [alicevision/meshroom#1295]
**[SOLVED]**
The .obj absolutely needs to have a material, even blank. My exports were without material as I thought Meshroom created them by itself. It is not. _So it needs a material when exported !_

**Describe the bug**
The resulting texture of a photoscanned model is completely black.
The workflow I use is going through the regular Meshroom process to have my scanned model, I bring this highpoly into Blender for mesh cleaning and, most importantly, a proper UV unwrap. I re-export this .obj from Blender without changing scale/rotation/position and load it again in Meshroom using the workflow described there, Step 6 (https://sketchfab.com/blogs/community/tutorial-meshroom-for-beginners/).
After the new Texturing node has done its job, the resulting texture is completely black.

**To Reproduce**
1. Scan a model
2. Take the resulting .obj into Blender
3. Clean mesh / create a UV unwrap
4. Export it back in .obj
5. Import in Meshroom using the Other Input Mesh of the Texture node, using the path
6. Launch the Texturing computing
7. See the texture is black

**Expected behavior**
Textures should be correctly projected into the new model with the new UV map

**Screenshots**
![Meshroom Problem](https://user-images.githubusercontent.com/78477852/109059753-e1550a80-76e4-11eb-9035-5be221f2f2e4.PNG) Node setup

![customUV](https://user-images.githubusercontent.com/78477852/109060143-59233500-76e5-11eb-8999-509d9f7b74d0.PNG) Unwrapped mesh in Blender

**Desktop (please complete the following and other pertinent information):**
 - Meshroom version: 2020.1.1

**Comment by jthorngren** [comment]
Does this work for multiple atlases / udims? Tried the mtl route and didn't have much luck.
