### ISSUE TITLE
Point density limitation

### ISSUE THREAD

**Issue by Kimakim322** [alicevision/meshroom#1302]
I have 2 datasets of images, on the first i have 1500 images of a building, the second one is actually the part of the first one and contains only two walls, so it consists of 900. I made a few tests with default settings on both datasets and with increased settings in Meshing node (Max Input Points = 500,000,000; Max Points = 10,000,000) and in DepthMap node (Downscale = 1). All camera poses in sfm node are correct. However, amount of points on the output of the texture, as well as in densePointCloud and densePointCloud_raw between these 2 datasets are almost the same, and about 4-4,5 millions, even with maximum settings. Thus, it turns out that model from 1500 images dataset is more sparse than the second one given the same amount of points, however it is expected that 1500 images produce significantly more points than 900 images. I suppose Meshroom has some limitation on the maximum amount of points. Can you please advise on how to deal with that.
Meshroom version - 2020.1
Ram - 64Gb

**Comment by fabiencastan** [comment]
It's only controlled by "Max Input Points" and "Max Points". We reduce the number of points until we are lower than the threshold on the number of points. So from one configuration to another, it may go too fast below the "Max Points" value when we iterate to reduce the density and stop with much less points than the threshold. I think that could explain the difference between the 2 datasets.

**Comment by Kimakim322** [comment]
@fabiencastan Thanks for quick answer. Given your answer, i would like to clarify one more thing. i want to create very high density cloud and i try different settings for MaxPoints and different dataset (>3k images) and the largest number of points i can get is about 5.5m. Is it possible for Meshroom to build 10m or even 100m densePointCloud_raw at the step of Meshing. If yes, what settings should i set? or this is strictly limited by MaxPoints?

**Comment by RomTreg** [comment]
@Kimakim322 , the same issue, struggled to build high dense cloud and still no success, all about 5M points. @fabiencastan , if u have any ideas, i will be much appreciated.

**Comment by fabiencastan** [comment]
On very small datasets you can get more points with: `MinStep=1`, `pixSizeMarginInitCoef=1`, `pixSizeMarginFinalCoef=1`.
But if you have a 3K images, I'm really surprised that you are not getting more points by simply increasing maxPoints and maxInputPoints.
Could you share the log with verbose=debug?
