### ISSUE TITLE
[cosmetic bug in UI] Display features buttons are changing width of cameras in the 3D Viewer.

### ISSUE THREAD

**Issue by gadaszewski** [alicevision/meshroom#1304]
**Describe the bug**

**To Reproduce**
1. Turn on visibility of the Features
2. Pressing on that button _(when I hover on it I can't see the name what is that)_
![image](https://user-images.githubusercontent.com/32915902/109340162-f064c580-7868-11eb-82c3-fe2e5118b2ab.png)
cameras in the 3D Viewer are changing width.

**Screenshots**
There is gif which is showing the bug:
![ae5lkiwVIl](https://user-images.githubusercontent.com/32915902/109340292-1c804680-7869-11eb-9868-42b5a1cbda66.gif)

**Desktop:**
 - OS: Windows 10
 - Python 3.9.0
 - Meshroom version: 2020.1.1

**Comment by natowi** [comment]
Same as https://github.com/alicevision/meshroom/issues/1136 - Still an (minor) issue in the 2021 release.
