### ISSUE TITLE
Help building on CentOS 7 [question]

### ISSUE THREAD

**Issue by rdauria** [alicevision/meshroom#1309]
**Describe the problem**
I have installed AliceVision but I am stuck with getting meshroom installed on a CentOS 7 system. In particular I have issues with the PySide2 dependency (and its shiboken2 dependency). Anyone can share some wisdom? Thanks

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ] CentOS Linux release 7.9.2009
 - Python version [e.g. 2.6] 2.7
 - Qt/PySide version [e.g. 5.12.4] I have installed Qt version 5.12.11 to support this install but I have not been able to get PySide installed yet (and shiboken2)
 - Meshroom version: please specify if you are using a release version or your own build
   - Commit reference (if applicable) [e.g. 08ddbe2] I have cloned the devel branch (commit ee408bf651325484653d8b9a6125cea274641922)

**Comment by natowi** [comment]
Try using the _exact_ versions as specified in the requirements.txt

>psutil>=5.6.3
enum34;python_version<"3.4"
PySide2==5.14.1
markdown==2.6.11
requests==2.22.0
