### ISSUE TITLE
[bug]meshroom doesnt generate /imageMatches.txt file

### ISSUE THREAD

**Issue by ronvais1** [alicevision/meshroom#1311]
**Describe the bug**
While runing meshroom on set of pictures (taken on galaxy S20+ with default node organization) the program poped a warning about imageMatches,txt file missing at FeatureMatching node - i checked the path and it realy didnt generate that file to that specific path
when checking the previous node (ImageMatching) the program log says that the imageMatches.txt was exported 
note: the program is run in admin mode and i made sure no authorization problems should happen 

**Log**
ImageMatching log:
Program called with the following parameters:
 * featuresFolders =  = [C:/Users/admin/Desktop/Meshroom-2021.1.0/man/1/MeshroomCache/FeatureExtraction/b51d413d466f967e6e4b8326205d491f78d9d6e4]
 * input = "C:/Users/admin/Desktop/Meshroom-2021.1.0/man/1/MeshroomCache/CameraInit/ca84cf1cdd9348e34248f581fa59ea03a5ff3ca3/cameraInit.sfm"
 * matchingMode = "a/a" (default)
 * maxDescriptors = 500
 * method =  Unknown Type "enum EImageMatchingMethod"
 * minNbImages = 200
 * nbMatches = 50
 * nbNeighbors = 50 (default)
 * output = "C:/Users/admin/Desktop/Meshroom-2021.1.0/man/1/MeshroomCache/ImageMatching/8c66b81da260e9ce01c9961dfbc94e989c486dd6/imageMatches.txt"
 * outputCombinedSfM = "" (default)
 * tree = "C:\Users\admin\Desktop\Meshroom-2021.1.0\aliceVision\share\aliceVision\vlfeat_K80L3.SIFT.tree"
 * verboseLevel = "info"
 * weights = ""

[05:25:23.093506][info] Use EXHAUSTIVE method.
[05:25:23.093506][info] Number of selected image pairs: 1275
[05:25:23.382056][info] pairList exported in: C:/Users/admin/Desktop/Meshroom-2021.1.0/man/1/MeshroomCache/ImageMatching/8c66b81da260e9ce01c9961dfbc94e989c486dd6/imageMatches.txt

FeatureMatching log :

Program called with the following parameters:
 * crossMatching = 0
 * describerTypes = "sift"
 * distanceRatio = 0.8
 * exportDebugFiles = 0
 * featuresFolders =  = [C:/Users/admin/Desktop/Meshroom-2021.1.0/man/1/MeshroomCache/FeatureExtraction/b51d413d466f967e6e4b8326205d491f78d9d6e4]
 * geometricError = 0
 * geometricEstimator =  Unknown Type "enum aliceVision::robustEstimation::ERobustEstimator"
 * geometricFilterType = "fundamental_matrix"
 * guidedMatching = 0
 * imagePairsList =  = [C:/Users/admin/Desktop/Meshroom-2021.1.0/man/1/MeshroomCache/ImageMatching/8c66b81da260e9ce01c9961dfbc94e989c486dd6/imageMatches.txt]
 * input = "C:/Users/admin/Desktop/Meshroom-2021.1.0/man/1/MeshroomCache/CameraInit/ca84cf1cdd9348e34248f581fa59ea03a5ff3ca3/cameraInit.sfm"
 * knownPosesGeometricErrorMax = 5
 * matchFilePerImage = 0 (default)
 * matchFromKnownCameraPoses = 0
 * maxIteration = 2048
 * maxMatches = 0
 * output = "C:/Users/admin/Desktop/Meshroom-2021.1.0/man/1/MeshroomCache/FeatureMatching/8ef2883943370b89a905a8b7751d7a71795ecb86"
 * photometricMatchingMethod = "ANN_L2"
 * randomSeed = 5489 (default)
 * rangeSize = 20
 * rangeStart = 0
 * savePutativeMatches = 0
 * useGridSort = 1 (default)
 * verboseLevel = "info"

[05:25:25.731312][info] Load pair list from file: C:/Users/admin/Desktop/Meshroom-2021.1.0/man/1/MeshroomCache/ImageMatching/8c66b81da260e9ce01c9961dfbc94e989c486dd6/imageMatches.txt
[05:25:25.731312][warning] loadPairs: Impossible to read the specified file: "C:/Users/admin/Desktop/Meshroom-2021.1.0/man/1/MeshroomCache/ImageMatching/8c66b81da260e9ce01c9961dfbc94e989c486dd6/imageMatches.txt".

**Desktop (please complete the following and other pertinent information):**
 - OS: win10
 - Meshroom version: 2021.1.0

**Additional context**
What can make the meshroom not generate the imageMatches.txt file?

**Comment by natowi** [comment]
Can you try running Meshroom without special privileges?

**Comment by ronvais1** [comment]
hey natowi
i tryed running the program without special privileges - same thing happens

**Comment by natowi** [comment]
Maybe a cache folder hick-up? Try deleting the relevant folders in the cache folder (! loss of computation progress !) or create a new project at a new location. Don´t place Meshroom or the cache folder on the Desktop or user-folders as this can cause issues in some cases. Check if the following dataset works: https://github.com/alicevision/dataset_monstree

**Comment by colliflowers** [comment]
I have this same problem. No idea why. I've tried making new projects, I've tried using different cameras, I've tried saving a new folder, I've tried deleting the ImageMatching data folder and starting again, I've tried making the folder and the txt document beforehand, and then running the ImageMatching node (which didn't work).
And for some annoying reason, it works with example datasets. Like, maybe my images are bad, but they should at least produce something.
The image below is of the ImageMatching folder after I ran the node.
![image](https://user-images.githubusercontent.com/80601461/111044204-0bc1fa00-843f-11eb-9bfa-b079a09a27cd.png)

**Comment by colliflowers** [comment]
I think I might have found a solution. I installed an older version of Meshroom which, whilst also seeming to run faster, actually made my AVG antivirus popup, saying that they've blocked an application from making a text document, which just so happens to be imageMatches.txt. I disabled my antivirus and it now works. It seems to be getting blocked by antivirus?

**Comment by natowi** [comment]
> I disabled my antivirus and it now works. It seems to be getting blocked by antivirus for ransomware protection?

Yes, some antivirus packages block Meshroom. Add Meshroom to the list of trusted programs.

**Comment by colliflowers** [comment]
In meshroom's case, I had to add 5 instances of it to the "allowed apps" list, incase anyone with this problem is still not getting it to work. I'm presuming these are all the steps that try to make a txt document. If you're using AVG, it might be easier to just turn off ransomware protection when you run meshroom. If you're not using AVG, then idk what you need to do.
![image](https://user-images.githubusercontent.com/80601461/111067143-af042500-84ba-11eb-8462-92030d886605.png)
