### ISSUE TITLE
Time in Taskmanager [request]

### ISSUE THREAD

**Issue by datavizzard** [alicevision/Meshroom#1316]
It would be nice to the the time every node needed till it finished in the Taskmanager, a summary would be nice too. This would it be easier to find the Sweetspot for the Settings.

Node Name | Time running / Time Time spent | Node Status (running/completed)

**Comment by natowi** [comment]
When I remember correctly, @ChemicalXandco did some tests in this direction https://github.com/alicevision/meshroom/pull/842. This request is somewhat difficult to implement, as the computation time can vary based on settings and hardware resources.

**Comment by datavizzard** [comment]
Maybe my mistake, I have expressed myself a bit incorrectly

Actually it was simply read the start time from the single node (for example CameraInit) log, read the end time from the node log, calculate the used time and then display it in the task manager. And maybe at the end a grand total for the time spent for the whole stack of nodes.

Like Peter Falkingham did in https://peterfalkingham.com/2021/03/02/meshroom-2021-1-0-whats-new-and-what-parameters-to-tweak/ in the Table of **Meshroom 2021 – improvements in speed/reconstruction?**

The calculation of the estimated time is too complex and IMHO not necessary at the moment.
