### ISSUE TITLE
How to use two photo sets shot by the same camera but with different lenses

### ISSUE THREAD

**Issue by nafergo** [alicevision/meshroom#1317]
I want to use two photo sets shot by the same camera but with different lenses. 
Can someone please point me in the right direction? How to setup meshroom?

**Comment by natowi** [comment]
Meshroom should be able to detect a lense change from the metadata ("serial number" from the lens). Check in the camerinit node, there should be two entries for the intrinsics parameters. If that is not the case, please provide some more details on your camera model and image format/metadata.
