### ISSUE TITLE
Wrong release download links 

### ISSUE THREAD

**Issue by hiankun** [alicevision/meshroom#1318]
In the [release page](https://github.com/alicevision/meshroom/releases), both the links in `Meshroom 2020.1.1 (2020/10/14)` are directed to `2021.1.0`.

**Comment by natowi** [comment]
Thank you. You can find older versions here: https://www.fosshub.com/Meshroom-old.html
But we should attach the binaries to the release to have a backup in any case.
@fcastan

**Comment by natowi** [comment]
In a few minutes, all releases will be available from the Github releases page as fallback solution and as version archive
