### ISSUE TITLE
[question] What is Spherical Harmonics for?

### ISSUE THREAD

**Issue by andytany** [alicevision/meshroom#1320]
How to use this thing added in the 3d view of version 2021.1.0?

![image](https://user-images.githubusercontent.com/76229960/110108691-c7828a00-7dac-11eb-8dcb-ccad417643eb.png)

**Comment by fabiencastan** [comment]
Hi @andytany,
This allows to use a file with spherical harmonics (in a custom file format) for the lighting of the scene.
This is allows to visualize intermediate data of wip developments, so it has no interest for end users for now.
It would be good to have a dev mode to hide wip stuff.
