### ISSUE TITLE
The model texture was restored incorrectly

### ISSUE THREAD

**Issue by NSiY** [alicevision/meshroom#1322]
Good afternoon! The texture of my model was not made in the right way. It has dark areas. How do I fix this?
![Скриншот 06-03-2021 154229](https://user-images.githubusercontent.com/50863128/110204151-5ff33a00-7e93-11eb-8e56-2add52200788.png)
![IMG_20210306_122033](https://user-images.githubusercontent.com/50863128/110204155-68e40b80-7e93-11eb-88b1-76723283627b.jpg)

**Comment by natowi** [comment]
How does the Meshing result look like? (without Texture)
