### ISSUE TITLE
ImageMatching crashes

### ISSUE THREAD

**Issue by adam-bielanski** [alicevision/meshroom#1326]
**Describe the problem**
I have sometimes an unexpected stop at ImageMatching stage, completely out of blue. I think it happens more often when I mix SIFT & AKAZE in FeatureExtraction, but not sure...

**Log**
WARNING: downgrade status on node "FeatureMatching_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureMatching_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureMatching_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "StructureFromMotion_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "ImageMatching_1":
Log:
Program called with the following parameters:
 * featuresFolders =  = [C:/Temp/MeshroomCache/FeatureExtraction/0aebb8b51003ef7b94d6e83f61732781eb949ec3]
 * input = "C:/Temp/MeshroomCache/CameraInit/f737a8d938fe72e700a23158e689606e8559f0a4/cameraInit.sfm"
 * matchingMode = "a/a" (default)
 * maxDescriptors = 500
 * method =  Unknown Type "enum EImageMatchingMethod"
 * minNbImages = 50
 * nbMatches = 50
 * nbNeighbors = 50
 * output = "C:/Temp/MeshroomCache/ImageMatching/4045a6d9c71e635a2e9d2f99023821b983266c48/imageMatches.txt"
 * outputCombinedSfM = "" (default)
 * tree = "C:\Program Files\Meshroom-2020.1.1\aliceVision\share\aliceVision\vlfeat_K80L3.SIFT.tree"
 * verboseLevel = "info"
 * weights = ""

[12:57:52.099730][fatal] Can't find descriptor of view 330027 in:
        - C:/Temp/MeshroomCache/FeatureExtraction/0aebb8b51003ef7b94d6e83f61732781eb949ec3
**Desktop (please complete the following and other pertinent information):**
 - OS:  win 
 - Python version - no idea
 - Qt/PySide version - no ideaa
 - Meshroom version: 2020.1.1 release

**Comment by remmel** [comment]
As the descriptor is missing, the problem seems to come from FeatureExtracting node an seems to occurs when you have more than 40 images and customizing the 1st steps of the pipeline, I have a similar problem: https://github.com/alicevision/meshroom/issues/1240

You have 50 images right? Does it work with 39 images? My workaround was to copy pasting the .desc and .feat but in you case thoses are different from non customized node
