### ISSUE TITLE
Speed up/clean up feature

### ISSUE THREAD

**Issue by adam-bielanski** [alicevision/meshroom#1327]
Commercial software Zephyr has an interesting add-on called Masquerade that speeds up/ simplifies the work.
In a simple way you may mask the image for the main programme to define "foreground" and 'background", items to be calculated and items to be ommited. I would perfectly work for example in case of some trees branches in front of the building facade.
On the other hand time spent on masking images would significantly reduce calculation overall time and would give better final results (less noise)
Can anyone invent something like that for Meshroom?

**Comment by natowi** [comment]
It is already on the to do list but nothing ready to use for the genera public. https://github.com/alicevision/meshroom/issues/713 has all the answers/news/early stage demo links
