### ISSUE TITLE
Meshroom2021.1.0 - CameraInit error

### ISSUE THREAD

**Issue by adam-bielanski** [alicevision/meshroom#1328]
**Describe the bug**
The CameraInit module generates false directory on output the path is marked with "/" instead of "\", therefore all stops, telling that output directory does not exist. 

**To Reproduce**
1. Go to 'import images' and then to the text window
2. See error

**Expected behavior**
The module should import images, but it does nothing.

**Screenshots**.

**Log**
WARNING:root:importFilesDialog fileUrls: file:///C:/Temp/IMG/proste/IMG_20210308_112138.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_112141.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_112204.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124323.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124325.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124327.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124328.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124330.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124331.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124337.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124339.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124341.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124342.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124344.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124345.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124347.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124348.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124350.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124351.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124352.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124353.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124354.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124355.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124357.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124357_1.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124359.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124400.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124401.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124403.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124404.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124406.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124407.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124410.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124412.jpg,file:///C:/Temp/IMG/proste/IMG_20210308_124414.jpg
Program called with the following parameters:
 * allowSingleView = 1
 * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1"
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:\Users\Adam\AppData\Local\Temp\tmpyf780ap7/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"
 * output = "C:/Users/Adam/AppData/Local/Temp/tmpyf780ap7/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm"
 * sensorDatabase = "C:\Temp\Meshroom-2021.1.0\aliceVision\share\aliceVision\cameraSensors.db"
 * useInternalWhiteBalance = 1
 * verboseLevel = "info"
 * viewIdMethod =  Unknown Type "enum aliceVision::sfmDataIO::EViewIdMethod"
 * viewIdRegex = ".*?(\d+)" (default)

[10:41:19.919593][warning] Some image(s) have no serial number to identify the camera/lens device.
This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximation they will share the same internal camera parameters.
35 image(s) are concerned.
[10:41:19.945524][info] CameraInit report:
        - # views listed: 35
           - # views with an initialized intrinsic listed: 35
           - # views without metadata (with a default intrinsic): 0
        - # intrinsics listed: 1
ERROR:root:Error while building intrinsics: [Errno 2] No such file or directory: 'C:/Users/Adam/AppData/Local/Temp/tmpyf780ap7/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm'
Traceback (most recent call last):
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 818, in importImagesUrls
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 805, in importImagesFromFolder
  File "d:\release\BUILD\meshroom\meshroom\ui\reconstruction.py", line 874, in buildIntrinsics
  File "d:\release\BUILD\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 282, in buildIntrinsics
  File "d:\release\BUILD\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 92, in readSfMData
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Adam/AppData/Local/Temp/tmpyf780ap7/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm'
WARNING:root:Model size of -357 is less than 0
WARNING:root:Model size of -47 is less than 0
WARNING:root:ShellExecute 'file:///C:/Users/Adam/AppData/Local/Temp/MeshroomCache/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/' failed (error 2).

**Desktop (please complete the following and other pertinent information):**
 - OS: Windows 10
 -  Python version: no idea/irrelevant
 - Qt/PySide version: no idea/irrelevant
 - Meshroom version: 2021.1.0 release
 - 
**Additional context**
2020 release works fine on my machine.

**Comment by adam-bielanski** [comment]
Just an update - 2021.1.0 doesn't recognize camera....
![obraz](https://user-images.githubusercontent.com/79451289/111027674-07232480-83f2-11eb-8312-53a2d7acabda.png)
.... that 2020.1.1 does with no problem
![obraz](https://user-images.githubusercontent.com/79451289/111027761-97fa0000-83f2-11eb-881e-6f1922dbbc98.png)

Another (tiny) issue - when I press start button on 2020 it's changing colour (as it should), but on 2021 there is no change on clicking the button.

**Comment by natowi** [comment]
[I figured out](https://github.com/alicevision/meshroom/issues/1336#issuecomment-798870139), that "viewIdMethod = Unknown Type "enum aliceVision::sfmDataIO::EViewIdMethod"" occurs, when images have no metadata (or no metadata was detected), changing to viewIdMethod: filename helps.
But your images _have_ metadata and Meshroom does not recognize  it.
Any idea why your imported images in 2021 show the filename like this: _IMG_0182.jpg **-1**_ ?

**Comment by adam-bielanski** [comment]
I started with a set of my images and I thought I made some mistakes taking/downloading them. Therefore I tried the sample set with clearly definded metadata in it, unfortunately with the same result.
I have no idea what's wrong, I avoided long paths creating C:\MR\ folder for resting to avoid any "naming" problems, all in vain. Ufortunately the set without metadata is not recognized by SfM module and leaves blank space.

**Comment by natowi** [comment]
As I said before, I don´t have any issues with the dataset or version 2021. It is most likely an issue on your side. There could be numerous causes: https://github.com/alicevision/meshroom/wiki/Images-cannot-be-imported https://github.com/alicevision/meshroom/wiki/Troubleshooting

A similar issue was posted here:

> WARNING:root:importFilesDialog fileUrls: file:/

https://github.com/alicevision/meshroom/issues/1194

--

Is there a reason why you have the Live Reconstruction pane is open?

**Comment by adam-bielanski** [comment]
@natowi 
I've just realised that AV software (Comodo in my case) is to be blamed. 
Reconstruction panel opens "by default" at 2020
