### ISSUE TITLE
CPU/GPU/memory specification

### ISSUE THREAD

**Issue by mcuma** [alicevision/meshroom#1331]
First of all, thank you for creating a good intuitive 3D reconstruction program.

Also apologies if this is a duplicate question, I can't find an answer searching through the GitHub issues.

We are using Meshroom in a high performance computing (HPC) environment that supports sharing of node resources between multiple jobs. E.g. on a machine with 64 CPU cores and 256 GB RAM, we may only give the Meshroom job 1/2 of the node (32 CPUs, 128 GB RAM). 

From what I can tell, Meshroom tries to use the whole node, regardless of what part of it was allocated to it (in our case, using Linux cgroups through the SLURM job scheduler). Is there any way to tell Meshroom at run time how much CPU/memory to use? If not that would be a very useful feature to add.

On a similar note, if we also allocate GPUs this way, how does Meshroom grab those GPUs. Can one e.g. use CUDA_VISIBLE_DEVICES? And, will it support multiple GPUs in a single node?

Thanks,
Martin

**Comment by fabiencastan** [comment]
There is no option to limit the resources within meshroom, but you can use docker to limit the resources available to the execution. But I agree it would be good to be able to provide a max RAM and max nb CPUs using env variables and take that into account in AliceVision.

CUDA enumerates the available devices in fastest to slowest order by default, so we just pick the first one. If you precise CUDA_VISIBLE_DEVICES, it should be taken into account.

It would be great to see a SLURM submitter in Meshroom.

**Comment by natowi** [comment]
@fabiencastan https://github.com/alicevision/meshroom/wiki/Renderfarm-submitters#slurm-farm-hpc
