### ISSUE TITLE
[bug] latest meshroom can't import EXR images

### ISSUE THREAD

**Issue by ahemberger** [alicevision/meshroom#1336]
Trying to import exr images that imported fine in previous Meshroom versions, now I get an error:

"You probably have a corrupted image within the images you are trying to import". 

This error is thrown even when I try to import a single image. 

Sample exr image that causes this problem:
https://www.dropbox.com/s/gn2y2xwhca4ljnb/plate_cc.0.exr?dl=0

**Comment by natowi** [comment]
![test22](https://user-images.githubusercontent.com/8138537/111062200-c84fa600-84a7-11eb-8064-2558aaa03c9a.jpg)

Import works fine for me, but computing CameraInit takes suspiciously long. Stopping processing leads to GUI freeze. I think the cause could be the missing metadata and the default setting: viewID: metadata
which causes an error. Before importing images, change the _ViewID method_ to _filename_ and it should work. Maybe this also resolves your corrupted image message.

**Comment by ahemberger** [comment]
No, this doesn't help; I see the same error.

Is there a prerequisite install that the standalone Meshroom expects? Some EXR library perhaps? Nothing mentioned in docs.

**Comment by natowi** [comment]
> Is there a prerequisite install that the standalone Meshroom expects?

The only thing that comes into mind is [Visual C++  Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) 
taken from https://github.com/alicevision/meshroom/wiki/Troubleshooting
