### ISSUE TITLE
Is there a way to “help” or guide the camera reconstruction? [question]

### ISSUE THREAD

**Issue by xDEADC0DE** [alicevision/meshroom#1339]
**Describe the problem**
In my scene some pictures are not matched, even though they seem to be similar to other photos that have been correctly identified.
Is there a way to help the algorithm figure out where theses pictures should be?
If not, is it possible to know why those picture weren’t reconstructed?

**Screenshots**
![image](https://user-images.githubusercontent.com/1249572/111300306-3aafba00-8651-11eb-8d1c-7046c774b6fa.png)

**Dataset**
The dataset is 300+ pictures of a statue, taken at different times. The photos in the screenshot were taken at the same moment.

**Desktop**
 - OS: Windows 10
 - Meshroom version: 
   - Binary version 2021.1

**Comment by natowi** [comment]
>  If not, is it possible to know why those picture weren’t reconstructed?

They look like they were taken from the same position with a zoom. Even if you moved your camera toward the statue in a line, there is still not enough information to match the images. Better move around the statue and try to increase the overlap. Also ...204 seems to be a bit blurry.

**Comment by xDEADC0DE** [comment]
203 to 206 are indeed taken from the same position as 202 but zoomed in.
204 is not blurry at all, it actually looks particularly sharp… 203 is though, I’ll try removing it.

**Comment by natowi** [comment]
Zooming should be avoided at all costs when taking images for photogrammetry.
Always physically move your camera in space and keep an image overlap of 60%+.
(There are cases where it could be necessary to zoom in, but you should never take the zoomed in images from the same location.)

**Comment by xDEADC0DE** [comment]
I didn’t think about that! Of course zooming changes the perspective and makes it harder for the algorithm to understand what it’s looking at!

The statues I’ve photographed are 5 m above street level unfortunately, so every photo is zoomed-in 😅
Meshroom did a pretty good job anyways, I’ll just have more cleanup to do in Blender. 
Thanks for the info.

**Comment by natowi** [comment]
> so every photo is zoomed-in

As I said, in some cases this can´t be avoided. Meshroom can work with that, but you should follow the general guidelines for capturing images for photogrammetry.

Here are a few guides. Search the web to find more.
https://vimeo.com/channels/practicalphotogrammetry
https://journalists.org/resources/a-guide-to-photogrammetry-photography/
https://studio.knightlab.com/results/photojournalism3D/the-4-key-components-to-photogrammetry-capture/
https://unity3d.com/files/solutions/photogrammetry/Unity-Photogrammetry-Workflow_2017-07_v2.pdf
