### ISSUE TITLE
Good day all,[question]

### ISSUE THREAD

**Issue by Hellrazorblades** [alicevision/meshroom#1341]
**Describe the problem**
A clear and concise description of what the problem is.

**Screenshots**

**Dataset**
If applicable, add a link or *few* images to help better understand where the problem may come from.

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ]
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1]
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**

**Comment by Hellrazorblades** [comment]
I'm brand you to meshroom and I have this error, I hope there is something to do with that! Thanks for your help !!!

ERROR:root:Error on node computation: Error on node "PrepareDenseScene_1(0)":
Log:
Program called with the following parameters:
 * evCorrection = 0
 * input = "C:/Users/François/Desktop/MeshroomCache/StructureFromMotion/e26f7e042ce54c155f0c4f437e9c303a552796ac/sfm.abc"
 * output = "C:/Users/François/Desktop/MeshroomCache/PrepareDenseScene/40f2b344fe9356aa2f84ff4f6b9b10f7dceda24b"
 * outputFileType = "exr"
 * rangeSize = 40
 * rangeStart = 0
 * saveMatricesTxtFiles = 0
 * saveMetadata = 1
 * verboseLevel = "info"

Exporting Scene Undistorted Images
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
[21:31:13.799834][info] Median Camera Exposure: 0.64, Median EV: 0.643856

WARNING:root:Downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Status.NONE
WARNING:root:Downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING:root:Downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING:root:Downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE

Thanks for your help !!!

**Comment by natowi** [comment]
Avoid special characters like ç in your folder path and it will work
