### ISSUE TITLE
Inconsistant 3D Production

### ISSUE THREAD

**Issue by phanthanhkhai480** [alicevision/meshroom#1343]
**Describe the problem**
I was using the software for one of my projects in the school, with the exact dataset, using default parameter in Meshroom, and suddenly, I found that when using the proceeding the same dataset, with the same default parameter, it provides a totally different result. It's not like 5-10% different, which I can totally understand, but this one is off by like 20-25%. 

**Screenshots**
**Dataset1**: 
- Vertices: 224185 - Faces: 447086 ![1](https://user-images.githubusercontent.com/50007190/111523775-0cee7200-8732-11eb-8fc7-50bb83679b7a.PNG)
- Vertices: 161795- Faces: 322899
![2](https://user-images.githubusercontent.com/50007190/111523790-0f50cc00-8732-11eb-847f-ab46fc31839b.PNG)

**Dataset2**: 
- Vertices: 224185 - Faces: 447086 ![3](https://user-images.githubusercontent.com/50007190/111523817-1677da00-8732-11eb-9ebd-08cfaf8c95e0.PNG)
- Vertices: 173582 - Faces: 345922 ![4](https://user-images.githubusercontent.com/50007190/111523824-17a90700-8732-11eb-9b05-fc986179f6c3.PNG)

**Dataset**
The image is not available for the public :(.

**Log**
Seems like there is no log as I run the program via Meshroom so :(. I was trying to run the meshroom_photogrammetry but figure I might want to try something with the GUI first. 

**Desktop (please complete the following and other pertinent information):**
 - OS: **Tested in Windows 10, Fedora 33** 
 - Python version: **>3.5**
 - Qt/PySide version: **unsure**
 - Meshroom version: please specify if you are using a release version or your own build: **I used the release version for both**

**Additional context**
I would like to know if there is anything I can do to make the model consistent. I didn't change anything, keep all as default as I believe if I do change some parameter, it might clearly show the difference.

**Comment by natowi** [comment]
Depending on what images Meshroom choses as initial camera pair the result can vary.
So the result will vary from reconstruction to reconstruction. But the difference is quite drastic in your case.

But there are a few things you can do to improve the results in general:
- it looks like you try to capture a person. From what I can see from the scene your shooting conditions are far from ideal.
- follow the general advices on capturing images for photogrammetry

Here are a few guides. Search the web to find more.
https://vimeo.com/channels/practicalphotogrammetry
https://journalists.org/resources/a-guide-to-photogrammetry-photography/
https://studio.knightlab.com/results/photojournalism3D/the-4-key-components-to-photogrammetry-capture/
https://unity3d.com/files/solutions/photogrammetry/Unity-Photogrammetry-Workflow_2017-07_v2.pdf

**Comment by phanthanhkhai480** [comment]
For capturing the person, there is no movement in the object and the reason the dataset seems to be dark is that there are many small objects inside the room, so we have to put some light into the body to allow the software to distinguish between the main object vs. irrelevant one. I was trying to get the bokeh on the main object but it doesn't work so... Is there any parameter I can use to improve this or this would strongly depend on the dataset?

**Comment by natowi** [comment]
Here are general parameters you can tweak https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters

> that there are many small objects inside the room, so we have to put some light into the body to allow the software to distinguish between the main object vs. irrelevant one.

If you are unable to recreate a real studio environment, don´t.
In this case better check that everything is well lit and there are now hard shades.
The "irrelevant background objects" can actually help with the camera estimation process, as the provide additional features that can be detected. Of course this comes at the cost of computation time.
The best thing to minimize the reconstruction time is to shoot images where the person or object of interest fills up 80%+ of your images. Shoot close up images and avoid landscape images with the person in the middle, filling only 1/3 of the image as it will increase the reconstruction of unwanted surroundings and computation time and decrease the quality/resolution of your target if this are your only images.

**Comment by phanthanhkhai480** [comment]
Hey Natowi, thanks a lot for your advice and guided information on the picture as I tested it with different datasets that like you said and the result is only different in a range of 0.1%->1%. Just wanna check if this range is an acceptable rate? Also, besides parameter tweak in the software, would upgrading the hardware make the process faster? I am currently using a Ryzen 7 2700x/32GB RAM/RTX 3070. Thanks alot

**Comment by natowi** [comment]
> the result is only different in a range of 0.1%->1%. Just wanna check if this range is an acceptable rate?

Which result? Is this your calculation of the differences? Then yes, that sounds about right.

> would upgrading the hardware make the process faster? I am currently using a Ryzen 7 2700x/32GB RAM/RTX 3070.

Your setup is quite good. You probably already have a SSD installed, if not, you could think about it. 32GB Ram is more than enough to start with (will handle a ~2000 images or a few hundred high-res raw images). For larger projects monitor the RAM usage and if you regularly come close to 32GB, you can think about upgrading it.

**Comment by phanthanhkhai480** [comment]
The result for # of vertices and faces between each reconstruction process. I have an NVMe installed so that should be good. For the RAM, you are right, I've never reached the 32 limits. However, the CPU kinda bottleneck as it is always running at 100% @4.1GHz across 16 threads, while the GPU is not doing much work (CUDA running about 40%). Is there a way I can share the work to both GPU and CPU to faster the process?

**Comment by phanthanhkhai480** [comment]
For the ForceCPUExtraction, I already found that and it seems that is the only place I can find where i can utilize the GPU for using.

**Comment by natowi** [comment]
> Is there a way I can share the work to both GPU and CPU to faster the process?

Sadly, no.

> and it seems that is the only place I can find where i can utilize the GPU for using.

That´s right. GPU support in FeatureExtraction is still experimental, as it will not work from time to time depending on the size of your dataset, and DepthMap is the only other node that utilizes the GPU at the moment.
