### ISSUE TITLE
[bug] wrong release date on website (typo)

### ISSUE THREAD

**Issue by FrankBau** [alicevision/meshroom#1344]
**Describe the bug**
https://github.com/alicevision/meshroom/releases/tag/v2021.1.0 headline says 
Release 2021.1.0 (202**0**/02/26)
which should read
Release 2021.1.0 (202**1**/02/26)

**To Reproduce**
1. Go to 'https://github.com/alicevision/meshroom/releases/tag/v2021.1.0'

**Expected behavior**
https://github.com/alicevision/meshroom/releases/tag/v2021.1.0 headline should say 
Release 2021.1.0 (2021/02/26)

**Additional context**
Seems to be a trivial typo but is confusing.

**Comment by simogasp** [comment]
Thanks it should be ok now!
