### ISSUE TITLE
win10 egpu nvidia gtx 1050ti

### ISSUE THREAD

**Issue by EnzoCastellaneta** [alicevision/meshroom#1345]
Hello, I bought on Lenovo yoga 920 a thunderbolt 3 razen egpu device with msi gtx 1050ti.

System recognizes the videocard and other apps (i.e. flight simulator 2020) work perfectly. I forced under panel, video, video card advanced, to use for meshroom.exe the nvidia card but at cuda step it stops in saying that recognizes not an installed cuda gpu.

Any solution?

**Comment by natowi** [comment]
You are the first using an eGPU, so no experience there. Here you can find all information related to GPU issues: https://github.com/alicevision/meshroom/wiki/Error:-This-program-needs-a-CUDA-Enabled-GPU https://github.com/alicevision/meshroom/wiki/DepthMap-slow-or-red-bar-or-crash

**Comment by EnzoCastellaneta** [comment]
already read, unfortunatelly nothing useful. 

It's not something related to drivers... it is much more  something related to a system call to main video card instead of looking for installed cards that suite (I tried also to disable integrated videocard but nothing happened).

**Comment by natowi** [comment]
I don´t know how eGPUs are being handled by the system drivers compared to a second build in GPU. Meshroom probably does not detect the external card as available. Setting the eGPU as primary GPU is probably also not possible. 
Maybe the force GPU settings are only applied to the meshroom.exe but is not correctly applied to all subprocesses like depthmap.
You could try to add the aliceVision_depthMapEstimation.exe from meshroom\aliceVision\bin to the nvidia list and enable force gpu for this tool as well.

**Comment by EnzoCastellaneta** [comment]
unfortunately also adding depthMap*.exe makes no differences. 
Should I add any other *.exe to windows 10 advanced graphics settings? 

I read, but I cannot find anymore the article, another guy that used under MacOS EGPU with Meshroom but with no probs... definitively win and mac are different systems but if there is support there, why couldn't be also on Windows?

Seen I am one of the earliest one to use it under EGPU... just a challenge for you all... wouldn't it be great to update your old notebook to great GPU computing without changing your whole notebook? that's the question that I am trying to experiment with this solution... I really hope that others of you could join my request for supporto to developers community.

**Comment by natowi** [comment]
Other users solved this issue by updating all nvidia related drivers https://github.com/alicevision/meshroom/issues/197 If this does not help, it is probably due to your specific eGPU setup. At the moment it is not possible to select a GPU manually in Meshroom.

**Comment by fabiencastan** [comment]
Could you show the full log of the DepthMap node?
