### ISSUE TITLE
It is possible to implement node using python to add softpool point cloud completion to the pipeline?

### ISSUE THREAD

**Issue by nicolalandro** [alicevision/meshroom#1347]
**Describe the problem**
[softpool](https://github.com/wangyida/softpool) is a newer neural network that complete your point cloud. I want to try to create a node that use it. How can I do? Is it possible to create nodes with python? Where can I find the documentation to create this node?

We can obtain improvement on the point cloud as follow:
![softpool](https://user-images.githubusercontent.com/18419702/112308377-5abf2900-8ca2-11eb-9e95-5a1a10929aa8.png)

**Comment by natowi** [comment]
>I want to try to create a node that use it. How can I do? Is it possible to create nodes with python? Where can I find the documentation to create this node?

https://github.com/natowi/meshroom_external_plugins/wiki/2-DevDoc

**Comment by nicolalandro** [comment]
Thank you! So for example I can use [this](https://github.com/natowi/meshroom_external_plugins/blob/master/MVEDepthMap2PointCloud.py) simple script to exec my program that should create into the output folder the expected files? Correct?

Thank you in advance!

**Comment by natowi** [comment]
Yes, this is a really basic example. Take a look at the other files like https://github.com/natowi/meshroom_external_plugins/blob/master/InstantMeshes.py or browse though https://github.com/alicevision/meshroom/tree/develop/meshroom/nodes/aliceVision to get a more complete idea. If you have a cli tool that has parameters to define the input and output directory and parameters, it can be implemented quite easily as a node. 
How do you intend to use softpool? Like this SFM->[convertsfmformat node]->[inputformat?]Softpool[outputformat?]->Meshing?

**Comment by nicolalandro** [comment]
Thank you, I will try to implement something.

**Comment by natowi** [comment]
@nicolalandro I´d be interested to see the your results of your work when it is ready

**Comment by nicolalandro** [comment]
I will let you know, but I'm new to this world and it is not for my work, so I will take some time.

**Comment by nicolalandro** [comment]
@natowi, as I said I'm very slow. I'm not arrived to the softpool, but I succeded in train an AtlasNet you can see [there](https://github.com/nicolalandro/completion3d). As you can see in [this competition](https://completion3d.stanford.edu/) this network is the worst, and softpool should be better, but is a starting point. If you are interested I do a colab notebook in wich I use a (worse) pre-trained model. The general Idea of the core code should be that but with another model.

**Comment by natowi** [comment]
Thank you for the update :) We are not in a hurry so take your time. Maybe you can get in touch with @Dok11 , he did some tests here https://github.com/alicevision/meshroom/issues/528

When you get to adding a new Meshroom node for the gui, check out the updated documentation, we now have some more details on the API https://meshroom-manual.readthedocs.io/en/latest/feature-documentation/core/nodes.html
