### ISSUE TITLE
Meshroom sfm file missing error[question]

### ISSUE THREAD

**Issue by adiethesmallone** [alicevision/meshroom#1348]
Hello, I would like to ask if there´s anyone who could help with an issue I ran into while using Meshroom. This is my first time using this program, I just followed a tutorial for beginners. I used a Canon EOS 70D to capture the photos that I wanted to use for creating a 3D model. I imported the file with the photos in jpg format into Meshroom. But when I try to start computing these images, I get an error at the very first CameraInit node stating :  [11:13:50.879900][error] The input sfm file doesn't exist
I´m not really sure how to resolve this issue on my own
I´m using an official release from the website on a Windows 10 laptop.

**Comment by adam-bielanski** [comment]
Hi @adiethesmallone,
I had initially similar problem with Meshoom 2021. It appeared that the problem caused my antivirus software that treats Alicevsion modules as viruses. So... check your AV first and re-run Meshroom.
Adam
