### ISSUE TITLE
[bug] Images with the same EXIF information are ignored

### ISSUE THREAD

**Issue by esrat** [alicevision/meshroom#1353]
**Describe the bug**
Meshroom does not accept images with the same EXIF camera and timestamp information.

**To Reproduce**
Just try to add more than one image file with the same EXIF camera and timestamp information to the project. - Meshroom will only accept the first one, ignoring all others.

**Expected behavior**
Meshroom should accept any number of image files with the same EXIF information.

**Desktop (please complete the following and other pertinent information):**
 - OS: Windows 7 Professional 64 Bit
 - Meshroom version:
   - binary release versions: 2018.1.0, 2019.1.0, 2019.2.0, 2020.1.1, 2021.1.0 (maybe more)

**Additional context**
Every version I've ever used does ignore image files with similar EXIF information. I was never too happy about having to delete all EXIF data from my files before I could add them to Meshroom. I often have to record automatic picture series, because I don't have the time to choose every angle manually or I simply can't reach the record button for some angles I have to hold the camera in. This results in multiple pictures per second!

**Comment by fabiencastan** [comment]
If metadata are available and fully identical, we consider that it is the same image. So if you move your images into another folder it will keep the same ID.
We use the time in milliseconds if available: "Exif:SubsecTimeOriginal", so you should not have this issue:
https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/sfmData/uid.cpp#L53
Maybe it's not set with your camera? What camera are you using?
Is it only the images within the same second that are considered as a single image?

**Comment by natowi** [comment]
@fabiencastan I added this info to the wiki. Maybe we could add a notification window for such cases to inform the user why the images were not added.

**Comment by esrat** [comment]
> Maybe it's not set with your camera? What camera are you using?

My picture series I do record using a Samsung Galaxy S5 Mini and the app OpenCamera. Under Windows I use other free tools like IrfanView which also only knows / supports a precision of seconds.

> Is it only the images within the same second that are considered as a single image?

Yes, exactly the pictures with the same timestamp, up to the last digit which is the second for most of the tools. (I've read about the possible support of milliseconds but obviously that is not used by many common tools.)

**Comment by fabiencastan** [comment]
Ok, so we should probably add the file "DateTime" when "Exif:SubsecTimeOriginal" is missing.

**Comment by esrat** [comment]
What do you mean?
Are you speaking of the file system's timestamp? Then I would not encourage that way. Different systems have different resolutions and much information is lost during copying. (In my case the files do carry _about_ the correct time, maybe plus some seconds if the JPEG encoding did take some time. I also can see only seconds, under Windows.) In some situations (e.g. no direct access to the files allowed – only some kind of “media connection”) with several devices the file timestamps will be lost completely while transferring the pictures to the PC. - In general I would not expect any benefit in using the system's timestamps.

**Comment by esrat** [comment]
I've checked my example again:
It's not the encoding time which produces the difference between EXIF time and file time, it's the resolution of the file system's time itself! The files themselves do have only a timestamp resolution of 2 seconds.
That should be considered the normal case, because most memory cards will use some FAT system to be compatible with as much devices and operation systems as possible.

So the 1-s-resolution of the EXIF timestamp is the best you can get - but _not sufficient_ to identify a picture of some camera!

I've also examined other EXIF data of all the devices I've used so far. - Only some borrowed NIKON camera did write SubsecTimeOriginal and some "Serial number" (but created file timestamps with a 2-s-resolution!). Neither my compact camera nor the smartphone did write these.
It's not that uncommon that two people use the same consumer compact camera or the same Samsung smartphone. So, you cannot even detect the device using EXIF - how do you expect to identify a specific photo taken with that device???
