### ISSUE TITLE
E' possibile fare il calcolo sino al nodo Mesghing, solo esclusivamente della nuvola densa.....senza calcolare la mesh! 

### ISSUE THREAD

**Issue by MarcoRos75** [alicevision/meshroom#1354]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MarcoRos75** [comment]
Ciao! volevo sapere se è possibile calcolare la sola nuvola di punti densa......e lasciare in un secondo momento il calcolo della mesh!!!

**Comment by ChemicalXandco** [comment]
Hello, does the discussion in issue #888 help you?

**Comment by natowi** [comment]
![exportpcl1](https://user-images.githubusercontent.com/8138537/112762740-a60a6c00-9001-11eb-868e-2657034002b0.JPG)
![exportpcl2](https://user-images.githubusercontent.com/8138537/112762741-a73b9900-9001-11eb-88ee-2398b02e9ccc.JPG)

**Comment by MarcoRos75** [comment]
Grazie natowi !!! le impostazioni del nodo che mi hai indicato, le conosco!  Non so se è solo un mio capriccio ...! Ma mi piacerebbe poter scegliere di calcolare solo la nuvola di punti densa..... e magari poi calcolare la mesh...!!! aspetterò sviluppi futuri del programma!!!

**Comment by MarcoRos75** [comment]
Grazie ChemicalXandco!  ci darò una occhiata! ma ho capito che per il momento bisogna portare a termine tutto il lavoro del nodo....quini anche la mesh  per poi avere la nuvola densa di punti.

**Comment by MarcoRos75** [comment]
Per il momento si chiude il post!   Aspettiamo aggiornamenti futuri del programma Meshroom...che già così è fantastico!!! Grazie!
