### ISSUE TITLE
[question] Usage of KeyframeSelection bound to special restrictions?

### ISSUE THREAD

**Issue by esrat** [alicevision/meshroom#1356]
**Describe the problem**
I am able to use the KeyframeSelection node to successfully filter a directory of video frames, using the default options.
I would like to use it also for photo series! I thought it should work when I set the min and max frame steps to minimal values to not lose too much pictures. I just want it to compare directly successive pictures for sharpness and lighting, letting through every nth picture (according to the settings) which seems to be a usable source. That **does include** blurry pictures with bad lighting if there are no better ones directly before or after. (Creating a bad / low resolution model is better than creating no model at all!)
Right now, the best I was able to get for some test series was a subset of pictures which only showed the front side of some wooden bench. There was some slope behind the bench, so I was not able to get proper sharp pictures of its back. - I expected the algorithm to let through every single one of them, because there are no better ones at all. But it filtered out ALL of the back side pictures so that it is not possible to create a holistic model of the bench anymore.

So: _Is there a way to get the KeyframeSelection to work like I would expect it to work?_

**Log**
The log does not give any details on why it used or skipped pictures, even on trace level.

**Desktop**
- OS: Windows 7 Professional 64 Bit
- Meshroom version: binary version 2021.1

**Additional context**
My **picture set is not ideal**! I had very tight time constraints to not completely lose my fellow hikers. So, I just took out my smartphone and started recording a picture series without any preparation. I am not expecting any fine-tuned model from this.
I also had to disable "Use Sparse Distance Selection" completely. With it enabled the algorithm just took the first 1 to 3 pictures and skipped all others!?

**Comment by HarikalarKutusu** [comment]
I ran into a similar problem and I had to untick related algorithms to just get N image-frames/per-second on drone videos (3-5 min long). Then I visually scanned the extracted images to see if there are problematic ones. They were 4K@100Mbps, so no blur. I removed out-of-scope images (too far, viewing to unrelated areas etc).

So basically I could have done the same with Premiere Pro, ffmpeg or similar SW...

In one image set with sharp shadows, I used IrfanView in batch mode to reduce contrast + sharpen the images a bit.
