### ISSUE TITLE
[question] Problem with dataset reconstruction 

### ISSUE THREAD

**Issue by billyk1990** [alicevision/meshroom#1358]
Hello!

I am new to photogrammetry and I am trying to make a simple model. I have taken many sets of photos but the results are not so good. Mainly the problem is that many photos are rejected (camera: not reconstructed). 
I tried to place the object in a white space, I took the photos from a lot of angles, i changed the describer preset to high etc. I think that the main problem is lighting but i am not sure.. And if it is, I don't know how to solve it!
These are the links to 3 datasets: 

a) https://drive.google.com/drive/folders/106iEFSi7nmuOy9x1uVXUG5vwm3dJGpJx?usp=sharing 

b) https://drive.google.com/drive/folders/1-ZwbVAwnViesJ6uNv8ZDjfFGxV6_S4Ca?usp=sharing

c) https://drive.google.com/drive/folders/1kJu0eDd1lQyNiptQB-qg73YcA50LXWpd?usp=sharing 

The second issue is that even the parts that are constructed are not well detailed! I have taken photos from a close distance and I use a tripod, but the surface of my object is not well-constructed. 

Any tip would be highly appreciated! 
Thank you!

**Comment by natowi** [comment]
> I am trying to make a simple model

Your model is not an easy one to start with: small size, many single coloured areas, smooth surface, reflections

In addition to that your captured images are not ideal: many are blurry or overexposed, you turned the model but kept the background with a hard line, many images are nearly identical in their point of view.

If you are just looking for something to scan to test Meshroom, best choose an object from nature or made of natural materials, avoid anything too smooth, reflective or single coloured.

If it has to be your figurine, capture the images by moving around and without moving it. Read up on how to set up a turntable with featureless background (there are diy solutions out there)

**Comment by natowi** [comment]
Is this an ancient model or replica? 20 cm is a good size and probably larger than your test model.

> So you think i should not turn it, and I should turn so meshroom can have more surrounding points to locate?

You can move around your model to take images, but there are a few things to consider: don´t move or turn your model in any way during the capturing. The background will mess up the matching process if you move it. If you have to do this, mask out the background in your images.

> What I do now is to have the sun light on my background when i shoot!

You should have total control of the lighting conditions of your shooting area. Shades, reflections and glares should be avoided.

I would highly recommend you to invest in a foldable LED lightbox (Shooting Tent) (20-50€ depending on the size) that can help with lighting and applying a featureless background.
You could then manually turn your model or use a turntable. In both cases use a tripod and a remote/auto trigger if possible.
With the single coloured backdrop you can easily rotate your model as you like. If you use a turntable, you need to build a support structure to hold the model turned upside down in position. Do a full rotation of the model and shoot images of the lower third (without parts of the turntable!) and the upper part. Then turn your model upside down and do the same.


The white areas on your model may cause problems.
Experimental setup:
In this case you could project light patterns on the surface and move your camera around the model (as I doubt it is possible to physically alter your model by painting on it). https://github.com/alicevision/meshroom/wiki/Projected-Light-Patterns
If you want to use a turntable and the light box, you could try to project horizontal lines on your model and take two images per partial rotation: one with light pattern and one without. It is important the projector and the camera don´t move and are perfectly aligned with your model and the model is centred on the turntable. This will emulate horizontal lines being drawn on your model, which can help with the reconstruction. Unstructured patterns would be better, but then the turntable setup would no longer work, as the pattern are out of sync.

If you want datasets similar to you use case, I´m sure you can find something here https://github.com/BritishMuseumDH

I can highly recommend you to browse through this website: http://culturalheritageimaging.org/Technologies/Photogrammetry/
They have valuable tools and tutorials.

**Comment by billyk1990** [comment]
Natowi thank you so so much for your advice!!

I haven't tried it yet but your interest in my problem is more than I ever expected!! 
I don't care if it works, but I am excited for your response!

Thank you
Have a good day!

**Comment by natowi** [comment]
@billyk1990 you are welcome. It would be great if you could share your final workflow/setup or even publication once it is complete.
