### ISSUE TITLE
[question] Orthomosaic tiff/geotiff export

### ISSUE THREAD

**Issue by ELEGER** [alicevision/meshroom#1359]
Hello,
Thanks for developing Meshroom. Really neat tool.
I am using Meshroom for Orthomosaic reconstruction through SFM. I would like to know if it is possible to export an Tiff/Geotiff of the final texturing model. From what I found online, it seem we have to go through blender . But even with importing the obj in blender, I cannot get what I want: 2D, Nadir view of the reconstruction orthomosaic. Similar to what can be obtained with classical UAV reconstruction software. 
Thanks for your answer and your time.
Best
Emmanuel

**Comment by MarcoRos75** [comment]
Ciao! io spesso uso CloudCompare o MeshLab...per ricavare sezioni ed estrarre dati dalla nuvola di punti densa...! Forse  cè una funzione per ricavare ortofoto...?!?!?!

**Comment by ELEGER** [comment]
Thanks.
I was not able to extract what I wanted from Meshlab. I tried too, but was not successful. Can you export an tiff/geotiff out of Meshlab ?
Thanks
Emmanuel

**Comment by natowi** [comment]
Sorry, at the moment Meshroom does not have any functions to export Orthoimages. I can recommend Opendronemap for this purpose.

**Comment by ELEGER** [comment]
Thanks

**Comment by natowi** [comment]
Here is a Meshroom / BlenderGIS / QGIS tutorial - it´s in Italian, but shows the complete workflow

**Comment by natowi** [comment]
Glad to hear. We have an open Feature Request for this, so I will close this issue. You can leave a thumbs up here https://github.com/alicevision/meshroom/issues/246 - so we can keep track on how many people are interested in this feature.
