### ISSUE TITLE
[bug]  Error on node "CameraInit_1":

### ISSUE THREAD

**Issue by veggiet** [alicevision/meshroom#1360]
Starting a photogammetry process fails almost immediately when I start it. I believe it has something to do with my laptop because I can use a different pc with the same photos successfully. I've tried the suggestions that I've found in searching for the errors. I've added my phone's camera to the camerasensors.db file (which did cause the photos to register with a green status instead of yellow). I've tried moving the file to a folder with only ascii characters, no effect.

EDIT: I have now tried checking Virus Protection (no threats detected), disabling windows smartscreen (smartscreen was blocking individual plugins from being run from explorer,) converting all the images to png (which was suggested in a different question), running meshroom as admin and moving the meshroom folder into C:\Programs\  

**Log**
```

> `ERROR:root:Error on node computation: Error on node "CameraInit_1":
> Log:
> Program called with the following parameters:
>  * allowSingleView = 1
>  * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1"
>  * defaultCameraModel = "" (default)
>  * defaultFieldOfView = 45
>  * defaultFocalLengthPix = -1 (default)
>  * defaultIntrinsic = "" (default)
>  * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
>  * imageFolder = "" (default)
>  * input = "c:/Users/samss/Downloads/Photostree/MeshroomCache/CameraInit/cf80ecda195cdb4ad9588772a7df8de6b7e2a2bd//viewpoints.sfm"
>  * output = "c:/Users/samss/Downloads/Photostree/MeshroomCache/CameraInit/cf80ecda195cdb4ad9588772a7df8de6b7e2a2bd/cameraInit.sfm"
>  * sensorDatabase = "C:\Users\samss\Downloads\Meshroom-2021.1.0-win64\Meshroom-2021.1.0\aliceVision\share\aliceVision\cameraSensors.db"
>  * useInternalWhiteBalance = 1
>  * verboseLevel = "debug"
>  * viewIdMethod =  Unknown Type "enum aliceVision::sfmDataIO::EViewIdMethod"
>  * viewIdRegex = ".*?(\d+)"
> 
> [20:08:45.209485][info] CameraInit report:
>         - # views listed: 75
>            - # views with an initialized intrinsic listed: 75
>            - # views without metadata (with a default intrinsic): 0
>         - # intrinsics listed: 2
> 

````

System Specs:

> `OS Name	Microsoft Windows 10 Home
> Version	10.0.19042 Build 19042
> Other OS Description 	Not Available
> OS Manufacturer	Microsoft Corporation
> System Name	LAPTOP-TTJN6K5M
> System Manufacturer	LENOVO
> System Model	81SX
> System Type	x64-based PC
> System SKU	LENOVO_MT_81SX_BU_idea_FM_Legion Y540-15IRH
> Processor	Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)
> BIOS Version/Date	LENOVO BHCN36WW, 2/10/2020
> SMBIOS Version	3.0
> Embedded Controller Version	1.36
> BIOS Mode	UEFI
> BaseBoard Manufacturer	LENOVO
> BaseBoard Product	LNVNB161216
> BaseBoard Version	SDK0R32862 WIN
> 
> Installed Physical Memory (RAM)	32.0 GB
> Total Physical Memory	31.9 GB
> Available Physical Memory	18.7 GB
> Total Virtual Memory	64.4 GB
> Available Virtual Memory	38.4 GB
> Page File Space	32.5 GB
> 
> Name	NVIDIA GeForce GTX 1660 Ti
> PNP Device ID	PCI\VEN_10DE&DEV_2191&SUBSYS_3FFC17AA&REV_A1\4&FE38360&0&0008
> Adapter Type	GeForce GTX 1660 Ti, NVIDIA compatible
> Adapter Description	NVIDIA GeForce GTX 1660 Ti
> Adapter RAM	(1,048,576) bytes
> Installed Drivers	C:\WINDOWS\System32\DriverStore\FileRepository\nvlt.inf_amd64_c8af195ee1543133\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvlt.inf_amd64_c8af195ee1543133\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvlt.inf_amd64_c8af195ee1543133\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvlt.inf_amd64_c8af195ee1543133\nvldumdx.dll
> Driver Version	26.21.14.4223
> `

**Comment by adam-bielanski** [comment]
@veggiet - check the Antivirus software first. In many cases AV treats alicevisioin modules as viruses.

**Comment by veggiet** [comment]
> @veggiet - check the Antivirus software first. In many cases AV treats alicevisioin modules as viruses.

Thank you, that was an avenue I hadn't explored, but Antivirus doesn't seem to be an issue, I use Malwarebytes and Windows Defender Antivirus.

However I did find that Windows Smartscreen was blocking the individual Alicevision exe's from being run, however after I disabled Smartscreen entirely I'm still experiencing the issue. I can now run the individual exe's without issue, but the behaviour in Meshroom hasn't changed
