### ISSUE TITLE
[question] Comparison between different versions

### ISSUE THREAD

**Issue by xzhub** [alicevision/meshroom#1364]
Is there any results comparison between different Meshroom versions? I couldn't find any in youtube or any other sources. According to my tests with limited test sets, I feel the 2019 version is better than v2020 and v2021.
It might because of the poor images I fed to Meshroom, but the 2019 version give me a better result with the same parameters(sift+akaze, high FeatureExtraction describerPreset, guided matching) and same images.

v2019:
![image](https://user-images.githubusercontent.com/3990687/113796448-d7153a00-9781-11eb-9714-992760452d1c.png)

v2021:
![image](https://user-images.githubusercontent.com/3990687/113796648-51de5500-9782-11eb-97e0-bc9e59d78644.png)

I'd like to see more, and in depth comparision, if there is any. Could any one provide that info? I think the dev team must have some testsets. is there any blog post or videos talking about this?

**Comment by fabiencastan** [comment]
We are doing intensive tests to avoid regressions. If you find one exemple with a repeatable regression that would be interesting to analyse.

Could you try to run it multiple times? The process is not repeatable, so 2 different runs could end-up in different results with some variation in quality. So the difference may come from variations between runs instead of changes between software version.

One problem is that the notion of density on sift feature extraction has changed a bit, so that's difficult to make side-by-side comparison.

Could you try without akaze?
Could you try with the new dsp-sift?

**Comment by xzhub** [comment]
Should I try to replace sift with dsp-sift, or just simply add dsp-sift? 

Should I still use akaze If I work with a project of face scan? (in previous version, akaze is recommanded for human skin, so I am wondering if this has been changed)

**Comment by fabiencastan** [comment]
If you use DSP-SIFT, use it instead of SIFT (there is no interest in using them together).

Multiple changes have been done on SIFT. So it would be good to re-evaluate if it still make sense to combine it with AKAZE. SIFT or DSP-SIFT may be enough now.

**Comment by xzhub** [comment]
DSP-SIFT only works great on this project! It's better than before definitely. Will try SIFT only as well.
![image](https://user-images.githubusercontent.com/3990687/113917929-6d923b80-9814-11eb-9576-113809bb54c3.png)

**Comment by xzhub** [comment]
SIFT only is not as good as DSP-SIFT only. But still better than SIFT+AKAZE
![image](https://user-images.githubusercontent.com/3990687/113933343-0a5dd480-9827-11eb-8a6d-4b3ca585f8d2.png)

The SfMTransform_1 module does not work as it used to be in v2019.  So the viewpoint is randomly changed.

**Comment by fabiencastan** [comment]
Thanks for sharing your results.
I end up with the same conclusion in my various tests too. I'm considering changing the default value to dsp-sift in the 3D reconstruction pipeline (for the panorama use case, SIFT is still a bit better).
