### ISSUE TITLE
Problems with 2021.1 meshing (2020.1 gives better results)

### ISSUE THREAD

**Issue by poloarqueologicodeviseu** [alicevision/meshroom#1365]
Using 2021.1 Linux

This is the SFM
![Screenshot from 2021-04-07 11-38-15](https://user-images.githubusercontent.com/58147722/113853987-3d0bbc80-9796-11eb-80b6-51d7803e0c81.png)
This is the  end result.
![Screenshot from 2021-04-07 11-38-27](https://user-images.githubusercontent.com/58147722/113854066-5a408b00-9796-11eb-91b5-95c6a62b4424.png)

Settings I changed
1. Feature extraction: akaze and describers set as High
2. feature matching: guided matching
3. Dephtmap: downscale 1
4. Depthmap filter: Min Consisten Cameras 2 and Min Consistent Cameras Bad similarity 3
5. Meshing: max points: 300000

Any ideas what is happening?

For comparison, I run same photos with 2020.1.0 Linux with similar settings (made the same changes to defaults)
this is SFM
![Screenshot from 2021-04-07 11-49-51](https://user-images.githubusercontent.com/58147722/113855116-94f6f300-9797-11eb-911f-7908d0dcbbb6.png)

and this is end result
![Screenshot from 2021-04-07 11-49-32](https://user-images.githubusercontent.com/58147722/113855156-9f18f180-9797-11eb-9435-a192c8ef5329.png)

**Comment by natowi** [comment]
Try to disable AKAZE in the SFM node (expand the node and remove the node connection for the describer type to be able to deselect it)
https://github.com/alicevision/meshroom/issues/1314

Did you try the new dsp-sift describer type?
https://github.com/alicevision/meshroom/issues/1364
