### ISSUE TITLE
Feature extraction computing CPU vs. GPU

### ISSUE THREAD

**Issue by adam-bielanski** [alicevision/meshroom#1372]
I noticed  strange thing at my laptop - when I turn of "force CPU extraction" it seems the basic GPU (Intel) is involved in calculation more than Nvidia card.  I DID force "use Nvidia" for Meshroom and alicevision_featureextraction.exe in Nvidia Control Panel, but all in vain. 
Does anyone knows what to do with it?

 - OS:Win10
 - Meshroom version: 2021.1.0

**Comment by natowi** [comment]
As long as force cpu extraction is disabled, Meshroom will use the NVIDIA GPU to compute the SIFT describers. Other GPUs are not supported and would fall back on the cpu.

**Comment by adam-bielanski** [comment]
@natowi - that's clear for the desktop machine. The question is how to force Meshroom to choose GPU1 instead of GPU0 in first place?

**Comment by natowi** [comment]
Does the DepthMap node compute for you? In that case the NVIDIA Gpu is correctly enabled for Meshroom

**Comment by adam-bielanski** [comment]
Depthmap node runs fine on GPU, I noticed the issue at extraction phase only.

**Comment by natowi** [comment]
In that case your NVIDIA GPU is correctly recognized by Meshroom and will be utilized in Feature extraction if "force CPU extraction" is disabled. I don´t know why your Intel GPU seems to utilizes resources, but I would not worry about it (if it is not an issue for you). There can be numerous reasons for this behaviour.

**Comment by xzhub** [comment]
@adam-bielanski How much difference do you see the speed change in Feature extraction step by using CPU only v.s. GPU? Does it make sense to use GPU?

**Comment by adam-bielanski** [comment]
@xzhub - reportedly the GPU should be significantly faster (when it's Nvidia card). Unfortunately I see slow down when it is on-board Intel card calculating instead of I7 processor... and I'm not surprised with this result.

**Comment by natowi** [comment]
The speed up can be up to 4 times (depending on the dataset and other selected describers). The "force gpu" option should not be changed from the default when no NVIDIA GPU is installed.

**Comment by adam-bielanski** [comment]
@natowi I'm a bit confused, Meshroom (or at least part of it) doesn't work at all on machine without Nvidia, does it?

**Comment by natowi** [comment]
@adam-bielanski The DepthMap node will only compute on a NVIDIA GPU. NVIDIA GPU Support (for SIFT) in FeatureExtraction is disabled by default.

**Comment by adam-bielanski** [comment]
@natowi and what about dpssift, does it have an option to enable you support? Maybe this is an issue in my case, as I read that dpssift is more efficient than the "ordinary" one and I tested files with this sole  parameter on.

**Comment by natowi** [comment]
Only SIFT can utilize the GPU, it is set to use the CPU by default. 
DSP-SIFT is more efficient and will probably become the new default describer type in the next release.

**Comment by adam-bielanski** [comment]
Thanks @natowi  for the clarification.
