### ISSUE TITLE
ValueError: invalid attr name 'io_counters'

### ISSUE THREAD

**Issue by MakersF** [alicevision/meshroom#1373]
On Ubuntu 20 under WSL

```
meshroom_compute --toNode FeatureExtraction --forceStatus test.mg
WARNING:root:Downgrade status on node "FeatureExtraction_1(0)" from Status.ERROR to Status.SUBMITTED
WARNING:root:Downgrade status on node "FeatureExtraction_1(1)" from Status.ERROR to Status.SUBMITTED
WARNING:root:Downgrade status on node "FeatureExtraction_1(2)" from Status.ERROR to Status.SUBMITTED
WARNING:root:Downgrade status on node "FeatureExtraction_1(3)" from Status.ERROR to Status.SUBMITTED
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
  File "/opt/Meshroom/meshroom/core/stats.py", line 293, in run
  File "/opt/Meshroom/meshroom/core/stats.py", line 287, in updateStats
  File "/opt/Meshroom/meshroom/core/stats.py", line 241, in update
  File "/opt/Meshroom/meshroom/core/stats.py", line 191, in update
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psutil/__init__.py", line 514, in as_dict
ValueError: invalid attr name 'io_counters'
```

The reason is that `as_dict `is being called at https://github.com/alicevision/meshroom/blob/develop/meshroom/core/stats.py#L191 with the `io_counters `key https://github.com/alicevision/meshroom/blob/develop/meshroom/core/stats.py#L166.

`psutil `checks that the attributes are valid https://github.com/giampaolo/psutil/blob/c3e63b4dd59f1724a7fa29371e53dfa7f46cbcd3/psutil/__init__.py#L513.
Valid attributes are the attributes of the `Process `class https://github.com/giampaolo/psutil/blob/c3e63b4dd59f1724a7fa29371e53dfa7f46cbcd3/psutil/__init__.py#L1267.
The process class doesn't always have a property `io_counters`, but only on some implementations https://github.com/giampaolo/psutil/blob/c3e63b4dd59f1724a7fa29371e53dfa7f46cbcd3/psutil/__init__.py#L755

I suggest either removing the key, or use `net_io_counters` (https://github.com/giampaolo/psutil/blob/c3e63b4dd59f1724a7fa29371e53dfa7f46cbcd3/psutil/__init__.py#L2086) and  `disk_io_counters`(https://github.com/giampaolo/psutil/blob/c3e63b4dd59f1724a7fa29371e53dfa7f46cbcd3/psutil/__init__.py#L2029), or being able to graciously fail (by capturing the exception and removing from the dynamic key the attributes that are not valid).

**Comment by fabiencastan** [comment]
Thanks for the precise report.
As a short term fix, we could remove the key as it is not yet used.
But I agree that it would be good to find a way to ensure that the list of keys we are using are available based the psutil api.

Could you submit a fix in a PR?

**Comment by MakersF** [comment]
Here you go #1374
