### ISSUE TITLE
Problems with 2021.1.0 (2020.1.1 gives other/better results)[question]

### ISSUE THREAD

**Issue by datavizzard** [alicevision/meshroom#1380]
**Describe the problem**
Import images into Meshroom 2020.1.1, 2021.1.0, process wirh default settings, no changes.
Image orientation is not recognized in both versions, problem keeps popping up unfortunately.
Pointcloud in 2020.1.1 is more dense, the Mesh in 2021.1.0 has a lot of holes.

![pointcloud](https://user-images.githubusercontent.com/7428102/115023566-43e5ae00-9ebf-11eb-99ca-2dd7379eac5f.png)

Left ist 2020.1.1, Right 2021.1.0
![2021-04-16 14_45_09-MeshLab 2020 12 -  Project_1](https://user-images.githubusercontent.com/7428102/115027509-194a2400-9ec4-11eb-87b2-95891f17c804.png)

**Dataset**
Data set I can also provide request at short notice

**Desktop (please complete the following and other pertinent information):**
 - OS: Win 1909
 - Meshroom version: 2020.1.1, 2021.1.0

**Additional context**
Sometimes, but not allways "Fill Holes" in the Texture node fix it. I noticed that I noticed that the 2021.1.0 introduces holes around an object earlier than it was before. I think this is more a bug than a question, even though I marked it as the latter now.

I noticed that Reality Caputure sometimes preprocesses the images and makes them clearer, which can be seen later in the finer textures. Is this perhaps as a preprocess a solution for a node in Meshroom that takes over beforehand to then refine the results?

**Comment by fabiencastan** [comment]
> Pointcloud in 2020.1.1 is more dense, the Mesh in 2021.1.0 has a lot of holes.

Do you mean in output of the SfM? Could you provide numbers? Did you change default parameters?

> I noticed that the 2021.1.0 introduces holes around an object earlier than it was before.

This may come from the new post-processing of the tetrahedralization.
To get previous behavior, change the following parameters on the Meshing node (in the advanced params):
 - nbSolidAngleFilteringIterations=0
 - InvertTetrahedronBasedOnNeighborsNbIterations=0

**Comment by datavizzard** [comment]
> 

> > Pointcloud in 2020.1.1 is more dense, the Mesh in 2021.1.0 has a lot of holes.

> Do you mean in output of the SfM? Could you provide numbers? Did you change default parameters?
> 
> > I noticed that the 2021.1.0 introduces holes around an object earlier than it was before.

SFM, no a single Value changed. Default Settings.
 
> This may come from the new post-processing of the tetrahedralization.
> To get previous behavior, change the following parameters on the Meshing node (in the advanced params):
> 
>     * nbSolidAngleFilteringIterations=0
changed
>     * InvertTetrahedronBasedOnNeighborsNbIterations=0
Didn't find this one in Advanced Attributes, do you mean this?:
![2021-04-16 15_45_11-C__PhotoGram_frbg_Statue_pol Kirche_2021 mg_ - Meshroom 2021 1 0](https://user-images.githubusercontent.com/7428102/115033526-d2136180-9eca-11eb-8de0-2b4bcc80d01d.png)

**Comment by fabiencastan** [comment]
> SFM

How many landmarks?

> InvertTetrahedronBasedOnNeighborsNbIterations=0

Yes

**Comment by datavizzard** [comment]
> landmarks

0, Just plain Photos from Object in Free roam, SIFT

BTW, here the results with the both settings you told me to change. Looks like its getting worse, take a look for the Ground.
![2021-04-16 19_29_12-MeshLab 2020 12 -  Project_1](https://user-images.githubusercontent.com/7428102/115062066-37c31600-9eea-11eb-95cd-86ec7d16cea1.png)

![2021-04-16 19_28_57-MeshLab 2020 12 -  Project_1](https://user-images.githubusercontent.com/7428102/115062039-2e39ae00-9eea-11eb-8b43-6b0be62d0dc2.png)

**Comment by datavizzard** [comment]
I mentioned it before but you can see how the bottom gets a second layer from the bottom as if it were a balloon. On the statue model it is very flat and very hard to remove. I have to test this again but somehow SFMTransform has a negative influence on the result.

![2021-05-01 23_41_44-C__PhotoGram_Baum_baum mg_ - Meshroom 2021 1 0](https://user-images.githubusercontent.com/7428102/116795649-d3ea4100-aad6-11eb-94fa-04f37a635de1.png)
