### ISSUE TITLE
Meshroom Verrsion 2021.1.1.0

### ISSUE THREAD

**Issue by Manuelpuga** [alicevision/meshroom#1385]
Hello 
 I don't see the texturing button on the right once the process is finished ... is there a problem with the nodes? Run the process from 0, letting the nodes run by default and computing node by node and there is no texturing scene. .. Please Help
![Texturing Error](https://user-images.githubusercontent.com/38764879/115128463-8aacd400-9fa3-11eb-8c35-e64558924763.JPG)

**Comment by adam-bielanski** [comment]
@Manuelpuga  - just double-click on "meshing" or "texturing" node name at the pipeline to get relevant phase visible.
