### ISSUE TITLE
Export Animated Camera frames out of order

### ISSUE THREAD

**Issue by daveabbott** [alicevision/meshroom#1386]
When I export an animated camera, it doesn't follow the number order of the image sequence used. The frames appear shuffled, causing the camera to jump around wildly.

I filmed a fake moon rotating on a string in front of a green screen. It's been keyed and rendered as an image sequence. Meshroom has tracked and solved the mesh perfectly; the cameras appear in a ring around the moon. I would like to be able to have the cameras back as an animated camera that I can re-project the original footage with. It's so very close to working, Meshroom just won't export the frames in the correct order.

I've tried labeling the images moon_####.exr and moon.####.exr, and the log does not show any errors.

This shows the point cloud and cameras in a ring. This is correct as the object was being rotated in front of the camera.
![Screenshot-20210418180904-1140x675](https://user-images.githubusercontent.com/17044396/115138750-4f78d680-a071-11eb-987b-eff150b29ab6.png)

Here's the same thing in Houdini, but I've used grey spheres to show the incorrect path that the camera jumps along.
![Screenshot-20210418180855-1202x730](https://user-images.githubusercontent.com/17044396/115138747-46880500-a071-11eb-8c30-67d34f023a39.png)

 - OS: Fedora 33 - 5.11.13-200.fc33.x86_64 
 - Python version: 3.63
 - Meshroom version: 2021.1.0

**Comment by daveabbott** [comment]
I just ran Meshroom via Terminal to see if that'd reveal anything and it looks like the CameraInit is processing the frames out of order... Is that normal?

`[18:52:08.686920][warning] Image 'moon_0179.exr' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.`

`[18:52:08.687640][warning] Image 'moon_0040.exr' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.`

`[18:52:08.688402][warning] Image 'moon_0102.exr' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.`

`[18:52:08.688698][warning] Image 'moon_0317.exr' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.`

`[18:52:08.690075][warning] Image 'moon_0300.exr' focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.`

**Comment by natowi** [comment]
You could try changing the ViewID Method to "filename".

**Comment by daveabbott** [comment]
Yep, I discovered that just before you commented. It's solved it, thanks.

If anyone else runs into this issue; you need to view the advanced options for CameraInit and change the ViewId Method to Filename.

**Comment by hrivis** [comment]
> Yep, I discovered that just before you commented. It's solved it, thanks.
> 
> If anyone else runs into this issue; you need to view the advanced options for CameraInit and change the ViewId Method to Filename.

Please how can I change it? there is no checkbox... only input dot. thanks
