### ISSUE TITLE
[bug] FeatureMatching crashing

### ISSUE THREAD

**Issue by vieacq** [alicevision/meshroom#1387]
Using the Meshroom pipeline I found "FeatureMatching" failing in a rather strange way:

The pipeline was more or less standard (I have tuned some attributes) for processing 1043 images. 

The chunk #0 did run as expected until almost finished, then crashed. Meshroom did reset the nodes  "FeatureMatching" and following "from Status.SUBMITTED to Status.NONE", but continued processing the following chunks of "FeatureMatching" (from chunk #1 on). The chunks prior to the then actively processing chunks were shown as being in error (red indicator).

After retrying several times I found at last a logfile-entry stating that "...\Meshroom-2021.1.0\Projects\...\MeshroomCache\FeatureMatching\...\putativeMatches\0.matches.txt" ("...": substituted) could not be accessed.

I found directory "putativeMatches" missing (and thus it could obviously not be accessed).

**Workaround**
On the next retry to run "FeatureMatching" I manually created the directory "putativeMatches" as soon as chunk #0 of "FeatureMatching" started.

Then processing of the pipeline continued to run as expected.

**Log**
Logfile was lost on retry attempts.

**Desktop**
 - OS: Windows 10 
 - Python: Python 3.7.4
 - Qt/PySide: PySide2 5.15.2
 - Meshroom version: 2021.1.0 (Release)

**Comment by fabiencastan** [comment]
"savePutativeMatches" is not enabled by default, but it looks like a bug when this option is enabled.
I have not tested it to verify the issue.

If that's the case, we should create the folder if it does not exist:
https://github.com/alicevision/AliceVision/blob/develop/src/software/pipeline/main_featureMatching.cpp#L417

Do you have some C++ experience to make this small fix?
Something like:
```
  namespace fs = boost::filesystem;

  if (!fs::exists(p))
    fs::create_directory(p);
```

It would be good to fix in all case, but on the other hand, this a debug option for dev. I'm not sure why someone would want to enable this option.

**Comment by vieacq** [comment]
Thank you for your prompt reply. I'm new to Meshroom and try to find my way around like a blind man: the documentation leaves much to whish. I activated "Save Putative Matches" in the hope it would enhance results - but I now see it is, as you said, just for debugging purposes.

Unfortunately I have no development environment at hand (at least for the while being). So I cannot help out at this time.

I would like to add that I find AliceVision / Meshroom to be a really great product - but still with a few kinks. The documentation in particular needs more depth - if one day I have a better understanding, maybe I can help with that.

**Comment by fabiencastan** [comment]
Hi @vieacq ,

Yes, we agree that the documentation is not complete! Hopefully, there are already amazing contributions from the community!
A lot of "advanced" parameters are not documented as they are there only for development, but that should be indicated.

So yes, contributions to the documentation would be more than welcome ;)
In all case, thanks for you feedback.

Best,
