### ISSUE TITLE
Reprojection problem

### ISSUE THREAD

**Issue by masi1515** [alicevision/meshroom#1388]
Hello

Scanning process are successful but..
When I come back with my retopo, low poly unwrapped and duplicate PrepareDenseScene node, setting image folder, where I slightly change color on it, the texturing node go to fail. Yes the images are same except the color. I want to use the secondary dataset only for reprojection. Using Meshroom 2020.1.1 version. Please help.

Here is comment about dimensions but they are all correct. 
	
          [12:12:44.204322][fatal] Bad image dimension for camera : 0
        - expected dimension : 5472x3648
	- real dimension : 3648x5472

**Comment by natowi** [comment]
> I come back with my retopo, low poly 

Sometimes _really low_ poly can cause issues. Don´t know how much you simplified your model.
You could try a different texturing method

https://github.com/alicevision/meshroom/wiki/Texturing-after-external-re-topology

**Comment by fabiencastan** [comment]
Does the texturing work on your retopo without modification to the PrepareDenseScene?

**Comment by masi1515** [comment]
Thanks for reply. I figured it out. When I recalculated everything with dataset with no metadata and the new dataset had no metadata either. A question is if (I suspect) Affinity photo change some metadata during batch job. Have same metadata for both datasets from cameras or AI utility could work... but I am not going to test it. So you can mark the issue as a closed.
