### ISSUE TITLE
std::out_of_range Error during FeatureExtraction

### ISSUE THREAD

**Issue by riematrix** [alicevision/meshroom#139]
I got this error while executing feature extraction step.
i'm using ububtu 14.04 and python2.7

hope someone helping me out

[1/1](1/3) FeatureExtraction
 - commandLine: aliceVision_featureExtraction  --describerTypes sift --forceCpuExtraction True --verboseLevel info --input "/home/zj/data/ke/MeshroomCache/CameraInit/5e4a524c4f3c4698188a8a7acb5a6010f1834957/cameraInit.sfm" --describerPreset normal --output "/home/zj/data/ke/MeshroomCache/FeatureExtraction/2a8a6180ee28b7e95537c09e2f61edf8cb703d69" --rangeStart 0 --rangeSize 40
 - logFile: /home/zj/data/ke/MeshroomCache/FeatureExtraction/2a8a6180ee28b7e95537c09e2f61edf8cb703d69/0.log
(' - elapsed time:', '0:00:00.140262')
[2018-07-05 21:58:16,152][ERROR] Error on node computation: Error on node "FeatureExtraction_1(0)":
Log:
Program called with the following parameters:
 * describerPreset = "normal"
 * describerTypes = "sift"
 * forceCpuExtraction = 1
 * input = "/home/zj/data/ke/MeshroomCache/CameraInit/5e4a524c4f3c4698188a8a7acb5a6010f1834957/cameraInit.sfm"
 * maxThreads = 0 (default)
 * output = "/home/zj/data/ke/MeshroomCache/FeatureExtraction/2a8a6180ee28b7e95537c09e2f61edf8cb703d69"
 * rangeSize = 40
 * rangeStart = 0
 * upright = 0 (default)
 * verboseLevel = "info"

terminate called after throwing an instance of 'std::out_of_range'
  what():  Invalid imageDescriber : sift
Aborted (core dumped)

WARNING: downgrade status on node "FeatureExtraction_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureExtraction_1(2)" from Status.SUBMITTED to Status.NONE
[2018-07-05 21:58:16,153][ERROR] Error during Graph execution Error on node "FeatureExtraction_1(0)":
Log:
Program called with the following parameters:
 * describerPreset = "normal"
 * describerTypes = "sift"
 * forceCpuExtraction = 1
 * input = "/home/zj/data/ke/MeshroomCache/CameraInit/5e4a524c4f3c4698188a8a7acb5a6010f1834957/cameraInit.sfm"
 * maxThreads = 0 (default)
 * output = "/home/zj/data/ke/MeshroomCache/FeatureExtraction/2a8a6180ee28b7e95537c09e2f61edf8cb703d69"
 * rangeSize = 40
 * rangeStart = 0
 * upright = 0 (default)
 * verboseLevel = "info"

terminate called after throwing an instance of 'std::out_of_range'
  what():  Invalid imageDescriber : sift
Aborted (core dumped)

**Comment by yann-lty** [comment]
We've merged some [changes](https://github.com/alicevision/AliceVision/pull/410/commits/e87ff05f4d7ebe4cd7933b65b05799a7d5dd5af1) recently on the 'feature' module in AliceVision in order to unify cases, and describer types are now lowercase. Could you try to pull AliceVision's develop branch, build it and run Meshroom (also up-to-date on develop) again ?

**Comment by riematrix** [comment]
Problem solved after update and re-build.
