### ISSUE TITLE
[question] MeshRoom for animated sequences

### ISSUE THREAD

**Issue by simesgreen** [alicevision/meshroom#1391]
First of all, I'm impressed how good the results from MeshRoom are these days!

I'm trying to use MeshRoom to process an animated sequence from a static multi-camera rig - so I have a set of images for each frame of the animation. I can do this using meshroom_compute on the command line, but the output meshes have a different orientation for each frame since the estimated camera poses are slightly different each time.

Is there any easy way to get MeshRoom to run the SfM once, and then just run the dense pipeline for each set of new images?

Thanks,

Simon.

**Comment by natowi** [comment]
> animated sequence from a static multi-camera rig

Here are the details on how to set up the rig files https://github.com/alicevision/meshroom/wiki/Multi-Camera-Rig

We nearly have support for known fixed camera positions previously reconstructed, but there is still a gap (replacing the image paths in the sfm file) that is not yet supported and would require some custom scripts or manual work.

The following nodes will help to auto-orient the sfm and align a new reconstruction to the reference sfm:
SfMTransfer, SfMAlignment and SfMTransform. You could also place CCTAG Markers in your scene to auto orient, scale and align your models: https://github.com/alicevision/meshroom/wiki/CCTAG-scaling

**Comment by simesgreen** [comment]
Great, thanks for the pointers!
