### ISSUE TITLE
Export of reconstructed CCtag markers?

### ISSUE THREAD

**Issue by lexvandersluijs** [alicevision/meshroom#1394]
I need to know the 3D locations of the reconstructed CCTag markers. Is there a way to retrieve/export them, where each point is labelled with the ID of its marker?

I tried to check the Alembic file using HDF tools but it seems I need to build the tools here https://github.com/alembic/alembic/ , so before embarking on that effort I thought I would check if this makes sense at all.

**Comment by fabiencastan** [comment]
You can use convertSfMFormat, select only CCTags and export it in JSON.

**Comment by lexvandersluijs** [comment]
Hi Fabien,

Thanks, that works I think!

I got this (abbreviated) result:

```
   "structure": [
        {
            "landmarkId": "107",
            "descType": "cctag3",
            "color": [
                "4",
                "0",
                "0"
            ],
            "X": [
                "0.95187246799468994",
                "-0.42258498072624207",
                "1.8167023658752441"
            ],
            "observations": [
                {
                    "observationId": "138697269",
                    "featureId": "1",
                    "x": [
                        "1510.5",
                        "1067.469970703125"
                    ],
                    "scale": "0"
[...]
      {
            "landmarkId": "251",
            "descType": "cctag3",
            "color": [
                "1",
                "0",
                "0"
            ],
            "X": [
                "0.87196892499923706",
                "-0.94633853435516357",
                "1.3873556852340698"
            ],
            "observations": [
                {
                    "observationId": "93123801",
                    "featureId": "1",
                    "x": [
```
I was looking for the ID of the CCtag itself, and I think it can be found in the first element of the 'color' property, right?
There were 5 distinct CCtags in this dataset, and I find exactly and uniquely the numbers 0, 1, 2, 3 and 4 in here.

If you could just confirm this, I think the issue can be closed. Could be good to add this to the wiki or docs perhaps.

Thanks again!

**Comment by lexvandersluijs** [comment]
To add, is there a way to get this additional node to work in combination with meshroom_photogrammetry.exe? 

In the parameter list of this program I see no option to load a .mg file, but that would be a great capability. Or is it perhaps implicit, in that it will load it in case a .mg file is found in the current working directory?

**Comment by fabiencastan** [comment]
You can move to 2021 release.
The command has been renamed meshroom_batch and contains a `--pipeline` option.

**Comment by lexvandersluijs** [comment]
Yes! I just found it in the docs at the same time :-) :-)

It's a little bit hidden in the help output of the executable, but it's there too, with the -p parameter:

usage: meshroom_photogrammetry.exe [-h]
                                   [-i [SFM/FOLDERS/IMAGES [SFM/FOLDERS/IMAGES ...]]]
                                   [-I [FOLDERS/IMAGES [FOLDERS/IMAGES ...]]]
                                   [-p photogrammetry/panoramaHdr/panoramaFisheyeHdr/**MG_FILE**]
