### ISSUE TITLE
Error Estimate DepthMap

### ISSUE THREAD

**Issue by ThorsPanzer** [alicevision/meshroom#1397]
Hello

I am doing my first scan and I am stuck with the DepthMap node giving me red errors.
I have also changed the TdrDelay value to 60, so this shouldn't be the problem.

I shot a very simple rock for training purposes, 30 images so nothing too hard. Everything works fine until the DepthMap node. On my other attempt it was also the DepthMap which gave me the same problem. I tried every possible setting on "Downscale" but nothing is working for me.

So I sent all my data to a friend of mine who tried to create the depth maps and it worked perfectly for him! So something must be wrong on my side. But what can it be?

- GTX 1660 Ti
  - Drivers all updated
  - TdrDelay > 60
- Ryzen 5 1600X
- 16GB RAM

- https://github.com/alicevision/meshroom/wiki/Troubleshooting
- went through the Troubleshooting and tried everything, nothing worked.
- test images from this side also didn't work (used the mini6 data set)

Edit: - Computing the same photos with 2018 version seems to be working.

**Comment by adam-bielanski** [comment]
Hi @ThorsPanzer ,
Maybe an awkward hint, but sometimes Antivirus softwares block nodes of Meshroom. Check AV blocked list...

**Comment by ThorsPanzer** [comment]
Windows Defender doesnt show any activity. Tried disableing it (I hope I disabled everything?) and it still didn't work

**Comment by adam-bielanski** [comment]
Sometimes depthmap stops when can't match sufficient number of cameras, did you try to reduce it from 10 to, say, 5?

**Comment by ThorsPanzer** [comment]
If you mean the option SGM: Nb Neighbour Cameras, then changing it didn't do a difference.
Tested values: 5, 2 and 1

**Comment by adam-bielanski** [comment]
There are two parameters there SGM: Nb Neighbour Cameras and Refine: Nb Neighbour Cameras. In my models both of them sometimes stopped computing.

**Comment by ThorsPanzer** [comment]
Alright. But like I said, changing those parameters didn't fix the problem unfortunately

**Comment by nanuklost** [comment]
hey guys!
I have a similar problem. I am trying to run a solve with 233 photos from an iPhone (I know not ideal, but the best cam is the one you have with you ;)) They where shot raw and imported into MR. All icons green. The point cloud scene looks promising, but the DepthMap shows red bars pretty quick after starting processing the data.

this is the log from Chunk0:
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "d:/_Projects/20210422_rockFace/002_scene/Meshroom/MeshroomCache/PrepareDenseScene/0bf30f82ac12fff8c8f05ef8a12fe7dc6c23a421"
 * input = "d:/_Projects/20210422_rockFace/002_scene/Meshroom/MeshroomCache/StructureFromMotion/e749d43a245585724083fd5783b8f54d0e574f2e/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 4
 * nbGPUs = 0
 * output = "d:/_Projects/20210422_rockFace/002_scene/Meshroom/MeshroomCache/DepthMap/d96f7a35b6a1735b347f2325148e7d3c11373145"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[23:12:33.798269][info] CUDA-Enabled GPU.
Device information:
    - id:                      0
    - name:                    GeForce RTX 2060 SUPER
    - compute capability:      7.5
    - total device memory:     8192 MB
    - device memory available: 7173 MB
    - per-block shared memory: 49152
    - warp size:               32
    - max threads per block:   1024
    - max threads per SM(X):   1024
    - max block sizes:         {1024,1024,64}
    - max grid sizes:          {2147483647,65535,65535}
    - max 2D array texture:    {131072,65536}
    - max 3D array texture:    {16384,16384,16384}
    - max 2D linear texture:   {131072,65000,2097120}
    - max 2D layered texture:  {32768,32768,2048}
    - number of SM(x)s:        34
    - registers per SM(x):     65536
    - registers per block:     65536
    - concurrent kernels:      yes
    - mapping host memory:     yes
    - unified addressing:      yes
    - texture alignment:       512 byte
    - pitch alignment:         32 byte
[23:12:33.953696][info] Supported CUDA-Enabled GPU detected.
[23:12:35.242496][info] Found 1 image dimension(s):
[23:12:35.242496][info]     - [3024x4032]
What am I doing wrong?
TdrDelay is 60
Cheers,
Nanuk Lost

**Comment by ChemicalXandco** [comment]
The latest windows update has broken nvidia gpus for some people. Try rolling back Windows 10 Update KB5000842.

**Comment by adam-bielanski** [comment]
It happened a couple of times in the past, blocking normal operation of all software that uses GPU (like Revit). In my case reinstallation of Nvidia driver with option "clean installation" was sufficient.

**Comment by nanuklost** [comment]
I am using NVIDIA Studio Driver Version 462.31

**Comment by nanuklost** [comment]
> It happened a couple of times in the past, blocking normal operation of all software that uses GPU (like Revit). In my case reinstallation of Nvidia driver with option "clean installation" was sufficient.

did you use Geforce Experience to do the reinstall?

**Comment by nanuklost** [comment]
ok, it is crunching numbers now! I did 2 things:
1 installing the driver mentioned above
2 converting my .dngs to .png (16bit)

**Comment by adam-bielanski** [comment]
> > It happened a couple of times in the past, blocking normal operation of all software that uses GPU (like Revit). In my case reinstallation of Nvidia driver with option "clean installation" was sufficient.
> 
> did you use Geforce Experience to do the reinstall?

No, I don't game on my machine, so basic driver is sufficient for me.

**Comment by adam-bielanski** [comment]
> I am using NVIDIA Studio Driver Version 462.31

@nanuklost  - in fact it doesn't matter which version of the Nvidia software you have, the latest or the old one. The "Windows-Nvidia" problem appears on Windows updates, when some Nvidia drivers are replaced by Windows ones without warning. And then... some software crashes "with no reason", as they try to reach specific Nvidia files in vain.

**Comment by ThorsPanzer** [comment]
I cannot roll back from KB5000842. It doesn't show in the "deinstall updates". So how could I resolve the problem?

Btw I tried to downscale to 16 and set all the other options to the lowest and this works. The results are garbage tho
