### ISSUE TITLE
[bug] Meshroom 2021.1.0: Meshing results broken for "big" scale data. Meshing only works when bounding box is small enough

### ISSUE THREAD

**Issue by Kreshi** [alicevision/meshroom#1399]
**Describe the bug**

When meshing the whole scene, the resulting mesh is broken.
When reducing the meshing region by using the bounding box to a small enough size, meshing results were good again.
This issue occured in 2021.1.0.
This issue did not occur in 2020.1.1.
This issue did not occur in 2019.2.0.

**To Reproduce**

Use a dataset with > 100 images where you focus an object inside a room.
Settings: default settings (although i switched off "Force CPU extraction" to speed up the process).

**Expected behavior**

I expect the mesh to be correctly reconstructed regardless of the reconstruction box.

**Screenshots**

Broken meshing:

![broken](https://user-images.githubusercontent.com/5603486/115967697-4afe6300-a534-11eb-9ceb-3839a5a659b0.JPG)
![broken2](https://user-images.githubusercontent.com/5603486/115967700-4e91ea00-a534-11eb-9f7b-9aafdd6f19b6.JPG)

Working meshing after using a small enough reconstruction box:

![working](https://user-images.githubusercontent.com/5603486/115967715-68333180-a534-11eb-852b-e90b6b643c63.JPG)
![working2](https://user-images.githubusercontent.com/5603486/115967717-6a958b80-a534-11eb-9dae-0a15b82eed62.JPG)

**Desktop**

 - OS: Windows 10
 - Specs: i7, 16 GB DDR4, RTX 2060
 - Meshroom version: 2021.1.0

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/issues/1380#issuecomment-821182738
https://github.com/alicevision/meshroom/issues/1380

**Comment by Kreshi** [comment]
> [#1380 (comment)](https://github.com/alicevision/meshroom/issues/1380#issuecomment-821182738)
> #1380

I know about this thread but changing this specific parameters does not resolve the problem.
The issue is related to the size of the reconstruction bounding box / size of the data to reconstruct.

**Comment by natowi** [comment]
I think both problems are caused by changes in the Meshing node

**Comment by Kreshi** [comment]
> I think both problems are caused by changes in the Meshing node

That's for sure (since reducing the reconstruction bounding box which is part of the meshing node can resolve the issue).

**Comment by davidbrodrick** [comment]
There's so many related issues about this and associated problems, which have all been closed by the bot. There's nothing to suggest anything has actually been fixed :/
