### ISSUE TITLE
[question] Manual input of camera model

### ISSUE THREAD

**Issue by tiedbranches** [alicevision/meshroom#1400]
Which node should I use to manually input the camera model? It exists in the database, and it is normally automatically detected, but my pictures are lacking their exif data since they are video frames.

Many thanks and please excuse the basic question.

**Comment by natowi** [comment]
A) you could add the information in the cameraInit node. Import an image with exif data to see which data you can add.
B) add the exif data to your images with a tool like exiftool.
C) use the keyframeselection node to extract keyframes from supported video formats. The node provides fields for the camera information and adds it to the exif data. The output images from the node can be dragged from the node folder into Meshroom.
