### ISSUE TITLE
[question] Is it possible to use custom feature matching?

### ISSUE THREAD

**Issue by cameronfabbri** [alicevision/meshroom#1401]
I would like to use the feature matching algorithm described [here](https://github.com/zju3dv/LoFTR), is this possible?

I've written up a simple Python wrapper to run the Meshroom pipeline from the command line (see [here](https://github.com/cameronfabbri/Meshroom-Python-Wrapper)), so I'm thinking I might be able to plug in the matching algorithm mentioned above and write to the feature files in the correct format.

**Comment by natowi** [comment]
LoFTR is really interesting. All the computation and processing is being done on the Alicevision side. Here you can take a look on how the implementation of the new dsp-sift was being done https://github.com/alicevision/AliceVision/pull/935
