### ISSUE TITLE
Meshroom 2021.1.0 crashes when importing [bug]

### ISSUE THREAD

**Issue by shanji97** [alicevision/meshroom#1404]
**Describe the bug**
When importing images to the project (regardless of untitled or existing .mg file), it doesn't matter if drag and drop them or import them manually. Also the quantity  of images I import, doesn't seem to affect the behaviour, as it crashes on just one image or multiple images. The loading (importing) of the images is shown, but after it is "completed" it just crashes. Also the command line window is empty.
I don't know what was changed, because a few weeks ago everything was practically the same.

**To Reproduce**
1. Take 82,167 and 201 image sets of objects or download datasets  [https://drive.google.com/drive/folders/11-lZEM8RIR2OblDu_ftUtqsD8gikpSaZ?usp=sharing](Google drive folder), the "Djord" folder has an mg file which I use as my template file.
2. (Optional) Import a custom *.mg file
3. Drag and drop dataset images or import them using the import button
4. See the crash

**Expected behavior**
When imported, images should appear in the image viewer and not crash.

**Desktop (please complete the following and other pertinent information):**

 - OS: Windows 10 19042.928
 - 32 GB DDR4 3200@CL16-18-18
 - Ryzen 5 5600x
 - Python version  3.9 (installed), 3.7 (as dll inside meshroom binary folder)
 - Asus GTX 1650 mini dual OC 4GB (Studio ready drivers 462.31 and previous version, actually checked if this could be the reason, but after update is it the same)
 - Qt/PySide version [e.g. 5.12.4] : PySide2 folter in the subofolders located
 - Meshroom version: downloaded from alicevision site (2021.1.0)
 -No overclock

Image from another computer ![Screenshot_20210503-152329_Gmail.jpg](https://user-images.githubusercontent.com/13587507/116881648-cdb5ab00-ac23-11eb-9aca-2a7d2d7bb96e.jpg)
The odd thing is that I ran meshroom with some other dng photos and it worked just fine using Google Pixel 4a 5g

**Comment by sannyi** [comment]
Hi! As one of my colleagues found out one of the folder was solved by renaming the folder/files, form "Đorđ" to "Djord". I have not fully tested this claim, but I'd certainly try it out. However two of the other folders didn't work either which **do not have ** special charaters like "đ, š, č, ž" (in Slovenian - well đ is not exactly Slovene)
A feature request would be that the program either warns the user for characters or renames the files/folders. I'll try this out and see the results what happens if the files/folder are renamed.

**Comment by louis1lal** [comment]
I think this software is just not stable at all. I solved the problem by installing the windows media feature for my version of windows, then the process stopped because of depth map, they can't find CUDA GPU , but I actually have one... I did like someone said by configuring the nvidia control pannel for meshroom.  Did not work either so I did couple of updates then the import images stopped working again... So, at this stage I am kind of bored of all of this, Let me know when this app will work ;p

I did everything I could do to make it work but it's not stable... at all or you need like the latest computer!? Sorry, I thought it would have been great but it's not.

my video card is Nvidia geforce 650m and I can see it's cuda capable.

**Comment by sannyi** [comment]
Are there any alternatives that offer at least one month trial of all features?

**Comment by natowi** [comment]
> download datasets [here]https://slo-tech.com/novice/t784908/p7149703#p7149703), the "Djord" folder has an mg file which I use as my template file.

I don´t find a dataset there

**Comment by sannyi** [comment]
Hi! Thanks for the reminder. I pasted the wrong link to the wrong place. I downloaded program files available on their official download links because I don't know how to compile it myself.

**Comment by sannyi** [comment]
Hi! @natowi and @louis1lal . I just updated the link to the datasets. The camera brand is "Google", the model "Pixel 4a (5G)" and the number is "5.560000" in case you need it. [https://drive.google.com/drive/folders/11-lZEM8RIR2OblDu_ftUtqsD8gikpSaZ?usp=sharing](Again, the link for the datasets). Hi I donwloaded the "clean" Meshroom files for the version 2021.1. I tried this datasets on two different computers (one my main one and the other a laptop (i7 10750h, 1660 Ti 6 GB and 16GB of RAM), I have also a third one, but is greatly underpowered for anything else than websurfing.

**Comment by natowi** [comment]
I have no issues importing the images. ![Unbenannt55](https://user-images.githubusercontent.com/8138537/117549051-99355b00-b038-11eb-8618-f4c1b523e65e.JPG)

Try installing the Visual C++ Redistributable Package as mentioned here: https://github.com/alicevision/meshroom/wiki/Images-cannot-be-imported

About the path and image names: only ASCII characters should be used

Does Meshroom work for you with any other dataset?

**Comment by sannyi** [comment]
Hi!
Thank you for the information, I have those instributables already installed, at first I didn't have ASCII charaters, but the I renamed them and still no dice. My colleagues had for some reason better results and even a currupted file(s) warning, which I didn't have (and yours are better results too) opening the files. I found out that I had only issues with my phone's raw files (curiously yours are perfect import). I'll play around and see what I can find out. Thank you for the information.

**Comment by natowi** [comment]
>I had only issues with my phone's raw files

Try converting them to JPG. (RAW formats should be supported, but sometimes causes issues)
Details on RAW/JPG https://peterfalkingham.com/2020/05/22/photogrammetry-does-shooting-raw-or-jpg-make-a-difference/

**Comment by sannyi** [comment]
Ok, so I converted them to jpg using dark table. The funny thing is, that now the laptop tells the files are corrupted, white the PC works just fine. Also I apparently have no CUDA gpus while having meshroom added to the Nvidia control panel and CUDA 11.3 installed.

**Comment by natowi** [comment]
I had an issue with another laptop, where cuda was not detected in Meshroom. Turned out Windows took the liberty to overwrite my NVIDIA settings with the default Intel GPU

**Comment by sannyi** [comment]
Hi!
My main computer has a Ryzen 5 5600X AMD CPU which does not have an iGPU. So it should (not currently by my computer ) be a no brainer. Also in the NVIDIA control panel Meshroom was manually added.

**Comment by floriankraemer** [comment]
This is still an issue and seems to be related to the folder names. I have a folder with `ß` in it. I've tried to move the files to a folder called "Test" and it worked, at least the import. Using Mehsroom 2021.1.0.

**Comment by gvelasco02** [comment]
YES! the issue is the folder name and folder path, I had the same issue and one of the folders in the folder path of my images folder had a º and it was crashing. I changed it to desktop and now it works. Thanks.
