### ISSUE TITLE
[bug] Meshroom 2021.1.0 CCTag3 not working 

### ISSUE THREAD

**Issue by GeorgLeb** [alicevision/meshroom#1405]
First of all, thanks for the great work of meshroom! It's really a great program! I am new to github, so sorry if I am not familiar with posting correctly.

I have Meshroom 2021.1.0 freshly downloaded to make sure, i have the current version.
  I have a set of images including the cctag3 markers, shot with the huawei p20 pro (5472x7296px). The standard pipeline with sift or akaze works without any problems, but when i try to use the "cctag3" describer type for the FeatureExtraction-node nothing happens. The node gets orange first, and after about 10 seconds turns into red. There is only one short warning in the very beginning (first line of log, only occurs if cctag3 is enabled).

**To Reproduce**
I have tried it with multiple sets of photos, it always happens. the workflow is the standard pipeline, only with additional "cctag3". Also happens with photos without markers.

![Capture](https://user-images.githubusercontent.com/83650797/117014997-a4fbe700-acf1-11eb-99ba-72ee1c48746c.PNG)

Log: (Verbose-level: trace)
```
WARNING:root:Downgrade status on node "FeatureExtraction_1(0)" from Status.ERROR to Status.SUBMITTED
 - commandLine: aliceVision_featureExtraction  --input "C:/Users/User/Downloads/test_marker/MeshroomCache/CameraInit/4022124b380b736bdcea2f4c0760fd1a661249ce/cameraInit.sfm" --describerTypes cctag3,sift --describerPreset normal --describerQuality normal --contrastFiltering GridSort --gridFiltering True --forceCpuExtraction True --maxThreads 0 --verboseLevel trace --output "C:/Users/User/Downloads/test_marker/MeshroomCache/FeatureExtraction/bb61c77eff87661971873ef7ed8f4ebd42c329f9" --rangeStart 0 --rangeSize 40
 - logFile: C:/Users/User/Downloads/test_marker/MeshroomCache/FeatureExtraction/bb61c77eff87661971873ef7ed8f4ebd42c329f9/0.log
ERROR:root:Error on node computation: Error on node "FeatureExtraction_1(0)":
Log:
Program called with the following parameters:
 * contrastFiltering =  Unknown Type "enum aliceVision::feature::EFeatureConstrastFiltering"
 * describerPreset =  Unknown Type "enum aliceVision::feature::EImageDescriberPreset"
 * describerQuality =  Unknown Type "enum aliceVision::feature::EFeatureQuality"
 * describerTypes = "cctag3,sift"
 * forceCpuExtraction = 1
 * gridFiltering = 1
 * input = "C:/Users/User/Downloads/test_marker/MeshroomCache/CameraInit/4022124b380b736bdcea2f4c0760fd1a661249ce/cameraInit.sfm"
 * maxNbFeatures = 0 (default)
 * maxThreads = 0
 * output = "C:/Users/User/Downloads/test_marker/MeshroomCache/FeatureExtraction/bb61c77eff87661971873ef7ed8f4ebd42c329f9"
 * rangeSize = 40
 * rangeStart = 0
 * relativePeakThreshold = 0.02 (default)
 * verboseLevel =  Unknown Type "enum aliceVision::system::EVerboseLevel"

[16:00:09.573795][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce GTX 1070 Ti
        - compute capability:      6.1
        - total device memory:     8192 MB
        - device memory available: 7208 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   2048
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {131072,65536}
        - max 3D array texture:    {16384,16384,16384}
        - max 2D linear texture:   {131072,65000,2097120}
        - max 2D layered texture:  {32768,32768,2048}
        - number of SM(x)s:        19
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte
0
[16:00:09.714748][info] Supported CUDA-Enabled GPU detected.
[16:00:09.714748][info] Job max memory consumption for one image: 3169 MB
[16:00:09.714748][info] Memory information:
        - Total RAM:     15.92 GB
        - Free RAM:      11.3834 GB
        - Available RAM: 11.3834 GB
        - Total swap:    131072 GB
        - Free swap:     131035 GB
[16:00:09.714748][info] Max number of threads regarding memory usage: 3
[16:00:09.714748][info] # threads for extraction: 3
[16:00:10.365574][trace] Read image C:/Users/User/Downloads/test_marker/IMG_20210504_132833.jpg (encoded in sRGB colorspace).
[16:00:10.403561][trace] Read image C:/Users/User/Downloads/test_marker/IMG_20210504_132759.jpg (encoded in sRGB colorspace).
[16:00:10.413558][trace] Read image C:/Users/User/Downloads/test_marker/IMG_20210504_132818.jpg (encoded in sRGB colorspace).
[16:00:10.827429][info] Extracting cctag3 features from view 'C:/Users/User/Downloads/test_marker/IMG_20210504_132833.jpg' [cpu]
[16:00:10.921396][info] Extracting cctag3 features from view 'C:/Users/User/Downloads/test_marker/IMG_20210504_132759.jpg' [cpu]
[16:00:10.965382][info] Extracting cctag3 features from view 'C:/Users/User/Downloads/test_marker/IMG_20210504_132818.jpg' [cpu]
```

Used Desktop:
OS: win 10
Python version: 3.9.2
Meshroom version: 2021.1.0

Thanks for your help!

Edit:
If I use the available photos from this post: [url](https://github.com/alicevision/meshroom/issues/716), or some synthetic data (markers digitally positioned on some white background) the extraction works perfect. Seems to be caused by my phone-camera.

Edit2:
With a different camera the same setting works, so it might be the images from the Huawei P20 Pro

**Comment by MarcoRos75** [comment]
Ciao! Confermo anche io il problema con foto fatte con Huawei Mate 20

**Comment by simogasp** [comment]
Could you share the three images?

**Comment by GeorgLeb** [comment]
Of course:

![IMG_20210504_132818](https://user-images.githubusercontent.com/83650797/117256279-c6241b00-ae4a-11eb-8b42-150df88225b8.jpg)
![IMG_20210504_132825](https://user-images.githubusercontent.com/83650797/117256293-ca503880-ae4a-11eb-9a32-7bc667b027a8.jpg)
![IMG_20210504_132759](https://user-images.githubusercontent.com/83650797/117256305-cf14ec80-ae4a-11eb-9482-55edf815763e.jpg)
![IMG_20210504_132833](https://user-images.githubusercontent.com/83650797/117256261-bd334980-ae4a-11eb-8955-e6e915ac4276.jpg)
![IMG_20210504_132808](https://user-images.githubusercontent.com/83650797/117256272-c1f7fd80-ae4a-11eb-9b8f-e3ca4e0329d3.jpg)

**Comment by simogasp** [comment]
There was this error message in the log:
```
terminate called after throwing an instance of 'std::length_error'
  what():  EdgePointCollection::set_frame_size: image resolution is too large
Aborted (core dumped)
```
from here https://github.com/alicevision/CCTag/blob/develop/src/cctag/Types.cpp#L24 
So after quick investigation, it turns out the images you are using are too large for cctag.
There is actually a bound limit on the resolution of the images that can be processed defined by a hardcoded constant 
https://github.com/alicevision/CCTag/blob/cad82713b27cc3f507890c955f24e029a4fb0260/src/cctag/Types.hpp#L24
```c++
  static constexpr size_t MAX_RESOLUTION = 6144;
```
so the max resolution that can be processed is `MAX_RESOLUTION*MAX_RESOLUTION`
@griwodz can say it better than me, it's probably related to the cuda memory that can be actually used

So you need either to take lower resolution images to meet that requirement or simply resize them.
I just did it and it seem to work:
CCTAGs are detected
![image](https://user-images.githubusercontent.com/1331744/117264725-cb399800-ae53-11eb-8bf1-8c69e8a610a4.png)
and 3d model is computed
![image](https://user-images.githubusercontent.com/1331744/117264832-e7d5d000-ae53-11eb-8a42-83a903ba37bb.png)

**Comment by simogasp** [comment]
> Ciao! Confermo anche io il problema con foto fatte con Huawei Mate 20

Prova anche tu a ridurre la risoluzione delle immagini, potrebbe essere lo stesso problema.

**Comment by GeorgLeb** [comment]
Thanks a lot for the answer! Do you think it will be possible to enlarge the max_resolution for future-releases? Mobile-cameras are getting better really fast and I think the CCtag-markers for cloud-transformation are really a great solution. Great work after all!

**Comment by simogasp** [comment]
I really don't know the rationale behind that exact number, @griwodz will tell us.
If it is somehow related to the Cuda memory maybe it can be set dynamically to meet the specifications of the gpu card.

**Comment by MarcoRos75** [comment]
Si ! Confermo!  diminuendo le dimensioni delle foto funziona!!   Anche se al dire il vero io preferisco fare con la fotocamera Reflex, almeno mi riconosce il tipo di sensore ecc....! 👍

**Comment by MarcoRos75** [comment]
Scusa Simone!!! Ma se come dici tu è un problema di "CUDA memory"  perchè con le foto della Reflex  con risoluzione 5184 x3456  e con la GoPro a 3648x2736  , va tutto bene, mentre con il Cellulare no?
Non sarà forse anche la questione che non riconosce i dati del sensore del Cel. ?
Scusa e grazie!!!

**Comment by simogasp** [comment]
> Scusa Simone!!! Ma se come dici tu è un problema di "CUDA memory" perchè con le foto della Reflex con risoluzione 5184 x3456 e con la GoPro a 3648x2736 , va tutto bene, mentre con il Cellulare no?
> Non sarà forse anche la questione che non riconosce i dati del sensore del Cel. ?
> Scusa e grazie!!!

Perche' nel codice di cctag c'e un vincolo imposto che impedisce di gestire piu' di 6144* 6144 pixels. Se le dimensioni delle foto col cellulare sono piu' grandi cctag lancia un errore. Nel tuo caso reflex e gopro sono < 6144* 6144, per contro le foto che ha postato qui erano 7200x5600 che in termini di "area" o numero di pixel e' maggiore di 6144*6144.
Non so esattamente a cosa corrisponda questo numero magico, per il momento cerca di usare una risoluzione compatibile con questo vincolo, nella prossima release troveremo una soluzione piu' furba che lanciare un errore ;-)

**Comment by MarcoRos75** [comment]
Ciao! ho appena aggiornato i driver della mia scheda INVUIDIA GTX 1650..... !   con la risoluzione 5472x7296  foto di GeorgLeb ora funziona!!!!Non si blocca!   misteri della vita!

**Comment by evanmayer** [comment]
I recently ran into this issue using a newer ~40 MP mirrorless camera. Does anyone know the answer to the question above? What is this magic number for? Can I safely hack CCTag to lift the constraint?
