### ISSUE TITLE
[question]How to set the descriptorTypes in FeatureExtraction to'sift'+'akaze'  by --paramOverrides？

### ISSUE THREAD

**Issue by WellTung666** [alicevision/meshroom#1411]
**Describe the problem**
I want to use CLI to run Meshroom and set the descriptorTypes in FeatureExtraction to'sift'+'akaze' but it fails.

**Screenshots**
code:
![image](https://user-images.githubusercontent.com/48502095/117433172-c6610b00-af5d-11eb-97ff-2570ca067305.png)

error:
![image](https://user-images.githubusercontent.com/48502095/117433764-6c147a00-af5e-11eb-9e24-6303ba5edb9a.png)

code:
![image](https://user-images.githubusercontent.com/48502095/117433880-9403dd80-af5e-11eb-9f94-8c16dc0c14f1.png)

error:
![image](https://user-images.githubusercontent.com/48502095/117433844-877f8500-af5e-11eb-918c-dc5adcf12a2e.png)

 - OS:ubuntu18.04
 - Python version 3.7
 - Meshroom version: Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2

**Comment by Dev-hestabit** [comment]
anyone found any solution regarding this
