### ISSUE TITLE
[bug] SfMTransform causes different Mesh Results

### ISSUE THREAD

**Issue by datavizzard** [alicevision/meshroom#1412]
**Describe the bug**
Mesh getting holes or a lot of more holes when SfMTransform is rotating, moving SFM data.
![2021-05-07 17_23_09-Window](https://user-images.githubusercontent.com/7428102/117472226-f8bc3980-af58-11eb-82c3-93a188878d22.png)

**To Reproduce**
Default Settings, duplicate Pipeline after StructureFromMotion Node and put a SfMTransform like in the Picture below (Like in the Meshroom Documentation)
Status after Meshing Node: Left default, right SfMTransform
![2021-05-07 17_13_11-Window](https://user-images.githubusercontent.com/7428102/117471892-995e2980-af58-11eb-9a61-5b0e0dce0a75.png)

**Expected behavior**
Same SfM generates same Mesh but rotated

**Desktop (please complete the following and other pertinent information):**
 - OS: Win10
 - Meshroom version: Win Exe
   - Binary version 2021.1.0

**Additional context**
Status after Texture Node: Left default, right SfMTransform
![2021-05-07 17_13_20-Window](https://user-images.githubusercontent.com/7428102/117470934-9dd61280-af57-11eb-86a2-539e56a567cf.png)

**Comment by natowi** [comment]
Reference: https://github.com/alicevision/meshroom/issues/1380

**Comment by MarcoRos75** [comment]
Ciao! anche io ho notato questo! ma credo sia corretto! in quanto la prima nuvola viene referenziata con i CCTAG ( viene trasformata- referenziata)  mentre la seconda no..non è orientata! Oltre con la mesh lo fa anche con la nuvola di punti spara e densa!!!
