### ISSUE TITLE
[Error in StructureFromMotion]

### ISSUE THREAD

**Issue by johannarwth** [alicevision/meshroom#1414]
i am using Meshroom for a projekt at my university to create 3D-models from different objects out of waste streams. I am using a rotary plate to move the object and a camera on an tripod to take the photos. Eventhough the camera stands still at one place, this construction has worked and i have created a solid 3D-model from another object to test the construction. When i am trying to scan other objects now, Meshroom stops at the StructureFromMotion part and i have no idea where the issue is

![Screenshot (71)](https://user-images.githubusercontent.com/84012166/117790468-aaa18180-b249-11eb-9614-7627871c74df.png)
![Screenshot (70)](https://user-images.githubusercontent.com/84012166/117790517-b725da00-b249-11eb-8c4b-9c8f5da2c5af.png)

Maybe someone can halp me with this Problem.
Many Thanks ind advance.

**Comment by natowi** [comment]
Check your image path /25°/ -> the degree character is not allowed. Your paths should only contain ASCII Characters.

**Comment by natowi** [comment]
It is also possible that there were not enough matches for the SfM.
Glossy and reflective objects are difficult to capture. Enable the Feature Preview in the ImageViewer to see the detected features. Repeat your capturing session and make sure your objects fill the image frame.

**Comment by datavizzard** [comment]
@johannarwth Don't use special characters, I had a similar problem when I started with Meshroom. Change the characters in the name and put them in a new pipeline and new .mg, this should work. Can you provide the data to reproduce the error for analysis.

You can right click on the node to delete the old data by the way
