### ISSUE TITLE
High quality SfM but poor depth mapping [question]

### ISSUE THREAD

**Issue by Swirl-droid** [alicevision/meshroom#1420]
**Problem**
A dataset of around 400 images of an outdoor statue was taken. When imported to Meshroom, the SfM data looks great and can be meshed directly to produce a reasonable result. However, after depth mapping and filtering, the end result is unrecognizable.  Looking at the depth mapping visualizer, I found that its a little noisy, but it looks alright otherwise. Can anyone help me to fix this problem?

**Screenshots**
![SfM v Depth Map](https://user-images.githubusercontent.com/84341487/118531574-45b4c280-b746-11eb-85f1-569372f0f5c2.png)
![Result](https://user-images.githubusercontent.com/84341487/118532148-ea370480-b746-11eb-9010-4b7355a51ea6.png)

**Dataset**
https://drive.google.com/file/d/1dD5AeiU28fLzlz5niuxl9h-ya2Y_LTnb/view?usp=sharing

**Other information**
 - OS: Win 10
 - Meshroom version: 2021.1.0
 - Images taken with a Nikon D7000. focal length: 200 mm, f-stop number: 32, Metering: Matrix, Shutterspeed: Automatic (around 1 sec)

**Comment by tkircher** [comment]
This has been a known issue for ages. There is a very significant amount of noise in the depth map step; the only reliable output is from the SfM step. It's actually better to have more points there and skip the depth map.
