### ISSUE TITLE
Issue: W10 x64 Missing plugins

### ISSUE THREAD

**Issue by sanscorp1** [alicevision/meshroom#1421]
Just thought I'd give Meshroom a try.
When executing "meshroom.exe" I get a CLI with errors:

WARNING:root:Missing plugin qtAliceVision.
WARNING:root:Missing plugin qtOIIO.

Running as admin, latest version of W10 x64 pro.
Python 3.9.5 installed as well as MS visual C++ 2015-2019 (and older, 2008 trough 2013)

I cannot load images and get errors:
RuntimeError: CameraInit failed with error code 3221225781
WARNING:root:Model size of -1355 is less than 0
WARNING:root:Model size of -205 is less than 0

(re)ïnstalled: vc_redist.x64.exe and W10 media pack (alltough I do not run Windows 10 N).

Removed spaces from paths.
Ran Meshroom from root D:\
Placed images on D:\testimage

Still no luck.
Any ideas?

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/issues/1194

**Comment by NickoGNS** [comment]
I have the same problem and the #1194 didn't solve the issue.
