### ISSUE TITLE
[question] How to apply the 3D textured mesh operation on a different set of images without changing the structure of the mesh?

### ISSUE THREAD

**Issue by ARTLAUROO** [alicevision/meshroom#1422]
**Describe the problem**
Meshroom is very capable into stitching 2D images together to a 3D textured mesh. What I want is to change the texture of that 3D textured mesh, **without** changing the 3D model on which that texture is rendered. Is there a way to do this with meshroom?

**Screenshots**
Let me clarify it with an example.

At first meshroom takes as input some images and produced as output a textured mesh. Like this:  
![image](https://user-images.githubusercontent.com/3845426/118831267-ec709e80-b8bf-11eb-880c-ece80bde775d.png)

Now, what I want to do is save the computations that are used above to create the mesh from the images. But apply them to a different set of images. That is what I try to visualize here:
![image](https://user-images.githubusercontent.com/3845426/118832206-b7188080-b8c0-11eb-918e-617d863ffce0.png)
So the actual structure, the white object in the middle, remains the same and is based on the original images, while the texturing/coloring of the object has changed.

(Please forgive my terrible photoshop skills. Also disregard the actual contents of the images/masks displayed here, it is just for illustration.) 

In principle this should be possible. Perhaps I can swap in the second set of images instead of the first set of images after the feature matching? But I do not know how to do this. Is there anyone who could give me some pointers on this?

**Comment by natowi** [comment]
The workflow is described here: https://github.com/alicevision/meshroom/wiki/Projected-Light-Patterns
It is being used to replace images taken from the same positions.
