### ISSUE TITLE
[bug] Segfault on StructureFromMotion

### ISSUE THREAD

**Issue by cameronfabbri** [alicevision/meshroom#1424]
**Problem**
Getting a Segfault immediately when running SFM. I'm using [these images](https://github.com/alicevision/dataset_monstree/tree/master/mini6) to test.

**Desktop**
 - OS: Ubuntu 20.04.2 LTS
 - Python version 3.8.10 via Anaconda (also tried 3.5.6) 
 - Meshroom: Using the latest master branch of Meshroom and Alicevision. Built AliceVision from source using the following cmake command

`cmake -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-8 -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-8 -DUSE_SSE2:BOOL=OFF -DCMAKE_BUILD_TYPE=Release -DALICEVISION_USE_CUDA:BOOL=ON -DALICEVISION_USE_ALEMBIC:BOOL=ON -DALICEVISION_USE_OPENMP:BOOL=ON -DTARGET_ARCHITECTURE:STRING=zen`

**Log**
[2021-05-24 09:30:46,835][WARNING] == The following "submitters" plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

[2021-05-24 09:30:47,836][WARNING] Missing plugin qtAliceVision.
[2021-05-24 09:30:47,836][WARNING] Missing plugin qtOIIO.
Program called with the following parameters:
 * allowSingleView = 1
 * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1"
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "20EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "/tmp/tmpe06rubik/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"
 * output = "/tmp/tmpe06rubik/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm"
 * sensorDatabase = ""
 * useInternalWhiteBalance = 1
 * verboseLevel = "info"
 * viewIdMethod =  Unknown Type "N11aliceVision9sfmDataIO13EViewIdMethodE"
 * viewIdRegex = ".*?(\d+)" (default)

add_exif_item_to_spec: didn't know how to process Exif:ComponentsConfiguration, type 7 x 4
add_exif_item_to_spec: didn't know how to process Exif:SceneType, type 7 x 1
add_exif_item_to_spec: didn't know how to process Exif:ComponentsConfiguration, type 7 x 4
add_exif_item_to_spec: didn't know how to process Exif:SceneType, type 7 x 1
add_exif_item_to_spec: didn't know how to process Exif:ComponentsConfiguration, type add_exif_item_to_spec: didn't know how to process Exif:ComponentsConfiguration, type add_exif_item_to_spec: didn't know how to process Exif:ComponentsConfiguration, type 7 x 4
add_exif_item_to_spec: didn't know how to process Exif:ComponentsConfiguration, type 7 x 4
7 x 4
add_exif_item_to_spec: didn't know how to process Exif:SceneType, type 7 x 1
add_exif_item_to_spec: didn't know how to process Exif:SceneType, type 7 x 1
add_exif_item_to_spec: didn't know how to process Exif:SceneType, type 7 x 1
7 x 4
add_exif_item_to_spec: didn't know how to process Exif:SceneType, type 7 x 1
[09:30:53.465952][warning] Some image(s) have no serial number to identify the camera/lens device.
This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximation they will share the same internal camera parameters.
6 image(s) are concerned.
[09:30:53.467369][info] CameraInit report:
	- # views listed: 6
	   - # views with an initialized intrinsic listed: 6
	   - # views without metadata (with a default intrinsic): 0
	- # intrinsics listed: 1
 - commandLine: aliceVision_cameraInit  --viewIdMethod metadata --groupCameraFallback folder --verboseLevel info --sensorDatabase "" --useInternalWhiteBalance True --defaultFieldOfView 45.0 --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --output "/tmp/MeshroomCache/CameraInit/7ace6f41b0b0ce62bfbe423861d5077f854eef07/cameraInit.sfm" --allowSingleView 1 --input "/tmp/MeshroomCache/CameraInit/7ace6f41b0b0ce62bfbe423861d5077f854eef07//viewpoints.sfm"
 - logFile: /tmp/MeshroomCache/CameraInit/7ace6f41b0b0ce62bfbe423861d5077f854eef07/log
 - commandLine: aliceVision_featureExtraction  --describerTypes sift --maxThreads 0 --input "/tmp/MeshroomCache/CameraInit/7ace6f41b0b0ce62bfbe423861d5077f854eef07/cameraInit.sfm" --contrastFiltering GridSort --verboseLevel info --describerPreset low --describerQuality low --gridFiltering True --forceCpuExtraction True --output "/tmp/MeshroomCache/FeatureExtraction/c77c2a9b767ad27e4d735c8a0d5098ba49d105ec" --rangeStart 0 --rangeSize 40
 - logFile: /tmp/MeshroomCache/FeatureExtraction/c77c2a9b767ad27e4d735c8a0d5098ba49d105ec/0.log
 - commandLine: aliceVision_imageMatching  --featuresFolders "/tmp/MeshroomCache/FeatureExtraction/c77c2a9b767ad27e4d735c8a0d5098ba49d105ec" --maxDescriptors 500 --minNbImages 200 --nbMatches 40 --verboseLevel info --input "/tmp/MeshroomCache/CameraInit/7ace6f41b0b0ce62bfbe423861d5077f854eef07/cameraInit.sfm" --nbNeighbors 5 --tree "" --method SequentialAndVocabularyTree --weights "" --output "/tmp/MeshroomCache/ImageMatching/70f43846d3d3337f19f9dc142651e6bb6c39fc3b/imageMatches.txt"
 - logFile: /tmp/MeshroomCache/ImageMatching/70f43846d3d3337f19f9dc142651e6bb6c39fc3b/log
 - commandLine: aliceVision_featureMatching  --imagePairsList "/tmp/MeshroomCache/ImageMatching/70f43846d3d3337f19f9dc142651e6bb6c39fc3b/imageMatches.txt" --geometricEstimator acransac --matchFromKnownCameraPoses False --savePutativeMatches False --describerTypes sift --maxMatches 0 --maxIteration 2048 --exportDebugFiles False --knownPosesGeometricErrorMax 5.0 --geometricFilterType fundamental_matrix --geometricError 0.0 --featuresFolders "/tmp/MeshroomCache/FeatureExtraction/c77c2a9b767ad27e4d735c8a0d5098ba49d105ec" --guidedMatching False --verboseLevel info --crossMatching False --input "/tmp/MeshroomCache/CameraInit/7ace6f41b0b0ce62bfbe423861d5077f854eef07/cameraInit.sfm" --photometricMatchingMethod ANN_L2 --distanceRatio 0.8 --output "/tmp/MeshroomCache/FeatureMatching/591ddaea64bbe309422d78557a1f2b6489d5c381" --rangeStart 0 --rangeSize 20
 - logFile: /tmp/MeshroomCache/FeatureMatching/591ddaea64bbe309422d78557a1f2b6489d5c381/0.log
 - commandLine: aliceVision_incrementalSfM  --maxAngleInitialPair 40.0 --interFileExtension .abc --lockAllIntrinsics False --maxReprojectionError 4.0 --lockScenePreviouslyReconstructed False --useLocalBA True --localizerEstimator acransac --maxNumberOfMatches 0 --minInputTrackLength 2 --minAngleForTriangulation 3.0 --initialPairB "" --minNumberOfObservationsForTriangulation 2 --verboseLevel debug --input "/tmp/MeshroomCache/CameraInit/7ace6f41b0b0ce62bfbe423861d5077f854eef07/cameraInit.sfm" --useRigConstraint True --describerTypes sift --minAngleForLandmark 2.0 --localBAGraphDistance 1 --useOnlyMatchesFromInputFolder False --filterTrackForks False --minAngleInitialPair 5.0 --featuresFolders "/tmp/MeshroomCache/FeatureExtraction/c77c2a9b767ad27e4d735c8a0d5098ba49d105ec" --observationConstraint Scale --initialPairA "" --minNumberOfMatches 0 --matchesFolders "/tmp/MeshroomCache/FeatureMatching/591ddaea64bbe309422d78557a1f2b6489d5c381" --localizerEstimatorError 0.0 --localizerEstimatorMaxIterations 4096 --output "/tmp/MeshroomCache/StructureFromMotion/667d209185ac54d3f95155ca60178ffcc85209ec/sfm.abc" --outputViewsAndPoses "/tmp/MeshroomCache/StructureFromMotion/667d209185ac54d3f95155ca60178ffcc85209ec/cameras.sfm" --extraInfoFolder "/tmp/MeshroomCache/StructureFromMotion/667d209185ac54d3f95155ca60178ffcc85209ec"
 - logFile: /tmp/MeshroomCache/StructureFromMotion/667d209185ac54d3f95155ca60178ffcc85209ec/log
[2021-05-24 09:31:52,628][ERROR] Error on node computation: Error on node "StructureFromMotion_1":
Log:
Program called with the following parameters:
 * describerTypes = "sift"
 * extraInfoFolder = "/tmp/MeshroomCache/StructureFromMotion/667d209185ac54d3f95155ca60178ffcc85209ec"
 * featuresFolders =  = [/tmp/MeshroomCache/FeatureExtraction/c77c2a9b767ad27e4d735c8a0d5098ba49d105ec]
 * filterTrackForks = 0
 * initialPairA = ""
 * initialPairB = ""
 * input = "/tmp/MeshroomCache/CameraInit/7ace6f41b0b0ce62bfbe423861d5077f854eef07/cameraInit.sfm"
 * interFileExtension = ".abc"
 * localBAGraphDistance = 1
 * localizerEstimator =  Unknown Type "N11aliceVision16robustEstimation16ERobustEstimatorE"
 * localizerEstimatorError = 0
 * localizerEstimatorMaxIterations = 4096
 * lockAllIntrinsics = 0
 * lockScenePreviouslyReconstructed = 0
 * matchesFolders =  = [/tmp/MeshroomCache/FeatureMatching/591ddaea64bbe309422d78557a1f2b6489d5c381]
 * maxAngleInitialPair = 40
 * maxNumberOfMatches = 0
 * maxReprojectionError = 4
 * minAngleForLandmark = 2
 * minAngleForTriangulation = 3
 * minAngleInitialPair = 5
 * minInputTrackLength = 2
 * minNumberOfMatches = 0
 * minNumberOfObservationsForTriangulation = 2
 * observationConstraint =  Unknown Type "N11aliceVision3sfm18EFeatureConstraintE"
 * output = "/tmp/MeshroomCache/StructureFromMotion/667d209185ac54d3f95155ca60178ffcc85209ec/sfm.abc"
 * outputViewsAndPoses = "/tmp/MeshroomCache/StructureFromMotion/667d209185ac54d3f95155ca60178ffcc85209ec/cameras.sfm"
 * randomSeed = 5489 (default)
 * useLocalBA = 1
 * useOnlyMatchesFromInputFolder = 0
 * useRigConstraint = 1
 * verboseLevel = "debug"

Loading features
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[09:31:51.971049][debug] Loading matches
[09:31:51.979794][debug] Loading match file: /tmp/MeshroomCache/FeatureMatching/591ddaea64bbe309422d78557a1f2b6489d5c381/0.matches.txt
[09:31:51.980498][debug] Track building
[09:31:51.983023][debug] Track filtering
[09:31:51.991239][debug] Track export to internal structure
[09:31:51.991709][debug] Build tracks per view
[09:31:51.995687][debug] Build tracks pyramid per view
[09:31:51.996922][info] Fuse matches into tracks: 
	- # tracks: 2517
	- # images in tracks: 6
[09:31:51.996953][info] TrackLength, Occurrence
[09:31:51.996969][info] 	2	1829
[09:31:51.996976][info] 	3	542
[09:31:51.996981][info] 	4	116
[09:31:51.996986][info] 	5	28
[09:31:51.996991][info] 	6	2
Automatic selection of an initial pair:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[09:31:51.997171][debug] Automatic initial pair choice test - I: 83363121, J: 1581597181, common tracks: 198
[09:31:51.997203][debug] Automatic initial pair choice test - I: 83363121, J: 629562206, common tracks: 376
[09:31:51.997205][debug] Automatic initial pair choice test - I: 629562206, J: 1581597181, common tracks: 203
[09:31:51.997216][debug] Automatic initial pair choice test - I: 1581597181, J: 1777953580, common tracks: 195
[09:31:51.997287][debug] Automatic initial pair choice test - I: 1129807039, J: 1581597181, common tracks: 411
[09:31:51.997302][debug] Automatic initial pair choice test - I: 1581597181, J: 1892028081, common tracks: 472
Segmentation fault (core dumped)

**Comment by yzho0907** [comment]
+1 what is the root of this issue？
