### ISSUE TITLE
3D viewer using a lot of CPU power.

### ISSUE THREAD

**Issue by MagicBOTAlex** [alicevision/meshroom#1425]
I suggest a checkbox that will disables the 3D viewer, automatically after the "StructureFromMotion" node finishes. 

Idle:
![image](https://user-images.githubusercontent.com/44818698/119607064-fe889a80-bdf3-11eb-94ef-81405e7616a5.png)
![image](https://user-images.githubusercontent.com/44818698/119607172-1e1fc300-bdf4-11eb-840d-b63cb3c56bde.png)

Disabled:
![image](https://user-images.githubusercontent.com/44818698/119607206-2e37a280-bdf4-11eb-930c-b9c5881e04ad.png)
![image](https://user-images.githubusercontent.com/44818698/119607216-3263c000-bdf4-11eb-9a17-30cc8dbb303a.png)

I would rather save the CPU power, for processing instead of rendering non-changing point cloud.

**Comment by drewp** [comment]
I think the 3d viewer is rerendering constantly and burning CPU even when nothing's happening. Launching meshroom immediately starts eating 20% of my 4 cores.

**Comment by fabiencastan** [comment]
We hope that it will work better with the major changes to Qt 3D rendering engine in Qt6... But I don't know yet.
https://github.com/alicevision/meshroom/pull/1406

**Comment by MagicBOTAlex** [comment]
While we're on this. The graph editor also uses a small amount of CPU load.

I noticed this when changing the size of the node graph window and saw the CPU load increase when the window was bigger.
