### ISSUE TITLE
[bug] No Scene displayed in 3D-Viewer when running Meshroom from Source Release 

### ISSUE THREAD

**Issue by vieacq** [alicevision/meshroom#1430]
When _Meshroom-2021.1.0.zip_ (Source) is installed according to the guidelines…
	1. 3D-Viewer shows Grid&Gizmo only, shows no computed Scene
	2. "Missing Plugins" reported
	3. But: properly installed binary release works as expected

**Steps taken to identify problem**

- 	Try to run with Python from same code as the binary release

		a. Install _Meshroom-2021.1.0-win64.zip_
		b. Run _Meshroom.exe_ (loading a computed Project: [File]>[Open Recent])
			• Runs as expected
			• 3D-Viewer shows computed Scene (as expected)
		c. Delete  _Meshroom\python37.dll_ to force use of installed Python
			• Running _Meshroom.exe_ works as expected
		d. Run Python (from _cmd.exe_)
			set PYTHONPATH=C:\Projects\AliceVision\Meshroom;^
				C:\Projects\AliceVision\Meshroom\lib;^
				C:\Projects\AliceVision\Meshroom\lib\meshroom;^
				C:\Program Files\Python37\Lib
			set PYTHONHOME=C:\Projects\AliceVision\Meshroom
			python C:\Projects\AliceVision\Meshroom\lib\meshroom\ui\__main__.py
			; __main__.py copied from Source release - missing in binary release
		   • Log
			[2021-05-27 21:41:50,078][WARNING] Missing plugin qtAliceVision.
			[2021-05-27 21:41:50,078][WARNING] Missing plugin qtOIIO.
		   • Meshroom-Window opens, computed Project loaded ([File]>[Open Recent])
			• 3D-Viewer shows no computed scene (shows Grid&Gizmo only)

- Suspected Problem
	• Plugins not loaded when run through Python/Pyside2
	• Possible failing to reference proper directory in PySide.QtCore.QPluginLoader
	• Plugins seem to be loaded correctly in Meshroom.exe, maybe due to possible special coding in Meshroom.exe source.

**Log**
`[2021-05-27 21:41:50,078][WARNING] Missing plugin qtAliceVision.`
`[2021-05-27 21:41:50,078][WARNING] Missing plugin qtOIIO.`

**Desktop:**
 - OS: Windows 10 Pro 20H2
 - Python version 3.7.8
 - Qt/PySide version 5.15.2
 - Meshroom version: both, the binary and the source releases were used
    	○ Meshroom-2021.1.0.zip (Source)
	○ Meshroom-2021.1.0-win64.zip

**Desired usage**
	• Meshroom and AliceVision Development in Visual Studio 16 2019 IDE
	• Debugging of Meshroom's Code using Visual Studio 16 2019 Debugger
	• Combined Visual Studio 16 2019 Project for Meshroom and AliceVision Components debugging

**Comment by JieRen0** [comment]
我也遇到

**Comment by JieRen0** [comment]
我也遇到了类似的问题，请问有解决方案吗
