### ISSUE TITLE
Can't open Meshroom.

### ISSUE THREAD

**Issue by Ofeosys** [alicevision/meshroom#1438]
Every time when I'm trying to run Meshroom, this error appears. What should I do to fix this?

![fff](https://user-images.githubusercontent.com/85644263/121415175-1c1b3f80-c970-11eb-84f5-015954d81e8d.png)

OS: Windows 10
Python 3.9.5

**Comment by natowi** [comment]
Did you download https://www.fosshub.com/Meshroom.html?dwl=Meshroom-2021.1.0-win64.zip or the source code? For the latter you need to follow the instructions. Use the binaries if possible. If you have issues running the binaries, make sure you have the Visual Studio 2015, 2017 and 2019  installed and don´t have any strange paths https://github.com/alicevision/meshroom/wiki/Troubleshooting
