### ISSUE TITLE
[question] KeyframeSelection node wrong Focal Length?

### ISSUE THREAD

**Issue by HarikalarKutusu** [alicevision/meshroom#1447]
**Describe the problem**
In my project where I also have drone videos, I started with HQ images and tried to augment the model with frames from KFS node, but in my previous trials, I failed. I revisited the problem and I saw that the KFS node assigned a Focal Length of 1.2 - which is not correct. After removing Exif data (and putting a random serial number and model names) they could augment - with red icons on the left.

It is a DJI Phantom 4 Pro. The videos are 4K (2160p). Info here:
https://www.djzphoto.com/blog/2018/12/5/dji-drone-quick-specs-amp-comparison-page
https://www.dji.com/phantom-4-pro/info#specs

FOV 84° 8.8 mm/24 mm (35 mm format equivalent) f/2.8 - f/11 auto focus at 1 m - ∞

There are options in the node, namely, mmFocals & pxFocals, but I have no idea how to fill them as DJI did not expose these values. I looked for calculations with crop factors etc but I can never be sure.

How can we approach this?
I also could not find the "inferred" focal length in the log files from exif-stripped reconstruction. Where should I look for the estimate?

**Comment by natowi** [comment]
open the CameraInit folder and the camerainit.sfm contained within.

There you can find the inferred camera parameters, but I don´t know if it is so wise to use them (you need to test it):

intrinsics": [
        {
            "intrinsicId": "1537589559",
            "width": "700",
            "height": "525",
            "sensorWidth": "-1",
            "sensorHeight": "-0.75",
            "serialNumber": "C:\/Users\/Pictures",
            "type": "radial3",
            "initializationMode": "unknown",
            "pxInitialFocalLength": "-1",
            "pxFocalLength": "844.97474683058317",
            "principalPoint": [
                "350",
                "262.5"
            ],
            "distortionParams": [
                "0",
                "0",
                "0"

**Comment by HarikalarKutusu** [comment]
Unfortunately, I don't own that model drone. I'll try to find it on the Internet, somebody must have used this procedure...
I was hoping to have a simple mathematical formula using trigonometry.

Thank you...

**Comment by natowi** [comment]
If you have still images from the same camera, you can use the metadata from them.

**Comment by HarikalarKutusu** [comment]
That I already have, but 1" sensor's photo focal length (which is known) and 4K video frame's focal length (which is unknown as there is no related EXIF data in videos) are different because of the cropping factor (which is not specified in the documentation). Thus, if you shot an image and a video from the same position, the video will be more "zoomed in".
I would think just copying EXIF will be misleading for Meshroom... I read some articles/forum posts about cropping factor calculations but many are just estimates for single shots, not suitable for photogrammetry, I think.
If I could have some pointers for the correct calculations and/or exact definitions of pxFocals I would perhaps be able to calculate mmFocals and/or pxFocals. The tips in the SW and in the documentation are very generic.
But the main question still remains, KFS node gives a wrong focal length, at least in my case...
