### ISSUE TITLE
[Request] Using GPS and accelerometer data to enhance camera reconstruction

### ISSUE THREAD

**Issue by ShinyLuxray** [alicevision/meshroom#1449]
I've been getting decent results from Meshroom, but it could be made even better with GPS and accelerometer data. Other photogrammetry software programs use this data already. As a start, it could at least help verify the camera locations determined by the existing algorithm during StructureFromMotion after appropriate scaling.

With smartphones and drones being able to record their position when taking photos, I think it could potentially be useful to include GPS data embedded in EXIF or in a list taken from a flight path. Smartphones and camera gimbals can also record their tilt through their accelerometer and embed that in their photos.

Being able to use geo-reference information in photos may help with reconstruction quality, and could further be used to scale and orient the model automatically. Not saying any of this is easily done but I'm curious if any of these kinds of things will be considered in the future.

**Comment by natowi** [comment]
Yes, this is on the [wish list](https://github.com/alicevision/meshroom/wiki/Good-first-contributions#gps-support), as are many other geo-related features

**Comment by ShinyLuxray** [comment]
Ok that's great, I'll keep on wishing then. Looking forward to seeing progress on this project!
