### ISSUE TITLE
CameraInit issues when running meshroom_batch on server.

### ISSUE THREAD

**Issue by ukito-pl** [alicevision/meshroom#1454]
**Describe the bug**
Hi, I am trying to run automatic photogrammetry jobs on the cloud server and I ran into issue with CameraInit. I am using images from [Apple photogrammetry example](https://developer.apple.com/documentation/realitykit/creating_a_photogrammetry_command-line_app) as source. I converted them from HEIC to JPGs. 

When I try to run a meshroom_batch command I get error 139 in CameraInit task as log below suggests. Unfortunately this behavior isn't consistent because I also encountered two other errors when running the same command:
- Process got stuck, when inspected with `top` I got: 
 `PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND`
`9567 ubuntu    20   0 9074016 8.055g  27484 R 100.3 52.5  48:06.65 aliceVision_cam`
-  Got error 134, also on CameraInit task, but I didn't save the log file (I will paste it here if it occurs again).

On positive note, one time computation got all the way to DepthMapFiltering and everything was working fine. Unfortunately my ssh connection closed and task got terminated.

What can be a cause for such erratic behavior?

**To Reproduce**
1. Go to folder with example `images` folder
2. Run `meshroom_batch -i images --cache cache -o model -p photogrammetry`

**Expected behavior**
Photogrammetry job should output an obj file.

**Log**

> Program called with the following parameters:
>  * allowSingleView = 1
>  * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1"
>  * defaultCameraModel = "" (default)
>  * defaultFieldOfView = 45
>  * defaultFocalLengthPix = -1 (default)
>  * defaultIntrinsic = "" (default)
>  * groupCameraFallback =  Unknown Type "20EGroupCameraFallback"
>  * imageFolder = "" (default)
>  * input = "/tmp/tmp0z8qqt4o/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"
>  * output = "/tmp/tmp0z8qqt4o/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm"
>  * sensorDatabase = "/home/ubuntu/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/aliceVision/share/aliceVision/cameraSensors.db"
>  * useInternalWhiteBalance = 1
>  * verboseLevel = "info"
>  * viewIdMethod =  Unknown Type "N11aliceVision9sfmDataIO13EViewIdMethodE"
>  * viewIdRegex = ".*?(\d+)" (default)
> 
> Segmentation fault (core dumped)
> Traceback (most recent call last):
>   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
>   File "/opt/Meshroom/setupInitScriptUnix.py", line 39, in run
>   File "bin/meshroom_batch", line 143, in <module>
>   File "/opt/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 277, in buildIntrinsics
> RuntimeError: CameraInit failed with error code 139.
> Command was: "aliceVision_cameraInit  --sensorDatabase "/home/ubuntu/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/aliceVision/share/aliceVision/cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --useInternalWhiteBalance True --viewIdMethod metadata --verboseLevel info --output "/tmp/tmp0z8qqt4o/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm" --allowSingleView 1 --input "/tmp/tmp0z8qqt4o/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"".

**Desktop:**
 - OS: Ubuntu 18.04 hosted on AWS (Deep Learning AMI (Ubuntu 18.04) Version 45.0 - [link](https://aws.amazon.com/marketplace/pp/prodview-x5nivojpquy6y) )
 - Python version 2.7.17
 - Qt/PySide version  ----
 - Meshroom version - Binary version 2021.1.0
  

**Additional context**
I also tried to run the exact same job on my local PC and, beside working very slow, I didn't encounter similiar errors.

**Comment by tokiea** [comment]
I have the same error
