### ISSUE TITLE
Only one intrinsic allowed (2 found, count flips: 1)

### ISSUE THREAD

**Issue by Darker** [alicevision/meshroom#1455]
**Describe the problem**
I discovered that Meshroom can also do panoramas. So far the only program that worked for me was Microsoft's Image Composite Editor, but it does not have a CLI version which is kinda annoying. So I tried it with one previously failed panorama sequence of a huge rainbow.

I selected the "Panorama HDR" pipeline and added the images. After starting it I get this error from node `PreparePanoramaImages`:

```
[22:49:25.575538][error] Only one intrinsic allowed (2 found, count flips: 1)
```

The error does not occur when only 4 images out of 30 were used. I'd rather not have to upload all 30 and I think this is a user error and not an error in meshroom.

Meshroom: 2021.1.0
OS: Windows 10 
Python: 3.7.4

**Comment by fabiencastan** [comment]
Do you use multiple cameras? Or change the zoom during the acquisition?

**Comment by Darker** [comment]
I did not change zoom deliberately, but it may not have been perfectly constant - ie. it may have wiggled a little on my cheap lens. I will retry with other photos, but whatever the cause is, the error may have been more helpful.

**Comment by fabiencastan** [comment]
Sure. Currently, it assumes that the camera and focal length are fixed and creates this error when it's not the case.

**Comment by Darker** [comment]
Thanks, I am closing this on the account that the question has been answered fully. The message probably ought to improve, but now that there's googleable explanation it's not such a big deal.
