### ISSUE TITLE
Camera rig folders cannot be loaded.

### ISSUE THREAD

**Issue by Mikor-mkr** [alicevision/meshroom#1456]
Hello people,
thank you for taking the time to check my issue.

Problem description:
I try to load a folder with subfolder of images based on the example of this [link](https://meshroom-manual.readthedocs.io/en/v19.01.45/faq/multi-camera-rig/multi-camera-rig.html?highlight=rig). The only difference is that I have 4 folders in total.

+ rig/  
|-+ 0/ 
|---- 1.JPG  
|---- 2.JPG
|-+ 1/
|---- 1.JPG
|---- 2.JPG
|-+ 2/
|---- 1.JPG
|---- 2.JPG
|-+ 3/
|---- 1.JPG
|---- 2.JPG

![image](https://user-images.githubusercontent.com/55749072/123235138-44fd1200-d4e4-11eb-83cb-8aee12be23cd.png)

And when I drag and drop the folder in meshroom I get back the following error which I do now know how to interpret.
![image](https://user-images.githubusercontent.com/55749072/123235660-bf2d9680-d4e4-11eb-9ce6-6a59f978a8a5.png)

Any ideas ?

EDIT: I dragged-dropped the sub-folders and not the rig folder and the images are loaded but they are **not linked** is this because I am missing EXIF information if yes then how should I approach this?

**Comment by fabiencastan** [comment]
what do you mean by "they are not linked"?

**Comment by Mikor-mkr** [comment]
hello @fabiencastan, thanks for the interest! I saw at wiki in the multi camera rig section the following:


![image](https://user-images.githubusercontent.com/55749072/123249240-6d3f3d80-d4f1-11eb-8de5-bf2a6e3a6662.png)

This does not happen my case.

**Comment by natowi** [comment]
Did you check out the issues linked there and the exif requirements?

**Comment by Mikor-mkr** [comment]
@natowi yes, the issue was the timestamps. Even though the cameras are synchronized, after post-processing the timestamps were off.
