### ISSUE TITLE
[question] Installation and write issue

### ISSUE THREAD

**Issue by tomlogan501** [alicevision/meshroom#1457]
**Describe the problem**
When I launch meshroom, an error occurs about a path in temp that can't be access

Is there some launch options that I could specify ?

**Screenshots**
![image](https://user-images.githubusercontent.com/56969577/123402350-ee590c00-d5a7-11eb-8872-dc97507cd644.png)

**Desktop (please complete the following and other pertinent information):**
 - OS:  win 10
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: release version 2021

**Comment by tomlogan501** [comment]
Also if I try with a configured shortcut to a project, i got this issue just with a simple picture batch
![image](https://user-images.githubusercontent.com/56969577/123404581-51976e00-d5a9-11eb-97e7-9b26e6071143.png)

**Comment by natowi** [comment]
I don´t know what the zip file is supposed to contain. Did you download Meshroom from the official place? https://github.com/alicevision/meshroom/releases/tag/v2021.1.0

**Comment by tomlogan501** [comment]
yes sure ! I think it's some troubles with my user session but even on the admin session I got the last error.

**Comment by natowi** [comment]
I´ve never seen this error before. The missing e character in your second screenshot is really strange, too

**Comment by simogasp** [comment]
Are you sure that you have the rights to write in  `C:\save_meshroom`?
That is the feature matching step, are all the previous steps successful? They also write in that location

**Comment by tomlogan501** [comment]
Yes I got the rights, I occurs randomly
