### ISSUE TITLE
Unable to Add Photos into Meshroom GUI

### ISSUE THREAD

**Issue by alcurb** [alicevision/meshroom#146]
I'm running Ubuntu v16.04LTS. I'm stuck in that the Meshroom GUI is not accepting any photo dragged into it. The Images panel highlights in the act of dragging in but image file doesn't drop in; field stays empty. I got the following errors in my terminal:
xx@xx-thinkstation-p900:~/meshroom$ PYTHONPATH=$PWD python meshroom/ui
Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMayaMVG, ExportUndistortedImages, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
Plugins loaded:  AppendFiles, AppendText, Ls
[2018-07-13 11:34:32,622][WARNING] == Error while loading the following plugins ==
  * simpleFarmSubmitter: No module named simpleFarm

Failed to download scene at QUrl("")
/bin/sh: 1: aliceVision_cameraInit: not found
[2018-07-13 11:35:51,198][ERROR] Error while building intrinsics : Traceback (most recent call last):
  File "/home/ac/meshroom/meshroom/ui/reconstruction.py", line 365, in buildIntrinsics
    views, intrinsics = cameraInitCopy.nodeDesc.buildIntrinsics(cameraInitCopy, additionalViews)
  File "/home/ac/meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 133, in buildIntrinsics
    subprocess.returncode, cmd)
RuntimeError: CameraInit failed with error code 127. Command was: "aliceVision_cameraInit  --defaultFieldOfView 45.0 --verboseLevel info --sensorDatabase "" --output "/tmp/tmpA9l3U7/CameraInit/fdba592891e8db45e3af8f93b1a59e1470b45d69/cameraInit.sfm" --allowSingleView 1  --input "/tmp/tmpA9l3U7/CameraInit/fdba592891e8db45e3af8f93b1a59e1470b45d69/viewpoints.sfm" --allowIncompleteOutput 1"

Anything I can do to make this work?

**Comment by fabiencastan** [comment]
`/bin/sh: 1: aliceVision_cameraInit: not found`

You need to have [AliceVision](https://github.com/alicevision/AliceVision) binaries in your PATH, like:
`export PATH=/path/to/AliceVision/install/bin:$PATH`

**Comment by fabiencastan** [comment]
Did you manage to build AliceVision and use it in Meshroom?

**Comment by yann-lty** [comment]
@alcurb did you manage to fix this problem?
@robotiko this log looks okay to me, do you have issues to drop images into Meshroom?

**Comment by slate0** [comment]
In my Windows 10 64bit system, I found that once I closed Meshroom, a python exe remained running on my system (using task manager).  I ended the process and when I booted Meshroom again, I was able to drag and drop images into Meshroom.

**Comment by slate0** [comment]
Watch out with that PATH and EXPORT command.  Windows is so messed up it might truncate the user's path, losing data, and EXPORT makes it impossible to get the data back (had this happen to me while building some other open source software).  

I believe the solution was to use the gui environment variables tool.  I would recommend looking into it.

**Comment by AmberReindeer** [comment]
@alcurb 
@robotiko 
Found this page while trying to find answers:

https://groups.google.com/forum/m/#!topic/alicevision/VuLTiKWjiRs

This means that the problem with adding images is probably not in relation to the error in the console.

**Comment by AmberReindeer** [comment]
I know this sounds stupid, but after I started copying images to my desktop first, instead of dragging them straight to Meshroom from an external drive, it started working properly.

**Comment by fabiencastan** [comment]
Yes, it's a know issue that AliceVision only supports ascii characters in file paths.
