### ISSUE TITLE
Meshroom - no node able to be processed

### ISSUE THREAD

**Issue by byelton86** [alicevision/meshroom#1460]
I have 37 photos taken with an iPhone 6S that I've uploaded to my laptop and imported to Meshroom.  When I click start, an error message comes up, stating "Computation/Submitting - Meshroom 2021.1.0  There is no node able to be processed."

**Comment by natowi** [comment]
Could you please share a screenshot?

**Comment by byelton86** [comment]
Program called with the following parameters:
 * allowSingleView = 1
 * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1"
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:\Users\linds\AppData\Local\Temp\tmp1xthq7wd/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"
 * output = "C:/Users/linds/AppData/Local/Temp/tmp1xthq7wd/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm"
 * sensorDatabase = "C:\Users\linds\OneDrive\Documents\Meshroom-2021.1.0-win64\Meshroom-2021.1.0\aliceVision\share\aliceVision\cameraSensors.db"
 * useInternalWhiteBalance = 1
 * verboseLevel = "info"
 * viewIdMethod =  Unknown Type "enum aliceVision::sfmDataIO::EViewIdMethod"
 * viewIdRegex = ".*?(\d+)" (default)

[12:04:05.026082][warning] Some image(s) have no serial number to identify the camera/lens device.
This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximation they will share the same internal camera parameters.
24 image(s) are concerned.
[12:04:05.084166][info] CameraInit report:
        - # views listed: 24
           - # views with an initialized intrinsic listed: 24
           - # views without metadata (with a default intrinsic): 0
        - # intrinsics listed: 1
 - commandLine: aliceVision_cameraInit  --sensorDatabase "C:\Users\linds\OneDrive\Documents\Meshroom-2021.1.0-win64\Meshroom-2021.1.0\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --useInternalWhiteBalance True --viewIdMethod metadata --verboseLevel info --output "C:/Users/linds/OneDrive/Documents/Meshroom-2021.1.0-win64/Dallas/MeshroomCache/CameraInit/7bbc8351375d922e28c14fe877bcf0feee276523/cameraInit.sfm" --allowSingleView 1 --input "C:/Users/linds/OneDrive/Documents/Meshroom-2021.1.0-win64/Dallas/MeshroomCache/CameraInit/7bbc8351375d922e28c14fe877bcf0feee276523//viewpoints.sfm"
 - logFile: C:/Users/linds/OneDrive/Documents/Meshroom-2021.1.0-win64/Dallas/MeshroomCache/CameraInit/7bbc8351375d922e28c14fe877bcf0feee276523/log
 - commandLine: aliceVision_featureExtraction  --input "C:/Users/linds/OneDrive/Documents/Meshroom-2021.1.0-win64/Dallas/MeshroomCache/CameraInit/7bbc8351375d922e28c14fe877bcf0feee276523/cameraInit.sfm" --describerTypes sift --describerPreset normal --describerQuality normal --contrastFiltering GridSort --gridFiltering True --forceCpuExtraction True --maxThreads 0 --verboseLevel info --output "C:/Users/linds/OneDrive/Documents/Meshroom-2021.1.0-win64/Dallas/MeshroomCache/FeatureExtraction/e76f4fb50c2c4f691d9b31e61632386f3ce75d60" --rangeStart 0 --rangeSize 40
 - logFile: C:/Users/linds/OneDrive/Documents/Meshroom-2021.1.0-win64/Dallas/MeshroomCache/FeatureExtraction/e76f4fb50c2c4f691d9b31e61632386f3ce75d60/0.log
Traceback (most recent call last):
  File "d:\release\BUILD\meshroom\meshroom\ui\graph.py", line 384, in execute
  File "d:\release\BUILD\meshroom\meshroom\core\taskManager.py", line 192, in compute
  File "d:\release\BUILD\meshroom\meshroom\core\taskManager.py", line 368, in raiseImpossibleProcess
RuntimeError: [COMPUTATION] Impossible Process:
There is no node able to be processed.

**Comment by byelton86** [comment]
Pictures were taken with an iPhone 6S.

**Comment by byelton86** [comment]
I tried taking a whole second set of pictures from a more distant focal length, but same result (code listed above).

**Comment by natowi** [comment]
Did you download the binary release from here https://www.fosshub.com/Meshroom.html?dwl=Meshroom-2021.1.0-win64.zip ?

Try to use a folder that is not synced with OneDrive

**Comment by byelton86** [comment]
Yes, I'm running 2021.1.0

**Comment by byelton86** [comment]
I also moved the images to a folder on the desktop, and it still gives me the same error message.
