### ISSUE TITLE
[question] Convert Raw Dense Point Cloud from .ABC to .PLY

### ISSUE THREAD

**Issue by juacarri** [alicevision/meshroom#1463]
I am currently trying to export the densified point cloud, created during the meshing process to import it into CloudCompare. To do so, I have followed the default workflow, activating the "Save Raw Dense Point Cloud" option from the advanced options of the Meshing process, and then using the "ConvertSfmFormat" tool to convert the raw point cloud in .abc format, which is correctly created in .ply format. The problem is that when the process is completed, the point cloud that weighs more than 400mb in .abc is converted to a 10kb file. Could you tell me where the error is?

![Sin título](https://user-images.githubusercontent.com/15093811/124013701-50bc6d00-d9eb-11eb-8855-6f803b5c67c2.png)

Log of the ConvertSfmFormat tool:
`[19:59:06.804652][warning] Alembic LOAD: NO OBSERVATIONS_WITH_FEATURES: , mvg_visibilityFeatId: 0, mvg_visibilityFeatPos: 0, OBSERVATIONS_WITH_FEATURES flag: true`

**Comment by fabiencastan** [comment]
The dense point cloud is not linked to a specific describer type. So you need to enable "unknown" describer type in the ConvertSfmFormat.

**Comment by juacarri** [comment]
Thank you so much Fabien. I just read that it is also written in the manual.
