### ISSUE TITLE
[question] Create a meshroom better than (guest)estimation calculator

### ISSUE THREAD

**Issue by ownrepo1s** [alicevision/meshroom#1470]
**Describe the problem**

I'm trying to find non-linear responses (increase / decrease in time and memory) to different changes in the input configuration, with a fixed hardware configuration and photo set input.

**Additional context**
Basically I'm trying to create a calculator for better than guesstimating the time and memory requirements when I do a change on the configuration for a given dataset of pictures that I benchmarked once or twice on the same physical machine.

**Questions**

1. How do you suggest I approach this?
    I have the following in mind:
   
    a. Create a log parser and plot the time differences for each log file meshroom creates.
    b. Find the pareto in this (20% of things take 80% of the time/memory to compute)
    c. Focus on those inputs that affect the output in a non-linear way (say you increase an input configuration variable with 5%, and the time to compute the output increases with 50% or more) 

2. How can I benchmark your code on a function by function basis, more easily?
I'm thinking about contributing with performance tests and by writing those, extracting the required information for the calculator as well. But there may be a faster way of achieving this on the whole project without actually writing code. 
WDYT?

**Comment by natowi** [comment]
Take a look at https://github.com/alicevision/meshroom/pull/842

**Comment by ownrepo1s** [comment]
Thanks, looking in the weekend, cheers, @natowi
