### ISSUE TITLE
Texturing with a selection of different set of photos

### ISSUE THREAD

**Issue by leilaessa** [alicevision/meshroom#1472]
I am trying to generate a multispectral 3D model with both visile, UV and IR images. The picture are acquired with the object always in the same position and with different light sources. 
My problem is the following: i acquired 3 rings of pictures with visible light (flipping the object on different sides), but only for two of them I have the photos with the UV and IR source.  

I used the 3 rings with visible light to build the 3D model and then I would like to use the method reported in:

  https://github.com/alicevision/meshroom/issues/763 

to generate a texture with the UV and IR set (only 2 set of images). The process fail because a set of image is missing.

Is it possible to use only 2 of the 3 set of photo to re-texture the model?

Thanks

**Comment by fabiencastan** [comment]
You need to find a way to provide to the Texturing node an sfmData file with only the selected views/cameras.

**Comment by fabiencastan** [comment]
For instance, you can use the ConvertSfmFormat node and set an "Image White List".
You can put a simplified regex in it to match a specific set of images:
```
"image white list containing uid(s), image filenames or regex(es) on the image file path (supported regex: '#' matches a single digit, '@' one or more digits, '?' one character and '*' zero or more)"
```

**Comment by leilaessa** [comment]
In which part of the pipeline should I insert the ConvertSfmFormat node?
I tried to insert it after the StructureFromMotion and before the PrepareDenseScene, but this last fails with this log:


<img width="800" alt="Schermata 2021-07-15 alle 15 35 48" src="https://user-images.githubusercontent.com/87311787/125797136-a3e3645f-7915-4343-9803-419d2e20b70e.png">


This is the pipeline that i used:

<img width="974" alt="Schermata 2021-07-15 alle 15 41 23" src="https://user-images.githubusercontent.com/87311787/125798010-162fdf43-ebbb-4c2f-a50d-3833ef600c32.png">

**Comment by fabiencastan** [comment]
You should put it between the Meshing and Texturing nodes.
Be careful to check all the feature types including the "unknown" one.

**Comment by fabiencastan** [comment]
(But the PrepareDenseScene should not have failed like this...)

**Comment by leilaessa** [comment]
I tried, but i think I am making some kind of mistake. Can you send me more information of how to connect properly the meshing,  ConvertSfmFormat and tecturing nodes?

Thank you

**Comment by leilaessa** [comment]
> You should put it between the Meshing and Texturing nodes.
> Be careful to check all the feature types including the "unknown" one.

I tried, but i think I am making some kind of mistake. Can you send me more information of how to connect properly the meshing, ConvertSfmFormat and tecturing nodes?

Thank you
