### ISSUE TITLE
Initial pair view error when using command line

### ISSUE THREAD

**Issue by mrobertudes** [alicevision/meshroom#1481]
**Describe the problem**
I am trying to run the ["Monstree" dataset](https://github.com/alicevision/dataset_monstree) with Meshroom's command line feature. For this I use the following python script : 
[run_alicevision.zip](https://github.com/alicevision/meshroom/files/6836382/run_alicevision.zip)

The error seems to happen at the "Depth map" step, but "Structure from motion" and "Prepare Dense Scene" also output nothing.
The error :
![image](https://user-images.githubusercontent.com/43117873/126070408-490621d4-f45f-43ae-9c94-62f0ff502b20.png)

I also realized that the "initialPairA" doesn't have the right value when using this command :

![image](https://user-images.githubusercontent.com/43117873/126071255-031fdde4-3312-4817-b89b-a43876ebcdf8.png)

**Desktop (please complete the following and other pertinent information):**
 - OS: Win 10
 - Python version 3.6.9
 - Meshroom version: 2021.1.0 (Release)

**Comment by ChemicalXandco** [comment]
This is not a problem with meshroom, this is a problem with your script. If you want to use meshroom from the command line I highly recommend that you use the command line scripts as documented [in the official documentation](https://meshroom-manual.readthedocs.io/en/latest/feature-documentation/cmd/photogrammetry.html) (although this has been renamed to `meshroom_batch` in the latest version and the documentation has not been updated since)

**Comment by mrobertudes** [comment]
Thank you for your answer @ChemicalXandco ,

I did see that script was mentioned in the official documentation, but I was not able to find it in the binaries of the project (which is where it is supposed to be according to the project's README, if I'm not mistaken)
![image](https://user-images.githubusercontent.com/43117873/126075925-ca9fc7a5-5500-4b1d-8402-a1fd3180e317.png)

Do you know where I could find it?
Thank you

**Comment by ChemicalXandco** [comment]
> Do you know where I could find it?

it is in the root of the folder `Meshroom-2021.1.0` in the [release zip file](https://github.com/alicevision/meshroom/releases/tag/v2021.1.0)

**Comment by Etigau37** [comment]
> > Do you know where I could find it?
> 
> it is in the root of the folder `Meshroom-2021.1.0` in the [release zip file](https://github.com/alicevision/meshroom/releases/tag/v2021.1.0)

since when is running a .exe with python legit? As i can see, the meshroom_batch file you are refering to is an executable.
![image](https://user-images.githubusercontent.com/46386751/126082589-d3f2d0bc-41d7-4d95-be72-39c8bb3c3060.png)

**Comment by Etigau37** [comment]
@ChemicalXandco It works when executing:
 `meshroom_batch.exe --input INPUT_IMAGES_FOLDER --output OUTPUT_IMAGES_FOLDER`
 The "python" in front was confusing me, but in the end I should have tried earlier without it. Anyway, thanks for the help :)
