### ISSUE TITLE
Transfering calibration data from OpenCV to Camera Init node

### ISSUE THREAD

**Issue by Phoenix-64** [alicevision/meshroom#1484]
I calibrated my camera with the OpenCV method [cv2.aruco.calibrateCameraCharucoExtended](https://docs.opencv.org/4.5.2/d9/d6a/group__aruco.html). This returns me the focal length and distortion parameters in the Brown-Conrady model. The specific parameters are k1, k2 and k3 for radial distortion and p1, p2 for tangential distortion.
The problem is that in the Camera Init node if the Camera Type is set to brown and I add 5 distortion parameters, they are not labelled. Wich are the tangential and which are the radial ones? And in what order are they? 
Transfering calibration data from OpenCV to Camera Init node
Here is a example of the parameters returned by OpenCV:
                 fx               fy                    cx                    cy                   k1  \
value   2983.609062  2983.609062  2008.786077  1129.857428  0.069759   
stddev     0.000000     2.959608     3.664702     4.215931  0.003851   

              k2           p1            p2             k3  
value   0.068102  0.001089  0.000459 -0.424215  
stddev  0.022468  0.000464  0.000493  0.040313 
 - OS: Windows 10
 - Meshroom version: 2921.1.0

**Comment by natowi** [comment]
From https://github.com/alicevision/meshroom/issues/921 and by comparing to OpenMVG it should be as follows:
Distortion Parameters:
0 - k1
1 - k2
2 - k3
3 - p1
4 - p2

This information should be added to the tooltip
