### ISSUE TITLE
Is it possible to use meshroom as a back-end for visual positioning?

### ISSUE THREAD

**Issue by sam1am** [alicevision/meshroom#1486]
Here is what I am imagining: 

1. Compute a mesh of an area to be used as the reference. 
2. Phone sends image via API to server with meshroom
3. Meshroom computes the single photo against the mesh
4. The camera pose is returned to the phone 

Would this be possible with the current command line tools?

**Comment by natowi** [comment]
Compute a mesh of an area to be used as the reference.
    -> no, Meshroom can not match an image against an existing mesh
    
    Phone sends image via API to server with Meshroom
    Meshroom computes the single photo against the mesh
    ->you could augment an existing reconstruction with a new image. It will try to match the new images with the other images based on detected features. But this is probably not robust enough for your use case.
    
    The camera pose is returned to the phone
    -> depending on different conditions it is possible, but may be time consuming depending on the covered area and amount of images in the dataset the new image has to be matched against.

**Comment by sam1am** [comment]
> no, Meshroom can not match an image against an existing mesh

Ah, right. I meant the mesh metadata (reconstruction is the correct term?). If you add one photo into an existing project with all the current photos already trained - does it take long to have one more calculated, or does it have to go back through all the photos again?  

Meshroom is extremely accurate and figuring out camera positions. I know it's not built for this purpose but it could be a possible capability to explore.

**Comment by simogasp** [comment]
There is a camera localization module that does exactly that but it does not take as input the mesh but the sfm reconstruction output, i.e. the camera poses, the landmarks (sparse point cloud) and the associated descriptors.

**Comment by natowi** [comment]
https://meshroom-manual.readthedocs.io/en/latest/feature-documentation/nodes/CameraLocalization.html
