### ISSUE TITLE
Drag and drop for images is irresponsive

### ISSUE THREAD

**Issue by 12xq4** [alicevision/meshroom#149]
I have encountered an issue regarding drag and drop of images into the editor. Currently when I mouse over the editor with any photos the cursor is disabled and dropping photos into the viewport have no effect. Meanwhile, the console does not display any additional log.
I am using a x64 Windows 10 PC with GTX 970 GPU, and I built Alice Vision with Visual Studio 2015.4.

Logs after executing python meshroom/ui:
Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, ExportUndistortedImages, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
Plugins loaded:  AppendFiles, AppendText, Ls
[2018-07-18 16:27:54,690][WARNING] == Error while loading the following plugins ==
 * simpleFarmSubmitter: No module named simpleFarm

Failed to download scene at QUrl("")

**Comment by fabiencastan** [comment]
Did you manage to understand and fix the problem?

**Comment by 12xq4** [comment]
Hi yea, apparently the solution to this issue is to run meshroom from Powershell (the non-admin version). Would love some explanations.

**Comment by dimabe0** [comment]
for me 
[https://answers.microsoft.com/de-de/windows/forum/all/vcomp140dll-fehlt-pl%C3%B6tzlich/599a913c-a8b1-48ec-b48f-f93158ff7361](https://answers.microsoft.com/de-de/windows/forum/all/vcomp140dll-fehlt-pl%C3%B6tzlich/599a913c-a8b1-48ec-b48f-f93158ff7361)
helped. After installing the tools drag and drop worked for both non-admin and admin.

**Comment by KickingKing** [comment]
> Did you run Meshroom as admin? If yes, that's the cause. _Windows disables drag and drop on applications being run as admin._

^ THISSS! Worked for me. Thanks
