### ISSUE TITLE
[question] Build Meshroom with QtOIIO and qtAliceVision : Missing plugin qtOIIO.

### ISSUE THREAD

**Issue by remmel** [alicevision/meshroom#1492]
I build AliceVision and Meshroom on **Ubuntu 20.04** and almost everything work fine, except the DepthMap viewer (and Sfm)
Indeed I have following error :
```
[2021-07-31 10:57:04,601][WARNING] Missing plugin qtAliceVision.
[2021-07-31 10:57:04,601][WARNING] Missing plugin qtOIIO.
```

(Because my priority is to view exr DepthMap - **qtOIIO** plugin - , I'll simplify and not use [qtAliceVision](https://github.com/alicevision/QtAliceVision/blob/develop/INSTALL.md) and QmlAlembic. It is possible to use qtOIIO without qtAliceVision and QmlAlembic, right?)

I built successfully [qtOIIO](https://github.com/alicevision/QtOIIO/blob/develop/INSTALL.md):
```
~/workspace/meshroom-global/QtOIIO/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/home/remmel/Qt/5.13.2/gcc_64 -DCMAKE_INSTALL_PREFIX=install
CMake version: 3.16
-- OpenImageIO found.
-- Qt 5.13 found.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/remmel/workspace/meshroom-global/QtOIIO/build
~/workspace/meshroom-global/QtOIIO/build$ make install
[ 11%] Automatic MOC for target QtOIIOPlugin
[ 11%] Built target QtOIIOPlugin_autogen
[ 55%] Built target QtOIIOPlugin
[ 66%] Automatic MOC for target depthMapEntityQmlPlugin
[ 66%] Built target depthMapEntityQmlPlugin_autogen
[100%] Built target depthMapEntityQmlPlugin
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /home/remmel/workspace/meshroom-global/QtOIIO/build/install/imageformats/libQtOIIOPlugin.so
-- Up-to-date: /home/remmel/workspace/meshroom-global/QtOIIO/build/install/qml/DepthMapEntity/qmldir
-- Up-to-date: /home/remmel/workspace/meshroom-global/QtOIIO/build/install/qml/DepthMapEntity/libdepthMapEntityQmlPlugin.so
```

And I run meshroom with thoses parameters:
```
export PYTHONPATH=$PWD
export QML2_IMPORT_PATH=/home/remmel/workspace/meshroom-global/QtOIIO/build/install/qml
export QT_PLUGIN_PATH=/home/remmel/workspace/meshroom-global/QtOIIO/build/install/
python3 meshroom/ui
```

To avoid building myself thoses qtLib, I also tried **without success** to use those packaged with last release
```
export PYTHONPATH=$PWD
export QML2_IMPORT_PATH=/home/remmel/workspace/bin/Meshroom-2021.1.0/qtPlugins/qml
export QT_PLUGIN_PATH=/home/remmel/workspace/bin/Meshroom-2021.1.0/qtPlugins
python3 meshroom/ui
```

What's wrong on my command running meshroom/ui ?

**Comment by natowi** [comment]
You could try MESHROOM_INSTALL_DIR
https://github.com/alicevision/meshroom/issues/667

**Comment by remmel** [comment]
Thanks, I can **successfully** run **Meshroom source tag v2021.1.0** with **AliceVision release 2021.1**:

`LD_LIBRARY_PATH=/home/remmel/workspace/bin/Meshroom-2021.1.0/aliceVision/lib/ PYTHONPATH=$PWD QML2_IMPORT_PATH=/home/remmel/workspace/bin/Meshroom-2021.1.0/qtPlugins/qml QT_PLUGIN_PATH=/home/remmel/workspace/bin/Meshroom-2021.1.0/qtPlugins python3 meshroom/ui`
(or with MESHROOM_INSTALL_DIR instead: `LD_LIBRARY_PATH=/home/remmel/workspace/bin/Meshroom-2021.1.0/aliceVision/lib/ PYTHONPATH=$PWD MESHROOM_INSTALL_DIR=/home/remmel/workspace/bin/Meshroom-2021.1.0/ python3 meshroom/ui` )

But I'm **still stucked** with running **Meshroom source dev** branch with **AliceVision dev** (got `Missing plugin qtAliceVision. Missing plugin qtOIIO.`) . I'm suspecting some missing share lib required by qtOIIO.
@natowi can your share your directory structure ? Where to checkout, build and install in order to have similar structure ? Are you using win or linux? Where can I find the script which generate the zip in https://github.com/alicevision/meshroom/releases ?

**Comment by remmel** [comment]
I tried with `Qt5.14.1` (instead of `5.13.2`) to match version used in [Docker](https://github.com/alicevision/meshroom/blob/develop/docker/build-ubuntu.sh) but I still have `Missing plugin` errors.
Someone as some tip of what I should check or debug? how to debug the qml to have more information? (I tried without success to get more information using `aliceVisionPluginLoader.errorString()` in [Viewer2D.qml](https://github.com/alicevision/meshroom/blob/develop/meshroom/ui/qml/Viewer/Viewer2D.qml)

```
# install of QT, use the exact same way than docker
wget wget https://download.qt.io/archive/qt/5.14/5.14.1/qt-opensource-linux-x64-5.14.1.run
export QT_CI_LOGIN=remy@gmail.com
export QT_CI_PASSWORD=123456
/qt-opensource-linux-x64-5.14.1.run --verbose --platform minimal --script /home/remmel/workspace/meshroom-global/meshroom/docker/qt-installer-noninteractive.qs

# qmlAlembic
cd ~/workspace/meshroom-global/qmlAlembic/build
cmake .. -DAlembic_DIR=~/workspace/meshroom-global/alembic/build/lib/Alembic -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/home/remmel/Qt5.14.1/5.14.1/gcc_64
make install

# QtAliceVision
cd ~/workspace/meshroom-global/QtAliceVision/build/
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/home/remmel/Qt5.14.1/5.14.1/gcc_64 -DCMAKE_INSTALL_PREFIX=/home/remmel/workspace/meshroom-global/qtPlugins
make install

# QtOIIO
cd ~/workspace/meshroom-global/QtOIIO/build/
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/home/remmel/Qt5.14.1/5.14.1/gcc_64 -DCMAKE_INSTALL_PREFIX=/home/remmel/workspace/meshroom-global/qtPlugins
make install

# Run UI
cd ~/workspace/meshroom-global/meshroom
pip install -r requirements.txt -r dev_requirements.txt
export PYTHONPATH=$PWD
export LD_LIBRARY_PATH=/home/remmel/workspace/meshroom-global/build/Linux-x86_64/
export PATH=$PATH:/home/remmel/workspace/meshroom-global/build/Linux-x86_64/
export QML2_IMPORT_PATH=/home/remmel/workspace/meshroom-global/qtPlugins/qml
export QT_PLUGIN_PATH=/home/remmel/workspace/meshroom-global/qtPlugins
python3 meshroom/ui
```
