### ISSUE TITLE
[question] How to provide Depth maps instead of estimating them??

### ISSUE THREAD

**Issue by MAdelElbayumi** [alicevision/meshroom#1493]
As depth maps estimation is taking most of my pipline time, I want to provide them already from my camera and skip the estimation, how could I achieve that?

**Comment by remmel** [comment]
I'm working on that topic, importing kinect or Honor tof depth image. https://github.com/remmel/meshroom/tree/dev_importTofDepthMap
Where does your images come from?

Same topic : https://github.com/alicevision/meshroom/issues/1361

**Comment by MAdelElbayumi** [comment]
it should be from TOF camera

**Comment by remmel** [comment]
Which camera or smartphone?

Le jeu. 5 août 2021 à 18:09, MAdelElbayumi ***@***.***> a
écrit :

**Comment by MAdelElbayumi** [comment]
I am trying the ability of doing that, can you please tell me which mobile tof is more convenient for your work?

**Comment by remmel** [comment]
There are a couple of Android Tof devices. All Huawei/Honor seems to use the same sensor. I'm using Honor View 20. You can find a list of Android tof devices in the description : https://play.google.com/store/apps/details?id=com.lvonasek.tofviewer

**Comment by MAdelElbayumi** [comment]
Thank you very much, I just cloned your work and it's really awesome!!
But I am facing troubles building it. can you please share the steps to run your meshroom version on windows? I want to examine the node

**Comment by natowi** [comment]
@MAdelElbayumi Place DepthMapImport.py from [meshroom/meshroom/nodes/aliceVision/](https://github.com/remmel/meshroom/blob/dev_importTofDepthMap/meshroom/nodes/aliceVision/DepthMapImport.py) into the folder of your normal Meshroom installation: Meshroom\Meshroom-2021.1.0-win64\Meshroom-2021.1.0\lib\meshroom\nodes\aliceVision

This does only work for nodes that reference libraries that are available with the Meshroom binary build.
For development, you can download the Meshroom 2021.1 [binaries](https://github.com/alicevision/meshroom/releases/download/v2021.1.0/Meshroom-2021.1.0-win64.zip) with the corresponding 2021.1 [source code](https://github.com/alicevision/meshroom/archive/refs/tags/v2021.1.0.zip), copy the AliceVision folder and the folders from within the qtPlugins folder to the Meshroom Source Code folder and run the start.bat / start.sh

**Comment by MAdelElbayumi** [comment]
@remmel, I run meshroom and found the node you've added, can you please share any TOF series with us to test the pipeline?

**Comment by remmel** [comment]
> @remmel, I run meshroom and found the node you've added, can you please share any TOF series with us to test the pipeline?

Great! I replied here https://github.com/alicevision/meshroom/issues/1361#issuecomment-894847430

**Comment by MAdelElbayumi** [comment]
I got this error while importing images Failed to Import Images:
**`You probably have a corrupted image within the images that you are trying to import.`**

**Comment by remmel** [comment]
Do you have same problem importing other image? There is probably a more
concrete error in the terminal, can you send it? The terminal error will
probably indicate that the binary or shared lib is missing. In that case
you have to set the PATH and/or LD_LIBRARY_PATH

**Comment by MAdelElbayumi** [comment]
That's right, I got the same problem with other images that works fine on the binaries version. so, which PATH should I set? 

```
[2021-08-09 16:52:53,939][WARNING] == The following "submitters" plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

[2021-08-09 16:52:56,239][WARNING] Missing plugin qtAliceVision.
[2021-08-09 16:52:56,240][WARNING] Missing plugin qtOIIO.
[2021-08-09 16:53:40,946][WARNING] Model size of -9 is less than 0
[2021-08-09 16:53:51,115][ERROR] Error on node computation: Error on node "CameraInit_1":
Log:
Program called with the following parameters:
 * allowSingleView = 1
 * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1,3deanamorphic4,3deradial4,3declassicld"
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "E:/DepthmapMeshroom/MeshroomCache/CameraInit/a4cd0d4d88ff601c55d5f5fa6a4849808c163650//viewpoints.sfm"
 * output = "E:/DepthmapMeshroom/MeshroomCache/CameraInit/a4cd0d4d88ff601c55d5f5fa6a4849808c163650/cameraInit.sfm"
 * sensorDatabase = ""
 * useInternalWhiteBalance = 1
 * verboseLevel = "info"
 * viewIdMethod =  Unknown Type "enum aliceVision::sfmDataIO::EViewIdMethod"
 * viewIdRegex = ".*?(\d+)" (default)

[16:53:50.828806][fatal] 3deanamorphic4

[2021-08-09 16:53:51,115][WARNING] Downgrade status on node "FeatureExtraction_1(0)" from Status.SUBMITTED to Status.NONE
[2021-08-09 16:53:51,118][WARNING] Downgrade status on node "FeatureMatching_1(0)" from Status.SUBMITTED to Status.NONE
[2021-08-09 16:53:51,119][WARNING] Downgrade status on node "StructureFromMotion_1" from Status.SUBMITTED to Status.NONE
[2021-08-09 16:53:51,121][WARNING] Downgrade status on node "DepthMapImport_1" from Status.SUBMITTED to Status.NONE
[2021-08-09 16:53:51,123][WARNING] Downgrade status on node "Meshing_2" from Status.SUBMITTED to Status.NONE
[2021-08-09 16:53:51,126][WARNING] Downgrade status on node "MeshFiltering_2" from Status.SUBMITTED to Status.NONE
[2021-08-09 16:53:51,129][WARNING] Downgrade status on node "Texturing_2" from Status.SUBMITTED to Status.NONE
[2021-08-09 16:53:51,131][WARNING] Downgrade status on node "PrepareDenseScene_1(0)" from Status.SUBMITTED to Status.NONE
[2021-08-09 16:53:51,133][WARNING] Downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Status.NONE
[2021-08-09 16:53:51,136][WARNING] Downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
[2021-08-09 16:53:51,137][WARNING] Downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
[2021-08-09 16:53:51,139][WARNING] Downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
[2021-08-09 16:53:51,142][WARNING] Downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
[2021-08-09 16:53:51,145][WARNING] Downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
[2021-08-09 16:53:51,147][WARNING] Downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
[2021-08-09 16:53:51,149][WARNING] Downgrade status on node "ImageMatching_1" from Status.SUBMITTED to Status.NONE
[2021-08-09 16:53:54,978][WARNING] ShellExecute 'file:///home/remmel/workspace/dataset/2021-07-27_centerchess/photos' failed (error 2).
Program called with the following parameters:
 * allowSingleView = 1
 * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1,3deanamorphic4,3deradial4,3declassicld"
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:\Users\pc\AppData\Local\Temp\tmpnkcn9g5t/CameraInit/a4cd0d4d88ff601c55d5f5fa6a4849808c163650//viewpoints.sfm"
 * output = "C:/Users/pc/AppData/Local/Temp/tmpnkcn9g5t/CameraInit/a4cd0d4d88ff601c55d5f5fa6a4849808c163650/cameraInit.sfm"
 * sensorDatabase = ""
 * useInternalWhiteBalance = 1
 * verboseLevel = "info"
 * viewIdMethod =  Unknown Type "enum aliceVision::sfmDataIO::EViewIdMethod"
 * viewIdRegex = ".*?(\d+)" (default)

[16:54:13.229933][fatal] 3deanamorphic4
[2021-08-09 16:54:13,291][ERROR] Error while building intrinsics: CameraInit failed with error code 1.
Command was: "aliceVision_cameraInit  --sensorDatabase "" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1,3deanamorphic4,3deradial4,3declassicld --useInternalWhiteBalance True --viewIdMethod metadata --verboseLevel info --output "C:/Users/pc/AppData/Local/Temp/tmpnkcn9g5t/CameraInit/a4cd0d4d88ff601c55d5f5fa6a4849808c163650/cameraInit.sfm" --allowSingleView 1 --input "C:\Users\pc\AppData\Local\Temp\tmpnkcn9g5t/CameraInit/a4cd0d4d88ff601c55d5f5fa6a4849808c163650//viewpoints.sfm"".

[2021-08-09 16:54:13,294][WARNING] QQmlComponent: Created graphical object was not placed in the graphics scene.

```

**Comment by remmel** [comment]
> That's right, I got the same problem with other images that works fine on the binaries version
I understand that MR release version works fine (but don't have my node). How to you do to use source version? (dev Meshroom with release Alicevision? or you build Alicevision as well?)

> ShellExecute 'file:///home/remmel/workspace/dataset/2021-07-27_centerchess/photos'
Why do you have that? Are you using the .mg file I put on Google Drive? It should not work as we don't have same directory structure

**Comment by MAdelElbayumi** [comment]
I followed @natowi comment above, using your dev meshroom branch and copying alicevision and qtplugins from binaries then I run start.bash after installing requirements. Actually I can see your node in the program but can't load images. 

**Note:** Sorry, I tried to load the scene also, I edited the above comment.

**Comment by remmel** [comment]
It won't work because binaries you use are from Alicevision 2021.1 and UI
from Meshroom DEV. You have to use compatible version (built yourself
Alicevision Dev to use with Meshroom Dev OR use Alicevision 2021.1 with
Meshroom git tag 2021.1).
Or probably easier if it works, as mention by @natowi
<https://github.com/natowi>, to copy paste my python file in last
Alicevision/Meshroom release, without the need to clone and build anything

**Comment by MAdelElbayumi** [comment]
Actually, I added the file as you've mentioned @natowi, I got this warning `* DepthMapImport: No module named 'cv2'` ,  although I have opencv on my pip, and I can't see the node in the application, but the loading problem was gone (I am usig meshroom latest binaries with DepthMapImport.py approach) am I missing something?

**Comment by MAdelElbayumi** [comment]
@remmel  Okay, I built Alicevision Dev and got your Meshroom Dev version what should I do next?

**Comment by MAdelElbayumi** [comment]
The problem was I couldn't import images inside meshroom, nvm for now. 

Now I skipped this, I am calling alicevision binaries from Python, and there is something I can't understand in your pipeline, I think that you did this work to skip estimating depthmaps, but I found that in order to import depth maps I have to run DepthMap and DepthMapFiltering nodes, and you've said that I can either enhance depth maps or importing them, 
I don't want to go through these Nodes, how to achieve this in your script DepthMapImport.py? 
![image](https://user-images.githubusercontent.com/72761370/129221572-0ffc6abc-9e91-4678-9d36-6c6d864accbb.png)

**Comment by remmel** [comment]
The pipeline I tested uses depthmaps and DepthMapFilter in order to
calculate the ratio between Sfm size and meters. This is not mandatory as
you can calculate that yourself, and set the ratio. You should probably
modify the script a little bit to avoid needed DepthMap. In October, I'll
update the script. The pipeline I used is in the screenshot of the other
GitHub issue

**Comment by MAdelElbayumi** [comment]
I was debugging the work, actually it's awesome! :D 
The only help I need is to know what does the ratio means and I see it's the reason you need depth maps, but what does it represent to be able to calculate it, upon reading I understood that it's a scaling factor you use to calibrate your new depth maps, but can you provide more details on how to calculate it from inputs previous inputs?

**Comment by remmel** [comment]
The ratio is the difference between the sfm unit and the tof unit (tof unit are in meter or mm).
Both set of data must use same unit. Is like comparing temperature in celcius, fahrenheit: you must use same unit.
I use depthmaps to automatically calculate the unit difference of both dataset.
There are alternative, for example

- if you know the space between 2 poses
- measuring object in the point cloud and reality
- placing markers
Late you set yourself the "ratio" in my script, or you decide to scale the sfm in order to have same scale using https://meshroom-manual.readthedocs.io/en/bibtex1/node-reference/nodes/SfMTransform.html

**Comment by VihangMhatre** [comment]
What format do the depth maps need to me? I have depth maps in TIFF format. WIll that work or they need to be in EXR format? 
@remmel @MAdelElbayumi

**Comment by remmel** [comment]
> What format do the depth maps need to me? I have depth maps in TIFF format. WIll that work or they need to be in EXR format? @remmel @MAdelElbayumi

In my https://github.com/remmel/meshroom/blob/425b64c1a3976a0ab01a02171e61d7484857b653/meshroom/nodes/aliceVision/DepthMapImport.py if you check the `readInputDepth` it handles png file (16b grayscale) or Android DEPTH16 binary. You can update my script to handle tiff or convert your tiff to 16b png.
I don't know if opencv will handle your type of tiff. Where did you get it?

**Comment by VihangMhatre** [comment]
> > What format do the depth maps need to me? I have depth maps in TIFF format. WIll that work or they need to be in EXR format? @remmel @MAdelElbayumi
> 
> In my [DepthMapImport.py](https://github.com/remmel/meshroom/blob/425b64c1a3976a0ab01a02171e61d7484857b653/meshroom/nodes/aliceVision/DepthMapImport.py) if you check the `readInputDepth` it handles png file (16b grayscale) or Android DEPTH16 binary. You can update my script to handle tiff or convert your tiff to 16b png. I don't know if opencv will handle your type of tiff. Where did you get it?

Got it from iphone

**Comment by remmel** [comment]
How with the iPhone? Using which application? front portrait photo
(structured of light) or back portrait photo (lidar) ?

**Comment by VihangMhatre** [comment]
> 

lidar back camera

**Comment by remmel** [comment]
ok. If it can help, I was able to extract the depth from the iphone front
portrait mode using image magick (exiftool -b -MPImage3 IMG_0520.JPG >
depth.jpg). But the depth is "RangeInverse" or "RangeLinear" check
https://developers.google.com/depthmap-metadata/reference to understand
what I'm talking about. It should be the same in the tiff  and 0 might not
mean 0m (far/near option).
