### ISSUE TITLE
why cameras is shown in SFM model? and can I make them disappear?

### ISSUE THREAD

**Issue by ohadOrbach** [alicevision/meshroom#1495]
**Describe the problem**
As you can see in the photo when i put my sfm model (ply format) in MeshLab i get also all cameras (circle in green) when i need only the cloud of points. can i make them disappear?

**Screenshots**
![image](https://user-images.githubusercontent.com/46603682/128251714-cea38ffa-5faf-4f39-9d9f-7b0cefaf5afa.png)

**Comment by natowi** [comment]
You exported the point cloud with the cameras. Read https://github.com/alicevision/meshroom/wiki/Export-

**Comment by ohadOrbach** [comment]
hi @natowi  thank you for your answer, but I still didn't found where can I change the settings so the cameras want exported.
I used ConvertSFMFormat and try all settings in this node.

**Comment by natowi** [comment]
![scs](https://user-images.githubusercontent.com/8138537/128892509-4601b065-c990-47c0-bff7-f0680003a1aa.JPG)
