### ISSUE TITLE
[bug] Cannot import photos.

### ISSUE THREAD

**Issue by Pheidologeton** [alicevision/meshroom#1497]
**Describe the bug**
Error Importing photos. I use Meshroom and Alice-Vision from AUR. When importing such an error in the GUI (see Screenshot). 

**To Reproduce**
1) Start meshroom

2) Import photos

**Expected behavior**

**Screenshots**
![Screenshot_41](https://user-images.githubusercontent.com/61123444/128582117-987867df-f46c-45c5-a391-3b4dc34a64bd.png)

**Log**
~~~ Meshroom
WARNING:root:== The following "submitters" plugins could not be loaded ==
* simpleFarmSubmitter: No module named 'simpleFarm'

WARNING:root:Missing plugin qtAliceVision.
WARNING:root:Missing plugin qtOIIO.
aliceVision_cameraInit: error while loading shared libraries: libImath-3_0.so.28: cannot open shared object file: No such file or directory
ERROR:root:Error while building intrinsics: CameraInit failed with error code 127.
Command was: "aliceVision_cameraInit  --sensorDatabase "/usr/share/aliceVision/cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --useInternalWhiteBalance True --viewIdMethod metadata --verboseLevel info --output "/tmp/tmp9ebnmbbi/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm" --allowSingleView 1 --input "/tmp/tmp9ebnmbbi/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"". 

WARNING:root:QQmlComponent: Created graphical object was not placed in the graphics scene. ~~~

**Desktop (please complete the following and other pertinent information):**
 - OS: Garuda linux (arch based)
 - Python version (3.9)
 - 5.15.2
 - Meshroom version: latest AUR (2021.1.0-6)
   - Binary version 2021.1.0

**Comment by natowi** [comment]
The qt plugins are not installed: 
WARNING:root:Missing plugin qtAliceVision.
WARNING:root:Missing plugin qtOIIO.

**Comment by Pheidologeton** [comment]
The thing is that I do not have in the Meshroom installation folder of these Qt Pliguns.
How can I install them?

**Comment by natowi** [comment]
The folders should be in the Meshroom folder
https://meshroom-manual.readthedocs.io/en/latest/first-steps/install/getting-meshroom/platforms/linux.html
https://github.com/alicevision/meshroom/releases/tag/v2021.1.0

**Comment by Pheidologeton** [comment]
The problem is solved. The fact is that for work and compilation requires CUDA version 10, it does not work with version 11 and is not compiled from the source code. The most strange thing is that version from AUR compiled without an error with CUDA 11. BIN version from AUR works without problems with CUDA 11, strange. Also, the problem is that alice-vision from AUR is not compiled with CUDA 11.
