### ISSUE TITLE
Single image augmentation

### ISSUE THREAD

**Issue by bgpantojar** [alicevision/meshroom#1501]
Hello,

I was wondering if it is possible to do a single image augmentation attaching this image to one already used in the sfm. I have a reconstruction and want to add just an image knowing which is the most similar to this.

Best,
Bryan

**Comment by natowi** [comment]
Did you try "augment reconstruction" when you drag and drop the image in Meshroom?

**Comment by bgpantojar** [comment]
Yes, I did try and most of the times works (It failed when the augmentation was with images from other device). What I would like to do is just tell to meshroom to do the augmentation giving beforehand the image matching between new image and one of the old images. In that way, I want the feature matching would be only between those images and the new pose calculated from that pre-defined image. Is it possible to do it?

**Comment by natowi** [comment]
So maybe you are looking for something like https://github.com/alicevision/meshroom/issues/1486 ? ->camera localization

**Comment by bgpantojar** [comment]
Yes, it is what I was looking for. Thanks a lot!
