### ISSUE TITLE
Meshroom result issue 

### ISSUE THREAD

**Issue by ghost** [alicevision/meshroom#1502]
I'm so new with Meshroom...... Dose anyone could help me what happened ? im trying to 3d Scan Human Head but end up with a giant Cube Meshing  

![Screenshot (15)](https://user-images.githubusercontent.com/88781094/129034900-8c4b01a8-14e3-40ef-94c6-58198e5d9cc6.png)

![Screenshot (14)](https://user-images.githubusercontent.com/88781094/129034863-d7b788f3-0cbd-4d24-b3c6-44bb48fbe54e.png)

**Comment by fabiencastan** [comment]
Could you share your dataset with me to reproduce it?
fabien.castan@mikrosimage.com

**Comment by Twistzz6868** [comment]
You need my file or just Photo do re-do scanning ?

**Comment by fabiencastan** [comment]
Just the input images to see if the error is repeatable.

**Comment by Twistzz6868** [comment]
will send to you when upload is finish..... thank before hand
