### ISSUE TITLE
Replace sync image from 3D viewer

### ISSUE THREAD

**Issue by bgpantojar** [alicevision/meshroom#1505]
Hello,

After doing the 3D reconstruction, there is a nice feature you have implemented to overlap the image with the point cloud as in the image shown.

![Screenshot from 2021-08-16 15-21-55](https://user-images.githubusercontent.com/35929939/129570509-bb6407ec-70ad-45f8-9776-2c214b5e615d.png)

Now I am willing to replace this image in both image and 3D viewer with a new image. For that I change the image in the original path for the one I want. When loaded, the image in the it is displayed the next:

![Screenshot from 2021-08-16 15-25-11](https://user-images.githubusercontent.com/35929939/129571018-fca82ace-4824-4261-844f-6e602017f70e.png)

You can see that only the image viewer is loading the new image. I would like to update this in the 3D viewer as well. Do you have any suggestions on how to do it?

Thanks,

Best,
Bryan

**Comment by fabiencastan** [comment]
The image displayed in the 3D Viewer is the undistorted image (the output of the PrepareDenseScene).

**Comment by bgpantojar** [comment]
perfect... thanks a lot!
