### ISSUE TITLE
VCOMP140.dll was not found [question]

### ISSUE THREAD

**Issue by dabiz7** [alicevision/meshroom#1506]
**Describe the problem**
A clear and concise description of what the problem is.

**Screenshots**

**Dataset**
If applicable, add a link or *few* images to help better understand where the problem may come from.

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ]
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1]
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**

**Comment by dabiz7** [comment]
OS win 10
Pyhton 3.7.4
Meshroom Win 10 2021.1.0

I confirmed VCOMP140.dll is in fact in the folder, still get same issue. WTF>????

**Comment by dabiz7** [comment]
I even tried to download the test images, still got the same error

**Comment by natowi** [comment]
Install  [Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) to solve the VCOMP140.dll not found error [#840](https://github.com/alicevision/meshroom/issues/840) vc_redist.x64.exe
