### ISSUE TITLE
[question] Point Cloud after sFM Mis-Oriented

### ISSUE THREAD

**Issue by ForbiddenEra** [alicevision/meshroom#1519]
**Describe the problem**
While the point cloud seems to have sort of a floor, this is mis-aligned with the floor mesh. I'm aware I can use a sfm transform to help fix it but should this even be necessary? Is it an issue with my dataset?

**Screenshots**
![image](https://user-images.githubusercontent.com/7980490/131247970-508dacc5-30a7-4979-b1e5-4a44d4985bc8.png)

(fixed as best I could with transform but this was a big pain since none of the gizmo axis align with any actual axis, I almost wonder if an intuitive add-on for transform would be being able to free rotate the gizmo/origin/data separately or something?)

![image](https://user-images.githubusercontent.com/7980490/131248061-5346b1c6-5090-4123-b474-b2af4d40accb.png)

**Comment by ForbiddenEra** [comment]
Also (I'm sure I'm missing something) even after adjusting with the transform, my mesh when it appears is un-aligned as if it was never transformed, even if I add a second sfmtransform before (or after) meshing?

![image](https://user-images.githubusercontent.com/7980490/131248235-0db50d00-4f3f-4a5d-9172-e949f4e98605.png)

**Comment by ForbiddenEra** [comment]
I'm also a little confused as to why the object like.. literally doesn't appear in the mesh.. like as if it wasn't in the photos..? Is there not enough contrast between the object and the background or something?

**Comment by fabiencastan** [comment]
For the initial question, there is no notion of scale and orientation in SfM.
The only solution are some heuristics that you can do at the end, as done in the SfMTransform node. But we have not found a rule that works for all dataset, so it's not by default.
Have you tried SfMTransform with "auto_from_landmarks"?

For the 2nd question: why the object is not in the Mesh. It's probably due to the lack of texture on the object.
The lighting conditions also seems to be far from optimal. You probably have much more noise than texture details on this weakly-textured object.
If you don't care about the texture, you can project a texture pattern or add some temporary texture to the object.

**Comment by ForbiddenEra** [comment]
> 
> 
> For the initial question, there is no notion of scale and orientation in SfM.
> The only solution are some heuristics that you can do at the end, as done in the SfMTransform node. But we have not found a rule that works for all dataset, so it's not by default.
> Have you tried SfMTransform with "auto_from_landmarks"?
> 
> For the 2nd question: why the object is not in the Mesh. It's probably due to the lack of texture on the object.
> The lighting conditions also seems to be far from optimal. You probably have much more noise than texture details on this weakly-textured object.
> If you don't care about the texture, you can project a texture pattern or add some temporary texture to the object.

Thanks for the response. I assumed that it was contrast/texture, and yeah, lighting wasn't ideal - just wanted to play around with the software and get started with PG. I'll try again later with better lighting and something to give contrast between the object and the floor.

I think that perhaps (and again, maybe wouldn't work for all datasets) finding the 'floor' orientation based off the camera orientation might be a possibility, we are generally taking "domes" around our object - although some might do under as well. It seemed to know which way was down - and there was an obvious sort of 'floor plane' in the point cloud that could potentially be used. 

auto_from_landmarks made no difference at all I don't think, it was the default.
