### ISSUE TITLE
[question] Installation guide for Windows + docker

### ISSUE THREAD

**Issue by nekym** [alicevision/meshroom#1525]
Hi guys!
I'm trying to install the meshroom on my Windows 11 machine.
I have WSL2 and GTX1070.
I installed CUDA from https://developer.nvidia.com/cuda-downloads
And I got the following when run `nvidia-smi` in my console on Windows
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.06       Driver Version: 510.06       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| 32%   46C    P2    32W / 180W |   2005MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```
The same I will get if I run `nvidia-smi` inside my WSL (I have Ubuntu on WSL)

For the meshroom I have the following docker file
```
FROM alicevision/meshroom:2021.1.0-av2.4.0-centos7-cuda10.2

# CentOS
RUN curl -sL https://rpm.nodesource.com/setup_16.x | bash -
RUN yum -y install nodejs && \
    yum -y install mc && \
    yum -y install fish

# Build client and server.
WORKDIR /app

COPY package*.json ./

RUN npm install 

COPY . .

EXPOSE 80

CMD [ "npm", "start" ]
```
which I run with docker compose:
```
  generator:
    build: ../3D-generator
    restart: always
    volumes:
      - ${VOLUME_PATH}/viewer:/app/data
    networks:
      - proxy-tier
      - 3d-net
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu, utility]
```

Then I just run the container and inside it I'm trying to run `meshroom_batch --input ./images/ --output ./`
And I got error messages
```
- commandLine: aliceVision_depthMapEstimation  --input "/tmp/MeshroomCache/StructureFromMotion/594820ac183b969d4ad1febb01d20f0203660824/sfm.abc" --imagesFolder "/tmp/MeshroomCache/PrepareDenseScene/7b16d7ec8d5410b5c215283481963ed07ceaa522" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5..5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output "/tmp/MeshroomCache/DepthMap/7a6c9cecbe96964313d8622bb5b09f1faa3b39c5e" --rangeStart 6 --rangeSize 3
 - logFile: /tmp/MeshroomCache/DepthMap/7a6c9cecbe96964313d8622b5b09f1faa3b39c5e/2.log
ERROR:root:Error on node computation: Error on node "DepthMap_1(2)":
Log:
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "/tmp/MeshroomCache/PrepareDenseScene/7b16d7ec8d5410b5c215283481963ed07ceaa522"
 * input = "/tmp/MeshroomCache/StructureFromMotion/594820ac183b969d4ad1febb01d20f0203660824/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "/tmp/MeshroomCache/DepthMap/7a6c9cecbe96964313d8622b5b09f1faa3b39c5e"
 * rangeSize = 3
 * rangeStart = 6
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[09:37:04.257558][warning] Could not determine number of CUDA cards in this system
[09:37:04.257484][warning] No CUDA-Enabled GPU.
[09:37:04.257656][error] cudaGetDeviceCount failed: CUDA driver version is insufficient for CUDA runtime version
[09:37:04.257669][info] Can't find CUDA-Enabled GPU.
[09:37:04.257675][error] This program needs a CUDA-Enabled GPU (with at least compute capability 2.0).
```

Can you please help me? What did I do wrong?

**Comment by simogasp** [comment]
you need to run docker with the nvidia support `-it --runtime nvidia`, e.g. for meshroom
```docker
# docker run -it --runtime nvidia -p 2222:22 --name meshroom -v</path/to/your/data>:/data alicevision/meshroom:develop-av2.2.8.develop-ubuntu20.04-cuda11.0
```
see here https://github.com/alicevision/meshroom/blob/1a9692d498621164da285b2a5138220808b3b4a5/docker/Dockerfile_centos#L9

**Comment by nekym** [comment]
> you need to run docker with the nvidia support `-it --runtime nvidia`, e.g. for meshroom
> 
> ```
> # docker run -it --runtime nvidia -p 2222:22 --name meshroom -v</path/to/your/data>:/data alicevision/meshroom:develop-av2.2.8.develop-ubuntu20.04-cuda11.0
> ```
> 
> see here
> 
> https://github.com/alicevision/meshroom/blob/1a9692d498621164da285b2a5138220808b3b4a5/docker/Dockerfile_centos#L9

Do you know how to do it in the case of docker-compose?
I found https://docs.docker.com/compose/gpu-support/ this help, but seems that it does not work properly because I even cannot run their examples with `nvidia-smi` inside the container.

**Comment by simogasp** [comment]
I don't know then.
Have you installed nvidia docker?
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker

**Comment by nekym** [comment]
> Have you installed nvidia docker?
> https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker
No, I have not.
And it is a good question, should I install it or not?
Because it's only for the unix systems and I'm trying to run docker containers from Windows.
Or should I install it on my WSL kernel (Ubuntu)? 
Or should I install it inside my meshroom docker container?

**Comment by simogasp** [comment]
I don't know on windows but on Linux you have to otherwise it won't work

**Comment by nekym** [comment]
Good news. 
The first is that I had to install cuda drivers on my WSL. Here is official NVIDIA guide https://docs.nvidia.com/cuda/wsl-user-guide/index.html
The second thing is that after the first one it did not work :-D
But if I will run my docker from `docker run` instead of `docker-compose` then it works!
So for now it is a good question how to apply `-gpus all` options for the docker-compose.

**Comment by nekym** [comment]
Solved!
For the docker-compose works the following:
```
  generator:
    build: ../3D-generator
    restart: always
    volumes:
      - ${VOLUME_PATH}/viewer:/app/data
    networks:
      - proxy-tier
      - 3d-net
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu

```
I took it from https://github.com/docker/compose/issues/6691

**Comment by fabiencastan** [comment]
Hi @nekym,
Thanks for the feedback! That looks cool!
Could you make a PR with the specific docker files for windows?

**Comment by nekym** [comment]
> Hi @nekym,
> Thanks for the feedback! That looks cool!
> Could you make a PR with the specific docker files for windows?

Hi!
To be honest, it is not a docker file. It's a docker-compose file.
And the main reason why I had my problem was that I did not installed nvidia drivers for WSL and used incorrect docker-compose parameters.

If you wish I can write an installation guide for Windows + WSL + Docker (with docker-compose or without) + Meshroom?
