### ISSUE TITLE
Meshroom shuts down when importing images(win)

### ISSUE THREAD

**Issue by APOS80** [alicevision/meshroom#1526]
**Describe the bug**
Meshroom starts, i select images and when i push the button it shuts down.

**To Reproduce**
1. Start Meshroom
2. Select images
3. klick to import
4. meshroom dissapears

**Expected behavior**
images gets in

**Desktop (please complete the following and other pertinent information):**
 - OS: Win 10

 - Meshroom version: 2021.1.0

**Comment by APOS80** [comment]
Seams to be a speciffic batch om images thats cousing the problem.

**Comment by APOS80** [comment]
Problem found, it cant handle "ÅÄÖ" in foldernames.

**Comment by natowi** [comment]
Yes, that is a known issue #209
