### ISSUE TITLE
Dense reconstruction fails

### ISSUE THREAD

**Issue by bgpantojar** [alicevision/meshroom#1531]
I run the meshroom pipeline for a set of images (around 100 having partial view of the table -> aimed to be reconstructed) getting the next reconstruction for SfM (you can see how the cameras were distributed):

![Screenshot from 2021-09-13 13-10-47](https://user-images.githubusercontent.com/35929939/133074125-ec107ceb-f948-49f3-a158-33a55aa06fbf.png)

Although that reconstruction was ok (all the images were registered), the mesh and textured mesh from the dense reconstruction fails as you can see:

Just textured.

![Screenshot from 2021-09-13 13-11-07](https://user-images.githubusercontent.com/35929939/133074766-f7f774c0-fab1-4a9e-bc30-c928c5cff2b0.png)

SfM + textured

![Screenshot from 2021-09-13 13-11-22](https://user-images.githubusercontent.com/35929939/133074788-e2c31407-be50-4ebd-a742-c57ccf4ce103.png)

From my interest is the dense reconstruction. Do you have any idea why is not working? I assumed that the depth maps are not well assigned for the area that is missing. Is it possible to modify some parameters in the pipeline to make it work? (I was imagining maybe to restrict to use just some images with depth information for instance). Do you recomend a beter set up of the cameras? (maybe one where from each image it is possible to see the full table instead of partially).

Best,
Bryan

**Comment by dpellegr** [comment]
I am encountering the same problem: good SfM data, but totally off mesh reconstruction.
No solution so far. Having some guidelines/settings to try to approach the problem would be great.
