### ISSUE TITLE
software stops tracking camera placement

### ISSUE THREAD

**Issue by 0neSpeed** [alicevision/meshroom#1534]
Hi, am new here (on github and with Meshroom) so be forgiving if possible.
I am having an issue where the camera seems to stop tracking my model but always in the same spot, no matter what I do, might that be changing settings or reshooting from scratch.

I am using a turntable setup to try and photogrammetry a coffee bean.

I've been using akaze since sift seems to want to track the background... even though it is completely blank.
I've been using medium for both describer density and quality. Image matching is Vocabulary Tree and guided matching is set to on

Here is a screenshot of what the software is doing with the cameras
![Cameras](https://user-images.githubusercontent.com/90956860/133881717-6995a8d5-cba7-4ee3-8a7c-71002cb907f8.png)

Here is a picture cropped in to show the resolution/distortion I am currently working with.
![_DSC7438](https://user-images.githubusercontent.com/90956860/133881661-417d7d9d-9722-4427-b75f-325be299c338.JPG)

Here is a gif with a green and red indicator showing when the software can and cant solve the camera position:
![Normal-2](https://user-images.githubusercontent.com/90956860/133881634-82056aa0-6721-4054-92ef-774d263e452d.gif)

**Desktop:**
 - OS: win 10
 - Meshroom version: 2021.1.0

Which parameter can I adjust to help the program figure out where my camera is? 
Any help would be greatly appreciated, thank you.

**Comment by fabiencastan** [comment]
When the object is on the side, there is not enough surface & texture to get matches. Put a textured surface on the ground (rotating with the object).
