### ISSUE TITLE
Mesh is filled with holes and missing areas. Help!

### ISSUE THREAD

**Issue by alexwatsoncreative** [alicevision/meshroom#1536]
I am using over 200 photos from a DJI drone. High res and good quality. My point cloud isn't as dense as I'd like and the mesh is filled with holes once I bring it into C4D. How can I fix this? 

Attached are just a few pics from the drone, the others are the point cloud and mesh from the MeshFiltering folder inside C4D. 

What setting should I adjust? Should I do something different with the photos?

<img width="323" alt="2021-09-22 10_02_06-p__Whitestone_PhotoGrammerty Test_Jasper_Meshroom_Jasper mg - Meshroom 2021 1 0" src="https://user-images.githubusercontent.com/91203975/134359668-8d610940-0989-4dc0-8e52-c438d7ea07c2.png">
<img width="690" alt="2021-09-22 10_02_41-CINEMA 4D R20 059 Studio (RC - R20) -  Untitled 1 _  - Main" src="https://user-images.githubusercontent.com/91203975/134359669-2b8f10fe-867b-4663-9fb5-bcb23ec351a7.png">
<img width="618" alt="2021-09-22 10_11_22-8000×6000_ DJI_0010 jpg" src="https://user-images.githubusercontent.com/91203975/134360155-e36ce42a-f156-4225-a775-3c9932c69553.png">
<img width="429" alt="2021-09-22 10_11_39-8000×6000_ DJI_0091 jpg" src="https://user-images.githubusercontent.com/91203975/134360156-2c72228d-880e-4c12-8258-9268828d356f.png">
<img width="928" alt="2021-09-22 10_11_56-8000×6000_ DJI_0166 jpg" src="https://user-images.githubusercontent.com/91203975/134360160-d41f0458-65d5-49ad-8e80-5ed1b23f7a80.png">

**Comment by davidbrodrick** [comment]
There's many related bugs reported on here. I just did a comparison.

Meshroom 2020.1 - sift+akaze - high density - 270k points, 436 images matched
Meshroom 2021.1 - dspsift - high density - 75k points, 438 images matched
Meshroom 2021.1 - dspsift - ultra density - 75k points, 424 images matched
Meshroom built from latest source - dspsift - high density - 277k points, 445 images matched (but it won't let me visualise the point cloud or textured mesh).

So I think reverting to last year's release is probably the best option?

**Comment by fabiencastan** [comment]
Hi @davidbrodrick,

I'm sorry but I do not understand your argumentation. You are presenting various number related to different parameter settings and I don't see what this shows.

In the "develop" branch, the default value "dspsift with normal density" is now more stable across datasets. This reduce the need to adjust this density parameter per dataset.

**Comment by fabiencastan** [comment]
@alexwatsoncreative Did you get all your cameras localized?

**Comment by davidbrodrick** [comment]
Dear @fabiencastan . The numbers are just to illustrate to the OP reported, and what many others have said here in various issues: that 2021.1 returns a much lower number of points than the 2020 version. Of course dspsift wasn't available in 2020 for a direct comparison, but out of the different combinations with reasonable, typical settings, the 2021.1.0 version (presumably what OP was using) performs much worse than the others. Switching to the development branch or the 2020 release would probably solve their problems.
It seems the development code is also fixed, although I have other problems with that at least in my build. I guess a 2021.2.0 release would be great when you are ready.
Thanks for your work in developing an amazing tool!
