### ISSUE TITLE
Grid and gizmo missing from 3D viewer

### ISSUE THREAD

**Issue by jhaggle** [alicevision/meshroom#1546]
I have installed Meshroom on ubuntu according to the instructions in this link:
https://meshroom-manual.readthedocs.io/en/latest/first-steps/install/getting-meshroom/platforms/linux.html
(Although my version is Meshroom-2021.1.0-linux-cuda10.tar.gz.)
![asdf](https://user-images.githubusercontent.com/11705343/136343026-fa09eb34-8ac8-4646-9a8c-eca625ef3489.png)

It now should look like this:
![with_gizmo](https://user-images.githubusercontent.com/11705343/136343083-42ade9ac-654f-4a20-ba0a-7ec46e46baf2.png)

However, as seen from this image I don't have the grid or the gizmo in the 3D viewer
![without_gizmo](https://user-images.githubusercontent.com/11705343/136343160-ab45dc7e-fc5e-4448-aa0e-8097dfca6da9.png)

Also, after running the pipeline, I cannot see the cameras.
What is wrong and how can it be fixed?

**Comment by davidbrodrick** [comment]
I also have this problem, or at least a similar problem. After building from source last week I cannot visualise the point clouds at all. Nothing is rendered. Mesh visualisation is okay though.

**Comment by davidbrodrick** [comment]
So my problem is different actually. The grid is rendered okay, but "StructureFromMotion" label never appears under SCENE and the point cloud if never shown, whether the SfM completes, or if I double click on the node to try to visualise it.

**Comment by Goh-tsen** [comment]
I have the same problem. Once I run the program (preinstalled version for Ubuntu), there is no grid and trackball in 3d viewer panel with these two option active. This problem doesn't exist when I run the windows version in another PC. I don't know if there are some key packages required before I run the program?

**Comment by fadenb** [comment]
I am experiencing the same issue:
```
Version 2021.1.0
Linux 5.15.0-56-generic 
Python 3.6.3
```
