### ISSUE TITLE
3D - 2D correspondences

### ISSUE THREAD

**Issue by bgpantojar** [alicevision/meshroom#1550]
Hello,

I was wondering if it is possible to identify the 3D-2D correspondences between the key-points detected and the SfM (sparse) point cloud. Is there a file among the output files that contains this information?

I would like to know the position of the key point in the image and its descriptor, and also which is the correspondent 3D point.

Thanks,

Bryan

**Comment by bgpantojar** [comment]
Hello,

No worries at all. I closed the issue as I had found exactly the information you shared. Thanks anyway.

I was wondering if the sift descriptors saved inside the feature extraction folder can be loaded from opencv. or should I use alicevision function directly for this? I saw that they are binary files. Is there the possibility to save them as no binary files?

Thanks for the help

Best,
Bryan

**Comment by bgpantojar** [comment]
@simogasp

**Comment by bgpantojar** [comment]
@simogasp Hello. I just wrote a code extracting the Descriptor.hpp and numeric.cpp-.hpp files to read the binary descriptors and save it in a text file (using alicevision function loadDescsFromBinFile. When I run it, the saved value of the descriptors elements make non sense and then I cannot use them for matching for instance. The code I wrote and some of the point descriptors are in the images attached. Do you see maybe the possible mistake in the code I wrote?
![Screenshot from 2022-03-28 14-30-47](https://user-images.githubusercontent.com/35929939/160399853-59412b98-2e08-424b-9f97-c5c962675d61.png)

![Screenshot from 2022-03-28 14-30-20](https://user-images.githubusercontent.com/35929939/160399903-debbd652-9a74-4dae-bd18-fdef88363740.png)

**Comment by simogasp** [comment]
where did you get the 61 for the descriptor size from?
Akaze is either 64 or 144 float, see here
https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/feature/regionsFactory.hpp

**Comment by bgpantojar** [comment]
I thought it used same than opencv where it is 61. Despite of that, even for sift I am geting wrong descriptors when reading... I tried to use the results to match kps and got the following:
![Screenshot from 2022-03-28 15-20-57](https://user-images.githubusercontent.com/35929939/160406865-2e14ba78-e2fe-43a5-88a9-8052ca180b3a.png)
![Screenshot from 2022-03-28 15-21-04](https://user-images.githubusercontent.com/35929939/160406868-db023283-68a1-4932-96ca-7cee34733cc9.png)

**Comment by bgpantojar** [comment]
Yes, I did that checking and those quantities are the same. In the next link I have put the output files (an the ones getting with my small function)

https://drive.google.com/drive/folders/1gtEenPVOcSohbkch9SstV1VUSN7Hdi2c?usp=sharing

**Comment by simogasp** [comment]
they seem correct to me. I ran a quick test loading from bin and saving to txt and i get the same values as your code.

**Comment by bgpantojar** [comment]
the one that just says akaze
![Screenshot from 2022-03-28 16-36-18](https://user-images.githubusercontent.com/35929939/160422396-20e2ccbd-cf01-4222-89aa-9c42b06e855c.png)

**Comment by simogasp** [comment]
that one corresponds to `using AKAZE_Float_Regions = ScalarRegions<float,64>;` , so float with 64 elements
