### ISSUE TITLE
[question]How to use different set of image for texturing?

### ISSUE THREAD

**Issue by aeoleader** [alicevision/meshroom#1559]
I am trying to use downscaled image sets for sfm and mesh reconstruction and use the original images for texturing. Since the feature extraction node doesn't offer image downscale options I need to preprocess the input images first then perform feature extraction and the following calculations. However, to ensure the final quality of the output mesh I want to calculate texture based on the original image sets. Is there a way to do so? 

I checked the previous issues and the closest matching problem is #763 but it is using the previous version of meshroom, the new version we need to provide Dense SfMData to the texturing node.

**Comment by natowi** [comment]
Popsift hast a limit on the image size https://github.com/alicevision/popsift/issues/77
I don´t know how to solve your dimension mismatch problem for now. Maybe dsp-sift works with the full image?.

**Comment by aeoleader** [comment]
> Popsift hast a limit on the image size [alicevision/popsift#77](https://github.com/alicevision/popsift/issues/77) I don´t know how to solve your dimension mismatch problem for now. Maybe dsp-sift works with the full image?.

Thanks for your reply! 

Would switching to a GPU with larger VRAM help?

**Comment by aeoleader** [comment]
BTW, I think maybe a feature request can be made regarding adding downscale factor to the feature extraction node, because sometimes it is inefficient to use the fullsize images to perform tracking, and the fullscale images are usually required at the reconstruction stage in practice.
