### ISSUE TITLE
Panorama HDR - 2 lenses, 1 image

### ISSUE THREAD

**Issue by Manopoli** [alicevision/meshroom#1560]
Hi Meshroom community, 

These last few weeks I've been working with Meshroom 2021.1.0 (Windows 10). It took a bit of getting used to but I fell in love with the software. 

So far, I'm using this to reconstruct large public environments like streets and a public square. I took a bunch of photos from the buildings, sidewalk and crossing but I did not scan the road itself. I did however capture 360-photographs from the road and, to my surprise, Meshroom offers an option to generate mesh from panorama HDR. 

I have tried both the Panorama HDR and the Panorama Fisheye HDR pipelines but I am not able to finish reconstruction. Here's the log error:: 
[12:08:04.580688][error] Unable to load matches files from: [D:/Meshroom projects/MeshroomCache/FeatureMatching/d29578197a7df3515cfde79a58f99217d8d66f65]

I'm guessing this has to do with the 360° camera saving the photographs from 2 lenses into 1 file. The camera itself is recognized so if this is the issue, then my question is:
**Is there an option somewhere to manually add an extra lens in the PanoramaInit node?**

And in case this is not the issue here, please let me know what I should do to fix this.

Thanks in advance!

![Screenshot 2021-10-28 115742](https://user-images.githubusercontent.com/6077108/139233638-8de25da6-3540-4c02-80e0-a217926c2f39.jpg)
![Screenshot 2021-10-28 121944](https://user-images.githubusercontent.com/6077108/139237224-35d05107-6f36-4e86-96a2-5c13e93c5a66.jpg)
![Screenshot 2021-10-28 122505](https://user-images.githubusercontent.com/6077108/139238092-d8620043-45a5-4981-9344-e0fcf1e33f64.jpg)
)

**Comment by Manopoli** [comment]
@fabiencastan 
We are about to purchase a new 360 cam, for this feature in Meshroom. 
Which cameras are supported/do you recommend? I was thinking about getting the Theta Z1.

Thanks in advance!

**Comment by natowi** [comment]
Place the .pcy file in the _Meshroom-2021.1.0\lib\meshroom\nodes\aliceVision_ folder:
[Split360Images.zip](https://github.com/alicevision/meshroom/files/7714368/Split360Images.zip) (You can also place .py nodes in this folder and Meshroom will create the pyc in a subfolder on startup.)

**Comment by Erol444** [comment]
@natowi Could you elaborate on this sentence?
```
At the moment connections to the init node are not supported, so you need to drag and drop the output back into Meshroom
```
I am not sure how to properly connect InitCamera with these two Split360Images nodes, I have tried many things already.
