### ISSUE TITLE
Why do I have so many blemishes on my face, I ask everyone to help improve the quality of the facial model

### ISSUE THREAD

**Issue by Miracle086** [alicevision/meshroom#1566]
![图片1](https://user-images.githubusercontent.com/94168302/141446371-8df3b15e-d0db-46a9-9ab6-48bf795c8b65.png)

Does anyone know how to adjust the parameters to improve the quality of the face model? I used the dense reconstruction function, the effect is not very good

**Comment by natowi** [comment]
How did you capture the images and what camera did you use? The result is not bad assuming the setup is not optimal.

**Comment by Miracle086** [comment]
> How did you capture the images and what camera did you use? The result is not bad assuming the setup is not optimal.

I used the IPHONE7 to take photos, and the set parameters are default. But there are too many blemishes on the face

**Comment by Miracle086** [comment]
![1636743517(1)](https://user-images.githubusercontent.com/94168302/141520592-51a8f73a-f5f4-4e26-87d5-e1e6a0c091a5.png)
You can see my photo, This is my first contact with meshroom, maybe I need to adjust my parameters, but I don’t know how to adjust.

**Comment by natowi** [comment]
The blemishes are likely caused by small movements and different lighting of your skin. 
 Here are parameters you can adjust in general https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters
 Also smoothing the mesh could help (MeshDenoising node).

**Comment by Miracle086** [comment]
Thanks everyone for your help，

> The blemishes are likely caused by small movements and different lighting of your skin. Here are parameters you can adjust in general https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters Also smoothing the mesh could help (MeshDenoising node).

Thanks for your help to me, I will be try it. Have a good weekend

**Comment by Miracle086** [comment]
> The blemishes are likely caused by small movements and different lighting of your skin. Here are parameters you can adjust in general https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters Also smoothing the mesh could help (MeshDenoising node). There is a reason, why big studios have a [camera rig with lighting to capture people](https://www.creativebloq.com/features/the-secrets-of-3d-scanning) ;)

Can you help me solve a small problem? How to use meshdenoising node, please forgive me for being a beginner

**Comment by natowi** [comment]
You can place the node after the mesh filtering node (remove the out connection and connect it with the new node in between)
Increase the lamda a bit to get a better result for skin.

**Comment by Miracle086** [comment]
> 您可以将节点放置在网格过滤节点之后（删除输出连接并将其与中间的新节点连接） 稍微增加 lamda 以获得更好的皮肤效果。
> 
> 类似#1098

OK，Thanks I try do it

**Comment by natowi** [comment]
This is the reconstruction quality one can achieve in Meshroom with a professional dataset (I used an old sample by https://triplegangers.com/blog/cat/technology/post/free-scan-sample/) without smoothing or post processing:

![face1](https://user-images.githubusercontent.com/8138537/141539720-697b0bc5-959e-48c5-a363-2fd42d5c21b7.JPG)
![face2](https://user-images.githubusercontent.com/8138537/141539885-d7134238-36a3-4bda-af99-027d3215d32e.JPG)

22 raw images, Meshroom settings optimized for quality, 2h reconstruction.

**Comment by Miracle086** [comment]
> This is the reconstruction quality one can achieve in Meshroom with a professionally captured dataset (I used an old sample by https://triplegangers.com/blog/cat/technology/post/free-scan-sample/) without smoothing or post processing:
> 
> ![face1](https://user-images.githubusercontent.com/8138537/141539720-697b0bc5-959e-48c5-a363-2fd42d5c21b7.JPG) ![face2](https://user-images.githubusercontent.com/8138537/141539885-d7134238-36a3-4bda-af99-027d3215d32e.JPG)
> 
> 22 raw images, Meshroom settings optimized for quality, 2h reconstruction.

Do you mean to import the triplegangers for rendering first, and then import it into the meshroom?  Unfortunately, we can only use meshroom for rendering tests.

**Comment by natowi** [comment]
No I was just showing what can be achieved quality wise in Meshroom. Experiment with your capturing setup and the Meshroom parameters. As you can see even with a professional setup there are still some blemishes.

**Comment by Miracle086** [comment]
> No I was just showing what can be achieved quality wise in Meshroom (as I don´t have your dataset). Experiment with your capturing setup and the Meshroom parameters to improve your reconstruction. As you can see even with a professional setup there are still some blemishes.

The photos you posted are really good, how did you adjust the parameters? If it is convenient, can you send a screenshot of the photo you adjusted the parameters of the character's avatar?

**Comment by natowi** [comment]
In Feature extraction you can enable dspsift and increase the describer quality and quantity. In Depthmap set downscale to 1.

**Comment by Miracle086** [comment]
> No I was just showing what can be achieved quality wise in Meshroom (as I don´t have your dataset). Experiment with your capturing setup and the Meshroom parameters to improve your reconstruction. As you can see even with a professional setup there are still some blemishes.



> 在特征提取中，您可以启用 dspsift 并提高描述器的质量和数量。在 Depthmap 中将 downscale 设置为 1。

OK, Thanks for your help to me, I will be try do it.

**Comment by stephahn0916** [comment]
@[Miracle086](https://github.com/Miracle086) Did the setup worked for you?
