### ISSUE TITLE
BSOD on Feature Matching

### ISSUE THREAD

**Issue by grainsoflight** [alicevision/meshroom#1568]
**Describe the bug**
I cannot seem to progress past Feature Matching on 2021.1.0. Whenever it reaches that point, I receive a BSOD error "Paging error in unpaged area." Turning off paging results in a BSOD "Whea uncorrectable error." Upon reboot the project will show it's progress but all nodes will contain no data and the project will need to start from scratch. It seems that I get more progress by disabling "Force CPU" in Feature Extraction, but it will eventually happen after sometime on the Feature Matching node.

**Desktop (please complete the following and other pertinent information):**
 - OS: Win 10 
 - Meshroom version: 2021.1.0
 - Intel i9-9900k
 - 32GB DDR4 3200mhz RAM
 - Nvidia RTX 3060

**Comment by herosnowman** [comment]
Your pc's RAM could be faulty. You could test that using Windows Memory Diagnostics or MemTest86.
