### ISSUE TITLE
CameraCalibration node - how to run?

### ISSUE THREAD

**Issue by jhaggle** [alicevision/meshroom#1570]
**Describe the problem**
I want to run the CameraCalibration node by right clicking it and select compute. See image below. This works fine with the CameraInit node as soon as I dropped some images into meshroom. But what do I need to do in order to run CameraCalibration??

![image](https://user-images.githubusercontent.com/11705343/142882875-8cc7f057-bf33-4665-bc00-6a70d038f41e.png)

**Comment by simogasp** [comment]
In the input field, you need to copy-paste the path to a video or a folder
containing the images.
