### ISSUE TITLE
Multi Camera Rig - wrong number of cameras reconstructed

### ISSUE THREAD

**Issue by jhaggle** [alicevision/meshroom#1571]
I have run the default pipeline, but with 8 cameras organized as a rig.
I finally got it working after reading for example the tips in this link:
https://github.com/alicevision/meshroom/issues/527
When I start the default pipeline and run the first node CameraIinit and then look at cameraInit.sfm everyting looks nice. I got a rig with 8 cameras. HOWEVER, after running the pipeline up to StructureFromMotion and look at the result in the 3D-viewer I get the result in the image below. What is wrong? If I have a rig with 8 cameras, there should only be 8 cameras in the 3D-viewer, right?

![image](https://user-images.githubusercontent.com/11705343/142935486-8922245e-f3e5-406b-8e18-516ab7f4959c.png)

**Comment by fabiencastan** [comment]
Hi,
I'm not sure to understand the problem.
How many images have you used in input?
Do you have a sample scene to share (with few images), so we can discuss on a dataset?

**Comment by jhaggle** [comment]
> Hi, I'm not sure to understand the problem. How many images have you used in input? Do you have a sample scene to share (with few images), so we can discuss on a dataset?

I have a folder named rig with 8 subfolders named 0,1,2,3,4,5,6,7:
![image](https://user-images.githubusercontent.com/11705343/143044715-ef35a583-3c17-4a2b-8394-43baf2954629.png)

Each subfolder contains about 150 images and all images in a subfolder comes from the same camera. For example, the images in folder 0 comes from camera 0, the images in folder 1 comes from camera 1 etc.
![image](https://user-images.githubusercontent.com/11705343/143044977-85368efd-cb10-4de2-8a35-81394104ae1f.png)

All images are of a charucopattern:
![image](https://user-images.githubusercontent.com/11705343/143045208-b520be5e-ecef-4a17-99a5-3418f3347f89.png)

When I look at the file cameraInit.sfm resulting from the first node, I can see that there is a rigId:
![image](https://user-images.githubusercontent.com/11705343/143045642-f7672180-e651-4a13-8178-c53274b34e5e.png)

Also there is is rigs:
![image](https://user-images.githubusercontent.com/11705343/143045724-cc0c269b-1b26-45b9-842a-c19758df7235.png)

As i understand it, this should result in meshroom finding the eight cameras in the rig, and not one camera for each image! (Or whatever is happening.)

**Comment by fabiencastan** [comment]
You will always get one camera per input image.
The only difference is that cameras are sharing the same rig-pose and sharing the same relative pose within the rig.

In this case, it will locate the pose of 150 acquisitions of a rig of 8 cameras.
So 150 rig-pose with 8 relative poses which means 150*8 cameras.

**Comment by jhaggle** [comment]
> 

Ok, so one camera per input image. I can accept that. But ALL images from the same camera (i.e. the same folder) should have the same coordinates and correspond to one of the 8 rig positions, right? But in such case there is something wrong with the image in my first post above since cameras scattered all over, in a lot more than 8 positions. Am I thinking right?
