### ISSUE TITLE
Yet another Nvidia / CUDA driver issue (probably)

### ISSUE THREAD

**Issue by KodiTheDog** [alicevision/meshroom#1575]
Get this failure message on DepthMap ....
[20:03:45.556418][warning] Could not determine number of CUDA cards in this system
[20:03:45.548424][warning] No CUDA-Enabled GPU.
[20:03:45.556418][error] cudaGetDeviceCount failed: CUDA driver version is insufficient for CUDA runtime version
[20:03:45.556418][info] Can't find CUDA-Enabled GPU.
[20:03:45.556418][error] This program needs a CUDA-Enabled GPU (with at least compute capability 2.0).

Been through the previous entries on this and updated the drivers ..
[Display]
Operating System:	Windows 10 Enterprise, 64-bit
DirectX version:	12.0 
GPU processor:		Quadro K2100M
Driver version:		411.63
Direct3D API version:	12
Direct3D feature level:	11_0
CUDA Cores:		576 
Core clock:		666 MHz 
Memory data rate:	3008 MHz
Memory interface:	128-bit 
Memory bandwidth:	48.13 GB/s
Total available graphics memory:	10192 MB
Dedicated video memory:	2048 MB GDDR5
System video memory:	0 MB
Shared system memory:	8144 MB
Video BIOS version:	80.06.7D.00.06
IRQ:			Not used
Bus:			PCI Express x16 Gen3
Device Id:		10DE 11FC 15CC1028
Part Number:		2039 0503

meshroom is explicitly set to use the NVIDIA card in Manage 3D settings (Nvidia control panel)

What did I miss?

**Comment by wasder1234** [comment]
Hello! 
Had same issue with Quadro K1100M. Install latest drivers from NVIDIA! not from your notebook supplier. I did clean install and didn't alter any default settings. It gets worked.

**Comment by KodiTheDog** [comment]
Indeed. I worked through the drivers on the NVIDIA site and the oldest one that worked for me was 418 U9. That seemed to be the critical version. Just so anyone else having the issus has a reference point.
