### ISSUE TITLE
Panorama HDR - list of recommended 360 cameras

### ISSUE THREAD

**Issue by Manopoli** [alicevision/meshroom#1579]
**Describe the problem**
About a month ago I discovered that Meshroom also offers Panorama HDR and Panorama HDR Fisheye pipelines, which obviously is awesome.

When trying out the new HDR pipelines however, I discovered that our Kandao Qoocam 8K 360 camera is not supported due to it having both the lenses in a single image, as I understood it from @fabiencastan. The current version of Meshroom support only one "Fisheye circle" per image, thus our rig (containing 2 lenses per image) can not be used for these pipelines.

I am very much interested in using the HDR pipelines and am willing to purchase a new 360° camera (like the Theta Z1) for this feature. Before I make this purchase however, I need to be absolutely sure that the camera is supported by Meshrooms HDR pipelines. 

So far I have not been unable to find a list of approved 360 cameras. Does anyone know where I can find this?
Thanks in advance!

![Screenshot 2021-12-13 140910](https://user-images.githubusercontent.com/6077108/145821275-680616a8-3319-4c60-b239-e24b89feede3.jpg)

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/issues/1560#issuecomment-993931018
