### ISSUE TITLE
Improve SfM reconstruction

### ISSUE THREAD

**Issue by bgpantojar** [alicevision/meshroom#1581]
After doing a SfM reconstruction, when displaying the features in the image viewer window, it shows 3 "different features". I understand they are the next: 
- The first (blue) are the extracted using the detector algorithm (sift for instance). 
- The second (orange) are those features that were not taken into account in the final reconstruction (but still are tracks).
- The third (red) are those that belong to the structure (final SfM sparse point cloud - reconstructed tracks).

I would like that my reconstruction improves. For that I think that there are some parameters inside the pipeline I could tune to include more of the orange points in the final reconstruction. Could you guide me in the selection of these parameters? The reason I would like to do this is because various of my input images are ignored during the registration of the view.

Some of the parameters I modified already and slightly improve the reconstruction were: 1)Method for imageMatchin: Exhaustive. 2) Describer density and quality in FeatureExtraction: high

Thanks in advance.
Bryan

**Comment by natowi** [comment]
Does this help? https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters
