### ISSUE TITLE
[bug] special caracter in image path causes prepare dense scene to fail 

### ISSUE THREAD

**Issue by JulesDoe** [alicevision/meshroom#1584]
I had an umlaut (ä) in the folder name of the Images. This caused the "PrepareDenseScene" Node to fail with no further information.

**To Reproduce**
1. create image folder with ä in name.
2. select all images in folder
3. drag and drop into meshroom
4. save .mr file and Start.

**Expected behavior**
I would like it to process compleatly. Or to Error out and inform me which characters are exapted.

**Screenshots**

**Log**
- non

**Desktop (please complete the following and other pertinent information):**
 - OS: Win 10
 - Python 3.7.4
 - Qt/PySide sry no idea
 - Meshroom version: 21.1.0

**Additional info**
renaming the folder **and** deleating the by previous steps already generated Data. Fixed the problem.

**Comment by natowi** [comment]
Yes, this is a known issue
