### ISSUE TITLE
[question] Image not reconstructed 

### ISSUE THREAD

**Issue by Khoomn** [alicevision/meshroom#1586]
Hey, so today I had to put down my dog, I took around 52 photos of him in a circular motion to put him into mesh room and make him a 3d asset.  I'm having some problems around the face though. Even though I can clearly tell where this one image is supposed to go, it says it can not reconstruct it. I was wondering if there is a way to manually put in the camera and line it up as I want his face to be there.
![image](https://user-images.githubusercontent.com/20747451/147632783-2789eeeb-814a-4be5-9be9-9bacbba96361.png)
![image](https://user-images.githubusercontent.com/20747451/147632802-8792236c-6c57-419f-9b31-c32b340c771a.png)
![image](https://user-images.githubusercontent.com/20747451/147632877-ee71e84a-3cc5-4243-9508-80996cffee9c.png)

**Comment by simogasp** [comment]
I'm so sorry for you and your friend 😢 It's an original way to remember him/her, though!

My guess is that there is too much displacement between the 3 images and the matching is really difficult between those 3 images. You can try to change the presets of the feature extractor to have more features but if you are using the latest release it should be already the case.
You can visually debug using the plugins (included in the release) to visualize the extracted features and the correctly matched ones. Probably that image has too few (good) matches.

**Comment by simogasp** [comment]
You can also try to use `guided matching` in the matching node, if it manages to find a few good matches it might help in getting some more.

**Comment by Khoomn** [comment]
How would I go about doing the things you said? I just picked up the program yesterday and I don't know how to enable plugins or change the matching mode

**Comment by simogasp** [comment]
In the `FeatureMatching` node you can check the Guided matching case.
https://meshroom-manual.readthedocs.io/en/latest/feature-documentation/nodes/FeatureMatching.html

**Comment by Khoomn** [comment]
> In the `FeatureMatching` node you can check the Guided matching case. https://meshroom-manual.readthedocs.io/en/latest/feature-documentation/nodes/FeatureMatching.html

Which part of the node before and after do i drag guided matching to?

![image](https://user-images.githubusercontent.com/20747451/147739631-abdafc03-0e92-4419-aa29-f6d78734c704.png)

**Comment by Khoomn** [comment]
Ok I'm actually confused about the guided matching now. I started it about 15 minutes ago and its still on the feature matching, it hasn't actually had me do anything to assist it yet and it feels like its taking longer than before. Am I supposed to do something while its on this or do I just leave it as is?

**Comment by simogasp** [comment]
You need to click on the node `FeatureMatching` and then look on the right pane in the attribute list, where you can modify the values. No need to drag anything on the graph.
Mind you, it's gonna take longer to perform the matching with this setting

**Comment by Khoomn** [comment]
> You need to click on the node `FeatureMatching` and then look on the right pane in the attribute list, where you can modify the values. No need to drag anything on the graph. Mind you, it's gonna take longer to perform the matching with this setting

It got through feature matching, I have guided matching on but it still couldn't reconstruct the image. Could I just manually put the image where I know its supposed to be? Or is there nothing else I can really do?

**Comment by simogasp** [comment]
You can try to add Akaze among the features to extract in `FeatureExtraction`, it will again slow down the process but maybe it'll manage to get more reliable matches.
You can also share your dataset if you want, but I won't be able to run it until I get back to my PC mid january.

**Comment by natowi** [comment]
This may also be helpful: https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters

**Comment by Khoomn** [comment]
> You can try to add Akaze among the features to extract in `FeatureExtraction`, it will again slow down the process but maybe it'll manage to get more reliable matches. You can also share your dataset if you want, but I won't be able to run it until I get back to my PC mid january.

I ended up getting the program to use every photo but the face never actually changed and it seemed to make it worse as there are 2 huge holes in his back now. Heres the dataset download if you would like to try to get his face to be there
https://www.mediafire.com/file/bh1o49de95mhyeo/cooper.zip/file
