### ISSUE TITLE
There is no node able to be processed

### ISSUE THREAD

**Issue by dserrill** [alicevision/meshroom#1589]
**Describe the problem**
Hi all, I am pursuing the ability to create solid 3D models using photogrammetry and have chosen Meshroom as a first software trial. Unfortunately I am unable to get past the Meshroom test phase using the monster tree file photos. Several hours of troubleshooting and reviewing similar threads of this problem but no success, still getting ' There is no node able to be processed' error. Advice?   [questiTraceback (most recent call last):   File "d:\release\BUILD\meshroom\meshroom\ui\graph.py", line 384, in execute   File "d:\release\BUILD\meshroom\meshroom\core\taskManager.py", line 192, in compute   File "d:\release\BUILD\meshroom\meshroom\core\taskManager.py", line 368, in raiseImpossibleProcess RuntimeError: [COMPUTATION] Impossible Process: There is no node able to be processed.on]

**Screenshots**

**Dataset**
If applicable, add a link or *few* images to help better understand where the problem may come from.

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ]
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1]
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**

**Comment by natowi** [comment]
Looks like you are starting from source code - in this case AliceVision is missing. Try a Release from: https://github.com/alicevision/meshroom/releases/tag/v2021.1.0

**Comment by dserrill** [comment]
That was the ticket. Thanks very much for your response!

**Comment by geographerwang** [comment]
hi, there , do you solve the problem?  how to solve it?   any suggestion?
