### ISSUE TITLE
[question] Colour space and internal colour rendering pipeline

### ISSUE THREAD

**Issue by Shrinks99** [alicevision/meshroom#1615]
Hi there!  I had a look through your documentation and I was unable to find any information on colour rendering in Meshroom.  I am currently working with EXR files that contain image data in the Red Wide Gamut Log 3G10 colour space.  Unfortunately when I load my EXRs into Meshroom they seem a little washed out which is to be expected if the program thinks they are supposed to be rendered with a linear power function instead of Red's log function.

Most other VFX software seems to use [OCIO](https://opencolorio.org/) to handle these issues by transforming the image into a radiometric-like linear working space where calculations are performed, viewed with a display OETF, and then back out in the user's colour space of choice.  In Meshroom's case, I assume the program does _some_ of this as a part of the texturing workflow but I cannot find if or where these options are exposed to the user as an option when reading in images.

If I have simply missed something please let me know!  Thank you for creating this software, my initial results using it for basic match move work have left me very impressed!

**Desktop:**
 - OS: Win 10
 - Python version 3.7.4
 - Meshroom version: please specify if you are using a release version or your own build
   - 2021.1.0 Release

**Comment by natowi** [comment]
Meshroom uses OIIO, jope this helps: https://github.com/alicevision/QtOIIO

**Comment by Shrinks99** [comment]
OIIO is a great library for reading and writing images and while OIIO and OCIO are [somewhat integrated](https://github.com/OpenImageIO/oiio/pull/200) without OCIO it doesn't really do the things I've described above... As far as I'm aware anyways, I don't have much first hand experience with the library other than using software built with it.

As it stands (to answer my questions above for others that may stumble upon this thread) from my tests, it _seems_ that Meshroom is largely unmanaged right now and your best bet is to convert your non-raw images to sRGB or possibly rec709 before loading them into Meshroom?  I've converted my RWG EXR sequence to a rec709 TIFF sequence and it looks as expected across Meshroom and Nuke.

**Comment by fabiencastan** [comment]
Hi @Shrinks99 ,
Meshroom uses oiio (and it is built with ocio), but there is no way to provide an ocio configuration file for now. Computation is done in linear and display is done in sRGB.
Conversions are done based on the file format information. But there is no way to know the colorspace of your EXR file (without extra information like ocio nomenclature), we only know that it should be linear as it uses floating point values.

**Comment by Shrinks99** [comment]
Thank you @fabiencastan!  This answers my questions :)

**Comment by fabiencastan** [comment]
I see that, contrary to my expectations, the [public builds does not include ocio](https://github.com/alicevision/AliceVision/blob/develop/CMakeLists.txt#L601), (we are using a dedicated build internally).
We will have to fix that for the next release.

**Comment by Shrinks99** [comment]
Would love to see OCIO make its way into the program as a CameraInit attribute.  I don't think Meshroom presently has any global program preference pane where a config could be defined, but being able to choose a file's colour space as a camera intrinsic parameter for my image sequence would have saved me a step here.
