### ISSUE TITLE
[request] Export a lens re-distortion STMap with `ExportAnimatedCamera`

### ISSUE THREAD

**Issue by Shrinks99** [alicevision/Meshroom#1617]
**Is your feature request related to a problem? Please describe.**
I recently used Meshroom to 3D track a shot that had poorly documented camera and lens information.  While my track was very successful, unfortunately no lens distortion grid was shot for this lens and while Meshroom helpfully exports an STMap that allows me to un-distort my footage, I have no means of using this (without some extra work and tools on my end, [don't worry there _are_ solutions to this problem](http://www.andreageremia.it/tutorial_invert_stmap.html)) unless I can re-distort my renders to match my original images and their lens distortion.

**The solution I'd like!**
It would be real helpful if Meshroom could export both a lens un-distortion STMap and a lens re-distortion STMap!  While most CG workflows would properly prefer do this step separately, in situations like mine where that's sadly not an option this would be quite helpful.

I assume this is possible and there's some way of inverting the lens data used to generate the STMap?  Nuke has C_STMap which allows for you to invert it and attempt to inpaint missing areas but that can result in some issues without manual fixes in my experience.

**Comment by fabiencastan** [comment]
Yes! In the develop branch, we now export both Undistort & Distort maps:
https://github.com/alicevision/AliceVision/commit/b272d40b540a304887a94446b61743dd4f34bc81

**Comment by Shrinks99** [comment]
Hey look at that, how nice!  I suppose this issue can be closed once that goes live then ;P

Are there nightly / pre-release builds readily available anywhere?

**Comment by fabiencastan** [comment]
Unfortunately not...

**Comment by Stuartbedford** [comment]
Hi,

When do you imagine this will be in the release?
Also would it be possible to export 32 bit UV maps to improve the quality of the distort?

thanks

**Comment by Shrinks99** [comment]
@Stuartbedford The bit depth issue has apparently been resolved in the dev branch, for more details see #1644

As for when it releases I believe the answer is "when it's ready".

**Comment by Stuartbedford** [comment]
Great thanks for the reply.

**Comment by Shrinks99** [comment]
Meshroom has seen a release and so this should be in now!
