### ISSUE TITLE
Add meshroom_photogrammetry unit test

### ISSUE THREAD

**Issue by fabiencastan** [alicevision/meshroom#162]
`meshroom_photogrammetry -i /tmp/input -o /tmp/output --save "testScene.mg"`

The save option disables the computation, so it will just check the graph creation.

**Comment by simogasp** [comment]
can we also add a `--dry_run` option that just prints out the command lines that will be called?

**Comment by fabiencastan** [comment]
Yes, would be great but in another PR as it's less trivial.
This first test would already check most of the behaviors and avoid to break the command line while improving the UI.
