### ISSUE TITLE
[question]ERROR:root:Error while building intrinsics: CameraInit failed with error code 1.

### ISSUE THREAD

**Issue by BanKeTang** [alicevision/meshroom#1628]
**Describe the problem**
I used Pycharm to open and debug meshroom, aliceVision and plugins which were all pre-built binaries. All I could determine was that the path of sensorDatabase was correct, but when I ran and imported images there was an error. The same error occurs when I package the project as an EXE file to run. Please help me out. I used Python 3.8.1, Qt 5.14.2.

**Screenshots**
![image](https://user-images.githubusercontent.com/4518176/154667640-03eff3e1-81d2-4251-8d2f-3661e833bcd3.png)

**Dataset**
I used dataset_monstree- Master, which I downloaded from the website.

**Log**
C:\Works\meshroom-develop\venv\Scripts\python.exe C:/Works/meshroom-develop/meshroom/ui/__main__.py
WARNING:root:== The following "submitters" plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

WARNING:root:file:///C:/Works/meshroom-develop/meshroom/ui/qml/main.qml:415:21: Unable to assign [undefined] to QFont
Program called with the following parameters:
 * allowSingleView = 1
 * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1,3deanamorphic4,3deradial4,3declassicld"
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:\Users\wooci\AppData\Local\Temp\tmp00ktv7x8/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/viewpoints.sfm"
 * output = "C:/Users/wooci/AppData/Local/Temp/tmp00ktv7x8/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm"
 * sensorDatabase = "C:\Works\meshroom-develop\aliceVision\share\aliceVision\cameraSensors.db"
 * useInternalWhiteBalance = 1
 * verboseLevel = "info"
 * viewIdMethod =  Unknown Type "enum aliceVision::sfmDataIO::EViewIdMethod"
 * viewIdRegex = ".*?(\d+)" (default)

[19:25:23.896217][fatal] 3deanamorphic4
ERROR:root:Error while building intrinsics: CameraInit failed with error code 1.
Command was: "aliceVision_cameraInit  --sensorDatabase "C:\Works\meshroom-develop\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1,3deanamorphic4,3deradial4,3declassicld --useInternalWhiteBalance True --viewIdMethod metadata --verboseLevel info --output "C:/Users/wooci/AppData/Local/Temp/tmp00ktv7x8/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm" --allowSingleView 1 --input "C:\Users\wooci\AppData\Local\Temp\tmp00ktv7x8/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/viewpoints.sfm"".

WARNING:root:QQmlComponent: Created graphical object was not placed in the graphics scene.

Process finished with exit code 0

**Desktop (please complete the following and other pertinent information):**
 - OS: [win 10, osx, ]
 - Python version [3.8.1]
 - Qt/PySide version [5.12.4]
 - Meshroom version: lastest meshroom source code from github
- Binary version [2021.1.0]

**Comment by natowi** [comment]
Is there a reason why you use 3deanamorphic4: Pinhole camera with a 4 anamorphic distortion ?
Default would be pinhole

Other things to check in general:
Do you get this error with the monstree dataset? https://github.com/alicevision/dataset_monstree
Are there any special characters in your paths or file names?

**Comment by natowi** [comment]
"I guess their latest source might not be compatible with the pre-built binary files"
Are you trying to mix the Meshroom source with Alicevision binaries? This will result in errors, as some new features implemented in the latest source is not supported by the prebuild binaries.

You can download Meshroom (including Alicevision) from [here}(https://github.com/alicevision/meshroom/releases/download/v2021.1.0/Meshroom-2021.1.0-win64.zip). In case you want to modify the Meshroom code, use the source files provided with the release. ([Meshroom source](https://github.com/alicevision/meshroom/archive/refs/tags/v2021.1.0.zip), AliceVision binaries are included with the Meshroom release)

**Comment by BanKeTang** [comment]
It works well with the pre-built binaries files now. Thx for the source code.
