### ISSUE TITLE
Why is meshroom exporting so many image textures?

### ISSUE THREAD

**Issue by Logancolon1** [alicevision/meshroom#1639]
I was just wondering if this is supposed to happen. After all of the processing was done, I noticed that my model has a ton of textures. I scrolled to the bottom and I had counted 729 textures! everything about the model looks fine, but when I go to upload a scan to sketchfab as a zip file, it says that the file is too large (because of the 729 textures). Is meshroom supposed to be this way?
![image](https://user-images.githubusercontent.com/100886330/156678097-7113ee5d-d87c-46bc-98bd-2d76b0db1447.png)

**Comment by revisionarian** [comment]
Hi @Logancolon1, I think that you are running the MeshroomCL software, which is different than Meshroom. If so, you should post your question over in the MeshroomCL repository here: https://github.com/openphotogrammetry/meshroomcl/issues. MeshroomCL is known to create a ton of texture files, and the developers over there can probably help you out.

**Comment by Logancolon1** [comment]
Alright! Thanks!
