### ISSUE TITLE
[bug] Lens Distortion ST map artifacts

### ISSUE THREAD

**Issue by Shrinks99** [alicevision/Meshroom#1644]
**Describe the bug**
When using exported undistortion maps I have noticed that they seem to produce some blocky artifacts.  I _suspect_ that this may be due to the fact that it is exported with 16 bit half float precision?  Usually (in my experience anyways) data passes should be processed and exported with 32 bit precision.  Example ST Map that is used in the following screenshots is provided here: [Distortion_UVMap_3725456799.zip](https://github.com/alicevision/meshroom/files/8238677/Distortion_UVMap_3725456799.zip)

As a hacky solution for anyone who is trying to use this program in production right now and can't wait for a fix, this can be worked around by applying a 3-5px blur to the exported ST map.  

**To Reproduce**
1. Export an ST undistortion Map from Meshroom
2. Apply it to an image of the same resolution (I used Nuke here)
3. Zoom in and check for artifacts, typically they will be easiest to spot in the middle of the frame/

**Expected behavior**
The lens distortion is applied without creating artifacts and pixels remain square.

**Screenshots**

Source image:
![Source Image](https://user-images.githubusercontent.com/5672810/158038437-1ee062da-92dc-4ff1-b8e3-e7ec502b86a0.png)

Warped image:
![Warped Example](https://user-images.githubusercontent.com/5672810/158038457-52288484-1ffd-4e0e-b8ac-7a15c86afd11.png)

**Desktop:**
 - OS: Windows 10
 - Python: 3.7.4
 - Meshroom version: 2021.1.0 Release

**Comment by servantftechnicolor** [comment]
Is it possible for you to send the original images, or at least the content of the structurefrommotion node ? (.abc or .sfm).

**Comment by Shrinks99** [comment]
I can't send the original images (NDA) and I deleted the original cache because I finished this shot but I can recompute and send you that data if it's helpful.  Should be able to get around to it this weekend.

**Comment by Shrinks99** [comment]
Recomputed the sequence, can confirm that the undistorted JPEG files Meshroom spits out do not exhibit this issue.

![Screenshot 2022-03-19 221306](https://user-images.githubusercontent.com/5672810/159145114-3961c802-abde-4cf8-ae9a-ee59eaddd4d7.png)

Unfortunately the point cloud generated by the StructureFromMotion node contains sensitive data that I cannot post publicly.  Fortunately, this issue should be replicable with any other image sequence.

**Comment by servantftechnicolor** [comment]
Thanks for the details. This issue is solved in a development branch. This should be merged with the next release.

**Comment by Shrinks99** [comment]
This issue is still present, is still a bug, and should be closed once the next version comes out.  I dislike bots that perform these actions :P

**Comment by Shrinks99** [comment]
Pretty sure this has been fixed now?

**Comment by earlywill** [comment]
Seeing the issue in Meshroom 2023.3.0 with `ExportDistortion` node. 

But looks like addressed month ago here https://github.com/alicevision/AliceVision/pull/1677

![stmapmeshroom](https://github.com/alicevision/Meshroom/assets/33976398/5efc290d-6a47-45ad-975f-20db0676b265)

**Comment by fabiencastan** [comment]
Yes exactly. I missed to link it with this issue.

**Comment by Shrinks99** [comment]
@fabiencastan No worries, glad to see this put to bed!  Blur hack was good enough at the time, shots got finaled! :)
