### ISSUE TITLE
Missing documentation and labeling on CameraInit Distortion Parameters

### ISSUE THREAD

**Issue by Phoenix-64** [alicevision/Meshroom#1647]
I computed the brown distortion conditions k1 k2 k3 p1 p2 with an OpenCV script and want to use them in Meshroom but i dont know what parameter is corresponding to what.
If the Camera Type in the CameraInit is set to brown and I add 5 distortion parameters they are only labeled 0 trough 4 and not with the brown coefficients labels k1 k2 k3 p1 and p2 do I just have to enter them in this order or did I miss something completely?
Thanks for helping.

![grafik](https://user-images.githubusercontent.com/52720948/158689195-6af5bda1-2993-4e33-91fe-b76b54efef0f.png)

**Comment by natowi** [comment]
Distortion Parameters:
0 - k1
1 - k2
2 - k3
3 - p1
4 - p2
