### ISSUE TITLE
How do I resume my project after recovering the progress from the cache?

### ISSUE THREAD

**Issue by Asah935** [alicevision/meshroom#1662]
**Describe the problem**
This was my first attempt with Meshroom so I do not know what to look for. A project was almost done when my PC lost power for a few seconds when the powerstrip was bumped. I have recovered the project as far as I can tell and I don't know how to restart from the same point. All pictures and nodes are accounted for with the same nodes showing green and the Meshing node still orange. Although the Meshing node says RUNNING in the status, the Task Manager is empty and the CPU usage is not as high as it was when I knew the project was running. When I click Start at the top of the screen, a window pops up saying "There is no node to be processed". I made no changes to the project before I began, all I did was drag in the folder of pictures and click start. Any clear steps to resume are desperately appreciated.

Before the power loss
![Screenshot](https://user-images.githubusercontent.com/8138537/161446833-037a2a6d-f438-46be-a805-2ed4463b5786.png)

Now
![Screenshot](https://user-images.githubusercontent.com/8138537/161446872-beed630b-e78e-4ced-8607-57964028c56f.png)

**Desktop (please complete the following and other pertinent information):**
 - OS: Windows 10
 -Meshroom 2021.1.0

**Comment by natowi** [comment]
Try clearing the pending status for the Meshing (and following) nodes:
![grafik](https://user-images.githubusercontent.com/8138537/161446382-a494327b-f011-4c79-8c05-309e446c0ee2.png)

**Comment by Asah935** [comment]
Thanks, that worked. And yeah, I knew I had way more than needed, but I didn't have a quick way to preserve the angles while reducing the images so I just imported a portion of what I had and let it fly. I erred on the side of too many since my only other attempt of a much simpler object had too few. I will definitely take that step in the future.
