### ISSUE TITLE
Meshroom input sfm file doesn't exist

### ISSUE THREAD

**Issue by 12wfhe** [alicevision/meshroom#1666]
Hello everyone, I am new in Meshroom. When I started to transform images into mesh, an error apperared, it said the  input sfm file doesn't exist. The complete log is as follows:
Program called with the following parameters:
 * allowSingleView = 1
 * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1"
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "D:/Studium/6.Semester/Tutor_Fachgebiegt_Geb?udelehre/Tutorial/MeshroomCache/CameraInit/ee8d2707ee94d78eda1836aa341311bb3a2182b3//viewpoints.sfm"
 * output = "D:/Studium/6.Semester/Tutor_Fachgebiegt_Geb?udelehre/Tutorial/MeshroomCache/CameraInit/ee8d2707ee94d78eda1836aa341311bb3a2182b3/cameraInit.sfm"
 * sensorDatabase = "D:\Meshroom-2021.1.0\aliceVision\share\aliceVision\cameraSensors.db"
 * useInternalWhiteBalance = 1
 * verboseLevel = "info"
 * viewIdMethod =  Unknown Type "enum aliceVision::sfmDataIO::EViewIdMethod"
 * viewIdRegex = ".*?(\d+)" (default)

[17:56:28.430017][error] The input sfm file doesn't exist.

Thanks you for answering.

**Comment by natowi** [comment]
Geb?udelehre

Umlaute are not supported in paths

**Comment by 12wfhe** [comment]
Thanks Simon. I have fixed it.
