### ISSUE TITLE
any plans for a 2022 release?

### ISSUE THREAD

**Issue by nafergo** [alicevision/Meshroom#1667]
Any plans for a 2022 release?

**Comment by natowi** [comment]
As you can see here, the 2022.1.0 release is on track: 
https://github.com/alicevision/meshroom/milestone/13
https://github.com/alicevision/AliceVision/milestone/33

So yes, a 2022 release is planned, but no release date is set. There will be a release when it is ready.

**Comment by bilinxing** [comment]
2022 is coming to an end😁
