### ISSUE TITLE
sfmTransform a mesh with cctag3

### ISSUE THREAD

**Issue by flobotics** [alicevision/meshroom#1676]
hi, 

Is 0000.pdf == marker-id=0 ??  

i printed 4 cctag3 markers and fastened them on a 1cm thick wooden-board. The markers are in a square and the distance is 20cm from each marker-center.
![IMG_20220425_014504](https://user-images.githubusercontent.com/11964445/165002123-9466fba9-eccb-4db0-a933-faf0d3fff9d9.jpg)

Now i placed the wooden-board on the floor under a table and took some pictures. 

Now i put in the pictures into meshroom and run it till "structureFromMotion"-node.

Now i add a "sfmTransform"-node after the "structureFromMotion"-node and add these values

<img width="657" alt="sfmtransform-1" src="https://user-images.githubusercontent.com/11964445/165002299-30c1066a-4e11-4ed1-8a93-2f62a2b495bd.PNG">

<img width="659" alt="sfmtransform-2" src="https://user-images.githubusercontent.com/11964445/165002304-cdedd249-3736-4fe2-9230-dcca34d41533.PNG">

I set "Additional Scale" to "2" , because "1" = 100mm.   And i placed the markers 20 cm away from each other. So is this correct ?

Then i used only "1" in the "Coord"-values of each marker ?  Is this correct then ?

---

When i run now the "sfmTransform"-node and watch the result in "3d-view" it looks like this
<img width="803" alt="sfmtransform-3" src="https://user-images.githubusercontent.com/11964445/165002465-b0e023e9-07fa-4223-82c3-da128fd13b26.PNG">

<img width="896" alt="sfmtransform-4" src="https://user-images.githubusercontent.com/11964445/165002475-975f59f4-4165-4f8d-8098-0e78aea12ddf.PNG">

Not bad , but the "brown"-part of the point-cloud should be on the "green"-axis , because it is the floor.

Also it is not correctly at zero-position, is this because the wooden-board is 1-cm in height and i put in the wrong values in the "Coord"-section of "sfmTransform"-node ?

thx for help

P.S. Would be nice to have one pdf directly with 4 or more markers placed on it . Also directly having a center-point in the pdf-markers for measuring the distance between them, would be nice.  Also having the marker-id, e.g. at the outer-circle, in the pdf,  would be nice.    nice,nice,nice :)

**Comment by flobotics** [comment]
sorry, in the https://github.com/alicevision/CCTag/blob/develop/markersToPrint/generators/generate.py  you can use --addId  and --addCross  to generate markers with a cross in the center and a ID printed in the corner.

Putting 4 or perhaps more on one PDF would be nice.

**Comment by flobotics** [comment]
i extended the code to generate 4 markers on one sheet

With the commandline:   python3 generate.py --rings=3 --outdir=/tmp --addCross --addId --radius=120 --margin=50 --equalDistance=250 --fourMarkers --generatePdf

it produces:
![ScreenshotCCtagFourMarkers](https://user-images.githubusercontent.com/11964445/165124264-99ae7802-244b-40b7-8fbc-1d56cff6a06e.png)




`#!/usr/bin/env python3

import argparse
import os

import svgwrite

from svglib.svglib import svg2rlg
from reportlab.graphics import renderPDF, renderPM

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='Generate the svg file for the markers.')
    parser.add_argument('--rings', metavar='N', type=int, default=3, choices=[3, 4],
                        help='the number of rings (possible values {%(choices)s}, default: %(default)s)')
    parser.add_argument('--outdir', metavar='dir', type=str, default='./',
                        help='the directory where to save the files (default: %(default)s)')
    parser.add_argument('--margin', metavar='N', type=int, default=400,
                        help='the margin to add around the external ring (default: %(default)s)')
    parser.add_argument('--radius', metavar='N', type=int, default=500,
                        help='the radius of the outer circle (default: %(default)s)')
    parser.add_argument('--addId', action='store_true',
                        help='add the marker id on the top left corner')
    parser.add_argument('--addCross', action='store_true',
                        help='add a small cross in the center of the marker')
    parser.add_argument('--generatePng', action='store_true',
                        help='also generate a png file')
    parser.add_argument('--generatePdf', action='store_true',
                        help='also generate a pdf file')
    parser.add_argument('--whiteBackground', action='store_true',
                        help='set the background (outside the marker) to white instead of transparent')
    #add argument to add id at the outer ring
    parser.add_argument('--addIdOuter', action='store_true',
                        help='add the marker id on the outer ring')
    #add arg for equal_distance
    parser.add_argument('--equalDistance', metavar='N', type=int, default=250,
                        help='equal distance between markers')
    #add arg to choose 4 markers on one sheet
    parser.add_argument('--fourMarkers', action='store_true',
                        help='choose 4 markers on one sheet')

    args = parser.parse_args()

    # size of the marker (ie the diameter)
    size = 2 * args.radius
    scale = args.radius / 100

    # size of the image, diameter + margin
    width = size + args.margin
    height = size + args.margin

    # id of the first marker
    markerId = 0

    # font size for the id
    font_size = int(0.037 * height)

    # center of the marker
    center = (width / 2, height / 2)

    radius = args.radius

    # create out directory if it does not exist
    if args.outdir and not os.path.isdir(args.outdir):
        os.makedirs(args.outdir)

    if args.rings == 3:
        input_file = 'cctag3.txt'
    else:
        input_file = 'cctag4.txt'

    # if not fourMarkers
    if not args.fourMarkers:

        with open(input_file) as f:

            for line in f:

                # name of the output file
                base_filename = os.path.join(args.outdir, str(markerId).zfill(4))
                out_filename = base_filename + '.svg'

                # create the svg
                dwg = svgwrite.Drawing(out_filename, profile='tiny', size=(width, height))
                if args.whiteBackground:
                    dwg.add(dwg.rect(insert=(0, 0), size=('100%', '100%'), rx=None, ry=None, fill='white'))
                # print the id of the marker if required
                if args.addId:
                    dwg.add(dwg.text(text=str(markerId), insert=(5, 50), font_size=font_size))

                # print the outer circle as black
                dwg.add(dwg.circle(center=center, r=size / 2, fill='black'))

                fill_color = 'white'
                count = 0
                # each value of the line is the radius of the circle to draw
                # the values are given for a marker of radius 100 (so scale it accordingly to the given size)
                for r in line.split():
                    radius = int(r)
                    # print(r)
                    dwg.add(dwg.circle(center=center, r=scale * radius, fill=fill_color))
                    if fill_color == 'white':
                        fill_color = 'black'
                    else:
                        fill_color = 'white'
                    count = count + 1

                # sanity check
                if args.rings == 3:
                    assert count == 5
                else:
                    assert count == 7

                if args.addCross:
                    # print a small cross in the center
                    dwg.add(dwg.line(start=(center[0] - 10, center[1]), end=(center[0] + 10, center[1]), stroke="gray"))
                    dwg.add(dwg.line(start=(center[0], center[1] - 10), end=(center[0], center[1] + 10), stroke="gray"))

                # get the actual radius of the outer ring



                dwg.save(pretty=True)

                if args.generatePng or args.generatePdf:
                    drawing = svg2rlg(out_filename)
                    if args.generatePdf:
                        renderPDF.drawToFile(drawing, base_filename + ".pdf")
                    if args.generatePng:
                        renderPM.drawToFile(drawing, base_filename + ".png", fmt="PNG")

                markerId = markerId + 1

    # if fourMarkers
    else:

        # size of the image, diameter + margin
        width = size*2 + args.margin*2
        height = size*2 + args.margin*2

        ## generate 4 markers on one sheet
        with open(input_file) as f:

            # get line count
            line_count = 0
            for line in f:
                line_count = line_count + 1

            # reset the file
            f.seek(0)

            #read 4 lines and check if read was ok
            while line_count:
                line_count = line_count - 4
                lines = []
                for i in range(4):
                    lines.append(f.readline())
                if len(lines) != 4:
                    print("Error: not enough lines in the input file")
                    exit()



                # get 4 lines
                # lines = [f.readline() for i in range(4)]


                # create 4 center points for the markers in a square
                center_points = [(width/2-(args.equalDistance/2), height/2-(args.equalDistance/2)), \
                                (width/2+(args.equalDistance/2), height/2-(args.equalDistance/2)), \
                                (width/2-(args.equalDistance/2), height/2+(args.equalDistance/2)), \
                                (width/2+(args.equalDistance/2),height/2+(args.equalDistance/2))]


                # name of the output file
                base_filename = os.path.join(args.outdir, str(markerId).zfill(4))
                out_filename = base_filename + '.svg'
                # create 1 svg with 4 markers
                dwg = svgwrite.Drawing(out_filename, profile='tiny', size=(width, height))


                # draw the 4 markers
                for i in range(4):

                    # # create the svg
                    # dwg = svgwrite.Drawing(out_filename, profile='tiny', size=(width, height))
                    if args.whiteBackground:
                        dwg.add(dwg.rect(insert=(0, 0), size=('100%', '100%'), rx=None, ry=None, fill='white'))


                    # print the outer circle as black
                    dwg.add(dwg.circle(center=center_points[i], r=size / 2, fill='black'))

                    fill_color = 'white'
                    count = 0
                    # each value of the line is the radius of the circle to draw
                    # the values are given for a marker of radius 100 (so scale it accordingly to the given size)
                    for r in lines[i].split():
                        radius = int(r)
                        # print(r)
                        dwg.add(dwg.circle(center=center_points[i], r=scale * radius, fill=fill_color))
                        if fill_color == 'white':
                            fill_color = 'black'
                        else:
                            fill_color = 'white'
                        count = count + 1

                    # print the id of the marker if required, to the center of the marker with black font color
                    if args.addId:
                        dwg.add(dwg.text(text=str(markerId), insert=(center_points[i][0], center_points[i][1]), font_size=font_size*2, fill='black'))

                    markerId = markerId + 1

                    # draw the center crosses for the 4 markers in the center_points
                    if args.addCross:
                        for i in range(4):
                            dwg.add(dwg.line(start=(center_points[i][0] - 10, center_points[i][1]), end=(center_points[i][0] + 10, center_points[i][1]), stroke="gray"))
                            dwg.add(dwg.line(start=(center_points[i][0], center_points[i][1] - 10), end=(center_points[i][0], center_points[i][1] + 10), stroke="gray"))


                    # sanity check
                    # if args.rings == 3:
                    #     assert count == 5
                    # else:
                    #     assert count == 7

                #save the svg
                dwg.save(pretty=True)

                if args.generatePng or args.generatePdf:
                    drawing = svg2rlg(out_filename)
                    if args.generatePdf:
                        renderPDF.drawToFile(drawing, base_filename + ".pdf")
                    if args.generatePng:
                        renderPM.drawToFile(drawing, base_filename + ".png", fmt="PNG")`

**Comment by flobotics** [comment]
i printed them, after measuring the distance it is 8,85cm between the markers. I took some photos and run it through meshroom and added a "sfmTransform"-node after sfm-node, and it nearly works.  Nice, if you only need to print and use them.

The only thing which is "wrong" is the axis where the floor is . The brown-part is the floor, so it should be on the green-axis, or ?  

<img width="1090" alt="sfmtransform-5" src="https://user-images.githubusercontent.com/11964445/165144144-ed9042ce-c359-4e25-b3ef-6fb03babcb9c.PNG">

What do i wrong?

**Comment by flobotics** [comment]
hmm, as i dont get it to align right with changing x,y,z values for each marker in sfmTransform-node.  Would it not be cool to have some options e.g. to say "four markers with id=[0,1,2,3]" are a wall, or floor, ceiling, etc. to set the transform ?

Or, perhaps, also a 3d-control option (like the one to 3d-control the stuff in 3d-viewer). You set in the attribute-view what four-markers you want to use (e.g. one-sheet-marker-0-3) , then you coursly move the sfm to the position you like. Then watch in the attribute-view, what values have changed, and do a fine-tuning of these values ?

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/wiki/CCTAG-scaling --> Section: "Using multiple markers for scaling and orientation"

**Comment by flobotics** [comment]
thx, it works
