### ISSUE TITLE
Texturing Step error Meshroom V2021.1.0

### ISSUE THREAD

**Issue by Endvad** [alicevision/meshroom#1695]
Hello, I have a problem with the Texturing Step, all works except this step, i have no idea why it doesn't work.

![image_2022-05-23_182859107](https://user-images.githubusercontent.com/39588134/169865517-9ba6ee2c-f2fb-401f-bffe-60952734ff5b.png)

Desktop
 - OS: Windows 10
 - Meshroom version: Last
 - Ryzen 5 3600
 - Gtx 980
 - 16 Go Ram 3200Mhz
[log.log](https://github.com/alicevision/meshroom/files/8756394/log.log)

**Comment by natowi** [comment]
Abnormal program termination: memory exhausted

-> you don´t have enough Ram to finish.

Reduce the Texture Side and/or increase the Downscale factor

**Comment by Endvad** [comment]
Okay thanks, I will test that !

**Comment by Endvad** [comment]
Thanks a lot, it's worked !
