### ISSUE TITLE
Alembic crash when loading in Blender

### ISSUE THREAD

**Issue by verbal007** [alicevision/meshroom#170]
Having the ability to bring the cameras + images into Blender would be priceless for touching up and correcting geometry and texture of a scanned model. Was curious to see how far the Alembic files would take me towards this goal, but...

Loading the files crash Blender. I've tested other alembic files (60GB animated geometry) and it works ok... but not these scenes.

Curious if these Alembic files have been tested at all with Blender yet.

Attached is one of my Alembic .abc files. Using the file location shown in the "Meshroom: Open Source 3D Reconstruction Software" demo video at 2:43. 
[sfm.abc.zip](https://github.com/alicevision/meshroom/files/2268057/sfm.abc.zip)

**Comment by verbal007** [comment]
@simogasp , thanks for checking this out. I initially tried the file on two different computers that are both running Manjaro w/ Blender 2.79b.  I also *just* tried it again on a Windows 10 partition that is running 2.79 and it crashed there too.

**Comment by fabiencastan** [comment]
@verbal007 Can you make a bug report on Blender?

**Comment by verbal007** [comment]
@fabiencastan , No problem.  I will set myself a reminder for next week. I'm prepping some stuff for Siggraph... and... yeah, running/ran out of time... and haven't used Blender's bug system yet... so will probably take me longer than norm.

**Comment by brothermechanic** [comment]
Same for me with blender-2.79b and blender-2.79.6 (git) (with Meshroom 2018.1.0 (2018/08/09) sfm file)
@verbal007 how to progress with your bugreport , do you have a patch for blender ?

**Comment by natowi** [comment]
Solved by #460

**Comment by brothermechanic** [comment]
no, it import only one camera
very poor functions
alembic is better

**Comment by natowi** [comment]
@brothermechanic you can use [meshroom2blender ](meshroom2blender) to import camera views.

**Comment by brothermechanic** [comment]
of course
i check it and write my post above

**Comment by natowi** [comment]
With Blender 2.8 (Nightly) it no longer crashes when importing alembic files from Meshroom, but there are still some problems with the views.
![blend](https://user-images.githubusercontent.com/8138537/57320088-63ce9d80-70fe-11e9-9e03-e251da038249.JPG)
