### ISSUE TITLE
Can’t save project with name of a folder?

### ISSUE THREAD

**Issue by AFWSI** [alicevision/meshroom#174]
Is this a bug? I created a main folder for my meshroom project. Within that folder, I created a folder for pictures and tried to save the project as the same name as the folder. Instead of saving, it entered the folder with the same name.

**Comment by yann-lty** [comment]
I think this is the default behavior of Windows' default save dialog (and something we don't control on Meshroom side). You can explicitly add Meshrom ".mg" extension to the project name to make it understand you want to save the project file, not enter the subfolder.

**Comment by AFWSI** [comment]
OK, at least it’s not a bug. Kind of annoying ,but have to remember when I go to naming my folder and projects. I didn’t think about adding the “.mg” extension. I will try that and see if it happens to work.

**Comment by yann-lty** [comment]
Thanks for your reply, I'm closing this issue as it is not a Meshroom bug.
