### ISSUE TITLE
Can´t drag from the node points

### ISSUE THREAD

**Issue by juangea** [alicevision/meshroom#176]
I´m trying to connect a point from a node to a different point in a different node but I´m not being able to drag the "cable" to connect both of them

Should I press some key or something to be able to connect two nodes?

Cheers!

**Comment by simogasp** [comment]
Normally you should use a right click to remove the link between nodes (if you need to do that).
Then to connect two nodes, just click on the white circle/square representing the parameter and drag it to the other parameter you want to connect.

**Comment by juangea** [comment]
The problem was that for some reason the circles were not lighting up in white, so I was not able to drage the connector, after a while it came back and I were able to connect two nodes.

Thanks!
