### ISSUE TITLE
Can we use markers to help in the reconstruction / alignment?

### ISSUE THREAD

**Issue by juangea** [alicevision/meshroom#177]
Hi there.

To do a big scene reconstruction with as much precission as possible, can we use some markers that we can place in the space to help with the reconstruction later?

Cheers.

**Comment by natowi** [comment]
Yes. To scale a model, you can import your model in Meshlab and use your markers and known distances.

**Comment by Eric-Lotze** [comment]
Doing some thread necromancy here, can STag Markers be used?

**Comment by fabiencastan** [comment]
What do you mean by STag?

In the development branch, we can now use CCTag markers to define the coordinate system of the reconstruction.

**Comment by Eric-Lotze** [comment]
I can use that then.  I am VERY armchair in the feild, and am new to
meshroom, but when digging for tracking markers i found a paper on a new
one called "STag" that is supposedly one of the best.  GRANTED for
stationary use (ie not AR/MR/VR or motion capture), near anything can work
i guess?

**Comment by natowi** [comment]
@Eric-Lotze in meshroom only CCTAGs are supported. If you need other markers, you would need to implement them yourself.

**Comment by simogasp** [comment]
the code is here
https://github.com/bbenligiray/stag
this fork has everything necessary to build
https://github.com/dartmouthrobotics/stag
