### ISSUE TITLE
[question] how can i get Projection Matrix ?

### ISSUE THREAD

**Issue by ByungHyun21** [alicevision/meshroom#1773]
this is my data

### Camera info
< cameras.sfm >

        {
            "viewId": "515892622",
            "poseId": "515892622",
            "intrinsicId": "3952687073",
            "resectionId": "28",
            "path": "D:\/VariousCar\/image20M\/000000014109.jpg",
            "width": "3840",
            "height": "2160",
            "metadata": {
                "AliceVision:useWhiteBalance": "1",
                "ResolutionUnit": "none",
                "XResolution": "1",
                "YResolution": "1",
                "jpeg:subsampling": "4:2:0",
                "oiio:ColorSpace": "sRGB"
            }
        },

**viewId = poseId = 515892622
intrinsicId = 3952687073
width = 3840, height = 2160**
### Transform matrix
        {
            "poseId": "515892622",
            "pose": {
                "transform": {
                    "rotation": [
                        "0.65733950373107908",
                        "0.2795359293539032",
                        "-0.69983172336985999",
                        "-0.25914178293195705",
                        "0.95587190317273873",
                        "0.13839957031643099",
                        "0.70763713382879023",
                        "0.090380135678012383",
                        "0.70077180158836228"
                    ],
                    "center": [
                        "0.36200976311954958",
                        "-0.067715034780622796",
                        "0.70427057366735701"
                    ]
                },
                "locked": "0"
            }
        },

**R = (3x3 matrix)
[ 0.65733950373107908, -0.25914178293195705, 0.70763713382879023]
[ 0.2795359293539032, 0.95587190317273873, 0.090380135678012383]
[ -0.69983172336985999, 0.13839957031643099, 0.70077180158836228]
 *
C = (3x1 Vector)
[0.36200976311954958]
[-0.067715034780622796]
[0.70427057366735701]
 *
so, t = -RC 
t = (3x1 Vector)
[-0.75387912]
[-0.10011991]
[-0.23081531]
 *
i will call [R|t] as T (Transform matrix)
T = (4x4 matrix)
[ 0.65733950373107908, -0.25914178293195705, 0.70763713382879023 -0.75387912]
[ 0.2795359293539032, 0.95587190317273873, 0.090380135678012383 -0.10011991]
[ -0.69983172336985999, 0.13839957031643099, 0.70077180158836228 -0.23081531]
[ 0 0 0 1]**

### Intrinsic
and this is my intrinisc

    "intrinsics": [
        {
            "intrinsicId": "3952687073",
            "width": "3840",
            "height": "2160",
            "sensorWidth": "-1",
            "sensorHeight": "-0.5625",
            "serialNumber": "D:\/VariousCar\/image20M",
            "type": "radial3",
            "initializationMode": "unknown",
            "pxInitialFocalLength": "-1",
            "pxFocalLength": "2842.2085240265769",
            "principalPoint": [
                "1916.3270083815435",
                "1058.1218808240308"
            ],
            "distortionParams": [
                "-0.039093726085364995",
                "0.17575681078070138",
                "-0.18121865139221041"
            ],
            "locked": "0"
        }
    ],

**f = 2842.2085
cx = 1916.3270
cy = 1058.1218
 *
K = (3x3 matrix)
[f 0 cx]
[0 f cy]
[0 0 1]**

### parsing point cloud
and i parse point cloud from "sfm.ply" except [0 255 0] color

**

  ply
  format ascii 1.0
  element vertex 546289
  property float x
  property float y
  property float z
  property uchar red
  property uchar green
  property uchar blue
  end_header
   -1.72249 -0.638394   1.34485 0 255 0 -> i think this is camera position
   -2.43947 -0.714306   1.39105 0 255 0
...
-4.48241 -1.00212  2.65313 180 178 181 -> i think this is point cloud position
-3.96914 -0.75441  2.25534 152 146 146
-4.75828 -1.20515   2.9993 136 135 133
 -4.40906 -0.682589    1.6348 83 89 77

**from "sfm.ply", i can get these
*
point cloud = [nx3 matrix]
[-4.48241 -1.00212  2.65313 ]
[-3.96914 -0.75441  2.25534 ]
[-4.75828 -1.20515   2.9993 ]
[-4.40906 -0.682589  1.6348]** 

### Projection

p_2d = K * T * [point cloud]
or
p_2d = K * inv(T) * [point cloud]

i try both T and inv(T), but both result is not correct

can you catch what i done wrong?

**Comment by ByungHyun21** [comment]
i find my bug.. 

hahaha...

**Comment by auger1** [comment]
Please where is your bug?
