### ISSUE TITLE
Windows Defender prevents from opening the Windows executable

### ISSUE THREAD

**Issue by steren** [alicevision/meshroom#178]
Windows Defender SmartScreen forbids me from executing the Meshroom executable.

I guess it is because it is of unknown editor.
I am not sure what can be done, maybe sign the binary?

**Comment by simogasp** [comment]
I think you can add an exception for the executables.

https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-defender-antivirus
