### ISSUE TITLE
how to package release

### ISSUE THREAD

**Issue by kk518** [alicevision/Meshroom#1795]
**Describe the problem**
hi，my friend , I succseefully git the code and run in my Pycharm ,now I want to package release to our classmate ,what should can i do?

**Screenshots**

**Dataset**
If applicable, add a link or *few* images to help better understand where the problem may come from.

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ]
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1]
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**

**Comment by natowi** [comment]
First of all - Meshroom consists of a few components you need if you want to build it from source (Meshroom for the GUI, AliceVision for the "backend" CLI that is doing the actual heavy lifting and a few helper plugins: -qmlAlembic,QtOIIO,QtAliceVision)

If you just want to develop on the Meshroom/GUI part, I´d recommend to download the source code that is attached to a current release and work with that. This way you can avoid building AliceVision and the plugins, which can be tricky. If you feel confident building all components, you can find the build info in the corresponding repositories.

Here is a quick start for the "simple" solution of just building the Meshroom part from source:
Download the (official Build)[https://github.com/alicevision/Meshroom/releases/download/v2021.1.0/Meshroom-2021.1.0-win64.zip] - we´ll use parts of it later.

--

Python should be set up properly (added to system PATH)

Clone meshroom to a local directory using git or by downloading a clone from (Github)[https://github.com/alicevision/Meshroom/archive/refs/tags/v2021.1.0.zip] (extract zip to C:\meshroom)

start cli

git clone https://github.com/alicevision/meshroom.git C:\meshroom

navigate to extracted folder

cd C:\meshroom

set python PATH:

set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

Install dependencies

pip install -r requirements.txt -r dev_requirements.txt --timeout 45

Build Meshroom UI

python setup.py build

----

Now we want to put everything together:

replace the contents from your "build" folder in the prebuild folder

# Meshroom standalone structure

- Meshroom/
   - aliceVision/
       - bin/    # runtime bundled binaries (windows: exe + libs, unix: executables)
       - lib/    # runtime bundled libraries (unix: libs)
       - share/  # resource files
           - aliceVision/
               - COPYING.md         # AliceVision COPYING file
               - cameraSensors.db   # sensor database
               - vlfeat_K80L3.tree  # voctree file
   - lib/      # Python lib folder
   - qtPlugins/
   Meshroom    # main executable
   COPYING.md  # Meshroom COPYING file
"""

You could use an "installer creator tool" to package the Meshroom binaries, but that is not necessary. It can be used like a "portable" installation.

Hope this helps.

**Comment by jornare** [comment]
It would be really nice if this could be automated in ci, so that one could always get nightly releases. Seeing the amount of development happening here, it's a shame that last release was 2 years ago.

**Comment by natowi** [comment]
It is a little bit hidden, as it is still under development until the official release, but you can have a sneak peek here: https://ci.appveyor.com/project/AliceVision/meshroom/builds/46255780/artifacts

**Comment by jornare** [comment]
I have tried this, but it has some dependencies that are hard to find a working build/version of. QTAliceVision for instance.

**Comment by natowi** [comment]
I think we can close this issue now.

If someone is looking on how to package Meshroom into an installer, read on here: https://github.com/natowi/Meshroom-Installer
