### ISSUE TITLE
meshroom_batch change FeatureExtraction:describerTypes syntax 

### ISSUE THREAD

**Issue by Dev-hestabit** [alicevision/Meshroom#1797]
Using the command line tool "meshroom_batch" I am able to override parameters like the "forceCpuExtraction" successfully like this:

./meshroom_batch -i /input -o /output --paramOverrides FeatureExtraction:forceCpuExtraction=0

If I wantet o override the "describerTypes" to sift + akaze (for example) as well I tried something like this:

./meshroom_batch -i /input -o /output --paramOverrides FeatureExtraction:forceCpuExtraction=0 FeatureExtraction:describerTypes=sift,akaze

This does not work. The error message I get is the following:

ValueError: ChoiceParam value "s" is not in "['sift', 'sift_float', 'sift_upright', 'dspsift', 'akaze', 'akaze_liop', 'akaze_mldb', 'cctag3', 'cctag4', 'sift_ocv', 'akaze_ocv']".

So obviously the syntax I use to assign the two types via command line is incorrect.
Any help on the correct syntax would be appreciated.

I am running on Linux (arch) with the latest version of meshroom (2021.1.0)

**Comment by mugulmd** [comment]
Hey @Dev-hestabit, thanks for reporting this!

Unfortunately after looking at the source code it looks like what you're trying to achieve here (passing multiple values to a non-exclusive ChoiceParam from the command line) is currently not supported, so there's no correct syntax (at least to my knowledge).

I'll see if I can fix this!

**Comment by Dev-hestabit** [comment]
I have fix this issue by changing the FeatureExtraction, Feature Matching and Structured for motion .pyc file with the git .py file and changes the default value from dspsift to sift,akaze and without passing any paramOverrides it works exactly with command line that i want it to using command line

**Comment by Dev-hestabit** [comment]
Is there anyway apart from CCtag for scaling 3d model to its real life size?

**Comment by mugulmd** [comment]
> Is there anyway apart from CCtag for scaling 3d model to its real life size?

Sorry I'm not sure I see how this is related to this issue..
