### ISSUE TITLE
couldn't load SfM

### ISSUE THREAD

**Issue by vrue360** [alicevision/meshroom#180]
I success the build of qmlAlembic and link the meshroom, so there is SfM UI in meshroom but SfM can't load. It has infinit loading.

What can I do?

===============log============

Microsoft Windows [Version 10.0.17134.191]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\user>cd c:\project\meshroom

c:\project\meshroom>set PYTHONPATH=%CD% && python meshroom/ui
Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, ExportUndistortedImages, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[2018-08-10 13:36:07,909][WARNING] == The following plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

QObject::setParent: Cannot set parent, new parent is in a different thread
Failed to download scene at QUrl("")
Program called with the following parameters:
 * allowIncompleteOutput = 1
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraModel = 2 (default)
 * imageFolder = "" (default)
 * input = "C:\Users\user\AppData\Local\Temp\tmpjlkg4vbj/CameraInit/2731003bd822aa3d98acd3185af7e6a65750fcd4//viewpoints.sfm"
 * output = "C:/Users/user/AppData/Local/Temp/tmpjlkg4vbj/CameraInit/2731003bd822aa3d98acd3185af7e6a65750fcd4/cameraInit.sfm"
 * sensorDatabase = ""
 * verboseLevel = "info"

[13:36:13.164103][info] Sensor width computed from 'FocalLength' and 'FocalLengthIn35mmFilm' metadata.
        - sensor width: 2.96685 mm
        - focal length: 3 mm
[13:36:13.165102][info] Sensor width computed from 'FocalLength' and 'FocalLengthIn35mmFilm' metadata.
        - sensor width: 2.96685 mm
        - focal length: 3 mm
[13:36:13.165102][info] Sensor width computed from 'FocalLength' and 'FocalLengthIn35mmFilm' metadata.
        - sensor width: 2.96685 mm
        - focal length: 3 mm
[13:36:13.165102][info] Sensor width computed from 'FocalLength' and 'FocalLengthIn35mmFilm' metadata.
        - sensor width: 2.96685 mm
        - focal length: 3 mm
[13:36:13.165102][info] Sensor width computed from 'FocalLength' and 'FocalLengthIn35mmFilm' metadata.
        - sensor width: 2.96685 mm
        - focal length: 3 mm
[13:36:13.165102][info] Sensor width computed from 'FocalLength' and 'FocalLengthIn35mmFilm' metadata.
        - sensor width: 2.96685 mm
        - focal length: 3 mm
[13:36:13.191031][info] CameraInit report:
        - # views listed in SfMData: 6
        - # views with an initialized intrinsic listed in SfMData: 6
        - # intrinsics listed in SfMData: 1
Nodes to execute:  ['CameraInit_1', 'FeatureExtraction_1', 'ImageMatching_1', 'FeatureMatching_1', 'StructureFromMotion_1']

[1/5] CameraInit
 - commandLine: aliceVision_cameraInit  --sensorDatabase "" --defaultFieldOfView 45.0 --verboseLevel info --output "C:/Users/user/AppData/Local/Temp/MeshroomCache/CameraInit/0289b0ba86f5e05f25cafdbab107df95b0779945/cameraInit.sfm" --allowSingleView 1  --input "C:/Users/user/AppData/Local/Temp/MeshroomCache/CameraInit/0289b0ba86f5e05f25cafdbab107df95b0779945//viewpoints.sfm"
 - logFile: C:/Users/user/AppData/Local/Temp/MeshroomCache/CameraInit/0289b0ba86f5e05f25cafdbab107df95b0779945/log
 - elapsed time: 0:00:00.120584

[2/5] FeatureExtraction
 - commandLine: aliceVision_featureExtraction  --input "C:/Users/user/AppData/Local/Temp/MeshroomCache/CameraInit/0289b0ba86f5e05f25cafdbab107df95b0779945/cameraInit.sfm" --describerTypes sift --describerPreset normal --forceCpuExtraction True --verboseLevel info --output "C:/Users/user/AppData/Local/Temp/MeshroomCache/FeatureExtraction/5a0d6372b0116dd66c30599279a4599edf4a53f9" --rangeStart 0 --rangeSize 7
 - logFile: C:/Users/user/AppData/Local/Temp/MeshroomCache/FeatureExtraction/5a0d6372b0116dd66c30599279a4599edf4a53f9/0.log
 - elapsed time: 0:00:07.842012

[3/5] ImageMatching
 - commandLine: aliceVision_imageMatching  --input "C:/Users/user/AppData/Local/Temp/MeshroomCache/CameraInit/0289b0ba86f5e05f25cafdbab107df95b0779945/cameraInit.sfm" --featuresFolders "C:/Users/user/AppData/Local/Temp/MeshroomCache/FeatureExtraction/5a0d6372b0116dd66c30599279a4599edf4a53f9" --tree "" --weights "" --minNbImages 200 --maxDescriptors 500 --nbMatches 50 --verboseLevel info --output "C:/Users/user/AppData/Local/Temp/MeshroomCache/ImageMatching/413cf048e78e6ecb591a124302680545f684c3a1/imageMatches.txt"
 - logFile: C:/Users/user/AppData/Local/Temp/MeshroomCache/ImageMatching/413cf048e78e6ecb591a124302680545f684c3a1/log
 - elapsed time: 0:00:00.119680

[4/5] FeatureMatching
 - commandLine: aliceVision_featureMatching  --input "C:/Users/user/AppData/Local/Temp/MeshroomCache/CameraInit/0289b0ba86f5e05f25cafdbab107df95b0779945/cameraInit.sfm" --featuresFolders "C:/Users/user/AppData/Local/Temp/MeshroomCache/FeatureExtraction/5a0d6372b0116dd66c30599279a4599edf4a53f9" --imagePairsList "C:/Users/user/AppData/Local/Temp/MeshroomCache/ImageMatching/413cf048e78e6ecb591a124302680545f684c3a1/imageMatches.txt" --describerTypes sift --photometricMatchingMethod ANN_L2 --geometricEstimator acransac --geometricFilterType fundamental_matrix --distanceRatio 0.8 --maxIteration 2048 --maxMatches 0 --savePutativeMatches False --guidedMatching False --exportDebugFiles False --verboseLevel info --output "C:/Users/user/AppData/Local/Temp/MeshroomCache/FeatureMatching/c951fd416339e74d63033fa326cc86dc86cafa95" --rangeStart 0 --rangeSize 7
 - logFile: C:/Users/user/AppData/Local/Temp/MeshroomCache/FeatureMatching/c951fd416339e74d63033fa326cc86dc86cafa95/0.log
 - elapsed time: 0:00:02.066457

[5/5] StructureFromMotion
 - commandLine: aliceVision_incrementalSfM  --input "C:/Users/user/AppData/Local/Temp/MeshroomCache/CameraInit/0289b0ba86f5e05f25cafdbab107df95b0779945/cameraInit.sfm" --featuresFolders "C:/Users/user/AppData/Local/Temp/MeshroomCache/FeatureExtraction/5a0d6372b0116dd66c30599279a4599edf4a53f9" --matchesFolders "C:/Users/user/AppData/Local/Temp/MeshroomCache/FeatureMatching/c951fd416339e74d63033fa326cc86dc86cafa95" --describerTypes sift --localizerEstimator acransac --lockScenePreviouslyReconstructed False --useLocalBA True --localBAGraphDistance 1 --maxNumberOfMatches 0 --minInputTrackLength 2 --minNumberOfObservationsForTriangulation 2 --minAngleForTriangulation 3.0 --minAngleForLandmark 2.0 --maxReprojectionError 4.0 --minAngleInitialPair 5.0 --maxAngleInitialPair 40.0 --useOnlyMatchesFromInputFolder False --initialPairA "" --initialPairB "" --interFileExtension .abc --verboseLevel info --output "C:/Users/user/AppData/Local/Temp/MeshroomCache/StructureFromMotion/e9d2b41afe98ba8b4c3c609451b158247c3e3872/sfm.abc" --outputViewsAndPoses "C:/Users/user/AppData/Local/Temp/MeshroomCache/StructureFromMotion/e9d2b41afe98ba8b4c3c609451b158247c3e3872/cameras.sfm" --extraInfoFolder "C:/Users/user/AppData/Local/Temp/MeshroomCache/StructureFromMotion/e9d2b41afe98ba8b4c3c609451b158247c3e3872"
 - logFile: C:/Users/user/AppData/Local/Temp/MeshroomCache/StructureFromMotion/e9d2b41afe98ba8b4c3c609451b158247c3e3872/log
 - elapsed time: 0:00:01.823718

**Comment by simogasp** [comment]
Is it possible that the SfM didn't work? Is the progress bar green or red?

You can also post the content of the log file `C:/Users/user/AppData/Local/Temp/MeshroomCache/StructureFromMotion/e9d2b41afe98ba8b4c3c609451b158247c3e3872/log` to have a better idea of what happened.

**Comment by kakakakaaka** [comment]
progress bar is green....
SfM is working successly, but I can't see output of SfM in the 3D viewer.

**Comment by simogasp** [comment]
ok just to be sure, did you also set the `QML2_IMPORT_PATH=/path/to/qmlAlembic/install/qml` pointing to the install dir of qmlAlembic before launching?

In the 3D Viewer pane do you see the 4 ticks Sfm, Mesh, Grid and locator (see image)?
![image](https://user-images.githubusercontent.com/1331744/43952205-837dfa10-9c95-11e8-9505-fc1463ff9191.png)

If it is so, try to drag and drop in the 3D Viewer this file `C:/Users/user/AppData/Local/Temp/MeshroomCache/StructureFromMotion/e9d2b41afe98ba8b4c3c609451b158247c3e3872/sfm.abc`, it should load the result.

**Comment by simogasp** [comment]
can u share the .abc somewhere?

**Comment by kakakakaaka** [comment]
If you say that the .abc files where is, the path is "C:\Users\user\AppData\Local\Temp\MeshroomCache\StructureFromMotion\d146c1d569ef52ce7e5e0fdd3d6a00994f77da97"

**Comment by simogasp** [comment]
yes i mean if you can upload the file somewhere so i can have a look

**Comment by kakakakaaka** [comment]
oh, I see. You want to get my .abc file, right?

[sfm.zip](https://github.com/alicevision/meshroom/files/2282506/sfm.zip)

**Comment by simogasp** [comment]
ok the abc seems fine
![image](https://user-images.githubusercontent.com/1331744/44025464-8736c59e-9ef0-11e8-9cf8-2720b61f3e5c.png)
(there are no points because I myself have a problem with the shaders on my Mac) This is what it looks like in Maya
![image](https://user-images.githubusercontent.com/1331744/44025775-4bd606d0-9ef1-11e8-85fd-97afe194d9ad.png)

So maybe it's once again this issue #145 that messes things around.
Can you start Meshroom without any project and just drag and drop the abc in the 3D viewer?

**Comment by simogasp** [comment]
and BTW are there any logs in the terminal when you load the abc?

**Comment by kakakakaaka** [comment]
No.. I can't see any reaction.. but I changed the app.py to check meshroom output qml warning. Then, I saw new error!
The error is :
file:///C:/project/meshroom/meshroom/ui/qml/Viewer/Viewer3D.qml:325: Error: Cannot assign QObject* to Qt3DCore::QEntity*

How can I assign that??

**Comment by EnigmaHong** [comment]
@simogasp I can run the program successfully,, but there is no  ticks of  SFM like this image. How can I add it ?

![a](https://user-images.githubusercontent.com/28854145/45077987-569d8100-b121-11e8-80fc-ca3553c40a9d.png)

**Comment by simogasp** [comment]
what does the terminal log say at the very beginning when you launch meshroom?
You may be missing the Alembic plugin

**Comment by yann-lty** [comment]
If the SfM tick is missing, you are indeed missing the [qmlAlembic](https://github.com/alicevision/qmlAlembic) plugin.

**Comment by EnigmaHong** [comment]
Thank you for your answer, the qmlAlembic plugin is not installed. I will try to install it .

**Comment by SummerPoon928** [comment]
What should the "qml" folder contain? In QML2_IMPORT_PATH=/path/to/qmlAlembic/install/qml ? 

As I use CMake Plugins to generate the Visual Studio Solution and build successfully with "alembicEntityQmlPlugin.dll", "alembicEntityQmlPlugin.lib". 

However, my built project does not contain "qml" folder.  I need to make it myself, so i would like to ask what should qml folder contain?

> ok just to be sure, did you also set the `QML2_IMPORT_PATH=/path/to/qmlAlembic/install/qml` pointing to the install dir of qmlAlembic before launching?
> 
> In the 3D Viewer pane do you see the 4 ticks Sfm, Mesh, Grid and locator (see image)?
> ![image](https://user-images.githubusercontent.com/1331744/43952205-837dfa10-9c95-11e8-9505-fc1463ff9191.png)
> 
> If it is so, try to drag and drop in the 3D Viewer this file `C:/Users/user/AppData/Local/Temp/MeshroomCache/StructureFromMotion/e9d2b41afe98ba8b4c3c609451b158247c3e3872/sfm.abc`, it should load the result.

**Comment by 1992Zz** [comment]
> 
> 
> ok the abc seems fine
> ![image](https://user-images.githubusercontent.com/1331744/44025464-8736c59e-9ef0-11e8-9cf8-2720b61f3e5c.png)
> (there are no points because I myself have a problem with the shaders on my Mac) This is what it looks like in Maya
> ![image](https://user-images.githubusercontent.com/1331744/44025775-4bd606d0-9ef1-11e8-85fd-97afe194d9ad.png)
> 
> Can you start Meshroom without any project and just drag and drop the abc in the 3D viewer?

I don't have this folder!C:/Users/user/AppData/Local/Temp/MeshroomCache/StructureFromMotion/e9d2b41afe98ba8b4c3c609451b158247c3e3872/sfm.abc

**Comment by natowi** [comment]
The folder structure for qtPlugins is

```
Meshroom
   - qtPlugins
        -  imageformats
               -  QtOIIOPlugin files
         - qml
                - AlembicEntity
                       - alembicEntityQmlPlugin files
                - DepthMapEntity
                       - depthMapEntityQmlPlugin files
```

If you don´t want to build the plugins yourself, you can copy the folder from the pre-build version
