### ISSUE TITLE
Not recognizing my GPU

### ISSUE THREAD

**Issue by nickblock** [alicevision/meshroom#182]
I'm getting this error:
[error] This program needs a CUDA-Enabled GPU (with at least compute capability 2.0).

I'm running on Windows 10, GeForce GTX 1080, driver 385.54

Any ideas?

**Comment by GeoffreyMarchal** [comment]
Same for me with a GeForce GTX 960m

**Comment by AFWSI** [comment]
@nickblock and @GeoffreyMarchal try reinstalling or updating your driver. Here’s a meshroom thread on https://blenderartist.org and few people ran into the same issue. 

https://blenderartists.org/t/meshroom-free-photogrammetry/1120286/62

**Comment by nickblock** [comment]
Yeah updating to 398.82 did it, cheers.

**Comment by oussama04** [comment]
I have Intel HD graphics 3000 and i have the same probleme "CUDA...." so meshroom don't support this GPU?

**Comment by nickblock** [comment]
@oussama04 you will need an nvidia card for CUDA I'm afraid.

**Comment by Nivel2-SCADA-IIoT-Monclova** [comment]
Install cuda toolkit 7.5 and visual studio 2012 in windows 7, I have a 2010 quadro 2000 graphics card, it shows me the error described here, I want to keep the same cuda 7.5 version, do you recommend uninstalling version 7.5 and installing it again? or do I install the same version as if it were an update?

**Comment by ChemicalXandco** [comment]
@Nivel2-SCADA-IIoT-Monclova that graphics card has CUDA 2.1 which does not meet the requirements. Try using an older version such as https://github.com/alicevision/meshroom/releases/tag/v2019.2.0 which should work with a older CUDA version
