### ISSUE TITLE
Depthmap: Found 0 image dimension(s)

### ISSUE THREAD

**Issue by Nicolaj-J** [alicevision/Meshroom#1820]
Hello.

I'm a student trying to automate Meshroom via cmd for a school project. I have been following this guide:
http://filmicworlds.com/blog/command-line-photogrammetry-with-alicevision/ 

I have been updating the python automation software given in the guide to work with Meshroom 2021 where I ran into a problem with depthmap generating. I get this message back for what looks like each image given:
      [20:48:16.428047][info] Supported CUDA-Enabled GPU detected.
      [20:48:16.439047][info] Found 0 image dimension(s):
      [20:48:16.439546][info] Overall maximum dimension: [0x0]
      [20:48:16.440046][info] No camera to process.
      
I found something about this problem in this thread where there was a solution with registry key changes: 
https://github.com/alicevision/meshroom/issues/593#issuecomment-622867419  

This does not look like it works for me since I still get the same messages back. After the messages it just dies without making a depthmap. Anyone know how to fix this?
Let me know if there is any other information needed. If so please say where I can find it since I'm new to Meshroom.

Thanks alot

**Python code**

```
def Run_07_DepthMap(baseDir,binDir,numImages,groupSize, srcImageDir):
	SilentMkdir(baseDir + "/07_DepthMap")
	print("numImages: ",numImages)
	print("groupsize: ", groupSize)
	print("(numImages + groupsize -1)/groupsize: ", (numImages + (groupSize-1))/groupSize)
	numGroups = (numImages + (groupSize))/groupSize
	print("numGroups: ", numGroups)
	srcIni = baseDir + "/05_PrepareDenseScene/mvs.ini"
	binName = binDir + "\\aliceVision_depthMapEstimation.exe"
	dstDir = baseDir + "/07_DepthMap"

	cmdLine = binName
	cmdLine = cmdLine + " --sgmGammaC 5.5 --sgmWSH 4 --refineGammaP 8.0 --refineSigma 15 --refineNSamplesHalf 150 --sgmMaxTCams 10 --refineWSH 3 --downscale 2 --refineMaxTCams 6 --verboseLevel info --refineGammaC 15.5 --sgmGammaP 8.0"
	cmdLine = cmdLine + " --refineNiters 100 --refineNDepthsToRefine 31 --refineUseTcOrRcPixSize False" 
	cmdLine = cmdLine + " " + srcIni
	cmdLine = cmdLine + " --output \"" + dstDir + "\""
	cmdLine = cmdLine + " --imagesFolder " + srcImageDir
	cmdLine = cmdLine + " --input " + "G:/3_semester_projekt_v2/Intimediary_files/00_CameraInit/cameraInit.sfm"


	for groupIter in range(int(numGroups)):
		groupStart = groupSize * groupIter
		groupSize = min(groupSize,numImages - groupStart)
		print("DepthMap Group %d/%d: %d, %d" % (groupIter, numGroups, groupStart, groupSize))

		cmd = cmdLine + (" --rangeStart %d --rangeSize %d" % (groupStart,groupSize))
		print(cmd)
		os.system(cmd)

```
**Dataset**
[images_sample.zip](https://github.com/alicevision/Meshroom/files/9984202/images_sample.zip)

**Log**
G:\3_semester_projekt_v2\Meshroom-2021.1.0\aliceVision\bin\aliceVision_depthMapEstimation.exe --sgmGammaC 5.5 --sgmWSH 4 --refineGammaP 8.0 --refineSigma 15 --refineNSamplesHalf 150 --sgmMaxTCams 10 --refineWSH 3 --downscale 2 --refineMaxTCams 6 --verboseLevel info --refineGammaC 15.5 --sgmGammaP 8.0 --refineNiters 100 --refineNDepthsToRefine 31 --refineUseTcOrRcPixSize False G:\3_semester_projekt_v2\Intimediary_files/05_PrepareDenseScene/mvs.ini --output "G:\3_semester_projekt_v2\Intimediary_files/07_DepthMap" --imagesFolder G:\3_semester_projekt_v2\dataset_monstree-master\Billeder --input G:/3_semester_projekt_v2/Intimediary_files/00_CameraInit/cameraInit.sfm --rangeStart 9 --rangeSize 3
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0 (default)
 * imagesFolder = "G:\3_semester_projekt_v2\dataset_monstree-master\Billeder"
 * input = "G:/3_semester_projekt_v2/Intimediary_files/00_CameraInit/cameraInit.sfm"
 * maxViewAngle = 70 (default)
 * minViewAngle = 2 (default)
 * nbGPUs = 0 (default)
 * output = "G:\3_semester_projekt_v2\Intimediary_files/07_DepthMap"
 * rangeSize = 3
 * rangeStart = 9
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[20:43:07.002979][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    NVIDIA GeForce GTX 1650
        - compute capability:      7.5
        - total device memory:     4095 MB
        - device memory available: 3300 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   1024
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {131072,65536}
        - max 3D array texture:    {16384,16384,16384}
        - max 2D linear texture:   {131072,65000,2097120}
        - max 2D layered texture:  {32768,32768,2048}
        - number of SM(x)s:        14
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte
[20:43:07.221479][info] Supported CUDA-Enabled GPU detected.
[20:43:07.232994][info] Found 0 image dimension(s):
[20:43:07.232994][info] Overall maximum dimension: [0x0]
[20:43:07.233494][info] No camera to process.

**Comment by mugulmd** [comment]
Hey @Nicolaj-J 
Have you tried running your process through the GUI as a sanity check ? This would make it easier to locate the problem (if it is in your script or somewhere else).

Also if you're trying to automate launching a Meshroom pipeline there is already a command-line utility for that, called meshroom_batch. You may want to look into it (before re-writing it on your own) 😄

**Comment by Nicolaj-J** [comment]
Hello @mugulmd 

I got the pictures from a friend that has been able to make 3D models with them and I just tried it myself it looks fine.

But I don't know anything about meshroom_batch and tried to look it up but there weren't a lot of guides. Also, the documentation isn't really beginner friendly or at least I just get a warning when trying to run it. Do you know of any guide I can follow?

**Comment by mugulmd** [comment]
Hey @Nicolaj-J indeed we started re-working the documentation system, it's going to improve progressively 😄 

In the mean time, here's the manual page for `meshroom_batch` : 
https://meshroom-manual.readthedocs.io/en/latest/feature-documentation/cmd/photogrammetry.html

If you're using the standard photogrammetry pipeline you can just type: 
`python bin/meshroom_batch --input /path/to/your/images/folder --pipeline photogrammetry`
Also if you want to override some default parameters there is a `--paramOverrides` option.

**Comment by Nicolaj-J** [comment]
Hello @mugulmd 

Thanks for all the help. 

I did find the page. But when I try to run it with your command I just get this: 

G:\3_semester_projekt_v2\Meshroom-2021.1.0>python bin/meshroom_batch --input G:\3_semester_projekt_v2\dataset_monstree-master\Billeder --pipeline photogrammetry
python: can't open file 'bin/meshroom_batch': [Errno 2] No such file or directory

G:\3_semester_projekt_v2\Meshroom-2021.1.0>PAUSE
Press any key to continue . . .

**Comment by mugulmd** [comment]
My bad, you don't need to call python there's already an executable you can call directly, so the line is simply: 
`meshroom_batch --input /path/to/images/folder --pipeline photogrammetry`

**Comment by Nicolaj-J** [comment]
I tried this before and just got "nothing to compute".

G:\3_semester_projekt_v2\Meshroom-2021.1.0>meshroom_batch --input G:\3_semester_projekt_v2\dataset_monstree-master\Billeder --pipeline photogrammetry
      Program called with the following parameters:
       * allowSingleView = 1
       * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1"
       * defaultCameraModel = "" (default)
       * defaultFieldOfView = 45
       * defaultFocalLengthPix = -1 (default)
       * defaultIntrinsic = "" (default)
       * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
       * imageFolder = "" (default)
       * input = "C:\Users\Nicolaj\AppData\Local\Temp\tmprot6rtjh/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"
       * output = "C:/Users/Nicolaj/AppData/Local/Temp/tmprot6rtjh/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm"
       * sensorDatabase = "G:\3_semester_projekt_v2\Meshroom-2021.1.0\aliceVision\share\aliceVision\cameraSensors.db"
       * useInternalWhiteBalance = 1
       * verboseLevel = "info"
       * viewIdMethod =  Unknown Type "enum aliceVision::sfmDataIO::EViewIdMethod"
       * viewIdRegex = ".*?(\d+)" (default)
      
      [12:35:09.306696][warning] Some image(s) have no serial number to identify the camera/lens device.
      This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
      The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximation they will share the same internal camera parameters.
      97 image(s) are concerned.
      [12:35:09.332696][info] CameraInit report:
              - # views listed: 97
                 - # views with an initialized intrinsic listed: 97
                 - # views without metadata (with a default intrinsic): 0
              - # intrinsics listed: 1
      No output set, results will be available in the cache folder: "C:/Users/Nicolaj/AppData/Local/Temp/MeshroomCache"
      WARNING:root:Nothing to compute
      
      G:\3_semester_projekt_v2\Meshroom-2021.1.0>PAUSE
      Press any key to continue . . .

Is this because I'm missing a step?

**Comment by mugulmd** [comment]
Have you already done a photogrammetry of that same image dataset in that same output folder (which seems to be the default cache folder in AppData/Local/Temp) ?
If so, meshroom will detect those cache files and see that their status is SUCCESS so it won't recompute them.
There are two workarounds for this (choose the one you prefer): 
- use the `--cache` argument to set a custom cache folder
- use the `--forceCompute` argument to force recalculating everything
