### ISSUE TITLE
[request] Optimize

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [alicevision/Meshroom#1825]
When you compare speed of every step of meshroom with any commercial software, the difference in time required is significant.
Optimize every step, include cuda more often allow more parallelization, utilize cpu extensions, you name it.

**Comment by FinnT730** [comment]
I think the main optimization should be in AliceVision, not Meshroom.
Meshroom is just the GUI part of the software :)

**Comment by natowi** [comment]
AliceVision is in constant development, and there are numerous recent improvements wip for example https://github.com/alicevision/AliceVision/pull/1296
But this is not an easy matter. Commercial software has significantly more funding and full time developers, so they spend all resources to improve the performance.

**Comment by ErfolgreichCharismatisch** [comment]
Sacrifice quality for speed. This is huge.
Many times I want to get a vague overview what my final model will look like to quickly tweak settings, enable a preview setting.

**Comment by natowi** [comment]
That is what draft meshing is for: https://github.com/alicevision/Meshroom/wiki/Draft-Meshing
