### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by bhegedus** [alicevision/Meshroom#1828]
**Describe the problem**
stop processing at the 5th phase

**Screenshots**
[
![Screenshot 2022-11-19 20 24 52](https://user-images.githubusercontent.com/7994732/202868029-04bacde3-9191-4b6a-941d-5d8ed09c06fb.png)
](url)

**Dataset**
![20220907_121359](https://user-images.githubusercontent.com/7994732/202868053-e130dcc8-c211-4781-a725-329b5e675051.jpg)
![20220907_121402](https://user-images.githubusercontent.com/7994732/202868058-644edd89-3dcb-42f9-b105-784a6b678a79.jpg)
![20220907_121407](https://user-images.githubusercontent.com/7994732/202868065-95270032-be53-49c5-b09d-f9bffbd21992.jpg)

**Log**

rogram called with the following parameters:
 * allowSingleView = 1
 * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1"
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:\Users\GEP_AMD\AppData\Local\Temp\tmpso49g2z9/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"
 * output = "C:/Users/GEP_AMD/AppData/Local/Temp/tmpso49g2z9/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm"
 * sensorDatabase = "C:\Users\GEP_AMD\Desktop\Meshroom-2021.1.0\aliceVision\share\aliceVision\cameraSensors.db"
 * useInternalWhiteBalance = 1
 * verboseLevel = "info"
 * viewIdMethod =  Unknown Type "enum aliceVision::sfmDataIO::EViewIdMethod"
 * viewIdRegex = ".*?(\d+)" (default)

[18:30:48.576029][warning] Some image(s) have no serial number to identify the camera/lens device.
This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximation they will share the same internal camera parameters.
16 image(s) are concerned.
[18:30:48.583031][info] CameraInit report:
        - # views listed: 16
           - # views with an initialized intrinsic listed: 16
           - # views without metadata (with a default intrinsic): 0
        - # intrinsics listed: 1
WARNING:root:Retrying to obtain clipboard.

**Desktop (please complete the following and other pertinent information):**
 - OS: win 10,

 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2021.1]

**Comment by mugulmd** [comment]
Hey @bhegedus it seems that you put the CameraInit's log in the issue, whereas what we would need to help you is the log of the node that failed (I'm guessing StructureFromMotion since you said it's the 5th) 😅 
Also could you add your whole image dataset in a zip file to the issue (instead of 3 uncompressed images) ? That would allow us to reproduce the pipeline on our side.

**Comment by bhegedus** [comment]
Hi.
Enclose the log and the image files compressed.
[log.txt](https://github.com/alicevision/Meshroom/files/10055525/log.txt)
[photos.zip](https://github.com/alicevision/Meshroom/files/10057129/photos.zip)

**Comment by bhegedus** [comment]
I have remade all the photos. I the process is finished but no success.
![Screenshot 2022-11-21 15 52 21](https://user-images.githubusercontent.com/7994732/203086921-51f24321-bc70-4c49-9817-744c0af860ee.png)
[photos1.zip](https://github.com/alicevision/Meshroom/files/10057583/photos1.zip)
[photos2.zip](https://github.com/alicevision/Meshroom/files/10057585/photos2.zip)

**Comment by mugulmd** [comment]
Glad to see the computations went through 😄 

Unfortunately what you end up with seems like a dataset issue: the object your trying to reconstruct with meshroom is composed of flat specular surfaces without texture, therefore the pipeline is not likely to work very well...
Adding texture to your object and reducing light reflections would probably improve your results.
