### ISSUE TITLE
Cannot launch the linux binary on linux mint 17.2

### ISSUE THREAD

**Issue by ZX-WT** [alicevision/meshroom#185]
Nothing happen after double clicking the executable, so I start it with terminal and the following error occurred
```
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 13, in run
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/opt/Meshroom/setupInitScriptUnix.py", line 27, in <module>
OSError: [Errno 7] Argument list too long
```
Just in case it is related to the locale I am using ,I am using Traditional Chinese.

**Comment by textoo** [comment]
same problem with mint 13.8

**Comment by kynjo** [comment]
Hello guys, did you solve the problem?

**Comment by andershem** [comment]
Same in linux mint 18

**Comment by kynjo** [comment]
Hmm. In my case all problem be in path. I just copy in /home/user/Meshroom.

**Comment by Nefor111** [comment]
Use only english named directories,do not use locales.For example /home/user/Программы gives me an error message. /home/user/programms works fine.

**Comment by john-davies** [comment]
> Same in linux mint 18
> there is no /opt/rh in my system, guessing thats some Redhat specific package and absolute pathing, will try to build the source.
> 
> When starting from git i just get a black window and the below lines repeting:
> QOpenGLShaderProgram::uniformLocation(qt_Matrix): shader program is not linked
> QOpenGLShaderProgram: could not create shader program
> QOpenGLShader: could not create shader
> QOpenGLShader: could not create shader
> shader compilation failed:

I get exactly the same thing on Ubuntu 16.04, did you manage to build from source?

**Comment by andershem** [comment]
sorry, i had no luck on that either so 
i gave it up.

**Comment by john-davies** [comment]
OK, thanks. Might I suggest to the project maintainers that something like a Linux Snap package is provided instead? I appreciate that this is more work but it would at least make the software more easily available on Debian/Ubuntu/Mint systems.

**Comment by fabiencastan** [comment]
I'm sorry, we don't have resources for making a Snap package, but we would be happy to support such an initiative.

For the ubuntu problem have you tried the following suggestion from the [README](https://github.com/alicevision/meshroom/blob/develop/README.md)?
```
On Ubuntu, you may have conflicts between native drivers and mesa drivers. In that case, you need to force usage of native drivers by adding them to the LD_LIBRARY_PATH: LD_LIBRARY_PATH=/usr/lib/nvidia-340 PYTHONPATH=$PWD python meshroom/ui You may need to adjust the folder /usr/lib/nvidia-340 with the correct driver version.
```

**Comment by john-davies** [comment]
Hmm, I thought I was using those drivers but if I try:

`LD_LIBRARY_PATH=/usr/lib/nvidia-384 ./Meshroom`

then it loads and runs fine. Thanks for your help.
