### ISSUE TITLE
Documentation? 

### ISSUE THREAD

**Issue by AFWSI** [alicevision/meshroom#186]
Are you guys gonna make any documentation since there’s now a “release”?  I can’t figure out why half of my pictures fail and why the cameras are always lined up about a 30 degree angle from the ground. I’m sure tweaking some settings will prolly help with this ,but which ones on which node is the question. Some documentation on these settings would be nice.

**Comment by AdityaSrivastava2819** [comment]
Yeah, we can't use Meshroom to the fullest without some documentation or tutorials. Also, Alicevision should start using its YouTube channel more and more.

**Comment by ChemicalXandco** [comment]
I am willing to contribute to the documentation.

**Comment by fabiencastan** [comment]
Yes, we definitely need more documentation!
Currently the best source of information is still the video https://youtu.be/v_O6tYKQEBA.
To understand the 3D reconstruction concepts behind each node, you have a short description with references to publications here: https://alicevision.github.io/#photogrammetry

Thanks for the contribution proposition, that would be really useful.
We will publish a new tutorial soon that will provide an initial document that can be improved collaboratively.

**Comment by AdityaSrivastava2819** [comment]
That'll be great! You should post more and more tutorials on YouTube. That
would attract people and then they will also make tutorials. Also, they
would then be able to contribute to the documentation. YOUTUBE is a great
place for such things. Just look at Blender's channel. They post a lot
about development and there is an active community that makes more
tutorials. You should also do livestreams and tell about the development. 1
video per week or 2 weeks would be great! Also, we need FORUMS for
Meshroom. BLOGS are also great like those of Unreal, Unity, Blender, etc.

**Comment by fabiencastan** [comment]
Hi @AdityaSrivastava2819

Thanks for your message. As explained in https://github.com/alicevision/meshroom/issues/234, we are a small team and cannot manage to maintain all that. Creating videos, update blogs and forums takes a huge amount of time.
Contributions would be much appreciated to help us to focus on speedups and new features for the next release.
Best,

**Comment by ChemicalXandco** [comment]
@fabiencastan I am ok in python and would like to contribute to meshroom but the codebase is confusing to me, what would be the best way to get in touch with the devs so I can be familiar with it?

**Comment by fabiencastan** [comment]
@ChemicalXandco Oh cool, that would be great! @yann-lty is on vacation this week and he knows this part better than anyone else. So we can setup a conf call next week for a first meeting if it's good for you.

And then of course, we will see for slack or gitter for direct discussions.

**Comment by slate0** [comment]
"CG Geek" has a 35 minute quick tutorial.  Well, he it's Meshroom for 12 minutes and then he moves to blender for further processing.  https://www.youtube.com/watch?v=k4NTf0hMjtY

**Comment by ChemicalXandco** [comment]
@fabiencastan don't waste your precious time on me, I'm only interested in the front-end and I can probably work out a lot of it anyway. Gitter is fine thanks.

**Comment by natowi** [comment]
I am working on a User Guide, collecting all the information from github issues, source code comments, blogs, tutorials and the Alicevision homepage. I´ve also created screenshots, wrote text and collected information from various papers. 
Figuring out the node parameters is hard, but step by step I´m getting there.
At the moment I am at 44 pages (.odt doc.). I have to do some cleanup and add citations before I am ready to share it.
This might be a good base to start the documentation. Maybe it is easier for the AliceVision team to contribute details/content to an existing manual.

**Comment by simogasp** [comment]
@natowi That's simply great! Maybe you can share the document as a public googledoc so we can suggest correct and complete your document. You can share publicly and allows people only to suggest changes, rather than directly change the content.

**Comment by ubershy** [comment]
@natowi thank you for working on this. I really miss documentation.

**Comment by natowi** [comment]
Update: 90% done. Here is a short summary. It took me some time to bring all the information in order.
There´s still a lot of work to do, but at the end of the week we´ll have something to work with.

Summary
This manual starts with the Meshroom _history_ and how to _download_, _install_ or _compile_ it for your platform.
New users should start with the _First Steps: Meshroom_ chapter, which is a walk through the default pipeline using a demo dataset to prevent errors and get a good first result.
The next chapter _Advanced Reconstruction_ is for Users, who want to use their own data.
At first, it contains some _photo shooting advices ([#17](https://github.com/alicevision/meshroom/issues/17))_ for new users, followed by a list for suitable tethering software to optimize data collection.
The last part of the chapter describes _different ways to add images_ to Meshroom and _handle common problems_.
The _Background: Default Pipeline_ chapter contains detailed _background information and descriptions_ for the default pipeline. It is highly recommended to read, as it contains useful insights.
If you want to customize the default pipelines settings, jump to the “_Improve the default pipeline_” chapter.
The chapter is followed by the _Complete Node List with descriptions, tips and comments_.
At last you will find tips on how to _share or export models_ from Meshroom and import them in other software.
At the end there´s a list with related projects, the Meshroom _licenses, contact details, ways to contribute, special thanks and a comprehensive references list_.

// I included some chapters not specifically related to Meshroom, but I think they might be interesting for users, who are new to photogrammetry.
__
@johnhable is it okay to use and modify your [helpful blogpost](http://filmicworlds.com/blog/command-line-photogrammetry-with-alicevision/) as part of the documentation?
@ryanfb is it okay to use and modify your [Mac OSX help](https://ryanfb.github.io/etc/2018/08/17/alicevision_and_meshroom_on_mac_os_x.html) as part of the documentation?
Big thanks in advance

**Comment by johnhable** [comment]
Hi @natowi. Sure, feel free to use any part of that blog post in your documentation.

**Comment by ryanfb** [comment]
@natowi - yes, feel free.

**Comment by serapth** [comment]
First off, awesome software, cool to see this open source.  I agree full-heartedly about the need for documentation, I struggled to get a good result out of the box too.

In the end though, I did put together this [step by step](https://www.gamefromscratch.com/post/2018/10/18/Creating-3D-Models-From-Photos-Using-Meshroom.aspx) tutorial, that will at least get you up and started using an existing photo set, so people can at least get off on the right foot.  Also did a few suggestions, from my own experience, on taking photos that will work, which is going to be a tripping point for many.  I also did a much more in-depth [30 minutes with Meshroom video](https://www.youtube.com/watch?v=R0PDCp0QF1o), that people will hopefully find useful.

Again, great work!

**Comment by natowi** [comment]
I am still working on the manual so there are some messy parts. But feel free to read and comment: https://docs.google.com/document/d/17HYtYS1tvx053k3_nO6Z2GnP2R3cXMlGMN-1WIe3kJE/edit?usp=sharing
If you want to contribute at this state, 1) Open the link. 2) At the top right, click Share. 3) Enter your email address and click Send request.

**Comment by steren** [comment]
Thanks for the user guide. It's especially great that users can comment and suggest via Google Docs for fast iteration.

I think the main problem is that it is completely hidden. Even if it's not perfect, what do you think of publishing it online and keep iterating on its content on GitHub? You could start pointing at it from teh Meshroom homepage.

Github pages can be a great way to easily publish static content from a git repository.
Or using the wiki associated with this repo could also work.

**Comment by natowi** [comment]
@steren Thank you for the feedback.

The idea was to add the manual content to the [wiki](https://github.com/alicevision/meshroom/wiki) and release a complete PDF. At the moment the wiki is used for FAQ. 

Before pushing the manual to github, I would like to bring it in a _presentable_ form. (Order, name and content of the chapters, formatting, images, references, phrasing,...)

I could use some help, so you are welcome to edit or comment the current manual.

**Comment by ultrasuperpingu** [comment]
The GoogleDoc document is a great start for people who don't have time to dig into the academic papers ;). Thanks a lot.

**Comment by natowi** [comment]
Due to increasing demand I´ll start migrating the documentation to Github soon.

**Comment by fabiencastan** [comment]
Hi @natowi,
Help on documentation would be awesome!
I'm not sure to understand what you're planning to do.
Could we setup a confcall to discuss about it?

**Comment by natowi** [comment]
Hi @fabiencastan, 
to make contributions and access easier, I would like to move my [google doc](https://docs.google.com/document/d/17HYtYS1tvx053k3_nO6Z2GnP2R3cXMlGMN-1WIe3kJE/edit) (after some restructuring and cleanup) to github.
I´ll send you an email to setup a confcall.

**Comment by dmontagu** [comment]
This google doc looks extremely useful, but it is extremely hard to navigate (presumably due to the sharing protections?). Is there another more easily browsed version somewhere else?

**Comment by natowi** [comment]
[Here](https://github.com/natowi/meshroom_doc) is the new home of the documentation. There is still a lot to do, but we are getting there. In the future we will be able to create the doc as pdf and html, readthedocs compatible.

**Comment by natowi** [comment]
Check out the _latest_ (or _dev-install-firstpass_) [Meshroom manual](https://readthedocs.org/projects/meshroom-manual/)  (PDF, HTML, EPUB)
[Contributions are welcome](https://github.com/alicevision/meshroom-manual).
