### ISSUE TITLE
IDs editable in node settings

### ISSUE THREAD

**Issue by robertguetzkow** [alicevision/meshroom#187]
The UI allows to edit the automatically generated IDs in the node properties. These fields should be disabled / not editable.

![2018_08_13_editable_ids](https://user-images.githubusercontent.com/25986807/44041612-7ed4c03a-9f1e-11e8-9d6e-c61971d56a6d.jpg)

**Comment by natowi** [comment]
- [ ] add id to Advanced Settings or disable editing

**Comment by natowi** [comment]
With the 2019.2 release the sliders were replaced by value fields. Setting the fields to advanced settings would be possible, but nearly all settings in this node are for advanced users. We also do not want to disable these fields because they a valuable for finding problems.
