### ISSUE TITLE
Documentation on camera Calibration 

### ISSUE THREAD

**Issue by DrakeFirebreed** [alicevision/Meshroom#1872]
For the life of me I can't calibrate my camera... I've done a video and image set. If I link directly to video through copy file path for input I get input= Unknown Type "class boost:: filesystem::path"

I've created a default.xml document like in the tutorial
`<opencv_storage>`
<images>
filepath1
filepath2
</images>
`<opencv_storage>`

I get the same unknown input.

I've tried a file with just photos. 
Nothing seems to work and I've read everything that is available for it.

**Comment by natowi** [comment]
I have updated the documentation a few days ago:
https://meshroom-manual.readthedocs.io/en/latest/feature-documentation/nodes/CameraCalibration.html
Below the node parameters there is a short tutorial.
The first link to the opencv documentation was just for reference on the theory of camera calibration. I´ll rephrase it.

**Comment by natowi** [comment]
I hope this helped. If you still have questions, feel free to ask.

**Comment by sgtjar90** [comment]
I'm gonna see if I can get this opened up again - I've been having the same issue as the original asker:
     - unable to put something successfully in the input path. 

I solved it, so far, by moving the calibration video to my desktop and linking that path  to the input text field - it worked there, so i think it has something to do with the length of the file path. Also, made sure my video is in mp4 format.

For pictures, I also tried putting them on my desktop, but apparently the input text field doesn't accept .jpg? It worked on a single photo by making sure the photo was in the png format.

**Comment by DrakeFirebreed** [comment]
I just bought a thunk 3d scanner much easier if you have the cash flow

**Comment by sgtjar90** [comment]
> I just bought a thunk 3d scanner much easier if you have the cash flow
> […](#)


well, im jelly -_-.

**Comment by natowi** [comment]
I´ll try to improve the doc. Thanks for the feedback
