### ISSUE TITLE
No module named 'mpc',  No module named 'simpleFarm'

### ISSUE THREAD

**Issue by RufinoN** [alicevision/Meshroom#1877]
**Describe the bug**
when trying to test meshroom i get the following errors:

"[2023-01-23 10:19:24,917][WARNING] == The following "submitters" plugins could not be loaded ==
  * rippleSubmitter: No module named 'mpc'
  * simpleFarmSubmitter: No module named 'simpleFarm'"

**To Reproduce**
after downloading the repository and having alicevision build i run the following command on the meshroom folder:

"set PYTHONPATH=%CD% && python meshroom/ui"

**Expected behavior**
open a meshroom test windows

**Desktop (please complete the following and other pertinent information):**
 - OS: [win 10]
 - Python version [3.9]
 - Qt/PySide version [None]
 - Meshroom version: git source as from 1/23/2023

**Comment by natowi** [comment]
This is just an information, not a bug. Meshroom will work as intended.
Both submitters are used project internally at the moment.

**Comment by fabiencastan** [comment]
@RufinoN Thanks for reporting it.
It is only used internally, so it's perfectly normal to get this warning. We keep them in the project as examples for people to build their own submitters. We should maybe find a way to not include them by default to avoid this warning.

**Comment by fabiencastan** [comment]
ALICEVISION_ROOT should be the install root folder defined by "-DCMAKE_INSTALL_PREFIX".

**Comment by RufinoN** [comment]
> ALICEVISION_ROOT should be the install root folder defined by "-DCMAKE_INSTALL_PREFIX".

i build alicevision with the following command line "cmake .. -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 17 2022" -A x64 -T host=x64"

and then I use VS 2022 to build the relase, which build sucessfully without any error. is there a different wat to build it? because I didn't use the "-DCMAKE_INSTALL_PREFIX". but instead follow the building steps.

**Comment by fabiencastan** [comment]
Without the build of the "INSTALL" target ("make install" on linux), it will not gather all the files into one output folder.
In all case, for a development version the full path to the source files will be used if ALICEVISION_ROOT is not set. But to package it and send it to someone else, you need to run the INSTALL target and defined the ALICEVISION_ROOT.

**Comment by RufinoN** [comment]
Okay, so I guess I'm missing an step. After building the release version (windows 10 + VS 17 2022) what should I do?
VS 17 2022 produce 262 files inside the folder AliceVision\build\Windows-AMD64\Release
(where alicevision is the folder obtained from github)

I was assuming this to be my root folder. Is that the case or I'm missing a step where I need to build the files in the release folder as an INSTALL?

sorry for the many questions?

**Comment by RufinoN** [comment]
> Without the build of the "INSTALL" target ("make install" on linux), it will not gather all the files into one output folder. In all case, for a development version the full path to the source files will be used if ALICEVISION_ROOT is not set. But to package it and send it to someone else, you need to run the INSTALL target and define the ALICEVISION_ROOT.

Okay, so I guess I'm missing an step. After building the release version (windows 10 + VS 17 2022) what should I do?
VS 17 2022 produce 262 files inside the folder AliceVision\build\Windows-AMD64\Release
(where alicevision is the folder obtained from github)

I was assuming this to be my root folder. Is that the case or I'm missing a step where I need to build the files in the release folder as an INSTALL?

sorry for the many questions
