### ISSUE TITLE
Load mesh button

### ISSUE THREAD

**Issue by AFWSI** [alicevision/meshroom#190]
OK, so yesterday I did a small piece of petrified wood. Once everything was completed, I never got the load mesh button and had to manually load the mesh from the folder. I noticed if I open the saved project the button shows up. I have done 4 different projects and this is the first time it has never given me the load mesh button when completed.

**Comment by natowi** [comment]
@AFW Is this still an issue?

**Comment by codingcatgirl** [comment]
Yes, this is still an issue. Happened to me right now. Changed something about the settings, re-ran the pipeline, better result as far as i could tell… but the load mesh button was gone and since i'm new to meshroom idk how to load the mesh some other way.

**Comment by natowi** [comment]
@codingcatgirl Simply double-click on the Meshing node or drag-n-drop the mesh file in the viewer

**Comment by codingcatgirl** [comment]
Cool, thanks! Will try it next time
