### ISSUE TITLE
CCTag not included in Meshroom 2018.1

### ISSUE THREAD

**Issue by aavenel** [alicevision/meshroom#192]
Hi, 

Thanks for your great tool!
I tried to extract features by using CCtag3, but unfortunately the process failed.
If I launch `aliceVision_featureExtraction` by using command line, CCtag describer type is not listed.
I am using Meshroom 2018.1 release.
```
./aliceVision_featureExtraction.exe
AliceVision featureExtraction:

Required parameters:
  -i [ --input ] arg                    SfMData file.
  -o [ --output ] arg                   Output path for the features and
                                        descriptors files (*.feat, *.desc).

Optional parameters:
  -d [ --describerTypes ] arg (=sift)   Describer types used to describe an
                                        image:
                                        * sift: Scale-invariant feature
                                        transform.
                                        * sift_float: SIFT stored as float.
                                        * sift_upright: SIFT with upright
                                        feature.
                                        * akaze: A-KAZE with floating point
                                        descriptors.
                                        * akaze_liop: A-KAZE with Local
                                        Intensity Order Pattern descriptors.
                                        * akaze_mldb: A-KAZE with
                                        Modified-Local Difference Binary
                                        descriptors.

```

Looking at the code, I guess that "CCTag 1.0.0" package was not found or ALICEVISION_HAVE_CCTAG is not defined.

Is this an intended behavior ?

**Comment by crparis1** [comment]
I noticed this pretty quickly as well.  Shouldn't be too tough to add by compiling from source with the CCtag libraries with the AliceVision CCTag libraries?

**Comment by simogasp** [comment]
yes for the moment cctag is not packaged in the current release. It will come soon with the next ones.

**Comment by lexvandersluijs** [comment]
Having CCtag support would really be super amazingly awesome for the application I'm working on!

If I build it myself, how straightforward would it be to include it in the build?

**Comment by simogasp** [comment]
@lexvandersluijs you can try the latest develop, there is a option to build alicevision and the dependencies altogether with support for CCTAG. At cmake you should do something like this:
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DALICEVISION_BUILD_DEPENDENCIES:BOOL=ON -DINSTALL_DEPS_BUILD:BOOL=ON -DCMAKE_INSTALL_PREFIX=<path_where_u_want_to_install>
```
Then you should get the latest develop of meshroom and follow the instruction to install the needed dependency as explained in README and INSTALL file at the root.

**Comment by natowi** [comment]
Building the solution worked, but in VS I am stuck building OpenGV

**Comment by simogasp** [comment]
what's teh error?

**Comment by natowi** [comment]
VS does not continue compiling. No error message. I think I will try again with OpenGV disabled. Looks like there is still an error https://travis-ci.org/alicevision/opengv

**Comment by simogasp** [comment]
I see why it is broken, they added a submodule recently and we are not pulling that.
Real quick, can you try to add `-DBUILD_PYTHON:BOOL=OFF` just before ` <SOURCE_DIR>` here:
https://github.com/alicevision/AliceVision/blob/develop/CMakeLists.txt#L209

(well i'm assuming you are using our script to install everything?)

**Comment by natowi** [comment]
Thank you, but that did not work. Yes, I am using the build script. Could be my fault. I´ll be waiting for the OpenGV PR.

**Comment by fabiencastan** [comment]
CCTAG is now packaged in the releases.
