### ISSUE TITLE
Meshing taking over 14 hours

### ISSUE THREAD

**Issue by Sarngond** [alicevision/meshroom#195]
I don't know if this is my fault or Meshroom's but I put 68 images in and once it got to meshing it has already taken 14 hours and is still going. I don't know if this is normal or what, i just want to know if you guys think my model will be done soon. It has currently been on Comute boykov_kolmogorov_max_flow since 23:10:14.

**Comment by Sarngond** [comment]
should I just stop the process cuz it's still going.

**Comment by Sarngond** [comment]
I went ahead and stopped it.

**Comment by Sarngond** [comment]
does anyone know why it was taking so long?

**Comment by simogasp** [comment]
can you share your images in private (alicevision-team@googlegroups.com)?
@fabiencastan @yann-lty @gregoire-dl will try to launch it and debug it as soon as they are back from SIGGRAPH.

**Comment by fabiencastan** [comment]
How much RAM do you have on your machine?
You should reduce the value of `maxPoints` to avoid using too much RAM & SWAP.

**Comment by fabiencastan** [comment]
It's a parameter of the Meshing node.
If you have 12GB, you definitely need to reduce this value.
We should add something to adapt to your machine resources, but in our use case we compute on renderfarm and use some constraints to get machines with >= 32GB.
I don't know the exact mapping from this value to the RAM needed. So you should try 1000000 first, and then 2000000 which should be fine too.

**Comment by urgaylol** [comment]
can you change the value while it's running and it will continue the process, but start the meshing with the new value? or are you supposed to stop everything, modify the value and then start it again?

**Comment by fabiencastan** [comment]
@Sarngond : Does this allow you to compute the Meshing node?

@urgaylol : If you change the parameters of a node while the node is being computed, the parameter changes will have no impact on the current computation.

**Comment by cyberprodigy** [comment]
In latest MeshRoom, double clicking Meshing node and lowering values helped me to get further 
![image](https://user-images.githubusercontent.com/1835465/56078323-f5403d80-5de6-11e9-85ec-694e37191295.png)

I went pretty low. I am not an expert but I think the lower you go, the less ram it will use, so play around with it.

**Comment by brothermechanic** [comment]
> In latest MeshRoom, double clicking Meshing node and lowering values helped me to get further
> ![image](https://user-images.githubusercontent.com/1835465/56078323-f5403d80-5de6-11e9-85ec-694e37191295.png)
> 
> I went pretty low. I am not an expert but I think the lower you go, the less ram it will use, so play around with it.
Same issue - looong time meshing 
Thank you for workaround!
