### ISSUE TITLE
[bug] aliceVision_imageProcessing node fails

### ISSUE THREAD

**Issue by 4CJ7T** [alicevision/Meshroom#1957]
The module is working in release 2021.1.0 but not 2023.1.0.

OS: Windows 11

![graph](https://user-images.githubusercontent.com/108303308/229998147-687f8e33-0a73-438e-b3a4-a3bc0aad5c21.jpg)

**Comment by 4CJ7T** [comment]
Trying to run SfM at half resolution to save time then scale the intrinsics for dense reconstruction.

**Comment by cbentejac** [comment]
Hi @4CJ7T,

Thanks for raising this issue! 

There's indeed been a problem with the packaging of the Windows release that caused the ImageProcessing node to always fail.

The Windows release has been correctly re-packaged and re-uploaded, so [downloading it again](https://www.fosshub.com/Meshroom.html?dwl=Meshroom-2023.1.0-win64.zip) should fix the issue.
