### ISSUE TITLE
About the error message at the FeatureMatching step

### ISSUE THREAD

**Issue by takwaiservice** [alicevision/meshroom#196]
Hi,

I try the software, there is a error message at the FeatureMatching step, How to solve this problem.

Thank you.
![error](https://user-images.githubusercontent.com/20833371/44295118-52760480-a2d5-11e8-8b1e-d3e49e82a83a.jpg)

**Comment by ChemicalXandco** [comment]
All this means is that is can't find the Alice vision Executable. Go to `Meshroom-2018.1.0/aliceVision/bin`; is there a file called `aliceVision_featureMatching.exe`?

**Comment by fabiencastan** [comment]
@takwaiservice Could you show the log tab?
