### ISSUE TITLE
More meaningful "Failed to import images" and more robust JPG reader

### ISSUE THREAD

**Issue by chuong** [alicevision/Meshroom#1977]
**Is your feature request related to a problem? Please describe.**
First, Meshroom has been a great tool for image-based 3D reconstruction. The new version 2023 is even better than before. Below is just a request to further improve user experience.

If Meshroom fails to import any images, it will cancel the process and display this error window without further detail what and why images failed to import.
<img width="548" alt="image" src="https://user-images.githubusercontent.com/776061/231612526-a4cc45b8-fac0-431f-969f-dc91be87ebc0.png">

This is very frustrated for user to know how to solve the problem.

More low-cost phones are used by science citizens to collect image data, but the images often fail to import into Meshroom, although they can be viewed without any issue on Windows or Linux.

**Describe the solution you'd like**
At least Meshroom says what image(s) fails to import. Even better, it continues to import the remaining images if possible so that a reconstruction could be done.

The best solution is to use a more robust JPG reader that can read all images that can be viewed using the default image viewer on Windows or Linux.

**Describe alternatives you've considered**
Image Magick and Bad Peggy could be used to find out what images causes the issue. However this is not always reliable. Some images pass the check but still fail to import into Meshroom.

Running this command in the image folder could correct some issues, but not always:
`magick mogrify -format jpg *.jpg `

Converting JPG to PNG format will solve some of the issues but this strips out EXIF metadata and leads to lower reconstruction quality.
`magick mogrify -format png *.jpg `

Below image captured by an OPPO phone is an example that Bad Peggy says "not damaged", but still fails to import into Meshroom (even after converting to PNG by Image Magick). Tested with Meshroom v2023 on Windows.
![IMG20230411165545](https://user-images.githubusercontent.com/776061/231613730-357a28bc-6485-4b3f-84d0-e21c1dd04428.jpg)

**Comment by triforcely** [comment]
I have tried to use Meshroom for the first time today, took some photos with my OnePlus 9 Pro and all of the photos fail with this exact message when I try to import them to Meshroom.

**Comment by Jojo-1000** [comment]
Related issue on alicevision: https://github.com/alicevision/AliceVision/issues/1411

I can confirm that simply adding 'a' to the end of filenames (and a full path without special characters) seems to fix the import

**Comment by downace** [comment]
> I can confirm that simply adding 'a' to the end of filenames (and a full path without special characters) seems to fix the import

I spent a few hours to figure this out 🤦
My files were named like `IMG20230509212509.jpg`, path like `C:\Users\me\Downloads\masha`, no special characters in path. Nothing special at all.

Batch renaming software helps (e.g. add space after filename: `IMG20230509212509 mg.jpg`).

BTW, when special characters were present, Meshroom just crashes (already reported in #1988).

**Comment by cbentejac** [comment]
Hi, the issue you encountered when attempting to import images from your phone is indeed the same as alicevision/AliceVision#1411 and it will be fixed with alicevision/AliceVision#1565: the large numbers in the filenames were causing an unhandled exception, which in return prompted Meshroom to display that generic (and in that case, misleading) error.

Improving those messages in on the to-do list, but alicevision/AliceVision#1565 should probably eliminate a good 95% of them :)

**Comment by chuong** [comment]
I confirm that we can get around the error but renaming the image files. I use this one line Bash script for this purpose:
`$ ls -v | cat -n | while read n f; do mv -n "$f" "$n.jpg"; done`
