### ISSUE TITLE
Meshroon building question

### ISSUE THREAD

**Issue by fbi369123456** [alicevision/meshroom#198]
My Building Environment is in Ubuntu 16.04

I have compile and build AliceVision successfully, but I dont know how to conect with Meshroom.

My step is :
1. export two environment variable ALICEVISION_SENSOR_DB and ALICEVISION_VOCTREE
2. Because the AliceVision is install in /usr/local so I don't know I have added AliceVision Path or not.
3. Use command pip install -r requirements.txt -r dev_requirements.txt
4. Trying to start 3d Reconstruction python bin/meshroom_photogrammetry --input INPUT_IMAGES_FOLDER --output OUTPUT_FOLDER

I get these error message

Traceback (most recent call last):
  File "bin/meshroom_photogrammetry", line 4, in <module>
    import meshroom
ImportError: No module named meshroom

PS. I don't need GUI only command Line, so I didn't use QT Plugin.

If anyone can ask this question, I will very appreciate.

**Comment by fabiencastan** [comment]
You just need to set your PYTHONPATH to the root folder of meshroom to provide the meshroom module to Python.

**Comment by fbi369123456** [comment]
Thanks a lot it work.
