### ISSUE TITLE
Does Meshroom support spherical panoramic images?

### ISSUE THREAD

**Issue by happyfrank** [alicevision/meshroom#199]
Hello Dear all Does Meshroom support spherical panoramic images?

**Comment by Powerbyte7** [comment]
As of now, it doesn't. It relies on metadata like the sensor size and focal length to obtain a solid reconstruction of the scene.

**Comment by simogasp** [comment]
there is a support for 360 images in AliceVision, the library Meshroom relies on.
https://github.com/alicevision/AliceVision/blob/develop/src/software/utils/main_split360Images.cpp

This enables you to split your panoramic image into many images to be processed through the normal pipeline.
I don't think that this is dealt with automatically in meshroom, though @yann-lty

**Comment by ejnaren** [comment]
Is there a roadmap somewhere where we could upvote this feature? Would be very handy for interiors.

**Comment by jeffreyianwilson** [comment]
I am a strong believer in this feature for environment production work.  I have had varying degrees of success with Photoscan in the past.

**Comment by jjisnow** [comment]
#526 mentions that splitting the 360 image works, via Meshroom-2019.1.0\aliceVision\bin\aliceVision_utils_split360Images.exe (cli only, thanks @natowi) - I've tried it and it works!

**Comment by natowi** [comment]
`Does Meshroom support spherical panoramic images`
The question has been answered. For any other/new questions, please open a new issue.
