### ISSUE TITLE
Error in FeatureExtraction

### ISSUE THREAD

**Issue by marcpetit** [alicevision/meshroom#200]
Hi,

I have unzipped the Windows bin version (Meshroom-2018.1.0) and used it with a set of photos from my phone. Processing stops with feature exrtaction going red.

Here is the **log**

Program called with the following parameters:
 * describerPreset = "normal"
 * describerTypes = "sift"
 * forceCpuExtraction = 1
 * input = "C:/Outils/3D/Faucon/MeshroomCache/CameraInit/b132e17a58e3601eea5abdaa344f1346f6b54b21/cameraInit.sfm"
 * maxThreads = 0 (default)
 * output = "C:/Outils/3D/Faucon/MeshroomCache/FeatureExtraction/03a494fec77274562fba453187c65a60721ac327"
 * rangeSize = 17
 * rangeStart = 0
 * verboseLevel = "info"

[13:32:39.431252][info] Extracting sift features from view 'C:/Outils/3D/Faucon/20180816_121442.jpg' [cpu]
[13:32:39.433247][info] Extracting sift features from view 'C:/Outils/3D/Faucon/20180816_121429.jpg' [cpu]
[13:32:39.464165][info] Extracting sift features from view 'C:/Outils/3D/Faucon/20180816_121518.jpg' [cpu]
[13:32:39.479124][info] Extracting sift features from view 'C:/Outils/3D/Faucon/20180816_121409.jpg' [cpu]
[13:32:39.496079][info] Extracting sift features from view 'C:/Outils/3D/Faucon/20180816_121437.jpg' [cpu]
[13:32:39.506053][info] Extracting sift features from view 'C:/Outils/3D/Faucon/20180816_121424.jpg' [cpu]
[13:32:39.538964][info] Extracting sift features from view 'C:/Outils/3D/Faucon/20180816_121524.jpg' [cpu]
[13:32:39.539962][info] Extracting sift features from view 'C:/Outils/3D/Faucon/20180816_121413.jpg' [cpu]

And here is the **Status** : 

{
    "status": "ERROR",
    "execMode": "LOCAL",
    "nodeName": "FeatureExtraction_1",
    "nodeType": "FeatureExtraction",
    "packageName": "aliceVision",
    "packageVersion": null,
    "graph": "",
    "commandLine": "aliceVision_featureExtraction  --input \"C:/Outils/3D/Faucon/MeshroomCache/CameraInit/b132e17a58e3601eea5abdaa344f1346f6b54b21/cameraInit.sfm\" --describerTypes sift --describerPreset normal --forceCpuExtraction True --verboseLevel info --output \"C:/Outils/3D/Faucon/MeshroomCache/FeatureExtraction/03a494fec77274562fba453187c65a60721ac327\" --rangeStart 0 --rangeSize 17",
    "env": null,
    "startDateTime": "2018-08-20 13:32:37.804604",
    "endDateTime": "",
    "elapsedTime": 0,
    "hostname": "DESKTOP-6QIORMF",
    "sessionUid": "973cd798-a46c-11e8-a833-a434d9395237",
    "returnCode": 3221225477,
    "elapsedTimeStr": "0:00:00"
}

This is my first try at AliceVision/Meshroom, so a configuration issue is possible.

Thank you for any help.

Marc

**Comment by marcpetit** [comment]
Hi,

for some reason my laptop has rebooted while I was not here. I've relaunched meshroom and activated the trace level for FeatureExtraction and ... it worked. I don't know if the reboot did anything yet since distribution is zip based I don't expect a reboot should be needed.

I'm now stucked at the DepthMap phase for my gfx card is not recognized as a CUDA one so I guess I'll just install the SDK. If it doesn't work I'll create a new request for this probably is related.

Thank you for the fast answer.

**Comment by fabiencastan** [comment]
Yes, reboot is not required. So that's strange!
Yes, for the depth maps, you probably need to update your drivers.
Let us know if it works for you.

**Comment by marcpetit** [comment]
It now works but only reconstructs from 3 photos while I have 16. I probably need to change some parameters but there are many and I now need to figure them out.

**Comment by fabiencastan** [comment]
The most critical parameter is on FeatureExtraction, you should try to set describerPreset to HIGH.

**Comment by marcpetit** [comment]
I've tried several sets of parameters (describerPreset to high and even ultra) and never got more than 3 pictures reconstructed. When I try to get some parameters too high I even have some steps in error.

This is just a toy case (the Millenium Falcon from SIGGRAPH's expo) in order to get started with Meshroom. It may be a bit tricky (the model was in a glass showcase so there are reflections) but I think it's interesting in order to see how Meshroom actually behaves (sensitivity to reflections, error reporting, easiness of configuration ...). If you're interested I can send you the photos (approx. 50MB).

**Comment by scientes** [comment]
Have the Same /similar problem:
My workflow:
1. Shot by canon5dmk2 with 50mm 1.8 stm II lens with dual iso (the room was pretty dark)
2. Processed dual iso
3. Color correction through Adobe camera raw (exported to jpeg with all metadata enabled)
4. started meshroom 2018.1.0 (latest release)

Log:

Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, ExportUndistortedImages, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[QtOIIO] Plugin Initialized
[DepthMapEntity] DepthMapEntity
Failed to download scene at QUrl("")
Program called with the following parameters:
 * allowIncompleteOutput = 1
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraModel = 2 (default)
 * imageFolder = "" (default)
 * input = "C:\Users\Scientes\AppData\Local\Temp\tmpp58c5irt/CameraInit/2731003bd822aa3d98acd3185af7e6a65750fcd4//viewpoints.sfm"
 * output = "C:/Users/Scientes/AppData/Local/Temp/tmpp58c5irt/CameraInit/2731003bd822aa3d98acd3185af7e6a65750fcd4/cameraInit.sfm"
 * sensorDatabase = "C:\Users\Scientes\Downloads\Meshroom-2018.1.0\aliceVision\share\aliceVision\cameraSensors.db"
 * verboseLevel = "info"

[19:03:21.965785][info] CameraInit report:
        - # views listed in SfMData: 48
        - # views with an initialized intrinsic listed in SfMData: 48
        - # intrinsics listed in SfMData: 2
Nodes to execute:  ['CameraInit_1', 'FeatureExtraction_1', 'ImageMatching_1', 'FeatureMatching_1', 'StructureFromMotion_1', 'PrepareDenseScene_1', 'CameraConnection_1', 'DepthMap_1', 'DepthMapFilter_1', 'Meshing_1', 'MeshFiltering_1', 'Texturing_1']

[1/12] CameraInit
 - commandLine: aliceVision_cameraInit  --sensorDatabase "C:\Users\Scientes\Downloads\Meshroom-2018.1.0\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --verboseLevel info --output "D:/meshfiles/MeshroomCache/CameraInit/a9b96b690fc621305c9e348abf193e345180f578/cameraInit.sfm" --allowSingleView 1  --input "D:/meshfiles/MeshroomCache/CameraInit/a9b96b690fc621305c9e348abf193e345180f578//viewpoints.sfm"
 - logFile: D:/meshfiles/MeshroomCache/CameraInit/a9b96b690fc621305c9e348abf193e345180f578/log
 - elapsed time: 0:00:00.579954

[2/12](1/2) FeatureExtraction
 - commandLine: aliceVision_featureExtraction  --input "D:/meshfiles/MeshroomCache/CameraInit/a9b96b690fc621305c9e348abf193e345180f578/cameraInit.sfm" --describerTypes sift --describerPreset normal --forceCpuExtraction True --verboseLevel trace --output "D:/meshfiles/MeshroomCache/FeatureExtraction/a28c7d0c861d0ba74bb25cd7812cf9da6735b189" --rangeStart 0 --rangeSize 40
 - logFile: D:/meshfiles/MeshroomCache/FeatureExtraction/a28c7d0c861d0ba74bb25cd7812cf9da6735b189/0.log
 - elapsed time: 0:00:16.227244
ERROR:root:Error on node computation: Error on node "FeatureExtraction_1(0)":
Log:
Program called with the following parameters:
 * describerPreset = "normal"
 * describerTypes = "sift"
 * forceCpuExtraction = 1
 * input = "D:/meshfiles/MeshroomCache/CameraInit/a9b96b690fc621305c9e348abf193e345180f578/cameraInit.sfm"
 * maxThreads = 0 (default)
 * output = "D:/meshfiles/MeshroomCache/FeatureExtraction/a28c7d0c861d0ba74bb25cd7812cf9da6735b189"
 * rangeSize = 40
 * rangeStart = 0
 * verboseLevel = "trace"

[19:04:16.387241][debug] Job max memory consumption: 1611764072 B
[19:04:16.389239][debug] Memory information:
        - Total RAM:  15.9617 GB
        - Free RAM:   10.9344 GB
        - Total swap: 131072 GB
        - Free swap:  131068 GB

[19:04:16.393239][debug] # threads for extraction: 6
[19:04:18.779207][info] Extracting sift features from view 'D:/Pictures/source/test/_MG_0837.jpg' [cpu]
[19:04:19.045203][info] Extracting sift features from view 'D:/Pictures/source/test/_MG_0798.jpg' [cpu]
[19:04:19.055204][info] Extracting sift features from view 'D:/Pictures/source/test/_MG_0867.jpg' [cpu]
[19:04:19.083203][info] Extracting sift features from view 'D:/Pictures/source/test/_MG_0936.jpg' [cpu]
[19:04:19.269201][info] Extracting sift features from view 'D:/Pictures/source/test/_MG_0828.jpg' [cpu]
[19:04:19.287200][info] Extracting sift features from view 'D:/Pictures/source/test/_MG_0924.jpg' [cpu]

WARNING: downgrade status on node "FeatureExtraction_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "ImageMatching_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureMatching_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureMatching_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureMatching_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "StructureFromMotion_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "PrepareDenseScene_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "CameraConnection_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(11)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(12)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(13)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(14)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(15)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "FeatureExtraction_1(0)":
Log:
Program called with the following parameters:
 * describerPreset = "normal"
 * describerTypes = "sift"
 * forceCpuExtraction = 1
 * input = "D:/meshfiles/MeshroomCache/CameraInit/a9b96b690fc621305c9e348abf193e345180f578/cameraInit.sfm"
 * maxThreads = 0 (default)
 * output = "D:/meshfiles/MeshroomCache/FeatureExtraction/a28c7d0c861d0ba74bb25cd7812cf9da6735b189"
 * rangeSize = 40
 * rangeStart = 0
 * verboseLevel = "trace"

[19:04:16.387241][debug] Job max memory consumption: 1611764072 B
[19:04:16.389239][debug] Memory information:
        - Total RAM:  15.9617 GB
        - Free RAM:   10.9344 GB
        - Total swap: 131072 GB
        - Free swap:  131068 GB

[19:04:16.393239][debug] # threads for extraction: 6
[19:04:18.779207][info] Extracting sift features from view 'D:/Pictures/source/test/_MG_0837.jpg' [cpu]
[19:04:19.045203][info] Extracting sift features from view 'D:/Pictures/source/test/_MG_0798.jpg' [cpu]
[19:04:19.055204][info] Extracting sift features from view 'D:/Pictures/source/test/_MG_0867.jpg' [cpu]
[19:04:19.083203][info] Extracting sift features from view 'D:/Pictures/source/test/_MG_0936.jpg' [cpu]
[19:04:19.269201][info] Extracting sift features from view 'D:/Pictures/source/test/_MG_0828.jpg' [cpu]
[19:04:19.287200][info] Extracting sift features from view 'D:/Pictures/source/test/_MG_0924.jpg' [cpu]

**Comment by natowi** [comment]
@scientes I downloaded your dataset and don´t get any error messages. However only two images are being used in the default pipeline. With FeatureDetection Describer+AKAZE +High ->21 matched images.
Result: 
![img3d](https://user-images.githubusercontent.com/8138537/47260053-47497b80-d4b4-11e8-94e3-ca2b8fab5e4f.JPG)
In general: your dataset is unsuitable (blurry, rotated object with shadows,...).

**Comment by ShekharSahu** [comment]
Hi, @marcpetit did you resolve this error? If yes, please share.

**Comment by tuthyisernhagen** [comment]
Please help

**Comment by fabiencastan** [comment]
@tuthyisernhagen Could you launch the FeatureExtraction with `verbose=trace` and send the "log" file?
Would be also useful to send the "statistics" and "status" files.

**Comment by remmel** [comment]
Hello,

I have the same problem (using a OVH cloud GPU) with Windows Server 2019, below is the verbose trace.
Please note that I ran that exact photos on another AWS instance and it was ok. So maybe it become from the virtualization. The only thing I installed is : [Nvidia CUDA](https://developer.nvidia.com/cuda-zone) driver (not the nvidia driver) and meshroom. That's it.
(using Mushroom 2019.2.0)

Thanks!
```
Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportColoredPointCloud, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, LDRToHDR, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
WARNING:root:glPointSize() and GL_PROGRAM_POINT_SIZE are not supported by ES 2.0
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:\Users\Administrator\AppData\Local\Temp\2\tmp032695g3/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm"
 * output = "C:/Users/Administrator/AppData/Local/Temp/2/tmp032695g3/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm"
 * sensorDatabase = "C:\Users\Administrator\Downloads\Meshroom-2019.2.0-win64\Meshroom-2019.2.0\aliceVision\share\aliceVision\cameraSensors.db"
 * verboseLevel = "info"

[10:30:44.784102][warning] Some image(s) have no serial number to identify the camera/lens device.
This makes it impossible to correctly group the images by device if you have used multiple identical (same model) camera devices.
The reconstruction will assume that only one device has been used, so if 2 images share the same focal length approximation they will share the same internal camera parameters.
26 image(s) are concerned.
[10:30:44.819868][info] CameraInit report:
        - # views listed: 26
           - # views with an initialized intrinsic listed: 26
           - # views without metadata (with a default intrinsic): 0
        - # intrinsics listed: 2
Nodes to execute:  ['CameraInit_1', 'FeatureExtraction_1', 'ImageMatching_1', 'FeatureMatching_1', 'StructureFromMotion_1', 'PrepareDenseScene_1', 'DepthMap_1', 'DepthMapFilter_1', 'Meshing_1', 'MeshFiltering_1', 'Texturing_1']

[1/11] CameraInit
 - commandLine: aliceVision_cameraInit  --sensorDatabase "C:\Users\Administrator\Downloads\Meshroom-2019.2.0-win64\Meshroom-2019.2.0\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/CameraInit/11b1209ff142313a4d4c6f8c24f76af252461753/cameraInit.sfm" --allowSingleView 1  --input "C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/CameraInit/11b1209ff142313a4d4c6f8c24f76af252461753//viewpoints.sfm"
 - logFile: C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/CameraInit/11b1209ff142313a4d4c6f8c24f76af252461753/log
 - elapsed time: 0:00:00.347852

[2/11] FeatureExtraction
 - commandLine: aliceVision_featureExtraction  --input "C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/CameraInit/11b1209ff142313a4d4c6f8c24f76af252461753/cameraInit.sfm" --describerTypes sift --describerPreset normal --forceCpuExtraction True --verboseLevel info --output "C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/FeatureExtraction/19b691c5e22e47ec4446b6bd743719a4498d53a3" --rangeStart 0 --rangeSize 40
 - logFile: C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/FeatureExtraction/19b691c5e22e47ec4446b6bd743719a4498d53a3/0.log
 - elapsed time: 0:00:26.943338
ERROR:root:Error on node computation: Error on node "FeatureExtraction_1(0)":
Log:
Program called with the following parameters:
 * describerPreset = "normal"
 * describerTypes = "sift"
 * forceCpuExtraction = 1
 * input = "C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/CameraInit/11b1209ff142313a4d4c6f8c24f76af252461753/cameraInit.sfm"
 * maxThreads = 0 (default)
 * output = "C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/FeatureExtraction/19b691c5e22e47ec4446b6bd743719a4498d53a3"
 * rangeSize = 40
 * rangeStart = 0
 * verboseLevel = "info"

[10:30:56.932599][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce GTX 1080 Ti
        - compute capability:      6.1
        - total device memory:     11264 MB
        - device memory available: 9294 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   2048
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {131072,65536}
        - max 3D array texture:    {16384,16384,16384}
        - max 2D linear texture:   {131072,65000,2097120}
        - max 2D layered texture:  {32768,32768,2048}
        - number of SM(x)s:        28
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte

[10:30:57.254519][info] Supported CUDA-Enabled GPU detected.
[10:31:00.092402][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171812.jpg' [cpu]
[10:31:00.158791][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171708.jpg' [cpu]
[10:31:00.313062][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171514.jpg' [cpu]
[10:31:00.616673][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171637.jpg' [cpu]
[10:31:00.834340][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171534.jpg' [cpu]
[10:31:01.238273][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171554.jpg' [cpu]
[10:31:01.385188][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171531.jpg' [cpu]
[10:31:01.427273][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171625.jpg' [cpu]

WARNING: downgrade status on node "ImageMatching_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureMatching_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureMatching_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "StructureFromMotion_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "PrepareDenseScene_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "FeatureExtraction_1(0)":
Log:
Program called with the following parameters:
 * describerPreset = "normal"
 * describerTypes = "sift"
 * forceCpuExtraction = 1
 * input = "C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/CameraInit/11b1209ff142313a4d4c6f8c24f76af252461753/cameraInit.sfm"
 * maxThreads = 0 (default)
 * output = "C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/FeatureExtraction/19b691c5e22e47ec4446b6bd743719a4498d53a3"
 * rangeSize = 40
 * rangeStart = 0
 * verboseLevel = "info"

[10:30:56.932599][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce GTX 1080 Ti
        - compute capability:      6.1
        - total device memory:     11264 MB
        - device memory available: 9294 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   2048
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {131072,65536}
        - max 3D array texture:    {16384,16384,16384}
        - max 2D linear texture:   {131072,65000,2097120}
        - max 2D layered texture:  {32768,32768,2048}
        - number of SM(x)s:        28
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte

[10:30:57.254519][info] Supported CUDA-Enabled GPU detected.
[10:31:00.092402][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171812.jpg' [cpu]
[10:31:00.158791][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171708.jpg' [cpu]
[10:31:00.313062][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171514.jpg' [cpu]
[10:31:00.616673][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171637.jpg' [cpu]
[10:31:00.834340][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171534.jpg' [cpu]
[10:31:01.238273][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171554.jpg' [cpu]
[10:31:01.385188][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171531.jpg' [cpu]
[10:31:01.427273][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171625.jpg' [cpu]

Nodes to execute:  ['FeatureExtraction_1', 'ImageMatching_1', 'FeatureMatching_1', 'StructureFromMotion_1', 'PrepareDenseScene_1', 'DepthMap_1', 'DepthMapFilter_1', 'Meshing_1', 'MeshFiltering_1', 'Texturing_1']

[1/10] FeatureExtraction
 - commandLine: aliceVision_featureExtraction  --input "C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/CameraInit/11b1209ff142313a4d4c6f8c24f76af252461753/cameraInit.sfm" --describerTypes sift --describerPreset ultra --forceCpuExtraction True --verboseLevel info --output "C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/FeatureExtraction/f057d2837ff98da331f84b3928ea67d0472360d0" --rangeStart 0 --rangeSize 40
 - logFile: C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/FeatureExtraction/f057d2837ff98da331f84b3928ea67d0472360d0/0.log
 - elapsed time: 0:00:57.836806
ERROR:root:Error on node computation: Error on node "FeatureExtraction_1(0)":
Log:
Program called with the following parameters:
 * describerPreset = "ultra"
 * describerTypes = "sift"
 * forceCpuExtraction = 1
 * input = "C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/CameraInit/11b1209ff142313a4d4c6f8c24f76af252461753/cameraInit.sfm"
 * maxThreads = 0 (default)
 * output = "C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/FeatureExtraction/f057d2837ff98da331f84b3928ea67d0472360d0"
 * rangeSize = 40
 * rangeStart = 0
 * verboseLevel = "info"

[10:31:47.516279][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce GTX 1080 Ti
        - compute capability:      6.1
        - total device memory:     11264 MB
        - device memory available: 9294 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   2048
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {131072,65536}
        - max 3D array texture:    {16384,16384,16384}
        - max 2D linear texture:   {131072,65000,2097120}
        - max 2D layered texture:  {32768,32768,2048}
        - number of SM(x)s:        28
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte

[10:31:47.814891][info] Supported CUDA-Enabled GPU detected.
[10:31:49.464963][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171708.jpg' [cpu]
[10:31:49.595071][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171537.jpg' [cpu]

WARNING: downgrade status on node "ImageMatching_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureMatching_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureMatching_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "StructureFromMotion_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "PrepareDenseScene_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "FeatureExtraction_1(0)":
Log:
Program called with the following parameters:
 * describerPreset = "ultra"
 * describerTypes = "sift"
 * forceCpuExtraction = 1
 * input = "C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/CameraInit/11b1209ff142313a4d4c6f8c24f76af252461753/cameraInit.sfm"
 * maxThreads = 0 (default)
 * output = "C:/Users/Administrator/Downloads/meshroom_calendar/MeshroomCache/FeatureExtraction/f057d2837ff98da331f84b3928ea67d0472360d0"
 * rangeSize = 40
 * rangeStart = 0
 * verboseLevel = "info"

[10:31:47.516279][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce GTX 1080 Ti
        - compute capability:      6.1
        - total device memory:     11264 MB
        - device memory available: 9294 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   2048
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {131072,65536}
        - max 3D array texture:    {16384,16384,16384}
        - max 2D linear texture:   {131072,65000,2097120}
        - max 2D layered texture:  {32768,32768,2048}
        - number of SM(x)s:        28
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte

[10:31:47.814891][info] Supported CUDA-Enabled GPU detected.
[10:31:49.464963][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171708.jpg' [cpu]
[10:31:49.595071][info] Extracting sift features from view 'C:/Users/Administrator/Downloads/photos/IMG_20200429_171537.jpg' [cpu]

```
