### ISSUE TITLE
Error on PrepareDenseScene

### ISSUE THREAD

**Issue by fbi369123456** [alicevision/meshroom#201]
Hi

It's my first time to build AliceVision on Ubuntu.
I execute meshroom_photogrammetry, but I get some error message:

Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, ExportUndistortedImages, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[2018-08-20 21:53:10,613][WARNING] == The following plugins could not be loaded ==
  * simpleFarmSubmitter: No module named simpleFarm

Nodes to execute:  ['PrepareDenseScene_1', 'CameraConnection_1', 'DepthMap_1', 'DepthMapFilter_1', 'Meshing_1', 'MeshFiltering_1', 'Texturing_1', 'Publish_1']
WARNING: downgrade status on node "PrepareDenseScene_1" from Status.ERROR to Status.SUBMITTED

[1/8] PrepareDenseScene
 - commandLine: aliceVision_prepareDenseScene  --verboseLevel info --input "/tmp/MeshroomCache/StructureFromMotion/5fd83ae248840110951facebccadef96408ecd47/sfm.abc" --output "/tmp/MeshroomCache/PrepareDenseScene/22a9cbadff4985d800dd07ceeee7bbb8c6033312" 
 - logFile: /tmp/MeshroomCache/PrepareDenseScene/22a9cbadff4985d800dd07ceeee7bbb8c6033312/log
(' - elapsed time:', '0:00:00.168711')
[2018-08-20 21:53:10,881][ERROR] Error on node computation: Error on node "PrepareDenseScene_1":
Log:
Program called with the following parameters:
 * input = "/tmp/MeshroomCache/StructureFromMotion/5fd83ae248840110951facebccadef96408ecd47/sfm.abc"
 * output = "/tmp/MeshroomCache/PrepareDenseScene/22a9cbadff4985d800dd07ceeee7bbb8c6033312"
 * verboseLevel = "info"

terminate called after throwing an instance of 'std::runtime_error'
  what():  Can't open '/tmp/MeshroomCache/StructureFromMotion/5fd83ae248840110951facebccadef96408ecd47/sfm.abc' : Alembic file is not valid.
Aborted (core dumped)

WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "CameraConnection_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(11)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Publish_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
Traceback (most recent call last):
  File "bin/meshroom_photogrammetry", line 64, in <module>
    meshroom.core.graph.executeGraph(graph, toNodes=toNodes, forceCompute=args.forceCompute, forceStatus=args.forceStatus)
  File "/home/yueh/meshroom/meshroom/core/graph.py", line 1124, in executeGraph
    chunk.process(forceCompute)
  File "/home/yueh/meshroom/meshroom/core/node.py", line 271, in process
    self.node.nodeDesc.processChunk(self)
  File "/home/yueh/meshroom/meshroom/core/desc.py", line 407, in processChunk
    raise RuntimeError('Error on node "{}":\nLog:\n{}'.format(chunk.name, logContent))
RuntimeError: Error on node "PrepareDenseScene_1":
Log:
Program called with the following parameters:
 * input = "/tmp/MeshroomCache/StructureFromMotion/5fd83ae248840110951facebccadef96408ecd47/sfm.abc"
 * output = "/tmp/MeshroomCache/PrepareDenseScene/22a9cbadff4985d800dd07ceeee7bbb8c6033312"
 * verboseLevel = "info"

terminate called after throwing an instance of 'std::runtime_error'
  what():  Can't open '/tmp/MeshroomCache/StructureFromMotion/5fd83ae248840110951facebccadef96408ecd47/sfm.abc' : Alembic file is not valid.
Aborted (core dumped)

Here is my cmake command

cmake -DCMAKE_BUILD_TYPE=Release -DALICEVISION_BUILD_TESTS=ON -DALICEVISION_USE_CUDA=OFF -DALICEVISION_USE_ALEMBIC=ON -DALICEVISION_BUILD_EXAMPLES=ON ..

I have checked the Alembic ON and I confirmed that Alembic be compiled.

In the SFM Log File, I got some message:

[20:51:11.088121][info] Structure from motion took (s): 9.740000
[20:51:11.088154][info] Generating HTML report...
[20:51:11.094355][info] Export SfMData to disk: /tmp/MeshroomCache/StructureFromMotion/5fd83ae248840110951facebccadef96408ecd47/sfm.abc
[20:51:11.094394][error] Cannot save the SfM data file: '/tmp/MeshroomCache/StructureFromMotion/5fd83ae248840110951facebccadef96408ecd47/cloud_and_poses.abc'.
The file extension is not recognized.
[20:51:11.094407][error] Cannot save the SfM data file: '/tmp/MeshroomCache/StructureFromMotion/5fd83ae248840110951facebccadef96408ecd47/sfm.abc'.
The file extension is not recognized.

It seems that the data file can not save, but why?

If anyone can tell me how to fix this problem I will appreciate.
Thanks.

**Comment by fabiencastan** [comment]
I recommend you to save your scene first.
It would be interesting to see if the Alembic file is valid and can be open in meshroom, or another 3D software. The problem is probably on the StructureFromMotion node.
But currently, this file is in /tmp so it has been removed if you have reboot:
/tmp/MeshroomCache/StructureFromMotion/5fd83ae248840110951facebccadef96408ecd47/sfm.abc

**Comment by fbi369123456** [comment]
I reboot and try it again, and it work successfully.

It seems that the pipeline corrupted, some file didn't save completely.

Thanks a lot.

**Comment by natowi** [comment]
Same problem, but reboot / clear cache/temp did not work and Alembic file can not be opened in meshroom. Any ideas?

StructureFromMotion (ok)
Structure from Motion results:
        - # input images: 7
	- # cameras calibrated: 7
	- # landmarks: 2094
----
PrepareDenseScene Log:
[trace] 7 extrinsics declared and 7 extrinsics used.
Exporting Scene Data
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
--------

----
Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, ExportUndistortedImages, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[QtOIIO] Plugin Initialized
[DepthMapEntity] DepthMapEntity
Failed to download scene at QUrl("")
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: F:\GitHub\vcpkg-release\buildtrees\hdf5\src\CMake-hdf5-1.10.1\hdf5-1.10.1\src\H5F.c line 408 in H5Fis_hdf5(): unable open file
    major: File accessibilty
    minor: Not an HDF5 file
  #001: F:\GitHub\vcpkg-release\buildtrees\hdf5\src\CMake-hdf5-1.10.1\hdf5-1.10.1\src\H5Fint.c line 532 in H5F__is_hdf5(): unable to open file
    major: Low-level I/O
    minor: Unable to initialize object
  #002: F:\GitHub\vcpkg-release\buildtrees\hdf5\src\CMake-hdf5-1.10.1\hdf5-1.10.1\src\H5FD.c line 809 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: F:\GitHub\vcpkg-release\buildtrees\hdf5\src\CMake-hdf5-1.10.1\hdf5-1.10.1\src\H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = 'C:/Users/User/3D Objects/l+Âewngeb/MeshroomCache/StructureFromMotion/055af343bcebf5b989c1829a81146f3c40f1173d/sfm.abc', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
Nodes to execute:  ['PrepareDenseScene_1', 'CameraConnection_1', 'DepthMap_1', 'DepthMapFilter_1', 'Meshing_1', 'MeshFiltering_1', 'Texturing_1']
WARNING: downgrade status on node "PrepareDenseScene_1" from Status.ERROR to Status.SUBMITTED

[1/7] PrepareDenseScene
 - commandLine: aliceVision_prepareDenseScene  --input "C:/Users/User/3D Objects/löewngeb/MeshroomCache/StructureFromMotion/055af343bcebf5b989c1829a81146f3c40f1173d/sfm.abc" --verboseLevel trace --output "C:/Users/User/3D Objects/löewngeb/MeshroomCache/PrepareDenseScene/92288eea204997d3f9ae490e0b41c8653fa62ff8"
 - logFile: C:/Users/User/3D Objects/löewngeb/MeshroomCache/PrepareDenseScene/92288eea204997d3f9ae490e0b41c8653fa62ff8/log
 - elapsed time: 0:00:01.721919
ERROR:root:Error on node computation: Error on node "PrepareDenseScene_1":
Log:
Program called with the following parameters:
 * input = "C:/Users/User/3D Objects/löewngeb/MeshroomCache/StructureFromMotion/055af343bcebf5b989c1829a81146f3c40f1173d/sfm.abc"
 * output = "C:/Users/User/3D Objects/löewngeb/MeshroomCache/PrepareDenseScene/92288eea204997d3f9ae490e0b41c8653fa62ff8"
 * verboseLevel = "trace"

Exporting Scene Data
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|

WARNING: downgrade status on node "CameraConnection_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "PrepareDenseScene_1":
Log:
Program called with the following parameters:
 * input = "C:/Users/User/3D Objects/löewngeb/MeshroomCache/StructureFromMotion/055af343bcebf5b989c1829a81146f3c40f1173d/sfm.abc"
 * output = "C:/Users/User/3D Objects/löewngeb/MeshroomCache/PrepareDenseScene/92288eea204997d3f9ae490e0b41c8653fa62ff8"
 * verboseLevel = "trace"

Exporting Scene Data
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
