### ISSUE TITLE
Failed to Import Images - Meshroom 2023.1.0  You probably have a corrupted image within the images that you are trying to import.[question]

### ISSUE THREAD

**Issue by Iservei** [alicevision/Meshroom#2025]
**Describe the problem**
A clear and concise description of what the problem is.

**Screenshots**

**Dataset**
If applicable, add a link or *few* images to help better understand where the problem may come from.

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ]
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1]
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**

**Comment by mcDandy** [comment]
It happens fór mě when trying to import images from ffmpeg.

**Comment by juj46** [comment]
for feedback:

Hey 

between the Last et new version 2023, I dont use the same picture of drone Anafi . It s writte "Failed to Import Images - Meshroom 2023.1.0 You probably have a corrupted image within the images that you are trying to import." 
If  I use and copy picture directly of the memory stick no hay problem, but I use the application of drone for transfert and copy picture, it s bad.

Linux Mint 21.1 Cinemon
Python 3.10.6 


The computer 

"System: 
  Kernel: 5.15.0-73-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.6.8
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: Micro-Star model: B450M MORTAR TITANIUM (MS-7B89) v: 2.0
    serial: <superuser required> UEFI: American Megatrends LLC. v: A.H0 date: 07/27/2022
CPU:
  Info: 8-core model: AMD Ryzen 7 3700X bits: 64 type: MT MCP arch: Zen 2 rev: 0 cache:
    L1: 512 KiB L2: 4 MiB L3: 32 MiB
  Speed (MHz): avg: 2410 high: 4254 min/max: 2200/3600 boost: enabled cores: 1: 2090 2: 4185
    3: 2083 4: 2056 5: 2200 6: 2199 7: 2200 8: 2199 9: 2110 10: 4254 11: 2083 12: 2118 13: 2199
    14: 2199 15: 2199 16: 2199 bogomips: 115197
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA GP106 [GeForce GTX 1060 3GB] driver: nvidia v: 530.41.03 pcie: speed: 8 GT/s
    lanes: 16 ports: active: none off: HDMI-A-1 empty: DP-1,DVI-D-1 bus-ID: 26:00.0
    chip-ID: 10de:1c02
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 95
  Monitor-1: HDMI-0 res: 1920x1080 dpi: 96 diag: 585mm (23")
  OpenGL: renderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2 v: 4.6.0 NVIDIA 530.41.03
    direct render: Yes
Audio:
  Device-1: NVIDIA GP106 High Definition Audio driver: snd_hda_intel v: kernel pcie: speed: 8 GT/s
    lanes: 16 bus-ID: 26:00.1 chip-ID: 10de:10f1
  Device-2: AMD Starship/Matisse HD Audio vendor: Micro-Star MSI driver: snd_hda_intel v: kernel
    pcie: speed: 16 GT/s lanes: 16 bus-ID: 28:00.4 chip-ID: 1022:1487
  Sound Server-1: ALSA v: k5.15.0-73-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Micro-Star MSI
    driver: r8169 v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: f000 bus-ID: 22:00.0
    chip-ID: 10ec:8168
  IF: enp34s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Drives:
  Local Storage: total: 5.22 TiB used: 3.31 TiB (63.4%)
  ID-1: /dev/nvme0n1 vendor: Crucial model: CT1000P5PSSD8 size: 931.51 GiB speed: 63.2 Gb/s
    lanes: 4 serial: <filter> temp: 40.9 C
  ID-2: /dev/sda vendor: Western Digital model: WD15EADS-22P8B0 size: 1.36 TiB speed: 3.0 Gb/s
    serial: <filter>
  ID-3: /dev/sdb vendor: Crucial model: CT240BX500SSD1 size: 223.57 GiB speed: 6.0 Gb/s
    serial: <filter>
  ID-4: /dev/sdc vendor: Samsung model: SSD 870 QVO 1TB size: 931.51 GiB speed: 6.0 Gb/s
    serial: <filter>
  ID-5: /dev/sdd type: USB vendor: Western Digital model: WD Elements 2621 size: 1.82 TiB
    serial: <filter>
Partition:
  ID-1: / size: 569.36 GiB used: 529.3 GiB (93.0%) fs: ext4 dev: /dev/nvme0n1p5
  ID-2: /boot/efi size: 96 MiB used: 31.2 MiB (32.5%) fs: vfat dev: /dev/nvme0n1p2
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 35.2 MiB (1.7%) priority: -2 file: /swapfile
Sensors:
  System Temperatures: cpu: N/A mobo: N/A gpu: nvidia temp: 47 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 30%
Repos:
  Packages: 3345 note: see --pkg apt: 3296 flatpak: 49
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //ftp.crifo.org/mint-packages vera main upstream import backport
    2: deb http: //distrib-coffee.ipsl.jussieu.fr/pub/linux/ubuntu jammy main restricted universe multiverse
    3: deb http: //distrib-coffee.ipsl.jussieu.fr/pub/linux/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //distrib-coffee.ipsl.jussieu.fr/pub/linux/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/onedrive.list
    1: deb [arch=amd64 signed-by=/usr/share/keyrings/obs-onedrive.gpg] https: //download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/xUbuntu_22.04/ ./
  Active apt repos in: /etc/apt/sources.list.d/skype-stable.list
    1: deb [arch=amd64] https: //repo.skype.com/deb stable main
Info:
  Processes: 407 Uptime: 3h 20m Memory: 31.27 GiB used: 6.7 GiB (21.4%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.3.0 alt: 11/12 Client: Unknown python3.10 client inxi: 3.3.13"

**Comment by TomTLC** [comment]
I had same error as you but I got it sorted out!
My pics had a very long filename. I renamed all of the 200pictures to something short.

To do that. Select all your pics, press F2, rename something short and press ENTER.

After that Meshroom loaded them no problem.

**Comment by juj46** [comment]
@TomTLC Thanks you, it works good, I can restart my projects many thanks

**Comment by dalabonba** [comment]
I tried to rename and I still failed🥲

**Comment by LyesEpitech** [comment]
Same problem here.

The filename are 1.jpg, 2.jpg, etc.

**Comment by PawAlldeller** [comment]
The same problem appears .if the folder and its path contain Cyrillic characters.

**Comment by PyNitid** [comment]
Same with accentuation signs. Thanks!

**Comment by karan3242** [comment]
I am still getting this error and I don't seem to think that this is a file name issue, now that it is resolved.

**Comment by PawAlldeller** [comment]
Remove Cyrillic from the folder\photos path, rename everything to numbers.

**Comment by jamwisme** [comment]
ITS ALL BECAUSE YOUR FOTOS ARE NOT IN THE SAME DIRECTORY/ HARDDRIVE AS MESHROOM........just have all files and programm on one drive and it should be fine!
