### ISSUE TITLE
windows 10, This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0)

### ISSUE THREAD

**Issue by pyarchinit** [alicevision/meshroom#203]
On Windows 10 the process is stopped at DepthMap.

I have NVIDIA CUDA QUADRO M2000M.

Thanks a lot!!!

I post the log:

Program called with the following parameters:
 * downscale = 4
 * ini = "C:/Users/Luca/3D_project/porta_galliana/MeshroomCache/PrepareDenseScene/8054f9119cbbeb7e35809c4b011e73c96a6c19f1/mvs.ini"
 * output = "C:/Users/Luca/3D_project/porta_galliana/MeshroomCache/DepthMap/aa8bda2b29a0e42c74a8c64ffdd47fe79812c629"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[18:38:10.594433][info]
[18:38:10.598817][error] This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0).

**Comment by simogasp** [comment]
try re-installing /updating your nvidia driver
see #197

**Comment by pyarchinit** [comment]
Solved with an update.
I suggest to put this message inside the log for any newbie.
ps: the software is great! Simply as agisoft powerfull as mic mac!!!

With a georeferencing module will be the leader for SFM and GIS world.

**Comment by jansindl3r** [comment]
Update helped me with the same problem  as well
