### ISSUE TITLE
[bug] Problem using LdrToHdrSampling node with manualy selected bin count

### ISSUE THREAD

**Issue by mcDandy** [alicevision/Meshroom#2048]
**Describe the bug**
Cannot use LdrToHdrSample node with more than 1 bucket. Automatically it sellected 1 which is wrong.
**To Reproduce**
1. Get dataset with exposure bracketed images (5 images in bracket)- I used OpenCamera with these settings: Bracket count:5 Max stop: +-3
3. Create new Panorama HDR pipeline
4. import image dataset
5. set LdrToHdrSampling number of buckets to 5
6. start process
7. fail at LdrToHdrSampling  node

**Expected behavior**
The node will create HDR images as it should
**Screenshots**

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )
Node itself does not output anything to log.

https://pastebin.com/uW86dWCu

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ] windows 11
 - Python version [e.g. 2.6] 3.7.4 (I have installed 3.9 and 3.11)
 - Qt/PySide version [e.g. 5.12.4] (I do not have installed. Part of distribution, cannot check)
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1] 2023.1.0
   - Commit reference (if applicable) [e.g. 08ddbe2] n/a

**Additional context**

**Comment by cbentejac** [comment]
Hi @mcDandy,

Were you using JPG images when you encountered that issue?

**Comment by mcDandy** [comment]
Yes, I was.

Dne po 12. 6. 2023 9:37 uživatel Candice Bentéjac ***@***.***>
napsal:
