### ISSUE TITLE
Error when importing photos

### ISSUE THREAD

**Issue by Chaks243** [alicevision/meshroom#205]
When I tried to do my first scan the process stopped on FeatureExtraction and the loading bar turned red. Now when I try to import photos into the program I get this error:

Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, ExportUndistortedImages, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[QtOIIO] Plugin Initialized
[DepthMapEntity] DepthMapEntity
Failed to download scene at QUrl("")
Program called with the following parameters:
 * allowIncompleteOutput = 1
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraModel = 2 (default)
 * imageFolder = "" (default)
 * input = "C:\Users\Enric\AppData\Local\Temp\tmp9sww7ry_/CameraInit/2731003bd822aa3d98acd3185af7e6a65750fcd4//viewpoints.sfm"
 * output = "C:/Users/Enric/AppData/Local/Temp/tmp9sww7ry_/CameraInit/2731003bd822aa3d98acd3185af7e6a65750fcd4/cameraInit.sfm"
 * sensorDatabase = "D:\Software\Work\Meshroom-2018.1.0\aliceVision\share\aliceVision\cameraSensors.db"
 * verboseLevel = "info"

ERROR:root:Error while building intrinsics : Traceback (most recent call last):
  File "f:\tmp\meshroom\meshroom\ui\reconstruction.py", line 384, in buildIntrinsics
  File "f:\tmp\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 129, in buildIntrinsics
RuntimeError: CameraInit failed with error code 3221226505. Command was: "aliceVision_cameraInit  --sensorDatabase "D:\Software\Work\Meshroom-2018.1.0\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --verboseLevel info --output "C:/Users/Enric/AppData/Local/Temp/tmp9sww7ry_/CameraInit/2731003bd822aa3d98acd3185af7e6a65750fcd4/cameraInit.sfm" --allowSingleView 1  --input "C:\Users\Enric\AppData\Local\Temp\tmp9sww7ry_/CameraInit/2731003bd822aa3d98acd3185af7e6a65750fcd4//viewpoints.sfm" --allowIncompleteOutput 1"

**Comment by Chaks243** [comment]
I think it was my Antivirus, since I can now import images after Whitelisting Meshroom, however, I'm now getting this error:

WARNING: downgrade status on node "PrepareDenseScene_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "CameraConnection_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "StructureFromMotion_1":
Log:
Program called with the following parameters:
 * describerTypes = "sift"
 * extraInfoFolder = "D:/Projects/3D Models/3D Scans/Llavero Flamingo/MeshroomCache/StructureFromMotion/1f13b7d70e3a59a249617e5aaf9768eb01128845"
 * featuresFolders =  = [D:/Projects/3D Models/3D Scans/Llavero Flamingo/MeshroomCache/FeatureExtraction/102ba9c0fa5adc166576a2bb9a331bd518ae02e4]
 * initialPairA = ""
 * initialPairB = ""
 * input = "D:/Projects/3D Models/3D Scans/Llavero Flamingo/MeshroomCache/CameraInit/2fd9d9f6bfae135dbcf13f43a6cdd178d3db2e80/cameraInit.sfm"
 * interFileExtension = ".abc"
 * localBAGraphDistance = 1
 * localizerEstimator = "acransac"
 * lockScenePreviouslyReconstructed = 0
 * matchesFolders =  = [D:/Projects/3D Models/3D Scans/Llavero Flamingo/MeshroomCache/FeatureMatching/6cc14a8eda3de671840883c1bf76415c28852f37]
 * maxAngleInitialPair = 40
 * maxNumberOfMatches = 0
 * maxReprojectionError = 4
 * minAngleForLandmark = 2
 * minAngleForTriangulation = 3
 * minAngleInitialPair = 5
 * minInputTrackLength = 2
 * minNumberOfObservationsForTriangulation = 2
 * output = "D:/Projects/3D Models/3D Scans/Llavero Flamingo/MeshroomCache/StructureFromMotion/1f13b7d70e3a59a249617e5aaf9768eb01128845/sfm.abc"
 * outputViewsAndPoses = "D:/Projects/3D Models/3D Scans/Llavero Flamingo/MeshroomCache/StructureFromMotion/1f13b7d70e3a59a249617e5aaf9768eb01128845/cameras.sfm"
 * refineIntrinsics = 1 (default)
 * useLocalBA = 1
 * useOnlyMatchesFromInputFolder = 0
 * useTrackFiltering = 1 (default)
 * verboseLevel = "info"

Loading features
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[20:02:55.593258][warning] No matches file loaded in: D:/Projects/3D Models/3D Scans/Llavero Flamingo/MeshroomCache/FeatureMatching/6cc14a8eda3de671840883c1bf76415c28852f37
[20:02:55.595253][warning]      - D:/Projects/3D Models/3D Scans/Llavero Flamingo/MeshroomCache/FeatureMatching/6cc14a8eda3de671840883c1bf76415c28852f37

[20:02:55.595253][error] Unable to load matches.

**Comment by ChemicalXandco** [comment]
This error means what it says, there are no matches in that file. Try putting describer preset to High or Ultra, sift+akaze matching to get the best chance of finding matches.

**Comment by yann-lty** [comment]
@Chaks243 did you manage to go beyond FeatureMatching or are you still stuck?

**Comment by qdxizao** [comment]
> sensorDatabase "D:\Software\Work\Meshroom-2018.1.0\aliceVision\share\aliceVision\cameraSensors.db

@Chaks243 I have the same problem as you. How do you solve this problem？

**Comment by millsoft** [comment]
I have the same problem but only with some images. Especially photos taken with Samsung Galaxy S9 (Front camera). I removed the exif data using `convert -strip input.jpg output.jpt` now I can import the file into meshroom. One problem s that when I remove the exif data, my picture gets rotated, so I needed to `convert -rotate -90 output.jpt output.jpg`.

This is just a quick fix for me. If one of the devs wants to try to import that picture, [here is one of these pics](https://www.dropbox.com/s/n32j0zfc0lr7jx4/20181001_123855.jpg?dl=0).

**Comment by Fehrox** [comment]
Hey @millsoft,

Thanks for posting your solution, I'm also facing this issue having used a Samsung Galaxy S9 Front camera. Could you add a little more info to your solution; for instance, where can convert be found and how should it be run? Is this part of the Meshroom installation or some other third party application?

Thanks for taking the time to post your solution btw.

**Comment by markus-i** [comment]
Same issue here. I grabbed 20 screenshots from a 3d site as a trial, and get stuck with

Loading features
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[13:59:09.912966][warning] No matches file loaded in: D:/Markus/3dprinting/angryduck/MeshroomCache/FeatureMatching/69941c848455503b17b699db51402ac6213f85f1
[13:59:09.913966][warning] 	- D:/Markus/3dprinting/angryduck/MeshroomCache/FeatureMatching/69941c848455503b17b699db51402ac6213f85f1

[13:59:09.913966][error] Unable to load matches.

Meshroom 2018.1.0 under Windows 10, Python 3.6.5

**Comment by millsoft** [comment]
@Fehrox 

Convert is a software that is a part of [image magick](https://www.imagemagick.org/script/index.php). Meshroom tries to read the exif meta data from the images and something is not right about the exif stored in S9 images.

**Comment by ljcool2006** [comment]
This is still happening to me even with Exif data removed.
