### ISSUE TITLE
[bug] bad allocation on LdrToHdrCallibration node

### ISSUE THREAD

**Issue by mcDandy** [alicevision/Meshroom#2051]
**Describe the bug**
Bad allocation when running LdrToHdrCallibration on 1 set of images (belonging to 1 hdr image)
**To Reproduce**
1. create 5 raw images with different exposures to make 1 hdr image
2. Import to meshroom with HDR panorama pipeline
3. Run the pipeline

**Expected behavior**
It will finish creating panorama or show error that it cannot continue with 1 image

**Screenshots**

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )
```
[2023-06-12 16:18:45.902777] [0x00005194] [trace]   Embedded OCIO configuration file: 'D:\Users\Daniel Martinek\Documents\Meshroom-2023.1.0\aliceVision/share/aliceVision/config.ocio' found.
Program called with the following parameters:
 * byPass = 0
 * calibrationMethod =  Unknown Type "enum aliceVision::hdr::ECalibrationMethod"
 * calibrationWeight = "default"
 * channelQuantizationPower = 10
 * input = "D:/a/v/a/MeshroomCache/PanoramaPrepareImages/e5d0a20b5f6c5975756b02b4c44f27ee333be448/cameraInit.sfm"
 * maxCoresAvailable =  Unknown Type "unsigned int" (default)
 * maxMemoryAvailable = 18446744073709551615 (default)
 * maxTotalPoints = 1000000
 * nbBrackets = 5
 * response = "D:/a/v/a/MeshroomCache/LdrToHdrCalibration/1e2b232f4b87d506b5756eba62c2372eb90d2091/response.csv"
 * samplesFolders = "D:/a/v/a/MeshroomCache/LdrToHdrSampling/b81daef7dd8313ad4d8705bbfb8e55a5079b8d05"
 * verboseLevel = "trace"
 * workingColorSpace =  Unknown Type "enum aliceVision::image::EImageColorSpace" (default)

Hardware : 
	Detected core count : 12
	OpenMP will use 12 cores
	Detected available memory : 6992 Mo

[16:18:45.911062][trace] 0 extrinsics declared and 5 extrinsics used.
[16:18:45.915567][info] Number of brackets automatically detected: 5. It will generate 1 hdr images.
[16:18:45.928715][info] Analyzing samples for each group
[16:19:30.503516][info] Extracting samples for each group
[16:19:42.038108][info] Start calibration
[16:19:42.038108][info] Debevec calibration with 712194 samples.
[16:19:49.169495][fatal] bad allocation
```

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ] Windows 11
 - Python version [e.g. 2.6] shows 2.7.4. I have installed 3.9 and 3.11
 - Qt/PySide version [e.g. 5.12.4] (not installed)
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1] 2023.1
   - Commit reference (if applicable) [e.g. 08ddbe2] n/a

**Additional context**

**Comment by mcDandy** [comment]
There Is no such option in failing node or nodes before it.

Dne út 4. 7. 2023 11:12 uživatel Daniel Martinek ***@***.***>
napsal:

**Comment by mcDandy** [comment]
Found maxnumberofpoints, but I have no idea how to change it. It Is not
acessable through node atributem panel and there is no value node.

Dne út 4. 7. 2023 11:17 uživatel Daniel Martinek ***@***.***>
napsal:

**Comment by cbentejac** [comment]
Meshroom only seems to detect 6 GB of available RAM when the node starts computing, based on that log:
```
Hardware : 
	Detected core count : 12
	OpenMP will use 12 cores
	Detected available memory : 6992 Mo
```

> There Is no such option in failing node or nodes before it.

Yes, sorry! `maxTotalPoints` is the name of the command-line argument, it corresponds to "Max Number Of Points" in the interface, in the `LdrToHdrCalibration` node. It is set to "1000000" by default. 

It is an advanced attribute so you might not see it by default. You can enable the advanced attribute by clicking here:
<div align="center"><img src="https://github.com/alicevision/Meshroom/assets/11963329/5be2947d-c0e5-40bf-968a-ed7cd327148e" width=400 /></div>

**Comment by mcDandy** [comment]
Ok, did not know about the advanced settings tick. The only 6GB of memory might be becouse the rest is used by other things.

**Comment by mcDandy** [comment]
The error message should probably be made better. I thought there was an errer in the code.
