### ISSUE TITLE
Meshroom not importing photos

### ISSUE THREAD

**Issue by philipposslicher** [alicevision/meshroom#206]
I have tried importing photos on many occasions, only to have Meshroom do absolutely nothing. 

# Things I've tried: 
Restarting Meshroom, restarting computer, change Meshroom disk, change cache location, reinstall Meshroom, different image set. Run Meshroom as admin

# What happens when importing:
Flash of the images metadata extraction screen (< 0.5 s duration)
No images appearing in images panel
Meshroom debug command line changes to only show this
![capture](https://user-images.githubusercontent.com/11558016/44625634-23881000-a91f-11e8-95e8-7585e53613d1.PNG)

# System specs (if of interest):
i7 7700K
GTX 1070Ti
Windows 10 Pro
SSD and 2 HDD's

**Comment by ThatBananer** [comment]
I'm having the same issue, but when I Initially installed and ran it worked. I stopped the process a little less than halfway through. From there tried to import photos and that when I had the issue.

**Comment by yann-lty** [comment]
That's surprising... The whole log in the output window is replaced only by this incomplete line? 
I doubt this is related to your image sets, but just to be sure, could you try with [this one](https://github.com/alicevision/dataset_monstree/tree/master/mini6)?

@ThatBananer You have the same behavior with the log window?

**Comment by yann-lty** [comment]
Could this be related to an antivirus configuration blocking Meshroom subprocesses? It was the potential source of this issue: https://github.com/alicevision/meshroom/issues/205#issuecomment-416006478.

**Comment by philipposslicher** [comment]
Tried the image set linked above, with AV turned completely off, same problem.

**Comment by yann-lty** [comment]
Any chance you keep the complete log output when launching Meshroom.exe from a command prompt instead of double-clicking on it?

**Comment by philipposslicher** [comment]
Heres the log output. Also note that when the cli spits this out, for some reason windows explorer opens a new tab. (no idea why)
`[QtOIIO] Plugin Initialized
[DepthMapEntity] DepthMapEntity
Failed to download scene at QUrl("")
find: ‘/I’: No such file or directory
find: ‘/N’: No such file or directory
find: ‘SoundMixer.exe’: No such file or directory
find: ‘/I’: No such file or directory
find: ‘/N’: No such file or directory
find: ‘explorer.exe’: No such file or directory
ERROR:root:Error while building intrinsics : Traceback (most recent call last):
  File "f:\tmp\meshroom\meshroom\ui\reconstruction.py", line 384, in buildIntrinsics
  File "f:\tmp\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 129, in buildIntrinsics
RuntimeError: CameraInit failed with error code 1. Command was: "aliceVision_cameraInit  --sensorDatabase "C:\Users\Philippos Slicher\Downloads\Meshroom-2018.1.0-win64\Meshroom-2018.1.0\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --verboseLevel info --output "C:/Users/PHILIP~1/AppData/Local/Temp/tmpj12h14in/CameraInit/2731003bd822aa3d98acd3185af7e6a65750fcd4/cameraInit.sfm" --allowSingleView 1  --input "C:\Users\PHILIP~1\AppData\Local\Temp\tmpj12h14in/CameraInit/2731003bd822aa3d98acd3185af7e6a65750fcd4//viewpoints.sfm" --allowIncompleteOutput 1"
`

**Comment by natowi** [comment]
@philipposslicher does the latest release fix your problem (so we can close this issue)?

**Comment by ThatBananer** [comment]
yes
