### ISSUE TITLE
Please add camera model(s) and sensor width(s) in the database.

### ISSUE THREAD

**Issue by SmartySmart702** [alicevision/meshroom#207]
I get the Error above so I added WIKO;GETAWAY;4.82 to the database but doesn't worked!
I read in an other thread that there is a problem with spaces behind the names so I copied the names directly from the error message in the console.

EDIT: Here is the console message: 

[12:54:06.307419][error] image: 'IMG_20180826_113722.jpg'
        - camera brand: WIKO
        - camera model: GETAWAY

![unbenannt](https://user-images.githubusercontent.com/42713365/44627530-b466e780-a92f-11e8-8838-7b95ceaed160.JPG)

**Comment by simogasp** [comment]
try with
```
WIKO;WIKO GETAWAY;4.82
```
Also, be sure you quit meshroom before trying again after modifying the db.
If it works you can also pull request the change directly in https://github.com/alicevision/AliceVision

**Comment by SmartySmart702** [comment]
Thanks for you fast answer but it down't work :(
The program was closed when I edited the file.

**Comment by simogasp** [comment]
What about this?
```
WIKO;WIKO GETAWAY               ;4.82
```
(because of this https://github.com/alicevision/meshroom/issues/179#issuecomment-413016629)

**Comment by SmartySmart702** [comment]
Thats what I said before with the spaces.
But I found out that if I rename the names in the images meta to "wiko" and "getaway" and than use wiko;getaway;4.82 (of course :D) it works!
