### ISSUE TITLE
[bug] Import Reports Corrupted Image, Persists Through Image Processing

### ISSUE THREAD

**Issue by greenbrettmichael** [alicevision/Meshroom#2075]
**Describe the bug**
Importing image results in the error message 

Failed to Import Images - Meshroom 2023.1.0

You probably have a corrupted image within the images that you are trying to import.

**To Reproduce**
1. Download Meshroom 2023.1.0 release on Windows 11 64bit
2. Import Image
![65200b7e-ffed-41f2-b30a-e20681148891](https://github.com/alicevision/Meshroom/assets/10648075/6d215134-ec52-481e-9015-9e5b9e4bfaef)

**Expected behavior**
Image is added into image gallery.

**Desktop (please complete the following and other pertinent information):**
 - OS: Windows 11
 - Meshroom version:
   - Binary version 2023.1.0

**Additional context**
This occurs even if image is resized or converted through irfanview. badpeggy reports the image is OK.

**Comment by greenbrettmichael** [comment]
The issue did not survive upload and redownloading. Is there a more detailed log that can be used to trace the issue? 
Or is it possible to put in a feature request where failed imports are skipped but successful imports are added? My datasets are usually 500-2000, and about 5-10 will have this issue in a given dataset.

**Comment by betstick** [comment]
I've found that long paths and/or underscores in an image's name can cause this on images that are fine. For whatever reason, if there's three underscores in the path, it reports the image to be corrupt. Removing the third underscore fixes it. I've also heard non ASCII characters can cause this.

**Comment by greenbrettmichael** [comment]
This has happened long ago and I won't be able to reproduce anymore. Closing my issue
