### ISSUE TITLE
software not importing photos

### ISSUE THREAD

**Issue by vettorazi** [alicevision/meshroom#208]
Machine:
surface book 2

**error:**
in the startup of the software:
```
lugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, ExportUndistortedImages, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[QtOIIO] Plugin Initialized
[DepthMapEntity] DepthMapEntity
Failed to download scene at QUrl("")

```

**on the import:**```

ERROR:root:Error while building intrinsics : Traceback (most recent call last):
  File "f:\tmp\meshroom\meshroom\ui\reconstruction.py", line 384, in buildIntrinsics
  File "f:\tmp\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 129, in buildIntrinsics
RuntimeError: CameraInit failed with error code 3221225477. Command was: "aliceVision_cameraInit  --sensorDatabase "C:\......."
```

**Comment by rgoupil** [comment]
I had the same problem here, on a workstation running Win10 with 16Go of RAM.
I was  trying to import several images of 2988x5312.
When I downscaled them to 2656x1494 it could correctly imported them.
I assume this is related to the amount of RAM and the size of your image (5312x2988x3 != 45Go vs 2656x1494x3 ~= 11Go).

**Comment by yann-lty** [comment]
Image size should not be a problem to initialize the project. They are never all loaded simultaneously in memory (only 3 at the same time). Could you share a few images from your (original scale) dataset to see what goes wrong?

**Comment by McSmithe** [comment]
It did not import images for me as well, but if I just open them and resave them it did. Doesn't need to resize, something about the image format from the phone makes it break

**Comment by rgoupil** [comment]
Interesting, I will check my original pictures if I still have them.
The importer should probably be more exlicit when hitting this kind of issue: "could not parse image" would already be a much better error message than the current one IMO.
