### ISSUE TITLE
[question] "DepthMap" stage taking ages

### ISSUE THREAD

**Issue by usr577** [alicevision/Meshroom#2086]
**Describe the problem**
The "DepthMap" stage now took 4 hrs and isn't even one fourth completed but it doesn't even use half of my system resources. Is there anyway to tell it to use more of my system resources for better reconstruction speed?

Also the orange part of the progress bar that shows what's being processed is so small, it's barely visible.

**Desktop (please complete the following and other pertinent information):**
 - OS: Win 11
 - Meshroom version: latest release

**Comment by 4CJ7T** [comment]
That's normal for the DepthMap stage. No, there isn't a way for it to use more resources.
Image count, image resolution, downscale?

**Comment by usr577** [comment]
Ok thanks for the quick answer I'll try out some of the things you mentioned and see if it gets better.
