### ISSUE TITLE
Error when save path contains special characters

### ISSUE THREAD

**Issue by eisensafran** [alicevision/meshroom#209]
Meshroom stops after ~10 minutes after starting the default building process with the following error when special characters are part of the save path:
`ERROR:root:Error during Graph execution Error on node "PrepareDenseScene_1":`

Tested on Win10 (1803)
Since my default user folder contains the special character ß (German double s) this error occurs.

**Comment by zvrba** [comment]
Ah, it's not about "special characters", it's about (not) being Unicode-aware.

**Comment by ertgtct** [comment]
For me this Error occurs every time, even when I have an ASCII compatible Path.
But I am also working on a German Windows Machine.
My Software version is 1.0

**Comment by eisensafran** [comment]
Can confirm the error from ertgtct:
Meshroom quits also working when umlauts (äöü) are part of the file path OR file name.

**Comment by ertgtct** [comment]
I got it fixed for me:
You need an ASCII compatible filepath **and** you must save the file in the Programm directory

**Comment by ertgtct** [comment]
Or at least at the same Drive
