### ISSUE TITLE
PrepareDenseScene std::bad_alloc error

### ISSUE THREAD

**Issue by finnbear** [alicevision/meshroom#210]
Does this error happen simply because 8GB of RAM isn't enough for my project?

**Platform:**
* Lenovo Yoga 260
* Ubuntu 18.04
* 8GB RAM

**Node log:**
```
Program called with the following parameters:
 * input = "/tmp/MeshroomCache/StructureFromMotion/4d5fadc5e8a3148b72fb4de229e0cd3f5cf08ae3/sfm.abc"
 * output = "/tmp/MeshroomCache/PrepareDenseScene/f40b6fb0c11a65be0c020011238ee5b24a644cf6"
 * verboseLevel = "debug"

Exporting Scene Data
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

**Chart of system RAM/swap after restarting node:**
![image](https://user-images.githubusercontent.com/20015102/44634344-67920980-a94d-11e8-919d-751790ecde6a.png)

**Comment by fabiencastan** [comment]
Yes, maybe due to the trivial parallelization that we use at this step. In our renderfarm, we always have machines with more RAM than that.
Could you try to set this environment variable before launching Meshroom?
`export OMP_NUM_THREADS=1`

It will make other steps really slow, but just to see if it fixes the problem. And we will need to add rules to check the amount of RAM available to limit the parallelization.

**Comment by fabiencastan** [comment]
To only affect Meshroom, you can do:
`OMP_NUM_THREADS=1 ./Meshroom`

**Comment by finnbear** [comment]
I just tried that, and for some reason, Meshroom returned to the same state I left it yesterday. Note that I did load the same images but I didn't save the project file. Same error occurred. I will try with new images to avoid caching of previous results.

**Comment by finnbear** [comment]
Right now, I could only find 4 other images to test on, which apparently isn't enough. I get this error:
```
[08:25:08.499546][info] AutomaticInitialPairChoice, test I: 842950222, J: 1808247737, nbCommonTracks: 1479
[08:25:08.619930][info] Initial pair is:
  A - view id: 842950222 - filepath: /home/******/Pictures/shotwell/2018/08/21/DSC_5965.JPG
  B - view id: 1808247737 - filepath: /home/******/Pictures/shotwell/2018/08/21/DSC_5968.JPG
[08:25:08.622097][info] 1479 matches in the image pair for the initial pose estimation.
[08:25:09.088035][info] Remove outliers: 
	- # outliers residual error: 0
	- # outliers angular error: 0
terminate called after throwing an instance of 'std::runtime_error'
  what():  Initialization failed after trying all possible initial image pairs.
Aborted (core dumped)
```

Until I can test new images, I don't thing the OMP_NUM_THREADS worked. I will try:

- More powerful desktop hardware (32 GB ram)
- Down-scaling image from 6k resolution to 2k.
