### ISSUE TITLE
[bug] UID upgrade not saved 

### ISSUE THREAD

**Issue by mh0g** [alicevision/Meshroom#2111]
**Describe the bug**
Since the new release that changes the uid computation, the following issue arises.
When opening an old project and performing the uid upgrade as specified by the warning, saving the project without modifying the graph does not perform the upgrade. When opening again the project, the warning is gone but the wrong uid is present in the save files.

**To Reproduce**
See above

**Expected behavior**
The upgrade and save should work

**Comment by cbentejac** [comment]
This might be fixed as a side effect of #2127, which solves several "UID conflict"-related issues.
