### ISSUE TITLE
[question] World coordinate (3d) project to Image coordinate (2d)

### ISSUE THREAD

**Issue by tak-ho** [alicevision/Meshroom#2112]
I try to use the exported sfm.json from ConvertSfMFormat to calculate the 3d world coordinate to 2d image pixel coordinate, but the calculation is different from the actual struct point X (3d) to x (pixel) mapping. 
The same calculation is correct when apply to others photogrammetry software (Pix4D), so I wonder whether this is data incorrect or calculation incorrect...

I am using this dataset: https://github.com/alicevision/dataset_monstree

Instrinsics information:
```
"intrinsics": [
    {
        "intrinsicId": "3643440531",
        "width": "4032",
        "height": "3024",
        "sensorWidth": "4.8899998664855957",
        "sensorHeight": "3.6675000190734863",
        "serialNumber": "",
        "type": "radial3",
        "initializationMode": "estimated",
        "initialFocalLength": "3.9899998910587993",
        "focalLength": "4.0263723615187379",
        "pixelRatio": "1",
        "pixelRatioLocked": "true",
        "principalPoint": [
            "-12.66035627781941",
            "-2.7971447852237494"
        ],
        "distortionInitializationMode": "none",
        "distortionParams": [
            "0.08249736610498426",
            "-0.28557394923282603",
            "0.3365638389510236"
        ],
        "locked": "false"
    }
],
```

extrinsic information for target image:
```
{
    "poseId": "323678839",
    "pose": {
        "transform": {
            "rotation": [
                "0.0094217031096691835",
                "0.98418854462185668",
                "0.17687323185158657",
                "-0.97933457096314991",
                "0.044818307067944908",
                "-0.19721845113474265",
                "-0.2020272992121033",
                "-0.17135993693589888",
                "0.9642721308771649"
            ],
            "center": [
                "-0.41174254704989571",
                "0.46019158010672834",
                "0.25912755186797759"
            ]
        },
        "locked": "0"
    }
},
```

A particular Struct point information (I only include one observation related to the target image)
```
{
    "X": [
        "-0.43265685439109802",
        "0.083013921976089478",
        "1.2571489810943604"
    ],
    "observations": [
        {
            "observationId": "323678839",
            "featureId": "7893",
            "x": [
                "2547.669921875",
                "835.10198974609375"
            ],
            "scale": "5.4046502113342285"
        }
    ]
}
```

In this case the calculation be like this:
```
world_pos = [-0.43265685439109802, 0.083013921976089478, 1.2571489810943604]
cam_pos = [-0.41174254704989571, 0.46019158010672834, 0.25912755186797759]
cam_rotation_m = np.array([
    [0.009421703109669183, -0.9793345709631499, -0.2020272992121033], 
    [0.9841885446218567, 0.04481830706794491, -0.17135993693589888], 
    [0.17687323185158657, -0.19721845113474265, 0.9642721308771649]
])

# first transform to cam_coordinate
cam_coord = np.dot(cam_rotation_m.T, (np.array(world_pos) - np.array(cam_pos)))

img_w = 4032
img_h = 3024
# I guess the meshroom principle point is start from center so will shift it
principle_pt = [-12.66035627781941, -2.7971447852237494]
principle_pt = [principle_pt[0] + (img_w/2), principle_pt[1] + (img_h/2)]

focal_len = 4.0263723615187379
sensor_w = 4.8899998664855957
# someone said the focal length need to be in pixel instead of mm, so I also transform it
focal_len = focal_len * img_w / sensor_w

# then according to the equation
xh = cam_coord[0]/cam_coord[2]
yh = cam_coord[1]/cam_coord[2]
r2 = math.pow(xh, 2)*math.pow(yh, 2)
r4 = math.pow(r2, 2)
r6 = r2*r4

radial_mat = [0.08249736610498426, -0.28557394923282603, 0.3365638389510236]
xhd = (1+(radial_mat[0]*r2)+(radial_mat[1]*r4)+(radial_mat[2]*r6)) * xh
yhd = (1+(radial_mat[0]*r2)+(radial_mat[1]*r4)+(radial_mat[2]*r6)) * yh

xd = -(focal_len*xhd) + principle_pt[0]
yd = -(focal_len*yhd) + principle_pt[1]
```

Actual x is **[2547.669921875, 835.10198974609375]**
But the result I get is [2630.82319814, 2131.41539936]

I read some comment and someone said the coordinate system of meshroom is different from others, so I add negative to y and z for the coordinate, in this case
```
world_pos = [-0.43265685439109802, -0.083013921976089478, -1.2571489810943604]
cam_pos = [-0.41174254704989571, -0.46019158010672834, -0.25912755186797759]
```
But the result I get is [2634.76141212, 2269.57915496] still not close

some people said the negative need to add when when divide cam_coord_y to cam_coord_z, so I also try modify this:
```
yh = -cam_coord[1]/cam_coord[2]
```
The result I get is [2634.76141212,  748.82655547] or with negative y, z result is [2630.82319814,  886.99031107]
still, incorrect.

Am I using some wrong data or the equation is actually incorrect? Could anyone give me some helps? Thanks a lot!!!

**Comment by tak-ho** [comment]
I get some of the equation over here:
https://calib.io/blogs/knowledge-base/camera-models

**Comment by natowi** [comment]
Does this help? https://github.com/alicevision/Meshroom/issues/2003

**Comment by tak-ho** [comment]
> Does this help? #2003

I have already extract the necessary information from the sfm, but thanks!

**Comment by tak-ho** [comment]
> Sorry I don't have much time to check thoroughly your code, but I noticed 2 things.
> 
> The poses are stored as a rotation matrix `R` and the camera center `C`, so that the projection law (without distortion) is
> 
> ```
> q ~ K [R t] Q
> ```
> 
> where `Q` is a 3D point in world reference system, `q` its projection onto the image plane that you want to compute, `K` the calibration matrix, and `t` is the translation component `t =-R*C`. So you may want to take that into account.
> 
> Second, the rotation matrix `R` is stored in the json file in **row-major** order, and it seems to me that you are actually using the column-major order when importing it. So try to fix that too.

Yes, I think I calculate incorrectly with the equation, I do `t =-RT*C` instead of the correct one `t =-R*C`
Thank you so much for the help!!!

**Comment by evilADevil** [comment]
@tak-ho could you share the modified calculation python fragment?
