### ISSUE TITLE
[question] Does draft meshing support texture?

### ISSUE THREAD

**Issue by ManuShi98** [alicevision/Meshroom#2136]
**Describe the problem**
I followed the wiki of the draft meshing but there was no texture generated, but I saw the example in the wiki did have the texture. Are there any options or steps I missed?

**Desktop (please complete the following and other pertinent information):**
 - OS: win10
 - Meshroom version: 
   - Binary version: 2023.2

**Comment by natowi** [comment]
Did you double-click on the Texturing node when it finished? This will load the textured model to the viewer.

**Comment by ManuShi98** [comment]
> Did you double-click on the Texturing node when it finished? This will load the textured model to the viewer.

I tried again with the [Monstree dataset](https://github.com/alicevision/dataset_monstree) and double-clicked on the Texturing node as you said but there was still no texture there. I used the built-in photogrammetry draft pipeline and made no change to it.

**Comment by RichyT** [comment]
I am also having this issue. Not too worried as I'm only using the draft to poke while I get my CUDA issues sorted out.

I get colored dots in the "Structure from Motion" node but nothing after that. Not sure if there's a bad connection somewhere or something. This is with my own dataset. I'll try and dig in a little more but I ran into this while doing a quick search

**Comment by cbentejac** [comment]
Hi @RichyT,

Do you use the official binary or did you build and setup Meshroom on your own?

**Comment by RichyT** [comment]
It's the official binary on a fairly barebones install of Slackware. I got my GPU working so I'm currently doing a full mesh and we'll see how that does.

**Comment by RichyT** [comment]
Full meshing is working fine except I get a divide by zero fatal error on the texturing. Not a big deal for my purposes. Not sure if it's related to this issue.

**Comment by ManuShi98** [comment]
Hi @cbentejac,

Could you please check if the modification in this pr [mesh-also use assimp for mesh::saveToObj](https://github.com/alicevision/AliceVision/commit/a6ba95437a06e76cb60cd7056f7ee8cf01456a96) causes the problem? In the older version, the saveToObj function reads the color from _color array and outputs six numbers to the file: x, y, z, r, g, and b. However, in the latest version, I didn't see the color array being used anywhere. I tested with the older version(2019 or 2020), and the draft mesh does work with texture.

**Comment by cbentejac** [comment]
Hi @ManuShi98,

The issue will be fixed with #2232, which will be part of the next release. The nodes have evolved a lot since the 2019/2020 release, and the "Photogrammetry Draft" pipeline needed to be updated for the textures to be correctly generated.

Thanks for letting us know about this issue!

The "divide by zero" fatal error is a different issue which will need to be addressed separately and thus won't be fixed by #2232.
