### ISSUE TITLE
[bug] Meshroom crashing while importing images from folders with special characters

### ISSUE THREAD

**Issue by mrindholt** [alicevision/Meshroom#2139]
**Describe the bug**
The program crashes while I try to import images from folders with a name containing the special characters like æ ø å.

**To Reproduce**
1. Create a folder with a name containing æ, ø or å
2. Put images into the folder
3. Create a new Photogrammetry pileline in Meshroom
4. Drag pictures from the folder with a name containing æ, ø or å
5. Wait for the program to crash

**Desktop:**
 - OS: Windows 10
 - Python version 3.7.4
 - Meshroom version: 2023.2.0

**Comment by natowi** [comment]
This is a known issue https://github.com/alicevision/Meshroom/wiki/Troubleshooting

**Comment by natowi** [comment]
Keeping this issue open as an reminder to fix the issue

**Comment by cbentejac** [comment]
This issue appears to be fixed with Meshroom 2023.3.0.
I'll wait for someone that encountered the issue with Meshroom 2023.2.0 (or older) to confirm that this does not occur anymore on their side as well, and if that is the case, I'll close this issue and all the similar ones that exist.

Thanks!
