### ISSUE TITLE
Add requirements (specifically, NVIDIA GPU required) to download page

### ISSUE THREAD

**Issue by LauritzThaulow** [alicevision/meshroom#214]
There is currently no mention anywhere that I could find, except in some of the open issues on github, that NVIDIA GPUs are currently a requirement for this application.

Please add a prominent notice to the download page so that people with different GPU cards don't waste their time taking lots of pictures, downloading and figuring out the program, only revealing that their efforts were wasted when the process is almost complete.

**Comment by yann-lty** [comment]
We should have done that earlier, thanks for pointing this out. It has been added to the download page.

**Comment by AndreaMonzini** [comment]
Hello, there is a thread to evaluate solutions for other GPU.

https://github.com/alicevision/AliceVision/issues/439#issuecomment-416528894

**Comment by LauritzThaulow** [comment]
Thanks for the quick resolution, @yann-lty. I really appreciate the work you and the other devs are doing on this project, thank you!

And thanks for pointing me to that thread, @AndreaMonzini, I'll keep an eye on it, as I'm sure it's only a matter of time until AMD support comes along, given the [momentum](https://trends.google.com/trends/explore?q=meshroom) this project seems to be getting.
