### ISSUE TITLE
scanning rooms[question]

### ISSUE THREAD

**Issue by chenkianwee** [alicevision/Meshroom#2144]
**Describe the problem**
I am trying to scan rooms

**Desktop (please complete the following and other pertinent information):**
 - OS: ubuntu 22.04.2
  - Meshroom version: please specify if you are using a release version or your own build
   - Binary version 2023.2.0

I have seen questions on this topic before but have not seen solution to it. So I am asking it again. This is the room I am trying to scan, as with most rooms the walls are bland and have not much texture.
![image](https://github.com/alicevision/Meshroom/assets/13062600/12469dd1-5368-473d-a131-d5080457b92f)

However, this is the result I got. It seems like meshroom is removing the walls from the scans. I have set the DescriberPreset from Normal to High for the FeatureExtraction node. 
![image](https://github.com/alicevision/Meshroom/assets/13062600/b677029e-b1f3-47b0-9a20-fb8988bf52c9)

Is there any parameters I can tweak for scanning rooms?

**Comment by msanta** [comment]
Unfortunately there are no features to detect on the blank walls. The simplest solution to get the walls included could be to add lots of stickers to the walls, but you may not want that in the final output.

There is a wiki article about using light patterns and taking two sets of photos (one with the pattern and one without). The photos with the pattern are used for the feature extraction part, while the photos without are used for texturing. The wiki article is here: https://github.com/alicevision/Meshroom/wiki/Projected-Light-Patterns

**Comment by chenkianwee** [comment]
The wiki article is a great resource. Thanks very much.
