### ISSUE TITLE
[question] Does dspsift not utilize GPU even if Force CPU Extraction is off?

### ISSUE THREAD

**Issue by mrindholt** [alicevision/Meshroom#2149]
**Problem**
I've been messing a bit with some old models from 2021.1.0, that I tried to re-build in 2023.2.0, but when extracting features (with the new default settings but Force CPU Extraction off), it still only utilizes some/most of the CPU threads (12c/24t) when running with dspsift. However when picking ordinary sift in the same model, the feature extractions are run on the GPU.

Anyone who knows if I'm doing something wrong, or if this should be retagged as a bug?

**Desktop**
OS: Windows 10
GPU: NVIDIA GeForce RTX 3070 Ti
Python version 3.7.4
Meshroom version: 2023.2.0

**Comment by natowi** [comment]
no, there is only GPU support for sift

**Comment by mrindholt** [comment]
Thank you for clarifying! 😄

**Comment by mrindholt** [comment]
Thank you for clarifying! 😄
