### ISSUE TITLE
sensorWidth, SensorHeight, Metadata

### ISSUE THREAD

**Issue by vintheruler1** [alicevision/Meshroom#2151]
**Describe the problem**
How do I add "sensorWidth" and "sensorHeight" to the metadata of a photo and what photo taker would you recrommend to get all the data required.

**Desktop (please complete the following and other pertinent information):**
 - OS: [win10 ]
 - Python version: 3.9
 - Qt/PySide version: 5.15.2
 - Meshroom version: latest (2023-2)

**Comment by natowi** [comment]
This information is usually not saved with the metadata. This is why the sensordb exists:
https://github.com/alicevision/Meshroom/wiki/Add-Camera-to-database

**Comment by vintheruler1** [comment]
> This information is usually not saved with the metadata. This is why the sensordb exists:
> https://github.com/alicevision/Meshroom/wiki/Add-Camera-to-database

Issue is, I looked there and I could not find my sensor. It is the OmniVision OV9734.

**Comment by natowi** [comment]
SensorWidth is 1.81958mm
https://www.gophotonics.com/products/cmos-image-sensors/omnivision-technologies/21-118-ov9734 (1819.58 x 1033.34 µm Imaging area)
You need to check the metadata of your images for make and model and then add the following to the database:
`CameraMaker;CameraModel;1.8;usercontribution`
Replaca CameraMaker and CameraModel accordingly

**Comment by vintheruler1** [comment]
> SensorWidth is 1.81958mm
> https://www.gophotonics.com/products/cmos-image-sensors/omnivision-technologies/21-118-ov9734 (1819.58 x 1033.34 µm Imaging area)
> You need to check the metadata of your images for make and model and then add the following to the database:
> `CameraMaker;CameraModel;1.8;usercontribution`
> Replaca CameraMaker and CameraModel accordingly
> Please report both values back, so we can add it to the database

I have not been able to confirm if this works. I keep getting an error #1497 and #1194 but none of the solutions work. Still havent installed QtAliceVision because I do not know how to and the install.md isnt very detailed. Anyway we can get on a call and you can help?

**Comment by natowi** [comment]
Adding the camera to the database will still help. Could you please share the make and model from your cameras exif data?
