### ISSUE TITLE
How can I use a separate set of pictures for texturing?

### ISSUE THREAD

**Issue by MaxDidIt** [alicevision/Meshroom#2168]
I want to create a 3D model of an object that has several transparent and relatively featureless surfaces.

I have placed the object on a piece of paper with markers and a pattern on it. I have then created two sets of images the object:

In the first set, the object is in its original state with the transparent surfaces and everything:
<img src="https://github.com/alicevision/Meshroom/assets/4189913/2c228fff-9cd8-4ca2-b365-0de7e7a7f5f4" height=600>

In the second set, I have painted and sprinkled the object with paint. It looks pretty messy, but it does provide Meshroom with a number of features it can use during the photogrammetry process:
<img src="https://github.com/alicevision/Meshroom/assets/4189913/8633c7b3-aced-49d2-881c-2d08a41c5940" height=600>

It is the same object, standing in the exact same position and orientation on the same markers. However, the camera angles in the two image sets are not exactly the same, since they are two different image sets.

How can I create a Meshroom pipeline that uses the second image set for creating the 3D model, but the first image set to texture the model?

I have already tried to set up two CameraInit nodes and assign the two image sets to the two CameraInit nodes respectively. I would then basically run the first half of the pipeline in parallel:
![grafik](https://github.com/alicevision/Meshroom/assets/4189913/42c35444-ec49-447d-ae0c-7df7985d01c6)
The problem is that the point cloud and the camera positions of the first set don't match the second set and because of this, the texture looks broken. However, I'm not sure how to tell the first and the second image set to sync up the scale and orientation of their respective point clouds and camera positions.

Can someone point me in the right direction with this?

**Comment by natowi** [comment]
SfMAlignment node: Align the sfm from reconstruction1 with reconstruction2 (original). Use "From Markers".
Now you can  set the reconstructed1 mesh as input for reconstruction2 (original) Texturing Input Mesh similar to https://github.com/alicevision/Meshroom/wiki/Texturing-after-external-re-topology 
Instead of an optimized Mesh, we provide the better and aligned mesh as input.

Something like this:
![grafik](https://github.com/alicevision/Meshroom/assets/8138537/734e27fe-19c8-4337-80f1-c6938250c624)

**Comment by MaxDidIt** [comment]
Yes, awesome! It works! 

![Persil](https://github.com/alicevision/Meshroom/assets/4189913/7554ef47-c02c-4367-a65b-914cd77a20d0)

The SfMAlignment node was the missing puzzle piece. Thank you, this really helped me out!

Not needing a camera setup that will take the images for the two image sets from the exact same angles as described in [Projected Light Patterns](https://github.com/alicevision/Meshroom/wiki/Projected-Light-Patterns) is very helpful. I will keep experimenting with this, but considering how (literally) quick and dirty the input image creation process was, I'm already quite happy with the result.

**Comment by natowi** [comment]
Great! May I use your images to update the documentation?
