### ISSUE TITLE
[question] How to build Meshroom Install-Setup (exe)

### ISSUE THREAD

**Issue by Sadegh-Kalami** [alicevision/Meshroom#2178]
**Issue Description**
Hello, Meshroom team! First of all, great job on the work you've done so far. I'm new to this field and I'm excited to start using Meshroom.

**Problem Statement**
I'm interested in creating an executable (`.exe`) version of Meshroom, similar to what you've done in your official releases. As a newcomer, I'm not entirely sure how to go about this process.

**Request for Assistance**
I kindly request your guidance and assistance in creating an executable version of Meshroom. It would be immensely helpful if you could provide me with step-by-step instructions or point me to relevant documentation/resources.

**Additional Information**
- Operating System: [Windows]

Thank you in advance for your help! I'm looking forward to using Meshroom and contributing to the community.

Best regards,

**Comment by fabiencastan** [comment]
Hi @Sadegh-Kalami
Yes, we can setup a meeting to discuss about it. Contact me at "fabien.castan@technicolor.com".
Would you be interested in contributing to setup automatic packaging in the CI to allow anyone (including you :) ) to test the development version on the fly?

**Comment by natowi** [comment]
This may help: https://github.com/natowi/Meshroom-Installer
