### ISSUE TITLE
Can you use meshroom with amd video cards?

### ISSUE THREAD

**Issue by tomer3535** [alicevision/meshroom#218]
Hey, I started using meshroom today and at first everything went well and it got to DepthMap, then it stopped. It said [error] This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0). What I understand from that is that I need a NVIDIA GPU because CUDA doesn't run with amd or something. Does that mean I can't use the software with an amd video card?

my amd video card is Radeon RX 470

**Comment by fabiencastan** [comment]
Yes, you cannot do the depth map computation on AMD cards as it is implemented in CUDA. So you cannot create the mesh.
Duplicates of https://github.com/alicevision/AliceVision/issues/439

**Comment by aviallon** [comment]
Hello, would it be possible for you to use [hipify](https://github.com/ROCm-Developer-Tools/HIP/tree/master/hipify-clang) to automatically convert your CUDA code to HIP ? Would be very nice, and it did work very well with all of my personal projects.

**Comment by lloydw88** [comment]
Aviallon did this work by chance?  Im relatively new to photogrametry, i was looking for a program that didnt have a huge learning curve.  Came upon meshroom only to get a depth error and my research landed me to this thread.  So like i said im new so be easy, what you have linked, will that fix my depth issue in meshroom? And how do i use what you posted?

**Comment by natowi** [comment]
@lloydw88 Yes, Hip now supports all cuda functions used in alicevision, so using hipify is possible, but I did not have time yet to figure out how to compile the hipified code. Check the referenced issues (above) for details.

**Comment by lloydw88** [comment]
Thank you.  Im new to photogramatry, so please be gentle.  So when you say hipify will work.  Is hipify a seperate program I have to download?  Do we embed it in meshroom?  How exactly do you use hipify with meshroom to make a decent model?

**Comment by natowi** [comment]
@lloydw88 At the moment there is no ready to use version that works without cuda. Hip is a layer that can translate cuda code. Hipified code can be compiled and run on nvidia _and_ amd GPUs.
Until there is a Meshroom version with amd support (no implementation time frame is set) you can use [draft meshing](https://github.com/alicevision/meshroom/wiki/Draft-Meshing) (at the cost of reconstruction quality). For smaller projects you could run meshroom online (no GUI): https://github.com/alicevision/meshroom/wiki/Meshroom-in-Google-Colab-(cloud) or https://github.com/alicevision/meshroom/wiki/Meshroom-on-AWS

**Comment by natowi** [comment]
@lloydw88 I watched your youtube video. Note: You won´t get Hip+Meshroom running without some coding knowledge. So you need to wait for us to compile a non-cuda version or use the alternatives I listed before.
Regarding your model from the video:
You have to many large, featureless (same colour (black/yellow), no texture) surfaces, and reflections so you won´t get a good reconstruction from this. Check out  some "how to capture images for photogrammetry" tutorials to get the basics.

**Comment by lloydw88** [comment]
Thank you.  Im new to photogrammetry if you couldnt tell.  Lol.  How long
do you suppose the version of meshroom will be available for non gpu
computers?

Lloyd Willis

**Comment by natowi** [comment]
@lloydw88 There will be an announcement when there is a non cuda version. Release date is unknown.

**Comment by Richardsonmapper** [comment]
I am hopeful that this announcement will be not too far away @natowi 😊?

**Comment by natowi** [comment]
@Richardsonmapper Sorry, I had to pause looking into this for now, as I have to work on another, time-sensitive project. I´ll get back to it.

**Comment by kDome89** [comment]
It would be very cool if meshroom would work with AMD-Cards.

**Comment by Nosenzor** [comment]
Yes, it’s a shame to use a locked technology (CUDA) in this great open source software. Go sycl !

**Comment by diver-down** [comment]
Hey, just another ++ from an AMD user! 

Getting rid of my last NVIDIA card next week, and would love to keep using and promoting Meshroom <3

If any testers are needed for this effort, I'd love to help. :)

**Comment by Richardsonmapper** [comment]
> Hey, just another ++ from an AMD user!
> 
> Getting rid of my last NVIDIA card next week, and would love to keep using and promoting Meshroom <3
> 
> If any testers are needed for this effort, I'd love to help. :)

Like wise I would be happy to assist with any testing if needed :)

**Comment by unfa** [comment]
I'm waiting for an AMD-enabled Meshroom version as well!

**Comment by Eversor** [comment]
Same here

**Comment by OnlyHardOfficial** [comment]
Hi all,

Same here:
With  NITRO+ RX 5700 XT 8G


Same problems here:
Program called with the following parameters:

downscale = 4
exportIntermediateResults = 0
imagesFolder = "C:/Users/ONLYHA~1/AppData/Local/Temp/MeshroomCache/PrepareDenseScene/b5506dfdae0783ed4f2af93ed5e456c597410b68"
input = "C:/Users/USERxxxx/AppData/Local/Temp/MeshroomCache/StructureFromMotion/a18323503797a7ca24cbdebf412d6b86d0ad0932/sfm.abc"
maxViewAngle = 70
minViewAngle = 2
nbGPUs = 0
output = "C:/Users/USERxxxx/AppData/Local/Temp/MeshroomCache/DepthMap/36f66f7ffefbecb47504f7cbd92b7f8e44e4c9af"
rangeSize = 3
rangeStart = 0
refineGammaC = 15.5
refineGammaP = 8
refineMaxTCams = 3
refineNDepthsToRefine = 31
refineNSamplesHalf = 150
refineNiters = 100
refineSigma = 15
refineUseTcOrRcPixSize = 0
refineWSH = 3
sgmGammaC = 5.5
sgmGammaP = 8
sgmMaxTCams = 3
sgmWSH = 4
verboseLevel = "error"
[11:15:01.772700][error] cudaGetDeviceCount failed: CUDA driver version is insufficient for CUDA runtime version
[11:15:01.772700][error] This program needs a CUDA-Enabled GPU (with at least compute capability 2.0).

**Comment by HairyStuntWaffle** [comment]
AMD compat would be AMAZING
