### ISSUE TITLE
Enhancement: monospace font for log display

### ISSUE THREAD

**Issue by LukeV1** [alicevision/meshroom#219]
As this is just an enhancement suggestion please close or ignore this if you`ve got too much work to do...

It would be nice if the log output in meshroom would be shown in a monospace font since otherwise the character-progressbars aren't readable at all. Currently you are not able to tell if a bar is finished or not when looking at the meshroom log - what would be helpful especially now as the software isn't fully stable..

Example of monospace log vs meshroom log:
![monospace log vs meshroom log](https://user-images.githubusercontent.com/8466561/44739985-8c2ae480-aaf9-11e8-96a4-bedb193599ab.png)

**Comment by yann-lty** [comment]
Totally agree, this is the expected behavior. It's actually set up to do that, but I found out too late that "Monospace" font was not available by default on Windows. I'll make a fix.

**Comment by robertguetzkow** [comment]
@yann-lty Courier New should be available by default on Windows.
