### ISSUE TITLE
Question: Does Meshroom Support Reconstruction Regions?

### ISSUE THREAD

**Issue by jmontserrat** [alicevision/meshroom#220]
Hi,

As the title says, does Meshroom support reconstruction regions? I couldn't find anything about that in the nodes.
That would greatly improve the reconstruction times.

Thanks

**Comment by fabiencastan** [comment]
That's obviously an important feature, but it is not yet implemented.
Same request idea than: https://github.com/alicevision/meshroom/issues/217
