### ISSUE TITLE
deleting Cache

### ISSUE THREAD

**Issue by abszolut** [alicevision/meshroom#221]
Hi,

I would like to delete the meshroomcache in ...AppData\Temp.

If I use the same filenames the process doesn't start.
Is there a script to empty the Cache? 

Thank you

**Comment by LukeV1** [comment]
Actually there is a built-in function to delete the Cache (for each node separately) - just right click the node and select "Clear Data"

**Comment by abszolut** [comment]
Can I do this with command line?
Thanks

**Comment by LukeV1** [comment]
Presumably, but I don't know the command - I'm not a developer of AliceVision..

**BUT**: you can use `-f` to force recomputation of your cache ([source](https://github.com/alicevision/AliceVision/blob/develop/docs/sphinx/rst/software/SfM/ComputeFeatures.rst)).

**Comment by fabiencastan** [comment]
@abszolut I don't understand what you are looking for. Could you precise?

Currently, you can remove the cache per node from the UI. You can also retrieve the cache folder to delete it manually. If you want to clear everything, you just have to remove the main MeshroomCache folder. If you want to remove all variations of a node type, you can do it as they are grouped in the same folder.
