### ISSUE TITLE
[question] Failed to estimate space from SfM: The space bounding box is too small.

### ISSUE THREAD

**Issue by Mactarvish** [alicevision/Meshroom#2210]
**Describe the problem**
When executing 3D reconstruction, error shown in `Meshing` node : `Failed to estimate space from SfM: The space bounding box is too small.`

**Screenshots**
![image](https://github.com/alicevision/Meshroom/assets/13399458/254d8b28-cee4-4889-856c-30a046dd2538)

**Dataset**
![IMG_8086 HEIC](https://github.com/alicevision/Meshroom/assets/13399458/416a2ee7-a5f6-4761-be82-13b22bf43fee)
![IMG_8087 HEIC](https://github.com/alicevision/Meshroom/assets/13399458/6d025b1e-ab5c-4ee1-8fbc-731367eab71c)
![IMG_8088 HEIC](https://github.com/alicevision/Meshroom/assets/13399458/9e20a6c0-7d96-4043-83e7-510183ff7ad1)
![IMG_8089 HEIC](https://github.com/alicevision/Meshroom/assets/13399458/bcac71b0-a138-4daf-a395-35409026f0ca)
![IMG_8090 HEIC](https://github.com/alicevision/Meshroom/assets/13399458/2a9296cb-0687-4f8a-846d-f6ae1b5f555d)

**Log**
```
Program called with the following parameters:
 * addLandmarksToTheDensePointCloud = 0
 * angleFactor = 15
 * colorizeOutput = 0
 * contributeMarginFactor = 2
 * densifyNbBack = 0 (default)
 * densifyNbFront = 0 (default)
 * densifyScale = 1 (default)
 * depthMapsFolder = "C:/Users/29184/AppData/Local/Temp/MeshroomCache/DepthMapFilter/89825c1f54ba04af8a63428311ede28490c2eb13"
 * estimateSpaceFromSfM = 1
 * estimateSpaceMinObservationAngle = 10
 * estimateSpaceMinObservations = 3
 * exportDebugTetrahedralization = 0
 * fullWeight = 1
 * helperPointsGridSize = 10
 * input = "C:/Users/29184/AppData/Local/Temp/MeshroomCache/StructureFromMotion/1ef6b9eb5b0b810f05e2c8c161058febc244390e/sfm.abc"
 * invertTetrahedronBasedOnNeighborsNbIterations = 10
 * maskBorderSize = 1 (default)
 * maskHelperPointsWeight = 0 (default)
 * maxInputPoints = 50000000
 * maxNbConnectedHelperPoints = 50
 * maxPoints = 5000000
 * maxPointsPerVoxel = 1000000
 * minAngleThreshold = 1
 * minSolidAngleRatio = 0.2
 * minStep = 2
 * minVis = 2 (default)
 * nPixelSizeBehind = 4
 * nbSolidAngleFilteringIterations = 2
 * output = "C:/Users/29184/AppData/Local/Temp/MeshroomCache/Meshing/d9744e1e30715c5095131ec5b501239a1e714865/densePointCloud.abc"
 * outputMesh = "C:/Users/29184/AppData/Local/Temp/MeshroomCache/Meshing/d9744e1e30715c5095131ec5b501239a1e714865/mesh.obj"
 * partitioning =  Unknown Type "enum EPartitioningMode"
 * pixSizeMarginFinalCoef = 4
 * pixSizeMarginInitCoef = 2
 * refineFuse = 1
 * repartition =  Unknown Type "enum ERepartitionMode"
 * saveRawDensePointCloud = 0
 * seed =  Unknown Type "unsigned int"
 * simFactor = 15
 * simGaussianSize = 10
 * simGaussianSizeInit = 10
 * universePercentile = 0.999 (default)
 * verboseLevel = "info"
 * voteFilteringForWeaklySupportedSurfaces = 1
 * voteMarginFactor = 4

[16:06:59.566208][info] Found 1 image dimension(s): 
[16:06:59.567271][info] 	- [4032x3024]
[16:06:59.572373][info] Overall maximum dimension: [4032x3024]
[16:06:59.572373][warning] repartitionMode: 1
[16:06:59.572373][warning] partitioningMode: 1
[16:06:59.572373][info] Meshing mode: multi-resolution, partitioning: single block.
[16:06:59.572373][info] Estimate space from SfM.
[16:06:59.573454][fatal] Failed to estimate space from SfM: The space bounding box is too small.

```
**Desktop (please complete the following and other pertinent information):**
 - OS: [Win10 ]
 - Python version [3.7.4]
 - Qt/PySide version [e.g. 5.15.2]
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [2021.1.0] ( Same error if updating to the newst version)

**Comment by natowi** [comment]
The box has a glossy, featureless surface, which is hard to reconstruct using photogrammetry.
As you can see (A), only two views have been reconstructed. Enable (B) to show the detected features for your images.
![grafik](https://github.com/alicevision/Meshroom/assets/8138537/90e228bc-c71f-4569-ab58-9dd4bdb99cb0)

You may get some better results placing some newspaper under your box to provide reference features for the algorithm to pick up. If this is your first test project, I´d suggest the classic beginner project "rock (rough surface)" or "tree (bark)" reconstruction.

Check out some tutorials on capturing images for photogrammetry: https://github.com/alicevision/Meshroom/wiki/Tutorials

**Comment by Mactarvish** [comment]
Thanks very much! I'll check it.
