### ISSUE TITLE
Mess instead of mesh

### ISSUE THREAD

**Issue by eXConf** [alicevision/meshroom#223]
Love the idea of this software but everytime I try it, I get some mess instead of mesh, although the SfM preview shows the correct model. Any advice on it?
SfM: http://prntscr.com/ko847c
SfM + mesh: http://prntscr.com/ko84sp
.obj: https://www.dropbox.com/s/a2tsfcayw9sa2mp/texturedMesh.obj?dl=0

P.S.> this time I used 1920x1280 photos just to speed up process. Previous attempts with 5184x3456 gave the same results.

**Comment by fabiencastan** [comment]
That's weird.
Which platform version are you using?

Could you try with the sample dataset?
https://github.com/alicevision/dataset_monstree/tree/master/mini6

**Comment by fabiencastan** [comment]
That's really surprising. We have run the pipeline on many different hardware without experiencing this problem.
I have no idea how to reproduce and fix that...

We are making many changes on the depth map gpu code, so it will be interesting to test it again when this work will be finished and integrated.

**Comment by eXConf** [comment]
The only thing I can add is that I'm not on the latest Nvidia drivers, cause for some reasons they don't get installed properly. Also I would be glad to help with any tests, just tell me what to do.

**Comment by yann-lty** [comment]
One thing that we have never tested is Windows 8, but I fail to see how this could come into play. Would be nice if someone with a working Meshroom on this OS could refute this theory though.

**Comment by Heller93** [comment]
Hi I have the exact same problem, no matter what settings I use (used the default settings and random numbers, made no difference)  I get that blob. all the while SfM looks perfect!
I don't if it could help you to figure out the problem but, generated EXR DepthMapFilters are in the shape of [stripes](http://prntscr.com/kwnwf2) , and the depth map itself looks like solid fill layer.
To test if my camera or the way I shot photos was the problem I downloaded Agisofts sample Monument file and used it's photos, which turned out the [same way](http://prntscr.com/kwq05w)( a nonsensical BLOB)- Note that I used the default setting for this .
My GPU driver isn't a powerfull one but I am able to use it for game developmet( GT 555M - and is up to date ,Windows 10, 12G RAM Core i7 2.7-(ish) GHz ).
I think the main problem is in the generation of the depth map rather than meshing node, something might not be working concerning CUDA (maybe, I don't even kno what I'm talking about! :D )...
By the way I used an iphone 6 to capture the photos.

I Hope this helps you figure out what the problem is...

**Comment by Heller93** [comment]
> That's really surprising. We have run the pipeline on many different hardware without experiencing this problem.
> I have no idea how to reproduce and fix that...
> 
> We are making many changes on the depth map gpu code, so it will be interesting to test it again when this work will be finished and integrated.

Hi I have the exact same problem, no matter what settings I use (used the default settings and random numbers, made no difference)  I get that blob. all the while SfM looks perfect!
I don't if it could help you to figure out the problem but, generated EXR DepthMapFilters are in the shape of [stripes](http://prntscr.com/kwnwf2) , and the depth map itself looks like solid fill layer.
To test if my camera or the way I shot photos was the problem I downloaded Agisofts sample Monument file and used it's photos, which turned out the [same way](http://prntscr.com/kwq05w)( a nonsensical BLOB)- Note that I used the default setting for this .
My GPU driver isn't a powerfull one but I am able to use it for game developmet( GT 555M - and is up to date ,Windows 10, 12G RAM Core i7 2.7-(ish) GHz ).
I think the main problem is in the generation of the depth map rather than meshing node, something might not be working concerning CUDA (maybe, I don't even kno what I'm talking about! :D )...
By the way I used an iphone 6 to capture the photos.

I Hope this helps you figure out what the problem is...

**Comment by Stano71** [comment]
I have the same problem  and believe its cuda related due to the errors in the logs.... ???
https://github.com/alicevision/meshroom/issues/258

**Comment by ricston94** [comment]
I get similar results to the above mentioned ones. I have both Windows 10 and Ubuntu 16.04 on my computer and I got the same results in them. The sfm looks perfect but then the mesh just becomes a blob.

I have the following hardware in my laptop:
Processor: Intel i5 3230M
VGA: Intel HD 4000 and NVidia GForce 635M
RAM: 8GB

I use the release version 2018.1.0 of MeshRoom.

(I run MeshRoom on Ubuntu with the command: LD_LIBRARY_PATH=/usr/lib/nvidia-384 ./Meshroom to use the right driver)

**Comment by Stano71** [comment]
Is the problem caused by older GPUs (635m and lower) that only allow installation of cuda 8 ????????
 Is a workaround possible?

**Comment by TristanHehnen** [comment]
I would like to report that I'm experiencing similar issues. 
The sfm point cloud looks fine, the mesh however is not. I had two instances where I took pictures of an object placed in the middle of a room. The point cloud was relatively dense showing a good approximation of the object, as well as some parts of the floor around it. However, the mesh consisted only of the walls of the room, its floor and party of the corridor (I left the door open), while the object itself was not part of the mesh at all. 
This seemed odd, the point cloud and the mesh basically show complementary parts of the whole scene as if both only get parts of it that somehow aren't connected.

System:
Windows 10 Pro, 64 bit, v. 1803
i9-7900X
64 GB RAM
nvidia GTX 1080 Ti, driver: 411.70

**Comment by ChemicalXandco** [comment]
It is worth noting that the point cloud and the mesh are completely different, they formed by different processes.

**Comment by TristanHehnen** [comment]
Okay, good to know. 

I just thought that they were related and that the mesh was to be built from information of the sfm point cloud. Looking at the default node setup it looks like, at least at first glance, that the sfm point cloud is used as input for the group of nodes that later creates the depth map and the mesh.

Could I just simply remove all nodes after sfm and somehow create the mesh from the point cloud directly?

**Comment by ChemicalXandco** [comment]
@TristanHehnen take a look at #266 you can then use [meshlab](http://www.meshlab.net/) to attempt a poission reconstruction but I can't guarantee it will turn out very well depending on how many points there are.

**Comment by TristanHehnen** [comment]
I'll have  a look. 
Thank you very much!

**Comment by fabiencastan** [comment]
@TristanHehnen This sounds like a bug in our cuda code. I have no idea where it comes from yet and why it appears only on some machines. Unfortunately it's difficult to debug without being able to reproduce it. We have made some preliminary clean up in this part, so I would be interested to see if it's fixed in the next release.

> Could I just simply remove all nodes after sfm and somehow create the mesh from the point cloud directly?

This will be possible in the next release (already in the "develop" branch). The quality of the final mesh is much lower (you can set FeatureExtraction.preset to HIGH or ULTRA to increase a bit the density).

**Comment by wienio2** [comment]
Hello,

unfortunately i have exactly the same problem.... exacly the same effect like here (tried exactly the same photos as input):
https://user-images.githubusercontent.com/6028657/46792925-c8ec2b80-cd87-11e8-98d6-4edca5e07168.jpg

Processor: Intel i5
GPU: NVidia GeForce GT 730
RAM: 8GB
System: Windows 7 64bit

NVidia driver version: 391.35.
There are newer drivers for GEForce 700 series, but for GT 730 it is only possible to install 391.35 as newer version (this card is no more supported by nvidia and you can not install newer drivers as 391.35).

On the same hardware i tried it with 3DF Zephyr Free and with this software it works perfect. So it seams not to be a hardware or driver problem. It seam to be a bug in your software ...

How can i help you, so you can analyze the problem and try to fix it ? Some logs whould help?
Please advice me ... i will send you all infos what you need.

**Comment by fabiencastan** [comment]
As said before, it's probably a bug on our side that is only visible on some graphic cards.

To help us to find the problem, you can launch the depth map computation in cuda-memcheck.
For that, you can see the command line launched by meshroom on the "DepthMap" node.
Then run this command with cuda-memcheck, like:
`cuda-memcheck aliceVision_depthMapEstimation ALL_THE_PARAMETERS`
and send us the log.

**Comment by wienio2** [comment]
Ok, i will do that on monday ...then i have the access to the hardware where i have the problem.

How to do it exactly in windows?
Do i need to install CUDA SDK ?
Then start the Meshroom as usuall (Meshroom.exe), create some project and compute it till "camera connection". 
Then from windows command line run "cuda-memcheck aliceVision_depthMapEstimation ALL_THE_PARAMETERS" ?

Or should i start this command on different way ?

**Comment by Stano71** [comment]
> As said before, it's probably a bug on our side that is only visible on some graphic cards.
> 
> To help us to find the problem, you can launch the depth map computation in cuda-memcheck.
> For that, you can see the command line launched by meshroom on the "DepthMap" node.
> Then run this command with cuda-memcheck, like:
> `cuda-memcheck aliceVision_depthMapEstimation ALL_THE_PARAMETERS`
> and send us the log.

Hi FabienCasten, I did as you suggested in windows powershell and  have attached the resulting output outputA,.......................( CMD.exe returns a different result (no errors) see CMDoutput.txt) 


[outputA.txt](https://github.com/alicevision/meshroom/files/2682338/outputA.txt)    I hope this is what you are looking for, thanks for your help 


Program called with the following parameters:
 * downscale = 2
 * ini = "C:/Users/Stano71/Documents/MeshroomSave/MeshroomCache/PrepareDenseScene/248ec318eb2109f9ffab458ad38bbfa889f56e6a/mvs.ini"
 * output = "C:/Users/Stano71/Documents/MeshroomSave/MeshroomCache/DepthMap/f49e78e88436c2fdbd61de972c56c654bf096354"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 5
 * sgmWSH = 4
 * verboseLevel = "info"

number of CUDA devices:	1
   0: GeForce GT 635M
CUDA device no 0 for 0
Device 0 memory - used: 359.696869, free: 1688.303101, total: 2048.000000
Device 0 memory - used: 435.446869, free: 1612.553101, total: 2048.000000
========= CUDA-MEMCHECK
========= Internal Memcheck Error: Device not supported. Please refer to the "Supported Devices" section of the cuda-memcheck documentation
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:C:\WINDOWS\system32\nvcuda.dll (cuGraphicsResourceGetMappedPointer + 0x1a6704) [0x1b3dd8]
=========     Host Frame:C:\meshroom\alicevision\bin\cudart64_91.dll (_cudaInitManagedRuntime + 0x886c) [0x15d2c]
=========     Host Frame:C:\meshroom\alicevision\bin\cudart64_91.dll (_cudaInitManagedRuntime + 0x8a30) [0x15ef0]
=========     Host Frame:C:\meshroom\alicevision\bin\cudart64_91.dll (_cudaInitManagedRuntime + 0x93e6) [0x168a6]
=========     Host Frame:C:\meshroom\alicevision\bin\cudart64_91.dll (_cudaInitManagedRuntime + 0x58a3) [0x12d63]
=========     Host Frame:C:\meshroom\alicevision\bin\cudart64_91.dll [0x57f3]
=========     Host Frame:C:\meshroom\alicevision\bin\cudart64_91.dll (cudaMemGetInfo + 0xea) [0x2296a]
=========     Host Frame:C:\meshroom\alicevision\bin\aliceVision_depthMap.dll (aliceVision::depthMap::pr_printfDeviceMemoryInfo + 0x21) [0x38c51]
=========     Host Frame:C:\meshroom\alicevision\bin\aliceVision_depthMap.dll (aliceVision::depthMap::ps_deviceAllocate + 0x128) [0x3eab8]
=========     Host Frame:C:\meshroom\alicevision\bin\aliceVision_depthMap.dll (aliceVision::depthMap::PlaneSweepingCuda::PlaneSweepingCuda + 0x6f8) [0x23e78]
=========     Host Frame:C:\meshroom\alicevision\bin\aliceVision_depthMap.dll (aliceVision::depthMap::computeDepthMapsPSSGM + 0x31d) [0x1d16d]
=========     Host Frame:C:\meshroom\alicevision\bin\aliceVision_depthMap.dll (aliceVision::depthMap::computeDepthMapsPSSGM + 0x26a) [0x1d75a]
=========     Host Frame:C:\meshroom\alicevision\bin\aliceVision_depthMapEstimation.exe [0x14c92]
=========     Host Frame:C:\meshroom\alicevision\bin\aliceVision_depthMapEstimation.exe [0x159a5]
=========     Host Frame:C:\WINDOWS\System32\KERNEL32.DLL (BaseThreadInitThunk + 0x14) [0x13034]
=========     Host Frame:C:\WINDOWS\SYSTEM32\ntdll.dll (RtlUserThreadStart + 0x21) [0x73691]
=========
========= Internal Memcheck Error: Initialization failed
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:C:\WINDOWS\system32\nvcuda.dll (cuGraphicsResourceGetMappedPointer + 0x1a6704) [0x1b3dd8]
=========     Host Frame:C:\meshroom\alicevision\bin\cudart64_91.dll (_cudaInitManagedRuntime + 0x886c) [0x15d2c]
=========     Host Frame:C:\meshroom\alicevision\bin\cudart64_91.dll (_cudaInitManagedRuntime + 0x8a30) [0x15ef0]
=========     Host Frame:C:\meshroom\alicevision\bin\cudart64_91.dll (_cudaInitManagedRuntime + 0x93e6) [0x168a6]
=========     Host Frame:C:\meshroom\alicevision\bin\cudart64_91.dll (_cudaInitManagedRuntime + 0x58a3) [0x12d63]
=========     Host Frame:C:\meshroom\alicevision\bin\cudart64_91.dll [0x57f3]
=========     Host Frame:C:\meshroom\alicevision\bin\cudart64_91.dll (cudaMemGetInfo + 0xea) [0x2296a]
=========     Host Frame:C:\meshroom\alicevision\bin\aliceVision_depthMap.dll (aliceVision::depthMap::pr_printfDeviceMemoryInfo + 0x21) [0x38c51]
=========     Host Frame:C:\meshroom\alicevision\bin\aliceVision_depthMap.dll (aliceVision::depthMap::ps_deviceAllocate + 0x128) [0x3eab8]
=========     Host Frame:C:\meshroom\alicevision\bin\aliceVision_depthMap.dll (aliceVision::depthMap::PlaneSweepingCuda::PlaneSweepingCuda + 0x6f8) [0x23e78]
=========     Host Frame:C:\meshroom\alicevision\bin\aliceVision_depthMap.dll (aliceVision::depthMap::computeDepthMapsPSSGM + 0x31d) [0x1d16d]
=========     Host Frame:C:\meshroom\alicevision\bin\aliceVision_depthMap.dll (aliceVision::depthMap::computeDepthMapsPSSGM + 0x26a) [0x1d75a]
=========     Host Frame:C:\meshroom\alicevision\bin\aliceVision_depthMapEstimation.exe [0x14c92]
=========     Host Frame:C:\meshroom\alicevision\bin\aliceVision_depthMapEstimation.exe [0x159a5]
=========     Host Frame:C:\WINDOWS\System32\KERNEL32.DLL (BaseThreadInitThunk + 0x14) [0x13034]
=========     Host Frame:C:\WINDOWS\SYSTEM32\ntdll.dll (RtlUserThreadStart + 0x21) [0x73691]
=========
========= ERROR SUMMARY: 2 errors

-------------------------
[CMDoutput.txt](https://github.com/alicevision/meshroom/files/2682340/CMDoutput.txt)

**Comment by Stano71** [comment]
Sorry for the bold text .... I used the command below.....
\alicevision\bin> cuda-memcheck aliceVision_depthMapEstimation  --ini "C:/Users/Stano71/Documents/MeshroomSave/MeshroomCache/PrepareDenseScene/248ec318eb2109f9ffab458ad38bbfa889f56e6a/mvs.ini" --downscale 2 --sgmMaxTCams 5 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineMaxTCams 6 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --verboseLevel info --output "C:/Users/Stano71/Documents/MeshroomSave/MeshroomCache/DepthMap/f49e78e88436c2fdbd61de972c56c654bf096354" --rangeStart 0 --rangeSize 3 > output.txt    
is there a better way to log the output?

**Comment by Vojtik69** [comment]
Same for me.
If it helps:
NVIDIA GT 545, driver 388.73
CUDA 9.1.126 driver

**Comment by ccode111** [comment]
![whyyy](https://user-images.githubusercontent.com/46238944/50535123-c9a28b80-0b46-11e9-90da-ca23e75b42ce.jpg)
 i have same exact problem on fresh windows 10... instaled by computer scientist with 0 errors at doing anythign beside this meshroom software making a huge blob instead mesh... why :/ ? gpu is GTS 450 driver 391.35 has 192 cuda cores and suports 2.0 and above picture is in attachment

**Comment by fabiencastan** [comment]
@ccode111 : I still don't know if it comes from depth maps or meshing...
In the next release, we will include the 3D depth maps viewer in the windows binaries, so we will be able to visualize where the problem comes from.

**Comment by stuffactory** [comment]
I also have the same problem. Everything is passing just fine but the final mesh is wrong. I try the latest video drivers from nvidia, also an old version with no luck.
I suspected the old video on my PC, but found people with newer models that had the same problem.

Here's the setup:
NVIDIA GeForce GTX 460
Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
16Gb Ram

Hope you are releasing new version soon and you had fix this problem.

**Comment by justi2** [comment]
To end this in a positive note, I would like to chime in and say that I downloaded and installed Meshroom-2018.1.0win7-64.zip onto my:
Dell Precision M4800
i7 processor 
Win 7 64bit
16 gb ram
Quadra K2100M

I had to install:
Visual C Plus Plus 2013 (vcredist_x64.exe) Microsoft Download 
Visual C Plus Plus 2015 (vcredist_x64.exe, vcredist_x86.exe) Microsoft Download
Latest Nvidia graphics driver (412.16-quadro-desktop-notebook-win8-win7-64bit-international-while.exe)

I downloaded and ran Cherub pic set with meshroom default settings. Took a little time......but impressive!

Totally understand why it will not run on all machines beings how I come from a pro/engineer environment. But one should not be stressed out over free software if it does not work on a their pc. You will just need to upgrade your pc like I had to.

Thanks for the free software to learn photogrammetry, I’m sure I will have many hours of fun!

**Comment by ccode111** [comment]
This upgrading my older setup just made me back off from this free software
all completly , yes i will upgrade now but i will buy some more
professional software that is scripted so good it can run even in stone age
, thanks again....

sub, 19. sij 2019. 21:32 justi2 <notifications@github.com> je napisao:

**Comment by Boomslang10** [comment]
I have the same issue, Win7x64; 8bg ram, GTX550Ti.

Maybe it might be Compute V2.1 cards that have this issue?

**Comment by Shrediquette** [comment]
Same issue here... What a pity, I was so much looking forward to work with meshroom... Is there nothing I could do?

Microsoft Windows 10 Pro
Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz, 2701 MHz
GeForce GTX 560 Ti
c:\windows\system32\driverstore\filerepository\nv_ref_pubwu.inf_amd64_708ec8f9a4d134c6\nvlddmkm.sys (23.21.13.9135)

![sfm](https://user-images.githubusercontent.com/42935970/54203446-94190780-44d2-11e9-8c40-662645c4e766.JPG)
![mess](https://user-images.githubusercontent.com/42935970/54203448-94190780-44d2-11e9-8fd0-8527fc6d4030.JPG)

**Comment by fabiencastan** [comment]
Could you try again with the release 2019.1.0?
https://github.com/alicevision/meshroom/releases/tag/v2019.1.0

**Comment by Shrediquette** [comment]
Hi Fabien,
thanks for that comment. With the latest release, I do actually get a good mesh with the sample dataset! But none of my own projects work anymore. I think the program stops (at least the "start button" becomes green again), and the log shows:

```
.....
WARNING: downgrade status on node "DepthMapFilter_1(70)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(71)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(72)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(73)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(74)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "PrepareDenseScene_1(15)":
Log:
Program called with the following parameters:
 * input = "C:/Users/Siva/Documents/Python_test/GoPro Calibration/Recorded_Images/135GOPRO/undistort/MeshroomCache/StructureFromMotion/af981532c6497b3be9c35c06a1f4a3455eae9cec/sfm.abc"
 * output = "C:/Users/Siva/Documents/Python_test/GoPro Calibration/Recorded_Images/135GOPRO/undistort/MeshroomCache/PrepareDenseScene/4b756ea95f412dbfb91bb910dfccf57ed96e1356"
 * outputFileType = "exr"
 * rangeSize = 40
 * rangeStart = 600
 * saveMatricesTxtFiles = 0
 * saveMetadata = 1
 * verboseLevel = "info"

Exporting Scene Undistorted Images
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*******************************************
```

**Comment by fabiencastan** [comment]
That's really surprising to get an error on the PrepareDenseScene, that's the most simple node...
Could you put the verbose to "trace" on this node to see if you get more information?

**Comment by Shrediquette** [comment]
I couldn't reproduce the error above. Now I get an error during DepthMap...:

[error.txt](https://github.com/alicevision/meshroom/files/2961658/error.txt)

**Comment by Boomslang10** [comment]
2019 Is working for me. Also got an appcrash during depthmap, scaled pics down to 2mp to get it working. Looks like the 1gb ram on my gtx550 is not enough.

**Comment by fabiencastan** [comment]
Instead of downscaling the source images, you can use the `downscale` factor on the DepthMap node.
So SfM still benefits from the full resolution.

**Comment by macbibi33** [comment]
I have the same issue with release 2019.1.0
Microsoft Windows 10
Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz, 3.4 MHz
RAM 12 Go
GeForce GTX 645

**Comment by macbibi33** [comment]
![image](https://user-images.githubusercontent.com/49074301/55249637-ceadce80-524c-11e9-96c9-ba4be4544d19.png)

**Comment by macbibi33** [comment]
![image](https://user-images.githubusercontent.com/49074301/55249730-0e74b600-524d-11e9-8e12-fc776183aec3.png)
