### ISSUE TITLE
Warning at start that cuda is not present

### ISSUE THREAD

**Issue by canonex** [alicevision/meshroom#224]
Currently Meshroom warn you, with a message _only in the console_, that you need a Cuda enabled harware, only when you reach "Prepare dense scene" node.

Would be handy not to start a project if you don't have the correct hardware (or driver installed):
a solution could be to **prompt the warning immediatly** when you start the software.

Thank you,
Riccardo

**Comment by KFFTFUFTUR** [comment]
also it would be great to add the information that meshroom needs Cuda on the Project page so people like me who have a powerfull AMD card dont install it just to see that it was incompatible with their system.

or you might just add CPU or maybe even OpenCL Support, but usually people who use CUDA dont care about others not having the hardware.

**Comment by fabiencastan** [comment]
Yes, it would be good to add a warning when starting the application. We could add an invalid status on the GPU nodes if we cannot compute them locally (but can still submit them).

Regarding the download page, it's already indicated explicitly that "NVIDIA CUDA-enabled GPU (compute capability >= 2.0)" is required: https://github.com/alicevision/meshroom/releases

**Comment by MightyBOBcnc** [comment]
Agreed, it would be user-friendly to run this check on program start and present a notification.
