### ISSUE TITLE
CUDAError: an illegal memory access was encountered

### ISSUE THREAD

**Issue by DGhost001** [alicevision/meshroom#225]
Whenenver I try to reconstruct the depthmap the program crashes with a SigSev after reporting tons of CUDA illegal memory access errors.

Like:
``
 CUDAError: an illegal memory access was encountered
  file:       /opt/AliceVision_git/src/aliceVision/depthMap/cuda/planeSweeping/plane_sweeping_cuda.cu
  function:   ps_deviceUpdateCam
  line:       402
``
And this one:

``
CUDAError: an illegal memory access was encountered
  file:       /opt/AliceVision_git/src/aliceVision/depthMap/cuda/planeSweeping/plane_sweeping_cuda.cu
  function:   ps_computeSimilarityVolume
  line:       1010
``

The complete log is here:
[0.log.txt](https://github.com/alicevision/meshroom/files/2333045/0.log.txt)

**Comment by judge-mental** [comment]
Exactly the same problem on Ubuntu 16.04 ending with 'Segmentation fault (core dumped)':
MBPro Intel® Core™ i7-4960HQ CPU @ 2.60GHz × 8 
GeForce GT 750M/PCIe/SSE2

**Comment by PKeidel** [comment]
I get the error "Device free failed, an illegal memory access was encountered" at step "DepthMap". Could this be related to this bug here?

The first Chunk works, the second aborts.

This are the last view lines of the log:
```
Device 0 memory - used: 1969.062500, free: 2072.625000, total: 4041.687500
total size of volume map in GPU memory: 66.577148
nDepths 505, nDepthsToSearch 505 
ps_computeSimilarityVolume elapsed time: 3.302000 ms 
ps_SGMoptimizeSimVolume
ps_updateAggrVolume
ps_aggregatePathVolume
ps_aggregatePathVolume done
ps_updateAggrVolume done
terminate called after throwing an instance of 'std::runtime_error'
  what():  Device free failed, an illegal memory access was encountered
Aborted
```

Version 2019.2.0
Linux 5.0.0-29-generic 
Python 3.6.3
