### ISSUE TITLE
Sensor width doesn't exist in the database, but how can I add it?

### ISSUE THREAD

**Issue by alrayel** [alicevision/meshroom#226]
Hi guys,

I'm a 3D designer and found out today about meshroom and gave it a try with my Sony Xperia Z5 mobile.
I already searched for this issue but without success. I actually found someone with same problem but it didn't work for me.

I found that the sensor for the camera on Xperia Z5 is 1/2.3" (~ 6.16 x 4.62 mm) and I have added "Sony;Sony E6663;6.16" to the camersensors.db file (is it the one at X:\Meshroom-2018.1.0\aliceVision\share\aliceVision????)

See a print of the error below... Let me know if you got any hint on this one 👍 

![image](https://user-images.githubusercontent.com/42814845/44804885-11190b00-ab99-11e8-8c18-caa53d288f3b.png)

**Comment by chrisnagy** [comment]
Try using Photoshop to make your images bigger sizes at least eight megapixels

**Comment by ChemicalXandco** [comment]
@chrisnagy just no. The error is not because of resolution probably same as [#179 (comment)](https://github.com/alicevision/meshroom/issues/179#issuecomment-413016629)

**Comment by fabiencastan** [comment]
@alrayel : Have you tried to add `Sony;E6663;6.16` to the camersensors.db file as suggested by @hcw70 ?
This is supposed to work.

**Comment by Marsleader** [comment]
I am getting the error:
```
[03:19:37.002221][error] Sensor width doesn't exist in the database for image(s) :
[03:19:37.002221][error] image: 'IMG_1577.JPG'
	- camera brand: Canon
	- camera model: Canon EOS REBEL T5

[03:19:37.003221][error] Please add camera model(s) and sensor width(s) in the database.
```
I checked the cameraSensors.db and my camera is already in there. After reading these comments I'm still not sure I see an answer or am I missing something?

**Comment by alrayel** [comment]
Thank you all for the replies
@fabiencastan Yes, I tried Sony;E6663;6.16 and no do :(

I had checked #179 before, but I don't see where those spaces are to change the name of my camera...

**Comment by hcw70** [comment]
@Marsleader Are you shure that camera is in (with exact name)?
i only get:
`Canon;Canon EOS Rebel T5 / 1200D;22.3
`
which is not the exact name from your log line. Maybe try adding with the exact reported name.

**Comment by Marsleader** [comment]
Unfortunately no success. I copy pasted the name and even another with an extra space at the beginning that I noticed in the log. nothing. My database looks like: 
```
....
Canon;Canon EOS Rebel T4i / 650D;22.3
Canon;Canon EOS Rebel T5 / 1200D;22.3
Canon;Canon EOS REBEL T5 / 1200D;22.3
Canon; Canon EOS REBEL T5 / 1200D;22.3
Canon;Canon EOS Rebel T5i / 700D;22.3
.....
```
would shooting in RAW fix this problem?

**Comment by yann-lty** [comment]
@Marsleader @alrayel  Have you tried to recreate a project from scratch after editing the sensor database file? Re-opening a file saved before this modification won't help as it's already initialized.
If your model is properly recognized, you should not see the orange aperture icon on your images anymore after dropping them into Meshroom.

@alrayel I might be asking an already answered question but have you also tried the simpler:
`Canon;Canon EOS Rebel T5;22.3`
?

**Comment by FrostyPenguin** [comment]
I had the same problem with my SONY DSC-HX9V.

It took me some minutes until I noticed that the console output was not `"SONY"` and `"DSC-HX9V"` but
`"SONY"` and `"DSC-HX9V               "` (it's hard to see but there are 15 spaces behind the model number).

After adding this entry to my database file (with the spaces)
```
SONY;DSC-HX9V               ;7.77
```
everything worked just fine.

Perhaps you missed some spaces too.
Definitely, I'd say this is a bug and Meshroom should either remove the extra spaces or ignore them in the database file.

Hope that helps! :pray:

**Comment by jbcoulter** [comment]
How do I find the sensor depth for my Canon EOS Digital Rebel XT ?
![img_0101](https://user-images.githubusercontent.com/5018732/49701620-20015780-fba3-11e8-967e-5873425497ae.JPG)
![capture](https://user-images.githubusercontent.com/5018732/49701634-4626f780-fba3-11e8-83fb-58ab8579b8e0.JPG)

I tried adding to the database a Canon's sensor width from one in the database, in a glorious attempt to bypass the error = fail.

**Comment by jbcoulter** [comment]
I got it.
Canon;Canon EOS DIGITAL REBEL XT;22.2

Playing around with other syntax (in this case removing spaces) worked.

**Comment by oo5p4c3oo** [comment]
check the jpeg exif info( camera type line) and this type insert in the cameradatabase 

my modyfied line for sony XZ premium
Sony;G8141;4.69
