### ISSUE TITLE
[bug] View Depth Map in 3D crashes Meshroom

### ISSUE THREAD

**Issue by natowi** [alicevision/Meshroom#2307]
**Describe the bug**
- View Depth Map in 3D crashes Meshroom

**To Reproduce**
- Compute Depthmap
- Click on View Depth Map in 3D button

Meshroom 2023.3

**Comment by cbentejac** [comment]
This issue is already fixed with https://github.com/alicevision/QtAliceVision/pull/63/files, it will be part of the next Meshroom release.
