### ISSUE TITLE
failed to import 

### ISSUE THREAD

**Issue by hanjoonwon** [alicevision/Meshroom#2317]
my image like that 
![image](https://github.com/alicevision/Meshroom/assets/125524043/5cdc73db-bd4c-452c-a292-e82f9c59390d)
![image](https://github.com/alicevision/Meshroom/assets/125524043/3de975e8-c58b-45e2-ad6e-1e1d51da2c00)
when i import my images, error occured

**Comment by natowi** [comment]
Did you check that there are only English characters in the path?

**Comment by MrClock8163** [comment]
Also check that there are no white spaces in the path

**Comment by hanjoonwon** [comment]
> Did you check that there are only English characters in the path?

Thanks

**Comment by hanjoonwon** [comment]
O9
