### ISSUE TITLE
is there any introduction to use CameraCalibration?

### ISSUE THREAD

**Issue by eroswade** [alicevision/meshroom#233]
i searched on google, and can't find anything about how to use cameracalibration node on meshroom. 
the most important part is
1, i find structfrommotion node refined the camera internal martix. 
  if i use camera calibration, how to forbit use refine?
2 how to use camera calibration result to init camera? camera connection node?

**Comment by fabiencastan** [comment]
This node is not yet available in the binaries of the current release (as it needs to build many additional dependencies), but it will probably be in the next release.
So currently, you can only use it if you built it yourself. Also we currently use it only for camera tracking and it cannot yet be directly connected to the SfM pipeline in the UI. That would be obviously a nice feature to have. The camera models and parameters are the same, so you could use the resulting values and put them into the pipeline manually.
So it just needs a bit more work before using it directly into the Meshroom graph. If someone is interested to contribute to this feature, we would be glad to provide assistance.

Also the parameter to lock the intrinsics of a specific camera has been added in AliceVision but is not yet exposed in Meshroom. This will be added soon.

**Comment by eroswade** [comment]
thanks fabiencastan .
then, how to add result values manually, into pipeline? 
that's the first question i've answered above. 
though i haven't read all the code. (meshroom, and AliceVision lab), is there any hints?

**Comment by eroswade** [comment]
thank you so much

**Comment by eroswade** [comment]
i find that . in AliceVision lib--> software->pipeline->main_incrementalSfM.cpp . line 266
that's can lock the refine intrinsics. 
and this parameter not used in meshroom. 
but i can change it manuly . or add it to meshroom .
