### ISSUE TITLE
[question] How to obtain pictures from a reconstruction

### ISSUE THREAD

**Issue by alsozatch** [alicevision/Meshroom#2336]
I'm trying to see if there is a functionality in Meshroom for _obtaining_ new pictures of the scene based on a reconstruction that you have already made. When looking for this topic all I find are people asking how to obtain good photos to reconstruct with, but I have no issues with that. 

I'm seeing if I can specify a new Camera position and orientation, and then capture what that Camera would see based on the reconstruction, or even some intermediate step like a point cloud or something.

Thanks!

**Comment by natowi** [comment]
You can load Meshroom data in Blender and render new views from there

**Comment by alsozatch** [comment]
Thanks
