### ISSUE TITLE
Saving takes forever on 3.0 [question] [linux] [bug?]

### ISSUE THREAD

**Issue by FarmFarmInc** [alicevision/Meshroom#2338]
When I go save (even empty projects), it takes about 10 minutes for the window to appear, and it never seems to load to the point of letting me interact with the window. CPU usage hovers around 50% like it’s trying to do something. 

Downgrading to 2023.2.0 resolved the issue 

 - OS: Ubuntu 
 - User error potential: 67.3
 - Meshroom version: 2023.3.0 (I do not have this issue with 2023.2.0)

**Comment by msanta** [comment]
I have the same issue in 2023.3 where the file dialog becomes basically unresponsive.

**Comment by cbentejac** [comment]
Hi,

There is an issue with native dialogs on Linux with Qt 5.15 (which is used for Meshroom 2023.3.0) that causes the file dialogs to sometimes be unresponsive. 

A workaround is available in the `develop` branch of Meshroom (https://github.com/alicevision/Meshroom/pull/2439) and will be part of the next release.
