### ISSUE TITLE
[question] CCTag ID extraction

### ISSUE THREAD

**Issue by hofbauerc** [alicevision/Meshroom#2343]
Hello,

I am trying to apply CCTag detection on some images. My workflow works without issues. However, I also want to know the ID of each CCTag detected in the image. 

The FeatureExtraction part of the pipeline generates .feat files which describe the position, orientation and scale of each feature detected in the image. 

But how do i know the ID of each feature? Am I missing something?

**Comment by natowi** [comment]
I´d recommend to print markers with IDs. ID labeling in the image viewer is currently not supported.

With MR2023+ it is possible to debug the markers detected in the scene by writing all marker numbers and their relative distance to each other into the node log of the SMDistance node: ![234114967-f610c472-fcd2-4c87-a3eb-5a92e0528868](https://github.com/alicevision/Meshroom/assets/8138537/227fe128-00ac-4f4d-bb56-bee33cc89a5f)

So in combination this is good for testing the scaling process: ![234116473-cb87f8be-822e-4355-a649-ea932727dc10](https://github.com/alicevision/Meshroom/assets/8138537/67267902-7ad8-4c34-8f68-6d0f313f34e8)

**Comment by simogasp** [comment]
The ID is encoded in the descriptor.
The descriptor is a 128-element array, each element is set to 0 but the one corresponding to the id which is set to 255.
I.e marker with id 12 has descriptor 0 0 0 0 0 0 0 0 0 0 0 255 0 0... 0

you can see it here
https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/feature/cctag/ImageDescriber_CCTAG.hpp#L125

The id is not exposed in Meshroom interface at the moment

**Comment by hofbauerc** [comment]
Hi,

I think I found a solution now to my Problem. I applied a ConvertSFMFormat to my output of the pipleine. Then I get a Json where the CCTag Landmark is described as this:

 {
            "landmarkId": "831",
            "descType": "cctag3",
            "color": [
                "2",
                "0",
                "0"
            ],
            "X": [
                "-0.92568343877792358",
                "-0.59823548793792725",
                "-1.7420458793640137"
            ],
            "observations": [
                {
                    "observationId": "514805430",
                    "featureId": "2",
                    "x": [
                        "1856.0899658203125",
                        "4168.02001953125"
                    ],
                    "scale": "218.6300048828125"
                },
                {
                    "observationId": "744141116",
                    "featureId": "1",
                    "x": [
                        "2514.85009765625",
                        "3634.89990234375"
                    ],
                    "scale": "195.1199951171875"
                },
                {
                    "observationId": "938362682",
                    "featureId": "1",
                    "x": [
                        "331.06100463867188",
                        "4045.320068359375"
                    ],
                    "scale": "167.1199951171875"
                },
                {
                    "observationId": "1305785324",
                    "featureId": "1",
                    "x": [
                        "1289.760009765625",
                        "3492.760009765625"
                    ],
                    "scale": "305.5419921875"
                }
            ]
        },

I did some comparisons of landmarks and images and if I am not mistaken, the first color value represents the ID of the cctag.

Is that correct?

**Comment by MrClock8163** [comment]
It is
The marker ID is stored in the red value

**Comment by hofbauerc** [comment]
Thanks again, that answers my question.
