### ISSUE TITLE
Why is it stuck with this orange bar?

### ISSUE THREAD

**Issue by joaonoob22** [alicevision/Meshroom#2356]
Since yesterday the program stopped in the "meshing" node, I don't know what to do guys, I really need this to work for today
![why-is-it-stuck-in-the-meshing-v0-yy3jz759marc1](https://github.com/alicevision/Meshroom/assets/165405300/28b05267-721b-439c-9f38-a3a4e5d8f18b)

**Comment by msanta** [comment]
In the node editor toolbar there is the option to force unlock nodes.
![image](https://github.com/alicevision/Meshroom/assets/5391990/54923232-d5ee-4066-b20f-15e14cbcfe14)

**Comment by joaonoob22** [comment]
> In the node editor toolbar there is the option to force unlock nodes. ![image](https://private-user-images.githubusercontent.com/5391990/318739385-54923232-d5ee-4066-b20f-15e14cbcfe14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNTc3MDgsIm5iZiI6MTcxMjA1NzQwOCwicGF0aCI6Ii81MzkxOTkwLzMxODczOTM4NS01NDkyMzIzMi1kNWVlLTQwNjYtYjIwZi0xNWUxNGNiY2ZlMTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMTEzMDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTcwMDhiNjAzNzQ5ZDc5YjdmMWFjYzY3NjM0OTQ2YzNkZGYyMTBhMDNkY2IyYzc3Y2E2NGNjNmUxYjcxNzZjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JjTMGZTtLW9POTFwcvDBUlXwMol0yZiYjzh6VXQDtlw)

It doesn't work :(

**Comment by msanta** [comment]
What about clearing the pending status for the node?
![image](https://github.com/alicevision/Meshroom/assets/5391990/1953d149-3f2f-45b2-9dd9-3372fdacdd9a)

**Comment by joaonoob22** [comment]
> What about clearing the pending status for the node? ![image](https://private-user-images.githubusercontent.com/5391990/318769921-1953d149-3f2f-45b2-9dd9-3372fdacdd9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzA0MDksIm5iZiI6MTcxMjA3MDEwOSwicGF0aCI6Ii81MzkxOTkwLzMxODc2OTkyMS0xOTUzZDE0OS0zZjJmLTQ1YjItOWRkOS0zMzcyZmRhY2RkOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMTUwMTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjU4ZWZkMGM5MjBmY2JlODlmMDcwN2ZkNWJlZTRiOWU3YWNhNWMyZTM3ZWYwYzIyODFmZGE5ZDA2MDJhZWJiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nsDuqTmkkCnnEYbsgBacMeqGbAOgVtK92QjEGQSvihk)

It worked! Thank you
