### ISSUE TITLE
No camera insrinsic Paramentrs? missing metadata

### ISSUE THREAD

**Issue by anccon** [alicevision/meshroom#238]
Help me please, every time i upload pohto in meshroom at photos right top corner is yellow thing and when you put your cursor on it, it says "No Camera Instrinsic Parameters (missing metadata?)"
what to do?
Can some smart person help me?

![screenshot_1](https://user-images.githubusercontent.com/43042727/45171270-a2782500-b20a-11e8-8100-77fb829241ca.jpg)

**Comment by anccon** [comment]
What do you mean?

**Comment by ChemicalXandco** [comment]
![tempsnip](https://user-images.githubusercontent.com/32775248/45226893-c180c080-b2b7-11e8-9c23-dd9ffc4fa490.png)

**Comment by nafergo** [comment]
Maybe your camera is missing. Check this 
https://github.com/alicevision/AliceVision/issues/491
