### ISSUE TITLE
Photo alignment / meshing errors 

### ISSUE THREAD

**Issue by miikkaeli** [alicevision/meshroom#239]
Hello, thanks for releasing the binaries for this great tool! I finally got around to trying it out, and I did so on a fairly normal dataset of a birch tree. However, there is a problem with the output I got with the default settings and I couldn't really figure out which settings to change. The one on the left is from COLMAP+openMVS combination, the one on the right is Meshroom.
![comparison](https://user-images.githubusercontent.com/14274665/45200460-94152200-b279-11e8-9bf3-9c249cdb11b7.jpg)
Aside the error, the results are pretty much on par, but with Meshroom being a lot faster! :) Any tips how to fix trouble like this?

**Comment by ChemicalXandco** [comment]
So the problem is alignment? Just put matching preset to High or Ultra and sift+akaze that should do it.

**Comment by fabiencastan** [comment]
The first thing to check: How many images in input? How many cameras reconstructed in the StructureFromMotion?

Could you also copy-paste the end of the SfM log?

**Comment by miikkaeli** [comment]
Hey guys, thanks for answering! Setting the matching preset to High and also checking akaze fixed it. It took way longer but gave a clean outcome. :)

I actually checked the SfM log as well, and it would seem to me all the images were part of the earlier reconstruction so I'm assuming the initial alignment was the problem.
