### ISSUE TITLE
system requirement for designing 3d scan device

### ISSUE THREAD

**Issue by amira133** [alicevision/Meshroom#2400]
Hello
I want to design a 3D scanning device that has an accuracy of 0.1 mm and a resolution of 0.2 mm. What camera, sensors and instructions do you recommend for this?
If you know any help in this field, please send it.
Thanks

**Comment by natowi** [comment]
Depends on your use case. For macro, take a look at https://www.youtube.com/watch?v=hnB7sApWzss

**Comment by amira133** [comment]
Thanks for your reply @natowi 
I am looking for the design of a 3D handy scanning device(like [Shining 3D pro 2](https://cubeek3d.com/products/shining-3d-einscan-pro-2x?variant=44288694649110&currency=EUR&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&utm_term=&utm_campaign=&utm_source=adwords&utm_medium=ppc&hsa_acc=8753063334&hsa_cam=15948337565&hsa_grp=&hsa_ad=&hsa_src=x&hsa_tgt=&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAjw0YGyBhByEiwAQmBEWpQEuJ-zODCtvvRSqO9mQ111cwHA-38YesL4gSp5M5FGLdEu36fgnBoC7VMQAvD_BwE)), do you know any guidance on this matter, what are the challenges and what camera model is suitable for this?
As I understand, there are many cameras for this work, but I did not find an answer as to which one can produce 0.1 mm accuracy in practice. Do you have experience in this field? Is there a forum to exchange information in this field?Can use Meshroom for this accuracy?

**Comment by datavizzard** [comment]
You know that you need a laser scanner for the precision you are aiming for?

I know that a German car builder uses Shining "3D FreeScan Trio 3D Scanner" for precision. The measurement comes from the scanner and the texture from the cameras

**Comment by natowi** [comment]
https://en.openscan.eu/post/0-008mm-accuracy-with-the-openscan-mini-tutorial-mesh-analysis-using-cloudcompare-1

**Comment by amira133** [comment]
thank you @natowi
