### ISSUE TITLE
Question: Not Reconstructed

### ISSUE THREAD

**Issue by insanity180** [alicevision/meshroom#241]
I am working on my first photogrammetry project and for whatever reason I am having an issue getting multiple images (basically a third of my asset) to construct. Anyone have knowledge on why they may fail? 

My images can be found here [https://drive.google.com/drive/folders/1kXFitUqLkFnr4j3m7keTeXWc2SvrtgpI?usp=sharing] (Takes about 20min to get structure on 7700hq and 1060)

Additionally I had to add to the database my phone, "Google;Pixel 2 XL;8.01"

If anyone can help me or give me some information on what could cause an image to not construct that'd be amazing. I was unable to identify anything in the imagery to declare an error, I imagine it has to do with tolerance though.

FYI the original images were .DNG, I renamed them in file explorer to .jpg after realizing this is a variation of jpeg I guess, I used Camera FV-5 to manually control exposure and white levels. 

![meshroomhelp](https://user-images.githubusercontent.com/15659176/45233324-60012780-b2a0-11e8-8ae2-899805b67563.jpg)

**Comment by insanity180** [comment]
Update: Just changed my Describer preset to high and also added akaze to my describer type. used to have 23 images not be constructed, now I am at 13. Going to try Ultra and hope it is done before the EoD. Any recommendations would be amazing! 
![meshroomhelp2](https://user-images.githubusercontent.com/15659176/45238706-c5f5ab00-b2b0-11e8-8e41-a6c1af993190.jpg)

**Comment by EthanKoltz** [comment]
I was able to get okay results on ultra with akaze enabled on both the movement and the feature option ( I believe in away from my computer). I guess my biggest thing is why would an image not be constructed. What causes this? Also my ultra with these extra options had worse results then you so perhaps I missed settings in the mesh and texture steps.

Also I have tested this on both a 1060 and a 1070 and both have cuda cores. If anyone knows of a detailed tutorial or documentation that would help.

**Comment by ChemicalXandco** [comment]
You don't need 100% of images to be aligned, it's not the end of the day if several don't get 'constructed' as long as you can have it from most angles. The reason why they don't get reconstructed is that it can't compute the exact location of that camera, and so having that camera would only spoil the scene. Sometimes, no matter how much Ultra you put, it will still not work, but you just need to find the best settings for your particular picture set.

As for 1060/1070, there is no difference. If anything it will speed up the computation of depth map but at the moment it isn't very optimised anyway so the benefits are minuscule.

Documentation is on its way apparently, but for now, you should just refer to the [alicevision youtube](https://youtu.be/v_O6tYKQEBA) but for a more in-depth tips, refer to [CG Geek video](https://youtu.be/k4NTf0hMjtY).
