### ISSUE TITLE
How to integrate AI with the development of AI

### ISSUE THREAD

**Issue by xiaoboelse** [alicevision/Meshroom#2418]
1. With the development of AI, there may be more opportunities for meshrooms. Can we use AI to calculate images from different perspectives to reconstruct the model, but with only a few images and incomplete metadata information? Can this be achieved
2. If these few images are made into vector images for reconstruction, can we obtain smoother or more beautiful models without edges.
Thank you, thank you all for your hard work and dedication

**Comment by fabiencastan** [comment]
Yes, it's already here:
https://github.com/alicevision/MeshroomResearch
There are endless papers and tests to explore. We welcome your contributions to the experimentation in MeshroomResearch. Any findings that prove useful will be integrated into Meshroom.
