### ISSUE TITLE
GPU Not fully utilized?

### ISSUE THREAD

**Issue by DarkCluster** [alicevision/meshroom#244]
I have 2 1080 TIs,  in SLI , 64 GB RAM with a threadripper 1950X for processor. I noticed a couple of things 
1. It seemed that the GPU never went over 15% on either of the GPUs but was mostly using CPU for feature extraction.

2. It seems to take a long time to do feature matching, again, not much GPU usage.

Do i need to do something to enable GPU utilization? Also can Meshroom utilize SLI?

Thanks for the awesome work so far team! :) Is there anywhere i can see the documentation on all the nodes? Willing to help if this doesn't exist.

Cheers.
<img width="640" alt="meshroom_gpu" src="https://user-images.githubusercontent.com/43158181/45332891-1b87bd00-b528-11e8-8ace-2c653ad616ea.png">

**Comment by DarkCluster** [comment]
Seems like disabling SLI increases the GPU utilization. But you can only use 1 GPU?

**Comment by Valouleloup** [comment]
I think this is related to [#481](https://github.com/alicevision/AliceVision/issues/481)

**Comment by ChemicalXandco** [comment]
Only the depth map node uses GPU/CUDA the rest only use CPU. As you can see in this screenshot, the meshroom ui with nothing loaded/running uses some GPU, which explains the usage you are seeing: 

![cap1](https://user-images.githubusercontent.com/32775248/45370860-0f136b00-b5e1-11e8-9c2e-1adb36c51535.png)

The depthmap isn't very well optimised, as @Valouleloup pointed out. 

Please see [this thread](https://devtalk.nvidia.com/default/topic/367747/cuda-programming-and-performance/sli-use-with-cuda-programming-general-cuda-programming/) before talking about SLI. As such, you mean to have <1 GPU's for computation, I don't know if this works, I only have 1.

Refer to #186 concerning documentation.

**Comment by DarkCluster** [comment]
Seems like disabling SLI increases GPU Utilization but your right only spike i saw was in depth map calculation. Also thank you for redirection to #481 :) . I'll check out #186 as well.

Cheers!
