### ISSUE TITLE
aliceVision_cameraCalibration: not found

### ISSUE THREAD

**Issue by bhallnz** [alicevision/meshroom#245]
Using the prebuilt linux binary release (2018.1.0) and attempting CameraCalibration results in:

ERROR:root:Error during Graph execution Error on node "CameraCalibration_1":
Log:
/bin/sh: 1: aliceVision_cameraCalibration: not found

Full steps to reproduce the problem: Right click in "Graph Editor" >  "CameraCalibration" to create a cameraCalibration node. Right click the new node and hit "Compute".

It appears that there is no aliceVision_cameraCalibration executable.

**Comment by fabiencastan** [comment]
Yes, the first binary release (2018.1.0) doesn't include dependencies that are not required for the main 3D reconstruction pipeline.
This will be available in a next release.
