### ISSUE TITLE
Alicevision only using 1 GPU?

### ISSUE THREAD

**Issue by rygo6** [alicevision/meshroom#250]
I tried Alicevision on a machine with 8 Nvidia K80's installed. It seemed to only utilize one. Is this correct? Is there someway to get aliceVision to use all GPU's?

AliceVision does recognize all 8 K80's. It reports seeing all 8 of them multiple times.

**Comment by ChemicalXandco** [comment]
Is this the same as #244? 8 Nvidia K80's is very overkill, and depthmap is not optimised anyway. Even if you could get all of them to be utilised, it's just not worth it. I've not ran it with more then one GPU, but it seems correct.

**Comment by natowi** [comment]
Multi GPUs are now supported, but DepthMap is still not fully optimized
