### ISSUE TITLE
Complex Models Dont Mesh

### ISSUE THREAD

**Issue by chrisnagy** [alicevision/meshroom#251]
The more Complex Model the more It gets stuck on Meshing and will not go further

Nodes to execute:  ['Meshing_1', 'MeshFiltering_1', 'Texturing_1']

[1/3] Meshing
 - commandLine: aliceVision_meshing  --ini "C:/Users/Dragon Stone/Desktop/Bench/MeshroomCache/PrepareDenseScene/2781cadb0ef13a4e0bab1efb057e8e4ca086de5f/mvs.ini" --depthMapFolder "C:/Users/Dragon Stone/Desktop/Bench/MeshroomCache/DepthMap/f33cdbf02b301684f6b74e3d33492848cc41afde" --depthMapFilterFolder "C:/Users/Dragon Stone/Desktop/Bench/MeshroomCache/DepthMapFilter/a15e6d9cd115a4c768adb3506bc4d9c99b6af004" --maxInputPoints 50000000 --maxPoints 5000000 --maxPointsPerVoxel 1000000 --minStep 2 --partitioning singleBlock --repartition multiResolution --angleFactor 15.0 --simFactor 15.0 --pixSizeMarginInitCoef 2.0 --pixSizeMarginFinalCoef 4.0 --voteMarginFactor 4.0 --contributeMarginFactor 2.0 --simGaussianSizeInit 10.0 --simGaussianSize 10.0 --minAngleThreshold 1.0 --refineFuse True --verboseLevel info --output "C:/Users/Dragon Stone/Desktop/Bench/MeshroomCache/Meshing/2cac2e283bcbe3c8847cff9d40ef7092501060f9/mesh.obj"
 - logFile: C:/Users/Dragon Stone/Desktop/Bench/MeshroomCache/Meshing/2cac2e283bcbe3c8847cff9d40ef7092501060f9/log

147 images 136 cameras of a tree.

Geforce GTX 970 8g

If i turn down max points you think this will help?
![meshroom_2018-09-18_09-42-46](https://user-images.githubusercontent.com/20977788/45691802-220cca80-bb0e-11e8-88f7-a803e3baa386.png)

**Comment by fabiencastan** [comment]
Could you try to reduce the value of `maxPoints` on the Meshing node to avoid using too much RAM & SWAP?

**Comment by chrisnagy** [comment]
I will try this today..

**Comment by chrisnagy** [comment]
I put it down to 500000 and it went through.. (thumbs up) I will keep upping the count to see which will break it

**Comment by Devoney** [comment]
I think I experienced a similar issue. Got 302 images of a rock. The process halted after approx 12 hours in the meshing step. Memory exhausted it says. I got a GTX 980m with 8GB dedicated RAM, and a i7 Quadcore CPU with 32GB RAM. Which memory do you think got exhausted? I halved the value of max points by factor 0.5, and also for max input points. I pressed compute on the mesh step, and still waiting for the results.

I know that when I tried the same image sequence with VisualSFM and Meshlab, that the computer showed almost 30GB of RAM used, of which ~25GB where used by Meshlab! 

Besides describing the error I experienced I would also like to mentioned that Meshroom is really awesome and well done with respect to options and interface, chaining all steps in this pipeline. Really, really awesome. Thanks so much. If I have good results I am definitely making a donation, this is awesome software. And also the webpage with history, explanation of the steps, references to research articles. Really great.

**Comment by fabiencastan** [comment]
The meshing step only use CPU/RAM.
You should monitor your RAM/SWAP usage to see if it's the problem.

**Comment by ashtez** [comment]
Same problem here, I had to reduce `maxPoints` to 1000000 for it to work.

**Comment by MasterPharaon90** [comment]
I had a memory problem, even though it is enough. Solved the problem by adding virtual memory of the size of the system's choice. It took the same amount of RAM on the disk as the RAM itself (doubling the system memory) - the problem disappeared. Additional system parameters ->
System properties -> Performance -> Advanced -> Virtual memory -> Select the desired drive -> System selectable size -> Set -> OK -> restart the computer.
