### ISSUE TITLE
Noticing something with the database file 

### ISSUE THREAD

**Issue by tyguymedia** [alicevision/meshroom#253]
I found that my Canon Rebel EOS t6 was not in the database, and so I couldn't get past the initialization process, getting this error:

[11:31:29.167103][error] Sensor width doesn't exist in the database for image(s) :
[11:31:29.177098][error] image: 'IMG_2836.JPG'
        - camera brand: Canon
        - camera model: Canon EOS Rebel T6

I went into the db file to try and add it, and no matter how I did it would not work. What I realized is for some reason the syntax seems to change at the canon models? 

Instead of something like:
Canon;Canon EOS Rebel T6;22.3

they all look like: 
Canon;Canon EOS Rebel T6 / 750d;22.3

So, just to see what would happen, I deleted everything from the database file and put in:
Canon;Canon EOS Rebel T6;22.3

...and that solved my issue. Don't know if this will help anyone else or what this is about but thought I'd share.

**Comment by simogasp** [comment]
related to https://github.com/alicevision/AliceVision/issues/485

**Comment by fabiencastan** [comment]
@tyguymedia Thanks for your precise report.

**Comment by gregoire-dl** [comment]
Should be fix with alicevision/AliceVision#512
Thanks.
