### ISSUE TITLE
Unknown input SfM data format: '.abc'

### ISSUE THREAD

**Issue by qdxizao** [alicevision/meshroom#254]
I have a problem when use meshroom:
[error] Unknown input SfM data format: '.abc'
[error] The input SfMData file 'C:/Users/89b0/sfm.abc' cannot be read.

**Comment by qdxizao** [comment]
> Did you built AliceVision yourself?
> If yes, Meshroom needs to have AliceVision built with Alembic support enabled.



> Did you built AliceVision yourself?
> If yes, Meshroom needs to have AliceVision built with Alembic support enabled.



> Did you built AliceVision yourself?
> If yes, Meshroom needs to have AliceVision built with Alembic support enabled.

but I have Alembic.

**Comment by qdxizao** [comment]
@fabiencastan 
thanks,but I have Alembic.

**Comment by fabiencastan** [comment]
Need more information to help you, like platform, log, step of the pipeline concerned, version used, is it manually built, etc.

**Comment by qdxizao** [comment]
@fabiencastan 
It is my Log: Program called with the following parameters:
 * input = "F:/sift/work/MeshroomCache/StructureFromMotion/24a10fc95fb3dff5cea66be81ac03b4b896fecc0/sfm.abc"
 * output = "F:/sift/work/MeshroomCache/PrepareDenseScene/b6d85904629b2e7f017e2ed1221eb568a87e3179"
 * verboseLevel = "info"

[16:14:20.139697][error] Unknown input SfM data format: '.abc'
[16:14:20.140667][error] The input SfMData file 'F:/sift/work/MeshroomCache/StructureFromMotion/24a10fc95fb3dff5cea66be81ac03b4b896fecc0/sfm.abc' cannot be read.

**Comment by qdxizao** [comment]
@fabiencastan 
My Meshroom is 2018.1.0
My Alembic is 1.7.8

**Comment by qdxizao** [comment]
@fabiencastan 
Thanks for your help. I put qmlAlembic in the root directory of AliceVision and the problem has solved.

**Comment by aymanyaish** [comment]
I have the same issue mentioned above , but i dont know how to "I put qmlAlembic in the root directory of AliceVision and the problem has solved." as mentioned above in the commenta . What is the root directory ?! and what i should do exactly?

[19:20:01.480049][warning] There is no valid GT data to read from C:/Users/HP/Desktop/3D printed/3d scanning photo/MeshroomCache/PrepareDenseScene/a436c5af69379478f49dbc42e303b33b14faae19\gt_dense_cameras
[19:20:01.481051][error] The input SfMData file 'C:/Users/HP/Desktop/3D printed/3d scanning photo/MeshroomCache/PrepareDenseScene/a436c5af69379478f49dbc42e303b33b14faae19' cannot be read.

My meshroom is 2018.1.0 i install it after 2020 meshroom which had alot of errors.
