### ISSUE TITLE
Kinect camera pipeline

### ISSUE THREAD

**Issue by TheBricktop** [alicevision/meshroom#255]
Do Alicevision could have support for RGBD cameras for sfm ?

**Comment by jgwinner** [comment]
I've got the modern Intel D415 depth camera, which is similar to the Kinect. There are a number of RGB depth cameras out there now, so I'd be interested in this topic as well.

So giving this a bump up.

== John ==

**Comment by JonathanLehner** [comment]
?

**Comment by fabiencastan** [comment]
I'm sorry I didn't answer earlier. That's of course an interesting topic, but it's not on our roadmap for now. But we could be happy to support any initiative on this topic.
Re-open the issue if someone is interested to work on it.

**Comment by natowi** [comment]
Well, there is https://github.com/alicevision/AliceVision/pull/489

**Comment by fabiencastan** [comment]
Yes, that's a first step in this direction: getting the kinect depth maps and the SfM in the same coordinate system (to be able to combine them in the dense part of the pipeline).

**Comment by jgwinner** [comment]
Just jumping in: I hope "Kinect" means "RGBD in general" as the Kinect is of course pretty obsolete and hard to find. The D415 and others are easily available.

        == John ==

**Comment by fabiencastan** [comment]
@jgwinner @TheBricktop @JonathanLehner 

Is there a standard file format supported by all RGBD sensors with a standard way to retrieve focal length and principal point (to be able to convert the depth values into 3D points)?
Do you have some sample datasets to share?

What do you expect from RGBD sensors?  Get scale information in SfM and improve robustness to weakly textured surfaces?

**Comment by natowi** [comment]
There does not seem to be one standard format, but there are libraries for depth cameras like https://github.com/AmmarkoV/RGBDAcquisition
