### ISSUE TITLE
Invalid texture reference/ Invalid device function .. DepthMap Win10  Pointcloud good   mesh broken

### ISSUE THREAD

**Issue by Stano71** [alicevision/meshroom#258]
Most likely something I did  wrong but Meshroom  has errors at Depthmap .. Invalid texture reference, I dont have F:/...  With only 6 pics from the monstree set the process completes but is not textured correctly UPDATE : it completes with full set of pics but still looks wrong and same error messages in log.. PLEASE HELP !
 using the Windows 64 build   from here     https://github.com/alicevision/meshroom/releases/download/v2018.1.0/Meshroom-2018.1.0-win64.zip 
any help would be appreciated as this is the perfect addition to my 3D printing toolset,
a big thankyou to the creators...

edited log :
Program called with the following parameters:
 * downscale = 2
 * ini = "C:/Users/Stano71/AppData/Local/Temp/MeshroomCache/PrepareDenseScene/6a938c251bc5362179f7df592e5d63e0da4fef53/mvs.ini"
 * output = "C:/Users/Stano71/AppData/Local/Temp/MeshroomCache/DepthMap/32912bf1a095b6b299bf2c23dc34045f4cc97f29"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[17:22:23.786788][info] CUDA-Enabled GPU.
Device information:
	- id:                      0
	- name:                    GeForce GT 635M
	- compute capability:      2.1
	- total device memory:     2048 MB 
	- per-block shared memory: 49152
	- warp size:               32
	- max threads per block:   1024
	- max threads per SM(X):   1536
	- max block sizes:         {1024,1024,64}
	- max grid sizes:          {65535,65535,65535}
	- number of SM(x)s:        2
	- registers per SM(x):     32768
	- registers per block:     32768
	- concurrent kernels:      yes
	- mapping host memory:     yes
	- unified addressing:      yes
	- texture alignment:       512 byte
	- pitch alignment:         32 byte

[17:22:23.833661][info] Supported CUDA-Enabled GPU detected.
[17:22:23.833661][info] Found 1 image dimension(s): 
[17:22:23.833661][info]  - [4032x3024]
[17:22:23.833661][info] Overall maximum dimension: [2016x1512]
[17:22:23.833661][info] Create depth maps.
number of CUDA devices:	1
   0: GeForce GT 635M
[17:22:23.849286][info] Number of GPU devices: 1, number of CPU threads: 8
[17:22:23.849286][info] PSSGM autoScaleStep: scale: 2, step: 2
[17:22:23.849286][info] PlaneSweepingCuda:
	- nImgsInGPUAtTime: 6
	- scales: 2
	- subPixel: Yes
	- varianceWSH: 

CUDAError: invalid texture reference
  file:       F:/GitHub/AliceVision/src/aliceVision/depthMap/cuda/planeSweeping/plane_sweeping_cuda.cu
  function:   aliceVision::depthMap::ps_deviceUpdateCam
  line:       402

CUDAError: invalid texture reference
  file:       F:/GitHub/AliceVision/src/aliceVision/depthMap/cuda/planeSweeping/plane_sweeping_cuda.cu
  function:   aliceVision::depthMap::ps_deviceUpdateCam
  line:       402

CUDAError: invalid texture reference
  file:       F:/GitHub/AliceVision/src/aliceVision/depthMap/cuda/planeSweeping/plane_sweeping_cuda.cu
  function:   aliceVision::depthMap::ps_deviceUpdateCam
  line:       402

CUDAError: invalid texture reference
  file:       F:/GitHub/AliceVision/src/aliceVision/depthMap/cuda/planeSweeping/plane_sweeping_cuda.cu
  function:   aliceVision::depthMap::ps_deviceUpdateCam
  line:       402
MANY more similar errors

CUDA device no 0 for 0
Device 0 memory - used: 367.071869, free: 1680.928101, total: 2048.000000
Device 0 memory - used: 455.946869, free: 1592.053101, total: 2048.000000
[17:22:34.665720][info] Compute depth map: C:/Users/Stano71/AppData/Local/Temp/MeshroomCache/DepthMap/32912bf1a095b6b299bf2c23dc34045f4cc97f29/797046670_idDepthMap_scale2_step2_SGM.png
[17:22:34.666719][warning] rc: 0 - found only 5/10 tc by seeds

CUDAError: invalid device function
  file:       F:/GitHub/AliceVision/src/aliceVision/depthMap/cuda/planeSweeping/plane_sweeping_cuda.cu
  function:   aliceVision::depthMap::ps_computeSimilarityVolume
  line:       1010

CUDAError: invalid device function
  file:       F:/GitHub/AliceVision/src/aliceVision/depthMap/cuda/planeSweeping/plane_sweeping_cuda.cu
  function:   aliceVision::depthMap::ps_computeSimilarityVolume
  line:       1010

CUDAError: invalid device function
  file:       F:/GitHub/AliceVision/src/aliceVision/depthMap/cuda/planeSweeping/plane_sweeping_cuda.cu
  function:   aliceVision::depthMap::ps_computeSimilarityVolume
  line:       1010
Many more similar errors...

CUDAError: invalid texture reference
  file:       F:/GitHub/AliceVision/src/aliceVision/depthMap/cuda/planeSweeping/plane_sweeping_cuda.cu
  function:   aliceVision::depthMap::ps_deviceUpdateCam
  line:       402

CUDA device no 0 for 0
Device 0 memory - used: 367.071869, free: 1680.928101, total: 2048.000000
Device 0 memory - used: 455.946869, free: 1592.053101, total: 2048.000000
[17:23:13.968888][warning] rc: 0 - found only 5/10 tc by seeds
[17:23:13.969887][warning] rc: 0 - found only 5/6 tc by seeds
gpu elapsed time: 4.000000 ms 
gpu elapsed time: 6.000000 ms 
gpu elapsed time: 4.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 6.000000 ms 
gpu elapsed time: 4.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 3.000000 ms 
gpu elapsed time: 4.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 4.000000 ms 
gpu elapsed time: 3.000000 ms 
gpu elapsed time: 4.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 3.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 8.000000 ms 
gpu elapsed time: 3.000000 ms 
gpu elapsed time: 6.000000 ms 
gpu elapsed time: 3.000000 ms 
gpu elapsed time: 70.000000 ms 
gpu elapsed time: 71.000000 ms 
gpu elapsed time: 73.000000 ms 
gpu elapsed time: 69.000000 ms 
rc: 0, gpu elapsed time: 56.000000 ms 
rc: 0, gpu elapsed time: 67.000000 ms 
rc: 0, gpu elapsed time: 74.000000 ms 
rc: 0, gpu elapsed time: 67.000000 ms 
[17:23:16.397385][warning] rc: 1 - found only 5/10 tc by seeds
[17:23:16.398384][warning] rc: 1 - found only 5/6 tc by seeds
gpu elapsed time: 4.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 4.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 8.000000 ms 
gpu elapsed time: 4.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 4.000000 ms 
gpu elapsed time: 4.000000 ms 
gpu elapsed time: 6.000000 ms 
gpu elapsed time: 3.000000 ms 
gpu elapsed time: 6.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 8.000000 ms 
gpu elapsed time: 8.000000 ms 
gpu elapsed time: 3.000000 ms 
gpu elapsed time: 4.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 4.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 70.000000 ms 
gpu elapsed time: 69.000000 ms 
gpu elapsed time: 70.000000 ms 
gpu elapsed time: 68.000000 ms 
rc: 1, gpu elapsed time: 62.000000 ms 
rc: 1, gpu elapsed time: 52.000000 ms 
rc: 1, gpu elapsed time: 72.000000 ms 
rc: 1, gpu elapsed time: 73.000000 ms 
[17:23:18.811891][warning] rc: 2 - found only 5/10 tc by seeds
[17:23:18.812890][warning] rc: 2 - found only 5/6 tc by seeds
gpu elapsed time: 5.000000 ms 
gpu elapsed time: 6.000000 ms 
gpu elapsed time: 6.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 3.000000 ms 
gpu elapsed time: 3.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 6.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 4.000000 ms 
gpu elapsed time: 6.000000 ms 
gpu elapsed time: 4.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 5.000000 ms 
gpu elapsed time: 4.000000 ms 
gpu elapsed time: 7.000000 ms 
gpu elapsed time: 8.000000 ms 
gpu elapsed time: 8.000000 ms 
gpu elapsed time: 70.000000 ms 
gpu elapsed time: 74.000000 ms 
gpu elapsed time: 70.000000 ms 
gpu elapsed time: 72.000000 ms 
rc: 2, gpu elapsed time: 63.000000 ms 
rc: 2, gpu elapsed time: 59.000000 ms 
rc: 2, gpu elapsed time: 63.000000 ms 
rc: 2, gpu elapsed time: 57.000000 ms 
[17:23:21.243386][info] Task done in (s): 57.450000

**Comment by Stano71** [comment]
![meshroom error](https://user-images.githubusercontent.com/6028657/46124303-a70e8700-c266-11e8-9ef9-6b0987705c4b.jpg)

**Comment by Stano71** [comment]
![output](https://user-images.githubusercontent.com/6028657/46124920-ff935380-c269-11e8-868a-a655c8b4268f.jpg)

**Comment by Stano71** [comment]
When I load the model.......  and the resulting mesh 
![mesh1](https://user-images.githubusercontent.com/6028657/46185469-5312a980-c31d-11e8-8098-685d5b1767ed.jpg)


Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, ExportUndistortedImages, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[QtOIIO] Plugin Initialized
[DepthMapEntity] DepthMapEntity
Failed to download scene at QUrl("")
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
[Qt3DRender::GLTexture] No QTextureData generated from Texture Generator yet. Texture will be invalid for this frame
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
[Qt3DRender::GLTexture] No QTextureData generated from Texture Generator yet. Texture will be invalid for this frame
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
Unknown uniform type or value: QVariant(Invalid) Please check your QParameters
[Qt3DRender::GLTexture] No QTextureData generated from Texture Generator yet. Texture will be invalid for this frame

**Comment by ChemicalXandco** [comment]
Maybe try more then 6 images, the dataset has like 40

**Comment by Stano71** [comment]
> Maybe try more then 6 images, the dataset has like 40

I tried all 41 images and the error messages are still the same. 
Why does it look at this location, there is NO    F:/...   on my system???? ... 
Thankyou for your help.

CUDAError: invalid texture reference
file: F:/GitHub/AliceVision/src/aliceVision/depthMap/cuda/planeSweeping/plane_sweeping_cuda.cu
function: aliceVision::depthMap::ps_deviceUpdateCam
line: 402.    ALL the errors are looking for the same location, Can these errors be ignored? 
resulting mesh of 41 images, does it look correct??
![mesh mtree](https://user-images.githubusercontent.com/6028657/46242947-ca296a00-c411-11e8-82b8-61f8fbf9dd2a.jpg)
![sfm](https://user-images.githubusercontent.com/6028657/46242960-d9a8b300-c411-11e8-9a13-bcd0babeaabd.jpg)
![sfm mesh](https://user-images.githubusercontent.com/6028657/46242961-df05fd80-c411-11e8-90f2-c15dd32667c5.jpg)
![meshroom compute](https://user-images.githubusercontent.com/6028657/46242970-ffce5300-c411-11e8-88fc-994e50c6d941.jpg)

**Comment by Stano71** [comment]
![cherub sfm](https://user-images.githubusercontent.com/6028657/46636543-c75e1000-cb9b-11e8-8dd6-089f75059d9a.jpg)
![cherub mesh](https://user-images.githubusercontent.com/6028657/46636552-ccbb5a80-cb9b-11e8-8211-1768f8bf8803.jpg)
![cherub errors](https://user-images.githubusercontent.com/6028657/46636556-d0e77800-cb9b-11e8-87bb-af365555c6fc.jpg)

**Comment by ricston94** [comment]
Hi! Any updates about this problem? I get the same results and the same errors.

**Comment by Stano71** [comment]
> Hi! Any updates about this problem? I get the same results and the same errors. I have the same GPU as Stano71, I think the problem originates from there.

I still have the same issue , I think it might be because we can only go to cuda 8 with our chipset???????
I am not a programmer so just guessing this is the cause......

**Comment by wienio2** [comment]
Unfortunately have the same problem  .... on GeForce GT 730 ... 
Same final effect, same errors in log ....

With other software on the same hardware it works fine (tested with 3df zephyr free).

Is there any change for update, so it whould work fine by us with meshroom as well ?

**Comment by ccode111** [comment]
i have same exact resulted mesh from those pictures using same pictures on gts 450 pls help same thing in logs too i have win 10 64 bit

**Comment by Boomslang10** [comment]
I have the same issue. Win7x64, 8GB ram, gtx550ti

My gtx550 is Compute V2.1, does all your cards also have V2.1/0 or V3 and up?

**Comment by Stano71** [comment]
This issue is related to https://github.com/alicevision/meshroom/issues/223
and has a little more info .... Hopefully the update is not far away and offers a solution for us on older hardware or its time to upgrade ....
