### ISSUE TITLE
[bug] Keyframe selection inputs

### ISSUE THREAD

**Issue by mh0g** [alicevision/Meshroom#2580]
**Describe the bug**
In the keyframe selection node, the input paths and masks are "advanced" parameters.
This means that in the current camtrack pipeline, the edges are hidden which is very counter intuitive as Keyframe selection is then visually disconnected from the graph.

**To Reproduce**
Steps to reproduce the behavior: open the camtrack pipeline

**Expected behavior**
The node should be visually connected

**Comment by cbentejac** [comment]
Will be fixed by https://github.com/alicevision/Meshroom/pull/2578.
