### ISSUE TITLE
nlEigenSolve_ARPACK "Could not factorize matrix" error

### ISSUE THREAD

**Issue by DevoStevo66** [alicevision/meshroom#259]
I'm getting an error in the Texturing Node log "nlEigenSolve_ARPACK...Could not factorize matrix" during mesh atlasing. Just wondering if this can be easily fixed. I did notice nlEigenSolve_ARPACK was also from AliceVision (Geogram) but I have no idea on how to add any code to Meshroom. I just double click it to run.

**Comment by fabiencastan** [comment]
Which platform version and what unwrapping mode?
Did you use the binaries of the version "2018.1.0" or did you build it yourself?
