### ISSUE TITLE
SFM Transform failed to detect CCTAG3 Tags 

### ISSUE THREAD

**Issue by santiago2389** [alicevision/Meshroom#2593]
**Settings used and issue**
I have used two CCTAG3 in my capture. IDs are 1 and 10. In SFM Transform settings only cctag3 is enabled and two markers with their IDs added. The distance between two tags is 200 mm so Additional Scale is mentioned as 2. Here issue is tags are not detected when Transformation Method is set to from_markers

![image](https://github.com/user-attachments/assets/03709749-3c68-4a52-8fe0-8f0b81fc73ea)

![image](https://github.com/user-attachments/assets/de96cc02-c1d6-407c-9362-b72978893913)

**Dataset**
Input image example
![00000](https://github.com/user-attachments/assets/cda31537-25bc-4f9b-ba02-579b8eb8f78d)
![00010](https://github.com/user-attachments/assets/d8fd0405-6d9e-4f64-84ac-30d8a9364609)
![00020](https://github.com/user-attachments/assets/2f5a438c-a26d-4cae-a9d2-d939cf1086e3)

**Log**
![image](https://github.com/user-attachments/assets/72e1e6cc-83c3-448d-8816-2367df021a81)
Detection failed as seen in log

**Comment by msanta** [comment]
The marker IDs begin from 0. While it shows '1' on the paper the actual ID is 0 and for '10' the actual ID is 9.

**Comment by santiago2389** [comment]
Yes. Thanks.
Please close the issue.
