### ISSUE TITLE
This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0).

### ISSUE THREAD

**Issue by atsage** [alicevision/meshroom#260]
I have a Quadro 2000 which according to this page https://en.wikipedia.org/wiki/CUDA is compute capability version 2.1.  I've updated the drivers and it did not make a difference.  Is there any way to make this GPU work?  As a side note, there is a typo in your error message: capablility has an extra l and should be capability.

**Comment by atsage** [comment]
I finally figured out how to query the video card info (below).  The newest toolkit does not support my video card so I had to go back to v8.  Here is the output.  As the wiki pages suggests, it's compute capability version 2.1.  Is there some other check for this card that is failing?

PS E:\Programs\NVIDIA GPU Computing\extras\demo_suite> .\deviceQuery.exe
E:\Programs\NVIDIA GPU Computing\extras\demo_suite\deviceQuery.exe Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "Quadro 2000"
  CUDA Driver Version / Runtime Version          8.0 / 8.0
  CUDA Capability Major/Minor version number:    2.1
  Total amount of global memory:                 1024 MBytes (1073741824 bytes)
  ( 4) Multiprocessors, ( 48) CUDA Cores/MP:     192 CUDA Cores
  GPU Max Clock rate:                            1251 MHz (1.25 GHz)
  Memory Clock rate:                             1304 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 262144 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65535), 3D=(2048, 2048, 2048)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 32768
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1536
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (65535, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  CUDA Device Driver Mode (TCC or WDDM):         WDDM (Windows Display Driver Model)
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 8.0, CUDA Runtime Version = 8.0, NumDevs = 1, Device0 = Quadro 2000
Result = PASS

**Comment by littlewhitebutterflies** [comment]
I am having the same problem during the Depth Map phase. I get the error "This program requires a CUDA-enabled GPU (with at least compute capability 2.0). I have a GeForce GTX 1050, which runs CUDA and has a compute capability of 6.1. I have tried reinstalling my drivers, which has not worked, and my GTX 1050 driver is up-to-date. Anyone have any ideas on how to solve this?

**Comment by nmartin9319** [comment]
I have the same problem too, with GTX 960M in the depth map phase. I'm sure that CUDA 9.0 was properly installed, since I can TensorFlow on GPU without any problems. The nvidia-smi also shows that meshroom uses my GPU (and in the previous phases, like Feature matching I see in the GPU usage, that it is actually used). Downgraded to CUDA 8.0, but the problem still occours.

**Comment by atsage** [comment]
Is there anybody out there?

**Comment by fabiencastan** [comment]
Sorry, we don't have the time to look at it right now, but will come back to you.

The code where we test the capabilities of the device is here:
https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/system/gpu.hpp

**Comment by pfc** [comment]
Same problem, I have a 1070 and 1080 which both support CUDA.  Would be great to have a more detailed error message.

**Comment by panbeep** [comment]
What about Mac OSX version? It has CUDA drivers.

**Comment by atsage** [comment]
I don't have a Mac.

**Comment by Farsash** [comment]
Quadro P600. Same error.

**Comment by nmartin9319** [comment]
I have downloaded the precompiled version (2018.1.0) instead of compiling it myself and now it works.

**Comment by atsage** [comment]
The precompiled version (2018.1.0) does not work for me.

**Comment by fabiencastan** [comment]
Difficult to analyze it without more explicit error messages.
If someone has built it manually, the "develop" branch should provide more precise error messages now (else it will be included in the next release).

**Comment by atsage** [comment]
@natowi No, I'm on windows 10 64 bit.
@fabiencastan I attempted to build the project manually a while ago, but unfortunately it would require more time than I'm willing to put in to it to learn how to do it.  I believe it was the AliceVision stuff I couldn't get compiled.  Hopefully someone else here already knows how it's done and can help out.  If not, as you said the next release will provide these errors, I will post whatever comes up then.

**Comment by giorgionetg** [comment]
Same problem here with Nvida Quadro K4000 with win 10, CUDA 6.0.1, but same error on Depth Map node where message is:

This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0)

**Comment by griwodz** [comment]
I have seen strange behaviour of the cudaGetDeviceProperties function in two situations:
- Using an up-to-date CUDA installation with a compute capability 2 card.
- Using a CC 3 and CC 5 card in the same computer.
In the first case, no card is found, in the second case, whichever card is scanned second is not found.

I did not dig deeply, but the cards seem to work to some extent if we don't check for device properties at all. Unfortunately not calling cudaGetDeviceProperties is not really an option for us because we need to know how much memory each of the cards has.

**Comment by NonSecwitter** [comment]
I have a Quadro 4000 and have the same issues. I was looking at the code that @fabiencastan 
 referenced [here](https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/system/gpu.hpp )

My error message is specifically "Can't find CUDA-Enabled GPU." which seems to indicate that cudaGetDeviceProperties is not detecting my card. I'm installing the CUDA toolkit now to run the CUDA capability detection from the sample script. 

@atsage if you set that node to debug logging, you may get more details. The message "This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0)" looks like a generic failure notification [here](https://github.com/alicevision/AliceVision/blob/7bc255a3b14fe483f846445ee4fef729b09de632/src/software/pipeline/main_depthMapEstimation.cpp#L158)

I haven't tried to compile anything, but it looks like there may be a logic error in gpu.hpp [here](https://github.com/alicevision/AliceVision/blob/f392f97999a09a9fac22b2a2dc75625378f1be29/src/aliceVision/system/gpu.hpp#L123-L126) and [here](https://github.com/alicevision/AliceVision/blob/f392f97999a09a9fac22b2a2dc75625378f1be29/src/aliceVision/system/gpu.hpp#L50-L53). You're calling gpuSupportCuda(2,0) and then checking whether `deviceProperties.major > 2` ... implying that the major version must be 3. I think this should be `deviceProperties.major >= 2`

**Comment by atsage** [comment]
@NonSecwitter I've already ran deviceQuery.exe and it comes back with a valid card for me.  Not much more info even setting the node to trace:

```
[15:11:24.142941][info]
[15:11:24.150426][debug] Can't find CUDA-Enabled GPU.
[15:11:24.150426][error] This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0).
```

**Comment by NonSecwitter** [comment]
@atsage That's interesting because the error you got only happens when `cudaGetDeviceProperties` is called and the result is zero. So, it seems there is either an issue with the CUDA or a problem with how it's called.... the call looks accurate per specs, so I'm curious why the toolkit is showing zero devices. 

I'll take a closer look at this tonight or tomorrow... 

Did you look through the deviceQuery.exe source code? Is it even calling `cudaGetDeviceProperties` ??

**Comment by oblee** [comment]
I'm having the same error at DepthMap.  I have a GTX980m

**Comment by griwodz** [comment]
Several people who have this problem have mobile cards, perhaps we are missing something when GPUs from different vendors exist in the computer? Newer OSes can switch on-demand between integrated low-power and discrete NVidia GPU, but perhaps we have to do something to tell the OS that we have such a demand?

**Comment by NonSecwitter** [comment]
Okay... I think I figured this out... Meshroom is using `cudart64_91.dll`, which is the 9.1 toolkit, when calling `cudaGetDeviceCount`. For me, my card is incompatible with anything newer than 7.5. 

I'm guessing there is a reason for updating to 9.1, so maybe we can fix this by figuring out the oldest version with `cudaGetDeviceCount` available and loading it specifically for compatibility checking?

**Comment by oblee** [comment]
Is there any workaround we can attempt?  I'm so close!!!  hahaha, this software is truly amazing, I can't wait to see what it can do.

**Comment by yann-lty** [comment]
The only CUDA-version / minimum CC table I've found (https://stackoverflow.com/a/28933055 - from someone working at NVIDIA) indeed shows that CUDA 9.1 requires CC >= 3.0. Despite the fact that the documentation of `cudaGetDeviceCount` is still `Returns the number of devices with compute capability greater or equal to 2.0`, even in the 10.0 SDK. It seems like CUDA 8.0 would still be compatible with CC 2.0, but in all cases this would require a new build of AliceVision.

**Comment by griwodz** [comment]
Yann, your post gave me the idea to search for functions that can at least give us better error messages (something like "This release expects CUDA SDK 10, you have CUDA SDK 9"):
cudaDriverGetVersion(int* version) - returns the system's current CUDA driver version
cudaRuntimeGetVersion(int* version) - return the system's current runtime (SDK) version; version = 1000*major+10*minor, CUDA SDK 92 -> 9020

Also, we could revise the memory check. Compute capability 2 cards could already report their major/minor compute capability and totalGlobalMem in cudaGetDeviceProperties, but CUDA 2 did not have the cudaGetMemInfo function at all, it was apparently impossible to check available memory. Worst case guessing is probably the way to go.

**Comment by atsage** [comment]
Others were reporting driver updates work, but it looks like if you have under compute capability 3 card it just will not work for now.

**Comment by Uber616** [comment]
Same thing here sadly. Stops at depth map. Quadro M1000M (Compute Capability 5.2) I have tried disabling the Intel GPU it did not help. Any workarounds?

**Comment by piflixe** [comment]
Same Problem with meshroom version Version 2018.1.0, Windows 10, Python 3.6.5 and a K4200 GPU and Intel Xeon E5 1650 v3. From my understanding this should fulfill the requirements. I have the driver version 22.21.13.8607 installed that dates to 19.12.2017

**Comment by oblee** [comment]
Updating GPU drivers did the trick for me.  Very very very cool software.

**Comment by ShamrockLee** [comment]
Same problem with meshroom
Version 2018.1.0
Linux 4.15.0-43-generic 
Python 3.6.3
Graphics:  Card-1: Intel UHD Graphics 620 bus-ID: 00:02.0 chip-ID: 8086:5917
           Card-2: NVIDIA GM108M [GeForce MX130] bus-ID: 01:00.0 chip-ID: 10de:174d
           Display Server: x11 (X.Org 1.19.6 ) drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1600x900@59.95hz
           OpenGL: renderer: Mesa DRI Intel UHD Graphics 620 (Kabylake GT2)
           version: 4.5 Mesa 18.0.5 (compat-v: 3.0) Direct Render: Yes
Driver: 
    Neither
    xserver-xorg-video-nouveau 1.0.15-2
    nor
    nvidia-driver-390 390.77-0ubuntu0.18.04.1
    works

**Comment by ats1080** [comment]
@Allecsxx that is not the solution for this issue.

**Comment by Allecsxx** [comment]
@ats1080 it did worked for me. 
Win8.1
Geforce 820M

**Comment by atsage** [comment]
@Allecsxx sure, but this issue is specifically relating to under compute capability 3 cards.  There is a bug that no matter what driver you use it just will not work.

**Comment by piflixe** [comment]
@vsolenoid when using Ubuntu with Nvidia driver for the quadro 2000 it detected the graphics card correctly. But when trying to compute a model it ran into a gpu ram overflow. Does anyone have a recommendation on how much gpu ram is necessary?

**Comment by 4xle** [comment]
> @vsolenoid when using Ubuntu with Nvidia driver for the quadro 2000 it detected the graphics card correctly. But when trying to compute a model it ran into a gpu ram overflow. Does anyone have a recommendation on how much gpu ram is necessary?

You may be able to get away with the 1GB you have by dropping the overall density/quality of the pipeline. Alternatively, could try downsampling your imagery. "How much is necessary" will depend largely on what you are attempting.

**Comment by atsage** [comment]
@fabiencastan Is there any update?

**Comment by eAddict** [comment]
Having same issue with my GT640...

**Comment by ToddVG** [comment]
I am also having the same issue, but just love what they have done with Meshroom. If someone could tell me the exact video card to buy I will run out and get it.

**Comment by vsolenoid** [comment]
I have ended up running out an buying a "new" (used) PC - Dell 3610 with K4000 and 32RAM and the program started from the first time. Anyway, the results with default setting aren't impressive(even if they still need 8 to 12 hours for a run), so I'm trying all other options. So far 3dzephir is leading with most accurate dense point clouds. Just to be clear - I'm trying to create a 3D model of a person and in most of the sets of pictures he has moved a bit. I don't have any tests with a static objects.

**Comment by natowi** [comment]
@vsolenoid 3d scans of persons are difficult task. For good results, the person should not move even a bit. For this reason, for capturing persons you should use a camera rig or at least try to steady the person.
---
@ToddVG I have a GTX1080 and the latest drivers and Meshroom works for me. There are also other users with GTX10xx GPUs and no issues (e.g. [GTX1060](https://github.com/alicevision/meshroom/issues/367)), so the problems listed here might be related to specific setup/driver combinations.

**Comment by Hans2004** [comment]
I have the same problem that Meshroom does not see my CUDA nvidia GTX1050 in my optimus laptop. I am using OpenSuse Tumbleweed, and I know that CUDA works in other software. I can even run the Windows version of Meshroom with wine as follows: optirun wine Meshroom.exe, and then everything works. But when running the Linux version, it complains about not finding a CUDA enabled GPU.

**Comment by Killian3145** [comment]
How do you do Depth Mapping without a CUDA enabled GPU?

**Comment by natowi** [comment]
@Killian3145 have a look at [MVE](https://github.com/simonfuhrmann/mve), OpenMVG, MicMac or Regard3D

**Comment by Killian3145** [comment]
Thanks, this worked well. But it still sucks that you can't do depth mapping without a CUDA enabled GPU.

**Comment by natowi** [comment]
@Killian3145 Removing CUDA dependency is being discussed. Read [this](https://github.com/alicevision/AliceVision/issues/439) for details.

**Comment by nmz787** [comment]
Happening here with me too, ubuntu 18.04 and a GTX1080TI

**Comment by piflixe** [comment]
Seems to work for me with the latest mesh room version an Nvidia K4200-- Felix Piela August & Piela Konstruktiv GbR Tempelhofer Weg 11-12 10829 Berlin Tel 030 91905511 Mobil 015231937441 Fax 030 9190 9733-------- Ursprüngliche Nachricht --------Betreff: Re: [alicevision/meshroom] This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0). (#260)Von: nmz787 An: alicevision/meshroom Cc: Felix Piela ,Comment Happening here with me too, ubuntu 18.04 and a GTX1080TI

**Comment by burtsevyg** [comment]
Got it on gtx 250

**Comment by releyshic** [comment]
What i can do if i have Vega 56 + Ryzen2700x?
I have mistakes on the DepthMap:
Could not determine number of CUDA cards in this system
[17:21:36.401940][warning] No CUDA-Enabled GPU.
