### ISSUE TITLE
How to set texture file format from exr to png when using meshroom_batch.exe

### ISSUE THREAD

**Issue by citystrawman** [alicevision/Meshroom#2607]
**Describe the problem**
I am using meshroom_batch.exe commandline tool to run the whole pipeline, and I want to export the final obj file to meshlab which only supports png file as texture. I know that I can set the texture file format to png in the GUI texture node, but I dont know how to set this parameter when using meshroom_batch.exe commandline tool.

I appreciate if anyone could help me. Thank you!

**Comment by cbentejac** [comment]
Hi @citystrawman,

You have two options to specify non-default values for parameters with meshroom_batch:
```
--overrides SETTINGS  A JSON file containing the graph parameters override.
--paramOverrides [NODETYPE:param=value NODEINSTANCE.param=value ...]
                 Override specific parameters directly from the command line (by node type or by node names).
```

In your case, since you only want to change one parameter's value, you can directly use `--paramOverrides`. To change the file format of the texturing node, you need to add the following:
`--paramOverrides Texturing:colorMapping.colorMappingFileType="png"`

**Comment by citystrawman** [comment]
> Hi @citystrawman,
> 
> You have two options to specify non-default values for parameters with meshroom_batch:
> 
> ```
> --overrides SETTINGS  A JSON file containing the graph parameters override.
> --paramOverrides [NODETYPE:param=value NODEINSTANCE.param=value ...]
>                  Override specific parameters directly from the command line (by node type or by node names).
> ```
> 
> In your case, since you only want to change one parameter's value, you can directly use `--paramOverrides`. To change the file format of the texturing node, you need to add the following: `--paramOverrides Texturing:colorMapping.colorMappingFileType="png"`

Hi @cbentejac , I just tried to change the outputMeshFileType to gltf, and my command was as follows:
`.\meshroom_batch.exe --input G:\test_images --output G:\meshroom_test --paramOverrides Texturing:colorMapping.colorMappingFileType="png" Texturing:outputMesh.outputMeshFileType="gltf"`

Powershell gave me error messages as follows:
```
Overrides Texturing.colorMapping.colorMappingFileType=png
Overrides Texturing.outputMesh.outputMeshFileType=gltf
Traceback (most recent call last):
  File "C:\Release\sources\Meshroom\venv\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Release\sources\Meshroom\venv\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "bin/meshroom_batch", line 198, in <module>
  File "C:\Release\sources\Meshroom\meshroom\common\core.py", line 112, in func_wrapper
  File "C:\Release\sources\Meshroom\meshroom\core\node.py", line 600, in attribute
AssertionError
```
I am not sure how to solve this issue. I think the program has recognized my overrides params but somehow it could not work it out.

**Comment by citystrawman** [comment]
> > Hi @citystrawman,
> > You have two options to specify non-default values for parameters with meshroom_batch:
> > ```
> > --overrides SETTINGS  A JSON file containing the graph parameters override.
> > --paramOverrides [NODETYPE:param=value NODEINSTANCE.param=value ...]
> >                  Override specific parameters directly from the command line (by node type or by node names).
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In your case, since you only want to change one parameter's value, you can directly use `--paramOverrides`. To change the file format of the texturing node, you need to add the following: `--paramOverrides Texturing:colorMapping.colorMappingFileType="png"`
> 
> Hi @cbentejac , I just tried to change the outputMeshFileType to gltf, and my command was as follows: `.\meshroom_batch.exe --input G:\test_images --output G:\meshroom_test --paramOverrides Texturing:colorMapping.colorMappingFileType="png" Texturing:outputMesh.outputMeshFileType="gltf"`
> 
> Powershell gave me error messages as follows:
> 
> ```
> Overrides Texturing.colorMapping.colorMappingFileType=png
> Overrides Texturing.outputMesh.outputMeshFileType=gltf
> Traceback (most recent call last):
>   File "C:\Release\sources\Meshroom\venv\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
>   File "C:\Release\sources\Meshroom\venv\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
>   File "bin/meshroom_batch", line 198, in <module>
>   File "C:\Release\sources\Meshroom\meshroom\common\core.py", line 112, in func_wrapper
>   File "C:\Release\sources\Meshroom\meshroom\core\node.py", line 600, in attribute
> AssertionError
> ```
> 
> I am not sure how to solve this issue. I think the program has recognized my overrides params but somehow it could not work it out.

I found the solution in: https://github.com/alicevision/Meshroom/blob/2d56016770c12480a2a45cf452ed8ece0c98d3dc/meshroom/nodes/aliceVision/Texturing.py#L98

just use `Texturing:outputMeshFileType="gltf"`
