### ISSUE TITLE
Camera model

### ISSUE THREAD

**Issue by burgerlX** [alicevision/meshroom#262]
I am using Alcatel U5 but i dont know what to add to the cameraSensors.db file
Please help

**Comment by burgerlX** [comment]
Does anyone know whats the camera sensor width?

**Comment by ChemicalXandco** [comment]
Looking at https://www.devicespecifications.com/en/model/a2f841ac, there is no value for sensor width. I cannot find anywhere so your best bet is to wait until the next release according to #245 where `cameraCalibration` will be included in the binaries and by showing multiple veiws of a checkerboard, it can retrive focal length, principal point and distortion parameters.
