### ISSUE TITLE
RuntimeError: CameraInit failed with error code 127

### ISSUE THREAD

**Issue by Heryx** [alicevision/meshroom#263]
Hi,
I tried to install meshroom on Ubuntu 18.04 LTS.
Meshroom folder is in Home path, but I don't understand if I have to install AliceVision inside Meshroom folder. I did that. 
So, I run meshroom in this folder with this command: PYTHONPATH=$PWD python meshroom/ui
Then, I drag and drop my images in meshroom and I get that error.

Greetings.

**Comment by stevefoy** [comment]
Hi,
I tried to install meshroom on Ubuntu 16.04 LTS.
In a conda environment 


Then, I drag and drop my images in meshroom and I get that error.

Console ouput:_______________________
/bin/sh: 1: aliceVision_cameraInit: not found
[2019-10-19 13:47:04,540][ERROR] Error while building intrinsics : Traceback (most recent call last):
  File "/home/stephen/Projects/meshroom/meshroom/ui/reconstruction.py", line 632, in buildIntrinsics
    views, intrinsics = cameraInitCopy.nodeDesc.buildIntrinsics(cameraInitCopy, additionalViews)

**Comment by fabiencastan** [comment]
Have you already successfully tested the release binaries before trying to install it manually?
https://github.com/alicevision/meshroom/releases
