### ISSUE TITLE
Export pointcloud

### ISSUE THREAD

**Issue by Shadetail** [alicevision/meshroom#266]
My reconstruction looks good in the sparse point cloud preview in the viewport, but reconstructed mesh turns out totally broken. Is there any way to export dense (or even sparse) point cloud?

**Comment by fabiencastan** [comment]
Does the depth maps look correct?
You can visualize them by looking at the EXR files in the output of the DepthMapFilter node.

**Comment by robertguetzkow** [comment]
The sparse point cloud is saved in **./MeshroomCache/StructureFromMotion/<hash>/cloud_and_poses.abc** (or .ply if configured in the SfM node setting named "Inter File Extension"). I believe the dense point cloud is stored in **./MeshroomCache/Meshing/<hash>/denseReconstruction.bin**, however I'm not sure if that binary format is anything that other software can read.

**Comment by nmenu** [comment]
I want to emphasis how important this is to be able to export the dense point cloud to a standard point cloud file format. 

There are many cases you do not want to work with the mesh but with a dense point cloud. Web visualization with Potree for example, input to the point cloud to make analysis, build TIN terrain model, etc... in an enginerring application. 
This is a must if you could add this option , really a BIG improvement for usability.
Thanks

**Comment by dlivingstone** [comment]
+1 for being able to export point clouds
Is there format for the binary point cloud file detailed anywhere?

**Comment by fabiencastan** [comment]
You can use the vertices of the OBJ and you will get the same points than in the bin format. The bin format is only useful to get the visibility information of each vertex.
In all case, you will not have color information (as this information is not stored), so it needs a processing step to compute it (as it's done at the end of the SfM to add colors to the Alembic sparse point cloud).

It's not in our roadmap, but as it's easy to do, we will probably add something for that.

**Comment by mobarre** [comment]
Actually, I just found out that .ply files can be exported just fine. It's just not obvious:
Add a ConvertSfMFormat node to the output of the StructureFromMotion node, and if you really want to make it look pretty, add a Publish node right after. This allows me to open point clouds in meshlab (I do seem to lack normals though).

Does that help ?

**Comment by TokyoWarfare** [comment]
I also wish there was a Dense Point cloud option instead of Mesh,  with the option to colorize the cloud.

**Comment by hectorC** [comment]
> I also wish there was a Dense Point cloud option instead of Mesh, with the option to colorize the cloud.

Plus one here. I need to produce colorized point clouds instead of meshes.

**Comment by cdosrunwild** [comment]
I agree 100 percent

**Comment by cdosrunwild** [comment]
Coffee/lunch on me                                                 
                                *Tony Lars thought you’d love Ritual.*
 
      Use the $10 gift for lunch and coffee soon! 
          Get Ritual & Accept Gift
<http://c.ritual.co/track/click/30316704/invite.ritual.co?p=eyJzIjoiYUJlbGJWWE9ral9rTFFiWm95YTdyTzkzYXFrIiwidiI6MSwicCI6IntcInVcIjozMDMxNjcwNCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2ludml0ZS5yaXR1YWwuY29cXFwvVE9OWTIwMDcwP3M9MzRcIixcImlkXCI6XCJjNzg5Y2JmYzAwZmE0NTQzYWQ1ZTdmNmJiMzZmMjIxOFwiLFwidXJsX2lkc1wiOltcImY4ZjY4ODg0ZDc5NzE2ZTI4ODM4YzFhNWRkZTdiOTE0MTc2NzMwZTFcIl19In0>  
                       *What’s Ritual?* 
       A quick and easy way to order from hundreds of restaurants in your
city, right from your phone.  
       Tony and thousands more use Ritual to get exclusive perks and
savings, skip the wait in-store, and skip the trip entirely when ordering
lunch or coffee along with teammates in the office.  
       *(yes, that means free delivery from coworkers!)*
<http://c.ritual.co/track/click/30316704/instagram.com?p=eyJzIjoiTU1pTE1uM0RaVkdCd0dINWJyR19VOUNoWUZzIiwidiI6MSwicCI6IntcInVcIjozMDMxNjcwNCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2luc3RhZ3JhbS5jb21cXFwvcml0dWFsX2NvXFxcL1wiLFwiaWRcIjpcImM3ODljYmZjMDBmYTQ1NDNhZDVlN2Y2YmIzNmYyMjE4XCIsXCJ1cmxfaWRzXCI6W1wiZDJlMDA0Y2NiMzFlMWUxMDQzNDYwNmFkMWY4ODU3YWNiN2JkZGJjYlwiXX0ifQ> <http://c.ritual.co/track/click/30316704/twitter.com?p=eyJzIjoieHRHVy03SWFtVVFVRzBjNE9yYmtnVDR2YXZJIiwidiI6MSwicCI6IntcInVcIjozMDMxNjcwNCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3R3aXR0ZXIuY29tXFxcL3JpdHVhbF9jb1wiLFwiaWRcIjpcImM3ODljYmZjMDBmYTQ1NDNhZDVlN2Y2YmIzNmYyMjE4XCIsXCJ1cmxfaWRzXCI6W1wiNDAxMjQ0NzRkNzg1MDYyYjBjMjhiZjViZTljZGMwOWY1ODA1ZGM3MVwiXX0ifQ>
<http://c.ritual.co/track/click/30316704/www.facebook.com?p=eyJzIjoiS0EtN0NwVGctX04wZ1B1aVdVLVotYW5GbVFnIiwidiI6MSwicCI6IntcInVcIjozMDMxNjcwNCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3d3dy5mYWNlYm9vay5jb21cXFwvcml0dWFsLmNvXCIsXCJpZFwiOlwiYzc4OWNiZmMwMGZhNDU0M2FkNWU3ZjZiYjM2ZjIyMThcIixcInVybF9pZHNcIjpbXCI3ODY1N2RlMGJlMjg2N2Y4ZDE3ZWMzZjczY2U1MGJhZTk1OThiYWU5XCJdfSJ9>       support@ritual.co
<mailto:support@ritual.co>    www.ritual.co <http://c.ritual.co/track/click/30316704/www.ritual.co?p=eyJzIjoicHREWWZuVENIcHRFUEhCamF6SEJ6RFIwR2NBIiwidiI6MSwicCI6IntcInVcIjozMDMxNjcwNCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3d3dy5yaXR1YWwuY29cIixcImlkXCI6XCJjNzg5Y2JmYzAwZmE0NTQzYWQ1ZTdmNmJiMzZmMjIxOFwiLFwidXJsX2lkc1wiOltcIjdmMGY0NTQ4Mjg4ZGZjODEwMDAyMTRlYzA4NTY5NjlkMmYwMDk5OGFcIl19In0>   
Email Preferences
<http://c.ritual.co/track/click/30316704/order.ritual.co?p=eyJzIjoiRHFhcE5yQXQ1T2hKaGx6NFZobVVfTDZNM1FZIiwidiI6MSwicCI6IntcInVcIjozMDMxNjcwNCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL29yZGVyLnJpdHVhbC5jb1xcXC91bnN1YnNjcmliZT90eXBlPW1hcmtldGluZyZlbWFpbD1yZXBseSswMjdhZDI5ZDU0NTBlNjE3MmU1MjMyYWMzMGMzNzlmZWQyZmQzMzczOWI4ZjNmMWI5MmNlYmFiZDA5NmI5MmExNjljZTE1ZGFlYWVhQHJlcGx5LmdpdGh1Yi5jb21cIixcImlkXCI6XCJjNzg5Y2JmYzAwZmE0NTQzYWQ1ZTdmNmJiMzZmMjIxOFwiLFwidXJsX2lkc1wiOltcImY4ZjY4ODg0ZDc5NzE2ZTI4ODM4YzFhNWRkZTdiOTE0MTc2NzMwZTFcIl19In0>
   Unsubscribe
<http://c.ritual.co/track/click/30316704/order.ritual.co?p=eyJzIjoiRHFhcE5yQXQ1T2hKaGx6NFZobVVfTDZNM1FZIiwidiI6MSwicCI6IntcInVcIjozMDMxNjcwNCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL29yZGVyLnJpdHVhbC5jb1xcXC91bnN1YnNjcmliZT90eXBlPW1hcmtldGluZyZlbWFpbD1yZXBseSswMjdhZDI5ZDU0NTBlNjE3MmU1MjMyYWMzMGMzNzlmZWQyZmQzMzczOWI4ZjNmMWI5MmNlYmFiZDA5NmI5MmExNjljZTE1ZGFlYWVhQHJlcGx5LmdpdGh1Yi5jb21cIixcImlkXCI6XCJjNzg5Y2JmYzAwZmE0NTQzYWQ1ZTdmNmJiMzZmMjIxOFwiLFwidXJsX2lkc1wiOltcImY4ZjY4ODg0ZDc5NzE2ZTI4ODM4YzFhNWRkZTdiOTE0MTc2NzMwZTFcIl19In0>
   Privacy <http://c.ritual.co/track/click/30316704/ritual.co?p=eyJzIjoiYk1JbHdqN1ZpOGs0RVFMazN1X3FUdzgzVGZ3IiwidiI6MSwicCI6IntcInVcIjozMDMxNjcwNCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3JpdHVhbC5jb1xcXC9wcml2YWN5XCIsXCJpZFwiOlwiYzc4OWNiZmMwMGZhNDU0M2FkNWU3ZjZiYjM2ZjIyMThcIixcInVybF9pZHNcIjpbXCJmYTRmNzVlNzI5OGM4YzNhOWRiYzAzZTg3ZjY1NjMwNTRkZTg3MTY1XCJdfSJ9>    
  
 82 Peter Street, Toronto, ON, M5V 2G5

**Comment by natowi** [comment]
@hectorC https://github.com/alicevision/meshroom/pull/382

**Comment by natowi** [comment]
Now available with the 2020 release.
