### ISSUE TITLE
Camera orientation is wrong?

### ISSUE THREAD

**Issue by madmage** [alicevision/meshroom#274]
Dear all,
we want to retrieve the camera track from SfM node, there is a file, cameras.sfm in the working dir of SfM, that seems to be the right thing. However, when I use those poses in another software (namely, Blender or THREE.js), while the position is fine, the orientation (i.e., the rotation matrix) seems to be somehow rotated. Given that the cameras are oriented in such a way that they see what is towards the negative Z and they have Y upwards (as it is shown in the 3D view and as it is quite common in all 3D software), when I import those poses into Blender or THREE.js, I see that there is a rotation, it seems like it is a rotation around the camera X axis (horizontal axis) of 180 degrees (i.e., the camera is looking towards the positive Z and its up vector is -Y). Is this correct? If it is correct, why?
This seems to me that it also answer to the question "why the models are usually upside down (their up vector is negative Y)", that has been asked many times here.

**Comment by fabiencastan** [comment]
Yes, it exists multiple standard coordinate systems. AliceVision uses the one standard in computer vision.
It's not the same standard in 3D softwares like Blender, Maya, Unity, Unreal.
In Maya, for instance, you have to invert Y and Z. So multiply by a matrix:
```
1  0  0 0
0 -1  0 0
0  0 -1 0
0  0  0 1
```
In Unity, for instance, you have to invert X and Y. So multiply by a matrix:
```
-1  0  0 0
 0 -1  0 0
 0  0  1 0
 0  0  0 1
```
I don't know for the others.
If you use the Alembic file, it ensures that you export/import with the correct conversions.

For the upside down by default, it's a different problem and it's related to the way we compute the initial camera pair. I never had enough time to look at it.

**Comment by madmage** [comment]
Thanks for the prompt and precise answer, @fabiencastan .
I am happy that our reverse engineering study has been successful ;-).
In order to understand exactly what you are saying, correct me if I am wrong: when you say "multiple standard coordinate systems", you are not referring to a reference frame, but to how the camera is oriented with respect to its own reference system, is this correct? I mean, in OpenGL the camera has Y up and Z backwards, it seems that in AliceVision has Z in the direction of the "view", and -Y up.

I am a bit confused about the matrices you mentioned: inverting Y and Z without inverting also the X, makes the reference system left-handed, while it should remain right-handed. Do I understand correctly what you said?

**Comment by simogasp** [comment]
> I am a bit confused about the matrices you mentioned: inverting Y and Z without inverting also the X, makes the reference system left-handed, while it should remain right-handed. Do I understand correctly what you said?

Actually you are rotating along the x axis by `pi`, so the generic rotation matrix for a rotation along X
```
1    0         0    0
0 cos a  -sin a     0
0 sin a   cos a     0
0   0         0     1
```
assumes that form for `a = pi`

@fabiencastan we should write a wikipedia entry for that, once for all, as it is a recurrent nigthmare question :-D

**Comment by simogasp** [comment]
> However, what do you ( @fabiencastan ) mean for "multiple standard coordinate systems"?
It's exactly what you wrote: different systems (Maya, OpenGL) have different conventions for the reference system of the camera. As you said opengl has z axis pointing "inside" the camera while in computer vision normally it's the other way around. This is just a convention, nothing changes, you just need to find the transformations that map these reference systems one into another.

**Comment by natowi** [comment]
Maybe this conversion can be implemented in a node.

**Comment by madmage** [comment]
@simogasp ok that's fine for me, but at this point I see that the camera visualization in the 3D view of Meshroom is misleading: it shows a camera with the Z axis pointing backwards (with respect to what it sees) and the X to the right ("OpenGL way"), while Meshroom (AliceVision) is using a camera reference frame rotated in another way ("computer vision way")

**Comment by Buithienbao** [comment]
Hi everyone, I know this issue has been closed but I am facing the same problem but I can't figure out the solution. Hence, I would like to ask you guys here. 
@madmage @everyone would you mind share with me your solution regarding how to convert the pose from blender world to meshroom world? 
I have tried something like:
- Create a scene in blender with an object and a synthetic camera
- Take pictures of that object using the created camera above
- Calibrate that synthetic camera
- Perform the pipeline of Meshroom with that set of images using the obtained intrinsic values (lock intrinsic params in the pipeline)
- Once the model is generated, I load the generated alembic file (sfm.abc) in blender. Then I compare the poses displayed in blender with the one in the cameras.sfm file, and I have found this: To go from meshroom to blender, the rotation matrix has to be multiplied element-wise with the 3x3 matrix
`1 -1 -1
1 -1 -1
-1 1 1`
and then swap the 2nd and 3rd row. With respect to the translation, the 2nd row has to be swap with (-1)*3rd row, for example the original translation is 
`a b c`
after converting it becomes
`a -c b`

Is this correct? I think this is a bit weird compared to other software like Maya, Unity, etc where you only need a simple matrix multiplication. 
If you can help me with this, I would greatly appreciate it.

**Comment by simogasp** [comment]
the conversion Meshroom -> Blender/Maya (through alembic) is described here for the pose
https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/sfmDataIO/AlembicExporter.cpp#L108

You also need to consider that beside the different reference system convention, there is also a row-major (meshroom/Eigen) to column-major (Blender/OpenGl...) conversion to make
