### ISSUE TITLE
Bad uv's

### ISSUE THREAD

**Issue by Hazzy155** [alicevision/meshroom#276]
I'm getting really bad uv's on a rock, I've tried all three of the unwrap methods LSCN ABF basic.
I've tried doing it the way that yann-lty said in #236, but I get the same error as the two other guys in that thread.

is there a way that I can make my own uv map?

for an example how bad the uv's are, they're literally taking up 1/4 of the texture at 4k.

**Comment by fabiencastan** [comment]
Do you have the problem in the meshroom viewer? Or only when you import the mesh into another software?

**Comment by Hazzy155** [comment]
Really wish I could just uv it myself.

**Comment by fabiencastan** [comment]
You could already create your own UVs manually in your preferred 3D modeling software and the re-texturing will use it.

**Comment by Hazzy155** [comment]
do I just edit the mesh in the MeshFiltering stage? because I tried doing that like what yann-lty said in #236 
and it didn't work.

**Comment by Hazzy155** [comment]
Update: I may have gotten it to work I'll report back in 10 minutes when it's done

**Comment by Hazzy155** [comment]
Update2: i got it to work
Steps so other people can get it to work as well
Step1 - right click on the stage before texturing and click open folder
Step2 - open the Mesh up in blender(do not rotate or move it at all and you may want to create a backup of the mesh)
Step3 - go into edit mode and unwrap it
Step4 - then go to export as obj
Step5 - make sure the export settings are all unticked except
Selection Only
Apply Modifiers
include UVs
Step5 - and export it to the same mesh as one you opened it from

**Comment by Hazzy155** [comment]
Cool that should make it much easier(and safer lol) tomorrow I'll try that and update my steps
thanks for your help :)
