### ISSUE TITLE
aliceVision_incrementalSfm - AliceVision 2.0.0 has stopped working

### ISSUE THREAD

**Issue by Angus94** [alicevision/meshroom#278]
![2018-10-19_10-53-22](https://user-images.githubusercontent.com/39000124/47190798-35ba8380-d38f-11e8-937e-5eeec16cb356.jpg)

had this program 30 minutes and the message window above popped up during a try of the software. can someone please offer a solution.

thank you

i notice i also get this message when starting up  .....
![2018-10-19_12-38-33](https://user-images.githubusercontent.com/39000124/47192950-1a09aa00-d39c-11e8-9fcd-1a7b2bd49284.jpg)

and here is my latest log file....
Program called with the following parameters:
 * describerTypes = "sift"
 * extraInfoFolder = "F:/vega funny car pics/MeshroomCache/StructureFromMotion/0929c39916eee656beac989e62817062a602d64e"
 * featuresFolders =  = [F:/vega funny car pics/MeshroomCache/FeatureExtraction/c55d0b6adbfc5bc8a92d5e969da53b4d47e488ef]
 * initialPairA = ""
 * initialPairB = ""
 * input = "F:/vega funny car pics/MeshroomCache/CameraInit/3b45fd86345be938df08ac4dc4d62d09bd293578/cameraInit.sfm"
 * interFileExtension = ".abc"
 * localBAGraphDistance = 1
 * localizerEstimator = "acransac"
 * lockScenePreviouslyReconstructed = 0
 * matchesFolders =  = [F:/vega funny car pics/MeshroomCache/FeatureMatching/bda1d599555e661ca31167278c4cb00aa13ce140]
 * maxAngleInitialPair = 40
 * maxNumberOfMatches = 0
 * maxReprojectionError = 4
 * minAngleForLandmark = 2
 * minAngleForTriangulation = 3
 * minAngleInitialPair = 5
 * minInputTrackLength = 2
 * minNumberOfObservationsForTriangulation = 2
 * output = "F:/vega funny car pics/MeshroomCache/StructureFromMotion/0929c39916eee656beac989e62817062a602d64e/sfm.abc"
 * outputViewsAndPoses = "F:/vega funny car pics/MeshroomCache/StructureFromMotion/0929c39916eee656beac989e62817062a602d64e/cameras.sfm"
 * refineIntrinsics = 1 (default)
 * useLocalBA = 1
 * useOnlyMatchesFromInputFolder = 0
 * useTrackFiltering = 1 (default)
 * verboseLevel = "info"

Loading features
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

computer specs are
win7 Ult 64bit, 32gb DDR ram, nVidia GeForce GTX760 vid card, plenty of hard drive space

**Comment by natowi** [comment]
I don´t know why it crashed, but try again with the demo files from https://github.com/alicevision/dataset_monstree
The "Failed to download..." error is nothing to worry about

**Comment by Angus94** [comment]
natowi.....thanks for your reply, i downloaded the demo files, dragged the pics in and adjusted nothing else, then hit START, the progress bar at the top didnt move for ages, so i pressed STOP, slowly the bar moved along as i restarted the process.......when it got to StructureFromMotion the same dialogue box appeared and stopped the application

**Comment by natowi** [comment]
Seems to be the Win7 related problem, read #216 #183 #145

**Comment by Angus94** [comment]
i tried the workaround they suggested but its just sitting idle, so i think i will just give up on this program and look for another offering, i dont have the time or patience to play around and nursemaid this software, its a bit disappointing to be honest

**Comment by yann-lty** [comment]
@Angus94 Could you try with the patched version for Windows 7, available [here](https://github.com/alicevision/meshroom/releases/download/v2018.1.0/Meshroom-2018.1.0-win7-64.zip), and close this issue if this solves your problem ?

**Comment by konvoj** [comment]
I'm getting the same issue on Win 10. Lowering the maxPoints as suggested didn't help. Tried to play with different values as well, using lower res pictures, nothing helped. Log below:

Program called with the following parameters:
 * angleFactor = 15
 * contributeMarginFactor = 2
 * depthMapFilterFolder = "C:/Users/j.konvicny/Desktop/Scan/MeshroomCache/DepthMapFilter/2973e05047f10653f5a64e33a2ac1eba64cc59fc"
 * depthMapFolder = "C:/Users/j.konvicny/Desktop/Scan/MeshroomCache/DepthMap/9fbc520f4833adba83a4eda8296a1e8e03fc94f3"
 * ini = "C:/Users/j.konvicny/Desktop/Scan/MeshroomCache/PrepareDenseScene/f097dc1c98985a843df98ab1774c0fa6ae2b45af/mvs.ini"
 * maxInputPoints = 10
 * maxPoints = 10
 * maxPointsPerVoxel = 10
 * minAngleThreshold = 1
 * minStep = 2
 * output = "C:/Users/j.konvicny/Desktop/Scan/MeshroomCache/Meshing/abe53973c494ba1e7211b42af8458fa5e1845a89/mesh.obj"
 * partitioning =  Unknown Type "enum EPartitioningMode"
 * pixSizeMarginFinalCoef = 4
 * pixSizeMarginInitCoef = 2
 * refineFuse = 1
 * repartition =  Unknown Type "enum ERepartitionMode"
 * simFactor = 15
 * simGaussianSize = 10
 * simGaussianSizeInit = 10
 * verboseLevel = "info"
 * voteMarginFactor = 4

[12:58:37.267998][info] Found 1 image dimension(s): 
[12:58:37.267998][info]  - [3968x2976]
[12:58:37.271007][info] Overall maximum dimension: [1984x1488]
[12:58:37.271007][warning] repartitionMode: 2
[12:58:37.272010][warning] partitioningMode: 1
[12:58:37.272010][info] Meshing mode: regular Grid, partitioning: single block.
[12:58:37.274015][info] Estimate space.

**Comment by konvoj** [comment]
I made second set of images and had no issue with crashing. It seems that if there isn't enough pictures accepted for reconstruction, the aliceVision will crash. 
Even I followed guidelines for taking pictures, first attempt was 3/28 accepted and crash, second attempt 8/24 and no crash, but unusable reconstruction.
