### ISSUE TITLE
I can't see Graph editor

### ISSUE THREAD

**Issue by Disminer** [alicevision/meshroom#279]
When I open Meshroom, two windows open. One that looks like Meshroom should look (screenshot below)
![meshroom screenshot](https://user-images.githubusercontent.com/43815230/47218099-f568fe80-d3aa-11e8-9e4a-1b848218130b.jpg)

and the other one looks like (screenshot below).
![meshroom screenshot 2 1](https://user-images.githubusercontent.com/43815230/47218199-4a0c7980-d3ab-11e8-88fd-2c27203dea66.jpg)
![meshroom screenshot 2 2](https://user-images.githubusercontent.com/43815230/47218392-e6cf1700-d3ab-11e8-82ee-92261436b6c1.jpg)

and also, in graph editor, I can't see anything, like i can click blindly on things but they are not showing up. When I press start it starts but then stops.

**Comment by natowi** [comment]
Make sure you have the latest Nvidia driver installed. As you can see from the error log, OpenGL with GLSL 3+ is required.

**Comment by Disminer** [comment]
When I download any Nvidia driver, it's not compatible with my device.

**Comment by natowi** [comment]
What graphics card do you have? A Nvidia card is required.

**Comment by kma-innovate** [comment]
I have the same problem. I'm running a GTX 1070 with the 12/12/2018 GeForce Came Ready Driver Version 417.35. Runs fine on my other box with a GT 710.

![image](https://user-images.githubusercontent.com/45835791/49907831-bf854b00-fe2c-11e8-94e3-5221b7793db3.png)

Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, ExportUndistortedImages, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[QtOIIO] Plugin Initialized
[DepthMapEntity] DepthMapEntity
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete, missing attachment.
Failed to download scene at QUrl("")
QOpenGLShader::compile(Vertex): ERROR: 0:1: 'core' : invalid version directive
ERROR: 0:2: 'in' : storage qualifier supported in GLSL ES 3.00 only
ERROR: 0:3: 'in' : storage qualifier supported in GLSL ES 3.00 only
ERROR: 0:4: 'out' : storage qualifier supported in GLSL ES 3.00 only
ERROR: 0:7: '1.0f' : Floating-point suffix unsupported prior to GLSL ES 3.00
ERROR: 0:7: '1.0f' : syntax error

*** Problematic Vertex shader source code ***
#version 330 core
#line 1
        uniform mat4 modelViewProjection;
        in vec3 vertexPosition;
        in vec3 vertexColor;
        out vec3 colors;
        void main(void)
        {
            gl_Position = modelViewProjection * vec4(vertexPosition, 1.0f);
            colors = vertexColor;
        }

***
QOpenGLShader::compile(Fragment): ERROR: 0:1: 'core' : invalid version directive
ERROR: 0:1: 'in' : storage qualifier supported in GLSL ES 3.00 only
ERROR: 0:1: '' : No precision specified for (float)
ERROR: 0:2: 'out' : storage qualifier supported in GLSL ES 3.00 only
ERROR: 0:2: '' : No precision specified for (float)

*** Problematic Fragment shader source code ***
#version 330 core
#line 1
        in vec3 color;
        out vec4 fragColor;
        void main(void)
        {
            fragColor = vec4(color, 1.0);
        }

***
QOpenGLShader: could not create shader

**Comment by chernordiallo** [comment]
Please don't send me this anymore.

**Comment by fabiencastan** [comment]
As explained in the Release notes and the README:
```
Linux: on some distributions (e.g Ubuntu), you may have conflicts between native drivers and mesa drivers, resulting in an empty black window. In that case, you need to force usage of native drivers by adding them to the LD_LIBRARY_PATH: LD_LIBRARY_PATH=/usr/lib/nvidia-340 ./Meshroom
You may need to adjust the folder /usr/lib/nvidia-340 with the correct driver version.
```
Have you tried that?

**Comment by kma-innovate** [comment]
I apologize, I should have stated that I am using Windows 10.
