### ISSUE TITLE
"Not Reconstructed", why do i keep getting this on certain images?

### ISSUE THREAD

**Issue by ChewBaz** [alicevision/meshroom#285]
Hello!

I have this issue where i seem to get "Not Reconstructed" on some pictures and I can´t figure out why so I can eliminate a bad camera practice maybe. What are the usual causes for this message?

(For those that do not know I am talking about i mean when you get a red minus over your picture)

Thanks!

EDIT: Another question, how do I edit the database file to fix this: "The camera found in the database is slightly different for image(s):"?

**Comment by natowi** [comment]
I think these links answer your questions:
https://github.com/alicevision/meshroom/wiki/Add-Camera-to-database
https://github.com/alicevision/meshroom/wiki/StructureFromMotion-fails

**Comment by ChewBaz** [comment]
Thank you really much! That helped me! I wish there was a preset function though so I do not have to change to akaze everytime I restart the program.

Thank you again!

**Comment by mb3m3r** [comment]
Hi everyone, I'm having this issue with some images only. They were all taken by the same camera but some of them are marked as "camera not reconstructed". Do you guys think this is an issue of the camera itself? Or software related?

**Comment by natowi** [comment]
@mb3m3r probably dataset related. Maybe the image is blurry and not enough features were detected+matched to other images.
