### ISSUE TITLE
DB AliceVision for Nokia 7 Plus

### ISSUE THREAD

**Issue by LambaFlips** [alicevision/meshroom#287]
Hi

Here is the console message:
[16:54:37.875188][error] image: 'IMG_20181104_163601.jpg'
        - camera brand:
        - camera model: Nokia 7 plus

[16:54:37.875188][error] Please add camera model(s) and sensor width(s) in the database.

I tried to insert various lines like

Nokia;Nokia 7 plus;2.55

but without success

tips?

https://www.devicespecifications.com/en/model/290e4872

**Comment by LambaFlips** [comment]
Thanks for your help

unfortunately it is not good with your suggestion, same error

[16:54:37.875188][error] image: 'IMG_20181104_163601.jpg'
- camera brand:
- camera model: Nokia 7 plus

[16:54:37.875188][error] Please add camera model(s) and sensor width(s) in the database.

**Comment by natowi** [comment]
I tested Meshroom with Nokia 7 plus [sample images](https://www.fonearena.com/blog/250234/nokia-7-plus-camera-samples.html) - they load with default values (Make is empty). When I add the camera Make "Nokia" to the Exif, the images are loaded with the sensordb info.
- Check the Exif data of your images. It should contain Make: Nokia and Model Nokia 7 plus
If the import still fails, you can share a sample image here for testing.

**Comment by LambaFlips** [comment]
Hello,

thanks for the help, yes, in the EXIF of the photos, as "Model", the word "Nokia" was missing

now it's processing, thank you!
