### ISSUE TITLE
Error on Import

### ISSUE THREAD

**Issue by styleznma** [alicevision/meshroom#289]
Thank you in advanced.

I get this when I import a photo (see log below)
I tried adding the camera to the DB but no luck

Samsung S9plus.

I tried these strings;
Samsung;Samsung Galaxy S7;5.75
Samsung;Samsung Galaxy S9;5.75
Samsung;Samsung Galaxy S9plus;5.75
Samsung;Samsung Galaxy S9 plus;5.75
Samsung;Samsung Galaxy G965;5.75
Samsung;Samsung Galaxy G965U;5.75
Samsung;Samsung Galaxy SM-G965U;5.75
Samsung;Samsung Galaxy SM G965U;5.75
Samsung;Samsung Galaxy SMG965U;5.75

But i dont know if this is the problem or not. I also tried to strip EXIF data as well with no luck.

ERROR:root:Error while building intrinsics : Traceback (most recent call last):
  File "f:\tmp\meshroom\meshroom\ui\reconstruction.py", line 384, in buildIntrinsics
  File "f:\tmp\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 129, in buildIntrinsics
RuntimeError: CameraInit failed with error code 3221225477. Command was: "aliceVision_cameraInit  --sensorDatabase "C:\Users\style\Desktop\Meshroom-2018.1.0\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --verboseLevel info --output "C:/Users/style/AppData/Local/Temp/tmpzjm4f7np/CameraInit/2731003bd822aa3d98acd3185af7e6a65750fcd4/cameraInit.sfm" --allowSingleView 1  --input "C:\Users\style\AppData\Local\Temp\tmpzjm4f7np/CameraInit/2731003bd822aa3d98acd3185af7e6a65750fcd4//viewpoints.sfm" --allowIncompleteOutput 1"

**Comment by natowi** [comment]
@styleznma is this still an issue or did you fix it?
