### ISSUE TITLE
Stuck on PrepareDenseScene

### ISSUE THREAD

**Issue by ROllie84** [alicevision/meshroom#290]
I'm very new to this and am constantly finding a completed orange bar over PrepareDenseScene node and the log I have shows its completed but doesn't proceed to CameraConnection. I'm only using 29 images and the log below is as follows:

Program called with the following parameters:
 * input = "S:/3DSMFiles/Rudys3dhead/CompiledHead/MeshroomCache/StructureFromMotion/4783bbb0448dbfb5e286a00b80956525fb68c7ef/sfm.abc"
 * output = "S:/3DSMFiles/Rudys3dhead/CompiledHead/MeshroomCache/PrepareDenseScene/d548193ad52d968d9f2ef105ce8ed8d3ef9a3f0d"
 * verboseLevel = "info"

Exporting Scene Data
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

I'm on a windows 7 system. Any help would be appreciated.

**Comment by natowi** [comment]
Meshroom on Win7 is known to have some problems #216 #183 #145.
Try again with a sample dataset that is known to work and report back: https://github.com/alicevision/dataset_monstree/tree/master/mini6

**Comment by ROllie84** [comment]
Tested out with the images provided in the link. I get approximately 50% DepthMap before an error message: 

Program called with the following parameters:
 * downscale = 2
 * ini = "S:/3DSMFiles/testtree/MeshroomCache/PrepareDenseScene/687e9e26fa2613bde47fc382b5ab8a0c17541575/mvs.ini"
 * output = "S:/3DSMFiles/testtree/MeshroomCache/DepthMap/f19492531717ac0752f345e89ec115fb0631e588"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[15:51:19.629176][info] 
[15:51:19.635176][error] This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0).

The last line doesn't make sense as I have a GeForce GTX 750 with a 5.0 compute capability. Unless they want a capablility which I hope is just an error in spelling and not some new computer jargon.

I hope I am missing something and any help would be appreciated.

**Comment by natowi** [comment]
@ROllie84 Install the latest Nvidia driver for your GTX 750. Sometimes the driver is not up to date, a wrong driver version for your GPU or not installed at all.
If it still does not work, I am pretty sure this is a Win7 related bug #216 #183 #145

**Comment by ROllie84** [comment]
Thanks @natowi 
I've verified my driver settings are up to date. I have re-run the process. This is the latest log report.

Program called with the following parameters:
 * downscale = 2
 * ini = "S:/3DSMFiles/testtree/MeshroomCache/PrepareDenseScene/687e9e26fa2613bde47fc382b5ab8a0c17541575/mvs.ini"
 * output = "S:/3DSMFiles/testtree/MeshroomCache/DepthMap/f19492531717ac0752f345e89ec115fb0631e588"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[12:20:50.550727][info] CUDA-Enabled GPU.
Device information:
	- id:                      0
	- name:                    GeForce GTX 750
	- compute capability:      5.0
	- total device memory:     2048 MB 
	- per-block shared memory: 49152
	- warp size:               32
	- max threads per block:   1024
	- max threads per SM(X):   2048
	- max block sizes:         {1024,1024,64}
	- max grid sizes:          {2147483647,65535,65535}
	- number of SM(x)s:        4
	- registers per SM(x):     65536
	- registers per block:     65536
	- concurrent kernels:      yes
	- mapping host memory:     yes
	- unified addressing:      yes
	- texture alignment:       512 byte
	- pitch alignment:         32 byte

[12:20:50.939749][info] Supported CUDA-Enabled GPU detected.
[12:20:50.939749][info] Found 1 image dimension(s): 
[12:20:50.939749][info]  - [4032x3024]
[12:20:51.077757][info] Overall maximum dimension: [2016x1512]
[12:20:51.077757][info] Create depth maps.
number of CUDA devices:	1
   0: GeForce GTX 750
[12:20:51.080757][info] Number of GPU devices: 1, number of CPU threads: 2
[12:20:51.080757][info] PSSGM autoScaleStep: scale: 2, step: 2
[12:20:51.080757][info] PlaneSweepingCuda:
	- nImgsInGPUAtTime: 6
	- scales: 2
	- subPixel: Yes
	- varianceWSH: 
CUDA device no 0 for 0
Device 0 memory - used: 408.628906, free: 1639.371094, total: 2048.000000
Device 0 memory - used: 497.878906, free: 1550.121094, total: 2048.000000
[12:21:56.109476][info] Depth map already computed: S:/3DSMFiles/testtree/MeshroomCache/DepthMap/f19492531717ac0752f345e89ec115fb0631e588/797046670_idDepthMap_scale2_step2_SGM.png
[12:21:56.109476][info] Depth map already computed: S:/3DSMFiles/testtree/MeshroomCache/DepthMap/f19492531717ac0752f345e89ec115fb0631e588/1350185492_idDepthMap_scale2_step2_SGM.png
[12:21:56.109476][info] Depth map already computed: S:/3DSMFiles/testtree/MeshroomCache/DepthMap/f19492531717ac0752f345e89ec115fb0631e588/1585770300_idDepthMap_scale2_step2_SGM.png
number of CUDA devices:	1
   0: GeForce GTX 750
[12:21:56.157479][info] Number of GPU devices: 1, number of CPU threads: 2
[12:21:56.157479][info] PSSGM autoScaleStep scale: 2, step: 2
[12:21:56.157479][info] PlaneSweepingCuda:
	- nImgsInGPUAtTime: 6
	- scales: 2
	- subPixel: Yes
	- varianceWSH: 
CUDA device no 0 for 0
Device 0 memory - used: 402.160156, free: 1645.839844, total: 2048.000000
Device 0 memory - used: 491.410156, free: 1556.589844, total: 2048.000000
[12:22:57.470986][warning] rc: 0 - found only 5/10 tc by seeds
[12:22:57.471986][warning] rc: 0 - found only 5/6 tc by seeds
gpu elapsed time: 1279.000000 ms 
gpu elapsed time: 1230.000000 ms 
gpu elapsed time: 1237.000000 ms 
gpu elapsed time: 1208.000000 ms 
gpu elapsed time: 1245.000000 ms 
gpu elapsed time: 1243.000000 ms 
gpu elapsed time: 1246.000000 ms 
gpu elapsed time: 1194.000000 ms 
gpu elapsed time: 1216.000000 ms 
gpu elapsed time: 1245.000000 ms 
gpu elapsed time: 1241.000000 ms 
gpu elapsed time: 1206.000000 ms 
gpu elapsed time: 857.000000 ms 
gpu elapsed time: 1233.000000 ms 
gpu elapsed time: 1242.000000 ms 
gpu elapsed time: 1220.000000 ms 
gpu elapsed time: 809.000000 ms 
gpu elapsed time: 1250.000000 ms 
gpu elapsed time: 1289.000000 ms 
gpu elapsed time: 1202.000000 ms 
gpu elapsed time: 1359.000000 ms 
gpu elapsed time: 1371.000000 ms 
gpu elapsed time: 1426.000000 ms 
gpu elapsed time: 1436.000000 ms 
rc: 0, gpu elapsed time: 607.000000 ms 
rc: 0, gpu elapsed time: 580.000000 ms 
rc: 0, gpu elapsed time: 580.000000 ms 
rc: 0, gpu elapsed time: 606.000000 ms 
[12:23:36.369211][warning] rc: 1 - found only 5/10 tc by seeds
[12:23:36.369211][warning] rc: 1 - found only 5/6 tc by seeds
gpu elapsed time: 1166.000000 ms 
gpu elapsed time: 1262.000000 ms 
gpu elapsed time: 1251.000000 ms 
gpu elapsed time: 1153.000000 ms 
gpu elapsed time: 1202.000000 ms 
gpu elapsed time: 1264.000000 ms 
gpu elapsed time: 1267.000000 ms 
gpu elapsed time: 1168.000000 ms 
gpu elapsed time: 785.000000 ms 
gpu elapsed time: 1192.000000 ms 
gpu elapsed time: 1247.000000 ms 
gpu elapsed time: 1243.000000 ms 
gpu elapsed time: 683.000000 ms 
gpu elapsed time: 1260.000000 ms 
gpu elapsed time: 1259.000000 ms 
gpu elapsed time: 1209.000000 ms 
gpu elapsed time: 1120.000000 ms 
gpu elapsed time: 1269.000000 ms 
gpu elapsed time: 1268.000000 ms 
gpu elapsed time: 1123.000000 ms 
gpu elapsed time: 1414.000000 ms 
gpu elapsed time: 1326.000000 ms 
gpu elapsed time: 1439.000000 ms 
gpu elapsed time: 1385.000000 ms 
rc: 1, gpu elapsed time: 552.000000 ms 
rc: 1, gpu elapsed time: 530.000000 ms 
rc: 1, gpu elapsed time: 544.000000 ms 
rc: 1, gpu elapsed time: 508.000000 ms 
[12:24:14.253378][warning] rc: 2 - found only 5/10 tc by seeds
[12:24:14.253378][warning] rc: 2 - found only 5/6 tc by seeds
gpu elapsed time: 1107.000000 ms 
gpu elapsed time: 1259.000000 ms 
gpu elapsed time: 1258.000000 ms 
gpu elapsed time: 1106.000000 ms 
gpu elapsed time: 1234.000000 ms 
gpu elapsed time: 1235.000000 ms 
gpu elapsed time: 1246.000000 ms 
gpu elapsed time: 1186.000000 ms 
gpu elapsed time: 1137.000000 ms 
gpu elapsed time: 1259.000000 ms 
gpu elapsed time: 1261.000000 ms 
gpu elapsed time: 1208.000000 ms 
gpu elapsed time: 799.000000 ms 
gpu elapsed time: 1223.000000 ms 
gpu elapsed time: 1292.000000 ms 
gpu elapsed time: 1241.000000 ms 
gpu elapsed time: 705.000000 ms 
gpu elapsed time: 1252.000000 ms 
gpu elapsed time: 1263.000000 ms 
gpu elapsed time: 1226.000000 ms 
gpu elapsed time: 1350.000000 ms 
gpu elapsed time: 1352.000000 ms 
gpu elapsed time: 1335.000000 ms 
gpu elapsed time: 1414.000000 ms 
rc: 2, gpu elapsed time: 531.000000 ms 
rc: 2, gpu elapsed time: 604.000000 ms 
rc: 2, gpu elapsed time: 533.000000 ms 
rc: 2, gpu elapsed time: 512.000000 ms 
[12:24:52.372558][info] Task done in (s): 241.823000

The task done in (s):241.823000 has been unchanged for the past three hours on Chunk 1. Chunk 0 was a success within seconds.

**Comment by yann-lty** [comment]
Could you try with the patched version for Windows 7, available [here](https://github.com/alicevision/meshroom/releases/download/v2018.1.0/Meshroom-2018.1.0-win7-64.zip), and close this issue if this solves your problem ?
Thanks!

**Comment by Cheboy** [comment]
Im also new to this and Im using Win10. Having the same issue as the mate here describes. Dont know how to go any further. In my case Im using 119 pic. and I have a geforce 940mx. Not a powerful gpu but I did get some good results with the sample fotos of the rock that someone in github provided.
Im open to suggestions.
