### ISSUE TITLE
Thoughts on "Sensor width doesn't exist in the database for image(s)" and "Please add camera model(s) and sensor width(s) in the database"

### ISSUE THREAD

**Issue by ScottMcNay** [alicevision/meshroom#295]
I just downloaded and installed the binary for 2018.1.0 Win64. It doesn't like my camera (Samsung SGH-i717). I'm not able to find any information about it on the two sites listed. I see that the next version is planned to have an auto-detect feature, but it appears that the user is assumed to have the camera available to run the auto-detect procedure; I don't (actually, I know someone who might have one, but that's beside the point). I put in a fake number and it's working now, but:

1. Propose a failsafe mechanism, for if the auto-detect fails (camera not available, etc): ask the user for data; refer to the two sites and tell the user the size range and mean for cameras with similar info.

2. Propose asking the user for permission to auto-submit camera info (EXIF data doesn't match the name in the database, found sensor info from a third party source, autodetected info) to the server.

3. What's the result of using a fake number which is too far from reality? What do we look for to know that the fake number needs to be changed, and in which direction to change it, and by how much to try changing it?

--Scott.

**Comment by natowi** [comment]
Your Samsung SGH-I717 phone is [also known as](https://www.gsmarena.com/samsung_galaxy_note_i717-4374.php) Samsung Galaxy Note 4G or Samsung Galaxy Note LTE or [4 Duos](https://www.devicespecifications.com/en/model/974e3049). It has a [1/2.6” BSI-CMOS Sensor - Sony IMX-240](https://www.sammobile.com/2014/08/21/exclusive-samsung-galaxy-note-4-camera-features-16mp-side-touch-wide-selfie-and-much-more/) ([IMX240](https://en.wikipedia.org/wiki/Exmor)).
Try~ 5.54 as width.

1) I think this is already on the to-do list

2) I like this idea, but this requires a server...

3) The sensor width is used to set-up the internal coordinate system, so it is important to have a value close to reality. The "width" range of the sensor for many mobile phone main cameras is approx. 4-7mm.
