### ISSUE TITLE
meshroom errors

### ISSUE THREAD

**Issue by pyorkie** [alicevision/meshroom#297]
**Configuration**
Version 2018.1.0
Windows 10 pro ver 1803
Python 3.6.5

Hi
I have installed Meshroom and tried to do some pics (22 of them) but the CLI widow comes up with errors I don't understand and not sure what to do to fix ... any help would be appreciated  ... I included the CLI capture and the pic info ... maybe this might it clear to someone.
Thank you in advance for any help.
pyorkie

![meshromm error](https://user-images.githubusercontent.com/16525036/48986103-5e8b2100-f164-11e8-8c3c-e7a2ee3b26f1.png)
![pic details](https://user-images.githubusercontent.com/16525036/48986104-5e8b2100-f164-11e8-9446-11c4657ec532.png)

**Comment by natowi** [comment]
Read https://github.com/alicevision/meshroom/wiki/Add-Camera-to-database
