### ISSUE TITLE
Import camera positions

### ISSUE THREAD

**Issue by eriol726** [alicevision/meshroom#300]
Hi, I wonder if there is a way to import a file of pre-calculated camera positions in the pipeline. I know exactly the locations of my cameras, so I thought it was unnecessary to let the program calculate it. I thought it was possible to just modify the positions in the `cameras.sfm` file generated from the StructureFromMotion node and use this file as input in the StructureFromMotion node and the calculate the point cloud. I also tested to modify the camera positions in the `cameras.abc` file in maya and use the file as input. But it seems that the SFM node can only be used with the `cameraInit.sfm` file as input. Is there any other way to change camera positions?

**Comment by DanAndersen** [comment]
Hi, @eriol726, I was wondering if you had any update on your success with importing pre-calculated camera poses. I am wanting to do something similar and wanted to see if others had success or tips before getting into it myself. For my photogrammetric reconstruction, I have an estimated 6-DOF pose for each photo (accuracy is within a few centimeters for position, and within 10 degrees for rotation). Will using these initial poses help with the reconstruction, given that these initial poses are not exact? Thanks!

**Comment by fabiencastan** [comment]
This has been added recently: https://github.com/alicevision/AliceVision/pull/576
Now, if you provide camera positions without 3D points (landmarks), it will triangulate them from features matches.

**Comment by Karltlbm** [comment]
Hi ! Can you briefly explain how to use this new functionnality please ?

**Comment by nickpolet** [comment]
Would it be possible to provide and example of how to do this? I also have accurate camera positions that I can plug in. Struggling to figure out where to place the camera positions. Would be good to know how to do this via the command line (scripts) if possible.

**Comment by javl** [comment]
@nickpolet  @fabiencastan 
Do you maybe now where I can find some reference on this format? Can't seem to find anything describing what the different rotation values in the pose object are.
(I have a quaternion for each of my cameras, but I'm not sure which values to plug into the rotation part of the pose)

**Comment by shadowmint** [comment]
@javl I also found this mysterious, but if you read the source, you'll find: https://github.com/alicevision/meshroom/blob/bc1eb83d92048e6f888c4762c7ffcaab50395da6/meshroom/ui/reconstruction.py#L293

ie. This is rotation matrix.

To get a quaternion, see: https://math.stackexchange.com/questions/893984/conversion-of-rotation-matrix-to-quaternion

Or, tangibly, as code:
https://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToQuaternion/
