### ISSUE TITLE
I got stuck at the "Feature Extraction"

### ISSUE THREAD

**Issue by Batsu1** [alicevision/meshroom#301]
i got stuck here

https://i.hizliresim.com/nQkDRl.png

i found out some solutions for this but in their solutions it should say something like "task done in..." and then you are just going and changing Error to Succes but in my situation it says "RUNNING" but its not doing anything should i wait more or there is a solution to this ?

Status: 

{
    "status": "RUNNING",
    "execMode": "LOCAL",
    "nodeName": "FeatureExtraction_1",
    "nodeType": "FeatureExtraction",
    "packageName": "aliceVision",
    "packageVersion": null,
    "graph": "",
    "commandLine": "aliceVision_featureExtraction  --input \"C:/Users/User/Desktop/do\u011fukan/scan/MeshroomCache/CameraInit/5ed6087fd683f7f685dbed7be6706444614377ea/cameraInit.sfm\" --describerTypes sift --describerPreset normal --forceCpuExtraction True --verboseLevel info --output \"C:/Users/User/Desktop/do\u011fukan/scan/MeshroomCache/FeatureExtraction/b544df69cd7996663792e256868533c0f11b587c\" --rangeStart 0 --rangeSize 31",
    "env": null,
    "startDateTime": "2018-12-04 21:26:23.345606",
    "endDateTime": "",
    "elapsedTime": 0,
    "hostname": "User-Bilgisayar",
    "sessionUid": "3cc800b8-f7fa-11e8-ab04-002522b6cd70",
    "elapsedTimeStr": "0:00:00"
}

Log:
Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocaliza
tion, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, Conver
tSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, ExportUn
distortedImages, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchin
gMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshRe
sampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, Struc
tureFromMotion, Texturing
[QtOIIO] Plugin Initialized
[DepthMapEntity] DepthMapEntity
Failed to download scene at QUrl("")
Program called with the following parameters:
 * allowIncompleteOutput = 1
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraModel = 2 (default)
 * imageFolder = "" (default)
 * input = "C:\Users\User\AppData\Local\Temp\tmp6qrehvfy/CameraInit/2731003bd822
aa3d98acd3185af7e6a65750fcd4//viewpoints.sfm"
 * output = "C:/Users/User/AppData/Local/Temp/tmp6qrehvfy/CameraInit/2731003bd82
2aa3d98acd3185af7e6a65750fcd4/cameraInit.sfm"
 * sensorDatabase = "C:\Users\User\Desktop\programlar\Meshroom-2018.1.0\aliceVis
ion\share\aliceVision\cameraSensors.db"
 * verboseLevel = "info"

[21:24:50.872316][info] CameraInit report:
        - # views listed in SfMData: 47
        - # views with an initialized intrinsic listed in SfMData: 47
        - # intrinsics listed in SfMData: 1
Nodes to execute:  ['CameraInit_1', 'FeatureExtraction_1', 'ImageMatching_1', 'F
eatureMatching_1', 'StructureFromMotion_1', 'PrepareDenseScene_1', 'CameraConnec
tion_1', 'DepthMap_1', 'DepthMapFilter_1', 'Meshing_1', 'MeshFiltering_1', 'Text
uring_1']

[1/12] CameraInit
 - commandLine: aliceVision_cameraInit  --sensorDatabase "C:\Users\User\Desktop\
programlar\Meshroom-2018.1.0\aliceVision\share\aliceVision\cameraSensors.db" --d
efaultFieldOfView 45.0 --verboseLevel info --output "C:/Users/User/Desktop/doğuk
an/scan/MeshroomCache/CameraInit/5ed6087fd683f7f685dbed7be6706444614377ea/camera
Init.sfm" --allowSingleView 1  --input "C:/Users/User/Desktop/doğukan/scan/Meshr
oomCache/CameraInit/5ed6087fd683f7f685dbed7be6706444614377ea//viewpoints.sfm"
 - logFile: C:/Users/User/Desktop/doğukan/scan/MeshroomCache/CameraInit/5ed6087f
d683f7f685dbed7be6706444614377ea/log
 - elapsed time: 0:00:00.196011

[2/12] FeatureExtraction
 - commandLine: aliceVision_featureExtraction  --input "C:/Users/User/Desktop/do
ğukan/scan/MeshroomCache/CameraInit/5ed6087fd683f7f685dbed7be6706444614377ea/cam
eraInit.sfm" --describerTypes sift --describerPreset normal --forceCpuExtraction
 True --verboseLevel info --output "C:/Users/User/Desktop/doğukan/scan/MeshroomC
ache/FeatureExtraction/b544df69cd7996663792e256868533c0f11b587c" --rangeStart 0
--rangeSize 31
 - logFile: C:/Users/User/Desktop/doğukan/scan/MeshroomCache/FeatureExtraction/b
544df69cd7996663792e256868533c0f11b587c/0.log

**Comment by Batsu1** [comment]
okay i tried another picture stuck its okay now alicevision stopping at structurefrom motion

https://i.hizliresim.com/9aRzzN.png

LOG:

Program called with the following parameters:
 * describerTypes = "sift"
 * extraInfoFolder = "C:/Users/User/Desktop/do�ukan/scan/MeshroomCache/StructureFromMotion/5c711b84cdca05ffe5152d13cae66462b6031129"
 * featuresFolders =  = [C:/Users/User/Desktop/do�ukan/scan/MeshroomCache/FeatureExtraction/83d16f2945df8d580d83cf06e106cd3402a428c1]
 * initialPairA = ""
 * initialPairB = ""
 * input = "C:/Users/User/Desktop/do�ukan/scan/MeshroomCache/CameraInit/ce785c521ea6ed9f17b468f0d3fda9e0c18286be/cameraInit.sfm"
 * interFileExtension = ".abc"
 * localBAGraphDistance = 1
 * localizerEstimator = "acransac"
 * lockScenePreviouslyReconstructed = 0
 * matchesFolders =  = [C:/Users/User/Desktop/do�ukan/scan/MeshroomCache/FeatureMatching/7a4045afcecdd77a28ed8eac9798b754f3d1c2e7]
 * maxAngleInitialPair = 40
 * maxNumberOfMatches = 0
 * maxReprojectionError = 4
 * minAngleForLandmark = 2
 * minAngleForTriangulation = 3
 * minAngleInitialPair = 5
 * minInputTrackLength = 2
 * minNumberOfObservationsForTriangulation = 2
 * output = "C:/Users/User/Desktop/do�ukan/scan/MeshroomCache/StructureFromMotion/5c711b84cdca05ffe5152d13cae66462b6031129/sfm.abc"
 * outputViewsAndPoses = "C:/Users/User/Desktop/do�ukan/scan/MeshroomCache/StructureFromMotion/5c711b84cdca05ffe5152d13cae66462b6031129/cameras.sfm"
 * refineIntrinsics = 1 (default)
 * useLocalBA = 1
 * useOnlyMatchesFromInputFolder = 0
 * useTrackFiltering = 1 (default)
 * verboseLevel = "info"

Loading features
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[23:45:16.494234][info] Fuse matches into tracks: 
	- # tracks: 129
	- # images in tracks: 4
[23:45:16.495235][info] TrackLength, Occurrence
[23:45:16.495235][info] 	2	129
Automatic selection of an initial pair:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[23:45:16.497235][info] AutomaticInitialPairChoice, test I: 846033875, J: 1611058250, nbCommonTracks: 60
[23:45:16.498235][info] AutomaticInitialPairChoice, test I: 154382635, J: 1094105218, nbCommonTracks: 69
[23:45:16.635243][error] No valid initial pair found automatically.

**Comment by fabiencastan** [comment]
Could you try with the sample dataset?
https://github.com/alicevision/dataset_monstree/tree/master/mini6
To see if you still have problems.

What platform are you using?

**Comment by DavePSB** [comment]
I am trying the Meshroom-2018.1.0-win7-64.zip Win 7 fix.  I found it stopped after Feature Extraction.  I believe the status was still RUNNING, but not sure.  I decided to quit and try another set of photos.  Same thing.  For some reason, I decided to restart Meshroom and open the first project, even though I didn't think that was going to work.  However, it loaded, I hit Start, and it carried immediately with the next step (Image Matching).  It wizzed up to DepthMap (farthest I've ever got), and it currently seems stuck there in the same way as Feature Extraction.  I will give it a reasonable time to complete, then plan to stop and reload/Start the project.  Not a great bug report I know, but I have not seen my "reload the failed project and start" solution before.   Win 7 Ultimate, 32Gb ram, Nvidia 980Ti (6Gb), Driver 417.35.

**Comment by NotExpectYet** [comment]
@DavePSB  I had a similar issue, and for some reason will only pass feature extraction when set to Low, not medium.

Windows 10 with Nvidia 1050ti

**Comment by DavePSB** [comment]
Thanks for the info.  I have not tried the new 2019 build yet.  However, with the last 2018 build especially for the Win7 pause problem, I found that wherever it pauses (it varies), the answer is to give it a reasonable time to complete (unfortunately depends on experienceJ and when it’s obvious it is stuck, regardless of reported status, then just stop the calculations and then just click,on the last successfully completed node.  It will generally wiz past that node and the folllowing one - the one that caused the problem in the first place - and then it will begin calculating the next node.  Usually only one or two start stops like this are required.  Like I said, I hope this has been fixed in the 2019 build, but if it hasn’t, try what I just described.

**Comment by natowi** [comment]
Did the latest build fix your problems?

**Comment by lightsrout** [comment]
Hi!

I had the same issue and I think I found a solution. It's probably to late for you but hopefully it will help other people stumbling on this thread.
My issue came from the fact that the images were in a folder with vowel mutations in the name (ä, ö etc). I removed them from the folder name and everything works perfectly now.

Hope it helps!
