### ISSUE TITLE
Crashed at Meshing

### ISSUE THREAD

**Issue by SiNScorpion79** [alicevision/meshroom#303]
I make it through the process Untill windows seems to dump the program at Meshing Here is the last part of the log hope it helps.

Nodes to execute:  ['Meshing_1', 'MeshFiltering_1', 'Texturing_1']
WARNING: downgrade status on node "Meshing_1" from Status.ERROR to Status.SUBMIT
TED
**EDIT**  I attempted a different shoot with more photos and it seems to have worked so you can disregard this.  thanks

**Comment by SiNScorpion79** [comment]
I got a windows error saying the program stopped and needed to close and it froze up.  I did a different shoot with more photos and it worked so it might have been something in the photos from the first attempt its all good thanks

**Comment by tycone** [comment]
I was able to re-produce this error with a set that meshed fine on the previous release.
