### ISSUE TITLE
Meshroom failed to start because no qt platform plugin could be initialized...

### ISSUE THREAD

**Issue by thesanatkumar** [alicevision/meshroom#304]
I am trying to run meshroom on my windows 7(64-bit) pc but the program failed to launch with following error message:
"This application failed to start because no qt platform plugin could be initialized."

PS. I am getting similar error message while trying to run Paraview.
Anybody here knows how to solve this issue?

**Comment by froginred** [comment]
I had it too, had a weird solution but it worked:
Try to move the whole folder to a different path so the new path wouldn't contain any non-ASCII characters (Only regular English)
my path used to be 
D:\<HEBREW STUFF>\BLABLABLA
now it's
C:\Meshroom-2018.1.0 
 and it works.

**Comment by thesanatkumar** [comment]
Thank you froginred.
After few hours of searching here and there, I found a different solution.
One numerical model installed in my computer had the environment variable for Qt plugin to different folder.
I deleted the environment variable and both paraview and meshroom are working now.
But I am not sure if this will affect that numerical model or not. :) :)

**Comment by martysgames** [comment]
i'm having this issue with both 2019.1.0 and 2019.2.0. i have no idea how to fix it, i tried changing the folder names but that did nothing.

**Comment by natowi** [comment]
@martysgames can you provide more details? Did you check the environment variable?

**Comment by thesanatkumar** [comment]
> i'm having this issue with both 2019.1.0 and 2019.2.0. i have no idea how to fix it, i tried changing the folder names but that did nothing.

the problem could be due to environment variables to Qt plugin assigned to different folder. You can fix it there.
