### ISSUE TITLE
Replace Meshroom´s generated mesh with clean one (From Maya or Instant Meshes )

### ISSUE THREAD

**Issue by Divelxtr** [alicevision/meshroom#308]
Hey guys,

I haven't really figured out how to change the self-made meshroom´s mesh by a cleaned one. and at same time keeping texture node working just to transfer textures to the new cleand mesh. Is there a way to do this? or maybe to added it as feature?

Thank you.

**Comment by Powerbyte7** [comment]
Hi,
This is described in the wiki [here](https://github.com/alicevision/meshroom/wiki/Texturing-after-external-re-topology)

**Comment by Divelxtr** [comment]
i can´t get it work, just get error on my Texturing node-

"ERROR:root:Error during Graph execution Error on node "Texturing_2":"

is there somthing else to care about except Coordinates and Postion / Orientation?

**Comment by Powerbyte7** [comment]
Can I see a screenshot of your texturing node?

**Comment by Divelxtr** [comment]
here is some screenshots.
![screenshot 242](https://user-images.githubusercontent.com/32413438/49699319-d3804100-fbcf-11e8-9b06-7e4f807be856.jpg)
![screenshot 243](https://user-images.githubusercontent.com/32413438/49699320-d3804100-fbcf-11e8-91a1-78ced3932a38.jpg)
![screenshot 244](https://user-images.githubusercontent.com/32413438/49699321-d3804100-fbcf-11e8-9f90-9a501834f1bb.jpg)

**Comment by Divelxtr** [comment]
Ok, it will be nice if fixed. many thanks.

**Comment by barefoots** [comment]
Just wanted to add a big thank you for providing Meshroom for free use! Great piece of software. If i had the skills I would contribute! Thank you again! Definitely looking forward to future release with this bug fixed and further documentation & tutorials by the community.

**Comment by fabiencastan** [comment]
Thanks!
