### ISSUE TITLE
Supporting (coded) Markers? 

### ISSUE THREAD

**Issue by 2d3** [alicevision/meshroom#312]
Hi! Does Alicevision/Meshroom support the processing of markers or coded targets to calculate reference points for coordinate system, scan-area or scale definition? THX for response

markers placed in the surrounding of the object ...

**Comment by fabiencastan** [comment]
AliceVision/Meshroom support CCTag markers: https://github.com/alicevision/CCTag.

CCTag is not yet provided in the pre-built binaries of Meshroom.
