### ISSUE TITLE
Full body scans

### ISSUE THREAD

**Issue by 2d3** [alicevision/meshroom#313]
Thx for recent reply! Has anyone experience with full body scans using alicevision/meshroom? How is the quality? Greets and thx for reply.

**Comment by natowi** [comment]
@massimo-tech3d #188 #270

**Comment by massimo-tech3d** [comment]
oh thanks. Indeed I see a bit of an issue with that type of solution, even if fully automated. It does remove a lot of details from the background which are very helpfull to achieve a superior camera alignment.
The best would be doing it in a similar way that Capturing Reality does. It just skips the calculations for whatever point is outside the selected volume. Not a clue how they do it, unfortunately

**Comment by natowi** [comment]
@massimo-tech3d Yes, a bounding volume is on the to-do list somewhere

**Comment by 2d3** [comment]
@hargrovecompany How does your project turn out? I still struggle with the parameter settings for reconstructing people. Especially the depthmap computation takes time. I want to reduce time as much as possible to get a fast preview of the reconstructed person. And have as little as possible of environment structures in the reconstructed model. Have you found a good working set of parameters for your scans? 
Greets 2d3

**Comment by massimo-tech3d** [comment]
@hargrovecompany you can manually focus the Pi cameras, it's tedious process but you only do it once.

**Comment by hargrovecompany** [comment]
We tried doing that...this batch had too much glue holding the lenses.  Only a couple could be manually focused without distorting the lense

**Comment by hargrovecompany** [comment]
I'm adding dslr cameras to improve texture detail.  I'm curious if anyone has suggestions as how optimize the use of the dslr images vs pi images for the actual texture.  i.e.  If I have 4 pi cameras that capture a ring on someone's hand, and they pick up very little detail, but one DSLR image captures very good detail, what algorythm determines the detail used in the texture?  If a given point is an average of those five pictures, and a small speck that shows as black in the dslr image, but shows as gold in the 4 pi images, is the texture for that point going to be an average of the color values of all 5 images?  And if that's the case, if I make 5 copies of the dslr image each with unique names to use as part of the image set, would the solution include all of them in averaging a value?   I am probably way, way off base but I have no clue how it works...

**Comment by skinkie** [comment]
@hargrovecompany wouldn't you be able to do the following. Using the Pi cams you create a rough contour for the DSLR cams to snap to. You remove the Pi cams input after the DSLR cam poses have been estimated.
