### ISSUE TITLE
Increase Generated Mesh Polycount

### ISSUE THREAD

**Issue by TheLegend368** [alicevision/meshroom#316]
Is there a way to increase the poly count of the generated mesh? It seems Meshroom is just creating the amount of poly it thinks is alright. This is fine for some assets but trying to scan a surface (Ground or concrete) it doesn't create a detailed enough mesh to get a detailed normal map from.

**Comment by fabiencastan** [comment]
As explained [in the wiki](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters), if you have enough RAM you can increase the `Max Points` parameter on the Meshing node.
You could also try to change the `Downscale` factor on the `DepthMap` node from 2 to 1 to compute the depth maps in full resolution.
