### ISSUE TITLE
No module named 'simpleFarm' 

### ISSUE THREAD

**Issue by Randal7** [alicevision/meshroom#317]
[2018-12-14 10:01:27,062][WARNING] == The following plugins could not be loaded ==
Plugins loaded: CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
simpleFarmSubmitter: No module named 'simpleFarm' 

How to solve？

**Comment by fabiencastan** [comment]
This is just a warning as explained here #114.

**Comment by alanhzh** [comment]
I had the same issue  and after I successfully run the released version, I found the message :

"Prebuilt binaries on this page are all-in-one packages including AliceVision and all required resources."

So, I assumed that meshroom need AliceVision to run:
https://github.com/alicevision/AliceVision

**Comment by natowi** [comment]
@alanhzh The Meshroom binaries include alicevision https://github.com/alicevision/meshroom/releases
Note: some features (as render farm support) are not yet included in the public release (but you could build alicevision and meshroom yourself).
