### ISSUE TITLE
Fantastic

### ISSUE THREAD

**Issue by prahjister** [alicevision/meshroom#318]
I really enjoy using this software and appreciate you publishing for everyones use. I have had the best luck so far then all the other solutions I have tried. 

Have you thought about adding a structured light scanner? You guys are using a lot of the same libraries. I have used brown universities that was published with success but it is so difficult to align the point clouds generated. 

Anyway thank you for your efforts and have a great day

**Comment by natowi** [comment]
MR 2019.1 PrepareDenseScene: New imagesFolders option to override input images. This enables to use images with light patterns projected for SfM and MVS parts and do the Texturing with another set of images.
