### ISSUE TITLE
Unable to upload images

### ISSUE THREAD

**Issue by Stiui** [alicevision/meshroom#322]
Hi All,

I just installed Meshroom on my Windows 10. When I open it everything looks fine, but when I drag and drop my picture in the programme nothing happens and I get this message:

03bd822aa3d98acd3185af7e6a65750fcd4/cameraInit.sfm'

This is the log as soon as I open Meshroom:

Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, ExportUndistortedImages, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[QtOIIO] Plugin Initialized
[DepthMapEntity] DepthMapEntity
Failed to download scene at QUrl("")

Any idea on why I can't upload any picture? I tried different formats and dimensions but always obtained the same result.

Thank you in advance,

Stiui

**Comment by hargrovecompany** [comment]
I'm brand new to the software, but ran into the same issue.  The camera type that I used was not in the camera database db file in the software.  I downloaded a set of test images from a website, and they dropped straight into the software perfectly.        If you drill down into the files, you'll find the camera database, and you can open it with a text editor to see if your camera type is listed.  If the photos were taken by someone else and you don't know the camera type, search for a website that checks EXIF info.  Drop an image into the page on the website and it will give you the information you need.

**Comment by hargrovecompany** [comment]
Actually, my reply above might be incorrect.  If you're saying the images simply don't load into the software, I ran into that as well.  I believe the exif info in the images was bad, but I'm sorry, I don't recall.  Regardless, when I used images with good exif info, from a canon camera that is listed in the camera db, the problem didn't exist.

**Comment by Stiui** [comment]
Thanks for the replies. I tried to install "Bad Peggy" but with no results. The programme says the photos are fine.
I tried to add my sensor in the list but no luck with that as well. I have a Samsung S8 and I looked up on devicespecifications.com finding it has a Sony IMX333 RS. I then added this line "Sony;Sony IMX333 Exmor RS;4.25" but nothing happened and I got the same line in the log. The sensor width was not specified on the website so I looked around and found that value. Maybe it's not the correct one?

**Comment by Stiui** [comment]
I even tried to copy/paste the updated list of sensor from github but with no results. Same error. =(

**Comment by Stiui** [comment]
I had a look at the exif data and used those values to add the camera in the database but I got the same result. Is there any "test image" I could downoad to see if it's just a problem of compatibility with my phone?

**Comment by fabiencastan** [comment]
You can test with this dataset: https://github.com/alicevision/dataset_monstree

**Comment by lantisswe** [comment]
I have the exact same problem, i have found all the information on my camera my phone is useing and have put the info in camerasensor.db but im pretty sure i do somthing wrong. Can some one pls help me with the code line? =) 

Info links
https://www.umidigi.com/page-umidigi_f1play_specification.html
https://www.samsung.com/semiconductor/image-sensor/mobile-image-sensor/S5KGM1/

**Comment by natowi** [comment]
@lantisswe you need to make sure model and make in the sensor db are the same as in your image metadata. If you still need help, please attach a sample image.

**Comment by lantisswe** [comment]
@natowi 
The line i wrote was Umidigi;Umidigi F1;4.7;devicespecifications and that´s the information i found in the metadata. https://www.get-metadata.com/result/252de0c4-baa5-44f2-bdce-03ac5ed19e12

Here is the link to the picture i uploaded: 
https://www.dropbox.com/s/krt2scdq5ztbojt/IMG_20190701_182351_9.jpg?dl=0

**Comment by natowi** [comment]
Umidigi;F1;4.7;devicespecifications should do the trick.
Tip: Your object is extremely difficult to reconstruct (reflective+single coloured). [This might help](https://www.instructables.com/lesson/Shooting-for-Photogrammetry/)

**Comment by lantisswe** [comment]
@natowi 
`Umidigi;F1;4.7;devicespecifications` diden´t help :/ When i upload pictures Meshroom shows a blue loading bar for 0.2 sec and nothing happens. 
I  downloaded some picures for a meshroom tutorial and they didn´t work eather... can i find a error log or something? 
Meshrooms cmd window show `9571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm'`

**Comment by natowi** [comment]
Do you run Meshroom as admin? If yes, that's the cause. Windows disables drag and drop on applications being run as admin.

Also avoid special characters/non-ASCII characters in Meshroom and images file paths.

You can find a log in the Meshroom cli in the background and when you click the CameraInit node, on the right there is the Log tab.

**Comment by lantisswe** [comment]
@natowi
I don't run Meshroom as a administrator

I have tried to rename some images to simpel names like test1 etc and put them in simple paths like d:/meshroomtest

**Comment by natowi** [comment]
System specs are good, but should not affect the image import.
I was able to load your sample image without problems, so I do not know what went wrong. Posting the log file would be useful.

**Comment by lantisswe** [comment]
I added `Umidigi;F1;6.4;devicespecifications` in the db and nothong changed, i took a look at the log and its empty... then i added a whole folder under Live reconstruction and it added the pictures to the program when i hit the start button, the pictures had a red dot in the corner... it was the same thing when i added the tuturial pictures.

**Comment by natowi** [comment]
![import-image](https://user-images.githubusercontent.com/8138537/60524598-272db580-9ced-11e9-8c2f-a590800e9e82.jpg)
In case this window does not change, it sometimes helps to switch to the CLI in the background, click into the window and hit enter. This should resume the import.

Without a log or screenshot I can not provide more help, as your image works for me:
![im111](https://user-images.githubusercontent.com/8138537/60524955-cfdc1500-9ced-11e9-8e4d-37fe05bf23ca.jpg)

**Comment by lantisswe** [comment]
This is how it look when i import pictures throw the folder under Live reconstruction and the log is empty.
![meshroomprint](https://user-images.githubusercontent.com/52416695/60535274-06248f00-9d04-11e9-8de9-19a40c8821dd.png)

this is the statics log:
[statistics.txt](https://github.com/alicevision/meshroom/files/3351693/statistics.txt)
this is the status log
[status.txt](https://github.com/alicevision/meshroom/files/3351696/status.txt)

**Comment by natowi** [comment]
You need to check which metadata is missing in the EXIF and provide the missing information
![missing](https://user-images.githubusercontent.com/8138537/60547254-7c82ba80-9d1f-11e9-92fb-0ef6b62d2475.png)

**Comment by lantisswe** [comment]
So weard, i gave it up for a while and reinstalled windows on my pc then i gave meshroom a try again and it worked at thd first try

**Comment by natowi** [comment]
@lantisswe is the issue solved?

**Comment by lantisswe** [comment]
Yeah It runs perfect. Thankyou again for all the help

**Comment by mvdstelt** [comment]
Hi,

i try to upload images but got issues with that. Hope to resolve that so I can use this great software.
I am Using a machine with Fedora 29, with a Xfce Desktop environment.
I installed Meshroom and AliceVision using the folling guide:
https://meshroom-manual.readthedocs.io/en/stable/install/linux/linux.html
I also updated the camerasensor.db file with:
https://github.com/alicevision/meshroom/wiki/Add-Camera-to-database

When running and try to drop images in the picture area of Meshroom I immediately with an error "You probably have a corrupt image within the images that you are trying to import."
I think there is anissue with the installation, and/or some plug-in issue.
Maybe you are able to pint-point. Thanks in advance.
![Screenshot_2020-04-26_18-11-38](https://user-images.githubusercontent.com/64353614/80304681-2e78ff00-87ea-11ea-88ff-8a5341774a5a.jpg)


The Terminal gives the following warning:
"QQmlComponent: Created graphical object was not placed in the graphics scene."

**Comment by natowi** [comment]
@mvdstelt Try again using this dataset https://github.com/alicevision/dataset_monstree
If this does fail, there is something wrong with your images https://github.com/alicevision/meshroom/wiki/Images-cannot-be-imported

**Comment by natowi** [comment]
@mvdstelt here is the latest guide https://meshroom-manual.readthedocs.io/en/latest/install/linux/linux.html

**Comment by mvdstelt** [comment]
Also to mention. I used raw pjg pictures from my Sony FDRX3000 action cam
(in photo mode) as well as converted pictures to png (using the Digikam
Linux app). As well as the 6 test tree pictures from AliceVision website
and pictures from my Samung Note 5. All occasions give the same error.

Kind regards and thanks,
Machiel van der Stelt
https://stelt-technologies.com.au/
Short stories by Machiel
<https://archive.org/details/@machiel_van_der_stelt>

**Comment by natowi** [comment]
@mvdstelt The AliceVision Monstree dataset should work, so there is probably something wrong with your installation. Please follow the updated guide I linked before and try again.
