### ISSUE TITLE
Skip the Texturing Node

### ISSUE THREAD

**Issue by FletcHRUSA** [alicevision/meshroom#324]
Thank you very much for providing this software, you're hard work is clear and I appreciate it very much!

I want my model mesh but do not care about the textures. I also think it would save a lot of time calculating if I can skip the texturing of the mesh. Can anyone help me with steps how to do this?

Is the depth mapping part of the texturing or part of building the mesh itself - if it's only needed for the texturing portion of the process, how can I skip that part?

**Comment by FletcHRUSA** [comment]
Thank you, is the depth mapping portion required to create the mesh or is it for creating the depth map for the texturing? As a 3D artist, Depth Map has a specific meaning to me, I think in this case it means something else...

**Comment by FletcHRUSA** [comment]
So I simply delete that last Texturing node, it's that simple?

**Comment by natowi** [comment]
Here some background on [Depth mapping](https://alicevision.github.io/#photogrammetry/depth_maps_estimation). The depth mapping node is used for mesh generation and texturing.

**Comment by FletcHRUSA** [comment]
Thank you!
