### ISSUE TITLE
Meshroom frozen at Depthmap step

### ISSUE THREAD

**Issue by arnoldpredator** [alicevision/meshroom#326]
Hello my friends. 

THis is my story with Meshroom. I made 534 pictures of an statue and I have been able to make it work with 300 pictures. With the whole 534 I think I don't have enough memory to do it but I expected it to work maybe with 400. 

I have tried and it crashed, I would like to understand why and what is the maximum number of pictures I can handle on my computer. I upload the log file of the last step before crashing.

[71.log](https://github.com/alicevision/meshroom/files/2690106/71.log)

**Comment by fabiencastan** [comment]
You could have memory issues on the Meshing node (in that case, you can reduce the "Max Points" as explained [here](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters).

You sent the log of the DepthMap but I don't see any error in the log.
On which node do you have an error?

**Comment by natowi** [comment]
@arnoldpredator You did not provide any information on your hardware, but for _larger_ datasets you should have _at least_ 32gb-64gb ram.

**Comment by arnoldpredator** [comment]
Thanks guys. 

I have an intel xeon with 6 cores at 3ghz and an nvidia quadro p600, I have 16gb of memory. 
Fabien at step 72 of 161 in the depthmap it stoped, normally it takes 6 to 8 minutes to calculate one step and it has been there for hours so the last log file is that one at the previous step.

**Comment by natowi** [comment]
@arnoldpredator [DepthMap node too slow](https://github.com/alicevision/meshroom/wiki/DepthMap-node-too-slow)

**Comment by arnoldpredator** [comment]
> @arnoldpredator [DepthMap node too slow](https://github.com/alicevision/meshroom/wiki/DepthMap-node-too-slow). 16gb? I´d recommend you to upgrade the memory.

Well, I am going to try to download the quality as you suggest. 

I am very poor to be honest :) but I will consider it.

**Comment by shawnngtq** [comment]
@arnoldpredator , could you share what's the maximum number of photos the software can handle? I am unable to find this piece of info.

Would be great if you already have a blog / doc about this. Thanks!

**Comment by fabiencastan** [comment]
There is no specific limit in number of images that the software can use.
The only limit is the number of 3D points you can create on the Meshing node depending on your amount of RAM.

**Comment by natowi** [comment]
@shawnngtq 
At the moment the GPU computation is not fully optimized, so many modern GPUs won´t be fully utilized https://github.com/alicevision/meshroom/wiki/GPU-usage. Having enough RAM is important as not having enough for your project limits the reconstruction quality (image resolution, downscale factor).

Example: Meshing

If you have less than 16G of RAM, you will need to reduce the Max Points to fit your RAM limits. You may also augment it, to recover a more dense/precise mesh.
