### ISSUE TITLE
Improvements: Live Reconstruction

### ISSUE THREAD

**Issue by natowi** [alicevision/meshroom#327]
- when stopping _Live Reconstruction_, re-route last SFM node to default pipeline (PrepareDenseScene->Texturing)

- copy node settings from initial nodes and use them in new nodes added for _Live Reconstruction_

#102 --> partial auto-layout

**Comment by albmef** [comment]
Hi @natowi 
how do you copy settings between nodes while doing live reconstruction ?
regards,
A

**Comment by natowi** [comment]
You can can not add nodes while live reconstruction is in progress, but you can right click on a node and copy/copy from here
This issue is from 2018 and outdated, Meshroom behaves differently now
