### ISSUE TITLE
problems opening jpeg files

### ISSUE THREAD

**Issue by massimo-tech3d** [alicevision/meshroom#332]
hello,
I stumbled in the following issue: datasets captured with raspberry camera, the jpg photos opens correctly on linux, they do not read correctly on windows 10. Every photo is reported as "Corrupt JPEG data: premature end of data segment".
This happens with *every* jpeg dataset captured from raspberry camera: OK on linux, NOK on win.
The jpgs are ok and correctly read by any other photogrammetry application (on windows), therefore the issue must be with the windows version of meshroom jpeg parser.

attaching one photo as example
![cam-5-15](https://user-images.githubusercontent.com/23615524/50487967-8d651300-0a00-11e9-8eaf-fbbdb443ef85.jpg)

kind regards
Massimo

**Comment by natowi** [comment]
Read this wiki page: [Images-cannot-be-imported](https://github.com/alicevision/meshroom/wiki/Images-cannot-be-imported)

**Comment by massimo-tech3d** [comment]
thanks a lot !

**Comment by massimo-tech3d** [comment]
By the way, fixing the jpegs as described in the wiki works fine when MeshRoom is running on windows. What puzzles me is that this is not necessary (same photoset) when MeshRoom is running on Linux. Heck, if the jpeg is broken, then it should be broken regardless of the OS.

Great software anyway :-)
