### ISSUE TITLE
Mesh Problem

### ISSUE THREAD

**Issue by 200sx200** [alicevision/meshroom#333]
Hi, I'm Martin :)

First of all sorry for my bad english

I started the 3d scan at the beginning of the week and unfortunately I'm going around in circles :(

So I went on a simple form, "StructureFromMotion" gives a result not too bad: 
<a href="http://fr.tinypic.com?ref=24d3skg" target="_blank"><img src="http://i66.tinypic.com/24d3skg.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

But when it goes in mesh, on all models tested, the mesh is just a plane (more or less).
Mesh result:
<a href="http://fr.tinypic.com?ref=260shp4" target="_blank"><img src="http://i65.tinypic.com/260shp4.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

Thanks,

**Comment by fabiencastan** [comment]
Hi Martin, Hi Joshua,
Uncheck the option "Keep Only the Largest Mesh" in the "MeshFiltering" Node.
In the coming release, this will become the default value.

Same issue than #359.

**Comment by fabiencastan** [comment]
great!

**Comment by 200sx200** [comment]
Thanks
