### ISSUE TITLE
Can we have a more recent build for the new year? (features, bugfixes, etc...)

### ISSUE THREAD

**Issue by juangea** [alicevision/meshroom#334]
That´s it, the current build is dated from August 9th, a new updated build with some new features that could have been implemented (like a better texturing system) and, I´m sure, a lot of bugfixes, could be VERY welcome :)

Thanks!

**Comment by fabiencastan** [comment]
Yes, I agree. The new release is planned for the coming weeks.

**Comment by juangea** [comment]
Awesome :)

Thanks!

**Comment by gerroon** [comment]
thanks

**Comment by juangea** [comment]
How is this going? :D

**Comment by fabiencastan** [comment]
It's getting closer and closer:
https://github.com/alicevision/AliceVision/pull/584
