### ISSUE TITLE
Is there a graph design specifically for room scanning?

### ISSUE THREAD

**Issue by sirisian** [alicevision/meshroom#337]
I haven't seen anyone try this, so I took 2,000 4000x4000 high resolution images of a room. They all overlap by a decent amount capturing most of the details of the room. When I run Meshroom with the default settings up to the "Structure from Motion" step it seemingly picks only around 5 pictures and generates part of a wall.

The data set clearly has images that are adjacent to these 5 pictures. The quality of them are also really high with a lot of distinct features that should anchor the algorithm easily.

Is the default graph designed to aggressively remove "background" information and thinks the room is background data? Basically I need a graph that generates every point cloud point possible.

**Comment by natowi** [comment]
Read [this wiki page](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters)

**Comment by sirisian** [comment]
It took about 30 days to run feature matching, but I got the same result. In the structure matching it only uses 11 images of the 2,000. Interestingly it's the same 11 images as when it's ran naively. It seems to fixate on those 11 images ignoring other images that are next to those images. Sounds like a complicated bug maybe.

I'll wait a year and try again with new images. Maybe it'll be optimized by then to run with larger datasets.

**Comment by natowi** [comment]
I had similar problems with large datasets. There can be multiple causes for this issue. When I have some time, I will look into it. You could try to split your project dataset into parts using the Augment Reconstruction drop field and merge the reconstructed SFM nodes.

**Comment by natowi** [comment]
There will be a new version soon, which might fix this problem.
