### ISSUE TITLE
Camera not in sensors.A1 VFD 720

### ISSUE THREAD

**Issue by ivankuzev** [alicevision/meshroom#341]
I could not find the sensor width for this camera to add it in the CameraSensors.db
Can something be done?Like figuring out the thing experimentally?

**Comment by natowi** [comment]
Many camera sensors in phones have a sensor width of ~4-6mm, so give 6mm a try.
You can [calculate/approximate](http://vfxcamdb.com/film-back-calculator/) or [Link2 ](http://www.ni.com/product-documentation/54616/en/)the sensor width using a reference image. The CameraCalibration node in Meshroom will be available in the future.

**Comment by ivankuzev** [comment]
For now i tried adding it with 6.4 mm it seems to work best(for my image sequence at least). looking forward to the addition of new features

**Comment by ivankuzev** [comment]
Is the CameraCalibration  node operational? and how to use it?

**Comment by natowi** [comment]
CameraCalibration is not operational in the Meshroom 2018.1 build due to missing dependencies.
