### ISSUE TITLE
All steps completed without errors, but 3D Viewer remains empty and no files are written.

### ISSUE THREAD

**Issue by RuudGiddance** [alicevision/meshroom#342]
Any idea what's wrong?

![meshroom](https://user-images.githubusercontent.com/46442174/50761597-5c58ce00-129d-11e9-9cf0-5bea22fe1503.jpg)

**Comment by natowi** [comment]
Click on the Load Model Button. (Check the log to see if enough features were reconstructed)

**Comment by RuudGiddance** [comment]
Thank you for your reply.
I forgot to mention that the Load Model button does nothing. The logs state that both textures and mesh have been created, but still the folders are empty.

**Comment by dominik098** [comment]
I have the same problem. All steps are complited and 3D view reamins nothing after whole process.  Did you find any solution for this problem?

**Comment by RuudGiddance** [comment]
In my case it was Comodo (antivirus program) that was running Meshroom "inside the container". Meshroom worked great after I cleared that.


    On Friday, 15 February 2019, 4:09:45 pm GMT+7, dominik098 <notifications@github.com> wrote:  
 
 
I have the same problem. All steps are complited and 3D view reamins nothing after whole process. Did you find any solution for this problem?
