### ISSUE TITLE
How to use only parts of the photogrammetry pipeline?

### ISSUE THREAD

**Issue by nekojan** [alicevision/meshroom#347]
For example, I'd like to only get the DepthMapFilter output, and not continue on to the meshing and texturing.

**Comment by fabiencastan** [comment]
Hi,
You can right click on the DepthMapFilter node and select "Compute", and it will compute all the nodes required to finalize this node.
When the computation is done, you can right click on the DepthMapFilter node and select "Open Folder" or add a "Publish" node to copy the results into another folder.
Does that answer your question?

**Comment by nekojan** [comment]
Hi. Yes, thank you. That's very convenient :)

Is there a way to do this from the command line too?  (i.e. specify the nodes I want to use and their parameters)

**Comment by sunil1239** [comment]
> Hi. Yes, thank you. That's very convenient :)
> 
> Is there a way to do this from the command line too? (i.e. specify the nodes I want to stop the process)
> 
> Edit: I find that I could change default parameters by going to \meshroom\nodes\aliceVision, I still couldn't figure out how not to run the whole default pipeline though (using command line to run Meshroom).

Yes you can do that by using --toNode argument (ie.,... --toNode DepthmapFilter ...) in commandLine but those files will only be in the cache files. This command will not copy files to you output folder. You need to check it manually in the <temp>/MeshroomCache/

**Comment by nekojan** [comment]
Thank you.
