### ISSUE TITLE
CUDA not CUDA?

### ISSUE THREAD

**Issue by Dejv311** [alicevision/meshroom#351]
Hi there,
well I tried making some cool stuff in meshroom, but it would seem that my NVIDIA GeForce GTX 645 does not support CUDA, which it obviously should, even compute power 3.0. But that is my opinnion, the log file does not thing so.
[0.log](https://github.com/alicevision/meshroom/files/2751890/0.log)
The program gets stuck in the depth map phase. Any help would be greatly appreciated.

This should be somewhat my card:
https://www.techpowerup.com/gpu-specs/geforce-gtx-645-oem.c2359

But here is what I actually have:
https://support.hp.com/id-en/document/c03957842

**Comment by fabiencastan** [comment]
That's strange. We will release a new version soon that will print more information. This may enable to understand what's going on.

**Comment by Dejv311** [comment]
Please let me know, when it is released. Also the "first part" until the depth map took really long (about an hour), which should be much faster, shouldn't it? Is it possible that meshroom for some reason decided to use integrated graphics chip?

**Comment by fabiencastan** [comment]
That's maybe the problem on the depth maps, even I don't see why... The previous steps are all cpu in the current release.
How much images did you have in input?

**Comment by Dejv311** [comment]
Somewere about 270 images at 16 Mpx resolution

**Comment by eAddict** [comment]
Same thing here..  I have a GT640 and according to Nvidia the score is high enough for the program requirements

![screenshot_1](https://user-images.githubusercontent.com/24842943/52376048-c42e4000-2a26-11e9-863f-e4a077e21224.png)
![screenshot_2](https://user-images.githubusercontent.com/24842943/52376058-c7293080-2a26-11e9-9a59-2de26d2ff5a8.png)
