### ISSUE TITLE
camera not calibrated in structure from motion step

### ISSUE THREAD

**Issue by willm1075** [alicevision/meshroom#355]
i have tried scanning a mug, a kettle and a chair in meshroom and every time only 2 or 3 of my photos are calibrated on this step therefor the model doesn't  complete. the images 
![Uploading DSC_0478.JPG…]()
![Uploading DSC_0479.JPG…]()
![Uploading DSC_0480.JPG…]()
![Uploading DSC_0481.JPG…]()
![dsc_0483](https://user-images.githubusercontent.com/46696673/51151575-8a529980-18bf-11e9-9ed7-480168cb4cec.JPG)
![dsc_0484](https://user-images.githubusercontent.com/46696673/51151576-8a529980-18bf-11e9-9abc-e2dbf3192dce.JPG)
![dsc_0485](https://user-images.githubusercontent.com/46696673/51151577-8aeb3000-18bf-11e9-8824-ca4fdb7fcd8d.JPG)
![Uploading DSC_0470.JPG…]()
![Uploading DSC_0471.JPG…]()
![Uploading DSC_0472.JPG…]()
![Uploading DSC_0473.JPG…]()
![Uploading DSC_0474.JPG…]()
![Uploading DSC_0476.JPG…]()
![Uploading DSC_0477.JPG…]()

are attached below

**Comment by hargrovecompany** [comment]
Are you using a flash?  I think you'll get better results with stationary lighting.  You have shadows in different location on different pictures.
