### ISSUE TITLE
My object (a person) is missing from the mesh but visible in Sfm

### ISSUE THREAD

**Issue by mrdanjohnson** [alicevision/meshroom#359]
After the rendering is finished, my subject is clearly seen in the 3d viewer, but in the final mesh they are missing and only the ground an background remain. In the 3d viewer, the entire model exists in when Sfm is selected, but missing if only mesh is selected.

**Comment by fabiencastan** [comment]
Uncheck the option "Keep Only the Largest Mesh" in the "MeshFiltering" Node.
In the coming release, this will become the default value.

**Comment by natowi** [comment]
I had the same problem, so I removed the MeshFiltering Node, optimized the [reconstruction parameters](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters) and the DepthMap node settings for my dataset.

I will include tips on how to optimize the settings to get better results for some image sets in the documentation.

Example:
![improvements](https://user-images.githubusercontent.com/8138537/51330866-b5341d80-1a78-11e9-8617-fdb987be2dfb.JPG)

**Comment by fabiencastan** [comment]
You should not remove the MeshFiltering, it's important for the final quality.
You should just unckeck the option "Keep Only the Largest Mesh".

**Comment by natowi** [comment]
@fabiencastan Thank you, I´ll keep that in mind.
