### ISSUE TITLE
better Texture resolution

### ISSUE THREAD

**Issue by maddsketch** [alicevision/meshroom#362]
hello, i've been trying out scanning small objects like weed buds 3"-4" sizes in length. as expected the resolution is fairly low but ive tried to use 45mp, with a 88 to 100 macro lenses and i still somewhat get the same results. is there a way to get more resolution out of my textures with this?

**Comment by ChemicalXandco** [comment]
In the *Texturing* node set `Texture Downscale` to 1 instead of 2. That will get you the maximum possible resolution with the resolution of your images.

**Comment by fabiencastan** [comment]
Does that answer your question @maddsketch? If yes, you can close the issue.

**Comment by maddsketch** [comment]
oh sorry about that, yeah i guess that's the best it can do. i was curious if it can be sharper but oh well. thank you yeah i'll close the issue now.
