### ISSUE TITLE
Can't download Windows version

### ISSUE THREAD

**Issue by jumpjack** [alicevision/meshroom#363]
I downloaded the Windows version 3several times, each times downoad stops around 200MB and can't be resumed. It can't be resumed also if I manually pause it after a few MBs.
Can this be fixed?

Using Chrome and Win10.

**Comment by ChemicalXandco** [comment]
This is not related to meshroom but the download works fine for everyone else. If you have problems with your internet try using a download manager like [XDM](http://xdman.sourceforge.net/) which allows you to resume any time.

**Comment by jumpjack** [comment]
Chrome has a download manager embedded, I often use it to pause and restart large downloads, but it looks like it is not working properly on github, also with other projects.
Anyway I was eventually able to download the zip file... after 5 attempts ( 1GB download for 200MB...)

**Comment by MikeA2019** [comment]
Hi,
Yes, I have the same issue, I have just blown a gig of my data download trying to download the windows version. I am also using Chrome and its download manager.

**Comment by natowi** [comment]
@ChemicalXandco @fabiencastan  https://www.fosshub.com/ would be a suitable mirror page for Meshroom releases.

**Comment by FossHub** [comment]
@ChemicalXandco @fabiencastan @natowi as far as I know, other projects reported similar issues in the past. Example: https://forum.shotcut.org/t/unable-to-download/3771/9 or https://forum.shotcut.org/t/failed-forbidden-while-downloading/6647/2

As you can see, the result was this: https://shotcut.org/download/

Our bandwidth is premium (worldwide coverage) which means we have a 100% uptime SLA so you shouldn't expect any issues with us.

Open Source and generally free, clean projects are welcome!

**Comment by oussama04** [comment]
i just cant download the windows meshroom version it always stops before the download is complet i tried chrome download ,XDM download and same thing 
i thaught i should maintion that i dont have Nvidia as graphic card instead i have Intel HD graphic 
anyone could help
thanks i really need this free software

**Comment by ChemicalXandco** [comment]
@MikeA2019 @oussama04 to help users struggling to download meshroom I am seeding the meshroom 2018.1.0 files through torrent for a few days which should be more stable then github.  The torrent files are available on [dropbox](https://www.dropbox.com/sh/ez8iod7qd66aewf/AAB2cWpso64ovkbWP-t1znoea?dl=0) and you can use [qBittorrent](https://www.qbittorrent.org/download.php) to download it. I hope this helps you.

**Comment by oussama04** [comment]
thanks a lot ChemicalXandco it realy helps me

Le mar. 19 févr. 2019 à 15:00, ChemicalXandco <notifications@github.com> a
écrit :

**Comment by MikeA2019** [comment]
Yes,  thank you very much. 

⁣Get BlueMail for Android ​
