### ISSUE TITLE
Meshroom making flat models...

### ISSUE THREAD

**Issue by BhagavadGitHub** [alicevision/meshroom#365]
So I have tried using 3 different cameras. Iphone 7, Samsung J7, and Canon Rebel SL1. Everytime I try to create a model it turns out flattish and nothing like the object. I am running windows 10 with a GeForce GT 710 2GB card. I don't move the object but walk around taking pictures far away and gradually get closer. Any help would be appreciated.
![structurefrommotionpreview](https://user-images.githubusercontent.com/46541178/51569355-5fd18500-1e59-11e9-9076-cbc45cca5a0f.JPG)

**Comment by fabiencastan** [comment]
Hi,
A similar question has been asked regarding the Meshing:
https://github.com/alicevision/meshroom/issues/359

But here it seems to be directly on the SfM, isn't it? Could you put one of your input image to get a better understanding of what you are trying to do and what can be the problem?

**Comment by BhagavadGitHub** [comment]
![img_8362](https://user-images.githubusercontent.com/46541178/51570955-dd978f80-1e5d-11e9-8601-b7afa964d553.JPG)
![20190103_123319](https://user-images.githubusercontent.com/46541178/51570970-e7b98e00-1e5d-11e9-8ed5-ae1969dd7916.jpg)
![img_0554](https://user-images.githubusercontent.com/46541178/51570981-f2742300-1e5d-11e9-812f-3e33487bf74d.JPG)
Here are the 3 images I tried to scan. The SFM screenshot in my first post is from the fan. I know there is a bit too much sun but all meshes come out super flat. I unchecked the "Keep Only the Largest Mesh", but like you said, I haven't gotten to this node yet in the preview. After I run the full construction it turns out similarly flat.

**Comment by BhagavadGitHub** [comment]
![test3sfm](https://user-images.githubusercontent.com/46541178/51571345-2c91f480-1e5f-11e9-92a7-727d366a767c.JPG)
Here is a SfM screenshot from the silica bead jug.

**Comment by BhagavadGitHub** [comment]
![test3texture](https://user-images.githubusercontent.com/46541178/51571777-66afc600-1e60-11e9-9821-aef7e455188e.JPG)
Ok, so I decided to start a full mesh of the silica bead jug and it is significantly better after the unchecked the "Keep Only the Largest Mesh" option. Still pretty rough though.

**Comment by natowi** [comment]
@BhagavadGitHub Your objects are not easy to reconstruct, because they have a smooth, single coloured surface. You can tweak some node parameters to get better results. I´d recommend you to use another object for your test reconstructions (a small rock, tree trunk or a dirty old [flowerpot](https://github.com/natowi/dataset_flowerpot)).
