### ISSUE TITLE
Meshing on Linux Mint fills up Memory and freezes OS

### ISSUE THREAD

**Issue by zweutisiouz** [alicevision/meshroom#368]
It crashed in "Maxflow: add edges." step. [log ](https://github.com/alicevision/meshroom/files/2787363/default.log)
Specs:
AMD A8 7600
Nvidia 1050 ti
8GB Ram
msi A68HM Granade Motherboard

Linux Mint 19.1
nvidia drivers 415.27
Kernel 4.15.0-43-generic
Meshroom 2018.1.0

**Comment by RussellGrew** [comment]
See general advice regarding meshing on machines with < 16 GB memory

https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters
