### ISSUE TITLE
 trouble at Depthmap step

### ISSUE THREAD

**Issue by a511344** [alicevision/meshroom#370]
I have tried change the `Downscale' setting to 1 . But no success. how can I??
[124.txt](https://github.com/alicevision/meshroom/files/2790200/124.txt)

**Comment by natowi** [comment]
The answer is in your error log: [11:54:41.413540][error] This [program needs a CUDA-Enabled GPU](https://github.com/alicevision/meshroom/wiki/Error:-This-program-needs-a-CUDA-Enabled-GPU...) (with at least compute capablility 2.0).

**Comment by a511344** [comment]
how can I do?

**Comment by natowi** [comment]
You need a NVIDIA graphic card or have to wait for the next release as described in the wiki.

**Comment by AndreaMonzini** [comment]
related to https://github.com/alicevision/AliceVision/issues/439

**Comment by a511344** [comment]
Thank you !
