### ISSUE TITLE
ERROR: unrecognised option '--allowIncompleteOutput'

### ISSUE THREAD

**Issue by fishcu** [alicevision/meshroom#371]
I'm running into this problem when trying to drop a folder of images into the meshroom GUI:
```LD_LIBRARY_PATH=/usr/lib/nvidia-410 PYTHONPATH=$PWD python meshroom/ui
Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[2019-01-24 16:25:43,742][WARNING] == The following plugins could not be loaded ==
  * simpleFarmSubmitter: No module named simpleFarm

ERROR: unrecognised option '--allowIncompleteOutput'
Usage:

AliceVision cameraInit:

Required parameters: [...]
```

I'm running Ubuntu 16.04, with nvidia 410 drivers.
meshroom is on latest develop commit (efed2c649922ce5d4928e11ccc4f7e579de3b616), and alicevision is on latest develop commit (48fb766417f0a2609b6a6dd099f86c822ceb4ba1) as well.
Are these current commits incompatible? Which could I check out that are compatible?

**Comment by fishcu** [comment]
I have tried checking out v2018.1.0 for meshroom, and v2.0.0 for AliceVision. Haven't gotten it to compile yet.

**Comment by fishcu** [comment]
Meshroom works in the version combination mentioned above.

**Comment by yann-lty** [comment]
#369 has been merged
