### ISSUE TITLE
CameraInit node error

### ISSUE THREAD

**Issue by bluecd** [alicevision/meshroom#372]
Win10 64 w/CUDA, error on import images/does not import/ and processing/if loaded Meshroom project. Env. variables for AliceVision root, cameraSensors.db and voctree set systemwide.

`D:\Programowanie\meshroom>set PYTHONPATH=%CD% && python meshroom/ui
Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[2019-01-24 20:52:55,114][WARNING] == The following plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

'aliceVision_cameraInit' is not recognized as an internal or external command,
operable program or batch file.
[2019-01-24 20:53:53,493][ERROR] Error while building intrinsics : Traceback (most recent call last):
  File "D:\Programowanie\meshroom\meshroom\ui\reconstruction.py", line 386, in buildIntrinsics
    views, intrinsics = cameraInitCopy.nodeDesc.buildIntrinsics(cameraInitCopy, additionalViews)
  File "D:\Programowanie\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 132, in buildIntrinsics
    subprocess.returncode, cmd)
RuntimeError: CameraInit failed with error code 1. Command was: "aliceVision_cameraInit  --sensorDatabase "D:\Programowanie\AliceVision\build\Windows-AMD64\Release\share\cameraSensors.db" --defaultFieldOfView 45.0 --verboseLevel info --output "C:/Temp/tmpltsgxv3u/CameraInit/2731003bd822aa3d98acd3185af7e6a65750fcd4/cameraInit.sfm" --allowSingleView 1  --input "C:\Temp\tmpltsgxv3u/CameraInit/2731003bd822aa3d98acd3185af7e6a65750fcd4//viewpoints.sfm" --allowIncompleteOutput 1"`

**Comment by kai04420** [comment]
I have the same error too,do you fix this problem?

**Comment by Aymdr** [comment]
I have met this problem, how to solve it

**Comment by fabiencastan** [comment]
Are you using the release binaries??
Where is the AliceVision binaries installed? Could you check where the file "aliceVision_cameraInit.exe" is located on your filesystem?

**Comment by ethansu1992** [comment]
Hi, I am facing the same problem. However i am trying to run the meshroom-develop codes and i am facing the issue on this too.

'aliceVision_cameraInit' is not recognized as an internal or external command,
operable program or batch file.

I do not see any "aliceVision_cameraInit.exe" in the develop version.

**Comment by natowi** [comment]
@ethansu1992 

> I do not see any "aliceVision_cameraInit.exe" in the develop version.

Did you build alicevision and placed the files in the alicevision/bin folder?

**Comment by ethansu1992** [comment]
Hi Natowi,

I followed through the steps through the building of the aliceVision, i dont get the .exe file do you think if it were to put the downloaded aliceVision_cameraInit.exe file from the program, do you think it will work?

**Comment by natowi** [comment]
Using a Meshroom dev build with the alicevision binaries provided by the official release can cause incompatibility issues, so you should use the latest alicevision binaries.

We now have pre-build Snapshots you can use. Please read this for details: https://github.com/alicevision/AliceVision/wiki/Windows-Snapshot-Builds
