### ISSUE TITLE
DOESNT COMPLETE PROCESS

### ISSUE THREAD

**Issue by utkarsh7227** [alicevision/meshroom#373]
![mouse problem](https://user-images.githubusercontent.com/47073924/51798119-4b173780-2233-11e9-8364-ccc9375210a7.jpg)

**Comment by utkarsh7227** [comment]
* minAngleForLandmark = 2
 * minAngleForTriangulation = 3
 * minAngleInitialPair = 5
 * minInputTrackLength = 2
 * minNumberOfObservationsForTriangulation = 2
 * output = "C:/Users/UTKARSH/Documents/MeshroomCache/StructureFromMotion/6c6687
31d079f5f00b7be573ba5ebff706db3d6d/sfm.abc"
 * outputViewsAndPoses = "C:/Users/UTKARSH/Documents/MeshroomCache/StructureFrom
Motion/6c668731d079f5f00b7be573ba5ebff706db3d6d/cameras.sfm"
 * refineIntrinsics = 1 (default)
 * useLocalBA = 1
 * useOnlyMatchesFromInputFolder = 0
 * useTrackFiltering = 1 (default)
 * verboseLevel = "info"

Loading features
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[12:54:27.592446][info] Fuse matches into tracks:
        - # tracks: 300
        - # images in tracks: 6
[12:54:27.592446][info] TrackLength, Occurrence
[12:54:27.608046][info]         2       282
[12:54:27.608046][info]         3       18
Automatic selection of an initial pair:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
******************************[12:54:27.608046][info] AutomaticInitialPairChoice
, test I: 513178176, J: 1111185747, nbCommonTracks: 62
[12:54:27.608046][info] AutomaticInitialPairChoice, test I: 599528417, J: 977491
804, nbCommonTracks: 72
[12:54:27.608046][info] AutomaticInitialPairChoice, test I: 599528417, J: 111118
5747, nbCommonTracks: 62
**********[12:54:27.608046][info] AutomaticInitialPairChoice, test I: 857897448,
 J: 977491804, nbCommonTracks: 60
***********
[12:54:27.643247][info] AutomaticInitialPairChoice, test I: 857897448, J: 109369
6302, nbCommonTracks: 62
[12:54:27.774047][error] No valid initial pair found automatically.

WARNING: downgrade status on node "PrepareDenseScene_1" from Status.SUBMITTED to
 Status.NONE
WARNING: downgrade status on node "CameraConnection_1" from Status.SUBMITTED to
Status.NONE
WARNING: downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Statu
s.NONE
WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Statu
s.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Statu
s.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Statu
s.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to
 Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to
 Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NO
NE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Sta
tus.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.
NONE
ERROR:root:Error during Graph execution Error on node "StructureFromMotion_1":
Log:
Program called with the following parameters:
 * describerTypes = "sift"
 * extraInfoFolder = "C:/Users/UTKARSH/Documents/MeshroomCache/StructureFromMoti
on/6c668731d079f5f00b7be573ba5ebff706db3d6d"
 * featuresFolders =  = [C:/Users/UTKARSH/Documents/MeshroomCache/FeatureExtract
ion/361153261cdb5ea2cec035137badc59777d910c6]
 * initialPairA = ""
 * initialPairB = ""
 * input = "C:/Users/UTKARSH/Documents/MeshroomCache/CameraInit/7e49b03ae6cf5c55
d51170f7f5df4fa31e98da4b/cameraInit.sfm"
 * interFileExtension = ".abc"
 * localBAGraphDistance = 1
 * localizerEstimator = "acransac"
 * lockScenePreviouslyReconstructed = 0
 * matchesFolders =  = [C:/Users/UTKARSH/Documents/MeshroomCache/FeatureMatching
/a306d5cbc21553d60fdc71e952a290103354f6d3]
 * maxAngleInitialPair = 40
 * maxNumberOfMatches = 0
 * maxReprojectionError = 4
 * minAngleForLandmark = 2
 * minAngleForTriangulation = 3
 * minAngleInitialPair = 5
 * minInputTrackLength = 2
 * minNumberOfObservationsForTriangulation = 2
 * output = "C:/Users/UTKARSH/Documents/MeshroomCache/StructureFromMotion/6c6687
31d079f5f00b7be573ba5ebff706db3d6d/sfm.abc"
 * outputViewsAndPoses = "C:/Users/UTKARSH/Documents/MeshroomCache/StructureFrom
Motion/6c668731d079f5f00b7be573ba5ebff706db3d6d/cameras.sfm"
 * refineIntrinsics = 1 (default)
 * useLocalBA = 1
 * useOnlyMatchesFromInputFolder = 0
 * useTrackFiltering = 1 (default)
 * verboseLevel = "info"

Loading features
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[12:54:27.592446][info] Fuse matches into tracks:
        - # tracks: 300
        - # images in tracks: 6
[12:54:27.592446][info] TrackLength, Occurrence
[12:54:27.608046][info]         2       282
[12:54:27.608046][info]         3       18
Automatic selection of an initial pair:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
******************************[12:54:27.608046][info] AutomaticInitialPairChoice
, test I: 513178176, J: 1111185747, nbCommonTracks: 62
[12:54:27.608046][info] AutomaticInitialPairChoice, test I: 599528417, J: 977491
804, nbCommonTracks: 72
[12:54:27.608046][info] AutomaticInitialPairChoice, test I: 599528417, J: 111118
5747, nbCommonTracks: 62
**********[12:54:27.608046][info] AutomaticInitialPairChoice, test I: 857897448,
 J: 977491804, nbCommonTracks: 60
***********
[12:54:27.643247][info] AutomaticInitialPairChoice, test I: 857897448, J: 109369
6302, nbCommonTracks: 62
[12:54:27.774047][error] No valid initial pair found automatically.

QOpenGLFramebufferObject: Framebuffer incomplete attachment.
QOpenGLFramebufferObject: Framebuffer incomplete, missing attachment.
Nodes to execute:  ['StructureFromMotion_1', 'PrepareDenseScene_1', 'CameraConne
ction_1', 'DepthMap_1', 'DepthMapFilter_1', 'Meshing_1', 'MeshFiltering_1', 'Tex
turing_1']
WARNING: downgrade status on node "StructureFromMotion_1" from Status.ERROR to S
tatus.SUBMITTED

[1/8] StructureFromMotion
 - commandLine: aliceVision_incrementalSfM  --input "C:/Users/UTKARSH/Documents/
MeshroomCache/CameraInit/7e49b03ae6cf5c55d51170f7f5df4fa31e98da4b/cameraInit.sfm
" --featuresFolders "C:/Users/UTKARSH/Documents/MeshroomCache/FeatureExtraction/
361153261cdb5ea2cec035137badc59777d910c6" --matchesFolders "C:/Users/UTKARSH/Doc
uments/MeshroomCache/FeatureMatching/a306d5cbc21553d60fdc71e952a290103354f6d3" -
-describerTypes sift --localizerEstimator acransac --lockScenePreviouslyReconstr
ucted False --useLocalBA True --localBAGraphDistance 1 --maxNumberOfMatches 0 --
minInputTrackLength 2 --minNumberOfObservationsForTriangulation 2 --minAngleForT
riangulation 3.0 --minAngleForLandmark 2.0 --maxReprojectionError 4.0 --minAngle
InitialPair 5.0 --maxAngleInitialPair 40.0 --useOnlyMatchesFromInputFolder False
 --initialPairA "" --initialPairB "" --interFileExtension .abc --verboseLevel in
fo --output "C:/Users/UTKARSH/Documents/MeshroomCache/StructureFromMotion/6c6687
31d079f5f00b7be573ba5ebff706db3d6d/sfm.abc" --outputViewsAndPoses "C:/Users/UTKA
RSH/Documents/MeshroomCache/StructureFromMotion/6c668731d079f5f00b7be573ba5ebff7
06db3d6d/cameras.sfm" --extraInfoFolder "C:/Users/UTKARSH/Documents/MeshroomCach
e/StructureFromMotion/6c668731d079f5f00b7be573ba5ebff706db3d6d"
 - logFile: C:/Users/UTKARSH/Documents/MeshroomCache/StructureFromMotion/6c66873
1d079f5f00b7be573ba5ebff706db3d6d/log
 - elapsed time: 0:03:00.574878
ERROR:root:Error on node computation: Error on node "StructureFromMotion_1":
Log:
Program called with the following parameters:
 * describerTypes = "sift"
 * extraInfoFolder = "C:/Users/UTKARSH/Documents/MeshroomCache/StructureFromMoti
on/6c668731d079f5f00b7be573ba5ebff706db3d6d"
 * featuresFolders =  = [C:/Users/UTKARSH/Documents/MeshroomCache/FeatureExtract
ion/361153261cdb5ea2cec035137badc59777d910c6]
 * initialPairA = ""
 * initialPairB = ""
 * input = "C:/Users/UTKARSH/Documents/MeshroomCache/CameraInit/7e49b03ae6cf5c55
d51170f7f5df4fa31e98da4b/cameraInit.sfm"
 * interFileExtension = ".abc"
 * localBAGraphDistance = 1
 * localizerEstimator = "acransac"
 * lockScenePreviouslyReconstructed = 0
 * matchesFolders =  = [C:/Users/UTKARSH/Documents/MeshroomCache/FeatureMatching
/a306d5cbc21553d60fdc71e952a290103354f6d3]
 * maxAngleInitialPair = 40
 * maxNumberOfMatches = 0
 * maxReprojectionError = 4
 * minAngleForLandmark = 2
 * minAngleForTriangulation = 3
 * minAngleInitialPair = 5
 * minInputTrackLength = 2
 * minNumberOfObservationsForTriangulation = 2
 * output = "C:/Users/UTKARSH/Documents/MeshroomCache/StructureFromMotion/6c6687
31d079f5f00b7be573ba5ebff706db3d6d/sfm.abc"
 * outputViewsAndPoses = "C:/Users/UTKARSH/Documents/MeshroomCache/StructureFrom
Motion/6c668731d079f5f00b7be573ba5ebff706db3d6d/cameras.sfm"
 * refineIntrinsics = 1 (default)
 * useLocalBA = 1
 * useOnlyMatchesFromInputFolder = 0
 * useTrackFiltering = 1 (default)
 * verboseLevel = "info"

Loading features
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[12:57:05.705990][info] Fuse matches into tracks:
        - # tracks: 300
        - # images in tracks: 6
[12:57:05.708990][info] TrackLength, Occurrence
[12:57:05.709990][info]         2       282
[12:57:05.710990][info]         3       18
Automatic selection of an initial pair:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**********[12:57:05.710990][info] AutomaticInitialPairChoice, test I: 513178176,
 J: 1111185747, nbCommonTracks: 62
**********[12:57:05.710990][info] AutomaticInitialPairChoice, test I: 599528417,
 J: 977491804, nbCommonTracks: 72
********************[12:57:05.726590][info] AutomaticInitialPairChoice, test I:
599528417, J: 1111185747, nbCommonTracks: 62
[12:57:05.726590][info] AutomaticInitialPairChoice, test I: 857897448, J: 977491
804, nbCommonTracks: 60
***********
[12:57:05.779390][info] AutomaticInitialPairChoice, test I: 857897448, J: 109369
6302, nbCommonTracks: 62
[12:57:05.886793][error] No valid initial pair found automatically.

WARNING: downgrade status on node "PrepareDenseScene_1" from Status.SUBMITTED to
 Status.NONE
WARNING: downgrade status on node "CameraConnection_1" from Status.SUBMITTED to
Status.NONE
WARNING: downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Statu
s.NONE
WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Statu
s.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Statu
s.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Statu
s.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to
 Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to
 Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NO
NE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Sta
tus.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.
NONE
ERROR:root:Error during Graph execution Error on node "StructureFromMotion_1":
Log:
Program called with the following parameters:
 * describerTypes = "sift"
 * extraInfoFolder = "C:/Users/UTKARSH/Documents/MeshroomCache/StructureFromMoti
on/6c668731d079f5f00b7be573ba5ebff706db3d6d"
 * featuresFolders =  = [C:/Users/UTKARSH/Documents/MeshroomCache/FeatureExtract
ion/361153261cdb5ea2cec035137badc59777d910c6]
 * initialPairA = ""
 * initialPairB = ""
 * input = "C:/Users/UTKARSH/Documents/MeshroomCache/CameraInit/7e49b03ae6cf5c55
d51170f7f5df4fa31e98da4b/cameraInit.sfm"
 * interFileExtension = ".abc"
 * localBAGraphDistance = 1
 * localizerEstimator = "acransac"
 * lockScenePreviouslyReconstructed = 0
 * matchesFolders =  = [C:/Users/UTKARSH/Documents/MeshroomCache/FeatureMatching
/a306d5cbc21553d60fdc71e952a290103354f6d3]
 * maxAngleInitialPair = 40
 * maxNumberOfMatches = 0
 * maxReprojectionError = 4
 * minAngleForLandmark = 2
 * minAngleForTriangulation = 3
 * minAngleInitialPair = 5
 * minInputTrackLength = 2
 * minNumberOfObservationsForTriangulation = 2
 * output = "C:/Users/UTKARSH/Documents/MeshroomCache/StructureFromMotion/6c6687
31d079f5f00b7be573ba5ebff706db3d6d/sfm.abc"
 * outputViewsAndPoses = "C:/Users/UTKARSH/Documents/MeshroomCache/StructureFrom
Motion/6c668731d079f5f00b7be573ba5ebff706db3d6d/cameras.sfm"
 * refineIntrinsics = 1 (default)
 * useLocalBA = 1
 * useOnlyMatchesFromInputFolder = 0
 * useTrackFiltering = 1 (default)
 * verboseLevel = "info"

Loading features
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[12:57:05.705990][info] Fuse matches into tracks:
        - # tracks: 300
        - # images in tracks: 6
[12:57:05.708990][info] TrackLength, Occurrence
[12:57:05.709990][info]         2       282
[12:57:05.710990][info]         3       18
Automatic selection of an initial pair:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**********[12:57:05.710990][info] AutomaticInitialPairChoice, test I: 513178176,
 J: 1111185747, nbCommonTracks: 62
**********[12:57:05.710990][info] AutomaticInitialPairChoice, test I: 599528417,
 J: 977491804, nbCommonTracks: 72
********************[12:57:05.726590][info] AutomaticInitialPairChoice, test I:
599528417, J: 1111185747, nbCommonTracks: 62
[12:57:05.726590][info] AutomaticInitialPairChoice, test I: 857897448, J: 977491
804, nbCommonTracks: 60
***********
[12:57:05.779390][info] AutomaticInitialPairChoice, test I: 857897448, J: 109369
6302, nbCommonTracks: 62
[12:57:05.886793][error] No valid initial pair found automatically.

**Comment by fabiencastan** [comment]
Your dataset is not well textured and is highly reflective, which makes it really difficult to reconstruct. And you have really few images.
You could try to set the `preset` parameter to `high` or `ultra` on the FeatureExtraction node.
