### ISSUE TITLE
Using "Clear submitted status" does not solve the "Graph is being computed externally" issue

### ISSUE THREAD

**Issue by Darker** [alicevision/meshroom#376]
Because Meshroom refused to stop when asked to (kept running steps, instead of ending after last step), I had to kill it.

Now the project is broken. Start and stop buttons are greyed out and I see this:

![image](https://user-images.githubusercontent.com/5508988/51870693-a4c35300-2354-11e9-8b48-e6e6cbc88ca3.png)

Following any sugestions found here on github broke it even further. For example, after pressing "Clear submitted status", I got this state:

![image](https://user-images.githubusercontent.com/5508988/51870791-e0f6b380-2354-11e9-8b6f-949ee543466e.png)

But the buttons are still blocked.

**Comment by nugai** [comment]
You need to "Clear submitted status" not just for the node that failed, but also for each and every node that follows the one that failed.
