### ISSUE TITLE
Uniform medical images will not mesh

### ISSUE THREAD

**Issue by jamesmoe** [alicevision/meshroom#380]
I have a series of 75 images similar to the one attached. The images go all around the anatomy and logically should make an easy mesh due to the detail and clear contrast. Meshroom will only green check a couple in the series and absolutely nothing in terms of creating a mesh. Thoughts on settings to make this work? Thanks.
![sample](https://user-images.githubusercontent.com/1613284/52013110-3c868580-24aa-11e9-89f8-749648d3cc4c.jpg)

**Comment by hargrovecompany** [comment]
I am certainly not qualified to provide an answer, but here's a question....if all of the images have the same scale overlay, and alphanumeric info, won't the software try to align the photos on those features as well?  I'm guessing that a set of images without that overlay would probably work

**Comment by fabiencastan** [comment]
@jamesmoe Did you manage to get decent results?

**Comment by jamesmoe** [comment]
Nope. Took out all the lettering in the background. Turned settings all the way up. There is no reason this should not have worked. I ended up using something called 3D slicer, but that was a pain cause I had to basically learn how to read a ct scan to isolate the anatomy.

On Feb 11, 2019, at 6:46 AM, Fabien Castan <notifications@github.com<mailto:notifications@github.com>> wrote:


@jamesmoe<https://github.com/jamesmoe> Did you manage to get decent results?

**Comment by fabiencastan** [comment]
Any chance you can send me the images privately to understand why it's not working?

**Comment by jamesmoe** [comment]
You bet. Have a Dropbox or something I can zip them up and send?

On Feb 11, 2019, at 10:34 AM, Fabien Castan <notifications@github.com<mailto:notifications@github.com>> wrote:


Any chance you can send me the images privately to understand why it's not working?

**Comment by hargrovecompany** [comment]
just out of curiosity, i am wondering how much overlap you have for adjacent images?  and how much difference in camera angle?

**Comment by fabiencastan** [comment]
@jamesmoe Could you send me an email to `fabien.castan@mikrosimage.com` to find a way for sending files?

**Comment by RadCLarite** [comment]
FYI for the developers and others on this particular data set. 

The source data is a CTA study of the aortic arch, and it was a 3D model to begin with. The rendered images were artificially created with fake lighting and rendering. So, the question really is, what is the goal of meshing this? If the goal is a 3D rendering of the aortic arch, then just take the original data, run it through slicer or itk-snap, then apply a texture to the output. If for some reason you are trying to recreate the 3D source data, I guess you could try to mesh this, but presumably it is stored somewhere.

**Comment by jamesmoe** [comment]
I ended up learning enough of 3D Slicer to isolate the aorta from the source CTA and export it to STL.

It was a bit of a learning curve for what I was trying to accomplish.

It would have been much easier to take this and run it through meshroom treating it like photos around a 3d object. It should totally have worked as it is much cleaner than a real series of images out in the wild.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
