### ISSUE TITLE
Sensor width doesn't exist in the database for image(s) 

### ISSUE THREAD

**Issue by jtduoffMontpellier3D** [alicevision/meshroom#387]
Hi,
I have a problem with methroom, we succeed to launch it but when import images, we have errors like this :
 
Sensor width doesn't exist in the database for image(s) 
/bin/sh: 1: aliceVision_cameraInit: not found
 
After installation we didn’t found the file sensorscamera.sb
We are under mac os. We have xcode 10.0
We have tried everything but noway.
Could you please help us to solve the problem?

**Comment by natowi** [comment]
You can add your own Camera and Sensor by creating a txt file and change it to camerasensor.db and place it in ..\Meshroom-201x.x.0\aliceVision\share\aliceVision\
You can download the db from here: https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/sensorDB/cameraSensors.db
This sensor db is for the latest release! If you have the 2018 release, you need to remove the last column ( ;devicespecifications ) -> change file extension to csv, remove column in Office Calc save as ; separated.

**Comment by jtduoffMontpellier3D** [comment]
Thanks! :-) we'll try it tonight, if it works no problem to share of course , have a good day ! http://jtduoff.fr
