### ISSUE TITLE
cant get past load mesh

### ISSUE THREAD

**Issue by tom3563** [alicevision/meshroom#391]
Hi

I been trying everything i cant get past meshing the button turns green and if i start again it just turns green again..
update: i tried a set of test photos from someone online of a rock and it working why do my photos not work they are large clear photos?
Why dont my photos work i retook the photos 3 time and still stops at meshing..?
thank you for any help..
Let me know if you need any other screen shots..

![untitled-1](https://user-images.githubusercontent.com/47339452/52384846-c99a8300-2a44-11e9-9327-99b3ce3f04fb.jpg)

**Comment by natowi** [comment]
There are a few things to check: 
- are most of the 18 images used for reconstruction?
- check the StructureFromMotion node log (Structure from Motion results: # input images: xx # cameras calibrated: xxx # landmarks: xxxxx.).
To improve the results, you can [optimize some nodes](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters).
- If you have a good result from the SFM node, but still have the MeshFiltering problem, try to disable "Keep Only the Largest Mesh"

**Comment by tom3563** [comment]
Thank you for your help .
Sorry im not following well.

Can you circle on my screen shot were these options are please..

**Comment by tom3563** [comment]
were is * try to disable "Keep Only the Largest Mesh" in the MeshFiltering node.?
Im just not finding it..

**Comment by tom3563** [comment]
ok but it does not go that far to meshfilting, i can't get past Meshing.. 
So i cant * , try to disable "Keep Only the Largest Mesh" in the MeshFiltering node.

Thank you..

**Comment by fabiencastan** [comment]
We can see on your screenshot that only 2 cameras are reconstructed, which means that the SfM has almost failed.
Look at the related wiki page for options that may improve that:
https://github.com/alicevision/meshroom/wiki/StructureFromMotion-fails

**Comment by tom3563** [comment]
ok I took new photos outside it was kind of over cast sky  its  working all the way threw to finish in meshroom. The pictures were clear, i took 13 pictures  but  obj model came out dark.
Any advice to make it better?
![texturedmesh](https://user-images.githubusercontent.com/47339452/52446110-a4fce480-2af2-11e9-8a26-790349e2c246.jpg)
![24](https://user-images.githubusercontent.com/47339452/52446129-b514c400-2af2-11e9-9f3f-8fc05024d114.jpg)

Thank you for your help

**Comment by hargrovecompany** [comment]
How many of the 13 were used (did you see red "x" on any of them) after structure from motion?  13 images is not going to give you a really high quality "person."  Leave your camera oriented in landscspe but get way closer (to the point where he covers most of the width of the screen).  Try 10+ pics including everything from his shoes to his thighs, and a set of 10}from his thighs to his chest, and a set of 10+ from his mid torso to his head.  Alter the angles slightly to make sure you get every point (under the arms, between the legs/feet, inside of the hands) from 3 angles.  Maybe it will take more than 30.
  The challenge is keeping him as still as possible.  If he moves, you'll see that some of the images are thrown out.

**Comment by hargrovecompany** [comment]
….also....he's wearing black pants....those don't offer features that the software needs.  Blue jeans would work better.  And again, the closer you get with the camera, the more features will be available for the software to use.
