### ISSUE TITLE
My camera is already in the DB but not recognized

### ISSUE THREAD

**Issue by Galbi3000** [alicevision/meshroom#394]
A minor issue as it's easily corrected. 
It did not like photos from my Sony Cyber-shot HX200V camera saying I need to add the model and sensor width in the database. After finding out the correct info ready to add it to the database I looked first in the file for Sony cameras and found it is indeed in the database already!

The problem is that the camera produces photos with the model as "DSC-HX200V" but you have it in the database as "Sony CyberShot DSC HX200V". Also the brand is "SONY" (all caps) in the photo data. To temporarily fix it my end I copied the existing line from the database changing the brand & model to exactly match the information in the photo.

**Comment by natowi** [comment]
This is a known problem with Alicevision/Meshroom. Some improvements have been made in the 2019.1 release. Your workaround is already listed in the Meshroom [wiki](https://github.com/alicevision/meshroom/wiki/Add-Camera-to-database).

**Comment by Darker** [comment]
I had the same issue. I just re-added the camera. Btw we might need to think of a better way of maintaining the sensor DB.
