### ISSUE TITLE
[AV210 & pr-release-2019.1] ERROR: unrecognised option '--groupCameraFallback' 

### ISSUE THREAD

**Issue by tycone** [alicevision/meshroom#395]
-Built the aliceVision Binaries using the AliceVision v2.1.0 release source.
-Built Meshroom Executable using the 'pr-release-2019.1' branch.

The below which I get when trying to add an image to a project, tells me that I am trying to use the wrong build version combinations? 

``
Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
WARNING:root:== The following plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

ERROR: unrecognised option '--groupCameraFallback'
Usage:

AliceVision cameraInit:

Required parameters:
  -i [ --input ] arg                    A SfMData file (*.sfm) [if specified,
                                        --imageFolder cannot be used].
  --imageFolder arg                     Input images folder [if specified,
                                        --input cannot be used].
  -s [ --sensorDatabase ] arg           Camera sensor width database path.
  -o [ --output ] arg (=cameraInit.sfm) Output file path for the new SfMData
                                        file

Optional parameters:
  --defaultFocalLengthPix arg (=-1)     Focal length in pixels. (or '-1' to
                                        unset)
  --defaultFieldOfView arg (=-1)        Empirical value for the field of view
                                        in degree. (or '-1' to unset)
  --defaultIntrinsic arg                Intrinsics Kmatrix "f;0;ppx;0;f;ppy;0;0
                                        ;1".
  --defaultCameraModel arg              Camera model type (pinhole, radial1,
                                        radial3, brown, fisheye4, fisheye1).
  --groupCameraModel arg (=2)           * 0: each view have its own camera
                                        intrinsic parameters
                                        * 1: view share camera intrinsic
                                        parameters based on metadata, if no
                                        metadata each view has its own camera
                                        intrinsic parameters
                                        * 2: view share camera intrinsic
                                        parameters based on metadata, if no
                                        metadata they are grouped by folder

  --allowIncompleteOutput arg (=0)      Allow the program to output an
                                        incomplete SfMData file.
                                        Warning: if incomplete the output file
                                        can't be use in another program and
                                        should be post-process.
  --allowSingleView arg (=0)            Allow the program to process a single
                                        view.
                                        Warning: if a single view is process,
                                        the output file can't be use in many
                                        other programs.

Log parameters:
  -v [ --verboseLevel ] arg (=info)     verbosity level (fatal, error, warning,
                                        info, debug, trace).

ERROR:root:Error while building intrinsics : Traceback (most recent call last):
  File "C:\Users\tyler\Desktop\alicevision\meshroom-pr2019\meshroom\meshroom\ui\reconstruction.py", line 382, in buildIntrinsics
    views, intrinsics = cameraInitCopy.nodeDesc.buildIntrinsics(cameraInitCopy, additionalViews)
  File "C:\Users\tyler\Desktop\alicevision\meshroom-pr2019\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 192, in buildIntrinsics
    subprocess.returncode, cmd)
RuntimeError: CameraInit failed with error code 1. Command was: "aliceVision_cameraInit  --sensorDatabase "C:\Users\tyler\Desktop\alicevision\aliceVision\src\aliceVision\sensorDB\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "C:/Users/tyler/AppData/Local/Temp/tmpsjybxhzs/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm" --allowSingleView 1  --input "C:\Users\tyler\AppData\Local\Temp\tmpsjybxhzs/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm""
``

**Comment by fabiencastan** [comment]
Hi,
The option "groupCameraFallback" exists on the AliceVision side, so you are probably using another version.
See the code on the "v2.1.0" tag:
https://github.com/alicevision/AliceVision/blob/v2.1.0/src/software/pipeline/main_cameraInit.cpp#L213

**Comment by tycone** [comment]
Posting the solution in my case, in the off chance it helps another. Just to be safe I re-fetched and re-built the AliceVision binaries but still got the error. I removed some entries to PATH created from previous versions awhile back and it worked like a charm. Thanks @fabiencastan
