### ISSUE TITLE
Prepare DenseScene Fails

### ISSUE THREAD

**Issue by Thorngage** [alicevision/meshroom#396]
Hi, I managed to import the images and start the process, but it stops and fails at the Prepare Dense Scene Node

> [1/1] PrepareDenseScene
>  - commandLine: aliceVision_prepareDenseScene  --input "C:/Users/miche/Documents/Università/Scienza della Rappresentazione 3/Fotogrammetria/MeshroomCache/StructureFromMotion/197f30e80b9377e706ef632436e6379768d4684a/sfm.abc" --verboseLevel info --output "C:/Users/miche/Documents/Università/Scienza della Rappresentazione 3/Fotogrammetria/MeshroomCache/PrepareDenseScene/712d09931794378c58abeeeb122107caa29f26e9"
>  - logFile: C:/Users/miche/Documents/Università/Scienza della Rappresentazione 3/Fotogrammetria/MeshroomCache/PrepareDenseScene/712d09931794378c58abeeeb122107caa29f26e9/log
>  - elapsed time: 0:00:11.818315
> ERROR:root:Error on node computation: Error on node "PrepareDenseScene_1":
> Log:
> Program called with the following parameters:
>  * input = "C:/Users/miche/Documents/Università/Scienza della Rappresentazione 3/Fotogrammetria/MeshroomCache/StructureFromMotion/197f30e80b9377e706ef632436e6379768d4684a/sfm.abc"
>  * output = "C:/Users/miche/Documents/Università/Scienza della Rappresentazione 3/Fotogrammetria/MeshroomCache/PrepareDenseScene/712d09931794378c58abeeeb122107caa29f26e9"
>  * verboseLevel = "info"
> 
> Exporting Scene Data
> 0%   10   20   30   40   50   60   70   80   90   100%
> |----|----|----|----|----|----|----|----|----|----|
> 
> ERROR:root:Error during Graph execution Error on node "PrepareDenseScene_1":

Also, if I double click the Structure from motion node, the point cloud does not appear, not sure if it's related

**Comment by fabiencastan** [comment]
Could you provide the log of the StructureFromMotion?

**Comment by Thorngage** [comment]
[log.txt](https://github.com/alicevision/meshroom/files/2860649/log.txt)
 This is the whole log, I believe

**Comment by MacMachin** [comment]
I have a similar problem, PrepareDenseScene fail with the following status:
{
    "status": "ERROR",
    "execMode": "LOCAL",
    "nodeName": "PrepareDenseScene_1",
    "nodeType": "PrepareDenseScene",
    "packageName": "aliceVision",
    "packageVersion": null,
    "graph": "",
    "commandLine": "aliceVision_prepareDenseScene  --input \"D:/Work/Dessin-Peinture/3D/R\u00e9f\u00e9rences/CC/MeshroomCache/StructureFromMotion/fe599f901558abb877b2e8a766ab4141707d8d0a/sfm.abc\" --verboseLevel trace --output \"D:/Work/Dessin-Peinture/3D/R\u00e9f\u00e9rences/CC/MeshroomCache/PrepareDenseScene/a5e0b24f4baeb04af781fa9377c9ebf9248e4faf\" ",
    "env": null,
    "startDateTime": "2019-02-22 11:45:27.488309",
    "endDateTime": "",
    "elapsedTime": 0,
    "hostname": "MAISON",
    "sessionUid": "7159a146-368e-11e9-a395-001583f5e6f8",
    "returnCode": 3221226505,
    "elapsedTimeStr": "0:00:00"
}

The output of the previous node is attached in a zip file
[SFM.zip](https://github.com/alicevision/meshroom/files/2893583/SFM.zip)

**Comment by BTeaJoe** [comment]
On my computer (GTX 960, Intel  i5-6400, 16GB memory, Win10) the program crashes for a set of images almost immediately after I start PrepareDenseScene. Two days ago, my computer still had 8GB and Win7, but the upgrade did not change anything. However, the computation of this set of images worked just fine on a different computer.

[log-StructureFromMotion.zip](https://github.com/alicevision/meshroom/files/2945431/log-StructureFromMotion.zip)

**Comment by ulfgroote** [comment]
I have the same problem – but I suspect it comes from StructureFromMotion: that node gets green (and Meshroom crashes on the next node, PrepareDenseScene), but this is the log from StructureFromMotion:

[1/1] StructureFromMotion
 - commandLine: aliceVision_incrementalSfM  --input "O:/Spielereien/Photogrammetrie/Fußabdruck/MeshroomCache/CameraInit/bb43b7d26dfee971482dbab12db561c47d883d45/cameraInit.sfm" --featuresFolders "O:/Spielereien/Photogrammetrie/Fußabdruck/MeshroomCache/FeatureExtraction/e519d4d14c9b10164eb9fad0f17948ce215ac976" --matchesFolders "O:/Spielereien/Photogrammetrie/Fußabdruck/MeshroomCache/FeatureMatching/4ae203ddcf3e33a2c9ce59e5645c5d584fa980e7" --describerTypes sift --localizerEstimator acransac --localizerEstimatorMaxIterations 4096 --localizerEstimatorError 0.0 --lockScenePreviouslyReconstructed False --useLocalBA True --localBAGraphDistance 1 --maxNumberOfMatches 0 --minInputTrackLength 3 --minNumberOfObservationsForTriangulation 2 --minAngleForTriangulation 3.0 --minAngleForLandmark 2.0 --maxReprojectionError 4.0 --minAngleInitialPair 5.0 --maxAngleInitialPair 40.0 --useOnlyMatchesFromInputFolder False --useRigConstraint True --lockAllIntrinsics True --initialPairA "" --initialPairB "" --interFileExtension .abc --verboseLevel warning --output "O:/Spielereien/Photogrammetrie/Fußabdruck/MeshroomCache/StructureFromMotion/c72059613522267ad618e0e1e944f584af2f69c6/sfm.abc" --outputViewsAndPoses "O:/Spielereien/Photogrammetrie/Fußabdruck/MeshroomCache/StructureFromMotion/c72059613522267ad618e0e1e944f584af2f69c6/cameras.sfm" --extraInfoFolder "O:/Spielereien/Photogrammetrie/Fußabdruck/MeshroomCache/StructureFromMotion/c72059613522267ad618e0e1e944f584af2f69c6"
 - logFile: O:/Spielereien/Photogrammetrie/Fußabdruck/MeshroomCache/StructureFromMotion/c72059613522267ad618e0e1e944f584af2f69c6/log
 - elapsed time: 0:00:39.657431
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: C:\GitHub\vcpkg\buildtrees\hdf5\src\CMake-hdf5-1.10.1\hdf5-1.10.1\src\H5F.c line 408 in H5Fis_hdf5(): unable open file
    major: File accessibilty
    minor: Not an HDF5 file
  #001: C:\GitHub\vcpkg\buildtrees\hdf5\src\CMake-hdf5-1.10.1\hdf5-1.10.1\src\H5Fint.c line 532 in H5F__is_hdf5(): unable to open file
    major: Low-level I/O
    minor: Unable to initialize object
  #002: C:\GitHub\vcpkg\buildtrees\hdf5\src\CMake-hdf5-1.10.1\hdf5-1.10.1\src\H5FD.c line 809 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: C:\GitHub\vcpkg\buildtrees\hdf5\src\CMake-hdf5-1.10.1\hdf5-1.10.1\src\H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = 'O:/Spielereien/Photogrammetrie/Fu├ƒabdruck/MeshroomCache/StructureFromMotion/c72059613522267ad618e0e1e944f584af2f69c6/sfm.abc', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file

Node output:
[sfm.zip](https://github.com/alicevision/meshroom/files/3470888/sfm.zip)

**Comment by natowi** [comment]
@Thorngage do not use special characters (Università) as @ulfgroote pointed out.
Same as: https://github.com/alicevision/meshroom/issues/209

**Comment by csiszibeni** [comment]
> }

Hy, 
did you finde any solution? 
I have the same problem. What should I do? 

Beni

**Comment by csiszibeni** [comment]
> I have a similar problem, PrepareDenseScene fail with the following status:
> {
> "status": "ERROR",
> "execMode": "LOCAL",
> "nodeName": "PrepareDenseScene_1",
> "nodeType": "PrepareDenseScene",
> "packageName": "aliceVision",
> "packageVersion": null,
> "graph": "",
> "commandLine": "aliceVision_prepareDenseScene --input "D:/Work/Dessin-Peinture/3D/R\u00e9f\u00e9rences/CC/MeshroomCache/StructureFromMotion/fe599f901558abb877b2e8a766ab4141707d8d0a/sfm.abc" --verboseLevel trace --output "D:/Work/Dessin-Peinture/3D/R\u00e9f\u00e9rences/CC/MeshroomCache/PrepareDenseScene/a5e0b24f4baeb04af781fa9377c9ebf9248e4faf" ",
> "env": null,
> "startDateTime": "2019-02-22 11:45:27.488309",
> "endDateTime": "",
> "elapsedTime": 0,
> "hostname": "MAISON",
> "sessionUid": "7159a146-368e-11e9-a395-001583f5e6f8",
> "returnCode": 3221226505,
> "elapsedTimeStr": "0:00:00"
> }
> 
> The output of the previous node is attached in a zip file
> [SFM.zip](https://github.com/alicevision/meshroom/files/2893583/SFM.zip)

Hy,
did you finde any solution?
I have the same problem. What should I do?

Beni

**Comment by natowi** [comment]
@csiszibeni "3D/R\u00e9f\u00e9rences" you probably have special characters in your path that are not supported. Change the folder name.

**Comment by csiszibeni** [comment]
@natowi  Thank you! It was the problem. Now, it is working. ;)
