### ISSUE TITLE
LG Nexus 5X doesn't exist in database

### ISSUE THREAD

**Issue by macio97** [alicevision/meshroom#397]
![screenshot](https://user-images.githubusercontent.com/8861988/52821800-34386800-30b0-11e9-9bf2-44932ede56be.jpg)
I get this error in the log:
`Sensor width doesn't exist in the database for image(s)`
`camera brand: LGE`
`camera model: Nexus 5X`

**Comment by natowi** [comment]
Read the [wiki](https://github.com/alicevision/meshroom/wiki/Add-Camera-to-database). You can close this issue.

**Comment by macio97** [comment]
I followed it, i added the LGE;Nexus 5X;4.7 line in the database, then i reopened the Meshroom, imported the image, same erorr

**Comment by natowi** [comment]
Did you check if this matches your EXIF data and tested the workarounds as described in the wiki?

**Comment by macio97** [comment]
![img_20190214_154514](https://user-images.githubusercontent.com/8861988/52871751-0e13d600-314b-11e9-8eeb-1fa51e93a248.jpg)
This is one of the photos made with my LG Nexus 5X camera.
Yes i tried to lowercase, use LG instead of LGE.. same error

**Comment by natowi** [comment]
OK, LGE;Nexus 5X;4.7 matches the Metadata entry. Some cameras use extra EXIF fields which cause an error when importing images to Meshroom. To fix this problem, strip all uncommon EXIF data and add Make and Model. Now the Meshroom import should work. https://github.com/alicevision/meshroom/issues/205#issuecomment-425863617 You can use Exif tools like Exif Editor or ExifToolGUI. 
This problem might be [related to this](https://github.com/alicevision/meshroom/wiki/Images-cannot-be-imported)

**Comment by macio97** [comment]
I tried it again in Windows and now it works, i just didn't save the database file.
Now, during the process i get this CUDA error:
`This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0).`
![screenshot](https://user-images.githubusercontent.com/8861988/52875485-be3a0c80-3154-11e9-8ca9-c589dc31f8fd.jpg)
I don't have a Nvidia GPU, I have an AMD RX 580 (8GB), is there a way to use it or maybe just the CPU?

**Comment by natowi** [comment]
You will be able to use Meshroom without a Nvidia GPU with the upcomming Release 2019.1.0. From the release note: "Draft Meshing (no CUDA required): the result of the sparse reconstruction can now be directly meshed to get a 3D model preview without computing the depth maps."

**Comment by macio97** [comment]
Great! Thanks! Can't wait for 2019.1! You can close this task
