### ISSUE TITLE
Issue when republishing the texturing with edited mesh

### ISSUE THREAD

**Issue by sunil1239** [alicevision/meshroom#401]
Hi, I'm using the meshroom photogrammetry, My task is to generate a mesh with meshroom and then stop the process after the MeshFiltering and that's done with some code changes in photogrammetry. Now comes the tough part as if I change the mesh or edit the mesh by using maya and again saving the mesh and replace the old mesh in meshroomCache->MeshFiltering, I'm getting the issue saying  "unable to load the mesh" can anyone help with the issue?

**Comment by natowi** [comment]
Have a look at the [wiki](https://github.com/alicevision/meshroom/wiki/Texturing-after-external-re-topology). I think you need to keep the scale/orientation of the model, in order to stay in the same 3D space as the original reconstruction.

**Comment by sunil1239** [comment]
Yes I had kept the model in same place and just made some mesh cuts... I got the issue like I'm using 2018.1 Alice vision. And in 2019.1 they fixed the issue of obj importing to Meshroom

Thanks for the reply

**Comment by fabiencastan** [comment]
I'm closing the issue as it's fixed in 2019.1. Feel free to re-open if there is still a problem.
