### ISSUE TITLE
Need help to build meshroom into single exe like official release v2018.1.0

### ISSUE THREAD

**Issue by TMwhuhan** [alicevision/meshroom#404]
Hi, all. 
    With competent document  of AliceVision project, I success build AliceVision using vs2017. 
The meshroom  work well in commandline. Anyway the ui is setup as  expect. But an error occur when  build this project with pyinstaller. This is the command： pyinstaller -F meshroom/ui/_main_.py
The error message is "2401 INFO: UPX is not available."
    Is there any advice?

**Comment by BanKeTang** [comment]
Hello, have you successfully packaged meshroom into exe file?  I need your help

**Comment by natowi** [comment]
@BanKeTang Why do you need to build it?

If we are only talking about Meshroom (and not the plugins and AliceVision) it is pretty easy: https://github.com/alicevision/meshroom/blob/develop/INSTALL.md

! Note: All Meshroom components require matching versions. Building the latest develop code requires also building AliceVision and plugins. It can not be mixed with pre-built AliceVision binaries. Use the Source code attached to the corresponding release for that purpose.

More detailed:
Python should be set up properly (added to system PATH)

Clone Meshroom to a local directory using git or by downloading a clone from github (extract zip to C:\meshroom)

start cli

git clone https://github.com/alicevision/meshroom.git C:\meshroom

navigate to extracted folder

cd C:\meshroom

set python PATH:

set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

Install dependencies

pip install -r requirements.txt -r dev_requirements.txt --timeout 45

Build Meshroom UI

python setup.py build
