### ISSUE TITLE
Cannot find sensor width for my camera

### ISSUE THREAD

**Issue by octoConnors** [alicevision/meshroom#407]
It's the LG K20 (LG-M255) rear camera. I promise I looked for this camera and even similar cameras (in case one of them has the same part in it) and the specs do not mention sensor width...

**Comment by natowi** [comment]
You can try to use 6 as sensor with. You can also calculate the sensor width by taking a reference image of a known scale. Search the Web for the formula.

**Comment by octoConnors** [comment]
Cool, might try that, sounds like an interesting experiment anyway.

**Comment by natowi** [comment]
@octoConnors Have a look at these links [Calculate camera sensor width with known Pixel size in µm](https://www.vision-doctor.com/en/camera-calculations/sensor-diagonal-sensor-ratio.html)

[Sensor Width Formula](http://vfxcamdb.com/film-back-calculator/)
