### ISSUE TITLE
meshroom doesn't open

### ISSUE THREAD

**Issue by dean48** [alicevision/meshroom#410]
when I click on the meshroom file for some reason the program doesnt start up and briefly shows a window but a split second later it closes. I did extract all of the files.

**Comment by Xcarnoxometzx** [comment]
Do not right click and run as administrator. Instead, just double left click Meshroom and it should open.

I hope this solution helps. I'm sorry if your problem is something else.

**Comment by vsandre** [comment]
The same for me. (Win 10 x64, 2019.1.0) I the next step I startet it via the command line (cmd.exe). I expacted to see some errors. But meshrooms started without warnings and shows the log in the command line box.

**Comment by fabiencastan** [comment]
Could you provide screenshot or screencast or anything to show us your problem. Currently I don't have enough information to understand what's the problem.

**Comment by moncasi** [comment]
I have the same issue on Linux. Here is the error : 
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 13, in run
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/opt/Meshroom/setupInitScriptUnix.py", line 27, in <module>
OSError: [Errno 7] Argument list too long

Thanks

**Comment by obrowny** [comment]
@moncasi you need to move your directory to /opt and it should work.
sudo mv Meshroom-2019.1.0 /opt

**Comment by mitsakosgr** [comment]
I had the exact same problem on my laptop. It opens the command, briefly shows the main window and shuts down without a message, even when run from command.
The solution was to right click the program and choose "Run with Graphics Processor" and select my NVIDIA, high performance gpu.

**Comment by johhnry** [comment]
@obrowny 
Thanks for the answer, I had the same problem on Kali Linux and it worked.
It should be said on the website or in the `INSTALL.md`.

**Comment by Mcavity5** [comment]
I am having the same issue with Meshroom 2019. I get the following when I run it from command line

c:\meshroom\Meshroom-2019.1.0-win64\Meshroom-2019.1.0>meshroom
WARNING:root:No class defined in plugin: .__init___1
Traceback (most recent call last):
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\venv\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\venv\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "meshroom/ui/__main__.py", line 10, in <module>
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\meshroom\ui\app.py", line 9, in <module>
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\meshroom\core\__init__.py", line 253, in <module>
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\meshroom\core\__init__.py", line 234, in loadAllNodes
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\meshroom\core\__init__.py", line 213, in registerNodeType
RuntimeError: Node Desc CameraCalibration is already registered.

Meshroom 2018 however does run.

**Comment by jsteelman2** [comment]
It seems like Linux users might have resolved their problems, but the original post was for Win10.  Here is a screen capture of my CMD window:

![Meshroom closes immediately](https://user-images.githubusercontent.com/47118598/61311035-1d12b900-a7bb-11e9-9742-c23bae6a16e3.PNG)

The Meshroom main window opened for a second or so, then closed.  No apparent error message was generated.

I also tried running the Meshroom.exe as an administrator.  The window stayed open, but I could not add images.

Recommendations for troubleshooting or diagnosis?

**Comment by natowi** [comment]
@jsteelman2 this sounds like Meshroom is being blocked by your antivirus software.

**Comment by elipeters** [comment]
Still happening in October 2020

**Comment by oskar2014** [comment]
Hi,  not working even in 2020.1 release. Windows 10, all Microsoft Visual C++ Redistributable installed. Just black screen and it hangs. No error message, nothing.
Any idea or does anybody succeeded running it on Windows 10?

**Comment by jjzapp10** [comment]
Anybody know how to fix i am getting the problem still

**Comment by natowi** [comment]
This is most likely an issue with windows (updates) or conflict with other apps like antivirus or cgp/gpu tools running in the background.
Similar reports can be found online:
https://windowsreport.com/programs-close-immediately-after-opening/

**Comment by DrGrana** [comment]
I had an issue on Windows 10 where the black screen displayed a warning and would not start. But for some reason it works if you **right click on the application** or shortcut and choose **Run as Administrator**. No issues with that!
Strange, but I hope it helps for the time being.

**Comment by obye94** [comment]
i cut the folder out of my downloads after extraction and pasted it to C: and it started working
