### ISSUE TITLE
No GPU usage during DepthMap step of reconstruction

### ISSUE THREAD

**Issue by Darker** [alicevision/meshroom#411]
I'd say my CPU is more likely an average one, but the GPU is rather new. Therefore it makes me kinda sad to see no GPU usage when running the depth map step:

![image](https://user-images.githubusercontent.com/5508988/53687953-fab45d80-3d3b-11e9-9e52-f186e704ebf8.png)

Is there any setting I could fiddle with to make any use of the GPU that I have? The depth map takes the longest by far, so optimizing it would help me a lot.

**Comment by hargrovecompany** [comment]
Did you notice that at different times, you'll see disk spike, then cpu, then memory, then gpu, etc?
Also, I've noticed that some of the GPU utilization tools don't do a proper calculation of utilization.  Download Nvidia's tool and see if it shows a higher utilization rate

**Comment by Darker** [comment]
Thanks for the advice, I will try a different tool. I have noticed the disk spikes. I think there's a problem that the IO is not asynchronous. The program could go faster if it calculated why waiting for IO.
