### ISSUE TITLE
Release Download from Github

### ISSUE THREAD

**Issue by mrkmg** [alicevision/meshroom#412]
I maintain the AUR package for meshroom-bin.

https://aur.archlinux.org/packages/meshroom-bin/

In the latest release, it appears you are only distributing the binary via Fosshub. This makes it impossible for me to update the meshroom-bin package as Fosshub invalidates any download link and makes me unable to have the PKGBUILD download the binary automatically.

Would it be possible to also allow download via Github for the release like the 2018 version?

**Comment by mrkmg** [comment]
Any comment on this? If this is something you prefer not to do, I will look into an alternate way to distribute a built version that follows the licensing available.

**Comment by fabiencastan** [comment]
Hi @mrkmg,
Sorry for the delay to answer. You are right, I will update the release.
I cannot do it right now, but I will do it asap and let you know.

**Comment by mrkmg** [comment]
Sorry for being persistent. Any change on getting the release uploaded to the release section on GitHub?

**Comment by fabiencastan** [comment]
It's updated now!

**Comment by mrkmg** [comment]
Everything worked with the new package. Will be released on AUR within the hour.
