### ISSUE TITLE
CameraInit Issue with AliceVision built from source

### ISSUE THREAD

**Issue by not-lob** [alicevision/meshroom#416]
I recently built AliceVision from source in order to try and add camera calibration. However, I can't seem to import images into the GUI. I'm using the sample image set just in-case of a problem with exif. I've tried with the pre-built binaries without issue. Any help would be greatly appreciated (output is attached below). Fantastic software and amazing open source initiative!

`
C:\Users\johna_000\Desktop>cd C:\Users\johna_000\Documents\Development\meshroom

C:\Users\johna_000\Documents\Development\meshroom>set PYTHONPATH=C:\Users\johna_                                        000\Documents\Development\meshroom   && python meshroom/ui
Plugins loaded:  CameraCalibration, CameraConnection, CameraInit, CameraLocaliza                                        tion, CameraRigCalibration, CameraRigLocalization, ConvertAnimatedCamera, Conver                                        tSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, ExportUn                                        distortedImages, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchin                                        gMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshRe                                        sampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, Struc                                        tureFromMotion, Texturing
[2019-03-09 14:53:53,544][WARNING] == The following plugins could not be loaded                                         ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_server_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_server_method
qt.network.ssl: QSslSocket: cannot resolve SSL_CONF_CTX_new
qt.network.ssl: QSslSocket: cannot resolve SSL_CONF_CTX_free
qt.network.ssl: QSslSocket: cannot resolve SSL_CONF_CTX_set_ssl_ctx
qt.network.ssl: QSslSocket: cannot resolve SSL_CONF_CTX_set_flags
qt.network.ssl: QSslSocket: cannot resolve SSL_CONF_CTX_finish
qt.network.ssl: QSslSocket: cannot resolve SSL_CONF_cmd
qt.network.ssl: QSslSocket: cannot resolve SSL_select_next_proto
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_next_proto_negotiated
qt.network.ssl: QSslSocket: cannot resolve SSL_set_alpn_protos
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_alpn_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_alpn_selected
Failed to download scene at QUrl("")
ERROR: unrecognised option '--allowIncompleteOutput'
Usage:

AliceVision cameraInit:

Required parameters:
  -i [ --input ] arg                    A SfMData file (*.sfm) [if specified,
                                        --imageFolder cannot be used].
  --imageFolder arg                     Input images folder [if specified,
                                        --input cannot be used].
  -s [ --sensorDatabase ] arg           Camera sensor width database path.
  -o [ --output ] arg (=cameraInit.sfm) Output file path for the new SfMData
                                        file

Optional parameters:
  --defaultFocalLengthPix arg (=-1)     Focal length in pixels. (or '-1' to
                                        unset)
  --defaultFieldOfView arg (=-1)        Empirical value for the field of view
                                        in degree. (or '-1' to unset)
  --defaultIntrinsic arg                Intrinsics Kmatrix "f;0;ppx;0;f;ppy;0;0
                                        ;1".
  --defaultCameraModel arg              Camera model type (pinhole, radial1,
                                        radial3, brown, fisheye4, fisheye1).
  --groupCameraFallback arg (=folder)   When there is no serial number in the
                                        image metadata, we cannot know if the
                                        images come from the same camera. This
                                        is problematic for grouping images
                                        sharing the same internal camera
                                        settings and we have to decide on a
                                        fallback strategy:
                                         * global: all images may come from a
                                        single device (make/model/focal will
                                        still be a differentiator).
                                         * folder: different folders will be
                                        considered as different devices
                                         * image: consider that each image has
                                        different internal camera parameters
  --allowSingleView arg (=0)            Allow the program to process a single
                                        view.
                                        Warning: if a single view is process,
                                        the output file can't be use in many
                                        other programs.

Log parameters:
  -v [ --verboseLevel ] arg (=info)     verbosity level (fatal, error, warning,
                                        info, debug, trace).

[2019-03-09 14:54:25,457][ERROR] Error while building intrinsics : Traceback (mo                                        st recent call last):
  File "C:\Users\johna_000\Documents\Development\meshroom\meshroom\ui\reconstruc                                        tion.py", line 384, in buildIntrinsics
    views, intrinsics = cameraInitCopy.nodeDesc.buildIntrinsics(cameraInitCopy,                                         additionalViews)
  File "C:\Users\johna_000\Documents\Development\meshroom\meshroom\nodes\aliceVi                                        sion\CameraInit.py", line 129, in buildIntrinsics
    subprocess.returncode, cmd)
RuntimeError: CameraInit failed with error code 1. Command was: "aliceVision_cam                                        eraInit  --sensorDatabase "C:\Users\johna_000\Documents\Development\AliceVision\                                        src\aliceVision\sensorDB\cameraSensors.db" --defaultFieldOfView 45.0 --verboseLe                                        vel info --output "C:/Users/JOHNA_~1/AppData/Local/Temp/tmpi2avmdh6/CameraInit/2                                        731003bd822aa3d98acd3185af7e6a65750fcd4/cameraInit.sfm" --allowSingleView 1  --i                                        nput "C:\Users\JOHNA_~1\AppData\Local\Temp\tmpi2avmdh6/CameraInit/2731003bd822aa                                        3d98acd3185af7e6a65750fcd4//viewpoints.sfm" --allowIncompleteOutput 1"`

**Comment by fabiencastan** [comment]
Hi,
You are probably using a version of Meshroom with an incompatible version of AliceVision, as you have this error message:
`ERROR: unrecognised option '--allowIncompleteOutput'`

Use "develop" branch on both Meshroom and AliceVision OR 'v2019.1.0' on Meshroom and "v2.1.0" on AliceVision.

Let us know if that fixes you issue.
Best,

**Comment by not-lob** [comment]
Perfect, thank you.
