### ISSUE TITLE
embedded libraries / crash on Linux 

### ISSUE THREAD

**Issue by alexmyczko** [alicevision/meshroom#417]
Would it be possible to not distribute: libbz2, ncurses?

I try to make a debian package, and having it built, I get the following when trying to start it:
```
$ Meshroom
Fatal Python error: initfsencoding: Unable to get the locale encoding
ImportError: invalid flags 1551282119 in 'encodings'

Current thread 0x00007f4eb6958740 (most recent call first):
zsh: abort      Meshroom
```

**Comment by fabiencastan** [comment]
Thanks for the report. I cannot do it right now, but we will have a look.
