### ISSUE TITLE
result is flat black surface

### ISSUE THREAD

**Issue by chris-aeviator** [alicevision/meshroom#418]
meshroom creates this black surface (200mb) as obj file from 99 indoor pictures of a room - the pictures produce a (semi) good result in comparable software (openMVS+colmap/visualfsm). 

![image](https://user-images.githubusercontent.com/11522213/54272054-21b43000-4583-11e9-93c2-983b3760b70e.png)

I can see the sparse point cloud correctly in meshroom.
![image](https://user-images.githubusercontent.com/11522213/54272265-9e470e80-4583-11e9-927a-75508b4cf5c7.png)

The resulting folder structure makes me think maybe meshroom did not completely finish the pipeline, since it's the `./MeshroomCache/Textures` folder where I'm opening the `.obj` file from.

**Comment by hargrovecompany** [comment]
Chris....I don't know if I can help, but I'll try.  I am a bit confused by the post. The image at the top is meshlab, right?

**Comment by natowi** [comment]
When capturing rooms, do not take all the images from two spots. Move parallel to the walls and take 60%+ overlapping images of the opposite. Also move around difficult objects and take additional images.

**Comment by chris-aeviator** [comment]
I was able to get a much better result by doing as @natowi suggests. The result was also correct after running the same pipeline again and it did not result in the black surface anymore. Anyways I could not figure out why it initially happened as I did not tweak any settings in the first neither the second try.

**Comment by chris-aeviator** [comment]
> Chris....I don't know if I can help, but I'll try. I am a bit confused by the post. The image at the top is meshlab, right?

yes, correct I tried to visualize in meshlab
