### ISSUE TITLE
CUDA detection fails with multiple GPUs

### ISSUE THREAD

**Issue by daktylus** [alicevision/meshroom#419]
Hi, I run a test set of images through Meshroom 2018.1 on different configurations of a virtual machine (Microsoft Azure NC-family). It works flawlessly with 1 or 2 Tesla K80 GPUs. However, using 4 Tesla K80 GPUs in the VM causes an error as CUDA support is not properly detected in the DepthMap-Node.

Error message:
[12:43:36.084380][info] 
[12:43:36.218626][error] This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0).

**Comment by fabiencastan** [comment]
I don't see how things can change between 2 and 4 GPUs. Are you sure you have exactly the same configuration between the setup with 2 GPUs vs the setup with 4 GPUs? Same version of drivers, etc.

**Comment by daktylus** [comment]
It Is the same VM with the same image. Only the assignment is changed (see below). NC6 and NC12 work fine only NC24 failes every time.

Model | vCPU | RAM GB | SSD GB | GPUs | GRAM GB
-----------------------------------------------------
Standard_NC6 | 6 | 56 | 340 | 1 | 8 |
Standard_NC12 | 12 | 112 | 680 | 2 | 16 |
Standard_NC24 | 24 | 224 | 1.440 | 4 | 32 |
