### ISSUE TITLE
GLIBC-2.27 is not found

### ISSUE THREAD

**Issue by SriGanesh130** [alicevision/meshroom#421]
While running depthmapfilternode, it's giving libgeogram requires GLIBC version 2.27(this is for ubuntu 18.04). I am using ubuntu 16.04 and GLIBC for 16.04 is 2.23. how can i solve this issues.

**Comment by fabiencastan** [comment]
Are you using the 2019.1 release binaries? Are you sure about the version?
It was built on CentOS 7.0, so it should only require glibc 2.17.

**Comment by SriGanesh130** [comment]
I am using 2019.1 binaries only. If i use 2018 binaries will it work?
System: ubuntu 16.04

**Comment by fabiencastan** [comment]
If I check the GLIBC used in the 2019.1 release:
```
strings  ./aliceVision/bin/aliceVision_depthMapFiltering | grep -Hn GLIBC_
(standard input):518:GLIBC_2.2.5
(standard input):520:GLIBC_2.14
```

So it seems to be on the other direction. It uses your own version of `libm.so.6` (as it's not included in the release) and your `libm.so` needs GLIBC-2.27 (the default of your OS) but one of the library that we provide is probably hiding the GLIBC of your OS.
Can you run the following command from the meshroom folder?
```
ldd ./aliceVision/bin/aliceVision_depthMapFiltering
```
This should help to analyze the problem.
Best,

**Comment by SriGanesh130** [comment]
Downgraded the geogram  which uses existed GLIBC and linked to the Alice Vision. Now it's working perfectly.
Thank You
