### ISSUE TITLE
Meshroom generates mesh for everything around the subject, except the subject

### ISSUE THREAD

**Issue by Techno-Hwizrdry** [alicevision/meshroom#423]
I imported photos of my subject (a pair of boots), generated a mesh, and Meshroom generated the point cloud of the boots but not a mesh for the boots.  As a matter of fact, it generated the mesh of everything around the boots, but not the boots.  This can be seen in the screenshots below.

![meshroom](https://user-images.githubusercontent.com/11062093/54651718-7d525200-4a8a-11e9-9a27-5c1e18f172f2.png)
![meshroom2](https://user-images.githubusercontent.com/11062093/54651719-7d525200-4a8a-11e9-8a5a-8c778c2a90b4.png)
![meshroom3](https://user-images.githubusercontent.com/11062093/54651720-7deae880-4a8a-11e9-819f-a654a3bbdc19.png)

I am running Meshroom 2019.1 on Ubuntu 16.04.  Also, since I am running it without a CUDA enabled GPU, I have to use the Draft Mesh method as defined [here](https://github.com/alicevision/meshroom/wiki/Draft-Meshing).  Strangely, I was able to successfully generate a mesh using [this dataset](https://github.com/mkbreuer/Misc-Share-Archiv/raw/master/testing/Rockscan_50_Images.zip) and the Draft Mesh method.

This is my first time using Meshroom, so I might be overlooking some feature or switch I am not aware of.  Any advice would be deeply appreciated.

**Comment by natowi** [comment]
Disable "Keep Only The Largest Mesh". This is disabled by default in the 2019.1.0 release to avoid this problem. The largest Mesh is in your case the reconstructed background. The transparent, single coloured box might not provide enough matching points, so your boots are not connected to your large background mesh and are therefore removed. You should place your object of interest on a well structured non transparent or reflecting surface (e.g. a newspaper).

**Comment by Techno-Hwizrdry** [comment]
Hi natowi!   I'm still new to photogrammetry and Meshroom, and I thank you for your patience.  I tried everything you mentioned and still no dice.  I re-shot all the boots with a brown cardboard box underneath them and I still got the problem, as seen below.

Is cardboard a good surface to place a subject on?

I want to update my sensor database, but I can not find the sensor width of the smartphone camera I used anywhere (motorola e5 play).  Is there a "ball park" sensor width I could use for these photos?

![Screenshot from 2019-03-20 18-13-38](https://user-images.githubusercontent.com/11062093/54722831-fbbafc80-4b3b-11e9-8143-72f9cb80f295.png)

**Comment by hargrovecompany** [comment]
Get a lot more illumination on the boots so that maybe you'll have more features.  Get several lamps or whatever you can use, and try to make sure the light shines between the boots as well.  I'm pretty sure you'll get a different result.

**Comment by hargrovecompany** [comment]
in addition to lighting, you might try moving your camera closer.  don't worry about getting full view of the boots in one shot...and getting adequate shots with features between the boots will be a challenge.  think about possibly doing one boot at a time, then combining the output  in meshlab?

**Comment by natowi** [comment]
@Techno-Hwizrdry You can try 3.66 as camera sensor width. 
Single coloured objects with few features are difficult to capture. To improve the results you can [optimize the parameters](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters) and reduce the reflections of the boots by adding some chalk or flour on the surface.
