### ISSUE TITLE
Mesh Denoising Not Completing

### ISSUE THREAD

**Issue by Lievargus** [alicevision/meshroom#424]
My models are coming out with a lot of extra bumps and I was hoping to use the Mesh Denoising node to reduce the severity of the issue but I have been unable to get Meshroom to complete the step.  If it starts at all it will run for a some period until eventually just turning red without any error indication.  The last thing in the log/console is always "Preprocessing...".  I am unsure if I am hooking the node up in the wrong spot (I have tried either side of Mesh Filtering and even after Texturing) or if its something else.

I am using Meshroom 2019 with a GTX 1060 GPU.

**Comment by natowi** [comment]
![mr](https://user-images.githubusercontent.com/8138537/54708064-ce258180-4b42-11e9-9efe-c0c913f205ea.JPG)

**Comment by Monk2011** [comment]
@natowi  Are you saying that decimation would fix the issue better or are you saying that is how you string the nodes but accidentally clicked decimate instead of denoise?

**Comment by natowi** [comment]
@Lievargus Sorry, I clicked on the wrong node. This is how I connect the Mesh Denoising node.

**Comment by Lievargus** [comment]
@natowi 
I managed to get it running it again but its hanging up in a different way now.


[10/12] MeshFiltering
 - commandLine: aliceVision_meshFiltering  --input "D:/Meshroom/Projects/Kristen - Test 2/MeshroomCache/Meshing/1293cfde6b763526c19ecc5b216eaa90ed795c31/mesh.obj" --removeLargeTrianglesFactor 60.0 --keepLargestMeshOnly False --iterations 5 --lambda 1.0 --verboseLevel info --output "D:/Meshroom/Projects/Kristen - Test 2/MeshroomCache/MeshFiltering/c14c9abb1b12f1bb648cf1f53b79de155ac7abef/mesh.obj"
 - logFile: D:/Meshroom/Projects/Kristen - Test 2/MeshroomCache/MeshFiltering/c14c9abb1b12f1bb648cf1f53b79de155ac7abef/log
 - elapsed time: 0:00:17.391893

[11/12] MeshDenoising
 - commandLine: aliceVision_meshDenoising  --input "D:/Meshroom/Projects/Kristen - Test 2/MeshroomCache/MeshFiltering/c14c9abb1b12f1bb648cf1f53b79de155ac7abef/mesh.obj" --denoisingIterations 5 --meshUpdateClosenessWeight 0.001 --lambda 2.0 --eta 1.5 --mu 1.5 --nu 0.3 --meshUpdateMethod 0 --verboseLevel info --output "D:/Meshroom/Projects/Kristen - Test 2/MeshroomCache/MeshDenoising/890d314ebd30b733bfa4a13cf801d8fba58cc18b/mesh.obj"
 - logFile: D:/Meshroom/Projects/Kristen - Test 2/MeshroomCache/MeshDenoising/890d314ebd30b733bfa4a13cf801d8fba58cc18b/log
 - elapsed time: 0:11:24.560398
ERROR:root:Error on node computation: Error on node "MeshDenoising_1":
Log:
Program called with the following parameters:
 * denoisingIterations = 5
 * eta = 1.5
 * input = "D:/Meshroom/Projects/Kristen - Test 2/MeshroomCache/MeshFiltering/c14c9abb1b12f1bb648cf1f53b79de155ac7abef/mesh.obj"
 * lambda = 2
 * meshUpdateClosenessWeight = 0.001
 * meshUpdateMethod = 0
 * mu = 1.5
 * nu = 0.3
 * output = "D:/Meshroom/Projects/Kristen - Test 2/MeshroomCache/MeshDenoising/890d314ebd30b733bfa4a13cf801d8fba58cc18b/mesh.obj"
 * verboseLevel = "info"


====== Filter parameters =========
Lambda: 2
Eta:1.5
Mu:1.5
Nu:0.3
Mesh denoising outer iterations: 5
==================================

[23:11:33.270747][info] Mesh file: "D:/Meshroom/Projects/Kristen - Test 2/MeshroomCache/MeshFiltering/c14c9abb1b12f1bb648cf1f53b79de155ac7abef/mesh.obj" loaded.
[23:11:33.270747][info] Input mesh: 638070 vertices and 1275256 facets.
[23:11:33.274728][info] Mesh normalization.
[23:11:33.322662][info] Start mesh denoising.
Denoising started
Outer iteration 1...
Preprocessing......
Filtering......
Solver converged after 16 iterations
Starting iterative mesh update......
Outer iteration 2...
Preprocessing......

WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "MeshDenoising_1":
Log:
Program called with the following parameters:
 * denoisingIterations = 5
 * eta = 1.5
 * input = "D:/Meshroom/Projects/Kristen - Test 2/MeshroomCache/MeshFiltering/c14c9abb1b12f1bb648cf1f53b79de155ac7abef/mesh.obj"
 * lambda = 2
 * meshUpdateClosenessWeight = 0.001
 * meshUpdateMethod = 0
 * mu = 1.5
 * nu = 0.3
 * output = "D:/Meshroom/Projects/Kristen - Test 2/MeshroomCache/MeshDenoising/890d314ebd30b733bfa4a13cf801d8fba58cc18b/mesh.obj"
 * verboseLevel = "info"


====== Filter parameters =========
Lambda: 2
Eta:1.5
Mu:1.5
Nu:0.3
Mesh denoising outer iterations: 5
==================================

[23:11:33.270747][info] Mesh file: "D:/Meshroom/Projects/Kristen - Test 2/MeshroomCache/MeshFiltering/c14c9abb1b12f1bb648cf1f53b79de155ac7abef/mesh.obj" loaded.
[23:11:33.270747][info] Input mesh: 638070 vertices and 1275256 facets.
[23:11:33.274728][info] Mesh normalization.
[23:11:33.322662][info] Start mesh denoising.
Denoising started
Outer iteration 1...
Preprocessing......
Filtering......
Solver converged after 16 iterations
Starting iterative mesh update......
Outer iteration 2...
Preprocessing......

Nodes to execute:  ['MeshDenoising_1', 'Texturing_1']
WARNING: downgrade status on node "MeshDenoising_1" from Status.ERROR to Status.SUBMITTED

[1/2] MeshDenoising
 - commandLine: aliceVision_meshDenoising  --input "D:/Meshroom/Projects/Kristen - Test 2/MeshroomCache/MeshFiltering/c14c9abb1b12f1bb648cf1f53b79de155ac7abef/mesh.obj" --denoisingIterations 5 --meshUpdateClosenessWeight 0.001 --lambda 2.0 --eta 1.5 --mu 1.5 --nu 0.3 --meshUpdateMethod 0 --verboseLevel info --output "D:/Meshroom/Projects/Kristen - Test 2/MeshroomCache/MeshDenoising/890d314ebd30b733bfa4a13cf801d8fba58cc18b/mesh.obj"
 - logFile: D:/Meshroom/Projects/Kristen - Test 2/MeshroomCache/MeshDenoising/890d314ebd30b733bfa4a13cf801d8fba58cc18b/log

**Comment by Lievargus** [comment]
I think I finally sorted out the problem. I am unsure why the initial error was occurring but something about the files within the cache was breaking future attempts.  Once I cleared out the Denoising cache folder it was able to run properly.
