### ISSUE TITLE
Image Drog&Drop don`t  work / images analyze wont start

### ISSUE THREAD

**Issue by emilsvfx** [alicevision/meshroom#427]
Hi.
I can`t add images images by Drog&Drop ,but can add only by Live Reconstruction.
But it`s don't start analyze images and give me the error.
I can't really understand what PC missing  some dependency or it `s are software bug.
I run win10

Video example of issue
https://youtu.be/oIj1MGAe6g0

**Comment by natowi** [comment]
Does [this ](https://github.com/alicevision/meshroom/wiki/Images-cannot-be-imported) help?

**Comment by emilsvfx** [comment]
It`s not worker  :(

I try different image and remane 1,2,3 dont work for me.

He is one image error from Console:

[11:05:14.353574][info] CameraInit report:
        - # views listed: 59
           - # views with an initialized intrinsic listed: 59
           - # views without metadata (with a default intrinsic): 0
        - # intrinsics listed: 1

Nodes to execute:  ['CameraInit_1', 'FeatureExtraction_1', 'ImageMatching_1', 'FeatureMatching_1', 'StructureFromMotion_1', 'PrepareDenseScene_1', 'DepthMap_1', 'DepthMapFilter_1', 'Meshing_1', 'MeshFiltering_1', 'Texturing_1']
WARNING: downgrade status on node "CameraInit_1" from Status.ERROR to Status.SUBMITTED

[1/11] CameraInit
 - commandLine: aliceVision_cameraInit  --sensorDatabase "G:\Applications\# 3D_Software\Meshroom-2019.1.0\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "C:/Users/Emilsvfx/AppData/Local/Temp/MeshroomCache/CameraInit/035e0e584d7d3ec5268d066714efe6ea74a1fc45/cameraInit.sfm" --allowSingleView 1  --input "C:/Users/Emilsvfx/AppData/Local/Temp/MeshroomCache/CameraInit/035e0e584d7d3ec5268d066714efe6ea74a1fc45//viewpoints.sfm"
 - logFile: C:/Users/Emilsvfx/AppData/Local/Temp/MeshroomCache/CameraInit/035e0e584d7d3ec5268d066714efe6ea74a1fc45/log
 - elapsed time: 0:00:01.129640
ERROR:root:Error on node computation: Error on node "CameraInit_1":
Log:
The system cannot find the path specified.
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:/Users/Emilsvfx/AppData/Local/Temp/MeshroomCache/CameraInit/035e0e584d7d3ec5268d066714efe6ea74a1fc45//viewpoints.sfm"
 * output = "C:/Users/Emilsvfx/AppData/Local/Temp/MeshroomCache/CameraInit/035e0e584d7d3ec5268d066714efe6ea74a1fc45/cameraInit.sfm"
 * sensorDatabase = "G:\Applications\# 3D_Software\Meshroom-2019.1.0\aliceVision\share\aliceVision\cameraSensors.db"
 * verboseLevel = "info"

[11:05:24.568321][info] CameraInit report:
        - # views listed: 59
           - # views with an initialized intrinsic listed: 59
           - # views without metadata (with a default intrinsic): 0
        - # intrinsics listed: 1

WARNING: downgrade status on node "FeatureExtraction_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureExtraction_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "ImageMatching_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureMatching_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureMatching_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "FeatureMatching_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "StructureFromMotion_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "PrepareDenseScene_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "PrepareDenseScene_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(11)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(12)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(13)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(14)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(15)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(16)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(17)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(18)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(19)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "CameraInit_1":
Log:
The system cannot find the path specified.
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:/Users/Emilsvfx/AppData/Local/Temp/MeshroomCache/CameraInit/035e0e584d7d3ec5268d066714efe6ea74a1fc45//viewpoints.sfm"
 * output = "C:/Users/Emilsvfx/AppData/Local/Temp/MeshroomCache/CameraInit/035e0e584d7d3ec5268d066714efe6ea74a1fc45/cameraInit.sfm"
 * sensorDatabase = "G:\Applications\# 3D_Software\Meshroom-2019.1.0\aliceVision\share\aliceVision\cameraSensors.db"
 * verboseLevel = "info"

[11:05:24.568321][info] CameraInit report:
        - # views listed: 59
           - # views with an initialized intrinsic listed: 59
           - # views without metadata (with a default intrinsic): 0
        - # intrinsics listed: 1

**Comment by emilsvfx** [comment]
the was bug in my system.  This bug can be closed. :)
