### ISSUE TITLE
Only getting background, keep only the largest mesh unchecked

### ISSUE THREAD

**Issue by POM57** [alicevision/meshroom#429]
I am trying to make a model of the nose of an aircraft, however I only got the hangar and landing gear with struts that connect to nothing, no part of the fuselage made it. I searched around here and tried unchecking keep only the largest mesh setting as some people suggested, but didn't make much difference, I get couple of tiny fragments, but that's it. Is there anything else I could try?

**Comment by natowi** [comment]
Can you provide a sample image? Reflective surfaces can be difficult to capture.

**Comment by POM57** [comment]
Unfortunately I am not allowed to share those pictures, I did make another model of an entire aircraft outside, under bright sun with a lot of reflections and hard shadows. To my surprise it turned out really well, for what I need anyway. The one I have issues with is basically the same aircraft, but with pictures of just the nose and in hangar with much softer lighting and less reflections. The images got matched perfectly as well, the fragments seem to be in the correct spots.
Here is the picture of the result, if that's of any help, the landing gear is very well recreated even though it was only barely visible on just a few images. I am surprised it's even there, but the rest of the aeroplane is just missing.

![masasasaa](https://user-images.githubusercontent.com/48828103/54822086-6ab36500-4ca4-11e9-9c33-5c9616a862d4.png)

**Comment by fabiencastan** [comment]
Do you have points at the SfM step on the problematic/missing part?
Have you tried with the release 2019.1?

**Comment by POM57** [comment]
Yes, there is a reasonable amount of points there. Didn't even realize there was a new version of Meshroom though, will try that as soon as current reconstruction is done, thanks for telling me.

**Comment by POM57** [comment]
I got a little better result with 2019, still not anything usable though. There is a lot of points, but no mesh is created.
![Untit222led](https://user-images.githubusercontent.com/48828103/54837702-5af94800-4cc7-11e9-8745-2ae418cb2a71.png)

**Comment by POM57** [comment]
Here is the other one, It's pretty decent given how bad the conditions were and actually very helpful for me. However the wings are not reconstructed at all even though the points are there. Is there a setting that will make it more likely to make mesh out of them aside from lowering Min Consistent Cameras and Min Consistent Cameras Bad Similarity?
![33333](https://user-images.githubusercontent.com/48828103/54844203-96e7d980-4cd6-11e9-98fd-3332f32a36bf.png)

**Comment by AlexandrParkhomenko** [comment]
Try take images with soft shadow

**Comment by POM57** [comment]
@AlexandrParkhomenko Unfortunately I do not have the luxury to be able to do that, although funnily enough the one I took in hangar with soft shadows ended up not working at all, while the one I took outside, under direct sun did. I did manage to do what I needed with the result I got in the end though.

**Comment by AlexandrParkhomenko** [comment]
Try more marks ( big contrast points ) on wings and invisible parts.

**Comment by XAKEPEHOK** [comment]
Same problem. All images with soft shadows, "keep only the largest mesh" is unckecked. And thats my results:
http://screenshot.lvcdn.ru/c336579550.jpg
http://screenshot.lvcdn.ru/d5b79455c7.jpg

**Comment by natowi** [comment]
@XAKEPEHOK  Take some close-up images and try again. The girl should fill most of the image frame.

**Comment by AlexandrParkhomenko** [comment]
In alicevision exist limit to sift points. and you can make invisible girl ;-)))

**Comment by darwinharianto** [comment]
> )

What do you mean by exist limit to sift points?
I am having the same problem too. My object is not constructed, only the environment.

**Comment by AlexandrParkhomenko** [comment]
> > In alicevision exist limit to sift points. and you can make invisible girl ;-)))
> 
> What do you mean by exist limit to sift points?
> I am having the same problem too. My object is not constructed, only the environment.

Please see AliceVision code. Sift points can be about 500.

**Comment by darwinharianto** [comment]
>>>In alicevision exist limit to sift points. and you can make invisible girl ;-)))
>>
>>What do you mean by exist limit to sift points?
>>I am having the same problem too. My object is not constructed, only the environment.
>>
>Please see AliceVision code. Sift points can be about 500.

is this max points on meshing node?

I tried to take a picture of a tree and it doesnt go well.
![Screenshot from 2020-09-11 09-40-55](https://user-images.githubusercontent.com/44696192/92833454-d434af80-f413-11ea-8e45-fecb00e03b08.png)
![Screenshot from 2020-09-11 09-41-04](https://user-images.githubusercontent.com/44696192/92833459-d5fe7300-f413-11ea-995e-5ade70a55eb6.png)

Is there anything i could do?

**Comment by AlexandrParkhomenko** [comment]
> is this max points on meshing node?
> 
> I tried to take a picture of a tree and it doesnt go well.

> 
> Is there anything i could do?

[Sift points](https://en.wikipedia.org/wiki/Scale-invariant_feature_transform) must be found before building a mesh
