### ISSUE TITLE
Sensor width doesn't exist in the database for image

### ISSUE THREAD

**Issue by SriGanesh130** [alicevision/meshroom#432]
Camera brand: Canon
Model : Canon EOS 5D Mark III
Above camera model is existed in database. But still it's saying "sensor width doesn't exist in the database". I checked the previous discussion on same problem. there it's because of spacing but it's not worked for me.
![error](https://user-images.githubusercontent.com/42513897/54909302-dea57580-4f0f-11e9-9091-41706b62ab66.png)

**Comment by natowi** [comment]
Have a look at the [wiki](https://github.com/alicevision/meshroom/wiki/Add-Camera-to-database)

**Comment by SriGanesh130** [comment]
I am using MR2019.1. Error was not there when i ran binary files. But the error is coming when i ran MR2019.1 which is built from source. I checked the camera in database everything is fine, The same thing  working for other photos(which are taken from mobile phone), not showing any error.

**Comment by natowi** [comment]
@SriGanesh130 can you share a sample image?

**Comment by SriGanesh130** [comment]
issue was solved. It's because the path to sensordb is null by default(you can see in the above screen shot). I gave the path to camerasensors.db in camera_init.py file. Now, it's working.
Thank you.
