### ISSUE TITLE
distorted reconstructions

### ISSUE THREAD

**Issue by brenainnJordan** [alicevision/meshroom#434]
Hi, first off I just wanted to say I'm loving the software so far, I've tried a few scans and they have mostly come out fantastic, however I'm having issues with this particular one.

It's a stone barn, which I photographed on my Canon 600D with a vintage lens on an adapter (it was the only lens I had on me at the time), so there is no focal length meta data (or possibly incorrect focal length data).

The issue is that the structure from motion reconstruction appears distorted, and has failed to aligned some groups of cameras, resulting in one side of the barn being reconstructed twice with a large misalignment (see red lines below). It also looks like the corners of the barn are not 90 degrees suggesting that it has calibrated with the incorrect focal length.

Do you have any suggestions to fix this?

![meshroom_distorted_reconstructions1](https://user-images.githubusercontent.com/23136988/55112082-ab134880-50d3-11e9-8888-80a4598e1f34.PNG)
![meshroom_distorted_reconstructions2](https://user-images.githubusercontent.com/23136988/55112083-ab134880-50d3-11e9-9760-73913a8881aa.PNG)

The background was pretty messy in some images so I painted them to white hoping that might help but it didn't seem to make any difference:

![meshroom_distorted_reconstructions3](https://user-images.githubusercontent.com/23136988/55112084-ab134880-50d3-11e9-9e2b-b1713ee9cbe7.PNG)

**Comment by natowi** [comment]
Did you try to manually add the focal length to the EXIF data of your images?

**Comment by hargrovecompany** [comment]
I am assuming the images that were not included were "above" the two red lines?  Just curious...if that's correct, did the camera angle change significantly between the cameras that are included and those that weren't?  was there plenty of overlap between those that weren't included and those that were?  Also, the method of masking that you used....did you try processing without using the masking?

**Comment by fabiencastan** [comment]
Keep the " Focal Length" init value but set the "Initial Focal Length" to -1 if you are not sure of the value.
That may solve your problem.

**Comment by brenainnJordan** [comment]
@fabiencastan thank you that worked perfectly!
