### ISSUE TITLE
Ability to use SEM images? 

### ISSUE THREAD

**Issue by Gorecraft** [alicevision/meshroom#436]
Hello, 
i want to use scanning electron microscopy images and therefore i don't have a camera sensor but a scanned area and an electron detector. What informations should i provide for "camera intrinsic"? focal length is more or less the working distance and sensor width the "true"  width of the image (width of the scanned area)?
Thanks and regards

**Comment by natowi** [comment]
Did you try processing the images with default values?
I think you should be able to estimate the camera intrinsic parameters.
There are a few papers discussing SEM photogrammetry and camera calibration such as:
http://www.irisa.fr/lagadic/pdf/2014_icra_cui.pdf,
http://www.irisa.fr/lagadic/pdf/2015_ijom_cui.pdf
or
https://hal.archives-ouvertes.fr/hal-01644885/document

If you have a calibration pattern, you could use it to get these parameters as well.
(At the moment, camera calibration is not implemented in the binary release)
https://boofcv.org/index.php?title=Tutorial_Camera_Calibration
https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html

**Comment by natowi** [comment]
Microphotogrammetry experiments if someone is interested: http://fab.cba.mit.edu/classes/864.20/people/camron/microphotogrammetry/final.html
