### ISSUE TITLE
Mesh defects

### ISSUE THREAD

**Issue by tpieco** [alicevision/meshroom#437]
Hi. I'm having great results in Meshroom but I occasionally have small circular defects on a mesh. I can usually smooth them out in blender but it can be pretty tricky to fix when they form a hole through the object. Are there any settings I can change to avoid this issue?

Thanks.

![vase1](https://user-images.githubusercontent.com/49287303/55578587-357c2d80-570e-11e9-9cc0-9ea29ddb1efe.jpg)
![vase2](https://user-images.githubusercontent.com/49287303/55578601-3b720e80-570e-11e9-9d46-2b6ec87ca65e.jpg)
![vase3](https://user-images.githubusercontent.com/49287303/55578616-42991c80-570e-11e9-9de6-2f527839c6f5.jpg)

**Comment by natowi** [comment]
Do these defects occur in areas (like the tip of the speer from your last image)?
If not, is there anything else specific to the affected regions?

**Comment by tpieco** [comment]
I haven't noticed a pattern to where the defects appear, it seems to be random. In the case of the above model the spear tip and other dark areas are fine, the defects appearing on the more textured but smoother areas. Some models have been very rough and textured, with no dark areas, but have still had the defects, while other models have had large areas of featureless dark areas that have had zero defects.
