### ISSUE TITLE
When I Compute Texture Graph Log file is getting huge

### ISSUE THREAD

**Issue by MeoVargas** [alicevision/meshroom#439]
It's growing until I am out of disk space but doesn't create any textures. 

![image](https://user-images.githubusercontent.com/17743087/56015483-3f9fbc80-5d0a-11e9-8e1b-eff711b6bcad.png)

It went 16 gigs last time. Should log file became that big until it starts to create textures?

**Comment by fabiencastan** [comment]
Thanks for the report.
This is probably related to the problem fixed in https://github.com/alicevision/AliceVision/pull/598.
So it should be fixed in the next release.

For a quick workaround, you could try to use very large value for the `Texture Side` parameter on the `Texturing` node.

**Comment by MeoVargas** [comment]
Thank you, I have used a single texture UV as a workaround. quality bit blurry but does job for me.
