### ISSUE TITLE
Live Reconstruction 

### ISSUE THREAD

**Issue by ToddVG** [alicevision/meshroom#442]
Sorry everyone but “First Time caller, long time listener”

If I import files thru the Drag and drop process, then latter decide I will want to add more photos, can I create a new folder and use it as a Live Reconstruction folder?

And if yes, should the original photos be dropped into that same folder?

**Comment by natowi** [comment]
Use the "Augment Reconstruction" field to drop additional images.
You could also use the Live Reconstruction folder.
