### ISSUE TITLE
Drone Project

### ISSUE THREAD

**Issue by ToddVG** [alicevision/meshroom#443]
I have been just having the toughest time doing a project with my “DJI Spark” drone, I don’t know if it is the Resolution 72dpi, the file size, camera or energy the Meta data.

But I have taken 100’s of photos of my house or my car, and just have not been able to come up with a completed project that is of any use.

Anyone out there have help on using photos from a drone and even better a DJI Spark?

Any advice would be great

**Comment by natowi** [comment]
There are several things to consider. Have a look at the [wiki for FAQ](https://github.com/alicevision/meshroom/wiki).
[OpenDroneMap](https://www.opendronemap.org/) might be a better choice.

**Comment by curtthemartian** [comment]
I have used my DJI Mavic pro Platinum on 2 separate major projects with good success.  The key is to take many pictures close together with a lot of overlap.   Also take pictures from different distances.  
My project is to take pictures and make a model of my childhood home.  You will need at least 16 gigs of ram preferably 32 if you have close to a 1000 photos on one project.  
I have run into issues where the program would fail with certain photos and my only way to get around it has been to use the live-update features and drop in about a dozen photos at a time.   If you do that you need to make sure the settings are such that it keeps all data.  I cant remember the setting at the moment.  It will take a long time to run.

**Comment by ToddVG** [comment]
Wow, great info. Would love to know the exact steps that you went thru to do a project with so many photos. 

I have 16 GB ram with a 1070 video card. 

I have added upto 400 photos at one time, with several fails. 

When you add additional photos was Live Reconstruction folder already started with original photos. Or did you add Live Reconstruction option after the original run thru with the new photos.

**Comment by fabiencastan** [comment]
Hi,
There is a bug in the release 2019.1 described [here](https://github.com/alicevision/meshroom/issues/409) which creates problem when you have some images poorly connected. It is fixed for the next release, in the meantime, if you have this issue you could use the previous release.
Best,

**Comment by curtthemartian** [comment]
Like you, mine failed many times until I started breaking it up Into groups of 20-50 depending on if a particular photo was causing problems for some reason.  And unfortunately the folder will have to be empty first.  It also seems to matter which photos come first, though I don’t really have any recommendations for that.   All of this was for the 2018 version of Meshroom.  I am running a nvidia 1070 and 32gigs of ram on an i7-7700HQ CPU Alienware laptop with the highest resolution photos my device could do.   Also, it doesn’t seem to work with multiple camera types like when I try to augment the drone photos with pictures from my phone.   I also didn’t have success with RAW format photos.  Good luck to you!
Avoid hitting the objects you are capturing with your drone, it won’t end up well.  In my case all I had to do was replace the props, but still be careful!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
