### ISSUE TITLE
Not see any of that in Graph editor, on the laptop

### ISSUE THREAD

**Issue by Sinto13** [alicevision/meshroom#447]
Not see any of that in Graph editor, tell me how to decide, platform win 64 graphics card if you nvidea 635М

**Comment by Sinto13** [comment]
Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
WARNING:root:glPointSize() and GL_PROGRAM_POINT_SIZE are not supported by ES 2.0

**Comment by natowi** [comment]
Duplicate issue #279

Try the following:

- avoid special characters/non-ASCII characters in Meshroom and images file paths

- make sure your antivirus program does not interfere with Meshroom

- run Meshroom as Admin

- Check your Python installation /reinstall as admin and check the PATH if there are any conflicts

- Try the Meshroom [2018.1](https://github.com/alicevision/meshroom/releases/tag/v2018.1.0) release, when using windows 7 try the corresponding release

**Comment by Sinto13** [comment]
Unfortunately not one item did not fit. The problem remains urgent

**Comment by ChemicalXandco** [comment]
Did you use the official binaries or is it running from the source code? The problem seems to be related to a problem with openGLES, I believe openGLES 2.0 is outdated? Sorry but I still struggle to comprehend what the issue is.

**Comment by Sinto13** [comment]
Tried to install, did not help. After that, reinstalled Windows, installed fire wood, launched. Turned off the program, turn l again and the same problem

**Comment by ChemicalXandco** [comment]
I think this problem is slightly different from #279 comparing the logs. It seems a very small portion of users are affected by this, maybe you could try on a different machine?

**Comment by Sinto13** [comment]
solved the problem, you need to set the settings of the graphics card forced the run if you and the standard was launched by Intel graphics card. 
Thanks for the tips. 

Moderators please add in the title that the problem is on the laptop, then it turned out to be the key
