### ISSUE TITLE
Crash on Meshing / GPU driver crash / SIGBREAK

### ISSUE THREAD

**Issue by Capzor** [alicevision/meshroom#448]
On meshing, the GUI closes leaving the command window running.
I can modify the meshing "status" file in the cache folder for this project to ""SUCCESS"," and then i can continue as normal.
This has also occurred during other parts of the processing.

My screen loses signal and recovers soon after. The following appears in the event viewer:

> Display driver nvlddmkm stopped responding and has successfully recovered.

System:
Windows 10 v. 1809
Nvidia GTX 1080ti, driver version 425,31
i5 4670K
16GB RAM

Two log files attached where this occurred.

I also run Meshroom on a weak laptop and this does not occur. That machine has windows 10, an Nvidia MX150 with driver version 419.67. I tried the 419.67 driver version on my desktop machine and Meshroom continues to crash.

Heres more details from Event Viewer:

> Faulting application name: Meshroom.exe, version: 0.0.0.0, time stamp: 0x5a355fd7
> Faulting module name: nvoglv64.dll, version: 25.21.14.2531, time stamp: 0x5cac820e
> Exception code: 0xc0000409
> Fault offset: 0x0000000000ee5de9
> Faulting process ID: 0x2470
> Faulting application start time: 0x01d4f70783a5bfd8
> Faulting application path: D:\Programs\Meshroom-2019.1.0\Meshroom.exe
> Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_37ec54c19854e219\nvoglv64.dll
> Report ID: bdaa4366-d541-479f-a622-b6deb7ddbffd
> Faulting package full name: 
> Faulting package-relative application ID: 

And some more details from Event Viewer:

> The description for Event ID 1 from source NVIDIA OpenGL Driver cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
> 
> If the event originated on another computer, the display information had to be saved with the event.
> 
> The following information was included with the event: 
> 
> Unable to recover from a kernel exception. The application must close.
> 
> 
> Error code: 3 (subcode 2)
>  (pid=9328 tid=4508 meshroom.exe 64bit)
> 
> Visit http://www.nvidia.com/page/support.html for more information.
> 
> The message resource is present but the message was not found in the message table

Here is what shows in the command window after the GUI crashed:

> Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
> WARNING: downgrade status on node "Meshing_1" from Status.RUNNING to Status.NONE
> WARNING:root:QQmlComponent: Created graphical object was not placed in the graphics scene.
> Nodes to execute:  ['Meshing_1']
> 
> [1/1] Meshing
>  - commandLine: aliceVision_meshing  --input "D:/Programs/Meshroom-2019.1.0/Projects/Minnes/MeshroomCache/StructureFromMotion/6611f0f666a1a410aaa4629dca804a140eec63ad/sfm.abc" --depthMapsFolder "D:/Programs/Meshroom-2019.1.0/Projects/Minnes/MeshroomCache/DepthMap/46056e35a58e91a4916e0127027767b5a5827171" --depthMapsFilterFolder "D:/Programs/Meshroom-2019.1.0/Projects/Minnes/MeshroomCache/DepthMapFilter/2d503e8757229d5b65d226d79af8ceece72b7f15" --estimateSpaceFromSfM True --estimateSpaceMinObservations 3 --estimateSpaceMinObservationAngle 10 --maxInputPoints 50000000 --maxPoints 5000000 --maxPointsPerVoxel 1000000 --minStep 2 --partitioning singleBlock --repartition multiResolution --angleFactor 15.0 --simFactor 15.0 --pixSizeMarginInitCoef 2.0 --pixSizeMarginFinalCoef 4.0 --voteMarginFactor 4.0 --contributeMarginFactor 2.0 --simGaussianSizeInit 10.0 --simGaussianSize 10.0 --minAngleThreshold 1.0 --refineFuse True --addLandmarksToTheDensePointCloud False --verboseLevel info --output "D:/Programs/Meshroom-2019.1.0/Projects/Minnes/MeshroomCache/Meshing/9194f74243784844fac653451a1e7122a6933fb2/mesh.obj"
>  - logFile: D:/Programs/Meshroom-2019.1.0/Projects/Minnes/MeshroomCache/Meshing/9194f74243784844fac653451a1e7122a6933fb2/log
> WARNING:root:QQmlComponent: Created graphical object was not placed in the graphics scene.
> WARNING:root:QQmlComponent: Created graphical object was not placed in the graphics scene.

[log.txt](https://github.com/alicevision/meshroom/files/3099571/log.txt)
[log 2.txt](https://github.com/alicevision/meshroom/files/3099608/log.2.txt)

**Comment by Capzor** [comment]
Update:
Guessing before testing here, but It may have something to do with factory overclocked GPU's.

( https://forums.tomshardware.com/threads/what-could-be-causing-gpu-rendering-on-a-1080ti-to-crash-my-machine.3348773/ )

The specific model of GPU i am using is "asus gtx 1080 ti rog strix oc"

I will try with underclocking it to see if it helps and report back.

**Comment by chad123chad** [comment]
Did it help?

**Comment by fabiencastan** [comment]
The GPU is not used in the Meshing node.
The Meshing use a lot of RAM. If you have 16GB (or less) it will be close to the limit (especially if you have other things open that can use a lot of RAM like chrome or maya), the OS may have to kill some processes, like the meshing process or the Meshroom UI or something else.
See https://github.com/alicevision/meshroom/wiki/Crashed-at-Meshing.

**Comment by djoerg** [comment]
I'm a little late, but:
As Capzor mentioned 'My screen loses signal and recovers soon after', could this be again a TdrDelay related problem?
See #593
