### ISSUE TITLE
pictures do not align/match as in other photometric programs

### ISSUE THREAD

**Issue by LOLserver** [alicevision/meshroom#450]
There are many pictures that meshroom does not align/match as other known photometric programs easily do. So there is need to take several or many new pictures & add them in the already running project.

Can pictures be aligned/match manually?, Why does pictures gets discarded when I see no obvious mistakes like out of focus, touching edges, bad lightning, etc. I simply makes the process very tedious : ((

Hope someone has a solution, regards

**Comment by natowi** [comment]
You could use these [Reconstruction-parameters](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters) to improve your reconstruction.

Manual image matching is not possible, but already on the wishlist
