### ISSUE TITLE
CCTAG support for latest windows build

### ISSUE THREAD

**Issue by goetzmoritz** [alicevision/meshroom#451]
Hi there,

in meshroom I can define cctag to be detected. However, I get an error when I try.
Is there any plans to have it in the pre-built packages? Or do I do something wrong?

Thanks

**Comment by natowi** [comment]
CCTAG requires OpenCV, which is not yet included in the pre-build packages.

**Comment by natowi** [comment]
Should be available with the next release https://github.com/alicevision/AliceVision/pull/657#event-2461037879
