### ISSUE TITLE
Meshroom will not import images

### ISSUE THREAD

**Issue by chrisrogers3d** [alicevision/meshroom#452]
when i drag an image into the image pane, i get this error. Win10, python3.6

`D:\code\meshroom>set PYTHONPATH=%CD% && python meshroom/ui
Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportColoredPointCloud, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[2019-04-24 16:43:06,733][WARNING] == The following plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

'aliceVision_cameraInit' is not recognized as an internal or external command,
operable program or batch file.
[2019-04-24 16:43:17,522][ERROR] Error while building intrinsics : Traceback (most recent call last):
  File "D:\code\meshroom\meshroom\ui\reconstruction.py", line 382, in buildIntrinsics
    views, intrinsics = cameraInitCopy.nodeDesc.buildIntrinsics(cameraInitCopy, additionalViews)
  File "D:\code\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 192, in buildIntrinsics
    subprocess.returncode, cmd)
RuntimeError: CameraInit failed with error code 1. Command was: "aliceVision_cameraInit  --sensorDatabase "" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "C:/Users/CHRIST~1.ROG/AppData/Local/Temp/tmp2dzu9ajg/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm" --allowSingleView 1  --input "C:\Users\CHRIST~1.ROG\AppData\Local\Temp\tmp2dzu9ajg/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm""`

**Comment by natowi** [comment]
Did you use the [binary release](https://github.com/alicevision/meshroom/releases)?
Have a look at the [wiki](https://github.com/alicevision/meshroom/wiki)
