### ISSUE TITLE
How to impose camera positions?

### ISSUE THREAD

**Issue by theytaz3** [alicevision/meshroom#453]
Hello,
I saw on a previous post that it was necessary to modify the cameras.sfm file generated by the SFM step and input this new file into an SFM. So I did this: 

https://www.noelshack.com/2019-17-5-1556265346-git2.png

My goal here was to impose the position of two cameras that had not been spotted and to see how Meshroom was doing. However, the camera positions I had were not very accurate. So I have several questions:

- Does Meshroom take into account the two new cameras added? Even if you add their position in the camera.sfm file (don't forget to take the pose_id associated with the image), the two cameras are not added after the StructureFromMotion step.

- Doesn't Meshroom take all the information from cameras.sfm if the file data is not very accurate? 

- I received an error just before the DepthMap step:  https://www.noelshack.com/2019-17-5-1556265345-git.png   Is this because I didn't enter the exact coordinates of the two cameras I was trying to impose? Indeed, I noticed that PrepareDenseScene generate much less file output than when I did not modify the cameras.sfm file.

- Is there a way to know exactly the cameras pose if they will always be fixed? 

Thank you in advance for your answers.

**Comment by fabiencastan** [comment]
I'm not sure to understand all your questions precisely, but I will try to answer.
How many cameras do you provide in input? How many poses are you providing? How many camera are reconstructed at the end?

If you provide known poses in input of the SfM node, it will start by trying to triangulate and apply a bundle adjustment on the results before adding new views. If your input cameras are not good enough the provided poses could be removed.

Set the verbose mode to "debug" or "trace" to analyze how the algorithm reacts. You will see when cameras are added and/or removed, etc.

**Comment by theytaz3** [comment]
Sorry for the late answer, I had to work on other things in the meantime.

So I took 7 pictures with 7 camera poses whose orientation and center I know.

So I modified the camerainit.sfm file by incorporating my rotation matrix and camera position. 

first question in relation to the rotation matrix. It is basic in a 3x3 form while in the camera.sfm file, we have 9 lines. The first three rows correspond to the first row of the rotation matrix or the first column? 

So I modified the input of the nodes StructureFromMotion by choosing my new file camerainit.sfm created (so with the camera poses).

I have the following error displayed: 

[https://imgur.com/OqGbGU9](url)

**Comment by theytaz3** [comment]
I put the verbose mode in debug and I get the following lines: 

[15:28:28.594597][debug] Unable to load match file: 1569438493.matches.txt in: /syngenta/data_reconstruction_3D/IDS/pomme/14-05-15h06/MeshroomCache/FeatureMatching/bda132d915a896d2366021d84de38688aeafd414
[15:28:28.594641][debug] Unable to load match file: 1719353294.matches.txt in: /syngenta/data_reconstruction_3D/IDS/pomme/14-05-15h06/MeshroomCache/FeatureMatching/bda132d915a896d2366021d84de38688aeafd414
[15:28:28.594674][debug] Unable to load match file: 297319909.matches.txt in: /syngenta/data_reconstruction_3D/IDS/pomme/14-05-15h06/MeshroomCache/FeatureMatching/bda132d915a896d2366021d84de38688aeafd414
[15:28:28.594764][debug] Unable to load match file: 1166717806.matches.txt in: /syngenta/data_reconstruction_3D/IDS/pomme/14-05-15h06/MeshroomCache/FeatureMatching/bda132d915a896d2366021d84de38688aeafd414


and indeed, these files do not exist which is very strange given that I only touched the input of the SFM

**Comment by theytaz3** [comment]
After some research, I retested with 2 images where meshroom can locate the camera poses. I got the cameras.sfm file from the first StructureFromMotion node and I modified the values in rotation and center.

I created a second node that takes cameras.sfm as input. 

I think my mistake comes from the fact that I do not have the same orientation of the axes at the origin.

I have created a program in which I enter the coordinates of my camera and it automatically calculates the rotation matrix to be applied so that it targets the origin of my reference (which is the object I take a picture of). 

My camera center and rotation matrix may not be compatible with Meshroom

**Comment by skinkie** [comment]
@theytaz3 would you be willing to share this program, or at least its basic concepts? I am very interested in something like a supervised method for meshroom that could be used to hint the system, and potentially reduce the computation time.
