### ISSUE TITLE
I have problem with importing photos...

### ISSUE THREAD

**Issue by AndyKowalski** [alicevision/meshroom#455]
After I imported photos I don't have green mark "V"ok but green kind of focus sign ( info - serial number metadata is missing) I use my Nikon D5200. After I push start, many photos are with red camera image and it's says "no reconstructed". I've tried with my iPhone and it's the same.

**Comment by AndyKowalski** [comment]
Hallo is there anybody ?

**Comment by natowi** [comment]
Have a look at the [wiki](https://github.com/alicevision/meshroom/wiki/Add-Camera-to-database)

**Comment by Lesani** [comment]
@natowi a very unhelpful message
@AndyKowalski use the 2018.01 version. the 2019 has lots of issues with non-perfect photo sets (red camera image)
