### ISSUE TITLE
What is the best way to cite meshroom?

### ISSUE THREAD

**Issue by SBCV** [alicevision/meshroom#457]
I'm aware of the bibtex entries provided here: https://github.com/alicevision/AliceVision

Is there also a paper / tech report to cite Meshroom? Or do I have to reference the website?

**Comment by simogasp** [comment]
Hello,

there is not yet a publication associated to meshroom. If you want cite the software for a scientific paper you can use this
```latex
@Misc{Meshroom,
  Title                    = {{Meshroom: A 3D reconstruction software.}},
  Author                   = {AliceVision},
  Year                     = {2018},
  url = {https://github.com/alicevision/meshroom}
}
```
Otherwise, if you want to refer to a particular algorithm of the pipeline you can refer to any of the specific publications cited in alicevision repository.

Thanks!

**Comment by SBCV** [comment]
Thank you for the quick response. Just wanted to make sure that I'm not missing something.

**Comment by fabiencastan** [comment]
@SBCV Thank you for asking!

**Comment by griwodz** [comment]
The final version of the AliceVision Meshroom paper is ready and will be public in about a month, perhaps we can already update the bibtex:

@inproceedings{alicevision2021,
    title={{A}liceVision {M}eshroom: An open-source {3D} reconstruction pipeline},
    authors={Carsten Griwodz, Simone Gasparini, Lilian Calvert, Pierre Gurdjos, Fabien Castan, Benoit Maujean, Gregoire De Lillo, Yann Lanthony},
    booktitle={Proc. 12th ACM Multimed. Syst. Conf. - MMSys '21},
    doi = {10.1145/3458305.3478443}
    publisher = {ACM Press},
    year = {2021}
}

**Comment by fabiencastan** [comment]
https://github.com/alicevision/meshroom/pull/1520
