### ISSUE TITLE
CameraInit.sfm/ photos import issue

### ISSUE THREAD

**Issue by REIVAN2852** [alicevision/meshroom#459]
Hi guys,
Im unable to import any photos when I drag them it shows me this 
![error](https://user-images.githubusercontent.com/50277507/57185091-6a260500-6ec5-11e9-970c-c44d015a8ca3.png)
If I choose to import photos by selecting folder it imports them but they are all without metadata. I basically cant do anything. I tries multiple cameras (all in database) ****I even tried to import photos downloaded from other users that worked(saw models with my own eyes) for them**** so what on earth could be the problem? any help please?

**Comment by natowi** [comment]
[Here](https://github.com/alicevision/meshroom/wiki/Troubleshooting) is a list of a few things you can try/check (not everything does apply in your case).
