### ISSUE TITLE
Blender 2.8 motion track import

### ISSUE THREAD

**Issue by s-leger** [alicevision/meshroom#460]
Hi guys, 
Made small importer for camera match moving (cameras.sfm) in order to fix crash issues with alembic import into blender 2.8 series.

https://github.com/s-leger/Meshroom_tracking_for_blender

**Comment by fabiencastan** [comment]
Great, that's a good idea!

**Comment by brothermechanic** [comment]
no, it import only one camera
very poor functions
alembic is better

**Comment by s-leger** [comment]
If you succeed in importing alembic in blender 2.8, please let me know..
It does import one single animated camera. 
This is the desired behaviour when it comes to motion tracking.

**Comment by brothermechanic** [comment]
blender-2.78 susses imported alembic
i don't know why latest blender can't do this

**Comment by robertguetzkow** [comment]
@s-leger has this issue been reported to the blender devs? If not it would be great if you could add a [ticket](https://developer.blender.org/maniphest/task/edit/form/1/).

**Comment by natowi** [comment]
@robertguetzkow https://developer.blender.org/T62720

**Comment by robertguetzkow** [comment]
@natowi Thanks. It's already resolved that's why I didn't find it in a quick search.

**Comment by SBCV** [comment]
This addon (https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer) allows you to import the camera motion into Blender
