### ISSUE TITLE
[Improvement] Add file picker to add images

### ISSUE THREAD

**Issue by stephen304** [alicevision/meshroom#461]
It appears the only way to add photos (when not doing "Live Reconstruction") is to drag and drop. This unfortunately is impossible for those of us without a file manager installed (there is nowhere to drag files from).

It should be pretty simple to add a button to choose files or make double (or single) clicking the drop area open a file chooser, and it would make it a lot easier to use. I currently use live reconstruction to pick a folder and then stop the live reconstruction, but that seems like a very roundabout way to do it.

**Comment by natowi** [comment]
A file picker is now available in the 2020 release
