### ISSUE TITLE
Half of the mesh is not made properly

### ISSUE THREAD

**Issue by rfblock** [alicevision/meshroom#462]
I tried to run meshroom. It only uses less than half of the photos and only one side of the mesh.
I have a
GTX 760
i3-8100 LGA1151
on Windows 10
https://imgur.com/a/WxVLHIS
I can't find any other topic about this.
I'm not sure what to post since this is my first time posting, so if you need any more info just ask

**Comment by fabiencastan** [comment]
You have only 17 cameras localized on the 46 input images. So some connections between images are missing. Consider adding more images on the acquisition side, or try to recover more of them with more aggressive/compute intensive parameters are described here:
https://github.com/alicevision/meshroom/wiki/StructureFromMotion-fails
Best,

**Comment by rfblock** [comment]
> You have only 17 cameras localized on the 46 input images. So some connections between images are missing. Consider adding more images on the acquisition side, or try to recover more of them with more aggressive/compute intensive parameters are described here:
> https://github.com/alicevision/meshroom/wiki/StructureFromMotion-fails
> Best,

Hopefully this will work, it sounds about right. I'm running the program right now and I will put the results. Thanks!

**Comment by rfblock** [comment]
So far i've tried:
Feature Extraction High
Feature Extraction High akaze (with feature matching and structure from motion akaze)
Feature Extraction Ultra w/ and w/o akaze. Which led to "Graph is being computed externally". So i Do Graph Editor -> Clear Pending Status -> works for 10 seconds and crashes my PC.
I can't find anything else to help or anyone with the same problem. I feel like it's with my model being somewhat symmetrical as well as the background.
