### ISSUE TITLE
Can´t  open for first time

### ISSUE THREAD

**Issue by ZdendaL** [alicevision/meshroom#463]
I´ve installed Meshroom on Windows, extract files and open application. But the program open error message that it didn´t find the thing called VCRUNTIME140.dlll. I tried to reinstall but the problem is still there
I found that thing in searching but the program doesn´t see it
Thanks for answering

**Comment by natowi** [comment]
You can try to install/reinstall Microsoft Visual C++ 2015 Redistributable.
