### ISSUE TITLE
Process failed on Meshing

### ISSUE THREAD

**Issue by artofka** [alicevision/meshroom#469]
Error:
Program called with the following parameters:
 * addLandmarksToTheDensePointCloud = 0
 * angleFactor = 15
 * contributeMarginFactor = 2
 * depthMapsFilterFolder = "/tmp/MeshroomCache/DepthMapFilter/94beda5270ebb39a02199c73e84b95bab3c52368"
 * depthMapsFolder = "/tmp/MeshroomCache/DepthMap/3567eba867c26d3e72f4d583c78a6b4f18a4d8e3"
 * estimateSpaceFromSfM = 1
 * estimateSpaceMinObservationAngle = 10
 * estimateSpaceMinObservations = 3
 * input = "/tmp/MeshroomCache/StructureFromMotion/8ae8803122e7e296c259be56df056d270644e2c9/sfm.abc"
 * maxInputPoints = 50000000
 * maxPoints = 50000
 * maxPointsPerVoxel = 1000000
 * minAngleThreshold = 1
 * minStep = 2
 * output = "/tmp/MeshroomCache/Meshing/e64de7f44e9f6924bf85455b3464d7ff7ac3016f/mesh.obj"
 * partitioning =  Unknown Type "17EPartitioningMode"
 * pixSizeMarginFinalCoef = 4
 * pixSizeMarginInitCoef = 2
 * refineFuse = 1
 * repartition =  Unknown Type "16ERepartitionMode"
 * simFactor = 15
 * simGaussianSize = 10
 * simGaussianSizeInit = 10
 * universePercentile = 0.999 (default)
 * verboseLevel = "trace"
 * voteMarginFactor = 4

[18:55:11.231792][trace] 2 extrinsics declared and 23 extrinsics used.
[18:55:11.231945][info] Found 1 image dimension(s): 
[18:55:11.231965][info] 	- [5472x3648]
[18:55:11.231984][debug] [IO] Read Image Metadata: /tmp/MeshroomCache/DepthMap/3567eba867c26d3e72f4d583c78a6b4f18a4d8e3/96673869_depthMap.exr
[18:55:11.236654][debug] Reading view 96673869 projection matrix from image metadata.
[18:55:11.236743][debug] [IO] Read Image Metadata: /tmp/MeshroomCache/DepthMap/3567eba867c26d3e72f4d583c78a6b4f18a4d8e3/1375539529_depthMap.exr
[18:55:11.240169][debug] Reading view 1375539529 projection matrix from image metadata.
[18:55:11.240191][info] Overall maximum dimension: [5472x3648]
[18:55:11.240244][warning] repartitionMode: 1
[18:55:11.240258][warning] partitioningMode: 1
[18:55:11.240268][info] Meshing mode: multi-resolution, partitioning: single block.
[18:55:11.240538][info] Estimate space from SfM.
Abnormal program termination: function terminate() was called

Opensuse 42.2 / MeshRoom 2019.1.0

**Comment by Magisteri** [comment]
I am also encountering this issue:

WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "Meshing_1":
Log:
Program called with the following parameters:
 * addLandmarksToTheDensePointCloud = 0
 * angleFactor = 15
 * contributeMarginFactor = 2
 * depthMapsFilterFolder = "C:/Users/Vagrant King/Desktop/Backpack/MeshroomCache/DepthMapFilter/b14540583140147484978bd26c6642ed494fafc8"
 * depthMapsFolder = "C:/Users/Vagrant King/Desktop/Backpack/MeshroomCache/DepthMap/e70177272e9e1983dcdadc18d6a28a863c27b32d"
 * estimateSpaceFromSfM = 1
 * estimateSpaceMinObservationAngle = 10
 * estimateSpaceMinObservations = 3
 * input = "C:/Users/Vagrant King/Desktop/Backpack/MeshroomCache/StructureFromMotion/24cbf36192ec6b61800ae19a4ddaa307aa29dd91/sfm.abc"
 * maxInputPoints = 50000000
 * maxPoints = 5000000
 * maxPointsPerVoxel = 1000000
 * minAngleThreshold = 1
 * minStep = 2
 * output = "C:/Users/Vagrant King/Desktop/Backpack/MeshroomCache/Meshing/4d752c785424faea60298060200e82ff22ca4a67/mesh.obj"
 * partitioning =  Unknown Type "enum EPartitioningMode"
 * pixSizeMarginFinalCoef = 4
 * pixSizeMarginInitCoef = 2
 * refineFuse = 1
 * repartition =  Unknown Type "enum ERepartitionMode"
 * simFactor = 15
 * simGaussianSize = 10
 * simGaussianSizeInit = 10
 * universePercentile = 0.999 (default)
 * verboseLevel = "info"
 * voteMarginFactor = 4

[18:06:08.860909][info] Found 1 image dimension(s):
[18:06:08.861908][info]         - [4032x3024]
[18:06:08.873904][info] Overall maximum dimension: [4032x3024]
[18:06:08.873904][warning] repartitionMode: 1
[18:06:08.873904][warning] partitioningMode: 1
[18:06:08.873904][info] Meshing mode: multi-resolution, partitioning: single block.
[18:06:08.874905][info] Estimate space from SfM.
Abnormal program termination: function terminate() was called

**Comment by Powerbyte7** [comment]
Unchecking Estimate space from SfM solved this problem for me, although I'm not sure why. It could be because I used .ply as the inner file extension in the structure from motion node.

**Comment by crissi-x3** [comment]
> Unchecking Estimate space from SfM solved this problem for me, although I'm not sure why. It could be because I used .ply as the inner file extension in the structure from motion node.

this did work for me too

**Comment by bachirelkhoury** [comment]
Having the same issue here. How did you uncheck SfM? I can't seem to find that option in the UI.

**Comment by NimbleDiscoveries** [comment]
Hey try it outside

**Comment by abhinavkolla99** [comment]
Can you help me out in  uncheck the sfm please

**Comment by pcox** [comment]
To uncheck SfM make sure to click "Advanced attributes" in the three vertical settings of the node panel.

**Comment by ljcool2006** [comment]
> Unchecking Estimate space from SfM solved this problem for me, although I'm not sure why. It could be because I used .ply as the inner file extension in the structure from motion node.

Still doesn't work.
