### ISSUE TITLE
Severe Surface Pitting

### ISSUE THREAD

**Issue by libraryx** [alicevision/meshroom#470]
I am desperately trying to help someone do a recreation of a bust of her grandfather, but I am having a ton of trouble getting solid results. My last few runs came out with intense deformities. 

I masked the background out of each image, but I do have the originals as well. Though, those images resulted in no results other than a small cluster. 

Any help would be very appreciated. 

![Bust Meshroom - Face](https://user-images.githubusercontent.com/50721699/57893209-e1796400-77f6-11e9-888b-3adad24eac0c.png)

![Bust Meshroom](https://user-images.githubusercontent.com/50721699/57892611-644cef80-77f4-11e9-9a95-7d9b50327c07.png)

[Bust Masked - Color Corrected.zip](https://github.com/alicevision/meshroom/files/3189311/Bust.Masked.-.Color.Corrected.zip)

**Comment by natowi** [comment]
The white, reflective surface is difficult to capture.
You need to add some structure or markers to the bust or project a pattern on the surface.
