### ISSUE TITLE
Describer Types

### ISSUE THREAD

**Issue by QuentinJouanisson** [alicevision/meshroom#471]
Hi there.
I'm using Meshroom along with a DSLR camera for game asset creation, and I was wondering what is the workflow with describer types.

I understand that you can pick multiples describers at once, but what is the point of doing so ? Are they running in parallel ? Are the results mixed ? 
Also, if I run a specific algorithm for features extraction (for instance) Do I need to use the same algorithm for the next node ? Does it changes data types as well ?

**Comment by fabiencastan** [comment]
Hi,
You can choose to use one or multiple describer types. If you use multiple types, they will be combined together to help get results in challenging conditions.
**The values should always be the same between `FeatureExtraction`, `FeatureMatching` and `StructureFromMotion`.**
The only case, you will end up with different values is for testing and comparing results: in that case you will enable all options you want to test on the FeatureExtraction and then use a subset of them in Matching and SfM.

**Comment by QuentinJouanisson** [comment]
Thank you a lot !
