### ISSUE TITLE
Problems with texturing after re-topology

### ISSUE THREAD

**Issue by herosnowman** [alicevision/meshroom#474]
Basically when I put re-topo-ed mesh(from blender) back to meshroom, it has wrong orientation. I've experimented with different export settings but can't find the right one. Can any blender user help me?

**Comment by herosnowman** [comment]
SFM points show where the mesh should actually be
![image](https://user-images.githubusercontent.com/28194972/57982355-0109ca00-7a4d-11e9-980d-21a97eda9870.png)

**Comment by keke0003** [comment]
Import the obj from Meshroom and don't change any import settings. It is important that you don't transform the model in any way inside Blender it needs the exact same rotations/location/scale values. I always parent the mesh to an empty and transform this for clean-up purposes.
For the Export make sure that you clear the transforms of the empty (alt+r, alt+s, alt+g) and select only the model. In the obj export settings uncheck everything except for  "Selection Only" and "Object as OBJ Objects" (also check "Include UVs" if you unwrapped the model).
This always works for me.

**Comment by herosnowman** [comment]
@keke0003 Thank you so much! It fixed all my problems!
