### ISSUE TITLE
cameras showing up in incorrect locations

### ISSUE THREAD

**Issue by hargrovecompany** [alicevision/meshroom#475]
I have 60 cameras, on 12 columns, 5 each.  Numbers are  in order, starting at 101.jpg up to 105.jpg on column one, 106 to 110 on column 2, etc.    It appears to me that in this example a couple of the cameras were located based on what are really background features instead of the foreground subject.  But I'm guessing.  
I haven't done anything more than load the images and process.  The exif has no camera serial number for any of the cameras.  I have no clue how to use the rig calibration module.  I don't know that location tags would work, as I have projectors displaying an image and I'm assuming the pattern would make it impossible for the software to recognize tags.  

Links to image set and mg file:

https://www.dropbox.com/sh/oyl6f4vke1ubx7o/AAD-hrTh9XCHd7kF_5nk6foba?dl=0

https://www.dropbox.com/s/pqjapz84gt9uevs/badcamlocations.mg?dl=0

**Comment by natowi** [comment]
Try to optimize the [Meshroom settings](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters) and see if you get more matches without the structured light. Tags are not yet supported in the binary release.

**Comment by hargrovecompany** [comment]
I'll try guided matching and brute force....
If I can't get the matching to line up that way, I'm thinking I should add
some starts, circles, squares, etc. in the background area so that maybe
the software can distinguish one side of the booth from the other.
Interestingly, when I put two people together in the booth, they occupy the
majority of every frame and it works like a charm.
I'll alter the projected image pattern as well...
I've had zero luck when attempting to process the normal images...If the
things I mentioned above don't help, I'll give that another shot.

Of note...I compared to Reality Capture...Meshroom has been hands down
providing better results as I've been throwing problematic image sets in
for processing.

**Comment by natowi** [comment]
Adding some structure to the scene is a good idea. Also try to avoid Lens Flare (use indirect lighting) and unsharp images.
Your subject should take most of the space in your image frame.

**Comment by hargrovecompany** [comment]
Reorienting all of the cameras that were in landscape but capturing, for example, lower legs....the subject was taking up only a small part of the screen...made a HUGE difference.  it appears to me that the software treated the background as the legitimate features, and attempted to line up what was in the majority of the screen.  With the subject occupying the majority of every image the alignment issues have disappeared.  I was concerned that the software would choke with different orientations but it had no problem.
