### ISSUE TITLE
 I can not get the final mesh preview

### ISSUE THREAD

**Issue by Hopulka** [alicevision/meshroom#477]
Please I need help. I am really confused. I tried a lot of times to create a mesh with different photo objects (stones, cars, stump), but it is still the same. After whole long process and double click on texturing, I clicked Load model an it is nothing happened. I can not get the final mesh preview. What I do wrong? Any idea? Thank you!

**Comment by natowi** [comment]
Are you using the 2019.1 version? Sometimes it takes some time to load the model in the 3d viewer. Check the Texturing folder for the OBJ, open the OBJ in [Meshlab](http://www.meshlab.net/).

**Comment by Hopulka** [comment]
Thank you for your answer. I do not use 2019.1 version, but I have to use version 2018 because of windows 7. When I try to open in Blender, I see the same like in Meshroom. Textures are weird and object is not drawn correctly. In every video that I saw is double-click in the end of process (texturing) and everyone have awesome object. When i double-click on texturing, nothing happened (still see only many of squares) and in blender is object deforming. I don't know where is problem.

**Comment by natowi** [comment]
In the 2018 version there should be a button in the 3d viewer when the reconstruction is complete. 
![loadm](https://user-images.githubusercontent.com/8138537/58243866-ca37fa80-7d51-11e9-87e4-b1ec5b380de1.JPG) (Double clicking on the node does not work in the 2018 version).
The Meshroom 3d viewer can be quite slow in loading the Mesh.

Depending on the size of your Mesh, your 8GB Ram might be a limiting factor. 
Open the Texturing folder (right-click on the node). It should contain the texturedMesh.obj, mtl and png.
Open the OBJ in [Meshlab](http://www.meshlab.net/).

**Comment by jingzhouhuang** [comment]
I don't have this "Loda Model " node  when the project is over,but I can open the project.obj file in 3D software. You can try if you meet this question too.

**Comment by natowi** [comment]
@jingzhouhuang Double click on the Texturing node to load the model in the viewer.
(Double clicking on nodes works for many other nodes, too)

**Comment by cydoroga** [comment]
Hi!
I am using Ubuntu 18.04.2 and Meshroom 2021.1.0
The dataset of 65 photos was taken from here:
https://www.3dflow.net/3df-zephyr-reconstruction-showcase/
And I can not see any mesh or texturing of the reconstructed model.
From the list on the right, it seems, that the mesh was loaded though.
The installation was done by extracting the tar archive from the web page.
CPU: Intel Xeon (32 cores), 4 geforce gtx 1080 ti GPUs, 256gb ram.
Thank you!
![Снимок экрана 2021-07-13 в 13 02 26](https://user-images.githubusercontent.com/14786986/125434592-8a965ce1-c4dc-4979-bfc2-81eacfd94b71.png)

**Comment by natowi** [comment]
@cydoroga looks like the StructureFromMotion results overlay your mesh. Disable or remove all other layers except the Meshing layer. If it still does not show up, double click on the Meshing node. Check the cli window for any error messages.
