### ISSUE TITLE
Meshroom general problems

### ISSUE THREAD

**Issue by IvanMN7** [alicevision/meshroom#478]
When I put the images in Meshroom it doesn't make all the cameras and the result has a bad mesh with a lot of errors. How can I get better results?

Also the sensor weight of huawei mate 10 is not listed on camerasensor.db. I tried writing this line:"Huawei;Huawei Mate 10;5.0" but it doesn't work.

GTX 1050Ti / 8Gb RAM DDR3 / i5-2400 CPU 3.1Gz

**Comment by natowi** [comment]
Huawei Mate 10 has a 1/2.9″ BSI CMOS color sensor, 5 or 4.96 should work.
Check the EXIF info of your images and use the _camera_ and _make_ information provided there.
--
With 8GB RAM, you will need to reduce the _Max Points_ to fit your RAM limits, so you might want to consider upgrading your Ram

Here are some tips on how to [optimize reconstruction parameters](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters)
