### ISSUE TITLE
ERROR: unrecognised option '--ini'

### ISSUE THREAD

**Issue by Anass012** [alicevision/meshroom#479]
I'm running the **Run_07_DepthMap** function, and it gave me the following error : 
 
ERROR: unrecognised option '--ini'

it appears the error is with os.system(cmd), but i'm not sure.

I can't figure out how to resolve this error, can I have some help on this? 
Thank you

**Comment by Nicolaj-J** [comment]
Hello.

I have the same problem. Did you find a fix for it?
