### ISSUE TITLE
Working with images from a Bebop drone

### ISSUE THREAD

**Issue by mobarre** [alicevision/meshroom#482]
Hi,

I'm currently working on a dataset of about 1000 photos taken with 2 things: a Gopro and a video from a bebop drone.
No problem with the images from the gopro. It actually works really well. The Bebop drone video is another story, at least with meshroom.
When you make a video with a Bebop (and I assume most drones), the images from the sensor are cropped, which allows to pan the view without any moving parts. once you got the video, you just split it into a series of images with VLC for instance and you can start working.
The thing is that the images you'll have will not have any prior known focal length.

Is there any way to work with this with meshroom ? do the camera parameters have to be known or did I miss something in the options. I know that colmap handles that just fine, but I could not find any way to do the same with meshroom.

Cheers,
Marc-Olivier Barre.

**Comment by mobarre** [comment]
Additional note:
I know that if I take full frame photographs instead of a video, I could get nice EXIF data and probably work my way around the fact that no one seems to know the sensor size of a bebop drone camera, but, there's a but:
Most of the projects I'm working on are either houses with a nicely sized garden, or whole complexes of several acres. The difference between taking one photo at a time and just shooting a video is battery usage. You go much faster just filming the ride around and thus have less of  need to recharge the battery before you can continue working.

**Comment by natowi** [comment]
Import the image series to Meshroom and start the reconstruction. Worked for me.

**Comment by mobarre** [comment]
ok, well I'll try again but as far as I remember, this is what I did. and since there was no exif data, the images where just filtered out because not associated with anything in the sensor database.
I'll give it another shot...

**Comment by mobarre** [comment]
It seems you are right. I must have tried with an older version... works fine on 2019.1.

I'll play around ith my dataset to see how meshroom handles it compared to colmap. Now we're playing :)

**Comment by fabiencastan** [comment]
Good to hear! It would be nice if you have some results that you can share at the end ;)

**Comment by mobarre** [comment]
@fabiencastan I'd be glad if you're interested. Could make a nice demo of house scanning :) Still a lot of work to do though, and the challenge is that my dataset is not perfect and has not been made in one shot. Some elements have moved in between sessions... it's a house, it's a living thing :) masking helped with colmap a little bit. Might try the masking hack with meshroom (paint it black) :)
