### ISSUE TITLE
CCTag Workaround

### ISSUE THREAD

**Issue by Albanbrice** [alicevision/meshroom#483]
Being pretty unconfortable as a newbie with compiling or building from source, and therefore not able to include the CCTag support and OpenCV dependencies, I am looking for any workaround to register the SFM output to a local coordinate system (properly scaled and oriented) from which I could keep on working the whole process (densification, meshing, retopo, etc). Is there anyway to adapt a 4x4 matrix given i.e. by CloudCompare or Meshlab to the SfMtransform node? Thanks for any hints. Regards

**Comment by natowi** [comment]
Here are two nodes that might be useful:
- the SfM Alignment can align a SfM file to another scene.
- the SfM Transform node can apply a given transformation camera as the origin of the coordinate system. It also supports XYZRS transformation.

**Comment by Albanbrice** [comment]
Ok thanks for the quick answer. Actually the SfM Transform node may help a bit, but not totally as its transformation method deals only with a 1-axis rotation. Therefore I couldn't managed to horizontally align a turntable 'scan'. One has to pay attention as well to the syntax of this command (value separated by , and ;) and to the fact that the scale factor is by default set to '10'.
