### ISSUE TITLE
CPU load only on early nodes (possibility to include CUDA?) 

### ISSUE THREAD

**Issue by Airwrecka3D** [alicevision/meshroom#485]
since my latest meshroom project is already running for 2 days straight I was wondering if the GPU could assist by computing the earlier nodes. The GPU only kicks in on less time consuming nodes 

Did anyone tried something in that regard already? It would help to speed things up a bit, cause computing 1 chunk takes around 3hrs in FeatureMatching on my 5GHz quadcore.

Another question: does meshroom scale well with CPU core count? The new Ryzen processors are looking tempting

**Comment by ChemicalXandco** [comment]
FeatureMatching has a CUDA implementation for sift, enable it by unchecking `Force CPU Extraction`.

**Comment by Airwrecka3D** [comment]
I already tried that but somehow the GPU load still stays around 0 (only sift is checked as describer)
