### ISSUE TITLE
Documentation improvement: Chaining 2 SfM nodes

### ISSUE THREAD

**Issue by mobarre** [alicevision/meshroom#486]
On the wiki, here: https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters it is suggested that "Then, you can chain another SfM with the standard parameters, so the second one will try again to localize the cameras not found by the first one but with different parameters. This is useful if you have only a few cameras reconstructed within a large dataset."
Could an example (or a screenshot) be provided so one can understand how to connect the 2 SfM nodes in order to do that ?
Is it simply a matter of piping the output of a first SfM node into the input of another (highly doubt that it is so simple ;-)  )

**Comment by skinkie** [comment]
@mobarre I wonder if wording means the pipeline you get when using "Augmenting" by adding extra images or it is literally chaining SfM. I'll try it out later today.

**Comment by mobarre** [comment]
Yes I wonder too. Although I have to report that I seem to have had some success yesterday night by just connecting the output of one SFM to the input of the next (not forgetting to connect also the features and matches directories).

It kind of looked like it worked for a first attempt. I did obtain more resolved cameras after the second pass.

A word from the author to confirm we did that right ? :)

**Comment by Baasje85** [comment]
For me this does not increase the number of reconstruction. 

![image](https://user-images.githubusercontent.com/51262792/58747724-7f179900-846f-11e9-9dc5-b4d1719c90c2.png)

**Comment by fabiencastan** [comment]
Yes, that's right.
But it only make sense if you use different parameters on each SfM. So usually more strict parameters on the first one to ensure that you reconstruct the more stable ones first, then do another one with default parameters to get the final reconstruction.

**Comment by fabiencastan** [comment]
To keep the graph more readable, you can connect to the input parameters of the first SfM for feature/matches folders.
