### ISSUE TITLE
GPU detection  failure: Archlinux - GTX1080 - driver's 430.14

### ISSUE THREAD

**Issue by mobarre** [alicevision/meshroom#487]
Hi,

Title says all. I could only find similar bug reports for Windows 10. Only solution I've seen so far is a driver update, but I'm already using latest driver anyways.
The error looks like this:
```
[17:02:51.271650][error] cudaGetDeviceCount failed: unknown error
[17:02:51.271682][info] Can't find CUDA-Enabled GPU.
```
Any hints on what might be wrong or what I should try ?

Cheers.

**Comment by fabiencastan** [comment]
I have no idea, your error comes directly from the initial call to cuda `cudaGetDeviceCount`. All the code is here:
```
    success = cudaGetDeviceCount(&nbDevices);
    if( success != cudaSuccess )
    {
        ALICEVISION_LOG_ERROR("cudaGetDeviceCount failed: " << cudaGetErrorString(success));
        nbDevices = 0;
    }
```
https://github.com/alicevision/AliceVision/blob/6734014372354f73cd9b1cd8aaf8456cb2672686/src/aliceVision/gpu/gpu.cpp#L23

I'm using a GTX1080 too, currently on Windows 10 without any issue.

On linux, as mention in the AliceVision [README.md](https://github.com/alicevision/meshroom/blob/develop/README.md), you may need to adjust the LD_LIBRARY_PATH to use the right libraries for the drivers:
```
On Ubuntu, you may have conflicts between native drivers and mesa drivers. In that case, you need to force usage of native drivers by adding them to the LD_LIBRARY_PATH: LD_LIBRARY_PATH=/usr/lib/nvidia-340 PYTHONPATH=$PWD python meshroom/ui You may need to adjust the folder /usr/lib/nvidia-340 with the correct driver version.
```

**Comment by mobarre** [comment]
Ok, so it's not my card detection. run from the same session  run meshroom:
[mobarre@steamos ~]$ nvidia-debugdump --list --verbose
Listing all GPUs.
Found 1 NVIDIA devices
	Device ID:              0
	Device name:            GeForce GTX 1080   (*PrimaryCard)
	GPU internal ID:        GPU-4890a3cc-8c71-4e49-2084-4252f1ea4a79

Now I do have an idea. Archlinux package depends on the cuda package, which defaults to latest version on arch. Latest available is cuda 10.1.
I'm using meshroom-bin. The binaries are downloaded from github (so it's the official ones from here). Have your linux binaries been compiled with an earlier version of cuda by any chance ?

**Comment by mobarre** [comment]
ok, my bad, this has nothing to do with the meshroom binaries. the dependency is on alicevision lib. Good thing with archlinux, you can tweak your deps. Ill give a shot to cuda 8 and 9

**Comment by mobarre** [comment]
CUDA 9.0 works. I'm guessing 9.1 will work fine too. it's CUDA 10.1 the issue just like with colmap. I'll report to the maintainers of the AUR package.
Maybe we should add this to a readme of a requirements file ?

**Comment by mobarre** [comment]
My issues kind of continue, bu might be unrelated to the choice of cuda version:
When feature extraction (sift) makes use of my GPU, the processing freezes after the first session. it's like the software isn't detecting that the aliceVision_featureExtraction process has finished the first batch.

Some more useful info:
alicevision is version 2.1.0
meshroom is 2019.1
I settled for cuda 9.2 and magma 2.5.0
system is still archlinux
nvidia drivers is 430.14

I tested using the monstree dataset (full), and the default pipeline to the exeption of the forceCpuExtraction which is set to false (it works just fine with CPU).

no nouveau drivers installed, so no problem with the library choices there I guess.

Should this be a different issue altogether ?

This might be a linux specific bug... ideas ?

**Comment by fabiencastan** [comment]
The "forceCpuExtraction" is set to true by default as the GPU extraction is still experimental and has known issues.

**Comment by joseandres42** [comment]
Same problem here on linux with a GTX1060.
alicevision 2.2.0
meshroom 2019.2.0
cuda 10.1.243
magma 2.5.1
nvidia drivers 430.40
kernel version 5.2.10

**Comment by joseandres42** [comment]
Installing cuda-9.2 solves the issue, maybe there's something cuda 10 does differently.
