### ISSUE TITLE
How to stop a node?

### ISSUE THREAD

**Issue by AravindChandradoss** [alicevision/meshroom#488]
I am new to meshroom. 

Currently, _Texturing_  node is running. I need to know how to cancel/stop/terminate the process.  
I ran of out memory and so, I had to hard-reboot my laptop. When I reopened the file, the _Texturing_  node is running again. 

Any command? settings?

Thanks

**Comment by natowi** [comment]
Before starting Meshroom, delete the Texturing node folder from your project files. Now you can open your project, adjust the Texturing node (lower resolution) and compute the node.
