### ISSUE TITLE
Docs: Is a more dense point cloud required when camera reconstruction is "perfect"?

### ISSUE THREAD

**Issue by Baasje85** [alicevision/meshroom#490]
When a describer preset is increased, a higher number of features can be extracted and potentially be matched between images. In the SfM step a more dense point cloud can be observed. Since the construction step has been done, is a more dense point cloud required to get a better estimate for the depthmap and texturing? Or are in these steps other properties of the input image used, regardless of the number of features extracted?

**Comment by fabiencastan** [comment]
The density of the point cloud will not improve the dense part of the pipeline (depth map + meshing) in itself. The number of features reconstructed may improve the localization/calibration of the cameras and thus may improve the dense reconstruction indirectly.
The dense reconstruction only use the camera pose/calibration. So the point cloud from the SfM is not used directly in the dense reconstruction (except if you enable "Add Landmarks to the dense point cloud").

**Comment by Baasje85** [comment]
@fabiencastan thanks for this clear answer. Happy to contribute it to the Google Docs manual and the wiki here!
