### ISSUE TITLE
Is there a more optimal node setup for smaller scale objects?

### ISSUE THREAD

**Issue by herosnowman** [alicevision/meshroom#492]
Thanks for passing by my question!
My question is really short: Has someone found more **optimal/faster** node setup for smaller scale object scanning?
![image](https://user-images.githubusercontent.com/28194972/58764631-4a403a80-8572-11e9-9093-abca6f02a9ed.png)
![image](https://user-images.githubusercontent.com/28194972/58764636-5c21dd80-8572-11e9-855e-e04320088270.png)
For example this tree scan, I don't really need **that detailed** scan. Wich node's settings can be changed in order to get the final mesh **faster?**

**Comment by natowi** [comment]
Have a look at [Reconstruction-parameters](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters) and [Draft-Meshing](https://github.com/alicevision/meshroom/wiki/Draft-Meshing)
