### ISSUE TITLE
[Bug] Chained SfM result does not appear in 3D viewer (resolved with workaround)

### ISSUE THREAD

**Issue by skinkie** [alicevision/meshroom#493]
Release 2019.1.

When chaining two SfM with different parameters, the second SfM does not generate an entry in the 3D viewer. A similar problem appears when opening a previous project, where only the last SfM is shown (all previous SfM are ignored). Is it possible to add a result manually to the 3D viewer to workaround the issue?

![chained](https://user-images.githubusercontent.com/502394/58778689-d9ca0580-85d3-11e9-8b66-e6abb97f0e25.png)

**Comment by natowi** [comment]
Did you try double-clicking on the node?

**Comment by Baasje85** [comment]
When opening a previous project, double-clicking on each previous SFM-node does add to the point cloud, provided they weren't already mentioned below 'scene'.

**Comment by skinkie** [comment]
@fabiencastan should this bug be logged somewhere with respect it does not automatically add the result to the scene? Additionally the documentation component of double clicking on the node to get the result in the scene was also not that obvious.
