### ISSUE TITLE
Getting more accurate results in 2018.1 vs 2019.1

### ISSUE THREAD

**Issue by barefoots** [alicevision/meshroom#495]
**Hello Alicevision Team,**

Thankyou for all your hard work on such a fantastic piece of software! Thankyou for fixing the bug related to retexturing a reimported mesh with new uvs.

The problem i am running into is related to the SfM point cloud reconstruction.
In Meshroom 2018.1 I threw in photos from my Motorola G4 Plus mobile phone and the results were great & accurate, without any tweaking. 

In 2019.1 the same photos produce a very different result. The point cloud looks to be sucked in towards the middle. Outlying objects are close and on top of each other. The depth calculations are not accurate. The final model looks smooshed around in places, or completely different when compared to results from 2018.1. 

I am wondering what has changed between the versions to have such different outcomes?
And more importantly, _what do I need to do to_ get the kind of results I was getting from 2018.1 without having settings that greatly increase the processing time? 

Attached are screen captures of the SfM from each version of Meshroom using the same photo sets & default settings for all nodes. 

**2018.1.** - Point Cloud (Cloud is spread out accurately accordingly to reality) 
![2018_1_](https://user-images.githubusercontent.com/46009756/59004543-4b68b480-885d-11e9-9894-1e23f68653d5.jpg)
.
**Textured Mesh Result**
![2018_1_model_](https://user-images.githubusercontent.com/46009756/59004620-97b3f480-885d-11e9-9e4e-d95a98e96636.jpg)

**2019.1.** - Point Cloud (Cloud is sucked in closer to centre. Squished together)
![2019 1_](https://user-images.githubusercontent.com/46009756/59004576-6804ec80-885d-11e9-81b4-b030db58bdb3.jpg)

Could not get a final textured model from this photo set. Depth Map would crash at first chunk. 

.
**Example 2.**
2018.1 - Textured Mesh (Tree Trunk)
![2018 1_tree_](https://user-images.githubusercontent.com/46009756/59004803-56701480-885e-11e9-9233-9e650b3ed803.jpg)

**2019.1** - Textured Mesh (Tree Trunk)
![2019 1_tree_](https://user-images.githubusercontent.com/46009756/59004847-81f2ff00-885e-11e9-931d-2d3f0da099c9.jpg)

Thanks in advance for your help and thank-you again for all your hard work.
Kind Regards,
Brendan

**Comment by natowi** [comment]
I´ve read about this problem (here on github or in the google group). When I remember correctly there were some changes introduced in the 2019.1 release that led to different results/behaviours for the same dataset compared to the 2018.1 release. 
The 2019.2 release is around the corner which includes improvements and bug fixes.

**Comment by fabiencastan** [comment]
@barefoots Thanks for your precise report. I'm quite surprised by your results.
Have your done these 2 reconstructions with the default parameters?
Could you share your dataset to see if we can reproduce it?

**Comment by natowi** [comment]
Something changed between 2018.1 and 2019.1.
This are the SfM landmarks of one of my datasets:
Dataset in 2018.1: landmarks: 24570
Dataset in 2019.1: landmarks: 31685
In this case I get more landmarks in the 2019.1 release, but I also can remember getting fewer landmarks for some datasets.

**Comment by fabiencastan** [comment]
The choice of the initial image pair may change from one run to another. In that case, you can start the reconstruction from a very different part of the scene which may provide very different results.

This problem is independent from the release version, you can recompute the same dataset with the same version and get different results. On most datasets the output will be almost the same but on some datasets were there are multiple candidates for the initial pair with similar scores, you may start from a very different place and get very different results.

The question is therefore to know, if the issue reported here comes from this problem or if there is really a difference between the 2 releases.

And in the long run, of course, improve the repeatability of the initial pair choice which is already somewhere in the todo list.

**Comment by barefoots** [comment]
Hey guys,

Thanks for your quick responses. 
I am happy to provide a link to my photos via this dropbox link. [https://www.dropbox.com/sh/8jc3fl15drnhelp/AAAxMDZQUptwy-TDFfKEseXLa?dl=0](url)

There are 3 sets of photos. 
Both the images for the above examples and a _extra set_ of a cliff I tried today. 
I have included screen shots of the cliff mesh from both versions in the photo folder. 
Also in the Tree folder I have provided screen shots of each nodes attributes from both 2018 & 2019. I know you don't need to see each node but put them in anyway.

Hope it helps.
Thanks again. 

Kind Regards,
Brendan

**Comment by yann-lty** [comment]
It seems that something went wrong with the sensor database for this specific model between 2018.1 and 2019.1.

**Metadata from images**
Make: Motorola
Model: Moto G (4)

**2018.1 cameraSensors.db**
Motorola;Moto G (4);**6.06**  => used value (correct)
**2019.1 cameraSensors.db**
Motorola;Moto G;6.06   
Motorola;Motorola 4;6.06;   
Motorola;Motorola Moto G4;**3.67**;devicespecifications  => used value (not correct)
Motorola;Motorola Moto G4 Plus;6.06;devicespecifications

If you open the database file and replace one of the first 2 lines with - or add -
`Motorola;Moto G (4);6.06` 
and re-create a project with your images it should fix your problem.
You can access the sensor database file from Meshroom:
![image](https://user-images.githubusercontent.com/1674646/59102759-5ee35080-892d-11e9-885e-64957dcacdcb.png)
See the [wiki ](https://github.com/alicevision/meshroom/wiki/Add-Camera-to-database)page for more details.
Let use know if this works for you, we'll fix that for the next release!

**Comment by barefoots** [comment]
@fabiencastan @yann-lty 
Hey guys,

Thanks! The correction to the device specification worked beautifully!! 

Thank-you so much for checking it out for me and figure out what was going wrong! I have re-run the previous data sets and some others done in the 2018 release....they have come out better and faster than before! So cool, even though they are photos from a budget phone.

I look forward to seeing how you continue to improve & update this excellent software.
Thanks again,
Kind regards,
Brendan

![Screenshot_1](https://user-images.githubusercontent.com/46009756/59146971-62173300-8a38-11e9-9fd4-5804d82f6cc9.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/46009756/59146972-62173300-8a38-11e9-9570-1f07d9e2211b.jpg)
