### ISSUE TITLE
Progress bar stuck on orange at end

### ISSUE THREAD

**Issue by trburns2007** [alicevision/meshroom#498]
I've tried resetting the previous and following nodes and deleting cache but when I restart the meshing node the bar goes straight to the end and just stays there

**Comment by skinkie** [comment]
If you click on a node, on the right bottom part of the screen you have attributes and log. If you click on log, you see 'chunks'. You might want to go to the last chunk with a different color to check what happened.

When you mention "removed cache" do you mean right click on the node, and remove data, or do you mean removing the directory on the filesystem?
