### ISSUE TITLE
Publish node not saving texture file

### ISSUE THREAD

**Issue by jgwill** [alicevision/meshroom#500]
Hi,
I am observing that the publish node do not export the created texture file.
see attachement:
regards,

![issue-publish-not-copying-texture-file](https://user-images.githubusercontent.com/23141173/59160355-e900f580-8aa2-11e9-9a2f-c6bca6fdf66f.JPG)

**Comment by natowi** [comment]
Have a look at your log for this node in the Meshroom GUI and the Meshroom CLI in the background to get more information on what went wrong.

**Comment by jgwill** [comment]
I will have a look. I am  not in front of the computer but I think the
issue happens when it’s an EXR image output that it does not get copied.
Like with png files it did...

**Comment by jgwill** [comment]
Am I understanding that it was fixed and next release will works ? :) :)
Here are the log and screenshot of the nodes.  It shows the exr not copying.
best regards


![issue-meshroom-publish-texturing__190620_texture](https://user-images.githubusercontent.com/23141173/59858690-72d57c00-9349-11e9-97ea-f725339c14ed.png)


![issue-meshroom-publish-texturing__190620_log](https://user-images.githubusercontent.com/23141173/59858583-3f92ed00-9349-11e9-8c84-6c488b0cc12b.png)
![issue-meshroom-publish-texturing__190620](https://user-images.githubusercontent.com/23141173/59858584-3f92ed00-9349-11e9-9c40-350a6c182347.png)

**Comment by fabiencastan** [comment]
Yes, we merged a fix, so it will be in the next release.

**Comment by jgwill** [comment]
Awesome:)
