### ISSUE TITLE
Meshroom not use gpu?

### ISSUE THREAD

**Issue by trburns2007** [alicevision/meshroom#502]
I have yet to see meshroom use any of my GPU. Only 100% of my CPU. Is this normal?

**Comment by skinkie** [comment]
Currently only some parts of the pipeline can use an Nvidia GPU via CUDA. For example the second step "feature extraction" when  SIFT is selected. In the logs you would read that it is using the GPU. If AKAZE is selected it would be computed over the CPU.

**Comment by natowi** [comment]
In FeatureExtraction disable "Force CPU Extraction" to use the GPU for this node. The GPU code is (at the moment) not optimized to utilize all available ressources.

**Comment by NotErikUden** [comment]
How do I turn **--forceCpuExtraction** to **false** when using Meshroom's GUI? It's not something I can change as an attribute in the FeatureExtraction node.

**Comment by skinkie** [comment]
@NotErikUden 
![image](https://user-images.githubusercontent.com/502394/99146450-9a349380-2678-11eb-8b68-f12b9f80d33a.png)
![image](https://user-images.githubusercontent.com/502394/99146454-a3256500-2678-11eb-9a52-6872b7d7db66.png)

**Comment by NotErikUden** [comment]
Thank you so much! All is resolved. (Petition to remove "advanced attributes" button. We're using Meshroom, we're not amateurs! :D)

**Comment by natowi** [comment]
> Thank you so much! All is resolved. (Petition to remove "advanced attributes" button. We're using Meshroom, we're not amateurs! :D)

@NotErikUden Most Meshroom users are in fact amateurs and hiding the advanced options reduces questions regarding settings that require in-depth knowledge of the used algorithms (and no real benefits for the user in most of the cases). The advanced options are intended for developers to test the results for specific parameters. Some features like GPU extraction are not stable and can cause issues, therefore they are hidden for the casual user until they are production ready.

**Comment by rutvikokate** [comment]
> How do I turn **--forceCpuExtraction** to **false** when using Meshroom's GUI? It's not something I can change as an attribute in the FeatureExtraction node.

How to turn this off in command line?

**Comment by ChemicalXandco** [comment]
@rutvikokate are you using `meshroom_compute` or `meshroom_batch`?

**Comment by rutvikokate** [comment]
> @rutvikokate are you using `meshroom_compute` or `meshroom_batch`?

meshroom_compute

**Comment by ChemicalXandco** [comment]
@rutvikokate you can add the argument `--paramOverrides FeatureExtraction:forceCpuExtraction=0`

**Comment by rutvikokate** [comment]
> @rutvikokate you can add the argument `--paramOverrides FeatureExtraction:forceCpuExtraction=0`

Okay thanks!

**Comment by WellTung666** [comment]
> @rutvikokate are you using `meshroom_compute` or `meshroom_batch`?

How to it off when using meshroom_compute ?  thanks!

**Comment by ChemicalXandco** [comment]
@WellTung666 you must change the setting in the meshroom file (.mg). You can do it in a text editor but I recommend doing it in the meshroom GUI if possible.

**Comment by WellTung666** [comment]
> @WellTung666 you must change the setting in the meshroom file (.mg). You can do it in a text editor but I recommend doing it in the meshroom GUI if possible.
Thanks！But i need to run on server.Or do you koew how to turn it  off using meshroom_photogrammetry(Meshroom-2019.1.0).

**Comment by ChemicalXandco** [comment]
> Meshroom-2019.1.0

Is there any reason why you can't use 2021.1.0? That is the latest version which has many improvements.

> do you know how to turn it off using meshroom_photogrammetry

Please look at [my comment above](https://github.com/alicevision/meshroom/issues/502#issuecomment-807130647) but it only works in versions 2020.1.0 and up.

**Comment by WellTung666** [comment]
> > Meshroom-2019.1.0
> 
> Is there any reason why you can't use 2021.1.0? That is the latest version which has many improvements.
> 
> > do you know how to turn it off using meshroom_photogrammetry
> 
> Please look at [my comment above](https://github.com/alicevision/meshroom/issues/502#issuecomment-807130647) but it only works in versions 2020.1.0 and up.

OK Thanks!

**Comment by busyBeaver1** [comment]
Hello. Im having a similar problem. @skinkie 's screenshots helped a lot with the FeatureExtraction step. But what about other steps? It still uses a lot of cpu, for example, on FeatureMatching. Maybe there are other options to use gpu on other steps?

**Comment by natowi** [comment]
GPU support can optionally be enabled for featurextraction and is required for depthmap. Other nodes do not have gpu support.

**Comment by Slyke** [comment]
Having the same issue.

I've added Meshroom to NVIDIA control panel:

![Image](https://github.com/user-attachments/assets/395a02a5-50e7-4c1b-a284-c9b02f0aa5c4)

I've turned off `dspsift` and turned on `sift`:

![Image](https://github.com/user-attachments/assets/24d0482a-7257-4ca8-8b5b-bb897a6aa927)

But my CPU is doing all the turn instead of my 4090 or 3080:

![Image](https://github.com/user-attachments/assets/a7dd8b96-c27a-4020-9c77-d26fe0bd4ec4)

**Comment by castelblends** [comment]
July 2026... and unfortunately this issue is still going ... I can't force it to use GPU. I'm in Windows 11 Pro v25H2 with a rtx3090.
