### ISSUE TITLE
Does anyone know why is this happening

### ISSUE THREAD

**Issue by IvanMN7** [alicevision/meshroom#505]
With the SFM activated:

![ProblemaMeshroom1](https://user-images.githubusercontent.com/50661711/59289082-8744b500-8c75-11e9-8640-4fb9ff5235fd.png)

And this with the texture activated:

![ProblemaMeshroom2](https://user-images.githubusercontent.com/50661711/59289088-8c096900-8c75-11e9-98b5-f5ed5f6a1248.png)

As seen in the Structure points, the object to which I took photos appears the structure with the points but at the time of doing the "load model" and with the texture does not appear the object, is broken.

Any solution?

**Comment by natowi** [comment]
Your sheep has few destinct features. The table/chair consumes 90% of your image, so most of your sheep (the areas with low maches) is filtered out.
Take some closeup images and try again. The object of interest should fill most of the image frame.

**Comment by IvanMN7** [comment]
> Your sheep has few destinct features. The table/chair consumes 90% of your image, so most of your sheep (the areas with low maches) is filtered out.
> Take some closeup images and try again. The object of interest should fill most of the image frame.

I did what you told me and now I have another problem:

When I try to insert some images without background in SFM(StructureFromMotion) section this error apears me: 
Aborted (core dumped)

This is the Log:

Program called with the following parameters:
 * describerTypes = "sift"
 * extraInfoFolder = "/home/nube7/Escritorio/Meshroom/robot3(studio)/MeshroomCache/StructureFromMotion/4f06d43ece206e6f3c753b1fee1fa555fa7c3f7f"
 * featuresFolders =  = [/home/nube7/Escritorio/Meshroom/robot3(studio)/MeshroomCache/FeatureExtraction/fa4d2043c60d9ed83166e317d360b5b85f8dba18]
 * initialPairA = ""
 * initialPairB = ""
 * input = "/home/nube7/Escritorio/Meshroom/robot3(studio)/MeshroomCache/CameraInit/2b0316e9aa38fd9274065bcd14f3d389db0b2b9e/cameraInit.sfm"
 * interFileExtension = ".abc"
 * localBAGraphDistance = 1
 * localizerEstimator =  Unknown Type "N11aliceVision16robustEstimation16ERobustEstimatorE"
 * localizerEstimatorError = 0
 * localizerEstimatorMaxIterations = 4096
 * lockAllIntrinsics = 0
 * lockScenePreviouslyReconstructed = 0
 * matchesFolders =  = [/home/nube7/Escritorio/Meshroom/robot3(studio)/MeshroomCache/FeatureMatching/8f6d0684673917cd64e90a40a32aed72b683b7e1]
 * maxAngleInitialPair = 40
 * maxNumberOfMatches = 0
 * maxReprojectionError = 4
 * minAngleForLandmark = 2
 * minAngleForTriangulation = 3
 * minAngleInitialPair = 5
 * minInputTrackLength = 2
 * minNumberOfObservationsForTriangulation = 2
 * output = "/home/nube7/Escritorio/Meshroom/robot3(studio)/MeshroomCache/StructureFromMotion/4f06d43ece206e6f3c753b1fee1fa555fa7c3f7f/sfm.abc"
 * outputViewsAndPoses = "/home/nube7/Escritorio/Meshroom/robot3(studio)/MeshroomCache/StructureFromMotion/4f06d43ece206e6f3c753b1fee1fa555fa7c3f7f/cameras.sfm"
 * useLocalBA = 1
 * useOnlyMatchesFromInputFolder = 0
 * useRigConstraint = 1
 * useTrackFiltering = 1 (default)
 * verboseLevel = "info"

Loading features
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
[11:19:02.885364][info] Supported CUDA-Enabled GPU detected.
***************************************************
[11:19:02.892875][info] Fuse matches into tracks: 
	- # tracks: 497
	- # images in tracks: 10
[11:19:02.892914][info] TrackLength, Occurrence
[11:19:02.892968][info] 	2	316
[11:19:02.892987][info] 	3	136
[11:19:02.892998][info] 	4	21
[11:19:02.893008][info] 	5	11
[11:19:02.893019][info] 	6	9
[11:19:02.893037][info] 	7	4
Automatic selection of an initial pair:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[11:19:02.918734][info] Initial pair is:
	- [A] view id: 1676625766, filepath: /home/nube7/Descargas/Robot 3 (studio)/IMG_20190612_101848.jpg
	- [B] view id: 2009016528, filepath: /home/nube7/Descargas/Robot 3 (studio)/IMG_20190612_101845.jpg
[11:19:02.918885][info] 141 matches in the image pair for the initial pose estimation.
[11:19:02.955958][info] Bundle adjustment start.
[11:19:02.956064][info] Start bundle adjustment iteration: 0
block_sparse_matrix.cc:81 Allocating values array with 35424 bytes.
detect_structure.cc:113 Schur complement static structure <2,3,6>.
detect_structure.cc:113 Schur complement static structure <2,3,6>.
[11:19:03.018721][info] Bundle Adjustment Statistics:
	- local strategy enabled: no
	- adjustment duration: 0.0404906 s
	- poses:
	    - # refined:  2
	    - # constant: 0
	    - # ignored:  0
	- landmarks:
	    - # refined:  246
	    - # constant: 0
	    - # ignored:  0
	- intrinsics:
	    - # refined:  0
	    - # constant: 1
	    - # ignored:  0
	- # residual blocks: 492
	- # successful iterations: 5
	- # unsuccessful iterations: 0
	- initial RMSE: 0.73318
	- final   RMSE: 0.64448
[11:19:03.018879][info] Remove outliers: 
	- # outliers residual error: 2
	- # outliers angular error: 0
[11:19:03.018901][info] Bundle adjustment iteration: 0 took 62 msec.
[11:19:03.018913][info] Start bundle adjustment iteration: 1
[11:19:03.019380][warning] Bundle Adjustment failed, the solution is not usable.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Initialization failed after trying all possible initial image pairs.
Aborted (core dumped)

**Comment by natowi** [comment]
Looks like we don´t get enough matches with default settings. You could [optimize the settings](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters). 
You could also add some removable colour to the uniform areas to provide better features for the algorithms.

**Comment by hargrovecompany** [comment]
refleaction on the table top.  you can see the different position of flourescent light reflection in every image.  get very close to the sheep so that it takes up most of the image.

**Comment by hargrovecompany** [comment]
also, after looking again it appears to me that the sheep might have some reflective surface.  So white points of reflected light would be in a different location on every one of the little "curls" of the sheep's wool.  And, I'm just guessing, i actually can't tell clearly if that's an issue.  If that's the case try setting up several lamps around the table....if it's still getting reflections, rub damp bar soap on your hands and smear all over the object then dust with baking powder.
