### ISSUE TITLE
Better matching lowering photo resolution

### ISSUE THREAD

**Issue by Botoni** [alicevision/meshroom#506]
Well, as title says, I've been doing some test with my smartphone camera, and with some sets of pictures at 4000x3000px meshroom only matches 2 pictures, I lower the resolution to 1920x1080 and voila, I get way better matchings. Is this to be expected? And if so, what is the reason?

If it's a bug or an unexpected behavior, i'll be happy to help with testing :)

**Comment by fabiencastan** [comment]
That's obviously not expected ;)
Are you using the default feature type SIFT?

Did you remove the metadata when changing the resolution? Maybe the sensor width for your device is wrong in the sensor DB:
https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/sensorDB/cameraSensors.db
You can look at the tooltips in Meshroom:
![image](https://user-images.githubusercontent.com/153585/59298548-0f818500-8c8b-11e9-9902-de449dbf101d.png)

**Comment by Botoni** [comment]
Well, metadata is intact after changing the resolution. I tried with sift, sift+akaze and sift+akaze+guided reconstruction, and describer presets from normal to ultra. Lowering the resolution almost always give better matching and more reconstruction points (but not necessarily better reconstruction). Only in one case the higher resolution pictures yield better results than the lowered ones.

Test were done with small data sets which are unlikely to give usable results.

**Comment by fabiencastan** [comment]
That's surprising. Could you send me your images with/without rescale to test and analyse it?
You can use the private mailing-list: alicevision-team@googlegroups.com
Best,

**Comment by Botoni** [comment]
Sure, the images were only for testing and I delete them regularly, but i'll send you the next image set that behaves this way ;-)

**Comment by natowi** [comment]
I read something similar on reddit. I will post the link when I find it.

**Comment by djoerg** [comment]
I know i'm a little late to this discussion, but have a gut feeling that this could be related to noise in the images. Especialy when you are using ooc jpegs, the in camera denoising could cause strange artifacts. I could imagine that the feature detection picks up the noise/artifacts as features. Scaling down the images greatly shrinks these artifacts (maybe to sub-pixel level) and let the feature detection pick up more 'real' features. 

Sadly, using lower resolution images leads to lower resolution depth-maps and so to lower res mesh.

I know, you can replace the input images used for feature detection in the PerpareDenseScene node before the DepthMap step. What i don't know is if it's possible to use different resultions. I guess that will not work, but i could be wrong.

If it's not possible, maybe bluring the input images by a 1 or 2 pixel gaussian-blur and replacing them with the unblurred images in the PrepareDenseScene step could work.

I never thought of that before reading this post. This could make the feature detection more robust and could also make it possible to use less features, speeding up the feature matching. I definitly must try this!

If it really helps, we should open a feature request to implement a blur function, or downscale mode, in the FeatureExtraction node!
