### ISSUE TITLE
Error in DepthMap

### ISSUE THREAD

**Issue by Aymdr** [alicevision/meshroom#511]
I have met a problem when the command line run in the DepthMap, 
It shows Error on node computation: Error on node "DepthMap_1(0)":  
and the log file is empty. 

so, I can not check the logfile to find why the error happen.
I try it in the software, it success. The logfile is same as the command line before the DepthMap stage.

**Comment by natowi** [comment]
Please provide details like OS, hardware and attach the complete CLI output.
