### ISSUE TITLE
[FeatureRequest] Camera projection on surface

### ISSUE THREAD

**Issue by Baasje85** [alicevision/meshroom#513]
While the grid typically does not align with the model (how could that be fixed?), I would like to see what surface area the camera would cover. Hence if a camera is tilted downwards, I would like to see the bounds of the surface. Preferable these should include lens distortion, but that could be a second enhancement.

The rationale is to see what surfaces have been covered, and what surfaced would need more overlap.

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/issues/256#issuecomment-709983331

Image overlay is now supported in the 2020 release: https://github.com/alicevision/meshroom/issues/1083

![sync-image](https://user-images.githubusercontent.com/8138537/96256354-ca750d80-0fb8-11eb-8529-07932b9ca50a.JPG)

**Comment by Baasje85** [comment]
great! I'll close this topic now

**Comment by natowi** [comment]
BTW you can double click on the computed PrepareDenseScene node to load the distorted images in the Image Viewer.
