### ISSUE TITLE
close-range tweaking

### ISSUE THREAD

**Issue by p30arena** [alicevision/meshroom#517]
This is my dataset

https://www.dropbox.com/s/q7fauei7xl8pviw/kooze.zip?dl=0

I set the Describer Preset to Ultra in FeatureExtraction
the describer type for FeatureExtraction and FeatureMatching and StructureFromMotion is set to sift
and I have to set the Downscale to 4 in DepthMap, otherwise, it crashes.

These are the final results

**3DF Zephyr Lite (with Close-Range Preset)**

![3df](https://user-images.githubusercontent.com/1261332/59660416-b56a4d80-91bd-11e9-88fe-46066f64408e.PNG)

**RealityCapture**

![open](https://user-images.githubusercontent.com/1261332/59660419-b8fdd480-91bd-11e9-8990-657691f469e5.PNG)

**Meshroom**

![me](https://user-images.githubusercontent.com/1261332/59660474-dcc11a80-91bd-11e9-9a4f-21b1722ac817.PNG)

### How can I tweak Meshroom to get a result similar to 3DF Zephyr?

...

**Comment by p30arena** [comment]
Ok, it seems that the StructureFromMotion was enabled in the view.

this is the result without it:

![me2](https://user-images.githubusercontent.com/1261332/59661261-a4224080-91bf-11e9-8fd3-563cbef0c812.PNG)


But I'm still eager to know any optimizations can be made to this type of close-range processing

...

**Comment by natowi** [comment]
See https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters
