### ISSUE TITLE
What is happening??!!

### ISSUE THREAD

**Issue by ZyroadGM** [alicevision/meshroom#519]
**Configuration**
Version 2019.1.0
Windows 10 
Python 3.6.6
I Have had StructureFromMotion not working for 4hours already and I have tried different modules but still same problem!
Pls help
![Screenshot (136)](https://user-images.githubusercontent.com/52015010/59803636-b94cbb80-92f4-11e9-9263-10164ed2f891.png)

**Comment by natowi** [comment]
Flat, single colored or glossy surfaces are difficult to reconstruct. You can try reconstructing with high/ultra [settings](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters). You could try powder some flour (easy to get & clean up) on your Pikachu to reduce the light reflections (of course you would need to retexture and smooth your Pikachu in a 3D modelling software later). Also, your subject should fill most of the image frame (in this case we are not interested in the environment).

**Comment by Dok11** [comment]
> Do not turn the object to capture different views with a well structured background!

Maybe Meshroom have support to create and/or use mask for captures (png24 for example)? It can be logic for cases like this.

**Comment by natowi** [comment]
@Dok11 See [#188](https://github.com/alicevision/meshroom/issues/188)
