### ISSUE TITLE
Help me understand the code 

### ISSUE THREAD

**Issue by gluttony47** [alicevision/meshroom#520]
I want to learn what is under the hood of meshroom. i understand the pipeline as described in the meshroom manual https://docs.google.com/document/d/17HYtYS1tvx053k3_nO6Z2GnP2R3cXMlGMN-1WIe3kJE/edit# (great job on the manual by the way). but i am stuck while reading the code as i am not sure where should i begin. can anyone please help? for example, you can say - "go read this code script xyz.py to begin understanding how to construct mesh from dense cloud points" 

thanks

**Comment by natowi** [comment]
When you start Meshroom, there is a CLI window in the background. You can run the nodes in Meshroom and check the CLI parameters to see how Meshroom calls up alicevision.

You can take a look at the [Meshroom GUI nodes](https://github.com/alicevision/meshroom/tree/develop/meshroom/nodes/aliceVision). The nodes basically call up the alicevision package functions located [here](https://github.com/alicevision/AliceVision/tree/develop/src/software) and [here](https://github.com/alicevision/AliceVision/tree/develop/src/aliceVision).
