### ISSUE TITLE
Camera Not reconstructed

### ISSUE THREAD

**Issue by ROKimaging** [alicevision/meshroom#521]
Firstly Hi,

I am not here as a developer but more a user, well hopefully!  I was looking to take a ContextCapture licence and then came across a video of how amazing Meshroom was and so I was quick to download and try it out.

I have tried to emulate a model I put together in ContextCapture but struggling to get the images to include in the model.  I get a red broken camera at the top right of the images with a message "Camera: Not Reconstructed".  I have searched on this matter and looked at the AddCamera to the database.  On this occasion I used a Nikon 3100 with a sensor size of 23.1mm, however this is already in the DB as per the explanation.  So the only other option is the StructureFromMotion.  But the explanation doesnt make sense to me and so I dont really understand where I am going wrong with the attributes.

The photos it chooses to ignore are also random.  I basically used the camera on a tripod and with the object on a table I rotated it around the Z Axis.  I also mounted the camera at 2 angles the first at approx 10deg to the horizontal and the 2nd at approx 45deg.  There are only 78 images in total.

Can anyone help?  Also are there any tutorials on changing the attributes as well as understanding the workflow and the benefits of adding multiple  nodes?

Thank you in advance

Jon

**Comment by glini** [comment]
So in short, you're using a kind of turntable technique. You should move your camera around the object. The important thing is the (in your case not changing) background. As I understand, your (not equal) background stays the same, only your object is turning. When you have to use turntable technique, your background should be uniform. The number of your pictures should give you a useful result. Hope this helps.

**Comment by natowi** [comment]
A turntable setup requires good indirect lighting, no shadows and a featureless background/underground.

Flat, single coloured or glossy surfaces are difficult to reconstruct. You can try reconstructing with high/ultra [settings](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters).  Also, your subject should fill most of the image frame (when using a turntable we are not interested in the environment).

**Comment by hargrovecompany** [comment]
also, make sure that to the extent possible, the object to be rendered (foreground) is covering most of the image.....especially if you're going to use a turntable....if there's too much background and not enough subject in the shots, the software will pay attention to the features in the background and try to align using those features instead of the subject
