### ISSUE TITLE
How to add another texturing node after completion?

### ISSUE THREAD

**Issue by trburns2007** [alicevision/meshroom#522]
I'd like to go back and get another image texture at 2k. Is there a way to do this without reprocessing the whole thing?

**Comment by natowi** [comment]
You can change the settings in the texturing node and compute this node again.

**Comment by trburns2007** [comment]
I tried this, however I just instantly get a red error

**Comment by natowi** [comment]
Then create a new Texturing node with the 2k setting and connect it the same way as the other texturing node.

**Comment by trburns2007** [comment]
Meshroom freezes whenever I change the texture res and click compute. And I tried to create a second texturing node but I cant figure out how to connect the image folder connect from the depth map

**Comment by natowi** [comment]
![texturingn](https://user-images.githubusercontent.com/8138537/60076358-a2103280-9727-11e9-8c3b-1aa2ec21467b.JPG)

You could also duplicate the node (right-click on node: duplicate node)

**Comment by trburns2007** [comment]
Ya tried making an entire new node completely as well and still freezes. I7 6300hq, gtx 1060, 16gb ram

**Comment by trburns2007** [comment]
It just freezes and says graph Is being computed externally

**Comment by natowi** [comment]
See https://github.com/alicevision/meshroom/wiki/Error:-Graph-is-being-computed-externally

**Comment by trburns2007** [comment]
So it seems it's an issue with selecting the 2k option. All other options work fine

**Comment by natowi** [comment]
Can you attach the cli and node log output?

**Comment by trburns2007** [comment]
I can try if you walk me through that process

**Comment by trburns2007** [comment]
I'm not sure that I can though as everything freezes as soon as I select the texture size option

**Comment by natowi** [comment]
That is unexpected. How are your computer stats in the task manager? You can grab a screenshot from the meshroom cli in the background.

**Comment by trburns2007** [comment]
Stats are about 40%. How do access the cli?

**Comment by natowi** [comment]
When you start meshroom a cli window opens in the background

**Comment by trburns2007** [comment]
![Screenshot (42)](https://user-images.githubusercontent.com/49292592/60090821-77f74a00-9700-11e9-9056-57023d1782b9.png)

**Comment by natowi** [comment]
Try removing the texturing node entries in the 3d viewer contents. There might be a conflict with the viewer.

**Comment by trburns2007** [comment]
Removed model from the 3d viewer but still getting graph is being computed externally and freezing even after folders were cleared

**Comment by trburns2007** [comment]
![Screenshot (43)](https://user-images.githubusercontent.com/49292592/60091567-22bc3800-9702-11e9-8b73-c19c3787da42.png)

**Comment by natowi** [comment]
Did you reset the node as [described here](https://github.com/alicevision/meshroom/wiki/Error:-Graph-is-being-computed-externally)?

**Comment by trburns2007** [comment]
I did yes

**Comment by natowi** [comment]
I´m out of ideas. Any suggestions @fabiencastan?
