### ISSUE TITLE
Export Animated Camera Error

### ISSUE THREAD

**Issue by selavfx** [alicevision/meshroom#524]
Hi.
I am trying to export an animated camera from the calculated StructureFromMotion.
The exporter immediately fails with the follwing error:

*terminate called after throwing an instance of 'std::regex_error'
what(): refex_error

Everything else in the nodechain is working without erroring by showing a green status color.. 
Source Images come from a still camera, I am using Meshroom 2019.1.0 on Linux CentOS 7.

Thanks in advance!
Sebastian

**Comment by natowi** [comment]
What kind of image dataset are you using?
Export animated camera requires an image sequence as it can be extracted from a video. This does not work for unstructured image sets (from my experience).

**Comment by pnuehrenberg** [comment]
Getting the same error on my datasets (image sequences, but not complete.. something like img_0_0000.png, img_0_0010.png, img_0_0020.png etc.).

`terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error`

When choosing to write the undistorted images, a first image is written to the output directory, but it is not the first of the image sequence. Also, my images are organized in subdirectories for each camera, could that be a problem? Sorting them (first numerically, then alphabetically) produces the correct sequence.

I'm using the prebuilt release.

Trying to use Meshroom with AliceVision built from sources just get's me following error:

`/bin/sh: 1: aliceVision_exportAnimatedCamera: not found`

**Comment by natowi** [comment]
> my images are organized in subdirectories for each camera, could that be a problem?
Yes

> Sorting them (first numerically, then alphabetically) produces the correct sequence.
That´s what I would have recommended.

The Animated Camera export feature is not optimized at the moment and requires a sequence of images with corresponding names (1-n) from the same folder at the moment. Unstructured images, naming conventions, folder structures... will not work or result in an error.

**Comment by natowi** [comment]
If this is still an issue, you can re-open it.

**Comment by simogasp** [comment]
this could be related to #615 , ie older version of gcc, gcc > 4.8 is needed
