### ISSUE TITLE
Thoughts on getting position from SteamVR tracking?

### ISSUE THREAD

**Issue by Thynix** [alicevision/meshroom#529]
I don't know how useful this would be if implemented, or how difficult it would be to implement, but:

Would it make sense to get or supplement camera position and orientation information from a SteamVR tracker attached to the camera?

This would require work to associate a position with a photo, but  if you're moving the camera but not the subject, my thought is that a [Vive Tracker](https://www.vive.com/us/vive-tracker/) has a 1/4" UNC threaded mount, just like cameras do, and in many situations it's straightforward enough to have base stations pointed at the camera from opposing sides.

My hope is that if this is viable, it'd reduce the processing required to determine camera position, and speed up the path to the final mesh.

**Comment by tycone** [comment]
I believe conception of additional means to generate meta-data or exif which could be embedded in images as information is outside the scope.

**Comment by Thynix** [comment]
That makes sense. Would it be within scope to support reading position hints from EXIF data?

**Comment by natowi** [comment]
When we have support for GPS registration, one could write a tool to convert tracker positions to a local coordinate system. ([similar projects](https://github.com/alicevision/meshroom/wiki/Good-first-contributions))

**Comment by natowi** [comment]
OpenVR-Tracking-Example: 
A small c++ example on how to access OpenVR tracking data and controller states using IVRInput system
https://github.com/Omnifinity/OpenVR-Tracking-Example

vive-diy-position-sensor: Code & schematics for position tracking sensor using HTC Vive's Lighthouse system and a Teensy board. https://github.com/ashtuchkin/vive-diy-position-sensor

HTC Vive Tracker Node for ROS 
https://github.com/moon-wreckers/vive_tracker

**Comment by fabiencastan** [comment]
There is no problem in the pipeline to provide an initial camera poses if you have the information.
As it's done when we do an SfM augmentation. These positions will be refined in the Bundle Adjustment as all other cameras.

The only part that would be nice to do is to use this geometric knowledge also in the feature matching to improve the quality.

It will not speed up the process but it should improve robustness to challenging conditions like indoor.

**Comment by Thynix** [comment]
Okay, looks like this is a feature idea for a supporting application, and a feature idea about integrating position data into feature matching. Given that's not the title of this issue, my inclination is to close it.

@fabiencastan I don't see an issue filed for adding this capacity to feature tracking; would it make sense to open one?
