### ISSUE TITLE
Prepare dense scene

### ISSUE THREAD

**Issue by jonbragado** [alicevision/meshroom#530]
**Configuration**
Version 2019.1.0
Windows 10 
Python 3.6.6

Going through every stage the node called PrepareDenseScene fails to compute. Goes red with no signal in the log of being wrong at any stage. 
I need the dense scene computation, and for some reason the camera export fails too; the baked .abc file lack any cached attributes as keyframes on the camera (unless it is the same case as in maya where the .abc have to be baked first?)

Thanks

[cinetometria_bragadoj_v001.zip](https://github.com/alicevision/meshroom/files/3343136/cinetometria_bragadoj_v001.zip)

**Comment by fabiencastan** [comment]
Could you show the log of the SfM node?

**Comment by jonbragado** [comment]
[log.zip](https://github.com/alicevision/meshroom/files/3343279/log.zip)

**Comment by fabiencastan** [comment]
It may be due to the non ascii character in the path `A�reo`.

**Comment by jonbragado** [comment]
How come then the other nodes are able to write to the respective folders properly without any issues of that non-ascii character? Im giving it a try now, just asking. 
Also, we have a workflow in Spanish of all the 3D software we use and run, even our windows in Spanish. Any chance we can get full on UTF-8 native support for future releases?

Thanks

**Comment by fabiencastan** [comment]
In the PrepareDenseScene we write images using the oiio library and the problem could be there. But first, we need to validate if the problem comes from that ;)

**Comment by jonbragado** [comment]
Internationalization is also something it would be great to have, Meshroom in Spanish. We can help on that as a proofreader for a first machine translation pass. 
Already doing it for another open source project called DJV. It would be great to have the interface in Spanish.

**Comment by natowi** [comment]
@fabiencastan this could be indeed be a oiio related issue which should be fixed with the latest release from what I read on https://github.com/OpenImageIO/oiio/pull/1454. Alicevision might has been using an outdated oiio version for the last build.

**Comment by wil97427** [comment]
hi i have the same probleme : 
![image](https://user-images.githubusercontent.com/56035006/65970949-7d3f0000-e478-11e9-87f8-a0eeb4f59347.png)

**Comment by fabiencastan** [comment]
It's due to the non ascii character in your path: "trait**é**e".
This is a known issue, for now you have to change your path.

**Comment by wil97427** [comment]
thank you , where i have to change that ?  in wich place or folder ?

**Comment by wil97427** [comment]
it is ok thank you very much ..;
