### ISSUE TITLE
Can't find object rx ry rz tool

### ISSUE THREAD

**Issue by DrHorologist** [alicevision/meshroom#545]
I searched through the forum and google but no results on how to enable the rx ry rz tool. I actually never had it in the first place and redownloaded the 2019.10 version and still nothing in the 3D viewer at the top left corner. Also I tried to play with the gizmo and origin feature but nothing works other than me panning the camera view, but not the object.

![Untitled](https://user-images.githubusercontent.com/49106233/60773176-54041300-a0c7-11e9-82d3-5583a96cb942.png)

**Comment by natowi** [comment]
The "rx ry rz tool" has been replaced by gizmo in MR 2019.1. At the moment it is not possible to adjust the model orientation within Meshroom, but it is on the ToDo list. You can use Meshlab to re-orient and rescale your model.

**Comment by DrHorologist** [comment]
:O thanks for the info!
