### ISSUE TITLE
Is it possible to impose camera's position ? 

### ISSUE THREAD

**Issue by art2611** [alicevision/meshroom#546]
Hello, 
I work on a project with more than 50 cameras and each position is fixed. Apparently, Meshroom have some difficulties to find their good position from pics, that's why I would like to impose their position. Is there a way to do this ? 
 I know there are already some subject on this question but I don't find answers. 

Thank you in advance for your answers.

**Comment by natowi** [comment]
You could try this: choose a perfect object for photogrammetry (well structured, no reflections,...) to get good camera positions for your rig. Then use the known camera positions [like this](https://github.com/alicevision/meshroom/issues/399).

Also #453 #475

There will be also some new camera rig options and probably cctag support in the upcoming release.

**Comment by art2611** [comment]
Ok thank you for your really quick answer ! So even if the solition is not easy, there's a way to do this ! 
I will try like you said, and let's see ! 
Nice for the upcoming release.
