### ISSUE TITLE
Is it possible to locate a camera given the reconstruction?

### ISSUE THREAD

**Issue by Paul92** [alicevision/meshroom#551]
Hello!

I just started using your application (and it's been awesome so far!).

One quick question: I plan to reconstruct a space (e.g. room), and then place the camera in a fixed position. Is it possible, without running the whole reconstruction pipeline, to localize that camera (i.e. to get the extrinsic matrix)?

**Comment by natowi** [comment]
See: https://github.com/alicevision/meshroom/issues/300 https://github.com/alicevision/meshroom/issues/399 https://github.com/alicevision/meshroom/issues/453 https://github.com/alicevision/meshroom/issues/475 https://github.com/alicevision/meshroom/issues/546

**Comment by fabiencastan** [comment]
Hi,

When you drop new images in Meshroom, you have 2 options:
1- "Add Images"
2- "Augment Reconstruction"
So use the second one to only localize the new images.

It will still make a global BA that can adjust a little bit the overall scene. If it's important to avoid that, after dropping new images, select the newly created StructureFromMotion node and check the option "Lock Scene Previously Reconstructed".

Best,
