### ISSUE TITLE
Mesh lacking the most important part of the model !

### ISSUE THREAD

**Issue by machampagne1** [alicevision/meshroom#552]
Hi, I'm trying to use the software to generate a model of a leaf (or other objects), but as you can see in this photo, the points of the leaf appear perfectly : 
![image](https://user-images.githubusercontent.com/51203484/61068633-7e601400-a3d8-11e9-9554-b77a8ecff569.png)

Thing is, when the mesh is generated, the leaf is non existant ! : 
![image](https://user-images.githubusercontent.com/51203484/61068714-a485b400-a3d8-11e9-9336-1ff4791b8c47.png)

How do I fix this ?
Thanks !

**Comment by ChemicalXandco** [comment]
Very thin objects will not mesh very well (with depthmaps) however you could use [draft meshing](https://github.com/alicevision/meshroom/wiki/Draft-Meshing) which uses the points generated in `StructureFromMotion`, since there are a decent amount of points there it should work better.

As a general rule scanning very thin objects should be avoided, it is probably better to make it in 3d modelling software.

**Comment by machampagne1** [comment]
> Very thin objects will not mesh very well (with depthmaps) however you could use [draft meshing](https://github.com/alicevision/meshroom/wiki/Draft-Meshing) which uses the points generated in `StructureFromMotion`, since there are a decent amount of points there it should work better.
> 
> As a general rule scanning very thin objects should be avoided, it is probably better to make it in 3d modelling software.
> 
> I hope this was useful information!

I'm currently trying this out !
I hope it works, I need an insane ammount of models/textures so this would defenitivly be better than modeling & texturing myself.
Thanks !

**Comment by fabiencastan** [comment]
You should try to reduce the 2 parameters "Min Consistent Cameras" on the DepthMapFilter.

You can also try the option "Add Landmarks To The Dense Point Cloud" on the Meshing node (to include the SfM points in the dense point cloud).

**Comment by fabiencastan** [comment]
A leaf usually contains specularities. You should consider using a polarizing filter on your camera for your shooting if it's not already the case.

**Comment by machampagne1** [comment]
oooo
I have one, I'll try this next
