### ISSUE TITLE
QtQuick.Controls

### ISSUE THREAD

**Issue by natowi** [alicevision/meshroom#563]
When building MR, I get the following error:

`WARNING:root:QQmlApplicationEngine failed to load component
WARNING:root:file:///D:/MeshroomDEV/2019test/meshroom/build/exe.win-amd64-3.6/lib/meshroom/ui/qml/main.qml:519 Type WorkspaceView unavailable
file:///D:/MeshroomDEV/2019test/meshroom/build/exe.win-amd64-3.6/lib/meshroom/ui/qml/WorkspaceView.qml:85 Type Viewer2D unavailable
file:///D:/MeshroomDEV/2019test/meshroom/build/exe.win-amd64-3.6/lib/meshroom/ui/qml/Viewer/Viewer2D.qml:189 Type FeaturesInfoOverlay unavailable
file:///D:/MeshroomDEV/2019test/meshroom/build/exe.win-amd64-3.6/lib/meshroom/ui/qml/Viewer/FeaturesInfoOverlay.qml:86 Type ColorChart unavailable
file:///D:/MeshroomDEV/2019test/meshroom/build/exe.win-amd64-3.6/lib/meshroom/ui/qml/Controls/ColorChart.qml:2 module "QtQuick.Controls" version 2.10 is not installed`

What do I have to do to enable QtQuick.Controls?

**Comment by yann-lty** [comment]
You can you either try:
- updating PySide2 to 5.13.0
- lowering the imported version of QtQuick.Controls in this file (e.g `import QtQuick.Controls 2.3`).

In all cases, we should modify this import in the code since we don't actually rely on something specific to QtQuick.Controls 2.10 here.

**Comment by natowi** [comment]
Thanks, I will try this.

**Comment by natowi** [comment]
Updating to PySide2 to 5.13.0 worked.
Why not add PySide2==5.13.0 to the requirements.txt?

**Comment by yann-lty** [comment]
This is planned: https://github.com/alicevision/meshroom/commit/40d954b6993c45709de57e94dbb911d41b6c1ea9  :)

**Comment by yann-lty** [comment]
Side note about 5.13.0 on Windows that we should not forget: the assimp sceneparser plugin is missing from prebuilt binaries, which prevents OBJ files to open in the 3D viewer. The missing library (assimpsceneimport.dll) must be copied from a previous PySide2 installation (Lib/site-packages/PySide2/plugins/sceneparsers). See https://bugreports.qt.io/browse/PYSIDE-1005.

**Comment by simogasp** [comment]
is the import the only reason for upgrading the minimum PySide version?
