### ISSUE TITLE
Meshroom only creates environment

### ISSUE THREAD

**Issue by JWBroers** [alicevision/meshroom#565]
Hello everyone,

 I have been trying to scan the frame of my glasses using Meshroom. Unfortunately, the results I keep getting do not include the scan I intend to scan, only everything around it. As an example ill include some pictures [here](https://imgur.com/a/6ZTak63). Here one is of the SfM in meshroom, two types of meshes (one from meshroom one from meshmixer) and an example of the types of photos i took. I have tried multiple ways of making sure the frame could be scanned properly (once without anything (so with a glossy surface), once after covering the entire frame with flour and once after covering the whole model with painting tape), and have tried multiple amounts of photos (90, 240, and 65 respectively). 

Does anyone know how to fix this problem?

**Comment by natowi** [comment]
Small objects (thin parts like on your frame) are difficult to capture. You should capture close-ups.
You can try High/Ultra [reconstruction settings ](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters) to get details on the small parts.

Similar to https://github.com/alicevision/meshroom/issues/505 https://github.com/alicevision/meshroom/issues/536 https://github.com/alicevision/meshroom/issues/521 https://github.com/alicevision/meshroom/issues/519

**Comment by hargrovecompany** [comment]
macro lens, zoom until the image is at least 50% occupied by the subject.  this will require a ton of images.  make sure they're overlapped by at least 50%.  as i mentioned on another post, I have had problems with images take with too much background and not enough of the subject.
