### ISSUE TITLE
RuntimeError: CameraInit failed with error code 139

### ISSUE THREAD

**Issue by simoneBrancati** [alicevision/meshroom#568]
I'm running several automatized reconstructions from command line in **Ubuntu 19.04** with **Meshroom 2019.1.0** .
Most of the time reconstructions run and the finish smoothly but sometimes errors related to `cameraInit` terminate the process or, worse, freeze the process without terminating it.

Most of the time the error is something like this:
```
[ERROR] Error while building intrinsics : Traceback (most recent call last):
  File "/home/simone/3D/meshroom/meshroom/ui/reconstruction.py", line 382, in buildIntrinsics
    views, intrinsics = cameraInitCopy.nodeDesc.buildIntrinsics(cameraInitCopy, additionalViews)
  File "/home/simone/3D/meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 192, in buildIntrinsics
    subprocess.returncode, cmd)
RuntimeError: CameraInit failed with error code 139. Command was: "aliceVision_cameraInit  --sensorDatabase "" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "/tmp/tmpfc0vk8vz/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm" --allowSingleView 1  --input "/tmp/tmpfc0vk8vz/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm""
```
I understand it's something related to the camera parameters given by the Exif, but i can't reproduce this error because it happens at random. Infact with the same dataset i can complete the reconstruction by restarting it without changing any parameter.

**Note**
I don't know if this is related but any reconstruction, either successful or failed, starts with these OpenImageIO debug messages for every image:  
 `add_exif_item_to_spec: didn't know how to process Exif:SceneType, type 7 x 1` or
`add_exif_item_to_spec: didn't know how to process Exif:ComponentsConfiguration, type 7 x 4`

**Note 2**
I get these messages and the error with the monstree dataset too.

**Comment by natowi** [comment]
You can check out the following links.
https://github.com/alicevision/meshroom/wiki/Supported-image-formats
https://github.com/alicevision/meshroom/wiki/Images-cannot-be-imported
https://github.com/alicevision/meshroom/issues/205
https://github.com/alicevision/meshroom/issues/208

This could be related to malformed EXIF data. Remove all additional Metadata fields and keep only those required by Meshroom

**Comment by simoneBrancati** [comment]
Thanks, i will look into it

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/pull/635
