### ISSUE TITLE
Mention detected CUDA version, and provide alternative pipelines

### ISSUE THREAD

**Issue by skinkie** [alicevision/meshroom#570]
The user should be made aware that some options are not available because the minimum CUDA version for a node are not satisfied. I would expect that in the interface some options disable automatically, or for the default pipeline the DepthMap is omitted and the alternative pipeline is created.

**Comment by natowi** [comment]
The user is made aware in the download details. You can use CUDA nodes on non CUDA devices when using a submitter to run the node on remote hardware.

**Comment by skinkie** [comment]
You are missing the point here. PopSIFT only works on CUDA 3.0 devices, I am unsure if the DepthMap step actually works on 2.1 or lower. This is something that the average user with a CUDA sticker on their PC is not aware about.

Additionally, if CUDA is not present, why would we present a default pipeline that will fail?

**Comment by natowi** [comment]
> PopSIFT only works on CUDA 3.0 devices

You are right there should also be a notice for PopSIFT+CUDA 3.0.

> I am unsure if the DepthMap step actually works on 2.1 or lower.


From the release note: Requirement: NVIDIA CUDA-enabled GPU (compute capability >= 2.0)

> Additionally, if CUDA is not present, why would we present a default pipeline that will fail?

The default pipeline should produce good quality models by default. Draft Meshing does not produce a model that meets this expectation.
Enabling Draft Meshing on non CUDA computers by defaults is laborious for people using a render farm with CUDA devices. 

A solution could be the proposed Templates Manager https://github.com/alicevision/meshroom/issues/360. You would be able to load a default graph of your choice.
