### ISSUE TITLE
for rig with multiple cameras....alternative for serial number

### ISSUE THREAD

**Issue by hargrovecompany** [alicevision/meshroom#572]
I have two type of of cameras in my rig.  Rasperry Pi and Canon DSLR.  The DSLR lenses are almost impossible to keep adjusted to the exact same focal length, and I think that's causing "ghosting" in my renderings. The software indicates that (my recollection) the serial number is what allows the software to associate data with a given camera.

Raspberry Pi cameras come with no serial number and nowhere to enter one into the camera as stored permanent data.  The Canon DSLR cameras allow for that, provided I can find a copy of the antique software that will allow me to do that (I've been looking...no luck).

Is it possible to create an option to automatically substitute the image name in as a serial number?

**Comment by natowi** [comment]
You could use [ExifTool](https://www.sno.phy.queensu.ca/~phil/exiftool/) +[GUI ](http://u88.n24.queensu.ca/~bogdan/) to bulk insert a serial for your images.

**Comment by hargrovecompany** [comment]
i might have to do that.  it just requires a ton of code, since there are 80 cameras, each taking an image with regular lighting and one with projected pattern.  i might shoot 50 sets on a busy day.  the guys here built a way for me to render using the projected images, then swap the images out just prior to texture.  long story short, it has to be automated and i was thinking it would be simpler to do it in meshroom

**Comment by hargrovecompany** [comment]
can anyone tell me which serial number is used by meshroom?  i haven't made sense of it yet but evidently there might be three different serial number entries....camera serial number, body serial number, and lens serial number.  i'm writing code to insert data as unique serial number and i want to get it right...
