### ISSUE TITLE
Help: Understanding why am I getting poor results? 

### ISSUE THREAD

**Issue by 3Rton** [alicevision/meshroom#581]
Image set
( https://drive.google.com/open?id=1y6w5sD4dE5-LnwqpbzMPnuK9NlbQeUj1 )

So I've been trying to get results with this image set (in 2019.1.0) but it is a struggle. At first I assumed the other side being considerably darker could be a problem but actually start seems to be the least of an issue? The biggest artifacts seem to be on the Vamp/Toebox (portion above toes) with weird bumps and the bright side of the heel (which gets very deep hole I can't understand) 
And overall the textures are very unclean/blotchy on the surface of the shoe (and especially weird dark blotching on the stool)

I've tried the default settings, Using FeatureExtraction high and ultra, using high and FeatureExtraction FeatureMatch SfM Akaze toggled... I'm just lost what I need to do better. Do my photos have too much depth blur? Is it because leather is quite reflective? Do I have to turn off sift when using akaze? 

I'm not going to be mad if this gets immediately closed but with no forum nor stuff it is pretty hard to find a channel which would have chance of actually reaching someone who can help to understand this beast.

**Comment by Dok11** [comment]
@3Rton 

> Understanding why am I getting poor results?

Metrial of your object is pretty shiny. The algorithms currently used cannot detect them correct.
So you can made material more roughness. Try use soda or flour or paper tape.
See https://www.tested.com/art/makers/460142-art-photogrammetry-how-take-your-photos/
