### ISSUE TITLE
PrepareDenseScene. Range is incorrect

### ISSUE THREAD

**Issue by Dok11** [alicevision/meshroom#583]
```
Program called with the following parameters:
 * input = "/MeshroomCache/StructureFromMotion/d9e58023169e077352754eb141c83fb5cd7ad5d2/sfm.abc"
 * output = "/MeshroomCache/PrepareDenseScene/a78616b66bfc556b3377fbf75a3a04680345c453"
 * outputFileType = "exr"
 * rangeSize = 17
 * rangeStart = 360
 * saveMatricesTxtFiles = 0
 * saveMetadata = 1
 * verboseLevel = "trace"

[13:37:35.140714][trace] 308 extrinsics declared and 359 extrinsics used.
[13:37:35.141712][error] Range is incorrect
```

![image](https://user-images.githubusercontent.com/2697890/62820898-243ba580-bb74-11e9-89e9-9b6d4beb3fbd.png)

How I can fix it?

And search by repositiory have not any matches when I search `Range is incorrect`. This text from 3rd party library?

**Comment by Dok11** [comment]
My temp hack decision:
![image](https://user-images.githubusercontent.com/2697890/62825913-1d388580-bbbc-11e9-81be-e6af5e44b5bb.png)

Just copy output path from PrepareDenseScene node and define this path as input in the DepthMap.
But it still stops at some steps :(

I think what this error related with adding images to calculate. Look at my generated scheme =)
![image](https://user-images.githubusercontent.com/2697890/62825934-70aad380-bbbc-11e9-95d4-8ae89b1cc30e.png)

Because in my dataset not all photos made step by step so I must use feature with adding part of images SFM to SFM part by part.

And as you can see on screenshot the node try calculate from rangeStart=360, but only 344 photos has in SFM node.
![image](https://user-images.githubusercontent.com/2697890/62825966-ca130280-bbbc-11e9-92c2-5c2c982dc66d.png)

**Comment by Dok11** [comment]
I think I found trouble.
Number of chunks (with range start and range size) of PrepareDenseScene node are describes before SFM defines how many images will be used for reconstruction. And when many image are lose PrepareDenseScene trying compute data for range what invalid at this moment.

So I think chunks for this node shoul be define only after SFM node will do their work.

**Comment by Dok11** [comment]
And one bug more.

If I remove images from groups then PrepareDenseScene dont recalculate chunks count. And it also leads to an error when reconstruction start

**Comment by Dok11** [comment]
![image](https://user-images.githubusercontent.com/2697890/63078893-a85fa580-bf45-11e9-831a-fb87f464a885.png)

Bug still in the new version

**Comment by fabiencastan** [comment]
Hi,
Thanks for the bug report.
I didn't managed to reproduce it for now.

Do you have a list of actions to reproduce it in a repeatable way? Like adding images, removing a subset of them, augment the reconstruction, remove some images from the augmentation, etc.?

Can you reproduce it with a small dataset?

Could you also send me an .mg file with the problem?

**Comment by Dok11** [comment]
> Can you reproduce it with a small dataset?

I will try, but think it related to large dataset where range calclation can broke

**Comment by olinpin** [comment]
Did someone solve this yet? I'm having the same issue as @Dok11
