### ISSUE TITLE
DNG File format Support

### ISSUE THREAD

**Issue by jgwill** [alicevision/meshroom#586]
Simple format support for the RAW DNG file format :)

best regards

**Comment by natowi** [comment]
RAW digital camera files (dng) should be supported by OIIO.
https://github.com/alicevision/meshroom/wiki/Supported-image-formats

**Comment by 1029chris** [comment]
Tried using RAW pictures from my Pixel 3, which are in the .dng format. It refuses it import them.

Here's the consoles output when I drag it in:
![image](https://user-images.githubusercontent.com/15712599/64905781-ffb27c00-d691-11e9-9079-4fd2a5395d9e.png)

**Comment by fabiencastan** [comment]
Could you provide some sample images?

**Comment by 1029chris** [comment]
Sure, here ya go. https://drive.google.com/open?id=13yILX1wIuuwCzlsc3P1YPWLcWONoI24g
