### ISSUE TITLE
Windows release download on Github?

### ISSUE THREAD

**Issue by yamlCase** [alicevision/meshroom#588]
We are attempting to create and maintain the Windows Chocolatey package, however we are unable to automate the creation due to the Windows binary release being hosed on Fosshub.  Can you also provide a Github release for Windows binaries?  Thank you!

https://github.com/chocolatey-community/chocolatey-package-requests/issues/645

https://github.com/alicevision/meshroom/issues/412

**Comment by fabiencastan** [comment]
Hi @yamlCase,
Thanks for reporting this! As requested, we will add binaries on github (with a static URL) for the coming release 2019.2 (which should be done this week).
Best,

**Comment by yamlCase** [comment]
thank you very much!
