### ISSUE TITLE
3D construction of tree

### ISSUE THREAD

**Issue by Sudhir2708** [alicevision/meshroom#591]
Hello Alicevision Team,

Thank you for such precise 3D software

I'm new to the Meshroom, I have tried to build 3D model of tree with help of 360 degree images around tree which are taken by mobile camera. I my case out of 50 images only 11 align correctly and most of them are not constructed (Approx. 50%) .

Is there any specific workflow or else manual alignment procedure for 360 images?
Right now I'm unable find solution for it, I have attached link of data set below.

https://drive.google.com/drive/u/5/folders/1FZv_BxkFvvJy441rjTAKCN2MvUB4QGWZ

Kindly Suggest @fabiencastan 
Thank you

![image](https://user-images.githubusercontent.com/53561073/62939734-92d86780-bdef-11e9-83c4-5f4bfa16920e.png)

**Comment by hargrovecompany** [comment]
keep doing images just as you did above, but make another right a bit higher, with your camera facing downward a bit,  then do it again, going even higher.  

every bit of every surface needs to be included in three images.  as an example, if you put a bucket on a table and took 50 pictures of the bucket, all the way around, but none over the top of the bucket, the software has no data for the inside of the bucket with which to render it.  your plant has a lot of surfaces that are blocked from cameras taking pictures in the ring of images you made.  more images from higher will make it much better. in fact, just got to the areas where you see big holes, take pictures from below and above, making sure you get enough overlap (50%) with each image and make sure they thread back to connect with the original ring.    in other words, a group of images made from above, that have overlap but do not include images overlapping your existing photos will not know how to connect with them

**Comment by Sudhir2708** [comment]
Thank you for suggestion.
