### ISSUE TITLE
Feature request: do cache results of FeatureExtraction node

### ISSUE THREAD

**Issue by Dok11** [alicevision/meshroom#592]
In my case the DepthMap node very often broke calculations on some images, then I remove them from dataset and start calculation again. And FeatureExtraction start again own calulcation but it was calculated before. What? Why?

So I think it many extra work for every time when I restarted pipeline.
If program will be cache the features for every image seprately in this node it would save many time =)

**Comment by fabiencastan** [comment]
Yes, the invalidation graph could be much more fine grained but it would also make the graph much more complicated and there are key steps that invalidate everything in all cases. So for now, we keep this simple invalidation graph.

BTW, could you try with the new release 2019.2 if you still have problems on depth maps? We have made multiple fixes regarding that:
https://github.com/alicevision/meshroom/releases/tag/v2019.2.0

**Comment by Dok11** [comment]
> Yes, the invalidation graph could be much more fine grained but it would also make the graph much more complicated and there are key steps that invalidate everything in all cases. So for now, we keep this simple invalidation graph.

For most cases as I can see the calculation is require much time, so inceresing speed calulation in any steps may create better impression from this program.
Maybe this feature with caching would not affect to graph and working in shadow as cache for every operation where usage something like cache salt including node parameters and md5 (for example) of image together. But I'm really dont know how it is working inside.

> BTW, could you try with the new release 2019.2 if you still have problems on depth maps? We have made multiple fixes regarding that:

At this moment I'm in intensive testing new version ;)

**Comment by Baasje85** [comment]
https://github.com/alicevision/meshroom/issues/510
