### ISSUE TITLE
Structure from motion node is missing in scene

### ISSUE THREAD

**Issue by eriol726** [alicevision/meshroom#596]
Hi, when I'm open my build version of meshrrom (Meshroom 2019.2.0-develop) the SFM node is missing in the Scene table. But if im open your pre-build version (Meshroom-2019.2.0 downloaded from https://www.fosshub.com/Meshroom.html?dwl=Meshroom-2019.2.0-win64.zip) the scene node is there. And this seems very important to have this node to be able to visualize the cameras and I cant find any way to add it in the meshroom GUI. Is this an issue or do I have to add this node in the python code before I run the program?

develop version vs pre-build version
https://imgshare.io/images/2019/08/16/Screenshot_37.png

**Comment by eriol726** [comment]
I just found that you can add the SFM-node from the graph editor to the scene by dubble click on the node, but that only works in the pre-build version

**Comment by natowi** [comment]
Did you inlcude qmlAlembic and QtOIIO?

**Comment by eriol726** [comment]
> Did you inlcude qmlAlembic and QtOIIO?

I thought I had but obviously not. To type  `set QML2_IMPORT_PATH=K:\qmlAlembic\installed\qml` in the cmd did it!

I thought it was the same as setting a new path in environment variables->system variables. But it doesn't seem that way
