### ISSUE TITLE
[bug]2019.2 Running Out of Memory

### ISSUE THREAD

**Issue by Chris-Clawson** [alicevision/meshroom#597]
I am running out of memory when processing the same image sets which previously ran successfully on the 2019.1 version. In some circumstances, the “Texturing” phase swallows up all available memory and terminates with an 'out of memory' error. I am using CPUID, which is my source for memory usage monitoring in this report.

My system
AMD Threadripper 32 Core w/64GB ECC memory
Windows 10 PRO 64
Video Card:NVIDIA Quadro P2000

“Buddah” dataset:
This downloadable image set works fine in both 2019 versions of Meshroom. In both cases, CPUID reports a total memory consumption of about 16% during the “Texturing” step. All of the  67 PNG images were used, in both runs, and produced a single PNG Texture image of 4096x4096.

“Chapel” dataset:
This is my own image set, taken with a CANON 650D (T4i) as raw .CR2 files. A stone chapel was photographed with 103 exposures. The 2019.1 version accepted 86 images and the 2019.2 accepted 100. Both tests set the Texturing to 8192 pixel sides with a Downscale factor of 2.
In both tests, the Texturing completed successfully, with CPUID reporting 19% memory use during 2019.1 run, but required 74% of the available memory with version 2019.2.

“Millsite” dataset:
This is another raw file image set, taken with my Canon camera. This is from a large 19th century mill site, which extends many hundreds of feet along a hydropower canal. This project suffered from the 2019.1 Depth Map bug, but is able to finish using a limited image set of 207 images. 

The 207 image mill dataset takes hours to run. The 2019.1 test is able to finish with a Texture map setting of 8192 pixel sides, Downscale 2, and produces 20 4096x4096 png texture images. The 2019.2 test rapidly consumes memory, during the final Texturing step, and then shuts down with an 'out of memory' error after climbing above 92% capacity as reported by CPUID.
The 2019.2 tests are able to finish if Texture Side is limited to any of the 1024 sides (any downscale setting), but exceeds memory requirements with 2048/1 or any higher resolution.

I think your work and effort is great and will be a spectacular asset in my work with historic presentations. I hope this report can help provide a solution or work-around in preventing this issue from being a problem. I will be happy to provide more data, if needed, but this involves large file sizes. I might post them on my server, if needed.
Congratulations on 2019.2! There are many improvements I am anxious to enjoy.

**Comment by Chris-Clawson** [comment]
Is it possible to replace the 2019.2.0 version of the 'Texturing' module with the one included in this latest version of Meshroom? How might I do this? (I have never tried to compile my own binaries)
The 2019.1 version stops me at "Depth Map", and the 2019.2 version stops me at 'Texturing'. I would be very happy to contribute any additional data which may help resolve my 'out of memory' problem.

**Comment by curtthemartian** [comment]
I too get Out of Memory errors in multiple stages even though the memory isn't all that close to being consumed.   I recently tried using 2018.1 version again and its memory management seems much much better even with higher settings selected.   I recall something was done to improve speed/efficiency for many of the later steps.   I am wondering if they have anything to do with the Memory issues.

**Comment by fabiencastan** [comment]
>
> I too get Out of Memory errors in multiple stages even though the memory
> isn't all that close to being consumed.
>
Could you be more specific and list the nodes that fail?
