### ISSUE TITLE
[bug]User Document Folder & Admin

### ISSUE THREAD

**Issue by voto1979** [alicevision/meshroom#599]
Windows 10 & Meshroom 2019.2.0

**Open Meshroom as administrator:** You can not drag and drop the image folder into the application.

**Save the project in the user documents folder**: Meshroom can not finish the calculation (red) mostly on the "StructureFromMotion" node … same Project saved on Desktop or any other folder / drive or as Unsaved Project… works perfect.

> C:\Users\Name\Documents\Photogrammetry\ProjectName\ProjectName.mg

**Comment by voto1979** [comment]
I use a "mklink" for my user documents folder!

> C:\Users\Name\Documents\Photogrammetry\ProjectName\ProjectName.mg

and

> D:\Documents\Photogrammetry\ProjectName\ProjectName.mg

are the same (C:\) is linked to (D:\). If I open the project over (C:\) it stops on the "StructureFromMotion" node and if I open it trough (D:\) it works without any issues. 

`mklink /J "C:\Users\Name\Documents\" "D:\Documents\"
`

**Comment by MightyBOBcnc** [comment]
I do not believe the first one is a bug.  In Windows you cannot drag and drop from a low-privilege process into a high-privilege process.  explorer.exe is not running as admin so it cannot drop onto a process that is running as admin.  https://blogs.msdn.microsoft.com/patricka/2010/01/28/q-why-doesnt-drag-and-drop-work-when-my-application-is-running-elevated-a-mandatory-integrity-control-and-uipi/

**Comment by voto1979** [comment]
@MightyBOBcnc ... Thank you ... I didn't know that :-)
> you cannot drag and drop from a low-privilege process into a high-privilege process

**Comment by voto1979** [comment]
The Problem with the user documents folder still exist!

**Comment by MightyBOBcnc** [comment]
Hmm, I've never used symbolic links/junctions before but it seems Windows has an imperfect implementation of them.

An answer suggested here is to use /D instead of /J when creating the link: https://superuser.com/questions/1031213/windows-10-symbolic-links-problems

And here some other issues are listed like the if a program is using file system or shell: https://stackoverflow.com/questions/43090597/how-are-windows-symbolic-links-treated-by-the-apps

**Comment by natowi** [comment]
@voto1979 From https://github.com/alicevision/meshroom/issues/593#issuecomment-522936453 it looks like you have resolved this.

**Comment by voto1979** [comment]
@MightyBOBcnc & @natowi … thank you both for your quick answers!

@MightyBOBcnc I don't remember exactly why I use (J) instead of (D) for mklink ... maybe I was not sure what happened when I make a backup from disk (C)!

With (mklink /J) ... I can make a system backup image with "Backup and Restore (Windows 7)" from (C:\) and it only saves the folder link and not the folder with content. So I can not accidentally overwrite my documents in the folder or important files If I revert to a backup image.
