### ISSUE TITLE
[bug] Windows release not finding aliceVision binaries on windows

### ISSUE THREAD

**Issue by Frizi** [alicevision/meshroom#600]
**Describe the bug**
It is impossible to import any images with the UI, as an error is being thrown on every attempt.

It seems like the aliceVision binaries are not being found or called correctly. I believe it should not be necessary, but I also tried adding aliceVision/bin directory to PATH. I am able to call `aliceVision_cameraInit.exe` through `cmd`, so it is definitely being found. Skimming through the sources, it seems like the (I believe) mandatory ".exe" extension is ommited in windows build.

https://github.com/alicevision/meshroom/blob/4b0f7f1c1a144cb00dc4cc2b3bfab0a5d5234277/meshroom/nodes/aliceVision/CameraInit.py#L93

**To Reproduce**
1. Download and unzip the 2019.2.0 release on windows
2. Run Meshroom.exe
3. Drag and drop any image
4. See error in the console
```
'aliceVision_cameraInit' is not recognized as an internal or external command,
operable program or batch file.
ERROR:root:Error while building intrinsics : Traceback (most recent call last):
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\meshroom\ui\reconstruction.py", line 399, in buildIntrinsics
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 192, in buildIntrinsics
RuntimeError: CameraInit failed with error code 1. Command was: "aliceVision_cameraInit  --sensorDatabase "C:\opt\Meshroom-2019.2.0\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "C:/Users/Frizi/AppData/Local/Temp/tmpbmo5atfd/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm" --allowSingleView 1  --input "C:\Users\Frizi\AppData\Local\Temp\tmpbmo5atfd/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm""
```
**Expected behavior**
The dropped image should be loaded

**Log**
See above, this is all that happens

**Desktop (please complete the following and other pertinent information):**
 - OS: Windows 10
 - Binary version 2019.2.0

**Comment by natowi** [comment]
Are you running Meshroom as admin?

**Comment by Frizi** [comment]
No, I just perform an ordinary doubleclick, without extra privilages. The system also has a single user with default permissions, nothing out of ordinary.

**Comment by natowi** [comment]
Maybe an antivirus software is blocking Meshroom?

**Comment by Frizi** [comment]
The only antivirus I have is the one builtin into the Windows. It sees no problems with meshroom.

**Comment by natowi** [comment]
Do the images from the Monstree sample dataset work?

**Comment by natowi** [comment]
Maybe this issue can help: https://github.com/alicevision/meshroom/issues/125

**Comment by 3danimationgeek** [comment]
Same thing here.

**Comment by BlueSmokeGuy** [comment]
I have this issue too.

Meshroom launches unable to load the plugin module simpleFarm.
Then I get the op error.

Monstree test data generates the same error.

PATH as follows:
C:\Program Files\Git\cmd
C:\Program Files\meshroom
C:\Program Files\meshroom\alicevision
C:\Program Files\meshroom\alicevision\src

**Comment by fabiencastan** [comment]
@frizi you have to extract the archive and not just launch it from the zip viewer.
See in your path : "C:\Users\DEV\AppData\Local\Temp\meshroom\meshroom\ui\reconstruction.py", you are in the temp folder of the zip viewer.

@BlueSmokeGuy You have to download the release binaries from here: https://github.com/alicevision/meshroom/releases

**Comment by usrnamesllrdytkn** [comment]
I have the same issue too.

**Comment by natowi** [comment]
This issue is solved and closed due to inactivity. The information has been added to the wiki. Feel free to re-open if new information is available.
