### ISSUE TITLE
[bug] Wavy output

### ISSUE THREAD

**Issue by Baasje85** [alicevision/meshroom#606]
**Describe the bug**
We are trying to reconstruct a building, having straight lines in its masonry. The (textured) results from Meshroom look as if the pattern waves. We had to increase downscale of the depthmap node to 4, otherwise it would not complete. Is there something that could be done in the mesh filtering stage?

**To Reproduce**
Dataset is available on request.

**Expected behavior**
We would expect straight lines, to retain straight lines.

**Screenshots**
![image](https://user-images.githubusercontent.com/51262792/63648789-f68a5b00-c734-11e9-894f-c08db15feb10.png)

![image](https://user-images.githubusercontent.com/51262792/63648848-f50d6280-c735-11e9-8404-cd5f03e02ccb.png)

**Desktop (please complete the following and other pertinent information):**
 - OS: Win10
 - Version 2019.2

**Comment by natowi** [comment]
It looks like a problem with feature detection/matching of the repeated/symmetric pattern
(similar https://github.com/alicevision/meshroom/issues/605).  The "waves" come likely from forced fused not matching image pairs. So the algorithms detected features, but due to the symmetry they were misaligned.

What algorithms/settings do you use that differ from the default pipeline?

**Comment by Baasje85** [comment]
> It looks like a problem with feature detection/matching of the repeated/symmetric pattern
> (similar #605). The "waves" come likely from forced fused not matching image pairs. So the algorithms detected features, but due to the symmetry they were misaligned.

There are **no** images from only the walls, everything has additional context.

![thumbs](https://user-images.githubusercontent.com/51262792/63649731-a82f8900-c741-11e9-9c6c-11ba6dc64ad5.JPG)

> What algorithms/settings do you use that differ from the default pipeline?

Force CPU Extraction: off
Guided Matching: on
Min Observation For Triangulation: 3
Prepare Dense Scene Outpuf File Type: jpg
Save Metadata: off
Save Matrices Text Files: on
Depthmap Downscale: 4 (To prevent errors)

Everything else is standard, experimented with "Keep Only The Largest Mesh" an "Smooth Iterations: 20"

**Comment by natowi** [comment]
> There are no images from only the walls, everything has additional context.
Ok, I thought the images were from the side wall of the church.

Do you use SIFT only or also AKAZE?

**Comment by Baasje85** [comment]
> Do you use SIFT only or also AKAZE?
> (https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters)

At this moment only SIFT. Would you suggest the combination of AKAZE and SIFT or replace SIFT with AKAZE?

**Comment by natowi** [comment]
You can try adding AKAZE to get more robust results (in DescriberTypes, FeatureExtraction, FeatureMatching and StructureFromMotion). I´d suggest to try this on a subset of your images to evaluate the results and save time.
You can use the new Features Viewer to see the detected features. https://github.com/alicevision/meshroom/pull/539

**Comment by Baasje85** [comment]
@natowi see #607

**Comment by natowi** [comment]
You need to enable Sift + Akaze in DescriberTypes, FeatureExtraction, FeatureMatching and StructureFromMotion.
Sift sould allways stay active.

Enabling akaze in FeatureMatching only for example results in an error.

**Comment by Baasje85** [comment]
> You need to enable Sift + Akaze in DescriberTypes for FeatureExtraction, FeatureMatching and StructureFromMotion.

This has been done, still the failure of #607 starts when additionally enabling the AKAZE. Could you validate if this works for you?

> Sift should always stay active.

I don't think this statement is true. Any of the describer types should work if used consistently in all nodes.

**Comment by natowi** [comment]
> This has been done, still the failure of #607 starts when additionally enabling the AKAZE. Could you validate if this works for you?

For me this does work with the Monstree dataset.



>>Sift should always stay active.
> 
> I don't think this statement is true. Any of the describer types should work if used consistently in all nodes.

Using Sift only in FeatureExtration  causes ImageMathing error for the Monstree dataset.

**Comment by Baasje85** [comment]
> For me this does work with the Monstree dataset.
> Can you share some of your images for testing?

Just tried the image that was the last line in the log file, which on individual basis is going through AKAZE without issues. The only difference: restarting Meshroom.

So I am now runing SIFT+AKAZE.

> > The vocabularytree used has been learned on SIFT features, so currently the ImageMatching is hardcoded to use SIFT descriptors only.

Is there any description on how the vocabularytree works?

**Comment by natowi** [comment]
> Is there any description on how the vocabularytree works?

You can read the original paper here:
http://www.ipol.im/pub/art/2018/199/

**Comment by Baasje85** [comment]
With SIFT+AKAZE the same number of photos are reconstructed 180 out of 183. The number of features doubled from 49169 to 109498. Will update the ticket when it is textured.

**Comment by Baasje85** [comment]
![image](https://user-images.githubusercontent.com/51262792/63664110-7a8c2380-c7c5-11e9-88ee-21c88d7bcb0e.png)

Not really an improvement.

**Comment by curtthemartian** [comment]
Can you show us your mesh?  You may get better results if you add 40 or so iterations on the MeshFiltering Smoothing iterations setting.   I tried changing the lambda, it got much worse if you go over 1.0 I have yet to try smaller.   But from my time doing Computational fluid dynamics in college.  I wonder how this Lambda actually works in this calculations math.

**Comment by curtthemartian** [comment]
Oh and thanks everyone for suggesting the use of Akaze toggle.   It really helped get better results in my dining room test.   I will be running a new simulation of my house with that added on here in the next few days.
