### ISSUE TITLE
[bug] Node log output multi line selection

### ISSUE THREAD

**Issue by Baasje85** [alicevision/meshroom#609]
**Describe the bug**
A selection multi-line selection of the log output of a node cannot be made.

**To Reproduce**
1. Go to a node
2. Click on log
3. Try to select multiple lines.

**Expected behavior**
A multi line selection that can be copied, without having to go to the raw log file.

**Screenshots**
![image](https://user-images.githubusercontent.com/51262792/63665096-0902a400-c7ca-11e9-8804-9a9da13db3a9.png)

**Desktop (please complete the following and other pertinent information):**
 - OS: win 10
 - Version 2019.2

**Comment by ChemicalXandco** [comment]
It is possible to copy multiple lines by clicking the copy button on the left side of the log.
