### ISSUE TITLE
[bug] Some pointcloud does not generate mesh

### ISSUE THREAD

**Issue by aerchit** [alicevision/meshroom#613]
**Describe the bug**
Hi, I am new to Meshroom.
I took some picture of my plant for a quick testing with all default settings.
Some pointcloud of the leafs does not generate mesh.
Does anyone know why? I feel this is a very basic question. I tried to look for a user manual, but I can't find it. Any help would be appreciated, thanks!
 

**Screenshots**
![2](https://user-images.githubusercontent.com/17045080/63842533-5859f780-c9b7-11e9-89f6-26df758835eb.PNG)
![3](https://user-images.githubusercontent.com/17045080/63842548-627bf600-c9b7-11e9-9bcb-68a62b5eb5cd.PNG)

**Comment by Dok11** [comment]
> Does anyone know why?

Try check meshing and mesh filtering options
![image](https://user-images.githubusercontent.com/2697890/63865715-b63c0e80-c9ba-11e9-8953-ddc34a62fb0d.png)

**Comment by Dok11** [comment]
And I think points are not enough. Try increase it
![image](https://user-images.githubusercontent.com/2697890/63865851-f00d1500-c9ba-11e9-8159-27de1b7c9d8b.png)

**Comment by aerchit** [comment]
Thanks very much! it improved a bit.

**Comment by phil123456** [comment]
still no mesh at all

**Comment by natowi** [comment]
It is really difficult to capture plant leaves with photogrammetry.
Here you can find parameters to adjust: https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters
