### ISSUE TITLE
[bug] Export Animated Cam

### ISSUE THREAD

**Issue by dovmeara** [alicevision/meshroom#615]
**Describe the bug**
Hi,

Using/Testing Meshroom 2018, 2019.1, 2019.2 on Linux CentOS 7.6 18.10 

I got a problem with the node ExportAnimatedCamera. Everything in the graph is ok, but I cant export my tracked Cam...
```
log= regex_error ?
```
**To Reproduce**
1. Start a reconstruction

2. Once done, add an ExportAnimatedCam node to the output node of StructureFromMotion

3. Compute

4. Instant Error. Red bar.

**Screenshots**
![Capture du 2019-09-02 10-19-38](https://user-images.githubusercontent.com/22868449/64100748-89964700-cd6c-11e9-834f-56c33ae6df9d.png)

![Capture du 2019-09-02 10-20-07](https://user-images.githubusercontent.com/22868449/64100775-9ca91700-cd6c-11e9-84de-a23a5c3ec63f.png)

My pictures are JPEG's with EXIF (greened) labelled = name_file-001,name_file-002, name_file-003, etc...

Hope it can help...
Thanks !

**Comment by cclaan** [comment]
You might try using underscore instead of hyphen "_"  I've had luck with this naming scheme:  frame_000000.jpg, frame_000001.jpg etc.

**Comment by dovmeara** [comment]
Thanks for your answer @cclaan ,
but unfortunately, even with this naming convention I got a "regex" error...
At least, everything is fine except...camera export.
So, no matchmove for me.
I need a windows OS...Nah...
Nevermind...

**Comment by simogasp** [comment]
can you please attach the input .abc to see what's wrong? (your file naming is not a problem)

**Comment by dovmeara** [comment]
Yes of course, I retry with a new file seq and same pb.
[318bb32d8d87844397eed42131d8608c594dd9c1.zip](https://github.com/alicevision/meshroom/files/3665760/318bb32d8d87844397eed42131d8608c594dd9c1.zip)

**Comment by simogasp** [comment]
This is the content of the `ExportAnimatedCameras` node, we need the abc file from the structure from motion node: right-click on the `StructureFromMotion` node, click `Open folder` and please attach the `sfm.abc` that you find in there.

**Comment by dovmeara** [comment]
Sorry, here it is...
[sfm.abc.zip](https://github.com/alicevision/meshroom/files/3666493/sfm.abc.zip)

**Comment by dovmeara** [comment]
There is a seq of cam, maybe with a mel/py script which could transform this seq in a simple path...Thx again for your precious time...furthermore a sunday morning !

**Comment by simogasp** [comment]
Hello, I cannot reproduce your problem, it works fine on my side (see attachment).
The only thing that I could not test is the undistortion of the images because I don't have them. You can try to uncheck `Export undistort Images` in the ExportAnimatedCamera` to see if there is any difference. 
[camera.abc.zip](https://github.com/alicevision/meshroom/files/3667334/camera.abc.zip)

**Comment by dovmeara** [comment]
Alright, then...maybe it’s OS related. I can’t open the source folder from the software UI too (from node panel)... Thanks again for your investigation, your time...and wise advice.

**Comment by dovmeara** [comment]
Ok, it's not related to checked / unchecked I think. It creates a folder ExportAnimatedCamera but no .abc in it. Just log, status and statistics...I was thinking to a root/admin related pb, but...no. 

And Someone has regex problems with ubuntu there...at the same point in the node tree...
https://github.com/alicevision/meshroom/issues/628

**Comment by simogasp** [comment]
can you report the result of 
```bash
gcc --version
```
from a terminal

**Comment by fabiencastan** [comment]
@dovmeara Interesting link with the other regex issue. Could you try the `convertSfMFormat` to see if you encounter the same issue?

**Comment by dovmeara** [comment]
@simogasp 
[root@ ~]# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright © 2015 Free Software Foundation, Inc.
Ce logiciel est libre; voir les sources pour les conditions de copie.  Il n'y a PAS
GARANTIE; ni implicite pour le MARCHANDAGE ou pour un BUT PARTICULIER.
[root@ ~]#

@fabiencastan Yes I can test that too...I will look at meshroom 2019.1 too... Pfffiuuu Busy WE day !  :)

**Comment by simogasp** [comment]
there it is!
you need at least gcc 4.9 as the previous versions didn't support completely regex
https://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions
Can u install a more recent version of gcc in your centos (4.9 would be swell). @fabiencastan which version did u package the binaries with?

**Comment by dovmeara** [comment]
@fabiencastan `convertSfMFormat` is ok for me (Meshroom 2019.2).

**Comment by dovmeara** [comment]
Allright ! It's the GCC version...Lazy sunday afternoon...@simogasp thx a lot, openSourceVFX chart is respected...but not on my workstation...! :D I need rpm's now...yum yum.

**Comment by simogasp** [comment]
ok, please let us know if a newer version fixes the problem.
In case, @fabiencastan we'd better update the `INSTALL.md` in alicevision and also in the release notes.

**Comment by fabiencastan** [comment]
Yes, or embed `libstdc++.so` in the release.

**Comment by dovmeara** [comment]
@simogasp @fabiencastan I will for sure as soon as possible ! (thx for your support !).

**Comment by dovmeara** [comment]
So, I put a source statement in my .bash-profile to change GCC version to devtoolset 4 (gcc 5.3.1)...I tested the scene, but it's a redbar again. Maybe I'm wrong with the different steps to accomplish, and need to re/compile Meshroom ? I'm a bit confused at this point. Anyway, it will be solved in a future version (and with an upgrade to CentOS 8 in a next future we will have a more recent gcc too). 

# .bash_profile
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
source scl_source enable devtoolset-4
	. ~/.bashrc
fi
# User specific environment and startup programs
PATH=$PATH:$HOME/.local/bin:$HOME/bin
export PATH`
