### ISSUE TITLE
[bug] si le calcul se passe sur telechargement , il y a erreur de calcul au niveau de 

### ISSUE THREAD

**Issue by sebjura** [alicevision/meshroom#619]
input = "C:/Users/s�bastien/Downloads/Meshroom/Nouveau dossier/MeshroomCache/StructureFromMotion/559804c6e518c3653712a2011652dbfd65d2d536/sfm.abc"

je pense que que le soucis vient du cela : � 
ce caractere doit foutre la zizanie

**Comment by simogasp** [comment]
If the character is an accented character (I guess an "é" of you name) it is never a good idea to use them in filenames and directory names. Try to move your project to another folder that has standard characters

**Comment by sebjura** [comment]
ok , j'ai change de repertoire a cela fonctionne super , c'etait juste pour aider a corrige le probleme au developpeur

ok, i changed directory to it works great, it was just to help fix the problem to the developer
