### ISSUE TITLE
cuda

### ISSUE THREAD

**Issue by sebjura** [alicevision/meshroom#624]
**Configuration**
Version 2019.2.0
Windows 7 
Python 3.6.6

"[13:33:12.712226][error] cudaGetDeviceCount failed: CUDA driver version is insufficient for CUDA runtime version
[13:33:12.713226][error] This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0).
"

hi all , can we use meshroom with a no cuda video cart ?

thanks

seb

**Comment by natowi** [comment]
See https://github.com/alicevision/meshroom/wiki/Error:-This-program-needs-a-CUDA-Enabled-GPU

**Comment by jaggzh** [comment]
In Debian I had to install nvidia-cuda-dev and it worked.
It was failing at the Depth Map node with the original author's error.
$ sudo apt install nvidia-cuda-dev
