### ISSUE TITLE
[bug]CameraLocalization, command not recognized

### ISSUE THREAD

**Issue by simoneBrancati** [alicevision/meshroom#625]
**Describe the bug**

**CameraLocalization** node doesn't work because AliceVision doesn't recognize the command  
`--nNearestKeyFrames`

**To Reproduce**

I'm trying to localize frames in a pointcloud using CameraLocalization. 
*  set the path to "camera.sfm"
*  set the path to the media (image) to localize
*  start the CameraLocalization node from the GUI, right after StructureFromMotion finishes.

**Log**
```
[1/1] CameraLocalization
 - commandLine: aliceVision_cameraLocalization  --sfmdata "/home/simone/3D/RicostruzioniPointCloud/MeshroomCache/StructureFromMotion/75e11bd891ba9c07eb88c6015e2e2ba48cea8e1b/sfm.abc" --mediafile "~/3D/RicostruzioniPointCloud/images/8.JPG" --visualDebug "" --descriptorPath "/home/simone/3D/RicostruzioniPointCloud/MeshroomCache/FeatureExtraction/f061281e744be9eaecf5a882b133c53afc1023db" --matchDescTypes sift --preset normal --resectionEstimator acransac --matchingEstimator acransac --calibration "" --refineIntrinsics False --reprojectionError 4.0 --nbImageMatch 4 --maxResults 10 --commonviews 3 --voctree "/home/simone/3D/AliceVision/voctree/vlfeat_K80L3.SIFT.tree" --voctreeWeights "" --algorithm AllResults --matchingError 4.0 --nbFrameBufferMatching 10 --robustMatching True --nNearestKeyFrames 5 --globalBundle "" --noDistortion False --noBArefineIntrinsics False --minPointVisibility 2 --outputAlembic "/home/simone/3D/RicostruzioniPointCloud/MeshroomCache/CameraLocalization/d53017125990c5ffc7ea77dcb5cb8a1a5d7cfb6d/trackedCameras.abc" --outputJSON "/home/simone/3D/RicostruzioniPointCloud/MeshroomCache/CameraLocalization/d53017125990c5ffc7ea77dcb5cb8a1a5d7cfb6d/trackedCameras.json" 
 - logFile: /home/simone/3D/RicostruzioniPointCloud/MeshroomCache/CameraLocalization/d53017125990c5ffc7ea77dcb5cb8a1a5d7cfb6d/log
 - elapsed time: 0:00:00.160893
[2019-09-09 14:42:00,366][ERROR] Error on node computation: Error on node "CameraLocalization_1":
Log:
ERROR: unrecognised option '--nNearestKeyFrames'

```
**Desktop:**
 - OS: Ubuntu 19.04
 - Meshroom Version 2019.2.0
 - AliceVision Version 2.2.0
 - Python version 3.7.3

**Comment by simogasp** [comment]
`nNearestKeyFrames` is only enabled if alicevision is built with CCTAG support.
Are u using the provided binaries or are u building your own?

**Comment by simoneBrancati** [comment]
I've built my own. Do i need to use CCTAG markers to localize a camera or is it optional?

**Comment by simogasp** [comment]
cctag is optional, you can localize the camera using any other type of features.
But now i see the problem, meshroom always add '--nNearestKeyFrames' independently of the CCTAG support.
I think you need to suppress the parameter from the meshroom node. @yann-lty help?

**Comment by simoneBrancati** [comment]
I removed the `nNearestKeyFrames` parameter from `/meshroom/nodes/aliceVision/CameraLocalization.py`.

It's this piece of code (lines: 168-175)
```python
desc.IntParam(
            name='nNearestKeyFrames',
            label='N Nearest Key Frames',
            description='''[cctag] Number of images to retrieve in the database Parameters specific for final (optional) bundle adjustment optimization of the sequence:''',
            value=5,
            range=(1, 100, 1),
            uid=[0],
            ),
```

Now **CameraLocalization** gets executed but hangs right after saving the log (just before saving the trackedCameras.json and trackedCameras.abc files)

**Comment by fabiencastan** [comment]
@simoneBrancati : Have you tried the workflow presented in [Meshroom Survival Guide](https://www.youtube.com/watch?v=eiEaHLNJJ94)?
Even if it's still WIP development, it's closer to production than the CameraLocalization node.

**Comment by simoneBrancati** [comment]
Thanks @fabiencastan.  
My intention is to solve camera poses in real time for AR purposes, so i was looking for a method that doesn't involve starting a new reconstruction for every new image.  
Is there a way to retrieve the 2D points to 3D points correspondences computed during **imageMatching**?

**Comment by fabiencastan** [comment]
@simoneBrancati Oh I see! We have worked in this area. We can a setup a confcall to discuss about it if you want (you can contact me at fabien.castan@mikrosimage.com).
