### ISSUE TITLE
[bug] ConvertSfMFormat image white list broken in Meshroom 2019.2.0 

### ISSUE THREAD

**Issue by nyacg** [alicevision/meshroom#628]
Putting anything in the image white list parameter of the ConvertSfMFormat node results in a `std::regex_error`. 

**To Reproduce**
Put anything (some view id's, some paths or a regex) in the image white list section of the ConvertSfMFormat node connected to a StructureFromMotion Node

_Note: this does *not* happen on Meshroom 2019.1.0, the expected behaviour does_

**Expected behavior**
A new smf file to be created with only views/poses for the selected view id's 

**Screenshots**
![image](https://user-images.githubusercontent.com/8298768/64607502-8b8d8500-d3c0-11e9-9dfd-a511448ae463.png)

**Log**
```
Nodes to execute:  ['ConvertSfMFormat_1']

[1/1] ConvertSfMFormat
 - commandLine: aliceVision_convertSfMFormat  --input "/tmp/MeshroomCache/StructureFromMotion/c8ba89ffcb61635e697bc3bd82cd77d3a90412de/sfm.abc" --describerTypes sift --imageWhiteList "12603840" "121933755" --views True --intrinsics True --extrinsics True --structure True --observations True --verboseLevel info --output "/tmp/MeshroomCache/ConvertSfMFormat/597a3188513273afff3829c03eee5ce17aa9a28f/sfm.abc" 
 - logFile: /tmp/MeshroomCache/ConvertSfMFormat/597a3188513273afff3829c03eee5ce17aa9a28f/log
 - elapsed time: 0:00:00.282726
ERROR:root:Error on node computation: Error on node "ConvertSfMFormat_1":
Log:
Program called with the following parameters:
 * describerTypes = "sift"
 * extrinsics = 1
 * imageWhiteList =  = [12603840, 121933755]
 * input = "/tmp/MeshroomCache/StructureFromMotion/c8ba89ffcb61635e697bc3bd82cd77d3a90412de/sfm.abc"
 * intrinsics = 1
 * observations = 1
 * output = "/tmp/MeshroomCache/ConvertSfMFormat/597a3188513273afff3829c03eee5ce17aa9a28f/sfm.abc"
 * structure = 1
 * verboseLevel = "info"
 * views = 1

terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped)

ERROR:root:Error during Graph execution Error on node "ConvertSfMFormat_1":
Log:
Program called with the following parameters:
 * describerTypes = "sift"
 * extrinsics = 1
 * imageWhiteList =  = [12603840, 121933755]
 * input = "/tmp/MeshroomCache/StructureFromMotion/c8ba89ffcb61635e697bc3bd82cd77d3a90412de/sfm.abc"
 * intrinsics = 1
 * observations = 1
 * output = "/tmp/MeshroomCache/ConvertSfMFormat/597a3188513273afff3829c03eee5ce17aa9a28f/sfm.abc"
 * structure = 1
 * verboseLevel = "info"
 * views = 1

terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped)

```

**Desktop (please complete the following and other pertinent information):**
 - OS: Ubuntu 16.04
 - Version 2019.2.0 
 - Binary version 2019.2.0

P.S. thanks for creating an awesome tool!

**Comment by fabiencastan** [comment]
Sounds difficult to debug without being able to reproduce it.
Do you still have the issue if you uncheck options like poses, views, etc.?
Do you have the same issue if you connect the `ConvertSfMFormat` directly on the output of the `CameraInit`?

**Comment by simogasp** [comment]
this may be related to #615, what's your gcc version? You may need to use a gcc and related libraries older than 4.8.

**Comment by nyacg** [comment]
Hi, I have the issue no matter what options I select to export (views, intrinsics, etc) and even if I just connect `CameraInit` to `ConvertSfMFormat`. Everything works fine if there are no elements in the image white list but fails if there is anything there.

GCC version is: `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609` but I'm using the release version of Meshroom so I wouldn't have thought this would matter?

Should the image white list be treating everything as a regex before trying to see if it's a possible id or image path?

**Comment by fabiencastan** [comment]
> GCC version is: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609 but I'm using the release version of Meshroom so I wouldn't have thought this would matter?

It's not supposed to be the case but there is a specific issue with some very old versions of libstdc++. But it's not the problem here as you have a recent version.

> Should the image white list be treating everything as a regex before trying to see if it's a possible id or image path?

It's here:
https://github.com/alicevision/AliceVision/blob/develop/src/software/convert/main_convertSfMFormat.cpp#L145
We create a regex object for each while list entry as we don't want to recreate the regex object for each input view.

Are you using a full path? It could be a problem with '\' or '/' which could be considered as valid regex characters.
Could you make a small test with just the filename?
