### ISSUE TITLE
[question] building Intrinsic fails, but Camera is in db and EXIF is ok, what else might it be?

### ISSUE THREAD

**Issue by daresan** [alicevision/meshroom#630]
**Describe the problem**
building Intrinsic fails, but Camera is in db, sensor width was wrong, which I corrected to 35.0 and EXIF is ok, what else might it be?

This is now the camera info in the db-file:
Sony;ILCE-7RM3;35.0

And this is the EXIF Information from the image files:
Model: ILCE-7RM3
Manufacturer: SONY
Sensor: 35.0 

(Image upload of the dataset does not work, because the files are bigger than 10Mb.)

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )
Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportColoredPointCloud, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, LDRToHDR, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:\Users\Daniel\AppData\Local\Temp\tmpvfw7bbga/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm"
 * output = "C:/Users/Daniel/AppData/Local/Temp/tmpvfw7bbga/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm"
 * sensorDatabase = "C:\Program Files\Meshroom-2019.2.0\aliceVision\share\aliceVision\cameraSensors.db"
 * verboseLevel = "info"

ERROR:root:Error while building intrinsics : Traceback (most recent call last):
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\meshroom\ui\reconstruction.py", line 399, in buildIntrinsics
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 192, in buildIntrinsics
RuntimeError: CameraInit failed with error code 3221225477. Command was: "aliceVision_cameraInit  --sensorDatabase "C:\Program Files\Meshroom-2019.2.0\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "C:/Users/Daniel/AppData/Local/Temp/tmpvfw7bbga/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm" --allowSingleView 1  --input "C:\Users\Daniel\AppData\Local\Temp\tmpvfw7bbga/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm""

**Desktop (please complete the following and other pertinent information):**
 - OS: win 10
 - Python version 3.6
 - Qt/PySide version ?
 - Meshroom version: 2019.2.0 release Win64

**Comment by fabiencastan** [comment]
It could be one corrupted image. Have you tried to drop only one image?

**Comment by daresan** [comment]
Thx, silly me - yes, indeed one image was corrupted!
Best regards,
Daniel

Von meinem iPad gesendet
