### ISSUE TITLE
Sony HDR-AS50

### ISSUE THREAD

**Issue by pegasuscloth** [alicevision/meshroom#636]
I want to make photogrammetry with a Sony HDR-AS50 action cam, my problem is this: can I remove the distortion of the fisheye lens inside Meshroom? If yes, how should I do it?

**Comment by natowi** [comment]
In CameraInit node, in its attributes panel, open Intrinsics and set Camera Type to Fisheye4.

**Comment by natowi** [comment]
This issue is closed due to inactivity. Feel free to re-open if new information is available.
