### ISSUE TITLE
Google Colab Meshroom not exporting mesh

### ISSUE THREAD

**Issue by Skierman** [alicevision/meshroom#638]
Hi,
When I try to use google colab for meshroom with this [https://github.com/alicevision/meshroom/wiki/Meshroom-in-Google-Colab-(cloud)](url) I get the exported .obj file as a point area cloud not as a mesh. I am opening it in blender. Thanks!

**Comment by natowi** [comment]
You may be downloading the wrong file. Look into the Texturing folder, it should contain .png, .obj and .mtl files. You need to make sure that your output directory is defined correctly.

**Comment by Skierman** [comment]
Thanks! I am downloading 3 png files one obj and one mtl file. Would you recommend using Meshlab to view them?
Thanks!

**Comment by natowi** [comment]
Yes, Meshlab is a good tool to inspect and adjust (orientation, scale) your model.
