### ISSUE TITLE
where is the script to run all the tests?

### ISSUE THREAD

**Issue by leaf918** [alicevision/meshroom#640]
![image](https://user-images.githubusercontent.com/170311/65008986-c0a85300-d93d-11e9-8761-5a329c49ad3b.png)

**Comment by natowi** [comment]
I think you have to build Alicevision with "ALICEVISION_BUILD_TESTS" set to "ON" (it is OFF by default)

**Comment by fabiencastan** [comment]
You have tests on the AliceVision side and tests on the Meshroom side.
On the Meshroom side, you can look at the travis file:
https://github.com/alicevision/meshroom/blob/d7e2a006c53fbf5a921ded9c9d5c45456d86c103/.travis.yml#L21
