### ISSUE TITLE
Manually apply exif data[question]

### ISSUE THREAD

**Issue by KenwoodFox** [alicevision/meshroom#642]
Using manual photos from my Moto Z 2 I get semi passable meshes. 
![image](https://user-images.githubusercontent.com/31870999/65085861-a3937480-d97d-11e9-8a22-3495ff8cf9db.png)
However, I've been trying to record a video at a high fps, to get less blur, so I have more images, I use blender to render out every frame as a png and use those for my projects, but I dont see the same results.
![image](https://user-images.githubusercontent.com/31870999/65085922-de95a800-d97d-11e9-9e94-7dece542ff6e.png)
Obviously the exif data is not preserved moving from a video to a still, can I add in the sensor size manually? I don't see the option for that.
Im using 2019.2.0
I'm mostly sure the camera sensor width is 4.96mm
Thanks for all the help.

 - OS: Windows 10 Home
 - Python version 3.7
 - Meshroom version: 2019.2.0 Used a release

**Comment by MightyBOBcnc** [comment]
To add EXIF data to the images you can use [ExifTool](https://www.sno.phy.queensu.ca/~phil/exiftool/) which is robust and powerful.

Manual addition of EXIF data within Meshroom would be a good feature request, I think, with options for selecting 1 or N specific images, or All images, to apply the data to.

**Comment by natowi** [comment]
@MightyBOBcnc added to https://github.com/alicevision/meshroom/wiki/Good-first-contributions
