### ISSUE TITLE
[question]Double graphics card CUDA... useful or not

### ISSUE THREAD

**Issue by lord666** [alicevision/meshroom#644]
Use CUDA graphics card, okay ... but, own 2 CUDA graphics cards (ex GTX 1070 and old GT730) does it speed up rebuilding in Meshroom or is it the same result?

**Comment by natowi** [comment]
Multi GPUs are supported, but DepthMap is still _not fully optimized_. 
For now, support for multiple GPUs if you want to utilize older graphics cards like two GT730.
Your GTX 1070 alone is good enough.
https://github.com/alicevision/meshroom/issues/250
https://github.com/alicevision/meshroom/issues/244

**Comment by lord666** [comment]
Thank you for your reply. I was hesitating because, precisely, my GPU didn't seem to me fully used ... but, the RAM ARGGGGG, I think invest in 16GB extra ... 32GB is the limit for a basic projects

**Comment by fabiencastan** [comment]
If you have 2 graphic cards, both will be used but the work is split equally between them, so if you have 2 very different configurations it could also decrease the overall performance...

Regarding RAM, you can reduce the number of points without major quality impact:
https://github.com/alicevision/meshroom/wiki/Crashed-at-Meshing

**Comment by lord666** [comment]
I wanted to test this option by reducing the value between 2000000 and 3000000 and indeed it greatly simplifies the calculations without there being big visual differences. 
I will test add photos to the project to increase the reconstruction. 
Is it possible to "lock" the 1st "structureFromMotion", so that when adding a new one,  doesn't touch it. I thought that it was already the case but comparing the "StructureFromMotion" there are small differences

**Comment by fabiencastan** [comment]
>Is it possible to "lock" the 1st "structureFromMotion", so that when adding a new one, doesn't touch it.

Yes, there is an option on the 2nd SfM to "Lock Scene Previously Reconstructed" to avoid any modification to the previously reconstructed cameras of the input SfM.
The best option IMO is to allow to make modifications to the previous scene and then realign with the previous scene using `SfMAlignment`.

**Comment by lord666** [comment]
oh..Thanks.. indeed, I had seen this option but I wasn't sure if that was it. 
I have also tested "SFMalignment" which works very well, but the meshroom interface makes it..hmm not very user-friendly for multi alignment. Mushroom is a great genius software with a very responsive community, but his nodal interface makes it difficult to access for a novice user, I'm not new in photogrammetry, but here, I'm lost like a young chick looking lol... I dream of a "nodal graph interface" like "Substance Designer" not necessarily with a lot of node, but, better management of links and especially a possibility to save node and graph presets...

**Comment by fabiencastan** [comment]
That's on its way, see some preliminary steps in this direction:
https://github.com/alicevision/meshroom/pull/632 with `--pipeline` option (so you can save a scene and use it as the default graph) and some ui improvements to the graph editor https://github.com/alicevision/meshroom/pull/612.

**Comment by lord666** [comment]
Oh oh!! it's christmas before the hour lol
I am really excited about the idea to test it, But, before that, I must continue to understand already existing option... and there are many héhé
