### ISSUE TITLE
[question] Always getting bad results, why?

### ISSUE THREAD

**Issue by LeonelF** [alicevision/meshroom#646]
I have tried several approaches, many pictures (3x around the object on different heights), few pictures (only 1x around the object) but I always got bad results similar to the screenshot bellow.

**Screenshots of the result**
- https://i.imgur.com/HYPOIBU.png
- https://i.imgur.com/5F2vbRo.jpg

**Source pictures** of the result above: https://github.com/LeonelF/Meshroom_fail_pics

**Log files**
https://github.com/LeonelF/Meshroom_fail_pics/tree/master/Logfiles

**Desktop**
 - OS: Windows 10 Professional
 - Python version 3.6.3
 - Meshroom version: 2019.2.0

 - CPU Intel Core i5-4460
 - GPU nVidia GeForce GTX 750ti
 - RAM 12 GB

Am i missing anything? Why am I getting this results with the pictures captured by me?
I have tried with markers printed on paper (different styles) and without them, always the same bad results.
I have tried with this dataset https://github.com/alicevision/dataset_monstree/tree/master/mini6 and the result was great so the problem must be with the pictures captured.

**Comment by Baasje85** [comment]
I'm on it! Going to see if I can do better.

**Comment by natowi** [comment]
Probably the texture is too smooth.

**Comment by Baasje85** [comment]
With a bit of tweaking you can retrieve all camera positions, then it is directly obvious which photos are missing. Try to make some photos of Mr. Squirrel from his eye level. I also wonder if your ground plate would perform better if it would have distinct coloured squares patters on the corners, opposed to all being black.

![image](https://user-images.githubusercontent.com/51262792/65369166-50a21180-dc4a-11e9-8cf3-79f48d4a427a.png)

Currently waiting for Depthmap, my hardware is not so impressive ;)

**Comment by Baasje85** [comment]
Sadly you got it further than I did...

![image](https://user-images.githubusercontent.com/51262792/65369458-5816ea00-dc4d-11e9-9823-92a03e6c10cb.png)

**Comment by LeonelF** [comment]
@Baasje85 But when I get the final result if I click the pictures on the left, on the result the position of the camera seems correct to me, I believe MeshRoom is getting that part ok.

@natowi I've also tried with a fur teddy bear with same results
Example using 76 pictures (one of the pictures: https://i.imgur.com/ALhugMu.jpg) result: https://i.imgur.com/OBC9eyF.jpg and with model loaded: https://i.imgur.com/ZN3WPiS.jpg if i increase the size of the points it fills the gap on the head: https://i.imgur.com/I08q5Dq.jpg

**Comment by natowi** [comment]
Try taking close-ups and adjust the [Reconstruction-parameters](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters)

**Comment by LeonelF** [comment]
Success!!!

I've tried again, tried taking pictures from more distance, and added some close ups as suggested by @natowi (thank you)

Here is the result: https://i.imgur.com/dnFqxI5.jpg
