### ISSUE TITLE
[question] Can't find the given initial pair view: --initialPairB , Could not find corresponding view in the initial pair: --initialPairB

### ISSUE THREAD

**Issue by theytaz3** [alicevision/meshroom#661]
Hello, everyone!
I would like to automate via a python script the call to the different meshroom steps. To do this, I call for each step the associated.exe in alicevision. 

However, I have a problem, at the StructureFromMotion step, the following message appears:

https://imgur.com/a/fiMQE2L

I wanted to know all the possible causes of the problem.

I would also like to point out that when I use the Meshroom GUI, everything goes well. I started the reconstruction with my images on the GUI, get the files of each step in order to launch the SFM with my script and alicevision, I still have the same error. 

**Desktop (please complete the following and other pertinent information):**
 - OS: WIN10
 - Python version : 3.7
 - Meshroom version: 2019.2.0

**Comment by Fbag96** [comment]
Hi @theytaz3,
Try changing from " " to ' '  when you use in the command line the --initialPairA parameter.
Best,
Francisco

**Comment by Nicolaj-J** [comment]
Hello @Zat-Code 

I have the same issue. Did you find a solution? I tried changing "" to ''. Didnt work for me.

**Comment by xzhang311** [comment]
@Fbag96 Thanks, changing "" to '' works for me.
