### ISSUE TITLE
[question] Only forward motion when recording

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [alicevision/meshroom#662]
**Describe the problem**
My footage comes from a camera on a car. Therefore it is one direction only. Can I tell Meshroom to not look in previous images for matches and speed up the recognition?

**Desktop (please complete the following and other pertinent information):**
 - OS: Win10
 - Meshroom version: Current

**Comment by skinkie** [comment]
I wonder if processing all the images in backwards direction might be better. Since every backward frame would contain all the information observed forward. You could make the pairlist yourself, but I am not aware of a 'videomode' similar to openMVG in the GUI.

**Comment by ErfolgreichCharismatisch** [comment]
Forward or backward is not really the issue, but preventing Meshroom from looking for reference points everywhere. In general, telling Meshroom how the pictures were taken roughly should help improve accuracy and processing speed.

**Comment by fabiencastan** [comment]
Is it only for speedup?

That's something that could be really easily be added into the ImageMatching node.

But if your camera comes back to a previous location (like a loop closure case), you will not be able to fuse the tracks from the beginning with the ones from the end. So you will start to have problems if you have a pure rotation at some point, etc.
So one more advanced strategy would be add to add another option in ImageMatching to match with prev/next images and also allow few distant images to fix the loop closure case.

**Comment by ErfolgreichCharismatisch** [comment]
@fabiencastan The issue is currently, that only a fraction of the photos being supplied are being used and the model is not being created properly. If Meshroom knew how I took the photos, it could use all photos.

**Comment by ErfolgreichCharismatisch** [comment]
I could improve the results a bit with "Guided Matching". But still, if Meshroom knew about the rough positions, it would be much more efficient. Terms like "Move in a straight line" or "no loop" could already help. Similar to the Microsoft ICE Structured Panorama option.

**Comment by curtthemartian** [comment]
If the photo method contained a GPS coordinate, it would be a lot easier like with drones.

**Comment by skinkie** [comment]
@curtthemartian Coordinates on their own would not help, since it would need to do a heading as inference, where any direction a photo could be taken on a path. Coordinates + heading would not help, because yaw, pitch and roll would need to be retrieved.

**Comment by natowi** [comment]
> That's something that could be really easily be added into the ImageMatching node.

"Sequential: based on filenames order" https://github.com/alicevision/meshroom/pull/768

**Comment by skinkie** [comment]
@natowi shall we assemble on the wiki a list of documentation issues, and try to create articles for each of them? I think many user questions are easy to reproduce. In addition: fun to describe and create a testset for.

**Comment by natowi** [comment]
@skinkie yes, that would be interesting. In the long run I try to merge all the information in the meshroom documentation. We could discuss this in a new Issue [here](https://github.com/alicevision/meshroom-manual)

**Comment by skinkie** [comment]
Lets do that!
