### ISSUE TITLE
[question]How do I make the best out of single fisheye footage?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [alicevision/meshroom#664]
**Describe the problem**
I am recording with a GoPro Hero 4 on a moving target in 4K. I use every frame for Meshroom. How do I make the best out of this fisheye footage?

**Comment by natowi** [comment]
In CameraInit node, in its attributes panel, open Intrinsics and set Camera Type to Fisheye4. You do not need to use every frame. Use the KeyframeSelection node https://github.com/alicevision/meshroom/issues/232#issuecomment-540717826

**Comment by natowi** [comment]
This issue is closed due to inactivity. Feel free to re-open if new information is available.
