### ISSUE TITLE
PrepareDenseScene error

### ISSUE THREAD

**Issue by haesenbaerg** [alicevision/meshroom#666]
Hello all,

in my actual meshroom proejct I have a problem, don't know how to fix. It allways stop at PrepareDenseScene with an error. The crazy thing is, if I don't safe before, it is working perfekt. Was deleting cache, reboot ...
But when I save it, it stops at the error at the same point.
Program called with the following parameters:
 * input = "D:/Photogrametrie/3D Scans/609er/609er außen/MeshroomCache/StructureFromMotion/a3aa525f03aa662cecda8b17531a7b52a3f53b85/sfm.abc"
 * output = "D:/Photogrametrie/3D Scans/609er/609er außen/MeshroomCache/PrepareDenseScene/1b844eef8f1e27a3c408a5ecb7d35a037414cf34"
 * outputFileType = "exr"
 * rangeSize = 26
 * rangeStart = 0
 * saveMatricesTxtFiles = 0
 * saveMetadata = 1
 * verboseLevel = "info"

Exporting Scene Undistorted Images
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|

**Comment by SBCV** [comment]
Does the problem still occur, if you remove the space in "609er außen"?
                                                                                                 ^^^

**Comment by SBCV** [comment]
Also the ß could cause problems

**Comment by haesenbaerg** [comment]
When I read it, I knew your are right. Was for sure the name of the folder. There are a few other ones in 3D Scans.  So with space it is working, but the "ß" was too much.

Thanks a lot
