### ISSUE TITLE
cameraSensor.db issues

### ISSUE THREAD

**Issue by fitzmurphy** [alicevision/meshroom#669]
I've just installed Meshroom and have run a few tests with my phone (Google Pixel 2) which seem to work just fine. I took some additional pictures with my Sony Cybershot HX9V and am getting the same error about needing to add the camera to cameraSensors.db. I've checked - and the camera is actually already IN cameraSensors.db (twice as a matter of fact). I also dumped the exif data for one of the images and there are no trailing spaces or any metadata related to the camera besides the following (from Meshroom error)

camera brand: SONY
camera model: DSC-HX9V

The exif dump shows the following:
MAKE : SONY
Camera Model Name: DSC-HX9V

Here are the two entries in cameraSensors.db:
 - Sony;DSC-HX9V;6.16
 - Sony;Sony Cyber-shot DSC-HX9V;6.17;dpreview,digicamdb,imaging-resource

Are there any other potential solutions to this issue that anyone has found?

**Comment by simogasp** [comment]
can you try to edit the file and put `Sony;Sony DSC-HX9V;6.16` for the first one?

**Comment by fitzmurphy** [comment]
Thanks for the reply - same error message...

**Comment by fitzmurphy** [comment]
Thanks Simone - just tried that with the same result...

Now I'm getting the same error on my pixel 2 XL... looks like it's reading
from the correct instance of cameraSensor.db (I'll try renaming it and see
.Meshroom errors out for not finding the .db file next...

I'll also try rebuilding aliceVision from source (although it looks like
all the dependencies have dependencies... )

John

**Comment by fitzmurphy** [comment]
Ok - just checked something - I have one set of images taken with my Pixel 2 XL which CAN be processed by Meshroom and another set that throw the error about the "camera not in the sensor database"... I dumped the exif for both images and (except for date time and location) they're identical EXCEPT for... I took one set of images in portrait mode and the other in landscape.. but there's no way that's a factor right?

**Comment by fitzmurphy** [comment]
Ok - just reinstalled everything from scratch and it seems to be working at
the moment... I'll try with some of the other images I've taken over the
past few days and let you know.

I deeply appreciate your help and support - what an awesome piece of
software this is!

John Sell
