### ISSUE TITLE
[question] Meshroom Google Colab jpg Upload

### ISSUE THREAD

**Issue by tmsd2001** [alicevision/meshroom#670]
If I upload my pics with the Script, google convert the jpg to png and then come the Error:

> focal length (in mm) metadata is missing.
Can't compute focal length (px), use default.

**Comment by natowi** [comment]
Some metadata is missing, default values are used. Check your Exif data, it should contain camera, make and ideally the focal length.

**Comment by tmsd2001** [comment]
> Some metadata is missing, default values are used. Check your Exif data, it should contain camera, make and ideally the focal length.

Yes, is missing, because google converts the files to png.

**Comment by natowi** [comment]
You can link colab to your google drive and copy the data to your colab directory. Check the google documentation for details.
