### ISSUE TITLE
Why are the models I built up all the reverse?

### ISSUE THREAD

**Issue by ProfessorMZX** [alicevision/meshroom#671]
Why are the models I built up all the reverse?
I need someone help me.

Meshroom 2.0 windows.

the model is upside down

**Comment by elliestath** [comment]
Umh, not sure what you mean. The reference system is typically random, except if you define it yourself e.g. by using known points (don't know if it is possible in AliceVision though). If it is only a visualization problem, you just need to rotate it manually.

**Comment by natowi** [comment]
> if you define it yourself e.g. by using known points (don't know if it is possible in AliceVision though).

This will be possible with the next release

> you just need to rotate it manually.

Meshlab is a good choice.

**Comment by MightyBOBcnc** [comment]
You can also insert a SfmTransform node with from_single_camera mode to define a specific camera to align the scene to.

**Comment by pjgoodall** [comment]
always upside-down
