### ISSUE TITLE
Feauture extraction error when set to Ultra

### ISSUE THREAD

**Issue by VRscience** [alicevision/meshroom#672]
**Describe the bug**
When you set the describer preset to Ultra in the Feature Extraction node, process fails

**To Reproduce**
Open Meshroon 2019 2.0
Load Images
Change describer preset to Ultra in Feature Extraction node
Start process

**Expected behavior**
Process stops with error

**Screenshots**

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: win 10
 - Meshroom version:
   - Binary version (if applicable) [e.g. 2019.2.0]

**Additional context**

**Comment by natowi** [comment]
How many images are in your project and what are your computer specs?

**Comment by nufanDK** [comment]
I have this issue as well. Running Win10, Surface Book 2 with both Intel and nVidia GPU. Forced the gpu to be nVidia when running meshroom, but it still happens. I can attach the log, if you want it
