### ISSUE TITLE
The Depth Map step crashes

### ISSUE THREAD

**Issue by Mentalink** [alicevision/meshroom#684]
Hello,
I tried to use Meshroom 2019.1.0 a few time ago and it had some issues... I decided to wait the next version, and now it has been released, I've tried it. Unfortunately, it still causes an issue. More precisely, all works until the Depth Map step (I didn't change any settings since I don't know how it works, at all..).
These are the logs:

[_4/11](4/4) FeatureMatching
 - commandLine: aliceVision_featureMatching  --input "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/CameraInit/7c57a06df38e74dc8daf26e205ee1fc68b3dba6b/cameraInit.sfm" --featuresFolders "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/FeatureExtraction/ae70f1b2cd9912472c67d221bc0f54d2f6f19c21" --imagePairsList "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/ImageMatching/a386d9581b96375f8a5ddf0c1c560b8dc925e5ed/imageMatches.txt" --describerTypes sift --photometricMatchingMethod ANN_L2 --geometricEstimator acransac --geometricFilterType fundamental_matrix --distanceRatio 0.8 --maxIteration 2048 --geometricError 0.0 --maxMatches 0 --savePutativeMatches False --guidedMatching False --exportDebugFiles False --verboseLevel info --output "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/FeatureMatching/f3d0a2e00edcaf227c2be0e99bb0773b7ab84092" --rangeStart 60 --rangeSize 20
 - logFile: C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/FeatureMatching/f3d0a2e00edcaf227c2be0e99bb0773b7ab84092/3.log
 - elapsed time: 0:00:16.108468

[5/11] StructureFromMotion
 - commandLine: aliceVision_incrementalSfM  --input "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/CameraInit/7c57a06df38e74dc8daf26e205ee1fc68b3dba6b/cameraInit.sfm" --featuresFolders "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/FeatureExtraction/ae70f1b2cd9912472c67d221bc0f54d2f6f19c21" --matchesFolders "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/FeatureMatching/f3d0a2e00edcaf227c2be0e99bb0773b7ab84092" --describerTypes sift --localizerEstimator acransac --localizerEstimatorMaxIterations 4096 --localizerEstimatorError 0.0 --lockScenePreviouslyReconstructed False --useLocalBA True --localBAGraphDistance 1 --maxNumberOfMatches 0 --minInputTrackLength 2 --minNumberOfObservationsForTriangulation 2 --minAngleForTriangulation 3.0 --minAngleForLandmark 2.0 --maxReprojectionError 4.0 --minAngleInitialPair 5.0 --maxAngleInitialPair 40.0 --useOnlyMatchesFromInputFolder False --useRigConstraint True --lockAllIntrinsics False --initialPairA "" --initialPairB "" --interFileExtension .abc --verboseLevel info --output "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/StructureFromMotion/182a36e2cf17306adc6173ee925feab1a6337e3e/sfm.abc" --outputViewsAndPoses "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/StructureFromMotion/182a36e2cf17306adc6173ee925feab1a6337e3e/cameras.sfm" --extraInfoFolder "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/StructureFromMotion/182a36e2cf17306adc6173ee925feab1a6337e3e"
 - logFile: C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/StructureFromMotion/182a36e2cf17306adc6173ee925feab1a6337e3e/log
 - elapsed time: 0:03:04.566757

[6/11](1/2) PrepareDenseScene
 - commandLine: aliceVision_prepareDenseScene  --input "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/StructureFromMotion/182a36e2cf17306adc6173ee925feab1a6337e3e/sfm.abc" --outputFileType exr --saveMetadata True --saveMatricesTxtFiles False --evCorrection False --verboseLevel info --output "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/PrepareDenseScene/cf9753f895ff52115e31dbe56b52b08c7f711b68" --rangeStart 0 --rangeSize 40
 - logFile: C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/PrepareDenseScene/cf9753f895ff52115e31dbe56b52b08c7f711b68/0.log
 - elapsed time: 0:01:58.937724

[6/11](2/2) PrepareDenseScene
 - commandLine: aliceVision_prepareDenseScene  --input "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/StructureFromMotion/182a36e2cf17306adc6173ee925feab1a6337e3e/sfm.abc" --outputFileType exr --saveMetadata True --saveMatricesTxtFiles False --evCorrection False --verboseLevel info --output "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/PrepareDenseScene/cf9753f895ff52115e31dbe56b52b08c7f711b68" --rangeStart 40 --rangeSize 40
 - logFile: C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/PrepareDenseScene/cf9753f895ff52115e31dbe56b52b08c7f711b68/1.log
 - elapsed time: 0:01:22.172145

[7/11](1/23) DepthMap
 - commandLine: aliceVision_depthMapEstimation  --input "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/StructureFromMotion/182a36e2cf17306adc6173ee925feab1a6337e3e/sfm.abc" --imagesFolder "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/PrepareDenseScene/cf9753f895ff52115e31dbe56b52b08c7f711b68" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/DepthMap/1fe787cc96ba2fab52f6c94c1a7a4a8e4a753e2e" --rangeStart 0 --rangeSize 3
 - logFile: C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/DepthMap/1fe787cc96ba2fab52f6c94c1a7a4a8e4a753e2e/0.log
 - elapsed time: 0:02:21.789140
ERROR:root:Error on node computation: Error on node "DepthMap_1(0)":
Log:
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/PrepareDenseScene/cf9753f895ff52115e31dbe56b52b08c7f711b68"
 * input = "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/StructureFromMotion/182a36e2cf17306adc6173ee925feab1a6337e3e/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/DepthMap/1fe787cc96ba2fab52f6c94c1a7a4a8e4a753e2e"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[17:26:32.968520][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce 710M
        - compute capability:      2.1
        - total device memory:     1024 MB
        - device memory available: 822 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   1536
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {65535,65535,65535}
        - max 2D array texture:    {65536,65535}
        - max 3D array texture:    {2048,2048,2048}
        - max 2D linear texture:   {65000,65000,1048544}
        - max 2D layered texture:  {16384,16384,2048}
        - number of SM(x)s:        2
        - registers per SM(x):     32768
        - registers per block:     32768
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte

[17:26:39.030832][info] Supported CUDA-Enabled GPU detected.
[17:26:39.780809][info] Found 1 image dimension(s):
[17:26:39.780809][info]         - [4032x3024]
[17:26:48.264917][info] Overall maximum dimension: [4032x3024]
[17:26:48.264917][info] Create depth maps.
number of CUDA devices: 1
   0: GeForce 710M
[17:26:48.280571][info] # GPU devices: 1, # CPU threads: 4
[17:26:48.280571][info] Plane sweeping parameters:
        - scale: 2
        - step: 3
[17:26:48.280571][info] PlaneSweepingCuda:
        - _nImgsInGPUAtTime: 2
        - scales: 2
        - subPixel: Yes
        - varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 201.793747, free: 822.206238, total: 1024.000000
Device 0 memory - used: 319.918762, free: 704.081238, total: 1024.000000
[17:27:33.152890][info] Estimate depth map, view id: 26352733

WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(11)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(12)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(13)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(14)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(15)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(16)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(17)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(18)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(19)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(20)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(21)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(22)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "DepthMap_1(0)":
Log:
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/PrepareDenseScene/cf9753f895ff52115e31dbe56b52b08c7f711b68"
 * input = "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/StructureFromMotion/182a36e2cf17306adc6173ee925feab1a6337e3e/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/Users/Antoine/Desktop/Test_photogrammetrie/MeshroomCache/DepthMap/1fe787cc96ba2fab52f6c94c1a7a4a8e4a753e2e"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[17:26:32.968520][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce 710M
        - compute capability:      2.1
        - total device memory:     1024 MB
        - device memory available: 822 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   1536
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {65535,65535,65535}
        - max 2D array texture:    {65536,65535}
        - max 3D array texture:    {2048,2048,2048}
        - max 2D linear texture:   {65000,65000,1048544}
        - max 2D layered texture:  {16384,16384,2048}
        - number of SM(x)s:        2
        - registers per SM(x):     32768
        - registers per block:     32768
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte

[17:26:39.030832][info] Supported CUDA-Enabled GPU detected.
[17:26:39.780809][info] Found 1 image dimension(s):
[17:26:39.780809][info]         - [4032x3024]
[17:26:48.264917][info] Overall maximum dimension: [4032x3024]
[17:26:48.264917][info] Create depth maps.
number of CUDA devices: 1
   0: GeForce 710M
[17:26:48.280571][info] # GPU devices: 1, # CPU threads: 4
[17:26:48.280571][info] Plane sweeping parameters:
        - scale: 2
        - step: 3
[17:26:48.280571][info] PlaneSweepingCuda:
        - _nImgsInGPUAtTime: 2
        - scales: 2
        - subPixel: Yes
        - varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 201.793747, free: 822.206238, total: 1024.000000
Device 0 memory - used: 319.918762, free: 704.081238, total: 1024.000000
[17:27:33.152890][info] Estimate depth map, view id: 26352733_

I hope someone is going to be able to help me finding a solution to my problem!
Have a nice day!

(PS: Sorry if my post contains mistakes, I'm not English)

**Comment by fabiencastan** [comment]
The capabilities of the graphic card is quite limited:
- compute capability: 2.1
- device memory available: 822 MB

You could try to reduce the "downscale" factor, it will reduce the quality of the output but it's probably the only way to get a result on this machine.

**Comment by bill-orange** [comment]
I had the same problem.  I re-photographed the subject with the resolution reduced to 1600 X 1200 on my Canon G11 and I did not experience the Depth Map crash again.

**Comment by Mentalink** [comment]
Thank you both for your answers, I will try to reduce the downscale and see if it works!

**Comment by Mentalink** [comment]
I saw it could work with Linux instead of Windows, so I've just tried it and it still crashes at DepthMap step... I also tried to set the downscale to the minimum (1 in lieu of 2) and it still doesn't work...

**Comment by fabiencastan** [comment]
1 means no downscale, so the image to process will be bigger.
You should try 4 instead of 1.

**Comment by bill-orange** [comment]
(4) worked for me when I tried it but chose to downsize the images to 1600 X 1200 instead.  I did not see any sort of quality hit and the image storage requirements both on the camera's SD and in the computer were decreased as a bonus.

**Comment by Mentalink** [comment]
Hello,
I tried to augment the downscale (4 then 8 then 16) and it still crashes.
I think I'm going to try bill-orange's tip, hoping it'll work :(

**Comment by bill-orange** [comment]
How many pictures?  I used about 40 only. Not to solve this problem, just laziness.

**Comment by Mentalink** [comment]
I tried with 91 new pictures (1440x1080) on Linux, and it still crashes but for another reason...
My computer has a Nvidia GPU (710M), which is not terrible but it should do the trick, right?

I let you see the logs:
`Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "/home/antoine/Documents/MeshroomCache/PrepareDenseScene/8a536c983e547a77ca021d02731d9818ad0dc20a"
 * input = "/home/antoine/Documents/MeshroomCache/StructureFromMotion/8238328fac74eacfc41b560ae426ed2538ec7c0d/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "/home/antoine/Documents/MeshroomCache/DepthMap/17092a4f1b9df3437692c2b0e057530ae4634dac"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[15:24:04.070718][warning] Could not determine number of CUDA cards in this system
[15:24:04.070401][warning] No CUDA-Enabled GPU.
[15:24:04.070916][error] cudaGetDeviceCount failed: CUDA driver version is insufficient for CUDA runtime version
[15:24:04.070935][info] Can't find CUDA-Enabled GPU.
[15:24:04.070950][error] This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0).
`

**Comment by bill-orange** [comment]
I am no expert but it looks like its griping about your video card.  I like Linux but but it doesn't have as many drivers as Windows for virus devices  and some are not current.  I still can not make Linux print to my laser printer.  See if you can find a different, possibly better driver for your video card.

**Comment by Mentalink** [comment]
So all I can do is giving up?
Maybe you know another (free) software to make photogrammetry? I am not sure OpenDroneMap works for short-distance...

**Comment by bill-orange** [comment]
There are used CUDA enabled cards on eBay priced at well under $100.  Even if you found software that would work, it would probably run like a slug.

**Comment by natowi** [comment]
@Mentalink 

> [15:24:04.070718][warning] Could not determine number of CUDA cards in this system
> [15:24:04.070401][warning] No CUDA-Enabled GPU.
> [15:24:04.070916][error] cudaGetDeviceCount failed: CUDA driver version is insufficient for CUDA runtime version
> [15:24:04.070935][info] Can't find CUDA-Enabled GPU.
> [15:24:04.070950][error] This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0).
> 

Your Nvidia Geforce 710M GPU supports CUDA 2.1. I think you did not install the nvidia driver correctly.

**Comment by Mentalink** [comment]
I will try that, thank you natowi! What do you think between Windows (10) and Linux is better?

**Comment by Mentalink** [comment]
I added the software to Nvidia settings and it worked! The DepthMap step ended with success! Now I'm waiting for the Meshing step to end, hoping it won't crash :)

**Comment by Mentalink** [comment]
All worked!! I'm very happy, thank you all for the help! ;)
