### ISSUE TITLE
Unable to add images to Meshroom GUI

### ISSUE THREAD

**Issue by colin4554** [alicevision/meshroom#685]
I'm able to open the Meshroom gui, but I'm unable to drag any images into the program.

**Error Message**

```
RuntimeError: CameraInit failed with error code 127. 
Command was: "aliceVision_cameraInit  --groupCameraFallback folder 
--defaultFieldOfView 45.0 --verboseLevel info --sensorDatabase "" 
--output "/var/folders/hb/8mjkctv109zfgfjq35sttchh0000gt/T/tmp7V8jab/
CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm" 
--allowSingleView 1
```

I'm running macOS 10.14.6
 - Python 3.7.4
 - The latest version of Meshroom

This is also my first post, so if I didn't do anything right just let me know.

**Comment by simogasp** [comment]
`--sensorDatabase "" ` is empty
You probably forgot to set `ALICEVISION_SENSOR_DB` to point to the `cameraSensors.db` database (usually in share if u are using the prebuilt binaries or instlled copy of alicevision or in /src/aliceVision/sensorDB/cameraSensors.db of the source code.
So when you launch meshroom be sure to `export ALICEVISION_SENSOR_DB=path/to/cameraSensors.db`

https://github.com/alicevision/meshroom/blob/develop/INSTALL.md#alicevision

**Comment by forest-hermit** [comment]
It happens the same to me but with different output:

`No input images.
ERROR:root:Error while building intrinsics : Traceback (most recent call last):
  File "/opt/Meshroom/meshroom/ui/reconstruction.py", line 399, in buildIntrinsics
  File "/opt/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 192, in buildIntrinsics
RuntimeError: CameraInit failed with error code 1. Command was: "aliceVision_cameraInit  --sensorDatabase "/home/otomo/Programas/Meshroom-2019.2.0/aliceVision/share/aliceVision/cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "/tmp/tmpish0s_7d/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm" --allowSingleView 1 "
`

**Comment by forest-hermit** [comment]
I checked that ALICEVISION_SENSOR_DB to point to the cameraSensors.db correctly.

**Comment by forest-hermit** [comment]
In my case it was caused by the strange JPEG format used by the drone, as soon as I converted to a normal JPEG the images was accepted (unfortunately doing that I lost all the metadata.
