### ISSUE TITLE
[question] Photo Align

### ISSUE THREAD

**Issue by JOSETUMAHE** [alicevision/meshroom#688]
Hello, i'am having an issue about the images align. All cams line up in the same side and i don't know how to repair it, all the presets are the originals.

Here you can see all the photos:https://drive.google.com/drive/folders/1cMpDNg_7f9AhwXD6_PbPUGalLf5wzmIz?usp=sharing

If someone can help me would be great.

**Comment by natowi** [comment]
- reflective and transparent surfaces are unsuited for photogrammetry.
- avoid lens flare and blurry images
- min. 60% image overlap
- object should fill most of the image frame

**Comment by MightyBOBcnc** [comment]
Furthermore, hard shadows (like a sunny day) aren't good for the process and can mess with feature extraction; ideally you want flat lighting like a cloudy day with little to no shadows (or controlled lighting). 

Also if it is having issues with alignment you can try adding some 'landmarks' around the object when you photograph it, like a test pattern printed on paper on the ground, or even mundane objects like a couple of shoes or large rocks or boxes on the ground near the helmet.  Take photos at 2 or 3 different distances (like 3, 6, 10, 15 feet) in a ring, trying to keep at least one of the landmark objects in each image.  The landmarks will help the software orient itself if it can see them.  Shoot at a high aperture number like F12, F14 if you can to stop the background from being out of focus.

**Comment by natowi** [comment]
This issue is closed due to inactivity. Feel free to re-open if new information is available.
