### ISSUE TITLE
Add option to export dense point cloud to other formats (Workaround here)

### ISSUE THREAD

**Issue by miquelrosell99** [alicevision/meshroom#690]
**Describe the bug**
PrepareDenseScene node fails for ConvertSfMFormat input in .ply, so i can only export .ply of low density point clouds
![Captura](https://user-images.githubusercontent.com/38435442/68072516-018de700-fd87-11e9-9563-e03de96ddeb4.JPG)

**Comment by natowi** [comment]
You can simply change the Inter File Extension from abc to ply in the StructureFromMotion node (Advanced settings enabled) so you don´t need the ConvertSfMFormat node in this case.

**Comment by miquelrosell99** [comment]
> You can simply change the Inter File Extension from abc to ply in the StructureFromMotion node (Advanced settings enabled) so you don´t need the ConvertSfMFormat node in this case.

But what if I need the dense point cloud? Meshing node only outputs .abc file, and I can't manage to use ConverSfM node there
Your suggestion was very useful for SfM node. thank you very much. I would really appreciate any help in the issue mentioned above. It's for a final degree project

**Comment by natowi** [comment]
You can export the Raw Dense Point Cloud by enabling the advanced settings in the Meshing node. You might also want to enable "Colourize Output" to get a coloured point cloud.

**Comment by miquelrosell99** [comment]
> You can export the Raw Dense Point Cloud by enabling the advanced settings in the Meshing node. You might also want to enable "Colourize Output" to get a coloured point cloud.

But the raw file is in .abc too. I need .ply

**Comment by natowi** [comment]
Let me check a few things

**Comment by natowi** [comment]
- [ConvertSfMFormat ](https://meshroom-manual.readthedocs.io/en/latest/node-reference/nodes/ConvertSfMFormat.html) at the moment only supports the internal sfm filetype

- Meshing node output filetype for the pointcloud can not be changed at the moment, although it should be possible as of this [PR](https://github.com/alicevision/AliceVision/pull/597)

- You can import the abc file in Blender (I am using v2.8) and then export the point cloudas obj (ply did not work for me...), then import the Point Cloud to Meshlab and File->ExportMeshAs->PLY

**Comment by miquelrosell99** [comment]
> * [ConvertSfMFormat ](https://meshroom-manual.readthedocs.io/en/latest/node-reference/nodes/ConvertSfMFormat.html) at the moment only supports the internal sfm filetype
> * Meshing node output filetype for the pointcloud can not be changed at the moment - in the GUI!
> 
> Run the Meshing node (only, delete data if necessary) in the GUI with selected settings, then go to the CLI in the background and copy the parameters to a text file (select+enter). Then change abc extension to ply.
> Open the Meshing folder and delete the files.
> 
> By running the Meshing node now from the CLI we will get our renamed file extension:
> 
> Start new CLI, navigate to ..\Meshroom-2019.2.0\aliceVision\bin
> then type:
> 
> aliceVision_meshing.exe (paste your changed parameters set + enter to run)
> 
> Example:
> 
> `C:\Users\user>D:\Meshroom\Meshroom-2019.2.0-win64\Meshroom-2019.2.0\aliceVision\bin\aliceVision_meshing.exe --input "C:/Users/user/AppData/Local/Temp/MeshroomCache/StructureFromMotion/5893adbb9647185e705e57e98007c459ebb29091/sfm.abc" --depthMapsFolder "C:/Users/user/AppData/Local/Temp/MeshroomCache/DepthMap/79bd8b4b35079d2c5a60be3b5302399952760ed5" --depthMapsFilterFolder "C:/Users/user/AppData/Local/Temp/MeshroomCache/DepthMapFilter/47bbddab7c0b3ee1c10675095772b16e22db6a01" --estimateSpaceFromSfM True --estimateSpaceMinObservations 3 --estimateSpaceMinObservationAngle 10 --maxInputPoints 50000000 --maxPoints 5000000 --maxPointsPerVoxel 1000000 --minStep 2 --partitioning singleBlock --repartition multiResolution --angleFactor 15.0 --simFactor 15.0 --pixSizeMarginInitCoef 2.0 --pixSizeMarginFinalCoef 4.0 --voteMarginFactor 4.0 --contributeMarginFactor 2.0 --simGaussianSizeInit 10.0 --simGaussianSize 10.1 --minAngleThreshold 1.0 --refineFuse True --addLandmarksToTheDensePointCloud False --colorizeOutput True --saveRawDensePointCloud False --verboseLevel info --outputMesh "C:/Users/user/AppData/Local/Temp/MeshroomCache/Meshing/709cfa61758574b425bb17aecfc577ca493193c3/mesh.obj" --output "C:/Users/user/AppData/Local/Temp/MeshroomCache/Meshing/709cfa61758574b425bb17aecfc577ca493193c3/densePointCloud.ply"`
> 
> ![ply](https://user-images.githubusercontent.com/8138537/68075791-08c7eb80-fdad-11e9-8854-f3a5731ae11b.JPG)
> 
> Monstree 3 images dense point cloud demo

Wow thanks so much. Tomorrow I'll look into it and report back

**Comment by miquelrosell99** [comment]
> * [ConvertSfMFormat ](https://meshroom-manual.readthedocs.io/en/latest/node-reference/nodes/ConvertSfMFormat.html) at the moment only supports the internal sfm filetype
> * Meshing node output filetype for the pointcloud can not be changed at the moment - in the GUI!
> 
> Run the Meshing node (only, delete data if necessary) in the GUI with selected settings, then go to the CLI in the background and copy the parameters to a text file (select+enter). Then change abc extension to ply.
> Open the Meshing folder and delete the files.
> 
> By running the Meshing node now from the CLI we will get our renamed file extension:
> 
> Start new CLI, navigate to ..\Meshroom-2019.2.0\aliceVision\bin
> then type:
> 
> aliceVision_meshing.exe (paste your changed parameters set + enter to run)
> 
> Example:
> 
> `C:\Users\user>D:\Meshroom\Meshroom-2019.2.0-win64\Meshroom-2019.2.0\aliceVision\bin\aliceVision_meshing.exe --input "C:/Users/user/AppData/Local/Temp/MeshroomCache/StructureFromMotion/5893adbb9647185e705e57e98007c459ebb29091/sfm.abc" --depthMapsFolder "C:/Users/user/AppData/Local/Temp/MeshroomCache/DepthMap/79bd8b4b35079d2c5a60be3b5302399952760ed5" --depthMapsFilterFolder "C:/Users/user/AppData/Local/Temp/MeshroomCache/DepthMapFilter/47bbddab7c0b3ee1c10675095772b16e22db6a01" --estimateSpaceFromSfM True --estimateSpaceMinObservations 3 --estimateSpaceMinObservationAngle 10 --maxInputPoints 50000000 --maxPoints 5000000 --maxPointsPerVoxel 1000000 --minStep 2 --partitioning singleBlock --repartition multiResolution --angleFactor 15.0 --simFactor 15.0 --pixSizeMarginInitCoef 2.0 --pixSizeMarginFinalCoef 4.0 --voteMarginFactor 4.0 --contributeMarginFactor 2.0 --simGaussianSizeInit 10.0 --simGaussianSize 10.1 --minAngleThreshold 1.0 --refineFuse True --addLandmarksToTheDensePointCloud False --colorizeOutput True --saveRawDensePointCloud False --verboseLevel info --outputMesh "C:/Users/user/AppData/Local/Temp/MeshroomCache/Meshing/709cfa61758574b425bb17aecfc577ca493193c3/mesh.obj" --output "C:/Users/user/AppData/Local/Temp/MeshroomCache/Meshing/709cfa61758574b425bb17aecfc577ca493193c3/densePointCloud.ply"`
> 
> ![ply](https://user-images.githubusercontent.com/8138537/68075791-08c7eb80-fdad-11e9-8854-f3a5731ae11b.JPG)
> 
> Monstree 3 images dense point cloud demo

I've seen the commits. Can't build meshroom at the moment, so if you do and share via link I'd appreciate it a lot. This way we can test it too. Thanks

**Comment by natowi** [comment]
@miquelrosell99 you don´t need to build Meshroom, you can use the CLI for now as I described.

**Comment by miquelrosell99** [comment]
@natowi Yes, that works. Thanks! Eager to see it implemented in GUI too!

**Comment by natowi** [comment]
Ok here is a work around with gui support

in meshroom/nodes/alicevision/meshing.py add 
```
desc.File(
            name="output",
            label="Output Dense Point Cloud",
            description="Output dense point cloud ('abc', 'ply', 'json', 'xml', 'baf', 'bin').",
			value='',
            uid=[],
        ),
```
as last entry within `inputs = [       ]`

This allows for a custom path to be defined for the dense point cloud.

You do not need to compile meshroom for this to work:
Download the Meshroom repository zip, extract it and copy the following folders from your Meshroom binary folder: aliceVision, qtPlugins

Then you can use the CLI (or create a .bat) to start the gui:

(yourhdd) d:
cd (yourpathtomeshroom)
set ALICEVISION_SENSOR_DB=(yourpath)\meshroom\aliceVision\share\aliceVision\cameraSensors.db
set ALICEVISION_VOCTREE=(yourpath)\meshroom\aliceVision\share\aliceVision\vlfeat_K80L3.SIFT.tree
set ALICEVISION_ROOT=(yourpath)\meshroom\aliceVision
set ALICEVISION=(yourpath)\meshroom\aliceVision
set PYTHONPATH=%CD% && python meshroom/ui

**Comment by miquelrosell99** [comment]
@natowi I get this error. I installed the python scripts it told me to install... First command works well btw
C:\Program Files\Meshroom Dev>set PYTHONPATH=%CD% && python meshroom/ui
WARNING:root:== The following plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
WARNING:root:QQmlApplicationEngine failed to load component
WARNING:root:file:///C:/Program Files/Meshroom Dev/meshroom/ui/qml/main.qml:2 plugin cannot be loaded for module "QtQuick.Controls": No se puede cargar la biblioteca C:\Users\Miquel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PySide2\qml\QtQuick\Controls.2\qtquickcontrols2plugin.dll: No se puede encontrar el m?dulo especificado.
![image](https://user-images.githubusercontent.com/38435442/68532039-47aff100-0319-11ea-8719-f2b1105c3e85.png)

**Comment by natowi** [comment]
You missed to copy the qtPlugins folder. The best way to put all folders together is to create a new folder and copy paste in the alicevision and qtplugins folders from the binary release and then the meshroom folder from the github repository download.
![mr](https://user-images.githubusercontent.com/8138537/68532514-58af3100-031e-11ea-9021-3c6cfcf95651.JPG)

You need to install the requirements using 

```
cd meshroom
pip install -r requirements.txt
```
You might need to install pip first.

**Comment by miquelrosell99** [comment]
I'm using Python 3.8. Maybe that's the issue. But I can't seem to get pip to install on 3.3
pip install PySide2==5.13.0 doesn't work on 3.8...

**Comment by natowi** [comment]
Do you have pip installed? https://pip.pypa.io/en/stable/installing/

**Comment by miquelrosell99** [comment]
Yes... Comes preinstalled on 3.8

**Comment by natowi** [comment]
Can you try pip install PySide2 ?

**Comment by miquelrosell99** [comment]
The error is the same 
![image](https://user-images.githubusercontent.com/38435442/68532736-5bf7ec00-0321-11ea-8f27-2de6804682b5.png)

**Comment by natowi** [comment]
Try running your cli as admin.

**Comment by miquelrosell99** [comment]
Okay, using Python 3.7.5 works. I guess PySide2 is not yet compatible with Python 3.8.0
Everything installed now. I'll try again

**Comment by miquelrosell99** [comment]
@natowi Once I add themodification to meshing node I get this error:
C:\Users\Miquel\Desktop\MESHROOM>set PYTHONPATH=C:\Users\Miquel\Desktop\MESHROOM   && python meshroom/ui
WARNING:root:== The following plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

Traceback (most recent call last):
  File "C:\Users\Miquel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Miquel\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "meshroom/ui\__main__.py", line 11, in <module>
    app = MeshroomApp(sys.argv)
  File "C:\Users\Miquel\Desktop\MESHROOM\meshroom\ui\app.py", line 104, in __init__
    r = Reconstruction(parent=self)
  File "C:\Users\Miquel\Desktop\MESHROOM\meshroom\ui\reconstruction.py", line 399, in __init__
    self.new()
  File "C:\Users\Miquel\Desktop\MESHROOM\meshroom\ui\reconstruction.py", line 409, in new
    self.setGraph(multiview.photogrammetry())
  File "C:\Users\Miquel\Desktop\MESHROOM\meshroom\multiview.py", line 63, in photogrammetry
    sfmNodes, mvsNodes = photogrammetryPipeline(graph)
  File "C:\Users\Miquel\Desktop\MESHROOM\meshroom\multiview.py", line 89, in photogrammetryPipeline
    mvsNodes = mvsPipeline(graph, sfmNodes[-1])
  File "C:\Users\Miquel\Desktop\MESHROOM\meshroom\multiview.py", line 155, in mvsPipeline
    depthMapsFilterFolder=depthMapFilter.output)
  File "C:\Users\Miquel\Desktop\MESHROOM\meshroom\core\graph.py", line 458, in addNewNode
    n = self.addNode(Node(nodeType, position=position, **kwargs), uniqueName=name)
  File "C:\Users\Miquel\Desktop\MESHROOM\meshroom\core\node.py", line 683, in __init__
    self._attributes.add(attributeFactory(attrDesc, None, True, self))
  File "C:\Users\Miquel\Desktop\MESHROOM\meshroom\common\qt.py", line 106, in add
    self.append(obj)
  File "C:\Users\Miquel\Desktop\MESHROOM\meshroom\common\qt.py", line 118, in append
    self.extend([obj])
  File "C:\Users\Miquel\Desktop\MESHROOM\meshroom\common\qt.py", line 123, in extend
    [self._referenceItem(obj) for obj in iterable]
  File "C:\Users\Miquel\Desktop\MESHROOM\meshroom\common\qt.py", line 123, in <listcomp>
    [self._referenceItem(obj) for obj in iterable]
  File "C:\Users\Miquel\Desktop\MESHROOM\meshroom\common\qt.py", line 268, in _referenceItem
    raise ValueError("Object key {}:{} is not unique".format(self._keyAttrName, key))
ValueError: Object key name:output is not unique

**Comment by natowi** [comment]
You need to remove the same code from the `outputs = [` section at the end of the file

**Comment by miquelrosell99** [comment]
> You need to remove the same code from the `outputs = [` section at the end of the file
> Basically we move the filepath gui part from output to the input class. (Only the input class allows path modification for now.)

I've taken a different approach to this. I modified the code so it has a .ply file type, but left everything else as is. This way it should work as always, but with .ply file output. After that I use a Publish node, so everything is in the same place if I need to export more stuff
![image](https://user-images.githubusercontent.com/38435442/68533203-8b105c80-0325-11ea-86be-63836a359237.png)

**Comment by natowi** [comment]
Yes, this is the easiest solution for your problem

**Comment by miquelrosell99** [comment]
Thanks for all the help. With this I can continue working on my project!
Also, any way to get the point could to more than 1 million points? Increasing FeatureExtraction to Ultra generates a denser sparse cloud, but final dense cloud is still 1 million points, same as using FeatureExtraction on Normal

**Comment by natowi** [comment]
You could try setting downscale to 1 in the DepthMap node and increase the Max Points in Meshing.

**Comment by miquelrosell99** [comment]
@natowi Using your commit for adding a proper menu works great!
This one: https://github.com/alicevision/meshroom/commit/984e76e09ae54e45768083f7dc84de716fd94c33
Will try your suggestion for increasing point count

**Comment by miquelrosell99** [comment]
@natowi This error appears when using commits from your branch to add the file type selection:
![image](https://user-images.githubusercontent.com/38435442/68542928-4af6bb80-03b1-11ea-8450-db2f7fb3897a.png)

**Comment by natowi** [comment]
I have changed the code since (check the PRfor details).

At the moment there is the problem left, that
```

class Meshing(desc.CommandLineNode):
    commandLine = 'aliceVision_meshing {allParams}'
```

calls all Params name=(...) but my file type selector is not a valid param

```
desc.ChoiceParam(
            name='outputDensePointCloud',
...
```

I think this can be fixed using all supported params, leaving out outputDensePointCloud:

```
class Meshing(desc.CommandLineNode):
    commandLine = 'aliceVision_meshing --input {inputValue} ...
```

I did not test this yet.

**Comment by miquelrosell99** [comment]
I'll test just to check. What do you mean by the PR? Latest commit is from 2 days ago

**Comment by natowi** [comment]
PR=Pull request 

My last update was `value=desc.Node.internalFolder + 'densepointcloud.{outputDenseFileTypeValue}',`

`commandLine = 'aliceVision_meshing --input {inputValue}` was my example.

`commandLine = 'aliceVision_meshing` starts the CLI and aliceVision_meshing.exe with the following parameters (by default {allParams}). allParams will look for all `desc.???Param(` and adds the name and value this way to the cli: `aliceVision_meshing.exe --input c:\sfm.abc ...`

By adding 
```
desc.ChoiceParam(
            name='outputDenseFileType',
```
and leaving {allParams} `--outputDenseFileType value` is added to the cli, but the command does not exist. I think this can be fixed by listing only the supported commands instead of {allParams}.

**Comment by miquelrosell99** [comment]
I see. So we would need to add all parameters manually?

**Comment by miquelrosell99** [comment]
@natowi I added these, but the error is still the same:
commandLine = 'aliceVision_meshing --input {inputValue} {depthMapsFolderValue} {depthMapsFilterFolderValue} {estimateSpaceFromSfMValue} {estimateSpaceMinObservationsValue} {estimateSpaceMinObservationAngleValue} {maxInputPointsValue} {maxPointsPerVoxelValue} {minStepValue} {partitioningValue} {repartitionValue} {angleFactorValue} {simFactorValue} {pixSizeMarginInitCoefValue} {pixSizeMarginFinalCoefValue} {voteMarginFactorValue} {contributeMarginFactorValue} {simGaussianSizeInitValue} {simGaussianSizeValue} {minAngleThresholdValue} {refineFuseValue} {addLandmarksToTheDensePointCloudValue} {colorizeOutputValue} {saveRawDensePointCloudValue} {verboseLevelValue} --output {outputMeshValue} {outputValue}'

**Comment by miquelrosell99** [comment]
After adding this :
commandLine = 'aliceVision_meshing --input {inputValue} {depthMapsFolderValue} {depthMapsFilterFolderValue} {estimateSpaceFromSfMValue} {estimateSpaceMinObservationsValue} {estimateSpaceMinObservationAngleValue} {maxInputPointsValue} {maxPointsPerVoxelValue} {minStepValue} {partitioningValue} {repartitionValue} {angleFactorValue} {simFactorValue} {pixSizeMarginInitCoefValue} {pixSizeMarginFinalCoefValue} {voteMarginFactorValue} {contributeMarginFactorValue} {simGaussianSizeInitValue} {simGaussianSizeValue} {minAngleThresholdValue} {refineFuseValue} {addLandmarksToTheDensePointCloudValue} {colorizeOutputValue} {saveRawDensePointCloudValue} {verboseLevelValue} --output {outputValue} {outputMeshValue}'
I get this error @natowi 
![image](https://user-images.githubusercontent.com/38435442/68545527-3f65bd80-03ce-11ea-9014-1a8975a06829.png)

**Comment by natowi** [comment]
{depthMapsFolderValue} will only add the /value/, so you need to look up all the --params and add them like this --input {inputValue}

**Comment by miquelrosell99** [comment]
I dont understand... HEre you use it like this
![image](https://user-images.githubusercontent.com/38435442/68545582-c31faa00-03ce-11ea-93ea-9c7f3c9b279f.png)

**Comment by natowi** [comment]
Yes, for Instant Meshes the expected CLI command is

<inputpath> -S <smoothvalue> --output <outputpath>

**Comment by miquelrosell99** [comment]
And for Meshing?

**Comment by natowi** [comment]
Required parameters:
  -i [ --input ] arg                    SfMData file.
  -o [ --output ] arg                   Output Dense SfMData file.
  -o [ --outputMesh ] arg               Output mesh (OBJ file format).

Optional parameters:
  --depthMapsFolder arg                 Input depth maps folder.
  --depthMapsFilterFolder arg           Input filtered depth maps folder.
  --maxInputPoints arg (=50000000)      Max input points loaded from images.
  --maxPoints arg (=5000000)            Max points at the end of the depth maps
                                        fusion.
  --maxPointsPerVoxel arg (=6000000)    Max points per voxel.
  --minStep arg (=2)                    The step used to load depth values from
                                        depth maps is computed from
                                        maxInputPts. Here we define the minimal
                                        value for this step, so on small
                                        datasets we will not spend too much
                                        time at the beginning loading all depth
                                        values.
  --simFactor arg (=15)                 simFactor
  --angleFactor arg (=15)               angleFactor
  --partitioning arg (=1)               Partitioning: 'singleBlock' or 'auto'.
  --repartition arg (=1)                Repartition: 'multiResolution' or
                                        'regularGrid'.
  --estimateSpaceFromSfM arg (=1)       Estimate the 3d space from the SfM.
  --addLandmarksToTheDensePointCloud arg (=0)
                                        Add SfM Landmarks into the dense point
                                        cloud (created from depth maps). If
                                        only the SfM is provided in input, SfM
                                        landmarks will be used regardless of
                                        this option.
  --colorizeOutput arg (=0)             Whether to colorize output dense point
                                        cloud and mesh.

Advanced parameters:
  --universePercentile arg (=0.999)     universe percentile
  --estimateSpaceMinObservations arg (=3)
                                        Minimum number of observations for SfM
                                        space estimation.
  --estimateSpaceMinObservationAngle arg (=10)
                                        Minimum angle between two observations
                                        for SfM space estimation.
  --pixSizeMarginInitCoef arg (=2)      pixSizeMarginInitCoef
  --pixSizeMarginFinalCoef arg (=1)     pixSizeMarginFinalCoef
  --voteMarginFactor arg (=4)           voteMarginFactor
  --contributeMarginFactor arg (=2)     contributeMarginFactor
  --simGaussianSizeInit arg (=10)       simGaussianSizeInit
  --simGaussianSize arg (=10)           simGaussianSize
  --minAngleThreshold arg (=0.10000000000000001)
                                        minAngleThreshold
  --refineFuse arg (=1)                 refineFuse
  --saveRawDensePointCloud arg (=0)     Save dense point cloud before cut and
                                        filtering.

Log parameters:
  -v [ --verboseLevel ] arg (=info)     verbosity level (fatal, error, warning,
                                        info, debug, trace).

**Comment by natowi** [comment]
There are a lot parameters, this is why I have not tested this yet.

**Comment by miquelrosell99** [comment]
But I already have all these parameters added. outputMesh is there in the code
![image](https://user-images.githubusercontent.com/38435442/68545682-9f109880-03cf-11ea-88da-ff7b2b7cc556.png)

**Comment by miquelrosell99** [comment]
Tag me when you test it please

**Comment by natowi** [comment]
You added only the value variables. They also need the --command prefix as listed above.

**Comment by miquelrosell99** [comment]
Okay now it works. I'll put all the proper names to optional parameters

**Comment by fabiencastan** [comment]
Do not modify the full pipeline to use another file format, just use ConvertSfM where you need to convert your Alembic file to something else.
Most of the file formats are not able to store all the information we need: cameras, visibilities, etc.
For instance, PLY is only able to deal with point clouds without extra-attributes.

**Comment by natowi** [comment]
miquelrosell99
> Meshing node only outputs .abc file, and I can't manage to use ConverSfM node there. It only exports the camera dots inside the .ply. No actual object points
> Your suggestion was very useful for SfM node.

**Comment by miquelrosell99** [comment]
Yep, problem is it only converts camera locations
Processing meshing node rn, but its been stuck here for about 2h, with 100% ram usage
![image](https://user-images.githubusercontent.com/38435442/68548092-7dbca600-03e9-11ea-90e1-a5179c283f66.png)

**Comment by miquelrosell99** [comment]
@natowi gonna push the commit if you want to use it ;)

**Comment by miquelrosell99** [comment]
@natowi @fabiencastan Hi, how can I add these changes to official meshroom repo? Now I have them on my own fork.
I fixed what was discussed here and it works great

> I have changed the code since (check the PRfor details).
> 
> At the moment there is the problem left, that
> 
> ```
> 
> class Meshing(desc.CommandLineNode):
>     commandLine = 'aliceVision_meshing {allParams}'
> ```
> 
> calls all Params name=(...) but my file type selector is not a valid param
> 
> ```
> desc.ChoiceParam(
>             name='outputDensePointCloud',
> ...
> ```
> 
> I think this can be fixed using all supported params, leaving out outputDensePointCloud:
> 
> ```
> class Meshing(desc.CommandLineNode):
>     commandLine = 'aliceVision_meshing --input {inputValue} ...
> ```
> 
> I did not test this yet.

**Comment by natowi** [comment]
@miquelrosell99 Good that the work around works for you. I closed the issue, since ConvertSfM should work, and [modifying all the parameters](https://github.com/alicevision/meshroom/pull/691#issuecomment-552206490) is only a work around and ply is not supported by the Texturing node and 3D viewer.

So for the official repo we need to[ fix the ConvertSfM](https://github.com/alicevision/meshroom/pull/691#issuecomment-552208314) node.

**Comment by miquelrosell99** [comment]
Nice! Gonna download latest files then

**Comment by natowi** [comment]
@miquelrosell99 unknown Describer Type should allready be available in your downloaded dev version of MR

**Comment by miquelrosell99** [comment]
> @miquelrosell99 Good that the workaround works for you. I closed the issue, since ConvertSfM should work, and [modifying all the parameters](https://github.com/alicevision/meshroom/pull/691#issuecomment-552206490) is only a workaround and ply is not supported by the Texturing node and 3D viewer.
> 
> We can use ConvertSfM but need to disable SIFT and enable unknown Describer Types
> *Note: not available in the binaries, option [recently added](https://github.com/alicevision/meshroom/commit/f859f8759dfffaf39f760374aef09734042ff9ae)

Any place I can get info on describer types?

**Comment by miquelrosell99** [comment]
> @miquelrosell99 unknown Describer Type should allready be available in your downloaded dev version of MR

Yes it is. But I'll download latest official one, since the only change I added was to get ply files, and i can do that with official. Better for future updates

**Comment by natowi** [comment]
Any place I can get info on describer types?

They are feature detection algorithms. SIFT for example: https://en.wikipedia.org/wiki/Scale-invariant_feature_transform

**Comment by natowi** [comment]
Resolved. Will be available in the upcoming release. Added to the documentation.
