### ISSUE TITLE
NVIDIA GPU Error on Ubuntu 18 LTS

### ISSUE THREAD

**Issue by JPGlaser** [alicevision/meshroom#693]
Hey All,
So I am trying my hand at trying out using Meshroom. I must say, already it is an impressive piece of software. However, I can't seem to get it fully running on the latest kernel of the Ubuntu 18 LTS (Dell Inspiron 7500 laptop). I received the following error:

```
[18:20:35.181521][warning] Could not determine number of CUDA cards in this system
[18:20:35.147742][warning] No CUDA-Enabled GPU.
[18:20:35.181724][error] cudaGetDeviceCount failed: no CUDA-capable device is detected
[18:20:35.181733][info] Can't find CUDA-Enabled GPU.
[18:20:35.181739][error] This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0).
```

However, I do have a CUDA-Enabled GPU (with the latest drivers and cuda-dev libraries installed).

```
sudo lshw -C display
  *-display                 
       description: VGA compatible controller
       product: GP107M [GeForce GTX 1050 Ti Mobile]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:129 memory:de000000-deffffff memory:c0000000-cfffffff memory:d0000000-d1ffffff ioport:e000(size=128) memory:df000000-df07ffff
  *-display
       description: VGA compatible controller
       product: Intel Corporation
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 04
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:126 memory:dd000000-ddffffff memory:b0000000-bfffffff ioport:f000(size=64) memory:c0000-dffff
```
Any suggestions on what might be the issue here?

~ Joe G.

**Comment by natowi** [comment]
Your computer might use the Intel GPU to save power. You need to set the NVIDIA GPU as primary gpu.
https://www.linuxbabe.com/desktop-linux/switch-intel-nvidia-graphics-card-ubuntu

**Comment by JPGlaser** [comment]
Hey @natowi , 
Thanks for the reply on this. I have actually gone through this and other tutorials on getting my NVIDIA GPU set as my primary to no avail. nvidia-settings will not open after the new drivers have been installed. I suspect it has to do with my secure-boot machine, but even after going through the steps to ensure the key was signed for the driver via the BIOS, Ubuntu is still using Intel.

I don't actually mind it using the Intel display as the primary, but shouldn't I be able to target my Nvidia card seperately as a "second" CUDA device? That is how things are normally done on the cluster computers I primarily work with.

~ Joe G.

**Comment by natowi** [comment]
> but shouldn't I be able to target my Nvidia card seperately as a "second" CUDA device?

This should be possible in the NVIDIA Control panel (Nvidia X Server Settings).

Did you try `sudo prime-select nvidia` ?

**Comment by JPGlaser** [comment]
```
Info: the nvidia profile is already set
```
Yeah, that's what I usually get when I try to use the PRIME option. It's too bad Bumblebee is no longer supported, because that use to be the easy solution for those who wanted to use hybrid systems.

~ Joe G.
