### ISSUE TITLE
added sensor data not recognized raspberry pi 8mp

### ISSUE THREAD

**Issue by hargrovecompany** [alicevision/meshroom#695]
![dbsnip](https://user-images.githubusercontent.com/45779552/68352412-f2cb6b00-00cb-11ea-8797-d4e4b759c548.PNG)
I added this to my camera database, but still get a yellow circle in the top left corner of imported images, with a message saying that the focal length and sensor width could not be determined from metadata....however, the message displays a focal length but not a 35mm focal length.  It also says sensor width is undefined.

**Comment by natowi** [comment]
Can you share an sample image for testing?

**Comment by hargrovecompany** [comment]
![138](https://user-images.githubusercontent.com/45779552/68426070-f662fe80-016c-11ea-92da-fc832a07e113.jpg)
Here is an image for testing....I'm running 2019.1.0-win64

**Comment by hargrovecompany** [comment]
I don't know if it's a problem with spacing between the descriptions in the metadata, but I noticed no spaces between some of the words

**Comment by natowi** [comment]
With `RaspberryPi;RP_imx219;3.674;` I get a green icon.

**Comment by natowi** [comment]
This issue is closed due to inactivity. Feel free to re-open if new information is available.
