### ISSUE TITLE
why AliceVision's depthmap estimator is crashed on my images?

### ISSUE THREAD

**Issue by byj200493** [alicevision/meshroom#696]
I am trying to obtain textured mesh from images captured by phone cells.
image size is 3024x4032. number of images is 53. images are jpg files.
I am using meshroom.
the steps from camera init to prepare dense scene are finished.
but depthmap estimator is crashed.
why is it crashed?
I wish anyone to help me.
thanks in advance.

**Comment by natowi** [comment]
See: https://github.com/alicevision/meshroom/wiki/DepthMap-slow-or-red-bar
https://github.com/alicevision/meshroom/wiki/Draft-Meshing
https://github.com/alicevision/meshroom/wiki/Error:-This-program-needs-a-CUDA-Enabled-GPU

**Comment by natowi** [comment]
This issue is closed due to inactivity. Feel free to re-open if new information is available.
