### ISSUE TITLE
Problem with recognition metadata of Canon RP[question]

### ISSUE THREAD

**Issue by TeslAndroid** [alicevision/meshroom#699]
I'm trying to pass CameraInit step, but have a trouble with recognition metadata.
I added this line to cameraSensors.db:
`
Canon;Canon EOS RP;35.9;dpreview,digicamdb,imaging-resource
`
but still get an error message. 
Here is an example of photo made by using RP:
![IMG_7086](https://user-images.githubusercontent.com/57593117/68545388-c79f8f00-03dd-11ea-9f62-a95a23ecb011.JPG)

**Comment by natowi** [comment]
Can you share the error message?

**Comment by TeslAndroid** [comment]
![fd1803261012f8c516a6c49c926d1bc6 1](https://user-images.githubusercontent.com/57593117/68545764-0f73e580-03e1-11ea-8f04-9da297472748.png)

**Comment by TeslAndroid** [comment]
We made photos with RP and Xiaomi Mi 5S (in one session) for comparing the results.
There is no problem with Xiaomi Mi 5s though.

**Comment by natowi** [comment]
Using `Canon;Canon EOS RP;35.9;dpreview,digicamdb,imaging-resource` works for me.
Restart Meshroom or update the db ![cdb](https://user-images.githubusercontent.com/8138537/68544721-88197880-03c6-11ea-8c3a-baaa957a690f.jpg)

**Comment by TeslAndroid** [comment]
Updating Intrinsics helped!
Many thanks! I thought that changing the file is enough.

**Comment by fabiencastan** [comment]
Can someone make a PR to add the camera model?
