### ISSUE TITLE
[question] DepthMap crash

### ISSUE THREAD

**Issue by xjoscx** [alicevision/meshroom#700]
My DepthMap alway crash, and i do not know why. 
Already installed a new driver for my geforce because the log showed issues with the geforce.
But it is still crashing.
Tested it with this : https://www.agisoft.com/downloads/sample-data/ today.

**Log**
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "D:/meshroom/doll/MeshroomCache/PrepareDenseScene/5bd236a02a56bdc27d3628421355da946d4bcba6"
 * input = "D:/meshroom/doll/MeshroomCache/StructureFromMotion/62165d02a29490bd5f6a1998f4be2fbc790d535d/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "D:/meshroom/doll/MeshroomCache/DepthMap/dfd2ed9f8b1565e8de7db5fc85937ee72e3e7f2e"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[09:09:48.536873][info] CUDA-Enabled GPU.
Device information:
	- id:                      0
	- name:                    GeForce 940M
	- compute capability:      5.0
	- total device memory:     2048 MB 
	- device memory available: 1945 MB 
	- per-block shared memory: 49152
	- warp size:               32
	- max threads per block:   1024
	- max threads per SM(X):   2048
	- max block sizes:         {1024,1024,64}
	- max grid sizes:          {2147483647,65535,65535}
	- max 2D array texture:    {65536,65536}
	- max 3D array texture:    {4096,4096,4096}
	- max 2D linear texture:   {65536,65536,1048544}
	- max 2D layered texture:  {16384,16384,2048}
	- number of SM(x)s:        3
	- registers per SM(x):     65536
	- registers per block:     65536
	- concurrent kernels:      yes
	- mapping host memory:     yes
	- unified addressing:      yes
	- texture alignment:       512 byte
	- pitch alignment:         32 byte

[09:09:49.337280][info] Supported CUDA-Enabled GPU detected.
[09:09:49.384141][info] Found 1 image dimension(s): 
[09:09:49.384141][info] 	- [4416x3312]
[09:09:51.945219][info] Overall maximum dimension: [4416x3312]
[09:09:51.946221][info] Create depth maps.
number of CUDA devices:	1
   0: GeForce 940M
[09:09:51.946221][info] # GPU devices: 1, # CPU threads: 4
[09:09:51.947222][info] Plane sweeping parameters:
	- scale: 2
	- step: 4
[09:09:51.947222][info] PlaneSweepingCuda:
	- _nImgsInGPUAtTime: 2
	- scales: 2
	- subPixel: Yes
	- varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 102.644531, free: 1945.355469, total: 2048.000000
Device 0 memory - used: 243.144531, free: 1804.855469, total: 2048.000000
[09:10:21.557578][info] Estimate depth map, view id: 9273165

 - OS: win 8.1
 - Meshroom version: 2019.2.0

**Comment by natowi** [comment]
Your computer has 4GB ram? You need to reduce the quality of your reconstruction.
https://github.com/alicevision/meshroom/wiki/DepthMap-slow-or-red-bar

**Comment by xjoscx** [comment]
Thank you for your answer.

**Comment by xjoscx** [comment]
I just checked and technically my computer has 8GB ram.

**Comment by natowi** [comment]
Depending on your images this might not be enough. Image datasets with ~80 images can consume up to 20GB Ram with the default values. So you need to use the downscale parameter as described in the wiki. Also https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters

**Comment by xjoscx** [comment]
So the downscale of DepthMap did not work for me.
Would it work if I use less images?

**Comment by xjoscx** [comment]
I found the Problem, install a different driver for my geforce and now it is working again.
