### ISSUE TITLE
[question] Problem on Masked Images

### ISSUE THREAD

**Issue by aarahvar** [alicevision/meshroom#702]
Hi
I use the masked images for 3D reconstruction. The output of SFM Looks great without any spare point. However, The output of the meshing process generates a white environment around the masked object.
Any help is appreciated.

**Screenshots**
A sample of the masked image:
![Masked](https://user-images.githubusercontent.com/46425755/68729703-ec376a80-0587-11ea-8f87-5653aa1416fb.PNG)

The output of SFM:
![image](https://user-images.githubusercontent.com/46425755/68729771-1be67280-0588-11ea-8a26-f254fac2615f.png)

Final output:
![image](https://user-images.githubusercontent.com/46425755/68729813-37ea1400-0588-11ea-969c-0cd67404f174.png)

**Comment by natowi** [comment]
Similar: https://github.com/alicevision/meshroom/issues/566

https://github.com/alicevision/meshroom/issues/188

**Comment by MightyBOBcnc** [comment]
Shouldn't the masking color should be black for Meshroom to ignore the masked pixels?

**Comment by natowi** [comment]
Yes, the experimental DepthMask filter requires black masks (but they can easily be generated from white bg). With the next release there will be a more advanced support to mask images.
