### ISSUE TITLE
meshroom2018.1.0 stuck on structurefrommotion

### ISSUE THREAD

**Issue by BOTMarvin** [alicevision/meshroom#703]
its my first time using this software and didnt find a solution from other sites or this one , i have latest CUDA cuda_10.1.243_426.00_win10.exe and thats all i think

Log from the strcuturefrommotion
 * describerTypes = "sift"
 * extraInfoFolder = "C:/Users/HP/Desktop/MeshroomCache/StructureFromMotion/ae2efe310270628dea9764bdbbc477d89ba73d4c"
 * featuresFolders =  = [C:/Users/HP/Desktop/MeshroomCache/FeatureExtraction/b6c4b2cf5c82af10037b450a8b8f019800944b63]
 * initialPairA = ""
 * initialPairB = ""
 * input = "C:/Users/HP/Desktop/MeshroomCache/CameraInit/584959e840d161e465e0ffa0f7202a0144a1a815/cameraInit.sfm"
 * interFileExtension = ".abc"
 * localBAGraphDistance = 1
 * localizerEstimator = "acransac"
 * lockScenePreviouslyReconstructed = 0
 * matchesFolders =  = [C:/Users/HP/Desktop/MeshroomCache/FeatureMatching/88cd174802b42811920f192b2cd11c104cef492f]
 * maxAngleInitialPair = 40
 * maxNumberOfMatches = 0
 * maxReprojectionError = 4
 * minAngleForLandmark = 2
 * minAngleForTriangulation = 3
 * minAngleInitialPair = 5
 * minInputTrackLength = 2
 * minNumberOfObservationsForTriangulation = 2
 * output = "C:/Users/HP/Desktop/MeshroomCache/StructureFromMotion/ae2efe310270628dea9764bdbbc477d89ba73d4c/sfm.abc"
 * outputViewsAndPoses = "C:/Users/HP/Desktop/MeshroomCache/StructureFromMotion/ae2efe310270628dea9764bdbbc477d89ba73d4c/cameras.sfm"
 * refineIntrinsics = 1 (default)
 * useLocalBA = 1
 * useOnlyMatchesFromInputFolder = 0
 * useTrackFiltering = 1 (default)
 * verboseLevel = "info"

Loading features
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
[20:13:42.213151][info] Fuse matches into tracks: 
	- # tracks: 468
	- # images in tracks: 6
[20:13:42.214151][info] TrackLength, Occurrence
[20:13:42.215149][info] 	2	440
[20:13:42.215149][info] 	3	26
[20:13:42.215149][info] 	4	2
Automatic selection of an initial pair:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*************************[20:1************3*************:42.215149][info] AutomaticInitialPairChoice, test I: 9662540, J: 915667969, nbCommonTracks: 74*

[20:13:42.216149][info] AutomaticInitialPairChoice, test I: 343439339, J: 479875803, nbCommonTracks: 68
[20:13:42.216149][info] AutomaticInitialPairChoice, test I: 78064443, J: 1594406558, nbCommonTracks: 292
[20:13:42.216149][info] AutomaticInitialPairChoice, test I: 915667969, J: 1594406558, nbCommonTracks: 64
[20:13:42.252128][error] No valid initial pair found automatically.

if its blank i dont know what is asked
 - OS: [win 10,]
 - Python version [36] came with the file
 - Qt/PySide version []
 - Meshroom version: 2018.1.0 
   - Binary version (if applicable) []
   - Commit reference (if applicable) []

**Comment by natowi** [comment]
This is likely a problem of your dataset. When capturing for photogrammetry you need to follow a few principles. Can you share a screenshot of your image set?

**Comment by BOTMarvin** [comment]
Do you mean all my images on the side or in a folder

**Comment by natowi** [comment]
The images on the side in Meshroom would do. This is only to get an overview of your dataset and to spot possible problems.

**Comment by BOTMarvin** [comment]
well does this help (i changed to the newest release to see if it would work and the pictures are of my head)
![pää,,](https://user-images.githubusercontent.com/57769729/68970858-edb79b80-07f0-11ea-85b8-294ce828e015.png)

**Comment by natowi** [comment]
OK, you could add the [sensor information](https://github.com/alicevision/meshroom/wiki/Add-Camera-to-database) of your iPhone to the sensordatabase to get better results. Since your iPhone has three cameras, you need to add the camera that is being used, that is likely the Primary: 12Mp camera with 1/2.55″ sensor, so the entry is likely _Apple;iPhone 11 Pro;5.75;_

Now to your SfM problem: make sure you do not have any special characters in your path, this can be a cause for errors. Next use improve the accuracy as described here: https://github.com/alicevision/meshroom/wiki/StructureFromMotion-fails

If this still does not work we need to address how you capture the images:
To capture your head, best ask someone to take images for you to reduce your head movements to a minimum. If this is not possible, lean your head on a wall and then take pictures of your head in half circles and from different angles. Look straight ahead and do not move while capturing.

**Comment by BOTMarvin** [comment]
i added the Apple;iPhone 11 Pro;5.75; in to the data base and updated it in the software but it didnt fix the yellow, im currently trying the second one and tomorrow im gonna get new pics if it doesnt work

**Comment by natowi** [comment]
Do you get a decent point cloud in the 3D viewer?
I can only assume that you moved your head while capturing.

**Comment by BOTMarvin** [comment]
well 
![Desktop Screenshot 2019 11 16 - 00 38 10 44 (2)gbgbg](https://user-images.githubusercontent.com/57769729/68980562-7b9f8080-0809-11ea-9152-87c5318cf1a9.png)

**Comment by BOTMarvin** [comment]
so i guess to just take new pictures

**Comment by BOTMarvin** [comment]
i took new pictures and now it fully completes but the program doesnt recognize angles from sides or back of my head so only my face is recognized. should i try other programs because this one aint cutting it

**Comment by natowi** [comment]
This is not a software problem. Ask a friend to take pictures for you. Images should have a 60% overlap.

https://adamspring.co.uk/single-post/2017/08/30/Single-Camera-Head-Scanning-Photogrammetry
https://studio.knightlab.com/results/photojournalism3D/the-4-key-components-to-photogrammetry-capture/
More general:
https://www.youtube.com/watch?v=D7Torjkfec4

**Comment by BOTMarvin** [comment]
i'll try that

**Comment by BOTMarvin** [comment]
so now im currently trying to convert it but i might just might be stuck or my computer is slow but anyways it hasnt moved for about 25mins and says (if i understand) that its complete btw i know i have alot of pictures and has been taking me from the time of posting 7.45h to get here.
![Desktop Screenshot 2019 11 17 - 01 43 13 18](https://user-images.githubusercontent.com/57769729/69000651-a4904600-08db-11ea-8aeb-aac61a0514f5.png)

**Comment by natowi** [comment]
Your object should fill most or all of your images to avoid reconstruction  of the environment and not your object (and also to save computation time).

**Comment by BOTMarvin** [comment]
i finished it, it turned out my computer was just slow but why is the model like this? i tried with a difrent thing and it was similar is it because of my phone camera or?
![Desktop Screenshot 2019 11 17 - 15 11 30 44](https://user-images.githubusercontent.com/57769729/69007903-c544b400-094c-11ea-836b-cc60828aa15a.png)

**Comment by natowi** [comment]
You were not close enough to the object and your object is single coloured with low details.
There are some basics you should know before capturing objects for photogrammetry. Please read the guides I posted before and search for more if necessary.

**Comment by curtthemartian** [comment]
You can smooth it in the mesh filtering node, but it will never bee as smooth as you want it to be.  It is really tricky with objects that are smooth and have uniform color or very smooth texture.

**Comment by natowi** [comment]
This issue is closed due to inactivity. Feel free to re-open if new information is available.
