### ISSUE TITLE
Help my. Persistent error at DepthMap stage

### ISSUE THREAD

**Issue by mamymar** [alicevision/meshroom#704]
Sorry about the English. I use an interpreter. No matter what project I do, there is always an error at the DepthMap stage. Below is the log from CMD.exe. I hope for Your help

==============
[7/11](1/42) DepthMap
 - commandLine: aliceVision_depthMapEstimation  --input "C:/3DSCAN/Mari/MeshroomCache/StructureFromMotion/e62243d8953a0c1f3853bdb89469aab764ee03e3/sfm.abc" --imagesFolder "C:/3DSCAN/Mari/MeshroomCache/PrepareDenseScene/ef2e949f65dc7fe8af20a13903d9b2cdee447e98" --downscale 1 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output "C:/3DSCAN/Mari/MeshroomCache/DepthMap/6444fac5aea03f786e312cfa0956ff987b8257dd" --rangeStart 0 --rangeSize 3
 - logFile: C:/3DSCAN/Mari/MeshroomCache/DepthMap/6444fac5aea03f786e312cfa0956ff987b8257dd/0.log
 - elapsed time: 0:00:15.064430
ERROR:root:Error on node computation: Error on node "DepthMap_1(0)":
Log:
Program called with the following parameters:
 * downscale = 1
 * exportIntermediateResults = 0
 * imagesFolder = "C:/3DSCAN/Mari/MeshroomCache/PrepareDenseScene/ef2e949f65dc7fe8af20a13903d9b2cdee447e98"
 * input = "C:/3DSCAN/Mari/MeshroomCache/StructureFromMotion/e62243d8953a0c1f3853bdb89469aab764ee03e3/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/3DSCAN/Mari/MeshroomCache/DepthMap/6444fac5aea03f786e312cfa0956ff987b8257dd"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[01:42:55.161525][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce 930MX
        - compute capability:      5.0
        - total device memory:     2048 MB
        - device memory available: 1695 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   2048
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {65536,65536}
        - max 3D array texture:    {4096,4096,4096}
        - max 2D linear texture:   {65536,65536,1048544}
        - max 2D layered texture:  {16384,16384,2048}
        - number of SM(x)s:        3
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte

[01:42:55.883452][info] Supported CUDA-Enabled GPU detected.
[01:42:56.166694][info] Found 1 image dimension(s):
[01:42:56.166694][info]         - [4000x3000]
[01:42:56.353194][info] Overall maximum dimension: [4000x3000]
[01:42:56.353194][info] Create depth maps.
number of CUDA devices: 1
   0: GeForce 930MX
[01:42:56.361895][info] # GPU devices: 1, # CPU threads: 4
[01:42:56.362891][info] Plane sweeping parameters:
        - scale: 2
        - step: 3
[01:42:56.362891][info] PlaneSweepingCuda:
        - _nImgsInGPUAtTime: 2
        - scales: 2
        - subPixel: Yes
        - varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 352.631256, free: 1695.368774, total: 2048.000000
Device 0 memory - used: 469.881256, free: 1578.118774, total: 2048.000000
[01:43:00.095602][info] Estimate depth map, view id: 4358495

WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(11)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(12)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(13)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(14)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(15)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(16)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(17)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(18)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(19)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(20)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(21)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(22)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(23)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(24)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(25)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(26)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(27)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(28)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(29)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(30)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(31)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(32)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(33)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(34)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(35)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(36)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(37)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(38)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(39)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(40)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(41)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(11)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(12)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "DepthMap_1(0)":
Log:
Program called with the following parameters:
 * downscale = 1
 * exportIntermediateResults = 0
 * imagesFolder = "C:/3DSCAN/Mari/MeshroomCache/PrepareDenseScene/ef2e949f65dc7fe8af20a13903d9b2cdee447e98"
 * input = "C:/3DSCAN/Mari/MeshroomCache/StructureFromMotion/e62243d8953a0c1f3853bdb89469aab764ee03e3/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/3DSCAN/Mari/MeshroomCache/DepthMap/6444fac5aea03f786e312cfa0956ff987b8257dd"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[01:42:55.161525][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce 930MX
        - compute capability:      5.0
        - total device memory:     2048 MB
        - device memory available: 1695 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   2048
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {65536,65536}
        - max 3D array texture:    {4096,4096,4096}
        - max 2D linear texture:   {65536,65536,1048544}
        - max 2D layered texture:  {16384,16384,2048}
        - number of SM(x)s:        3
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte

[01:42:55.883452][info] Supported CUDA-Enabled GPU detected.
[01:42:56.166694][info] Found 1 image dimension(s):
[01:42:56.166694][info]         - [4000x3000]
[01:42:56.353194][info] Overall maximum dimension: [4000x3000]
[01:42:56.353194][info] Create depth maps.
number of CUDA devices: 1
   0: GeForce 930MX
[01:42:56.361895][info] # GPU devices: 1, # CPU threads: 4
[01:42:56.362891][info] Plane sweeping parameters:
        - scale: 2
        - step: 3
[01:42:56.362891][info] PlaneSweepingCuda:
        - _nImgsInGPUAtTime: 2
        - scales: 2
        - subPixel: Yes
        - varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 352.631256, free: 1695.368774, total: 2048.000000
Device 0 memory - used: 469.881256, free: 1578.118774, total: 2048.000000
[01:43:00.095602][info] Estimate depth map, view id: 4358495

**Comment by natowi** [comment]
" CUDA device no 0 for 0"
You need to install the most recent drivers for your GeForce 930MX.
Also make sure the NVIDIA GPU is set as primary GPU. On some laptop the intel GPU is set to default to save energy.

**Comment by mamymar** [comment]
**natowi,** 
thank you! really worked through Intel. Also, the problem was solved by setting the parameter Downscale-4.
