### ISSUE TITLE
app doesnt open

### ISSUE THREAD

**Issue by ovmo** [alicevision/meshroom#709]
<img width="452" alt="Screen Shot 2019-11-21 at 12 24 08" src="https://user-images.githubusercontent.com/43478862/69333918-edd4f280-0c59-11ea-8e84-34f866da4f73.png">
after several reinstalls on my mac running parallels windows vm it still has the difficulty finding the file VCRUNTIME140.dll and it just shows a black screen when trying to proceed

thanks

**Comment by ChemicalXandco** [comment]
You could try installing visual studio c++ redistributable from microsoft, if the os is 64 bit this is the correct file: [VC_redist.x64.exe](https://aka.ms/vs/16/release/vc_redist.x64.exe). If this fails, you could find the dll file and put it under C:/Windows/System32, but I do not recommend doing this.

**Comment by natowi** [comment]
This issue is closed due to inactivity. Feel free to re-open if new information is available.
