### ISSUE TITLE
[question]3D viewer does not load mesh

### ISSUE THREAD

**Issue by tub-sgg** [alicevision/meshroom#717]
**Describe the problem**
A clear and concise description of what the problem is.

**Screenshots**
<img width="1272" alt="屏幕快照 2019-12-02 下午9 15 14" src="https://user-images.githubusercontent.com/44619635/69991943-eca0a100-1548-11ea-8fa4-ed40f950a9d8.png">

**Dataset**
If applicable, add a link or *few* images to help better understand where the problem may come from.

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS:  MacOS High Sierra
 - Python version: 3.7.4
 - Qt/PySide version: 5.12
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version: 2019.2

**Additional context**
https://github.com/ryanfb/homebrew-alicevision/issues/8

**Comment by tub-sgg** [comment]
Everthing seems fine but in 3d viewer there is not result at all. How can I solver the problem? @ryanfb

**Comment by natowi** [comment]
Maybe https://github.com/alicevision/qmlAlembic is not installed correctly. Does the feature viewer (three dots icon in the image viewer bottom left) work?

**Comment by tub-sgg** [comment]
but I use homebrew to install the dependencies of Alicevision @natowi

**Comment by natowi** [comment]
Yes, but what is the output of your error log?

**Comment by tub-sgg** [comment]
no error found but there is nothing in the 3D viewer @natowi

**Comment by natowi** [comment]
Drag and drop the obj file from the texturing folder to the 3d viewer. There should be an error log entry in the cli running in the background if this does not work

**Comment by tub-sgg** [comment]
can not  drag the .obj file to the 3D viewer but still no error found @natowi

**Comment by tub-sgg** [comment]
because my OS is MacOS ,I use homebrew(the command : brew install ryanfb/alicevision/alicevision ) to install all dependencies for meshroom.  Does it mean I have already installed all dependencies and plugins??? @natowi @ryanfb   Do I still need to install the two plugins above again?

**Comment by natowi** [comment]
You launch Meshroom using the cli and a command like this: `ALICEVISION_SENSOR_DB=/usr/local/Cellar/alicevision/2.1.0/share/aliceVision/cameraSensors.db ALICEVISION_VOCTREE=/usr/local/Cellar/alicevision/2.1.0/share/aliceVision/vlfeat_K80L3.SIFT.tree PYTHONPATH=$PWD python meshroom/ui`

The same window will show all processed nodes and also error messages.

Maybe you used different folders for your installation.

**Comment by tub-sgg** [comment]
(base) client-141-23-173-54:meshroom Alex$ brew list  ryanfb/alicevision/alembic 
/usr/local/Cellar/alembic/1.7.12/bin/abcconvert
/usr/local/Cellar/alembic/1.7.12/bin/abcdiff
/usr/local/Cellar/alembic/1.7.12/bin/abcecho
/usr/local/Cellar/alembic/1.7.12/bin/abcechobounds
/usr/local/Cellar/alembic/1.7.12/bin/abcls
/usr/local/Cellar/alembic/1.7.12/bin/abcstitcher
/usr/local/Cellar/alembic/1.7.12/bin/abctree
/usr/local/Cellar/alembic/1.7.12/include/Alembic/ (123 files)
/usr/local/Cellar/alembic/1.7.12/lib/libAlembic.1.7.12.dylib
/usr/local/Cellar/alembic/1.7.12/lib/cmake/ (4 files)
/usr/local/Cellar/alembic/1.7.12/lib/ (2 other files)
/usr/local/Cellar/alembic/1.7.12/share/alembic/cube.abc


where is the error log?  @natowi

**Comment by tub-sgg** [comment]
Program called with the following parameters:
 * angleHardThreshold = 90
 * bestScoreThreshold = 0.1
 * correctEV = 0
 * downscale =  Unknown Type "j"
 * fillHoles = 0
 * flipNormals = 0
 * forceVisibleByAllVertices = 0
 * imagesFolder = "/Users/Alex/Downloads/dataset_monstree-master/mini3/MeshroomCache/PrepareDenseScene/bcb349ed634eb4463470dca1046bbc985d00930a"
 * input = "/Users/Alex/Downloads/dataset_monstree-master/mini3/MeshroomCache/Meshing/488c71967282901b5a62d75846e8988b8dc42fad/densePointCloud.abc"
 * inputMesh = "/Users/Alex/Downloads/dataset_monstree-master/mini3/MeshroomCache/MeshFiltering/e9e10d5c9f1e71eb5bc9c08b5299823c6ad2263a/mesh.obj"
 * multiBandDownscale =  Unknown Type "j"
 * multiBandNbContrib =  Unknown Type "NSt3__16vectorIiNS_9allocatorIiEEEE"
 * output = "/Users/Alex/Downloads/dataset_monstree-master/mini3/MeshroomCache/Texturing/76fa851e66962de5fd89e0883daa5be2c85ebdbb"
 * outputTextureFileType = "png"
 * padding =  Unknown Type "j"
 * processColorspace = "sRGB"
 * textureSide =  Unknown Type "j"
 * unwrapMethod = "Basic"
 * useScore = 1
 * useUDIM = 1
 * verboseLevel = "info"
 * visibilityRemappingMethod = "PullPush"

[22:51:41.375744][info] Found 1 image dimension(s): 
[22:51:41.376219][info] 	- [4032x3024]
[22:51:41.380897][info] Overall maximum dimension: [4032x3024]
[22:51:41.380975][info] Loading mesh from obj file: /Users/Alex/Downloads/dataset_monstree-master/mini3/MeshroomCache/MeshFiltering/e9e10d5c9f1e71eb5bc9c08b5299823c6ad2263a/mesh.obj
[22:51:41.420199][info] 	- # vertices: 61554
	- # normals: 0
	- # uv coordinates: 0
	- # triangles: 122783
[22:51:41.537505][info] Mesh loaded: 
	- #points: 61554
	- # triangles: 122783
[22:51:41.618711][info] remapMeshVisibility based on triangles start.
[22:51:41.876159][info] remapMeshVisibility done.
[22:51:41.886750][info] Input mesh has no UV coordinates, start unwrapping (Basic)
[22:51:41.886849][info] Generating UVs (textureSide: 8192; padding: 5).
[22:51:41.886884][info] Creating texture charts.
[22:51:42.150599][info] Packing texture charts (122783 charts).
[22:51:42.478330][info] Finalize packed charts (124 charts).
[22:51:42.496764][info] Creating texture atlases.
[22:51:42.496842][info] 	- texture atlas 1
[22:51:42.497190][info] Filled with 124 charts.
[22:51:42.678489][info] Unwrapping done.
[22:51:42.678584][info] Writing obj and mtl file.
[22:51:42.847619][info] Writing done: 
	- obj file: /Users/Alex/Downloads/dataset_monstree-master/mini3/MeshroomCache/Texturing/76fa851e66962de5fd89e0883daa5be2c85ebdbb/texturedMesh.obj
	- mtl file: /Users/Alex/Downloads/dataset_monstree-master/mini3/MeshroomCache/Texturing/76fa851e66962de5fd89e0883daa5be2c85ebdbb/texturedMesh.mtl
[22:51:42.847665][info] Generate textures.
[22:51:42.847691][info] Texturing: Use multiband blending with the following contributions per band:
[22:51:42.847720][info]   - 1
[22:51:42.847745][info]   - 5
[22:51:42.847766][info]   - 10
[22:51:42.847787][info] Texturing in sRGB colorspace.
[22:51:42.847825][info] Images loaded from cache with: no exposure correction
[22:51:42.847902][info] Total amount of free RAM  : 2688 MB.
[22:51:42.847927][info] Total amount of memory available : 1993 MB.
[22:51:42.847949][info] Total amount of an image in memory  : 139 MB.
[22:51:42.847971][info] Total amount of an atlas pyramid in memory: 3072 MB.
[22:51:42.847993][info] Processing 1 atlases by chunks of 1
[22:51:42.848023][info] Generating texture for atlases 1 to 1
[22:51:42.848050][info] Generating texture for atlas 1/1 (122783 triangles).
[22:51:43.213724][info] Reading pixel color.
[22:51:45.524787][info] - camera 1046300148 (1/3) with contributions to 1 texture files:
[22:51:46.926390][info]   - Texture file: 1
[22:51:46.926563][info]       - band 1: 26204 triangles.
[22:51:48.165346][info]       - band 2: 95945 triangles.
[22:51:50.649644][info]       - band 3: 0 triangles.
[22:51:50.659388][info] - camera 1154011530 (2/3) with contributions to 1 texture files:
[22:51:51.979915][info]   - Texture file: 1
[22:51:51.980004][info]       - band 1: 30670 triangles.
[22:51:52.934491][info]       - band 2: 91737 triangles.
[22:51:55.654564][info]       - band 3: 0 triangles.
[22:51:55.664311][info] - camera 1632518334 (3/3) with contributions to 1 texture files:
[22:51:56.902417][info]   - Texture file: 1
[22:51:56.902497][info]       - band 1: 65633 triangles.
[22:51:58.893681][info]       - band 2: 56631 triangles.
[22:52:00.676836][info]       - band 3: 0 triangles.
[22:52:00.688920][info] Create texture 1
[22:52:00.689009][info]   - Computing final (average) color.
[22:52:01.538884][info]   - Edge padding (15 pixels).
[22:52:01.904833][info]   - Writing texture file: /Users/Alex/Downloads/dataset_monstree-master/mini3/MeshroomCache/Texturing/76fa851e66962de5fd89e0883daa5be2c85ebdbb/texture_1001.png
[22:52:10.084752][info] Task done in (s): 28.762000


this one is the texturing log but I am not sure whether it is this one  @natowi

**Comment by natowi** [comment]
Close all windows and start again with `ALICEVISION_SENSOR_DB=/usr/local/Cellar/alicevision/2.1.0/share/aliceVision/cameraSensors.db ALICEVISION_VOCTREE=/usr/local/Cellar/alicevision/2.1.0/share/aliceVision/vlfeat_K80L3.SIFT.tree PYTHONPATH=$PWD python meshroom/ui`

This is how an error will look like:
![err](https://user-images.githubusercontent.com/8138537/69999608-57f26f00-1559-11ea-8e7d-9012fa8c476d.JPG)

**Comment by tub-sgg** [comment]
yes  I saw this error :   [WARNING] Qt3DCore::QEntity *Qt3DRender::Render::LoadSceneJob::tryLoadScene(Qt3DRender::Render::Scene *, QSceneLoader::Status &, const QStringList &, const std::function<void (QSceneImporter *)> &) Found no suitable importer plugin for QUrl("file:///Users/Alex/Downloads/dataset_monstree-master/mini3/MeshroomCache/Texturing/76fa851e66962de5fd89e0883daa5be2c85ebdbb/texturedMesh.obj")

**Comment by tub-sgg** [comment]
@natowi

**Comment by tub-sgg** [comment]
So, which one should I install?? alembic I think I have already installed using homebrew @natowi

**Comment by tub-sgg** [comment]
(base) client-141-23-173-54:build Alex$ cmake ..
-- Found installed version of Eigen: /usr/local/share/eigen3/cmake
-- Found required Ceres dependency: Eigen version 3.3.7 in /usr/local/include/eigen3
-- Found required Ceres dependency: glog
-- Found installed version of gflags: /usr/local/lib/cmake/gflags
-- Detected gflags version: 2.2.2
-- Found required Ceres dependency: gflags
-- Found Ceres version: 1.14.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations]
-- Found AliceVision version: 2.2.0
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/Alex/Documents/meshroom/qtalicevision/QtAliceVision/build
(base) client-141-23-173-54:build Alex$ sudo make install
Password:
Scanning dependencies of target qtAliceVisionPlugin_autogen
[ 25%] Automatic MOC for target qtAliceVisionPlugin
[ 25%] Built target qtAliceVisionPlugin_autogen
Scanning dependencies of target qtAliceVisionPlugin
[ 50%] Building CXX object src/CMakeFiles/qtAliceVisionPlugin.dir/qtAliceVisionPlugin_autogen/mocs_compilation.cpp.o
[ 75%] Building CXX object src/CMakeFiles/qtAliceVisionPlugin.dir/FeaturesViewer.cpp.o
[100%] Linking CXX shared library libqtAliceVisionPlugin.dylib
[100%] Built target qtAliceVisionPlugin
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/qml/AliceVision/qmldir
-- Installing: /usr/local/qml/AliceVision/libqtAliceVisionPlugin.0.1.dylib
-- Installing: /usr/local/qml/AliceVision/libqtAliceVisionPlugin.0.dylib
-- Installing: /usr/local/qml/AliceVision/libqtAliceVisionPlugin.dylib


I think I have install qtAliceVision  successfully, but  still does not work yet?? what's wrong @natowi

**Comment by natowi** [comment]
I think there was a change in the 2019.2 release that moved the viewer plugins and this might not yet be updated in the homebrew recipe. I am not a OSX user, so I can not test this.
You might need to add https://github.com/alicevision/qmlAlembic and https://github.com/alicevision/QtAliceVision

(Please top @ mentioning people in every post. This feature should be used with care)

**Comment by tub-sgg** [comment]
I have installed both .what should I do next then? @natowi

**Comment by natowi** [comment]
You need to add them to your PATH when running Meshroom, like we do with the sensor db

**Comment by tub-sgg** [comment]
there is no point cloud data after sfm

**Comment by natowi** [comment]
Yes, it is the missing plugin.
set the path for QML2_IMPORT_PATH

**Comment by tub-sgg** [comment]
QML2_IMPORT_PATH=/usr/local/qml/AliceVision/libqtAliceVisionPlugin.dylib  like this??

**Comment by natowi** [comment]
just the folder

**Comment by tub-sgg** [comment]
@natowi

**Comment by tub-sgg** [comment]
QML2_IMPORT_PATH=/usr/local/qml/AliceVision/ I did it like this  but still does not work

**Comment by natowi** [comment]
QT_PLUGIN_PATH=<meshroom_develop>/qtPlugins
 QML2_IMPORT_PATH=<meshroom_develop>/qtPlugins/qml


The folder structure for qtPlugins is

```
Meshroom
   - qtPlugins
        -  imageformats
               -  QtOIIOPlugin files
         - qml
                - AlembicEntity
                       - alembicEntityQmlPlugin files
                - DepthMapEntity
                       - depthMapEntityQmlPlugin files

**Comment by tub-sgg** [comment]
I install alembic  in this folder:
/usr/local/Cellar/alembic/1.7.12/bin/abcconvert
/usr/local/Cellar/alembic/1.7.12/bin/abcdiff
/usr/local/Cellar/alembic/1.7.12/bin/abcecho
/usr/local/Cellar/alembic/1.7.12/bin/abcechobounds
/usr/local/Cellar/alembic/1.7.12/bin/abcls
/usr/local/Cellar/alembic/1.7.12/bin/abcstitcher
/usr/local/Cellar/alembic/1.7.12/bin/abctree
/usr/local/Cellar/alembic/1.7.12/include/Alembic/ (123 files)
/usr/local/Cellar/alembic/1.7.12/lib/libAlembic.1.7.12.dylib
/usr/local/Cellar/alembic/1.7.12/lib/cmake/ (4 files)
/usr/local/Cellar/alembic/1.7.12/lib/ (2 other files)
/usr/local/Cellar/alembic/1.7.12/share/alembic/cube.abc

so what is the QML2_IMPORT_PATH=?

**Comment by tub-sgg** [comment]
qtAliceVisionPlugin is Install the project...
-- Install configuration: ""
-- Installing: /usr/local/qml/AliceVision/qmldir
-- Installing: /usr/local/qml/AliceVision/libqtAliceVisionPlugin.0.1.dylib
-- Installing: /usr/local/qml/AliceVision/libqtAliceVisionPlugin.0.dylib
-- Installing: /usr/local/qml/AliceVision/libqtAliceVisionPlugin.dylib 
so the path is???  get confuesd now  by this  :(((

**Comment by tub-sgg** [comment]
I tried to install all the pluins . still does work  what can I do then @natowi

**Comment by natowi** [comment]
Continued in #719
