### ISSUE TITLE
SFM Only reconstructs front side of object [question]

### ISSUE THREAD

**Issue by michaelpayne02** [alicevision/meshroom#718]
I'm trying to reconstruct a model from a set of turntable-type images (they were probably rendered). Meshroom only reconstructs the front side of the object and strangely only plots cameras from exactly the front half of images. In the screenshots below, I added red dots to represent where there should be cameras. For my configuraion, I set the feature extraction decsriptors to ultra and added in akaze. The sparse cloud doesn't look very good, but I accept that as a result of a small image dataset and a low amount of detail on the model. Again, the front half looks decent but there isn't anything on the back. **Images 14-24 are not reconstructed.** 

Here's a screenshot of the scene with the features displayed. 
**Red dots indicate where cameras probably should be.**

![Reconstruction](https://user-images.githubusercontent.com/10254938/70017490-deeb1b80-1548-11ea-93b7-632960ccc1d6.png)

Sparse Cloud:
![sparseCloud](https://user-images.githubusercontent.com/10254938/70017518-f1fdeb80-1548-11ea-9142-647f2eb6aea8.png)

Here's a [Google drive](https://drive.google.com/open?id=17DtFsjMygYl_SlorAlu6lIMp1RpRJZeN) link to the images if you can test them out for yourself. 

 - OS: Win 10
 - Python 3.6.6
 - Meshroom version: 2019.2.0

Any help of info on this type of deal would be greatly appreciated. Thanks!

**Comment by natowi** [comment]
As you can see from the Feature Viewer only features at the edges of your model were detected.
You have to many large, featureless (same colour, no texture) surfaces, so you won´t get a good reconstruction from this.
You need to add some features to your model. Apply chalk spray, powder, paint it,.... to support feature detection and improve the reconstruction.

**Comment by michaelpayne02** [comment]
Sadly those are the only photos that I have of it. Is there any change there's another way to reconstruct the rest of the cameras without reshooting?

**Comment by natowi** [comment]
I will give it a try within the next days.

**Comment by michaelpayne02** [comment]
Okay thanks. I think I might just end up hand-modeling it in blender or some other sort of program from the reference images. I don't know if that will be easier or just a bigger pain but we'll see.

**Comment by natowi** [comment]
Maybe you can use this as reference:
[obj2.zip](https://github.com/alicevision/meshroom/files/3923117/obj2.zip)
[obj.zip](https://github.com/alicevision/meshroom/files/3923120/obj.zip)
