### ISSUE TITLE
QtPlugin Path setting[question]

### ISSUE THREAD

**Issue by tub-sgg** [alicevision/meshroom#719]
**Describe the problem**
A clear and concise description of what the problem is.

always get the problem:
 Qt3DCore::QEntity *Qt3DRender::Render::LoadSceneJob::tryLoadScene(Qt3DRender::Render::Scene *, QSceneLoader::Status &, const QStringList &, const std::function<void (QSceneImporter *)> &) Found no suitable importer plugin for QUrl("file:///Users/Alex/Downloads/dataset_monstree-master/mini3/MeshroomCache/Texturing/76fa851e66962de5fd89e0883daa5be2c85ebdbb/texturedMesh.obj")

### I have install the qtplugins, but how to set the path:
I installed QmlAlembic in this folder:
Up-to-date: /usr/local/qml/AlembicEntity/qmldir
-- Installing: /usr/local/qml/AlembicEntity/libalembicEntityQmlPlugin.0.1.dylib
-- Up-to-date: /usr/local/qml/AlembicEntity/libalembicEntityQmlPlugin.0.dylib
-- Up-to-date: /usr/local/qml/AlembicEntity/libalembicEntityQmlPlugin.dylib
I have install the qtAliceVisionPlugin,
-- Installing: /usr/local/qml/AliceVision/qmldir
-- Installing: /usr/local/qml/AliceVision/libqtAliceVisionPlugin.0.1.dylib
-- Installing: /usr/local/qml/AliceVision/libqtAliceVisionPlugin.0.dylib
-- Installing: /usr/local/qml/AliceVision/libqtAliceVisionPlugin.dylib

I have install the QtOIIO, but how to set the path:
Installing: /libQtOIIOPlugin.dylib
-- Installing: /usr/local/qml/DepthMapEntity/qmldir
-- Installing: /usr/local/qml/DepthMapEntity/libdepthMapEntityQmlPlugin.dylib

**Screenshots**

**Dataset**
If applicable, add a link or *few* images to help better understand where the problem may come from.

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ]MacOS 
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]5.13.2
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1]
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**
https://github.com/alicevision/meshroom/issues/717

**Comment by tub-sgg** [comment]
@fabiencastan @ryanfb @pramukta @nrondaud

**Comment by simogasp** [comment]
did u set the `QML2_IMPORT_PATH`?
see here https://meshroom-manual.readthedocs.io/en/latest/install/linux/linux.html#set-up-environment
in your case it should be:
```bash
export QML2_IMPORT_PATH=/usr/local/qml/
```

**Comment by tub-sgg** [comment]
Qt Plugins
Additional Qt plugins can be built to extend Meshroom UI features. They can be found on separate repositories, though they might get better integration in the future. Note that they are optional but highly recommended.

QmlAlembic
Adds support for Alembic file loading in Meshroom's 3D viewport. Allows to visualize sparse reconstruction results (point cloud and cameras).

QML2_IMPORT_PATH=/path/to/qmlAlembic/install/qml
QtOIIO
Use OpenImageIO as backend to load images in Qt. Allow to visualize RAW/EXR images in Meshroom. This plugin also provides a QML Qt3D Entity to load depthmaps files stored in EXR format.

QT_PLUGIN_PATH=/path/to/QtOIIO/install
QML2_IMPORT_PATH=/path/to/QtOIIO/install/qml
QtAliceVision
Use AliceVision to load and visualize intermediate reconstruction files.

QML2_IMPORT_PATH=/path/to/qtAliceVision/install/qml


so mine should be like this:
export QML2_IMPORT_PATH=/usr/local/qml
export QT_PLUGIN_PATH=/usr/local/?but it does not work yet @simogasp

**Comment by simogasp** [comment]
can you post the way you launch meshroom (command line I suppose?)

**Comment by tub-sgg** [comment]
PYTHONPATH=$PWD python meshroom/ui .  this way @simogasp

**Comment by tub-sgg** [comment]
the meshroom software is  in the folder: /Users/Alex/Documents/meshroom/meshroom  so under this folder, I use PYTHONPATH=$PWD python meshroom/ui . this command to launch meshroom @simogasp

**Comment by simogasp** [comment]
what if you try
```bash
QML2_IMPORT_PATH=/usr/local/qml PYTHONPATH=$PWD python meshroom/ui
```

**Comment by tub-sgg** [comment]
Qt3DCore::QEntity *Qt3DRender::Render::LoadSceneJob::tryLoadScene(Qt3DRender::Render::Scene *, QSceneLoader::Status &, const QStringList &, const std::function<void (QSceneImporter *)> &) Found no suitable importer plugin for QUrl("file:///Users/Alex/Downloads/dataset_monstree-master/mini3/MeshroomCache/Texturing/76fa851e66962de5fd89e0883daa5be2c85ebdbb/texturedMesh.obj")
same error @simogasp

**Comment by simogasp** [comment]
And i guess u don't see anything in the right panel after the sfm node completes?

**Comment by tub-sgg** [comment]
yes  nothing after sfm

**Comment by tub-sgg** [comment]
but I got get file, the .obj file I can open it using meshlab @simogasp

**Comment by simogasp** [comment]
anyway it's strange because the alembic plugin is only to show the alembic file, the obj it should be loaded natively by QT.
It may be a problem related to qt, https://bugreports.qt.io/browse/QTBUG-75145
You are using 5.13.2 both for Qt and PySide2 right?

**Comment by tub-sgg** [comment]
yes I am using the latest version of Qt

**Comment by simogasp** [comment]
it should be fixed in 5.13.2

It says:
> I also can't find any examples in my `/Users/user/Qt/Examples/Qt-5.12.2/qt3d` (it is where I have Qt installed) regarding *assimp* but according to the [documentation](https://doc.qt.io/qt-5/qt3d-attribution-assimp.html) it must be there.

Can you?

**Comment by tub-sgg** [comment]
I dont have such Qt-5.13.2   such file I use homebrew to install qt @simogasp

**Comment by tub-sgg** [comment]
yours meshroom can display normally in 3D viewer? @simogasp

**Comment by simogasp** [comment]
> I dont have such Qt-5.13.2 such file I use homebrew to install qt @simogasp

yes but still you should have a folder with the examples in your local or cellar path.

> yours meshroom can display normally in 3D viewer? 

Yes but I'm not on OSx at the moment, I'm on Linux

**Comment by tub-sgg** [comment]
I did not find such folder? can not display anything in 3D viewer 
<img width="1272" alt="屏幕快照 2019-12-02 下午9 15 14" src="https://user-images.githubusercontent.com/44619635/70041844-28298280-15be-11ea-8cf2-f87a1cd8a3b2.png">

**Comment by tub-sgg** [comment]
only like this  nothing in the 3d viewer window @simogasp

**Comment by simogasp** [comment]
it should be in /usr/local/Cellar/qt/5.13.2

**Comment by tub-sgg** [comment]
but there isn't 
<img width="287" alt="屏幕快照 2019-12-03 上午11 20 39" src="https://user-images.githubusercontent.com/44619635/70042378-01b81700-15bf-11ea-82f9-646a479d8971.png">

**Comment by simogasp** [comment]
can you do a 
```
brew info qt5
```
a post the result. If i remember correctly there should be an option to install the examples, like `--with-examples` or something like that.
If you then can run the example we can see if it is a qt problem

**Comment by tub-sgg** [comment]
there isn't such options .brew install qt --with-examples will fail

**Comment by tub-sgg** [comment]
Btw, do you know how can I open .abc file?I know I can use meshlab to open .obj file. which software can i use, open and free will be better @simogasp

**Comment by simogasp** [comment]
> there isn't such options .brew install qt --with-examples will fail

what does `brew info qt5` give?

For abc you can try the last version of Blender

**Comment by tub-sgg** [comment]
brew install qt5
Updating Homebrew...
Warning: qt 5.13.2 is already installed and up-to-date
To reinstall 5.13.2, run `brew reinstall qt` @simogasp   like this

**Comment by simogasp** [comment]
but that's not what i ask...

`brew` **info** `qt5`

**Comment by tub-sgg** [comment]
qt: stable 5.13.2 (bottled), HEAD [keg-only]
Cross-platform application and UI framework
https://www.qt.io/
/usr/local/Cellar/qt/5.13.2 (9,861 files, 336.7MB)
  Poured from bottle on 2019-12-03 at 11:01:41
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb
==> Dependencies
Build: pkg-config ✔
==> Requirements
Build: xcode ✔
Required: macOS >= 10.12 ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
We agreed to the Qt open source license for you.
If this is unacceptable you should uninstall.

qt is keg-only, which means it was not symlinked into /usr/local,
because Qt 5 has CMake issues when linked.

If you need to have qt first in your PATH run:
  echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile

For compilers to find qt you may need to set:
  export LDFLAGS="-L/usr/local/opt/qt/lib"
  export CPPFLAGS="-I/usr/local/opt/qt/include"

For pkg-config to find qt you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"

==> Analytics
install: 68,295 (30 days), 178,113 (90 days), 662,731 (365 days)
install-on-request: 18,940 (30 days), 48,864 (90 days), 188,588 (365 days)
build-error: 0 (30 days)

**Comment by simogasp** [comment]
> but there isn't
> <img alt="屏幕快照 2019-12-03 上午11 20 39" width="287" src="https://user-images.githubusercontent.com/44619635/70042378-01b81700-15bf-11ea-82f9-646a479d8971.png">

what's inside `plugins`? is there a `sceneparsers` folder?

**Comment by tub-sgg** [comment]
<img width="200" alt="屏幕快照 2019-12-03 下午2 47 57" src="https://user-images.githubusercontent.com/44619635/70056541-ed364780-15db-11ea-8d07-835c9d9510aa.png">

**Comment by simogasp** [comment]
and inside `sceneparsers`?

**Comment by tub-sgg** [comment]
there isn't either

**Comment by simogasp** [comment]
ok, last resource, do
```
locate libassimpsceneimport
```
if nothing is found from the qt directory the problem is with your qt install

**Comment by tub-sgg** [comment]
nothing found but I just use homebrew to install it and I tried several times, it seems okay

**Comment by tub-sgg** [comment]
btw, I installed qt directly using the package downloaded from official website ,and I checked ,and still haven't found the folder you mentioned. Sometimes I use Qt creator to do coding. nothing wrong happened until so far @simogasp

**Comment by tub-sgg** [comment]
Have you solved this problem? @simogasp

**Comment by simogasp** [comment]
no, actually i checked on my mac and i have the same error

**Comment by tub-sgg** [comment]
sad ,I thought you could somehow fix it, but.... so sad @simogasp

**Comment by natowi** [comment]
@tub-sgg You can use Meshlab to view your models until there is a fix for the 2019.2 version or you could build the 2019.1 version.

**Comment by tub-sgg** [comment]
maybe it is not good idea to use MacOS to run meshroom, which is not friendly to MacOS

**Comment by tub-sgg** [comment]
yes just use Meshlab and Blender to view the result,although it is not convenient, somehow I could check

**Comment by yangliuyu** [comment]
same issue here.
I install the two plugin under `/usr/local/Cellar/qt/5.13.2/plugins/qml`
```
(meshroom) ➜  build git:(develop) export ALEMBIC_DIR=/usr/local/Cellar/alembic/1.7.12/lib/cmake/Alembic/

(meshroom) ➜  build git:(develop) cmake .. -DAlembic_DIR=$ALEMBIC_DIR -DCMAKE_PREFIX_PATH=$QT_DIR -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/qt/5.13.2/plugins/ -DCMAKE_BUILD_TYPE=Release

make install
...
6 warnings generated.
[100%] Linking CXX shared library libalembicEntityQmlPlugin.dylib
[100%] Built target alembicEntityQmlPlugin
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/Cellar/qt/5.13.2/plugins/qml/AlembicEntity/qmldir
-- Installing: /usr/local/Cellar/qt/5.13.2/plugins/qml/AlembicEntity/libalembicEntityQmlPlugin.0.1.dylib
-- Installing: /usr/local/Cellar/qt/5.13.2/plugins/qml/AlembicEntity/libalembicEntityQmlPlugin.0.dylib
-- Installing: /usr/local/Cellar/qt/5.13.2/plugins/qml/AlembicEntity/libalembicEntityQmlPlugin.dylib
```
And launch meshroom:
```
ALICEVISION_SENSOR_DB=/usr/local/Cellar/alicevision/2.2.0/share/aliceVision/cameraSensors.db ALICEVISION_VOCTREE=/usr/local/Cellar/alicevision/2.2.0/share/aliceVision/vlfeat_K80L3.SIFT.tree PYTHONPATH=$PWD python meshroom/ui
```
got:
```
Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportColoredPointCloud, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, LDRToHDR, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
[2020-01-04 03:21:40,707][WARNING] == The following plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'

```

**Comment by yangliuyu** [comment]
![1](https://user-images.githubusercontent.com/1361821/71868478-3b91b580-3149-11ea-8931-0afe069e03e5.png)
When I switch to windows, only got sfm result but no mesh data with default installation.
