### ISSUE TITLE
Fisheye images to be used to reconstruct[question]

### ISSUE THREAD

**Issue by tub-sgg** [alicevision/meshroom#720]
**Describe the problem**
A clear and concise description of what the problem is.
Someone has idea how to do reconstruction with fisheye camera using meshroom.And where can I set the camera model?
**Screenshots**

**Dataset**
If applicable, add a link or *few* images to help better understand where the problem may come from.

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ]
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1]
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**

**Comment by simogasp** [comment]
in `CameraInit` node, in its attributes panel, open `Intrinsics` and set `Camera Type` to `Fisheye4`

**Comment by tub-sgg** [comment]
thanks，so only the fixed model can be used  @simogasp

**Comment by simogasp** [comment]
what you mean?

**Comment by tub-sgg** [comment]
because my case it is a little special, the image exists a great distortion, especially  on the edge .  so do you have some experience to do reconstruction from such images? @simogasp

**Comment by simogasp** [comment]
please share an example. But if it is taken with a fisheye than it should be working with the settings above

**Comment by tub-sgg** [comment]
![image](https://user-images.githubusercontent.com/44619635/70054924-c7f40a00-15d8-11ea-861e-fb4ebf020ac1.png)
images like this @simogasp

**Comment by natowi** [comment]
This issue is closed due to inactivity. Feel free to re-open if new information is available.
