### ISSUE TITLE
[question]computeStructureFromKnownPoses does not color the point cloud

### ISSUE THREAD

**Issue by ihmc3jn09hk** [alicevision/meshroom#721]
**Describe the problem**
The point-cloud result (.ply) from computeStructureFromKnownPoses does not contain color information of the target.

**Screenshots**
The result from computeStructureFromKnownPoses
![result_01](https://user-images.githubusercontent.com/13495525/70126987-21316b80-16b5-11ea-89a3-baafb5dcad1d.PNG)

The result from IncrementalSfM
![result_from_incrementalSfM](https://user-images.githubusercontent.com/13495525/70127066-42925780-16b5-11ea-870d-288ddb6c3471.PNG)

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: win 10 64bit
 - Python version 3.5
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: 2019.2

**Additional context**
Another issue would like some response is the question of pipeline completeness on globalSfM as well as computeFromKnownPoses. 
Apart from the color issue, using the exact same dataset I can constraint the camera-poses computeFromKnownPoses as the name suggested. It is much faster. However, the number of landmarks reconstructed is way less then the one using the incrementalSfM. Another reason I have to use computeFromKnowPoses is, the camera-poses cannot be fixed even with "--lockAllInstrinsics" and disable "--localBA" while using "incrementalSfM". I even tried setting "locked = 1" for all poses in the input *.sfm mannually.

Hope someone could response to the issues

**Comment by natowi** [comment]
You can use this graph:
![wfl](https://user-images.githubusercontent.com/8138537/74945551-3dad8c00-53f8-11ea-946f-338295b2409d.JPG)

Can you share some details on your use case?

Take a look at the discussion here https://github.com/alicevision/meshroom/issues/788
and the wiki https://github.com/alicevision/meshroom/wiki/Using-known-camera-positions
