### ISSUE TITLE
[error] Unknown input SfM data format: '.obj'

### ISSUE THREAD

**Issue by thomasderijk** [alicevision/meshroom#726]
Hi!

When inputting a cleaned model into the texturing node (in the input path with the input removed)
I get the following errors

[16:19:24.457774][error] Unknown input SfM data format: '.obj'
[16:19:24.458773][error] The input SfMData file 'D:/Dropbox/_danio/_ZBRUSH/Tompoes_remesh_lower_normalsremoved.obj' cannot be read.

using fbx gives the same kind error

I have tried some solutions listed, removing the normals and materials for example. But that doesnt seem to do anything 

running 2019.2.0

this issue seems to be related to a bug that was present end of last year, as most of my search directed towards that time period

**Comment by ChemicalXandco** [comment]
```
[16:19:24.457774][error] Unknown input SfM data format: '.obj'
[16:19:24.458773][error] The input SfMData file 'D:/Dropbox/_danio/_ZBRUSH/Tompoes_remesh_lower_normalsremoved.obj' cannot be read.
```

It seems you are putting the remeshed mesh file into the 'Input' attribute of the texturing node. This section is for the sfm data, which is a '.abc' file. The mesh file should go in the 'Other Input Mesh' attribute, and there should be an edge connected from 'output' on the meshing node, to 'input' on the texturing node. If this doesn't work, please put entire log (including the bit that lists all the input parameters)

**Comment by thomasderijk** [comment]
You are correct! My bad

**Comment by ChemicalXandco** [comment]
No problem! If you are satisfied please close this issue

**Comment by thomasderijk** [comment]
and it works really well!!!! such a alternative to all the crazy expensive options out there
