### ISSUE TITLE
Meshroom OpenEXR can't be opened in PS. [question]

### ISSUE THREAD

**Issue by gameanimation3d** [alicevision/meshroom#728]
**Describe the problem**
A clear and concise description of what the problem is.

The openEXR undistorted images can't be open for viewing by Photoshop, PdPlayer..
Do you use an specific proprietary file encoding for openEXR?

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ] Windows 10 64bit
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1] 2019.2

**Additional context**

**Comment by fabiencastan** [comment]
No it's standard EXR. It should work in all softwares.
I usually open them in xnview or Nuke, but it should work in Photoshop.
The only thing is that the undistorted images are encoded in half-float, so maybe some softwares doesn't support that. Could you also test with the EXR depth maps (encoded in full float)?

You can also drag&drop an EXR file directly in the Meshroom viewer to visualize it.

**Comment by gameanimation3d** [comment]
Ok. I checked it with Nuke again and it works perfectly fine. 

I dont have the newest photoshop version (2015) so the issue might be resolved already ;)

**Comment by natowi** [comment]
You could also use IrfanView.
