### ISSUE TITLE
Texturing: Multi Band Downscale [question]

### ISSUE THREAD

**Issue by gameanimation3d** [alicevision/meshroom#729]
**Describe the problem**
A clear and concise description of what the problem is.

Regarding the Texturing Settings:
-> the Setting **Multi Band Downscale** does it affect the Texturing Quality??
-> what does it mean?
-> or does it simpily gives the Blending Algorithm a bigger step size for more precise blending?

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ] Windows 10 64it
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1] 2019.2

**Additional context**

**Comment by fabiencastan** [comment]
> -> or does it simpily gives the Blending Algorithm a bigger step size for more precise blending?

Yes, it doesn't reduce the quality! It defines the step between the frequency bands used for blending.

**Comment by gameanimation3d** [comment]
Thanks :)
