### ISSUE TITLE
[question] python error on download

### ISSUE THREAD

**Issue by CGJ3301** [alicevision/meshroom#737]
hey there, 

For a new project i'm working on I thought meshroom would be really helpfull,
After reading some guides en watching online turtorials I tried to dowload it but while I try to
open it an error pops up saying that I haven't installed some python thing,

In the zip I downloaded from the website, I saw a system file called python but when I try to install it
windows doesn't give me an option to run/install it and it gives me a warning saying it can harm my device, can anybody help me with this or give me advice?

**Comment by fabiencastan** [comment]
The release archive includes all you need to run the software including python. You have probably not downloaded the right thing. Here is the URL to download the software:
https://alicevision.org/#meshroom
