### ISSUE TITLE
[bug] Unable to install requirements and dev_requirements

### ISSUE THREAD

**Issue by Kaszanas** [alicevision/meshroom#739]
**Describe the bug**
Requirements fail to install.

**To Reproduce**
Execute command: ```pip install -r requirements.txt -r dev_requirements.txt```

**Expected behavior**
Getting the Environment set up.

**Desktop (please complete the following and other pertinent information):**
 - OS: Win10
 - Python version: 3.7

**Additional context**
The following package ```cx_Freeze==5.1.1``` is known to cause issues on Windows 10.
The problem seems to be solved here:
https://github.com/anthony-tuininga/cx_Freeze/issues/410
and here:
https://github.com/anthony-tuininga/cx_Freeze/issues/496

I will try to execute the code with the proposed fix and if it runs correctly I will include that in a Pull Request.

**Comment by Kaszanas** [comment]
Changing the ```cx_Freeze==5.1.1``` to ```cx_Freeze``` fixed the problem for me.
current version of cx_Freeze is 6.0
I am yet to discover if that will not break any other functionality of the software.
Will keep You posted.

**Comment by natowi** [comment]
cxFreeze supports Python 3.5 or higher. For Python 2.x, cx_Freeze version 5.1.1 should be used. [*](https://cx-freeze.readthedocs.io/en/latest/)

"[latest cxFreeze 6.0 is not compatible with python 2.7 and breaks tests](https://github.com/alicevision/meshroom/blob/develop/dev_requirements.txt)", so cx_Freeze==5.1.1

**Comment by Kaszanas** [comment]
I agree @natowi this might break some tests. I have posted some sources that indicate this version to have compatibility issues.

On the other hand python 2.7 lost the official support as of this year and I would rather move all of the software towards newer releases of Python.
