### ISSUE TITLE
[bug]ERROR:root:Error during Graph execution Error on node "DepthMap_1(0)"

### ISSUE THREAD

**Issue by MildaGenius** [alicevision/meshroom#742]
**Describe the bug**
Converting process stops on DepthMap step with error:
`ERROR:root:Error during Graph execution Error on node "DepthMap_1(0)"`

**To Reproduce**
1. Start MeshRoom
2. Drag folder dataset_monstree/full with images to MeshRoom
3. press Start button
4. See error on DepthMap

**Expected behavior**
Process should pass over each state to finish.

**Log**
[MeshRoom 2019.2.0 ERROR:root:Error during Graph execution Error on node "DepthMap_1(0)"](https://gist.github.com/MildaGenius/34808d2178bcca83fb515511205e351d)

**Desktop (please complete the following and other pertinent information):**
 - OS: Windows 10
 - Python version 3.6.6
 - Qt/PySide version ?
 - Meshroom version: 2019.2.0

**Additional context**
I have the same behaviour for my images and for referencing dataset_monstree.

**Comment by natowi** [comment]
Might be the same bug as https://github.com/alicevision/meshroom/issues/593

**Comment by MildaGenius** [comment]
2019.1 has the same error.
2018.1 fails while starting
