### ISSUE TITLE
[request] BoundingBox filter node

### ISSUE THREAD

**Issue by polarathene** [alicevision/meshroom#744]
**Is your feature request related to a problem? Please describe.**

A bounding box similar to the feature in 3DF Zephyr allows you to define a volume(interactively in the viewport with a gizmo) to ignore data outside of it for future processing steps. This should allow for reducing computation and memory from observed data that the user knows is not important

**Describe the solution you'd like**

In other software, I have had a light point cloud generated with the alignment/extraction step. The bounding box can indicate the area of interest in case near/far points were added but not relevant for the final output(eg background/distance data of a scene, or the base of what the subject rests on top of). 

This avoids generating dense points outside of the volume, or meshing outside of the volume, or any data that doesn't contribute much value to the the content within the bounding box volume for any other operations like texturing.

A similar tool can also delete points/triangles, useful for removing the base surface.

**Describe alternatives you've considered**

Current advice is to handle this via external tools like MeshLab.

**Comment by mobarre** [comment]
Quick note here to accompany my thumps up. I use photogrammetry a lot for outside views of houses. Images are taken with a drone and often include views with a little altitude. I just did a house in a valley. you can imagine the amount of data I get, spanning several kilometers around (mountains in the background, houses in the neighborhood). This makes things incredibly difficult to process unless you have a monster workstation with terabytes of RAM :p

**Comment by natowi** [comment]
Image masking can be used to reconstruct only a specific area:
https://github.com/alicevision/AliceVision/pull/715
https://github.com/alicevision/meshroom/pull/708
https://github.com/alicevision/meshroom/pull/641
https://github.com/alicevision/meshroom/pull/750

**Comment by natowi** [comment]
Image masking will be (partially) supported with the next release or by building from source.
Getting a bounding box would be nice, but it will take some time until someone implements it.

**Comment by djoerg** [comment]
To accompany my thumps up. I think such a bounding box feature should be implemented to work with the output from the  Sfm-node  BEFORE the DepthMap step. Cause the DepthMap is the most computaional extensive step, it could bring the most performance benefit limiting this computation to only the relevant parts of the reconstruction.

Surely, this is not a trival task cause it needs an extra interface in the GUI and a relative big change in the DepthMap code.
So i didn't expect it to be implemented soon :(

**Comment by natowi** [comment]
Now available with the 2020 release: https://github.com/alicevision/meshroom/issues/256#issuecomment-709983331

**Comment by slate0** [comment]
May I add that in 2021.1 it appears that the bounding box functionality is integrated into the "Meshing" node with the checkbox "custom bounding box"?   This page comes up when searching for "meshroom bounding box" and I think it is worth updating with the latest information in order to help other users.

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/wiki/Bounding-Box

**Comment by natowi** [comment]
https://github.com/alicevision/Meshroom/wiki/New-Features-in-Meshroom-2023.1#1-image-masking
