### ISSUE TITLE
ABC and PLY

### ISSUE THREAD

**Issue by NexTechAR-Scott** [alicevision/meshroom#746]
Trying to set up a CLI pipeline for semi automated processing.  Everything works great with default pipe.

I do have a need to interrupt after SFM to edit the point cloud then insert the point cloud back into the pipe.

The reason is we know we get a lot of background in this process and it just adds compute time that id like to eliminate.

We can export ply and abc from Meshroom and there are tools to edit them.

What I'm running into is Meshroom, although it can export a ply does not seem to ingest and process them.

Editing SFM.abc and exporting from a third tool like Blender results in an abc that also does not process.

Has anyone had any luck exporting a point cloud from SFM node and bringing back into PrepareDenseScene node?

If yes what did you use?

Thanks a bunch.

**Comment by MightyBOBcnc** [comment]
Editing the point cloud breaks the indices storing point visibility.  

https://groups.google.com/forum/#!topic/alicevision/cxKA0mWEy-0

There's no way at the moment to edit the cloud directly.  They're working on some masking tools that might hopefully make it into the next release.  In the meantime you might check Fabien's suggestion in the linked thread for filtering the sparse cloud that generates the bounding box for which areas get meshed.

https://groups.google.com/forum/#!topic/alicevision/-peqet_Gfuo

**Comment by NexTechAR-Scott** [comment]
Thanks Bob

I’ve managed to get better results already with MinObservationAngle and will see if MinObservations is additive.

Fabiens explanation was an eye opener, in all my searches I’ve not seen anyone explicitly tie those two parameters to generating a bounding box.

Never clear how they worked, just that they changed output.

Cheers.
