### ISSUE TITLE
[bug] Text rendering wrong for nodes

### ISSUE THREAD

**Issue by clankill3r** [alicevision/meshroom#747]
I just downloaded meshroom 2019.2.0, the text in the nodes looks as follows:

![meshroom_text_rendering](https://user-images.githubusercontent.com/738650/71510994-afe67200-2888-11ea-960f-56380f27a4bd.png)

- win10
- python 3.7
- meshroom 2019.2.0

**Comment by natowi** [comment]
I can confirm this behaviour on high resolution screens with scaling enabled.
Reference https://github.com/alicevision/meshroom/issues/311

**Comment by natowi** [comment]
This might be no longer an issue with the upcoming release, as the nodes have been [redesigned](https://github.com/alicevision/meshroom/pull/612)
