### ISSUE TITLE
[question] Pathching up a model in another application?

### ISSUE THREAD

**Issue by clankill3r** [alicevision/meshroom#748]
In other photogrammetry programs I used I was able to export a model. Fix ugly / missing faces and then import the model back in the photogrammetry application so it could update for the textures.

Is it possible to do such thing in photogrammetry? And if so is there any tutorial availbe online? No matter what 3d modelling application they use for the fixes.

**Comment by ChemicalXandco** [comment]
[This wiki page](https://github.com/alicevision/meshroom/wiki/Texturing-after-external-re-topology) has instructions on how to do what you are trying to achieve
