### ISSUE TITLE
[bug] PNG metadata is not read, but JPG is (darktable exports)

### ISSUE THREAD

**Issue by chconnor** [alicevision/meshroom#751]
**Describe the bug**
Exporting a PNG from darktable results in an image that fails to load metadata in meshroom. Exporting to JPG works. If I examine in GIMP, metadata is present for both images. (Both images taken with same camera/lens.)

Example images:
http://caseyconnor.org/pub/image/bugs/meshroom/IMG_8681.png
http://caseyconnor.org/pub/image/bugs/meshroom/IMG_8624.jpg

Screenshot: http://caseyconnor.org/pub/image/bugs/meshroom/meshroom_sshot.png

 - OS: Ubuntu 18.10, 4.18.0-25-generic #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Python version 2.7.16 and 3.6.8
 - Qt/PySide version 5.11.1
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version 2019.2.0

**Comment by chconnor** [comment]
Let me know if there is anything else I can provide about this.

**Comment by fabiencastan** [comment]
@chconnor Thanks for the bug report. It is a problem in the image library that we are using to load images. The issue has been reported to oiio.

**Comment by chconnor** [comment]
Fantastic, thanks.

**Comment by natowi** [comment]
This should be resolved with the 2020 release.

**Comment by natowi** [comment]
https://github.com/OpenImageIO/oiio/issues/2573#issuecomment-726303479

Should work now with the latest release
