### ISSUE TITLE
colab ModuleNotFoundError: No module named 'meshroom'  

### ISSUE THREAD

**Issue by JihedHmida** [alicevision/meshroom#752]
File "/content/drive/My Drive/Box/test/meshroom/bin/meshroom_photogrammetry", line 7, in <module>
    import meshroom
ModuleNotFoundError: No module named 'meshroom'

PYTHONPATH = /env/python:/content/drive/My Drive/Box/test/meshroom

**Comment by natowi** [comment]
Did you follow https://gist.github.com/natowi/3044484ad0c98877692c399297e3ab7e ?

**Comment by JihedHmida** [comment]
Yes.. the only difference is that i used this 
!git clone --recursive git://github.com/alicevision/meshroom %cd meshroom !pip install -r requirements.txt
Because i get the "Cannot create symlink to '.......’: Operation not supported" error using the tar

**Comment by natowi** [comment]
You need to check the install location. You need to navigate into the destination folder before downloading. Try without google drive link first.

**Comment by fredkomo** [comment]
I have the same problem but I can't resolve it. Could you be more explicit in the steps to follow to make Meshroom work with colab (I have also the problem with tar and symlinks). Thanks.

**Comment by JihedHmida** [comment]
for me it worked by skiping  the google drive link part
"from google.colab import drive
drive.mount('/content/drive')"
and working directly on the /content..

**Comment by natowi** [comment]
I´ll take a look at this problem

**Comment by fredkomo** [comment]
> for me it worked by skiping the google drive link part
> "from google.colab import drive
> drive.mount('/content/drive')"
> and working directly on the /content..

Yes. It Works like this. No symlink problem with the tar archive. I was using /drive/content for install. Thanks ! And sorry for the noise.
