### ISSUE TITLE
Export blender traking solution for manual matching

### ISSUE THREAD

**Issue by canonex** [alicevision/meshroom#753]
In some cases, for some kind of surfaces, a manual tracking is required:
is there a possibility to export blender motion tracking data to Meshroom?
There are some other solutions?

Thank you,
Riccardo

**Comment by natowi** [comment]
I am not sure how and why you would like to use the blender motion tracking data in Meshroom.
Support for Manual tracking (manual control points) is on the to-do list.

**Comment by canonex** [comment]
I have plaster works to scan:
![0001-L](https://user-images.githubusercontent.com/1444378/72246649-7b4a1880-35f3-11ea-8e6f-e071470d6576.jpg)

I can't get acceptable results with the automatic procedure and I would like to enter the match points manually.
In other software (Photoscan) with the manual procedure you get very good results.

Since I know that the manual procedure is not present at the moment I was wondering if it would be possible to use the Blender tracker directly for this task.

**Comment by natowi** [comment]
You can try using CCTAGs. 
For white plaster you could use _structured light_ to get better results (I assume you can not paint/add markers on the plaster work)

**Comment by canonex** [comment]
It was on my plan to have another shooting session.
I'll try for sure a noise projection ( I can't even touch it, I dare not imagine what would happen if I paint it ;) ).

I would also like to insert markers for CCTAGs but I'm not good at compiling.
What variety / version of linux is known to run smoothly to compile it?

Thank you!
Riccardo

**Comment by natowi** [comment]
> I would also like to insert markers for CCTAGs but I'm not good at compiling.

CCTAG support is included in the latest release. You can use cctag3 markers from here https://github.com/alicevision/CCTag/tree/develop/markersToPrint

**Comment by canonex** [comment]
I didn't notice it was already in!

Thank you for guiding me.
