### ISSUE TITLE
Meshroom scans full room but not the scanned object

### ISSUE THREAD

**Issue by M4rcde** [alicevision/meshroom#755]
Hello,

first of all, thanks to all contributors of Meshroom! This is seriously some great software! However, i have following problem: 

### The Scan
I scanned an quite simple object with a sum of **~3000 images** (yes that quite takes a while to process). I tried to get one perfect scan. I fixed the quite big object on a chair with a displacer between chair and object, so i can scan it **360x360 degrees**.  My plan was to remove the displacer in Post-Production. This is 100% stiff, so the construction did not move around while taking the images. **Light was also perfect** (no shadows at all). My images were shot automatically quite tight together (like 3cm distance between each photo on horizontal axis and 30cm distance on vertical axis - see images). I dont know if this matters? I am using Meshroom-2019.2.0 on Windows with a RTX2070. 

### The Issue
**The output of the "Meshing"-Node does not show the object.** It does also not show the chair and the displacer (which isnt a requirement at all). **Instead, it shows the whole "room" like the object and the steel rodes were never in the room at any time** ^^ It is like the object was "cut out". The room looks quite good meshed however, but of course that is not what I wanted to do. As this took 4 days to process, I thought i messed up some settings (which are nearly all standard - just changed downscale setting). I remembered the "Keep only the largest Mesh"-setting in the "MeshFiltering"-Node. **But the "Keep Only the Largest Mesh"-Setting is NOT activated.** 

### Images
![struc](https://user-images.githubusercontent.com/6267156/72206946-02807a80-3494-11ea-8145-7949f8555342.PNG)
On this image you can see the output of the "StructureFromMotion" node. I set the camera-size and the point-size to very low. You can even see the object here quite good. Everything looks fine. 

![meshing](https://user-images.githubusercontent.com/6267156/72206945-02807a80-3494-11ea-9177-e6ca6126d139.PNG)
This image however shows the output of the "Meshing"-node from the same perspective. You can see, that the chair and everything on it is just gone. Instead, there its a little whole on the floor (its actually grass - i propably never did a capture of this area). 

![both](https://user-images.githubusercontent.com/6267156/72206944-02807a80-3494-11ea-9715-8bb9157af858.PNG)
This image shows "StructureFromMotion" and "Meshing"-Node Output at the same time. You can see that there is absolutly no Mesh were the object is...

Does anyone have any idea on how to avoid/solve this? Do I need to make a new scan? Is it just a setting-thingy? Which settings could produce such a result? Is it maybe an real issue?  

Thanks for your help. Marc

**Comment by natowi** [comment]
The object texture might be problematic (white?) and you are too far away for this object size. A ~200 images should suffice, your object does not look complicated. Do close ups.

**Comment by M4rcde** [comment]
Thanks for your answer!

> (open the Texturing folder and try to open the obj in Meshlab)
![meshlab](https://user-images.githubusercontent.com/6267156/72208264-0bc41400-34a1-11ea-8102-f85e2e879134.PNG)
I did, as you can see here. There is a little black whole in the middle. This is were the actual chair with the quite big object was (see image below). I mean it is sooo big, i think this is hard to "ignore" for the meshroom? 

> The object texture might be problematic (white?) and you are too far away for this object size. Round about 200 images should suffice, your object does not look complicated. Do close ups.
> Similar to this #505 and this #565

I am shooting with 24mm lens, as this gives me some quite linear non-distorted image. 
![exampleimg](https://user-images.githubusercontent.com/6267156/72208221-a6702300-34a0-11ea-8fd2-4983f71fc9fb.PNG)
As you can see here, i shot quite close (i needed to take a screenshot from the image - couldnt upload the original one)... My object is a split wood block, so it got quite some good texture to track and is non-reflective. I chose it, because i thought this would be quite easy and give good results. It is like 35cm in height (just to get an idea for the size).

I had a look at the two issues you posted. I dont think this is the same here?

**Comment by natowi** [comment]
> I mean it is sooo big, i think this is hard to "ignore" for the meshroom?

I think the problem is, that the wood is on a black brick and a mesh chair. there might not be enough features to connect the wood to the large surrounding mesh and might be filtered out.

_The object of interest should always fill most of the image frame_. With close ups your object can be reconstructed with a few images and in under an hour computation time.
