### ISSUE TITLE
Meshroom fails at texturing[bug]

### ISSUE THREAD

**Issue by strike-digital** [alicevision/meshroom#757]
when meshroom gets to the texturing phase, it loads all of the relevant info and then stops, with the node turning red. this is the log:

\`\Program called with the following parameters:
 * angleHardThreshold = 90
 * bestScoreThreshold = 0
 * downscale =  Unknown Type "unsigned int"
 * fillHoles = 0
 * flipNormals = 0
 * forceVisibleByAllVertices = 0
 * imagesFolder = "D:/Documents/meshroom/Naturall/rocks/rock 8/MeshroomCache/PrepareDenseScene/73ff6ecb5f2b76698d1ace95bfe5f19fa7bb168c"
 * input = "D:/Documents/meshroom/Naturall/rocks/rock 8/MeshroomCache/StructureFromMotion/e2ce29ba5dffd6734e4b5799f5c3eaa632430a77/sfm.abc"
 * inputDenseReconstruction = "D:/Documents/meshroom/Naturall/rocks/rock 8/MeshroomCache/Meshing/ca70afb88b3c19042b5a65b3cebde0bfc07d008b/denseReconstruction.bin"
 * inputMesh = "D:/Documents/meshroom/Naturall/rocks/rock 8/MeshroomCache/MeshFiltering/4a668633b114b8280b5cd97a5692f6217d81c39c/mesh.obj"
 * maxNbImagesForFusion = 3
 * output = "D:/Documents/meshroom/Naturall/rocks/rock 8/MeshroomCache/Texturing/974bbea0b54229f2bb7a757536a42c9218752583"
 * outputTextureFileType = "png"
 * padding =  Unknown Type "unsigned int"
 * textureSide =  Unknown Type "unsigned int"
 * unwrapMethod = "Basic"
 * verboseLevel = "info"
 * visibilityRemappingMethod = "PullPush"

[20:03:44.759035][info] Found 1 image dimension(s): 
[20:03:44.759035][info] 	- [5184x3456]
[20:03:46.534027][info] Overall maximum dimension: [5184x3456]`\`
![Screenshot (136)](https://user-images.githubusercontent.com/59890307/72378958-54323a80-370a-11ea-9cf1-e985ecdd1a9d.png)

this is the first time this has happened and all of my other projects have been successful

I'm on Windows 10 and I don't know what version of python it is

**Comment by fabiencastan** [comment]
Could you share the dataset with me (fabien.castan[at]mikrosimage.com) to see if, by any chance, I can reproduce it?

**Comment by fabiencastan** [comment]
I didn't manage to reproduce it. It works fine on my side.

**Comment by strike-digital** [comment]
Yeah, I ran it again from the start and it completed it. im not sure what went wrong.
