### ISSUE TITLE
[bug] MeshroomCache not found - Windows

### ISSUE THREAD

**Issue by FabienDanieau** [alicevision/meshroom#758]
When I load previously computed .mg file, in a new window, the cache is empty. This issue concerns Windows platforms only, I don't have this problem with Linux.

The cache is working properly within the same window. I can compute a new pipe, and then go back to old results. But if the meshroom is closed, I won't be able to recover the cache while it exists on the disk.

**To Reproduce**
1. Open meshroom 
2. Compute a pipe (default is fine)
3. Save pipe
4. Close meshroom
5. Open meshroom
6. Load pipe
X. Cache is missing

**Desktop (please complete the following and other pertinent information):**
 - OS: Win 10
 - Python version 3.5
 - Qt/PySide version 5.13
 - Meshroom version: please specify if you are using a release version or your own build

**Comment by natowi** [comment]
Try saving the project before starting the computation in a location of your choice
Save project
Close meshroom
Open meshroom
Load project

**Comment by FabienDanieau** [comment]
What do you mean by saving a project? I do save a pipe to get a .mg file (step 3). I guess it is what you call a project.

By the way the variable 'self.cacheDir' in graph.py is properly set when I load a project.

**Comment by natowi** [comment]
Meshroom menu->file->save as --- save your mg file and the cache folder to a directory of your choice. This should be done before doing the computation, as the cache folder will be created in the same folder as the mg file.

> By the way the variable 'self.cacheDir' in graph.py is properly set when I load a project.

Using the default temp folder is not recommended, maybe your system is set to clean up the temp folder?

**Comment by FabienDanieau** [comment]
Sorry I am not clear.
The project has been saved in My Documents. The cache folder is indeed created next to this file. However, when I close meshroom, re-open meshroom and load the project, the cache is not loaded.

The default temp folder is thus not used, and the self.cacheDir shows the correct location ("My Documents/MeshroomCache").

**Comment by natowi** [comment]
OK, that is strange. Did you check the cache folder and made sure it has content in the node folders?

**Comment by FabienDanieau** [comment]
Yes, the content is there.
Actually sub-folders are re-created. It seems that the generated ids differ from the original ones.

**Comment by natowi** [comment]
Did you make changes to the default graph/settings? Each change will create a new folder per node. If the changes are not saved, the mg file will load the last saved settings. However by using the same settings as before node data can be restored.

**Comment by FabienDanieau** [comment]
I have this issue with the default graph or a custom one.

**Comment by FabienDanieau** [comment]
uids are properly saved in the .mg file, and match the actual folders in the cache directory.

But somehow, when I load the same mg file in a new meshroom window, new uids are generated. This would explain why the cache folders are not found and why new ones are created.

**Comment by natowi** [comment]
Sorry, but I can not reproduce your error.

> The issue is NOT present with the release version 2019.2.0.

What version are you using?

**Comment by ChemicalXandco** [comment]
I was able to reproduce this in release version 2019.2.0

**Comment by FabienDanieau** [comment]
> What version are you using?

I reproduced the bug with yesterday's commit 44901f06c25aa48596c7bfe19f4e3d42950dd3b8, and the default project.

**Comment by fabiencastan** [comment]
> The default temp folder is thus not used, and the self.cacheDir shows the correct location ("My Documents/MeshroomCache").

self.cacheDir is supposed to be an absolute path

**Comment by FabienDanieau** [comment]
> self.cacheDir is supposed to be an absolute path

Yes it is sorry for the typo. C:\Users\Fabien\Documents\MeshroomCache

**Comment by fabiencastan** [comment]
The only thing that I'm aware of that can change the UID is the version of python.
So if you are using 2 versions of Meshroom one built with python-2 and the other one with python-3, the same scene will not give the same UID, so the data computed in one version cannot be loaded with the other version.

I don't see what else can change the UID, except, of course, if there is a change in the input images.

**Comment by fabiencastan** [comment]
Just to clarify, there is a typo in the steps to reproduce (otherwise it's normal for the cache to be lost):
```
Steps to reproduce the behavior:

1. Open meshroom
2. Compute a pipe (default is fine)
3. Save pipe => here the cache is modified to be in the same folder than the project, so you loose all the computed data. You need to save the scene before computing.
4. Close meshroom
5. Open meshroom
6. Load pipe
7. X. Cache is missing
```

**Comment by FabienDanieau** [comment]
The cache is missing either the pipe is computed before or after saving. I just tried with the more recent commit 2beb349b882ce93f726030d411ef4bd95f70fcdf. The be crystal clear, the cache is well created at the right location. It is just not loaded from a new meshroom window, meaning I have to recompute everything every time I close meshroom.

I don't have this issue with the binary version (release 2019.2.0). Actually it does not matter if the pipe is saved before or after computing. The cache is found anyway. This is the behavior I expect.

**Comment by FabienDanieau** [comment]
Apparently the problem is due to python. I upgraded python in my conda environment from 3.5 to 3.6.10 I had to reinstall psutil as well. The cache is now found properly...
I'll run more tests tomorrow with another computer. If my tests are successful, I'll close this thread.
