### ISSUE TITLE
Trying to get a scan of upper body, but getting hole where person should be

### ISSUE THREAD

**Issue by jplasencia** [alicevision/meshroom#760]
Hello all, 

I am trying to  make a 3d model of my son for 3D printing. I used a DSLR camera and took about 80 pictures. All of the pictures were focused on the the upper body, since I do not want to make a model of the whole body. 

I loaded these images into Meshroom, but when all is processed, I end up with a hole where the person should be. See screenshot below. Do I need to take pictures of the whole body to make this work?
![image](https://user-images.githubusercontent.com/1497066/72645489-c3de3a80-3941-11ea-8e17-0751f128b7b9.png)

I've already unchecked the "Keep only the largest mesh" setting in MeshFiltering, which has been suggested for similar issues, but this does seem to have an effect. I suppose I could go out and retake the pictures including the whole person this time, but if there's another setting I'm missing,  that would be even better.

Thanks,

Julio

**Comment by natowi** [comment]
The object of interest should always fill most of the image frame.
Similar to this #755, #505, #565, #646

**Comment by jplasencia** [comment]
Thanks, I retook the pictures and I'm re-processing them right now. It's
looking good so far.

**Comment by jplasencia** [comment]
Thanks, I re-took the pictures and I'm processing them right now. It's looking good so far.

Julio

**Comment by jplasencia** [comment]
Ok, I'm back. I retook the pictures and most of my pictures have the face filling most of the frame. Please see belowe:

![image](https://user-images.githubusercontent.com/1497066/72690448-85d04a80-3aea-11ea-9a6f-632ce1cff08e.png)


However, here's what I get when the processing is completed:
![image](https://user-images.githubusercontent.com/1497066/72690455-9b457480-3aea-11ea-86cd-0525a4e526bc.png)

What's interesting, is when previewing the texture in Meshroom, it seems to be capturing the person correctly, see below:

![image](https://user-images.githubusercontent.com/1497066/72690498-f4ada380-3aea-11ea-807a-1ec39ddec9b4.png)


But when processing is completed, only a hole is left where the person should be.

Are there any other settings that would affect this?

**Comment by natowi** [comment]
When you double click on the Meshing node, is the hole already in the mesh?

**Comment by jplasencia** [comment]
Hi @natowi ,

When I click on the meshing node, I see both the hole and my subject, with the subject floating above the hole, see below. The final texturing node, however, does not include my subject.


![image](https://user-images.githubusercontent.com/1497066/72733144-3f6c0180-3b65-11ea-8f46-cecf461cf2de.png)

**Comment by natowi** [comment]
Ok, I think you still have to many background areas in your images. As you captured the upper body  only, it is not connected to the larger surroundings and filtered out/ dismissed as outliers. It would be better to capture this in a studio setting with featureless background. The upcoming support for image masking will be useful to mask out the background. https://github.com/alicevision/AliceVision/pull/715

This is an images where your subject fills most of the screen:
![re1](https://user-images.githubusercontent.com/8138537/72733408-1add4d00-3b98-11ea-90d0-dde53d9a4897.JPG)

taking close ups would be even better:
![re2](https://user-images.githubusercontent.com/8138537/72733863-02216700-3b99-11ea-8f93-3ff3881dfa60.JPG)

**Comment by jplasencia** [comment]
Thanks, sounds like image masking would allow me to select areas of interest? I will retry taking pictures again. For now, I will mark this issue as closed. Thanks for your help.

**Comment by natowi** [comment]
> Thanks, sounds like image masking would allow me to select areas of interest?

Yes, you would mask out the background and leave only the area of interest.

**Comment by hargrovecompany** [comment]
If you're trying to do this with one camera you are fighting an uphill battle.  There will be movement between shots.  Shooting a static/still object with a single camera is fine, unless lighting changes (i.e. shooting outside when clouds might change lighting between shots).  But you simple can't get a high quality output when taking 80 shots of a person, even if they're seated.
