### ISSUE TITLE
[request] Don't save as .mg files

### ISSUE THREAD

**Issue by NorthernXY** [alicevision/meshroom#761]
I came here from a tutorial that saved as .ojb files.  Now it's using .mg files, which I can only find Meshroom uses.  Why go from supported to unsupported?

**Comment by simogasp** [comment]
The mg file has been always the project file of Meshroom where all the parameters and the pipeline graph are saved.

The obj are generated by the Texturing and/or the Publish nodes, just right click on the node, `Open Folder` and there they are.

**Comment by NorthernXY** [comment]
Much obliged, been trying to get a 3D map for a week to design a castle on.  I'm very new to graphic design and quite often steps are skipped or one add-on for Blender leads to another add-on I need, and so forth.

**Comment by simogasp** [comment]
No problem ;-)
feel free to close the issue if that answers your question.
