### ISSUE TITLE
Texturing with an alternative set of photos

### ISSUE THREAD

**Issue by tpieco** [alicevision/meshroom#763]
Is there a way to generate a mesh from one set of photos but then texture with another set? I've tried a number of things, like unplugging the imagesFolder connector from the texturing node and pointing to the directory of the new photos, and swapping the generated images in the PrepareDenseScene folder with the alternative photos but it causes the process to fail.

Is it possible at all now or will be in the future? 

Thanks

**Comment by natowi** [comment]
Use a structured light dataset for example, then set the image dataset without structured light in the PrepareDenseScene folder. Use the same image names. [Sample datasets](http://www.pi3dscan.com/index.php/download/category/sample-scan-files)

**Comment by tpieco** [comment]
Thanks for the reply.
The process completed but with mesh errors, seen in the image below. I might be completely wrong in thinking it would work, but I was with trying to make more accurate roughness maps by taking polarised and unpolarized photos of an object, using the texture generated from the unpolarized photos for the roughness map.

![additionalphotos](https://user-images.githubusercontent.com/49287303/72737859-4f510900-3b98-11ea-8014-2b153f1ee0d8.jpg)

**Comment by natowi** [comment]
So the "without" sample is computed from polarized images?

**Comment by tpieco** [comment]
Yes. The object on the right (without) is the result using polarized images. The object on the left uses the polarized images but with the unpolarized images added as Image Folders in the PrepareDenseScene. Hope that makes sense.

**Comment by natowi** [comment]
I think in your case it is best to use the polarized images only. The results are good and there is no reason to add the normal images for texturing, as they may contain reflections we want to avoid.

**Comment by tpieco** [comment]
I can't fault the results I'm getting with polarized images, they're brilliant. It's just that creating roughness maps is a frustration to me and I'm trying any tricks I can think of to make them more simply and accurate.

Thanks.

**Comment by natowi** [comment]
Projecting a pattern on the surface and use it for the reconstruction could improve the quality of the surface reconstruction. But this can be difficult to set up.

You can also try out adding powder or paint on your model to highlight more features (before, capture an image set for later texturing). 

If you need only a part of the model in high resolution for later use in a 3d modelling tool, you can generate a texture using [Reflectance Transformation Imaging](http://culturalheritageimaging.org/What_We_Offer/Downloads/Process/index.html) (RTI) and export the normals map.

**Comment by hargrovecompany** [comment]
I am needing to use the capability to swap from using projected pattern lighting images for mesh to normal lighting for texture.  I can't find the image that shows the entire workflow.  I found one in your wiki that has an image, but it's cut off on the left, doesn't show initiation of that part of the workflow.  I believe there was another issue or something here at one time that had an image of the full workflow...can anyone help?   Thanks!

**Comment by natowi** [comment]
@hargrovecompany Default pipeline + https://github.com/alicevision/meshroom/wiki/Projected-Light-Patterns

**Comment by hargrovecompany** [comment]
Natowi, I finally found the post that I was looking for.  https://groups.google.com/forum/#!topic/alicevision/Y1mde4F1KmU

I'm a bit confused....do I need to actually modify the workflow as in the link, or simply add the file location as in the link that you provided above?  

Also, I have some really good sample image sets now.  My rig is giving me great results.  If anyone here might need a set of images for testing, let me know.   

I've haven't tuned in here in quite some time.....I noticed something today about software to support a rig...I have a pretty good system, written in python.   It supports pi cameras and a bunch of DSLR cameras, and it has the ability to mix them.  It has color correction (post capture processing) capabilities.  Pretty nifty stuff.  If you guys need any of it let me know.

**Comment by natowi** [comment]
@hargrovecompany oh yes, thank you, I forgot. 
![image](https://user-images.githubusercontent.com/8138537/72788125-88898780-3c31-11ea-93c6-840413461a55.png)
I corrected it in the wiki. 

> Also, I have some really good sample image sets now. My rig is giving me great results. If anyone here might need a set of images for testing, let me know.

Having a camera rig sample dataset for Meshroom under a creative commons license would be nice, so it could be used for testing and for tutorials similar to the monstree dataset.

> I noticed something today about software to support a rig

Yes, there is some basic rig support. https://github.com/alicevision/meshroom/wiki/Multi-Camera-Rig

> I have a pretty good system, written in python. It supports pi cameras and a bunch of DSLR cameras, and it has the ability to mix them. It has color correction (post capture processing) capabilities. Pretty nifty stuff. If you guys need any of it let me know.

Yes, we talked about this in https://github.com/alicevision/meshroom/issues/480. Your contribution is welcome.

**Comment by tpieco** [comment]
@natowi Fantastic! That does exactly what I was looking to do. Thanks.

**Comment by hargrovecompany** [comment]
I just ran a projected/normal sequence adding only the NORMAL images location under the Prepare Dense Seen node  It appears to have worked property without modifying the workflow as in the image above.   I'll run it again with the modifications as in the image and and see if I can tell any significant difference.   

And, my apologies, but I have no clue how to contribute in way that complies with the normal processes....if you tell me how I can help, I'll do my best

**Comment by hargrovecompany** [comment]
Here is a link to one of my sample sets....projected and normal lighting, full size human scan

https://www.dropbox.com/sh/3zmb8hqtd84at2n/AACU-YMBZmBT2lXusyXQ_FuIa?dl=0

**Comment by hargrovecompany** [comment]
I tried adding the second Prepare Dense Scene node, and added the folder location for normal images.  I'm using version 2019.2.0    Here's a few shots of the workflow.   I still seem to have my patterned lighting images used as texture...
![nodes](https://user-images.githubusercontent.com/45779552/72932327-2b6efe00-3d25-11ea-8db5-1f04f4cda38b.PNG)
![folder](https://user-images.githubusercontent.com/45779552/72932362-417cbe80-3d25-11ea-925e-3962703b8aca.PNG)

**Comment by tpieco** [comment]
@hargrovecompany The photos in the Normal folder are also projected photos.

**Comment by hargrovecompany** [comment]
wow.....well, that's embarrassing....sorry about that

**Comment by tpieco** [comment]
lol. No probs.

**Comment by canonex** [comment]
Why in some screenshot PrepareDenseScene has 2 output and in some images 1?
The same for Texturing? I can't reproduce exactly the node setup in [Projected Light Patterns](https://github.com/alicevision/meshroom/wiki/Projected-Light-Patterns)...

I have also trouble because of this:
https://github.com/alicevision/meshroom/issues/614#issuecomment-576946800
as I have commented, the node is causing error

Here is my setup:
![PrepareDense](https://user-images.githubusercontent.com/1444378/73034678-e1ca0480-3e45-11ea-8087-959310b808a0.jpg)

Thank you,
Riccardo

**Comment by natowi** [comment]
Sorry, the screenshot was taken in a previous version. I will update the wiki shortly

**Comment by canonex** [comment]
I made the stupid mistake of not renaming the files correctly...
the bold text in the wiki helped me.

Thank you,
Riccardo

**Comment by hargrovecompany** [comment]
Here's another set of images of a test subject (real American Rodeo Cowboy)
I checked to make certain that it's correct....a set with pattern projection and a set with normal lighting, .35 seconds between
https://www.dropbox.com/sh/rbegeqgihpp6xwj/AAAWZFLvBCG5PlPIk059vVJpa?dl=0

**Comment by natowi** [comment]
@tpieco can you share your results with your polarised and unpolarized photos like you did [before](https://github.com/alicevision/meshroom/issues/763#issuecomment-576322981)?
I would like to add the comparison to the wiki/documentation.

**Comment by tpieco** [comment]
@natowi here are some screenshots but I'm not sure if they're going to be useful.

The first screenshot is the result of using cross polarized photos.

The second screenshot is the result using unpolarized photos, which surprisingly gives a better mesh than polarized photos.

The third screenshot is the result of using polarized photos, with unpolarized photos used for texturing without adding a new PrepareDenseScene node.

![polarized](https://user-images.githubusercontent.com/49287303/74111746-e2290600-4b8e-11ea-9120-9bb34caf1da6.jpg)
![unpolarized](https://user-images.githubusercontent.com/49287303/74111759-f10fb880-4b8e-11ea-99bb-83c6ea9c9ca5.jpg)
![combined](https://user-images.githubusercontent.com/49287303/74111764-fec53e00-4b8e-11ea-93e5-9fd0e32d7554.jpg)

**Comment by natowi** [comment]
@tpieco Thank you for this nice example. 
I see you have a red icon on your images that point to [missing metadata or sensor information](https://github.com/alicevision/meshroom/wiki/Add-Camera-to-database). Meshroom does a good estimation job, but adding this information can improve the overall accuracy.

**Comment by tpieco** [comment]
@natowi No problem. I shoot RAW photos and export them to PNGs using Capture One, which doesn't include the EXIF data. However I work out the correct FoV using an online calculator. Thanks for the lookout though.

**Comment by natowi** [comment]
Solved and added to the wiki.
