### ISSUE TITLE
[question] Importing Real Laser Depth Data

### ISSUE THREAD

**Issue by flolu** [alicevision/meshroom#764]
**Describe the problem**
I was wondering if it is possible to feed Meshroom with laser data? I've seen [this](https://youtu.be/M6Uf8kjfbSA?t=177) video where they were using **Laser** in combination with photo scanning, and they've got really good results.
But I also don't know which hardware is required for capturing real depth information with the help of a laser or something similar.

Is there already such a feature in Meshroom?
Which Hardware would I need?

**Video**
https://youtu.be/M6Uf8kjfbSA?t=177

**Additional context**
Maybe someone could point me in the right direction.

**Comment by natowi** [comment]
No, at the moment there is no such feature in Meshroom. (But there is a draft in a private repository for this based on PCL)

Cloud Compare (or Meshlab) could be used to align the point cloud ply created in the meshing node with laser scan. In Meshlab you could then create the mesh from the point cloud and do the texturing back in Meshroom. https://github.com/alicevision/meshroom/wiki/Texturing-after-external-re-topology

Laser scanners are expensive. There are 2D laser scanners starting at 80$ like a Slamtec RPLIDAR A1, but 3d scanners start at 2500$. 

Depth cameras like the Kinect would be cheaper, but Meshroom does not yet support them https://github.com/alicevision/meshroom/issues/255

Another way to improve accuracy would be using [projected light patterns](https://github.com/alicevision/meshroom/wiki/Projected-Light-Patterns), but this is not suitable for outdoor usage.

**Comment by natowi** [comment]
This issue is solved and closed due to inactivity. Feel free to re-open if new information is available.

**Comment by remmel** [comment]
If for each laser depth data you have an image, you could try to improve each exr files generated by Meshroom with you depth data..
As I have the same needs (Use the Kinect v1 depth data or use the tof images from my [Honor View 20](https://github.com/remmel/hms-AREngine-demo)) I'll try to read and improve exr files and I'll also try to do it on [OpenMVS](https://github.com/cdcseacave/openMVS/wiki/Usage#dense-point-cloud-reconstruction-using-available-depth-maps-optional)
Main avantage of mixing tof images with photogrammetry depth maps is that tof could be more precise and consume less time, but photogrammetry depth maps "see" dark surfaces

**Comment by mellinger** [comment]
@remmel Were you able to try this with OpenMVS? I couldn't figure out how to manually import those depth maps.

**Comment by remmel** [comment]
@mellinger I have not done anything with OpenMVS yet

**Comment by bednarhonza** [comment]
Hello everyone, I have noticed that the PR [#425](https://github.com/alicevision/AliceVision/pull/425) has been merged. Is it already in some working phase, or is still a development needed to use it?

Thanks for the great work!

**Comment by natowi** [comment]
@bednarhonza https://github.com/alicevision/AliceVision/pull/1441 it is on the milestone list for the next release https://github.com/alicevision/AliceVision/milestone/35
