### ISSUE TITLE
[question] Best settings for light field data?

### ISSUE THREAD

**Issue by ichlubna** [alicevision/meshroom#765]
Hi I want to use the 3D reconstruction on light field data (grid of cameras pointing the same direction). The process however fails at SfM with `Initialization failed after trying all possible initial image pairs.`. Could you please recommend me what parameters to change when dealing with such data?

[Here](http://lightfield.stanford.edu/lfs.html) is the dataset. I've already tried the default settings and the recommendations [here](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters). I also read [this](https://github.com/alicevision/meshroom/wiki/Large-scale-dataset) and I assume that due to the nature of the data the images are having good connections but which parameters exactly should be more strict?

Thanks and have a nice day!

**Comment by natowi** [comment]
What dataset are you using (there are multiple)? What are you trying to achieve? (Why use a camera grid dataset?)

**Comment by ichlubna** [comment]
Hmm I see, thanks for trying too. I tried the first two ones Chess and Lego Bulldozer and failed there. Are you using default parameters? The camera grid is the common light field representation, just doing some experiments with this kind of data.

**Comment by natowi** [comment]
> Chess and Lego Bulldozer and failed there

You picked the most difficult datasets ;)

Highly reflective and single coloured surfaces are difficult to reconstruct.

**Comment by ichlubna** [comment]
Yea I know they are not ideal. Just was wondering if the params can be adjusted to it produces something at least.

**Comment by natowi** [comment]
Are you interested in camera grids or do you just want to test some datasets ([here are some more suitable ones](https://github.com/natowi/photogrammetry_datasets))?

**Comment by ichlubna** [comment]
No I am not looking for datasets but thanks. Just wanted to try these data. I guess that nothing can be done about the ones I mentioned. I'll maybe work with the bunny instead or something more diffuse.

**Comment by natowi** [comment]
When I have some time I´ll give one of the difficult datasets a try, looks interesting :)

**Comment by ichlubna** [comment]
Thanks! Please let me know if you find a usable configuration. I've tried the methods mentioned above and probably will play for a while with it but maybe the scene is simply too bad for the reconstruction.

**Comment by natowi** [comment]
It is generally possible to capture scenes like the chessboard and compute them in Meshroom, but it requires a setup that is optimized for photogrammetry (using polarized filter and optimized lighting).
But I am curious of what can be done with this dataset.

**Comment by natowi** [comment]
Chess board dataset with 12 images only (with some space in between), default graph, + AKAZE settings
-> SfM works, error in Meshing node.

**Comment by ichlubna** [comment]
Is it better to remove some images in between for better results when having this dense dataset?

**Comment by natowi** [comment]
No, just to reduce computation time

**Comment by ichlubna** [comment]
Hmm so you just added akaze and it works? Maybe the image reduction actually did something :D
