### ISSUE TITLE
[question] Aicon scanner

### ISSUE THREAD

**Issue by flu60** [alicevision/meshroom#771]
Ich erstelle ein Projekt mit Aicon. Daraus kann ich die Orientierung der Bilder exportieren und danach in Agisoft importieren. Das Ergebnis des Scans ist dann richtig skaliert und liegt vom Ursprung her gleich wie das Originalprojekt. Ist dieses in Meshroom auch möglich?

**Comment by natowi** [comment]
[Welches Aicon Produkt wird verwendet](https://www.hexagonmi.com/products/white-light-scanner-systems)? Bilder _ohne_ Projektion/Laserlinie können in Meshroom geladen und verwendet werden.
Für Structured Light oder Laser gibt es andere Open Source Projekte. Warum nicht die Herstellersoftware für den Scanner verwenden?

**Comment by natowi** [comment]
[Welches Aicon Produkt wird verwendet](https://www.hexagonmi.com/products/white-light-scanner-systems)?

Bilder _ohne_ Projektion/Laserlinie können einfach in Meshroom geladen und verwendet werden. Wenn ein zufälliges Muster auf die Oberfläche projiziert werden kann, kann es auch verwendet werden.

Für Structured Light oder Laser gibt es andere Open Source Projekte. 

Meshroom unterstützt noch keine direkte Skalierung und Orientierung ohne zusätzliche Marker.

**Comment by flu60** [comment]
We are using DPA profesional and we are not scanning.
Aicon can give us the orientation of the camera positions X;Y;Z;omega;phi;kappa
What are aditional marker? Meshroom does not see oure glued points
In StructureFromMotion must be a file with the orientation of the cameras
Here an example:
![grafik](https://user-images.githubusercontent.com/60324056/73180258-4078d200-4115-11ea-9848-bddd7249bbfd.png)

**Comment by natowi** [comment]
Yes, it is possible to use known camera positions, but you need to write your own script to convert your table to the Meshroom format. Read #399, #740, #453, #475 and #300 for details.

>  What are aditional marker? Meshroom does not see oure glued points

I think the Aicon DPA profesional uses Agisoft Markers.
At the moment Meshroom only supports CCTAG markers that can be used for rescaling.
