### ISSUE TITLE
Axial Analysis - Step Depth Working but Integration is Not

### ISSUE THREAD

**Issue by MSteer1** [alicevision/meshroom#772]
Hi everyone, 

I'm having an battle with the software when trying to perform axial analysis at the moment. For some reason, step depth analysis is working perfectly but integration analysis isn't (everything appears red/orange). 

Previously both integration and step-depth analysis were both working, but updates to the map have broken things.

Does anyone know what may be causing this?

Many thanks in advance, 

Michael

**Comment by natowi** [comment]
Sorry, but I do not understand what you are doing. Can you explain what you are trying to achieve?
