### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by velazguez** [alicevision/meshroom#773]
Can you add the Xiaomi Redmi Note 8 Camera sensor

**Comment by natowi** [comment]
I was only able to find information on the main camera (!): Samsung [ISOCELL Bright GM2](https://www.samsung.com/semiconductor/minisite/isocell/mobile-image-sensors/isocell-bright-gm2/) sensor, 1/2.25", 0.8µm pixels
The [calculated value](https://www.vision-doctor.com/en/camera-calculations/sensor-diagonal-sensor-ratio.html) based on resolution (8000x6000) and pixel size (0.8µm) is 4.8
So ([depending on the exif data](https://github.com/alicevision/meshroom/wiki/Add-Camera-to-database)) try something like:

`Xiaomi;Redmi Note 8;4.8;`

If this works for you, it can be added to our database.

**Comment by velazguez** [comment]
Can I do it with the rx470 graphics card

**Comment by velazguez** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/25870387/73470974-be4d0f80-4399-11ea-868b-cffdc38cf15d.png)

**Comment by natowi** [comment]
At the moment you can use his workaround https://github.com/alicevision/meshroom/wiki/Draft-Meshing, as the depth map node requires a cuda gpu.

**Comment by velazguez** [comment]
![help](https://user-images.githubusercontent.com/25870387/73484680-cc5b5a00-43b2-11ea-87e8-a605418e3c29.png)

**Comment by natowi** [comment]
What is the output of the error log?

**Comment by velazguez** [comment]
where do we get the output

**Comment by natowi** [comment]
Node Properties -> Log tab
