### ISSUE TITLE
How to get more detailed meshes without increasing max. points[question]

### ISSUE THREAD

**Issue by strike-digital** [alicevision/meshroom#775]
In many other photogrammetry programmes, it is possible to generate millions of polygons from relatively few images, while in meshroom, the maximum I can achieve is 1mil per scan. I assume this is because I have to set the max. points setting in meshing to 1.5mil due to RAM limitations but I am wondering whether it is possible to increase the detail without using all of my RAM. This probably isn't possible, but it would be good to know.
I'm on Windows 10 using the release version of meshroom and I'm not sure what my python version is

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters

I am wondering whether it is possible to increase the detail without using all of my RAM.

Depends on how much RAM you have, it is also project specific. 
To get a scan with a higher resolution you need to increase the reconstruction parameters which requires more RAM and computation power.
