### ISSUE TITLE
Error at PrepareDenseScene

### ISSUE THREAD

**Issue by eviltartetatin** [alicevision/meshroom#776]
Hey, I'm trying to do a 3D model from a video sequence but keep on getting stuck on the PrepareDenseScene. Do you have any suggestions on what I could do to make it work again? I run Meshroom on a PC.

{
    "status": "ERROR",
    "execMode": "LOCAL",
    "nodeName": "PrepareDenseScene_1",
    "nodeType": "PrepareDenseScene",
    "packageName": "aliceVision",
    "packageVersion": null,
    "graph": "",
    "commandLine": "aliceVision_prepareDenseScene  --input \"C:/KUNST/2019 \u2013 Flight Characteristics - Dresden/Material/Meshroom/MeshroomCache/StructureFromMotion/c856200acbe92f16d9a6810dffbfdb0baeafacf9/sfm.abc\" --outputFileType exr --saveMetadata True --saveMatricesTxtFiles False --evCorrection False --verboseLevel info --output \"C:/KUNST/2019 \u2013 Flight Characteristics - Dresden/Material/Meshroom/MeshroomCache/PrepareDenseScene/2d12a014a7ed10f2d4052ae029c29a3a47187ea4\" --rangeStart 0 --rangeSize 40",
    "env": null,
    "startDateTime": "2020-02-03 15:38:13.733032",
    "endDateTime": "",
    "elapsedTime": 0,
    "hostname": "DESKTOP-HC4Q1V5",
    "sessionUid": "fcb5ea5c-4682-11ea-8f1d-04d9f5f73156",
    "returnCode": 3221226505,
    "elapsedTimeStr": "0:00:00"
}

**Comment by fabiencastan** [comment]
This node does not support non-ascii characters.

**Comment by eviltartetatin** [comment]
Yeah, I had read something similar shortly after posting, so I tried renaming the folder and it worked. Thanks for your quick reply!
