### ISSUE TITLE
Screen displaying white after power outage

### ISSUE THREAD

**Issue by jackcrane** [alicevision/meshroom#779]
In the midst of a reconstruction, my house lost our power, thus my computer stopped. Once the power was restored, I rebooted everything and it was fine. Then I loaded in Meshroom. The console showed fine, then the UI popped up and showed a white window, and nothing more. As I moved my cursor around, I found that it would still show the cursor images that it is supposed to, just the white screen. I deleted everything and redownloaded it, and had the same problem.

Any help?

**Comment by natowi** [comment]
Sorry but there is not much we can help you with.

Remove the old installation and re-download the zip file and extract it to a folder.

Here are a few things you can try:

- make sure the downloaded Meshroom files are not corrupted (incomplete/interrupted download)

- you have to extract the archive and not just launch it from the zip viewer.

- avoid special characters/non-ASCII characters in Meshroom and images file paths

- make sure your antivirus program does not interfere with Meshroom

**Comment by MightyBOBcnc** [comment]
Does Meshroom store any data in C:\Users\YOURNAMEHERE\AppData\Local\Temp ?  If you're on Windows you might purge your temp files.  

Do you have any other 3D software that you use?  Are they all working fine? (Hope it's just a Meshroom issue and not GPU damage.)

**Comment by jackcrane** [comment]
I cleared the temp files and it seems to be working....

Thank you so much!
