### ISSUE TITLE
incrementalSfM has stopped working

### ISSUE THREAD

**Issue by Abolfazl-82** [alicevision/meshroom#781]
**Configuration**
Version 2019.2.0
Windows 10 
Python 3.6.6
![error](https://user-images.githubusercontent.com/60793466/74057684-b294c500-49f9-11ea-9a5b-bf4395451f2b.png)

Hi and thank you for your nice program.
What is the problem that has happened to me?

**Comment by natowi** [comment]
Does restarting Meshroom and opening your project resolve your problem?
Test Meshroom using this dataset: https://github.com/alicevision/dataset_monstree
when Meshroom still crashes, report back and add your computer hardware info (CPU, GPU, RAM).

**Comment by natowi** [comment]
This issue is closed due to inactivity. Feel free to re-open if new information is available.
