### ISSUE TITLE
[question] How to use known camera poses

### ISSUE THREAD

**Issue by Dave-van-der-Meer** [alicevision/meshroom#786]
**Describe the problem**
A clear and concise description of what the problem is.
I want to generate a 3D model of my environment. As the environment is rather difficult to scan, the result is not that good and the calculation of the camera position is really bad.

As I know the position of the camera for all pictures, I want to use this information. Therefore, I first run the different nodes until I reach the StructureFromMotion node. I run it and take the resulting cameras.sfm file and replace it with the file I generate myself. Then I continue the process with my own cameras.sfm file.

In the end, the result is exactly the same as with the original file. What am I doing wrong? How can I include the known poses of my cameras to generate a more accurate 3D model?

I already read all related issues but I can't figure it out.

**Desktop (please complete the following and other pertinent information):**
 - OS: Ubuntu 18.04
 - Python version: 2.7.17
 - Meshroom version: Meshroom-2019.2.0

**Comment by natowi** [comment]
Duplicate

**Comment by natowi** [comment]
@Cartucho no, https://github.com/alicevision/meshroom/issues/788#issuecomment-586650552
Feel free to open a new issue with a detailed description of your problem.
