### ISSUE TITLE
Meshroom shows runtime error (code 127) when running on google colab

### ISSUE THREAD

**Issue by soham0243** [alicevision/meshroom#789]
Hello,
      I am trying to use meshroom 2019.1.0 (I also tried 2019.2.0) on google colab. Unfortunatety when I am trying to unzip it showed me something like unable to create symlink for *.so files.
I tried to clone the github repository and build it but it showed error again while building/installing. I also modifed the path (export PATH=/path/to/*/aliceVision/bin/*:$PATH)
     Then I tried to run binary directly the compiled binary file but it showed runtime error 127. 
I tried the following link [Not able to install meshroom 2019.2.0 on google colab #735](https://github.com/alicevision/meshroom/issues/735)
and [this solution](https://gist.github.com/natowi/3044484ad0c98877692c399297e3ab7e) .
     Unfortunately nothing solved my problem.
My ipynb file : [untitled0.ipynb](https://colab.research.google.com/gist/soham0243/b0affda78a0d3fa862790bfc26881b67/untitled0.ipynb)
       Thanks in advance.

**Comment by natowi** [comment]
Since so many people have this problem I will update the notebook within the next days.
