### ISSUE TITLE
[question] Missing camera  OnePlus 7T PRO in cameraSensors.db

### ISSUE THREAD

**Issue by geek111** [alicevision/meshroom#792]
Hello
I want to add entry OnePlus 7T PRO in cameraSensors.db but I can't find what is sensorWidth :( 
Can you tell me where I can find? :D Thanks

**Comment by natowi** [comment]
Google "oneplus 7t pro camera sensor" -> [IMX586](https://en.wikipedia.org/wiki/Exmor) -> [1/2"](https://www.digicamdb.com/sensor-sizes/) -> 6.4

OnePlus;OnePlus 7T PRO;6.4;usercontribution

https://github.com/alicevision/meshroom/wiki/Add-Camera-to-database

You may need to modify the model name to match the image metadata.

**Comment by geek111** [comment]
Thanks <3 :)

**Comment by geek111** [comment]
Thanks again it works :D I add this line in github cameraSensors.db :) 
Correct entry is: 

> OnePlus;OnePlus HD1913;6.4;usercontribution
