### ISSUE TITLE
Cuda not detected

### ISSUE THREAD

**Issue by jacknjackson** [alicevision/meshroom#793]
I am running Meshroom 2019.2.0 on Quadro K1200 with 512 cuda cores on Windows 10. The driver is version 441.12

The Depth Map log file reads:
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "C:/Users/Jack Koehler/Desktop/Orthotic photos/MeshroomCache/PrepareDenseScene/e434858e80bb82dc2f2a8216b74b0452c826abd3"
 * input = "C:/Users/Jack Koehler/Desktop/Orthotic photos/MeshroomCache/StructureFromMotion/de7345fc33e711f9fa10c191a2746a700a536492/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/Users/Jack Koehler/Desktop/Orthotic photos/MeshroomCache/DepthMap/efd3d07c44c9813e035eaa97fc9c8c965edb4533"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[10:49:30.607334][warning] Could not determine number of CUDA cards in this system
[10:49:30.606335][warning] No CUDA-Enabled GPU.
[10:49:30.607334][error] cudaGetDeviceCount failed: CUDA driver version is insufficient for CUDA runtime version
[10:49:30.608333][info] Can't find CUDA-Enabled GPU.
[10:49:30.608333][error] This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0).

Any help would be appreciated.

Thank you,
Jack

**Comment by natowi** [comment]
Your nvidia driver is not installed properly. Uninstall the current driver and install [the latest version](https://www.nvidia.com/Download/driverResults.aspx/156767/en-us)

Similar issues: #182 #197 #203

**Comment by jacknjackson** [comment]
Solved.
I updated the driver to version 442.19. Meshroom continued to report the same error, no Cuda.
The issue  was resolved using the NVIDia Control Center. In the left panel find 3D Settings / Manage 3D Settings. In the right panel use the Program Setting Tab to Add Meshroom. In the Feature List set CUDA - GPUs to All.

**Comment by JOSEBCDEF** [comment]
Thanks Jacknjackson that did the trick! As I already spent days getting cuda installed and active it was a joy to find a quick and easy solution to the last obstacle!
