### ISSUE TITLE
can we input gcp(ground control point) / georeferencing ?

### ISSUE THREAD

**Issue by fatchurrwp** [alicevision/meshroom#794]
**Describe the problem**
A clear and concise description of what the problem is.

**Screenshots**

**Dataset**
If applicable, add a link or *few* images to help better understand where the problem may come from.

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ]
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1]
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**

**Comment by natowi** [comment]
No, this is not yet supported.
