### ISSUE TITLE
Please see if this image imports

### ISSUE THREAD

**Issue by Chris-Clawson** [alicevision/meshroom#797]
I am unable to directly import raw DNG files to Meshroom, from my Mavic drone. The 'drag and drop' just doesn't complete and no error is reported. Below is a sample image. Might you comment, please? I tried this in both Windows 10 and Ubuntu, with Meshroom 2019.2.0.

[DJI_0007.zip](https://github.com/alicevision/meshroom/files/4241441/DJI_0007.zip)

**Comment by natowi** [comment]
Many drone cameras create invalid EXIF fields that are not supported. https://github.com/alicevision/meshroom/wiki/Images-cannot-be-imported Convert your images to '.jpg', '.jpeg', '.tif', '.tiff' or '.png'.

**Comment by Chris-Clawson** [comment]
Thanks for the quick reply. Raw images offer more possibilities. GPS metadata and other info get deleted or modified. Conversion to 48 bit color tiffs, png, etc., produce much larger file sizes.

Down the road, it would be great if Meshroom/Alicevision just ignored invalid fields. For now, I will continue using drone produced jpg images, and enjoy the benefit of the native metadata.

**Comment by Fastfingered** [comment]
Same issue here, having to convert all the RAW DNG images to JPEG (Using Lightroom C) while loosing some dynamic range and having to import them again is a bit tedious and time/space consuming. I would really like if we get the option to directly import the DNG files out of DJI drones.

**Comment by natowi** [comment]
The next release will update the supported image formats

**Comment by natowi** [comment]
This should be resolved with the 2020 release.
