### ISSUE TITLE
[question] Adding metadata 

### ISSUE THREAD

**Issue by Eulmiac** [alicevision/meshroom#802]
Hi,
I used ExiftoolGUI to add metadata to my set of pictures (coming from a video converted in png sequence). Unfortunatly, it seems that Meshroom doesn't recognize it since it tells me "Camera Intrinsics: unknown".

I'd like to use the plugin Meshroom2Blender - https://github.com/tibicen/meshroom2blender - but I got an error at the import.

![01](https://user-images.githubusercontent.com/61442500/75217755-f3187080-5765-11ea-94c3-fb7741be7842.jpg)

![02](https://user-images.githubusercontent.com/61442500/75218022-e5afb600-5766-11ea-9d05-b55b0dfb338b.jpg)

![03](https://user-images.githubusercontent.com/61442500/75218024-e8aaa680-5766-11ea-8ece-4605ba17ba01.jpg)

**Thanks for your help !**

**Comment by fabiencastan** [comment]
You can use the KeyframeExtraction node with uniform sampling to extract images from your video and set the camera metadata in the node.
