### ISSUE TITLE
How to get normal information of point clouds?

### ISSUE THREAD

**Issue by bgpantojar** [alicevision/meshroom#804]
Hello,

When I export the sparse point cloud as .ply using converSfMformat node, the file contain information about the coordinates and rgb colors. I need the file contain the normal information instead of the colors. is there some way to get that?

**Comment by natowi** [comment]
As far as I know, this is not supported in Meshroom, but you can estimate the normals using Meshlab https://www.youtube.com/watch?v=kVGENYi4gz8
