### ISSUE TITLE
Reconstruction Time

### ISSUE THREAD

**Issue by Vekolb** [alicevision/meshroom#806]
I am wondering if there is some place where one can estimate reconstruction time? 

I have a datasett of 1021 images where it has 1000 cameras. And now the depthmap has been running for almost 24 hours and its almost done seems to be at something that looks like 90-95% on the green bar. Is this normal?

My system is an Dell XPS15 9550 with
- i7 processor
- 16gb memory
- gtx960m card with integrated Intel 530

Also would i benefit much from upgrading to 32gb of memory? Or will something else be the bittleneck? 

At office I have a razer core x chroma with a gtx1060 6GB card not sure if it would help much on running it there instead, as it seems I have to let it run for such a long time anyway.

**Comment by natowi** [comment]
You can roughly calculate with 30s-60s per image with default settings.
The actual time is difficult to calculate as it depends on multiple factors, as image size, quality of the dataset, reconstruction settings and hardware.

**Comment by Vekolb** [comment]
Depth map have taken about 24h in my case, it didnt crash this time after I changes the TDR. And now its doing depth map filter. And that is about 50% after about 2 hours.

Safe to say this reconstruction is taking its time. 

Will upgrading from 16gb to 32gb ram help or is the bottleneck some where else?

**Comment by gryan315** [comment]
Feature extraction uses a lot of RAM. If you watch your system resources on that step, it will slowly climb up to using around 80% of your memory, then drop off, and repeat this process until it's done. If you have enough RAM, it will only have to do that ramp-up once. This is just from my observation from a small image set, I am not sure how much the other nodes are affected by RAM.

**Comment by Vekolb** [comment]
Thanks for great feedback. It seems to go better on the meshing etc. Its now on "Texturing" and the green bar has been at the end for a long time. It keeps going trough images in the log, but once done it starts all over. Only change is that "Texture file" now says 3. What is this?

**Comment by Vekolb** [comment]
From my calculation Texturing will take 34-36hours. Is there a way to speed this up without having to sacrifice to much?

**Comment by gryan315** [comment]
Which unwrap method did you select? If you chose LSCM to get a simpler texture file, it takes significantly longer than the basic unwrap. I just tested RAM usage for texturing. On a 300 image dataset at 1080p-ish resolution, I saw 11gb of memory usage on default texture side with 2 downscale. Reducing side to 2048 with 2 downscale saw 9gb of usage. Processing time was virtually the same for the basic unwrap method on both. A 4x downscale netted a very small speed-up, but drastically reduced the quality of the texture. 

The settings I normally use are 4096 side with 2 downscale, and LSCM unwrap for the simpler texture file. Through this testing, I noticed that LSCM seems to only use 1 CPU core, and also only 5.5gb of RAM for this dataset. I believe this is why I wasn't seeing significant memory usage during benchmarking. Overall, LSCM took 8.5 times longer than basic with this image set. Based on this, I would expect that to maximize speed, you would want lower resolution input images and more system memory, while using the basic unwrap method.

**Comment by Vekolb** [comment]
The dataset is 1012 images. I have tried all setting Texture side from 8k down to 1k but its not much difference, give or take a few hours. I also tried Texture downscale between 1-4 bit again no big difference. Like 8k 1 downscale is 34-36h. 1k and 4 downscale was 19h.
I also tried jpg and png and that didnt matter much either. 
Unwrap is set to basic on all. And other settings would just make this take even more time. 

Maybe I need to take 5 steps back and Split this dataset into several pieces and redo the whole thing. But I already spent 3 days doing this reconstruction. I might just wait for the weekend and let the laptop run for 40h with good settings.

**Comment by gryan315** [comment]
What resolution are your images? Maybe you could also decimate your mesh? I was able to shave off about 25% texturing time by decimating the 300 image set with the default .5 simplification factor. Are you using windows? I've noticed significant performance improvements by switching my workstation to linux, with an overall reduction in time of 20%, and a reduction in guided matching time of 30%.

A laptop just may not have the power needed for this kind of task with large photo sets, since even the highest spec mobile i7 will still only be around 40-50w. I'm currently setting up my photogrammetry workstation that I built from used parts for remote use, so I can remote into it, download my photos, then start processing from anywhere. 

You could also try setting up a cloud compute solution, either with GCP, AWS, azure, or paperspace. I haven't tested this myself, but seeing as how the high end tesla GPUs are more geared towards machine learning, based on their specs on paper, I wouldn't expect them to outperform a 1080 ti by a whole lot in meshroom due to their lower clock.

**Comment by Vekolb** [comment]
You probably right in a lot here. I have mesh decimated it a lot down to 250k verticies and still its 10h. But hey I can at least look how it kind of looks like and run a full in the weekend.
I do notice that Texture is using lots of ram so maybe upgrading from 16gb 2133mhz to 32gb 2400mhz might help as the cpu doesnt seem to run constant on 100%
And that upgrade isnt that expensive either.

**Comment by natowi** [comment]
PR https://github.com/alicevision/meshroom/pull/842
