### ISSUE TITLE
MeshResampling vs MeshDecimate

### ISSUE THREAD

**Issue by Vekolb** [alicevision/meshroom#809]
I am new to this and in the search to optimize reconstruction process I am having a hard time figuring out the difference between MeshResampling and MeshDecimate tool. They both seem to do much the same.
I did read this: 
https://meshroom-manual.readthedocs.io/en/latest/node-reference/nodes/MeshResampling.html

But it doesnt say much. Anyone have an example of the difference when say use 0.5 ratio on both. Which will you use for what?

**Comment by fabiencastan** [comment]
MeshDecimate kills vertices to reduce the density, so the vertices at the end already exist in the original mesh.
MeshResampling will recreate vertices on the surface with a uniform density, so there is no common vertice with the original mesh.

**Comment by Vekolb** [comment]
> MeshDecimate kills vertices to reduce the density, so the vertices at the end already exist in the original mesh.
> MeshResampling will recreate vertices on the surface with a uniform density, so there is no common vertice with the original mesh.

Could you elaborate more on this for a newbie? When will you use what? Are there some cases where one is better than the other? How will it affect the result?

**Comment by natowi** [comment]
![gif](https://user-images.githubusercontent.com/8138537/75572018-a8933e80-5a5a-11ea-89e0-ed08ef47b93f.gif)
