### ISSUE TITLE
WARNING:root:QGLXContext

### ISSUE THREAD

**Issue by bgpantojar** [alicevision/meshroom#810]
I am just trying to run Meshroom in a new computer and the opening is aborted with a message.

WARNING:root:QGLXContext: Failed to create dummy context

![Screenshot from 2020-02-27 15-01-47](https://user-images.githubusercontent.com/35929939/75452349-6ee70880-5972-11ea-8ac1-553e70272081.png)

Could you help me please solving this?

**Comment by gryan315** [comment]
I am very much not an expert, and a complete beginner in linux, but this looks like maybe an OS level QT dependency/version problem?

**Comment by natowi** [comment]
Try re-installing the dependencies

**Comment by bgpantojar** [comment]
Thanks!.. re-installing worked
