### ISSUE TITLE
StructureFromKnownPoses node doesn't show up

### ISSUE THREAD

**Issue by Dave-van-der-Meer** [alicevision/meshroom#811]
**Describe the bug**
StructureFromKnownPoses node doesn't show up when right clicking in the node editor window.

**To Reproduce**
I downloaded the StructureFromKnownPoses.py file and placed it inside the lib/meshroom/nodes/aliceVision folder. When I start the program, the node does not show up when I right click on the node editor. I tried making the .py file executable but it doesn't change anything.

**Expected behavior**
I expect the StructureFromKnownPoses node to show up in the list of the nodes when right clicking on the node editor but it doesn't.

**Desktop:**
 - OS: Ubuntu 18.04
 - Python version 2.7
 - Meshroom version: Meshroom version: Meshroom-2019.2.0 (binary version)

**Additional context**
I realize that all of the files inside the lib/meshroom/nodes/aliceVision folder are .pyc files and the added file is a .py file. Do I need to make a .pyc file out of it? How do I do this?
I followed the instructions from this site: https://github.com/natowi/meshroom_external_plugins

**Comment by natowi** [comment]
StructureFromKnownPoses  is experimental as is creating your own sfm files.

> I realize that all of the files inside the lib/meshroom/nodes/aliceVision folder are .pyc files and the added file is a .py file. Do I need to make a .pyc file out of it? How do I do this?

The pyc files are generated in the `__pycache__` folder when starting Meshroom. I am running windows and python 3.6. I did not try this on ubuntu or with linux binaries.

You can test this:
[StructureFromKnownPoses.zip](https://github.com/alicevision/meshroom/files/4266323/StructureFromKnownPoses.zip)

**Comment by Dave-van-der-Meer** [comment]
Okay, when I placed the StructureFromKnownPoses.pyc file inside the lib/meshroom/nodes/aliceVision folder in Windows 10 it shows up and it executes.
