### ISSUE TITLE
What is wrong here?

### ISSUE THREAD

**Issue by Vekolb** [alicevision/meshroom#812]
I am trying to learn meshroom and have tried some smaller sessions to see how things work. And then I tried scanning a speaker. But the walls which I guessed was going to be easy to capture did not.

![Example1](https://user-images.githubusercontent.com/61388851/75604173-5f80d000-5ad6-11ea-9d1e-e37f1798d892.jpg)

66 images and 66 cameras
Settings that was changed from default:

FE: Describer Preset: High
FM: Guided Matching Checked
DM: Downscale: 1

**Comment by natowi** [comment]
Featureless and reflective surfaces are difficult to reconstruct

**Comment by Vekolb** [comment]
> surfaces

So how can I do this better? Is there a setting I can run? Or do I need more pictures? I took 66 images of this and should be enough?

**Comment by natowi** [comment]
You could tape some flat newspaper sheets to the box walls. This will add more detectable features to the surface. Of course you would need to replace this part of the texture later.

**Comment by vichug** [comment]
isn't this a case of photogrammetry beeing tricked by visual illusion ? :D

**Comment by Vekolb** [comment]
I just installed a trial of Agisoft and that did the wall with default settings. So I guess is should work by adjusting some settings.

**Comment by natowi** [comment]
You can create node variations to compare different settings https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters. But without enough detected features the walls can not be reconstructed.
Agisoft probably uses a combination of multiple algorithms to improve the reconstruction.
