### ISSUE TITLE
[question] combine different camera specs

### ISSUE THREAD

**Issue by nafergo** [alicevision/meshroom#816]
Is it possible to combine photos from different cameras in the same reconstruction?
I'm thinking about drone+dslr+smartphone or some combination of these.

**Comment by natowi** [comment]
Yes, but you need to check in the cameraInit node that they are recognized as different cameras.

**Comment by nafergo** [comment]
wow thanks for fast reply :) 
Should I do something manually (like adding viewpoint or intrinsics or...) in advance or with correct photos metadata that should be automagically done by meshroom?

**Comment by natowi** [comment]
with correct photos metadata that should be automagically done by meshroom
