### ISSUE TITLE
[question] OCV options dont work...?

### ISSUE THREAD

**Issue by Fennecai** [alicevision/meshroom#818]
**Describe the problem**
when i use the "sift_ocv" or "akaze_ocv" options, it fails. idk why.

**Screenshots**
![image](https://user-images.githubusercontent.com/10889213/76154992-f46d6580-60a2-11ea-9cfc-7b3230740fa9.png)
![image](https://user-images.githubusercontent.com/10889213/76155022-870e0480-60a3-11ea-8ca0-e062e76c44e3.png)
![image](https://user-images.githubusercontent.com/10889213/76155026-8ffed600-60a3-11ea-8420-e10d6db11451.png)
![image](https://user-images.githubusercontent.com/10889213/76155032-ae64d180-60a3-11ea-92e5-6a8db3c779ce.png)

**Log**
Program called with the following parameters:
 * featuresFolders =  = [C:/Users/aekna/AppData/Local/Temp/MeshroomCache/FeatureExtraction/3ab8d5e64770c0f8729d408c1e1d2fe91ca2224d]
 * input = "C:/Users/aekna/AppData/Local/Temp/MeshroomCache/CameraInit/f3628da78c2ee742154e6f6be1461039de630246/cameraInit.sfm"
 * matchingMode = "a/a" (default)
 * maxDescriptors = 500
 * minNbImages = 200
 * nbMatches = 50
 * output = "C:/Users/aekna/AppData/Local/Temp/MeshroomCache/ImageMatching/e24004f4a25550044dde040c291121f8b96f8eae/imageMatches.txt"
 * outputCombinedSfM = "" (default)
 * tree = "I:\Tools\creation\asset creation\Meshroom-2019.2.0\aliceVision\share\aliceVision\vlfeat_K80L3.SIFT.tree"
 * verboseLevel = "trace"
 * weights = ""

[18:37:51.731946][trace] 0 extrinsics declared and 8 extrinsics used.

**Desktop (please complete the following and other pertinent information):**
 - OS: windows 10
 - Python version: i think i have multiple, i dont know
 - Qt/PySide version: i dont know
 - Meshroom version: 2019.2.10

**Comment by natowi** [comment]
You need to keep sift enabled and also use the same describer types in all the nodes.

**Comment by Fennecai** [comment]
that advice doesnt help. it still fails when i follow that advice.

**Comment by natowi** [comment]
Use [this dataset](https://github.com/alicevision/dataset_monstree) for testing and enable sift+sift_ocv  in the FeatureExtraction, FeatureMatching and StructureFromMotion nodes.

**Comment by natowi** [comment]
Now Meshroom does not work with ocv for me, too. Maybe this has something to do with windows updates / nvidia driver updates?

**Comment by natowi** [comment]
From the alicevision cmake:

> Since OpenCV 3, SIFT is no longer in the default modules. See
> https://github.com/itseez/opencv_contrib for more informations.
> Enable this to be able to use OpenCV SIFT in main_ComputeFeatures_OpenCV.
> option(ALICEVISION_USE_OCVSIFT "Add or not OpenCV SIFT in available features" OFF)

But since the patent expired this month, it should be activated by default soon.
