### ISSUE TITLE
[question] "aliceVision" plugins / SketchfabUpload: cannot import name 'idnadata'

### ISSUE THREAD

**Issue by natowi** [alicevision/meshroom#820]
**Describe the problem**

When I build Meshroom and run the exe, the CLI window does not show loaded plugins (but all nodes not listed work as expected)

```
WARNING:root:== The following "aliceVision" plugins could not be loaded ==
  * SketchfabUpload: cannot import name 'idnadata'

WARNING:root:== The following "submitters" plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'
```

The SketchfabUpload warning is not expected. What could be the cause of this error?

OS: Win10

**Comment by ChemicalXandco** [comment]
Seems to be the same problem as here: https://stackoverflow.com/q/45897252

It seems this module is not added automatically by cxfreeze

**Comment by natowi** [comment]
Thank you, I will look into this.

**Comment by ChemicalXandco** [comment]
I have added a commit in #783 which fixes this
