### ISSUE TITLE
[question] Store (x, y, z) of every point in every input image

### ISSUE THREAD

**Issue by Osamabu** [alicevision/meshroom#824]
I want to use meshroom to create a point cloud system.  I want also to store the mapping of each point in the images and where it maps in the point cloud.  This is basically the (x, y, z) coordinates of the matched point.  That is if an image point is (u, v), it corresponds to (x, y, z) in the point cloud.  Can I do that?
Thanks

**Comment by simogasp** [comment]
The output file of the Structure From Motion contains this information stored in `Observations`. This is a list of 3D points (of the cloud) and, for each of them, there is a list of 2D points indexed by the viewID which corresponds to the 2D feature point on that image.
You can extract the information from the sfm.abc you find on the node or, if you need a simpler format to process you can add a `ConvertSfMFormat` node to convert it:

![image](https://user-images.githubusercontent.com/1331744/76399156-7220c200-637e-11ea-8ec9-9b3fc730b6bf.png)

just select the format (eg json) in the combo box and run the node.

**Comment by Osamabu** [comment]
Thank you s o

> The output file of the Structure From Motion contains this information stored in `Observations`. This is a list of 3D points (of the cloud) and, for each of them, there is a list of 2D points indexed by the viewID which corresponds to the 2D feature point on that image.
> You can extract the information from the sfm.abc you find on the node or, if you need a simpler format to process you can add a `ConvertSfMFormat` node to convert it:
> 
> ![image](https://user-images.githubusercontent.com/1331744/76399156-7220c200-637e-11ea-8ec9-9b3fc730b6bf.png)
> 
> just select the format (eg json) in the combo box and run the node.

Thank you very much.  Is it possible to do this from command line too?  Thanks!

**Comment by natowi** [comment]
Yes

**Comment by simogasp** [comment]
if you mean Meshroom's command line, yes, but you need first to modify the graph as in the picture and then run only the node using `bin/meshroom_compute`.

You can do it also from the command line using the AliceVision binary with the same name, `aliceVision_convertSfMFormat` (.exe if u are on windoze).

**Comment by Osamabu** [comment]
Thank you.  This was very helpful.  One more question.  Are these absolute measurements or relative.  What I mean can I do distance measurements using these files?
Thanks

**Comment by natowi** [comment]
As far as I know, you need to scale the point cloud to a known scale first.

**Comment by lwndlnd** [comment]
Does anyone know how to do this for every 3D position instead of only the feature points? I've tried with the Dense SfM data but it does not give a meaningful value for the image point (u, v) (see https://github.com/alicevision/Meshroom/issues/1970)

**Comment by natowi** [comment]
@lwndlnd Does the ConvertSfMFormat node help? Structure should include depth information, using Image Whitelist you can even limit the images to export:
![grafik](https://github.com/alicevision/Meshroom/assets/8138537/501d0e54-b21f-4397-bf4d-bf9f6cac2fa2)

**Comment by lwndlnd** [comment]
@natowi Thanks for the response, the white list is actually very useful! I'm actually already using the ConvertSfMFormat node. My question is if this is also possible with the dense SfM data
![Screenshot from 2023-08-01 13-27-20](https://github.com/alicevision/Meshroom/assets/102163377/a4af83ea-14c0-4f0e-82f1-d4e7cc84911d)
It contains both the 3D and 2D points but the 2D points don't seem to make any sense:

![Screenshot from 2023-08-01 13-26-42](https://github.com/alicevision/Meshroom/assets/102163377/e613209c-78eb-4e98-98fd-6fcd2729f147)
Left is the SfMData directly from the structure from motion and right from the Meshing node

**Comment by natowi** [comment]
@lwndlnd you need to select the describer used before to include it in the output. In your case, select dspsift

**Comment by lwndlnd** [comment]
@natowi I set the describer type to dspsift in the first ConvertSfMFormat node. If I select dspsift in the second one after the meshing no observations are exported.
