### ISSUE TITLE
Image selection, without drag and drop

### ISSUE THREAD

**Issue by japrogramer** [alicevision/meshroom#825]
I'm on Linux and don't have a file manager that has drag and drop, because that's a silly feature.

I would like to be able to select the files from within the application in a dialog.

How can dragging and dropping be the only way to get images into meshroom.

**Comment by zachary-foster** [comment]
The drag and drop necessity does seem inconsistent with the rest of the software, which is quite sophisticated and flexible.

It would be nice if there was a node that you could type in a path to a folder and all the images in the folder are used. That way you could have multiple related but independent reconstructions in a single session. This might be useful if you wanted to compare the results different image transformations or have a "preview" pipeline alongside a computationally-intensive pipeline, for example. Also, if the path could be relative to the location of the saved meshroom file, it could be used in a template folder structure, which could aid in automation.

That being said, its a relatively minor issue, so if it would require a lot of work, I can understand if its not a priority. Meshroom is already awesome and I am really grateful for the developers making this open source and free.

**Comment by natowi** [comment]
This is already on the to do list https://github.com/alicevision/meshroom/wiki/Good-first-contributions
https://github.com/alicevision/meshroom/issues/461

> It would be nice if there was a node that you could type in a path to a folder and all the images in the folder are used.

There is the --imageFolder option that could be enabled in the node

> Also, if the path could be relative to the location of the saved meshroom file

https://github.com/alicevision/meshroom/issues/472

**Comment by natowi** [comment]
In the 2020 release you can now add images via File -> Import images
