### ISSUE TITLE
Incorporating Meshroom into other codes

### ISSUE THREAD

**Issue by ethansu1992** [alicevision/meshroom#826]
Hi i have been trying to conduct a 3D reconstruction, i have manage to generate point clouds but now i am facing an issue for texture mapping, may i ask if it is possible to import meshroom functions to my codes and run it like a library file?

**Comment by ChemicalXandco** [comment]
You can copy the 'meshroom' folder into the lib folder (`C:/Program Files/Python[X]/Lib` on windows) and then you can `import meshroom` in your code.

**Comment by ethansu1992** [comment]
Thank you so much for the help!  I have another question is that are there documentation or tutorial to execute the codes? Currently, i have 3 files: bundler.out", "list" and ".ply", may i ask how can i execute/ input these files for the texturing?

**Comment by simogasp** [comment]
You can find a list of tutorial here https://github.com/alicevision/meshroom/wiki
and a WIP documentation here https://meshroom-manual.readthedocs.io/en/latest/

We cannot import data from Bundler at the moment. But it should not be difficult to write an importer from bundler to sfmdata
