### ISSUE TITLE
Creating/Using my own feature and matches files

### ISSUE THREAD

**Issue by francoisCat** [alicevision/meshroom#827]
Hello,

First of all, thank you very much for your amazing software. It is so useful. I am sure my question is quite trivial but I would like to know how I can create my own features and matches files to pass them to an SfM node.

I would like to have some insight about the feasability of this and also have some insight on how to create such files.

I thank you very much for your help.
Kind regards

**Comment by natowi** [comment]
This is implemented on the alicevision side. You would need to implement your own descriptor.

Files generated by FeatureExtraction (sift)
view_id.sift.feat -> table with the extracted *features* (ascii files)
view_id.sift.desc -> descriptors (binary files)

.feat files are structured quite simple:

The image origin (top-left corner) has coordinate (0,0)
The lower-right corner is defined by the image dimensions
For a landscape images 5000x2000 this is (5000,2000)
Features=x

0-------------------------5000
.......................................x
.
.................x
.
. ............................x
............. x
2000

Next the descriptor files are generated.
See https://github.com/alicevision/AliceVision/tree/develop/src/aliceVision/feature

**Comment by francoisCat** [comment]
Thank you for your answer. Actually I wanted to generate this file off line and change the input folder path in the SfM node but it seems to be 'Locked' and I am not sure I can do it like that (or I do not see how to do so).

**Comment by natowi** [comment]
> generate this file off line and change the input folder path in the SfM node but it seems to be 'Locked' 

Can you explain what you are trying to achieve? I am not sure what you mean with "locked"

**Comment by francoisCat** [comment]
Sorry for not being clear. What I want to do is to generate a file (compatible with Meshroom format) than can be directly used as input to a layer. 

For instance I can generate off line matches using for instance Matlab. I would like to use the matches computed by Matlab in Meshroom SfM pipeline. I thought I could simply generate a matching file from Matlab that could be compatible with Meshroom and then from Meshroom provide the path to this generated file to the SfM node.

I am not sure my explanation is better but I hope you understand my goal.

**Comment by natowi** [comment]
Yes, this should be possible. You should check out https://github.com/alicevision/AliceVision/tree/develop/src/aliceVision/feature to find out how the desc files are being generated. This is not my area of expertise, so I can only can give you this pointer.
