### ISSUE TITLE
Concerning nvidia drivers and Debian.

### ISSUE THREAD

**Issue by gearwarrior** [alicevision/meshroom#828]
I have Buster installed with an Nvidia card.  Apparently there is an issue with the drivers and Nvidia's own position concerned with opening up their hardware.  I think that's fair for them but I wish they were more transparent.

However, upon reading the 'https://github.com/alicevision/meshroom/wiki/Error:-This-program-needs-a-CUDA-Enabled-GPU' page if you run on down to the CUDA on Linux paragraph it tells you to install the Nvidia Dev.  As of now, that breaks things.  

As I'm a novice, I had just assumed that what I was installing was simple header files and such.  Instead, what it installed took down Nouveau and left me without a desktop environment.  If anyone reads that page and tries that advice I think it might be handy to point them to something like this https://linuxhint.com/install_gnome_debian_10_minimal_server/ to fix it.  Other than reinstalling Gnome via tasksel I haven't found a suitable fix if someone tries this.

I hope this saves some folks a lot of headaches.

**Screenshots**

**Dataset**
If applicable, add a link or *few* images to help better understand where the problem may come from.

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ]
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1]
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**

**Comment by gryan315** [comment]
I had a very easy time using manjaro, which is an arch based distro that lags a couple weeks behind raw arch updates to increase stability testing. It gives you the option to install proprietary Nvidia drivers during the OS install, and CUDA 10.2 is in the arch community package repository, so installing is very straightforward. I had meshroom running on manjaro in under an hour as a complete beginner to Linux.
