### ISSUE TITLE
Trying to import fixed camera positions

### ISSUE THREAD

**Issue by bastkop** [alicevision/meshroom#829]
Hi,
I'm a student of mechanical engeneering currently working on a Project, where we try to build a transportable machinery to do automated photogrammetry scans of people.
For taking pictures we use three Raspberry Pi 3b+ with 4 Cameras (V.1.3) each, taking 132 Photos in 340° around a platform in about 34s.

This is what our setup looks like:
![asd](https://user-images.githubusercontent.com/62141663/76622454-cfa94000-6531-11ea-9eec-2f8a1c3f1d65.jpeg)

Due to the construction and programm we wrote, we know the position and rotation matrix of every photo and so we try to import them in Meshroom. 

In order to do that we wrote a program to modify the cameras.sfm with our data. 
After changing the sfm Meshroom continuous, but fails while computing the Mesh.

We also stumbled across https://github.com/natowi/meshroom_external_plugins/blob/master/StructureFromKnownPoses.py but don't know how to use it properly.

Here is what our abc looks like in blender compared to Meshrooms:
![Blenderbild1_LI](https://user-images.githubusercontent.com/62141663/76621851-9c19e600-6530-11ea-9315-bdf6787730db.jpg)

Furthermore we tried to compare our Matrix to Meshrooms in Gnuplot:
Our Matrix (z-vector):
![1](https://user-images.githubusercontent.com/62141663/76622944-c9679380-6532-11ea-82ca-553e88c65782.png)

Meshrooms Matrix (z-vector):
![2](https://user-images.githubusercontent.com/62141663/76622963-d2586500-6532-11ea-83f5-7b8072bada78.png)

Someones got a tip, what we are doing wrong?
Greetings from Germany :)

**Comment by MiniJaggy** [comment]
Hi Bastkop,

Having a similiar problem and i also do not know how to proceed. 
Maybe someone can help us. :)

**Comment by natowi** [comment]
> In order to do that we wrote a program to modify the cameras.sfm with our data.
> After changing the sfm Meshroom continuous, but fails while computing the Mesh.

What is the error log from the Meshing node?


Take a look at the [wiki ](https://github.com/alicevision/meshroom/wiki/Using-known-camera-positions) and the discussion here https://github.com/alicevision/meshroom/issues/788
https://github.com/alicevision/AliceVision/issues/747
At the moment using known camera positions is experimental.

**Comment by bastkop** [comment]
Here's a meshing log: [log.txt](https://github.com/alicevision/meshroom/files/4330199/log.txt)

We already followed all instructions on the wiki 'Using known camera positions'

Here is a sfm generated by Meshroom and modified by us:
[sfm.zip](https://github.com/alicevision/meshroom/files/4330239/sfm.zip)

**Comment by natowi** [comment]
But your dataset works with the default Meshroom graph?

**Comment by bastkop** [comment]
> 
> But your dataset works with the default Meshroom graph?
> 

Yes it works..

>
> Can you check your exr files in irfanview? The contours of your model should be visible
>

They seem to be correct..

> 
> I have not tried this myself, as I do not have a test dataset with known camera positions, but you >could try inserting the camera position in CameraInit as described in [alicevision/AliceVision#747] >(https://github.com/alicevision/AliceVision/issues/747) (you need to build alicevision from source >([_*changes_](https://github.com/alicevision/AliceVision/pull/730)) with [this fix](https://github.com >/alicevision/AliceVision/pull/748) and use the latest meshroom version as the MR 2019.2 version >does not include matchFromKnownCameraPosesm in FeatureExtraction.)
>

Not quite sure, how this is meant, but we will keep on trying to figure it out with some help..



Here is a example Dataset:
https://www.dropbox.com/sh/7l1b0o1bmuvbvlr/AABAb0RxvwHQxy01PLyNYxgHa?dl=0

Camera position and rotationmatrix are contained in xyzrotationsmatrix.txt
Here is my converter to modify cameras.sfm with our data from xyzrotationsmatrix.txt:

`import json
import numpy as np
import sys

try:
        path = str(sys.argv[1])
        filetoread = str(sys.argv[2])
        filetowrite = str(sys.argv[3])
        xyzrotationsmatrix = str(sys.argv[4])
except:
        print('Irgendwas mit den Parametern stimmt nicht..')
        sys.exit()


#Bestimmen der PoseID zu jedem Foto
pianzahl = 3
file = open(path+filetoread,'r')
z = json.load(file)
print(json.dumps(z,sort_keys=False,indent=10))

l = 0
id = np.empty([len(z['views']),2],dtype='object')
print(str(len(z['views'])))
for  p in z['views']:
        print(l)
        print('poseId '+ p['poseId'])
        print('path '+ p['path'])
        id[l,0] = str(p['path'])

        schtring = ''
        for k in range(0,len(id[l,0]),1):
                if id[l,0][k] == 'p' and id[l,0][k+1] == 'i' and int(id[l,0][k+2]) in range(1,pianzahl+1,1) :
                        zaehl = 0
                        for h in range(k,len(id[l,0]),1):
                                print(h)
                                schtring = schtring+str(id[l,0][h]) 
                                zaehl += 1
                        print(schtring)
                        id[l,0] = schtring
                        break
        id[l,1] = str(p['poseId'])
        l += 1
print(id)
print(len(id))
#Austauschen der Rotationsmatrix und Ortsvektoren
x = np.genfromtxt(path+xyzrotationsmatrix,dtype='str')
for p in z['poses']:
        for k in range(0,id.shape[0],1):
                if id[k,1] == p['poseId']:
                        break
        #print(k)
        #print(p['poseId'])
        #print(x[i,:])
        for i in range(0,x.shape[0],1):
                #print(x[i,0])
                #print(str(id[k,0]))
                if str(x[i,0]) == str(id[k,0]):
                        break
        #print(i) 
        p['pose'] = {
                 'transform': {
                         'rotation': [
                                 format(x[i,4],'.15'),
                                 format(x[i,7],'.15'),
                                 format(x[i,10],'.15'),
                                 format(x[i,5],'.15'),
                                 format(x[i,8],'.15'),
                                 format(x[i,11],'.15'),
                                 format(x[i,6],'.15'),
                                 format(x[i,9],'.15'),
                                 format(x[i,12],'.15')
                         ],
                         'center' : [
                                 (float(x[i,1])*0.0012937233071295*1.5), #0.0012937233071295
                                 (float(x[i,3])*0.0012937233071295*1.5),
                                 (float(x[i,2])*0.0012937233071295*1.5)
                        ]},
                'locked' : '1'
                }
file.close
ftw = open(path+filetowrite,'w')
ftw.write(json.dumps(z,sort_keys=False,indent=4))
ftw.close
`

Usage: python convertjson.py 'workdirectory' 'oldcameras.sfm' 'newcameras.sfm' 'xyzrotationsmatrix.txt'

**Comment by natowi** [comment]
I´ll take a look

**Comment by natowi** [comment]
[Here is a build for you](https://github.com/natowi/meshroom_external_plugins/releases/download/av-dev2020.0.1/Meshroom2020.0.1a.zip) that includes the alicevision StructureFromKnownPoses fix and the Meshroom "Match from known camera poses parameter" in FeatureMatching. (Does not include latest qtAlicevision or QtOIIO, so no preview of features or models.)

Then try the following settings:

- generate newcameras.sfm (completely remove "featuresFolders": [""], "matchesFolders": [""], I found out that leaving this messes up the paths)
- disconnect CameraInit and FeatureExtraction
- Input newcameras.sfm in FeatureExtraction 
- make sure the node shows advanced settings (click on ... in right border of the node settings)
- in FeatureMatching  you can now select "Match from known camera poses" (only in MR2020.x)
- in StructureFromMotion "Lock Scene previously reconstructed" and "Force Lock of all Intrinsic Camera Parameters"

**Comment by bastkop** [comment]
Thank you very much for your help!

> impressive work so far, especially with your limited (compared to a pro/pricey 10-20k) setup

We spend 1k for everything.. if you are intrested I can upload some more information as soon as we make some progress on our documentation.

> avoid moving people and objects in the background

>think about placing something (sheets) around the capturing unit to box it in to avoid >reconstruction of the background or the issue with moving people/objects in the background. Or >you add a backdrop that rotates with your cameras around the person and always hides the >background.
>This will allow to mask out the backgound (wip implementation in MR)

We already tried that with blue walls around the machinery, but ended up with worse results due to not being able to insert camera positions and photogrammetry being  confused with too much blue area. 

We also need to spend some more effort on our light setup, which was even worse during our test with the walls, so we might give it a second try. 
When we started we just had light installed on the camera arm. This led to illumination vary with the rotation angle, which photogrammetry also did not like. Lights need to be installed static, when photos are not taken at the same time..

Further thanks for uploading that build. 
I just tried it but it failed at the very beginning of FeatureExtraction:
![ffailt](https://user-images.githubusercontent.com/62141663/76880372-d9a3a980-6877-11ea-9959-50553767d2e6.JPG)

In order to generate  a originial cameras.sfm for that try I ran 2019.2 with the same photos..
https://www.dropbox.com/s/0svqhn9tj4rllf3/newcameras.sfm?dl=0

**Comment by fabiencastan** [comment]
Hi,

*I have not read the full thread in detail.*

When you get cameras poses from a mechanical device, it sounds very challenging to get the precision of 2 pixels needed by the SfM.

If you initialize all cameras before the SfM, it will only triangulate and fully rely on the Bundle Adjustment without any initial estimation. If your initialization has a lower precision, it may decrease the overall quality.
You could also remove the poses before running the SfM, so it can estimate camera poses. You can do that with the "ConvertSfMFormat" node and disable the "Extrinsics" param.

Even for the FeatureMatching, using known poses requires very good initialisation else it will decrease the quality. You can play a bit with the "Known Poses Geometric Error Max" to be a bit more tolerant.

**Comment by fabiencastan** [comment]
We have also started with a group of students to work on an acquisition setup:
https://github.com/alicevision/scanrig
It would be cool to setup a confcall to share our experiences if you are interested.

**Comment by bastkop** [comment]
Hi, that sounds intresting.. of course we can do that. TeamSpeak for example?
Due to the current pandemic disease we can not access our Project and only work from home.

When it comes to precision we are around +-1mm for the location vectors..
But when I look at the estimated camera positions, our coordinates and rotationmatrix should be way more accurate.

**Comment by fabiencastan** [comment]
You can contact me at fabien.castan[at]mikrosimage.com to find a time slot.

**Comment by natowi** [comment]
@bastkop the quotation marks in center are missing:

> "center": [
>                         1.2863135310302207,
>                         4.165465618130208,
>                         -0.5888422650168865
>                     ]

**Comment by bastkop** [comment]
@natowi 

> @bastkop the quotation marks in center are missing:

I fixed that and created a new project, but FeatureExtraction still fails..

`Program called with the following parameters:
 * describerPreset = "normal"
 * describerTypes = "sift"
 * forceCpuExtraction = 1
 * input = "C:/Users/sebas/Desktop/Scans/Scan/Cache2/newcameras.sfm"
 * maxThreads = 0
 * output = "C:/Users/sebas/Desktop/Scans/Scan/Cache2/MeshroomCache/FeatureExtraction/b61778230ab93b5f15682bc9e85919fb9bc4f273"
 * rangeSize = 40
 * rangeStart = 0
 * verboseLevel = "info"

[22:48:16.044175][info] Extracting sift features from view 'C:/Users/sebas/Desktop/Scans/Scan/pi2_27.jpeg' [cpu]
[22:48:16.069164][info] Extracting sift features from view 'C:/Users/sebas/Desktop/Scans/Scan/pi1_10.jpeg' [cpu]
[22:48:16.070163][info] Extracting sift features from view 'C:/Users/sebas/Desktop/Scans/Scan/pi2_41.jpeg' [cpu]
[22:48:16.139658][info] Extracting sift features from view 'C:/Users/sebas/Desktop/Scans/Scan/pi2_24.jpeg' [cpu]
[22:48:16.199638][info] Extracting sift features from view 'C:/Users/sebas/Desktop/Scans/Scan/pi3_3.jpeg' [cpu]
[22:48:16.201637][info] Extracting sift features from view 'C:/Users/sebas/Desktop/Scans/Scan/pi1_2.jpeg' [cpu]
[22:48:16.202637][info] Extracting sift features from view 'C:/Users/sebas/Desktop/Scans/Scan/pi3_31.jpeg' [cpu]
[22:48:16.204638][info] Extracting sift features from view 'C:/Users/sebas/Desktop/Scans/Scan/pi2_32.jpeg' [cpu]
`

Even when I do a default Meshroom run, I stopps at the same point:
`Program called with the following parameters:
 * describerPreset = "normal"
 * describerTypes = "sift"
 * forceCpuExtraction = 1
 * input = "C:/Users/sebas/Desktop/Scans/Scan/muellcache/MeshroomCache/CameraInit/efc964c680dd5c3fb86b1b8e414b2c45d9c1199a/cameraInit.sfm"
 * maxThreads = 0
 * output = "C:/Users/sebas/Desktop/Scans/Scan/muellcache/MeshroomCache/FeatureExtraction/fd61d692b3adc2f7f2dbafb9e5daefc36e0d761c"
 * rangeSize = 40
 * rangeStart = 0
 * verboseLevel = "info"

[22:51:16.339236][info] Extracting sift features from view 'C:/Users/sebas/Desktop/Scans/Scan/pi1_10.jpeg' [cpu]
[22:51:16.405214][info] Extracting sift features from view 'C:/Users/sebas/Desktop/Scans/Scan/pi2_32.jpeg' [cpu]
[22:51:16.407212][info] Extracting sift features from view 'C:/Users/sebas/Desktop/Scans/Scan/pi2_27.jpeg' [cpu]
[22:51:16.407212][info] Extracting sift features from view 'C:/Users/sebas/Desktop/Scans/Scan/pi3_31.jpeg' [cpu]
[22:51:16.408212][info] Extracting sift features from view 'C:/Users/sebas/Desktop/Scans/Scan/pi2_41.jpeg' [cpu]
[22:51:16.429206][info] Extracting sift features from view 'C:/Users/sebas/Desktop/Scans/Scan/pi3_3.jpeg' [cpu]
[22:51:16.448199][info] Extracting sift features from view 'C:/Users/sebas/Desktop/Scans/Scan/pi2_24.jpeg' [cpu]
[22:51:16.448199][info] Extracting sift features from view 'C:/Users/sebas/Desktop/Scans/Scan/pi1_2.jpeg' [cpu]
`

2019.2 has no problem doing a default run with the same photos

**Comment by natowi** [comment]
Can you attach me your sfm file (rename to txt) ?

**Comment by bastkop** [comment]
[newcameras.txt](https://github.com/alicevision/meshroom/files/4346038/newcameras.txt)

**Comment by natowi** [comment]
Ok, this could be a folder path related issue. It works perfectly for me.
Copy your images to another drive (D if available) or non-system/user folder.

**Comment by bastkop** [comment]
Just tried on a SSD mounted under D:\, still stuck at the same point .. If I had the same release for Linux I could try it on another system..

**Comment by natowi** [comment]
I´ll take another look tomorrow.

**Comment by bastkop** [comment]
Ugh .. didn't see that. Thats because he had Problems with two photos in the 2019.2 run, which generated the oldcameras.sfm. 
Will update soon.. (at least in the next 18h)

Also created a git for the converter containing an updated version:
https://github.com/bastkop/personenscanner/blob/master/convertjson.py

**Comment by bastkop** [comment]
I had tu exclude:
- pi3_16.jpeg
- pi3_37.jpeg

[newcameras.txt](https://github.com/alicevision/meshroom/files/4350021/newcameras.txt)


But I'm still stuck at FeatureExtraction..

**Comment by natowi** [comment]
ÃŸ -> do not use ß or ä ö ü in paths

**Comment by bastkop** [comment]
I think it is a problem related to that Meshroom build.. even with 5 Photos and default settings it stops at the exact same point:



```
Program called with the following parameters:
 * describerPreset = "normal"
 * describerTypes = "sift"
 * forceCpuExtraction = 1
 * input = "D:/IP_Personenscanner/Scans/Baustrahler/muellcache/MeshroomCache/CameraInit/8aaa213cfd49387317a14b5a32144824c082aee8/cameraInit.sfm"
 * maxThreads = 0
 * output = "D:/IP_Personenscanner/Scans/Baustrahler/muellcache/MeshroomCache/FeatureExtraction/f444f783ef3bfff0c27087628aa0a2a7d95e4858"
 * rangeSize = 40
 * rangeStart = 0
 * verboseLevel = "trace"

[18:00:51.307482][debug] Job max memory consumption: 378598400 B
[18:00:51.307482][debug] Memory information: 
	- Total RAM:  15.8783 GB
	- Free RAM:   9.42093 GB
	- Total swap: 131072 GB
	- Free swap:  131068 GB

[18:00:51.308481][debug] # threads for extraction: 5
[18:00:51.425445][trace] Read image D:/IP_Personenscanner/Scans/Baustrahler/pi1_3.jpeg (encoded in sRGB colorspace).
[18:00:51.441438][trace] Read image D:/IP_Personenscanner/Scans/Baustrahler/pi1_1.jpeg (encoded in sRGB colorspace).
[18:00:51.441438][trace] Read image D:/IP_Personenscanner/Scans/Baustrahler/pi1_5.jpeg (encoded in sRGB colorspace).
[18:00:51.457434][trace] Read image D:/IP_Personenscanner/Scans/Baustrahler/pi1_2.jpeg (encoded in sRGB colorspace).
[18:00:51.463431][trace] Read image D:/IP_Personenscanner/Scans/Baustrahler/pi1_4.jpeg (encoded in sRGB colorspace).
[18:00:51.509416][info] Extracting sift features from view 'D:/IP_Personenscanner/Scans/Baustrahler/pi1_3.jpeg' [cpu]
[18:00:51.521414][info] Extracting sift features from view 'D:/IP_Personenscanner/Scans/Baustrahler/pi1_1.jpeg' [cpu]
[18:00:51.529408][info] Extracting sift features from view 'D:/IP_Personenscanner/Scans/Baustrahler/pi1_5.jpeg' [cpu]
[18:00:51.538407][info] Extracting sift features from view 'D:/IP_Personenscanner/Scans/Baustrahler/pi1_4.jpeg' [cpu]
[18:00:51.539409][info] Extracting sift features from view 'D:/IP_Personenscanner/Scans/Baustrahler/pi1_2.jpeg' [cpu]
```


[newcameras.txt](https://github.com/alicevision/meshroom/files/4350291/newcameras.txt)

**Comment by natowi** [comment]
> I think it is a problem related to that Meshroom build

That is possible. I´ll do a few tests.

**Comment by natowi** [comment]
Works with the first five cameras [5cameras.txt](https://github.com/alicevision/meshroom/files/4350568/5cameras.txt)

**Comment by bastkop** [comment]
Mhh as already stated above it looks like I'm having some trouble with that build on my Windows machine.. 

Maybe it has something to do with the initial pair?

**Comment by natowi** [comment]
> Maybe it has something to do with the initial pair?

This is probably expected, as the 10 cameras are in no particular order and have not enough corresponding features.

> Mhh as already stated above it looks like I'm having some trouble with that build on my Windows machine..

Pretty strange that my 10cameras.sfm file does not work for you.

**Comment by bastkop** [comment]
> Pretty strange that my 10cameras.sfm file does not work for you.
> 
> Ok,
> "path": "C:/tmp/av/sfnp/Scan/pi1_34.jpeg" --> sometimes red bar error
> "path": "C:\/tmp\/av\/sfnp\/Scan\/pi1_34.jpeg" --> fixes red bar error in FeatureExtraction


I tried it on another machine, resulting in the same failure.
Not quite sure, where to insert these paths?

**Comment by natowi** [comment]
I did a test with pi1_34 - pi1_38. Meshroom throws no errors, but the sfm output is a mess:

![knownposes](https://user-images.githubusercontent.com/8138537/77059758-bdb71980-69d7-11ea-8fff-3d90c114d75e.JPG)

This is what it should look like:

![default](https://user-images.githubusercontent.com/8138537/77059794-cd366280-69d7-11ea-8100-f7ccc9b5c69d.JPG)

I see two possibilities: 1) your known camera poses are not precise enough 2) there is a conversion problem with the transformation matrix

**Comment by bastkop** [comment]
You can open the sfm with Blender to compare camerasposition and rotation from oldcameras and newcameras ..

**Comment by natowi** [comment]
When I directly insert the sfm file in StructureFromMotion and use the sfm file without poses in FeatureExtraction, this is the result:

![sfminsert](https://user-images.githubusercontent.com/8138537/77061444-85fda100-69da-11ea-8028-76e1b036e1de.JPG)

with Lock... and Force... in StructureFromMotion:

![sfminsert-force](https://user-images.githubusercontent.com/8138537/77061538-afb6c800-69da-11ea-9b5b-3de9c50e19a5.JPG)

Both somewhat resemble the expected result, but are scrambled.

I´ll pack the sfm files for you.

**Comment by natowi** [comment]
[sfmcomp.zip](https://github.com/alicevision/meshroom/files/4354186/sfmcomp.zip)
(you need to search+replace my image path with yours in the sfm files)

**Comment by bastkop** [comment]
default sfm:
![default](https://user-images.githubusercontent.com/62141663/77064370-a9771a80-69df-11ea-8263-5a078ff4f151.png)

knownposes sfm:
![knownposes](https://user-images.githubusercontent.com/62141663/77064394-b5fb7300-69df-11ea-9f22-6cb2a0d9188c.png)


looks like a 180° rotation..
As in my plot above coordinates should by correct relativly to each other. 

! ! But if you think there is any relation to the base coordinate system we can try to fix that..

**Comment by natowi** [comment]
Maybe you mixed up xyz order or positive/negative values? Or rotate your matrix in your conversion script by 180°

**Comment by bastkop** [comment]
> I´d give it a try.

The thing is the rotationmatrix is computet on our scanner and due to virus restriction we can't work with it at the moment, so we only have some existing datasets..

Depending on how long this remains, we can try to write another converter for the rotation..



Here are the other two plots:

sfminsert:
![sfminsert](https://user-images.githubusercontent.com/62141663/77065982-944fbb00-69e2-11ea-92b2-666a7c1b6755.png)


sfminsert-force:
![sfminsert-force](https://user-images.githubusercontent.com/62141663/77065994-9b76c900-69e2-11ea-9bc8-dc648aad1186.png)

**Comment by natowi** [comment]
You could try the following: convert your newcameras.sfm to ply or abc, flip it in a 3d program, then convert it back to sfm using ConvertSfM format.

**Comment by natowi** [comment]
I don´t know why I have no thought of this earlier, but you can use SfMAlignment to align your SfM computed with the default Graph with your knowncamerapositions.sfm. Place the SfMAlignment  node between SfM and PrepareDenseScene.

Transformation:
- Scale: 1.03423
- Rotation:
0.54991 -0.0549082   0.833417
-0.0691308  -0.997405  -0.020098
0.832358 -0.0465627  -0.552279
- Translate: -1.55478  1.20419 0.967016

You can convert your knowncamerapositions.sfm to abc using ConvertSfMFormat.

Maybe this helps.

**Comment by bastkop** [comment]
Okay we are currently trying to flip our coordinates. 

I need to work with 2019.2, due to 2020 always failing at FeatureExtraction
Just want to make sure, that I got that right:
- do normal run until StructureFromMotion is finished
- create newcameras.sfm from oldcameras.sfm with xyzrotationsmatrix.txt
- replace the sfm files
- place SfMAlignment between SFM and PrepareDenseScene
- compute

?

**Comment by natowi** [comment]
Yes. I don´t know if this is useful in your case, it just came to mind.

**Comment by natowi** [comment]
@bastkop If you´d like to chat, you can send me a Skype invite link. [myusername]at arcor.de . I have some spare time today.

**Comment by bastkop** [comment]
I'll send you a mail.

Here is the result of sfmaligment:

Original SFM:
![a1t](https://user-images.githubusercontent.com/62141663/77080340-7a6da280-69f9-11ea-909e-f54fa574c2b2.JPG)

Aligned SFM:
![s2t](https://user-images.githubusercontent.com/62141663/77080366-822d4700-69f9-11ea-8cc7-0b91e23aa3d9.JPG)

**Comment by natowi** [comment]
We run the default sfm with the image dataset from CameraInit to StructureFromMotion.
Then we add a SfMAlignment node and align the reconstructed SfM with the knowncamerapositions.sfm
Now we have a valid sfm file we can use:

![gg](https://user-images.githubusercontent.com/8138537/77097653-69309000-6a11-11ea-9dcb-1879bd3fb6ec.JPG)
ConvertSfM format (abc to sfm)

These steps are only necessary to circumvent the problem with the rotation matrix

Once you have a valid sfm file with known cameras, it can be used directly as input in the FeatureExtraction node.


Summary:
- check for syntax errors
- check file paths (+avoid non-standard characters)
- remove featuresFolders / matchesFolder
- check camera matrix
- when error occur, use a subset of your images to find the problem
- do a default reconstruction with your images to have a sfm file to compare your own generated sfm file to
- some settings are not available in MR2019

**Comment by natowi** [comment]
Tests with latest alicevision (including fix 748)+ meshroom build:

![tests](https://user-images.githubusercontent.com/8138537/77228918-e16e9100-6b8a-11ea-8f22-59bb183e712e.jpg)
