### ISSUE TITLE
Meshroom no permit to use CUDA 2 of my Geforce gt430 [bug]

### ISSUE THREAD

**Issue by exilaus** [alicevision/meshroom#830]
**Describe the bug**
see cuda enabled GPU  but  no enought compute version  but  my gt430 have cuda 2.1 enabled
Below cuda report from my of GPU
 

mCudaDriverLibrary.Initialized true.
mCudaDriverVersionManagement.VersionAvailable true.
mCudaDriverVersionManagement.Version: 9010
mCudaDriverDeviceManagement.DeviceCountAvailable true
mCudaDriverDeviceManagement.DeviceCount: 1
mCudaDriverDeviceManagement.Device[0].Number: 0
mCudaDriverDeviceManagement.Device[0].Handle: 0
mCudaDriverDeviceManagement.Device[0].Name: GeForce GT 430
mCudaDriverDeviceManagement.Device[0].ComputeCapability.Major: 2
mCudaDriverDeviceManagement.Device[0].ComputeCapability.Minor: 1
mCudaDriverDeviceManagement.Device[0].MemorySize: 1073741824
mCudaDriverDeviceManagement.Device[0].Properties.MaxThreadsPerBlock: 1024
mCudaDriverDeviceManagement.Device[0].Properties.MaxBlockDimension[0]: 1024
mCudaDriverDeviceManagement.Device[0].Properties.MaxBlockDimension[1]: 1024
mCudaDriverDeviceManagement.Device[0].Properties.MaxBlockDimension[2]: 64
mCudaDriverDeviceManagement.Device[0].Properties.MaxGridDimension[0]: 65535
mCudaDriverDeviceManagement.Device[0].Properties.MaxGridDimension[1]: 65535
mCudaDriverDeviceManagement.Device[0].Properties.MaxGridDimension[2]: 65535
mCudaDriverDeviceManagement.Device[0].Properties.MaxSharedMemoryPerBlock: 49152
mCudaDriverDeviceManagement.Device[0].Properties.MaxConstantMemory: 65536
mCudaDriverDeviceManagement.Device[0].Properties.WarpSize: 32
mCudaDriverDeviceManagement.Device[0].Properties.MaxMemoryPitch: 2147483647
mCudaDriverDeviceManagement.Device[0].Properties.MaxRegistersPerBlock: 32768
mCudaDriverDeviceManagement.Device[0].Properties.ClockFrequency: 1400000000
mCudaDriverDeviceManagement.Device[0].Properties.TextureAlignment: 512
mCudaDriverDeviceManagement.Device[0].Attributes.MaxThreadsPerBlock: 1024
mCudaDriverDeviceManagement.Device[0].Attributes.MaxBlockDimensionX: 1024
mCudaDriverDeviceManagement.Device[0].Attributes.MaxBlockDimensionY: 1024
mCudaDriverDeviceManagement.Device[0].Attributes.MaxBlockDimensionZ: 64
mCudaDriverDeviceManagement.Device[0].Attributes.MaxGridDimensionX: 65535
mCudaDriverDeviceManagement.Device[0].Attributes.MaxGridDimensionY: 65535
mCudaDriverDeviceManagement.Device[0].Attributes.MaxGridDimensionZ: 65535
mCudaDriverDeviceManagement.Device[0].Attributes.MaxSharedMemoryForBlocksPerMultiProcessor: 49152
mCudaDriverDeviceManagement.Device[0].Attributes.MaxConstantMemory: 65536
mCudaDriverDeviceManagement.Device[0].Attributes.MaxWarpSize: 32
mCudaDriverDeviceManagement.Device[0].Attributes.MaxMemoryPitch: 2147483647
mCudaDriverDeviceManagement.Device[0].Attributes.MaxRegistersForBlocksPerMultiProcessor: 32768
mCudaDriverDeviceManagement.Device[0].Attributes.ClockFrequency: 1400000000
mCudaDriverDeviceManagement.Device[0].Attributes.TextureAlignment: 512
mCudaDriverDeviceManagement.Device[0].Attributes.MemoryCopyAndKernelExecutionOverlap: TRUE
mCudaDriverDeviceManagement.Device[0].Attributes.MultiProcessorCount: 2
mCudaDriverDeviceManagement.Device[0].Attributes.RunTimeLimitForKernels: TRUE
mCudaDriverDeviceManagement.Device[0].Attributes.IntegratedWithHostMemory: FALSE
mCudaDriverDeviceManagement.Device[0].Attributes.CanMapHostMemoryIntoCudaAddressSpace: TRUE
mCudaDriverDeviceManagement.Device[0].Attributes.ComputeMode: 0 (DEFAULT/UNRESTRICTED)
mCudaDriverDeviceManagement.Device[0].Attributes.MaxTexture1DWidth: 65536
mCudaDriverDeviceManagement.Device[0].Attributes.MaxTexture2DWidth: 65536
mCudaDriverDeviceManagement.Device[0].Attributes.MaxTexture2DHeight: 65535
mCudaDriverDeviceManagement.Device[0].Attributes.MaxTexture3DWidth: 2048
mCudaDriverDeviceManagement.Device[0].Attributes.MaxTexture3DHeight: 2048
mCudaDriverDeviceManagement.Device[0].Attributes.MaxTexture3DDepth: 2048
mCudaDriverDeviceManagement.Device[0].Attributes.MaxTexture2DLayeredWidth: 16384
mCudaDriverDeviceManagement.Device[0].Attributes.MaxTexture2DLayeredHeight: 16384
mCudaDriverDeviceManagement.Device[0].Attributes.MaxTexture2DLayeredLayers: 2048
mCudaDriverDeviceManagement.Device[0].Attributes.MaxTexture2DArrayWidth: 16384
mCudaDriverDeviceManagement.Device[0].Attributes.MaxTexture2DArrayHeight: 16384
mCudaDriverDeviceManagement.Device[0].Attributes.MaxTexture2DArraySlices: 2048
mCudaDriverDeviceManagement.Device[0].Attributes.SurfaceAlignment: 512
mCudaDriverDeviceManagement.Device[0].Attributes.ConcurrentKernels: TRUE
mCudaDriverDeviceManagement.Device[0].Attributes.ErrorCorrectingCodesEnabled: FALSE
mCudaDriverDeviceManagement.Device[0].Attributes.PCIBusID: 7
mCudaDriverDeviceManagement.Device[0].Attributes.PCIDeviceID: 0
mCudaDriverDeviceManagement.Device[0].Attributes.UsingTCCDriver: FALSE
mCudaDriverDeviceManagement.Device[0].Attributes.MemoryClockFrequency: 800000000
mCudaDriverDeviceManagement.Device[0].Attributes.GlobalMemoryBusWidthInBits: 128
mCudaDriverDeviceManagement.Device[0].Attributes.Level2CacheSize: 131072
mCudaDriverDeviceManagement.Device[0].Attributes.MaxResidentThreadsPerMultiProcessor: 1536
mCudaDriverDeviceManagement.Device[0].Attributes.AsynchronousEngineCount: 1
mCudaDriverDeviceManagement.Device[0].Attributes.UnifiedAddressing: FALSE
mCudaDriverDeviceManagement.Device[0].Attributes.MaxTexture1DLayeredWidth: 16384
mCudaDriverDeviceManagement.Device[0].Attributes.MaxTexture1DLayeredLayers: 2048
mCudaDriverDeviceManagement.Device[0].Attributes.PCIDomainID: 0
mCudaDriverContext.Open( CudaDriverContextSchedulingAutomatic, mCudaDriverDeviceManagement.Device[0] ) successfull.
mCudaDriverContext.Enter successfull.
mCudaDriverContext.APIVersion: 3010
mCudaDriverContext.Handle: 39392104
mCudaDriverContext.IsOpen: TRUE
mCudaDriverContext.IsCurrent: TRUE
mCudaDriverContext.IsSameDevice: TRUE
mCudaDriverContext.CachePreference: 0
assignment test:
mCudaDriverContext.CachePreference := CudaDriverContextCachePreferenceLargerSharedMemorySmallerL1Cache(1)
mCudaDriverContext.CachePreference: 1
mCudaDriverContext.ResourceLimit[CudaDriverContextResourceLimitStackSize]: 1024
mCudaDriverContext.ResourceLimit[CudaDriverContextResourceLimitPrintfFifoSize]: 1048576
mCudaDriverContext.ResourceLimit[CudaDriverContextResourceLimitMallocHeapSize]: 8388608
assignment test:
mCudaDriverContext.ResourceLimit[CudaDriverContextResourceLimitStackSize] := 10100100
mCudaDriverContext.ResourceLimit[CudaDriverContextResourceLimitPrintfFifoSize] := 20100100
mCudaDriverContext.ResourceLimit[CudaDriverContextResourceLimitMallocHeapSize] := 30100100
mCudaDriverContext.ResourceLimit[CudaDriverContextResourceLimitStackSize]: 1024
mCudaDriverContext.ResourceLimit[CudaDriverContextResourceLimitPrintfFifoSize]: 20100352
mCudaDriverContext.ResourceLimit[CudaDriverContextResourceLimitMallocHeapSize]: 30146560
mCudaDriverContext.Leave successfull.
mCudaDriverContext.Close successfull.

**Comment by natowi** [comment]
Did you - by any chance - disable "Force CPU extraction"?
https://github.com/alicevision/meshroom/issues/734
