### ISSUE TITLE
Error when trying to compute the Export Animated Camera node

### ISSUE THREAD

**Issue by Hellbolato** [alicevision/meshroom#831]
Hello ! 
i'm new to Meshroom, so for my first try i uploaded to the project 21 jpg resized to 2000px for the length. named like "img_2020" with underscores and all images are in the same folder.  I got the green logo on the pictures so the exifs are okay. 
I saved the cache folder on a drive with enough diskspace. 
I'm using Meshroom 2019 2.0 on Windows 10

When i computed from structure from motion it went fine and the structure from motion scene appeared correctly.

Then i created the export animated camera node, connected the structure from motion output to the animated camera input, but when i click compute i get the instant red bar ! 

The log says : 

ERROR:root:Error during Graph execution Error on node "ExportAnimatedCamera_1":
Log:
Program called with the following parameters:
 * exportUndistortedImages = 1
 * input = "D:/Meshroom cache files/MeshroomCache/StructureFromMotion/e53f6bf2780e1222e27a20dfb5478720ba02e936/sfm.abc"
 * output = "D:/Meshroom cache files/MeshroomCache/ExportAnimatedCamera/20ff3098ec69163c60710a88e0926ca6fff8362b"
 * undistortedImageType = "jpg"
 * verboseLevel = "info"
 * viewFilter = ""

[22:58:12.079369][info] Build animated camera(s)...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**
WARNING:root:QQmlComponent: Created graphical object was not placed in the graphics scene.
WARNING:root:ShellExecute 'file:///D:/Meshroom cache files/MeshroomCache/ExportAnimatedCamera/20ff3098ec69163c60710a88e0926ca6fff8362b/camera.abc' failed (error 2).
WARNING:root:QQmlComponent: Created graphical object was not placed in the graphics scene.

help !

**Comment by natowi** [comment]
Do you have a sequence of images?

> The Animated Camera export feature is not optimized at the moment and requires a sequence of images with corresponding names (1-n) from the same folder. Unstructured images, naming conventions, folder structures... will not work or result in an error.

**Comment by Hellbolato** [comment]
Yes, with corresponding names such as _MG_0032, _MG_0033 and so on

**Comment by natowi** [comment]
Try changing the image names. If this does not help, you can share a part of your image sequence (link here or via private mailing list alicevision-team@googlegroups.com with a short description of your problem)
