### ISSUE TITLE
Adjust origin and Orientation

### ISSUE THREAD

**Issue by Snoman002** [alicevision/meshroom#832]
Hello,

Currently utilizing photogrammetry to determine camera prose (distance, position, orientation, etc).  Currently I am tracking moving objects with a fixed camera to achieve the motion.

One, the camera info appears to be in a .abc file which I cannot read, is there a parsable text file that contains the camera information?

Second, is there a method (or alternate software) where I can adjust the position and orientation of the origin to be along certain features of my reconstructions (and hence recalculate the relative camera position)?

**Comment by natowi** [comment]
> One, the camera info appears to be in a .abc file which I cannot read, is there a parsable text file that contains the camera information?

Use the ConvertSfMFormat node, it supports json output.

> where I can adjust the position and orientation of the origin to be along certain features of my reconstructions (and hence recalculate the relative camera position)?

You can use the SfMTransform node. It can Transform/Scale SfM using given transformation, cameras, landmarks, markers.

Transformation Method: fromsinglecamera

Set a specific camera as origin. Provide Camera UID or image filename. Applies correct orientation if possible.
