### ISSUE TITLE
I would like to help documentation

### ISSUE THREAD

**Issue by Snoman002** [alicevision/meshroom#833]
....but where to start.

Specifically, as a new user, I struggle with placing nodes together.  More specifically WHERE nodes can be placed.  I would be happy to start here if there is any documentation I can distill down.

Two, many of the features (akaze, akaze_liop) are foreign.  If you can point me to documentation I can do some work here.

**Comment by natowi** [comment]
You are welcome to help with the documentation or share your thoughts.
The current version can be found here: https://meshroom-manual.readthedocs.io
I am working on a [major update](https://github.com/alicevision/meshroom-manual/pull/7).

> many of the features (akaze, akaze_liop) are foreign

Adding a description of the features is on the to do list for the documentation.

[AKAZE Fast explicit diffusion for accelerated features in nonlinear scale spaces, P.F. Alcantarilla, J. Nuevo, A. Bartoli, 2013](http://www.bmva.org/bmvc/2013/Papers/paper0013/paper0013.pdf)

[A comparative analysis of SIFT, SURF, KAZE, AKAZE, ORB, and BRISK](https://www.researchgate.net/publication/323561586_A_comparative_analysis_of_SIFT_SURF_KAZE_AKAZE_ORB_and_BRISK)

Akaze_liop: Wang, Z., Fan, B., Wu, F.: Local intensity order pattern for feature description.  In:  IEEE  International  Conference  on  Computer  Vision  (ICCV).  pp.603–610 (2011)

[Feature Evaluation with High-Resolution Images](https://www.tnt.uni-hannover.de/papers/data/1101/CAIP2015_Cordes-Feature_Evaluation_with_High_Resolution_Images.pdf)

_general overview_

[Introduction to SIFT](https://medium.com/analytics-vidhya/introduction-to-sift-scale-invariant-feature-transform-65d7f3a72d40) 

[SIFT explained](https://medium.com/@vad710/cv-for-busy-developers-describing-features-49530f372fbb)

**Comment by Snoman002** [comment]
Thank you for the links, I will read through them as I can.

Are the details provided in the .io linked to the details provided in the popups within the program?

**Comment by natowi** [comment]
> Are the details provided in the .io linked to the details provided in the popups within the program?

The popup info is used in the documentation when there is no more detailed description available.
