### ISSUE TITLE
[question] Server or Desktop / Core-Count vs. Single Core Performance

### ISSUE THREAD

**Issue by nighttimedev** [alicevision/meshroom#834]
Hey there!

I'll soon create a 3D model of a BMW 325i, and I will throw a lot of images (I estimate ~ 200, when needed even more) into meshroom since my result needs to be as accurate as possible.  
Now I' wondering rather I should use my desktop PC, or one of my servers for that application.  
Setups in detail:  
#### Desktop:  
- 1x Ryzen 7, 2700x
- 16gb DDR4
- GTX970

#### My Home-Servers
- Up to 2x Intel Xeon E5645 (slow cores, but 24 threads in total)
- Up to 98gb DDR3 ECC
- GTX770 (overclocked model from MSI)

It basically comes down to the following parameters:
- Does more RAM (with a lower clock-speed) decrease my render time?
- Can Meshroom handle 24 Threads, and if yes, is it faster than my 2700x?

And of course we have to consider that a 770 is way slower than the 970.

Would be awesome to get some advice :)

Thanks in advance

**Comment by natowi** [comment]
At the moment Meshroom does not fully utilize multi-core cpus. 
Generally speaking more RAM is better. For 200 images 16gb  might not be enough (depends on image resolution).

**Comment by nighttimedev** [comment]
@natowi Thanks alot for your reply!  
You are expecting the server solution to be faster, am I reading this right?  
Regarding the image resolution: I will either use my Huawei P20 Pro and take 40 MP Raw images, or use my Canon EOS 5D **if** the phone's pictures aren't good enough for accurate results. Using the 5D pictures will increase the amount of data by a large amount.  

I will run some tests and write the results down here, so other people can take advantage of my adventure.

**Comment by natowi** [comment]
> 40 MP Raw images

Ok, in this case definitively use your server with 98gb ram.
Convert your raw images to  a [supported format](https://github.com/alicevision/meshroom/wiki/Supported-image-formats)

**Comment by gryan315** [comment]
The ryzen 2700x is ok, it performed about as well as my e5-1660v3 (which is more a testament to how good socket 2011-v3 was), but both chips get left in the dust by my lower clock 24 core v3 system with 128gb RAM. Also the slower ddr3 won't be too much slower since that platform is in triple channel vs dual channel ddr4. While the 970 is undoubtedly a better GPU, especially in power draw, the raw compute power shouldn't be too much more than the 770. I think there real challenge will be getting a working model from a reflective relatively featureless object with glass like a car.

**Comment by natowi** [comment]
> I think there real challenge will be getting a working model from a reflective relatively featureless object with glass like a car.

If you are willing to share a screenshot from the Meshroom images viewer with the thumbnails, maybe I can give you some advive on your dataset.

**Comment by nighttimedev** [comment]
> If you are willing to share a screenshot from the Meshroom images viewer with the thumbnails, maybe I can give you some advive on your dataset.

I don't have the images already. I will take them soon. Once I have them I would love to get some help since I never used Meshroom before. I'll come back to you!

> I think there real challenge will be getting a working model from a reflective relatively featureless object with glass like a car.

I'm aware of that problem - and to be honest.. I don't know how to deal with the reflections. I already opened a thread regarding that on reddit. Maybe there is a way of automatically removing reflections in any way. Here is the link, in case you are curious: https://www.reddit.com/r/AskComputerScience/comments/fkrq5k/automatically_remove_reflections_on_a_bulk_of/

**Comment by natowi** [comment]
Use your Canon EOS 5D with a polarization filter. When capturing try to keep reflections out of the image frame if possible. Park the car in the shades of a building / vegetation so there is no direct light.
Prepare your capturing session by reading [guides like this](https://www.vertexlibrary.com/guide-to-3d-scanning-outdoor-photogrammetry-tips) to avoid common mistakes.

**Comment by nighttimedev** [comment]
@natowi Holy... Why haven't I thought of the polarization filter. Awesome idea!

We can't wind down the windows, since we're talking about a race-car with fixed windows that aren't even made of glass.

I've also thought about covering the windows with some tape in case everything fails.
But as said, the polarization filter is sooo simple but should do the trick!

Another thing that came into my mind: Can you already assume what happens regarding the interior of the car? Is it possible that this will mess up my result?

**Comment by gryan315** [comment]
Every time I've tried something with glass, the glass mostly disappeared. As long as you can prevent reflections, it should do an alright job, maybe a little funkiness around the edges and on things behind the glass. Since you say it's not glass, I'll assume acrylic, which if scuffed up will probably show up spotty in the mesh.
