### ISSUE TITLE
iPhone TrueDepth reconstruction method

### ISSUE THREAD

**Issue by jymboche** [alicevision/meshroom#835]
I recently saw an iPhone app that does facial reconstruction very quickly and with impressive accuracy. For those who dont know, the iPhone X and later has an infrared projector and infrared camera in the front, in addition to the normal front facing camera. The infrared projector, laser based i assume, projects 30,000 dots on the persons face to help with depth mapping.

For my current multi-camera fixed rig, we take 2 photos from the SAME camera, one with projection to aid in reconstruction, and one without for accurate color/texture. The iPhone uses two separate cameras, not even the same resolution so what is the methodology being used? Is this even technically like stereoscopic rigs?

Ideally, I would like to have an IR camera and normal camera pair, so I could project IR and take the images at the same time to minimize any movement between the two images (moving objects) so the texture lines up properly with the 3D mesh (its a multicamera fixed rig that takes all photos at once). Ive also though about some sort of lens splitter/mirrors so the cameras could virtually be in the same place? Any advice? Am I going down the wrong rabbit hole?

**Comment by natowi** [comment]
> For my current multi-camera fixed rig, we take 2 photos from the SAME camera, one with projection to aid in reconstruction, and one without for accurate color/texture. 

Read https://github.com/alicevision/meshroom/wiki/Projected-Light-Patterns

**Comment by jymboche** [comment]
Thanks @natowi 
So, we're already using projected patterns (not IR, just regular projectors). We have a multicamera rig that takes one set with projection and one set without. This is the same setup from the link you shared. We can do this in about 400ms in between first shot and second projection shot. That doesnt seem like a long time but a lot of movement can happen, especially with animals.

If we had IR projectors and separate IR cameras we could shoot both at the same time. But these IR cameras would be separate cameras in different positions. Would we still be able to align build the texture from the normal cameras, or would they not align? I read the bottom link about polarized/non-polarized, which is new to me, but I'm unclear about his shooting methodology (if hes taking the photo with filter, and removing it while camera is in same position for example).

**Comment by natowi** [comment]
> If we had IR projectors and separate IR cameras we could shoot both at the same time. But these IR cameras would be separate cameras in different positions. Would we still be able to align build the texture from the normal cameras, or would they not align?

I can not think of a way this might work out of the box in Meshroom. Maybe there is a way using rig constraints or the known camera positions, but again, your use case is quite special.

> I read the bottom link about polarized/non-polarized, which is new to me, but I'm unclear about his shooting methodology (if hes taking the photo with filter, and removing it while camera is in same position for example).

This setup is used to work with reflective surfaces.
