### ISSUE TITLE
[question] Input of Bundle.out, list.txt and .ply file into texture.py?

### ISSUE THREAD

**Issue by ethansu1992** [alicevision/meshroom#836]
**Describe the problem**
Hi currently, i am trying to assemble a textured 3D model using the osmbundler and i would like to create a texture map over my model just like how meshroom is able to do in it the program. I have download the meshroom developer, but i cant seem to have the texturing codes running and can the codes have input from the bundler output such as bundle.out and list.txt? 

The error that i face:
`
[2020-03-19 15:58:27,422][WARNING] == The following "aliceVision" plugins could not be loaded ==
  * SketchfabUpload: No module named 'requests'

[2020-03-19 15:58:27,434][WARNING] == The following "submitters" plugins could not be loaded ==
  * simpleFarmSubmitter: No module named 'simpleFarm'`

**Comment by natowi** [comment]
> i am trying to assemble a textured 3D model using the osmbundler

Is there a reason why you can not directly use Meshroom?
https://github.com/alicevision/meshroom/releases
Alicevision is actually based on OpenMVG and CMPMVS (with many modifications and improvements).

> input from the bundler output such as bundle.out and list.txt?

You would need to convert your files in the Meshroom Format.

You could look into the [aliceVision_exportPMVS module](https://github.com/alicevision/AliceVision/blob/develop/src/software/export/main_exportPMVS.cpp) and may be able to "reverse" the code.

The error can be ignored if you don´t need SketchdbUpload.

--
Duplicate: https://github.com/alicevision/meshroom/issues/826
