### ISSUE TITLE
I can't add photos with metadata

### ISSUE THREAD

**Issue by NorbertCierpicki** [alicevision/meshroom#838]
Hi! I'm working on win10 with 8GB of ram gtx1050, and using Meshroom 2019 (2018 didn't make any difference).
Main problem is that I can't add photos with metadata. Drag and drop  doesn't work. I can only add photos by Live Reconctruction window by adding folder. After adding images i can see red symbol in the corner and it says generaly "there is no metadata". The strangest thing is, when i turn on meshroom on virtual machine with win10 there is no problem (i only needed to add my camera in the cameraSensors file), photos still can only be added by Live Reconctruction window (i don't know how to drag in VM), but its working, symbol is green, all metadata is correct. It can't work on VM because there is no CUDA processor and it's almost impossible to add graphic card into VM, BUT photos were added correctly on VM and on physical machine NOT.
I installed exif editors, all works fine, metedata is fine. It's not a problem with cameraSensors file, I have installed all Visual C++ Redistributable packages. My win10 is quite fresh, 3 weeks. 
On physical machine logs gives no errors or information, when i'm adding photos (as i said, unsuccesfully) with drop i get
\"939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm"\
On physical machine when i click "start" with photos marked RED it's fast going till the end of process, but there is no effect, nothing really processed. Log says only elapsed time.

I spend like 8hrs looking for solving... nothing worked for me. I think that maybe i have some software problems with system configuration settings or something.. i don't know even what to look for.

![2020-03-25_02h00_42](https://user-images.githubusercontent.com/61237045/77492605-418e5d00-6e41-11ea-9d18-9f8ec9abe9a3.png)

**Comment by fabiencastan** [comment]
That's really strange and it sounds difficult to debug!

Could you open aliceVision_cameraInit.exe into [depends](http://www.dependencywalker.com) inside and outside the VM to see if there is a difference in the loaded dlls?

**Comment by NorbertCierpicki** [comment]
Looks that i have some bigger problem with my system. Some command windows are showing for few miliseconds.  I scanned my laptop looking for malewares or viruses. Found nothing. This problems are only on physical machine.
Thanks for helping. I'll try to use your advise as soon as cmd will work.

**Comment by NorbertCierpicki** [comment]
Finally I reinstalled system and it works properly now.
Thanks for help
