### ISSUE TITLE
[bug] Windows 10, cannot drop images from file system

### ISSUE THREAD

**Issue by mpizenberg** [alicevision/meshroom#840]
**The bug**
Trying to drag and drop an image folder into meshroom triggers a missing VCOMP140.DLL error.

**To Reproduce**
1. Use a fresh Windows 10 installation (nothing fancy, just microsoft office, firefox and chrome, no coding environment)
2. Drag and drop an image folder into meshroom

**Expected behavior**
It should load the images into meshroom.

**Screenshots**
<img width="960" alt="missing-dll" src="https://user-images.githubusercontent.com/2905865/77681627-eb7efe00-6f95-11ea-8072-7db2d778a277.png">
<img width="674" alt="missing-dll-debug" src="https://user-images.githubusercontent.com/2905865/77681650-f3d73900-6f95-11ea-96b2-ddaabad2e65b.png">

**Log**
```
ERROR:root:Error while building intrinsics : Traceback (most recent call last):
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\meshroom\ui\reconstruction.py", line 399, in buildIntrinsics
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 192, in buildIntrinsics
RuntimeError: CameraInit failed with error code 3221225781. Command was: "aliceVision_cameraInit  --sensorDatabase "C:\Users\unive\Downloads\Meshroom-2019.2.0\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "C:/Users/unive/AppData/Local/Temp/tmp5ufk2uqh/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm" --allowSingleView 1  --input "C:\Users\unive\AppData\Local\Temp\tmp5ufk2uqh/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca//viewpoints.sfm""
```

**Desktop (please complete the following and other pertinent information):**
 - OS: windows 10
 - Python version ?
 - Qt/PySide version ?
 - Meshroom version:
   - Binary version 2019.2.0

**Comment by simogasp** [comment]
You might need to install Microsoft Visual C++ Redistributable Package

See point 3 here https://meshroom-manual.readthedocs.io/en/latest/install/windows/windows.html

**Comment by mpizenberg** [comment]
Great it solved the issue indeed!
It might be better to give a link to the install guide instead of just the executable on meshroom home page (https://alicevision.org/#meshroom) ?
