### ISSUE TITLE
Can't get Meshroom to crunch these photos. Is it a problem with my cell phone camera or the way I'm taking pictures?

### ISSUE THREAD

**Issue by ata136** [alicevision/meshroom#841]
I'm a relatively new user of Meshroom and have been busy watching videos and reading as much as I can about this amazing software. I have tried taking pictures of different objects and reconstructing the 3D view of them in the software...No success so far. I downloaded pictures of objects that other users have uploaded and got the 3D view of all of them WITH EASE!

The first issue I had with my cell phone was that it wasn't in the database! I am using a Samsung Galaxy A8 (A530W). I added this camera in the database as:

Samsung;Samsung Galaxy A8 SM-A530W;5.3;devicespecifications

This fixed the Metadata problem and I got the green Camera Intrinsics icon on all my imported photos.

I still can't get an output from the texturing node.

What I have tried:
- Changing describer preset to high & ultra
- Using "akaze" in FE, FM and SFM
- Enabling Guided Matching
- Taking close-up pics and increasing the number of pictures
- Lowering picture resolution from 3456x3456 to 2448x2448 (this helped a little bit)

None of these have worked so far.

**Screenshots**
![image](https://user-images.githubusercontent.com/62720357/77689398-333a6100-6f67-11ea-939a-d78a70524196.png)
![image](https://user-images.githubusercontent.com/62720357/77691129-0176c980-6f6a-11ea-968f-e6e0a62b13d1.png)

You can download all 68 of the pictures I took and used from here:

https://www.dropbox.com/s/27v8yo03w36wrvv/Glue%20Stick%202.zip?dl=0

I've also tried a pen:
![image](https://user-images.githubusercontent.com/62720357/77691010-d42a1b80-6f69-11ea-9b9a-2487e23bc6aa.png)

and a USB stick:
![image](https://user-images.githubusercontent.com/62720357/77691606-d80a6d80-6f6a-11ea-8094-985d98046ac4.png)

Can someone please help me? I need to know if the problem is with my cell phone camera (maybe i used the wrong sensor width?) or is it because I'm not taking pictures in a proper way?

**Desktop:**
- OS: win 10
- Meshroom version: 2019.2.0
- Phone: Samsung Galaxy A8 A530W
- GPU: NVIDIA GeForce RTX 2080 Ti

**Comment by natowi** [comment]
Your objects are not suited for photogrammetry. Try something easier like rocks, wood/bark,  ... basically everything that has a irregular, multicoloured and non-reflective surface. Read some guides [like this one](https://www.tested.com/art/makers/460142-art-photogrammetry-how-take-your-photos/) for details.

**Comment by ata136** [comment]
@natowi Thank you for your feedback. I'll try another object to see what the results look like. :)
