### ISSUE TITLE
Stuck on PrepareDenseScene

### ISSUE THREAD

**Issue by danielbijmolen** [alicevision/meshroom#845]
Hey everyone,

The calculation process keeps getting stuck at PrepareDenseScene and I'm not quite sure whats causing this problem.

This is the error I keep getting:

[6/11](1/2) PrepareDenseScene
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: C:\GitHub\vcpkg\buildtrees\hdf5\src\hdf5-c7a3a597c4\hdf5-1.10.5\src\H5F.c line 370 in H5Fis_hdf5(): unable open file
    major: File accessibilty
    minor: Not an HDF5 file
  #001: C:\GitHub\vcpkg\buildtrees\hdf5\src\hdf5-c7a3a597c4\hdf5-1.10.5\src\H5Fint.c line 826 in H5F__is_hdf5(): unable to open file
    major: Low-level I/O
    minor: Unable to initialize object
  #002: C:\GitHub\vcpkg\buildtrees\hdf5\src\hdf5-c7a3a597c4\hdf5-1.10.5\src\H5FD.c line 734 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: C:\GitHub\vcpkg\buildtrees\hdf5\src\hdf5-c7a3a597c4\hdf5-1.10.5\src\H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = 'C:/Users/Dani├½l/Documents/MeshroomCache/StructureFromMotion/6a2188665a2cc862356d6f801214a5e6beb9c025/sfm.abc', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
 - commandLine: aliceVision_prepareDenseScene  --input "C:/Users/Daniël/Documents/MeshroomCache/StructureFromMotion/6a2188665a2cc862356d6f801214a5e6beb9c025/sfm.abc" --outputFileType exr --saveMetadata True --saveMatricesTxtFiles False --evCorrection False --verboseLevel info --output "C:/Users/Daniël/Documents/MeshroomCache/PrepareDenseScene/536cecea715f8b5ac2018e8123a8ac1198b5efab" --rangeStart 0 --rangeSize 40
 - logFile: C:/Users/Daniël/Documents/MeshroomCache/PrepareDenseScene/536cecea715f8b5ac2018e8123a8ac1198b5efab/0.log
 - elapsed time: 0:00:07.866755
ERROR:root:Error on node computation: Error on node "PrepareDenseScene_1(0)":
Log:
Program called with the following parameters:
 * evCorrection = 0
 * input = "C:/Users/Daniël/Documents/MeshroomCache/StructureFromMotion/6a2188665a2cc862356d6f801214a5e6beb9c025/sfm.abc"
 * output = "C:/Users/Daniël/Documents/MeshroomCache/PrepareDenseScene/536cecea715f8b5ac2018e8123a8ac1198b5efab"
 * outputFileType = "exr"
 * rangeSize = 40
 * rangeStart = 0
 * saveMatricesTxtFiles = 0
 * saveMetadata = 1
 * verboseLevel = "info"

Exporting Scene Undistorted Images
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
[18:13:22.944646][info] median Ev : 6.46271

WARNING: downgrade status on node "PrepareDenseScene_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(11)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(12)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(13)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(14)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(15)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(16)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(17)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "PrepareDenseScene_1(0)":
Log:
Program called with the following parameters:
 * evCorrection = 0
 * input = "C:/Users/Daniël/Documents/MeshroomCache/StructureFromMotion/6a2188665a2cc862356d6f801214a5e6beb9c025/sfm.abc"
 * output = "C:/Users/Daniël/Documents/MeshroomCache/PrepareDenseScene/536cecea715f8b5ac2018e8123a8ac1198b5efab"
 * outputFileType = "exr"
 * rangeSize = 40
 * rangeStart = 0
 * saveMatricesTxtFiles = 0
 * saveMetadata = 1
 * verboseLevel = "info"

Exporting Scene Undistorted Images
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
[18:13:22.944646][info] median Ev : 6.46271

I've tried rebooting and emptying the cache, I also made shure the images I'm using are stored in a local folder.

 - OS: windows 10 pro N
 - Meshroom version: Meshroom-2019.2.0-win64 (release version)

**Comment by simogasp** [comment]
> C:/Users/Dani├½l/Documents/MeshroomCache/StructureFromMotion/6a2188665a2cc862356d6f801214a5e6beb9c025/sfm.abc

Please do not use spaces or accented letters in your paths.

**Comment by danielbijmolen** [comment]
Hey,

Thank you, this did the trick, it's no longer stuck on PrepareDenseScene, however now I get the following error when it's trying to calculate the DepthMap:

[1/5](1/18) DepthMap
 - commandLine: aliceVision_depthMapEstimation  --input "C:/Users/daniel/Meshroom-2019.2.0/projects/nathan/MeshroomCache/StructureFromMotion/92885a37f57a7c3657c8d9fb3cfc9a343bb9d06d/sfm.abc" --imagesFolder "C:/Users/daniel/Meshroom-2019.2.0/projects/nathan/MeshroomCache/PrepareDenseScene/fbfd70115898581b2bbc3fbccad453c67209467e" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output "C:/Users/daniel/Meshroom-2019.2.0/projects/nathan/MeshroomCache/DepthMap/d8ec287bbe7b21012865421fb1f156cfbed903af" --rangeStart 0 --rangeSize 3
 - logFile: C:/Users/daniel/Meshroom-2019.2.0/projects/nathan/MeshroomCache/DepthMap/d8ec287bbe7b21012865421fb1f156cfbed903af/0.log
 - elapsed time: 0:00:34.709806
ERROR:root:Error on node computation: Error on node "DepthMap_1(0)":
Log:
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "C:/Users/daniel/Meshroom-2019.2.0/projects/nathan/MeshroomCache/PrepareDenseScene/fbfd70115898581b2bbc3fbccad453c67209467e"
 * input = "C:/Users/daniel/Meshroom-2019.2.0/projects/nathan/MeshroomCache/StructureFromMotion/92885a37f57a7c3657c8d9fb3cfc9a343bb9d06d/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/Users/daniel/Meshroom-2019.2.0/projects/nathan/MeshroomCache/DepthMap/d8ec287bbe7b21012865421fb1f156cfbed903af"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[19:21:53.926852][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce GT 750M
        - compute capability:      3.0
        - total device memory:     2048 MB
        - device memory available: 1686 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   2048
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {65536,65536}
        - max 3D array texture:    {4096,4096,4096}
        - max 2D linear texture:   {65000,65000,1048544}
        - max 2D layered texture:  {16384,16384,2048}
        - number of SM(x)s:        2
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte

[19:21:54.175182][info] Supported CUDA-Enabled GPU detected.
[19:21:54.228157][info] Found 1 image dimension(s):
[19:21:54.228157][info]         - [6000x4000]
[19:21:54.353954][info] Overall maximum dimension: [6000x4000]
[19:21:54.354953][info] Create depth maps.
number of CUDA devices: 1
   0: GeForce GT 750M
[19:21:54.355954][info] # GPU devices: 1, # CPU threads: 8
[19:21:54.355954][info] Plane sweeping parameters:
        - scale: 2
        - step: 5
[19:21:54.356952][info] PlaneSweepingCuda:
        - _nImgsInGPUAtTime: 2
        - scales: 2
        - subPixel: Yes
        - varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 361.112488, free: 1686.887451, total: 2048.000000
Device 0 memory - used: 595.612488, free: 1452.387451, total: 2048.000000
[19:22:18.922738][info] Estimate depth map, view id: 13555436

WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(11)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(12)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(13)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(14)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(15)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(16)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(17)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "DepthMap_1(0)":
Log:
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "C:/Users/daniel/Meshroom-2019.2.0/projects/nathan/MeshroomCache/PrepareDenseScene/fbfd70115898581b2bbc3fbccad453c67209467e"
 * input = "C:/Users/daniel/Meshroom-2019.2.0/projects/nathan/MeshroomCache/StructureFromMotion/92885a37f57a7c3657c8d9fb3cfc9a343bb9d06d/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/Users/daniel/Meshroom-2019.2.0/projects/nathan/MeshroomCache/DepthMap/d8ec287bbe7b21012865421fb1f156cfbed903af"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[19:21:53.926852][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce GT 750M
        - compute capability:      3.0
        - total device memory:     2048 MB
        - device memory available: 1686 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   2048
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {65536,65536}
        - max 3D array texture:    {4096,4096,4096}
        - max 2D linear texture:   {65000,65000,1048544}
        - max 2D layered texture:  {16384,16384,2048}
        - number of SM(x)s:        2
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte

[19:21:54.175182][info] Supported CUDA-Enabled GPU detected.
[19:21:54.228157][info] Found 1 image dimension(s):
[19:21:54.228157][info]         - [6000x4000]
[19:21:54.353954][info] Overall maximum dimension: [6000x4000]
[19:21:54.354953][info] Create depth maps.
number of CUDA devices: 1
   0: GeForce GT 750M
[19:21:54.355954][info] # GPU devices: 1, # CPU threads: 8
[19:21:54.355954][info] Plane sweeping parameters:
        - scale: 2
        - step: 5
[19:21:54.356952][info] PlaneSweepingCuda:
        - _nImgsInGPUAtTime: 2
        - scales: 2
        - subPixel: Yes
        - varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 361.112488, free: 1686.887451, total: 2048.000000
Device 0 memory - used: 595.612488, free: 1452.387451, total: 2048.000000
[19:22:18.922738][info] Estimate depth map, view id: 13555436

**Comment by natowi** [comment]
Please try a reconstruction with this https://github.com/alicevision/dataset_monstree dataset, it should work on your hardware.
If it succeeds, there is a problem with your images/object.
If it fails there are a few possible causes, but my guess is you have a few hundred images and there is not enough memory/disk space

**Comment by natowi** [comment]
If this problem persists, feel free to reopen the issue.
