### ISSUE TITLE
upper and lower menu part invisible [bug]

### ISSUE THREAD

**Issue by WoerVinc** [alicevision/meshroom#848]
Hi, 

getting started with meshbox but having the problem that the upper menu is seemingly out of the window. (see screenshot - file, edit, etc are not visible). Has this happened to anyone else? 

thanks a lot

![Screenshot (11)](https://user-images.githubusercontent.com/62104225/78388390-31b10e80-75e1-11ea-9dfc-ba5662fef373.png)

**Comment by natowi** [comment]
It started in windowed mode. Double click on the upper border of the Meshroom window to bring it to full window size.

**Comment by WoerVinc** [comment]
Thanks for the quick response. You mean basically maximize the window? The screenshot is already of the fullscreen mode. (I'm doubleclicking the white bar above (red arrow in this screenshot)). That doesnt resolve the issue unfortunately :/ 
![Screenshot (13)_LI](https://user-images.githubusercontent.com/62104225/78389846-c3218000-75e3-11ea-958b-757c5a6b89d6.jpg)

**Comment by natowi** [comment]
Grab and move the window first

**Comment by WoerVinc** [comment]
Restarting hasnt changed anything yet - sounds plausible though, that its a windows problem not Meshroom. Either way besides, that its working great :)!.
