### ISSUE TITLE
Interesting Paper about AI Learning [request]

### ISSUE THREAD

**Issue by barefoots** [alicevision/meshroom#854]
[https://www.youtube.com/watch?v=nCpGStnayHk](url)

This Neural Network Learned To Look Around In Real Scenes - Two Minute Papers

You probably already know all about these things or this youtube channel.

**Comment by natowi** [comment]
(https://github.com/bmild/nerf)
Thank you. The problem is not finding ML examples, it is finding someone that can implement it in Meshroom. Also the dependencies are an issue: for the binaries you would need to find a way to include tensorflow. 

https://github.com/alicevision/meshroom/issues/528
