### ISSUE TITLE
Stops at DepthMap both 2018 and 2019 version

### ISSUE THREAD

**Issue by uxblock2020** [alicevision/meshroom#858]
**Describe the bug**

It stops at DepthMap both 2018 and 2019 version, any update? thx

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: [e.g. win 10, osx, ]
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) [e.g. 2019.1]
   - Commit reference (if applicable) [e.g. 08ddbe2]

**Additional context**

**Comment by gryan315** [comment]
Do you have an Nvidia GPU?
