### ISSUE TITLE
Bad detection of CUDA capabilities having 2 gfx cards [Solved] then gfx driver (or card) reset before computing was crashing Meshroom in DepthMap node [Solved]

### ISSUE THREAD

**Issue by Saroder** [alicevision/meshroom#860]
Hi guys,

I have much hopes about Mushroom so I tried all what was looking obvious or what I could read about this kind of problem (bad detection of CUDA capabilities).
But nothing could help, I'm blocked at :
`ERROR:root:Error during Graph execution Error on node "DepthMap_1(0)":`
...
```
[02:24:12.903341][warning] Could not determine number of CUDA cards in this syst
em
[02:24:12.900341][warning] No CUDA-Enabled GPU.
[02:24:12.904341][error] cudaGetDeviceCount failed: CUDA driver version is insuf
ficient for CUDA runtime version
[02:24:12.906341][info] Can't find CUDA-Enabled GPU.
[02:24:12.906341][error] This program needs a CUDA-Enabled GPU (with at least co
mpute capablility 2.0).
```

The problem is the same on 2 windows 7 computers (I may try with Ubunutu soon but it most probably will be not better or worst...)

**Both computers have 2 gfx cards**, a basic built in one and a good old gaming Nvidia with the latest working driver (NVIDIA GeForce GTX 560 Ti with CUDA 5.0.1 compute capability 2.1 and on the other computer Nvidia GTX680M CUDA 7.x compute capability 3.0)
On this one I updated the Nvidia driver a few days ago for Blender 2.82 and for Blender it solved the problem I had.

You can see CUDA version and settings of the driver on this screenshot, (CUDA set to "All" for Meshroom.exe...)

![Meshroom_CUDA_BUG](https://user-images.githubusercontent.com/63935162/79676778-ca52ab80-81e9-11ea-932a-bcc1d1559336.png)

Other details here : 
![Meshroom_CUDA_BUG2](https://user-images.githubusercontent.com/63935162/79677708-87e29c00-81f4-11ea-8374-c2f86a663cf8.png)

I was about to try installing a CUDA toolkit in case it could help...
If it works I'll update in a fex minutes but else...
You're my last hope because I would really like to get meshes of objects around ! :D

**Comment by Saroder** [comment]
Finally I thought it could be important for other people to know that, seeing CUDA toolkit 8.0 should be the higher version to use with a 2.1 compute capability card,  I tried installing it and...**it solved this detection problem !**, now the GTX is recognized and used :
```
[08:00:54.244061][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce GTX 560 Ti
        - compute capability:      2.1
        - total device memory:     1024 MB
        - device memory available: 700 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   1536
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {65535,65535,65535}
        - max 2D array texture:    {65536,65535}
        - max 3D array texture:    {2048,2048,2048}
        - max 2D linear texture:   {65000,65000,1048544}
        - max 2D layered texture:  {16384,16384,2048}
        - number of SM(x)s:        8
        - registers per SM(x):     32768
        - registers per block:     32768
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte

[08:00:55.516268][info] Supported CUDA-Enabled GPU detected.
[08:00:55.832669][info] Found 1 image dimension(s):
[08:00:55.832669][info]         - [3456x4608]
[08:00:58.376482][info] Overall maximum dimension: [3456x4608]
[08:00:58.376482][info] Create depth maps.
number of CUDA devices: 1
   0: GeForce GTX 560 Ti
[08:00:58.425283][info] # GPU devices: 1, # CPU threads: 4
[08:00:58.425283][info] Plane sweeping parameters:
        - scale: 2
        - step: 4
[08:00:58.426283][info] PlaneSweepingCuda:
        - _nImgsInGPUAtTime: 2
        - scales: 2
        - subPixel: Yes
        - varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 323.914063, free: 700.085938, total: 1024.000000
Device 0 memory - used: 475.914063, free: 548.085938, total: 1024.000000
[08:01:41.630531][info] Estimate depth map, view id: 1241995
Device 0 memory - used: 608.015625, free: 415.984375, total: 1024.000000
total size of volume map in GPU memory: 132.046875
nDepths 939, nDepthsToSearch 939
ps_computeSimilarityVolume elapsed time: 30.000000 ms
```
Finally, I got this log BUT Meshroom crashed at this step, so I will have to solve a new problem...

I must check a few things more about the new driver, as it looks like the Gfx driver was changed and not only the CUDA part... But Blender still works !

**Comment by AAronPurple** [comment]
Hi, can you provide a screen where it’s visible the difference in performance between only cpu computation and cpu + Cuda computation? I’m waiting to try my notebook with i7 7700HQ and GTX 1050 Ti to find which difference are between cpu performance and added Cuda performance. Thank you.

**Comment by natowi** [comment]
@Saroder yes, the tdr solution is documented here
https://github.com/alicevision/meshroom/wiki/DepthMap-slow-or-red-bar-or-crash

@AAronPurple DepthMap is Cuda only. But in FeatureExtraction you can disable ForceCPU extraction to use the GPU (cuda only, requires higher cc), this can speed up the extraction significantly.

**Comment by AAronPurple** [comment]
Sorry, what’s mean “cc”?

**Comment by natowi** [comment]
https://github.com/alicevision/popsift used in _FeatureExtraction_ needs cuda compute capability v3.  (The DepthMap node requires compute capability 2.1 only)
