### ISSUE TITLE
[bug] DepthMap fails with ERROR:root:Error on node computation: Error on node "DepthMap_1(1)"

### ISSUE THREAD

**Issue by jmf13** [alicevision/meshroom#861]
**Describe the bug**
I try to setup a computer to be able to use Meshroom. I installed Meshroom-2019.2.0.
The dataset Monster tree mini3 is working for all dataflow. Homever the mini6 dataset fails at DepthMap stage.

I can't interpret from the error message what's wrong.

I updated to latest Nvidia drivers, and the issue is the same.

Help welcomed :-)

**To Reproduce**
Systematically the same error on my setup

**Expected behavior**
Suceed the processing of the Monstertree mini6 dataset

**Screenshots**
Not Applicable

**Log**
The log is:
``[7/11](1/2) DepthMap
 - commandLine: aliceVision_depthMapEstimation  --input "C:/Users/Chloe Fourneron/Desktop/Scan Tiny/MeshroomCache/StructureFromMotion/73b6536dc5b0617d88e4a761c0e554714cab6f55/sfm.abc" --imagesFolder "C:/Users/Chloe Fourneron/Desktop/Scan Tiny/MeshroomCache/PrepareDenseScene/4420a24971611c5b881c54a1435dda867bc94d7b" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output "C:/Users/Chloe Fourneron/Desktop/Scan Tiny/MeshroomCache/DepthMap/d2c8de64f3255945478549af8efd001641b81f0a" --rangeStart 0 --rangeSize 3
 - logFile: C:/Users/Chloe Fourneron/Desktop/Scan Tiny/MeshroomCache/DepthMap/d2c8de64f3255945478549af8efd001641b81f0a/0.log
 - elapsed time: 0:03:18.221290

[7/11](2/2) DepthMap
 - commandLine: aliceVision_depthMapEstimation  --input "C:/Users/Chloe Fourneron/Desktop/Scan Tiny/MeshroomCache/StructureFromMotion/73b6536dc5b0617d88e4a761c0e554714cab6f55/sfm.abc" --imagesFolder "C:/Users/Chloe Fourneron/Desktop/Scan Tiny/MeshroomCache/PrepareDenseScene/4420a24971611c5b881c54a1435dda867bc94d7b" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output "C:/Users/Chloe Fourneron/Desktop/Scan Tiny/MeshroomCache/DepthMap/d2c8de64f3255945478549af8efd001641b81f0a" --rangeStart 3 --rangeSize 3
 - logFile: C:/Users/Chloe Fourneron/Desktop/Scan Tiny/MeshroomCache/DepthMap/d2c8de64f3255945478549af8efd001641b81f0a/1.log
 - elapsed time: 0:00:23.654525
ERROR:root:Error on node computation: Error on node "DepthMap_1(1)":
Log:
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "C:/Users/Chloe Fourneron/Desktop/Scan Tiny/MeshroomCache/PrepareDenseScene/4420a24971611c5b881c54a1435dda867bc94d7b"
 * input = "C:/Users/Chloe Fourneron/Desktop/Scan Tiny/MeshroomCache/StructureFromMotion/73b6536dc5b0617d88e4a761c0e554714cab6f55/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/Users/Chloe Fourneron/Desktop/Scan Tiny/MeshroomCache/DepthMap/d2c8de64f3255945478549af8efd001641b81f0a"
 * rangeSize = 3
 * rangeStart = 3
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[12:47:52.882775][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce 840M
        - compute capability:      5.0
        - total device memory:     2048 MB
        - device memory available: 1683 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   2048
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {65536,65536}
        - max 3D array texture:    {4096,4096,4096}
        - max 2D linear texture:   {65536,65536,1048544}
        - max 2D layered texture:  {16384,16384,2048}
        - number of SM(x)s:        3
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte

[12:47:53.211191][info] Supported CUDA-Enabled GPU detected.
[12:47:53.211191][info] Found 1 image dimension(s):
[12:47:53.211191][info]         - [4032x3024]
[12:47:53.240829][info] Overall maximum dimension: [4032x3024]
[12:47:53.240829][info] Create depth maps.
number of CUDA devices: 1
   0: GeForce 840M
[12:47:53.245289][info] # GPU devices: 1, # CPU threads: 4
[12:47:53.246281][info] Plane sweeping parameters:
        - scale: 2
        - step: 3
[12:47:53.246439][info] PlaneSweepingCuda:
        - _nImgsInGPUAtTime: 2
        - scales: 2
        - subPixel: Yes
        - varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 364.384369, free: 1683.615601, total: 2048.000000
Device 0 memory - used: 482.509369, free: 1565.490601, total: 2048.000000
[12:47:53.261150][info] Found only 4/10 nearest cameras for view id: 1902788980
[12:47:53.278603][info] Found only 4/6 nearest cameras for view id: 1902788980
[12:48:05.033088][info] Estimate depth map, view id: 1902788980

WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "DepthMap_1(1)":
Log:
Program called with the following parameters:
 * downscale = 2
 * exportIntermediateResults = 0
 * imagesFolder = "C:/Users/Chloe Fourneron/Desktop/Scan Tiny/MeshroomCache/PrepareDenseScene/4420a24971611c5b881c54a1435dda867bc94d7b"
 * input = "C:/Users/Chloe Fourneron/Desktop/Scan Tiny/MeshroomCache/StructureFromMotion/73b6536dc5b0617d88e4a761c0e554714cab6f55/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/Users/Chloe Fourneron/Desktop/Scan Tiny/MeshroomCache/DepthMap/d2c8de64f3255945478549af8efd001641b81f0a"
 * rangeSize = 3
 * rangeStart = 3
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "info"

[12:47:52.882775][info] CUDA-Enabled GPU.
Device information:
        - id:                      0
        - name:                    GeForce 840M
        - compute capability:      5.0
        - total device memory:     2048 MB
        - device memory available: 1683 MB
        - per-block shared memory: 49152
        - warp size:               32
        - max threads per block:   1024
        - max threads per SM(X):   2048
        - max block sizes:         {1024,1024,64}
        - max grid sizes:          {2147483647,65535,65535}
        - max 2D array texture:    {65536,65536}
        - max 3D array texture:    {4096,4096,4096}
        - max 2D linear texture:   {65536,65536,1048544}
        - max 2D layered texture:  {16384,16384,2048}
        - number of SM(x)s:        3
        - registers per SM(x):     65536
        - registers per block:     65536
        - concurrent kernels:      yes
        - mapping host memory:     yes
        - unified addressing:      yes
        - texture alignment:       512 byte
        - pitch alignment:         32 byte

[12:47:53.211191][info] Supported CUDA-Enabled GPU detected.
[12:47:53.211191][info] Found 1 image dimension(s):
[12:47:53.211191][info]         - [4032x3024]
[12:47:53.240829][info] Overall maximum dimension: [4032x3024]
[12:47:53.240829][info] Create depth maps.
number of CUDA devices: 1
   0: GeForce 840M
[12:47:53.245289][info] # GPU devices: 1, # CPU threads: 4
[12:47:53.246281][info] Plane sweeping parameters:
        - scale: 2
        - step: 3
[12:47:53.246439][info] PlaneSweepingCuda:
        - _nImgsInGPUAtTime: 2
        - scales: 2
        - subPixel: Yes
        - varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 364.384369, free: 1683.615601, total: 2048.000000
Device 0 memory - used: 482.509369, free: 1565.490601, total: 2048.000000
[12:47:53.261150][info] Found only 4/10 nearest cameras for view id: 1902788980
[12:47:53.278603][info] Found only 4/6 nearest cameras for view id: 1902788980
[12:48:05.033088][info] Estimate depth map, view id: 1902788980``

**Desktop (please complete the following and other pertinent information):**
 - OS: W10 64 bits
 - Python version [e.g. 2.6]
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: release version: 2019.2.0

**Additional context**
GPU is a Geforce 840M, with CUDA and compute capability of 5

**Comment by natowi** [comment]
How much RAM do you have installed?

**Comment by jmf13** [comment]
I have 8Go RAM (just the required minimum)

**Comment by natowi** [comment]
8gb are enough for this small dataset. You can check this https://github.com/alicevision/meshroom/wiki/Error:-This-program-needs-a-CUDA-Enabled-GPU#this-error-message-on-a-computer-with-nvidia-gpu

**Comment by jmf13** [comment]
I have looked at all the link thqt you provided. In my case, Meshrooms sees that I have a CUDA enabled GPU.

I had a look at https://github.com/alicevision/meshroom/wiki/DepthMap-slow-or-red-bar-or-crash#depthmap-crash--freeze

Could it be a  GPU drivers crash with long computations (TDR crash) ? (but in my case Meshroom does not crash, nor outputs a "TDR" error in the logs).

**Comment by natowi** [comment]
> Meshrooms sees that I have a CUDA enabled GPU.
Did you check in the nvidia settings that the gpu is used for Meshroom?

You could try the described TDR solution and see if it helps.

**Comment by jmf13** [comment]
I have modified the Registeries related to TDR according to the Howto. With the modification, I have succeeded to calculate the Monster Tree 6 dataset. I'm now trying to calculate the Monster Tree full dataset.
