### ISSUE TITLE
Wrong values in mtl ? [bug]

### ISSUE THREAD

**Issue by Saroder** [alicevision/meshroom#863]
Hi guys,

Importing a .obj (with mtl and texture files) give me ...a big mess, textures are not right applied...
Tried in Blender 2.82 (and a 2.90 alphabuild or something like this)
Looking at the mtl I wonder if it's normal to get the same values for all my different texture files.

```
# 
# Wavefront material file
# Created with AliceVision
# 

newmtl TextureAtlas_1001
Ka  0.6 0.6 0.6
Kd  0.6 0.6 0.6
Ks  0.0 0.0 0.0
d  1.0
Ns  0.0
illum 2
map_Kd texture_1001.png
newmtl TextureAtlas_1002
Ka  0.6 0.6 0.6
Kd  0.6 0.6 0.6
Ks  0.0 0.0 0.0
d  1.0
Ns  0.0
illum 2
map_Kd texture_1002.png
newmtl TextureAtlas_1003
Ka  0.6 0.6 0.6
Kd  0.6 0.6 0.6
Ks  0.0 0.0 0.0
d  1.0
Ns  0.0
illum 2
map_Kd texture_1003.png
newmtl TextureAtlas_1004
Ka  0.6 0.6 0.6
Kd  0.6 0.6 0.6
Ks  0.0 0.0 0.0
d  1.0
Ns  0.0
illum 2
map_Kd texture_1004.png
```

Am I doing something wrong or there's a bug here, or somewhere ... ?

**Comment by fabiencastan** [comment]
Does it loads correctly in the Meshroom 3D viewer?
Do you have the same problem on all datasets or only on a specific one?

**Comment by Saroder** [comment]
Thanx for trying to help, it's my first mesh... (I had, and still have much trouble on my other pc having Meshroom to work till the end...)
In Meshroom it was OK, just loading in Blender (2.82) the texture are not oriented like they should be.

**Comment by Saroder** [comment]
I wanted to check again, but can't figure out how to reload the textured mesh in Meshroom (Have I to copy everything again in the Texturing folder ?).

**Comment by fabiencastan** [comment]
You can drag&drop your OBJ file in the 3D viewer of Meshroom.

**Comment by Saroder** [comment]
Oh OK thank you I'll try (assuming it will find .mtl and .png in the same folder), too easy for me to think about it, I searched a few minute a (very?) old school "Load pictures" before I saw I could drag & drop :-/   But what do you think about the values in the .mtl, I'm just a newbie in 3D gfx but... for me it looks strange seeing no more details in the .mtl (I guess there are missing parts when I look at this : http://paulbourke.net/dataformats/mtl/ or https://people.cs.clemson.edu/~dhouse/courses/405/docs/brief-mtl-file-format.html, it looks like texture's mapping is missing in my mtl file)

**Comment by fabiencastan** [comment]
Your mtl looks fine.

**Comment by Saroder** [comment]
Yest it loaded right... I'll try to have a look at Blender again, I compute another mesh too... I thought most of people would work in blender after Meshroom finish his job, but maybe not... I was really not expecting suh a problem to import in Blender -_-

**Comment by natowi** [comment]
Did you try setting the texture resolution in Texturing  to a lower value? The texture might not be able to load due to hardware limitations. You can drag and drop the obj to _Meshlab_ for testing.

**Comment by Saroder** [comment]
OK thanks, I'll have a look at this but in Meshroom 3D viewer it loads fine
and blender loads my textures too , the problem is they're not in the right
place or side. I saw the data for textures positioning is in the .obj and
not in the .mtl as I first thought so I tried a 2 ways conversion obj>
sthing>obj with a web converter... I'll try to see what happen like this
too... Now all others problems with cuda and crashes in later nodes are
solved so I keep hope to solve this last texture orientation issue... a big
thank you for trying to help. Meshroom is nice enough for me to keep
fighting 😁   I just really need to import his job in Blender... Can
someone here import in Blender 2.82 (the last stable release) without
problem ?

**Comment by natowi** [comment]
Did you enable the texture to show in the Blender Layout tab?

![blend2](https://user-images.githubusercontent.com/8138537/80029329-ed7da380-84e6-11ea-90ef-03ca6b6e0f68.JPG)

**Comment by Saroder** [comment]
Thanks again natowi,

Yes I enabled textures, I'm not so lost or high :D Otherwise there would be NO texture at all ! ;-)
But like this it's just ...a big mess.
I tried to load the file from the online converter... but the converter just throw away the texture part -_-

Then I tried Meshlab and it loads my object and mtl fine,textured like in Meshrom 3D Viewer...
I'm really happy about this !

So full of hopes I tried 3 export from meshlab with textures, results :
OBJ =>(In blender 2.82) messy textures as before.
DAE =>exactly the same messy textures as before again.
PLY =>No textures...
:'(

And if I load back those three files in Meshlab everything is OK, including the textures in the ply, they doesn't fly away...

I feel a lil bit desperate about blender imports, I can't believe there are compatibility problems like this nor that 3 file types imports are broken in Blender 2.82

In your screen capture, you imported a .obj from Meshroom in Blender 2.82  or another version ? Or... you just got this picture somehow or somewhere without making your own import from Meshroom object ?

**Comment by natowi** [comment]
I loaded the obj in Blender 2.82.

> Yes I enabled textures, I'm not so lost or high :D Otherwise there would be NO texture at all ! ;-)
> But like this it's just ...a big mess.

Sometimes one misses the small things, so I just wanted to be sure.

Can you share a screenshot on _how_ your "big mess" looks like? Maybe this can give a hint on the problem.

**Comment by Saroder** [comment]
Oh you did it, so its only here... :O   I dream it would work, I really don't understand why it doesn't but it looks more and more like it's on Blender's side... (I know often "PEBCAK" but... I guess it's something else here because yes I'm a newbie in 3D graphics -it's my really first photogrammetric try- but I'm not really a lambda user, I was yet programming little games and many other useless things 35 years ago ! And don't say I'm old, I'm just not so young now... :p)

> Sometimes one misses the small things, so I just wanted to be sure. (Rule one when troubleshooting: never assume anything ;-) )

Sure, no problem.

A few times I wondered if a screen could be useful, now you ask for it so here it is :
![Sans titre](https://user-images.githubusercontent.com/63935162/80104272-fc139b80-8576-11ea-982b-55578872c933.png)
![untitled](https://user-images.githubusercontent.com/63935162/80104298-0afa4e00-8577-11ea-978d-6ec7b389eacd.png)

And you can see with the third one that it's OK in Meshlab... but export from Meshlab to Blender leads to the same disaster... -_-
![BergerBois3_01](https://user-images.githubusercontent.com/63935162/80104441-69bfc780-8577-11ea-82b1-42793754e10c.png)

> You can still try to manually apply the texture to your obj
Yes, as soon as I would learn how to do it I could... But I think it would be quite much work for nothing but a poor result.. :(   I still want to believe we will really solve this problem. Hope the screens could help you or someone else to understand what happen and know how to avoid this result.

**Comment by natowi** [comment]
Do you have one or multiple texture files? It looks like there are multiple texture files and one or more are not loaded in blender.

**Comment by Saroder** [comment]
I tried to ask in Blender chat... But I had no much help.

There are 4 textures and it looks like they are all loaded, but... I don't really know how they're applied -_-

Look at the very dark areas everywhere for example. I don't even really know where this black comes from, it looks darker than the shutter, and why it's everywhere.

But I'll investigate in this way, because some part of the textures are at the right places, others are missing, and I think some of them are maybe not at the right places... But there's maybe something to find about why some parts are at the right place and other parts are just missing...

Thank you for continu trying natowi. :-)

Maybe being much more used to this kind of things you understand something seeing the textures ?
They was too big to upload here, so reduced they are like this (they was between 20 and 34 MB).
![texture_1003_small](https://user-images.githubusercontent.com/63935162/80138087-90482780-85a4-11ea-8ad5-311f570d12e4.jpg)
![texture_1004_small](https://user-images.githubusercontent.com/63935162/80138089-9211eb00-85a4-11ea-9040-961d79a4493e.jpg)
![texture_1001_small](https://user-images.githubusercontent.com/63935162/80138090-93431800-85a4-11ea-8705-9d8c7c7b4582.jpg)
![texture_1002_small](https://user-images.githubusercontent.com/63935162/80138094-94744500-85a4-11ea-8ef6-8b18fa36af07.jpg)

**Comment by natowi** [comment]
Can you try again, using  1024 for texturing and ABF/LSCM in the texturing node? This should produce one texture file with more connected texture areas, which is easier to check. Then check again in Blender

**Comment by Saroder** [comment]
I'll try later, thx

(In blender the "Texture limit size" was off...)

**Comment by Saroder** [comment]
Computing with 1024/LSCM  for texturing...

**Comment by schmebs** [comment]
I once had trouble loading objs from Meshroom into other programs, until I discovered that Meshroom encodes the obj+mtl+png files in UDIM coordinates as default, which my other program (Meshmixer) couldn't handle. The "Use UDIM" option is in the texturing node. Try turning that off and see if it works.

 ![Capture](https://user-images.githubusercontent.com/58179311/80455409-f7ab0200-892b-11ea-89f9-1f3c1c783504.PNG)

**Comment by Saroder** [comment]
Thank you schmebs but it is not the problem, I had mesh created by Meshroom loading fine in blender with this "Use UDIM" box checked.
