### ISSUE TITLE
Correct AliceVision build necessary to run the 'dev' branch[question]

### ISSUE THREAD

**Issue by raphael2692** [alicevision/meshroom#865]
Hello, 

I am trying to test the new feature in the dev version of meshroom. I tried to run the dev branch uncompiled via script along with the windows-snapshot build named "Merge pull request https://github.com/alicevision/AliceVision/pull/770 from alicevision/remove_cxsparse" which seemed the latest. However, with this setup defualt pipe files at Feature Extraction node without a clear hint ("failed to extract sift feature").  I tried to use it with the 2019.2 release binaries but in this case the error was: "--method is not a valid parameter" in the Image Matching node. 

The batch script I use to start meshroom is the following: 

```batch
set PYTHONPATH=%CD% 
set PATH="path to alicevision bin";%PATH%
set ALICEVISION_SENSOR_DB="path to alicevision\cameraSensors.db"
set ALICEVISION_VOCTREE="path to alicevision\vlfeat_K80L3.SIFT.tree"
python meshroom/ui
```

Notice that I have no problem running the default pipeline with the same input photos and the stable releases of bot AliceVision and Meshroom.

**Comment by fabiencastan** [comment]
> However, with this setup defualt pipe files at Feature Extraction node without a clear hint ("failed to extract sift feature").

Could you put the FeatureExtraction node in verbose=trace and send the full log?
Could you also monitor your RAM usage during the FeatureExtraction computation?

**Comment by raphael2692** [comment]
I was not able to reproduce the feature extraction failure, with either the stable build or the afore mentioned snapshot. Instead, I got the failure again n image matching. The log (trace mod ha only 2 lines:

```
ERROR: unrecognised option '--method'
Usage:
```

For the record, the machine has 64 GB of ram and the input images are 6 (4000x3000). Using meshroom 2019.2 with the packaged AliceVision bin the ram caps at 50% usage.  During the test no memory leak occurred.

**Comment by raphael2692** [comment]
This is the log i get running alicevision snapshopt bin only. 
````
C:\xxxxx\alice_vision_snapshot\bin>.\aliceVision_featureExtraction.exe  -i "cache\\cameraInit.sfm" -o "cache\\" -v "trace"
Program called with the following parameters:
 * describerPreset = "normal" (default)
 * describerTypes = "sift" (default)
 * forceCpuExtraction = 0 (default)
 * input = "cache\\cameraInit.sfm"
 * maxThreads = 0 (default)
 * output = "cache\"
 * rangeSize = 1 (default)
 * rangeStart = -1 (default)
 * verboseLevel = "trace"

[17:26:36.564293][debug] Job max memory consumption: 944962832 B
[17:26:36.564293][debug] Memory information:
        - Total RAM:  63.9515 GB
        - Free RAM:   57.9117 GB
        - Total swap: 131072 GB
        - Free swap:  131068 GB

[17:26:36.569291][debug] # threads for extraction: 6
[17:26:36.937174][trace] Read image C:\\Users\\demo-emmeemme\\Desktop\\meshroom_bench\\input\5.tiff (encoded in sRGB colorspace).
[17:26:36.951169][trace] Read image C:\\Users\\demo-emmeemme\\Desktop\\meshroom_bench\\input\0.tiff (encoded in sRGB colorspace).
[17:26:36.964167][trace] Read image C:\\Users\\demo-emmeemme\\Desktop\\meshroom_bench\\input\3.tiff (encoded in sRGB colorspace).
[17:26:36.981158][trace] Read image C:\\Users\\demo-emmeemme\\Desktop\\meshroom_bench\\input\1.tiff (encoded in sRGB colorspace).
[17:26:36.994154][trace] Read image C:\\Users\\demo-emmeemme\\Desktop\\meshroom_bench\\input\2.tiff (encoded in sRGB colorspace).
[17:26:37.041141][trace] Read image C:\\Users\\demo-emmeemme\\Desktop\\meshroom_bench\\input\4.tiff (encoded in sRGB colorspace).
[17:26:37.064132][info] Extracting sift features from view 'C:\\Users\\demo-emmeemme\\Desktop\\meshroom_bench\\input\5.tiff' [cpu]
[17:26:37.082127][info] Extracting sift features from view 'C:\\Users\\demo-emmeemme\\Desktop\\meshroom_bench\\input\3.tiff' [cpu]
[17:26:37.092633][info] Extracting sift features from view 'C:\\Users\\demo-emmeemme\\Desktop\\meshroom_bench\\input\0.tiff' [cpu]
[17:26:37.092633][info] Extracting sift features from view 'C:\\Users\\demo-emmeemme\\Desktop\\meshroom_bench\\input\1.tiff' [cpu]
[17:26:37.108629][info] Extracting sift features from view 'C:\\Users\\demo-emmeemme\\Desktop\\meshroom_bench\\input\2.tiff' [cpu]
[17:26:37.124623][info] Extracting sift features from view 'C:\\Users\\demo-emmeemme\\Desktop\\meshroom_bench\\input\4.tiff' [cpu]
```

**Comment by natowi** [comment]
I have some strange behaviour, too; When I use the latest Alicevision snapshot, DepthMap terminates with "cudart64_92.dll missing". When using the Meshroom ([this](https://github.com/alicevision/meshroom/pull/875)) snapshot, the GUI crashes while running FeatureExtracion. I have yet to investigate the source of the problems.

**Comment by miquelrosell99** [comment]
After enabling verbose level to Trace i get a blank screen in Log secrion, but this is what the command line shows:
[1/1](1/200) DepthMap
 - commandLine: aliceVision_depthMapEstimation  --input "F:/Documentos/Universitat/GEM/Quart/TFG/Projectes Meshroom/Tests/Same Orientation VS Different Vertical/MeshroomCache/StructureFromMotion/2417bfa85a443fbe52236c954a21d6c5d6668d91/sfm.abc" --imagesFolder "F:/Documentos/Universitat/GEM/Quart/TFG/Projectes Meshroom/Tests/Same Orientation VS Different Vertical/MeshroomCache/PrepareDenseScene/0cd82a33e87c6d550e5905a9638d24aad5fe6b69" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel trace --output "F:/Documentos/Universitat/GEM/Quart/TFG/Projectes Meshroom/Tests/Same Orientation VS Different Vertical/MeshroomCache/DepthMap/19542b7b4ed2ddafe379aeaf918355fb48d10350" --rangeStart 0 --rangeSize 3
 - logFile: F:/Documentos/Universitat/GEM/Quart/TFG/Projectes Meshroom/Tests/Same Orientation VS Different Vertical/MeshroomCache/DepthMap/19542b7b4ed2ddafe379aeaf918355fb48d10350/0.log
 - elapsed time: 0:00:00.188534
[2020-05-09 17:45:49,507][ERROR] Error on node computation: Error on node "DepthMap_1(0)":
Log:

WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(11)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(12)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(13)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(14)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(15)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(16)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(17)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(18)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(19)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(20)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(21)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(22)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(23)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(24)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(25)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(26)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(27)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(28)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(29)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(30)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(31)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(32)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(33)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(34)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(35)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(36)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(37)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(38)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(39)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(40)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(41)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(42)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(43)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(44)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(45)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(46)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(47)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(48)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(49)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(50)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(51)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(52)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(53)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(54)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(55)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(56)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(57)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(58)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(59)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(60)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(61)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(62)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(63)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(64)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(65)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(66)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(67)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(68)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(69)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(70)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(71)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(72)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(73)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(74)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(75)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(76)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(77)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(78)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(79)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(80)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(81)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(82)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(83)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(84)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(85)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(86)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(87)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(88)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(89)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(90)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(91)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(92)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(93)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(94)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(95)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(96)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(97)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(98)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(99)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(100)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(101)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(102)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(103)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(104)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(105)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(106)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(107)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(108)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(109)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(110)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(111)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(112)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(113)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(114)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(115)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(116)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(117)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(118)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(119)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(120)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(121)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(122)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(123)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(124)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(125)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(126)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(127)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(128)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(129)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(130)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(131)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(132)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(133)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(134)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(135)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(136)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(137)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(138)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(139)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(140)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(141)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(142)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(143)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(144)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(145)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(146)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(147)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(148)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(149)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(150)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(151)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(152)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(153)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(154)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(155)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(156)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(157)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(158)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(159)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(160)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(161)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(162)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(163)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(164)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(165)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(166)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(167)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(168)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(169)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(170)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(171)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(172)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(173)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(174)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(175)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(176)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(177)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(178)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(179)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(180)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(181)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(182)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(183)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(184)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(185)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(186)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(187)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(188)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(189)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(190)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(191)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(192)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(193)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(194)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(195)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(196)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(197)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(198)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(199)" from Status.SUBMITTED to Status.NONE
[2020-05-09 17:46:02,445][ERROR] Error during Graph execution Error on node "DepthMap_1(0)":
Log:


Using latest AliceVision compilation. ImageMatching works, but DepthMap doesn't

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/issues/887#issuecomment-626220201

**Comment by natowi** [comment]
Fixed by https://github.com/alicevision/AliceVision/pull/776
