### ISSUE TITLE
My reconstruction is not looking right

### ISSUE THREAD

**Issue by danielkp1234** [alicevision/meshroom#866]
**Describe the problem**
Hello, I am having a problem using meshroom to create a duplicate of my lightsaber in 3d.
Below you can see some screenshots of the mesh. right on the table where the lightsaber is supposed to be it's fully messed up.
the camera I am using is a Samsung Galaxy s8.
**Screenshots**
![image](https://user-images.githubusercontent.com/19412591/80281661-09628e80-870d-11ea-894b-1a45a1c631c9.png)
Right here you can see they are just an empty void where the lightsaber should be and a lot if things nearby instead have a green colour cast on them.
**Dataset**
Here you can see some of the images I used to generate the mesh(i had over 200)
https://imgur.com/a/0m9avqj
OS: Windows 10 
 - Meshroom version: 2019.2

**Comment by natowi** [comment]
**Your object is not suited for photogrammetry.** (single coloured, featureless, does not fill image screen)
Also you can model the lightsaber in 5 minutes from scratch, so no need to waste time for photogrammetry.

**Comment by danielkp1234** [comment]
@natowi Cant  seem to figure out how to model something to look exactly like my real prop

**Comment by natowi** [comment]
Than scan the handle only. Take close ups and avoid reflections. Then add the green light (solid or effect) in a 3d software.

For single coloured objects with reflections, it is recommended to cover the surface with something that adds texture. You could cover the green light part in masking tape and apply some pen strokes to add features. This will result in a rough geometry but this can be smoothed.

But again, it is easier to model objects with easy geometry and no special features than to prepare the object, shoot the images and reconstruct the model using photogrammetry

Here is a list of some tutorials you can check out to familiarize yourself with Meshroom and Photogrammetry https://github.com/alicevision/meshroom/wiki/Tutorials
