### ISSUE TITLE
serial number of images to identify camera/lens device

### ISSUE THREAD

**Issue by anassnouri** [alicevision/meshroom#869]
Dear fellows, 
i'm novice to photogrametry  and I decided to use Meshroom for my first project. My problem is that I'm struggling with this warning : "some image(s) have no serial number to identify the camera/lens device".  However, the small circle at the tof-left of my images is green. Also i've added in the database "cameraSensors.db" the following  line to identify my Samsung Glaxy S8 (SM-G950FD) : Samsung;SM-G950F;4.2 

Can you help me ? 

Thanks

**Comment by simogasp** [comment]
Hi,
this is just a warning for an advanced feature, if the images are correctly
identified as Samsung and the icon is green then everything is fine and it
should work

S.

**Comment by anassnouri** [comment]
Ah ok, perfect. Thank you
