### ISSUE TITLE
Texturing after Retopology 

### ISSUE THREAD

**Issue by ryguystye** [alicevision/meshroom#870]
[I'm trying to follow the instructions here](https://github.com/alicevision/meshroom/wiki/Texturing-after-external-re-topology) to texture a mesh that I've edited (Tried with Blender and Instant Meshes). Upon running the Texturing node, it fails because it detects 0 triangles in the obj. mesh that I've set.

I looked at older reports here on github of the same problem and can't find a solution in any of them. I'm using the Windows 2019.2.0 version, if that matters.

**Comment by NexTechAR-Scott** [comment]
Your external mesh will fail if it has externally computed normals.

Export your obj from Blender without Normals

On my list of things to look at is how to get Instant Meshes to export without normals.

**Comment by natowi** [comment]
> On my list of things to look at is how to get Instant Meshes to export without normals.
> Also, make sure you are not generating a quad mesh, Instant Meshes default.

@NexTechAR-Scott Take a look at this InstantMeshes plugin, https://github.com/natowi/meshroom_external_plugins/issues/2#issuecomment-595740223 
See the source code for installation instructions.

**Comment by NexTechAR-Scott** [comment]
> > On my list of things to look at is how to get Instant Meshes to export without normals.
> > Also, make sure you are not generating a quad mesh, Instant Meshes default.
> 
> @NexTechAR-Scott Take a look at this InstantMeshes plugin, [natowi/meshroom_external_plugins#2 (comment)](https://github.com/natowi/meshroom_external_plugins/issues/2#issuecomment-595740223)
> See the source code for installation instructions.
> 
> You are welcome to contribute here #877

Nice, took a quick peek just now

Will take a longer look at that later today.

Sounds promising

Thanks

**Comment by fabiencastan** [comment]
@ryguystye Could you share me your problematic mesh to double check that it's correctly loaded in the develop branch?

**Comment by NexTechAR-Scott** [comment]
I can confirm 

> > On my list of things to look at is how to get Instant Meshes to export without normals.
> > Also, make sure you are not generating a quad mesh, Instant Meshes default.
> 
> @NexTechAR-Scott Take a look at this InstantMeshes plugin, [natowi/meshroom_external_plugins#2 (comment)](https://github.com/natowi/meshroom_external_plugins/issues/2#issuecomment-595740223)
> See the source code for installation instructions.
> 
> You are welcome to contribute here #877

Finally got to this tonight.   Happy to say, it works in Win 10.

Nicely done.

Used a dataset had on hand but will run against real datasets tomorrow and validate Linux as well.

Link for pymeshfix 3.6 64 bit   https://www.wheelodex.org/projects/pymeshfix/wheels/pymeshfix-0.13.4-cp36-cp36m-win_amd64.whl/

**Comment by NexTechAR-Scott** [comment]
Debian 10 works as well.

**Comment by ryguystye** [comment]
> > On my list of things to look at is how to get Instant Meshes to export without normals.
> > Also, make sure you are not generating a quad mesh, Instant Meshes default.
> 
> @NexTechAR-Scott Take a look at this InstantMeshes plugin, [natowi/meshroom_external_plugins#2 (comment)](https://github.com/natowi/meshroom_external_plugins/issues/2#issuecomment-595740223)
> See the source code for installation instructions.
> 
> You are welcome to contribute here #877

I've installed the plugin and can only get it to work sometimes. I'm trying to make a room scan mesh and using "fix mesh" in the InstantMeshes node messes with it. When I disable fix mesh, then the Texturing node (I'm using LSCM unwrapping) fails. I get this message in my log:

> OpenNL assertion failed: param > 0, file:C:\GitHub\vcpkg\buildtrees\geogram\src\1.6.9-d4422875a2\src\lib\geogram\NL\nl_api.c, line:193
Abnormal program termination: received signal 22 (SIGABRT)

**Comment by natowi** [comment]
@ryguystye did you make sure you were using _outputMesh_ and **not** _outputInstantMeshes_? (Happened to me, too. I think I will remove the outputInstantMeshes to avoid problems)

If your error occurs with _outputMesh_ -> _Texturing_ than this is probably due to a bug. As you can see from the TODO list in the Pull Request, "Meshroom compliant OBJ conversion" is not yet fully implemented, so in some cases the output OBJ will cause problems in Texturing.
