### ISSUE TITLE
FeatureExtraction: cudaGetDeviceCount fails on non NVIDIA gpu

### ISSUE THREAD

**Issue by mulder999** [alicevision/meshroom#871]
Even when forceCpuExtraction is enabled the application still tries to extract GPU count

Log file:
[FeatureExtraction.log](https://github.com/alicevision/meshroom/files/4547262/FeatureExtraction.log)

**Comment by NexTechAR-Scott** [comment]
It's not failing because a lack of CUDA.

You have two intrinsics and only one seems valid.
