### ISSUE TITLE
'std::regex_error' when exporting animated camara [bug] 

### ISSUE THREAD

**Issue by lal0cura** [alicevision/meshroom#881]
Hi, I was wondering if there is a workaround or alternative to be able to export a moving camera from Meshrom.

Currently when I hit compute on the export animated camera Node, it inmediately jumps to a std::Regex_Error

THis is the Log generated:

[13:36:54.232031][info] Build animated camera(s)...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped)

ERROR:root:Error during Graph execution Error on node "ExportAnimatedCamera_1":
Log:
Program called with the following parameters:
 * exportUndistortedImages = 1
 * input = "/home/lal0cura/3DViz/Calibration/Ubuntu_Test/MeshroomCache/StructureFromMotion/c2408d28198671500ad058efbdefcc4414e15e88/sfm.abc"
 * output = "/home/lal0cura/3DViz/Calibration/Ubuntu_Test/MeshroomCache/ExportAnimatedCamera/e4fc7ed33235f95d23a34e0bdcbb95cb7bb6e978"
 * undistortedImageType = "jpg"
 * verboseLevel = "info"
 * viewFilter = ""

[13:36:54.232031][info] Build animated camera(s)...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped)

lal0cura@MULCIBER:~/apps/Meshroom-2019.2.0$ gcc --version
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I already try on mint 18.03 but it gives me exactly the same error.

Unfortunately on ubuntu 20 I can only go as low as version 7 of gcc (For I saw in another post, this error is generated on gcc versions above 4.)

I also try to change the filenames to different names with the same result:
imagesec_001.jpg
001_imagesec.jpg
001imagesec.jpg

Im using the release version. ¿Do you know Could this error be avoided if I build from source code?
I dont have experience in programming or building.
So any tips would be helpful.

Thanks a lot.

**Comment by natowi** [comment]
> Hi, I was wondering if there is a workaround or alternative to be able to export a moving camera from Meshrom.

You can use this Blender Addon:
https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer

**Comment by lal0cura** [comment]
Awesome, that Blender Addon did the Trick. Thank you very Much!! I forgot to reply and thank you! I hope you Are OK.
