### ISSUE TITLE
[bug] When I click on a camera in the 3dviewer, the photo is not selected

### ISSUE THREAD

**Issue by skinkie** [alicevision/meshroom#882]
**Describe the bug**
When I click on a camera in the 3dviewer, the photo is not selected.

**To Reproduce**
![image](https://user-images.githubusercontent.com/502394/81227097-29872d00-8fec-11ea-84bf-0811e6580592.png)

1. Go to 3Dviewer
2. Click on Camera (any part, cube, or viewer)

**Expected behavior**
The photo is not selected.

**Desktop (please complete the following and other pertinent information):**
 - OS: Linux
 - Python version 3.6.10
 - Qt/PySide version 5.14.1
 - Meshroom version: please specify if you are using a release version or your own build
   - Commit reference 1e5889559b424dd90b8a0a882815660ed2fb92ed

**Comment by skinkie** [comment]
please keep it open

**Comment by ejnaren** [comment]
I am experiencing the same thing.
Release 2020.1
Is it s bug or is it not implemented?

**Comment by natowi** [comment]
@ejnaren Works for me. So it´s a bug.

**Comment by ejnaren** [comment]
Hmm... I'll see if I can share system info here.
