### ISSUE TITLE
[question] How to export dense cloud as bundler as well as file to link textures later

### ISSUE THREAD

**Issue by Florenzius** [alicevision/meshroom#885]
**Describe the problem**
Basically I want to export the DenseScene as a bundler file (*.out) and get a (preferably) text file to let Meshlab know where to compute the texture later.
I want to use the Dense cloud in Meshlab later on to have some more options to simplify the computed 3d mesh and calculate proper UV maps. Using Colmap, I always get a bundler file and a text file which I can then insert in Meshlab to continue. Is it possible to change the meshing output file from abc to out here? And either I am blind or too dumb to find a way to export texture information, can someone help with this as well?

**Screenshots**
![image](https://user-images.githubusercontent.com/12108718/81343114-a7167000-90b4-11ea-994d-c3425def89d0.png)
^ current meshing change. I enabled the raw option

**Desktop (please complete the following and other pertinent information):**
 - OS: Win 10
 - Meshroom version: release version
 - Binary version: 2019.2.0

Thanks for your help

**Comment by natowi** [comment]
> Is it possible to change the meshing output file from abc to out here?

Yes, there is the ConvertSfMFormat node, but when I remember correctly conversion of the dense point cloud is not supported in the 2019 version. Just place this file [ConvertSfMFormat.py](https://github.com/alicevision/meshroom/blob/develop/meshroom/nodes/aliceVision/ConvertSfMFormat.py) in Meshroom-2019.2.0\lib\meshroom\nodes\aliceVision to fix this.
Then enable the "Unknown" option for the conversion.

> some more options to simplify the computed 3d mesh

You could try this WIP InstantMeshes Plugin https://github.com/natowi/meshroom_external_plugins/issues/2#issuecomment-595740223

> a way to export texture information

Everything texturing related is being done in the Texturing node.

If you decide for external retopology, read this https://github.com/alicevision/meshroom/wiki/Texturing-after-external-re-topology

**Comment by fabiencastan** [comment]
It is not supported for now, but you are welcome to add an exporter to the [Bundler file format](https://github.com/snavely/bundler_sfm#output-format) in [AliceVision](https://github.com/alicevision/AliceVision/tree/develop/src/aliceVision/sfmDataIO).

**Comment by natowi** [comment]
You can convert a SFM file using aliceVision_exportPMVS from the cli. (Meshroom-2019.2.0\aliceVision\bin)

https://github.com/alicevision/AliceVision/blob/develop/src/software/export/main_exportPMVS.cpp
