### ISSUE TITLE
Low GPU usage [question]

### ISSUE THREAD

**Issue by AAronPurple** [alicevision/meshroom#886]
I'm trying very simple task, 350 foto from my phone, but i'm waiting maybe too much for DepthMap go to the end, and the GPU usage it's max 10-20%, GTX 1050 Ti. I need to enable something? It's normal? Thank you!

**Comment by natowi** [comment]
This is normal. DepthMap performance is not yet fully optimized.

**Comment by fabiencastan** [comment]
In short, it is normal.
Depth map computation is a complex step and a lot of optimizations have been done.
But the performance is not only limited by the processing capabilities but also by sync between multiple parallelized steps, wait for memory transfers, file loads, etc.
We are still working on it to improve the use of resources.

**Comment by AAronPurple** [comment]
Thank you, can I do something to understand how is the bottleneck in my case?

**Comment by fabiencastan** [comment]
You can use the cuda profiler to analyze the depth map step:
https://developer.nvidia.com/nvidia-visual-profiler

CPU and RAM ressources are critical on other steps.
