### ISSUE TITLE
Error when processing DepthMap node[bug]

### ISSUE THREAD

**Issue by miquelrosell99** [alicevision/meshroom#887]
**Describe the bug**
All the nodes in the project process just fine, but when I get to the DepthMap node, it gives an error like this one ( downgrade status on node "DepthMap_1(199)" from Status.SUBMITTED to Status.NONE):
![image](https://user-images.githubusercontent.com/38435442/81481205-a0ac0380-922e-11ea-8e2c-2db83718cd47.png)
![image](https://user-images.githubusercontent.com/38435442/81481209-a43f8a80-922e-11ea-8a0a-1e87f9450fec.png)

**To Reproduce**
1. Git clone meshroom
2. grab latest alicevision snapshot to use with meshroom
3. try to process any meshroom project

I need to use meshroom for a uni project, but all of a sudden this error appeared...

**Comment by natowi** [comment]
I am not sure yet, it could be an error with the snapshot build or a bug introduced with a PR.
Can you test this again with the oldest known to work snapshot build? https://ci.appveyor.com/project/AliceVision/alicevision/builds/31822915/artifacts

**Comment by natowi** [comment]
I think I found the error. Somehow a few files are missing in the snapshot:

CONCRT140.dll
VCRUNTIME140.dll
geogram_num_3rdparty.dll
popsift.dll
CCTag.dll
aliceVision_calibration.dll
aliceVision_cameraCalibration.exe
boost_date_time-vc140-mt-x64-1_70.dll
boost_filesystem-vc140-mt-x64-1_70.dll
boost_log-vc140-mt-x64-1_70.dll
boost_program_options-vc140-mt-x64-1_70.dll
boost_regex-vc140-mt-x64-1_70.dll
boost_serialization-vc140-mt-x64-1_70.dll
boost_thread-vc140-mt-x64-1_70.dll
cudart64_80.dll
dbghelp.dll
Half-2_3.dll
Iex-2_3.dll
IlmImf-2_3.dll
IlmThread-2_3.dll
Imath-2_3.dll
opencv_calib3d343.dll
opencv_core343.dll
opencv_features2d343.dll
opencv_flann343.dll
opencv_imgcodecs343.dll
opencv_imgproc343.dll
opencv_videoio343.dll
tbb.dll

Now I need to figure out what went wrong.

**Comment by natowi** [comment]
Has been fixed and will be merged soon.
