### ISSUE TITLE
Meshroom won´t start

### ISSUE THREAD

**Issue by twiggyderringer** [alicevision/meshroom#894]
Hello!

I have a problem that Meshroom won´t start...
Just downloaded it from their website and un-zipped it oo my desk, then when I try to start the program a command window with no information appears.

Anyone that has any idea why it won´t start?  

Im a total beginner with programming, python and so on, so if you can help me explain it like i'm five. :) 

OS: Win10
Meshroom verison: Relese version 2019.2.0
Python: 3.8

Regards
Twiggy

![1](https://user-images.githubusercontent.com/65335346/81913704-9db76700-95d0-11ea-8c26-be50362fb97b.png)

**Comment by natowi** [comment]
Try moving the application folder to another path. Check if your antivirus software blocks the app.

**Comment by twiggyderringer** [comment]
It worked! Thank you very much! :)

**Comment by fabiencastan** [comment]
@twiggyderringer What was the problem?

**Comment by twiggyderringer** [comment]
The problem was that I had the folder on a network server, it´s my work computer so all the files automatically i placed there when downloaded, so I just had to move the folder to C.
