### ISSUE TITLE
[question] Unable to Import images.. what am i doing wrong?

### ISSUE THREAD

**Issue by patrickdb1** [alicevision/meshroom#897]
im trying to import images that i've made,  they are JPG file images but i am unable to drag them into the program.

**Comment by TR7** [comment]
does one or more of these images work?
http://hosting141203.a2e6d.netcup.net/Thomas/HDKornmarkt/HeidelbergKornmarkt.zip

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/wiki/Images-cannot-be-imported

**Comment by gryan315** [comment]
Could also be missing C++ redistributable: https://meshroom-manual.readthedocs.io/en/latest/install/windows/windows.html

**Comment by natowi** [comment]
@gryan315 yes, thanks for the reminder. I will add it to the faq.

**Comment by patrickdb1** [comment]
> Could also be missing C++ redistributable: https://meshroom-manual.readthedocs.io/en/latest/install/windows/windows.html

it works now after i did this though im 99% sure i already had that installed.
