### ISSUE TITLE
Cannot import images into Meshroom [question]

### ISSUE THREAD

**Issue by 50ShadesOfGraham** [alicevision/meshroom#899]
When I drag and drop images into Meshroom, a dialog box with a progress bar displays very briefly, disappears, and nothing has changed in the GUI. No images imported. The CLI box shows this:
"39571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm'"

I have read all the other threads about this issue but have not found a solution. I have tried using the Monstree dataset, same problem. I have all C++ redists, not running as admin, etc.. I tried installing the latest Python, but no difference. If I use the Live reconstruction option, I can point it to a folder, and my images will show, but they are all missing the sensor metadata. Everything is "undefined". When I try and build a model with it, it finishes very quickly, and this is my final result, with "load model" not doing anything.

**Screenshots**
![Screenshot_29](https://user-images.githubusercontent.com/65547792/82217752-cd3cdb00-9912-11ea-97e8-a599b24ef63c.png)

**Desktop (please complete the following and other pertinent information):**
 - OS: Windows 10
 - Python version: 3.8.3
 - Meshroom version: 2019.2.0 full release, did not build myself.
 - i5 4690k, GTX 970, all latest drivers.

Cheers guys. Hope I posted correctly.

**Comment by Coninox** [comment]
I came here because that's my first try of Meshroom, and I have the exact same problems.
When I drag pictures, a progress bar appears and disappears almost immediately, and then nothing appens. No picture is visible. Even with the monstree dataset.

**Comment by natowi** [comment]
In many cases this is caused by missing the [Microsoft Visual C++ Redistributable Package 2015, 2017 and 2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

**Comment by Coninox** [comment]
In my case I had already installed it. I have tried to download it another time, reinstall it, and reboot my PC. It's still the same behavior.

**Comment by julianrendell** [comment]
I read somewhere that this can sometimes be due to not having the visual studio redistributable installed.

There are several versions of this; I think the 2015 version will work: https://www.microsoft.com/en-ca/download/details.aspx?id=48145

If that doesn’t help, write back with:

• Which version (eg download link) you’re using
• If there is an error message pop up, what does it say? (Screen shot if possible)
• There should be a command prompt window in the background with text output from Meshroom. Does anything show up there after you try to import pictures?

And hopefully that will be enough info for someone knowledgable to help.

Julian

**Comment by Coninox** [comment]
I'm on windows 10.
I've installed the following version of meshroom : https://www.fosshub.com/Meshroom.html?dwl=Meshroom-2019.2.0-win64.zip
I've installed "Visual Studio 2015, 2017 and 2019" from here : https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
(the vc_redist.x64.exe file)

There is no pop-up nor error message. Just nothing is appening after the disparition of the progress bar.
There is only one line in the console in the background : 939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm'

Some pictures of the problem in 3 steps :

the drag/drop :
![step1](https://user-images.githubusercontent.com/22373990/83266395-11599680-a1c3-11ea-8922-7137024b5584.png)

the progress bar :
![step2](https://user-images.githubusercontent.com/22373990/83266421-19b1d180-a1c3-11ea-928e-19e28d523119.png)

nothing have changed :
![step3](https://user-images.githubusercontent.com/22373990/83266430-1cacc200-a1c3-11ea-9e76-188e7d1fb2ff.png)

**Comment by natowi** [comment]
Here are a few things you can try:

- make sure the downloaded Meshroom files are not corrupted (incomplete/interrupted download)
- you have to extract the archive and not just launch it from the zip viewer.
- avoid special characters/non-ASCII characters in Meshroom and images file paths
- make sure your antivirus program does not interfere with Meshroom

> There is only one line in the console in the background : 939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm'

This could be a hint. Does the console list the loaded plugins like this?

> Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportColoredPointCloud, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, LDRToHDR, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing

**Comment by Coninox** [comment]
I've downloaded it and extracted it four times.

I've extracted it in "c:/meshroom" to avoid any problem with the path

The images are in "c:/test"

The only antivirus I have is the one integrated in windows 10, I don't think it's the cause of the problem.

The following lines are printed in the console at the startup :

`Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportColoredPointCloud, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, LDRToHDR, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing`

**Comment by natowi** [comment]
After importing the images, the cli window should look like this:
![mrimaJPG](https://user-images.githubusercontent.com/8138537/83519479-60157200-a4dc-11ea-97a0-83fc52850475.JPG)

How does it look like in your case?

**Comment by Coninox** [comment]
before the drag/drop :
![before](https://user-images.githubusercontent.com/22373990/83524603-1d579800-a4e4-11ea-8ba4-0eac2960e38d.png)

after the drag/drop :
![after](https://user-images.githubusercontent.com/22373990/83524672-36604900-a4e4-11ea-8244-0cd08f5bac7d.png)

**Comment by visualbruno** [comment]
> After importing the images, the cli window should look like this:
> ![mrimaJPG](https://user-images.githubusercontent.com/8138537/83519479-60157200-a4dc-11ea-97a0-83fc52850475.JPG)
> 
> How does it look like in your case?

Hi I had the same issue.
And I found a way to make it works:

**Reduce the resolution of your pictures.**

When I drag&drog picture with 3024x4032 (so 12Mpixels), it crashes with the same kind of message as you.
I reduced the resolution to 1512x2016 (3 Mpixels) and it worked.

**Comment by visualbruno** [comment]
Sorry, I was wrong.
Just open your picture with Paint and resave it. It works too.

**Comment by natowi** [comment]
@visualbruno There might be an issue with the exif data that causes a problem. Removing the exif metadata may solve the problem without resizing.
