### ISSUE TITLE
camera rig - not all photos are imported into meshroom [bug]

### ISSUE THREAD

**Issue by TR7** [alicevision/meshroom#905]
**Describe the bug**
as recommended in another threat here, I tried to load footage from a GoPro Fusion (2x 180 degree cameras) as a camera rig in meshroom.

the folder structure is:
/rig/0/0000.JPG
/rig/0/0001.JPG
...
/rig/1/0000.JPG
/rig/1/0001.JPG
...

when i drag the "rig" folder (or both "0" and "1" folders) into meshroom, only half of the images are loaded (only from folder "0")
When i try to drag ONLY folder "1" into a existing or new project in meshroom, nothing happens.

(The photos were taken in a supermarket with the permission of the store manager)

**To Reproduce**
1. download the dataset (only 2x8 = 16 Test-Images): http://hosting141203.a2e6d.netcup.net/Thomas/Scans/06/rig06.zip
2. Drag the extracted folders into Meshroom 2019.2.0

**Expected behavior**
- all 16 images should be loaded into meshroom, not only 8

**Screenshots**
![image](https://user-images.githubusercontent.com/9460997/82422828-3f343200-9a83-11ea-8555-f5d48ec1b669.png)
![image](https://user-images.githubusercontent.com/9460997/82422862-4bb88a80-9a83-11ea-9c3b-ff474f3db93b.png)
![image](https://user-images.githubusercontent.com/9460997/82423055-8b7f7200-9a83-11ea-8d06-5f333676af3f.png)

**Log**
is the loading process of images logged by meshroom? where?

**Desktop (please complete the following and other pertinent information):**
 - OS: win10
 - Python version 3.7
 - Meshroom version: 2019.2.0 release

**Comment by natowi** [comment]
Reference https://github.com/alicevision/meshroom/issues/527

**Comment by TR7** [comment]
great, import is working now! Thank you natowi :-)
maybe it could be a great small feature for meshroom to directly import such 360 degree camera rigs like the gopro fusion images without the need to change the exif tags.

**Comment by jhaggle** [comment]
Image link broken.

**Comment by TR7** [comment]
> Image link broken.

fixed
