### ISSUE TITLE
Parameters for photoscanning a model. [question]

### ISSUE THREAD

**Issue by Leterax** [alicevision/meshroom#908]
**Describe the problem**
I would like to know what describer type to use and what photometric matching method to use. I would also love a quick explanation of what the differences between the options are :). My rig is very GPU heavy but has a weak CPU (i7-2600) so the more the GPU gets used the better! So far I have used the default pipeline with "describer Preset" set to medium to get a quick look at the results. 
akaze seems to get a lot more detail on the model but both quickly reach the max. 
Also, It picks up a lot of stuff on the table, should I put something underneath the model? some paper? should I put markers on the paper?

**Screenshots**
![image](https://user-images.githubusercontent.com/38299494/82599051-ead8a180-9bab-11ea-836e-77f7fcd0f59b.png)
(using the high preset for feature extraction)

**Dataset**
https://imgur.com/a/XX6mmAd

**Desktop (please complete the following and other pertinent information):**
 - OS: win 10
 - Python version 3.6.6
 - Meshroom version:
   - Binary version 2019.2

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters

I´d recommend to take more close up images. The car should fill most of the image frame. This will reduce the amount of environment that is being reconstructed.

**Comment by Leterax** [comment]
Yes, the "dataset" is just the first few images, I took 135 in total. Most of those are more close up. It was able to match all but a few. I was just wondering what parameters I could use to speed things up. It took around 9h in total...

**Comment by Leterax** [comment]
I ended up using another table that didn't have as much detail on it and that helped a lot. But sift was still pretty bad compared to akaze. Sift was mostly picking up things in the blurry background....
