### ISSUE TITLE
[question]Extract 3D coordinate of specific point

### ISSUE THREAD

**Issue by quizzy5889** [alicevision/meshroom#913]
**Describe the problem**
Hey, everybody, I have a very simple question, I think. I use your sw to reconstruct a scene with a lot of texture, everything works very well even with a few images.

I put a chessboard inside the scene because I would like that to be the origin of the point cloud (this would be useful for postprocessing).

The chessboard is visible from several images, but let's say that in the first instance I could focus on one.

I can easily get the 3D orientation of the chessboard, I have the coordinates in pixels of the origin of the new reference system in my image, but I can't convert them into 3D metric coordinates...

Could you help me out on what might be the quickest way to achieve this?

Thanks

**Comment by natowi** [comment]
You can import your model in Meshlab and use the chessboard as reference for [scaling ](https://www.youtube.com/watch?v=6psAppbOOXM) and changing the origin.

**Comment by quizzy5889** [comment]
Thank you natowi for your super quick answer. Very kind. Possibly I'd like to do it automatically. 

What I would like to do is: take the image in question, get the position in pixels of the origin of the chessboard (I'm doing by myself), **convert this information into 3D coordinates** (I think the information is already extracted in the various steps of the workflow). With that information I would rototranslate the cloud a posteriori in an automatic way. Currently I can't do the step in bold.

Surely I will also use the information to scale the point cloud as well.

**Comment by natowi** [comment]
At the moment this is not possible. There will be some options to achieve this by using cctags in the next release.

**Comment by quizzy5889** [comment]
It doesn't matter. I will do it externally. 

Thanks a lot

**Comment by quizzy5889** [comment]
Sorry for reopening this issue, but I can't find a way to compute 3D points from stereo correspondences, or at least, I got an error and I don't know where it comes from. I would really appreciate if you have time to help me please.

Just to summarize: 

I put a chessboard in my scene and the goal is to find 3d position of its corners.
I executed the pipeline and I got the final point cloud, and the cameras.sfm as well.
From cameras.sfm I saved camera intrinsics ad distortions (k1, k2, k3, keeping p1 and p2 equal to zero). I also extracted the view poses computed by the sfm node.

Then:

I took two images where the chessboard is clearly visible and via openCV I extracted its corners.
 
`ret, corners = cv2.findChessboardCorners(grayscale_image, (num_rows, num_columns))`

Then points has been undistorted: https://docs.opencv.org/4.2.0/d9/d0c/group__calib3d.html#ga55c716492470bfe86b0ee9bf3a1f0f7e

`corners_subpixels = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
corners_undistort = cv2.undistortPoints(corners_subpixels, camera_matrix, dist_coeff)`

and finally triangulated 

`points_chessboard_homogeneous = cv2.triangulatePoints(projection_matrix_0, projection_matrix_1, projection_points_0, projection_points_1)`

where projection_matrix is P = [R|t], with t computed as -R*C and projection_points are the undistorted point. Then I converted from homogeneous coordinates to world coordinates but the results is not as expected as you can see in the picture. Any idea?

![Schermata 2020-05-25 alle 10 41 12](https://user-images.githubusercontent.com/3774189/82801959-6b362580-9e7e-11ea-9750-5fb812a7e190.png)

Thank you in advance

**Comment by natowi** [comment]
This might be useful https://github.com/alicevision/meshroom/issues/857

**Comment by natowi** [comment]
If you are interested in adding chessboard based orientation and scaling to Meshroom, take a look at SfMTransformation (scene transformation) and CameraCalibration (chessboard recognition).

**Comment by quizzy5889** [comment]
Thanks natowi, I've already checked #857, unfortunately without success...
Now I'm going to have a look at SfMTransformation... 

Thanks a lot

**Comment by quizzy5889** [comment]
Hi, sorry to write again, I feel very bad to ask you for help again, but I had the opportunity to spend some more time on the problem and check the steps, but I can't solve it.

I take the intrinsic paremeters and poses from cameras.sfm and I build them as exposed in #857 .

To exclude the problem of optical distortions, I take the images directly from the temp folder generated by PrepareDenseScene. 

The chesboard corners are extracted on the undistorted images using OpenCV's findChessboardCorners function and the results are definitely right, as displayed.

![1147811523_corners](https://user-images.githubusercontent.com/3774189/83035133-5fdb2980-a039-11ea-805b-5b2be1a953ab.jpg)

I then tried both TriangulateDLT and TriangulateNViewAlgebraic, but I get the red and the blue solution respectively.

![Schermata 2020-05-27 alle 16 42 12](https://user-images.githubusercontent.com/3774189/83035211-75505380-a039-11ea-9981-f1241f91f05e.png)

![Schermata 2020-05-27 alle 16 41 40](https://user-images.githubusercontent.com/3774189/83035190-6ff30900-a039-11ea-992a-0775f0cf317d.png)

Can you at least please confirm that I am not missing a theoretical step?  I honestly don't know what else to check anymore...

Sincerely thanks

**Comment by natowi** [comment]
Do you have an idea @simogasp ?

**Comment by simogasp** [comment]
* How many images with the checkerboard are you using?

* I assume the rails are really bent in reality, so the undistortion should be ok?

* it's hard to tell from the 2 images, are the 3D points (in both cases) at least lying on the same 3D plane (more or less)? If so, is this plane kind of parallel to the plane of the checkerboard? 

* I'd give it a try with `TriangulateNViewLORANSAC()` which can discard points that were not well detected, thus providing a more robust estimate. The 2 methods you used are least-squares based methods and they are not intrinsically robust to noise. 

* Maybe (if possible) use less images and prefer images where the checkerboard appears bigger in the image and less from a skew angle than the image you posted. The detector may struggle with less resolution.

**Comment by quizzy5889** [comment]
Thanks for your answer. I really appreciate.

- I'm using 16 image with the chessboard out of 24 total for the point cloud.

- Yes the rails are really bent. It's close to a curve.

- No, I tried with several different couples of images and the points move around the expected location, but I can't find a logic or a specific pattern in their relative position.

- For sure I am going to try it and then I will let you know, thanks for the suggestion.

- Ok, I'll take this into consideration.
