### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by AccomplishedCode** [alicevision/meshroom#914]
I have a graph which works perfectly for my results. I created the graph and added a few nodes to it in the GUI, and then saved the .mg file. My goal is to use this same graph for any dataset that I like, straight from the command line. However, I face an issue whenever I'm running the CLI command :
"python bin/meshroom_photogrammetry --input "X" --output "Y" --pipeline "Custom_Graph.mg" 
I always get camera_init failed with error code 1. I also always see the problem of the system detecting QT plugins but failing anyways. 

I also tried python bin/meshroom_compute "Custom_graph.mg" , but it says no nodes to compute. What am I doing wrong here? It seems to work great in the GUI but for the life of me I can't figure out how to use the same graph to recreate the results using a different dataset. 

**Screenshots**
![image](https://user-images.githubusercontent.com/40490288/82805093-0c35d800-9ea1-11ea-82ad-b569aba41522.png)
![image](https://user-images.githubusercontent.com/40490288/82805201-3ab3b300-9ea1-11ea-8740-3fbbc7afe721.png)

Here's the error when I try to run the main cLI command : 
![image](https://user-images.githubusercontent.com/40490288/82832712-7f5b4080-9ed9-11ea-9779-b3a0424649d1.png)

 - OS: Win10
 - Python version 3.7
 - Meshroom version:2019.08

I'd really appreciate any help in how to use this custom graph and run it on any dataset that I like through the CLI. My aim is to generate dense point clouds from multiple datasets to then combine them later, but also to automate it in a way that makes it easier to do on a server implementation rather than running it on a personal computer using the GUI. Thanks a lot!

**Comment by gryan315** [comment]
When I run CLI, I just make a launcher script for meshroom_photogrammetry and input the parameters I want that aren't default. The documentation is lacking in the full scope of available parameters, so it takes a little trial and error to get it working, but you can mostly use your mg file as a guide. Boolean parameters should be set as 1 or 0 for the command line arguments. Here's an example of one of my scripts:

`PYTHONPATH=$PWD python bin/meshroom_photogrammetry -i $HOME/Pictures/brass --cache $HOME/Pictures/MeshroomCache --paramOverrides FeatureExtraction:describerPreset=high FeatureMatching:guidedMatching=1`

In the same script you should include some basic paths like ALICEVISION_SENSOR_DB= (possibly why your camera init fails?) and ALICEVISION_VOCTREE= as well as any library or binary paths that might not automatically be detected. I have not tried adding any additional nodes by this method.

**Comment by AccomplishedCode** [comment]
> 
> 
> When I run CLI, I just make a launcher script for meshroom_photogrammetry and input the parameters I want that aren't default. The documentation is lacking in the full scope of available parameters, so it takes a little trial and error to get it working, but you can mostly use your mg file as a guide. Boolean parameters should be set as 1 or 0 for the command line arguments. Here's an example of one of my scripts:
> 
> `PYTHONPATH=$PWD python bin/meshroom_photogrammetry -i $HOME/Pictures/brass --cache $HOME/Pictures/MeshroomCache --paramOverrides FeatureExtraction:describerPreset=high FeatureMatching:guidedMatching=1`
> 
> In the same script you should include some basic paths like ALICEVISION_SENSOR_DB= (possibly why your camera init fails?) and ALICEVISION_VOCTREE= as well as any library or binary paths that might not automatically be detected. I have not tried adding any additional nodes by this method.

Thanks a lot! I will try this out. Quick question, when adding the sensor database in the script, should I just append the ALICEVISION_SENSOR_DB to the script, for example the one you just sent? I'm also confused that we have to do this if we have a custom graph already saved. Woudln't that graph file have all the sensor paths in it already???

**Comment by gryan315** [comment]
Yes, you can set the variables in the same script, before you execute meshroom. On Linux it would be 'export ALICEVISION_SENSOR_DB=/path/to/db/file' and I believe in Windows it's set rather than export. When you saved your .mg, was it from the same build of meshroom? Did you already import the pictures into it? I believe if you want to save a graph for the --pipeline usage, it should be empty of any paths to prevent bad paths if you move something. It's a safer bet to declare all paths at execution.
