### ISSUE TITLE
Unable to install or run

### ISSUE THREAD

**Issue by jancoow** [alicevision/meshroom#915]
**Describe the problem**
I want to try meshroom. However, I'm unable to run the binary or run the compiled package from dev or master. 

Both 2019.1 and 2019.2 results in this error:

```
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/opt/Meshroom/setupInitScriptUnix.py", line 39, in run
  File "meshroom/ui/__main__.py", line 10, in <module>
  File "/opt/Meshroom/meshroom/ui/app.py", line 5, in <module>
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/PySide2/__init__.py", line 51, in <module>
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/PySide2/__init__.py", line 21, in _setupQtDirectories
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/shiboken2/__init__.py", line 20, in <module>
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/tempfile.py", line 45, in <module>
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/random.py", line 46, in <module>
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/hashlib.py", line 190, in <module>
ImportError: /home/janco/LocalDocuments/Meshroom-2019.2.0/lib/libssl.so.10: undefined symbol: krb5_rc_destroy, version krb5_3_MIT

```

Both master and dev branch results in a segmentation fault when trying to run it:

```
gcc Meshroom -g
/usr/bin/ld: error in Meshroom(.eh_frame); no .eh_frame_hdr table will be created
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../lib/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

**Desktop (please complete the following and other pertinent information):**
 - OS: Arch Linux
 - Python version 3.8.3
 - Qt/PySide version 5.14.1
 - Meshroom version:
   - Binary version 2019.2, 2019.1
   - Commit reference latest dev / master

**Additional context**

**Comment by ChemicalXandco** [comment]
This is the same problem as in #850

**Comment by jancoow** [comment]
Agree, but that is only the issue for the libssl. What about the segfault?

**Comment by gryan315** [comment]
Are you trying to run gcc on the meshroom dev build? Meshroom is all written in python and doesn't need to be compiled to run, alicevision is what needs to be compiled, which is quite a task and doesn't go smoothly, especially now that gcc 10 is in the mix. I would recommend replacing that libssl file and running the binaries, I haven't been able to get the GUI running on the dev build on arch yet,  I'll let you know if I do.

**Comment by jancoow** [comment]
I used the AUR package for compiling it from source: https://aur.archlinux.org/packages/meshlab-git/ which didn't take that long. 

I tried copying libssl.so.10 from /usr/lib into the lib directory, but that resulted in other errors. I also tried copying _hashlib.cpython-36m-x86_64-linux-gnu.so from my system python3 folder into the lib directory, but that neither worked.

**Comment by gryan315** [comment]
I downloaded the libssl 10 from the centos 8.1 version on rpmfind and copied the files into the meshroom directory. This is not an ideal solution, but it works. You also linked to meshlab in the AUR, which is different from meshroom. I haven't tried the alicevision or meshroom builds from the AUR since January, so I'm not sure if they're functional or not with the current arch environment.

**Comment by jancoow** [comment]
Sorry my bad, I meant to link the meshroom aur: https://aur.archlinux.org/packages/meshroom/
Or the bin version: https://aur.archlinux.org/packages/meshroom-bin/ 

I'll try the copy libssl from centos.

**Comment by gryan315** [comment]
https://rpmfind.net/linux/RPM/centos/8.1.1911/appstream/x86_64/Packages/compat-openssl10-1.0.2o-3.el8.x86_64.html

This is the package I used, just extract the RPM and copy libssl.so.1.0.2.o and the symlink libssl.so.10 from the extracted usr/lib64 directory into your meshroom binary lib directory.

**Comment by jancoow** [comment]
That actually works! Thanks!

**Comment by gryan315** [comment]
I've managed to get the UI working on the dev build by using the pip install PySide2 instead of the built arch package, then adding the .local folders to my LD_LIBRARY_PATH and PATH. Still no luck getting the QT plugins for displaying features or geogram working for LSCM texture unwrap though.

**Comment by julianrendell** [comment]
@gryan315 - I had problems with the QT plugins (on windows), did get it to work: https://bugreports.qt.io/browse/QTBUG-84390 for details. (Will roll this back into the doc PR I have started on Meshroom when I have some time.)

Key thing from that bug: set `QML_IMPORT_TRACE=1` before running and you'll get debug info re where QT is searching for the plugins. Watch out for spaces, and quotes. (Quotes & paths don't work the way I had assumed.)

**Comment by gryan315** [comment]
When I run the trace, it seems to be looking in the right places, but still none of the plugins are working. No SFM point cloud, no features in photos, no depthmap view... I've tried setting the import path as the base qml directory that all the plugin folders are, as well as adding one specific path for each qtAliceVision, qmlAlembic, and qtOpenImage, I've even tried using the qt plugins folder from the 2019.2 release to no avail. Not sure if it matters, but my plugins are installed in /usr/local and qt is installed in /usr proper.

**Comment by julianrendell** [comment]
Any chance it's as simple as the executable flag needing to be twiddled?

Are you running anything that would block loads from where you have it installed?

By using the plugins folder from the released version, did you just set `$QML2_IMPORT_PATH` to the common `qml` directory, or copy them? If the later, did you try using them from their original location?

(Pretty obvious suggestions that you've probably tried. But just in case ;-).)

**Comment by gryan315** [comment]
I didn't think to check the executable flag, but yes, they were all executable. The bin qtplugins path is in my home directory, and I first tried it from where it was in the meshroom binary folder, then copied it over to the meshroom dev folder. I did notice that the one from the release has a depthmapentity and an imageformats plugin, but when I built qtIO it only made a depthmapentity.
