### ISSUE TITLE
Discoure for community chat and community generated documentation?

### ISSUE THREAD

**Issue by julianrendell** [alicevision/meshroom#916]
There was an [email](https://groups.google.com/forum/#!topic/alicevision/vujYyaSOWro) on the Google group asking if there was, or could be created a user chat forum.

I've read through #234 and understand some of the concerns. A counter-point is that a lot of beginners find chat systems very useful (when you're at the "I don't even know what the right words are to describe what I want to do and search for it..." stage, or need some encouragement to go search :-) ). As well it (can) build a sense of community.  

All of the above is with the caveat that it requires a threshold of community engagement to be successful.

I find discourse is a workable system:

- it's a forum with realtime chat like features
- it has a good internal search
- if it's public, it's searchable via Google
- can have "wiki posts": think of these as a thread with a pinned post, but the pin post can be edited by any member. It keeps history as revisions. I've found this to be a great way to draft up FAQs and How-to guides.
- easy to admin, and has good built in defenses against spam, and good workflows for "trust" levels and managing social issues.
- can be set up so users can self-signup.
- has good keyboard shortcuts, good search from all locations in the app, is easy to create posts/edits and mid post browse/search to other messages and drop in references, etc (IMHO markedly better than searching emails/using GMail's interface, or google groups.) 

I've found out that there is free Discourse hosting for qualifying projects- https://free.discourse.group/.

Would the dev team consider requesting (and "owning") a discourse instance? I believe the project owners need to make the request for discourse.org to consider it. (I would be willing to help as a moderator.)

If no, any strong feelings regarding end-users creating their own un-official channels/documentation? Especially with regard to naming? (If I understand correctly, AliceVision is a proper organization that has received funding- I'm guessing there are rules re how your project names can be used.) I'm thinking along the lines of an old-fashioned User Group.

If a discourse was created, any recommendations re content license? I lean towards something creative commons like, probably with attribution, but that allows commercial use (so posts could be used in the official documentation, or if someone were to use the materials as part of a book, or base a course on the materials.) I see Meshroom is MPL- would that be appropriate for discourse content?

Thanks for considering this!

**Comment by natowi** [comment]
At the moment there are only a hand full active core devs and community members, so adding another channel will spread the workload even wider. We have been discussing the topic recently, including how to better integrate the community. So far, questions in the Issues and Google Groups are manageable. There is some restructuring going on, so an official community forum is not completely out of the picture, but nothing is planned yet.

Here are some places for (unofficial) community discussions:
https://blenderartists.org/t/meshroom-free-photogrammetry/
https://www.reddit.com/r/photogrammetry/search/?q=meshroom&restrict_sr=1

Most of the frequently asked questions and new issues are from people who don´t use search engines properly. But that is a general problem. 
The best solution to this is a good manual and documentation with FAQ that can be linked to.

I am happy to give you some pointers where to start contributing to the documentation.

The manual is licensed under CC-BY-4.0.

**Comment by julianrendell** [comment]
Thanks for the links to those forums; I'm not much of a reddit user, but will join BA. (Oh, it's discourse, my favourite ;-) )

Email lists are very 1D (stream of consciousness). It's very difficult to build references for new users via them.  And they're surprisingly hard to search. (more on that below.) 

My experience with the wider public (run a makerspace...) email lists are considered "high ceremony". GitHub is intimidating for non-coders. For good or bad, the average beginner expects Google search to work, a message board/chat system or web based forum. Some are willing to contribute with guides etc, but only if it's low ceremony. 

(Many end users have no idea of what "normal" communication processes look like to software developers ;-). )

I personally agree re a manual, but it's always going to be out of date, and generic... and necessarily high-ceremony (need a GitHub account, fork, PR... the ReadTheDocs manual is 285 pages! (https://readthedocs.org/projects/docs/downloads/pdf/stable/))

Glad to hear a forum is not totally out of the question- I really do think there would be a benefit for a low-ceremony, quick and easy place for "shared online notes". (Especially looking at the number of tabs I have open right now linking to similar issues with nuggets of info :-) )

Will close this request, and plan to familiarize myself with Sphinx ;-)

@natowi maybe I'm missing a GitHub "send message" feature, but I'm not sure how to communicate re the docs. So I've created a fork, invited you as a collaborator and created a wiki page: https://github.com/julianrendell/meshroom-manual/wiki/Julian's-To-Do-List - please feel free to drop in any simpler/less technical things that you'd like to see done. I've listed a couple of things I'd like to see/contribute. (I'm assuming collaborators can edit wiki pages...)

Aside: I was going to agree re people and search, but having recently been mostly a "lurker" on the Google group, and decided to try to find things via Google search that's in the list archive. I've realized that the Google Group content is *incredibly* down-ranked in Google search. The only way I got something to surface via Google search was to force an exact string match (my test ended up requiring `alicevision meshroom "Two reconstructions, instead of one"` to get a result that included google group content.)

A little research (https://en.wikipedia.org/wiki/Google_Groups) shows that Google Groups search capabilities has been reduced, and I'm realizing that, at least for me, with my Google profile, mailing lists results are very, very downlinked (page 8+?).

Where as things on "websites" (forums, etc) are very up-ranked. E.g. http://www.google.com/?q=makeitzone%20photogrammetry (shameless self promotion ;-) ). We're a very small group of enthusiasts, and yet it surfaced immediately. Politics of the internet aside, I think most folks start with a Google search, and I now have more sympathy for those asking "you could've searched for that" questions to email lists... looks like email-list content is low on Google search results.

**Comment by simogasp** [comment]
maybe soon we will have this
https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions

**Comment by natowi** [comment]
We can already use discussions, but only for group members.

**Comment by simogasp** [comment]
yes but they are going to add it public open to everyone

**Comment by natowi** [comment]
I am looking forward to this.

**Comment by julianrendell** [comment]
Looks interesting. I had a quick look at the demo linked, and it does look like "top posts" can be made group editable -> FAQ like. 

Definitely a step in the right direction, but I'm going to guess that discourse will still be "best in bread". (I have concerns with tools trying to do everything so-so vs somethings well.)

Looking forward to being able to try it!

One "downside" --- I assume it's going to use Markdown format; if you keep the docs in rst someone is going to have to translate them. Or would you accept markdown for the official docs? I think ReadTheDocs/Sphynx can handle that. (Pls say yes to markdown- I know it's not as full featured, but I use it everyday ;-) )

**Comment by natowi** [comment]
At the moment I use https://www.typora.io/ for editing (it uses pandoc in the background). It creates markdown but can save files as rst.

**Comment by julianrendell** [comment]
@natowi - I will give that a try again, thanks sharing these tips!
