### ISSUE TITLE
[question] Example of overriding settings via json

### ISSUE THREAD

**Issue by KilianB** [alicevision/meshroom#917]
**Describe the problem**
A clear and concise description of what the problem is.

The meshroom cli specifies that individual parameters of the pipline can be overriden. 

````
--overrides SETTINGS  A JSON file containing the graph parameters override
````

Are there any examples available on how the json file is supposed to look like? Can I just take a *.mg file delete everything except the field I want to change and submit it?

e.g. 

````
{
    "graph": {
        "CameraInit_1": {
            "internalFolder": "newValue/",
		}
	}	
}
````

**Comment by natowi** [comment]
See https://github.com/alicevision/meshroom/issues/683#issuecomment-545801680
