### ISSUE TITLE
[bug] "Abnormal program termination: received signal 11 (SIGSEGV)" when Texturing

### ISSUE THREAD

**Issue by manulerider** [alicevision/meshroom#920]
Hi everyone, 

I'm new to Meshroom but it seems to work very well !

I'm working on a model, and I'm facing to issues with Texturing Node. Basic texturing works fine for me, but as I can't work with several textures, I want to use LSCM or ABF but I've a problem with both of these. I'm getting this problem when computing : 
"Abnormal program termination: received signal 11 (SIGSEGV)"

All my source images are green labelled, so I don't get what's going on.

What am I getting wrong? Thanks a lot !

Hardware : 

1 GTX 1080Ti
1 RTX 2080
Python updated
Windows 10 Pro

> Program called with the following parameters:
 * angleHardThreshold = 90
 * bestScoreThreshold = 0.1
 * correctEV = 0
 * downscale =  Unknown Type "unsigned int"
 * fillHoles = 0
 * flipNormals = 0
 * forceVisibleByAllVertices = 0
 * imagesFolder = "D:/2020/13 Sphere/Photogrametrie/Test boite Sel/MeshroomCache/PrepareDenseScene/281c6d986a3bf5f65c11113e9d590d73417baee1"
 * input = "D:/2020/13 Sphere/Photogrametrie/Test boite Sel/MeshroomCache/Meshing/9d8eeb81f98110031e59bb5958f81fd6900e386c/densePointCloud.abc"
"

**Comment by gryan315** [comment]
What version of meshroom are you using? I've been having a similar problem with the dev build because I can't seem to get geogram integrated properly. Also, what does it say right before the termination message?

**Comment by manulerider** [comment]
Thanks for the reply !

I'm using V2019.2.0

Right before the message, it says : 

`[14:20:10.912292][info] remapMeshVisibility based on triangles start.
[14:20:11.760168][info] remapMeshVisibility done.
[14:20:11.798129][info] Input mesh has no UV coordinates, start unwrapping (LSCM)
[14:20:11.867048][info] Start mesh atlasing (using Geogram LSCM).
`

**Comment by gryan315** [comment]
I wouldn't expect a fault like that with the binary distribution, how much memory does your PC have and how large is your photo set? What settings are you using for Texture Side and downscale?

**Comment by manulerider** [comment]
my Ram is 64Go and my photos are 5184x3456 bix, 100 Mo each, with a set of 51 photos = 5Go total

Are these too big?

**Comment by gryan315** [comment]
No, not too big, I use 36 MP photos, and 51 is a pretty small data set. Just checking because one cause of a segfault is running out of memory. Did you download the windows binary release from fosshub, where the alicevision website mirrors it? Another thing you could check is making sure your windows page file is disabled, you shouldn't need it with 64gb of RAM, and I wouldn't be surprised to see a bug past using it before RAM.

**Comment by manulerider** [comment]
Ok I just did remove the windows page file, and re downloaded the software, but had the same issue.

I tried to put a MeshResampling node instead of a MeshFiltering, and apparently it works, but my Texture is really weird then...

**Comment by gryan315** [comment]
I wouldn't use MeshResampling, you could just remove the MeshFiltering node alltogether, or put in MeshDecimate to reduce your triangles.

**Comment by manulerider** [comment]
ok, that was the Meshfiltering which was a problem, I don't really know why... Furthermore, my result is quite better now !

Thanks a lot man, have a nice day !
