### ISSUE TITLE
Setting up raw / cr3 files from Canon

### ISSUE THREAD

**Issue by GJPfaff** [alicevision/meshroom#924]
Tried adding the lines to the camera database no luck. Canon;Canon EOS Rebel SL3;22.3;dpreview,digicamdb,imaging-resource  Checked metadata and didn't see anything out of the ordinary.  https://www.metadata2go.com/result/d8a9e97a-cc0b-44c6-b661-2ff691afdf49
I do notice the temp folders it refers to do not exist....

Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "" (default)
 * output = "C:/Users/GilGame/AppData/Local/Temp/tmp_ko74z93/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm"
 * sensorDatabase = "E:\Meshroom-2019.2.0-win64\Meshroom-2019.2.0\aliceVision\share\aliceVision\cameraSensors.db"
 * verboseLevel = "info"

[18:27:25.415280][error] Program need -i or --imageFolder option
No input images.
ERROR:root:Error while building intrinsics : Traceback (most recent call last):
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\meshroom\ui\reconstruction.py", line 399, in buildIntrinsics
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 192, in buildIntrinsics
RuntimeError: CameraInit failed with error code 1. Command was: "aliceVision_cameraInit  --sensorDatabase "E:\Meshroom-2019.2.0-win64\Meshroom-2019.2.0\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "C:/Users/GilGame/AppData/Local/Temp/tmp_ko74z93/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm" --allowSingleView 1 "

**Comment by skinkie** [comment]
Just out of curiosity. If use the standard cameraSensors.db does the program work for you?

Can you paste the line you have added?

**Comment by GJPfaff** [comment]
I posted above the line, Canon;Canon EOS Rebel SL3;22.3;dpreview,digicamdb,imaging-resource it is the same as the SL1 and SL2 that are in the DB already.

**Comment by GJPfaff** [comment]
Canon;Canon EOS Rebel SL1;22.3;dpreview,digicamdb,imaging-resource
Canon;Canon EOS Rebel SL2;22.3;dpreview,digicamdb,imaging-resource
Canon;Canon EOS Rebel SL3;22.3;dpreview,digicamdb,imaging-resource
I added last line unless something is different in the SL3

**Comment by GJPfaff** [comment]
And same error with Canon;Canon EOS Rebel SL3;22.3;usercontribution on it

**Comment by skinkie** [comment]
> Just out of curiosity. If use the standard cameraSensors.db does the program work for you?

@GJPfaff  ^^

**Comment by GJPfaff** [comment]
No sir the current db does not have my camera sensor that is why I added it.  Either way I get same error.

**Comment by skinkie** [comment]
@GJPfaff A standard Meshroom installation will work *without* your specific sensor in there.

**Comment by GJPfaff** [comment]
I used the Windows installer package to install Meshroom.  What else is there to change? I Googled this for 2 days.  I had no problem using the monstree test images.  Meshroom is not accepting my Canon SL3 images.  Why I am here.  If there is some step I am missing please share.

**Comment by GJPfaff** [comment]
With or without my camera in the DB it does not work with my images.

**Comment by skinkie** [comment]
@GJPfaff if you want I can checkout your images. If you can put them somewhere :)

**Comment by GJPfaff** [comment]
I posted the EXIF link above.,  Tells you all you need to know about them. I even tried changing settings from RAW to JPEG etc.

**Comment by skinkie** [comment]
I does not tell me anything :-D because I cannot try it in meshroom myself.

**Comment by GJPfaff** [comment]
Wonder if it is because they are in .cr3 format.  Cannot get public photo hosting sites to take them.

**Comment by skinkie** [comment]
> Wonder if it is because they are in .cr3 format. Cannot get public photo hosting sites to take them.

Convert the files to PNG or JPEG 100%, and just try again. You will be surprised that even a scaled down image (1MP) is giving good structure results.

**Comment by natowi** [comment]
Yes, cr3 is not yet supported. It was only recently been added to the library we use for importing images in Meshroom https://github.com/OpenImageIO/oiio/blob/master/CHANGES.md

**Comment by GJPfaff** [comment]
AH!!!  I knew it was probably too new.  Thank you for the info.  So is there something I have to change to update or is the coding still in the works @natowi

**Comment by natowi** [comment]
I don´t know if all the recent additions to oiio are included, but you could try replacing the files in 
> Meshroom-2019.2.0\qtPlugins\imageformats
with the QtOIIO files from [here](https://ci.appveyor.com/project/AliceVision/qtoiio/builds/32643580/artifacts)

**Comment by skinkie** [comment]
@natowi maybe rename the topic to "Setting up raw / cr3 files from Canon"

**Comment by GJPfaff** [comment]
Ok,  Must not be updated in the lib yet.  Still no go.

**Comment by natowi** [comment]
Simply use another format as skinkie suggested, until it is supported.

**Comment by GJPfaff** [comment]
Already on it.  Thanks

**Comment by GJPfaff** [comment]
Well it didnt like the DNG either....

**Comment by natowi** [comment]
Try tif or png

**Comment by GJPfaff** [comment]
TIFF worked.  Will be looking forward to the update to support cr3.  Thanks for the assist.

**Comment by natowi** [comment]
It should be included in the next release. Alicevision was updated a few days ago to support oiio v2.1.15
