### ISSUE TITLE
[question] Adding my blog article to tutorials: How to use 3D scanning for CAD modeling

### ISSUE THREAD

**Issue by PellelNitram** [alicevision/meshroom#925]
Hi,

let me start by saying that Meshroom is amazing! And because of that, I used it for a toy project recently for which I also wrote a blog article. There, I explain how to use 3D scanning (using Meshroom) for CAD modeling. Also, I added a Jupyter Notebook for Google Colab and a feature-rich A4 printout to help Meshroom to find more features in the scene (it is more or less the same that https://www.youtube.com/watch?v=nWh51Ipp5Sc found independently from me).

My toy project was a custom transportation box for my tiny PC bluetooth mouse. I also recorded a small video of that project - it does not go into the details of Meshroom itself but shows what I used it for & thereby what Meshroom is capable of.

- You can find the blog article here: http://lellep.xyz/blog/how-to-use-3d-scanning-for-cad-modeling.html
- You can find the video here: https://www.youtube.com/watch?v=aft_jvATzFQ.

Do you think it is possible to add this blog post to the list of tutorials (here: https://github.com/alicevision/meshroom/wiki/Tutorials)? I have no commercial interests so that I don't feel guilty to ask at this point :-).

**Comment by simogasp** [comment]
@natowi

**Comment by natowi** [comment]
Thank you for sharing, I have added it to the wiki list [here](https://github.com/alicevision/meshroom/wiki/Tutorials). The wiki will be integrated into the docs soon.

**Comment by AccomplishedCode** [comment]
This is great! Thank you for your contribution!

**Comment by PellelNitram** [comment]
I am glad to read about your interest! It was a pleasure to contribute in this way and I hope that it helps to promote Meshroom a tiny bit more.

Thanks for adding it to the list of tutorials!

@natowi: Yes, please do so. CC-BY-SA means that, amongst others, me as the author of the picture will be credited, right?

**Comment by natowi** [comment]
> CC-BY-SA means that, amongst others, me as the author of the picture will be credited, right?

@PellelNitram, Thanks. Yes, I will give credit to you for the images I use from your tutorial. The whole manual is licensed under CC-BY-SA (Attributions, Share alike).

**Comment by PellelNitram** [comment]
Great! Please go ahead then. Thanks!
