### ISSUE TITLE
[question] Weird camera positions and sparse cloud with 360 datasets

### ISSUE THREAD

**Issue by TimothieGeulin** [alicevision/meshroom#926]
I tried several 360 datasets from several cameras that I splitted with AV's 360 splitter using several differents parameters (2, 4 and 8 splits, with resolutions of 1200 and 2400) and each combinations of these datasets always give me the same kind of weird results:

![weird](https://user-images.githubusercontent.com/31931443/83639799-7f2f0500-a5ab-11ea-936e-1ece076ac143.png)

The cameras are all placed on one side or the other of a line of points all on the same axis.
I thought at first that it had something to do with my camera but since I tested with some others as well i'm not sure anymore... So i think it have something to do with something that i'm unaware of which is highly likely since there's a whole lot of parameters in the pipeline that I don't understand.
I saw that some peoples had great results with splitted 360 pictures, so is there something in the pipeline that I need in order to do the same?

 - OS: Windows 10
 - Meshroom version: Release
   - Binary version 2019-2.0

[Dataset 1](https://drive.google.com/file/d/1hr8lwSYgUGyNpr2Yw7-xlsh1QBpfT-eC/view?usp=sharing) Original has 46 pictures, from a MADV QJXJ01FJ
[Dataset 2](https://drive.google.com/file/d/1eRAUVUK8mZ1hdHRxHXxDV950jRwYLmqC/view?usp=sharing) Original has 27 pictures, from a MADV QJXJ01FJ
[Dataset 3](https://drive.google.com/file/d/12JvLqIkWI3v4Ql1MW29TOOCLLEA-rLNH/view?usp=sharing) Don't know about that one, not mine, found it somewhere in this git

EDIT: Updated links, I uploaded them at the wrong place :)

**Comment by natowi** [comment]
What camera(s) do you use? Can you share a small sample dataset for testing?

**Comment by TimothieGeulin** [comment]
I'll add those to the original post

**Comment by TimothieGeulin** [comment]
Edited the original post

**Comment by TimothieGeulin** [comment]
No ideas ?

**Comment by natowi** [comment]
You probably took too few images. Depending on what you are trying to capture you need to take images from different places.

**Comment by TimothieGeulin** [comment]
Hmmm I thought it was enough, will try again with more then

**Comment by TimothieGeulin** [comment]
Okay so I tried with 450 shots of a smaller room and I still only have that kind of result, could it also have something to do with potentially incorrect metadatas?

**Comment by natowi** [comment]
Yes, that is possible. I´d have to look into this. Alternative: Do you have the (dual) fisheye images from your camera? Split the dual fisheye to single fisheye. Single fisheye images can be processed in Meshroom by changing the settings to fisheye in the cameraInit settings. Processing should work fine.

**Comment by TimothieGeulin** [comment]
I'll try this !

**Comment by TimothieGeulin** [comment]
I splitted the dual fisheyes but I don't see any fisheye setting in CameraInit, is it CLI only maybe? Or do I just put a 180 FOV ?

**Comment by TimothieGeulin** [comment]
It worked perfectly with single fisheyes ! Thanks for the help :)

**Comment by natowi** [comment]
Good. I´ll try to figure out what went wrong with your original dataset when I have some time.
