### ISSUE TITLE
[question] Photometric Stereo Reconstruction for GelSight Images

### ISSUE THREAD

**Issue by darty** [alicevision/meshroom#928]
I'm new to Meshroom and I apologize if this question is off-topic or unrelated.

I was wondering if it would be possible to use Meshroom to reconstruct images taken with a custom GelSight sensor?

## Example data
The following repository of Siyuan Dong has a nice test data set:
https://github.com/siyuandong16/gelsight_heightmap_reconstruction/tree/master/python_version/test_data

## GelSight info
A GelSight device consists of a silicone with a known hardness factor and has a reflective membrane layer. By pressing an object to the silicone, it will deform the membrane based on the surface structure of that object. Using this silicone, pictures are taken from a fixed position, with RGB lighting reflecting the surface details. Reconstruction of the surface normals is done based on calibration images taken of an object with a known geometry (i.e., a sphere). The surface normals are converted to a heightmap.

## Background
I'm asking this because I have built my own setup and I'm currently working on the reconstruction software. It would be great if this would be possible with an existing tool. If this is not possible with Meshroom, perhaps I can integrate my code with the software?

## References
Dong et al., Improved GelSight Tactile Sensor for Measuring Geometry and Slip, https://arxiv.org/pdf/1708.00922.pdf

**Comment by natowi** [comment]
That is really interesting, but I think the technology used for reconstruction (RGB lighting reflecting the surface details) is closer to RTI (Reflectance Transformation Imaging System) than photogrammetry. 
(http://culturalheritageimaging.org/What_We_Offer/Downloads/Process/index.html, example: https://rtimage.us/?page_id=86)

**Comment by darty** [comment]
Thank you for the info!

Are there any plans to include RTI workflows into Meshroom in the near future?

**Comment by fabiencastan** [comment]
@darty Yes, we are interested to integrate photometric stereo into the pipeline.
Would you be available for a confcall to discuss about it?
My email: fabien.castan@mikrosimage.com

**Comment by darty** [comment]
I'll reply via email 👍

**Comment by MikeZski** [comment]
Hi, this issue is very interesting to me. Did you make any progress?

**Comment by racer993** [comment]
Please let me know if there is any progress, it would be great if it would be possible to combine photometric stereo with photo grammetry to get the best of both worlds.

**Comment by fabiencastan** [comment]
You can follow the progression here:
https://github.com/alicevision/Meshroom/pull/1853
