### ISSUE TITLE
[my dataset is not reconstructed properly]

### ISSUE THREAD

**Issue by Karina-code** [alicevision/meshroom#932]
When I load images and start, it stops by error. 
I attach screenshot
I am using Windows 7, 64 bits, 12 GB RAM, Intel(R) HD Graphics 3000 graphics card. Meshroom 2019 2.0, downloaded from AliceVison page.

Could someone help me with this problem please? I am a beginner in this. Thank you very much.

![Screenshot](https://user-images.githubusercontent.com/66569699/83978632-4a8ab880-a8df-11ea-97db-4d441742749a.jpg)
![Screenshot2](https://user-images.githubusercontent.com/66569699/83978636-4bbbe580-a8df-11ea-993a-b7a820f94b0d.jpg)

**Comment by natowi** [comment]
Try again with another image path that does not contain special chartacters FOTOGRAMETR**Ì**A.
Also choose a folder for meshroom in a location that is not dedicated by the OS. If you have a second disk, place images and meshroom in d:/meshroom/... This helps to eliminate potential sources for errors. 

If you don´t have a nvidia gpu you need to change the graph: https://github.com/alicevision/meshroom/wiki/Draft-Meshing
To get better results you can optimize the parameters https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters

Note that your dolphins are difficult to reconstruct (reflective surface, don´t fill most of the image frame)

**Comment by Karina-code** [comment]
> Inténtelo nuevamente con otra ruta de imagen que no contenga caracteres especiales. FOTOGRAMETR **Ì** A.
> También elija una carpeta para meshroom en una ubicación que no esté dedicada por el sistema operativo. Si tiene un segundo disco, coloque imágenes y meshroom en d: / meshroom / ... Esto ayuda a eliminar posibles fuentes de errores.
> 
> Si no tiene una GPU nvidia, debe cambiar el gráfico: https://github.com/alicevision/meshroom/wiki/Draft-Meshing
> Para obtener mejores resultados, puede optimizar los parámetros [https://github.com/ alicevision / meshroom / wiki / Reconstruction-parámetros](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters)
> 
> Tenga en cuenta que sus delfines son difíciles de reconstruir (superficie reflectante, no ocupan la mayor parte del marco de la imagen). Para comenzar, use mejor algunos materiales naturales como rocas (sin pulir), madera, ... que son fáciles de reconstruir.

**Comment by Karina-code** [comment]
Natowi, First of all, thank you very much for responding quickly. And thanks for the tips.
I downloaded the CUDA toolkit, and the program went further with the images, but then stopped. It seems like I need a NVIDIA graphics card for it to work at all.
What characteristics should the graphics card have, that is, what model or specifications? Thanks again.

![Screenshot3](https://user-images.githubusercontent.com/66569699/83984590-301b0400-a90c-11ea-8a3d-c5ec4e9a1815.jpg)
![Screenshot4](https://user-images.githubusercontent.com/66569699/83984593-314c3100-a90c-11ea-91dc-4aa6e20ca236.jpg)

**Comment by Karina-code** [comment]
@natowi
First of all, thank you very much for responding quickly. And thanks for the tips.
I downloaded the CUDA toolkit, and the program went further with the images, but then stopped. It seems like I need a NVIDIA graphics card for it to work at all.
What characteristics should the graphics card have, that is, what model or specifications? Thanks again.

**Comment by natowi** [comment]
You need to modify the graph as described here  https://github.com/alicevision/meshroom/wiki/Draft-Meshing to use Meshroom without a NVIDIA Graphics card.

The NVIDIA Graphics card should support at least Cuda compute capability 2.0+ ([table](https://en.wikipedia.org/wiki/CUDA))

**Comment by gryan315** [comment]
I'm not natowi, but I've done a lot of testing with different Nvidia cards, from GTX 680 up to 1080 ti. I would recommend a GTX 1060 6gb model as a minimum, used models can be found for $120-140. The 1060 outperformed 2x GTX 780s, as well as the GTX 970.

**Comment by Karina-code** [comment]
@natowi I did it, I modify the graph, but it didn't go well. I will try with other images. Thank you very much again!

**Comment by Karina-code** [comment]
@gryan315 Hi, thank you very much for your comment and contribution. I looked at this model, here in my country, it has approximately 334 dollars, which would be equivalent to about 23.000 pesos in muy country, something far from my budget. Anyway, thank you very much! I hope this has a solution.

**Comment by gryan315** [comment]
@Karina-code that's just what I would recommend for efficiency. The depthmap will run on any supported card, but it will be very slow with some of these older ones. Some good cheaper options could be the GTX 650, 660, 750, 760, 950, 960, which should give acceptable performance. While the 500 series meets the minimum CUDA compute capability, it's no longer supported by the latest Nvidia drivers. The 600 series is still fully supported, but who knows for how much longer.

**Comment by natowi** [comment]
> I did it, I modify the graph, but it didn't go well. I will try with other images. 

You probably need to increase the quality of the reconstruction, as described [here](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters) (change describer preset, add akaze)

A better structured object will be easier to reconstruct.

**Comment by Karina-code** [comment]
@natowi  I will tray it. I hope to be lucky with this. Thank you so mach again!

**Comment by Karina-code** [comment]
@gryan315  Thanks for these recommendations. I will keep them in mind. Thank you, thank you very much!
