### ISSUE TITLE
[question] User supplied camera and track ?

### ISSUE THREAD

**Issue by redhoot-dev** [alicevision/meshroom#934]
I have several shots that have been camera tracked already and have fairly accurate lens calculations. I would like to use this data in meshroom to create a dense pointcloud and reconstruct the surface. 

IE, is it possible to supply an alembic camera instead of calculating it in meshroom first ? 

I have found that meshroom and our tracking soft produce slightly different results, especially meshroom as the data is only from one angle sort of speak. 

Thanks!

**Comment by natowi** [comment]
You can use your lens information in the cameraInit node camera intrinsics:

```
// Id #unique image id (auto-generated)
// Initial auto-estimated Focal Length (-1 unknown)
// Focal Length (known/calibrated)
// Camera Type (pinhole, radial, brown, fisheye)
// Width of the image (integer)
// Height of the image (integer)
// Serial Number
// principal point x-coord (double)
// principal point y-coord (double)
// Initialization Mode (unknown, calibrated, estimated, none)
// DistortionParams:
// #k0 (double)
// #k1 (double)
// #k2 (double)
```

With the upcoming release there will be an (experimental) option to use known camera positions.
For details read https://github.com/alicevision/meshroom/wiki/Using-known-camera-positions
As a starting point you could convert your alembic file to .sfm using the convertsfmformat.
