### ISSUE TITLE
Question about JPEG 2000 File Format

### ISSUE THREAD

**Issue by lal0cura** [alicevision/meshroom#937]
Hi Everyone. I hope that you are OK
I'm having this issue with .JP2 files under Linux. I drag my files to the image pane but they are ignored. 

The reason that I use that format is because it gives visually lossless quality in very little space.
For example .PNG files uses 4.8 Mb for each file. 
In .JP2 files with the same quality uses only 1.6 Mb each. So it can save a lot of space.

I have 5 Sequences in PNG that uses about 18Gb, in JP2 it uses 4.6Gb with the same visual quality.

So I was wondering if Meshroom can in fact support .JP2 File Formats. (Jpeg2000).
According to the manual it should be  because JP2 are part of the OIIO Library.

So I'm not sure if it is a bug, or I'm the only one having this issue. I hope you could check it up to see if you can use that file format or also you cant use them.

I use Meshroom in Ubuntu 20.04.

Thanks.

PD. when I drag the .jp2 file to the image Pane I get this error in the console:

Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "20EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "" (default)
 * output = "/tmp/tmp2w3jkfgy/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm"
 * sensorDatabase = "/home/lal0cura/apps/Meshroom-2019.2.0/aliceVision/share/aliceVision/cameraSensors.db"
 * verboseLevel = "info"

[23:40:57.083444][error] Program need -i or --imageFolder option
No input images.
ERROR:root:Error while building intrinsics : Traceback (most recent call last):
  File "/opt/Meshroom/meshroom/ui/reconstruction.py", line 399, in buildIntrinsics
  File "/opt/Meshroom/meshroom/nodes/aliceVision/CameraInit.py", line 192, in buildIntrinsics
RuntimeError: CameraInit failed with error code 1. Command was: "aliceVision_cameraInit  --sensorDatabase "/home/lal0cura/apps/Meshroom-2019.2.0/aliceVision/share/aliceVision/cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "/tmp/tmp2w3jkfgy/CameraInit/c448939571d5c70b05c9ae4ad416ada37d6273ca/cameraInit.sfm" --allowSingleView 1 "

**Comment by natowi** [comment]
I can confirm that.

**Comment by lal0cura** [comment]
Thanks.

Actually it would be great if Meshroom could add support for the complete filetypes of the OIIO library on some release in the future.

Its kinda odd that you can drag an .exr but no JP2.  (JP2 is used in digital cinema and in the medical field)

Thanks, have a great Day. Stay Safe

**Comment by natowi** [comment]
The image formats will be supported with the next release.
