### ISSUE TITLE
Current stage of gpu for computer

### ISSUE THREAD

**Issue by itisyeetimetoday** [alicevision/meshroom#939]
I've noticed that 1. my GPU usage is always pinned at 40% on my GTX 1060 3gb, and I have never seen it go beyond or below that, even when CUDA nodes are running, like depth map. It is also always around 30-40%, even when not computing. Second, as of 2020, what is the status on utilizing the GPU for more nodes and using more the GPU's power(e.g. using more of the cores, and having them active and computing more often)?

**Comment by natowi** [comment]
We are still working on it to improve the use of resources.
https://github.com/alicevision/meshroom/issues/673 https://github.com/alicevision/meshroom/issues/886

We tested multithreading, but the speed-up is not huge, it reduces the overall computation time only by ~10%. It requires more work to optimize the hardware usage.
