### ISSUE TITLE
Sensor Database complete guide button currently points to wrong wiki page

### ISSUE THREAD

**Issue by uGuardian** [alicevision/meshroom#942]
Currently the complete guide button points to
[https://github.com/alicevision/meshroom/wiki/Add-Camera-to-database](https://github.com/alicevision/meshroom/wiki/Add-Camera-to-database)
instead of
[https://github.com/alicevision/meshroom/wiki/Add-a-new-camera-to-the-database](https://github.com/alicevision/meshroom/wiki/Add-a-new-camera-to-the-database)
which is the page with the right information.

**Comment by natowi** [comment]
Yes, someone messed this up, I don´t know how this happened.

**Comment by uGuardian** [comment]
Probably because currently it seems anyone can edit the wiki and someone renamed the file, and then someone else posted a new page in its' place asking for "help"
I considered reverting the changed, but then I noticed you'd made edits to the real file since the rename, so I just posted a bug report instead.

**Comment by natowi** [comment]
Thanks for reporting, it´s fixed now. In the long run, the wiki will be merged with the documentation.
