### ISSUE TITLE
[question] Fixed model size?

### ISSUE THREAD

**Issue by xzhub** [alicevision/meshroom#944]
**Describe the problem**
After searched for how to generate a real size model, I Iearned that it is in the todo list and will take some time to implement. Since I'd like to view the model in AR model, it's very difficult to view a giant model. Currently, the model for a doll could be as large as a house, I have to scale to 10% to fit it on my desk. I am wondering if there is a way to restrict the model to fit in a limit cube, like 1 meter x 1 meter x 1 meter box, so that no mater how large the real thing is, the model can be easily viewed on my desk.

I am using Linux command version of mushroom 2019.2.

**Comment by natowi** [comment]
No it is not possible to scale a model to a fixed size, as the algorithm has no reference for scale.
With the next Meshroom release you will be able to use CCTAG markers placed in the scene with a known distance to scale your model to real world size.

At the moment you can use MeshLab to scale your models https://www.youtube.com/watch?v=6psAppbOOXM

**Comment by xzhub** [comment]
Is there anywhere in the log of meshroom_photogrammetry to show user how large the model is? With this number I might be able to set the scale factor in SfMTransform node then run it again to get a better sized model.

**Comment by natowi** [comment]
No, reconstructed scene is in its own internal coordinate system, without a reference in the reconstructed scene we don´t know the conversion value to real world measures. You can calculate this value by measuring a known distance in Meshlab and calculate the conversion value, but this value will change for a new reconstruction except when using a fixed camera dome rig.

**Comment by NexTechAR-Scott** [comment]
This is not a Meshroom issue.  Scale the model to the correct size with an external editor.
