### ISSUE TITLE
OpenDroneMap Node [request]

### ISSUE THREAD

**Issue by jeffreyianwilson** [alicevision/meshroom#945]
Are there any plans to support strong GIS, drone feature support such as OpenDroneMap (ODM)?  Could ODM CLI commands be passed through and shared in Meshroom nodes?

Jeff

**Comment by natowi** [comment]
Adding more geospatial tools natively to Meshroom is on the long term to do list. I am supporting this idea, too. 

You could write some nodes to access ODM cli https://github.com/natowi/meshroom_external_plugins/wiki/2-DevDoc.

**Comment by natowi** [comment]
I close this issue, as it does not really make sense to integrate ODM.
Native support for geospatial within Meshroom is on the to-do list (like https://github.com/alicevision/meshroom/issues/246 / https://github.com/alicevision/AliceVision/issues/402), but won´t likely be added anytime soon without community contributions as many other features have a higher priority.
