### ISSUE TITLE
DepthMap error[bug]

### ISSUE THREAD

**Issue by rlg1860** [alicevision/meshroom#947]
**Describe the bug**
The process is always stopped at the DepthMap stage. I've tried with several models and I have the same results.

**To Reproduce**
I followed the default values.

**Screenshots**
![error](https://user-images.githubusercontent.com/50922177/84660537-5aae2380-aeef-11ea-91a3-d4e467c2608e.jpg)

**Log**

[1/5](1/32) DepthMap
 - commandLine: aliceVision_depthMapEstimation  --input "C:/rodo2/2/MeshroomCache/StructureFromMotion/229e19c09b9d732e040aa895430a1541613c95db/sfm.abc" --imagesFolder "C:/rodo2/2/MeshroomCache/PrepareDenseScene/e940afcf6890810aedffd33791f8135dfe5fe1f7" --downscale 1 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel error --output "C:/rodo2/2/MeshroomCache/DepthMap/6c06d0c6af637d04d597ae809ddf7954ff221d61" --rangeStart 0 --rangeSize 3
 - logFile: C:/rodo2/2/MeshroomCache/DepthMap/6c06d0c6af637d04d597ae809ddf7954ff221d61/0.log
 - elapsed time: 0:00:30.929997
**ERROR:root:Error on node computation: Error on node "DepthMap_1(0)":
Log:**
Program called with the following parameters:
 * downscale = 1
 * exportIntermediateResults = 0
 * imagesFolder = "C:/rodo2/2/MeshroomCache/PrepareDenseScene/e940afcf6890810aedffd33791f8135dfe5fe1f7"
 * input = "C:/rodo2/2/MeshroomCache/StructureFromMotion/229e19c09b9d732e040aa895430a1541613c95db/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/rodo2/2/MeshroomCache/DepthMap/6c06d0c6af637d04d597ae809ddf7954ff221d61"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "error"

WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(11)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(12)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(13)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(14)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(15)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(16)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(17)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(18)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(19)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(20)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(21)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(22)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(23)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(24)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(25)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(26)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(27)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(28)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(29)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(30)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(31)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "DepthMap_1(0)":
Log:
Program called with the following parameters:
 * downscale = 1
 * exportIntermediateResults = 0
 * imagesFolder = "C:/rodo2/2/MeshroomCache/PrepareDenseScene/e940afcf6890810aedffd33791f8135dfe5fe1f7"
 * input = "C:/rodo2/2/MeshroomCache/StructureFromMotion/229e19c09b9d732e040aa895430a1541613c95db/sfm.abc"
 * maxViewAngle = 70
 * minViewAngle = 2
 * nbGPUs = 0
 * output = "C:/rodo2/2/MeshroomCache/DepthMap/6c06d0c6af637d04d597ae809ddf7954ff221d61"
 * rangeSize = 3
 * rangeStart = 0
 * refineGammaC = 15.5
 * refineGammaP = 8
 * refineMaxTCams = 6
 * refineNDepthsToRefine = 31
 * refineNSamplesHalf = 150
 * refineNiters = 100
 * refineSigma = 15
 * refineUseTcOrRcPixSize = 0
 * refineWSH = 3
 * sgmGammaC = 5.5
 * sgmGammaP = 8
 * sgmMaxTCams = 10
 * sgmWSH = 4
 * verboseLevel = "error"

**Desktop (please complete the following and other pertinent information):**
 - OS: Windows 10 64 bits 1909
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable)2019.2 (downloaded two days ago)

**Comment by natowi** [comment]
What are your hardware specs?

Check out if this can fix your problem https://github.com/alicevision/meshroom/wiki/DepthMap-slow-or-red-bar-or-crash

**Comment by rlg1860** [comment]
yes, I've tried but it didn't work.

Attach my hardware specs: 

[cpuid.txt](https://github.com/alicevision/meshroom/files/4799227/cpuid.txt)

**Comment by natowi** [comment]
Hardware looks good.
Do you have the latest drivers for the GPU installed?
