### ISSUE TITLE
Which algorithm is used by Meshroom for Texturing?

### ISSUE THREAD

**Issue by SBCV** [alicevision/meshroom#948]
**Describe the problem**
I want to cite Meshroom as well as the texturing algorithm used by Meshroom.  
Unfortunately, the [texturing documentation](https://meshroom-manual.readthedocs.io/en/latest/node-reference/nodes/Texturing.html) does not provide the corresponding information.
Thus, I'm wondering, if Meshroom has it's own texturing algorithm, or if the reference is missing in the documentation.
Since I could not find any information in the comments of the source code, I'm a bit lost. Would be nice, if someone could shed some light on this.

**Comment by fabiencastan** [comment]
Hi,
The texturing part is not a direct implementation of an existing paper.
The approach is based on a generalization of the multi-band blending ("A Multiresolution Spline With Application to Image Mosaics", Burt, Adelson, 1983) applied to 3D texturing with weighting strategies based on visibility and varying resolution.
It's in the same spirit than "Seamless Image-Based Texture Atlases using Multi-band Blending", Allène, Pons and Keriven, 2009 and "Blending images for texturing 3D models", Baumberg, 2002.

**Comment by fabiencastan** [comment]
So all you can do is a general citation:
```
@Misc{Meshroom,
  Title                    = {{Meshroom: A 3D reconstruction software.}},
  Author                   = {AliceVision},
  Year                     = {2018},
  url = {https://github.com/alicevision/meshroom}
}
```

**Comment by fabiencastan** [comment]
And we should update the doc on both the manual and the [website](https://alicevision.org/#photogrammetry/texturing).

**Comment by SBCV** [comment]
Thank you very much for the quick response! 
And for the detailed answer. I'll check out the papers. Thank you! 
If you want I can make a PR for that.

**Comment by fabiencastan** [comment]
Sure, that would be great!

**Comment by SBCV** [comment]
Added the PR, but I guess, I can't add the reference to the [webpage](https://alicevision.org/#photogrammetry/texturing).

**Comment by fabiencastan** [comment]
Thanks for the PR!

The website is also editable online: https://github.com/alicevision/alicevision.github.io/blob/master/view/pipeline/7_texturing.html

**Comment by SBCV** [comment]
Added a second PR, I hope I did not change the semantics, while merging those two descriptions
