### ISSUE TITLE
[question] How to reuse existing cache after changing some parameters in pipeline file (CLI)

### ISSUE THREAD

**Issue by xzhub** [alicevision/meshroom#949]
I noticed the intermediate files are stored in {cache}/{nodeType}/{uid0}/. The {uid0} is changing everytime you run the command `meshroom_photogrammetry --input img/ --output result/ --pipeline pipeline.mg`, even the pipeline.mg file is the same.

I tried to modify the pipeline.mg file, change all the `{cache}/{nodeType}/{uid0}/` to `{cache}/{nodeType}/`, so the cache file can be put into the same folder. However, seems this does not change anything, all the intermediate files are still being saved to folder `{cache}/{nodeType}/{uid0}/`

I'd like to know after I modify the parameters in pipeline.mg file, can meshroom_photogrammetry reuse the cache file and only redo the necessary steps? Thanks!

**Comment by natowi** [comment]
You can only re-use previously computed nodes up to the point where you changed a node. This node and all following nodes will be invalidated.
For the default graph:
If you change a parameter in the Meshing node, the node and the following nodes will be invalidated, but previously computed nodes will be kept. 
If you make changes in FeatureExtraction, all following nodes will be invalidated.
If you change the image count or other values in CameraInit, the whole graph will be invalidated.

**Comment by xzhub** [comment]
You are right, I modified a node in the beginning, so most of the nodes are recalculated.  Thanks!
