### ISSUE TITLE
[question] HDRI pipe line error (PanoramaExternalInfo: No such node (papywizard.header.lens))

### ISSUE THREAD

**Issue by thima2017** [alicevision/meshroom#952]
I don't know whether it's a bug report or a question. 
While trying to make HDRI map I get this messages in PanoramaExpternalInfo node:

```
Program called with the following parameters:
 * config = ""
 * input = "/media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/Documents/pan-mr/MeshroomCache/LDRToHDR/939be92a7a28b7f14eb18abe1023ba4d4d20646a/sfmData.sfm"
 * outSfMDataFilename = "/media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/Documents/pan-mr/MeshroomCache/PanoramaExternalInfo/7716c77eec7c09c1fd7ec75cf20754f7a86c7025/sfmData.abc"
 * verboseLevel = "debug"

Error parsing input file
[15:39:58.021753][fatal] No such node (papywizard.header.lens)
```
I tried to install papywizard with setup.py install --user, but it doesn't help. Probably it can't find the headers or something. 

And PanoramaExternalInfo has input for xml config file. Is it required and how to get it?

**Desktop**
 - OS: Ubuntu 20.04
 - Python version 2.7
 - Qt/PySide version 5.14.2
 - Meshroom version: I get it with git clone yesterday, I don't know what is the version.

I run meshroom with this command line:
```
MESHROOM_INSTALL_DIR=/media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/bouilds/meshroom/meshroom LD_LIBRARY_PATH=/media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/bouilds/meshroom/instdir/lib PYTHONPATH=. python meshroom/ui
```
And I have symlinks for qtPlugins, aliceVision and lib in meshroom's root.

**Comment by natowi** [comment]
This is a new feature and not yet documented.

**Comment by fabiencastan** [comment]
and not yet fully finished ;)
See wip in PR https://github.com/alicevision/meshroom/pull/808
