### ISSUE TITLE
[question] how to increase the output model faces 

### ISSUE THREAD

**Issue by MMmaomao** [alicevision/meshroom#954]
**Describe the problem**
I had tried some parameter, but the output model faces is always the same. about 120W faces,
Did I miss something ? I just want to increase the faces to 300W. I can do this in realitycapture. Can I do this in meshroom?
thank you

**Comment by fabiencastan** [comment]
Have you tried to set "downscale" to 1 on the DethpMap node?

**Comment by MMmaomao** [comment]
Yes, I tried downscale and it just increase the faces a little. but still can't get 300w faces
Is there any other settings?
thank you

**Comment by natowi** [comment]
https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters

**Comment by MMmaomao** [comment]
also tried the Reconstruction-parameters still not working.

**Comment by fabiencastan** [comment]
Not so easy to answer without any idea of the kind of dataset you are using (nb images, images resolution, image quality, textured surfaces or not, etc).
If you enable advanced parameters, you can experiment with more parameters.

On the Meshing node, you can set:
- `pixSizeMargin*` to 1
- `minStep` to 1

If it's still not enough, you could try to reduce the following params on the `DepthMapFilter` (but it may introduce more noise):
- `minNumOfConsistenCams` to 2
- `minNumOfConsistenCamsWithLowSimilarity` to 3

**Comment by MMmaomao** [comment]
thanks, I'll give it a shot

**Comment by MMmaomao** [comment]
I tried a fresh test, and this time "downscale" to 1 is worked, thanks all you guys
