### ISSUE TITLE
Importing Video

### ISSUE THREAD

**Issue by claudito1991** [alicevision/meshroom#955]
Hi fellows, 

I'm trying to import a video into meshroom to extract the stills from it using the KeyFrameSelection node but i'm having some troubles. 

I have two videos to test this a .mov and a .mp4 and when i drag&drop them nothing seems to load into the program.

I've tried a workaround by manually typing the path to the video and compute the node but i got this messages into the log  (image) and the cache file it's empty.

What am i doing wrong?

![image](https://user-images.githubusercontent.com/30451301/85164901-62493180-b23b-11ea-80ea-72eb7a1344d6.png)

**Comment by claudito1991** [comment]
To add more detail to this. The method i'm using now is to split the video in GIMP and (also in GIMP) lowering the density of frames, but the thing here is that i want to use KeyframeSelection node because it seems more fit to the task

**Comment by claudito1991** [comment]
So the node seems to compute succesfully but there's no frame in the output folder. I'm pasting the Log and status output. I can't understand this

[status.txt](https://github.com/alicevision/meshroom/files/4806607/status.txt)
[log.txt](https://github.com/alicevision/meshroom/files/4806608/log.txt)


and this is how i'm placing the node

![keyframe2](https://user-images.githubusercontent.com/30451301/85177935-8fa1d980-b253-11ea-9560-94c444219990.png)

**Comment by natowi** [comment]
Maybe an issue with your path? Test it again with your .mp4 file with short filename and path without special characters. ("clau_" could be an issue).

**Comment by claudito1991** [comment]
@natowi thanks i will try right away...another thing i've found if i try to drag&drop the video file i get this 
![image](https://user-images.githubusercontent.com/30451301/85178953-1b1c6a00-b256-11ea-8314-6a4b168f8f95.png)

**Comment by claudito1991** [comment]
Thanks @natowi i will try that right away. Another thing i've found if i try to drag&drop i get this error.
![impresiondepantalla](https://user-images.githubusercontent.com/30451301/85179112-74849900-b256-11ea-831a-bfc2fb978321.png)

**Comment by ChemicalXandco** [comment]
Video files are not supported with drag and drop in the latest binary release.

**Comment by natowi** [comment]
Yes, Drag and drop is not supported in 2019.2

**Comment by claudito1991** [comment]
@natowi i've tried with C:\test\celular.mp4 (changed the file name too) it doesn't work. In fact in DOES work but the log keep saying 'skipped' at every frame

**Comment by claudito1991** [comment]
@ChemicalXandco i see, but with the path it doesn't seem to work either. For me of course

**Comment by natowi** [comment]
What kind of video do you want to process? You may need to adjust the frame selections settings.

**Comment by claudito1991** [comment]
it's a cellphone made video. The camera take at best 13mp images, the video quality puts 'FHD' i believe it's 30 fps wich settings could be doing this?

**Comment by natowi** [comment]
If your image is too short, blurry or does not move enough... many frames may get dismissed.
You can try disabling Use Sparse Distance and Use Sharpness.

**Comment by claudito1991** [comment]
@natowi you were absolutely right man. My video seems to be pretty bad for the default presets, by lowering the sharpness preset i could get some images selected, i will keep playing with the options THANKS A LOT!

**Comment by NexTechAR-Scott** [comment]
Use ffmpeg command line to extract the frames.

ffmpeg -i source_filename.mpg  -vf fps=1 %d.jpg

change fps value to how many frames you want to extract per each second

you can use png or tiff for output filename

**Comment by claudito1991** [comment]
ohhh yes, to extract the videoframes i've used GIMP until now. But i was more interested in this sort of 'filter' that MESHROOM could do to help me find the best frames

**Comment by natowi** [comment]
@NexTechAR-Scott With KeyframeSelection and the adjusted Use Sparse Distance and Use Sharpness settings you can reduce the extracted frames to a minimum to finally reduce the reconstruction time.

**Comment by lynrayy** [comment]
Bump
Needs video import, image import sucks
