### ISSUE TITLE
Having some issues with using the void technique.

### ISSUE THREAD

**Issue by gguy825** [alicevision/meshroom#958]
Here is what im getting in mushroom currently. https://imgur.com/a/5iWL5B4

Here are the photos i have of the models. https://imgur.com/a/alMU3EL

Photos have been cleaned up in lightroom with the same settings for each photo. Using 2 LED spotlights in a softbox.

**Comment by fabiencastan** [comment]
You have only 17 cameras solved out of 131 input images. So you probably have issues on feature matching. Have you tried to set the "FeatureExtraction" "Describer Preset" to HIGH?

**Comment by gguy825** [comment]
Ah no i havent. I was going to retry and adjust my lighting setup since i got some responses saying it was pretty bad.

**Comment by gguy825** [comment]
> You have only 17 cameras solved out of 131 input images. So you probably have issues on feature matching. Have you tried to set the "FeatureExtraction" "Describer Preset" to HIGH?

Ah no i havent. I was going to retry and adjust my lighting setup since i got some responses saying it was pretty bad.

**Comment by NexTechAR-Scott** [comment]
Not trying to be mean but yes, lighting is terrible.

Really deep dark shadows and reflections.

Running higher feature extraction preset with those conditions won't help and will most likely hurt.

You'd just be picking up more of the features that are already contributing to the issue.

**Comment by gguy825** [comment]
> Not trying to be mean but yes, lighting is terrible.
> 
> Really deep dark shadows and reflections.
> 
> Running higher feature extraction preset with those conditions won't help and will most likely hurt.
> 
> You'd just be picking up more of the features that are already contributing to the issue.

Yea you're right. Im actually picking up a new proper soft box later tomorrow since the ones i have now are a more on the DIY side and not very well built.
