### ISSUE TITLE
CCTAG Scaling

### ISSUE THREAD

**Issue by NexTechAR-Scott** [alicevision/meshroom#960]
Simple enough question

CCTAGS, can we scale them and if yes by how much before they break, 10%, 25%, 50%,?

**Comment by fabiencastan** [comment]
It depends on your shooting, not the real scale of the object. The only question is the final resolution in your image. You theoretically need at least one pixel per band. In real life your have blur, pixel interpolation, etc.

**Comment by NexTechAR-Scott** [comment]
Thanks Fabien

**Comment by fabiencastan** [comment]
See some challenging results here to get a feeling of the limits:
https://github.com/alicevision/CCTag/blob/489a0471316cddaabf67180dbd71e7ae55e3baa8/doc/sphinx/source/img/challenging.png
