### ISSUE TITLE
export to bundler out format

### ISSUE THREAD

**Issue by giancan** [alicevision/meshroom#962]
Hi there,
is it possible to export the SfM alignment (cloud_and_poses.abc) into  bundler out format? Or is there any workaround to convert the *.abc file into *.out file?

Thanks

**Comment by natowi** [comment]
It is not supported for now, but you are welcome to add an exporter to the [Bundler file format](https://github.com/snavely/bundler_sfm#output-format) in [AliceVision](https://github.com/alicevision/AliceVision/tree/develop/src/aliceVision/sfmDataIO).
