### ISSUE TITLE
Inconsistent orientation/scaling on mesh reconstructions

### ISSUE THREAD

**Issue by HumayunMughal** [alicevision/meshroom#966]
I am trying to generate meshes on consecutive frames on a facial recording sequence but I do get random orientation/scaling discrepancies. I wanted to check if there's a way in meshroom of storing camera positions for subsequent use so that consistent transformations can be applied to the processed frames?

Windows & meshroom build version used:
 - OS: [win 10 ]
 - Meshroom version: Binary version 2019.2.0

**Comment by natowi** [comment]
Looks like you are using Meshroom in Houdini. You should be able to use the SfMTransform node with "from single camera" and the view id to transform your model to.

**Comment by HumayunMughal** [comment]
Hi natowi, no this is a windows build 2019.1, which I'm directly running on Windows 10.

**Comment by natowi** [comment]
Can you send a full screenshot?

**Comment by HumayunMughal** [comment]
I think your invaluable suggestion will work and let me setup a project and get back to you. My apologies it's 2019.2.0, which I'm using. Here's a screen grab for version reference.
![image](https://user-images.githubusercontent.com/67459006/85838376-2dd8f680-b7a2-11ea-8ca0-da47916a841e.png)

**Comment by natowi** [comment]
Yes, that´s more like it ;)
Change the Transformation Method to Single camera and provide in Transformation the filename or viewid.

**Comment by HumayunMughal** [comment]
Hello @natowi,

Following up on the scaling/orientation issue, I am experiencing a consistent offset in scale and transformations across consecutive frames, even though transformation method remains to be set to from_single_camera for all these frames. I've enclosed a couple of gifs below illustrating the meshroom settings and the output mesh offsets. Also note, that for demonstration purpose, I've imported the A1.tiff images used for transformation from these folders, inside meshroom to show that these are all consistent across image folders and there's no discrepancy in terms of scaling and orientation. 
![transformation_source](https://user-images.githubusercontent.com/67459006/85999344-a34bfd80-ba14-11ea-9a74-985b3c0f58de.gif)
![mesh_offsets](https://user-images.githubusercontent.com/67459006/85998936-1a34c680-ba14-11ea-837b-2c4060a5c4b3.gif)

**Comment by natowi** [comment]
Yes, as Meshroom does not have any reference, the origin will vary for each reconstruction.
If you have multiple scans with overlapping images (for what ever reason), you can use the SfMAlignment node to align identical viewids.
Why don´t you compute the full dataset at once and only use the frontal image to align the orientation?

**Comment by HumayunMughal** [comment]
Hello @natowi, yes that's exactly what I'm doing because we have 16 image pairs per each facial reconstruction and the frontal image isn't available from the dataset, therefore I am using the ones shown above in the screenshot as A1.tiff images. Here's my meshroom project for every facial reconstruction (16 images):
![image](https://user-images.githubusercontent.com/67459006/86097702-b961c880-babd-11ea-8bd9-a45f9acfb5f2.png)

I am new to meshroom so I might not comprehend your recommendations entirely but do let me know if there's any specific steps I can follow to achieve the desired results.
Thanks for your patience.

**Comment by natowi** [comment]
B4.tiff looks suitable. You need to set the Additional Scale to 1 to avoid enlarging your model. 

Scaling and orientation is not finalized in MR 2019.2. You can get better/faster results by using Meshlab for this.

**Comment by fabiencastan** [comment]
If your setup is stable you can make a first reconstruction of a well textured object and then use this SfM result for all other captures.
