### ISSUE TITLE
Warning: "The number of intrinsics is incoherent"

### ISSUE THREAD

**Issue by hlyman** [alicevision/meshroom#967]
In FeaureExtraction, FearureMatching and StructureFromMotion I am getting the following warnings: "The number of intrinsics is incoherent"

**Comment by hlyman** [comment]
In FeatureExtraction, FeatureMatching and StructureFromMotion I am getting the following warnings: 
"The number of intrinsics is incoherent:" and
"3 intrinsics declared and 1 intrinsics used:"
Photo attached.
![Screenshot (73)](https://user-images.githubusercontent.com/1063100/85891015-48f83600-b7a3-11ea-959b-6764f3b712bf.png)

**Comment by natowi** [comment]
Did you change the camera zoom during the capturing process? You can check the camera parameters in the CameraInit node. This is just a warning and probably won´t affect your results.

**Comment by fabiencastan** [comment]
Maybe you have added images (with different intrinsics), and then removed them from Meshroom?

So when you have added these images in the first place, it has created new intrinsics and then you have removed some of the views. So some intrinsics still exist but no more View are using them. We may want to filter such intrinsics in the CameraInit, but I think it's not done for now.

There will be no side effect to have some unused intrinsics, except the warnings.

**Comment by hlyman** [comment]
I did have 8 views I made with a new zoom.  I deleted them after an 
unsuccessful run.  I am still learning.  The last photos were taken 
after I painted the model flat grey.

------ Original Message ------

**Comment by hlyman** [comment]
That is what I did.  I am still a beginner. Thanks.

------ Original Message ------

**Comment by hlyman** [comment]
Here is the pix of my last run.  I now think I need to learn 
![Screenshot (75)](https://user-images.githubusercontent.com/1063100/85909627-b9b54780-b7cf-11ea-9992-a784b92f025e.png)
how to take pictures.

**Comment by natowi** [comment]
Take a look at this tutorial: https://www.3dscanstore.com/blog/3d-scanning-reflective-objects (Step 1 Prepare the surface for scanning)

**Comment by hlyman** [comment]
I studied the link you show. I prepared the model by spay painting it with flat white and while wet I sprinkled it will white flour. I then brushed it off smooth.  I then flipped black water color dots all over it.  I took 110 pictures of which 98 were used. The picture shows my result.  I am ready to quit.
![Screenshot (80)](https://user-images.githubusercontent.com/1063100/86302698-4ee48180-bbbe-11ea-9fbf-009f67a43e3e.png)

**Comment by hlyman** [comment]
I had a dentist appointment a few weeks ago and the doc took pictures of my mouth using an Intraoral Dentist camera. I saw the pictures he took on the monitor and asked him to send me a jpg copy. He did and I loaded it into Meshmix and had a shell image. I made it a solid and then printed a perfect copy.
![Screenshot (82)](https://user-images.githubusercontent.com/1063100/86303662-5f4a2b80-bbc1-11ea-88e8-3a233a9b0d5e.png)
![Screenshot (84)](https://user-images.githubusercontent.com/1063100/86303664-62ddb280-bbc1-11ea-9aef-5439bcb16afb.png)
Can an Intraoral Dental Camera be added to the Meshroom camerasensor file?

**Comment by hlyman** [comment]
I made an error in the last post.  The teeth file was and stl file dentist sent me.

**Comment by natowi** [comment]
Compared to your last result from five days ago, you have 70000 more points in sfm and 200000 more triangles. How does your model look like? In the DepthMap node, you can adjust the Downscale and set it to 1 to increase precision, but be careful, the calculation will be ~4x longer.

>  Can an Intraoral Dental Camera be added to the Meshroom camerasensor file?

Meshroom can process images even without the sensor width. For dental cameras it is really difficult to find sensor information.
The only model I could find with a quick search that provided sensor information was the model MD810UW with a 1/4 sony CCD -> sensor width 3.2

**Comment by hlyman** [comment]
The file is running now with Downscale set to 1.  It is now 1/4 into DepthMap and the image is looking better. Here is a close up picture of the model.
![DSC03233](https://user-images.githubusercontent.com/1063100/86394267-22c71000-bc53-11ea-951f-a459f2cb597d.JPG)

**Comment by natowi** [comment]
And the reconstructed 3d model? your last screenshot only showed the point cloud, which looked good.

**Comment by hlyman** [comment]
I don't understand point cloud..  Attached is a picture of the run now after 3 hrs, about 2/5s
![Screenshot (86)](https://user-images.githubusercontent.com/1063100/86401011-65dab080-bc5e-11ea-8b45-8360b453b6ec.png)
 through DepthMap.  There are Bundle Adjustment failed warnings in StruturedFromMotion.

**Comment by natowi** [comment]
What you see in the 3d viewer window _is_ the point cloud (the StructureFromMotion output). It consists of 90525 points, compared to the 20000 you got without the black dots on your statue. I expect your model will be quite good.

Once Texturing completes, double click on the Texturing node to load it in the viewer and disable/remove the StructureFromMotion layer in the Scene area.

**Comment by hlyman** [comment]
I watched this video, a tutorial on Blender, Instant Mesh, and Meshroom":
https://www.youtube.com/watch?v=kGBhM3-W7ic
Hoping my image gets through Meshroom I have been trying to install "Instant Mesh" with Blender without success.  Any suggestions or is there a simpler program to get my image converted to a stl file for printing?

**Comment by natowi** [comment]
[InstantMeshes](https://instant-meshes.s3.eu-central-1.amazonaws.com/Release/instant-meshes-windows.zip) can be used to simplify the model. 
The Meshroom output is an .OBJ file. It can be cleaned up and exported to STL in MeshLab, Meshmixer or Blender. [slic3r](https://slic3r.org/about/) can also be used to import a cleaned up OBJ model and save it as STL.

As this is not a general 3D forum, I´d like to stay focussed on Meshroom issues.

**Comment by hlyman** [comment]
Thanks for your outstanding help.
