### ISSUE TITLE
Meshroom will not load

### ISSUE THREAD

**Issue by Rmason0810** [alicevision/meshroom#968]
I can't not get the software to launch. I have tried doing it as an admin but it still won't open. 

I keep getting a message that appears and it's gone in a couple of seconds. Part of it says, "This application failed to start because a Qt platform plugin could be initialized. Reinstalling the application may fix this problem." Well, it didn't, so now what?

**Comment by natowi** [comment]
You need to provide more details and a screenshot is helpful, too.
Read https://github.com/alicevision/meshroom/wiki/Troubleshooting for a few thing you can check
