### ISSUE TITLE
[question] Same photos, same parameters, but different runs deliver different results

### ISSUE THREAD

**Issue by xzhub** [alicevision/meshroom#972]
Please checkout these two results, the input photos and parameters are identical, but the results are different. Maybe the order of photos are different, since I changed the photo filenames to different uuids each time. Does the order of photos matter?
![image](https://user-images.githubusercontent.com/3990687/86065658-c58c5c80-baa2-11ea-8fe8-fd627b7545bd.png)

I am using Linux version of 2019.2

**Comment by natowi** [comment]
Yes the result can vary depending on what images are being used as initial pair.

**Comment by xzhub** [comment]
@natowi, Is this a random process? Not sure if there is a way to make this step more stable? Should I keep the filename unchanged?

**Comment by xzhub** [comment]
I found this:
https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters

> To improve the robustness of the initial image pair selection/initial reconstruction, you can use a SfM with minInputTrackLength set to 3 or 4 to keep only the most robust matches (and improve the ratio inliers/outliers). Then, you can chain another SfM with the standard parameters, so the second one will try again to localize the cameras not found by the first one but with different parameters. This is useful if you have only a few cameras reconstructed within a large dataset.

it says " This is useful if you have only a few cameras reconstructed within a large dataset.", I don't have large dataset, so not sure if this will help.

**Comment by natowi** [comment]
In StructureFromMotion you can define the initial pair images. 

You need to do some experimentation to find the settings that best fit your reconstruction project.

**Comment by fabiencastan** [comment]
Yes, the initial choice of the image pair can change and radically changes the results.
But in all case, you will have slight variations in unconstrained/unstable areas like the border of the reconstruction (on the shoulder in your example) or problematic surfaces like hair.

**Comment by xzhub** [comment]
I'd like to try changing  minInputTrackLength  of StructureFromMotion node, and "chain another SfM with the standard parameters". However, there are so many lines between these nodes, and it does not allow me to link StructureFromMotion_2's input with StructureFromMotion's output(the blue line). Could you please show me the correct graph? Thanks a lot!
![Snip20200701_8](https://user-images.githubusercontent.com/3990687/86151080-d4215500-bb30-11ea-8ff7-10602bec9f2f.png)

**Comment by natowi** [comment]
You need to remove the old connector first. But why do you want to chain the nodes?

**Comment by xzhub** [comment]
This is recommended in the wiki: https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters

> Then, you can chain another SfM with the standard parameters, so the second one will try again to localize the cameras not found by the first one but with different parameters.

**Comment by natowi** [comment]
Ok, duplicate the node as you did before, then right click on the sfm2 input connector end delete it. Also delete the connector between sfm and preparedensescene. Now create a new connection from sfm output to sfm2 input and from sfm2 output to preparedensescene input.

**Comment by xzhub** [comment]
I can't connect from sfm output to sfm2 input, it does not allow me. Any idea? (yes, I've deleted the existing sfm2 input)

**Comment by xzhub** [comment]
@natowi do you think the idea of chaining 3 sfm nodes will work? If I set minInputTrackLength too high, will it throw out an exception then exit the whole process? Or it will silently generate 0 initial pair, then let the next sfm to try again?

**Comment by natowi** [comment]
![scr](https://user-images.githubusercontent.com/8138537/86220129-6b16fd00-bb83-11ea-9b6a-67a7861e704c.JPG)

**Comment by xzhub** [comment]
Just noticed, if I drag SFM2's input to SFM's output, it does not allow me. If I drag SFM's output to SFM2's input, it works! Thank you @natowi for showing me this figure!

**Comment by xzhub** [comment]
I'd like to update it here that in my testing examples, chain 2 or more SFM nodes do not provide better results. Instead, use only one SFM node, set minInputTrackLength higher to 3 or 4 usually provide better result.
