### ISSUE TITLE
[question]Error when running ImageMatching node

### ISSUE THREAD

**Issue by cindy0628** [alicevision/meshroom#974]
Hi,
I met a problem when executing ImageMatching node,
Here is the screenshot when error happened.
![Screenshot from 2020-07-01 15-26-39](https://user-images.githubusercontent.com/26700548/86237149-d38acc00-bbcd-11ea-845e-920b3be04ffe.png)

**Dataset**
Downloaded from: https://github.com/alicevision/dataset_monstree.git

**Desktop:**
 - OS: ubuntu16.04
 - Python version :2.7.12
 - Meshroom version: 2019.2.0
 - Alicevision version:2.2.0

**Additional context**
To set up the environment:
1. Downloaded binaries file of Meshroom and Alicevision
(from:https://github.com/alicevision/AliceVision/releases & https://github.com/alicevision/meshroom/releases)
2. Path setting in bashrc:
`export PYTHONPATH=/home/tsehou/meshroom`
`export PATH=$PATH:/home/lidar/tsehou/AliceVision-2.2.0/bin`
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lidar/tsehou/AliceVision-2.2.0/lib:/usr/lib/nvidia-430`

Here is screenshot of the error message:
![Screenshot from 2020-07-01 15-26-26](https://user-images.githubusercontent.com/26700548/86239665-557cf400-bbd2-11ea-9527-9782a0e90415.png)

**Log**
> Log:
> ERROR: unrecognised option '--nbNeighbors'
> Usage:
> 
> The objective of this software is to find images that are looking to the same areas of the scene. For that, we use the image retrieval techniques to find images that share content without the cost of resolving all feature matches in detail. The ambition is to simplify the image in a compact image descriptor which allows to compute the distance between all images descriptors efficiently.
> This program generates a pair list file to be passed to the aliceVision_featureMatching software. This file contains for each image the list of most similar images.
> AliceVision featureMatching:
> 
> Required parameters:
> -i [ --input ] arg SfMData file.
> -f [ --featuresFolders ] arg Path to folder(s) containing the extracted
> features.
> -t [ --tree ] arg Input file path of the vocabulary tree.
> This file can be generated by
> createVoctree. This software is intended
> to be used with a generic, pre-trained
> vocabulary tree.
> -o [ --output ] arg Filepath to the output file with the list
> of selected image pairs.
> 
> Optional parameters:
> --minNbImages arg (=200) Minimal number of images to use the
> vocabulary tree. If we have less images
> than this threshold, we will compute all
> matching combinations.
> --maxDescriptors arg (=500) Limit the number of descriptors you load
> per image. Zero means no limit.
> --nbMatches arg (=50) The number of matches to retrieve for each
> image (If 0 it will retrieve all the
> matches).
> -w [ --weights ] arg Input name for the vocabulary tree weight
> file, if not provided all voctree leaves
> will have the same weight.
> 
> Multiple SfM:
> --inputB arg SfMData file.
> --matchingMode arg (=a/a) The mode to combine image matching between
> the input SfMData A and B:
> * a/a+a/b : A with A + A with B
> * a/ab : A with A and B
> * a/b : A with B
> * a/a : A with A
> --outputCombinedSfM arg Output file path for the combined SfMData
> file (if empty, don't combine).
> 
> Log parameters:
> -v [ --verboseLevel ] arg (=info) verbosity level (fatal, error, warning,
> info, debug, trace).

This error message is a bit like the error description in #813, but already using the last release package.
Please kindly advise how to solve the problem. Many thanks.

**Comment by gryan315** [comment]
The only time I have encountered the unrecognized option error is when using a mismatched alicevision build with the meshroom dev build. Possibly some kind of problem with your path declarations (is it possible your user account does not have permission to access the lidar home directory)? You could try export ALICEVISION_INSTALL=/path/to/alicevision. Is there a specific reason you downloaded the two separate current releases instead of the binary build archive from fosshub? That archive should contain everything you need and run right out of the box. I have not tried any other method of running the current release build.

**Comment by ChemicalXandco** [comment]
As @gryan315 pointed out, you are using the binary release of alicevision with a more recent meshroom from the develop branch. Either compile alicevision or use the binary release of meshroom. The versions need to match because some parameters have been added/removed.
