### ISSUE TITLE
[bug] Cache folder does not open from GUI

### ISSUE THREAD

**Issue by aidanhasaknife** [alicevision/meshroom#976]
**Describe the bug**
clicking "open cache folder" under any node will not work, and if meshroom is currently working, it will crash.

**To Reproduce**
1. click on a node in the graph editor.
2. click on "..." in the top right of the node.
3. click "open cache folder."

**Expected behavior**
it would open the cache folder in explorer.

**Screenshots**
![image](https://user-images.githubusercontent.com/21160455/86390628-067ca080-bc5e-11ea-8b57-18899f2b4a13.png)

**Log**
```
C:\Users\aidan\Desktop\Meshroom-2019.2.0>Meshroom
Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, ExportAnimatedCamera, ExportColoredPointCloud, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, LDRToHDR, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
WARNING:root:ShellExecute 'file:///C:/Users/aidan/AppData/Local/Temp/MeshroomCache/Meshing/f3c6646af2ba6c7911d51ecad7182ed77cc5b466/' failed (error 2).
```

**Desktop (please complete the following and other pertinent information):**
 - OS: win10
 - python 3.6.6
 - Qt/PySide version ¯\_(ツ)_/¯
 - Meshroom version: please specify if you are using a release version or your own build
   - Binary version (if applicable) release 2019.2.0

**Comment by ChemicalXandco** [comment]
The cache folder is only created when computation starts, this is expected behaviour. Opening a folder with nothing in it is pointless. What exactly do you mean by 'crash', does the meshroom window disappear?

**Comment by Aidan-Lineberry** [comment]
crashing; the meshroom window turns not responding

**Comment by natowi** [comment]
Is this still an issue in the 2021 release?
