### ISSUE TITLE
[question] What parameters are recommended for buildings?

### ISSUE THREAD

**Issue by xzhub** [alicevision/meshroom#977]
I was playing meshroom with this dataset: https://www.sensefly.com/education/datasets/?dataset=1420

The result I got is not idea, the wall is very bumpy(red arrow) and some structures are melt down. 
![image](https://user-images.githubusercontent.com/3990687/86516570-4efdaf00-be54-11ea-9eb9-964de623077e.png)

Their result looks a little better on the wall:
![image](https://user-images.githubusercontent.com/3990687/86516607-a26ffd00-be54-11ea-88c9-d698e8928628.png)

Both have the "melt down" issue:
![image](https://user-images.githubusercontent.com/3990687/86516622-cfbcab00-be54-11ea-9358-c466c43014b3.png)

What to do to improve the quality of wall? I've tried "akaze" (https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters, no. 3), it is similar to the default parameters' result:
![image](https://user-images.githubusercontent.com/3990687/86516716-8f116180-be55-11ea-8192-6fafbe24b774.png)

**Comment by natowi** [comment]
The church and the immediate surrounding buildings have the best reconstruction quality, as it is in the centre of this capture.
With less image overlap at the edges, the quality decreases. 

![dat](https://user-images.githubusercontent.com/8138537/86519312-dee22f80-be39-11ea-9433-44921f557b07.JPG)

**Comment by xzhub** [comment]
@natowi this makes sense. The center is much better than edges. Is there any parameters we can tune for the wall? It looks bumpy at this moment.

**Comment by natowi** [comment]
Try again with settings for a denser point cloud (increease quality and add akaze to all nodes) and DepthMap (1). In DepthMapFilter you can modify the value to get a smoother surface.

**Comment by xzhub** [comment]
@natowi I can find the description on how to add akaze, and I think I can set downscale=1 to increase quality in DepthMap. But I am not sure which parameter I should change to smooth surface in DepthMapFilter? Could you please explain a bit more? Thanks !

**Comment by natowi** [comment]
You can experiment with the Smoothing value.

**Comment by xzhub** [comment]
I didn't see such parameter here: https://meshroom-manual.readthedocs.io/en/latest/node-reference/nodes/DepthMapFilter.html

what would be the range of this parameter?

**Comment by natowi** [comment]
Sorry, look in MeshDenoising

**Comment by fabiencastan** [comment]
How many images in input and how many cameras are localized at the end of the SfM?
(Try depthmap downscale=1 first without changing other params)

**Comment by natowi** [comment]
![1](https://user-images.githubusercontent.com/8138537/86528853-4afd7b80-beac-11ea-9b60-4fe0a69e2e90.JPG)

**Comment by xzhub** [comment]
downscale=1 and iterations=20 doesn't change much the result. Instead, resize to a lower resolution improves the result.

**Comment by xzhub** [comment]
I also noticed that, the bumpy walls only could be found in shade(red circle), where the image noise is higher. Here is a result from lower resolution image, you can see the wall is smoother. 
![image](https://user-images.githubusercontent.com/3990687/86831186-2e8a5a80-c0c9-11ea-876e-423022034f54.png)
![image](https://user-images.githubusercontent.com/3990687/86831421-74dfb980-c0c9-11ea-956c-cb25270d5c25.png)

**Comment by xzhub** [comment]
Using MeshDenoising improves the result a little bit.
https://meshroom-manual.readthedocs.io/en/v2019.2/node-reference/nodes/MeshDenoising.html

<img width="506" alt="Screen Shot 2020-07-22 at 3 50 40 AM" src="https://user-images.githubusercontent.com/3990687/88100546-3f5dc480-cbcf-11ea-8c62-c3da7c7cfce7.png">
<img width="438" alt="Screen Shot 2020-07-22 at 3 54 44 AM" src="https://user-images.githubusercontent.com/3990687/88100558-44bb0f00-cbcf-11ea-8811-460db0a2fd9c.png">
