### ISSUE TITLE
[bug] Mesh mode of "RegularGrid / Auto" error

### ISSUE THREAD

**Issue by tftangming** [alicevision/meshroom#979]
**Describe the bug**
Mesh mode of "RegularGrid / Auto" does not works in the meshing stage. My input images is about 277 images captured by UAV， and I can success to achieve the meshing by the default mode "Multi-resolution/Singleblock". But when I change the mode, I find the program is stucked after it produces two terrible sub-block meshs. So I beg for your help...

**Desktop:**
 - OS: Ubuntu16.04
 - Python version: Python 2.6
 - Qt/PySide version: Qt5.5.1
 - Meshroom version: Meshroom 2019.2

**Comment by natowi** [comment]
This are Advanced settings. Why do you want to change this settings?

**Comment by tftangming** [comment]
I want to achieve the mesh generation in the large-scale datasets and in finite memory. When I read the source code, I find it seems to exist the partitions mode , so I want to try it.

**Comment by natowi** [comment]
You can reduce the Max Points to fit your RAM limits

**Comment by tftangming** [comment]
Thanks your reply. I try to reduce the Max Points but it dose not work. And I find I have enough memory. In addition, can you give me some advice about dealing with the large-scale conditions?

**Comment by natowi** [comment]
"dealing with the large-scale conditions"

What exactly is the problem there? Not enough views detected? Mesh accuracy?...

**Comment by tftangming** [comment]
When I capture the city  by a UAV, I can obtain many images in order to reconstruct the city, but there are to many images so that wasting many time and memory during the meshing and texturing stages.

**Comment by natowi** [comment]
I am not aware of a setting to improve Meshing in your case. In Texturing you could limit the Max number of images to combine to create the final texture (Max Nb of Images For Fusion)
