### ISSUE TITLE
Incorrect camera positioning [question]

### ISSUE THREAD

**Issue by walls22** [alicevision/meshroom#987]
I'm trying to do some photoscans of products for the company I work at, but unfortunately a lot of these products have identical sides, so Meshroom is having trouble reconstructing the dataset properly. I tried putting some marked pieces of paper around the object to try and differentiate the individual sides from one another, but this didn't seem to work. How can I get the dataset to reconstruct properly if different sides of my object look the same?

![image](https://user-images.githubusercontent.com/36966560/87792984-a1ef4300-c812-11ea-9752-a7d7d49246ed.png)

![image](https://user-images.githubusercontent.com/36966560/87793097-c77c4c80-c812-11ea-9636-6527a204f12f.png)

**Desktop (please complete the following and other pertinent information):**
 - OS: win 10
 - Python version: not installed
 - Qt/PySide version: not installed
 - Meshroom version: 2019.2.0

**Comment by natowi** [comment]
If you have boxes, simply create some 3d cubes in a software and add the sides as texture. Faster and better results.

**Comment by hargrovecompany** [comment]
Are you rotating the box?  I cant tell from the pics....if so, don't do that.  The lighting will change and the software will get confused.
