### ISSUE TITLE
on meshing node: ERROR: unrecognised option '--depthMapsFilterFolder'

### ISSUE THREAD

**Issue by ludogemma** [alicevision/meshroom#995]
after the start all goes correctly but arrived at node meshing become red and in terminal says:
ERROR: unrecognised option '--depthMapsFilterFolder'

 - OSX High Sierra with Nvidia 1080Ti 11GB
 - Python version 3.7
 - Meshroom version: 2019.2.0

**Comment by natowi** [comment]
Use the source code from the 2019.2 release https://github.com/alicevision/meshroom/archive/v2019.2.0.zip

**Comment by ludogemma** [comment]
thanks @natowi but i guess i've already compiled correct versions..
i used git clone https://github.com/alicevision/AliceVision.git --recursive
for AliceVision
and installed the meshroom-2019.2.0

in fact when i start use in meshroom-2019.2.0:
ALICEVISION_VOCTREE=/usr/local
/Cellar/alicevision/2.2.0/share/aliceVision/vlfeat_K80L3.SIFT.tree PYTHONPATH=$PWD python
 meshroom/ui

**Comment by natowi** [comment]
installed the meshroom-2019.2.0

using git clone https://github.com/alicevision/meshroom.git ?

**Comment by ludogemma** [comment]
i used this: 
git clone https://github.com/alicevision/AliceVision.git --recursive

**Comment by fabiencastan** [comment]
You are not up-to-date on the meshroom side, there is no more `depthMapsFilterFolder` parameter:
https://github.com/alicevision/meshroom/blob/develop/meshroom/nodes/aliceVision/Meshing.py

**Comment by ludogemma** [comment]
ok but so what's the solution if you tell me to recompile everything with the source you told me ok .. i can .. if i need only to install different meshroom then tell me 
i'm a bit lost about what to do :)

**Comment by natowi** [comment]
"and for meshroom i used https://github.com/alicevision/meshroom/archive/v2019.2.0.zip"

That´s why I was asking.

When you use https://github.com/alicevision/AliceVision.git , you also have to use https://github.com/alicevision/meshroom.git

Otherwise the versions mismatch.

**Comment by ludogemma** [comment]
ok so the solution is to use using git clone https://github.com/alicevision/meshroom.git 
ok i will try that now

**Comment by ludogemma** [comment]
the problem gone with meshing .. now continue till texturing and then become red again 
in terminal i see this error:

[20:32:43.515112][info] Convert dense point cloud into ref mesh
[20:32:43.967619][info] remapMeshVisibility based on triangles start.
[20:33:03.548399][info] remapMeshVisibility done.
[20:33:03.565109][info] Input mesh has no UV coordinates, start unwrapping (LSCM)
[20:33:03.727637][info] Start mesh atlasing (using Geogram LSCM).
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
[20:39:55.216428][info] Mesh atlasing done.
Abnormal program termination: received signal 11 (Segmentation fault: 11)

**Comment by natowi** [comment]
Ah, ok you moved it here https://github.com/alicevision/meshroom/issues/996
