### ISSUE TITLE
[question] Texturing Segmentation fault

### ISSUE THREAD

**Issue by ludogemma** [alicevision/meshroom#996]
in the process of meshroom at texturing node i receive this error:

`Nodes to execute:  ['Texturing_1']
WARNING: downgrade status on node "Texturing_1" from Status.ERROR to Status.SUBMITTED

[1/1] Texturing
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/Users/sbarrile/opt/miniconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/sbarrile/meshroom/meshroom/core/stats.py", line 299, in run
    self.updateStats()
  File "/Users/sbarrile/meshroom/meshroom/core/stats.py", line 293, in updateStats
    if self.chunk.statistics.update(self.proc):
  File "/Users/sbarrile/meshroom/meshroom/core/stats.py", line 247, in update
    self.process.update(proc)
  File "/Users/sbarrile/meshroom/meshroom/core/stats.py", line 201, in update
    data = proc.as_dict(self.dynamicKeys)
  File "/Users/sbarrile/opt/miniconda3/lib/python3.7/site-packages/psutil/__init__.py", line 531, in as_dict
    ", ".join(map(repr, invalid_names))))
ValueError: invalid attr name 'io_counters'

 - commandLine: aliceVision_texturing  --input "/Volumes/Workbench/giro/MeshroomCache/Meshing/2f36e7632c2f8a79e9e4b8585ba462c9205eac10/densePointCloud.abc" --imagesFolder "/Volumes/Workbench/giro/MeshroomCache/PrepareDenseScene/241ed696b83350aa5c3c4aa92153825be4763778" --inputMesh "/Volumes/Workbench/giro/MeshroomCache/MeshFiltering/a8ef2c8791a286478ecc8009394403e8357001aa/mesh.obj" --textureSide 8192 --downscale 1 --outputTextureFileType png --unwrapMethod LSCM --useUDIM True --fillHoles False --padding 5 --multiBandDownscale 4 --multiBandNbContrib 1 5 10 0 --useScore True --bestScoreThreshold 0.1 --angleHardThreshold 90.0 --processColorspace sRGB --correctEV False --forceVisibleByAllVertices False --flipNormals False --visibilityRemappingMethod PullPush --subdivisionTargetRatio 0.8 --verboseLevel info --output "/Volumes/Workbench/giro/MeshroomCache/Texturing/b2c8e8bc7b8df7a234d0e80a29580c22bf0c4712"
 - logFile: /Volumes/Workbench/giro/MeshroomCache/Texturing/b2c8e8bc7b8df7a234d0e80a29580c22bf0c4712/log
 - elapsed time: 0:07:38.741788
[2020-07-23 20:40:10,943][ERROR] Error on node computation: Error on node "Texturing_1":
Log:
Program called with the following parameters:
 * angleHardThreshold = 90
 * bestScoreThreshold = 0.1
 * correctEV = 0
 * downscale =  Unknown Type "j"
 * fillHoles = 0
 * flipNormals = 0
 * forceVisibleByAllVertices = 0
 * imagesFolder = "/Volumes/Workbench/giro/MeshroomCache/PrepareDenseScene/241ed696b83350aa5c3c4aa92153825be4763778"
 * input = "/Volumes/Workbench/giro/MeshroomCache/Meshing/2f36e7632c2f8a79e9e4b8585ba462c9205eac10/densePointCloud.abc"
 * inputMesh = "/Volumes/Workbench/giro/MeshroomCache/MeshFiltering/a8ef2c8791a286478ecc8009394403e8357001aa/mesh.obj"
 * multiBandDownscale =  Unknown Type "j"
 * multiBandNbContrib =  Unknown Type "NSt3__16vectorIiNS_9allocatorIiEEEE"
 * output = "/Volumes/Workbench/giro/MeshroomCache/Texturing/b2c8e8bc7b8df7a234d0e80a29580c22bf0c4712"
 * outputTextureFileType = "png"
 * padding =  Unknown Type "j"
 * processColorspace = "sRGB"
 * subdivisionTargetRatio = 0.8
 * textureSide =  Unknown Type "j"
 * unwrapMethod = "LSCM"
 * useScore = 1
 * useUDIM = 1
 * verboseLevel = "info"
 * visibilityRemappingMethod = "PullPush"

[20:32:32.999368][info] Load dense point cloud.
[20:32:37.756843][warning] Alembic LOAD: NO OBSERVATIONS_WITH_FEATURES: , mvg_visibilityFeatId: 0, mvg_visibilityFeatPos: 0, OBSERVATIONS_WITH_FEATURES flag: false
[20:32:38.758778][info] Found 1 image dimension(s): 
[20:32:38.759122][info] 	- [6000x4000]
[20:32:40.898398][info] Overall maximum dimension: [6000x4000]
[20:32:40.899149][info] Load input mesh.
[20:32:40.899522][info] Loading mesh from obj file: /Volumes/Workbench/giro/MeshroomCache/MeshFiltering/a8ef2c8791a286478ecc8009394403e8357001aa/mesh.obj
[20:32:42.707886][info] 	- # vertices: 307863
	- # normals: 0
	- # uv coordinates: 0
	- # triangles: 615467
[20:32:43.509514][info] Mesh loaded: 
	- #points: 307863
	- # triangles: 615467
[20:32:43.515112][info] Convert dense point cloud into ref mesh
[20:32:43.967619][info] remapMeshVisibility based on triangles start.
[20:33:03.548399][info] remapMeshVisibility done.
[20:33:03.565109][info] Input mesh has no UV coordinates, start unwrapping (LSCM)
[20:33:03.727637][info] Start mesh atlasing (using Geogram LSCM).
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
[20:39:55.216428][info] Mesh atlasing done.
Abnormal program termination: received signal 11 (Segmentation fault: 11)`

OSX High Sierra with Nvidia 1080Ti 11GB
Python version 3.7
Meshroom version: 2019.2.0-develop

**Comment by natowi** [comment]
Seems to be similar to https://github.com/alicevision/meshroom/issues/898

**Comment by ludogemma** [comment]
> Seems to be similar to #898
> Try using another unwrap method to see if it works.


ok i can confirm that BASIC method for texturing node works without problem, other method no!
LSCM & ABF methods gives errors..
and this is very annoying cause the basic ..makes more textures and worse uv .. than other methods..

**Comment by natowi** [comment]
But it seems to be dev-build related. The binary build (2019.2, for windows) does not have this problem

**Comment by ludogemma** [comment]
> But it seems to be dev-build related. The binary build (2019.2, for windows) does not have this problem

ok so the problem occurs on source for linux and macos..

**Comment by misaalanshori** [comment]
Hey guys I'm on Windows 10 with Meshroom 2019.2.0 and I got a similar same problem, the changes I made to the graph editor is that in the Texturing node I enabled Fill Holes and Unwrap Method to LSCM, and at first it worked normally but then I duplicated the Texturing node so I can skip the mesh filtering (The first result was missing some parts that looked pretty clear on the Structure from motion) so i can toubleshoot but I got this error:

`OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix`

Okay so while I was writing this, the errors stopped (it wrote the error 1330 times to the log) and it seems to be continuing normally again:

```
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
[19:37:56.528403][info] Mesh atlasing done.
[19:38:30.086513][info] Loading mesh from obj file: C:\Users\user\AppData\Local\Temp\5572-c1da-754c-24a4.obj
[19:38:32.736471][info] 	- # vertices: 1173341
	- # normals: 0
	- # uv coordinates: 1470787
	- # triangles: 2346245
[19:38:40.247595][info] Mesh loaded: 
	- #points: 1173341
	- # triangles: 2346245
```

Okay so it finished normally, I opened the textured file and it looks normal.
(the parts that were missing before was still missing so I still need to find where it dissapeared)

Still very weird that it outputs that error so many times before it stops and just continues like normal

**Comment by herksaw** [comment]
Encountered the same issue on latest source. Fixed by downgrading geogram from 1.7.6 to 1.6.10.
[https://gforge.inria.fr/frs/?group_id=5833](https://gforge.inria.fr/frs/?group_id=5833)

Guessed they changed something on `GEO::mesh_make_atlas`, there was an extra parameter needed compared to previous version. Made few attempts to pass different values to it but end up still received the same result. No choice but to downgrade the library itself.
http://alice.loria.fr/software/geogram/doc/html/mesh__atlas__maker_8h_source.html

**Comment by guizy67** [comment]
@herksaw I am curious how you downgraded geogram.
I have tested with 1.6.6, 1.6.10, 1.6.13 by building from source off the develop branch and I'm still getting the same error.

I also downloaded the just released 2020.1.0 package and it also segfaults during texturing with LSCM.

**Comment by herksaw** [comment]
@guizy67 Hmmm strange, as what I have done is just dpkg the deb package, and install it on my ubuntu machine, before remake the binary. The source is based on develop branch too.

What I could think is maybe the mesh had hit the vertices/tris limit for lscm/abf method?

**Comment by natowi** [comment]
The recommended face count for different unwrap methods is as follows:
- Basic (> 600k faces) fast and simple. Can generate multiple atlases 
- LSCM (<= 600k faces): optimize space. Generates one atlas 
- ABF (<= 300k faces): optimize space and stretch. Generates one atlas

Some people report a working v.2019.2 project now fails in v.2020 with ABF/LSCM

Similar reports
https://github.com/alicevision/meshroom/issues/1107
https://github.com/alicevision/meshroom/issues/920
https://groups.google.com/g/alicevision/c/2cNXkaRSacY

So there is probably a bug somewhere.

**Comment by ChrisDean** [comment]
Another +1 on this issue on Ubuntu

**Comment by Ebbombe** [comment]
ElementaryOS here, same problem, only basic method works.

**Comment by MasterPharaon90** [comment]
I had a memory problem, even though it is enough. Solved the problem by adding virtual memory of the size of the system's choice. It took the same amount of RAM on the disk as the RAM itself (doubling the system memory) - the problem disappeared. Additional system parameters ->
System properties -> Performance -> Advanced -> Virtual memory -> Select the desired drive -> System selectable size -> Set -> OK -> restart the computer.

**Comment by MasterPharaon90** [comment]
I had a memory problem, even though it is enough. Solved the problem by adding virtual memory of the size of the system's choice. It took the same amount of RAM on the disk as the RAM itself (doubling the system memory) - the problem disappeared. Additional system parameters ->
System properties -> Performance -> Advanced -> Virtual memory -> Select the desired drive -> System selectable size -> Set -> OK -> restart the computer.
