### ISSUE TITLE
[research] ORB-SLAM3: An Accurate Open-Source Library for Visual, Visual-Inertial and Multi-Map SLAM

### ISSUE THREAD

**Issue by skinkie** [alicevision/meshroom#999]
https://github.com/UZ-SLAMLab/ORB_SLAM3

https://arxiv.org/abs/2007.11898

https://www.youtube.com/watch?v=E-7fsq7en2g

**Comment by natowi** [comment]
Yes, SLAM would be a good addition, it is already on the wish list https://github.com/alicevision/meshroom/wiki/Good-first-contributions#real-time-reconstruction-using-slam-
